- .github/workflows/build-desktop.yml
- apps/ledger-live-desktop/electron-builder-ci.yml
- apps/ledger-live-desktop/electron-builder-nightly.yml
- apps/ledger-live-desktop/electron-builder.yml
- apps/ledger-live-desktop/main.webpack.config.js
- apps/ledger-live-desktop/package.json
- apps/ledger-live-desktop/preloader.webpack.config.js
- apps/ledger-live-desktop/renderer.webpack.config.js
- apps/ledger-live-desktop/tools/dist/index.js
- apps/ledger-live-desktop/tools/main.js
- apps/ledger-live-desktop/tools/utils/WebpackWorker.js
- apps/ledger-live-desktop/webviewPreloader.webpack.config.js
- package.json
- pnpm-lock.yaml
- tools/native-modules-tools/index.js
- tools/native-modules-tools/package.json
> chore: tremendous bundling optimizations

- .github/labeler.yml
- .github/workflows/labeler.yml
- readme.md
[LIVE-1673]
[LIVE-1673]: https://ledgerhq.atlassian.net/browse/LIVE-1673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-1673 Labelling System

- .github/workflows/generate-screenshots.yml
> Test generate screenshots

- libs/ledger-live-common/tools/config-overrides.js
- libs/ledger-live-common/tools/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
**Self explanatory**
Had to fix a couple of things caused by package bumps, but it should work properly now.
> chore: make llc tools work

- apps/ledger-live-desktop/.eslintrc.js
- apps/ledger-live-desktop/RELEASE_NOTES.md
- apps/ledger-live-desktop/release-notes.json
- apps/ledger-live-desktop/src/renderer/modals/ReleaseNotes/ReleaseNotesBody.js
- apps/ledger-live-desktop/src/tsconfig.json
- apps/ledger-live-desktop/tools/main.js
- apps/ledger-live-desktop/tools/utils/WebpackWorker.js
- apps/ledger-live-desktop/tools/utils/processReleaseNotes.js
- apps/ledger-live-desktop/tsconfig.json
- pnpm-lock.yaml
Since we are moving away from github to store our release, I've switched to a local solution to parse and create the json file needed to display the correct release notes
> release note new integration

- .github/workflows/generate-screenshots.yml
- **Impacted projects**: [`ledger-live-desktop`]
Attempt to investigate ans fix playwright snapshot disparities between the monorepo and the old LLD repo.
N/A
_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/monorepo-setup/CONTRIBUTING.md#important-steps)._
> Investigate playwright disparities

- .github/workflow-templates/bot-coin-family.properties.json
- .github/workflow-templates/bot-coin-family.yml
- .github/workflows/bot-phosphore.yml
- .github/workflows/bot-staging-explorer-btc.yml
- .github/workflows/bot-staging-explorer-eth.yml
- .github/workflows/bot-transfer.yml
we are adding back the bot yml files to make the bot working.
> Add more bots and a bot template

- .github/labeler.yml
- apps/ledger-live-desktop/tests/specs/market.spec.ts
- apps/ledger-live-desktop/tests/specs/subAccounts.spec.ts
- apps/ledger-live-desktop/tests/specs/swap.spec.ts
- libs/ledger-live-common/src/families/ethereum/bridge.test.ts.bak
- **Impacted projects**: [`live-desktop`, `live-common`]
This PRs add a new label screenshots when there are changes in the desktop test folder.
This PR also disables the flaky desktop playwright tests and live-common jest tests.
No Demo
> Disable flaky tests

- .changeset/late-zebras-hug.md
- apps/ledger-live-desktop/src/config/languages.js
- apps/ledger-live-desktop/src/helpers/systemLocale.js
- apps/ledger-live-desktop/src/main/window-lifecycle.js
- apps/ledger-live-desktop/src/preloader/index.js
- apps/ledger-live-desktop/src/renderer/analytics/segment.js
- apps/ledger-live-desktop/src/renderer/components/IsSystemLanguageAvailable.js
- apps/ledger-live-desktop/src/renderer/reducers/application.js
- apps/ledger-live-desktop/src/renderer/reducers/settings.js
- **Impacted projects**: `live-desktop`
- **Linked resource(s)**: [LIVE-1928], [LIVE-1776], https://github.com/LedgerHQ/ledger-live-desktop/pull/4933
Original author: @ofreyssinet-ledger 
With this change, we add more languages (Chinese and Spanish) to the list that makes it easy for existing users and new users to switch to their OS language:
- New users get that language by default when first launching LLD.
- Existing users that use the app in another language (english typically) get prompted with a modal telling them that their OS language is available.
https://user-images.githubusercontent.com/91890529/164006563-0eef5118-83bf-470c-87e0-42aec001b951.mov
https://user-images.githubusercontent.com/91890529/164007283-2bd6bb7e-9bfa-4392-b83a-03a0fddcd92f.mov
_Please make sure you follow …
> Add Spanish (ES) and Chinese (ZH) to discoverable languages

- .changeset/green-suits-move.md
- libs/ledger-live-common/package.json
- pnpm-lock.yaml
- **Impacted projects**: `@ledgerhq/live-common`
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-2309
> LIVE-2309 Update stellar-sdk to v10.1.0

- .github/pull_request_template.md
If you check all the points of a checklist, it means you are "good". By making "Breaking changes" and not "No breaking changes" a checklist point, it confuses a bit that fact, and it's actually not good to check it. When you don't check a check list, it's where you need to explain why. I shouldn't explain why i'm not breaking =)
> tweak PR template to make checklist good to check

- .changeset/quick-hairs-obey.md
- libs/ledger-live-common/src/families/cosmos/__snapshots__/bridge.test.ts.snap
Snapshot need to be updated
- **Impacted projects**: [e.g. `live-desktop`, `@ledgerhq/live-common`]
@ledgerhq/live-common
> Update snapshot of cosmos

- .changeset/shy-bears-reflect.md
- apps/ledger-live-mobile/src/screens/Market/SearchHeader.tsx
- **Impacted projects**: ledger-live-mobile, ledger-live-common
- **Linked resource(s)**: [LIVE-2343]
When there was no result, the click on the browse assets button did nothing.
https://user-images.githubusercontent.com/29443638/169062134-b7e14279-973e-45e2-8bf8-e55ceed49285.mp4
[LIVE-2343]: https://ledgerhq.atlassian.net/browse/LIVE-2343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: click on browse assets button

- .changeset/swift-parrots-enjoy.md
- apps/ledger-live-mobile/src/screens/Portfolio/Header.tsx
- **Impacted projects**: ledger-live-mobile
- **Linked resource(s)**:[LIVE-2038]
During loading there was a glitch on the Ledger logo. The logo did not appeared immediately.
https://user-images.githubusercontent.com/29443638/169265577-cc06fef6-e988-4ed7-acfe-ce22adb61ed8.mp4
[LIVE-2038]: https://ledgerhq.atlassian.net/browse/LIVE-2038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: ledger logo glitch during loading

- apps/ledger-live-desktop/src/renderer/Default.js
- pnpm-lock.yaml
- **Impacted projects**: [`live-desktop`]
Disable the nightly overlay on LLD whenever we are in `next` (prerelease) mode.
No Screenshots
> remove nightly layer on prerelease

- libs/ledger-live-common/src/families/cosmos/specs.ts
Bot couldn't find the right elf for the specs tests in ATOM
- **Impacted projects**: [e.g. `live-desktop`, `@ledgerhq/live-common`]
@ledgerhq/live-common
> Remove firmware on ATOM spec

- package.json
- pnpm-lock.yaml
- **Impacted projects**: N/A
Upgrade turborepo to [`v1.2.9`](https://github.com/vercel/turborepo/releases/tag/v1.2.9).
N/A
> Upgrade turborepo to v1.2.9

- libs/ledger-live-common/src/families/bitcoin/bridge/js.ts
- **Impacted projects**: none
- **Linked resource(s)**: none
This PR only adds a comment.
> Add comment for Bitcoin segwit specific code

- .github/workflows/prerelease.yml
- pnpm-lock.yaml
- tools/github-bot/src/tools.ts
- **Impacted projects**: [`all repo`]
Allows the monorepo to have (on exceptional occasions) several release branches at the same time.
NO DEMO
> allow multiple release branches

- libs/ledger-live-common/src/apps/polyfill.ts
- **Impacted projects**: both LLD and LLM
This is a hardcoded list of dependencies between plugins and eth app that needs to be updated every time we release a plugin.
N/A
N/A
> feat: add kiln and alkemi to eth app deps

- libs/ledgerjs/package.json
- pnpm-lock.yaml
- **Impacted projects**: ledgerjs importer script
This fixes the dependencies needed for crypto-assets importer of ledgerjs to still work as expected.
> Fixes crypto-assets importer

- apps/ledger-live-mobile/README.md
Adds doc to LLM readme with knows workaround for M1 users
> update readme with m1 workarounds for llm

- .github/workflows/build-desktop.yml
- .github/workflows/build-mobile.yml
- tools/actions/composites/build-desktop/action.yml
closes #178
Issue #178 
- **Impacted projects**: automation
- **Linked resource(s)**: [LIVE-2464]
Allow the execution of CI on external contrib
NO DEMO
CI stills runs correctly for @ledgerhq users and run on different runners for external contributors
[LIVE-2464]: https://ledgerhq.atlassian.net/browse/LIVE-2464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-2464 Run CI on external contributions

- .github/workflows/build-desktop.yml
- tools/actions/composites/build-desktop/action.yml
Outputs where not passed from composite action to parent job that could not upload artifacts anymore. This fixes that
- **Impacted projects**: `automation`
NO DEMO
> add outputs on composite actions

- .changeset/weak-beans-fix.md
- libs/ui/packages/shared/palettes/dark.ts
- libs/ui/packages/shared/palettes/light.ts
- **Impacted projects**: `libs/ui`
In context of design updates we require new colors to be added to shared ui theme
> ui/shared - add new theme colors

- .changeset/calm-pets-sleep.md
- libs/ledger-live-common/cli/src/commands/getAddress.ts
- **Impacted projects**: ledger-live/cli
Fix verify flag for getAddress CLI cmd
> Fix bug on getAddress CLI cmd

- apps/ledger-live-mobile/src/families/cosmos/shared/02-SelectAmount.js
- **Impacted projects**:
LLM
https://ledgerhq.atlassian.net/browse/LIVE-2480
Uploading Simulator Screen Recording - iPhone X - 2022-05-25 at 18.41.13.mp4…
> LIVE-2480 Fix cosmos select amount screen

- .changeset/young-beers-obey.md
- apps/ledger-live-mobile/src/families/cosmos/DelegationFlow/02-Summary.tsx
- **Impacted projects**:
LLM
https://ledgerhq.atlassian.net/browse/LIVE-2486
Couldn't chose another validator than Ledger
> LIVE-2486 Fix choice of cosmos validator

- .changeset/wet-news-agree.md
- libs/ledger-live-common/src/exchange/swap/getExchangeRates.test.ts
- libs/ledger-live-common/src/exchange/swap/getExchangeRates.ts
- **Impacted projects**: [`@ledgerhq/live-common`]
https://ledgerhq.atlassian.net/browse/LIVE-2031
Take fees into account for swap rate
Amount to receive should match the rate.
> [BUGFIX][LIVE-2031] take fees into account for swap rate

- .github/workflows/test.yml
- **Impacted projects**: `automation`
- **Linked resource(s)**: [LIVE-2399]
Make sure we run the test on push events on develop and main using the previous commit to create a diff of affected packages.
NO DEMO
Runs the affected tests on push on develop and main
[LIVE-2399]: https://ledgerhq.atlassian.net/browse/LIVE-2399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix running tests on push events

- .github/pull_request_template.md
This PR tries to make the PR template more understood. unfortunately I still see many misusage of our template / some text are left in the PR template where they should remove, etc... I try here to make it more concise to be sure it's read & filled 🤞 
> If we want to continue even more, there is a possibility to make a 4rd check point to group the "Expectations to reach" and say "I have reached the expectation". but let's do it step by step , unless that Expectations section was really meant to be edited?
- **Impacted projects**: the PR template itself
- **Linked resource(s)**: none
DX team approval needed.
> PR template refinements

- .changeset/soft-snails-applaud.md
- .gitignore
- libs/ledger-live-common/src/derivation.ts
Fix collision between bip44 and glif nomral derivation modes
- **Impacted projects**: `ledger-live/common` 
> Fix collision between bip44 and glif nomral derivation modes

- .changeset/flat-kings-cover.md
- apps/ledger-live-mobile/index.js
- libs/ledger-live-common/package.json
- libs/ledger-live-common/src/families/polkadot/bridge/js.ts
- libs/ledger-live-common/src/families/polkadot/js-buildTransaction.ts
- libs/ledger-live-common/src/families/polkadot/js-estimateMaxSpendable.ts
- libs/ledger-live-common/src/families/polkadot/js-getTransactionStatus.ts
- libs/ledger-live-common/src/families/polkadot/js-prepareTransaction.ts
- libs/ledger-live-common/src/families/polkadot/js-synchronisation.ts
- libs/ledger-live-common/src/families/polkadot/polkadot-crypto.ts
- libs/ledger-live-common/src/families/polkadot/preload.ts
- libs/ledger-live-common/src/reactNative.ts
- pnpm-lock.yaml
Cherry-pick of #227 into `releases/llm-3.2.x`
- **Impacted projects**: ` ` 
- **Linked resource(s)**: ` `
> LIVE-2479 Cherry-pick of #227 into releases/llm-3.2.x

- libs/ledger-live-common/src/env.ts
ENV fix for Cardano API endpoint
> fix cardano api endpoint

- .changeset/empty-taxis-grin.md
- apps/ledger-live-mobile/src/screens/Market/SearchHeader.tsx
- apps/ledger-live-mobile/src/screens/Market/index.tsx
- libs/ledger-live-common/src/market/api/api.ts
- libs/ledger-live-common/src/market/types.ts
- **Impacted projects**:  @ledgerhq/live-common, live-mobile
- **Linked resource(s)**: [LIVE-2392]
We needed to make that refactor to be able to make a search on the top 100 and to move the filter logic out of the Market component.
https://user-images.githubusercontent.com/29443638/169496588-bf5fbf67-266c-402e-bf5c-ac6b198cdf60.mp4
[LIVE-2392]: https://ledgerhq.atlassian.net/browse/LIVE-2392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor top perfs filter

- README.md
Typo in About section...
`Leger -> Ledger`
> fixes typo in About section

- libs/ledger-live-common/src/families/cardano/speculos-deviceActions.ts
> add speculos step for auxiliary data

- libs/ledger-live-common/src/families/cardano/specs.ts
> fix speculos test

- apps/ledger-live-desktop/src/renderer/families/cardano/MemoValueField.js
- apps/ledger-live-desktop/src/renderer/families/cardano/SendAmountFields.js
- apps/ledger-live-desktop/static/i18n/en/app.json
Memo field support for Cardano
- **Impacted projects**: `ledger-live-desktop`
> memo field added

- libs/ledger-live-common/src/families/cardano/buildSubAccounts.ts
- libs/ledger-live-common/src/families/cardano/js-synchronisation.ts
- libs/ledger-live-common/src/families/cardano/logic.ts
Fix for cardano byron address 
> byron address fix

- .changeset/fifty-clouds-bake.md
- libs/ledger-live-common/package.json
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/xpub.ts
- pnpm-lock.yaml
the bitcoin bridge.getTransactionStatus was never ending in some cases due to `off()` not being available on the EventEmitter on the current stack. it was crashing (in uncaught background) without letting the promise to `resolve()`. It is unclear when the regression happened but `off` do not seem to exist on our current events polyfill / implementation. Only "removeListener" is. 
I suspect it's due to usage of https://github.com/parshap/node-libs-react-native (cc @jelbaz-ledger maybe you know better how it works and can help confirming or not?). According to the `pnpm mobile list events` command, we are supposed to be on 3.3.0 which have the `off(` function. On the other end, `pnpm common list events` do not tell me anything, so I wonder if it's somehow replaced by something else. super …
> [LIVE-2482] Bugfix: Fixes usage of events in wallet-btc

- .github/workflows/build-desktop.yml
- .github/workflows/build-mobile.yml
- .github/workflows/generate-screenshots.yml
- .github/workflows/test-desktop.yml
- .github/workflows/test-mobile.yml
- .github/workflows/test.yml
- pnpm-lock.yaml
- tools/actions/composites/build-desktop/action.yml
Trying out possible alternatives to Turborepo Remote Caching using Vercel.
Possible solutions => 
- using github actions https://github.com/felixmosh/turborepo-gh-artifacts
- using s3 https://github.com/fox1t/turborepo-remote-cache
current tests => GHA
- **Impacted projects**: `automation` `ci`
CI still runs, and can use cache as well
> test remote caching using github actions

- libs/ledger-live-common/package.json
- libs/ledger-live-common/src/families/cardano/logic.ts
typhonjs package update and fix address validation
> typhonjs package update

- apps/ledger-live-desktop/README.md
Adding some missing informations on LLD's Readme
- **Impacted projects**: `lld`
- **Linked resource(s)**: #292  
just some documentation update
make it easier for devs to understand the documentation
> update LLD doc, closes #292

- apps/ledger-live-mobile/src/components/FabActions.tsx
Entry point added to portfolio fab actions
- **Linked resource(s)**: [LIVE-2088]
https://user-images.githubusercontent.com/17146928/172903326-5a32057d-d54c-4b8c-b434-942e2a75d777.mp4
[LIVE-2088]: https://ledgerhq.atlassian.net/browse/LIVE-2088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Entry point added to portfolio fab actions

- .github/workflows/release-final-nightly.yml
- .github/workflows/release-final.yml
- .github/workflows/release-prerelease.yml
Tag Desktop et Mobile as well as libraries when we are publishing new versions
Should tag when prereleasing or releasing
Still releases but also tags LLD and LLM
closes #311 
> tag lld/llm as well

- apps/cli/src/live-common-setup-base.ts
- apps/ledger-live-desktop/cryptoassets.md
- apps/ledger-live-desktop/release-notes.json
- apps/ledger-live-desktop/src/live-common-set-supported-currencies.js
Remove filecoin because it's not ready yet
For legal reasons we need to remove FIlecoin (FIL) from 2.43.
Jira issue : https://ledgerhq.atlassian.net/browse/LIVE-2616
> LIVE-2616 remove filecoin support on release

- libs/ledgerjs/script/crypto-assets-importer/importers/ethereum-plugins.js
- **Impacted projects**: ledgerjs
- **Linked resource(s)**: ledger-live-assets
Add Ethereum testnets to the plugins json
n/a
> feat(ledgerjs-cal): add ethereum testnets

- apps/ledger-live-mobile/src/components/BuyDeviceBanner.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Onboarding/steps/doYouHaveALedger.tsx
- pnpm-lock.yaml
Padding added to doYouHaveALedger screen, texts modification\s, BuyDeviceBanner component images sizes fixes
> Reborn - Small Ui Fixes

- apps/ledger-live-desktop/src/config/urls.js
Support Hedera hyperlink modified when add account
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-2510` 
> LIVE-2510 Modification of Heredera article link

- .changeset/weak-geese-fetch.md
- apps/ledger-live-mobile/index.js
As done regularly, we update the list of "ignored errors" so they don't get automatically reported as they are "users side issues" (network, bluetooth, known error cases,..)
> Sentry LLM ignore list additions

- apps/ledger-live-mobile/src/components/Nft/NftCard.tsx
- apps/ledger-live-mobile/src/components/Nft/NftCollectionRow.tsx
- apps/ledger-live-mobile/src/components/Nft/NftImage.tsx
- apps/ledger-live-mobile/src/components/Nft/NftImageViewer.tsx
- apps/ledger-live-mobile/src/components/Nft/NftMedia.tsx
- apps/ledger-live-mobile/src/components/Nft/NftVideo.tsx
- apps/ledger-live-mobile/src/components/Nft/NftViewer.tsx
- apps/ledger-live-mobile/src/logic/nft.ts
- apps/ledger-live-mobile/src/screens/Nft/NftCollection/NftCollectionHeaderTitle.tsx
- apps/ledger-live-mobile/src/screens/SendFunds/01b-SelectCollection.tsx
- apps/ledger-live-mobile/src/screens/SendFunds/01c-SelectNft.tsx
- apps/ledger-live-mobile/src/screens/Settings/Accounts/HiddenNftCollections.tsx
This PR adds the support for new NFT medias like GIFs and videos. It's the continuation of this PR on LLC+LLD: #68 
- **Impacted projects**: [e.g. `ledger-live-mobile`]
https://ledgerhq.atlassian.net/browse/LIVE-1795
https://ledgerhq.atlassian.net/browse/LIVE-1567
> [LIVE-1567][LIVE-1795] Feature - NFT Medias on mobile

- .changeset/angry-ads-obey.md
- libs/ledgerjs/packages/hw-app-helium/package.json
- libs/ledgerjs/packages/hw-app-helium/src/serialization.ts
- libs/ledgerjs/packages/hw-app-helium/tests/Helium.test.ts
- pnpm-lock.yaml
- **Impacted projects**:
Helium ledger integration - `libs/ledgerjs/packages/hw-app-helium`
Fixes incorrect serialization of memo field which was causing transaction verification to fail.
> Fix memo serialization.

- .changeset/hip-socks-reply.md
- apps/ledger-live-mobile/src/screens/Exchange/ProviderList.js
Remove fiat filter so that we can see all multibuy providers
- **Linked resource(s)**: [LIVE-2665](https://ledgerhq.atlassian.net/browse/LIVE-2665) 
| Before: | After: |
|--------|-------|
| <img src="https://user-images.githubusercontent.com/3009753/173840748-b6904be9-ce11-4612-abc6-944d9a4ae66e.jpg" alt="LLM 3-3" width=250 /> | <img src="https://user-images.githubusercontent.com/3009753/173840774-326db2ac-e8ef-4188-99bd-8017d58c2bd2.png" width=250 /> |
> fix(multibuy): remove fiat filter [LIVE-2665]

- .github/templates/hotfix.md
- .github/templates/release.md
- .github/workflows/release-create-hotfix.yml
- .github/workflows/release-create.yml
- pnpm-lock.yaml
To make sure we don't forget anything when we are ready to make a release/hotfix, I've added a checklist to the PR so we are sure we don't forget any step (_hint_ the release notes on LLD)
No Demo
Display a checklist on the `release` and `hotfix` branches
> add templates to hotfix and release branches

- .changeset/neat-fireants-lie.md
- apps/ledger-live-desktop/README.md
- apps/ledger-live-desktop/src/renderer/components/OperationsList/AccountCell.js
Modified the height of the AccountCell to let some space for the CryptoCurrencyIcon it is embedding. Fixes an issue seen on Polkadot transactions history.
https://ledgerhq.atlassian.net/browse/LIVE-2504
- **Impacted projects**: ``LLD
> LIVE-2504 Fixed container height to prevent deformation of CryptoIcon

- .changeset/beige-lizards-leave.md
- libs/ledger-live-common/src/families/cosmos/speculos-deviceActions.ts
- **Impacted projects**: live-common
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-2500
When running the bot on Cosmos, it doesn't choke on ACCEPT and REJECT steps.
Solves the issue seen for example in that run: https://github.com/LedgerHQ/ledger-live/commit/8ba25fd3c2fccd164786af879b785981b620e0b0#commitcomment-74574949
> LIVE-2500 Update expected steps for Cosmos device actions

- apps/ledger-live-mobile/src/components/FabActions.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/NewReceiveFundsNavigator.tsx
- apps/ledger-live-mobile/src/const/navigation.js
- apps/ledger-live-mobile/src/screens/SelectAccount.tsx
- apps/ledger-live-mobile/src/screens/SelectCrypto.tsx
New navigator added for the improved receive flow
- **Linked resource(s)**: [LIVE-2453]
[LIVE-2453]: https://ledgerhq.atlassian.net/browse/LIVE-2453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Receive Flow - New navigator added for the improved receive flow

- .changeset/tasty-needles-wave.md
- apps/ledger-live-mobile/src/components/NoMoreOperationFooter.js
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Account/index.tsx
Renamed Last Operations in LLM to Last Transactions
Changed the translation key to keep it clear.
https://ledgerhq.atlassian.net/browse/LIVE-2344
⬇️
- **Impacted projects**: `` **Ledger Live Mobile**
> LIVE-2344 - Updated last operations => Last transactions

- apps/ledger-live-mobile/src/components/RootNavigator/MainNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/ManagerNavigator.tsx
- apps/ledger-live-mobile/src/components/TabBar/TransferDrawer.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Account/ReadOnly/ReadOnlyAccount.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/postWelcomeSelection.tsx
Some modifications : 
- popular tag added to the buy transfer button on the quick actions
- wording typo and texts fixed
- Manager tab button behavior fixed on readOnly mode when user bought a ledger
- **Linked resource(s)**: [LIVE-2685] [LIVE-2690] [LIVE-2686] 
[LIVE-2685]: https://ledgerhq.atlassian.net/browse/LIVE-2685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-2690]: https://ledgerhq.atlassian.net/browse/LIVE-2690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5 …
> Reborn - Manager tab button behavior fixed on readOnly mode when user bought a ledger

- .changeset/little-fishes-vanish.md
- libs/ui/packages/react/src/styles/breakpoints.stories.tsx
- libs/ui/packages/react/src/styles/theme.ts
This change add multiples breakpoints for the react ui
Every utility class can be applied conditionally at different breakpoints
- **Impacted projects**: ` ui:react` 
-  ✅ **Test coverage** 
-  ✅ **Atomic delivery** 
-  ✅ **No breaking changes** 
> feat: add desktop breakpoints

- .changeset/few-fireants-cheer.md
- libs/ui/packages/react/src/components/form/Checkbox/Checkbox.tsx
Avoid checkbox to shrink when to many words in label
- **Impacted projects**: `react ui` 
- ✅ **Test coverage** 
- ✅ **Atomic delivery** 
- ✅ **No breaking changes** 
befor
after
> bugfix: avoid checkbox to shrink

- .changeset/fluffy-rats-laugh.md
- libs/ledger-live-common/src/families/tezos/synchronisation.ts
Tezos got undefined address on some accounts during sync
this address for example : tz1aV8Sm5aLvJ3EDda3K2ZQrt4UvFNQBwGWT
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-2182` 
> add check for undefined address

- tools/github-bot/src/index.ts
- tools/github-bot/src/tools.ts
Improves the message a bit when the bot autocloses a PR because the description is missing or some section has been erased.
N/A
> chore: improve a bit the message when bot autocloses pr

- .changeset/happy-students-sleep.md
- libs/ledger-live-common/package.json
- pnpm-lock.yaml
update typhonjs package that fixes Byron address validation
- **Linked resource(s)**:  
> byron address validation fix

- .changeset/weak-gorillas-invent.md
- libs/ledger-live-common/src/derivation.ts
Fix tags for glif derivation modes
- **Impacted projects**: `@ledger-live/common`
> Change tags on glif derivation modes

- apps/ledger-live-desktop/src/renderer/Default.js
- apps/ledger-live-desktop/src/renderer/components/debug/DisableTransactionBroadcastWarning.js
- pnpm-lock.yaml
Added a simple label to LLD to warn when `DISABLE_BROADCAST_TRANSACTION=1` has been enabled. This is because during testing it is easy to forget that it's been applied and can confuse tired QA's as to why their transactions and swaps are failing to get confirmed.
It will only display when `DISABLE_BROADCAST_TRANSACTION=1` is put before the run command, for example:
- For a .dmg executable: `DISABLE_TRANSACTION_BROADCAST=1 DEV_TOOLS=1 /Applications/Ledger\ Live\ Beta.app/Contents/MacOS/Ledger\ Live\ Beta` 
- For the dev build: `DISABLE_TRANSACTION_BROADCAST=1 pnpm dev:lld` 
https://user-images.githubusercontent.com/87659842/174921106-b5efa2e4-8aab-49cb-bc8c-0dea48d847ea.mov …
> Support: Added Disable Broadcast Warning in LLD

- apps/ledger-live-mobile/src/components/CopyLink.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/ReceiveFunds/03-Confirmation.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/AdditionalInfoModal.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/ReceiveSecurityModal/ConfirmUnverified.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/ReceiveSecurityModal/InitMessage.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/ReceiveSecurityModal/index.tsx
- apps/ledger-live-mobile/src/screens/ReceiveSelectAccount.tsx
Receive screen done with security modal and additional info modal
You will need a DOGE account to test as shown in the video below
- **Linked resource(s)**: [LIVE-2451] 
https://user-images.githubusercontent.com/17146928/175319295-0bceb247-6de1-4b91-b506-290c83edad15.mp4
[LIVE-2451]: https://ledgerhq.atlassian.net/browse/LIVE-2451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feat/live 2451 Receive flow receive screen

- .changeset/slimy-ghosts-tell.md
- libs/ui/packages/react/src/components/message/Tip/index.tsx
Fixes a missing colon in a styled component. Spotted by an external dev.
> fix(Tip): missing colon in StyledIconContainer

- .github/workflows/test.yml
- apps/ledger-live-mobile/src/reducers/settings.js
- package.json
- pnpm-lock.yaml
Resuming the check on doc generation for Ledger.JS libraries in CI
- **Impacted projects**: `ledgerjs` 
- **Linked resource(s)**: [LIVE-2704]
CI should not pass if some docs are not up to date in Ledger.JS pacakges
[LIVE-2704]: https://ledgerhq.atlassian.net/browse/LIVE-2704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add doc checking on ledgerjs

- .github/workflows/test-integration.yml
To be able to have test-integration working, we don't use the concurrency feature for now, because it's problematic as it was cancelling sibling runs on different PRs and it also doesn't seem we can technically use the github.event.inputs in this 🤔 
```
The workflow is not valid. .github/workflows/test-integration.yml (Line: 19, Col: 10): Unexpected symbol: '""'. Located at position 31 within expression: github.event.inputs.filter || ""
```
> test-integration to run without concurrency

- libs/ledger-live-common/src/families/cardano/js-estimateMaxSpendable.ts
fix estimateMaxSpendable for Cardano 
- **Linked resource(s)**:  
> use dummy address for estimateMaxSpendable

- libs/ledger-live-common/src/families/cardano/js-estimateMaxSpendable.ts
> dummyRecipient change for estimateMaxSpendable

- .changeset/config.json
- package.json
Enhance the generation for the changelogs with more infos, links etc....
NO
Generate cleaner changelogs
> update changelog format

- libs/ledger-live-common/src/families/cardano/js-signOperation.ts
fix memo for Cardano optimistic operation
> optimisticOperation memo fix

- .github/workflow-templates/bot-coin-family.yml
- .github/workflows/bot-cardano-silicium.yml
- .github/workflows/bot-filecoin.yml
- .github/workflows/bot-phosphore.yml
- .github/workflows/bot-staging-explorer-btc.yml
- .github/workflows/bot-staging-explorer-eth.yml
Using codecov is not suited for our usage of the bot.
- first of all, there are different kind of bot with different seed and different subset of coin being tested. so coverage will differ.
- secondly, the bot isn't predictible. It's doing random choices and random mutations.
- finally, we can't run the bot on each commit, so we can't use the feature to see the diff of codecov, and it can create issue in PR that target a branch that ran the bot.
> Remove the 'codecov' from the bot

- apps/ledger-live-desktop/README.md
fix the codecheck cmd in README to match the cmd listed in the [lld package.json file](https://github.com/youssmak/ledger-live/blob/develop/apps/ledger-live-desktop/package.json#L36)
> docs(lld): fix README test:codecheck cmd

- libs/ledger-live-common/src/__tests__/range.ts
as attempt to fix flawkyness in codecov, this will make sure we have tests for RangeRaw
> Add unit tests on fromRangeRaw, toRangeRaw (codecov)

- apps/cli/README.md
refresh the output of `pnpm run:cli` into README.md of the CLI
- **Impacted projects**: `cli` 
> Update CLI documentation from the cli output

- .changeset/soft-foxes-deny.md
- apps/ledger-live-mobile/src/analytics/segment.js
- apps/ledger-live-mobile/src/screens/RatingsModal/Init.tsx
Reverts LedgerHQ/ledger-live#561
Should not have been merge on develop, fail
> Revert "Feat - LIVE-2362"

- .changeset/stale-kings-repeat.md
- apps/ledger-live-desktop/src/renderer/components/Ellipsis.jsx
- apps/ledger-live-desktop/src/renderer/modals/Send/steps/StepSummary.jsx
- apps/ledger-live-desktop/src/renderer/modals/SignTransaction/steps/StepSummary.jsx
Add ellipsis to memo for Cosmos
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-1127 
> Bugfix/live 1127 Add ellipsis to memo for Cosmos

- .github/workflows/backup/version-or-release.yml
- .github/workflows/release-final-nightly.yml
- .github/workflows/release-final.yml
- .github/workflows/release-prerelease.yml
Replace NPM token in CI by one provided by Infra
NO DEMO
We can still push to NPM
> update npm token in CI

- libs/ledger-live-common/src/families/ethereum/specs.ts
The bot currently has coverage for Ropsten, which isnt supported anymore on LL, but not for Goerli, which is supported since recently.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-3007 
tested locally with `pnpm run:cli bot -c ethereum_goerli`
> Change Ethereum Ropsten in Goerli in the testing bot

- apps/ledger-live-mobile/index.js
- apps/ledger-live-mobile/ios/Podfile.lock
- apps/ledger-live-mobile/package.json
- pnpm-lock.yaml
Sentry is upgraded to its latest version. It's a major version but it's still expected to work without the need to change anything. 
patch: I also took this Sentry iteration opportunity to filter out useless to track errors.
- **Impacted projects**: LLM 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-2977  
- ✅  ios (dev+sim) https://sentry.io/organizations/ledger/issues/3436335434/
- ✅ android (dev+sim) https://sentry.io/organizations/ledger/issues/3436335434/
> Upgrade Sentry in LLM + filtering more errors

- apps/ledger-live-mobile/ios/Podfile.lock
> chore: update podfile

- .github/workflows/test.yml
- codecov.yml
- configure codecov to wait the 2 reports
- don't upload to codecov if test fails
I think the combination of these two fixes will fix the codecov flawkyness which is due to one of the test failing and sending a partial report.
> codecov configuration update

- libs/ledger-live-common/src/bot/index.ts
fixed logic of #681 
- **Linked resource(s)**: `#ledger-live-bot` 
> Bot: fix warning logic to exclude Bitcoin warn if tesnet have funds

- .changeset/dirty-socks-smoke.md
- apps/ledger-live-desktop/release-notes.json
- apps/ledger-live-desktop/src/renderer/Default.jsx
- apps/ledger-live-desktop/src/renderer/components/BalanceInfos/index.jsx
- apps/ledger-live-desktop/src/renderer/components/BuyButton.jsx
- apps/ledger-live-desktop/src/renderer/components/ContextMenu/AccountContextMenu.jsx
- apps/ledger-live-desktop/src/renderer/screens/account/AccountActionsDefault.jsx
- apps/ledger-live-desktop/src/renderer/screens/account/AccountHeaderActions.jsx
- apps/ledger-live-desktop/src/renderer/screens/account/EmptyStateAccount.jsx
- apps/ledger-live-desktop/src/renderer/screens/asset/AssetBalanceSummaryHeader.jsx
- apps/ledger-live-desktop/src/renderer/screens/lend/modals/EmptyAccountDeposit/index.jsx
- apps/ledger-live-desktop/src/renderer/screens/market/MarketCoinScreen/index.tsx
- apps/ledger-live-desktop/src/renderer/screens/market/MarketRowItem.tsx
- apps/ledger-live-desktop/src/renderer/screens/platform/App.jsx
- apps/ledger-live-desktop/src/renderer/screens/platform/Catalog.jsx
- libs/ledger-live-common/src/featureFlags/types.ts
_Redirect all entry points of buy and sell towards the live app if feature flag is on_
- **Linked resource(s)**: [LIVE-2941] [LIVE-2942] 
[LIVE-2941]: https://ledgerhq.atlassian.net/browse/LIVE-2941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-2942]: https://ledgerhq.atlassian.net/browse/LIVE-2942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-2941 LIVE-2942 LLD - route buy and sell to live app + feature flag

- .changeset/spicy-eyes-decide.md
- libs/ui/packages/react/src/components/layout/List/VerticalTimeline/TimelineIndicator.tsx
- libs/ui/packages/react/src/components/layout/List/VerticalTimeline/TimelineItem.tsx
- libs/ui/packages/react/src/components/layout/List/VerticalTimeline/VerticalTimeline.stories.tsx
- libs/ui/packages/react/src/components/layout/List/VerticalTimeline/index.tsx
- libs/ui/packages/react/src/components/layout/index.ts
Migrate VerticalTimeline component from native-ui lib to react-ui lib
- **Impacted projects**: `react-ui`
- **Linked resource(s)**: [FAT-145]
[FAT-145]: https://ledgerhq.atlassian.net/browse/FAT-145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> support: migrate Vertical timeline component from native to UI

- .changeset/light-pans-report.md
- apps/ledger-live-mobile/src/helpers/formatAccountSearchResults.js
- apps/ledger-live-mobile/src/screens/RequestAccount/01-SelectCrypto.js
- apps/ledger-live-mobile/src/screens/RequestAccount/02-SelectAccount.js
Also refactor the screens with useCallback on the flatlist to improve perf
> fix: requestAccount to show all accounts

- apps/ledger-live-mobile/src/config/urls.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/logic/ratings.tsx
- apps/ledger-live-mobile/src/screens/RatingsModal/Disappointed.tsx
- apps/ledger-live-mobile/src/screens/Settings/index.tsx
Two small texts modifications made and english language restriction removed (two options `languages_whitelisted` and `languages_blacklisted` will be added to the feature flag configurations with the push notifications to manage languages restrictions in the remote config rather than in the code)
- **Linked resource(s)**: [LIVE-3009]
[LIVE-3009]: https://ledgerhq.atlassian.net/browse/LIVE-3009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Ratings language restriction removed and texts small modifications

- .changeset/green-crabs-begin.md
- libs/ledger-live-common/src/apps/support.ts
Next update of Polkadot network requires a new version of the Nano app, need to enforce this minimum version in Live.
New version is 13.9250.0
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-3068 
> LIVE-3068 Update Polkadot app minimum version to 13.9250.0

- apps/ledger-live-desktop/.gitignore
Add report.json to the gitignore in LLD
pnpm run test:jest generates an outputfile and we don't want to send it on the repo
> [LLD] Add report.json to .gitignore

- apps/ledger-live-desktop/static/i18n/de/app.json
- apps/ledger-live-desktop/static/i18n/es/app.json
- apps/ledger-live-desktop/static/i18n/ja/app.json
- apps/ledger-live-desktop/static/i18n/ko/app.json
- apps/ledger-live-desktop/static/i18n/zh/app.json
Please review translation and merge this pull request
> Smartling on-demand translation delivery from release

- libs/ledger-live-common/src/bot/formatters.ts
- libs/ledger-live-common/src/bot/index.ts
Improve bot formatting
bot is going to run on this PR and we will see the report improved 🤞 
> Improve bot formatting

- .changeset/witty-numbers-design.md
- apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx
_LLM - LEarn page add a close button in header for back to app navigation_
- **Impacted projects**: `ledgerlive-mobile` 
- **Linked resource(s)**: [LIVE-3015] 
[LIVE-3015]: https://ledgerhq.atlassian.net/browse/LIVE-3015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-3015 - LLM - Learn page add a close button for back navigation

- libs/ledger-live-common/src/bot/index.ts
polish bot report
- **Linked resource(s)**: `#ledger-live-bot` 
bot is about to comment on this PR. this will be the demo 😄 
> polish bot report

- .changeset/famous-pens-move.md
- libs/ui/packages/react/src/components/cta/Button/index.tsx
Fix button size in react-ui
- **Impacted projects**: `react-ui` 
- **Linked resource(s)**: https://github.com/LedgerHQ/ledger-live/pull/762
> Harmonize button size from React UI with current V3 desktop button

- apps/ledger-live-mobile/src/screens/ReceiveFunds/03a-ConnectDevice.tsx
_Fixes issue introduced ater failed merge in LLM Receive Flow_
- **Linked resource(s)**: [LIVE-3150] 
[LIVE-3150]: https://ledgerhq.atlassian.net/browse/LIVE-3150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-3150 - LLM - Receive flow crash after merge issue

- apps/ledger-live-desktop/src/renderer/components/WebPlatformPlayer/LiveAppSDKLogic.ts
Fix an incorrect import path in PlatformPlayer Desktop.
- **Impacted projects**: `LLD`
- **Linked resource(s)**: `none`
> Correct wrong import path of getEnv

- apps/ledger-live-mobile/src/screens/Portfolio/index.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/index.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricSections/OperationsHistory.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricSections/SectionTitle.tsx
- pnpm-lock.yaml
OperationsHistorySection added to the Wallet page
- **Linked resource(s)**: [LIVE-2799] 
[LIVE-2799]: https://ledgerhq.atlassian.net/browse/LIVE-2799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Asset Centric Wallet - OperationsHistorySection added to the Wallet page

- .changeset/real-lizards-help.md
- apps/ledger-live-mobile/src/screens/AccountSettings/index.tsx
- apps/ledger-live-mobile/src/screens/Accounts/AccountOrder.tsx
_Fixes issue on redirection after an account deletion_
- **Linked resource(s)**: [LIVE-3165] 
[LIVE-3165]: https://ledgerhq.atlassian.net/browse/LIVE-3165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BugFix/ LIVE-3165 - LLM - Account deletion issue on redirection

- .changeset/two-olives-push.md
- apps/ledger-live-mobile/src/screens/ReceiveFunds/02-AddAccount.tsx
_LLM Receive flow fixes missing parent account name during token account scanning_
- **Linked resource(s)**: [LIVE-2828] 
[LIVE-2828]: https://ledgerhq.atlassian.net/browse/LIVE-2828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-2828 - LLM - Receive flow fix issue on token account creation name

- .changeset/brown-nails-yell.md
- .github/workflows/test-desktop.yml
- apps/ledger-live-mobile/ios/Podfile.lock
- apps/ledger-live-mobile/package.json
- pnpm-lock.yaml
Storyly version updated to fix mobile
> Storyly version updated to fix mobile

- apps/ledger-live-desktop/src/renderer/index.html
Fixes the loader UI and animation
Before:
After:
> fix: the loader screen animation

- .changeset/serious-cherries-taste.md
- apps/ledger-live-mobile/src/components/FabActions.tsx
_LLM Market receive flow issue_
- **Linked resource(s)**: [LIVE-3199] 
[LIVE-3199]: https://ledgerhq.atlassian.net/browse/LIVE-3199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-3199 - LLM - Receive flow redirection issue from market

- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Portfolio/Header.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/index.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricSections/MarketPrice.tsx
- pnpm-lock.yaml
Market price section added to asset page
- **Linked resource(s)**: [LIVE-2808] 
https://user-images.githubusercontent.com/17146928/182817433-3a492def-1534-43b0-88cf-94d3617b9b7e.mp4
[LIVE-2808]: https://ledgerhq.atlassian.net/browse/LIVE-2808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Asset Centric Wallet -  market price section added to asset page

- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Analytics/RingChart.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/index.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricSections/Allocations.tsx
Allocation section added to the wallet page
- **Linked resource(s)**: [LIVE-2798]
https://user-images.githubusercontent.com/17146928/182855319-f5492f8c-be23-4f68-a744-12b8839cf9a2.mp4
[LIVE-2798]: https://ledgerhq.atlassian.net/browse/LIVE-2798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Asset Centric Wallet - Allocation section added to the wallet page

- libs/ledgerjs/README.md
add Nano S Plus in readme of ledgerjs root folder
- **Impacted projects**: `na` 
- **Linked resource(s)**: `na` 
> add Nano S Plus in README

- .changeset/tidy-bugs-camp.md
- libs/ledger-live-common/package.json
- pnpm-lock.yaml
Fix Cardano address validation
- **Linked resource(s)**:  
> fix cardano address validation

- .changeset/shiny-pumpkins-explain.md
- apps/ledger-live-mobile/src/screens/ReceiveFunds/02-AddAccount.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/02-SelectAccount.tsx
_LLM - Receive flow issue when selecting multiple accounts creating several ones_
- **Linked resource(s)**: [LIVE-3222] 
[LIVE-3222]: https://ledgerhq.atlassian.net/browse/LIVE-3222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bugfix/Live-3222 LLM receive flow multiple account issue

- apps/ledger-live-desktop/src/internal/index.js
- apps/ledger-live-desktop/src/main/index.js
- apps/ledger-live-desktop/src/sentry/internal.js
- apps/ledger-live-desktop/src/sentry/main.js
- apps/ledger-live-desktop/src/sentry/renderer.js
This reverts part of the commit c77394e41c48069f6e8419ec47f48941b5723c3d.
CI may reveal a problem on Mac and Linux on some work shipped by #782 
this tries to revert the part that is the least important of that other PR.
> Revert part of "LLD Sentry iteration"

- apps/ledger-live-desktop/README.md
- apps/ledger-live-mobile/README.md
- libs/ledger-live-common/README.md
- libs/ledgerjs/README.md
- libs/ledgerjs/packages/hw-app-algorand/README.md
- libs/ledgerjs/packages/hw-app-btc/README.md
- libs/ledgerjs/packages/hw-app-cosmos/README.md
- libs/ledgerjs/packages/hw-app-eth/README.md
- libs/ledgerjs/packages/hw-app-helium/README.md
- libs/ledgerjs/packages/hw-app-polkadot/README.md
- libs/ledgerjs/packages/hw-app-solana/README.md
- libs/ledgerjs/packages/hw-app-str/README.md
- libs/ledgerjs/packages/hw-app-tezos/README.md
- libs/ledgerjs/packages/hw-app-trx/README.md
- libs/ledgerjs/packages/hw-app-xrp/README.md
- libs/ledgerjs/packages/hw-transport-node-ble/README.md
- libs/ledgerjs/packages/hw-transport-node-hid-singleton/README.md
- libs/ledgerjs/packages/hw-transport-webhid/README.md
- libs/ledgerjs/packages/hw-transport-webusb/README.md
- libs/ledgerjs/packages/react-native-hid/README.md
- libs/ledgerjs/packages/react-native-hw-transport-ble/README.md
I previously added links to the Dev Portal and Discord, where external devs might use this repository. 
I updated the link to Discord and added the links in the readmes of LedgerJS packages.
- **Impacted projects**: `` External developers (Blockchain Support / Ledger support in third-party wallets)
No demo
> Links to the Dev Portal for external devs

- apps/cli/src/cli.ts
- apps/ledger-live-mobile/docs/ONBOARDING_LINUX.md
- libs/ledger-live-common/src/bot/index.ts
- libs/ledger-live-common/src/families/tezos/README.md
Fixes links that was still pointing to LLC repo
> Fixes links that was still pointing to LLC repo

- libs/ledger-live-common/src/account/serialization.ts
- libs/ledger-live-common/src/families/celo/serialization.ts
Attempt to bugfix no celoResources error when you got old account
> celo to raw account fix

- apps/ledger-live-desktop/tests/specs/services/discover.spec.ts
unclear if it's the only flawky test but this is one.
@nabil-brn suggested to try to use timeout first 🤞 
> Fixes CI flawky e2e tests

- apps/ledger-live-mobile/src/components/AccountGraphCard.tsx
- apps/ledger-live-mobile/src/components/AssetCentricGraphCard.tsx
- apps/ledger-live-mobile/src/components/CurrencyGradient.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/AccountsNavigator.tsx
- apps/ledger-live-mobile/src/screens/Account/Header.js
- apps/ledger-live-mobile/src/screens/Account/ListHeaderComponent.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/Header.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/Header.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/index.tsx
- pnpm-lock.yaml
Created GraphCard, header and the general upper layout of the new Wallet Page.
this is an intermediate merge, there are still some elements to add and pixel polish to be done
> Feat/live 2804/asset header graph v0

- apps/ledger-live-desktop/tests/specs/general/stability.spec.ts
- apps/ledger-live-desktop/tests/userdata/bot-accounts.json
- apps/ledger-live-desktop/tests/userdata/bot-accounts.md
accounts of the bot were put in a app.json and tested in a sanity stability test on LLD.
> Add a LLD e2e test that try to load app with all bot accounts

- package.json
- pnpm-lock.yaml
```diff
-    "@changesets/changelog-github": "^0.4.5",
+    "@changesets/changelog-github": "^0.4.6",
-    "@changesets/cli": "^2.23.0",
+    "@changesets/cli": "^2.24.3",
-    "turbo": "1.3.1"
+    "turbo": "1.4.3"
```
N/A
> chore: upgrade root dependencies

- .github/workflows/test.yml
replace deprecated python 2.7 in Test Libraries CI
no demo
same test results as python 2.7
> use python 3 in test libraries

- apps/ledger-live-mobile/src/components/RootNavigator/AccountsNavigator.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/ReadOnly/index.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/ReadOnlyAssets.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/Header.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/ReadOnly/index.tsx
- pnpm-lock.yaml
Read Only mode done for the new wallet pages
- **Linked resource(s)**: [LIVE-2815] 
[LIVE-2815]: https://ledgerhq.atlassian.net/browse/LIVE-2815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat/LIVE-2815-asset-centric-wallet-reborn Read only mode

- .changeset/breezy-cars-attack.md
- .changeset/heavy-mice-move.md
- apps/ledger-live-mobile/index.js
- apps/ledger-live-mobile/src/components/FirebaseFeatureFlags.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/DebugFeatureFlags.tsx
- libs/ledgerjs/packages/types-live/README.md
- libs/ledgerjs/packages/types-live/src/feature.ts
Some changes introduced in https://github.com/LedgerHQ/ledger-live/pull/507 made `getFeature` a hook (because it was now calling `useSelector`). It was previously a simple function that can be called from anywhere, and hooks can't be called from anywhere ([they can only be called from _React_ function components or custom hooks, and never in loops, conditions or nested functions](https://github.com/LedgerHQ/ledger-live/pull/507)).
**In multiple places this function is called either in loops or in plain JS functions (outside of React).**
I don't know if this was breaking anything so far, **I'd say it could have been breaking the sentry setup of tags** but some WIP of mine it was causing a crash (because I was reusing this function somewhere else).
The solution is just to make it a plain …
> Fix (LLM): getFeature being a hook & called as a regular function

- apps/ledger-live-mobile/src/components/AccountGraphCard.tsx
- apps/ledger-live-mobile/src/components/AccountRowLayout.tsx
- apps/ledger-live-mobile/src/components/FabActions/hooks/useAssetActions.tsx
- apps/ledger-live-mobile/src/components/FabActions/index.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/reducers/accounts.js
- apps/ledger-live-mobile/src/screens/Account/AccountHeader.tsx
- apps/ledger-live-mobile/src/screens/Account/index.tsx
- apps/ledger-live-mobile/src/screens/Accounts/AccountRow.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/AccountsSection.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/AssetRow.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/index.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricSections/OperationsHistory.tsx
- libs/ui/packages/native/src/components/tags/Tag/index.tsx
- libs/ui/packages/native/storybook/stories/Tag/Tag.stories.tsx
- Complete redesign of the AccountRowLayout component : Remove icon, some style change, add a Tag with Parent account name when it's a token
- Redesign TAG component in native ui library, so i add all the variants from the design system ( https://www.figma.com/file/wGzwuUVo0rkCJ3sM8cpbDY/%F0%9F%93%B1-LLM-%2F-Library?node-id=10008%3A93955 )
- Some crash fixes on token account page by modifying OperationHistory (didn't included the parentAccount) and AccountGraphCard component (didn't get the account currency the right way)
- **Impacted projects**: `` native-ui, live-mobile
- **Linked resource(s)**: `` https://www.figma.com/file/RjfewR5dPMMBYyiV0xkK8U/LLM-%2F-Assets-aggregation?node-id=493%3A41127 https://ledgerhq.atlassian.net/browse/LIVE-3343?atlOrigin=eyJpIjoiMzYxOTNmODc0ZjNhNGI3N2EwNzg2N …
> Feat - LIVE-3343 - LLM new asset page accounts section

- apps/ledger-live-desktop/release-notes.json
- apps/ledger-live-mobile/src/components/AccountRowLayout.tsx
- apps/ledger-live-mobile/src/components/AssetRowLayout.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Accounts/index.tsx
- apps/ledger-live-mobile/src/screens/Analytics/DistributionCard.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/EmptyStatePortfolio.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/index.tsx
- libs/ui/packages/native/src/components/tags/Tag/index.tsx
Some ui improvements on the accounts section and a few crashes fixed
- **Impacted projects**: `ledger-live-mobile` `native-ui` 
> Asset Centric Wallet - Some ui improvements on the accounts section and a few crashes fixed

- .changeset/twelve-gifts-jam.md
- libs/ui/packages/native/src/components/Layout/Divider/index.tsx
- libs/ui/packages/native/src/components/Layout/index.ts
- libs/ui/packages/native/storybook/stories/Layout/Divider.stories.tsx
This PR adds a simple divider component to the Native Design System.
> SUPPORT Add Divider component to the design system

- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Analytics/DistributionCard.tsx
- apps/ledger-live-mobile/src/screens/Market/MarketDetail/index.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/AccountsSection.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/index.tsx
> Asset Centric Wallet - Some ui improvements

- apps/ledger-live-mobile/src/components/AccountGraphCard.tsx
- apps/ledger-live-mobile/src/components/AssetCentricGraphCard.tsx
- apps/ledger-live-mobile/src/components/BackgroundGradient.tsx
- apps/ledger-live-mobile/src/components/CurrencyBackgroundGradient.tsx
- apps/ledger-live-mobile/src/components/CurrencyHeaderLayout.tsx
- apps/ledger-live-mobile/src/components/GraphCard.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Account/AccountHeader.tsx
- apps/ledger-live-mobile/src/screens/Account/index.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/GraphCardContainer.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/Header.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/Header.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/index.tsx
- pnpm-lock.yaml
Created new Header Layout component to avoid animations duplication
Modified GraphCards contents for both Account and Asset pages
Modified general animations.
https://user-images.githubusercontent.com/39890664/185371622-3e1068f8-f30c-4197-bffb-a70006fbe2a8.mov
> Feat/live 2804/headers andgraphs

- apps/ledger-live-mobile/src/screens/AccountSettings/index.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/Header.tsx
Asset settings removed from the account settings screen and now accessible from the asset page
> Asset Centric Wallet - Asset settings

- .changeset/beige-chefs-march.md
- .changeset/many-worms-clap.md
- .changeset/nervous-dingos-tap.md
- apps/ledger-live-mobile/src/reducers/settings.js
- apps/ledger-live-mobile/src/screens/AddAccounts/02-TokenCurrencyDisclaimer.js
- apps/ledger-live-mobile/src/screens/PostBuyDeviceScreen.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/02-AddAccount.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/02-SelectAccount.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/03-Confirmation.tsx
_LLM fix crash issues on receive flow_
- **Linked resource(s)**: [LIVE-3380] [LIVE-3385] [LIVE-3400] 
[LIVE-3380]: https://ledgerhq.atlassian.net/browse/LIVE-3380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-3385]: https://ledgerhq.atlassian.net/browse/LIVE-3385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-3400]: https://ledgerhq.atlassian.net/browse/LIVE-3400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …
> Bugfix/ LIVE-3380 LIVE-3385 LIVE-3400 crash receive flow issue

- apps/ledger-live-mobile/src/components/AccountGraphCard.tsx
- apps/ledger-live-mobile/src/components/AssetCentricGraphCard.tsx
- apps/ledger-live-mobile/src/components/CurrencyGradient.tsx
- apps/ledger-live-mobile/src/screens/Account/AccountHeader.tsx
- apps/ledger-live-mobile/src/screens/Account/ListHeaderComponent.tsx
Added tags (adress and parent name) to Account page + diverse tiny fixes
> Added Tags to Accounts pages + diverses tiny fixes

- libs/ledger-live-common/src/families/cardano/js-estimateMaxSpendable.ts
code like
```js
try {
typhonTransaction = await buildTransaction(a as CardanoAccount, t);
} catch (error) {
return new BigNumber(0);
}
```
must be improved, because this is literally silenting possible errors. Instead we must at least LOG them using ledgerhq/logs.
This PR solves this.
Important notes for Cardano maintainers
---
**(1)**
**⚠️  Current bug in estimateMaxSpendable implementation:**
Please also note that this helped identify a problem, it seems like this codebase always fails at this point with
```
info: Failed to estimate max spendableError: Invalid Address
```
to reproduce, you can simply try to estimate the max spendable of the bot account:
```
VERBOSE=1 pnpm run:cli estimateMaxSpendable --id js:2:cardano:da85e83cab046f8a50aa6fcd67bd7dffee0e1fd15ad3345a78838239d4d3fc2291f70e …
```
> Add a log on catch(error) in cardano/js-estimateMaxSpendable.ts

- .changeset/gentle-tips-help.md
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/SoftwareCheckContent.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/index.tsx
- apps/ledger-live-desktop/static/i18n/en/app.json
This PR add the UI for update available in sync onboarding
- **Linked resource(s)**: [FAT-248] 
[FAT-248]: https://ledgerhq.atlassian.net/browse/FAT-248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add UI for update available in sync onboarding

- libs/ledger-live-common/src/bot/engine.ts
- libs/ledger-live-common/src/bot/formatters.ts
this will solve this ugly message: 
> Fixes ugly bad logs in slack bot reports

- .github/workflows/build-desktop.yml
- .github/workflows/release-create-hotfix.yml
- .github/workflows/release-create.yml
- .github/workflows/release-final.yml
- .github/workflows/release-prepare-desktop.yml
- .github/workflows/release-prepare-hotfix.yml
- .github/workflows/release-prepare-mobile.yml
Remove unused fetch-depth: 0 from some job. should speed up the CI by not doing extra work
No Demo
> clean fetch: 0 to speed up some CI jobs

- .github/workflows/build-desktop.yml
- .github/workflows/build-mobile.yml
- .github/workflows/generate-screenshots.yml
- .github/workflows/test-desktop.yml
- .github/workflows/test.yml
- libs/ledger-live-common/scripts/build-ts.mjs
- tools/actions/turborepo-gh-cache/action.yml
- tools/actions/turborepo-gh-cache/src/cleanup.ts
- tools/actions/turborepo-gh-cache/src/main.ts
Attempts to fix windows CI erroring and still exiting with code 0.
> ci: attempt to fix windows unhandled promise exit code 0

- apps/ledger-live-desktop/release-notes.json
- apps/ledger-live-desktop/static/i18n/en/app.json
- apps/ledger-live-mobile/ios/Podfile.lock
- pnpm-lock.yaml
Renamed all Manager strings to My Ledger
- **Linked resource(s)**: [LIVE-3018]
N/A
[LIVE-3018]: https://ledgerhq.atlassian.net/browse/LIVE-3018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LLD - Renamed all occurrences of Manager to My Ledger

- .changeset/breezy-bananas-pull.md
- libs/ledger-live-common/src/hw/getGenuineCheckFromDeviceId.test.ts
- libs/ledger-live-common/src/hw/getGenuineCheckFromDeviceId.ts
- libs/ledger-live-common/src/hw/getLatestAvailableFirmwareFromDeviceId.ts
- libs/ledger-live-common/src/hw/hooks/useGenuineCheck.test.ts
- libs/ledger-live-common/src/hw/hooks/useGenuineCheck.ts
- libs/ledger-live-common/src/hw/hooks/useGetLatestAvailableFirmware.test.ts
- libs/ledger-live-common/src/hw/hooks/useGetLatestAvailableFirmware.ts
Hooks defined in live-common with unit-tests for:
- genuine check
- get latest available firmware
It has no breaking change, as it is not used in prod yet.
It is only used for the sync onboarding for both LLM and LLD.
An example of use for LLD can be found (with internal thread commands) in PR #1026 
You can see a demo on slack
- **Impacted projects**:  `live-common`
> feat: hooks for genuine check and get latest available firmware

- apps/ledger-live-mobile/src/actions/general.js
- apps/ledger-live-mobile/src/components/FabActions/index.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/ReadOnly/index.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/index.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/AssetRow.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/ReadOnly/index.tsx
- libs/ledger-live-common/src/portfolio/v2/index.ts
- libs/ledger-live-common/src/portfolio/v2/react.ts
Fixed the following bugs :
- LLM - Reborn user - App crash when onboarding with explore mode
- LLM - Polygon/BSC Account - App crash when delete last polygon account
- LLM - Assets List - Asset with account have balance 0 should be listed
- LLM - Account page - Delete an account redirect user to an black or white page(depends on theme)
- **Impacted projects**: `ledger-live-mobile` `ledger-live-common` 
- **Linked resource(s)**: [LIVE-3463] [LIVE-3429] [LIVE-3433] [LIVE-3469] 
[LIVE-3463]: https://ledgerhq.atlassian.net/browse/LIVE-3463?atlOrigin=eyJpIjoiNWRkNTljNzY …
> asset centric wallet various bugfixes

- .changeset/tough-birds-fry.md
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/CompletionScreen.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/SoftwareCheckContent.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/SoftwareCheckStep.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/index.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/index.tsx
Link together the work from [FAT-99] with [FAT-161] to have a fully working onboarding companion on desktop.
- **Linked resource(s)**: [FAT-296] 
[FAT-99]: https://ledgerhq.atlassian.net/browse/FAT-99?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAT-161]: https://ledgerhq.atlassian.net/browse/FAT-161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAT-296]: https://ledgerhq.atlassian.net/browse/FAT-296?atlOrigin=eyJpIjoiNWRk …
> Plug sync onboarding UI with device polling

- apps/ledger-live-mobile/src/screens/Account/ListHeaderComponent.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/index.tsx
- apps/ledger-live-mobile/src/screens/Settings/Accounts/TokenContextualModal.js
Fixed two bugs :
- Empty accounts not showing graph card
- Not redirecting to proper page when hiding token.
- **Linked resource(s)**: LIVE-3459 - LIVE-3466
N/A
> LLM - Wallet Centric Asset - diverse bugfixes (3459 + 3466)

- apps/ledger-live-desktop/src/internal/commands/getGenuineCheckFromDeviceId.ts
- apps/ledger-live-desktop/src/internal/commands/getLatestAvailableFirmwareFromDeviceId.ts
- apps/ledger-live-desktop/src/internal/commands/index.js
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/index.tsx
⚠️ Associated to PR #1025 <- this PR needs to be merge on `develop` first, and then rebase FAT-99. 
The commits `6946fdaaea413386ee51f4e7204ff855bbadde1f` and `88ca3610ea7c8a9ba8eec6bf4d27db93908a53e5` are currently cherry-picked from this PR.
- Commands for genuine check and get latest available firmware (so their associated hook can run on the internal thread)
- Example of use for the hooks
> feat: FAT-99 genuine check and get latest available firmware hooks

- apps/ledger-live-mobile/src/screens/ImportAccounts/DisplayResult.tsx
- apps/ledger-live-mobile/src/screens/ImportAccounts/DisplayResultItem.tsx
alternative UI that would improve https://github.com/LedgerHQ/ledger-live/pull/1066 one's
- **Linked resource(s)**: live-3512 
> Make all checkbox spinning to make it more obvious to the user

- apps/ledger-live-mobile/src/actions/accounts.ts
- apps/ledger-live-mobile/src/bridge/cache.ts
- apps/ledger-live-mobile/src/reducers/accounts.ts
- apps/ledger-live-mobile/src/screens/ImportAccounts/DisplayResult.tsx
- apps/ledger-live-mobile/src/screens/ImportAccounts/DisplayResultItem.tsx
- libs/ledger-live-common/src/account/importAccounts.integration.test.ts
- libs/ledger-live-common/src/account/importAccounts.test.ts
- libs/ledger-live-common/src/account/importAccounts.ts
We introduce a new function `syncNewAccountsToImport` that must be called to provide to `importAccountsReduce` the "syncResult" that result of the synchronisation of all accounts that are about to get imported.
Basically, for user land, we just need to change this:
**This new flow will guarantee that the accounts resulting of a Live QR importation** (importing Accounts from LLD with the animated QR code) will be fully ready to be used: synchronized and complete. 
- This fixes the problem that `tronResources` (or any other coin Resources field) was `undefined` and was causing a lot of random bugs.
- This fixes the problem that the UI was not ready to show the complete accounts (missing transactions, missing secondary balances, bad errors in send flow,...)
- This fixes the ability for us to …
> LLM: fixes import from desktop to fully sync accounts before save

- libs/ledger-live-common/src/families/bitcoin/specs.ts
Fix bch bot due to the bitcoincash prefix address problem
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-3478
> LIVE-3478 fix bch bot

- apps/ledger-live-mobile/fastlane/Fastfile
Ping in a Slack channel whenever we build a new release / pre-release / nightly
- **Impacted projects**: `ledger-live` 
- **Linked resource(s)**:  https://github.com/LedgerHQ/ledger-live-issues/issues/8 
Incoming....
Post into a dedicated slack channel whenever we publish new artifacts
> Report builds to slack

- libs/ledger-live-common/src/bot/engine.ts
PR to contain more evolution for the bot. (we will update this PR each time we do evolutions or fix on the bot and will merge it by batch, description will list all things covered)
- Wrap more cases into 'botTest' to catch the contextes
> Bot evolutions

- .changeset/dull-jeans-act.md
- libs/ledger-live-common/src/account/serialization.ts
- libs/ledger-live-common/src/reconciliation.ts
Types rework that happened in https://github.com/LedgerHQ/ledger-live/pull/451
The types rework introduced regressions in serialization.ts and reconciliation.ts because coin-specific account resources could no longer be present in the `Account` object.
Previous isolated fixes were done on both files but not systematically for all coins.
This PR ensures safety checks everywhere relevant and for all coins, in both files so that the serialization / patching of account resources is just skipped if missing.
This prevents crashes and allows LL at least a chance to trigger successful syncs on all coins.
However issues could still happen if the user attempts actions on accounts before a first sync is complete.
Proper fix will include further coin modularization to moves these parts of code inside …
> Safe serialization & reconciliation when no account resources

- apps/ledger-live-desktop/src/renderer/hooks/useDeeplinking.js
- libs/ledger-live-common/src/platform/react.ts
Add some comments / todo regarding deeplink and query params usage.
> [MISC] add comments regarding deeplink

- apps/ledger-live-desktop/static/i18n/en/app.json
Fix some minor typos in en/app.json
> Fix some typos in en/app.json

- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/ApplicationContent.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/GenuineCheckAnimationModal.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/SoftwareCheckContent.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/SoftwareCheckStep.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/index.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/shared.tsx
This PR add the logic of the genuine check and the firmware update in the sync onboarding
- **Linked resource(s)**: [FAT-152] 
[FAT-152]: https://ledgerhq.atlassian.net/browse/FAT-152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add genuine check and firware update logic

- apps/ledger-live-mobile/src/components/AccountRowLayout.tsx
- apps/ledger-live-mobile/src/components/AssetCentricGraphCard.tsx
- apps/ledger-live-mobile/src/components/Delta.tsx
- apps/ledger-live-mobile/src/components/GraphCard.tsx
- apps/ledger-live-mobile/src/screens/Account/ListHeaderComponent.tsx
- apps/ledger-live-mobile/src/screens/Accounts/AccountRow.tsx
- apps/ledger-live-mobile/src/screens/Market/DeltaVariation.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/AccountsSection.tsx
- libs/ui/packages/native/src/components/cta/QuickAction/QuickActionList/index.tsx
- Remove bottom padding for last item of accounts list
- Fix "delta" percent change text properties and icon
- Account page: Remove AccountHeader from the bottom of the graph card, as it is now in the "Earn" section
- Misc text properties fixes in asset and account page
- Fix last item of QuickActionList having margin right when it should not
-
- **Impacted projects**: `` live-mobile, native-ui
> Bugfix/LIVE-2652 - LLM - Asset centric wallet pixel polishing 

- apps/ledger-live-mobile/src/screens/Accounts/AccountsNavigationHeader.tsx
- apps/ledger-live-mobile/src/screens/Accounts/AddAccount.tsx
- apps/ledger-live-mobile/src/screens/Accounts/index.tsx
- apps/ledger-live-mobile/src/screens/AddAccounts/AddAccountsModal.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/AccountsSection.tsx
Clicking on + inside a specific crypto account list add the said crypto
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-3554
> LIVE-3354 - LLM - Clicking on + inside a specific crypto account list add the said crypto

- apps/ledger-live-mobile/src/components/FabActions/hooks/useAssetActions.tsx
- apps/ledger-live-mobile/src/components/FabActions/modals/ZeroBalanceDisabledModalContent.tsx
- apps/ledger-live-mobile/src/screens/Account/hooks/useAccountActions.tsx
- Fix navigate asset page to buy/sell/receive
- Fix Buttons - Blocked status → Receive flow was the old one
- Fix Buttons - Blocked status → couldn't open again when user went through Buy or Receive flow
- Add ZeroBalanceDisabledModal on account page for Sell Action when account is empty
> Bugfix/LIVE-2653 - LLM - Asset centric wallet - Misc assets/accounts fabActions fixes

- apps/ledger-live-desktop/.eslintrc.js
- apps/ledger-live-desktop/src/renderer/components/ConnectEnvsToSentry.tsx
- apps/ledger-live-desktop/src/renderer/screens/account/AccountBanner.jsx
- apps/ledger-live-desktop/src/renderer/screens/account/index.jsx
- apps/ledger-live-desktop/src/renderer/screens/market/MarketList.tsx
- apps/ledger-live-desktop/src/renderer/screens/nft/useOnScreen.js
- apps/ledger-live-mobile/src/families/cosmos/Delegations/index.tsx
- libs/ledger-live-common/src/families/cosmos/banner.test.ts
- libs/ledger-live-common/src/families/cosmos/banner.ts
- Conditional hook introduced on LLD with commit https://github.com/LedgerHQ/ledger-live/commit/ea43cc0f4c37ffe65d45d510f44855755b00a8fb#diff-4012b178928468ebbf2c2927a55e15a2af7c36b4680f125740274b26d8a8705a
This PR removes it.
- Includes other very minor lint fixes found by stricter eslint rules
- Additional optimization that changes the call stack of `getBannerProps` to not be async.
**Note**: no changeset as this fixes changes that were never released yet.
- **Impacted projects**: `ledger-live-common` `ledger-live-desktop` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-3599
> LIVE-3599 Remove conditional hook in account screen in LLD

- .changeset/empty-numbers-attack.md
- .changeset/spicy-spies-complain.md
- apps/ledger-live-desktop/static/i18n/en/app.json
- libs/ledger-live-common/src/families/cosmos/banner.test.ts
- libs/ledger-live-common/src/families/cosmos/banner.ts
- libs/ledger-live-common/src/families/cosmos/logic.ts
- Add delegate requirements
- Add redelegate requirements
- Change in desktop text
- LLD - Cosmos banner - Change wording "Low" for 7.5 Ledger commission https://ledgerhq.atlassian.net/browse/LIVE-3606
- LLD - Cosmos banner - during redelegation period , the banner should not ask for redelegation https://ledgerhq.atlassian.net/browse/LIVE-3607
- LLD - Cosmos banner - an account with less than 0.05ATOM can not be delegated https://ledgerhq.atlassian.net/browse/LIVE-3608
> fix: add requirement delegate and redelate cosmos banner

- apps/ledger-live-mobile/src/components/BalanceSummaryInfoItem.tsx
- apps/ledger-live-mobile/src/families/cosmos/AccountBalanceSummaryFooter.tsx
- apps/ledger-live-mobile/src/families/polkadot/AccountBalanceSummaryFooter.tsx
- apps/ledger-live-mobile/src/families/tron/Votes/index.tsx
- apps/ledger-live-mobile/src/screens/Account/ListHeaderComponent.tsx
- apps/ledger-live-mobile/src/screens/Lending/Account/AccountBodyHeader.tsx
- apps/ledger-live-mobile/src/screens/Lending/Account/CompoundSummary.tsx
- Fix compound summary section that had some css issue making it disappear
- Fix misc token families sections style
- 
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-3610
> Bugfix/LIVE-3610 - LLM - Coin token page with loan earn section not displayed correctly

- .changeset/eight-mayflies-compare.md
- apps/ledger-live-mobile/package.json
- apps/ledger-live-mobile/src/actions/settings.ts
- apps/ledger-live-mobile/src/analytics/segment.ts
- apps/ledger-live-mobile/src/reducers/settings.ts
- apps/ledger-live-mobile/src/screens/GetDeviceScreen.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/doYouHaveALedger.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/ReadOnly/index.tsx
- pnpm-lock.yaml
_Fix issues on analytics for reborn_
- **Linked resource(s)**: [LIVE-3446] [LIVE-3452] 
[LIVE-3446]: https://ledgerhq.atlassian.net/browse/LIVE-3446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-3452]: https://ledgerhq.atlassian.net/browse/LIVE-3452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-3446 LIVE-3452 LLM - fix analytics issue reborn

- .changeset/gold-coats-fix.md
- apps/ledger-live-desktop/src/renderer/screens/account/index.jsx
This PR fixes the usage of `account` instead of `mainAccount` as account can be one of 3 types:
- `Account` // Has a currency
- `TokenAccount` // Doesn't have a currency
- `ChildAccount` // Has a currency
If you're depending on the currency of an account, you're then forced to use the `getMainAccount` method to make sure you're using an `Account`. 
- https://ledgerhq.atlassian.net/browse/LIVE-3619
- https://ledgerhq.atlassian.net/browse/LIVE-3599 
No more crash when accessing a TokenAccount:
https://user-images.githubusercontent.com/44363395/188634175-e39ba3c2-b7e6-4442-a208-8a894f11632b.mov
No more crash when deleting an account:
https://user-images.githubusercontent.com/44363395/188634342-46bced13-eeb7-41c8-a288-4 …
> [LIVE-3619][LIVE-3599] Bugfix: Remove usage of account for mainAccount to prevent crash

- apps/ledger-live-mobile/android/app/src/main/AndroidManifest.xml
- apps/ledger-live-mobile/android/app/src/main/java/com/ledger/live/MainActivity.java
- apps/ledger-live-mobile/ios/ledgerlivemobile/AppDelegate.h
- apps/ledger-live-mobile/ios/ledgerlivemobile/AppDelegate.m
Config to allow RTL support in apps conf files. Tested on both Android and iOS.
- **Linked resource(s)**: LIVE-3031
N/A
> Setup for RTL in iOS and Android configuration files.

- apps/ledger-live-mobile/src/screens/Accounts/AccountsNavigationHeader.tsx
- apps/ledger-live-mobile/src/screens/Accounts/ReadOnly/ReadOnlyAccounts.tsx
- apps/ledger-live-mobile/src/screens/Accounts/index.tsx
- apps/ledger-live-mobile/src/screens/Assets/AssetsNavigationHeader.tsx
- apps/ledger-live-mobile/src/screens/Assets/index.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/ReadOnlyAssets.tsx
Updated the accounts and the assets screens headers to match the figma
- **Linked resource(s)**:  N/A 
> Asset centric wallet - assets and accounts screens headers changed

- apps/ledger-live-desktop/scripts/sync-families-dispatch.mjs
- apps/ledger-live-desktop/src/renderer/families/algorand/AccountHeaderManageActions.js
- apps/ledger-live-desktop/src/renderer/families/tezos/operationDetails.jsx
A couple glitches in the mechanism of generating components via the `sync-families-dispatch.js` script on LLD.
Thanks to @JesseKuntz for spotting them. :slightly_smiling_face: 
> Fix generated families components on LLD

- libs/ledger-live-common/src/families/cosmos/specs.ts
- libs/ledger-live-common/src/families/ethereum/specs.ts
- libs/ledger-live-common/src/families/osmosis/specs.ts
- libs/ledger-live-common/src/families/tron/specs.ts
- [bot: osmosis: add the missing botTest wrappers](https://github.com/LedgerHQ/ledger-live/commit/4a34b3c2177bdab6396b3f4b5b061238283cdf21) exactly as they exists in cosmos spec (i guess it was a forgotten part)
- [tron: allow approximation in send max](https://github.com/LedgerHQ/ledger-live/commit/03a35d74327e0d0ec1a1c6043885a686d12c1038)
> bot updates

- apps/ledger-live-mobile/src/components/FabActions/hooks/useAssetActions.tsx
Asset and market page actions : If only one account, use it directly for receive and send
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-3600
> Feat/LIVE-3600 - LLM - Asset and market page actions : If only one account, use it directly

- .github/workflows/release-prerelease.yml
Fixes the prerelease workflow versioning steps
> fix: prerelease versioning

- apps/ledger-live-desktop/src/sentry/install.js
as a continuous improvement, we add more errors in the exclusion list to not be spammed with user's condition issues on sentry.
- **Impacted projects**: `LLD sentry` 
- **Linked resource(s)**: LIVE-3642 among others 
> LLD Sentry: filter more errors in exclusion list

- .changeset/perfect-coins-float.md
- apps/ledger-live-mobile/docs/linux_setup.md
This PR update the GPG doc
- **Impacted projects**: `ledger-live` 
- **Linked resource(s)**:  
You check check the result in the GPG section : https://github.com/LedgerHQ/ledger-live/blob/support/update-doc-gpg/apps/ledger-live-mobile/docs/linux_setup.md
> update doc gpg

- .changeset/afraid-pandas-confess.md
- package.json
> Add debug command LLD

- libs/ledger-live-common/src/families/evm/specs.ts
- renamed Moonbeam spec to Flare (mistake)
- raise the minimum amount of balance for the mutation test
> EVM bot: polish spec

- .changeset/blue-ducks-learn.md
- apps/ledger-live-mobile/src/languages.ts
Capitalize P for Português language in settings
- **Linked resource(s)**: [LIVE-3584] 
Go to Settings > General > Display Language and scroll to select _Português_
[LIVE-3584]: https://ledgerhq.atlassian.net/browse/LIVE-3584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> support(Polish): 💄 Capitalize P for Português language

- .changeset/violet-pumpkins-teach.md
- apps/ledger-live-desktop/src/renderer/components/Pills.jsx
Text was larger than box in Pills in Account Balance
- **Linked resource(s)**: [LIVE-3579]
_Before_ 
_After_
Go to Portfolio on LLD
[LIVE-3579]: https://ledgerhq.atlassian.net/browse/LIVE-3579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bugfix(Dashboard): Text larger than box in Pills

- libs/ledger-live-common/src/bot/index.ts
- libs/ledger-live-common/src/bot/specs.ts
- libs/ledger-live-common/src/families/cardano/specs.ts
- libs/ledger-live-common/src/families/filecoin/speculos-deviceActions.ts
Bot: Fix accounts number in report. An old number is currently used.
> Bot: Fix accounts number in report

- libs/ledger-live-common/src/bot/engine.ts
- libs/ledger-live-common/src/bot/index.ts
- libs/ledger-live-common/src/bot/specs.ts
- libs/ledger-live-common/src/bot/types.ts
- libs/ledger-live-common/src/families/bitcoin/specs.ts
- libs/ledger-live-common/src/families/cardano/specs.ts
- libs/ledger-live-common/src/families/celo/specs.ts
- libs/ledger-live-common/src/families/celo/specs/createSendMutation.ts
- libs/ledger-live-common/src/families/cosmos/specs.ts
- libs/ledger-live-common/src/families/crypto_org/specs.ts
- libs/ledger-live-common/src/families/elrond/specs.ts
- libs/ledger-live-common/src/families/ethereum/specs.ts
- libs/ledger-live-common/src/families/filecoin/specs.ts
- libs/ledger-live-common/src/families/osmosis/specs.ts
- libs/ledger-live-common/src/families/polkadot/specs.ts
- libs/ledger-live-common/src/families/ripple/specs.ts
- libs/ledger-live-common/src/families/solana/specs.ts
- libs/ledger-live-common/src/families/stellar/specs.ts
- libs/ledger-live-common/src/families/tezos/specs.ts
- libs/ledger-live-common/src/families/tron/specs.ts
- [bot: introduces expectSiblingsHaveSpendablePartGreaterThan](https://github.com/LedgerHQ/ledger-live/commit/6191376376f0711eee7288fbb1c6416d788c8f45)
- [bot: drop stakenet spec](https://github.com/LedgerHQ/ledger-live/commit/92c38d5aa873158303f653aa027e65d62df0406a)
- [Remove unecessary resync in the bot engine](https://github.com/LedgerHQ/ledger-live/pull/1286/commits/3edf3cf42929f60c1d765261c984cbc994c09dce)
- [Add hintWarnings concept to highlight bot spec problems](https://github.com/LedgerHQ/ledger-live/pull/1286/commits/cc2664b8d691f303f05c5a22bae5f5bc52e58706)
_Pull Requests …
> Bot iterations

- .changeset/calm-pigs-end.md
- libs/ledger-live-common/src/notifications/ServiceStatusProvider/index.tsx
Protecting a function which can filter on empty arrays
- **Impacted projects**: LLC LLM LLD
- **Linked resource(s)**: LIVE-2707
N/A
> Protecting a function which can filter on empty arrays

- .github/workflows/bot-phosphore.yml
- libs/ledger-live-common/src/bot/engine.ts
- libs/ledger-live-common/src/bot/formatters.ts
- libs/ledger-live-common/src/bot/index.ts
- libs/ledger-live-common/src/bot/specs.ts
- libs/ledger-live-common/src/bot/types.ts
- libs/ledger-live-common/src/families/algorand/specs.ts
- libs/ledger-live-common/src/families/bitcoin/specs.ts
- libs/ledger-live-common/src/families/cardano/specs.ts
- libs/ledger-live-common/src/families/celo/specs/createSendMutation.ts
- libs/ledger-live-common/src/families/cosmos/specs.ts
- libs/ledger-live-common/src/families/ethereum/specs.ts
- libs/ledger-live-common/src/families/evm/specs.ts
- libs/ledger-live-common/src/families/filecoin/specs.ts
- libs/ledger-live-common/src/families/hedera/specs.ts
- libs/ledger-live-common/src/families/osmosis/specs.ts
- libs/ledger-live-common/src/families/polkadot/specs.ts
- libs/ledger-live-common/src/families/ripple/specs.ts
- libs/ledger-live-common/src/families/solana/specs.ts
- libs/ledger-live-common/src/families/tezos/specs.ts
- libs/ledger-live-common/src/families/tron/specs.ts
- libs/ledger-live-common/src/load/speculos.ts
This introduces a new feature to be able to define a test for the destination account on bot specs.
This allows to implement more assertions on the effect of a mutation, today with `test` we can only assess the effect of the transaction on the SENDER account. With this new feature, `testDestination` allows to write assertions on the RECEIVING account.
Notably, we can evaluate that a new operation is created on the receiving account that is consistently mirroring the sending one.
`testDestination(input)` have input type:
```ts
type TransactionDestinationTestInput<T> = {
sendingAccount: Account;
sendingOperation: Operation;
destinationBeforeTransaction: Account;
operation: Operation;
destination: Account;
transaction: T;
status: TransactionStatus;
};
```
generic test added at the generic …
> bot: add testDestination to assert impact on destination account + other bot fixes

- .changeset/wicked-peas-camp.md
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/GenuineCheckCancelModal.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/SoftwareCheckStep.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/shared.tsx
- apps/ledger-live-desktop/static/i18n/en/app.json
This PR add the cancel genuine check flow to the sync onboarding
https://user-images.githubusercontent.com/29443638/191043189-411d9ca6-b2fd-4a01-b475-ca335cb070bb.mp4
https://user-images.githubusercontent.com/29443638/191241774-a758b32b-5b7d-4311-b4f7-80fcc1cfe5d0.mp4
> add cancel genuine check flow

- .changeset/tiny-plants-divide.md
- libs/ui/packages/native/src/components/Icon/CryptoIcon.tsx
- libs/ui/packages/native/storybook/stories/Icon/CryptoIcons.stories.tsx
- libs/ui/packages/react/src/components/asorted/Icon/CryptoIcon.tsx
- libs/ui/packages/react/src/components/asorted/Icon/CryptoIcons.stories.tsx
Improvements for the crypto icons library for Desktop and Mobile
- **Impacted projects**: `@ledgerhq/ui` 
- **Linked resource(s)**: [LIVE-3550] 
https://user-images.githubusercontent.com/112866305/190601863-66eb53d9-010b-4098-b391-aae5fb0898cb.mov
https://user-images.githubusercontent.com/112866305/190601878-21dd99e4-b8b0-4e58-95a0-efaeb8ecad7c.mov
Launch StoryBook on Both Mobile and Desktop
[LIVE-3550]: https://ledgerhq.atlassian.net/browse/LIVE-3550?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> support(Improvments): Improvements for the crypto icons library

- .changeset/poor-books-rest.md
- apps/ledger-live-desktop/static/i18n/en/app.json
- apps/ledger-live-mobile/src/locales/en/common.json
Update error message when trying to send NFTs with LNS
- **Impacted projects**: `live-desktop` `live-mobile` 
- **Linked resource(s)**: [LIVE-2725] 
Try send NFT with Nano S or S Plus
[LIVE-2725]: https://ledgerhq.atlassian.net/browse/LIVE-2725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> support(SendNFT):  Update error message when trying to send NFTs with LNS

- apps/ledger-live-desktop/src/renderer/components/FirebaseFeatureFlags.tsx
- apps/ledger-live-desktop/src/renderer/screens/settings/SettingsSection.jsx
- apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/FeatureFlagsButton.tsx
- Easier visualisation of which flags are enabled/disabled
- Easier visualisation of which flags are locally overriden
- More compact UI
- Search input
- Easy toggle enabled/disabled
- "Add a missing flag" input for flags that are not explicited in the "default flags" list
- Pretty printing of flag value JSON
- **Linked resource(s)**: [FAT-435] 
https://user-images.githubusercontent.com/91890529/191305589-c426c6ef-163f-41dc-9639-a479bfcf8a6e.mov
[FAT-435]: https://ledgerhq.atlassian.net/browse/FAT-435?atlOrigin=eyJpIj …
> LLD Feature flag interface improvements

- README.md
- apps/ledger-live-mobile/README.md
I update the readme because some external devs wasn't happened to make ios working with the help of readme smoothly
- **Impacted projects**: `readme` 
> update readme info for devs

- apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/Welcome/Carousel.tsx
This PR refacto e2e fix on the onboarding carousel
CI should be green
> Fix flaky e2e test on onboarding

- libs/ledger-live-common/src/bot/index.ts
- libs/ledger-live-common/src/bot/types.ts
- tools/actions/composites/bot/action.yml
This adds a minimal report.json file that is exported on the CI and uploaded as separate "assets" on github.
The goal is to accumulate these JSON reports in order to do more long term analysis BETWEEN two successive runs or even better among all the runs of a period.
At the moment, we have individual bot runs and individuals bot report and it's not possible to automatically compare the runs, we have to do this work manually at the moment to see what are the "difference" or what is the general "coverage" of our tests (since ONE bot run is possibly "partial" we have to consider bot runs as a whole, for instance we want to see if a given mutation was getting run during a period of 1 MONTH, etc..). With this idea in mind, we could be able to refine our "coverage" automatically generated …
> bot: add a minimal report json exported in the CI

- .changeset/polite-spies-melt.md
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/Rates/Countdown.jsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/Rates/index.jsx
Fixing color title
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-3846
> fix: add swap title color LIVE-3846

- apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/Welcome/Carousel.tsx
- libs/ledger-live-common/src/env.ts
This PR use getEnv instead of process.env in the carousel
Green CI
> add get env to carousel

- apps/ledger-live-mobile/src/screens/Account/index.tsx
Fix earn section, by destructuring actions as it should have been done
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-3870
- 
> Bugfix / LIVE-3870 - Fix earn section by destructuring actions

- apps/ledger-live-desktop/src/renderer/families/ethereum/GasLimitField.jsx
- apps/ledger-live-desktop/src/renderer/families/ethereum/MaxBaseFeeField.jsx
- apps/ledger-live-desktop/src/renderer/families/ethereum/PriorityFeeField.jsx
- apps/ledger-live-desktop/src/renderer/families/ethereum/SelectFeeStrategy.jsx
This PR is for addressing comments from discussion in [PR-1301](https://github.com/LedgerHQ/ledger-live/pull/1301)
> Address PR-1301 comments

- libs/ledger-live-common/src/families/elrond/specs.ts
on elrond bot specs, the minimalAmount is way too low and create error on the bot runs. this should fix it.
> bot: elrond: increase minAmount

- .changeset/twelve-pianos-shop.md
- apps/ledger-live-desktop/static/i18n/en/app.json
- apps/ledger-live-mobile/src/locales/en/common.json
- libs/ledger-live-common/src/families/hedera/api/network.ts
- libs/ledger-live-common/src/families/hedera/errors.ts
This PR will appease this error that some users are facing when trying to add an account:
- https://discord.com/channels/885256081289379850/922904577903317033/1004652978839490620
- https://discord.com/channels/885256081289379850/922904577903317033/1013769973627363389
The `AccountBalanceQuery` that happens during the synchronization step (in the add account flow) can fail if ...
1. ... a scheduled mainnet update is happening
2. ... nodes are unavailable to process the request due to the load of transactions that are being processed
Before this PR, an ambiguous error message would get thrown at the user (shown in the discord links). This PR will catch that potential failure and show a more user friendly error message.
- **Impacted projects**: `Live Common`, `Live Desktop`, and `Live Mobile` …
> TECSUPPORT-1349 [Hedera] User-friendly error message for network error

- apps/ledger-live-mobile/.env.android.prerelease
- apps/ledger-live-mobile/.env.ios.prerelease
fixes a dumb mistake that was making the LLM prerelease sending error report to the release project on Sentry. (minor problem)
- **Impacted projects**: `llm` prerelease 
- **Linked resource(s)**: LIVE-3609 
> LLM: Fixes the Sentry DSN of prerelease to point to correct proj

- .github/workflows/bot-cardano-silicium.yml
- .github/workflows/build-desktop.yml
- .github/workflows/build-mobile.yml
Backport of https://github.com/LedgerHQ/ledger-live/commit/4798caaaca07f4c12a10147dfd20f7cb74a84a40 that's required for CI to create builds.
> Cherry-pick 4798caa

- tools/github-bot/src/tools.ts
Needed to take advantage of the Github revert PR feature.
See: https://github.com/LedgerHQ/ledger-live-issues/issues/34
> ci: allow revert branches

- tools/github-bot/src/tools.ts
it should fixes this situation: https://github.com/LedgerHQ/ledger-live/pull/1445#issuecomment-1265459818
where dependabot PR is getting auto closed by our own bot
> Allow dependabot to create PRs

- apps/ledger-live-desktop/src/sentry/install.js
- apps/ledger-live-mobile/index.js
Add more ignored cases into sentry implementation on light of recent spamming incidents.
- **Impacted projects**: `sentry` 
> Add more ignored cases into sentry implementation

- .changeset/brown-experts-agree.md
- apps/ledger-live-desktop/src/generic.test.ts
- libs/ledger-live-common/src/__tests__/environment.test.ts
- libs/ledgerjs/packages/cryptoassets/README.md
- libs/ledgerjs/packages/cryptoassets/src/abandonseed.ts
Introduce tests to ensure we define abandonseed values for coin we support
necessary to fix ETC swap support
doc: https://ledgerhq.atlassian.net/wiki/spaces/WALLETCO/pages/3870425637/How+to+maintain+abandonseed.ts
- **Impacted projects**: LLD/LLM 
- **Linked resource(s)**: LIVE-3963 
> Introduce tests to ensure we define abandonseed values for coin we support

- .changeset/orange-maps-walk.md
- libs/ledger-live-common/src/__tests__/families/bitcoin/wallet-btc/xpub.syncing.integration.test.ts
- libs/ledger-live-common/src/families/bitcoin/account.ts
- libs/ledger-live-common/src/families/bitcoin/bech32m.ts
- libs/ledger-live-common/src/families/bitcoin/bridge/js.ts
- libs/ledger-live-common/src/families/bitcoin/bridge/mock.ts
- libs/ledger-live-common/src/families/bitcoin/js-getFeesForTransaction.ts
- libs/ledger-live-common/src/families/bitcoin/js-synchronisation.ts
- libs/ledger-live-common/src/families/bitcoin/logic.ts
- libs/ledger-live-common/src/families/bitcoin/presync.ts
- libs/ledger-live-common/src/families/bitcoin/specs.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/crypto/base.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/crypto/bip32.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/crypto/bitcoincash.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/crypto/factory.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/crypto/litecoin.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/crypto/types.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/crypto/zec.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/crypto/zen.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/explorer/index.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/pickingstrategies/CoinSelect.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/pickingstrategies/DeepFirst.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/pickingstrategies/Merge.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/storage/index.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/utils.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/utils/eventemitter.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/wallet.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/xpub.ts
Cleanup & fix "ts-ignore" and lint warning in watllet-btc
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-2750
> LIVE-2750 Wallet btc code cleanup

- apps/ledger-live-mobile/src/components/Nft/AddNewItemList.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
Add new button
- **Linked resource(s)**: [LIVE-3966] 
https://user-images.githubusercontent.com/112866305/193618820-5f22e2fe-f82e-4b85-ae63-0e8ae8fc9321.mp4
[LIVE-3966]: https://ledgerhq.atlassian.net/browse/LIVE-3966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✨ feat(Add): Add new button

- .changeset/honest-mails-watch.md
- libs/ui/packages/native/src/components/Layout/List/VerticalTimeline/TimelineIndicator.tsx
- libs/ui/packages/native/src/components/Layout/List/VerticalTimeline/TimelineItem.tsx
- libs/ui/packages/native/src/components/Layout/List/VerticalTimeline/index.tsx
- libs/ui/packages/native/src/components/Layout/List/index.ts
- libs/ui/packages/native/storybook/stories/Layout/List/VerticalTimeline.stories.tsx
- libs/ui/packages/native/storybook/stories/index.ts
Extract the new vertical timeline component made in the sync onboarding PR (see https://github.com/LedgerHQ/ledger-live/pull/330) to be reuse in other PRs.
- **Impacted projects**: `native-ui` 
- **Linked resource(s)**: https://github.com/LedgerHQ/ledger-live/pull/330 
N/A, see proper slack channels.
> Add vertical timeline component from sync onboarding

- .changeset/twenty-pumpkins-shop.md
- apps/ledger-live-desktop/src/renderer/modals/SettingsAccount/AccountSettingRenderBody.jsx
- apps/ledger-live-desktop/static/i18n/en/app.json
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/AccountSettings/AdvancedLogs.tsx
Add warning on Advanced logs for xpub sharing
- **Impacted projects**: `live-mobile` `live-desktop` 
- **Linked resource(s)**: [LIVE-2183] 
https://user-images.githubusercontent.com/112866305/190199065-9944fe36-78fe-498a-a144-03a9e1d43244.mp4
Go to Accounts > Account > Account Settings > Advanced Logs
[LIVE-2183]: https://ledgerhq.atlassian.net/browse/LIVE-2183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> support(AdvancedLogs): Add warning on Advanced logs for xpub sharing

- .changeset/cold-papayas-sell.md
- apps/ledger-live-desktop/TERMS.es.md
- apps/ledger-live-desktop/TERMS.fr.md
- apps/ledger-live-desktop/TERMS.md
- apps/ledger-live-desktop/src/config/urls.js
Terms and Privacy Policy urls to update on LLD
- **Linked resource(s)**: [LIVE-3795] 
https://user-images.githubusercontent.com/112866305/192249207-983fdd1d-63ef-4e00-9f49-99eaa5f03cc5.mov
Onboarding > change language > test links
[LIVE-3795]: https://ledgerhq.atlassian.net/browse/LIVE-3795?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> support(URLs): LLD - Terms and Privacy Policy urls to update

- apps/ledger-live-mobile/src/components/Nft/AddNewItemList.tsx
- apps/ledger-live-mobile/src/components/Nft/NftList.tsx
- apps/ledger-live-mobile/src/components/Nft/NftListItem.tsx
- apps/ledger-live-mobile/src/screens/Account/NftCollectionsList.tsx
- apps/ledger-live-mobile/src/screens/Nft/WalletNftGallery/index.tsx
FlatList with NFTs and Add new button
- **Linked resource(s)**: [LIVE-3969] 
https://user-images.githubusercontent.com/112866305/194025781-342b81b0-1625-42d6-87da-9ac924219235.mp4
[LIVE-3969]: https://ledgerhq.atlassian.net/browse/LIVE-3969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✨ FlatList with NFTs and Add new button

- apps/ledger-live-mobile/.eslintrc.js
- apps/ledger-live-mobile/src/config/urls.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Nft/NftGallery/NftGalleryEmptyState.tsx
- apps/ledger-live-mobile/src/screens/Nft/WalletNftGallery/index.tsx
Handle nft gallery list empty state + bonus fix Link eslint for project
https://user-images.githubusercontent.com/89014981/194067827-18f18226-5698-4870-857c-0b9fe86758f6.mp4
> Feat/LIVE-3670 - Nft gallery list empty state

- apps/ledger-live-mobile/src/screens/Nft/WalletNftGallery/index.tsx
✨ Sorted List
- **Linked resource(s)**: [LIVE-3965] [LIVE-3964] 
[LIVE-3965]: https://ledgerhq.atlassian.net/browse/LIVE-3965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-3964]: https://ledgerhq.atlassian.net/browse/LIVE-3964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✨ Sorted List

- .changeset/few-books-reflect.md
- apps/ledger-live-mobile/src/screens/Onboarding/OnboardingQuizItem.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/newDeviceInfo.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/scenes/Intro.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/scenes/QuizzFinal.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/scenes/RecoveryPhrase.tsx
Accents were cropped on the Onboarding carousel
- **Linked resource(s)**: [LIVE-2675] 
Do Onboarding Flow in French
[LIVE-2675]: https://ledgerhq.atlassian.net/browse/LIVE-2675?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> support(UI-Improvment): Accents are cropped on the Onboarding carousel

- apps/ledger-live-mobile/src/components/Nft/NftListItem.tsx
Handle nft gallery list navigation too nft viewer page (and back)
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-3680?atlOrigin=eyJpIjoiNmYyNGU0ZjRlMTkzNDFkOTkwYjk2YmRiYzdlYTgwNzAiLCJwIjoiaiJ9
Uploading Screen_Recording_20221005-180511_LL [DEV].mp4…
> Feat/LIVE-3680 + LIVE-3723 - Handle nft gallery list navigation too nft viewer page (and back)

- .changeset/loud-zoos-scream.md
- libs/ui/packages/native/src/components/Layout/List/VerticalTimeline/TimelineIndicator.tsx
- libs/ui/packages/native/src/components/Layout/List/VerticalTimeline/TimelineItem.tsx
- libs/ui/packages/native/src/components/Layout/List/VerticalTimeline/index.tsx
- libs/ui/packages/native/storybook/stories/Layout/List/VerticalTimeline.stories.tsx
**Now the items inside the `VerticalTimeline` component can have a dynamic height and the component will animate automatically to fit them.**
It also removes the need to always render the items even when they are not active so it should solve some issues & remove complexity in the use of this component (for instance the component are unmounted when they are invisible so no need to pause/start some logic when the visibility state changes)
- **Impacted projects**: `native-ui` 
https://user-images.githubusercontent.com/91890529/194273852-5d728624-e35b-4291-8478-a56c982a05b0.mp4
_Pull Requests must pass the CI and be …
> native-ui: VerticalTimeline dynamic item height capability

- apps/ledger-live-mobile/src/actions/settings.ts
- apps/ledger-live-mobile/src/components/Nft/NftImage.tsx
- apps/ledger-live-mobile/src/components/Nft/NftList.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/WalletTabNavigator.tsx
- apps/ledger-live-mobile/src/components/WalletTabNavigatorTabBar.tsx
- apps/ledger-live-mobile/src/reducers/settings.ts
Save wallet navigator last visited tab in store and use it + memoize wallet tab tab bar
https://user-images.githubusercontent.com/89014981/194527805-16571388-7e34-4c3b-be45-4165febd96ea.mp4
> Feat/LIVE-3669 - Nft gallery - Save wallet navigator last visited tab in store and use it

- apps/ledger-live-mobile/src/families/polkadot/AccountBalanceSummaryFooter.tsx
Fix buggy scrollview inside polkadot account balance summary
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-3989
> Bugfix / LIVE-3989 - Fix buggy scrollview inside polkadot account balance summary

- .changeset/chilled-rats-fold.md
- apps/ledger-live-desktop/src/renderer/components/CustomImage/ImageCropper.tsx
- apps/ledger-live-desktop/src/renderer/drawers/NFTViewerDrawer/ExternalViewerButton.jsx
- apps/ledger-live-desktop/src/renderer/hooks/useNftLinks.js
- apps/ledger-live-desktop/src/renderer/screens/customImage/index.tsx
This PR fix: 
1. the error when importing a wrong pictures 
2. the NFT drawers redirection when selection an NFT for CLS
3. The cropping
4. 
- **Linked resource(s)**: [FAT-463] [FAT-465] [FAT-467] 
Ping me for the demo
User should be able to upload a valid picture after an error in the CLS
[FAT-465]: https://ledgerhq.atlassian.net/browse/FAT-465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAT-463]: https://ledgerhq.atlassian.net/browse/FAT-463?atlOrigin=eyJpIjoiNWRkNTl …
> fix CLS: import pictures, NFT drawers redirection and cropping

- .changeset/lemon-cups-greet.md
- apps/ledger-live-desktop/src/renderer/screens/market/index.tsx
In Market Click 'Starred Assets' button should clear search
- **Linked resource(s)**: [LIVE-1389] 
https://user-images.githubusercontent.com/112866305/192817201-4b2a018d-22d6-46d5-8316-af820ecbe511.mov
[LIVE-1389]: https://ledgerhq.atlassian.net/browse/LIVE-1389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bugfix(Market): Click 'Starred Assets' button should clear search

- apps/ledger-live-mobile/src/screens/Nft/WalletNftGallery/index.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/GenerateMockAccountsNFTs.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/index.tsx
- libs/ledger-live-common/src/mock/account.ts
- libs/ledger-live-common/src/mock/fixtures/nfts.ts
- libs/ledger-live-common/src/nft/helpers.ts
Mock NFT Gallery with adding entry in Debug 
https://user-images.githubusercontent.com/112866305/194583677-463a54b9-15a6-484f-b2eb-43baedb9a83c.mp4
> ✨ FEAT: Mock NFT Gallery V0

- apps/ledger-live-mobile/src/components/RootNavigator/WalletTabNavigator.tsx
- apps/ledger-live-mobile/src/components/WalletTabNavigatorTabBar.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Portfolio/Header.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/index.tsx
Static header in top of wallet tab navigator tabs
- **Linked resource(s)**: `` https://www.figma.com/file/kbcqFhPS0O1GQ4zPoXpGJa/LLM-%2F-Wallet?node-id=9687%3A162840 https://ledgerhq.atlassian.net/browse/LIVE-4050
https://user-images.githubusercontent.com/89014981/194864561-dfe8739b-030c-4c2a-98ff-1f1e5e4ee7e0.mp4
> Feat / LIVE-4050 - Static header nft gallery

- apps/ledger-live-mobile/src/components/Nft/AddNewItemList.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Nft/NftGallery/NftGalleryEmptyState.tsx
- apps/ledger-live-mobile/src/screens/Nft/NftGallery/ReceiveNFTsModal.hook.ts
- apps/ledger-live-mobile/src/screens/Nft/NftGallery/ReceiveNFTsModal.tsx
Add NFT from the Empty State page or the NFT Gallery 
- Add Drawer
- Add redirection
- Add Analytics
- **Linked resource(s)**: [LIVE-3830] 
https://user-images.githubusercontent.com/112866305/194863407-17a96804-49f7-491b-bad6-8ea1264ee011.mp4
[LIVE-3830]: https://ledgerhq.atlassian.net/browse/LIVE-3830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✨ FEAT : Add NFT from the Empty State page or the NFT Gallery 

- .changeset/wicked-ways-hang.md
- apps/ledger-live-desktop/DEEPLINK.md
- apps/ledger-live-desktop/src/renderer/hooks/useDeeplinking.js
- apps/ledger-live-mobile/deep-links-test-page.html
- apps/ledger-live-mobile/docs/linking.md
- apps/ledger-live-mobile/src/index.tsx
- apps/ledger-live-mobile/src/navigation/useDeepLinking.ts
Replace manager deeplink with myledger
- **Impacted projects**: `live-desktop` `live-mobile` 
- **Linked resource(s)**: [LIVE-3829] 
[LIVE-3829]: https://ledgerhq.atlassian.net/browse/LIVE-3829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bugfix♻️ Replace manager deeplink with myledger

- libs/ledger-live-common/src/bot/index.ts
- libs/ledger-live-common/src/bot/types.ts
working on https://github.com/LedgerHQ/ledger-live/pull/1494 made me realised i needed to know the 'other mutations' for a given spec. the error logs will also be more precise with the contextual test. finally a bonus adding a link to doc in individual reports.
> Improve bot reports to add needed field for the 'super report'

- apps/ledger-live-desktop/src/index.js
- apps/ledger-live-desktop/src/main/db/index.js
- apps/ledger-live-desktop/src/renderer/analytics/segment.js
- apps/ledger-live-desktop/src/renderer/components/AccountDistribution/index.jsx
- apps/ledger-live-desktop/src/renderer/components/AnimatedWave.jsx
- apps/ledger-live-desktop/src/renderer/components/AnnouncementProviderWrapper.jsx
- apps/ledger-live-desktop/src/renderer/components/AssetDistribution/Row.jsx
- apps/ledger-live-desktop/src/renderer/components/Carousel/helpers.jsx
- apps/ledger-live-desktop/src/renderer/components/ConnectTroubleshooting.jsx
- apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/Welcome/Carousel.tsx
- apps/ledger-live-desktop/src/renderer/components/TopBar/ActivityIndicator.jsx
- apps/ledger-live-desktop/src/renderer/drawers/OperationDetails/index.jsx
- apps/ledger-live-desktop/src/renderer/init.jsx
- apps/ledger-live-desktop/src/renderer/screens/WalletConnect/Provider.jsx
- apps/ledger-live-desktop/src/renderer/screens/market/MarketDataProviderWrapper.tsx
- apps/ledger-live-desktop/src/renderer/screens/settings/sections/About/index.jsx
- apps/ledger-live-desktop/src/renderer/storage.js
This PR removes the usage of `process.env` for the `PLAYWRIGHT_RUN` variable as it's used as a boolean and not using `getEnv` will parse it as a string instead.
> Bugfix - Update all process.env.PLAYWRIGHT_RUN to use getEnv

- libs/ledger-live-common/scripts/build-ts.mjs
> Fix ts rework error

- .changeset/empty-balloons-crash.md
- libs/ledger-live-common/src/market/MarketDataProvider.tsx
_LLC fix potential issue on MarketProvider chartData_
- **Impacted projects**: `ledger-live-common` `ledger-live-desktop` `ledger-live-mobile` 
- **Linked resource(s)**: [LIVE-3988] 
[LIVE-3988]: https://ledgerhq.atlassian.net/browse/LIVE-3988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-3988 -  LLC fix potential issue on MarketProvider chartData

- apps/ledger-live-mobile/src/components/Nft/NftListItem.tsx
- apps/ledger-live-mobile/src/components/Skeleton.tsx
Add props as Styled Component in Skelleton
- **Linked resource(s)**: [LIVE-3828]
[LIVE-3828]: https://ledgerhq.atlassian.net/browse/LIVE-3828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ♻️  Skelleton as Styled

- .changeset/proud-teachers-clean.md
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/Rates/CentralisedRate.jsx
Transparent text in swap text light mode
- **Linked resource(s)**: ``
LLD - Swap exchange rate not visible in light mode https://ledgerhq.atlassian.net/browse/LIVE-4181
> fix: text not visible light mode (release)

- .changeset/lemon-clouds-tease.md
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Market/EmptyStarredCoins.tsx
- apps/ledger-live-mobile/src/screens/Market/MarketRowItem.tsx
- apps/ledger-live-mobile/src/screens/Market/SortBadge.tsx
- apps/ledger-live-mobile/src/screens/Market/index.tsx
LLM - iOS/Android - Market General Layout polish
- **Linked resource(s)**: [LIVE-2096] 
https://user-images.githubusercontent.com/112866305/191550046-892db5af-0265-4dd9-bea4-3883a6b0e6ec.mp4
Go To Market Page
[LIVE-2096]: https://ledgerhq.atlassian.net/browse/LIVE-2096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> support(UI): LLM - iOS/Android - Market General Layout polish

- .changeset/silly-ways-marry.md
- .github/workflows/bot-cardano-silicium.yml
- apps/ledger-live-mobile/ios/Podfile.lock
- libs/ledger-live-common/package.json
- libs/ledger-live-common/src/families/cardano/specs.ts
- pnpm-lock.yaml
Update cardano package because new nano app is not compatible
- **Linked resource(s)**: `LIVE-4185` 
> LIVE-4185: update cardano-hw-app

- libs/ledger-live-common/src/families/stellar/api/horizon.ts
Not sure if it will fix the issue but I found a place that it wasn't cover by the hacky try catch we did.
Until we have a payload or a way to reproduce the 503 I can't fully resolve the ticket.
`next()` is an API call but was never cover by the try catch so it may be the cause of returning undefined. but still not sure !
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-3454 
> stellar fetch op wasn't full cover by try catch

- apps/ledger-live-mobile/ios/Podfile.lock
- pnpm-lock.yaml
https://github.com/LedgerHQ/ledger-live/commit/2c3d6b53eaaefc0f2ab766addf8584d2f83a5eb9 shouldn't have changed some dependencies
Revert pnpm lock changes from #1558
> Revert pnpm lock changes from #1558

- apps/ledger-live-desktop/src/renderer/screens/customImage/index.tsx
This PR fix the next button in LLD custom image
- **Linked resource(s)**: [FAT-532] 
/w me
[FAT-532]: https://ledgerhq.atlassian.net/browse/FAT-532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix custom image next button

- package.json
- pnpm-lock.yaml
- tools/actions/turborepo-gh-cache/build/server.js
- tools/actions/turborepo-gh-cache/src/server.ts
- turbo.json
The following logs does not make sense:
```
@ledgerhq/live-common:build: cache miss, executing fe088565818d5462
```
```
Got a GET request /v8/artifacts/fe088565818d5462
Got a POST request /v8/artifacts/events
Received 0 of 10416076 (0.0%), 0.0 MBs/sec
Got a POST request /v8/artifacts/events
Received 0 of 10416076 (0.0%), 0.0 MBs/sec
Received 0 of 10416076 (0.0%), 0.0 MBs/sec
Received 0 of 10416076 (0.0%), 0.0 MBs/sec
Received 2027468 of 10416076 (19.5%), 0.4 MBs/sec
Received 2027468 of 10416076 (19.5%), 0.3 MBs/sec
Received 6221772 of 10416076 (59.7%), 0.8 MBs/sec
Received 10416076 of 10416076 (100.0%), 1.3 MBs/sec
Cache Size: ~10 MB (10416076 B)
C:\Windows\System32\tar.exe -z -xf C:/actions-runner/_work/_temp/20700b1d-11fa-497e-b3d8-e210b9748c96/cache.tgz -P -C …
```
> Attempt to fix the turborepo caching server

- .changeset/slow-singers-grab.md
- apps/ledger-live-mobile/src/analytics/segment.ts
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/scenes/ConnectNano.tsx
_LLM analytics for reborn update._
- **Linked resource(s)**: [LIVE-4186] 
[LIVE-4186]: https://ledgerhq.atlassian.net/browse/LIVE-4186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-4186 - LLM analytics for reborn update

- .changeset/warm-parents-agree.md
- apps/ledger-live-mobile/src/components/FirmwareUpdateBanner.tsx
- apps/ledger-live-mobile/src/screens/Manager/AppsScreen.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/ReadOnly/index.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/index.tsx
_Fixes an issue on firmware update banner on LLM_
- **Linked resource(s)**: [LIVE-4047] 
<details>
<summary>Screenshot</summary>
</details>
[LIVE-4047]: https://ledgerhq.atlassian.net/browse/LIVE-4047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-4047 - LLM - fix Firmware Banner issue

- libs/ledger-live-common/package.json
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/crypto/zec.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/crypto/zen.ts
- libs/ledger-live-common/src/families/solana/bridge/mock-data.ts
Running pnpm common prettier doesn't work because it was still configured to run on the `cli` part in LLC.
Update the conf + update a few files where prettier wasn't run yet.
- **Linked resource(s)**: n/a
> [support] cleanup prettier conf in live common

- .changeset/loud-olives-give.md
- apps/ledger-live-mobile/src/components/FabActions/hooks/useAssetActions.tsx
Asset Receive Quick action Improvement
- **Linked resource(s)**: [LIVE-3715] 
https://user-images.githubusercontent.com/112866305/192789811-56964269-aba0-4475-9f4e-23a897f5734c.mp4
[LIVE-3715]: https://ledgerhq.atlassian.net/browse/LIVE-3715?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> support(QuickActions): Asset Receive Quick action Improvement

- .changeset/green-cups-cover.md
- apps/ledger-live-mobile/src/screens/Onboarding/steps/welcome.tsx
LLM - Onboarding - Terms and Privacy urls should not overflow screen in the small screen
- **Linked resource(s)**: [LIVE-3897] 
https://user-images.githubusercontent.com/112866305/192478118-fd07d81d-393e-4070-b90a-948685944ebf.mp4
[LIVE-3897]: https://ledgerhq.atlassian.net/browse/LIVE-3897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bugfix(CroppedText): LLM - Onboarding - Terms and Privacy urls should not overflow screen in the small screen

- .github/workflows/bot-mere-denis.yml
- .github/workflows/bot-mooncake.yml
- .github/workflows/bot-silicium.yml
Now that the report get also sent to PR as a comment, we can move on to this: ["ledger live bot"](https://github.com/LedgerHQ/ledger-live/wiki/LLC:bot) will be trigger-able directly on Github Actions and we will be able to chose any branch – as a future replacement to current hardcoding the branch names to trigger the bot.
there is still the conventional `support/bot-<name>-*` naming if you need a "per commit" systematic run behavior. but the new way to do will be to run on demand.
We prefer for now to split each bot into a dedicated github actions. for a few reasons:
- github don't allow to dynamically lookup in a secret. The fact we do this per `SEED{n}`.
- each bot is used with special behavior for each kind of bot. notably the fact it have a name (eg Mere Denis, Phosphore,..), but …
> Allow bots to be triggered to run on a branch

- apps/ledger-live-mobile/ios/Podfile.lock
- pnpm-lock.yaml
`pnpm i` is currently failling on `main` because of a corrupt resolution:
```
github.com/bitcoinjs/bip39/d8ea080a18b40f301d4e2219a2991cd2417e83c2:
resolution: {commit: d8ea080a18b40f301d4e2219a2991cd2417e83c2, repo: git+ssh://git@github.com/bitcoinjs/bip39.git, type: git}
name: bip39
version: 3.0.3
dependencies:
'@types/node': 11.11.6
create-hash: 1.2.0
pbkdf2: 3.1.2
randombytes: 2.1.0
dev: false
```
See https://github.com/LedgerHQ/ledger-live/actions/runs/3266312173/jobs/5369944337
This was introduced by latest merge of the `release` branch, starting from _pnpm-lock.yaml_ right before it and re-generating it again should solve the issue.
- **Impacted projects**: all 
Green CI, proving `pnpm i` is successful on all jobs.
>  Re-generate pnpm-lock.yaml for main

- .github/workflows/build-mobile.yml
Add a `NODE_OPTIONS: "--max-old-space-size=7168"` env var in CI LLM workflow for iOS builds similar to other places in the code.
- **Impacted projects**: N/A 
N/A
> Increase max space for LLM iOS in CI

- .changeset/quick-items-shave.md
- libs/ledger-live-common/src/apps/polyfill.ts
add plugins
- **Impacted projects**: `` llm & lld
- **Linked resource(s)**: `` ledger-asset-dapps
n/a
n/a
> support(llc): add plugins

- libs/ledger-live-common/src/bot/engine.ts
some coins, like Tezos, have one transaction generating more than one operation (e.g. REVEAL + OUT) this change the test to a more permissive one
```
OPERATIONS (66)
-0.000374 XTZ      REVEAL     opWrKvEALjrM2KTupNy7kCe5iccGbasJAMFXcJ7DaNJ5Km1JE8P 2022-10-19T19:27
-0.614935 XTZ      OUT        opWrKvEALjrM2KTupNy7kCe5iccGbasJAMFXcJ7DaNJ5Km1JE8P 2022-10-19T19:27
```
> Make bot generic tx test to not strictly expect op+1

- .changeset/sour-tables-cough.md
- apps/ledger-live-mobile/src/components/RootNavigator/ManagerNavigator.tsx
The dot to signal a new app update had a incorrect display condition - fixed it
- **Linked resource(s)**: [jira](https://ledgerhq.atlassian.net/browse/LIVE-4319)
> Fix: Live-4319 MyLedger tab logo dot condition

- .changeset/heavy-ducks-hide.md
- apps/ledger-live-mobile/src/components/SelectDevice2/index.tsx
This PR add margin to buy button in MyLedger
- **Linked resource(s)**: [FAT-543] 
[FAT-543]: https://ledgerhq.atlassian.net/browse/FAT-543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add margin to buy button in MyLedger

- libs/ledger-live-common/src/families/stellar/speculos-deviceActions.ts
Fixes this problem:
https://github.com/LedgerHQ/ledger-live/commit/e2da2d229c83a9a65fbdeafcf86ec183614d4eba#commitcomment-87426528
```
necessary accounts resynced in 560ms
▬ Stellar 4.0.0 on nanoS 2.1.0
→ FROM Stellar 3: 7.519 XLM (930ops) (GCO3UM5ZDTJ5S3EANZWDDMPSZMTO4OHBG3CAUYFXKW4T5WDTNORHQQT2 on 44'/148'/2') sep5#2 js:2:stellar:GCO3UM5ZDTJ5S3EANZWDDMPSZMTO4OHBG3CAUYFXKW4T5WDTNORHQQT2:sep5 (! sum of ops 7.5265378 XLM)  TokenAccount USDC: 5.3010801 USDC (10 ops)
max spendable ~6.019
★ using mutation 'move ~50% USDC asset'
→ TO Stellar 2: 2.7441 XLM (1055ops) (GAVHE2NH4SAMQ6VZL2M4CECK6JK4H4KETQ27PWHOVVUZ2V26PQBG2GYY on 44'/148'/1') sep5#1 js:2:stellar:GAVHE2NH4SAMQ6VZL2M4CECK6JK4H4KETQ27PWHOVVUZ2V26PQBG2GYY:sep5
✔️ transaction 
SEND 2.7144372 USDC
TO …
```
> Bot: stellar fix send of assets

- apps/ledger-live-mobile/src/components/Nft/NftListItem.tsx
- apps/ledger-live-mobile/src/components/WalletTab/CollapsibleHeaderFlatList.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Nft/NftGallery/ReceiveNFTsModal.tsx
- libs/ui/packages/native/src/components/Icon/CryptoIcon.tsx
Polishing Millestone 2 - NFT gallery
> 💄 Polishing Millestone 2 - NFT gallery

- libs/ledger-live-common/src/families/elrond/js-getTransactionStatus.ts
Elrond integ test was missing an amount required.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-3493 
> LIVE-3493 fix elrond empty amount

- .changeset/khaki-planes-love.md
- apps/ledger-live-desktop/static/i18n/en/app.json
- apps/ledger-live-mobile/src/locales/en/common.json
Typo on warning message in Advanced account settings
- **Impacted projects**: `live-mobile` `live-desktop` 
- **Linked resource(s)**: [LIVE-4307] 
[LIVE-4307]: https://ledgerhq.atlassian.net/browse/LIVE-4307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LL - Typo on warning message in Advanced account settings

- .pnpmfile.cjs
- pnpm-lock.yaml
- tools/metro-extra-config/index.js
- tools/metro-extra-config/package.json
We discovered that some devs have issues when building ledger-live-mobile through metro (`pnpm mobile start`) due to globally installed packages (for instance `@angular/cli` - which depends on `rxjs`).
It turns out that the following chain of events seems to happen:
- Some of our dependencies do not declare properly their deps (we knew that already - we just missed some)
- In that particular case, our custom resolution algorithm which uses [`@rnx-kit/metro-resolver-symlinks`](https://www.npmjs.com/package/@rnx-kit/metro-resolver-symlinks) will still resolve these packages if installed globally - likely due to the way pnpm creates the node_modules hierarchy
- `watchman` does not like that because the global pnpm store is outside the list of watched folders
- 💣 … 💥 
- Declare forcefully in …
> Guard against metro resolving global packages in LLM

- CONTRIBUTING.md
I added a link to the dev portal in the contributing file, as requested.
- **Impacted projects**: `` External devs
- **Linked resource(s)**: `` Issue R3PIC-313
No demo as it is only a minor documentation modification
> added link to dev portal

- libs/ledger-live-common/src/nft/helpers.test.ts
- libs/ledger-live-common/src/nft/helpers.ts
✅ Add firsts Tests for NFT Gallery
- **Impacted projects**: `live-mobile` `live-common` 
>  ✅ Add firsts Tests for NFT Gallery

- apps/ledger-live-mobile/src/components/Nft/AddNewItemList.tsx
- apps/ledger-live-mobile/src/components/Nft/NftListItem.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Nft/NftGallery/ReceiveNFTsModal.tsx
Pixel Polish Millestone v0
- **Linked resource(s)**: [LIVE-4400] 
[LIVE-4400]: https://ledgerhq.atlassian.net/browse/LIVE-4400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 💄Feat : Pixel Polishing Galery

- apps/ledger-live-desktop/CONTRIBUTORS.md
- apps/ledger-live-mobile/CONTRIBUTORS.md
- libs/ledger-live-common/CONTRIBUTORS.md
Credit where it's due. :slightly_smiling_face:
Thank you @jackthta!
- **Impacted projects**: all 
> [Hedera] Give some deserved credit

- apps/ledger-live-mobile/src/components/Nft/NftList.tsx
- apps/ledger-live-mobile/src/components/Nft/NftListItem.tsx
- apps/ledger-live-mobile/src/components/WalletTab/WalletTabNavigatorScrollManager.tsx
- apps/ledger-live-mobile/src/components/WalletTab/WalletTabNavigatorTabBar.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Nft/NftGallery/NftGalleryEmptyState.tsx
- apps/ledger-live-mobile/src/screens/Nft/NftGallery/ReceiveNFTsModal.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/PortfolioEmptyState.tsx
- libs/ui/packages/native/src/components/Tabs/Graph/index.tsx
Pixel polish on Nft list, nft list empty state (and copy update), portfolio empty state, wallet tab bar, portfolio graph card tabs,
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-4019
> Feat/LIVE-3665 - Nft gallery pixel polish2

- .github/workflows/bot-super-report.yml
- tools/actions/generate-bot-super-report/build/main.js
- tools/actions/generate-bot-super-report/logic.ts
the weekly bot report aggregate all the important data of the bot runs. it deserves to notify on #ledger-live instead of #ledger-live-bot (slack)
> bot weekly report to report to #ledger-live

- .changeset/ten-horses-check.md
- apps/ledger-live-desktop/src/internal/commands/index.js
- apps/ledger-live-desktop/src/internal/commands/waitForDeviceInfo.ts
- apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/Installing.tsx
- apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/steps/00-step-reset-device.tsx
- apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/steps/01-step-install-full-firmware.tsx
- apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/steps/02-step-flash-mcu.jsx
- apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/steps/02-step-flash-mcu.tsx
- apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/steps/02-step-updating.tsx
- apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/steps/03-step-confirmation.tsx
- apps/ledger-live-desktop/tests/models/FirmwareUpdateModal.ts
- apps/ledger-live-desktop/tests/specs/manager/firmwareupdate.spec.ts
On Firmware update that includes an update of the MCU, the language step was skipped.
I also took some time to migrate the firmware update components to TS 🏋️‍♀️
To run the associated playwright test: 
```
pnpm desktop test:playwright apps/ledger-live-desktop/tests/specs/manager/firmwareupdate.spec.ts
```
- **Linked resource(s)**: [FAT-574](https://ledgerhq.atlassian.net/browse/FAT-574?atlOrigin=eyJpIjoiNTg0NGU1ZmExNWM5NGE3N2JmMWViNjU4ZDdlZDFmMDUiLCJwIjoiaiJ9)
> Bugfix: FAT-574 LLD language fwm update

- libs/ledger-live-common/src/apps/support.ts
Set Polkadot minimum Nano app version to latest (15.9300.0)
- **Impacted projects**: n/a 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-4429
> LIVE-4429 Force Polkadot Nano app v15.9300.0

- .changeset/brave-shrimps-lie.md
- apps/ledger-live-mobile/src/components/Nft/NftLinksPanel.tsx
- apps/ledger-live-mobile/src/components/Nft/NftViewer.tsx
- apps/ledger-live-mobile/src/config/urls.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Discover/index.tsx
- apps/ledger-live-mobile/src/screens/Nft/NftCollection/index.tsx
- apps/ledger-live-mobile/src/screens/Nft/NftGallery/index.tsx
- apps/ledger-live-mobile/src/screens/Nft/NftInfoNotAvailable.tsx
- libs/ledger-live-common/src/featureFlags/defaultFeatures.ts
- libs/ledgerjs/packages/types-live/README.md
- libs/ledgerjs/packages/types-live/src/feature.ts
Disable NFT in iOS to be apple compliant.
Also it's require to add variable on firebase : `feature_disable_nft_ledger_market`
`feature_disable_nft_rarible_opensea`
`feature_disable_nft_send`
with value : 
```
{"enabled": true}
```
- **Impacted projects**: `live-common, live-mobile` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-4430 
https://user-images.githubusercontent.com/33897120/199937052-14e550bb-0052-40d1-a7d9-b5d7bc7998ca.mov
> LIVE-4430 feature ios disable nft FF

- .changeset/fuzzy-carrots-give.md
- apps/ledger-live-mobile/ios/Podfile.lock
- apps/ledger-live-mobile/package.json
- pnpm-lock.yaml
LLM - react-native updated to version 0.68.5 to fix android builds
> LLM - react-native updated to version 0.68.5 to fix android builds

- .changeset/long-gifts-kick.md
- apps/ledger-live-mobile/src/components/SelectDevice2/index.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
This PR add OTG Banner on LLM new device selection only on Android
- **Linked resource(s)**: [FAT-533] 
[FAT-533]: https://ledgerhq.atlassian.net/browse/FAT-533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add OTG Banner in the LLM device selection

- .changeset/breezy-pugs-tap.md
- .changeset/healthy-rivers-think.md
- .changeset/heavy-ducks-hide.md
- .changeset/honest-tools-smile.md
- apps/ledger-live-mobile/src/components/SelectDevice2/index.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
Some fixes/tweaks all required in the ticket [FAT-533]:
- Buy Ledger button direct redirection to buy screen
- Invert 2 options "Connect an existing Ledger" and "Set up a new Ledger"
- Pixel polish
- Change "keep your Ledger close" banner wording
- **Linked resource(s)**: [FAT-533] 
[FAT-533]: https://ledgerhq.atlassian.net/browse/FAT-533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAT-533]: https://ledgerhq.atlassian.net/browse/FAT-533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …
> Feat/fat 533 - New device selection product feedback

- libs/ledger-live-common/src/mock/fixtures/nfts.test.ts
- libs/ledger-live-common/src/mock/fixtures/nfts.ts
- libs/ledger-live-common/src/nft/helpers.test.ts
Add some new tests to already existing tests for live-common
- **Linked resource(s)**: [LIVE-4048] 
[LIVE-4048]: https://ledgerhq.atlassian.net/browse/LIVE-4048?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✅ Add some tests

- libs/ledger-live-common/src/families/bitcoin/bridge/mock.ts
- libs/ledger-live-common/src/families/bitcoin/js-getTransactionStatus.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/crypto/base.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/crypto/bitcoin.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/crypto/types.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/xpub.ts
- Improved calculation for BTC and altcoins Dust limit
- **Linked resource(s)**: `-` 
> Improved dust limit computation for BTC and BTC Alts

- apps/ledger-live-mobile/e2e/bridge/client.js
- apps/ledger-live-mobile/src/colors.tsx
- apps/ledger-live-mobile/src/components/Nft/NftLinksPanel.tsx
- apps/ledger-live-mobile/src/components/Nft/NftViewer.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/BaseOnboardingNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/CustomBlockRouterNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/MainNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/NftNavigator.tsx
- apps/ledger-live-mobile/src/components/SelectDevice2/index.tsx
- apps/ledger-live-mobile/src/components/TranslatedError.tsx
- apps/ledger-live-mobile/src/components/ValidateSuccess.tsx
- apps/ledger-live-mobile/src/families/cosmos/DelegationFlow/02-Summary.tsx
- apps/ledger-live-mobile/src/families/ethereum/EditFeeUnitEthereum.tsx
- apps/ledger-live-mobile/src/families/ethereum/EthereumFeesStrategy.tsx
- apps/ledger-live-mobile/src/families/hedera/EditMemo.tsx
- apps/ledger-live-mobile/src/navigation/navigatorConfig.tsx
- apps/ledger-live-mobile/src/screens/Account/ListHeaderComponent.tsx
- apps/ledger-live-mobile/src/screens/Analytics/Allocation.tsx
- apps/ledger-live-mobile/src/screens/Discover/index.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/importAccounts.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/scenes/BaseStepperView.tsx
- apps/ledger-live-mobile/src/screens/OperationDetails/index.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricSections/Allocations.tsx
- libs/ledger-live-common/package.json
- libs/ledgerjs/packages/errors/src/deserializeError.test.ts
- libs/ledgerjs/packages/errors/src/helpers.ts
- libs/ui/packages/native/package.json
- pnpm-lock.yaml
This is where the non regression bugs and any kind of fixes will be done to centralise effort on stabilizing typescript in LLM.
ISO Prod
> Stabilize TS on LLM

- libs/ledger-live-common/src/families/bitcoin/wallet-btc/__tests__/xpub.getAddress.integration.test.ts
`xpub.getAddress.ts` is an integration. Renamed the file as `xpub.getAddress.integration.test.ts`
N/A
> xpub.getAddress.ts -> xpub.getAddress.integration.test.ts

- libs/ledger-live-common/src/families/polkadot/api/sidecar.ts
Follow-up of https://github.com/LedgerHQ/ledger-live/pull/1798 fixing a typo introducing a bug.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-4546 
> polkadot sidecar-update - fix typo

- .changeset/tasty-games-fly.md
- libs/ledger-live-common/src/families/polkadot/api/sidecar.ts
- libs/ledger-live-common/src/families/polkadot/api/sidecar.types.ts
Last minute change with high importance / very low impact, that would be most welcome in the release.
A Polkadot network upgrade is likely to break our integration in a near future, which we only identified during last days.
This change should allow forward-compatibility with upcoming changes from Polkadot, without it we may need a hotfix for Polkadot before next LLM version.
**Test plan** : non-reg only, Polkadot add any account with funds + sync + simple send (or any type of transaction)
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-4546
_Pull Requests must pass the CI and be …
> LIVE-4546 Polkadot sidecar compatibility update

- .changeset/metal-hotels-clean.md
- apps/ledger-live-desktop/src/config/languages.ts
_LLD - reactivate portuguese language_
- **Linked resource(s)**: [LIVE-4585] 
[LIVE-4585]: https://ledgerhq.atlassian.net/browse/LIVE-4585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-4585 - LLD - reactivate portuguese language

- apps/ledger-live-mobile/src/components/RootNavigator/WalletTabNavigator.tsx
- apps/ledger-live-mobile/src/screens/Nft/NftGallery/ReceiveNFTsModal.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/PortfolioEmptyState.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/index.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricSections/OperationsHistory.tsx
fix firmware banner glitch by changing flex=1 by flexGrow=1
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-4541?atlOrigin=eyJpIjoiMTg1NTU5YjIwMGRkNDM0OTg4NTUxZmU0MTI2Y2I1NWEiLCJwIjoiaiJ9
> Feat/LIVE-4541 - Nft gallery - UI glitch on update firmware banner

- libs/ledger-live-common/src/families/cosmos/logic.ts
- libs/ledger-live-common/src/families/cosmos/specs.ts
- libs/ledger-live-common/src/families/osmosis/specs.ts
Condition on spec of bot doesn't seems to be the right one, hope it will fix
> Specs cosmos fix reward

- .github/workflows/build-desktop.yml
- .github/workflows/build-mobile.yml
- .github/workflows/test-desktop.yml
- .github/workflows/test-mobile.yml
A recent addition makes the CI smarter by skipping mobile/desktop build/tests when not necessary.
Unfortunately job success is necessary to pass the "required status checks" and to be able to merge PRs.
- **Linked resource(s)**: `https://github.com/LedgerHQ/ledger-live-issues/issues/63` 
N/A
> Make the CI run dummy jobs to pass required status checks

- .github/workflows/build-desktop.yml
- .github/workflows/build-mobile.yml
- .github/workflows/test-desktop.yml
- .github/workflows/test-mobile.yml
Because right now the `is-affected` git checkout does not fetch the remote repository if the PR comes from a forked repo.
Ah and it makes the CI fail for forks 😢.
N/A
> tweak the is-affected CI checkout to handle forks

- apps/ledger-live-mobile/src/analytics/segment.ts
- apps/ledger-live-mobile/src/notifications/braze.ts
- apps/ledger-live-mobile/src/reducers/settings.ts
- apps/ledger-live-mobile/src/reducers/types.ts
- apps/ledger-live-mobile/src/screens/Settings/Notifications/index.tsx
Every notifications categories are enabled by default even when updating LL to 3.11
> Every notifications categories are enabled by default even when updating LL to 3.11

- .changeset/dry-bugs-grow.md
- libs/ledger-live-common/src/families/ethereum/prepareTransaction.ts
Fix wrong gast limit estimation for smart contract interactions
- https://ledgerhq.atlassian.net/browse/LIVE-4608 
- https://ledgerhq.atlassian.net/browse/LIVE-4621 
> [LIVE-4608][LIVE-4621] Bugfix - Fix gas limit estimation for token transactions

- libs/ledger-live-common/src/families/elrond/specs.ts
Add uncapped provider for elrond bot tests.
> uncapped provider for tests

- libs/ledger-live-common/src/families/elrond/specs.ts
- libs/ledgerjs/packages/cryptoassets/src/tokens.ts
Active stake check when undelegate.
> active stake check

- apps/ledger-live-mobile/src/components/Nft/HideNftDrawer.tsx
- apps/ledger-live-mobile/src/components/Nft/NftLinksPanel.tsx
- apps/ledger-live-mobile/src/components/Nft/NftList.tsx
- apps/ledger-live-mobile/src/components/Nft/NftListItem.tsx
- apps/ledger-live-mobile/src/components/Nft/NftViewer.tsx
- apps/ledger-live-mobile/src/screens/Nft/NftGallery/NftGalleryEmptyState.tsx
- apps/ledger-live-mobile/src/screens/Nft/NftGallery/ReceiveNFTsModal.tsx
- apps/ledger-live-mobile/src/screens/Nft/WalletNftGallery/index.tsx
📈 Track analytics 
- **Linked resource(s)**: [LIVE-4629] 
[LIVE-4629]: https://ledgerhq.atlassian.net/browse/LIVE-4629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 📈 LLM - LIVE-4629:  Track analytics On NFT Gallery

- libs/ledger-live-common/src/families/elrond/specs.ts
- libs/ledger-live-common/src/families/elrond/speculos-deviceActions.ts
Deactivate fee check for esdts.
> Deactive fee check for esdts

- apps/ledger-live-mobile/src/components/Nft/NftList.tsx
- apps/ledger-live-mobile/src/components/Nft/NftListItem.tsx
Nft list : 
- Fix nft amount, wrong number was used
- fix placeholder for empty name
- now we use collectionMetadata for nft collection name, no more empty collection 
- **Impacted projects**: ` live-mobile
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-4607?atlOrigin=eyJpIjoiZWIwZWRlMmYwMzE4NDJjZjhiZWZhM2Q0ZjlmZTE5MTAiLCJwIjoiaiJ9 https://ledgerhq.atlassian.net/browse/LIVE-4615?atlOrigin=eyJpIjoiZTljNzgwNjhlY2M2NDk1MzlhZTg0NmJlYjU3ZGE0NTkiLCJwIjoiaiJ9 https://ledgerhq.atlassian.net/browse/LIVE-4627?atlOrigin=eyJpIjoiMzRiYjAzZDYwYjU2NDQxY2JmNDY2MGM4MjUzYmY0MjUiLCJwIjoiaiJ9
_Pull Requests must pass the CI and be internally …
> Feat/LIVE-4627/LIVE-4607/LIVE-4615 - Wallet NFt Gallery misc display fixes

- .github/workflows/bot-carbon.yml
- .github/workflows/bot-mere-denis.yml
- .github/workflows/bot-mooncake.yml
- .github/workflows/bot-oxygen.yml
- .github/workflows/bot-phosphore.yml
- .github/workflows/bot-silicium.yml
- libs/ledger-live-common/src/bot/index.ts
this improve slack reporting by adding contexts on who run the bot and on which branch.
it also simplify the output to have less "noise" on slack.
> Refine bot Slack reporting

- apps/ledger-live-mobile/src/dynamicContent/brazeContentCard.ts
- apps/ledger-live-mobile/src/dynamicContent/dynamicContent.tsx
- apps/ledger-live-mobile/src/dynamicContent/types.ts
- apps/ledger-live-mobile/src/dynamicContent/useContentCards.ts
- apps/ledger-live-mobile/src/reducers/types.ts
- apps/ledger-live-mobile/src/screens/Portfolio/index.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/index.tsx
- libs/ui/packages/native/src/components/Cards/CardB/index.tsx
- libs/ui/packages/native/src/components/Cards/index.ts
- libs/ui/packages/native/src/components/index.ts
- libs/ui/packages/native/storybook/stories/Cards/Cards.stories.tsx
- libs/ui/packages/native/storybook/stories/Cards/descriptionsCards.ts
LLM Assets Page Content Cards
- **Impacted projects**: `live-mobile` `ui-native`
- **Linked resource(s)**: [LIVE-4478] 
[LIVE-4478]: https://ledgerhq.atlassian.net/browse/LIVE-4478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✨ LLM 📱 -  [FEAT] : LIVE-4478 : Asset Content Card

- .github/workflows/test-integration-pr.yml
- pnpm-lock.yaml
- tools/actions/live-common-affected/action.yml
- tools/actions/live-common-affected/build/main.js
- tools/actions/live-common-affected/package.json
- tools/actions/live-common-affected/src/main.ts
- tools/actions/live-common-affected/tsconfig.json
Every time changes are made in `live-common` source code, "integration tests" are very likely relevant to be re-executed so we can confirm no breaking changes are made. (see https://github.com/LedgerHQ/ledger-live/wiki/LLC:integration-Tests )
So far, it was only at the responsibility of every dev to have to manually trigger the integration tests and this was often forgotten. We didn't trigger it every single time because it's both super slow and also is flawky: we can't assume integration tests are 100% network stable (so we didn't made it a "mandatory run" on every commit). That said, PRs that modify critical parts of our codebases like changing a specific coin integration would benefit a lot to guarantee the integration tests are maintained working and are passing on the CI.
With this …
> Introduce 'test-integration-pr'

- .changeset/sixty-buckets-kiss.md
- .changeset/warm-dolphins-study.md
- libs/ledger-live-common/src/families/ethereum/__tests__/transaction.unit.test.ts
- libs/ledger-live-common/src/families/ethereum/modules/erc1155.ts
- libs/ledger-live-common/src/families/ethereum/modules/send.ts
- libs/ledger-live-common/src/families/ethereum/specs.ts
- libs/ledger-live-common/src/families/ethereum/transaction.ts
- libs/ledger-live-common/src/families/ethereum/types.ts
- pnpm-lock.yaml
Cherry pick of these 2 PRs:
https://github.com/LedgerHQ/ledger-live/pull/1913
https://github.com/LedgerHQ/ledger-live/pull/1931
> Cherry-pick Hotfix 🍒 🌶️ 🩹 

- .changeset/yellow-pens-study.md
- libs/ledger-live-common/src/__tests__/test-helpers/bridge.ts
- libs/ledger-live-common/src/families/solana/bridge.integration.test.ts
- libs/ledger-live-common/src/families/solana/js-prepareTransaction.ts
- libs/ledger-live-common/src/families/solana/logic.ts
Prevent Sol user to max send all SOL
> Prevent Sol user to max send all SOL

- apps/ledger-live-mobile/src/components/Carousel/CarouselCard.tsx
- libs/ui/packages/native/src/components/Cards/CardA/index.tsx
- libs/ui/packages/native/src/components/Cards/CardB/index.tsx
- libs/ui/packages/native/src/components/Cards/helper.tsx
HighLight text on Asset Content Card & Refact function
- **Impacted projects**: `live-mobile` `ui-native` 
> ⚡ HighLight text on Asset Content Card

- apps/ledger-live-mobile/src/components/Carousel/CarouselCard.tsx
- apps/ledger-live-mobile/src/dynamicContent/dynamicContent.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/index.tsx
Improve analytics on Content cards
`live-mobile:start:  INFO  TRACK event saved {"event": "contentcard_clicked", "properties": {"androidArchitecture": "381", "androidVersionCode": "381", "appLanguage": "en", "appVersion": "3.3.0 (381)", "campaign": "NjM3Y2UwZDBhYzMyN2ZmMTE0NmFmZTA5XyRfY2M9ZDYzYWNhMzEtOTA1Yi1mOGJlLWFiMjktMzI3OGMwMGVjNGI0Jm12PTYzN2NlMGQwYWMzMjdmZjExNDZhZmUwYiZwaT1jbXA=", "devicesCount": 0, "environment": "development", "firstConnectHasDeviceUpdated": null, "firstConnectionHasDevice": true, "language": "en", "link": "https://github.com/LedgerHQ/ledger-live/pull/1923", "notificationsAllowed": true, "notificationsBlacklisted": ["allowed", "transactions", "market", "announcement", "price"], "platformOS": …
> 📈 Improve analytics on Content cards

- .changeset/ninety-eggs-look.md
- .changeset/sour-snakes-fry.md
- apps/ledger-live-desktop/src/config/urls.js
- apps/ledger-live-desktop/src/renderer/components/DeviceAction/index.tsx
- apps/ledger-live-desktop/static/i18n/en/app.json
- libs/ledger-live-common/src/errors.ts
_LLD - Handle ECONNRESET error with better message_
> LIVE-3432 - LLD - Handle ECONNRESET error with better message

- .gitignore
- .vscode/launch.json
- apps/ledger-live-desktop/README.md
It's all in the title.
- **Impacted projects**: none 
- **Linked resource(s)**: n/a
> [support] Provide VSCode configs to debug Electron main and renderer threads

- .changeset/empty-books-listen.md
- libs/ledger-live-common/src/families/solana/api/chain/index.ts
This is a super naive mode on catch error from Solana node that are too frequent and poluate sentry logs with network error
> catch all solana error into network down

- .changeset/breezy-lamps-pull.md
- libs/ui/packages/icons/src/additionalIcons/Providers/CIC.svg
New provider icon (CIC) added to in IconsUI demonstrate PTX team how to add icons to the lib.
- **Impacted projects**: IconsUI
- **Linked resource(s)**: LIVE-4367
N/A
> New CIC icon (knowledge transmission with ptx team)

- .changeset/sharp-gorillas-turn.md
- apps/ledger-live-mobile/src/components/Nft/AddNewItemList.tsx
- apps/ledger-live-mobile/src/components/Nft/NftList.tsx
- apps/ledger-live-mobile/src/components/WalletTab/WalletTabNavigatorTabBar.tsx
- apps/ledger-live-mobile/src/screens/Nft/NftGallery/NftGalleryEmptyState.tsx
- apps/ledger-live-mobile/src/screens/Nft/NftGallery/ReceiveNFTsModal.hook.ts
- apps/ledger-live-mobile/src/screens/Nft/NftGallery/ReceiveNFTsModal.tsx
- apps/ledger-live-mobile/src/screens/Nft/WalletNftGallery/index.tsx
📈 Improve Analytics on NFT Gallery Page
> 📈 Improve Analytics on NFT Gallery Page

- .changeset/serious-peaches-crash.md
- libs/ledger-live-common/src/exchange/platform/transfer/completeExchange.ts
- libs/ledger-live-common/src/exchange/testCurrencyConfig/data/erc20.ts
- libs/ledger-live-common/src/exchange/testCurrencyConfig/index.ts
- libs/ledger-live-common/src/mock/fixtures/cryptoCurrencies.ts
- libs/ledger-live-common/src/platform/logic.test.ts
- libs/ledger-live-common/src/platform/logic.ts
Update existing completeExchange logic to make it work with ERC-20 tokens
https://ledgerhq.atlassian.net/browse/LIVE-4592
Demo:
<details>
https://user-images.githubusercontent.com/9203826/203284202-5b4fd1a4-7549-454c-9241-e68c5bc4d4bb.mov
</details>
How to test:
In order to test this updated flow, you can use the [platform-app-test-exchange](https://github.com/LedgerHQ/platform-app-test-exchange) live app (follow the instruction in the project's README) to get it setup.
- **Linked resource(s)**: [LIVE-4592](https://ledgerhq.atlassian.net/browse/LIVE-4592)
_Pull Requests must pass the CI and be internally validated …
> [FEATURE][LIVE-4592] Add ERC 20 funding

- apps/ledger-live-mobile/src/analytics/TrackScreen.tsx
- apps/ledger-live-mobile/src/components/Nft/HideNftDrawer.tsx
- apps/ledger-live-mobile/src/components/Nft/NftLinksPanel.tsx
- apps/ledger-live-mobile/src/components/Nft/NftList.tsx
- apps/ledger-live-mobile/src/components/Nft/NftViewer.tsx
- apps/ledger-live-mobile/src/screens/Nft/NftGallery/NftGalleryEmptyState.tsx
- apps/ledger-live-mobile/src/screens/Nft/NftGallery/ReceiveNFTsModal.hook.ts
- apps/ledger-live-mobile/src/screens/Nft/NftGallery/ReceiveNFTsModal.tsx
Fixes to tracking in NFT Viewer and linked drawers
> Bugfix - Fixes to tracking in NFT Viewer and linked drawers

- tools/github-bot/src/index.ts
Today we don't have any checks and PRs can be merged even though they are out of date with the base branch.
We need to make sure that the CI is running against the **latest** merge commit before merging.
_It is quite hard to test the bot, best way would be to test live and make the check optional for some time before enforcing_
N/A
> CI: add a check to ensure that a PR is up to date

- .github/workflows/test-mobile-e2e.yml
- apps/ledger-live-mobile/.gitignore
- apps/ledger-live-mobile/e2e/environment.js
- apps/ledger-live-mobile/e2e/jest.config.js
- apps/ledger-live-mobile/e2e/reporters/AllureReporterCircus.js
- apps/ledger-live-mobile/package.json
- pnpm-lock.yaml
- tools/actions/composites/upload-allure-report/action.yml
- Add allure-detox reporter
- Add upload allure report action to reuse in Desktop test also
- Add report upload steps for test-mobile-e2e.yml
It points to detox-post-monorepo branch as it only an addition to it.
- [] **Test coverage** 
> B2CQA 1304 - Add Allure Reporting to Detox LLM test 

- .changeset/pink-houses-do.md
- apps/ledger-live-desktop/src/renderer/modals/Receive/steps/StepReceiveFunds.jsx
Remove redirection to account details from receive banner
- **Impacted projects**: `` LLD``
- https://ledgerhq.atlassian.net/browse/LIVE-4749
> feat: LIVE-4749 LLD  no redirection to asset page from receive banner

- .changeset/slow-camels-relax.md
- apps/ledger-live-mobile/src/components/CustomImage/CustomImageBottomModal.tsx
- apps/ledger-live-mobile/src/components/CustomImage/imageUtils.ts
- apps/ledger-live-mobile/src/components/CustomImage/types.ts
- apps/ledger-live-mobile/src/components/Nft/NftLinksPanel.tsx
- apps/ledger-live-mobile/src/components/Nft/NftList.tsx
- apps/ledger-live-mobile/src/components/Nft/NftListItem.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/CustomImageNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/types/CustomImageNavigator.ts
- apps/ledger-live-mobile/src/const/navigation.ts
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/CustomImage/NFTGallerySelector.tsx
- apps/ledger-live-mobile/src/screens/CustomImage/PreviewPreEdit.tsx
Add a new entrypoint for the NFT gallery. For more details, see Jira or Slack.
- **Linked resource(s)**: [FAT-599] 
N/A, see slack channels.
[FAT-599]: https://ledgerhq.atlassian.net/browse/FAT-599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> NFT Gallery entrypoint

- tools/github-bot/src/features/upToDate/index.ts
- tools/github-bot/src/features/upToDate/tools.ts
- tools/github-bot/src/index.ts
Needed to keep the check run in sync when there are changes in the base branch.
N/A
> Improve the pr up to date feature to sync on target change

- .changeset/serious-queens-yell.md
- libs/ledger-live-common/src/exchange/platform/transfer/index.ts
update existing youhodler partner and add new one uquid
- **Impacted projects**: `` lld&llm
- **Linked resource(s)**: `` exchange & crypto-assets
n/a
n/a
> support(llc): update fund partners

- apps/ledger-live-mobile/src/components/RootNavigator/NotificationCenterNavigator.tsx
- apps/ledger-live-mobile/src/dynamicContent/dynamicContent.tsx
- apps/ledger-live-mobile/src/dynamicContent/types.ts
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/NotificationCenter/Notifications.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/Header.tsx
- libs/ui/packages/native/src/components/Cards/CardC/index.tsx
- libs/ui/packages/native/storybook/stories/Cards/Cards.stories.tsx
Dismiss a LLM Notification Center Card (On Swipe)
- **Impacted projects**: `live-mobile` `ui:native` 
- **Linked resource(s)**: [LIVE-4559] 
https://user-images.githubusercontent.com/112866305/205096637-7e399da8-8b5e-4816-9846-734b3747003d.mp4
[LIVE-4559]: https://ledgerhq.atlassian.net/browse/LIVE-4559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✨ FEAT : V0 - LLM - LIVE-4559:  Dismiss a LLM Notification Center Card

- apps/ledger-live-desktop/src/renderer/families/cosmos/Delegation/index.jsx
- apps/ledger-live-desktop/src/renderer/families/cosmos/DelegationFlowModal/Info/index.jsx
- apps/ledger-live-desktop/src/renderer/families/cosmos/RedelegationFlowModal/steps/StepValidators.jsx
- apps/ledger-live-desktop/src/renderer/families/cosmos/UndelegationFlowModal/steps/Amount.jsx
- apps/ledger-live-desktop/src/renderer/families/cosmos/shared/components/CosmosFamilyValidatorRow.jsx
- apps/ledger-live-desktop/static/i18n/en/app.json
Change text of fixed atom with a currency ticket for LLD Cosmos
> LLD cosmos ui

- .changeset/quiet-llamas-travel.md
- .changeset/rich-cats-remember.md
- .changeset/tender-baboons-report.md
- apps/ledger-live-desktop/static/i18n/en/app.json
- apps/ledger-live-mobile/src/locales/en/common.json
- libs/ledger-live-common/src/families/stellar/errors.ts
- libs/ledger-live-common/src/families/stellar/js-synchronization.ts
- libs/ledger-live-common/src/families/stellar/logic.ts
See https://ledgerhq.atlassian.net/browse/PROD-173 and https://ledgerhq.atlassian.net/browse/LIVE-4014 for context.
- **Impacted projects**: `LLC` `LLD` `LLM` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-4014
> Handle address error during Stellar sync

- .changeset/ninety-eggs-look.md
- .changeset/pink-houses-do.md
- .changeset/shy-bats-end.md
- .changeset/slow-crabs-develop.md
- .changeset/spicy-jeans-study.md
- apps/cli/CHANGELOG.md
- apps/cli/package.json
- apps/ledger-live-desktop/CHANGELOG.md
- apps/ledger-live-desktop/package.json
- apps/ledger-live-desktop/static/i18n/en/app.json
- apps/ledger-live-mobile/CHANGELOG.md
- apps/ledger-live-mobile/package.json
- apps/ledger-live-mobile/src/locales/en/common.json
- libs/ledger-live-common/CHANGELOG.md
- libs/ledger-live-common/package.json
- libs/ledger-live-common/src/api/Tron.ts
- libs/ledger-live-common/src/families/tron/bridge/js.ts
- tools/common-tools/CHANGELOG.md
- tools/common-tools/package.json
Revert bad commits during a release LLD 2.50.1 (develop)
> Revert hotfix commits

- libs/ledger-live-common/src/families/ethereum/__tests__/signOperation.test.ts
- libs/ledger-live-common/src/families/ethereum/logic.ts
- libs/ledger-live-common/src/families/ethereum/prepareTransaction.ts
- libs/ledger-live-common/src/families/ethereum/signOperation.ts
- Add unit tests for the calculation of the `chainId` for the `signOperation` in the ethereum family 
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-4755`
> Signoperation unit test

- .github/workflows/test-desktop.yml
- .pnpmfile.cjs
- apps/ledger-live-desktop/package.json
- apps/ledger-live-desktop/tests/playwright.config.ts
- apps/ledger-live-mobile/ios/Podfile.lock
- pnpm-lock.yaml
- tools/actions/composites/test-desktop/action.yml
- Add `allure-playwright` reporter for PW tests
- Add report upload steps for `test-desktop.yml`
> B2CQA 1302 - Add Allure Reporting to Playwright and Desktop test workflow

- .github/workflow-templates/bot-coin-family.yml
- .github/workflows/bot-carbon.yml
- .github/workflows/bot-mere-denis.yml
- .github/workflows/bot-mooncake.yml
- .github/workflows/bot-nonreg-carbon.yml
- .github/workflows/bot-nonreg-mooncake.yml
- .github/workflows/bot-nonreg-oxygen.yml
- .github/workflows/bot-nonreg-phosphore.yml
- .github/workflows/bot-nonreg-silicium.yml
- .github/workflows/bot-phosphore.yml
- .github/workflows/bot-silicium.yml
- .github/workflows/bot-staging-explorer-btc.yml
- .github/workflows/bot-staging-explorer-eth.yml
- .github/workflows/bot-transfer.yml
- .github/workflows/build-desktop.yml
- .github/workflows/build-mobile.yml
Fix instance volume size for EC2 Runners
- **Impacted projects**: `ledger-live` 
- **Linked resource(s)**: `PE-1549` 
- [*] **Atomic delivery** 
- [*] **No breaking changes** 
> Add condition (if: always) for stop EC2 Linux Runner

- .github/workflows/test-desktop.yml
Fix Allure reporting when desktop tests are not affected
- **Linked resource(s)**: broken CI on Test Desktop (cc: @ggilchrist-ledger ) 
is working CI a good enough demo ?
> fix(allure-reports): add missing condition on allure reporting [desktop tests]

- apps/ledger-live-mobile/docs/llm_e2e_testing.md
Adding info about:
- Better setup steps
- `adb reverse` to get Android debug tests working
- Some more CI info
> Updated LLM E2E readme with better setup and test steps

- apps/ledger-live-desktop/src/renderer/families/cosmos/utils.jsx
- apps/ledger-live-mobile/src/families/cosmos/AccountBalanceSummaryFooter.tsx
- apps/ledger-live-mobile/src/families/cosmos/DelegationFlow/01-Started.tsx
- apps/ledger-live-mobile/src/families/cosmos/Delegations/index.tsx
- apps/ledger-live-mobile/src/families/cosmos/utils.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
Change ATOM label into Osmosis label
- **Impacted projects**: `live-mobile` `live-desktop` 
> cosmos sdk mobile ui

- .github/workflows/bot-mere-denis.yml
- .github/workflows/bot-mooncake.yml
- .github/workflows/bot-nonreg-carbon.yml
- .github/workflows/bot-nonreg-mere-denis.yml
- .github/workflows/bot-nonreg-mooncake.yml
- .github/workflows/bot-nonreg-oxygen.yml
- .github/workflows/bot-nonreg-phosphore.yml
- .github/workflows/bot-nonreg-silicium.yml
- .github/workflows/bot-oxygen.yml
- .github/workflows/bot-phosphore.yml
- .github/workflows/bot-silicium.yml
- .github/workflows/bot-staging-explorer-btc.yml
- .github/workflows/bot-staging-explorer-eth.yml
- .github/workflows/bot-transfer.yml
this branch updates the bot to https://github.com/LedgerHQ/coin-apps/pull/2
we can merge when the bot runs and as soon as we confirm there are no "apps not found" issues with that new branch
the evolution is that, this branch is generated and we no longer will have to maintain the coin-apps#ledger-live-bot branch that was confusing and not documented ( cc @haammar-ledger )
> Update coin apps remote branch to the generated one

- apps/ledger-live-mobile/src/components/CurrencyUnitValue.tsx
- apps/ledger-live-mobile/src/components/GraphCard.tsx
Fix reborn graph card that broke layout of whole page
Fix reborn amount that was not displaying zero amount, by fixing CurrencyUnitValue
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-50
> Feat/LIVE-5021 - Fix reborn page

- apps/ledger-live-mobile/src/components/AccountCard.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/types/RequestAccountNavigator.ts
- apps/ledger-live-mobile/src/components/WebPlatformPlayer/WebView.tsx
- apps/ledger-live-mobile/src/families/tron/Confirmation.tsx
- apps/ledger-live-mobile/src/reducers/accounts.ts
- apps/ledger-live-mobile/src/screens/AccountSettings/AdvancedLogs.tsx
- apps/ledger-live-mobile/src/screens/Accounts/AccountRow.tsx
- apps/ledger-live-mobile/src/screens/AddAccounts/01-SelectCrypto.tsx
- apps/ledger-live-mobile/src/screens/AddAccounts/03-Accounts.tsx
- apps/ledger-live-mobile/src/screens/AddAccounts/04-Success.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/02-AddAccountSelectDevice.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/03-Confirmation.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/03a-ConnectDevice.tsx
- apps/ledger-live-mobile/src/screens/RequestAccount/01-SelectCrypto.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/ReadOnly/index.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/index.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricSections/MarketPrice.tsx
- libs/ledger-live-common/src/currencies/helpers.ts
some usage of `as CryptoCurrency` was remaining in our codebase, it's something we never should do.  This is bad for our quality and it creates bugs (one that is currently in production and fixed by https://github.com/LedgerHQ/ledger-live/pull/2009 , there are possibly similar cases creating runtime crashes)
Here are tips for the future:
- never use `as *` for any of these Currency or Account types: We should at worse case prefer to `.type === "CryptoCurrency"` or at best make sure the type is correct. `.type` static field is the only guarantee we have on runtime objects that we are sure it matches with the type, TS also is able to type prove this.
- some navigation was defined with wrong types.
- When we use Currency, we sometimes actually mean to use CryptoOrTokenCurrency. ⚠️  Currency …
> LLM: kill all 'as CryptoCurrency'

- .github/workflows/test-mobile-e2e.yml
- apps/ledger-live-mobile/e2e/specs/nftGallery.spec.ts
- apps/ledger-live-mobile/e2e/specs/password.spec.ts
- apps/ledger-live-mobile/src/context/AuthPass/index.tsx
- updated password timing on mock mode
- updated tests
- removed timeout on first sendToHome()
b2cqa-1523 - Reducing time taken for password detox test
https://user-images.githubusercontent.com/87659842/209678480-8d8601f9-f73a-44e8-b76e-e0789e904497.mov
> Detox - Reduce password test wait time from 60 seconds to 5 seconds

- apps/ledger-live-mobile/detox.config.js
Setting to Detox debug level to debug so we have more info for debugging issues on the CI runners
> Set Detox debug level to Debug on CI runs

- apps/ledger-live-mobile/android/app/src/debug/java/com/ledger/live/ReactNativeFlipper.java
- apps/ledger-live-mobile/ios/Podfile.lock
- apps/ledger-live-mobile/ios/ledgerlivemobile/AppDelegate.m
- apps/ledger-live-mobile/package.json
- pnpm-lock.yaml
Implementation of [React Native Flipper performance monitor](https://github.com/bamlab/react-native-flipper-performance-monitor)
- **Impacted projects**: `` N/A
- **Linked resource(s)**: `` https://github.com/bamlab/react-native-flipper-performance-monitor#install-for-non-expo-projects
https://user-images.githubusercontent.com/16896559/207097751-1c614659-3c7a-42b7-9e67-f81febb750d7.mov
Must work on Android and iOS
> React Native Flipper performance plugin

- .changeset/three-jars-brake.md
- apps/ledger-live-mobile/src/screens/Manager/index.tsx
The MyLedger page UI looks broken if the `protectServicesMobile` feature flag is enabled, because the scroll view and the "buy a ledger" CTA are badly placed.
We would actually have a similar "broken UI" result with the `protectServicesMobile` disabled if the user has a lot of known devices (so with a long list that needs to scroll)
- **Impacted projects**: `mobile` 
- **Linked resource(s)**: [FAT-732],  Figma link in the ticket 
I don't know if I can share this on github so [putting the videos for Ledger employees here](https://drive.google.com/drive/folders/1Or2-8qoxGGxkoIhRNKJuJsYd7IaoyvNM?usp=sharing)
The "before" video shows how it is before this fix.
The "after" shows after the fix, with the `protectServicesMobile` enabled, then disabled.
If the protect related flags …
> Fix MyLedger device selection screen UI with the ServicesWidget

- .changeset/empty-donkeys-develop.md
- apps/ledger-live-mobile/src/actions/settings.ts
- apps/ledger-live-mobile/src/actions/types.ts
- apps/ledger-live-mobile/src/reducers/accounts.ts
- apps/ledger-live-mobile/src/reducers/appstate.ts
- apps/ledger-live-mobile/src/reducers/ble.ts
- apps/ledger-live-mobile/src/reducers/index.ts
- apps/ledger-live-mobile/src/reducers/notifications.ts
- apps/ledger-live-mobile/src/reducers/ratings.ts
- apps/ledger-live-mobile/src/reducers/settings.ts
- apps/ledger-live-mobile/src/reducers/swap.ts
- apps/ledger-live-mobile/src/screens/Settings/Debug/Debugging/Node.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/Debugging/Store.tsx
Improvements to the App state tool for debugging the app's memory. It includes the ability to export this to file for easily identifying the culprit when debugging an issue but also, and most importantly, the ability to edit the store from within LLM in a somewhat limited manner. We an now switch booleans, and edit strings and numbers.
I'll do a workshop for this in Q1 to explain the use cases but at least I'm lowering the entry barrier and making it a bit more accessible. The original functionality of editing the state over the Chrome dev tools or Flipper is still available but only if it's a dev build.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-5046` 
https://user-images.githubusercontent.com/4631227/210152596-6d31 …
> feat/LIVE-5046 Improvements to the App State tool.

- apps/ledger-live-mobile/src/dynamicContent/dynamicContent.tsx
- apps/ledger-live-mobile/src/dynamicContent/types.ts
- apps/ledger-live-mobile/src/screens/Learn/learn.tsx
Cards should sorted from latest to oldest in Learn Section
- **Linked resource(s)**: [LIVE-5043] 
[LIVE-5043]: https://ledgerhq.atlassian.net/browse/LIVE-5043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LLM - LIVE-5043 : Cards should sorted from latest to oldest in Learn Section

- .changeset/small-donkeys-buy.md
- apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/ClaimNftNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/types/BaseNavigator.ts
- apps/ledger-live-mobile/src/components/RootNavigator/types/ClaimNftNavigator.tsx
- apps/ledger-live-mobile/src/components/Scanner.tsx
- apps/ledger-live-mobile/src/config/urls.tsx
- apps/ledger-live-mobile/src/const/navigation.ts
- apps/ledger-live-mobile/src/index.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/logic/postOnboarding/actions.ts
- apps/ledger-live-mobile/src/screens/ClaimNft/ClaimNftQrScan.tsx
- apps/ledger-live-mobile/src/screens/ClaimNft/ClaimNftWelcome.tsx
- apps/ledger-live-mobile/src/screens/ImportAccounts/FallBackCameraScreen.android.tsx
- apps/ledger-live-mobile/src/screens/ImportAccounts/FallBackCameraScreen.d.ts
- apps/ledger-live-mobile/src/screens/PostOnboarding/PostOnboardingHub.tsx
This PR add the claim NFT flow on the post onboarding hub
- **Linked resource(s)**:  [FAT-451] [FAT-486] [FAT-487] [FAT-548] [FAT-701](https://ledgerhq.atlassian.net/browse/FAT-701)
Send me a DM on Slack to get a video demo
[FAT-486]: https://ledgerhq.atlassian.net/browse/FAT-486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAT-487]: https://ledgerhq.atlassian.net/browse/FAT-487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
> add claim NFT flow

- .changeset/chilled-ties-juggle.md
- apps/ledger-live-mobile/src/components/FabActions/hooks/useAssetActions.tsx
- apps/ledger-live-mobile/src/components/FabActions/index.tsx
- apps/ledger-live-mobile/src/components/SelectFeesStrategy.tsx
- apps/ledger-live-mobile/src/components/TabBar/TransferDrawer.tsx
- apps/ledger-live-mobile/src/screens/Swap/Form/Max.tsx
- apps/ledger-live-mobile/src/screens/Swap/Form/Requirement/Banner.tsx
- apps/ledger-live-mobile/src/screens/Swap/Form/Summary/index.tsx
- apps/ledger-live-mobile/src/screens/Swap/Form/TxForm/From.tsx
- apps/ledger-live-mobile/src/screens/Swap/Form/TxForm/To.tsx
- apps/ledger-live-mobile/src/screens/Swap/Form/index.tsx
- apps/ledger-live-mobile/src/screens/Swap/SubScreens/SelectFees.tsx
- apps/ledger-live-mobile/src/screens/Swap/SubScreens/SelectProvider.tsx
- apps/ledger-live-mobile/src/screens/Swap/utils.ts
LLM Swap Analytics
- **Impacted projects**: Mobile
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-4833
> feat: swap analytics for LLM

- .changeset/curvy-readers-dance.md
- libs/ledger-live-common/src/families/ethereum/modules/erc20.ts
- libs/ledger-live-common/src/families/ethereum/modules/erc20.unit.test.ts
Prevents over usage of our CDN for `erc20.json` file.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5126 
> [LIVE-5126] Bugfix - Add an LRU Cache on ERC20 CDN call

- .changeset/brown-socks-dress.md
- .changeset/sour-squids-protect.md
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.jsx
- libs/ledger-live-common/src/errors.ts
- libs/ledger-live-common/src/exchange/swap/getExchangeRates.test.ts
- libs/ledger-live-common/src/exchange/swap/getExchangeRates.ts
- libs/ledger-live-common/src/exchange/swap/hooks/useProviderRates.test.ts
- libs/ledger-live-common/src/exchange/swap/hooks/useProviderRates.ts
As a user on LLD, i want to know the min/max amount I can swap with DEX providers
- **Impacted projects**: 
- LLD
- Common
- https://ledgerhq.atlassian.net/browse/LIVE-4683
Although DEX limits are less restrictives, We do not know exactly the "amount".
We will not show any error message. Only a empty list.
> Feat: LIVE-4683 Add DEX limit UI

- apps/ledger-live-desktop/src/renderer/families/ethereum/StakeFlowModal/Body.jsx
- apps/ledger-live-desktop/src/renderer/families/ethereum/StakeFlowModal/component/ProviderItem.tsx
- apps/ledger-live-desktop/src/renderer/modals/Receive/steps/StepReceiveStakingFlow.tsx
Add hover effect ETH Stake modal
- **Impacted projects**: 
- LLD
- https://ledgerhq.atlassian.net/browse/LIVE-4972
> fix: LIVE-4972 add hover effect eth stake modal

- .changeset/beige-dancers-laugh.md
- .changeset/nervous-pans-compete.md
- .changeset/spicy-seals-invite.md
- apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx
- apps/ledger-live-desktop/static/i18n/en/app.json
- apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- libs/ledger-live-common/src/exchange/swap/utils/index.test.ts
- libs/ledger-live-common/src/exchange/swap/utils/index.ts
Updates KYC copy shown when swapping with Changelly.
We have already got copy for the CIC provider, so I've changed this field so we can pass in any provider name in future.
- **Impacted projects**: Desktop/Mobile
- **Linked resource(s)**:https://ledgerhq.atlassian.net/browse/LIVE-4192
> fix: adds copy for changelly's KYC alert

- apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx
- apps/ledger-live-mobile/src/screens/Discover/index.tsx
Bugfix discover learn section navigation fixed
- **Linked resource(s)**: `LIVE-5143` 
> Bugfix discover learn section navigation fixed

- .github/workflows/test-desktop.yml
_Allure server is polluted by PR results. We choose to limit playwright allure report to develop branch only._
> B2CQA - Limit playwright allure report to develop branch only

- libs/ledgerjs/packages/hw-transport/README.md
- libs/ledgerjs/packages/hw-transport/src/Transport.ts
in context of recent discussion that exchange() was misleading at saying "you should use send() instead" i rework a bit the documentation of hw-transport. I also took opportunity to use ChatGPT to complete some missing information or fix the English.
> Improve documentation of hw-transport

- .changeset/fifty-forks-bake.md
- libs/ledger-live-common/src/apps/polyfill.ts
add Cometh as dep
- **Impacted projects**: lld & llm
- **Linked resource(s)**: app manager
n/a
n/a
> support: add Cometh as dep

- .changeset/cool-camels-invent.md
- libs/ledger-live-common/src/postOnboarding/reducer.test.ts
- libs/ledger-live-common/src/postOnboarding/reducer.ts
Similar to #2157, we are getting the following error in a nightly build because some users have app data related to a post onboarding that was started before the device model identifier `"nanoFTS"` was changed to `"stax"`.
> Error: device 'nanoFTS' does not exist
> 
> {arguments: [{componentStack: 
>     in Root
>     in ReactNativeProfiler
>     in RCTView
>     in Unknown
>     in __Sentry.TouchEventBoundary
>     in RootApp
>     in RCTView
>     in Unknown
>     in RCTView
>     in Unknown
>     in AppContainer, isComponentError: True, message: device 'nanoFTS' does not exist, name: Error, stack: Error: device 'nanoFTS' does not exist
>     at getDeviceModel (/Users/ec2-user/Library/Developer/Xcode/DerivedData/ledgerlivemobile-cmbaeiebjyfcvogropprzhfbkzah/Build/Intermediates.noindex/Ar …
> Bugfix/fat 796 Crash because of legacy identifier "nanoFTS" in post onboarding data

- .changeset/twenty-cats-camp.md
- libs/ledger-live-common/scripts/sync-families-dispatch.mjs
- libs/ledger-live-common/src/families/bitcoin/walletApiAdapter.test.ts
- libs/ledger-live-common/src/families/bitcoin/walletApiAdapter.ts
- libs/ledger-live-common/src/families/ethereum/walletApiAdapter.test.ts
- libs/ledger-live-common/src/families/ethereum/walletApiAdapter.ts
- libs/ledger-live-common/src/families/polkadot/walletApiAdapter.test.ts
- libs/ledger-live-common/src/families/polkadot/walletApiAdapter.ts
- libs/ledger-live-common/src/families/ripple/walletApiAdapter.test.ts
- libs/ledger-live-common/src/families/ripple/walletApiAdapter.ts
- libs/ledger-live-common/src/generated/walletApiAdapter.ts
- libs/ledger-live-common/src/wallet-api/converters.test.ts
- libs/ledger-live-common/src/wallet-api/converters.ts
- libs/ledger-live-common/src/wallet-api/types.ts
With the migration from live-app-sdk to wallet-api, we also need to migrate transaction adapters logic to the new wallet-api types.
cf:
- https://github.com/LedgerHQ/ledger-live/pull/1900
- https://github.com/LedgerHQ/ledger-live/pull/1901
- **Impacted projects**: `LLM`, `LLD`, `LLC`
- **Linked resource(s)**: [LIVE-5085](https://ledgerhq.atlassian.net/browse/LIVE-5085)
[LIVE-5085]: https://ledgerhq.atlassian.net/browse/LIVE-5085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add walletApiAdapter files to migrate to wallet-api

- apps/ledger-live-mobile/src/components/Nft/NftList.hook.ts
- apps/ledger-live-mobile/src/components/Nft/NftList.tsx
- apps/ledger-live-mobile/src/components/Nft/NftListItem.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
Show notification after action is done
- **Linked resource(s)**: [LIVE-5112] 
[LIVE-5112]: https://ledgerhq.atlassian.net/browse/LIVE-5112?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ✨ Multiples Improvments and SnackBar when action of hide is done

- .changeset/five-years-dress.md
- .changeset/pre.json
- apps/ledger-live-desktop/package.json
Mistake were made and major was set instead of minor
- **Impacted projects**: `global` 
> revert nightly version to a minor

- apps/ledger-live-mobile/src/PlatformAppProviderWrapper.tsx
Remove use of staging for manifests providers because it does not exists anymore
> Remove use of staging for manifests providers

- apps/ledger-live-desktop/tools/utils/index.js
Allows LLD to be build without a `.git` foler
Implementation proposed by @phnx47, thanks to him 🙏 
- **Linked resource(s)**: #1719  
No Demo
still be able to build LLD through our pipelines
Updated => pre released build tested and working. we are good
closes #1719 
> fix(build): LLD add possibility to build without git access

- apps/ledger-live-mobile/docs/ONBOARDING_LINUX.md
- apps/ledger-live-mobile/docs/linking.md
- apps/ledger-live-mobile/docs/linux_setup.md
> Fix: typos

- .github/workflows/test-mobile-e2e.yml
- apps/ledger-live-mobile/.env.mock
- apps/ledger-live-mobile/e2e/helpers.ts
- apps/ledger-live-mobile/e2e/models/settings/generalSettingsPage.ts
- apps/ledger-live-mobile/src/screens/Onboarding/steps/language.tsx
_Fixing onboarding test by disabling llmNewDeviceSelection feature flag.
Adding scrollToText to helpers library to fix Android change language tests.
Improve emulator settings to prevent app crash_
- **Linked resource(s)**: [`GitHub run`](https://github.com/LedgerHQ/ledger-live/actions/runs/3959215041)   [`Allure iOS`](https://ledger-live.ars.green.ledgerlabs.net/allure/reports/173f35a1-fea9-4497-9371-556211c13bb7/index.html)   [`Allure Android`](https://ledger-live.ars.green.ledgerlabs.net/allure/reports/ff3b903f-0342-4768-b50d-ed9d39641240/index.html) …
> B2CQA - Fix Detox onboarding and language tests

- .changeset/brown-badgers-kiss.md
- libs/ledger-live-common/src/exchange/swap/getExchangeRates.test.ts
- libs/ledger-live-common/src/exchange/swap/getExchangeRates.ts
Polygon bug
- **Impacted projects**: Common
- **Linked resource(s)**: https://ledger.slack.com/archives/C044K2SBJ7P/p1674119117175289
https://ledgerhq.atlassian.net/browse/LIVE-5234
> Bugfix/include dex quotes false bug LIVE-5234

- .changeset/sharp-eyes-build.md
- libs/ledger-live-common/src/apps/support.ts
Update min support of polkadot.
This will help also sidecar and polkadot node update probably + CLI 👍 
> update min support polkadot

- apps/ledger-live-desktop/tests/utils/dummy-wallet-app/package.json
- pnpm-lock.yaml
Bump the wallet-api-client for the dummy-wallet-app in order to fix a build issue with the `hw-transport` package.
> support(dummy-wallet-app): bump wallet-api-client

- .github/workflows/release-create-hotfix.yml
- .github/workflows/release-create.yml
- .github/workflows/release-prepare-hotfix.yml
- .github/workflows/release-prepare.yml
- .github/workflows/release-prerelease.yml
To make the release flow as streamlined and as automated as possible, we need to remove the platform specific code from the workflow files.
- **Linked resource(s)**: `LIVE-5236` 
> chore: cleanup platform specific logic for release [LIVE-5236]

- .github/workflows/build-desktop.yml
- .github/workflows/healthchecks-runners.yaml
- .github/workflows/test-desktop.yml
- tools/actions/composites/build-desktop/action.yml
Moving up to the m1 runners
- **Linked resource(s)**: https://github.com/LedgerHQ/ledger-live-issues/issues/64 
CI is the same but faster
> ci(runners): switch some jobs to m1 runners

- .changeset/spicy-walls-return.md
- apps/ledger-live-desktop/src/renderer/screens/stake/constants.tsx
- apps/ledger-live-desktop/src/renderer/screens/stake/index.tsx
Add common staking flow when funds
import stakeFlow from "~/renderer/screens/stake/index.tsx";
useStakeFlow()
It can be used with a specific account. This integration will be used for "earn dashboard".
useStakeFlow({account, parentAccount)
- LLD - Portfolio -  staking flow when funds  https://ledgerhq.atlassian.net/browse/LIVE-4012
- Create stake inventory drawer https://ledgerhq.atlassian.net/browse/LIVE-5176
- Link inventory drawer with stake programs https://ledgerhq.atlassian.net/browse/LIVE-5177
> feat: LIVE-4012 add centralise stake flow

- .changeset/eight-mice-warn.md
- apps/ledger-live-desktop/.gitignore
- tools/actions/.gitignore
Adds entry in ledger-live-desktop/.gitignore
- **Linked resource(s)**:  None
> bugfix: updates LLD gitignore 

- .changeset/fuzzy-lamps-confess.md
- apps/ledger-live-desktop/src/renderer/screens/dashboard/FeaturedButtons.tsx
- apps/ledger-live-desktop/src/renderer/screens/stake/index.tsx
Links new exchange buttons on portfolio screen to relevant flows.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5175
https://user-images.githubusercontent.com/119950081/214585284-fb2cf934-36dc-41c7-b12b-23d24cb85ee6.mov
> feat: LLD - links exchange button from portfolio screen to relevant flows

- .changeset/six-plants-deliver.md
- libs/ledger-live-common/src/platform/logic.ts
- libs/ledger-live-common/src/wallet-api/logic.ts
Bellow you will find examples of this bad formatted message and how it is not easily readable.
> fix signTransaction and completeExchange error messages formatting

- .github/workflows/release-prepare-hotfix.yml
- .github/workflows/release-prepare.yml
Creates a PR if we have an error during the merge to develop for the release and the hotfix flows.
Also merge the hotfix to the release branch and handles errors here too.
- **Linked resource(s)**: [`LIVE-5237`](https://ledgerhq.atlassian.net/browse/LIVE-5237) 
> support: prevent merge error on the release flow

- .github/workflows/cal-importer.yml
> chore: Append erc20 subset copy to backend server

- .changeset/config.json
Clean the ignore field from the config file of changeset
> support(changeset): clear ignore field from the config.json

- .changeset/clever-lamps-sin.md
- .changeset/lucky-jeans-tease.md
- .changeset/shy-rats-beg.md
- .changeset/thin-pugs-enjoy.md
Forgot to include the changesets in this PR : https://github.com/LedgerHQ/ledger-live/pull/1370
- **Impacted projects**: `LL common, LLD`
- **Linked resource(s)**: ``
> missing changesets for v4 explorer PR

- .changeset/smooth-elephants-argue.md
- apps/ledger-live-desktop/src/renderer/screens/market/MarketCoinScreen/index.tsx
Shows stake button on asset screen
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5030
https://user-images.githubusercontent.com/119950081/215527064-c07fb672-9853-4974-bf92-f43b94fad569.mov
> feat: adds stake button to asset page

- .changeset/spicy-coats-trade.md
- .changeset/spotty-emus-collect.md
- apps/ledger-live-desktop/src/config/transportChannels.ts
- apps/ledger-live-desktop/src/internal/index.js
- apps/ledger-live-desktop/src/internal/transportHandler.ts
- apps/ledger-live-desktop/src/main/internal-lifecycle.js
- apps/ledger-live-desktop/src/renderer/IPCTransport.js
- libs/ledger-live-common/src/api/socket.ts
- libs/ledgerjs/packages/hw-transport/README.md
- libs/ledgerjs/packages/hw-transport/src/Transport.ts
- This implements a `exchangeBulk` method on Transport, that is implemented by default for all transports.
- We then can use it in `socket` logic in order to run the bulk of APDU when install apps, firmwares,...
- We overrides the "exchangeBulk" on the the IPC Transport to benefit the gain of performance.
Performance analysis:
- When Experimental Renderer Execution is ON => On a build, this was tested to optimise from **2 minutes** to **25 seconds** the installation of Polkadot app.
- When it is OFF (aka production) => On a build, I was able to see that the current production approach (commands & all is in internal) is relatively the same, but actually a bit slower (**27 seconds** on that try). The reason it could be slower is that Internal Process is today doing MORE than just dealing …
> Performance: Add transport.exchangeBulk API and extend IPCTransport

- .github/templates/hotfix-conflicts.md
- .github/templates/hotfix-release-conflicts.md
- .github/templates/release-conflicts.md
- .github/workflows/release-prepare-hotfix.yml
- .github/workflows/release-prepare.yml
Fix a bad usage of `if` with a single command, 2 options here:
```bash
if git merge release
then
```
or
```bash
if [[ $(git merge release) ]]
then
```
> support(ci): fix conditional binary operator expected

- .changeset/three-clocks-boil.md
- apps/ledger-live-mobile/src/components/Nft/NftList.hook.ts
- apps/ledger-live-mobile/src/components/Nft/NftList.tsx
Analytics were missing from the feature. Adding tracking to 3 requested events : When opening the mutiselect mode, when hiding selected collections and when canceling action
- **Linked resource(s)**: Epic w/ tracking plan : https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/463?modal=detail&selectedIssue=LIVE-4697
N/A
> Added analytics to Mutiselect-hide NFT's

- .github/workflows/healthchecks-runners.yaml
- .github/workflows/release-create-hotfix.yml
- .github/workflows/release-create.yml
- .github/workflows/release-final-nightly.yml
- .github/workflows/release-final.yml
- .github/workflows/release-prepare-hotfix.yml
- .github/workflows/release-prepare.yml
- .github/workflows/release-prerelease.yml
- .github/workflows/sync.yml
Use the new GitHub app token
Rename git user name to live-github-bot[bot]
- **Linked resource(s)**: [`LIVE-5305`](https://ledgerhq.atlassian.net/browse/LIVE-5305) 
> support: use GitHub app token [LIVE-5305]

- apps/ledger-live-desktop/src/renderer/components/BalanceInfos/index.jsx
- apps/ledger-live-desktop/src/renderer/components/DeviceAction/index.tsx
- apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx
- apps/ledger-live-desktop/src/renderer/screens/account/AccountHeaderActions.jsx
- apps/ledger-live-desktop/src/renderer/screens/asset/AssetBalanceSummaryHeader.jsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/ExchangeDrawer/index.jsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FeesDrawer/index.jsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FormKYCBanner/index.jsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FormLoginBanner/index.jsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FormNotAvailable/FormNotAvailable.jsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FormSelectors/FormInputs.jsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FormSelectors/FromRow.jsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FormSelectors/ToRow.jsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FormSummary/SectionFees.jsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FormSummary/SectionTarget.jsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/Rates/index.jsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/TargetAccountDrawer/index.jsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.jsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/KYC/Wyre/Pending.jsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/KYC/Wyre/index.jsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Navbar/index.jsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/utils/index.js
- apps/ledger-live-desktop/src/renderer/screens/market/MarketCoinScreen/index.tsx
- apps/ledger-live-desktop/src/renderer/screens/market/MarketRowItem.tsx
Adds `isDexEnabled` to all analytics events in the swap flow. This is sourced from a feature flag, so our shared event properties object is now loaded via a hook.
- **Linked resource(s)**:  https://ledgerhq.atlassian.net/browse/LIVE-5302
> feat: lld - adds swap feature flag values to analytic events

- .changeset/brave-kids-poke.md
- apps/ledger-live-desktop/src/renderer/screens/platform/App.jsx
- apps/ledger-live-desktop/src/renderer/screens/platform/utils.test.ts
- apps/ledger-live-desktop/src/renderer/screens/platform/utils.tsx
Hotfix: support deeplink from external browser
- https://ledgerhq.atlassian.net/browse/LIVE-5365
(https://github.com/LedgerHQ/ledger-live/pull/2507)
> fix: fix deeplink problem launching lld

- .github/workflows/build-desktop-external.yml
- .github/workflows/build-desktop.yml
- .github/workflows/build-mobile-external.yml
- .github/workflows/build-mobile.yml
- .github/workflows/gate.yml
- .github/workflows/generate-screenshots.yml
- .github/workflows/release-prerelease.yml
- .github/workflows/test-desktop-external.yml
- .github/workflows/test-desktop.yml
- tools/actions/composites/setup-test-desktop/action.yml
- tools/github-bot/src/commands/generate-screenshots.ts
- tools/github-bot/src/commands/regen-doc.ts
- tools/github-bot/src/commands/regen-pods.ts
- tools/github-bot/src/features/lintCommits/index.ts
- tools/github-bot/src/features/orchestrator/index.ts
- tools/github-bot/src/tools/monitorWorkflow.ts
Clean up PR
- **Linked resource(s)**: #1991  
No demo
> chore(cleanup): remove temp code from granular CI

- .github/workflows/build-desktop-external.yml
- .github/workflows/build-desktop.yml
- .github/workflows/build-mobile-external.yml
- .github/workflows/build-mobile.yml
- .github/workflows/test-desktop-external.yml
- .github/workflows/test-desktop.yml
- .github/workflows/test-mobile-e2e.yml
- .github/workflows/test-mobile.yml
- .github/workflows/test.yml
- tools/actions/composites/checkout-merge/action.yml
- tools/github-bot/src/features/orchestrator/const.ts
- tools/github-bot/src/features/orchestrator/tools.ts
- Make it possible to have required checks on the watcher
- Use merge commits on the workflows triggered by the bot
No Demo
run **optional** test and and still have watcher as success even if these fail
> chore(bot): make workflow runs requireable and use merge commit

- .changeset/lemon-bears-serve.md
- libs/ledger-live-common/src/currencies/helpers.test.ts
- libs/ledger-live-common/src/currencies/helpers.ts
- libs/ledger-live-common/src/helpers.ts
- libs/ledger-live-common/src/platform/converters.ts
- libs/ledger-live-common/src/platform/helpers.ts
- libs/ledger-live-common/src/platform/react.ts
- libs/ledger-live-common/src/platform/types.ts
- libs/ledger-live-common/src/wallet-api/converters.ts
- libs/ledger-live-common/src/wallet-api/helpers.ts
- libs/ledger-live-common/src/wallet-api/react.ts
`listCurrencies` was filtering too early and we weren't checking correctly for supported currency in the platform
- **Impacted projects**: `ledger-live-mobile` & `ledger-live-desktop` 
> fix: correctly filter after listCurrencies

- .changeset/large-eggs-dress.md
- apps/ledger-live-desktop/src/renderer/components/WebPlatformPlayer/WebViewV2.tsx
- apps/ledger-live-mobile/src/components/WebPlatformPlayer/WebViewV2.tsx
Cleanup the transport when we leave the webview
- **Impacted projects**: `leader-live-desktop` & `ledger-live-mobile` 
> fix(wallet-api): cleanup the transport on unmount

- .changeset/spicy-trees-doubt.md
- .github/workflows/bot-transfer.yml
- apps/cli/src/commands/botTransfer.ts
- libs/ledger-live-common/package.json
- libs/ledger-live-common/src/bot/engine.ts
- libs/ledger-live-common/src/bot/specs.ts
- libs/ledger-live-common/src/bot/types.ts
- libs/ledger-live-common/src/families/elrond/specs.ts
- pnpm-lock.yaml
- possibility to filter specific coins
- ability to send part of the funds
- more resiliency on independent transactions
- fix the handling of speculos in case one of the first async call fails
(nb this work was initially part of https://github.com/LedgerHQ/ledger-live/pull/2513 but we can deliver this separately)
https://github.com/LedgerHQ/ledger-live/actions/workflows/bot-transfer.yml
> fix: botTransfer has been fixed with more features

- .changeset/nine-horses-shave.md
- libs/ledger-live-common/src/account/serialization.ts
- libs/ledger-live-common/src/families/near/bridge/js.ts
- libs/ledger-live-common/src/families/near/serialization.ts
- libs/ledger-live-common/src/reconciliation.ts
Remove near coin specific logic outside of near family folder
- **Linked resource(s)**: `LIVE-4944` 
> [LIVE-4944] Near coin mod

- apps/ledger-live-mobile/src/components/Button.tsx
- apps/ledger-live-mobile/src/hooks/newsfeed/cryptopanicApi.ts
- apps/ledger-live-mobile/src/hooks/newsfeed/useCryptopanicPosts.ts
Add useCryptopanicPosts hook to help getting and using cryptopanic data for newsfeed page
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-5018
> Feat/LIVE-5019 - Newsfeed - Add cryptopanic hook

- tools/github-bot/tips/build-desktop-external.md
- tools/github-bot/tips/build-desktop.md
- tools/github-bot/tips/build-mobile-external.md
- tools/github-bot/tips/build-mobile.md
- tools/github-bot/tips/test-desktop-external.md
- tools/github-bot/tips/test-desktop.md
- tools/github-bot/tips/test-mobile-e2e.md
- tools/github-bot/tips/test-mobile.md
- tools/github-bot/tips/test.md
Adding more specific info about what the "checkout" part of our CI workflows do.
I was confused as to why running the test locally on my branch was producing different results from the CI. This might clarify things a bit for people who make the effort of reading the details of failed checks before diving into the logs of the workflow or simply before panicking :trollface: 
> docs(github-bot/tips): more specific information about the repo checkout

- tools/common-tools/src/demos/index.js
- tools/common-tools/src/demos/sync/index.js
- tools/common-tools/src/demos/sync/live-common-setup.js
Add in our deployed tools an easy way to test synchronisation of an account by its id. **This is mostly useful for developers in order to more precisely measure performance, profile JS, inspect Network activity (with moderns tools) of what a synchronisation is exactly doing.**
> In tools, add a utility to test a sync on the web, for any account id

- apps/ledger-live-mobile/src/hooks/newsfeed/cryptopanicApi.ts
- apps/ledger-live-mobile/src/hooks/newsfeed/useCryptopanicPosts.ts
- apps/ledger-live-mobile/src/screens/Newsfeed/index.tsx
Connected to CryptoPanic API, piped everything, added pull down to refresh
- **Linked resource(s)**: LIVE-5016 LIVE-5018
https://user-images.githubusercontent.com/39890664/218696707-6dd3712d-3c7a-496f-b8f9-75ad14a7dcbb.mp4
> Connected to CryptoPanic API, piped everything, added pull down to refresh

- .github/workflows/test.yml
This line seems wrong: `echo "diff=$(git diff --exit-code || 1)" >> $GITHUB_OUTPUT` 
```
Run echo "diff=$(git diff --exit-code || 1)" >> $GITHUB_OUTPUT
/home/runner/work/_temp/ce22bc0f-ab19-4d5a-a0[6](https://github.com/LedgerHQ/ledger-live/actions/runs/4161931812/jobs/7200479617#step:7:7)1-c2d0e55ea8b1.sh: line 1: 1: command not found
Error: Unable to process file command 'output' successfully.
Error: Invalid format 'index d95940813c..9c[7](https://github.com/LedgerHQ/ledger-live/actions/runs/4161931812/jobs/7200479617#step:7:8)7[8](https://github.com/LedgerHQ/ledger-live/actions/runs/4161931812/jobs/7200479617#step:7:9)b4acb 100644'
```
N/A …
> ci: fix git diff steps

- .changeset/dry-penguins-tease.md
- apps/cli/src/commands-index.ts
- apps/cli/src/commands/deviceSDKGetDeviceInfo.ts
- libs/ledger-live-common/src/deviceSDK/actions/core.ts
- libs/ledger-live-common/src/deviceSDK/actions/getDeviceInfo.ts
- libs/ledger-live-common/src/deviceSDK/commands/core.ts
- libs/ledger-live-common/src/deviceSDK/commands/genuineCheck.ts
- libs/ledger-live-common/src/deviceSDK/commands/getAppAndVersion.ts
- libs/ledger-live-common/src/deviceSDK/commands/getVersion.test.ts
- libs/ledger-live-common/src/deviceSDK/commands/getVersion.ts
- libs/ledger-live-common/src/deviceSDK/hooks/getDeviceInfo.ts
- libs/ledger-live-common/src/deviceSDK/tasks/core.ts
- libs/ledger-live-common/src/deviceSDK/tasks/genuineCheck.ts
- libs/ledger-live-common/src/deviceSDK/tasks/getDeviceInfo.ts
- libs/ledger-live-common/src/hw/deviceAccess.ts
First version of the new device SDK
💁 For now, implemented inside live-common.
🧑‍🏫 Check the implementation diagram ⬇️
<details>
<summary>New device action implementation diagram</summary>
</details>
First commands:
- getVersion
- getAppAndVersion
- genuineCheck
First task (with shared logic):
- getDeviceInfo
First action (with shared reducer logic):
- getDeviceInfo
And implemented a hook + a CLI for the getDeviceInfo as a usage example
- **Impacted projects**: `live-common`
- **Linked resource(s)**: [FAT-735](https://ledgerhq.atlassian.net/browse/FAT-735) …
> Feat: device SDK: first device action

- .changeset/nine-pillows-sin.md
- apps/ledger-live-mobile/src/screens/Portfolio/Header.tsx
Remove Old Warning Sign when status is down
- **Linked resource(s)**: [LIVE-5610] 
https://user-images.githubusercontent.com/112866305/218767187-399dcf4e-983e-4973-af55-d28985d113b1.mov
[LIVE-5610]: https://ledgerhq.atlassian.net/browse/LIVE-5610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(LLM): Remove Old Warning Sign when status is down

- .changeset/rotten-colts-protect.md
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FormSelectors/ToRow.jsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/Rates/index.jsx
Update data tracking following Amine comments
- **Linked resource(s)**:   https://ledgerhq.atlassian.net/browse/LIVE-5495
> Bugfix: LIVE-5495 lld fix swap track

- .changeset/calm-parents-report.md
- apps/ledger-live-mobile/src/components/DeviceActionModal.tsx
While working on https://github.com/LedgerHQ/ledger-live/pull/2579 and https://github.com/LedgerHQ/ledger-live/pull/2595 with @alexandremgo, we saw that we probably don't need to reset the result here.
When I checked the old code in the `ledger-live-mobile` repo we weren't doing this reset or even having a state here for the result.
> fix(DeviceActionModal): avoid resetting the result onModalHide

- .changeset/fifty-chairs-allow.md
- .changeset/hip-dancers-walk.md
- .changeset/olive-tools-pull.md
- apps/ledger-live-desktop/package.json
- apps/ledger-live-desktop/src/renderer/components/WebPlatformPlayer/WebViewV2.tsx
- apps/ledger-live-mobile/package.json
- apps/ledger-live-mobile/src/components/WebPlatformPlayer/WebViewV2.tsx
- libs/ledger-live-common/package.json
- libs/ledger-live-common/src/wallet-api/react.ts
- pnpm-lock.yaml
This PR provides `useWalletAPIServer` hook to easily set up server with React component. This change allows us to shares more logic between desktop and mobile.
- **Impacted projects**: `ledger-live-desktop`, `ledger-live-mobile`, `ledger-live-common` 
- **Linked resource(s)**: [`LIVE-4852`](https://ledgerhq.atlassian.net/browse/LIVE-4852) 
> Introduce useWalletAPIServer hook

- .changeset/sweet-mice-suffer.md
- apps/ledger-live-desktop/src/renderer/screens/account/index.jsx
- apps/ledger-live-desktop/src/renderer/screens/account/useGetBannerProps.ts
Fixes an issue whereby we were showing the ethereum staking banner on ethereum token account screens.
> fix: LLD - stop showing staking banner on ethereum tokens

- .changeset/rich-carpets-divide.md
- libs/coin-framework/src/env.ts
There was a warning at every start of LLD:
```
Invalid ENV value for FEATURE_FLAGS
```
Because of this:
```ts
if (value === undefined || value === null) {
console.warn(`Invalid ENV value for ${name}`);
return false;
}
```
and the fact that the `FEATURE_FLAGS` variable default was `""` which is parsed (with JSON.parse) as `undefined`.
So I replaced the default value `""` by `"{}"` which is parsed as a plain empty object, and that doesn't break the expected behaviour for overriding feature flags with the env variable:
```ts
function getFeature(key) {
// ...
const envFlags = getEnv("FEATURE_FLAGS") as
| { [key in FeatureId]?: Feature }
| undefined;
if (allowOverride && envFlags) {
const feature = envFlags[key];
if (feature)
return {
...feature,
overridesRemote: true,
overriddenByEnv: true, …
```
> fix(env.ts): add default non-undefined value for FEATURE_FLAGS json

- .github/workflows/test-desktop.yml
- apps/ledger-live-desktop/src/index.js
> ci: test merge queues NO MERGE

- apps/ledger-live-mobile/src/index.tsx
> ci: test merge queues DONT MERGE

- .github/workflows/build-desktop.yml
- .github/workflows/build-mobile.yml
- .github/workflows/gate.yml
- .github/workflows/test-mobile-e2e.yml
- pnpm-lock.yaml
- tools/actions/turbo-affected/action.yml
- tools/actions/turbo-affected/build/main.js
- tools/actions/turbo-affected/src/main.ts
- tools/github-bot/api/github/webhooks/index.ts
- tools/github-bot/package.json
- tools/github-bot/src/features/orchestrator/const.ts
- tools/github-bot/src/features/orchestrator/index.ts
- tools/github-bot/src/features/orchestrator/tools.ts
- tools/github-bot/src/features/upToDate/index.ts
- tools/github-bot/src/tools/index.ts
- tools/github-bot/src/tools/monitorWorkflow.ts
Add support for [merge groups](https://github.blog/changelog/2022-08-18-merge-group-webhook-event-and-github-actions-workflow-trigger/). 🥳 
N/A
> ci: add theoretical support for merge groups

- .changeset/hot-apricots-develop.md
- libs/ledger-live-common/src/api/Ethereum.ts
reduce explorer requests payload on eth family
Add noinput parameter for reduced payload
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5490 
> feat: add noinput parameter for reduced payload

- .changeset/gorgeous-boxes-refuse.md
- apps/ledger-live-desktop/src/renderer/index.js
jamais deux sans trois 
Problem: in some cases, Ledger Live Desktop don't properly set the env from process.env : when our JS code expected getEnv() value to be available and settled at boot time.
To fix this, we simply can load the module that do the setEnv (experimental.tsx in the current case of LLD) before the rest of our codebase (notably of coin implementations)
A way to reproduce the issue:
```
EXPERIMENTAL_EXECUTION_ON_RENDERER=1 API_STELLAR_HORIZON=https://stellar.coin.ledger-stg.com pnpm dev:lld
```
and when you sync a stellar account, it was still using the production one (see in Network panel) because the stellar impl have a getEnv() call at the module level: https://github.com/LedgerHQ/ledger-live/blob/develop/libs/ledger-live-common/src/families/stellar/api/horizon.ts#L26 …
> fix: load envs at js boot

- .changeset/big-planes-jog.md
- .changeset/silver-sloths-obey.md
- apps/ledger-live-desktop/src/renderer/families/near/StakeBanner.tsx
- apps/ledger-live-desktop/src/renderer/screens/account/AccountStakeBanner.tsx
- apps/ledger-live-desktop/static/i18n/en/app.json
- libs/ledger-live-common/src/families/near/banner.test.ts
- libs/ledger-live-common/src/families/near/banner.ts
Add stake banner to near account
- **Impacted projects**: LLD | Common
- **Linked resource(s)**:  https://ledgerhq.atlassian.net/browse/LIVE-5091
> Feat: lld show near staking banner

- apps/ledger-live-mobile/src/components/ServicesWidget/Protect/NewProtectState.tsx
- apps/ledger-live-mobile/src/components/ServicesWidget/index.tsx
- apps/ledger-live-mobile/src/screens/Manager/index.tsx
Make the entire Protect card in My Ledger card clickable (it opens the upsell page in Protect platform) if status is `NEW` 
- **Linked resource(s)**: [LIVE-5330](https://ledgerhq.atlassian.net/browse/LIVE-5330)
[LIVE-5330]: https://ledgerhq.atlassian.net/browse/LIVE-5330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feat / Protect - whole ledger protect card clickable

- .changeset/two-wolves-visit.md
- apps/ledger-live-desktop/src/renderer/families/cosmos/AccountHeaderManageActions.js
- apps/ledger-live-desktop/src/renderer/families/elrond/AccountHeaderManageActions.js
- apps/ledger-live-desktop/src/renderer/families/near/AccountHeaderManageActions.js
- apps/ledger-live-desktop/src/renderer/families/tron/AccountHeaderManageActions.js
Remove extra no funds modal case for:
Tron
Near
Elrond
Cosmos
Osmos
- https://ledgerhq.atlassian.net/browse/LIVE-5709
> fix: remove extra no funds modal case for multiple coins

- .changeset/stale-turtles-remember.md
- libs/ui/packages/native/src/components/Layout/List/VerticalStepper/StepperItem.tsx
- libs/ui/packages/native/src/components/Layout/List/VerticalStepper/index.tsx
- libs/ui/packages/native/src/components/Layout/List/VerticalTimeline/TimelineIndicator.tsx
- libs/ui/packages/native/src/components/Layout/List/VerticalTimeline/TimelineItem.tsx
- libs/ui/packages/native/src/components/Layout/List/index.ts
- libs/ui/packages/native/src/components/Layout/List/types.ts
- libs/ui/packages/native/storybook/stories/Layout/List/VerticalStepper.stories.tsx
- Add a new `VerticalStepper` component in Native UI
- Add a debug menu for the OS update UI taking advantage of the new component from Native UI
- **Impacted projects**: `ledger-live-mobile`, `native-ui` 
- **Linked resource(s)**: [FAT-499] 
[FAT-499]: https://ledgerhq.atlassian.net/browse/FAT-499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add new components to Native UI for the new OS update UI on LLM

- apps/ledger-live-desktop/src/renderer/families/avalanchepchain/DelegationFlowModal/steps/StepEndDate.jsx
Updating the date formatting of end date step's banner to better match the user's locale.
> feat: update end date banner text formatting

- .github/workflows/cal-importer.yml
ReOpen PR for https://github.com/LedgerHQ/ledger-live/pull/2720
Sync generates cryptoassets json files to staging environment.
> ci: sync generated json files to STG

- .changeset/strange-ways-punch.md
- apps/ledger-live-mobile/src/components/TabBar/Transfer.tsx
Improve the animation of the main transfer CTA on LLM
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-5827` 
https://user-images.githubusercontent.com/4631227/220573242-d8b6e0bf-2a85-477f-845b-12cf4eb9b293.mov
https://user-images.githubusercontent.com/4631227/220573250-280a2228-e414-446e-aee6-65dd7e5e32a7.mov
Just look at the animations and make sure nothing else is broken
> fix: Main transfer animation improvement

- .changeset/eighty-camels-care.md
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FeesDrawer/index.jsx
Fix swap drawer left padding
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5839
> fix: LIVE-5839 fix swap drawer left padding

- .changeset/cyan-numbers-judge.md
- apps/ledger-live-mobile/android/app/src/main/AndroidManifest.xml
- apps/ledger-live-mobile/ios/Podfile.lock
- apps/ledger-live-mobile/package.json
- pnpm-lock.yaml
Fixes the android webview camera usage
Also updates the `react-native-webview` package
https://user-images.githubusercontent.com/3009753/221158205-22fa9af9-da53-45d4-a641-835ce5ed986f.mov
https://user-images.githubusercontent.com/3009753/221158306-4d92bed1-260f-40c9-a90f-74bf2583f164.mov
> fix: android webview camera and audio

- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/scenes/RestoreWithProtect.tsx
Rewording of Restore using Ledger Recover screen and its drawer
- **Linked resource(s)**: [LIVE-5502](https://ledgerhq.atlassian.net/browse/LIVE-5502)
Screen |Drawer
:-----------------------:|:-----------------------:
[LIVE-5502]: https://ledgerhq.atlassian.net/browse/LIVE-5502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: rewording of restore with ledger recover

- .changeset/mighty-cherries-train.md
- .changeset/swift-flies-eat.md
- apps/ledger-live-mobile/src/actions/appstate.ts
- apps/ledger-live-mobile/src/actions/types.ts
- apps/ledger-live-mobile/src/components/FirmwareUpdateBanner.tsx
- apps/ledger-live-mobile/src/hooks/useListenToHidDevices.ts
- apps/ledger-live-mobile/src/index.tsx
- apps/ledger-live-mobile/src/reducers/appstate.ts
- apps/ledger-live-mobile/src/reducers/types.ts
The current logic on LLM for asking the user to plug in a wired device on the firmware update banner is governed by whether the last seen device was wired or not. This means that if I connected a Nano X and accessed the manager, and said device needs a firmware update, we would show the banner. However!, if the user plugs the device and tries to follow that banner, they will see a message asking them to plug in the device, which is already plugged in.
Supporting live USB device connectivity awareness on LLM allows us to know whether there's a plugged in device at the time of interacting with the banner and, therefore, show the right message. In this case redirect to the device selector. …
> bugfix/LIVE-5833 Incorrect prompt to plug USB on FW Update Banner

- .changeset/twelve-months-agree.md
- apps/ledger-live-mobile/.eslintrc.js
- apps/ledger-live-mobile/package.json
- apps/ledger-live-mobile/src/components/CustomImage/ImageCropper.tsx
- apps/ledger-live-mobile/src/components/DelegationInfo.tsx
- apps/ledger-live-mobile/src/components/Nft/NftCard.tsx
- apps/ledger-live-mobile/src/components/OperationRowNftName.tsx
- apps/ledger-live-mobile/src/families/tezos/DelegationFlow/SelectValidator.tsx
- apps/ledger-live-mobile/src/families/tron/VoteFlow/02-VoteCast.tsx
- apps/ledger-live-mobile/src/families/tron/VoteFlow/02-VoteModal.tsx
- apps/ledger-live-mobile/src/families/tron/VoteFlow/02-VoteRow.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Account/NftCollectionsList.tsx
- apps/ledger-live-mobile/src/screens/Account/SubAccountsList.tsx
- apps/ledger-live-mobile/src/screens/Exchange/ProviderList.tsx
- apps/ledger-live-mobile/src/screens/FirmwareUpdate/01-ReleaseNotes.tsx
- apps/ledger-live-mobile/src/screens/ImportAccounts/DisplayResult.tsx
- apps/ledger-live-mobile/src/screens/NotificationCenter/Notifications.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/scenes/ConnectNano.tsx
- apps/ledger-live-mobile/src/screens/OperationDetails/Title.tsx
- apps/ledger-live-mobile/src/screens/Platform/CatalogTwitterBanner.tsx
- apps/ledger-live-mobile/src/screens/SendFunds/01c-SelectNft.tsx
- apps/ledger-live-mobile/src/screens/SendFunds/SummaryNft.tsx
- pnpm-lock.yaml
On issue #2249, it was identified that there was a requirement for detecting untranslated string literals on LLM (and possibly LLD, depending on feasibility). I took it upon myself to address this need, by reviewing the codebase and resolving all missing translations. I excluded any untranslated strings that originated from a debug menu or mock UI component, although it is worth noting that these should eventually be translated as well, albeit with a low priority.
For cases where an untranslated string must be used, as long as it conforms to the ignore pattern defined in the eslint configuration, it will be deemed acceptable. Essentially, if the string consists solely of symbols, spaces, or capital letters, it will not trigger the rule, thereby enabling the inclusion of dev buttons, …
> feat/LIVE-5914: introduce lint rule to detect untranslated strings

- .changeset/tall-seals-rest.md
- apps/ledger-live-desktop/src/renderer/screens/platform/Catalog.jsx
Adding condition to the disclaimer to prevent it from being displayed on Ledger's apps.
- **Linked resource(s)**: `LIVE-5163` 
> Adding condition to disclaimer

- .github/workflows/cal-importer.yml
Add parameter to s3 bucket dynamic cal importer
- **Impacted projects**: `workflow` 
> ci: add acl public-read to prod cal importer

- .changeset/tricky-ears-boil.md
- libs/ledger-live-common/src/account/serialization.ts
- libs/ledger-live-common/src/families/tron/bridge/js.ts
- libs/ledger-live-common/src/families/tron/react.test.ts
- libs/ledger-live-common/src/families/tron/serialization.ts
- libs/ledger-live-common/src/reconciliation.ts
Remove coin specific logic outside of tron family
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-4950 
> [LIVE-4950] Tron coin mod

- .changeset/nice-shoes-agree.md
- .changeset/serious-dryers-pretend.md
- apps/cli/src/commands/appsCheckAllAppVersions.ts
- libs/ledger-live-common/src/apps/hw.ts
This is a PR to help @xchapron-ledger create the PR without having to setup monorepo on his machine.
- **Impacted projects**: `cli, live-common` 
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-5930` 
No demo
> feat: live-5930 disable security key from version check

- .changeset/thick-ducks-reply.md
- apps/ledger-live-mobile/src/components/WebPlatformPlayer/WebViewV2.tsx
- apps/ledger-live-mobile/src/components/WebPlatformPlayer/index.tsx
Hides the WebView header if it is Ledger Recover
- [LIVE-5129](https://ledgerhq.atlassian.net/browse/LIVE-5129)
- [LIVE-5488](https://ledgerhq.atlassian.net/browse/LIVE-5488)
[LIVE-5129]: https://ledgerhq.atlassian.net/browse/LIVE-5129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-5488]: https://ledgerhq.atlassian.net/browse/LIVE-5488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: hide webview header if ledger recover

- apps/ledger-live-mobile/src/components/ServicesWidget/types.ts
- apps/ledger-live-mobile/src/config/urls.tsx
- apps/ledger-live-mobile/src/screens/Protect/Login.tsx
Adds a forgot password link in Ledger Recover login page
- **Linked resource(s)**: [LIVE-5130](https://ledgerhq.atlassian.net/browse/LIVE-5130)
[LIVE-5130]: https://ledgerhq.atlassian.net/browse/LIVE-5130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: forgot password link in lr login page

- apps/ledger-live-mobile/src/components/ServicesWidget/Protect/ActiveProtectState.tsx
- apps/ledger-live-mobile/src/components/ServicesWidget/Protect/AddPaymentProtectState.tsx
- apps/ledger-live-mobile/src/components/ServicesWidget/Protect/ConfirmIdentityProtectState.tsx
- apps/ledger-live-mobile/src/components/ServicesWidget/Protect/NewProtectState.tsx
- apps/ledger-live-mobile/src/components/ServicesWidget/Protect/PaymentRejectedProtectState.tsx
- apps/ledger-live-mobile/src/components/ServicesWidget/Protect/SubscriptionCanceledProtectState.tsx
- apps/ledger-live-mobile/src/config/urls.tsx
Adds a param `source` to Protect Live app URLs
- **Impacted projects**: `ledgerlive-mobile`
- **Linked resource(s)**: [LIVE-4955]
[LIVE-4955]: https://ledgerhq.atlassian.net/browse/LIVE-4955
> feat: source param in ledger recover deeplinks

- .changeset/dull-radios-walk.md
- libs/ledger-live-common/src/api/Ethereum.test.ts
- libs/ledger-live-common/src/api/Ethereum.ts
- libs/ledger-live-common/src/families/ethereum/synchronisation.test.ts
- libs/ledger-live-common/src/families/ethereum/synchronisation.ts
eth use token for pagination
Use token for pagination for ethereum transaction retrieval
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5603 
> feat: ethereum explorer tx pagination

- .changeset/friendly-turkeys-dress.md
- libs/ledger-live-common/src/account/serialization.ts
- libs/ledger-live-common/src/families/celo/bridge/js.ts
- libs/ledger-live-common/src/families/celo/serialization.ts
- libs/ledger-live-common/src/reconciliation.ts
Remove coin specific logic outside of celo family
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-4937 
[LIVE-4937]: https://ledgerhq.atlassian.net/browse/LIVE-4937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIVE-4937] Coin mod celo

- .changeset/sixty-spies-impress.md
- .pnpmfile.cjs
- apps/ledger-live-mobile/.eslintrc.js
- apps/ledger-live-mobile/.gitignore
- apps/ledger-live-mobile/babel.config.js
- apps/ledger-live-mobile/e2e/babel.config.detox.js
- apps/ledger-live-mobile/e2e/jest.config.js
- apps/ledger-live-mobile/jest-setup.js
- apps/ledger-live-mobile/jest.config.js
- apps/ledger-live-mobile/package.json
- apps/ledger-live-mobile/src/__test__/test-renderer.tsx
- apps/ledger-live-mobile/src/components/LText/LText.test.tsx
- apps/ledger-live-mobile/src/components/LText/index.tsx
- apps/ledger-live-mobile/src/components/WebPlatformPlayer/liveSDKLogic.test.ts
- apps/ledger-live-mobile/tsconfig.json
- libs/ui/packages/crypto-icons/package.json
- libs/ui/packages/icons/package.json
- libs/ui/packages/native/package.json
- pnpm-lock.yaml
Addition of React Testing Library to unit test UI Components 
- Add react-testing-library
- Add a jest config and jest setup to run tests
- add a custom test renderer to include all our providers
> Setup react testing library in llm

- .changeset/chilly-ties-scream.md
- libs/ledger-live-common/src/__tests__/accounts/groupPerDay.ts
- libs/ledger-live-common/src/account/serialization.ts
- libs/ledger-live-common/src/families/tezos/bridge/js.ts
- libs/ledger-live-common/src/families/tezos/serialization.ts
- libs/ledger-live-common/src/reconciliation.ts
Remove tezos specific code outside of tezos family
- **Linked resource(s)**: `LIVE-4949` 
> [LIVE-4949] Tezos coin modularization

- .changeset/poor-toes-wash.md
- libs/ledger-live-common/src/account/serialization.ts
- libs/ledger-live-common/src/families/elrond/bridge/js.ts
- libs/ledger-live-common/src/families/elrond/js-signOperation.ts
- libs/ledger-live-common/src/families/elrond/js-synchronisation.ts
- libs/ledger-live-common/src/families/elrond/serialization.ts
- libs/ledger-live-common/src/reconciliation.ts
remove coin specific logic outside of elrond folder
Remove coin specific logic outside elrond family folder
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-4940` 
> [LIVE-4940] Coin modularization elrond

- apps/ledger-live-mobile/ios/ledgerlivemobile.xcodeproj/project.pbxproj
This reverts commit f0f2e75774a14cf2d5808926c79f8e33374db790, reversing changes made to 9172d0ef621ee8cc1c64a9d0e4cbc18ff42eee6d.
Reverts https://github.com/LedgerHQ/ledger-live/pull/2793
> Revert "Merge pull request #2793 from LedgerHQ/support/ios-builds-improvement"

- .github/workflows/release-prerelease.yml
Adds inputs to pre release flow for Recover LLM
> chore(recover): add input to pre release flow

- .changeset/smooth-insects-look.md
- libs/ledger-live-common/src/account/serialization.ts
- libs/ledger-live-common/src/families/cosmos/__snapshots__/bridge.integration.test.ts.snap
- libs/ledger-live-common/src/families/cosmos/bridge/js.ts
- libs/ledger-live-common/src/families/cosmos/js-synchronisation.ts
- libs/ledger-live-common/src/families/cosmos/serialization.ts
- libs/ledger-live-common/src/reconciliation.ts
remove coin specific logic outside of cosmos coin family
Cosmos coin modularization step 2 : implement 3 new method in the bridge for the cosmos family
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-4938 
> feat: cosmos coin modularization

- .changeset/happy-birds-share.md
- apps/ledger-live-mobile/android/.project
- apps/ledger-live-mobile/src/components/BleDevicePairingFlow/BleDevicePairing.tsx
- apps/ledger-live-mobile/src/components/BleDevicePairingFlow/BleDevicesScanning.tsx
- apps/ledger-live-mobile/src/components/BleDevicePairingFlow/index.tsx
- apps/ledger-live-mobile/src/components/DeviceAction/InstallSetOfApps/index.tsx
- apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx
- apps/ledger-live-mobile/src/components/DeviceLanguageInstalled.tsx
- apps/ledger-live-mobile/src/index.tsx
- apps/ledger-live-mobile/src/screens/ClaimNft/ClaimNftQrScan.tsx
- apps/ledger-live-mobile/src/screens/ClaimNft/ClaimNftWelcome.tsx
- apps/ledger-live-mobile/src/screens/Manager/Device/DeviceLanguage.tsx
- apps/ledger-live-mobile/src/screens/Manager/Device/DeviceLanguageSelection.tsx
- apps/ledger-live-mobile/src/screens/PostOnboarding/PostOnboardingHub.tsx
- apps/ledger-live-mobile/src/screens/SyncOnboarding/DesyncDrawer.tsx
- apps/ledger-live-mobile/src/screens/SyncOnboarding/FirmwareUpdateDrawer.tsx
- apps/ledger-live-mobile/src/screens/SyncOnboarding/GenuineCheckCancelledDrawer.tsx
- apps/ledger-live-mobile/src/screens/SyncOnboarding/GenuineCheckDrawer.tsx
- apps/ledger-live-mobile/src/screens/SyncOnboarding/LanguageSelect.tsx
- apps/ledger-live-mobile/src/screens/SyncOnboarding/ResyncOverlay.tsx
- apps/ledger-live-mobile/src/screens/SyncOnboarding/SoftwareChecksStep.tsx
- apps/ledger-live-mobile/src/screens/SyncOnboarding/index.tsx
- libs/ledger-live-common/mobile-test-app/android/.project
- libs/ledger-live-common/mobile-test-app/android/.settings/org.eclipse.buildship.core.prefs
This PR add analytics to LLM sync onboarding
- **Linked resource(s)**: [FAT-822] [FAT-823] [FAT-825] [FAT-826]
[FAT-822]: https://ledgerhq.atlassian.net/browse/FAT-822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAT-823]: https://ledgerhq.atlassian.net/browse/FAT-823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAT-825]: https://ledgerhq.atlassian.net/browse/FAT-825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …
> add analytics to LLM sync onboarding, claim NFT, install/restore apps and generics

- apps/cli/src/commands-index.ts
- apps/cli/src/commands/deviceSDKFirmwareUpdate.ts
- apps/ledger-live-mobile/src/components/FirmwareUpdate/index.tsx
- apps/ledger-live-mobile/src/components/FirmwareUpdateBanner.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/SettingsNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/types/SettingsNavigator.ts
- apps/ledger-live-mobile/src/const/navigation.ts
- apps/ledger-live-mobile/src/screens/Manager/AppsScreen.tsx
- apps/ledger-live-mobile/src/screens/Manager/Manager.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/Features/FirmwareUpdate.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/Features/index.tsx
- libs/ledger-live-common/src/api/Manager.ts
- libs/ledger-live-common/src/deviceSDK/actions/updateFirmware.ts
- libs/ledger-live-common/src/deviceSDK/commands/firmwareUpdate/flashMcuOrBootloader.ts
- libs/ledger-live-common/src/deviceSDK/commands/firmwareUpdate/installFirmware.ts
- libs/ledger-live-common/src/deviceSDK/commands/getVersion.ts
- libs/ledger-live-common/src/deviceSDK/commands/quitApp.ts
- libs/ledger-live-common/src/deviceSDK/hooks/useUpdateFirmware.ts
- libs/ledger-live-common/src/deviceSDK/mocks/aTransportRef.ts
- libs/ledger-live-common/src/deviceSDK/tasks/core.test.ts
- libs/ledger-live-common/src/deviceSDK/tasks/core.ts
- libs/ledger-live-common/src/deviceSDK/tasks/getDeviceInfo.ts
- libs/ledger-live-common/src/deviceSDK/tasks/getLatestFirmware.ts
- libs/ledger-live-common/src/deviceSDK/tasks/updateFirmware.test.ts
- libs/ledger-live-common/src/deviceSDK/tasks/updateFirmware.ts
- libs/ledger-live-common/src/deviceSDK/transports/core.ts
- libs/ledger-live-common/src/hooks/useLatestFirmware.ts
This creates a new device action using the new proposed device action paradigm for performing firmware updates (which weren't handled by device actions so far).
This PR contains only the first milestone for a complete firmware update, which works only for updates that require a SE upgrade only (defined in [FAT-736]). Updates including flashes to the Bootloaded and MCU will come in a different PR.  
- **Linked resource(s)**: [FAT-736](https://ledgerhq.atlassian.net/browse/FAT-736), [FAT-766](https://ledgerhq.atlassian.net/browse/FAT-766), [FAT-767](https://ledgerhq.atlassian.net/browse/FAT-767)
- [Not yet] **Test coverage** 
[FAT-736]: https://ledgerhq.atlassian.net/browse/FAT-736?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …
> FAT-736 FAT-766 FAT-767: New device action for the Firmware update

- .changeset/sweet-kiwis-fail.md
- apps/ledger-live-mobile/src/components/Nft/NftGallery/AddNewItemList.tsx
- apps/ledger-live-mobile/src/components/Nft/NftGallery/NftList.hook.ts
- apps/ledger-live-mobile/src/components/Nft/NftGallery/NftList.tsx
- apps/ledger-live-mobile/src/components/Nft/NftGallery/NftListItem.tsx
- apps/ledger-live-mobile/src/components/Nft/NftGallery/NftListItemFloorPriceRow.tsx
- apps/ledger-live-mobile/src/screens/CustomImage/NFTGallerySelector.tsx
- apps/ledger-live-mobile/src/screens/Nft/WalletNftGallery/index.tsx
Replace nft gallery item collection title row by a new row containing the floor price of the collection and the countervalue of it
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-4910
https://user-images.githubusercontent.com/89014981/222196452-c3bde2bc-50b7-49a4-a4bb-bd87e6ac8204.mp4
> Feat/LIVE-4910 - NFT Gallery - Add floor price to NFT Gallery items

- .changeset/stupid-rivers-repeat.md
- apps/ledger-live-mobile/src/config/urls.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/scenes/RestoreWithProtect.tsx
Updated support URL for Protect nanoX update modals
- **Linked resource(s)**: [LIVE-5861]
N/A
[LIVE-5861]: https://ledgerhq.atlassian.net/browse/LIVE-5861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LLM - Recover - update support URL

- .changeset/tough-teachers-perform.md
- apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/Header.tsx
New Wallet Connect entry point in LLM portfolio page (header). Added Upsell for reborn mode.
- **Linked resource(s)**: [LIVE-5864]
https://user-images.githubusercontent.com/39890664/224098861-01960d69-16c4-412b-9c1d-969bae766f42.mp4
[LIVE-5864]: https://ledgerhq.atlassian.net/browse/LIVE-5864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LLM - Wallet Connect New entry point

- .changeset/hungry-falcons-tan.md
- libs/ledgerjs/packages/hw-app-eth/README.md
- libs/ledgerjs/packages/hw-app-eth/src/Eth.ts
- libs/ledgerjs/packages/hw-app-eth/tests/Eth.unit.test.ts
This PR adds a new method `clearSignTransaction` which will handle both transaction`resolution` and transaction `signature` with optional failure resilience for the resolution.
This method will be used by `Connect` in order to remove tech debt on their side (copy pasting `hw-app-eth` basically in order to wrap it in Swift).
- **Impacted projects**: `hw-app-eth` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5077 
> [LIVE-5077] Feature: `hw-app-eth` all-in-one clear signing method

- tools/actions/composites/update-snapshots-desktop/action.yml
update-snapshots-desktop ci job now respects commit convention
> ci(update-snapshots-desktop): conventional commit implementation

- .changeset/bright-lions-battle.md
- apps/ledger-live-mobile/src/families/celo/accountActions.tsx
- apps/ledger-live-mobile/src/families/cosmos/accountActions.tsx
- apps/ledger-live-mobile/src/families/elrond/accountActions.tsx
- apps/ledger-live-mobile/src/families/ethereum/accountActions.tsx
- apps/ledger-live-mobile/src/families/near/accountActions.tsx
- apps/ledger-live-mobile/src/families/polkadot/accountActions.tsx
- apps/ledger-live-mobile/src/families/solana/accountActions.tsx
- apps/ledger-live-mobile/src/families/tezos/accountActions.tsx
- apps/ledger-live-mobile/src/families/tron/accountActions.tsx
- apps/ledger-live-mobile/src/screens/Account/hooks/useAccountActions.tsx
Update UI Button in account
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-6720
> Feat/llm/move stake button to main buttons LIVE-6720

- libs/ledger-live-common/src/families/hedera/api/mirror.ts
Fix mirror.ts to get all operations.
> fix: get all operations from mirror

- .changeset/real-peas-live.md
- libs/ledger-live-common/src/families/hedera/api/network.ts
Separate Hedera client created for balance specific queries
> feat: create client specifically to get balance

- tools/github-bot/README.md
Add a better README to the live-github-bot project
- **Impacted projects**: `live-github-bot` 
New shiny README
> documentation: github bot readme

- .changeset/sixty-singers-move.md
- apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/index.jsx
There were duplicate entries in the dev menu on LLD, this fixes that.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-6789` 
No demo
No duplicates
> fix(dev-tools): LIVE-6789 remove duplicated entries in dev menu LLD

- .changeset/quiet-snails-fold.md
- apps/ledger-live-mobile/src/actions/settings.ts
- apps/ledger-live-mobile/src/actions/types.ts
- apps/ledger-live-mobile/src/components/AssetCentricGraphCard.tsx
- apps/ledger-live-mobile/src/components/DateFormat/FormatDate.tsx
- apps/ledger-live-mobile/src/components/DateFormat/FormatDay.tsx
- apps/ledger-live-mobile/src/components/DateFormat/FormatRelativeTime.tsx
- apps/ledger-live-mobile/src/components/DateFormat/formatter.util.ts
- apps/ledger-live-mobile/src/components/DoubleCountervalue.tsx
- apps/ledger-live-mobile/src/components/GraphCard.tsx
- apps/ledger-live-mobile/src/components/SectionHeader.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/reducers/settings.ts
- apps/ledger-live-mobile/src/reducers/types.ts
- apps/ledger-live-mobile/src/screens/Lending/ClosedLoans/ClosedLoansRow.tsx
- apps/ledger-live-mobile/src/screens/Newsfeed/index.tsx
- apps/ledger-live-mobile/src/screens/OperationDetails/Content.tsx
- apps/ledger-live-mobile/src/screens/Settings/General/DateFormatDrawer.tsx
- apps/ledger-live-mobile/src/screens/Settings/General/DateFormatRow.tsx
- apps/ledger-live-mobile/src/screens/Settings/General/index.tsx
- apps/ledger-live-mobile/src/screens/Swap/SubScreens/OperationDetails.tsx
LLM - Date Format: new entry added to choose date format display in LLM 
- Default (Based on Language)
- DD/MM/YYYY
- MM/DD/YYYY
- **Linked resource(s)**: [LIVE-3796] 
https://user-images.githubusercontent.com/112866305/224984284-6350085b-5592-41e9-a0ac-0139608e0aba.mov
[LIVE-3796]: https://ledgerhq.atlassian.net/browse/LIVE-3796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FEAT]: LIVE-3796 Date Format in LLM

- .changeset/popular-ligers-confess.md
- apps/ledger-live-mobile/src/families/celo/accountActions.tsx
- apps/ledger-live-mobile/src/families/cosmos/accountActions.tsx
- apps/ledger-live-mobile/src/families/elrond/accountActions.tsx
- apps/ledger-live-mobile/src/families/ethereum/accountActions.tsx
- apps/ledger-live-mobile/src/families/near/accountActions.tsx
- apps/ledger-live-mobile/src/families/polkadot/accountActions.tsx
- apps/ledger-live-mobile/src/families/solana/accountActions.tsx
- apps/ledger-live-mobile/src/families/tezos/accountActions.tsx
- apps/ledger-live-mobile/src/families/tron/accountActions.tsx
- Tezos implementation was not done.
- Track stake account button is done here
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5233
> Bugfix/llm/fix stake account btn integration LIVE-5233

- .changeset/hot-tips-protect.md
- libs/ledger-live-common/src/account/serialization.ts
- libs/ledger-live-common/src/families/bitcoin/bridge/js.ts
- libs/ledger-live-common/src/families/bitcoin/descriptor.test.ts
- libs/ledger-live-common/src/families/bitcoin/js-synchronisation.ts
- libs/ledger-live-common/src/families/bitcoin/satstack.test.ts
- libs/ledger-live-common/src/families/bitcoin/serialization.test.ts
- libs/ledger-live-common/src/families/bitcoin/serialization.ts
- libs/ledger-live-common/src/migrations/accounts-dataset.ts
remove btc logic outside of its folder
BTC coin modularization step 2
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-4934 
> feat: Bitcoin coin modularization

- .changeset/flat-donkeys-behave.md
- libs/ledger-live-common/src/bot/portfolio/__snapshots__/formatter.test.ts.snap
- libs/ledgerjs/packages/cryptoassets/src/currencies.ts
> feat: update Hedera Explorer links

- .changeset/few-games-melt.md
- apps/ledger-live-mobile/src/screens/Account/hooks/useAccountActions.tsx
Change stake button to 3rd place
- **Linked resource(s)**:  https://ledgerhq.atlassian.net/browse/LIVE-5233
> fix: fix account order main buttons

- .changeset/silly-forks-train.md
- apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/StakeFlowNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/types/BaseNavigator.ts
- apps/ledger-live-mobile/src/components/RootNavigator/types/StakeNavigator.ts
- apps/ledger-live-mobile/src/components/Stake/index.tsx
- apps/ledger-live-mobile/src/components/TabBar/TransferDrawer.tsx
- apps/ledger-live-mobile/src/const/navigation.ts
- apps/ledger-live-mobile/src/families/ethereum/accountActions.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
Common stake flow integrated in the main menu
Ghost page which use select account flow to redirect to stake programs
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5229
https://user-images.githubusercontent.com/38540290/225891198-f493cd90-b987-4e9e-b5fc-dbd90d36146e.mov
> Feat/lld/add common stake flow 

- .changeset/silly-planets-bake.md
- libs/ledger-live-common/src/families/solana/api/chain/web3.ts
- libs/ledger-live-common/src/families/solana/bridge.integration.test.ts
- libs/ledger-live-common/src/families/solana/js-estimateMaxSpendable.ts
- libs/ledger-live-common/src/families/solana/js-prepareTransaction.ts
- libs/ledger-live-common/src/families/solana/logic.ts
Solana accounts require a minimum balance to be considered rent exempted (to not pay rent) to stay on the chain. This PR makes Ledger Live validate that an account has the minimum balance required after transfer and staking.
- **Impacted projects**: `live-common, LLD, LLM`
- https://ledgerhq.atlassian.net/browse/LIVE-5399 
- [Solana rent docs](https://docs.solana.com/developing/programming-model/accounts#rent)
- Ledger Live should make sure accounts have the minimum  balance after transfer and staking.
> [LIVE-5399] Bugfix - Solana: introduce minimum rent exemption balance

- apps/ledger-live-mobile/e2e/specs/languageChange.spec.ts
_Fix portugues language selection._
- **Linked resource(s)**: [`Test PASS`](https://github.com/LedgerHQ/ledger-live/actions/runs/4468125290) 
> [B2CQA-1718] Detox : fix language selection test

- .changeset/forty-pants-search.md
- libs/ledger-live-common/src/account/serialization.ts
Some cleaning was missing in last polkadot coin mod pr
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-4945` 
> feat: remove polkadot serialization

- apps/ledger-live-desktop/.gitignore
- apps/ledger-live-desktop/release-notes.json
ignore generated release notes file (LLD)
> chore: ignore generated release notes file

- .changeset/eighty-emus-press.md
- apps/ledger-live-desktop/src/renderer/components/TroubleshootNetworkButton.jsx
- apps/ledger-live-desktop/src/renderer/modals/TroubleshootNetwork/Body.jsx
**this feature was broken by the recent rework of internal:**
**it is now fixed:**
+ also wrong analytics label on the feature
> fixes: restore troubleshoot networking debug feature

- .changeset/sixty-cooks-occur.md
- apps/ledger-live-mobile/src/components/AccountCard.tsx
- apps/ledger-live-mobile/src/components/CurrencyIcon.tsx
UI for the list of accounts on the add account flow was rendering a broken icon where the background matched the wrong theme. I aligned with Aamir on the design and it should look like [this](https://ledger.slack.com/archives/C02PQA777EU/p1678376182429649?thread_ts=1678375050.412379&cid=C02PQA777EU).
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-6717` 
- Check the icons look good and not like the first image
> fix(ui): broken ui on add account flow list

- apps/ledger-live-desktop/src/renderer/IPCTransport.md
- apps/ledger-live-desktop/src/renderer/webworkers/README.md
document even more the PR #2859 
- **Impacted projects**: `doc` 
> Add LLD architecture documentation for IPCTransport and web workers

- apps/ledger-live-desktop/tests/specs/general/stability.spec.ts
test appears flawky. i think the balance takes forever to appear. we don't care about the balance in this test, its only purpose is to wait 5s on two screens and check it doesn't crash with real accounts like it could have in the past on very bad case.
> chore: stabilize the stability test =)

- .changeset/curly-spies-provide.md
- apps/ledger-live-desktop/src/renderer/families/cosmos/StakeBanner.tsx
Add track to Cosmos/Osmos account banner
- **Linked resource(s)**:  https://ledgerhq.atlassian.net/browse/LIVE-6744
> fix: add track cosmos/osmos account banner

- .changeset/serious-toes-turn.md
- apps/ledger-live-desktop/src/live-common-set-supported-currencies.js
- apps/ledger-live-mobile/src/live-common-setup.ts
- libs/ledger-live-common/src/account/serialization.ts
- libs/ledger-live-common/src/families/crypto_org/bridge/js.ts
- libs/ledger-live-common/src/families/crypto_org/serialization.test.ts
- libs/ledger-live-common/src/families/crypto_org/serialization.ts
remove coin specific logic outside its family folder
Remove cryptoorg coin specific logic outside of its family folder
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-4939 
> feat: Cryptoorg coin modularization

- .github/workflows/test-mobile-e2e.yml
_We want to monitor Detox fails. For this we notify [live-qa-alerts](https://ledger.slack.com/archives/CTMQ0S5SB/) Slack channel whenever they fail for develop branch._
> [B2CQA-1720] Report Detox tests fail for develop branch on slack

- .changeset/orange-toys-wave.md
- libs/ledgerjs/packages/cryptoassets/src/currencies.ts
Replaces inactive songbird RPC node with an active one.
- **Impacted projects**: `@ledgerhq/cryptoassets` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-6824 
> [LIVE-6824] Bugfix - Replace songbird RPC node

- .changeset/tough-feet-mate.md
- apps/ledger-live-desktop/src/renderer/families/cosmos/StakeBanner.tsx
- apps/ledger-live-desktop/src/renderer/families/elrond/StakeBanner.tsx
- apps/ledger-live-desktop/src/renderer/families/ethereum/StakeBanner.tsx
- apps/ledger-live-desktop/src/renderer/families/near/StakeBanner.tsx
- apps/ledger-live-desktop/src/renderer/families/solana/StakeBanner.tsx
Replace analytic token attribute in stake banner account (segment is filtering the word "token")
- **Linked resource(s)**:  https://ledgerhq.atlassian.net/browse/LIVE-6744
> fix: rename analytics token attribute in stake banner account LIVE-5013

- .changeset/long-glasses-walk.md
- libs/ledger-live-common/src/exchange/swap/getExchangeRates.test.ts
- libs/ledger-live-common/src/exchange/swap/getExchangeRates.ts
Device amount and ll amount for a fix swap does not match.
- **Linked resource(s)**:  https://ledgerhq.atlassian.net/browse/LIVE-5013
> fix: fix wrong display for amount to receive in swap drawer

- apps/ledger-live-mobile/src/locales/en/common.json
Change discover v2 wording based on the comment [here](https://github.com/LedgerHQ/ledger-live/issues/3025#issuecomment-1482768129).
- **Linked resource(s)**: close #3025 
> Change discover v2 wording

- .changeset/eight-timers-behave.md
Simple update to the webview refacto changeset to include mobile as well
> updated changeset

- .changeset/eight-timers-behave.md
Fixing wrong app name in the changeset
> chore: fix changeset

- .changeset/flat-wolves-heal.md
- apps/ledger-live-mobile/src/screens/Portfolio/index.tsx
Fixed feature flag verification to prevent upsell from triggering if the feature is disabled
- **Linked resource(s)**: [LIVE-6893]
N/A
[LIVE-6893]: https://ledgerhq.atlassian.net/browse/LIVE-6893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(LLM/Protect): Feature Flag

- libs/coin-polkadot/package.json
- libs/coin-polkadot/src/account.ts
- libs/coin-polkadot/src/api/bisontrails.ts
- libs/coin-polkadot/src/api/sidecar.ts
- libs/coin-polkadot/src/bridge/js.ts
- libs/coin-polkadot/src/cli-transaction.ts
- libs/coin-polkadot/src/js-buildTransaction.ts
- libs/coin-polkadot/src/js-prepareTransaction.ts
- libs/coin-polkadot/src/preload.ts
- libs/coin-polkadot/tsconfig.json
- pnpm-lock.yaml
Update `tsconfig.json` file to set `coin-polkadot` in a strictier TS compile mode.
> Update coin-polkadot tsconfig

- .changeset/hot-poems-dream.md
- apps/ledger-live-mobile/src/screens/Settings/Debug/Debugging/Logs.tsx
Small iteration of the debug tool for viewing and exporting logs, making it more convenient for me, I mean, us. Refactored it to use virtualized lists for better performance and added filtering.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-6912` 
https://user-images.githubusercontent.com/4631227/228358661-4f336147-cafd-4bd9-9d23-73566d42514a.mov
No need to QA, we can merge, it's just better.
> feat: improve the logs viewer tool for debug

- libs/ledger-live-common/package.json
- libs/ledger-live-common/src/families/avalanchepchain/hdhelper.ts
- pnpm-lock.yaml
This PR fixes the getAddressForIndex function
> feat: avalanche p chain rebase buffer fix

- apps/ledger-live-desktop/tests/models/AccountsPage.ts
- apps/ledger-live-desktop/tests/models/Drawer.ts
- apps/ledger-live-desktop/tests/models/InstallSetOfAppsPage.ts
- apps/ledger-live-desktop/tests/models/ManagerPage.ts
- apps/ledger-live-desktop/tests/models/MarketPage.ts
- apps/ledger-live-desktop/tests/models/Modal.ts
- apps/ledger-live-desktop/tests/models/OnboardingPage.ts
- apps/ledger-live-desktop/tests/models/PortfolioPage.ts
- apps/ledger-live-desktop/tests/models/SwapPage.ts
Tidying up page object elements so they don't use 'function' type
> B2CQA-1731 - Tidying up page object elements so they don't use 'function' type

- .changeset/gorgeous-dodos-bake.md
- .github/workflows/build-mobile.yml
- apps/ledger-live-mobile/index.js
- apps/ledger-live-mobile/package.json
- apps/ledger-live-mobile/src/components/RootNavigator/SendFundsNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/SignTransactionNavigator.tsx
- apps/ledger-live-mobile/src/config/urls.tsx
- apps/ledger-live-mobile/src/context/LedgerStore.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Platform/Catalog/DAppDisclaimer.tsx
- apps/ledger-live-mobile/src/screens/SendFunds/02-SelectRecipient.tsx
- apps/ledger-live-mobile/src/screens/SendFunds/04-Summary.tsx
- apps/ledger-live-mobile/src/screens/SendFunds/DomainServiceRecipientRow.tsx
- apps/ledger-live-mobile/src/screens/SendFunds/RecipientRow.tsx
- apps/ledger-live-mobile/src/screens/SendFunds/SummaryToSection.tsx
- libs/domain-service/src/resolvers/index.ts
- pnpm-lock.yaml
Enable domain service for LLM, UI part only
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5082 
> [LIVE-5082] Feature: ENS / domain service for LLM

- .changeset/wet-dogs-end.md
- apps/ledger-live-mobile/src/screens/Platform/v2/Catalog/Search/index.tsx
Remove recently used from search page Discovery 2
> feat: remove recently used from search page

- .changeset/empty-balloons-tease.md
- apps/ledger-live-mobile/src/screens/Platform/v2/Catalog/Search/SearchBar.tsx
- apps/ledger-live-mobile/src/screens/Platform/v2/Catalog/Search/index.tsx
- apps/ledger-live-mobile/src/screens/Platform/v2/Catalog/index.tsx
- apps/ledger-live-mobile/src/screens/Platform/v2/Catalog/types.ts
Remove the cancel button and make the top left arrow doing what the Cancel buttons (return to Browse Web3).
> feat: change navigation on discovery v2 search page

- .github/workflows/build-desktop.yml
- .github/workflows/generate-screenshots.yml
- .github/workflows/test-desktop.yml
- .github/workflows/test-mobile-e2e.yml
- package.json
- tools/actions/composites/setup-test-desktop/action.yml
- tools/actions/composites/setup-toolchain/action.yml
Needed because of `pnpm install` issues when running workflows on our own macos runners (same physical machine).
> Relocate pnpm install dest for macos runners

- apps/ledger-live-mobile/.env.mock
- apps/ledger-live-mobile/e2e/helpers.ts
- apps/ledger-live-mobile/e2e/models/accounts/accountPage.ts
- apps/ledger-live-mobile/e2e/models/accounts/accountsPage.ts
- apps/ledger-live-mobile/e2e/models/discovery/discoveryPage.ts
- apps/ledger-live-mobile/e2e/models/manager/managerPage.ts
- apps/ledger-live-mobile/e2e/models/stax/customLockscreenPage.ts
- apps/ledger-live-mobile/e2e/models/trade/receivePage.ts
- apps/ledger-live-mobile/e2e/models/trade/sendPage.ts
- apps/ledger-live-mobile/e2e/models/trade/swapFormPage.ts
- apps/ledger-live-mobile/e2e/models/wallet/portfolioPage.ts
- apps/ledger-live-mobile/e2e/specs/deeplinks.spec.ts
- apps/ledger-live-mobile/src/components/FilteredSearchBar.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/SendFundsNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/SwapFormNavigator.tsx
- apps/ledger-live-mobile/src/components/StepHeader.tsx
- apps/ledger-live-mobile/src/screens/Accounts/index.tsx
- apps/ledger-live-mobile/src/screens/CustomImage/Step0Welcome.tsx
- apps/ledger-live-mobile/src/screens/Manager/index.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/deviceSelection.tsx
- apps/ledger-live-mobile/src/screens/Platform/Catalog/Banner.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/01-SelectCrypto.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/02-SelectAccount.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/Header.tsx
_Detox tests for deeplinks_
Tested deeplinks : 
- `myledger` (opens manager then add device)
- `discover` (opens several apps)
- `send` (global page then ETH  with `?currency=`)
- `receive` (global page then ETH  with `?currency=`)
- `swap`
- `accounts` (then ETH and BTC accounts with `?accountId=`)
- `custom-image` (opens custom lock screen flow for `Stax`)
- **Linked resource(s)**: [`Allure iOS`](https://ledger-live.ars.green.ledgerlabs.net/reports/support/B2CQA-1522_LLM_Smoke_test_Deeplinks-ios)  [`Allure Android`](https://ledger-live.ars.green.ledgerlabs.net/reports/support/B2CQA-1522_LLM_Smoke_test_Deeplinks-android)
- 
_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-st …
> [B2CQA-1522] First LLM smoke tests for deeplinks

- .changeset/strange-bears-complain.md
- apps/ledger-live-desktop/package.json
- apps/ledger-live-desktop/src/main/db/index.ts
- apps/ledger-live-desktop/src/main/index.ts
- apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/WalletAPIWebview.tsx
- apps/ledger-live-desktop/src/renderer/modals/Receive/steps/StepReceiveStakingFlow.tsx
- apps/ledger-live-desktop/src/renderer/reset.ts
- apps/ledger-live-desktop/src/renderer/store.js
- apps/ledger-live-mobile/android/build.gradle
- apps/ledger-live-mobile/android/gradle.properties
- apps/ledger-live-mobile/ios/Podfile.lock
- apps/ledger-live-mobile/package.json
- apps/ledger-live-mobile/src/components/Web3AppWebview/WalletAPIWebview.tsx
- libs/ledger-live-common/src/wallet-api/react.ts
- pnpm-lock.yaml
The storage feature will be used for the following use cases:
Allow inter-web3app data sharing
Allow ledger live to read data stored from web3app (facilitate using tokens in the recover case)
In the future, easily "cloud syncing" data from web3app between multiple ledger live clients
It's totally sandboxed from one app to another by default. The sandboxing logic reside in the WalletAPIServer package. For now, we only allow an app to fetch data from its own namespace. In the future, special permissions in the manifest will allow a web3app to fetch data from a namespace it doesn't own.
- Updated wallet-api-server and wallet-api-core version
- Add Next storage & remove  obsolete `AsyncStorage_db_size_in_MB` & update Kotlin version as its a Next storage min requirement
- Added wallet api …
> feat: add wallet api storage support

- .changeset/gorgeous-swans-fetch.md
- libs/env/src/env.ts
- libs/ledger-live-common/src/families/cosmos/api/Cosmos.test.ts
- libs/ledger-live-common/src/families/cosmos/api/Cosmos.ts
- libs/ledger-live-common/src/families/cosmos/chain/Osmosis.ts
- libs/ledger-live-common/src/families/cosmos/chain/cosmosBase.ts
- libs/ledger-live-common/src/families/cosmos/js-buildTransaction.test.ts
- libs/ledger-live-common/src/families/cosmos/js-buildTransaction.ts
- libs/ledger-live-common/src/families/cosmos/js-prepareTransaction.test.ts
- libs/ledger-live-common/src/families/cosmos/js-prepareTransaction.ts
Fix cosmos gas estimation by simulating a tx
> LIVE-6665 Fix cosmos gas estimation

- .github/workflows/build-desktop-external.yml
- .github/workflows/generate-screenshots.yml
- .github/workflows/test-desktop-external.yml
- .github/workflows/test-desktop.yml
- .github/workflows/test-integration-pr.yml
- .github/workflows/test-integration.yml
- .npmrc
- tools/actions/composites/setup-test-desktop/action.yml
- tools/actions/composites/setup-toolchain/action.yml
> chore: fix windows install failing in CI

- apps/ledger-live-mobile/fastlane/Fastfile
> ci(Fastfile): fix syntax error

- .changeset/curvy-wombats-guess.md
- libs/ledger-live-common/src/families/cosmos/js-prepareTransaction.test.ts
- libs/ledger-live-common/src/families/cosmos/js-prepareTransaction.ts
Round fees up and remove cache on fee simulation
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-6665` 
> fix: not enough fees for osmosis staking

- .changeset/short-dogs-decide.md
- apps/ledger-live-mobile/ios/ledgerlivemobile/AppDelegate.m
- apps/ledger-live-mobile/ios/ledgerlivemobile/ledgerlivemobile.entitlements
- apps/ledger-live-mobile/src/components/BleDevicePairingFlow/BleDeviceItem.tsx
- apps/ledger-live-mobile/src/components/BleDevicePairingFlow/BleDevicesScanning.tsx
- apps/ledger-live-mobile/src/components/BleDevicePairingFlow/index.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/types/BaseNavigator.ts
- apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx
- apps/ledger-live-mobile/src/screens/BleDevicePairingFlow/index.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/deviceSelection.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/postWelcomeSelection.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/Configuration/ResetOnboardingStateRow.tsx
> <img width="494" alt="Screenshot 2023-03-31 at 12 53 00" src="https://user-images.githubusercontent.com/91890529/229101519-5d15b77a-6944-4302-9d37-a86e61d24537.png">
- [iOS native] Implement support for iOS universal links by implementing `application:continueUserActivity:restorationHandler` in `AppDelegate.m` and forwarding to React Native Linking library (`RCTLinkingManager`).
- [iOS native config]: Added all supported universal links domains in entitlements file, at `com.apple.developer.associated-domains` key
- [React Native JS]: Implement support for deep links coming from all universal links domains, in `react-navigation` linking configuration.
- [React Native JS]: Fix initial route name for deep links accessible in sync onboarding (Welcome screen instead of Portfolio screen).
- …
> [LIVE-6451] Bugfix - Adjust iOS universal links not working

- .changeset/twenty-beans-itch.md
- apps/ledger-live-mobile/src/screens/Swap/Form/index.tsx
- libs/ledger-live-common/src/exchange/swap/getExchangeRates.test.ts
- libs/ledger-live-common/src/exchange/swap/getExchangeRates.ts
Fixes error messaging on LLM swap screen.
- **Impacted projects**:  Mobile/desktop
- **Linked resource(s)**:  https://ledgerhq.atlassian.net/browse/LIVE-6922
> fix: llm - fixes error messaging for CEX swap providers

- libs/coin-polkadot/src/js-buildTransaction.test.ts
Add a unit test for happy path of transaction crafting in `coin-polkadot`.
> Add Polkadot unit test for transaction building

- .changeset/modern-fans-switch.md
- apps/ledger-live-desktop/src/renderer/screens/earn/useDeepLinkListener.ts
Create deeplink to stake on a specific account
- **Linked resource(s)**:  https://ledgerhq.atlassian.net/browse/LIVE-6917
> feat: add stake account deeplink LIVE-6917

- .changeset/rotten-wombats-rescue.md
- apps/ledger-live-mobile/src/screens/RatingsModal/DisappointedForm.tsx
LLM - added additional data to the ratings typeform
- **Linked resource(s)**: [LIVE-6964] 
[LIVE-6964]: https://ledgerhq.atlassian.net/browse/LIVE-6964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LLM - added additional data to the ratings typeform

- .github/workflows/cal-importer.yml
Currently only files in ledgerjs root data directory are added to CDN, this PR recursively adds all files (preserving directory structure). Here is the diff:
```
before								after
├── asa.json							├── asa.json
├── bep20.json							├── bep20.json
├── cardanoNative.json						├── cardanoNative.json
├── eip712.json							├── eip712.json
├── erc20.json							├── erc20.json
├── erc20-signatures.json					├── erc20-signatures.json
├── esdt.json							├── esdt.json
>	├── evm
>	│   ├── 1
>	│   │   ├── erc20.json
>	│   │   └── erc20-signatures.json
>	│   ├── 10
>	│   │   ├── erc20.json
>	│   │   └── erc20-signatures.json
>	│   ├── 11155111
>	│   │   ├── erc20.json
>	│   │   └── erc20-signatures.json
>	│   ├── 1284
>	│   │   ├── erc20.json
>	│   │   └── erc20-signatures.json
>	│   ├── 137
>	│   …
```
> LIVE-6864: Add all json files in ledgerjs data to CAL CDN

- .changeset/spicy-singers-care.md
- apps/ledger-live-desktop/src/renderer/components/FirebaseRemoteConfig.tsx
- apps/ledger-live-desktop/src/renderer/drawers/DataSelector/AccountList.tsx
- apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/AppActions.tsx
- apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/Item.tsx
- apps/ledger-live-mobile/src/components/FirebaseRemoteConfig.tsx
- apps/ledger-live-mobile/src/screens/RequestAccount/02-SelectAccount.tsx
Add Feature flag for all add Account entrypoints
- **Impacted projects**: `LLD/LLM`
- https://ledgerhq.atlassian.net/browse/LIVE-5099
- https://ledgerhq.atlassian.net/browse/LIVE-5100
- https://ledgerhq.atlassian.net/browse/LIVE-5110
> Add Account Feature Flag

- apps/ledger-live-desktop/src/renderer/components/WebPTXPlayer/TopBar.tsx
- apps/ledger-live-mobile/src/components/WebPTXPlayer/index.tsx
Add analytics when clicking on Back to LiveApp
- **Impacted projects**: `LLD and LLM` 
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-5324` 
> feat: add back to liveApp analytics

- .changeset/gorgeous-impalas-serve.md
- .changeset/hot-moose-destroy.md
- apps/ledger-live-mobile/src/components/AccountBanner.tsx
- apps/ledger-live-mobile/src/components/Alert.tsx
- apps/ledger-live-mobile/src/components/SettingsRow.tsx
- apps/ledger-live-mobile/src/components/SupportLinkError.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/Configuration/ResetOnboardingStateRow.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/Configuration/index.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/Features/Storyly.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/index.tsx
- libs/ui/packages/native/src/components/message/Alert/index.tsx
- libs/ui/packages/native/storybook/stories/message/Alert/Alert.stories.tsx
- libs/ui/packages/native/tsconfig.json
- native-ui:
- fix `tsconfig.json` (add jsx compiler option)
- `Alert` component:
- new design (text color, icon alignment, icons, icon color)
- new types `"secondary"` and `"success"`
- removed `renderContent` prop
- ledger-live-mobile:
- adapt changes of `Alert` component
- fix padding between around Alert component and settings rows
- **Impacted projects**: `llm` `native-ui` 
- **Linked resource(s)**: [Figma](https://www.figma.com/file/wGzwuUVo0rkCJ3sM8cpbDY/%F0%9F%93%B1-Native-Library?node-id=7995-84013&t=hXj354c3OQHMex1M-0) 
https://user-images.githubusercontent.com/91890529/232812517-3652f2e3-8fd2-40eb-8c9d-7eece4c33d1d.mov
_Pull Requests …
> Feat/native UI update alert design

- apps/cli/src/live-common-setup-base.ts
- libs/ledger-live-common/src/families/cosmos/api/Cosmos.ts
- libs/ledger-live-common/src/families/cosmos/bridge.integration.test.ts
- libs/ledger-live-common/src/families/cosmos/chain/Cosmos.ts
- libs/ledger-live-common/src/families/cosmos/chain/Umee.ts
- libs/ledger-live-common/src/families/cosmos/datasets/__snapshots__/desmos.integration.test.ts.snap
- libs/ledger-live-common/src/families/cosmos/datasets/__snapshots__/umee.integration.test.ts.snap
- libs/ledger-live-common/src/families/cosmos/datasets/axelar.ts
- libs/ledger-live-common/src/families/cosmos/datasets/desmos.integration.test.ts
- libs/ledger-live-common/src/families/cosmos/datasets/desmos.ts
- libs/ledger-live-common/src/families/cosmos/datasets/umee.integration.test.ts
- libs/ledger-live-common/src/families/cosmos/datasets/umee.ts
- libs/ledger-live-common/src/families/cosmos/js-prepareTransaction.ts
- libs/ledger-live-common/src/families/cosmos/specs.ts
- libs/ledger-live-common/src/load/speculos.ts
- libs/ledgerjs/packages/cryptoassets/src/abandonseed.ts
Add Desmos and umee in cosmos batch 1, functionnal + test
> feat: desmos umee with tests and specs

- .changeset/good-lemons-wave.md
- apps/ledger-live-mobile/src/components/Nft/NftLinksPanel.tsx
Unable to hide NFT collection on individual detail drawer
- **Linked resource(s)**: [LIVE-7085] 
[LIVE-7085]: https://ledgerhq.atlassian.net/browse/LIVE-7085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bugfix(NFT Gallery): LLM - Unable to hide NFTs

- apps/ledger-live-desktop/src/config/urls.ts
- apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/Tutorial/index.tsx
- apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/Tutorial/screens/RecoverPinCodeHowTo.tsx
Nano pin code selection in restore with recover flow
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-5848
> Feat/LIVE-5848 - LLD Recover - Nano pin code selection in restore with recover flow

- CODEOWNERS
Correcting team names into the codeowner file
live-platform-and-services -> ptx / wallet-api
> Bugfix/ Set right team names

- tools/actions/composites/setup-toolchain/action.yml
back to using proto in CI since it has been updated
> chore: support proto in CI

- apps/ledger-live-desktop/src/renderer/families/cosmos/ClaimRewardsFlowModal/steps/StepConfirmation.tsx
- apps/ledger-live-desktop/src/renderer/families/cosmos/Delegation/index.tsx
- apps/ledger-live-desktop/src/renderer/families/cosmos/DelegationFlowModal/fields/ValidatorField.tsx
- apps/ledger-live-desktop/src/renderer/families/cosmos/RedelegationFlowModal/fields/ValidatorField.tsx
- apps/ledger-live-desktop/src/renderer/families/cosmos/RedelegationFlowModal/steps/StepValidators.tsx
- apps/ledger-live-desktop/src/renderer/families/cosmos/TransactionConfirmFields.tsx
- apps/ledger-live-desktop/src/renderer/families/cosmos/UndelegationFlowModal/steps/Confirmation.tsx
- apps/ledger-live-desktop/src/renderer/families/cosmos/operationDetails.tsx
- apps/ledger-live-mobile/src/families/cosmos/operationDetails.tsx
- libs/ledger-live-common/src/families/cosmos/react.ts
- libs/ledger-live-common/src/families/cosmos/specs.ts
Change currency Name to Id for cosmos chain
- **Impacted projects**: `llc, lld, llm` 
> fix: change cosmos currency name to id

- apps/ledger-live-desktop/src/renderer/hooks/useDeeplinking.ts
Deeplinks now working when already on same screen
- **Linked resource(s)**: [LIVE-7060] 
[LIVE-7060]: https://ledgerhq.atlassian.net/browse/LIVE-7060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LLD - deeplinks now working when already on same screen

- apps/ledger-live-mobile/android/dapp-store/config.yaml
Solana dapp store release note
> fix: solana dapp store release note

- tools/actions/composites/setup-toolchain/action.yml
> chore: log proto version

- .changeset/polite-eyes-complain.md
- libs/ui/packages/react/src/components/message/Alert/Alert.stories.tsx
- libs/ui/packages/react/src/components/message/Alert/index.tsx
Update react-ui alert component align with native to be used in web and lld
- **Impacted projects**: libs/ui/react
- **Linked resource(s)**:  https://ledgerhq.atlassian.net/browse/LIVE-6890
- Associated Vercel deployment : https://react-ui-storybook-git-bugfix-update-react-ui-a-54405c-ledgerhq.vercel.app/?path=/story/messages-alerts--default&globals=backgrounds.value:!hex(131214)
https://user-images.githubusercontent.com/38540290/233985345-3bfdef3f-0859-4e48-90f6-7fc4a23e1c87.mov
> fix: update react-ui alert component

- .github/templates/hotfix-conflicts.md
- .github/templates/hotfix-release-conflicts.md
- .github/templates/release-conflicts.md
Update the templates used to create the PR for handling merge conflicts on release and hotfix flows
We're adding a warning to avoid a squash merge for this kind of PR
> chore: add warning in the templates for conflicts

- .changeset/empty-countries-compare.md
- apps/ledger-live-desktop/package.json
- apps/ledger-live-desktop/src/renderer/experimental.tsx
- apps/ledger-live-desktop/src/renderer/families/ethereum/MaxFeeField.tsx
- apps/ledger-live-desktop/src/renderer/screens/settings/sections/Experimental/ExperimentalFloat.tsx
- apps/ledger-live-desktop/src/renderer/screens/settings/sections/Experimental/index.tsx
- apps/ledger-live-desktop/static/i18n/en/app.json
- apps/ledger-live-mobile/package.json
- apps/ledger-live-mobile/src/experimental.ts
- apps/ledger-live-mobile/src/families/ethereum/EthereumCustomFees/utils.tsx
- apps/ledger-live-mobile/src/screens/Settings/Experimental/FeatureFloat.tsx
- apps/ledger-live-mobile/src/screens/Settings/Experimental/FeatureRow.tsx
- libs/env/src/env.ts
- libs/ledger-live-common/src/families/ethereum/gas.ts
- libs/ledger-live-common/src/families/ethereum/react.ts
- pnpm-lock.yaml
This PR is modifying the mulitiplier for the `baseFee` from `2` to `1.5` in order to reduce the visual impact on fees (at the expense of potentially having more users stuck with a transaction with not enough fees).
It also introduce an experimental env variable to make it customisable by everyone if needed.
- Ethereum
- Polygon
- Ethereum Goerli
- **Impacted projects**: `@ledgerhq/live-env` `@ledgerhq/live-common` `ledger-live-mobile` `ledger-live-desktop` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-7271 
https://user-images.githubusercontent.com/44363395/234917680-09d46f10-5b13-4f22-a885-dba7601826db.mov
https://user-images.githubusercontent.com/44363395/234917732-2ed53405-7122-407d-9bd0-e8cf185d5b8b.mp4 …
> [LIVE-7271] Feature - Update Base Fee mutliplier for EIP1559 transactions

- .changeset/smooth-toys-sit.md
- apps/ledger-live-mobile/src/actions/settings.ts
- apps/ledger-live-mobile/src/actions/types.ts
- apps/ledger-live-mobile/src/components/RootNavigator/NotificationCenterNavigator.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/reducers/settings.ts
- apps/ledger-live-mobile/src/reducers/types.ts
- apps/ledger-live-mobile/src/screens/NotificationCenter/Notifications.tsx
- apps/ledger-live-mobile/src/screens/NotificationCenter/Status.tsx
Notification status page is to change from drawer to page whenever the user clicks on the status icon
- **Linked resource(s)**: [LIVE-6910] 
https://user-images.githubusercontent.com/112866305/235100246-d186b9c1-0ca8-4bd5-84ed-0ca3b935817d.mov
https://user-images.githubusercontent.com/112866305/235107516-e4550ad6-920a-4bd3-a390-f0ee5afb197a.mp4
- 🍎 : https://github.com/LedgerHQ/ledger-live-build/actions/runs/4820354539
- 🤖 : https://github.com/LedgerHQ/ledger-live-build/actions/runs/4817270515
[LIVE-6910]: …
> feat(Status): LLM - UI Improvements to Status Center

- apps/ledger-live-desktop/static/i18n/en/app.json
Fix small typo of Recover LLD Recover promo popup
- **Impacted projects**: `` live-desktop
> Bugfix - LLD Recover - Fix typo of Recover LLD Recover promo popup

- tools/common-tools/package.json
- tools/common-tools/src/demos/repl/commands.js
- tools/common-tools/src/demos/repl/components/fields/ApplicationField.js
Fixes common-tools on Vercel
- **Impacted projects**: `tools` 
> chore(common-tools): make it build in Node 18

- .changeset/fluffy-pumas-brake.md
- .changeset/large-ducks-suffer.md
- apps/ledger-live-desktop/src/renderer/components/PlatformAppProviderWrapper.tsx
- apps/ledger-live-mobile/src/PlatformAppProviderWrapper.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/DiscoverNavigator.tsx
- libs/ledger-live-common/src/platform/filters.ts
> fix: add Catalog when discover ff is false

- .changeset/twenty-foxes-admire.md
- apps/ledger-live-desktop/tests/utils/serve-dummy-app.ts
- apps/ledger-live-mobile/src/screens/Platform/v2/Catalog/hooks.tsx
- apps/ledger-live-mobile/src/screens/Platform/v2/Catalog/index.tsx
- libs/ledger-live-common/src/platform/logic.test.ts
- libs/ledger-live-common/src/platform/providers/RemoteLiveAppProvider/api/mock.json
- libs/ledger-live-common/src/platform/providers/RemoteLiveAppProvider/index.tsx
- libs/ledger-live-common/src/platform/tracking.test.ts
- libs/ledger-live-common/src/platform/types.ts
- libs/ledger-live-common/src/wallet-api/logic.test.ts
- libs/ledger-live-common/src/wallet-api/tracking.test.ts
- libs/ledger-live-common/src/wallet-api/types.ts
add field visibility to manifest
- **Impacted projects**: `LLD, Common` 
- **Linked resource(s)**: https://github.com/LedgerHQ/manifest-api/issues/134 
> feat: add field visibility to manifest

- .changeset/honest-jokes-protect.md
- libs/ledger-live-common/src/config/defaultConfig.ts
Replace osmosis node in defaultConfig to fix history bug
- **Impacted projects**: `LLC,LLD,LLM` 
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-7334` 
> fix: fix osmosis transaction history

- apps/ledger-live-mobile/src/families/cosmos/shared/02-SelectAmount.tsx
- libs/ledger-live-common/src/families/cosmos/js-prepareTransaction.test.ts
Add delegation amount to lru cache deps for fees estimation
- **Impacted projects**: `LLC,LLD,LLM` 
- https://ledgerhq.atlassian.net/browse/LIVE-7329
- https://ledgerhq.atlassian.net/browse/LIVE-7333
> fix: onomy redelegate by adding new dep to lru cache (delegation amount)

- .changeset/dry-eagles-judge.md
- apps/ledger-live-mobile/src/components/BleDevicePairingFlow/BleDevicePairing.tsx
- apps/ledger-live-mobile/src/components/BleDevicePairingFlow/BleDevicesScanning.tsx
- apps/ledger-live-mobile/src/components/GenericErrorView.tsx
Pixel polishes in various pairing screens. See attached [Figma](https://www.figma.com/file/lIpMetdd2GqqLK41RBlwjk/Stax-%2F-upgrades?node-id=4264-209793&t=BF96uTivnGYp8CPy-0) file
- **Linked resource(s)**: [LIVE-7139]
https://user-images.githubusercontent.com/39890664/235706271-29343e8c-1e9e-447b-9bd5-14a1416b77c2.mp4
[LIVE-7139]: https://ledgerhq.atlassian.net/browse/LIVE-7139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> style(LLM): Pairing Flow Pixel-Polish

- .changeset/rare-tables-cheer.md
- libs/ledger-live-common/package.json
- libs/ledger-live-common/src/load/speculos.ts
- libs/ledgerjs/packages/hw-transport-node-speculos-http/package.json
- libs/ledgerjs/packages/hw-transport-node-speculos-http/src/SpeculosHttpTransport.ts
- pnpm-lock.yaml
Speculos are using mostly websocket to communicate, but it's seems this way of exchanging info is deprecated, so we change it to rest api
> ci: change speculos transport with http one

- .changeset/silent-steaks-search.md
- apps/ledger-live-desktop/src/renderer/hooks/useDeeplinking.ts
Add deeplink clicked track
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-7003
> feat: add deeplink clicked track

- .github/workflow-templates/bot-coin-family.yml
- .github/workflows/bot-carbon.yml
- .github/workflows/bot-mere-denis.yml
- .github/workflows/bot-mooncake.yml
- .github/workflows/bot-nitrogen.yml
- .github/workflows/bot-nonreg-carbon.yml
- .github/workflows/bot-nonreg-mooncake.yml
- .github/workflows/bot-nonreg-nitrogen.yml
- .github/workflows/bot-nonreg-oxygen.yml
- .github/workflows/bot-nonreg-silicium.yml
- .github/workflows/bot-oxygen.yml
- .github/workflows/bot-phosphore.yml
- .github/workflows/bot-portfolio-report.yml
- .github/workflows/bot-silicium.yml
- .github/workflows/bot-staging-explorer-btc.yml
- .github/workflows/bot-staging-explorer-eth.yml
- .github/workflows/bot-transfer.yml
- .github/workflows/build-desktop.yml
- .github/workflows/build-mobile.yml
- .github/workflows/cal-importer-stg.yml
- .github/workflows/cal-importer.yml
- .github/workflows/generate-screenshots.yml
- .github/workflows/healthchecks-runners.yaml
- .github/workflows/test-desktop-external.yml
- .github/workflows/test-desktop.yml
- .github/workflows/test-mobile-e2e.yml
Migrate GHA runners to dedicated cluster
> chore: [INFRAPRJ-2558] Migrate runners to dedicated cluster

- .changeset/heavy-dancers-cheat.md
- apps/ledger-live-desktop/src/renderer/components/Progress.tsx
The TypeScript migration broke the install animation on LLD making it not move and animate from the center, this PR fixes it and brings back the original animation.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-7399` 
https://github.com/LedgerHQ/ledger-live/assets/4631227/457389b0-81b9-4fa8-a8b2-c3d779b6faf6
> fix: LIVE-7399 fix animation regression in install apps my ledger

- .changeset/quick-candles-burn.md
- apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx
- apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/Installing.tsx
- apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/index.tsx
- apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/steps/01-step-prepare.tsx
- apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/steps/02-step-flash-mcu.tsx
- apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/steps/02-step-restore.tsx
- apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/steps/02-step-updating.tsx
- apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/steps/restore/CLS.tsx
- apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/steps/restore/Language.tsx
- apps/ledger-live-desktop/src/renderer/screens/manager/FirmwareUpdate/index.tsx
- apps/ledger-live-desktop/static/i18n/en/app.json
Following the document linked in the task there are a series of polishes to tackled before a release including the FW update as a drawer. This PR attempts to address them with a few caveats that I've described in the Jira task.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-7459` 
No demo
Go over the document from Benito and see if the behaviour in a build from this PR matches his expectations.
In particular the ones that he marked as Must Have for a release.
> bugfix/LIVE-7459 Polishes and changes from product feedback to FW update LLD

- .changeset/perfect-jeans-grab.md
- apps/ledger-live-mobile/src/analytics/TrackScreen.tsx
- apps/ledger-live-mobile/src/analytics/segment.ts
- apps/ledger-live-mobile/src/screens/SyncOnboarding/index.tsx
Tracking of the properties of the seeding step (number of words and type of seeding).
This one is a tiny bit more complex than other tracking logic because this information cannot be obtained directly from the device once it is seeded, so _during_ the onboarding we have to keep track of the onboarding state returned by the device and use the values we kept to track the event with the correct properties.
For Recover, the implementation will have to be completed separately, as specified in comments on the ticket.
- **Linked resource(s)**: [LIVE-6993]  …
> feat(llm/synconboarding/analytics): track seeding

- .changeset/silver-students-add.md
- libs/ledger-live-common/src/config/defaultConfig.ts
Add validators to default config
> feat: add ledger validators in default conf for cosmos batch 1

- libs/ledger-live-common/src/families/stacks/specs.ts
- libs/ledgerjs/packages/cryptoassets/src/abandonseed.ts
Complete some missing code requested by @haammar-ledger, and fix CI
> Complete stacks integration

- apps/ledger-live-desktop/RELEASE_NOTES.md
> chore: update RELEASE_NOTES

- libs/ledger-live-common/src/families/stacks/speculos-deviceActions.ts
Fix bot actions on stacks integration
> Fix bot actions on stacks integration

- libs/ledger-live-common/src/families/stacks/speculos-deviceActions.ts
> Fix bot actions on stacks

- libs/ledger-live-common/src/families/stacks/speculos-deviceActions.ts
> Fix bot specs on stacks

- .changeset/little-spies-peel.md
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/Header.tsx
- apps/ledger-live-mobile/src/screens/SyncOnboarding/LanguageSelect.tsx
- apps/ledger-live-mobile/src/screens/SyncOnboarding/index.tsx
Removed language switcher in LLD and LLM in Sync onboarding view.
- **Impacted projects**: LLD, LLM
- **Linked resource(s)**: [LIVE-7364] - [LIVE-7363]
[LIVE-7364]: https://ledgerhq.atlassian.net/browse/LIVE-7364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-7363]: https://ledgerhq.atlassian.net/browse/LIVE-7363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(LLM/LLD): Sync Onboarding Removed language switcher

- .github/workflows/test.yml
- tools/common-tools/src/demos/sync/live-common-setup.js
restore common-tools and add test for it.
this should fix vercel and add a test to never break it again.
> fix: restore common-tools and add test for it

- apps/ledger-live-desktop/src/sentry/install.ts
- apps/ledger-live-mobile/index.js
Sentry gets spammed with a backend error from Crypto.org: https://ledger.sentry.io/issues/3646900338/?project=6505205&referrer=slack
This PR adds it to the list of backend errors we ignore in Sentry, for both LLD and LLM.
- **Impacted projects**: `LLD` `LLM` 
- **Linked resource(s)**: https://ledger.sentry.io/issues/3646900338/?project=6505205&referrer=slack
> [support] Silence crypto.org backend error on sentry

- libs/ledger-live-common/src/families/bitcoin/walletApiAdapter.test.ts
- libs/ledger-live-common/src/families/bitcoin/walletApiAdapter.ts
- libs/ledger-live-common/src/families/ethereum/walletApiAdapter.test.ts
- libs/ledger-live-common/src/families/ethereum/walletApiAdapter.ts
- libs/ledger-live-common/src/families/polkadot/walletApiAdapter.test.ts
- libs/ledger-live-common/src/families/polkadot/walletApiAdapter.ts
- libs/ledger-live-common/src/families/ripple/walletApiAdapter.test.ts
- libs/ledger-live-common/src/families/ripple/walletApiAdapter.ts
- libs/ledger-live-common/src/platform/logic.ts
- libs/ledger-live-common/src/wallet-api/converters.test.ts
- libs/ledger-live-common/src/wallet-api/converters.ts
- libs/ledger-live-common/src/wallet-api/helpers.ts
- libs/ledger-live-common/src/wallet-api/logic.ts
- libs/ledger-live-common/src/wallet-api/types.ts
Convert Wallet API Ethereum transaction into Live Ethereum/EVM transaction based on Live account family.
- **Impacted projects**: `LLD`, `LLM`, `live-common`
- **Linked resource(s)**: https://github.com/LedgerHQ/ledger-live-issues/issues/108
> For trying out Polygon, you need to change its family from `ethereum` to `evm` on Ledger Live side [line](https://github.com/LedgerHQ/ledger-live/blob/d79a0b1b089ee2ff37181589ab898541188fb9fd/libs/ledgerjs/packages/cryptoassets/src/currencies.ts#L2241)
<details>
<summary>`manifest-local.json`</summary>
```
{
"id": "paraswap-2",
"name": "Paraswap",
"private": false,
"url": "http://localhost:3000/v2",
"params": {
"dappUrl": "https://embedded.paraswap.io/?referrer=ledger2&embed=true&enableStaking=false&displayMenu=false",
"nanoApp": "Paraswap", …
```
> feat(wallet-api): Support EVM family in wallet-api

- .changeset/fair-rice-sleep.md
- .changeset/heavy-mails-wait.md
- apps/cli/src/commands-index.ts
- apps/cli/src/commands/deviceSDKToggleOnboardingEarlyCheck.ts
- apps/ledger-live-mobile/src/screens/SyncOnboarding/EarlySecurityCheck.tsx
- apps/ledger-live-mobile/src/screens/SyncOnboarding/SyncOnboardingCompanion.tsx
- apps/ledger-live-mobile/src/screens/SyncOnboarding/index.tsx
- libs/ledger-live-common/src/deviceSDK/actions/toggleOnboardingEarlyCheck.ts
- libs/ledger-live-common/src/deviceSDK/commands/toggleOnboardingEarlyCheck.test.ts
- libs/ledger-live-common/src/deviceSDK/commands/toggleOnboardingEarlyCheck.ts
- libs/ledger-live-common/src/deviceSDK/hooks/useToggleOnboardingEarlyChecks.test.ts
- libs/ledger-live-common/src/deviceSDK/hooks/useToggleOnboardingEarlyChecks.ts
- libs/ledger-live-common/src/deviceSDK/tasks/core.ts
- libs/ledger-live-common/src/deviceSDK/tasks/toggleOnboardingEarlyCheck.test.ts
- libs/ledger-live-common/src/deviceSDK/tasks/toggleOnboardingEarlyCheck.ts
- libs/ledger-live-common/src/hw/extractOnboardingState.test.ts
- libs/ledger-live-common/src/hw/extractOnboardingState.ts
Introducing a new device action (implemented in the device SDK): `toggleOnboardingEarlyCheckAction` with
- its associated new command and task
- its associated new onboarding state
- a hook `useToggleOnboardingEarlyCheck` for simple usage on LLM and LLD
- unit tests
- its associated cli command `deviceSDKToggleOnboardingEarlyCheck`
This new action uses a new APDU to enter and exit the "early security check" blocking step during the onboarding of Stax.
Also implementing the new architecture on LLM for the sync onboarding:
- a new `SyncOnboardingCompanion` component getting (almost) all the logic that existed directly in the screen
- an empty `EarlySecurityCheck` component that directly notifies (for now) that everything is good
- a screen that orchestrate which of the 2 components should …
> Feat: LIVE-7290: toggle onboarding early checks apdu

- .changeset/warm-adults-clap.md
- apps/ledger-live-desktop/src/renderer/hooks/useDeeplinking.ts
- apps/ledger-live-desktop/src/renderer/screens/account/index.tsx
Added address query and navigation to account route for deeplinks
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-7770
Uploading Screen Recording 2023-06-06 at 17.50.39.mov…
> feat: added address query and navigation to account route for deeplinks

- libs/ledger-live-common/src/families/stacks/bridge/account.ts
- libs/ledger-live-common/src/families/stacks/bridge/utils/api.ts
- libs/ledger-live-common/src/families/stacks/bridge/utils/api.types.ts
- libs/ledger-live-common/src/families/stacks/bridge/utils/misc.ts
handle txs in mempool when estimating max spendable
> handle txs in mempool when estimating max spendable

- libs/ledgerjs/packages/hw-app-eth/src/services/ledger/index.ts
Simply modify the log already present to include more infos.
- **Impacted projects**: `@ledgerhq/hw-app-eth` 
> [SUPPORT] Update `hw-app-eth` plugin log

- .changeset/short-buses-type.md
- apps/ledger-live-desktop/src/renderer/modals/ConnectDevice/index.tsx
- apps/ledger-live-desktop/src/renderer/modals/types.ts
Fix undefined request changed in #3603 
We really need to find a way to automate the tests of the device to avoid this type of issue
> fix: ConnectDevice request undefined

- .changeset/gold-pumpkins-film.md
- apps/ledger-live-desktop/package.json
- apps/ledger-live-desktop/src/renderer/components/SelectCurrency.tsx
- apps/ledger-live-desktop/src/renderer/drawers/DataSelector/SelectAccountAndCurrencyDrawer.tsx
- apps/ledger-live-desktop/tests/models/AddAccountModal.ts
- pnpm-lock.yaml
Fix desktop currency search input by adopting to Fuse.js v6.
> Fix crash on desktop currency search input by adopting to Fuse.js v6

- apps/ledger-live-mobile/src/components/FloatingDebugButton.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/types/AddAccountsNavigator.ts
- apps/ledger-live-mobile/src/components/RootNavigator/types/CustomImageNavigator.ts
- apps/ledger-live-mobile/src/components/RootNavigator/types/RequestAccountNavigator.ts
- apps/ledger-live-mobile/src/components/RootNavigator/types/SignMessageNavigator.ts
- apps/ledger-live-mobile/src/components/Web3AppWebview/liveSDKLogic.test.ts
- apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx
- libs/ledger-live-common/src/deviceSDK/tasks/core.ts
- libs/ledger-live-common/src/mock/fixtures/cryptoCurrencies.ts
- libs/ledger-live-common/src/postOnboarding/reducer.ts
- libs/ui/packages/native/.storybook-web/main.js
- libs/ui/packages/native/.storybook/main.js
- libs/ui/packages/native/src/components/Carousel/index.tsx
- libs/ui/packages/native/src/components/Form/SelectableList.tsx
- libs/ui/packages/native/src/components/Icon/BoxedIcon.tsx
- libs/ui/packages/native/src/components/Icon/IconBadge.tsx
- libs/ui/packages/native/src/components/Icon/IconBox/index.tsx
- libs/ui/packages/react/.storybook/main.js
- libs/ui/packages/react/src/components/Chart/utils.ts
- package.json
- pnpm-lock.yaml
- tools/github-bot/src/features/upToDate/index.ts
update to TypeScript v5.
- **Impacted projects**: `*` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-7641 
> chore: update to TypeScript 5

- .changeset/healthy-buttons-promise.md
- .changeset/silver-turtles-knock.md
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/EarlySecurityCheck.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/SyncOnboardingCompanion.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/TroubleshootingDrawer.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/index.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/index.tsx
- apps/ledger-live-mobile/src/screens/SyncOnboarding/index.tsx
A new device action was introduced in https://github.com/LedgerHQ/ledger-live/pull/3497 : `toggleOnboardingEarlyCheckAction` 
This PR is implementing the new architecture on LLD for the sync onboarding:
- a new `SyncOnboardingCompanion` component getting (almost) all the logic that existed directly in the screen
- an empty `EarlySecurityCheck` component that directly notifies (for now) that everything is good
- a "screen" (`apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/index.tsx`) that orchestrate which of the 2 components should be rendered by checking the onboarding state of the device, and calling the new device action `toggleOnboardingEarlyCheckAction` when needed
- **Impacted projects**: `LLD` …
> feat: LIVE-7595 - LLD new architecture of the sync onboarding for the ESC

- .changeset/few-sheep-press.md
- apps/ledger-live-desktop/src/renderer/components/WebPlatformPlayer/LiveAppDrawer.tsx
- apps/ledger-live-desktop/src/renderer/screens/platform/Catalog/index.tsx
Fix continue button on live app disclaimer in discover v2 page.
> fix: disclaimer button for live apps

- libs/ledger-live-common/src/families/stacks/bridge/account.ts
- libs/ledger-live-common/src/families/stacks/bridge/utils/api.ts
- libs/ledger-live-common/src/families/stacks/bridge/utils/api.types.ts
- libs/ledger-live-common/src/families/stacks/bridge/utils/misc.ts
handle next nonce with multiple txs on mempool
> handle next nonce with multiple txs on mempool

- libs/ledger-live-common/src/families/stacks/account.ts
- libs/ledger-live-common/src/families/stacks/bridge/account.ts
- libs/ledger-live-common/src/families/stacks/bridge/utils/api.ts
- libs/ledger-live-common/src/families/stacks/bridge/utils/api.types.ts
- libs/ledger-live-common/src/families/stacks/bridge/utils/misc.ts
- libs/ledger-live-common/src/families/stacks/cli-transaction.ts
- libs/ledger-live-common/src/families/stacks/hw-getAddress.ts
- libs/ledger-live-common/src/families/stacks/hw-signMessage.ts
- libs/ledger-live-common/src/families/stacks/specs.ts
- libs/ledger-live-common/src/families/stacks/speculos-deviceActions.ts
- libs/ledger-live-common/src/families/stacks/transaction.ts
- libs/ledger-live-common/src/families/stacks/types.ts
- libs/ledger-live-common/src/families/stacks/utils.ts
Apply minor fixes to stacks integration
> Apply minor fixes to stacks integration

- .changeset/big-pugs-drum.md
- apps/ledger-live-mobile/src/components/AccountCard.tsx
- apps/ledger-live-mobile/src/components/Web3AppWebview/PlatformAPIWebview.tsx
- apps/ledger-live-mobile/src/screens/RequestAccount/02-SelectAccount.tsx
…d on mobil
Support token accounts in request account method on mobile.
https://github.com/LedgerHQ/ledger-live/assets/8398372/88b5b797-35b6-48b9-b60e-ff30f1992a4f
> Support token accounts in request account method on mobile

- .github/workflows/test.yml
- codecov.yml
codecov is not properly working since a few years now, it is polluting our repo with false positive info (it keeps raising fantasy % numbers). we will just remove it for now as it's not bringing anything valuable today (it's not measuring things properly).
at the same time, we will see how to approach code coverage & plan better solutions, we need this to be integrated on all our test approaches. codecov was actually only plugged to a very tiny part of all our test approaches.
> chore: sunset flawky codecov integration

- .github/workflows/gate.yml
Setup a job to update the lockfile on dependabot pull requests.
- **Linked resource(s)**: incoming 
> chore(dependabot): automate lockfile update for dependabot PRs

- .changeset/tall-files-exist.md
- apps/ledger-live-desktop/src/renderer/families/stellar/MemoTypeField.tsx
Fix stellar send flow ui. Add width to memo field.
> Fix: stellar memo ui

- .github/workflows/gate.yml
Fix git push in Gate workflow
- **Impacted projects**: CI 
> chore(dependabot): fix git push

- apps/ledger-live-mobile/src/screens/Portfolio/Header.tsx
LLM - Wallet - Switch Card entry point with QR code
- **Linked resource(s)**: [LIVE-7585] 
[LIVE-7585]: https://ledgerhq.atlassian.net/browse/LIVE-7585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(LLM): Switch Card entry point with QR code in Wallet

- libs/ledger-live-common/src/families/stacks/bridge/account.ts
fix estimateMaxSpendable func by adding recipient
> fix estimateMaxSpendable func by adding recipient

- .changeset/few-poets-knock.md
- apps/ledger-live-desktop/src/renderer/components/MainSideBar/index.tsx
- apps/ledger-live-desktop/src/renderer/modals/ProtectDiscover/index.tsx
Prevents Recover modal to affect the app performances.
- **Impacted projects**: `ledger-live-desktop`
- **Linked resource(s)**: [PROTECT-2016](https://ledgerhq.atlassian.net/browse/PROTECT-2016)
https://github.com/LedgerHQ/ledger-live/assets/102669540/04509944-4b83-4dc4-be18-79a52ae7e866
[PROTECT-2016]: https://ledgerhq.atlassian.net/browse/PROTECT-2016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: recover modal lag

- tools/github-bot/src/features/autoClose/index.ts
- tools/github-bot/src/features/autoClose/tools.ts
Allow renovate to work on the repo.
> chore(bot): allow for renovate

- tools/github-bot/package.json
- tools/github-bot/src/commands/generate-screenshots.ts
- tools/github-bot/src/commands/regen-doc.ts
- tools/github-bot/src/commands/regen-pods.ts
- tools/github-bot/src/commands/tools.ts
- tools/github-bot/src/features/autoClose/index.ts
- tools/github-bot/src/features/lintCommits/index.ts
- tools/github-bot/src/features/orchestrator/const.ts
- tools/github-bot/src/features/orchestrator/index.ts
- tools/github-bot/src/features/orchestrator/tools.ts
- tools/github-bot/src/features/upToDate/index.ts
- tools/github-bot/src/features/upToDate/tools.ts
- tools/github-bot/src/index.ts
- tools/github-bot/src/tools/index.ts
- tools/github-bot/src/tools/monitorWorkflow.ts
- tools/github-bot/src/tools/zip.ts
Add missing eslint config for github bot + lint fixes
- **Impacted projects**: `github-bot` 
> chore(bot): lint:fix bot

- .changeset/fluffy-lemons-know.md
- apps/ledger-live-desktop/RELEASE_NOTES.md
Update release notes
- **Linked resource(s)**: `release` 
> update release notes

- .changeset/gold-bobcats-attack.md
- apps/ledger-live-desktop/src/renderer/screens/platform/v2/Catalog/Card/hooks.ts
- libs/ledger-live-common/src/platform/types.ts
Display dappUrl instead of url when the live app is dapp.
Check POAP url for example.
> Display dappUrl instead of url when the live app is dapp

- .changeset/fresh-ducks-exercise.md
- apps/ledger-live-desktop/src/renderer/components/OperationsList/DateCell.tsx
Removes the double date existing in `DateCell.tsx`
> Bugfix - Remove double date in DateCell

- .changeset/poor-flowers-hope.md
- apps/ledger-live-mobile/src/components/AccountCard.tsx
Fix crash on selecting from account in swap form.
> Fix crash on selecting from account in swap form

- .changeset/modern-schools-explode.md
- libs/ledger-live-common/src/families/cosmos/api/Cosmos.test.ts
- libs/ledger-live-common/src/families/cosmos/api/Cosmos.ts
This PR adds support for pagination on cosmos nodes and remove the orderBy DESCENDING dirty fix for accounts that have more than 200 transactions
I tried to use the next_key parameter but it does not work...
see
https://cosmoshub4.coin.ledger.com/cosmos/tx/v1beta1/txs?events=transfer.recipient=%27cosmos1e533m29emngs7camh5rjzpxkr0ngyuekw95jeg%27&pagination.limit=10
Total is higher than 10 and next_key is still not defined
Doc says otherwise... but oh well
https://docs.cosmos.network/swagger/#/Service/GetTxsEvent
So i implemented the pagination with pagination.limit and pagination.offset, example :
https://cosmoshub4.coin.ledger.com/cosmos/tx/v1beta1/txs?events=transfer.recipient=%27cosmos1e533m29emngs7camh5rjzpxkr0ngyuekw95jeg%27&pagination.limit=50&pagination.offset=50
- **Impacted …
> feat:  pagination for cosmos nodes

- renovate.json
change renovate frequency (for now)
- **Impacted projects**: `live` 
> chore(renovate): change frequency

- .eslintrc.js
Remove the prettier plugin from eslint and just use the ruleset
https://typescript-eslint.io/linting/troubleshooting/performance-troubleshooting/
- **Impacted projects**: `live` 
- **Linked resource(s)**: @Justkant  
> chore(eslint): remove costly prettier plugin

- .changeset/pink-dogs-know.md
- apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx
- apps/ledger-live-mobile/src/components/Stake/index.tsx
Attempt to remove sentry navigation error that occur every prerelease
We shouldn't have a critical error when user stops his navigation flow
- **Linked resource(s)**: Sentry 
> remove critical error on navigation

- apps/ledger-live-mobile/e2e/bridge/server.ts
- apps/ledger-live-mobile/e2e/bridge/start-server.ts
- apps/ledger-live-mobile/e2e/helpers.ts
- apps/ledger-live-mobile/e2e/models/manager/managerPage.ts
- apps/ledger-live-mobile/e2e/models/trade/swapFormPage.ts
- apps/ledger-live-mobile/e2e/models/wallet/portfolioPage.ts
- apps/ledger-live-mobile/e2e/specs/deeplinks.spec.ts
- apps/ledger-live-mobile/e2e/specs/languageChange.spec.ts
- apps/ledger-live-mobile/e2e/specs/nftGallery.spec.ts
- apps/ledger-live-mobile/e2e/specs/password.spec.ts
- apps/ledger-live-mobile/e2e/specs/swap.spec.ts
- apps/ledger-live-mobile/src/components/CurrencyInput.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/SwapFormNavigator.tsx
- apps/ledger-live-mobile/src/components/TabBar/Transfer.tsx
- apps/ledger-live-mobile/src/components/TabBar/TransferDrawer.tsx
- apps/ledger-live-mobile/src/components/TransferButton.tsx
- apps/ledger-live-mobile/src/screens/Swap/Form/Max.tsx
- apps/ledger-live-mobile/src/screens/Swap/Form/Modal/Terms.tsx
- apps/ledger-live-mobile/src/screens/Swap/Form/TxForm/AmountInput.tsx
- apps/ledger-live-mobile/src/screens/Swap/Form/TxForm/From.tsx
- apps/ledger-live-mobile/src/screens/Swap/Form/TxForm/Selector.tsx
- apps/ledger-live-mobile/src/screens/Swap/Form/TxForm/To.tsx
- apps/ledger-live-mobile/src/screens/Swap/Form/index.tsx
- libs/ui/packages/native/src/components/Text/index.tsx
- libs/ui/packages/native/src/components/cta/Button/index.tsx
- Add swap test that goes up to 'Exchange' step, and supporting testIDs/ page model
- Removed redundant `await`/`async` in `loadConfig` function
- Some other prettier/stylistic changes
https://github.com/LedgerHQ/ledger-live/assets/87659842/80005a49-ef17-4570-9fb5-a253596e73f0
> Support/add basic UI llm swap test

- .changeset/gentle-kiwis-walk.md
> add changeset release notes

- .changeset/happy-moose-scream.md
- apps/ledger-live-desktop/src/renderer/screens/platform/v2/Catalog/Browse/Result/NoResult.tsx
- apps/ledger-live-desktop/src/renderer/screens/platform/v2/Catalog/Browse/Result/index.tsx
- apps/ledger-live-desktop/src/renderer/screens/platform/v2/Catalog/Browse/index.tsx
- apps/ledger-live-desktop/src/renderer/screens/platform/v2/hooks.ts
- apps/ledger-live-mobile/src/screens/Platform/v2/Catalog/Search/index.tsx
- apps/ledger-live-mobile/src/screens/Platform/v2/Catalog/index.tsx
- apps/ledger-live-mobile/src/screens/Platform/v2/hooks.ts
- libs/ledger-live-common/src/platform/providers/RemoteLiveAppProvider/index.tsx
- libs/ledger-live-common/src/wallet-api/react.ts
- libs/ledger-live-common/src/wallet-api/types.ts
Fix discover catalog visibility and ordering
- **Impacted projects**: `live-common`, `live-mobile`, `ledger-live-desktop` 
- **Linked resource(s)**: [`LIVE-7940`](https://ledgerhq.atlassian.net/browse/LIVE-7940) 
[LIVE-7940]: https://ledgerhq.atlassian.net/browse/LIVE-7940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix discover catalog visibility and ordering

- .github/workflows/bot-mere-denis.yml
- .github/workflows/bot-nitrogen.yml
- libs/env/src/env.ts
- libs/ledger-live-common/package.json
- libs/ledger-live-common/src/load/speculos.ts
- pnpm-lock.yaml
- tools/actions/composites/bot/action.yml
Add a github workflow option in bot to allow them to use websocket 
> [support] Add env var to switch speculos bot on websocket or REST

- .changeset/lazy-shirts-trade.md
- libs/coin-framework/src/bridge/jsHelpers.ts
Fix error during scan account with speculos.
- **Impacted projects**: `coin-framework` 
- **Linked resource(s)**: [LIVE-8139](https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/465?modal=detail&selectedIssue=LIVE-8139)
[LIVE-8139]: https://ledgerhq.atlassian.net/browse/LIVE-8139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-8139: fix Can't Open Device error with speculos bot test

- apps/ledger-live-mobile/src/components/DelegationDrawer.tsx
- apps/ledger-live-mobile/src/families/cosmos/DelegationFlow/04-ValidationSuccess.tsx
- apps/ledger-live-mobile/src/families/cosmos/RedelegationFlow/04-ValidationSuccess.tsx
- apps/ledger-live-mobile/src/families/elrond/accountActions.tsx
- apps/ledger-live-mobile/src/families/elrond/components/Flows/Delegate/components/SetDelegation/SetDelegation.tsx
- apps/ledger-live-mobile/src/families/elrond/components/Flows/Delegate/components/ValidationSuccess/ValidationSuccess.tsx
- apps/ledger-live-mobile/src/families/elrond/components/Flows/Delegate/types.ts
- apps/ledger-live-mobile/src/families/near/StakingFlow/02-Summary.tsx
- apps/ledger-live-mobile/src/families/near/StakingFlow/04-ValidationSuccess.tsx
- apps/ledger-live-mobile/src/families/near/StakingFlow/types.ts
- apps/ledger-live-mobile/src/families/near/accountActions.tsx
- apps/ledger-live-mobile/src/families/solana/DelegationFlow/ValidationSuccess.tsx
Implementation of the following tag to track on the last CTA for completing a staking: 
- Validator chosen 
- Successful staking
- Source of staking flow
For the following programs where Ledger is validator: NEAR, ELROND
- **Linked resource(s)**: `[LIVE-7674](https://ledgerhq.atlassian.net/browse/LIVE-7674)` 
N/A
[LIVE-7674]: https://ledgerhq.atlassian.net/browse/LIVE-7674?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Feat/LIVE-7674]: add staking tracking for NEAR, ELROND

- .changeset/afraid-pants-decide.md
- libs/ledger-live-common/src/config/index.ts
Let's reduce firebase usage, else we will have to get a pro plan
Increase ttl to 1 hour instead of 30mn
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-8225 
> increase ttl for coin config

- .changeset/two-eagles-cheat.md
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Onboarding/steps/ChoiceCard.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/NoLedgerYetModal.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/SelectionCard.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/postWelcomeSelection.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/useCaseSelection.tsx
fix icons alignment on new Onboarding
- **Linked resource(s)**: [LIVE-8205] 
[LIVE-8205]: https://ledgerhq.atlassian.net/browse/LIVE-8205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bugfix(LLM): fix icons aligment on new Onboarding

- .changeset/flat-garlics-shake.md
- apps/ledger-live-desktop/src/renderer/families/cosmos/DelegationFlowModal/steps/StepConfirmation.tsx
- apps/ledger-live-desktop/src/renderer/families/cosmos/RedelegationFlowModal/steps/StepConfirmation.tsx
Fix LLD Osmos track
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-8231
> fix: fix lld osmos track

- .changeset/flat-squids-warn.md
- apps/ledger-live-mobile/src/components/Nft/NftGallery/NftList.tsx
- apps/ledger-live-mobile/src/components/Nft/NftGallery/ScrollToTopButton.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
Scroll to top button to the NFT gallery page
- **Linked resource(s)**: `LIVE-7815` 
https://github.com/LedgerHQ/ledger-live/assets/1044686/b8fd969c-9d2c-4c37-99eb-1c73e51491ad
> feat: add scroll to top button to nft gallery

- apps/ledger-live-mobile/src/components/ValidateOnDevice.tsx
Confirm swap step (step 2) animation fixed as done with other device actions
- **Linked resource(s)**: N.A
> fix(LLM/Swap): Confirm swap step (step 2) animation fixed as done with other device actions

- apps/ledger-live-mobile/src/components/AccountCard.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/ReceiveFunds/01-SelectCrypto.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/02-SelectAccount.tsx
New Select Account UI
- **Linked resource(s)**: [LIVE-8308] 
https://github.com/LedgerHQ/ledger-live/assets/112866305/b2b3c930-a08f-40c9-a3bf-e36e1fe7d673
[LIVE-8308]: https://ledgerhq.atlassian.net/browse/LIVE-8308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> New Select Account UI

- .changeset/wise-spies-share.md
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.tsx
- apps/ledger-live-desktop/tests/models/SwapPage.ts
- apps/ledger-live-desktop/tests/specs/services/swap.spec.ts
- libs/ledger-live-common/src/exchange/swap/hooks/useFromState.test.ts
- libs/ledger-live-common/src/exchange/swap/hooks/useFromState.ts
- libs/ledger-live-common/src/exchange/swap/utils/debounce.ts
* Remove debounce logic from LLD specific swap page.
* More debounce logic to LLC.
* Add unit tests.
- **Impacted projects**: `LLC, LLD` 
- **Linked resource(s)**: [LIVE-8315](https://ledgerhq.atlassian.net/browse/LIVE-8315) 
https://github.com/LedgerHQ/ledger-live/assets/132384348/393901b8-16a5-4e1c-9882-db7e76d4d430
https://github.com/LedgerHQ/ledger-live/assets/132384348/11a6d6f3-5aa5-4447-9422-44526a7f3fba
[LIVE-8315]: https://ledgerhq.atlassian.net/browse/LIVE-8315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Fix/LIVE-8315]: move debounce logic on swap to LLC

- libs/env/src/env.ts
Just cleanup, trivial, zero impact.
- **Impacted projects**: `@ledgerhq/live-env` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-8345
> [support] Just cleanup unused legacy endpoint for Osmosis

- libs/ledger-live-common/src/families/cardano/speculos-deviceActions.ts
delegation screens updates for bot
> fix delegate screen title

- libs/ledger-live-common/src/families/cardano/speculos-deviceActions.ts
> add speculos action steps

- apps/ledger-live-mobile/ios/Podfile.lock
- apps/ledger-live-mobile/src/components/RootNavigator/BaseOnboardingNavigator.tsx
Adding a way for a user to come back from the pairing device menu during the onboarding.
- **Linked resource(s)**: [LIVE-8314](https://ledgerhq.atlassian.net/browse/LIVE-8314) 
[LIVE-8314]: https://ledgerhq.atlassian.net/browse/LIVE-8314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LLM - [LIVE-8314] : Fix stuck in pairing device screen

- apps/ledger-live-mobile/package.json
- apps/ledger-live-mobile/src/components/CopyLink.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/ReceiveFundsNavigator.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/ReceiveFunds/03-Confirmation.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/ConfirmationHeaderTitle.tsx
- pnpm-lock.yaml
Rework deposit qr code screen
Add package for handling haptic feedback
- **Impacted projects**: ``live-mobile
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-7522
- 
> LIVE-7522 - New deposit - Rework deposit qr code screen

- apps/ledger-live-mobile/src/components/FabActions/hooks/useAssetActions.tsx
Fixing the translation issue occurring in the Quick Actions section
- **Linked resource(s)**: [LIVE-8173] 
[LIVE-8173]: https://ledgerhq.atlassian.net/browse/LIVE-8173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix translation keys issue in LLM in the Quick Actions section

- apps/ledger-live-desktop/static/i18n/en/app.json
- apps/ledger-live-mobile/src/locales/en/common.json
Changes in wording on the recover app login
- **Impacted projects**: `LLM`, `LLD`
- **Linked resource(s)**: `PROTECT-1782`, `PROTECT-2171`
> feat(PROTECT-1782): Change the wording around login to recover app

- apps/ledger-live-desktop/package.json
- apps/ledger-live-mobile/ios/Podfile.lock
- apps/ledger-live-mobile/package.json
- libs/ui/packages/native/package.json
- libs/ui/packages/react/package.json
- pnpm-lock.yaml
This is apparently needed to upgrade Detox from the Q/A side? (yes, I am lacking context here)
> chore: upgrade babel/core to latest

- apps/ledger-live-mobile/src/components/RootNavigator/ReceiveFundsNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/types/ReceiveFundsNavigator.ts
- apps/ledger-live-mobile/src/screens/ReceiveFunds/01-SelectCrypto.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/02-SelectAccount.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/02-SelectNetwork.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/03-Confirmation.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/HelpButton.tsx
- libs/ledger-live-common/src/deposit/helper.ts
- libs/ledger-live-common/src/deposit/type.ts
- libs/ui/packages/native/src/components/Cards/BannerCard/index.tsx
> Starts screen connection + Edit Analytics + Update UI on Banner

- .changeset/calm-nails-report.md
- apps/ledger-live-mobile/src/screens/SendFunds/02-SelectRecipient.tsx
cherry-pick of #4024 to develop
> [LIVE-8490] Bugfix - Fix wrong `shouldSkipAmount` in LLM send flow

- .github/workflows/test-desktop.yml
- tools/github-bot/src/commands/full-suite.ts
Add a new command to run full test suite.
`/full-lld-tests` will run the `all` e2e test suite for LLD on each platform
- **Impacted projects**: `ci`, `lld` 
> chore: add test full suite command to github bot

- apps/ledger-live-mobile/src/components/BigCurrencyRow.tsx
- apps/ledger-live-mobile/src/components/FabActions/hooks/useAssetActions.tsx
> Update flow entry

- tools/github-bot/src/index.ts
connect the new command to the bot
- **Impacted projects**: `github bot` 
> chore: add command to bot

- apps/ledger-live-mobile/src/screens/WalletCentricAsset/AssetMarketSection.tsx
Fixing USDC Market Price component data due to the change in token id on Coingecko' s end
- **Linked resource(s)**: [LIVE-7318] 
[LIVE-7318]: https://ledgerhq.atlassian.net/browse/LIVE-7318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix USDC Market Price Component Data

- apps/ledger-live-desktop/tests/models/SwapPage.ts
- apps/ledger-live-desktop/tests/specs/services/liveapp-sdk.smoke.spec.ts
- apps/ledger-live-desktop/tests/specs/services/swap.smoke.spec.ts
- apps/ledger-live-desktop/tests/specs/services/swap.spec.ts
Added Playwright tests for when swap providers aren't available
- 404 from API
- Successful API response but with no providers
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/B2CQA-613
> B2CQA 613 -  Added Playwright tests for when swap providers aren't available

- apps/ledger-live-desktop/tests/fixtures/common.ts
Logging video path to make it easier to identify a pw video with a test
> Feat: logging playwright test video name in test

- apps/ledger-live-mobile/src/locales/en/common.json
Rename the CTA to access recover. `How does it benefit me?` -> `Get to know Ledger Recover`
- **Linked resource(s)**: `PROTECT-2239` 
> feat(PROTECT-2239): rename recover cta

- apps/ledger-live-desktop/src/renderer/families/cardano/Delegation/ContextMenu.tsx
- apps/ledger-live-desktop/src/renderer/families/cardano/index.ts
- apps/ledger-live-mobile/src/families/cardano/Delegations/Row.tsx
- apps/ledger-live-mobile/src/families/cardano/Delegations/index.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
Feedback updates for LLD and LLM 
- **Impacted projects**: `lld` `llm` 
> Cardano Staking - Feedback updates for LLD and LLM

- apps/ledger-live-mobile/fastlane/Fastfile
make sure to generate new profiles on refresh (and maybe certs ?)
> chore: make sure to generate new profiles on refresh

- .changeset/orange-books-scream.md
- apps/ledger-live-mobile/src/locales/en/common.json
LLM - Rephrase refer a friend banner in BTC account
- **Linked resource(s)**: [LIVE-8435] 
[LIVE-8435]: https://ledgerhq.atlassian.net/browse/LIVE-8435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 📝 [FEAT] - LLM - Rephrase refer a friend banner in BTC account

- apps/ledger-live-mobile/src/actions/settings.ts
- apps/ledger-live-mobile/src/components/BuyDeviceBanner.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/ReceiveFundsNavigator.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/reducers/settings.ts
- apps/ledger-live-mobile/src/screens/ReceiveFunds/03-Confirmation.tsx
Improvments for LLM Deposit
- **Linked resource(s)**: [LIVE-8815] [LIVE-8818] 
[LIVE-8815]: https://ledgerhq.atlassian.net/browse/LIVE-8815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-8818]: https://ledgerhq.atlassian.net/browse/LIVE-8818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FEAT] : ⚡️ Various Improvments on Deposit flow

- apps/ledger-live-mobile/src/components/FilteredSearchBar.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/01-SelectCrypto.tsx
Deposit flow add debounce to search crypto analytic
> feat(llm): deposit flow add debounce to search crypto analytic

- apps/ledger-live-mobile/src/screens/ReceiveFunds/01-SelectCrypto.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/02-SelectNetwork.tsx
Fix networks and crypto shown when deposit from NFT only MATIC & ETH
> 🐛 [FIX]: networks and crypto shown when deposit from NFT only MATIC & ETH

- .changeset/moody-ants-destroy.md
- apps/ledger-live-desktop/src/renderer/screens/platform/v2/Catalog/Card/Full.tsx
Adding translates support for discover v2 manifests
- **Impacted projects**: `LLD`
- **Linked resource(s)**: ``
> fix(discover): Add support for translates

- .changeset/chatty-apples-doubt.md
- .changeset/twelve-parrots-film.md
- apps/ledger-live-desktop/src/renderer/components/Carousel/Slide.tsx
- apps/ledger-live-desktop/src/renderer/components/Carousel/index.tsx
- apps/ledger-live-desktop/src/renderer/components/MainSideBar/index.tsx
- apps/ledger-live-desktop/static/i18n/en/app.json
- libs/ledger-live-common/src/featureFlags/defaultFeatures.ts
Added a tag for the referral in the sidebar with a new copy displaying the amount of the reward
Also a fix added to the size of the images in the content cards of the portfolio
- **Impacted projects**: `lld/llc` 
- **Linked resource(s)**: [LIVE-8433] 
[LIVE-8433]: https://ledgerhq.atlassian.net/browse/LIVE-8433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(lld): added a tag for the referral in the sidebar with a new copy

- .changeset/chilled-eagles-speak.md
- apps/ledger-live-desktop/src/renderer/reducers/settings.ts
- apps/ledger-live-desktop/src/renderer/screens/earn/index.tsx
- apps/ledger-live-desktop/tests/specs/services/earn.spec.ts
Add the locale param to the Earn app URL
> feat: adding locale and language to params

- .changeset/nine-oranges-guess.md
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/Rates/index.tsx
- apps/ledger-live-mobile/src/screens/Swap/Form/index.tsx
- Add `Swap Form - Edit Rates` tracking event to LLM.
- Add the following to this event on both LLD and LLM:
```ts
partnersList: string[];
exchangeRatesState: string[];
sourceCurrency: string;
targetCurrency: string;
```
- **Linked resource(s)**: [LIVE-7863](https://ledgerhq.atlassian.net/browse/LIVE-7863) 
[LIVE-7863]: https://ledgerhq.atlassian.net/browse/LIVE-7863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Feat/LIVE-7863]: Swap Form - Edit Rates tracking updates

- .changeset/sour-fishes-wash.md
- apps/ledger-live-desktop/src/renderer/modals/AddAccounts/steps/StepChooseCurrency.tsx
- apps/ledger-live-mobile/src/screens/AddAccounts/01-SelectCrypto.tsx
Feature flag wasn't correctly defined for Secret Network, causing it to always be available even with feature flag off.
- **Impacted projects**: `LLD` `LLM` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-8916
> [bugfix] Secret Network feature flag

- .changeset/dirty-points-argue.md
- apps/ledger-live-mobile/e2e/models/wallet/portfolioPage.ts
- apps/ledger-live-mobile/e2e/setup.ts
- apps/ledger-live-mobile/e2e/specs/wallet-api.spec.ts
- apps/ledger-live-mobile/src/screens/PTX/Earn/index.tsx
Add locale param to Earn app navigation.
I started adding a test but the current way of loading a manifest is locked to just the wallet API test app, so it will be a bigger rework to make other apps possible.
The test will look like this:
```
import { by, web } from "detox"; // this is because we need to use both the jest expect and the detox.expect version, which has some different assertions
import { loadConfig } from "../bridge/server";
import { isAndroid } from "../helpers";
import PortfolioPage from "../models/wallet/portfolioPage";
import LiveAppWebview from "../models/liveApps/liveAppWebview";
import { stopDummyServer } from "@ledgerhq/test-utils";
let portfolioPage: PortfolioPage;
let liveAppWebview: LiveAppWebview;
let continueTest: boolean;
describe("Earn", () => { …
```
> LLM: added locale to Earn App URL

- .changeset/young-monkeys-appear.md
- apps/ledger-live-mobile/src/families/cardano/DelegationFlow/01-Started.tsx
- apps/ledger-live-mobile/src/families/cardano/DelegationFlow/SelectPool.tsx
Recent merge of Cardano staking (https://github.com/LedgerHQ/ledger-live/pull/3388) introduced a few lint warnings on LLM, this PR fixes them.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-3196 
> [support] Add missing keys to RN components

- .github/workflows/test.yml
- libs/ledgerjs/README.md
- turbo.json
As discussed with @haammar-ledger, it was (and still is) a pain to find errors through the multiple steps required to make the tests work.
As such, I have splitted the libraries `tests` from the `lint` and `typecheck` (which are grouped together now) and updated the documentation wherever I was required and updated the outputs of the CI for the reports.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-8929 
> chore: split tests in test.yml

- apps/ledger-live-mobile/ios/Podfile.lock
- apps/ledger-live-mobile/package.json
- apps/ledger-live-mobile/src/components/StorylyStories/index.tsx
- pnpm-lock.yaml
This PR updates Storyly to fix seen attributes update: https://github.com/Netvent/storyly-mobile/issues/246
Unfortunately, the new version does not update seen attribute on a Story Group but for each story so we still need to manually update it for a group.
https://github.com/LedgerHQ/ledger-live/assets/31533861/d30e655e-79cb-4ad5-bc01-85212373a4da
Must work as before. When you have seen a story group the custom circle must disappear.
> LLM - Storyly update

- libs/ledger-live-common/src/exchange/swap/api/v5/fetchCurrencyAll.ts
- libs/ledger-live-common/src/exchange/swap/api/v5/fetchCurrencyFrom.ts
- libs/ledger-live-common/src/exchange/swap/api/v5/fetchCurrencyTo.ts
- libs/ledger-live-common/src/exchange/swap/getExchangeRates.ts
- libs/ledger-live-common/src/exchange/swap/getProviders.ts
- libs/ledger-live-common/src/exchange/swap/getStatus.ts
- libs/ledger-live-common/src/exchange/swap/postSwapState.ts
- libs/ledger-live-common/src/exchange/swap/utils/isIntegrationTestEnv.ts
- libs/ledger-live-common/src/exchange/swap/utils/isPlaywrightEnv.ts
Rename test env check fn from `isPlaywrightEnv` to `isIntegrationTestEnv`
- **Linked resource(s)**: ``
> support(test-env): rename test env check fn

- .changeset/shy-cows-yell.md
- apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/AppsList.tsx
- apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/Item.tsx
- apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/UpdateAllApps.tsx
If a feature flag name for a currency contains another existing currency (e.g `feature_currency_polygon_zk_evm` containing `polygon`) then the two currencies will conflict in the manager, causing https://ledgerhq.atlassian.net/browse/LIVE-8884
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-8884
> [bugfix] Avoid conflicts in currency feature flag names in manager

- .changeset/brave-jokes-relax.md
- apps/ledger-live-desktop/src/main/window-lifecycle.ts
- apps/ledger-live-desktop/src/renderer/components/WebRecoverPlayer/index.tsx
Using minirecover locally you need to set `IGNORE_CERTIFICATE_ERRORS=1`
> support: add recover local dev support

- .github/workflows/release-final.yml
Automatic trigger of release packages when using the `[Release](Hotfix) Prepare for releasing` workflow
> ci: add automatic trigger after using release prepare hotfix

- .changeset/friendly-mangos-pretend.md
- libs/ledger-live-common/src/families/cosmos/chain/Coreum.ts
Update coreum staking doc url
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/CSM-1524
> LIVE-8683 Update coreum staking doc url

- .changeset/red-coins-sneeze.md
- .changeset/shiny-carrots-mix.md
- .changeset/smooth-keys-brake.md
- apps/ledger-live-desktop/static/i18n/en/app.json
- apps/ledger-live-mobile/src/components/CustomImage/imageUtils.ts
- apps/ledger-live-mobile/src/components/CustomImage/useCenteredImage.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/CustomImage/PreviewPreEdit.tsx
- libs/ledger-live-common/src/customImage/errors.ts
The current error `ImageMetadataLoadingError` is too generic and used in very different cases, so we decided to split it in order to allow for a better UX (more accurate information given by error messages).
- **Impacted projects**: `llm` `lld` 
- **Linked resource(s)**: [LIVE-8601] 
[LIVE-8601]: https://ledgerhq.atlassian.net/browse/LIVE-8601?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(llm/customlockscreen): differentiation between error messages

- .changeset/popular-brooms-float.md
- apps/ledger-live-mobile/src/screens/Market/MarketDetail/index.tsx
Market details screen has no data under certain conditions (see screenshot below).  Now market details refresh when switching back to tab.
Steps to reproduce bug:
- LLM develop
- Enable ptxEarn
- Go to the new Market tab
- Click on a coin
- Click on “Crypto” on top left to be redirected to Portfolio
- Open the page for one account and go back to Portfolio with back arrow
- From Portfolio, navigate back to the new Market tab by clicking on Market on top
- **Linked resource(s)**: `LIVE-7162` 
Should display and what displays after this fix:
Bug display: …
> fix: no market data on market tab switching

- apps/ledger-live-mobile/src/families/evm/accountActions.tsx
Correct icon for staking
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-8998` 
> [BUGFIX][LIVE-8998][LLM] correct staking icon

- .changeset/dull-wombats-refuse.md
- libs/ledger-live-common/src/families/stacks/__tests__/sync.integration.test.ts
- libs/ledger-live-common/src/families/stacks/bridge/utils/api.ts
- libs/ledger-live-common/src/families/stacks/bridge/utils/misc.ts
Fix possible bug when parsing txns for stacks blockchain. 
- ledger-live-commons
> Bugfix/stacks: Parsing unknown txns 

- apps/ledger-live-desktop/src/renderer/modals/Receive/Body.tsx
- apps/ledger-live-desktop/src/renderer/modals/Receive/steps/StepReceiveFunds.tsx
- apps/ledger-live-desktop/src/renderer/screens/nft/Collections/Collections.tsx
Remove stake banner from receive nft flow
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-8858
> fix: remove stake banner from nft receive flow

- apps/ledger-live-mobile/src/screens/SendFunds/01c-SelectNft.tsx
Fix typing related issue on LLM causing an error when sending nft.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-9037
| Before | After |
|--------|--------|
|  <video src="https://github.com/LedgerHQ/ledger-live/assets/9203826/61bb6579-ff74-46c3-a31b-a40931e849fd">  | <video src="https://github.com/LedgerHQ/ledger-live/assets/9203826/0bf75192-459d-4685-87be-74cba068d55d"> |
> [BUGFIX][LIVE-9037] Fix LLM error on NFT send flow

- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Settings/index.tsx
Updated the tile of the enjoy screen in the nps flow
- **Linked resource(s)**: [LIVE-8888] 
[LIVE-8888]: https://ledgerhq.atlassian.net/browse/LIVE-8888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 💬  LLM - updated the tile of the enjoy screen in the nps flow

- .changeset/soft-berries-peel.md
- apps/ledger-live-mobile/src/screens/Onboarding/steps/protectFlow.tsx
- apps/ledger-live-mobile/src/screens/SyncOnboarding/SyncOnboardingCompanion.tsx
The base was missing to navigate in case the onboarding was the only screen present
> fix: accessing restore flow from onboarding

- .changeset/calm-falcons-kiss.md
- apps/ledger-live-desktop/src/renderer/hooks/useDeeplinking.ts
- apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx
Add deeplink_clicked track to LLM and improve deeplink_clicked track to LLD
- **Impacted projects**: LLM LLD
https://ledgerhq.atlassian.net/browse/LIVE-8880
https://ledgerhq.atlassian.net/browse/LIVE-9077
> fix: add deeplink track to llm and improve deeplink track lld

- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/SendFunds/02-SelectRecipient.tsx
Added a warning to the select recipient screen when there is already a send transaction pending
- **Linked resource(s)**: [LIVE-7717] 
[LIVE-7717]: https://ledgerhq.atlassian.net/browse/LIVE-7717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 💄 LLM - add warning on send flow when a tx is pending

- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/SyncOnboarding/EarlySecurityCheck.tsx
- apps/ledger-live-mobile/src/screens/SyncOnboarding/EarlySecurityCheckBody.tsx
- apps/ledger-live-mobile/src/screens/SyncOnboarding/FirmwareUpdateAvailableDrawer.tsx
- apps/ledger-live-mobile/src/screens/SyncOnboarding/GenuineCheckErrorDrawer.tsx
Implementation of tracking plan for LLM early security checks
- **Linked resource(s)**: [LIVE-7306] 
[LIVE-7306]: https://ledgerhq.atlassian.net/browse/LIVE-7306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(llm/earlysecuritychecks): implemented tracking plan

- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/ReceiveFunds/03-Confirmation.tsx
small deposit copy updates
- **Linked resource(s)**: [LIVE-9078] 
[LIVE-9078]: https://ledgerhq.atlassian.net/browse/LIVE-9078?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> support(llm): small deposit copy updates

- .changeset/khaki-hounds-reply.md
- apps/ledger-live-desktop/index-types.d.ts
- apps/ledger-live-desktop/src/renderer/components/OnboardingAppInstall/index.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/CompletionScreen.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/DesyncOverlay.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/Header.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/SyncOnboardingCompanion.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/assets/index.d.ts
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/index.tsx
- apps/ledger-live-desktop/tools/config/common.esbuild.js
Stax Pixel Polishing for LLD Sync Onboarding + add of the completed animation.
- **Linked resource(s)**: [LIVE-8596] [LIVE-6327]
https://github.com/LedgerHQ/ledger-live/assets/39890664/4813cb19-dd42-41e3-9d63-b69594958e35
[LIVE-8596]: https://ledgerhq.atlassian.net/browse/LIVE-8596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-6327]: https://ledgerhq.atlassian.net/browse/LIVE-6327
> feat(LLD/Sync Onboarding): Pixel polishing

- tools/common-tools/src/demos/index.js
- tools/common-tools/src/demos/svgIcons/App.css
- tools/common-tools/src/demos/svgIcons/index.js
we are seeing more and more incoming PRs that don't correctly pass the requirements for SVG Icons.
This PR implements a PoC of a tool that would be helpful to guide external developers through: instead of directly sending PRs on this repository, they can go to a page that validate all the requirements for them. See this video:
https://github.com/LedgerHQ/ledger-live/assets/211411/66ecb55b-cd27-4b91-a0d5-374e0b754c3f
I consider this PR can already be merged but there will need to be further improvements for a better DX:
- crypto-icons and live-common/data/icons are two places to actually target => instead we will try to kill the live-common's location and only have it all using the same place.
- it would be great to figure out a way to "convert" the SVG in-place. for now it's going to be …
> chore: add /svg-icons in common tools

- apps/ledger-live-desktop/src/renderer/components/TransactionConfirm/index.tsx
- libs/coin-evm/jest.config.js
- libs/coin-evm/package.json
- libs/coin-evm/src/__tests__/unit/api/gasTracker/ledger.unit.test.ts
- libs/coin-evm/src/api/gasTracker/ledger.ts
- libs/coin-evm/tsconfig.json
- pnpm-lock.yaml
<details><summary>The issue 📸  </summary>
</details> 
> Since our use of BigNumber implies only using integers, we need to round up to integer value with `integerValue()` after doing some math (like multiplying with a possible float value in this case)
Make sure bignumber fee values are integer to prevent rounding error between what is displayed on LL screens and what is displayed on nano device screen. Especially when interacting with `EIP1559_BASE_FEE_MULTIPLIER` that can be a float value.
Similar to what was done here https://github.com/LedgerHQ/ledger-live/blob/305f97b/libs/ledger-live-common/src/families/ethereum/react.ts
Could be removed once we remove the use of `EIP1559_BASE_FEE_MULTIPLIER` with https://ledgerhq.atlassian.net/browse/LIVE-7356
Add [`jest-expect-message` …
> [BUGFIX][LIVE-9028] fix fees rounding issue

- apps/ledger-live-mobile/src/locales/en/common.json
Adjust wording on recover Card
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/PROTECT-2420`
> feat(protect-2420): update recover wording

- libs/coin-framework/src/account/serialization.ts
- libs/ledger-live-common/src/families/cosmos/account.ts
> [WIP]fix: cosmos unit tests

- libs/coin-evm/.eslintrc.js
- libs/coin-evm/src/__tests__/fixtures/prepareTransaction.fixtures.ts
- libs/coin-evm/src/__tests__/integration/bridge.integration.test.ts
- libs/coin-evm/src/__tests__/unit/api/explorer/index.unit.test.ts
- libs/coin-evm/src/__tests__/unit/hw-getAddress.unit.test.ts
- libs/coin-evm/src/__tests__/unit/preload.unit.test.ts
- libs/coin-evm/src/__tests__/unit/signOperation.unit.test.ts
- libs/coin-evm/src/api/node/ledger.ts
- libs/coin-evm/src/api/node/rpc.common.ts
- libs/coin-evm/src/cli-transaction.ts
- libs/coin-evm/src/hw-signMessage.ts
- libs/coin-evm/src/prepareTransaction.ts
- libs/coin-evm/src/signOperation.ts
- libs/coin-evm/src/signer.ts
- libs/coin-evm/src/specs.ts
- libs/coin-evm/src/speculos-deviceActions.ts
- libs/coin-evm/src/synchronization.ts
- libs/coin-framework/src/bot/specs.ts
- libs/coin-framework/src/bot/types.ts
- Add [`explicit-function-return-type`](https://typescript-eslint.io/rules/explicit-function-return-type/) rule on `coin-evm` lib
- > Explicit return types do make it visually more clear what type is returned by a function. They can also speed up TypeScript type checking performance in large codebases with many large functions.
- Move some private types from `libs/coin-framework/src/bot/specs.ts` to `libs/coin-framework/src/bot/types.ts` and export them, to make them available for other libs (in order to explicitly type returns of functions for example)
- Update [`explicit-function-return-type`](https://typescript-eslint.io/rules/explicit-function-return-type/) as error for source files. Keep it as warning for tests files
- Fix `Unexpected any` errors in `coin-evm` src 
- **Impacted …
> [SUPPORT] Strengthen ts checks for coin-evm lib

- .changeset/proud-kangaroos-bake.md
- apps/ledger-live-desktop/src/renderer/families/solana/shared/components/LedgerByFigmentTCLink.tsx
- libs/ledger-live-common/src/families/solana/banner.ts
- libs/ledger-live-common/src/families/solana/js-preload.ts
- libs/ledger-live-common/src/families/solana/react.integration.test.ts
- libs/ledger-live-common/src/families/solana/utils.ts
- libs/ledger-live-common/src/families/solana/validator-app/index.ts
**(Backport of https://github.com/LedgerHQ/ledger-live/pull/4540 for `release` branch)**
The external backend we use to provide Solana validators details is flaky and sometimes doesn't provide details for the Ledger validator.
Long-term fix will consists in either fixing the external backend (unlikely, as validators.app has been unreliable for a long time now), or changing the provider we use to retrieve validators details for Solana.
In the meantime this PR mitigates this by using harcoded data as fallback if we don't get it from the backend.
- **Impacted projects**: `LLC` `LLD` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-9101 
_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-s …
> Hardcode Ledger validator details for Solana (release)

- .changeset/proud-kangaroos-bake.md
- apps/ledger-live-desktop/src/renderer/families/solana/shared/components/LedgerByFigmentTCLink.tsx
- libs/ledger-live-common/src/families/solana/banner.ts
- libs/ledger-live-common/src/families/solana/js-preload.ts
- libs/ledger-live-common/src/families/solana/react.integration.test.ts
- libs/ledger-live-common/src/families/solana/utils.ts
- libs/ledger-live-common/src/families/solana/validator-app/index.ts
The external backend we use to provide Solana validators details is flaky and sometimes doesn't provide details for the Ledger validator.
Long-term fix will consists in either fixing the external backend (unlikely, as validators.app has been unreliable for a long time now), or changing the provider we use to retrieve validators details for Solana.
In the meantime this PR mitigates this by using harcoded data as fallback if we don't get it from the backend.
- **Impacted projects**: `LLC` `LLD` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-9101  …
> Hardcode Ledger validator details for Solana

- .changeset/odd-spies-give.md
- apps/ledger-live-desktop/src/renderer/components/Exporter/QRCodeExporter.tsx
- libs/ledger-live-common/src/__snapshots__/cross.test.ts.snap
- libs/ledger-live-common/src/cross.test.ts
- libs/ledger-live-common/src/cross.ts
Add modelId and modelIdList in meta object when we do an export from the settings.
- **Impacted projects**: `llc` `lld` 
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-5226` 
> fix: Add modelId and modelIdList to metadata on export

- .changeset/four-months-battle.md
- apps/ledger-live-desktop/src/renderer/components/MainSideBar/index.tsx
Adds new tag to Earn in main side bar
- **Linked resource(s)**: `LIVE-6992` 
> feat: add new tag to earn in main side bar

- pnpm-lock.yaml
- tools/actions/change-product-name/action.yml
- tools/actions/composites/bot/action.yml
- tools/actions/generate-bot-super-report/build/main.js
- tools/actions/generate-bot-super-report/logic.ts
- tools/actions/generate-bot-super-report/package.json
- tools/actions/generate-release-message/action.yml
- tools/actions/get-workflow-artifacts-id/action.yml
- tools/actions/get-workflow-artifacts-id/build/main.js
- tools/actions/live-common-affected/action.yml
- tools/actions/prepare-comment-screenshots/action.yml
- tools/actions/submit-bot-report/action.yml
- tools/actions/submit-bot-report/build/main.js
- tools/actions/submit-bot-report/main.ts
- tools/actions/submit-bot-report/package.json
- tools/actions/turbo-affected/action.yml
- tools/actions/turborepo-gh-cache/action.yml
- tools/actions/turborepo-gh-cache/build/server.js
- tools/actions/turborepo-s3-cache/action.yml
- tools/actions/upload-images/build/main.js
- tools/actions/upload-images/main.ts
- tools/actions/upload-images/package.json
The PR #4539 was supposed to switch to node20 engine for our github actions (which should have a fetch implementation) but it seems it could not find a fetch function.
Using node-fetch to fix the builds.
- **Impacted projects**: `actions` 
- **Linked resource(s)**: #4539 
> fix: broken fetch in actions

- apps/ledger-live-mobile/src/components/FabActions/hooks/useAssetActions.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/SwapFormNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/SwapNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/types/SwapFormNavigator.ts
- apps/ledger-live-mobile/src/components/RootNavigator/types/SwapNavigator.ts
- apps/ledger-live-mobile/src/screens/Account/hooks/useAccountActions.tsx
- apps/ledger-live-mobile/src/screens/Swap/Form/index.tsx
- apps/ledger-live-mobile/src/screens/Swap/types.ts
Fix deeplink 
- **Impacted projects**: https://ledgerhq.atlassian.net/browse/LIVE-9197
- **Linked resource(s)**:  LLM
> fix: fix swap deeplink assets and accounts | token and currencies

- libs/env/src/env.ts
```
* It's just here as a backup, the REST API is supposed to be the right mode
* We can always fallback on the previous method if we need to.
* The websocket option is harmless, we can remove it at some point but let's
* keep it for a while just in case.
* Introduced on June 27th 2023 by https://github.com/LedgerHQ/ledger-live/pull/3824
```
> [SUPPORT] add comment for SPECULOS_USE_WEBSOCKET env var

- apps/ledger-live-mobile/ios/ledgerlivemobile.xcodeproj/project.pbxproj
This PR add all available languages to the IOS app configuration file.
- **Linked resource(s)**: [LIVE-7889] 
[LIVE-7889]: https://ledgerhq.atlassian.net/browse/LIVE-7889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LLM] - [LIVE-7889] - Adding available languages to IOS app

- apps/ledger-live-mobile/src/components/BleDevicePairingFlow/BleDevicesScanning.tsx
Add Help Icon and update design
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/463?modal=detail&selectedIssue=LIVE-6340` 
> fix: ble stax pairing help link

- .changeset/olive-ants-clean.md
- apps/ledger-live-mobile/src/components/Web3AppWebview/PlatformAPIWebview.tsx
- apps/ledger-live-mobile/src/components/Web3AppWebview/WalletAPIWebview.tsx
wallet api web view to open ios links
> feat: wallet api web view to open ios links

- .changeset/twenty-ears-care.md
- apps/ledger-live-desktop/jest.config.js
- apps/ledger-live-mobile/jest.config.js
Include untested files in code coverage calculation.
- **Impacted projects**: `LLM` `LLD`
- **Linked resource(s)**: `LIVE-9251` 
Code Coverage will include untested files.
> chore: coverage including untested files

- .github/workflows/test-mobile-e2e.yml
- apps/ledger-live-mobile/detox.config.js
- apps/ledger-live-mobile/e2e/bridge/client.ts
- apps/ledger-live-mobile/e2e/models/onboarding/onboardingSteps.ts
- apps/ledger-live-mobile/e2e/setup.ts
- apps/ledger-live-mobile/ios/Podfile.lock
- apps/ledger-live-mobile/package.json
- apps/ledger-live-mobile/src/screens/Onboarding/steps/discoverLiveInfo.tsx
- pnpm-lock.yaml
Fixing flakiness :
- onboardingReadOnly test : fix discover carousel  by disabling animation when MOCK
- Selecting free port for web socket servers and sharing it with client through Launch Arguments
- Emulator won’t restart between each test to prevent some shutdown failure
> [B2CQA-1965] Fix detox tests flakiness

- .changeset/quick-students-glow.md
- apps/ledger-live-desktop/tests/specs/services/buy.spec.ts
- apps/ledger-live-mobile/src/components/RootNavigator/ExchangeLiveAppNavigator.tsx
- apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx
- libs/ledger-live-common/src/wallet-api/constants.ts
update manifest id for multibuy to v2
- **Impacted projects**: Relates to: https://github.com/LedgerHQ/manifest-api/pull/238
- **Linked resource(s)**:  Closes https://ledgerhq.atlassian.net/browse/LIVE-9355
> feat: update manifest id for multibuy to v2

- .changeset/plenty-starfishes-train.md
- apps/ledger-live-mobile/src/screens/VerifyAccount/VerifyAddress.ts
- apps/ledger-live-mobile/src/screens/VerifyAccount/index.tsx
Improves the verify account screen used in the wallet-api and platform
- **Linked resource(s)**: [`LIVE-7751`](https://ledgerhq.atlassian.net/browse/LIVE-7751) 
https://github.com/LedgerHQ/ledger-live/assets/3009753/330ad013-a788-41f2-9bee-18a8bf625ec2
> fix: wallet-api & platform verify account screen [LIVE-7751]

- apps/ledger-live-desktop/static/i18n/en/app.json
Update auto update banner wording
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-9085` 
> chore: update wording auto-update banner

- .changeset/brown-lions-speak.md
- apps/ledger-live-mobile/src/components/WebPTXPlayer/index.tsx
- apps/ledger-live-mobile/src/screens/PTX/BuyAndSell/index.tsx
llm reset storage ptx web player
> feat: llm reset storage ptx web player

- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/NpsRatingsModal/Form.tsx
Update NPS condition to 8 and some wording.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-9143` + `https://ledgerhq.atlassian.net/browse/LIVE-9280` 
> Nps rating

- .changeset/great-tomatoes-punch.md
- apps/ledger-live-desktop/src/renderer/families/cosmos/StakeBanner.tsx
Replace incorrect link on account page banner with correct link to learn more about delegation for cosmos.
- **Impacted projects**: `` ledger live desktop
- **Linked resource(s)**: ``  https://ledgerhq.atlassian.net/browse/LIVE-9327#
> fix: replace eth link with cosmos staking link

- .changeset/quick-olives-grab.md
- libs/ledger-live-common/src/platform/converters.ts
- libs/ledger-live-common/src/platform/logic.ts
- libs/ledger-live-common/src/wallet-api/converters.ts
- libs/ledger-live-common/src/wallet-api/logic.ts
- improve variable naming in `converters` files
- compare liveTx family to live account family
- Perform the conversion from wallet-api to LL tx before asserting families match. In order to compare apple to apple
- Perform the same logic in platform-sdk logic and remove odd exception in condition
🧪  Note on tests:
[`completeExchangeLogic`](https://github.com/LedgerHQ/ledger-live/blob/35cb4422944f1e7af696c816a53a6ada74525de2/libs/ledger-live-common/src/platform/logic.test.ts#L110-L336)  tests from `platform` should be ported to [`wallet-api`](https://github.com/LedgerHQ/ledger-live/blob/develop/libs/ledger-live-common/src/wallet-api/logic.test.ts) cc. @LedgerHQ/wallet-api 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-9426
_Please make …
> [BUGFIX] fix wallet-api complete exchange logic

- apps/ledger-live-mobile/e2e/models/onboarding/onboardingSteps.ts
- apps/ledger-live-mobile/e2e/models/receive.ts
- apps/ledger-live-mobile/e2e/specs/addAccounts/bitcoin.spec.ts
- apps/ledger-live-mobile/e2e/specs/manager.spec.ts
- apps/ledger-live-mobile/e2e/specs/market.spec.ts
- apps/ledger-live-mobile/e2e/specs/nftGallery.spec.ts
- apps/ledger-live-mobile/e2e/specs/receive/bitcoin.spec.ts
- apps/ledger-live-mobile/e2e/specs/send/bitcoin.spec.ts
- apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx
- apps/ledger-live-mobile/src/screens/AddAccounts/03-Accounts.tsx
- apps/ledger-live-mobile/src/screens/Manager/Device/StorageBarItem.tsx
- apps/ledger-live-mobile/src/screens/PairDevices/Scanning.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/ReceiveSecurityModal/ConfirmUnverified.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/ReceiveSecurityModal/InitMessage.tsx
- libs/ui/packages/native/src/components/Loader/InfiniteLoader/index.tsx
_Infinite animation prevents detox from resuming testing. Disabling animation synchronisation causes tests to be flaky. Hence, we disable problematic animations when MOCK=1_
> [B2CQA-1972] Detox fix animations flakiness

- apps/ledger-live-mobile/src/components/BleDevicePairingFlow/BleDevicesScanning.tsx
Add padding bottom for can't find my ledger message
> fix: can't find my ledger padding

- apps/web-tools/package.json
one of the solution to our ongoing problem is to "set the package.json name exactly as the folder", so maybe it's our remaining fix for our caching issue 🤞 
https://stackoverflow.com/questions/70758736/nextjs-vercel-deployment-error-routes-manifest-json-couldnt-be-found/75774960
> chore(web-tools): make sure to name it 'web-tools' in package.json

- .changeset/short-dogs-buy.md
- libs/ledgerjs/packages/cryptoassets/src/currencies.ts
Zcash explorer was chain.so and do not support zcash anymore. Update the explorer to zcashblockexplorer.com.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-9239
> Feat/live 9239 update zcash explorer to zcashblockexplorer.com

- libs/ledger-live-common/src/exchange/swap/hooks/v5/useProviderRates.ts
set exchange rate to undefined
> fix: set exchange rate to undefined

- .changeset/gentle-tomatoes-draw.md
- .changeset/tender-laws-itch.md
- apps/ledger-live-desktop/src/renderer/families/algorand/AccountHeaderManageActions.ts
- apps/ledger-live-desktop/src/renderer/families/cardano/AccountHeaderManageActions.ts
- apps/ledger-live-desktop/src/renderer/families/cosmos/AccountHeaderManageActions.ts
- apps/ledger-live-desktop/src/renderer/families/elrond/AccountHeaderManageActions.ts
- apps/ledger-live-desktop/src/renderer/families/evm/AccountHeaderManageActions.ts
- apps/ledger-live-desktop/src/renderer/families/near/AccountHeaderManageActions.ts
- apps/ledger-live-desktop/src/renderer/families/polkadot/AccountHeaderManageActions.ts
- apps/ledger-live-desktop/src/renderer/families/solana/AccountHeaderManageActions.ts
- apps/ledger-live-desktop/src/renderer/families/tezos/AccountHeaderManageActions.ts
- apps/ledger-live-desktop/src/renderer/screens/account/AccountHeaderActions.tsx
- apps/ledger-live-mobile/src/components/FabActions/hooks/useAssetActions.tsx
- apps/ledger-live-mobile/src/families/cosmos/accountActions.tsx
- apps/ledger-live-mobile/src/families/elrond/accountActions.tsx
- apps/ledger-live-mobile/src/families/evm/accountActions.tsx
- apps/ledger-live-mobile/src/families/near/accountActions.tsx
- apps/ledger-live-mobile/src/families/polkadot/accountActions.tsx
- apps/ledger-live-mobile/src/families/solana/accountActions.tsx
- apps/ledger-live-mobile/src/families/tezos/accountActions.tsx
- apps/ledger-live-mobile/src/hooks/useQuickActions.ts
- Make sure Staking button icon is the same on LLM and LLD
- Add linespaces for better readability  
- **Impacted projects**: `LLD` `LLM`
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-9335` 
> [LLM & LLD] Update staking button

- .changeset/small-jars-hug.md
To avoid yielding a major update on customer facing applications when the changes should be transparents to them.
> Change LLM and LLD changesets from major to minor

- apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx
- apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/NetworkError.tsx
- apps/ledger-live-desktop/src/renderer/screens/customImage/Step1ChooseImage.tsx
- apps/ledger-live-desktop/src/renderer/screens/customImage/Step2AdjustImage.tsx
- apps/ledger-live-desktop/src/renderer/screens/customImage/Step3ChooseContrast.tsx
- apps/ledger-live-desktop/src/renderer/screens/customImage/Step4Transfer.tsx
- apps/ledger-live-desktop/static/i18n/en/app.json
Update wording:
https://www.figma.com/file/ENhosAbPoEsFw2G2oB16WP/Custom-lock-screen?type=design&node-id=1-3&mode=design&t=NwLKz0JD2wGYyrAY-0
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-8594` 
https://github.com/LedgerHQ/ledger-live/assets/31533861/6d664f5d-681c-43a1-83b3-d3c07fe1578b
> [LIVE-8594] Update customize lock screen Stax wording

- .changeset/smooth-shrimps-remember.md
- apps/ledger-live-mobile/src/families/evm/EvmCustomFees/index.tsx
- apps/ledger-live-mobile/src/families/evm/EvmFeesStrategy.tsx
Use account instead of main account for navigation
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-9509
> [BUGFIX][LLM] app crash when selecting custom / advanced fees on evm token send flow

- .changeset/red-lamps-switch.md
- apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx
- apps/ledger-live-desktop/src/renderer/reducers/devices.ts
The typing of `currentDevice` in the store has been changed from `Device | null | undefined` to `Device | undefined` in this PR #3926. After asking @Justkant who worked on that PR it was made to simplify the typing.
`device: undefined` isn't properly handled by device actions (it results in an infinite loading instead of showing "connect and unlock your device") so **it broke some device actions** (for instance when you open the manager page and no device is connected it just shows a loading indicator instead of showing actual instructions about plugging in and unlocking a device).
In order to fix that, the `currentDevice` should either be defined or null. This keeps the typing simple and fixes the issue.
Ideally we'd do a full cleanup on the device actions in order to have only 2 …
> fix(lld/reducers/devices): fix infinite loading in DeviceAction

- pnpm-lock.yaml
- tools/actions/upload-images/build/main.js
- tools/actions/upload-images/main.ts
- tools/actions/upload-images/package.json
Today we have 400 Error when we upload a file to imgur and it blocks the CI when it fails.
This PR fix how we upload images on imgur + prevent the CI to be blocked when it fails by resolving the promise.
==> https://github.com/LedgerHQ/ledger-live/actions/runs/6275020753/job/17041627925
> Fix imgur in CI

- .changeset/nice-cobras-obey.md
- apps/ledger-live-desktop/src/renderer/screens/exchange/index.tsx
- apps/ledger-live-mobile/src/screens/PTX/BuyAndSell/index.tsx
Add account wallet id conversion for buy deeplinks
- **Impacted projects**: LLM LLD
- **Linked resource(s)**:https://ledgerhq.atlassian.net/browse/LIVE-9482
> fix: add account wallet id conversion for buy deeplinks

- .changeset/smooth-shoes-wait.md
- apps/ledger-live-mobile/src/components/TabBar/Transfer.tsx
- apps/ledger-live-mobile/src/components/TabBar/TransferDrawer.tsx
- apps/ledger-live-mobile/src/hooks/useQuickActions.ts
- apps/ledger-live-mobile/src/locales/en/common.json
Add New Entry in TransferDrawer for Recover
- **Linked resource(s)**: [LIVE-9394] 
https://github.com/LedgerHQ/ledger-live/assets/112866305/a9afaf8d-d3f4-4fc5-8ba9-0739498ee964
[LIVE-9394]: https://ledgerhq.atlassian.net/browse/LIVE-9394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FEAT] : LLM - My wallet access button to Recover ✨

- .changeset/angry-apples-study.md
- .changeset/sixty-cooks-run.md
- apps/ledger-live-desktop/src/renderer/families/cardano/DelegationFlowModal/fields/ValidatorField.tsx
- apps/ledger-live-desktop/src/renderer/families/cardano/DelegationFlowModal/fields/ValidatorRow.tsx
- apps/ledger-live-desktop/src/renderer/families/cardano/DelegationFlowModal/steps/StepDelegation.tsx
- apps/ledger-live-mobile/src/families/cardano/DelegationFlow/SelectPool.tsx
- apps/ledger-live-mobile/src/families/cardano/shared/PoolRow.tsx
Remove Cardano poolCost
- **Impacted projects**: `LLM` `LLD`
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-9030`
> feat(blockchain-support) remove cardano poolCost

- apps/ledger-live-desktop/tests/specs/services/cosmosStaking.spec.ts
due to e2e flawkyness happening for a week now, a quick solution is to disable this test until it gets fixed by [insert ticket number].
- **Impacted projects**: `tests of lld` 
- **Linked resource(s)**: `na` 
> Disable cosmosStaking.spec.ts

- .github/workflows/test-desktop.yml
- .github/workflows/test.yml
- tools/github-bot/src/commands/full-suite.ts
Resume full e2e testing on LLD now that the full time is less than 20mnB
- **Impacted projects**: `lld`, `ci` 
> chore: resume full e2e tests for desktop on each PR

- .github/workflows/test-mobile-e2e.yml
- tools/github-bot/src/features/orchestrator/const.ts
- tools/github-bot/src/features/orchestrator/index.ts
Make sure the Mobile e2e tests are required on PRs
Adds a slack message on failure on `develop`, same as desktop e2e tests
- **Impacted projects**: `CI`, `llm` 
- **Linked resource(s)**: LIVE-9391 
> chore: make mobile e2e tests required

- apps/ledger-live-mobile/src/components/CustomImage/InjectedCodeDebugger.tsx
Improve the error message displayed to developers when this issue occurs in the Stax custom lock screen flow: https://github.com/facebook/hermes/issues/612
**before (left)**: people pinging me on Slack about this scary screen
**after (right)**: warning level + TL;DR about what to do (not panic) + more info in the message
- **Linked resource(s)**: no jira ticket 
> fix(llm/Stax/InjectedCodeDebugger): improve message for dev error

- .changeset/friendly-cycles-watch.md
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.tsx
- libs/ledger-live-common/src/exchange/swap/hooks/index.ts
- libs/ledger-live-common/src/exchange/swap/hooks/useIsSwapLiveApp.test.ts
- libs/ledger-live-common/src/exchange/swap/hooks/useIsSwapLiveApp.ts
- libs/ledger-live-common/src/featureFlags/defaultFeatures.ts
- libs/ledgerjs/packages/types-live/src/feature.ts
The objective of this FF will be to enable and disable the execution of swaps through the swap web app in LLD.
To mitigate risk, there will be the ability to filter the currencies/tokens that can be used for the swap (FROM currency/token).
- **Impacted projects**: `LLD, LLC` 
- **Linked resource(s)**: [LIVE-9344](https://ledgerhq.atlassian.net/browse/LIVE-9344) 
[LIVE-9344]: https://ledgerhq.atlassian.net/browse/LIVE-9344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Feat/LIVE-9344]: Integrate feature_ptx_swap feature flag

- .changeset/mean-wasps-allow.md
- apps/ledger-live-desktop/src/renderer/screens/exchange/index.tsx
- apps/ledger-live-mobile/src/screens/PTX/BuyAndSell/index.tsx
refactor ptx adding correct account to query string
> refactor: refactor ptx adding correct account to query string (#4841)

- apps/ledger-live-mobile/src/components/TabBar/TransferDrawer.tsx
LLM : Upsell Recover on TransferDrawer
- **Linked resource(s)**: [LIVE-9394] 
[LIVE-9394]: https://ledgerhq.atlassian.net/browse/LIVE-9394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BUGFIX] : Upsell Recover on TransferDrawer

- .changeset/smooth-shoes-wait.md
- apps/ledger-live-mobile/src/components/TabBar/Transfer.tsx
- apps/ledger-live-mobile/src/components/TabBar/TransferDrawer.tsx
- apps/ledger-live-mobile/src/hooks/useQuickActions.ts
- apps/ledger-live-mobile/src/locales/en/common.json
LLM : Upsell Recover on TransferDrawer
- **Linked resource(s)**: [LIVE-9394] 
[LIVE-9394]: https://ledgerhq.atlassian.net/browse/LIVE-9394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BUGFIX] : Upsell Recover on TransferDrawer 

- .changeset/large-pets-divide.md
- libs/ledger-live-common/src/exchange/swap/initSwap.ts
Include `amountFromInSmallestDenomination` in swap v5 call
> bugfix: include amountFromInSmallestDenomination

- .changeset/shiny-apes-rule.md
- apps/ledger-live-mobile/src/components/TabBar/TransferDrawer.tsx
- libs/ledger-live-common/src/featureFlags/defaultFeatures.ts
- libs/ledger-live-common/src/hooks/recoverFeatureFlag.ts
- libs/ledgerjs/packages/types-live/src/feature.ts
We need to redirect to specific link on featureflag on quick access recover LiveApp
- **Impacted projects**: `live-mobile` `types-live` `live-common` 
- **Linked resource(s)**: [PROTECT-2592](https://ledgerhq.atlassian.net/browse/PROTECT-2592) 
[PROTECT-2592]: https://ledgerhq.atlassian.net/browse/PROTECT-2592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(protect-2592): add other link on firebase for quick access

- .changeset/shy-forks-judge.md
- libs/ledger-live-common/package.json
- libs/ledger-live-common/src/families/cardano/hw-getAddress.ts
- libs/ledger-live-common/src/families/cardano/js-synchronisation.ts
- libs/ledger-live-common/src/families/cardano/logic.ts
- libs/ledger-live-common/src/families/cardano/tx-helpers.ts
- pnpm-lock.yaml
@cardano-foundation/ledgerjs-hw-app-cardano package update to support Cardano App v6.0.1
> cardano ledgerjs package update

- .changeset/happy-melons-taste.md
- apps/ledger-live-mobile/src/locales/en/common.json
LLM final wording: lock screen customization
- **Linked resource(s)**: [LIVE-8589] 
[LIVE-8589]: https://ledgerhq.atlassian.net/browse/LIVE-8589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SUPPORT] : LLM - Change wording on lock screen Stax

- .changeset/smart-candles-lie.md
- apps/ledger-live-mobile/src/components/RootNavigator/types/SendFundsNavigator.ts
- apps/ledger-live-mobile/src/families/evm/EvmCustomFees/index.tsx
- apps/ledger-live-mobile/src/families/evm/EvmFeesStrategy.tsx
- apps/ledger-live-mobile/src/families/evm/SelectFeesStrategy.tsx
- apps/ledger-live-mobile/src/families/evm/types.ts
- libs/coin-evm/src/__tests__/unit/api/gasTracker/ledger.unit.test.ts
- libs/coin-evm/src/prepareTransaction.ts
- libs/coin-evm/src/transaction.ts
Update custom strategy saving logic for evm on LLM to display the correct fee value to the user when he selects the saved custom strategy.
```
* When the user edits the custom fees, we save the related transaction patch
* in order to reapply it the next time the user selects the saved custom
* strategy entry in the strategy list.
* This is done in order to display the correct fees value for the saved custom
* entry in the fees strategy list.
* We don't need to save the transaction patch for other fees strategies since
* the transaction is already updated with the correct fee data retrieved from
* the gasTracker in `prepareTransaction`.
* cf. (as of 21-09-2023) https://github.com/LedgerHQ/ledger-live/blob/e87c4c2d879fb9322cd2849f2d34c3be9e500a1e/libs/coin-evm/src/prepareTransaction.ts#L190- …
```
> [BUGFIX][LLM] wrong fee value for evm custom fee

- .changeset/giant-guests-refuse.md
- libs/coin-evm/src/__tests__/unit/getTransactionStatus.unit.test.ts
- libs/coin-evm/src/getTransactionStatus.ts
Trying to send a token transaction (i.e: a transaction from a `TokenAccount`) without an amount on evm should raise an error in `getTransactionStatus`.
- update `validateAmount` to return an `AmountRequired` error if a token transaction does not have an amount provided
- update related test  
---
🧪  Flows tested:
- send ERC20 :white_check_mark:
- send ERC721 :white_check_mark:
- send ERC1155 :white_check_mark:
- interaction with live-app discover (1 inch)
- approve token (i.e: sign a tx with data but 0 amount) :white_check_mark:
- swap ETH -> USDT :white_check_mark:
- native swap
- could not tests since minimum amount required to swap from with Changelly is 96 USDT  ❓ 
---
- **Impacted projects**: `coin-evm` `LLD` `LLM`  …
> [BUGFIX] return error when tx from tokenAccount has no amount

- libs/ledger-live-common/src/families/cardano/speculos-deviceActions.ts
Update the speculos screens for Cardano App v6.0.1
> speculos screen updates

- tools/actions/change-product-name/action.yml
- tools/actions/generate-bot-super-report/action.yml
- tools/actions/generate-release-message/action.yml
- tools/actions/get-package-infos/action.yml
- tools/actions/get-workflow-artifacts-id/action.yml
- tools/actions/live-common-affected/action.yml
- tools/actions/prepare-comment-screenshots/action.yml
- tools/actions/submit-bot-report/action.yml
- tools/actions/turbo-affected/action.yml
- tools/actions/turborepo-gh-cache/action.yml
- tools/actions/turborepo-s3-cache/action.yml
- tools/actions/upload-images/action.yml
Downgrade our custom github actions to node16 while we upgrade our gha runners 
versions
- **Impacted projects**: `ci`, `macos` 
> chore: downgrade to node16 in custom actions

- libs/ledger-live-common/src/families/cardano/speculos-deviceActions.ts
> delegation screen fix

- .changeset/sixty-horses-joke.md
- apps/ledger-live-desktop/src/renderer/screens/platform/v2/Catalog/Card/Full.tsx
fix: apps description changed to shortDescription inside discover
- **Linked resource(s)**: `[JIRA](https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/623?selectedIssue=LIVE-9134)` 
> fix: apps description changed to shortDescription inside discover 

- .changeset/light-ants-hang.md
- apps/ledger-live-mobile/src/components/DeviceAction/common.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/FirmwareUpdate/index.tsx
LLM stax os update 
- **Linked resource(s)**: [LIVE-8588] 
[LIVE-8588]: https://ledgerhq.atlassian.net/browse/LIVE-8588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SUPPORT] : LLM stax os update 

- libs/ledger-live-common/src/families/cardano/speculos-deviceActions.ts
> retry delegate screen fix

- apps/ledger-live-mobile/src/components/ServicesWidget/Protect/useProtect.ts
- apps/ledger-live-mobile/src/screens/Portfolio/index.tsx
- libs/ledger-live-common/src/featureFlags/defaultFeatures.ts
- libs/ledger-live-common/src/hooks/recoverFeatureFlag.ts
- libs/ledgerjs/packages/types-live/src/feature.ts
Modifs in recover links
- **Linked resource(s)**: [LIVE-9485] 
[LIVE-9485]: https://ledgerhq.atlassian.net/browse/LIVE-9485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LLM - modifs in recover links

- .changeset/mighty-birds-mate.md
- apps/ledger-live-mobile/src/screens/SendFunds/02-SelectRecipient.tsx
QR Code scan during Send broken
- **Linked resource(s)**: [LIVE-9664] 
https://github.com/LedgerHQ/ledger-live/assets/112866305/62ebb6ca-a283-433c-aef7-06e126017c93
[LIVE-9664]: https://ledgerhq.atlassian.net/browse/LIVE-9664?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BUGFIX]: QR Code scan during Send broken

- libs/ledger-live-common/src/hooks/recoverFeatureFlag.ts
fix(llm): modifs in recover links
- **Linked resource(s)**: [LIVE-9485] 
[LIVE-9485]: https://ledgerhq.atlassian.net/browse/LIVE-9485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(llm): modifs in recover links

- apps/ledger-live-mobile/src/components/ServicesWidget/Protect/useProtect.ts
Remove source param on deeplinks recover
> fix(recover): source on useProtect

- tools/actions/composites/setup-toolchain/action.yml
Update setup-dotnet action
- **Linked resource(s)**: broken nighlty builds 
> chore: bump setup-dotnet action

- apps/ledger-live-mobile/src/components/TabBar/Transfer.tsx
> [BUGFIX] Height transfer drawer

- .changeset/small-singers-melt.md
- apps/ledger-live-desktop/src/renderer/families/cardano/Delegation/index.tsx
- apps/ledger-live-desktop/src/renderer/families/tezos/Delegation/index.tsx
Remove the {{ name }} in staking translation
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-9447 
> fix translation text delegation

- .changeset/gold-hats-relax.md
- apps/cli/src/commands/bot.ts
- apps/cli/src/commands/getAddress.ts
- Fix `getAddress` command: remove a useless line causing `--derivationMode` param to be broken
- Fix `bot` command: adapt to recent changes in https://github.com/LedgerHQ/ledger-live/pull/4207 that broke the `--currency` param
- **Impacted projects**: `CLI` 
> [support] Fixes for CLI commands `getAddress` and `bot`

- apps/ledger-live-mobile/src/locales/en/common.json
> [LLM] - [] - Fix Stax wording

- .changeset/plenty-hairs-hear.md
- .changeset/smart-elephants-exercise.md
- libs/coin-evm/src/__tests__/fixtures/synchronization.fixtures.ts
- libs/coin-evm/src/__tests__/unit/adapters/etherscan.unit.test.ts
- libs/coin-evm/src/__tests__/unit/adapters/ledger.unit.test.ts
- libs/coin-evm/src/__tests__/unit/api/explorer/ledger.unit.test.ts
- libs/coin-evm/src/__tests__/unit/logic.unit.test.ts
- libs/coin-evm/src/__tests__/unit/preload.unit.test.ts
- libs/coin-evm/src/logic.ts
- libs/coin-evm/src/preload.ts
- libs/coin-evm/src/synchronization.ts
- libs/coin-framework/src/account/accountId.ts
- libs/coin-framework/src/account/accountId.unit.test.ts
- libs/ledgerjs/packages/cryptoassets/src/tokens.ts
This PR is fixing 2 problems:
-  the token ids encoding in `TokenAccounts` ids could contain characters not handled by the `
encodeURIComponent` (like `_` `-` or `+`), which would then break its "deserialization". 
- https://github.com/LedgerHQ/ledger-live/blob/develop/libs/coin-framework/src/account/accountId.ts#L36 
- https://github.com/LedgerHQ/ledger-live/blob/develop/libs/coin-framework/src/operation.ts#L70
-  https://github.com/LedgerHQ/ledger-live/blob/develop/libs/coin-framework/src/operation.ts#L93
- the BSC tokens were added to the CAL using the `convertERC20` method instead of the `convertBEP20` method, changing the ids from `bsc/bep20/XYZ` to `bsc/erc20/XYZ` which was breaking the mappings we have in some Ledger backends. ⚠️ Having 2 disctinct types for `erc20` and `bep20` is …
> [LIVE-9653][LIVE-9691] Bugfix - Fix incorrect token id encoding in account ids & incorrect BSC tokens type

- .changeset/perfect-kiwis-tickle.md
- apps/ledger-live-desktop/static/i18n/en/app.json
- libs/ledgerjs/packages/hw-transport/src/Transport.ts
remove  TransportRaceCondition litera
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-9767
> fix: fix TransportRaceCondition literal

- .changeset/giant-wasps-exist.md
- apps/ledger-live-desktop/src/renderer/components/DeviceAction/index.tsx
- apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/CompleteExchange/Body.tsx
- libs/ledger-live-common/src/exchange/platform/transfer/completeExchange.ts
- libs/ledger-live-common/src/exchange/platform/types.ts
- libs/ledger-live-common/src/exchange/swap/completeExchange.ts
- libs/ledger-live-common/src/exchange/swap/webApp/utils.ts
- libs/ledger-live-common/src/hw/actions/completeExchange.ts
Fix confirmation message in swap web app (using platform)
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-9361
> fix: fix confirmation message swap web app

- .changeset/witty-pigs-beam.md
- apps/ledger-live-desktop/src/config/urls.ts
- apps/ledger-live-desktop/src/renderer/components/BuyButton.tsx
- apps/ledger-live-mobile/src/config/urls.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/SendFunds/04-Summary.tsx
To make it more visible
- fix buy CTA button style on LLD to make it more visible
- add related support link for NotEnoughGas error on LLM and LLD to display an "learn more" CTA redirecting to [related CS article](https://support.ledger.com/hc/en-us/articles/9096370252573?support=true)
- fix buy button when NotEnoughGas on LLM
- The logic to display the button was related to the currency being sent and not the main account currency (if I don't have enough fund to pay for the gas when I want to send USDT on ethereum, I need to buy some ETH and not some USDT) 
- The related text was wrongly hardcoded only for ethereum currency when a user might be using another evm network and thus needing to buy a different currency than ethereum (i.e: the currency of the actual EVM network he is using)
- …
> [BUGFIX] fix NotEnoughGas related UI on LLM and LLD

- apps/ledger-live-desktop/tests/fixtures/common.ts
- apps/ledger-live-desktop/tests/specs/general/passwordlock.spec.ts
**JavaScript Node.js rule of thumb: try to never use a `*Sync` API 🙏**
fixing these could slightly help playwright performance impact.
> chore(playwright): use fs/promises when possible

- apps/ledger-live-desktop/src/renderer/index.ts
- apps/ledger-live-desktop/src/renderer/init.tsx
- apps/ledger-live-desktop/src/renderer/pre.ts
- apps/ledger-live-desktop/tests/fixtures/common.ts
if the app never manages to load, instead of having an never loading app (showing the Ledger icon forever) this PR will make the app show the actual error like this:
having this would appear on playwright and it would have helped us identifying issues quickly. it can also be handy when an user is stuck with such problem to more quickly understand the situation.
- **Linked resource(s)**: na 
> chore: detect critical crash at boot of LLD and show them to user

- .changeset/healthy-dots-give.md
- apps/ledger-live-desktop/src/renderer/screens/recover/Player.tsx
- apps/ledger-live-mobile/src/screens/Protect/Player.tsx
Add query param `currency` on Recover redirection on LLM-LLD
- **Impacted projects**: `ledger-live-mobile`, `ledger-live-desktop`  
- **Linked resource(s)**: [PROTECT-2694](https://ledgerhq.atlassian.net/browse/PROTECT-2694)
[PROTECT-2694]: https://ledgerhq.atlassian.net/browse/PROTECT-2694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bugfix(protect-2694): pass currency query param to recover

- .changeset/tall-penguins-deliver.md
- apps/ledger-live-mobile/src/locales/en/common.json
- libs/coin-evm/src/getTransactionStatus.ts
Align `NotEnoughGas` error in LLM and LLD
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-7369
> Align NotEnoughGas error message in LLD and LLM

- .changeset/metal-bottles-add.md
- libs/ledger-live-common/src/families/hedera/tests/js-estimateMaxSpendable.integration.test.ts
- libs/ledger-live-common/src/families/hedera/tests/utils.integration.test.ts
- libs/ledger-live-common/src/families/hedera/utils.ts
Fix estimated fee so that max spendable works as intended
> fix: correct estimated fees so that max spendable works as intended

- apps/ledger-live-desktop/static/i18n/ar/app.json
- apps/ledger-live-desktop/static/i18n/de/app.json
- apps/ledger-live-desktop/static/i18n/es/app.json
- apps/ledger-live-desktop/static/i18n/fr/app.json
- apps/ledger-live-desktop/static/i18n/ja/app.json
- apps/ledger-live-desktop/static/i18n/ko/app.json
- apps/ledger-live-desktop/static/i18n/pt-BR/app.json
- apps/ledger-live-desktop/static/i18n/ru/app.json
- apps/ledger-live-desktop/static/i18n/tr/app.json
- apps/ledger-live-desktop/static/i18n/zh/app.json
- apps/ledger-live-mobile/src/locales/ar/common.json
- apps/ledger-live-mobile/src/locales/de/common.json
- apps/ledger-live-mobile/src/locales/es/common.json
- apps/ledger-live-mobile/src/locales/fr/common.json
- apps/ledger-live-mobile/src/locales/ja/common.json
- apps/ledger-live-mobile/src/locales/ko/common.json
- apps/ledger-live-mobile/src/locales/pt-BR/common.json
- apps/ledger-live-mobile/src/locales/ru/common.json
- apps/ledger-live-mobile/src/locales/tr/common.json
- apps/ledger-live-mobile/src/locales/zh/common.json
Please review this manually triggered translation push from the configuration set 'ledger-live - json - Pull Request' in your Smartling project https://dashboard.smartling.com/app/projects/be90da906/github-connector/configurationSets
> Smartling on-demand translation delivery from hotfix

- .changeset/metal-bottles-add.md
- libs/ledger-live-common/src/families/hedera/tests/js-estimateMaxSpendable.integration.test.ts
- libs/ledger-live-common/src/families/hedera/tests/utils.integration.test.ts
- libs/ledger-live-common/src/families/hedera/utils.ts
Fix estimated fee so that max spendable works as intended
(backport of external PR https://github.com/LedgerHQ/ledger-live/pull/4823, to help with the CI)
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-7182
> [bugfix] Hedera: correct estimated fees so that max spendable works as intended

- libs/ledger-live-common/src/families/casper/speculos-deviceActions.ts
Fix speculous actions for bot testing 
> fix speculous actions on casper integration

- libs/ledger-live-common/src/wallet-api/logic.test.ts
Port completeExchangeLogic tests from platform to wallet-api
- **Linked resource(s)**: [LIVE-9427] 
[LIVE-9427]: https://ledgerhq.atlassian.net/browse/LIVE-9427?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test: port completeExchangeLogic tests from platform to wallet-api [LIVE-9427]

- apps/ledger-live-desktop/package.json
- pnpm-lock.yaml
Updates vite to v4.5.0
`pnpm dev:lld` seems a bit faster (46s to 28s with no cache) and `pnpm build:lld` went from 2m6s to 1m59s with no cache so not a lot of changes (only tested once)
https://github.com/LedgerHQ/ledger-live/assets/3009753/60ef0409-916a-4ad6-974f-8b8a21f64360
https://github.com/LedgerHQ/ledger-live/assets/3009753/db848154-9808-4e6d-b2f6-ff2b26b7454e
https://github.com/LedgerHQ/ledger-live/assets/3009753/9d5c48e0-2a6e-4c70-9f13-8ad65ff23766
https://github.com/LedgerHQ/ledger-live/assets/3009753/9f2ed2a1-d2a1-41a1-9f9d-45cc7095776b
_Pull Requests must pass the CI and be …
> chore(deps): update vite to v4.5.0

- .changeset/poor-knives-tickle.md
- apps/ledger-live-mobile/src/screens/ReceiveFunds/ReceiveSecurityModal/index.tsx
Success event was not triggered on some cases (Deposit)
- **Linked resource(s)**: [LIVE-9799] 
[LIVE-9799]: https://ledgerhq.atlassian.net/browse/LIVE-9799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BUGFIX]: triggerSuccessEvent in Deposit flow

- .changeset/popular-drinks-repeat.md
- apps/ledger-live-desktop/src/renderer/components/CustomImage/NFTGallerySelector.tsx
- apps/ledger-live-desktop/src/renderer/screens/nft/Gallery/Collection.tsx
- apps/ledger-live-desktop/src/renderer/screens/nft/Gallery/Gallery.tsx
- apps/ledger-live-desktop/src/renderer/screens/nft/useOnScreen.ts
NFTs do not load in the gallery when displayed in list view
- **Linked resource(s)**: [LIVE-8374] 
https://github.com/LedgerHQ/ledger-live/assets/112866305/82ca6446-53c6-42ac-8a08-83dc0b85813a
[LIVE-8374]: https://ledgerhq.atlassian.net/browse/LIVE-8374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BUGFIX] : NFTs do not load in the gallery when displayed in list view

- apps/ledger-live-desktop/tests/specs/services/liveapp-sdk.spec.ts
Disabling a flaky test in the liveapp-sdk test suite until we can fix it
Sometimes the amount in the transaction shown in LLD is 0 same for the fees
- **Linked resource(s)**: [LIVE-9616] 
[LIVE-9616]: https://ledgerhq.atlassian.net/browse/LIVE-9616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test: disable flaky test [LIVE-9616]

- .changeset/thin-bats-drive.md
- apps/ledger-live-mobile/src/locales/en/common.json
Rename Entry points Deposit to Receive
- **Linked resource(s)**: [LIVE-9443] 
[LIVE-9443]: https://ledgerhq.atlassian.net/browse/LIVE-9443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SUPPORT] :  📝 Rename Entry points Deposit to Receive

- renovate.json
to avoid having a "big bang" at creating 10 concurrent PR in once and load our CI at same time.
> Reduce number of renovate PRs to 5

- .changeset/rare-ties-allow.md
- apps/ledger-live-desktop/src/renderer/screens/market/MarketCoinScreen/MarketInfo.tsx
LLD high-low inversion in market stats of asset
- **Linked resource(s)**: [LIVE-8059] 
[LIVE-8059]: https://ledgerhq.atlassian.net/browse/LIVE-8059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BUGFIX] : high-low inversion in market stats

- .changeset/cold-spoons-mix.md
- apps/ledger-live-mobile/src/experimental.ts
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Settings/Experimental/FeatureRow.tsx
- apps/ledger-live-mobile/src/screens/Settings/index.tsx
LM Experimental features section translation
- **Linked resource(s)**: [LIVE-7993] [LIVE-7995]
[LIVE-7993]: https://ledgerhq.atlassian.net/browse/LIVE-7993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-7995]: https://ledgerhq.atlassian.net/browse/LIVE-7995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BUGFIX] LLM Experimental features  & Developers section translation 📝

- apps/ledger-live-mobile/scripts/post.mjs
It was noted by @JustKant that some native modules come from node_modules and thus we've added the package.json hash as another check to rerun pod install or not
- **Impacted projects**: `dx` 
> chore: add json file as dependency for postinstall skip

- .changeset/wet-phones-wash.md
- apps/ledger-live-desktop/src/renderer/modals/LottieDebugger/index.tsx
- apps/ledger-live-desktop/src/renderer/modals/StorylyDebugger/index.tsx
- apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/FeatureFlagsSettings/FeatureFlagDetails.tsx
- apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/FeatureFlagsSettings/GroupedFeatures.tsx
- apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/FeatureFlagsSettings/index.tsx
- apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/OnboardingAppInstallDebug.tsx
- apps/ledger-live-desktop/static/i18n/en/app.json
Fix issues with translations
- **Linked resource(s)**: [LIVE-8004] [LIVE-9917]
[LIVE-8004]: https://ledgerhq.atlassian.net/browse/LIVE-8004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-9917]: https://ledgerhq.atlassian.net/browse/LIVE-9917?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SUPPORT]: Add more localisations text in Developers tabs

- .changeset/poor-trainers-share.md
- libs/ledgerjs/script/crypto-assets-importer/index.ts
`importers/internet_computer` file was removed in https://github.com/LedgerHQ/ledger-live/pull/5113
> [BUGFIX] remove reference to deleted file

- apps/ledger-live-desktop/tools/config/renderer.esbuild.js
> fix: revert extract json

- .changeset/fifty-masks-flash.md
- apps/ledger-live-mobile/src/screens/ReceiveFunds/03a-ConnectDevice.tsx
Closing the verify address page now redirect to previous page (QR code).
- **Linked resource(s)**: [LIVE-9798] 
https://github.com/LedgerHQ/ledger-live/assets/146743014/59e53158-37f5-4c2e-be88-4991e1836609
[LIVE-9798]: https://ledgerhq.atlassian.net/browse/LIVE-9798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(navigation): deposit flow, closing verify address correctly redirect to previous page

- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Settings/General/AuthSecurityToggle.tsx
Change password and biometrics descriptions trad.
- **Linked resource(s)**: [LIVE-2398] 
[LIVE-2398]: https://ledgerhq.atlassian.net/browse/LIVE-2398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(trads): change passwords options trad

- apps/ledger-live-desktop/tools/config/renderer.esbuild.js
> Fix json extract

- apps/ledger-live-mobile/src/components/NavBarColorHandler.android.ts
Catch errors from react-native-navigation-bar-color changeNavigationBarColor, as it's not critical and was throwing and crashing users ( https://ledger.sentry.io/issues/4382736390/?query=is%3Aunresolved+navigation+bar&referrer=issue-stream&statsPeriod=14d&stream_index=0 )
- **Linked resource(s)**: [LIVE-2140] 
[LIVE-2140]: https://ledgerhq.atlassian.net/browse/LIVE-2140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bugfix/LIVE-2140 - LLM - Catch errors from react-native-navigation-bar-color

- .changeset/stale-hairs-double.md
- apps/ledger-live-desktop/.unimportedrc.json
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/WebviewErrorDrawer/index.tsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.tsx
- apps/ledger-live-desktop/static/i18n/en/app.json
New generic error drawer for swap webview
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-9955
> feat: add swap webview generic error drawer

- .changeset/weak-swans-jog.md
- apps/ledger-live-desktop/src/renderer/analytics/segment.ts
- apps/ledger-live-desktop/src/renderer/components/FirebaseFeatureFlags.tsx
- apps/ledger-live-mobile/src/analytics/segment.ts
- apps/ledger-live-mobile/src/components/FirebaseFeatureFlags.tsx
- libs/ledgerjs/packages/hw-app-exchange/src/Exchange.integ.test.ts
- libs/ledgerjs/packages/types-live/src/feature.ts
- Add is batch analytic properties to segment identity.
- Update typings for the `feat_fetch_additional_coins` flag.
- **Impacted projects**: `[LLD, LLM, LJS]` 
- **Linked resource(s)**: [LIVE-9525](https://ledgerhq.atlassian.net/browse/LIVE-9525) 
[LIVE-9525]: https://ledgerhq.atlassian.net/browse/LIVE-9525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [feat/LIVE-9525]: add is batch analytics to segment identity, update ff types

- .github/workflows/test-mobile-e2e.yml
_On Mobile E2E action, we only rebundle JS part if build is already cached. But we missed replacing it in the app package, resulting in incorrect build._
--dev : If false, warnings are disabled and the bundle is minified (default: true)
--minify : Allows overriding whether bundle is minified. This defaults to false if dev is true, and true if dev is false. Disabling minification can be useful for speeding up production builds for testing purposes
- **Impacted projects**: `Detox LLM` 
- **Linked resource(s)**: Mobile E2E action run [1](https://github.com/LedgerHQ/ledger-live/actions/runs/6656028382/attempts/1) and [2](https://github.com/LedgerHQ/ledger-live/actions/runs/6665279672) 
_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop …
> Mobile E2E: fix detox JS bundling

- .changeset/shaggy-flowers-doubt.md
- apps/ledger-live-desktop/package.json
- apps/ledger-live-mobile/package.json
Make it easier to run `typecheck` and `lint`. Just call `pnpm mobile check` or `pnpm desktop check`
- **Impacted projects**: `LL` 
> [LL] - [] - Add check script

- .changeset/nervous-tables-pull.md
- libs/ledger-live-common/src/exchange/swap/api/v5/fetchRates.test.ts
- libs/ledger-live-common/src/exchange/swap/api/v5/fetchRates.ts
- libs/ledger-live-common/src/exchange/swap/types.ts
Wrong min | max amount swap
- **Impacted projects**:  LLC
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-9947
> fix: fix min|max limit swap

- apps/ledger-live-desktop/tests/specs/analytics/segment.spec.ts
fix analytics/segment test to not rely on timeouts
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-9791 
> test: analytics/segment test to not rely on timeouts

- renovate.json
give a try to this settings.
- **Impacted projects**: `renovate` 
- **Linked resource(s)**: [na] 
> chore: prioritize renovate for security deps

- apps/ledger-live-mobile/src/components/TabBar/TransferDrawer.tsx
Dedup Recover in TransferDrawer
> fix: dedup recover from transfer drawer

- .changeset/ninety-bottles-occur.md
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.tsx
- apps/ledger-live-mobile/ios/ledgerlivemobile.xcodeproj/project.pbxproj
- re introduce top bar for the swap live app
- **Linked resource(s)**: [LLD] 
> fix: reintroduce top bar

- libs/ledger-live-common/src/families/casper/bridge/account.ts
- libs/ledger-live-common/src/families/casper/bridge/bridgeHelpers/transferId.ts
- libs/ledger-live-common/src/families/casper/consts.ts
- libs/ledger-live-common/src/families/casper/specs.ts
Apply some small changes on tests and validations
> Apply some small changes on tests and validations

- renovate.json
Group linked metro update in renovate config to have only one PR
Currently:
- https://github.com/LedgerHQ/ledger-live/pull/5253
- https://github.com/LedgerHQ/ledger-live/pull/5255
- https://github.com/LedgerHQ/ledger-live/pull/5256
Those updates should come as one as they are released together
- **Impacted projects**: `renovate` 
> chore: bundle metro update renovate config

- .changeset/tiny-eyes-battle.md
- libs/ledger-live-common/src/socket/__snapshots__/socket.test.ts.snap
- libs/ledger-live-common/src/socket/index.ts
- libs/ledger-live-common/src/socket/scenarios.mock.ts
- libs/ledger-live-common/src/socket/socket.test.ts
- libs/ledgerjs/packages/hw-transport-mocker/package.json
- libs/ledgerjs/packages/hw-transport-mocker/src/openTransportReplayer.ts
- pnpm-lock.yaml
According to the React Native [v0.72.0 changelogs](https://github.com/facebook/react-native/blob/main/CHANGELOG.md#changed-5): on iOS a new library is used to handle web socket
> Use SocketRocket for web socket library (9ee0e1c78e)
It seems that it's changing a little bit the behavior of how fast the web socket is closed.
Because of this, and a wrong logic in our code, we were still receiving a last (`success`) message from the HSM just after handling a `bulk` message.
Normally just after receiving a `bulk` message, the web socket with the HSM is closed as nothing more is expected. Because the web socket `close` function is none-blocking, a last `sucess` message was still handled (reproduced it more after updating to a React Native version >= `0.72.0` on iOS), which would complete the …
> Fix: failing apps installation and uninstallation on iOS

- .changeset/forty-cycles-protect.md
- apps/ledger-live-mobile/src/locales/en/common.json
Onboarding partners mention
- **Linked resource(s)**: [LIVE-8041] 
[LIVE-8041]: https://ledgerhq.atlassian.net/browse/LIVE-8041?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BUGFIX]: Issue in Onboarding partners mention

- .github/workflows/release-create.yml
Remove failing step (import crypto asset) in release job
- **Impacted projects**: `github jobs` 
- **Linked resource(s)**: []
> remove import cryptoassets in release job

- apps/ledger-live-desktop/tests/fixtures/common.ts
- apps/ledger-live-desktop/tests/models/AccountPage.ts
- apps/ledger-live-desktop/tests/models/LiveAppWebview.ts
- apps/ledger-live-desktop/tests/models/PortfolioPage.ts
- apps/ledger-live-desktop/tests/models/SettingsPage.ts
- apps/ledger-live-desktop/tests/utils/waitFor.ts
commit in the validated work from testing branch https://github.com/LedgerHQ/ledger-live/pull/4918
- chore: adjust some timeout in e2e tests to fix rare issues
- test: tweak waitFor and textIsPresent
- chore: add PLAYWRIGHT_CPU_THROTTLING_RATE
- **Impacted projects**: `LLD tests` 
- **Linked resource(s)**: [live-9607] 
> playwright e2e fixes: incremental commits
