LedgerHQ/ledger-live

.changeset/seven-clouds-visit.md, libs/ledger-live-common/.unimportedrc.json, libs/ledger-live-common/src/currencies/mock.ts, libs/ledger-live-common/src/currencies/sortByMarketcap.test.ts, libs/ledger-live-common/src/currencies/sortByMarketcap.ts
Today we have some performance issues when we open the Swap page, because sortByMarkCap can be slow.
This PR improves the performance of the function.
- **Impacted projects**: `llm`, `lld` 
- https://ledgerhq.atlassian.net/browse/LIVE-9663
- https://ledgerhq.atlassian.net/browse/LIVE-9997
Before
After
=> fix: improve perf for sortByMarketCap

.changeset/thirty-zebras-punch.md, apps/ledger-live-mobile/android/build.gradle, apps/ledger-live-mobile/ios/Podfile.lock, apps/ledger-live-mobile/package.json, pnpm-lock.yaml
Update Android SDK to 34 (Android 14). Today it's slow to start the app on Android 14.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-10021
=> chore: update Android SDK to 34

.changeset/little-ways-share.md, apps/ledger-live-mobile/src/components/WalletTab/WalletTabNavigatorTabBar.tsx
Market Tab click event triggering Crypto Tab event wasn't the good one !
- **Linked resource(s)**: [LIVE-9999] 
[LIVE-9999]: https://ledgerhq.atlassian.net/browse/LIVE-9999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUGFIX] : Bad name of analytics was triggered on Market Tab in Header on LLM

.changeset/strange-snails-invent.md, apps/ledger-live-mobile/src/families/casper/operationDetails.tsx
Bugfix for crashing llm on viewing any operation.
=> Bugfix/casper: viewing operation on llm causing app crash

.changeset/tidy-items-explode.md, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/locales/en/common.json
The "My Ledger" screen was formerly called "Manager" / "the manager", so this PR corrects all the wording on this matter.
This PR does not include changes regarding the "Allow manager" wording that appears on the device, this will be treated subsequently ([LLM](https://ledgerhq.atlassian.net/browse/LIVE-5919), [LLD](https://ledgerhq.atlassian.net/browse/LIVE-5920)) as it also needs new animation assets which don't exist today. (Today there is a misalignment as we say "Allow Manager on your device" and show a lottie where the "Allow Manager" is written while on the device it says "Allow secure connection with Ledger".
- **Linked resource(s)**: [LIVE-4344] [LIVE-8051]  …
=> fix(llm/wording): replace "manager" by "My Ledger"

.changeset/tender-pandas-beam.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/WebviewErrorDrawer/index.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.tsx
- Add custom handlers to manage state and errors between ledger live desktop and swap live app.
=> [feat/LIVE-9363]: add custom handler to swap live app

apps/ledger-live-desktop/tests/specs/services/wallet-api.spec.ts
fixes LIVE-9996 flaky case. confirmed to work by https://github.com/LedgerHQ/ledger-live/pull/4918
- **Linked resource(s)**: [LIVE-9996] 
[LIVE-9996]: https://ledgerhq.atlassian.net/browse/LIVE-9996?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: fix LIVE-9996

apps/ledger-live-desktop/tests/models/Drawer.ts, apps/ledger-live-desktop/tests/models/LiveAppWebview.ts, apps/ledger-live-desktop/tests/specs/services/liveapp-sdk.spec.ts
fixes LIVE-9995 flaky case. confirmed to work by https://github.com/LedgerHQ/ledger-live/pull/4918
- **Linked resource(s)**: [LIVE-9995] 
[LIVE-9995]: https://ledgerhq.atlassian.net/browse/LIVE-9995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: fix LIVE-9995

apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/drawers/BluetoothConnection.tsx
Use correct typo for OS names in LLM.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-8126, https://ledgerhq.atlassian.net/browse/LIVE-8048
=> Capitalize OS when needed

libs/ledger-live-common/package.json, libs/ledger-live-common/src/families/stellar/api/horizon.ts, libs/ledger-live-common/src/families/stellar/js-buildTransaction.ts, libs/ledger-live-common/src/families/stellar/logic.ts, pnpm-lock.yaml
StellarSDK default import is of type `any`. We can use named import to have correct types instead.
```typescript
import StellarSDK from "stellar-sdk"; // StellarSDK is of type any
```
- **Linked resource(s)**: []
=> chore: remove default import stellarsdk

.changeset/swift-cherries-visit.md, apps/ledger-live-mobile/src/components/CancelButton.tsx, apps/ledger-live-mobile/src/components/Circle.tsx, apps/ledger-live-mobile/src/components/Graph/DefGrad.tsx, apps/ledger-live-mobile/src/components/ModalBottomAction.tsx, apps/ledger-live-mobile/src/components/Nft/NftMedia.tsx, apps/ledger-live-mobile/src/components/OperationIcon.tsx, apps/ledger-live-mobile/src/components/SetEnvsFromSettings.ts, apps/ledger-live-mobile/src/components/ShareLink.tsx, apps/ledger-live-mobile/src/components/ValidateOnDeviceDataRow.tsx, apps/ledger-live-mobile/src/context/AuthPass/AuthScreen.tsx, apps/ledger-live-mobile/src/icons/NoLocationImage.tsx, apps/ledger-live-mobile/src/icons/QRcodeZoom.tsx, apps/ledger-live-mobile/src/screens/AccountSettings/AccountAdvancedLogsRow.tsx, apps/ledger-live-mobile/src/screens/AddAccounts/03-Accounts.tsx, apps/ledger-live-mobile/src/screens/ImportAccounts/DisplayResultItem.tsx, apps/ledger-live-mobile/src/screens/OperationDetails/DataList.tsx, apps/ledger-live-mobile/src/screens/PairDevices/PendingContainer.tsx, apps/ledger-live-mobile/src/screens/ReceiveFunds/03a-ConnectDevice.tsx, apps/ledger-live-mobile/src/screens/ReceiveFunds/NotSyncedWarning.tsx, apps/ledger-live-mobile/src/screens/SendFunds/04-Summary.tsx, apps/ledger-live-mobile/src/screens/SendFunds/SummaryAmountSection.tsx, apps/ledger-live-mobile/src/screens/SendFunds/SummaryRow.tsx, apps/ledger-live-mobile/src/screens/SendFunds/SummaryRowCustom.tsx, apps/ledger-live-mobile/src/screens/Settings/Debug/Debugging/Crashes.tsx, apps/ledger-live-mobile/src/screens/Settings/General/PasswordAdd.tsx
This PR subscribe itself in the long term improvement of this repository. It doesn't change anything on the user side but rather improve the developer experience and the codebase step by step.
**Files with high risk changes:**
[SetEnvsFromSettings.ts](https://github.com/LedgerHQ/ledger-live/pull/5224/files#diff-f7d8c87e1340cbb323a14e894efff2cbdff7dc5304971874e1fcd43875d09e55)
- **Linked resource(s)**: [LIVE-10018] 
[LIVE-10018]: https://ledgerhq.atlassian.net/browse/LIVE-10018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …
=> [LLM] - [] - Upgrade legacy components to modern components

.changeset/swift-birds-explain.md, libs/ledger-live-common/src/exchange/platform/transfer/completeExchange.ts, libs/ledger-live-common/src/exchange/swap/completeExchange.ts, libs/ledgerjs/packages/hw-app-exchange/src/Exchange.integ.test.ts
With the new Swap format, SwapNG expect a baseUrl signature and does not need to convert it into a DER. AppExchange is in charge of converting it.
Add a new test case for AppExchange with data coming from third party software.
- **Impacted projects**: `hw-app-exchange`
=> Manage swap signature according to swap type

.changeset/late-spiders-battle.md, apps/ledger-live-desktop/src/renderer/components/QRCodeCameraPickerCanvas.tsx
Previously to this PR, if you were in dark mode, you were not properly seeing the fallback error on the QR Camera picker:
So I fixed it
- I also took opportunity to fix the layout. It seems this mode isn't tested often (and it's not easy to test), also i didn't see a way to automate this (we can simulate a fake camera, but i don't see how to simulate a permission deny case)
- I also ensured that the error eventually appears (20s) in case of some OS that never trigger an error case (in MacOS case, I could see it instantly tho, but there is history of this problem https://stackoverflow.com/questions/42176505/getusermedia-what-if-user-makes-no-choice )
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-10043 
_Please make sure you follow …
=> bugfix(lld): fix dark mode support of QR Code Camera Picker fallback

.changeset/swift-tomatoes-march.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.tsx
* add handler for custom.redirectToProviderApp
=> [feat/LIVE-9350]: add handler for custom.redirectToProviderApp

.changeset/bright-crabs-act.md, libs/coin-evm/package.json, libs/coin-evm/src/__tests__/unit/logic.unit.test.ts, libs/coin-evm/src/__tests__/unit/synchronization.unit.test.ts, libs/coin-evm/src/logic.ts, pnpm-lock.yaml
Changing the hash algorithm used for creating the `syncHash`. We were using a cryptographic algorithm (sha256) provided by the `ethers` library, which is very efficient on a desktop computer, but is very poorly optimised for a React Native environment. 
This function will now use a [MurmurHash](https://en.wikipedia.org/wiki/MurmurHash) algorithm which is a non cryptographic hash resulting in a 32 bits unsigned integer, which clearly has a collision drawback, but this `getSyncHash` method isn't vital for the coin module to work correctly. 
If a collision was to exist after a modification of the CAL, it would only prevent a new full synchronization of the account, making it impossible to display the updated tokens if they were to be owned by the user. A clear cache would then be enough to …
=> [LIVE-9998] Bugfix - Change `getSyncHash` hashing algorithm

.github/pull_request_template.md
some very minor refinement of the PR template
- "link" instead of "issue" to explicit the fact it's better just to have a ticket link
- the comment in the Impact of the changes to be in the title instead of the first tick has been annoying me a bit 😛 
- **JIRA or GitHub issue**: 
- 
---
=> chore: refine pull_request_template.md

.changeset/tough-plants-call.md, apps/ledger-live-desktop/src/renderer/hooks/useDeeplinking.ts, apps/ledger-live-mobile/deep-links-test-page.html
Various DEEPLINKS were failing or weren't implemented
1.  Add Account Deeplink
- `ledgerlive://add-account` Opens Add Account Modal
- `ledgerlive://add-account?currency=bitcoin` Opens Add Account Modal with Bitcoin pre-filled
2. Account Deeplink Fix
- `ledgerlive://account?currency=ethereum&address=0x1fd2c4d9e5Fd4f9B4B354Ae22fEc9C40F88324fB` Open 0x1fd2c4d9e5Fd4f9B4B354Ae22fEc9C40F88324fB's Account page
if you have same account but on Polygon and you change currency with polygon then you go to Polygon's Account page
- **Linked resource(s)**: [LIVE-5928] 
https://github.com/LedgerHQ/ledger-live/assets/112866305/4caf517e-95aa-4201-93af-93da5df2303d
https://github.com/LedgerHQ/ledger-live/assets/112866305/fc15f1a9-e4a6-46f4-a68d-1b550abae6f8
_Please make sure …
=> [SUPPORT] : Various Deeplinks improvements 

.changeset/sharp-birds-pay.md, apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/WalletConnectLiveAppNavigator.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
Remove "feature_wallet_connect_live_app" feature flag from codebase
- **Impacted projects**: `LLM`, `LLC` 
- **Linked resource(s)**: [LIVE-9054] 
[LIVE-9054]: https://ledgerhq.atlassian.net/browse/LIVE-9054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SUPPORT]: Remove walletConnectLiveApp FeatureFlag in LL

.changeset/light-months-rush.md, libs/ledger-live-common/src/wallet-api/react.ts
Bugfix: Make searchable manifests visible in categories
- **Impacted projects**: `LL-COMMON` `LLM` 
- **Linked resource(s)**: [JIRA-TICKET-LIVE-9042](https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/623?selectedIssue=LIVE-9042) 
=> feat: make searchable manifests visible in categories

.changeset/loud-bobcats-play.md, apps/ledger-live-desktop/src/renderer/screens/manager/FirmwareUpdate/index.tsx
Just adding some logs as I was not able to reproduce the issue.
- **Impacted projects**: `LLD`
- **Linked resource(s)**: [LIVE-8701](https://ledgerhq.atlassian.net/browse/LIVE-8701)
<details>
<summary>Success Demo on LLD macOS</summary>
In this video, i try to: 
- unplug the device and NOT putting it back in bootloader mode
- restart LLD completely
- and finally doing what was said: unplugging the device and putting it back IN bootloader mode by pressing on the left button
https://github.com/LedgerHQ/ledger-live/assets/15096913/7b617cdc-cd66-443f-8740-7457aa7a5b58
</details>
_Pull Requests must pass the CI and be internally validated in order to …
=> Chore(LIVE-8701): Adding logs to FirmwareUpdate component

.changeset/fast-forks-serve.md, apps/ledger-live-mobile/ios/ar.lproj/InfoPlist.strings, apps/ledger-live-mobile/ios/de.lproj/InfoPlist.strings, apps/ledger-live-mobile/ios/en.lproj/InfoPlist.strings, apps/ledger-live-mobile/ios/es.lproj/InfoPlist.strings, apps/ledger-live-mobile/ios/fr.lproj/InfoPlist.strings, apps/ledger-live-mobile/ios/ja.lproj/InfoPlist.strings, apps/ledger-live-mobile/ios/ko.lproj/InfoPlist.strings, apps/ledger-live-mobile/ios/ledgerlivemobile.xcodeproj/project.pbxproj, apps/ledger-live-mobile/ios/ledgerlivemobile/Info.plist, apps/ledger-live-mobile/ios/pt-BR.lproj/InfoPlist.strings, apps/ledger-live-mobile/ios/ru.lproj/InfoPlist.strings, apps/ledger-live-mobile/ios/tr.lproj/InfoPlist.strings, apps/ledger-live-mobile/ios/zh.lproj/InfoPlist.strings
Fix LLM localization in App Store but also introduce :
- translation of the various texts displayed in the native prompts
```
"NSBluetoothAlwaysUsageDescription"="Ledger Live needs to connect to your Ledger device to manage your crypto assets";
"NSBluetoothPeripheralUsageDescription"="The Ledger Live app needs access device";
"NSCameraUsageDescription"="The Ledger Live app needs access to your camera to scan QR codes";
"NSFaceIDUsageDescription"="This app requires Face ID permission to authenticate using Face recognition.";
"NSMicrophoneUsageDescription"="Allow $(PRODUCT_NAME) to use the microphone";
"NSPhotoLibraryUsageDescription"="Allow $(PRODUCT_NAME) to access your photos";
```
Ressources : 
- https://developer.apple.com/documentation/xcode/adding-support-for-languages-and-regions
- …
=> [SUPPORT] Fix Language displayed in AppStore and  Loacalize Info.plist 🌐

apps/ledger-live-desktop/tests/models/AccountPage.ts
`operationList.waitFor()` is creating more issues than solving (after the waitFor it's possible for operationList to be unmounted before the next async action), it's not needed and scrollIntoViewIfNeeded will already do this job.
- **JIRA or GitHub link**: [LIVE-10147](https://ledgerhq.atlassian.net/browse/LIVE-10147) 
- LLD e2e tests
---
[LIVE-10147]: https://ledgerhq.atlassian.net/browse/LIVE-10147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test(playwright): remove useless operationList.waitFor()

.github/workflows/test-desktop.yml, .github/workflows/test-mobile-e2e.yml
- ci: test desktop combine code and deadcode checks
- ci: test mobile e2e add timeout on ios
In an effort to stabilize our CI and speed it up, we bring various improvement in this PR
- added timeout on detox tests for ios to 45mn and did the same for android
- combine code checks and dead code checks on LLD
- ~~only run react UI tests on linux~~
- **Linked resource(s)**: [LIVE-9603] [LIVE-9777] 
[LIVE-9603]: https://ledgerhq.atlassian.net/browse/LIVE-9603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLW …
=> LIVE-9603 Various CI Improvements

.pnpmfile.cjs, apps/ledger-live-mobile/ios/ledgerlivemobile.xcodeproj/project.pbxproj, pnpm-lock.yaml, tools/actions/desktop-build-checks/build/main.js, tools/actions/desktop-build-checks/package.json, tools/actions/get-workflow-artifacts-id/build/main.js, tools/actions/turborepo-gh-cache/build/server.js, tools/actions/turborepo-s3-cache/build/server.js
Run a missing `pnpm build:actions` to update the desktop-build-checks custom action
- run `pnpm build:actions` to update the desktop-build-checks bundle
---
=> chore: pnpm build:actions

LICENSE.txt, package.json
Add license to Ledger Live repo
- 
---
=> LIVE-10117: Add license to Ledger Live repo

pnpm-lock.yaml, tools/actions/desktop-build-checks/build/main.js, tools/actions/desktop-build-checks/src/logic.ts, tools/actions/desktop-build-checks/src/main.ts
in the report will be also noted 'Comparing X against Y' to know what is compared during checks.
this is specifically important as we have tradeoff to "take the latest artifacts that was compiled" which is not always the latest commit of develop so there could always be false positive and it's good people to be aware of it. in future we could improve something.
fixes #5378 
- **JIRA or GitHub link**: n/a 
- desktop-build-checks only
---
=> chore(desktop-build-checks): annotate commit hashes of what is compared

.changeset/tall-spoons-swim.md, libs/ui/packages/native/storybook/stories/Icon/icons.stories.tsx, libs/ui/packages/react/src/components/asorted/Icon/Icons.stories.tsx
Adding documentation in Native and React Storybooks on how to update icons from design sources.
- 
---
=> feat(ReactUI, IconUI, Icons): Adding documentation on how to update icons from design sources

.changeset/lovely-hotels-wink.md, libs/ledger-live-common/src/hooks/recoverFeatureFlag.ts
Fix issue on url construction with undefined data.
- [Sentry Issue](https://ledger.sentry.io/issues/4617097405/?query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=2)
- 
---
=> bugfix(recover): fix custom uri hook

.changeset/heavy-mails-grow.md, apps/ledger-live-mobile/ios/Podfile.lock, apps/ledger-live-mobile/package.json, pnpm-lock.yaml
Fixed by updating the `react-native-share` library from 7.9.0 to 10.0.1 as indicated [here](https://github.com/react-native-share/react-native-share/issues/1463#issuecomment-1804804176)
https://github.com/LedgerHQ/ledger-live/assets/17146928/1f85e9ff-07fd-44a0-8d6b-5f5b1c7ac98e
- **JIRA or GitHub link**: [LIVE-10111]
- 
---
[LIVE-10111]: https://ledgerhq.atlassian.net/browse/LIVE-10111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LLM - Fixed unresponsive export logs on android 14

.github/workflows/release-prepare-hotfix.yml, .github/workflows/release-prepare.yml
Let's try something different for the automatic release. 
I'm not sure this will fix all the issues we have, but using `--no-ff` will create a merge commit.
Let's hope it'll simplify the merging process
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-9893 
- release and hotfix automatic merge flow
---
=> chore: improve automatic release/hotfix flow

libs/ledgerjs/packages/cryptoassets/src/crypto-assets-importer/importers/asa/asa.test.ts, libs/ledgerjs/packages/cryptoassets/src/crypto-assets-importer/importers/bep20/bep20.test.ts, libs/ledgerjs/packages/cryptoassets/src/crypto-assets-importer/importers/cardanoNative/cardanoNative.test.ts, libs/ledgerjs/packages/cryptoassets/src/crypto-assets-importer/importers/eip712/eip712.test.ts, libs/ledgerjs/packages/cryptoassets/src/crypto-assets-importer/importers/erc20/erc20.test.ts, libs/ledgerjs/packages/cryptoassets/src/crypto-assets-importer/importers/esdt/esdt.test.ts, libs/ledgerjs/packages/cryptoassets/src/crypto-assets-importer/importers/polygon/polygon.test.ts, libs/ledgerjs/packages/cryptoassets/src/crypto-assets-importer/importers/spl/index.ts, libs/ledgerjs/packages/cryptoassets/src/crypto-assets-importer/importers/spl/spl.test.ts, libs/ledgerjs/packages/cryptoassets/src/crypto-assets-importer/importers/stellar/stellar.test.ts, libs/ledgerjs/packages/cryptoassets/src/crypto-assets-importer/importers/trc20/trc20.test.ts
- Add a test to make sure we fetch the correct json file in a given importer
- **JIRA or GitHub link**: `N/A`
- 
---
=> [CAL importers] Test the json file name fetched in the CDN

apps/ledger-live-desktop/tests/playwright.config.ts
LLD e2e tests has been recently flaky and unfortunately by design: we have used `retries: process.env.CI ? 2 : 0` playwright suggested configuration which overall is a bad idea if we don't closely monitor what gets "flaky" over the time (and we didn't).
So in `playwright.config.ts`, `retries: 2`basically told playwright "it's fine if a tests fails 2/3 of the time". In our case, a mismatch screenshot will be allowed to run 2 more times until it really fails. This contributed to introduce even more flaky cases in the past months because it's really hiding test issues under the carpet. 
We reached a point where there were so much flaky tests that we had more chance to fail one of the flaky tests that succeed, even with the retries in place. It also contributed to make the CI runs slower …
=> chore: disable playwright retries set up

.changeset/funny-cobras-call.md, libs/ledger-live-common/src/exchange/swap/hooks/usePageState.ts, libs/ledger-live-common/src/exchange/swap/hooks/usePickDefaultAccount.ts
* fix: fix infinite loop in swap which crash the app
* chore: add changeset
Cherry-pick fix in develop
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/LIVE-10230
- 
---
=> Bugfix/live 10230 (#5519)

.changeset/eighty-berries-fly.md, apps/ledger-live-mobile/src/locales/en/common.json
Wording changed in Deposit/receive flow final step
- **JIRA or GitHub link**:[LIVE-10235] 
- 
---
[LIVE-10235]: https://ledgerhq.atlassian.net/browse/LIVE-10235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUGFIX]: Wording changed in Deposit/receive flow final step

.changeset/bright-seals-drive.md, apps/ledger-live-mobile/src/components/NavigationHeaderCloseButton.tsx, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/logic/postOnboarding/actions.ts, apps/ledger-live-mobile/src/logic/postOnboarding/index.tsx, libs/ledger-live-common/src/postOnboarding/hooks/useAllPostOnboardingActionsCompleted.test.ts, libs/ledger-live-common/src/postOnboarding/hooks/usePostOnboardingHubState.test.ts, libs/ledger-live-common/src/postOnboarding/hooks/usePostOnboardingHubState.ts, libs/ledger-live-common/src/postOnboarding/reducer.test.ts, libs/ledger-live-common/src/postOnboarding/reducer.ts, libs/ledgerjs/packages/types-live/README.md, libs/ledgerjs/packages/types-live/src/postOnboarding.ts
Modified LLM post onboarding items to reflect changes prior to stax launch
- **JIRA or GitHub link**: [LIVE-9559]
- 
---
[LIVE-9559]: https://ledgerhq.atlassian.net/browse/LIVE-9559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(LLM/LLC/PostOnboarding): Post onboarding items

.changeset/tasty-cobras-suffer.md, apps/ledger-live-mobile/src/screens/Settings/Notifications/index.tsx
Text in Settings > Notifications was not legible in Light mode
- **JIRA or GitHub link**: [LIVE-10247] 
- 
---
[LIVE-10247]: https://ledgerhq.atlassian.net/browse/LIVE-10247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUGFIX] Text in Settings > Notifications was not legible in Light mode

libs/coin-evm/docs/evm-family-integration-process/README.md
Document EVM family integration process
- https://ledgerhq.atlassian.net/browse/LIVE-10228
---
=> [SUPPORT][LIVE-10228] add evm-family-integration-process doc

libs/ledger-live-common/src/countervalues/logic.integration.test.ts
sample a subset of currencies to test against backend in countervalues/integration tests.
- **JIRA or GitHub link**: n/a 
- tests only
---
=> chore: lighter countervalues integration tests

apps/ledger-live-desktop/src/main/index.ts, apps/ledger-live-desktop/src/main/internal-lifecycle.ts, apps/ledger-live-desktop/src/main/menu.ts, apps/ledger-live-desktop/src/renderer/components/Delegation/ValidatorRow.tsx, apps/ledger-live-desktop/src/renderer/components/MainSideBar/index.tsx, apps/ledger-live-desktop/src/renderer/components/ModalQuizz/ModalQuizz.tsx, apps/ledger-live-desktop/src/renderer/components/Onboarding/LangSwitcher.tsx, apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/Tutorial/screens/GenuineCheck.tsx, apps/ledger-live-desktop/src/renderer/families/cosmos/ClaimRewardsFlowModal/steps/StepClaimRewards.tsx, apps/ledger-live-desktop/src/renderer/modals/ProtectDiscover/ProtectDiscoverBody.tsx, apps/ledger-live-desktop/src/renderer/screens/market/index.tsx, libs/ledgerjs/packages/types-live/src/feature.ts
Removed a bunch of `@ts-expect-error` from LLD project.
- chore: fixes TS around internal process env
- chore: fixes TS on electron menu
- chore: fixes TS issues related to UI
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-7304 
- LLD: right click contextual menu (non reg)
- LLD: onboarding modal quizz navigation (non reg)
- LLD: onboarding lang change (non reg)
- LLD: market change time range (non reg)
- LLD: cosmos delegation flow (non reg)
---
=> chore(lld): fix some TS errors

apps/ledger-live-desktop/cryptoassets.md
The `cryptoassets.md` file seems out of sync on `develop`.
An updated file with more tokens is generated after running `pnpm desktop test:jest` locally.
Side note:
Is this file still used and needed? It does not seem so at first glance if the file can be out of sync on develop without triggering any error or alert of some kind 🤔 
Hasn't this been replaced by the coinradar initiative (https://coinradar.ledger.com/ [VPN needed])?
- N/A
- Updated `cryptoassets.md`
---
=> [SUPPORT] update cryptoassets.md

.github/workflows/test-mobile-e2e.yml
_CI iOS E2E Tests are failing because iOS simulator can't be found. This aims at fixing this by creating the correct simulator version._
- **JIRA or GitHub link**: [B2CQA-2075](https://ledgerhq.atlassian.net/browse/B2CQA-2075) 
---
[B2CQA-2075]: https://ledgerhq.atlassian.net/browse/B2CQA-2075?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [B2CQA-2075] Fix iOS E2E Tests

.changeset/violet-mails-unite.md, apps/ledger-live-desktop/src/renderer/components/MainSideBar/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
Add isNew field to Feature_ProtectServicesDesktop and add it to the main sidebar.
Fix: Extra margin on CustomTag.
- **JIRA or GitHub link**: [LIVE-10093] 
**Before:**
**After:**
- 
---
[LIVE-10093]: https://ledgerhq.atlassian.net/browse/LIVE-10093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LLD] - [LIVE-10093] - Add isNew to ProtectServicesDesktop and rename "Ledger Recover" to "[L] Recover"

.github/workflows/regen-pods.yml, .github/workflows/test-mobile-e2e.yml, apps/ledger-live-mobile/e2e/jest.config.js, apps/ledger-live-mobile/react-native.config.js
Replay tests in parallel for detox and jest. 2 workers for android & ios
- **JIRA or GitHub link**: [LIVE-10135](https://ledgerhq.atlassian.net/browse/LIVE-10135) 
- 
---
[LIVE-10135]: https://ledgerhq.atlassian.net/browse/LIVE-10135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LIVE-10135] [CI] - [LLM] - [Optimization] - Add Parallelization For Jest and Detox

.changeset/plenty-waves-type.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/AddAccounts/03-Accounts.tsx
Avoid account scheme duplication in add account flow
There seems to be a duplication in the address type list. This PR makes sure the `newAccountSchemes` array, used as part of the logic to display the "Which address type to choose?" hint, only contains unique values.
This change does not impact other coins having multiple address schemes, like Bitcoin for example.
<details><summary>Bitcoin still doing fine</summary>
</details> 
PS: this hint does not seem to be present on LLD
| ![before](https://github.com/LedgerHQ/ledger-live/assets/9203826/74f75d0d-b718-4d7e-ab7a-9ff4fc41d992) |![after](https://github.com/LedgerHQ/ledger-live/assets/9203826/1dbf662a-0d90-4dbe-a19b-b2afbdc396fc)| …
=> [BUGFIX][LLM] Avoid account scheme duplication in add account flow

.changeset/quiet-items-switch.md, libs/ledger-live-common/src/hw/actions/implementations.ts, libs/ledger-live-common/src/hw/actions/staxLoadImage.ts
2 Timeouts were triggered:
- The `unresponsiveTimeout` (default to 15s) from `libs/ledgerjs/packages/hw-transport/src/Transport.ts` in the `exchangeAtomicImpl`
- The `connectionTimeout` (default and in our case 20s) from `libs/ledger-live-common/src/hw/actions/implementations.ts` in the `pollingImplementation`
The "unresponsive timeout" does not trigger an error, only sending an "unresponsive" event that is not used in our flow. 
The "conenction timeout" from the polling implementation was the one triggering a `ConnectManagerTimeout`. 
As it is already already used in a lot of other flows, updating it to 5min by default is not a good idea (currently the default is 20sec). The easiest fix is to configure it specifically for the "stax load image" action (as this timeout is configurable) to …
=> Fix: timeout when requested user to commit the loaded image on Stax

.changeset/serious-pans-battle.md, apps/ledger-live-mobile/src/components/RootNavigator/PostOnboardingNavigator.tsx, apps/ledger-live-mobile/src/logic/postOnboarding/useCompletePostOnboarding.ts, apps/ledger-live-mobile/src/screens/PostOnboarding/PostOnboardingHub.tsx, libs/ledger-live-common/src/postOnboarding/actions.ts
Fixed post onboarding not properly closed causing it to reopen
- 
---
=> fix(LLM/postOnboarding): Fixed post onboarding not properly closed causing it to reopen

.changeset/twelve-dryers-smile.md, apps/ledger-live-mobile/android/app/src/main/java/com/ledger/live/BackgroundRunner.kt, apps/ledger-live-mobile/android/app/src/main/java/com/ledger/live/MainApplication.java
Remove useless notification channel
[]
- **JIRA or GitHub link**:  [LIVE-7044](https://ledgerhq.atlassian.net/browse/LIVE-7044)
---
[LIVE-7044]: https://ledgerhq.atlassian.net/browse/LIVE-7044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Bugfix][LIVE-7044] Remove android channel notification

.changeset/poor-rats-repeat.md, apps/ledger-live-desktop/src/renderer/components/PostOnboardingHub/PostOnboardingActionRow.tsx, apps/ledger-live-desktop/src/renderer/components/PostOnboardingHub/logic/index.tsx, apps/ledger-live-desktop/src/renderer/modals/Receive/index.tsx, apps/ledger-live-desktop/src/renderer/modals/types.ts, apps/ledger-live-desktop/src/renderer/screens/exchange/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, libs/ledgerjs/packages/types-live/README.md, libs/ledgerjs/packages/types-live/src/postOnboarding.ts
New post onboarding items for LLD (same as LLM, see[ Live-9559](https://github.com/LedgerHQ/ledger-live/pull/5458))
https://github.com/LedgerHQ/ledger-live/assets/39890664/b793b29a-34dc-4eb3-9e43-a4aa0bf6f16d
- **JIRA or GitHub link**: [LIVE-9823]
- 
---
[LIVE-9823]: https://ledgerhq.atlassian.net/browse/LIVE-9823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(LLD) Post Onboarding New Items

.changeset/two-moons-reflect.md, apps/ledger-live-mobile/src/components/SelectDevice2/DeviceList.tsx, apps/ledger-live-mobile/src/components/SelectDevice2/index.tsx, apps/ledger-live-mobile/src/locales/en/common.json
Mask MyLedger device list when more than 3 devices paired
(For test purpose i changed limit to 2, because i only have 3 devices right now)
https://github.com/LedgerHQ/ledger-live/assets/112866305/c81fc661-ff2c-498a-a168-8d9320795543
- **JIRA or GitHub link**: [LIVE-9956] 
---
[LIVE-9956]: https://ledgerhq.atlassian.net/browse/LIVE-9956?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [FEAT] : Mask MyLedger device list when more than 3

pnpm-lock.yaml
=> [CI] - Fix CI lock file

apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
Few polishes on Stax myLedger LLD.
- **JIRA or GitHub link**: [LIVE-10204]
- 
---
[LIVE-10204]: https://ledgerhq.atlassian.net/browse/LIVE-10204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LLD] - [LIVE-10204] - Stax myLedger polishes

.changeset/mighty-comics-suffer.md, apps/ledger-live-desktop/src/renderer/components/DeviceAction/animations.ts, apps/ledger-live-mobile/src/helpers/getDeviceAnimation.ts
Replace localize lottie for "Allow Manager" by "validate" which just show a checkmark on the device screen (NanoS, NanoSP, NanoX)
|    
|          
|
- [LIVE-5499](https://ledgerhq.atlassian.net/browse/LIVE-5499)
---
[LIVE-5499]: https://ledgerhq.atlassian.net/browse/LIVE-5499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LIVE-5499] Replace 'Allow Manager' Lottie's by 'Validate' Lottie's 

.changeset/eleven-rivers-deny.md, apps/ledger-live-desktop/src/renderer/components/MainSideBar/index.tsx
Chnage analytics on menuentry_clicked from '/' to '/portfolio'
- **JIRA or GitHub link**: [LIVE-10226] 
- 
---
[LIVE-10226]: https://ledgerhq.atlassian.net/browse/LIVE-10226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUGFIX]: Change analytics on menuentry_clicked

.changeset/smart-carpets-sip.md, apps/ledger-live-desktop/src/renderer/screens/platform/v2/Catalog/Card/Cta.tsx, apps/ledger-live-desktop/src/renderer/screens/platform/v2/Catalog/Card/Full.tsx, apps/ledger-live-desktop/src/renderer/screens/platform/v2/Catalog/Card/Layout.ts, apps/ledger-live-desktop/src/renderer/screens/platform/v2/Catalog/Card/types.ts, apps/ledger-live-mobile/src/components/TabBar/BackgroundGradient.tsx, apps/ledger-live-mobile/src/screens/Platform/v2/Catalog/AppCard.tsx, apps/ledger-live-mobile/src/screens/Platform/v2/Catalog/Cta.tsx, libs/ledger-live-common/src/platform/types.ts
Manifest API PR : https://github.com/LedgerHQ/manifest-api/pull/332 
right now it's hard to attract the eye on a specific app. Recover having been launched recently, we would like to have it pop out more, to attract the eye.
Demo LLM / LLD : 
https://github.com/LedgerHQ/ledger-live/assets/5050709/0218adb5-f4ad-47a3-9271-841ca3ab82c7
https://github.com/LedgerHQ/ledger-live/assets/5050709/82b0aff1-8a4d-4dcb-9e7e-c1169f205db7
This PR introduces the ability to highlight specific live apps in the discover section.
A live app is highlighted if it has `"highlighted"` set to true in its manifest.json.
When highlighted, the app gets a new background (linear gradient css for LLD, linear gradient svg for LLM).  
Additional content for the displayed app is supported, this one sits in a button-like …
=> implements new display of highlighted live apps

renovate.json
This PR bring one baby step towards the ownership of libraries,
we roughly define some group of libraries here,
**this is just a test**, and to test it we need to merge to develop and iterate further more.
For each of these group, we can define in future a more specific rule like "only major" and also a frequency.
Worse case scenario = these groups will create PR to notify each team, there is chance these PR don't pass and then each team decide how to iterate from there.
Typically, the react-native matching is going to try a lot of deps at same time, it will fail, it's ok but at least we will **see** where we are outdated.
Note: the previous `team:@ledgerhq/foo` format was never going to work, as documented in sentry, it must be `team:foo`
- **JIRA or GitHub link**: only to study the …
=> chore: iterate on renovate filters

.changeset/little-boats-move.md, apps/ledger-live-desktop/src/renderer/families/cosmos/AccountBalanceSummaryFooter.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/families/cosmos/AccountBalanceSummaryFooter.tsx, apps/ledger-live-mobile/src/locales/en/common.json, libs/ledger-live-common/src/families/cosmos/api/Cosmos.ts
Quick and dirty display of USDC staking rewards for DYDX to have it for launch before a proper token integration for cosmos chains is done soon.
We fetch the info on the USDC Claimable Rewards balance in the `AccountBalanceSummaryFooter` component of the cosmos family and display the relevant amount beside other staking-related balances.
|![before](https://github.com/LedgerHQ/ledger-live/assets/9203826/ade4b45a-bacf-4aff-9f5d-ac264dcc70ce)|![after](https://github.com/LedgerHQ/ledger-live/assets/9203826/a8bf1124-b730-4c8d-bc88-017df00ff079)|
<details><summary>LLM</summary>
</details> 
- https://ledgerhq.atlassian.net/browse/LIVE-10335 …
=> Display USDC staking rewards for dydx

.changeset/smooth-bags-poke.md, libs/ledger-live-common/src/families/cosmos/chain/Dydx.ts
Update dydx unbonding period to 30 days in modal
- **JIRA or GitHub link**:[https://ledgerhq.atlassian.net/browse/LIVE-10372](https://ledgerhq.atlassian.net/browse/LIVE-10372)
- 
---
=> update dydx unbonding period

.changeset/sixty-rules-wait.md, apps/ledger-live-mobile/src/experimental.ts, apps/ledger-live-mobile/src/locales/en/common.json
Missing translation for Experimental features
- **JIRA or GitHub link**:[LIVE-7993] 
- 
---
[LIVE-7993]: https://ledgerhq.atlassian.net/browse/LIVE-7993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUGFIX]: Missing translation for Experimental features

.changeset/big-emus-hug.md, apps/ledger-live-desktop/src/renderer/components/SideDrawer.tsx
Add no drag zone on drawer
**Before :** 
https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/623?selectedIssue=LIVE-6957
**After :** 
https://github.com/LedgerHQ/ledger-live/assets/32883529/1fa4c844-5b5d-4870-a480-d77e3690badd
- **JIRA or GitHub link**: [JIRA-TICKET](https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/623?selectedIssue=LIVE-6957)
- 
- 
---
=> Add no drag zone on drawer

apps/ledger-live-desktop/src/renderer/components/MainSideBar/index.tsx
Fixing a bug I introduced when fixing a navbar overlap with notification component (Tag).
**Before:**
**After:**
- **JIRA or GitHub link**:  [LIVE-10421] 
- 
---
[LIVE-10421]: https://ledgerhq.atlassian.net/browse/LIVE-10421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LLD] - [LIVE-10421] - Fix cut notification tag on LLD when minimized navbar

libs/ledgerjs/packages/hw-app-exchange/README.md, libs/ledgerjs/packages/hw-app-exchange/src/Exchange.test.ts
Add unit test for `startExchange` method called in the app-exchange wrapper.
- 
---
=> Add unit test on startExchange

.changeset/honest-balloons-confess.md, apps/ledger-live-mobile/ios/ledgerlivemobile.xcodeproj/project.pbxproj, libs/ui/packages/native/.storybook-web/main.js, libs/ui/packages/native/.storybook-web/preview.js, libs/ui/packages/native/src/components/Form/Input/AnimatedInput/AnimatedNotchedLabel.tsx, libs/ui/packages/native/src/components/Form/Input/AnimatedInput/index.tsx, libs/ui/packages/native/src/components/Form/Input/AnimatedInput/inputTextColor.tsx, libs/ui/packages/native/src/components/Form/Input/AnimatedInput/useAnimatedInputFocus.tsx, libs/ui/packages/native/src/components/Form/Input/BaseInput/index.tsx, libs/ui/packages/native/src/components/Form/Input/index.ts, libs/ui/packages/native/storybook/stories/Form/Input/AnimatedInput.stories.tsx
New AnimatedInput component, based on the existing InputBase.
New logic to get inputs styles dynamically with a setup based on objects and utility tools to retrieve the appropriate styling and manage input ui states. (To be used on every form component)
Story for the component
https://github.com/LedgerHQ/ledger-live/assets/39890664/7914ed1e-7098-4dd1-b268-c68f4d313d89
- 
---
=> feat(NativeUI): New animated input component

.prettierignore, CODEOWNERS
(see jira ticket for more context, essentially it's a refinement on the CODEOWNERS that both had lot of mistakes and also needs evolution for next year changes)
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-9908 
---
=> chore: update CODEOWNERS for next year

.changeset/sharp-clocks-hide.md, libs/ledgerjs/packages/hw-app-exchange/src/Exchange.test.ts, libs/ledgerjs/packages/hw-app-exchange/src/Exchange.ts
`Buffer.subarray` method [does not work as expected on LLM](https://ledger.slack.com/archives/C0308JT8WS2/p1701958295755369).
- **JIRA or GitHub link**: [LIVE-10430](https://ledgerhq.atlassian.net/browse/LIVE-10430)
- Fix SELL and FUND issue on LLM
---
[LIVE-10430]: https://ledgerhq.atlassian.net/browse/LIVE-10430?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix issue with startExchange on LLM

.github/pull_request_template.md
In order for the Jira github bot to pickup the reference to a Jira ticket in a PR description and replace it by a link, the ticket number must be specifically written in this format: `[JIRA-123]`
- Github PR template, context section.
---
=> chore(github PR template): improve example of Jira or Github links

.changeset/neat-emus-know.md, apps/ledger-live-desktop/src/renderer/families/cosmos/Delegation/index.tsx, apps/ledger-live-desktop/src/renderer/families/cosmos/RedelegationFlowModal/steps/StepStarter.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/families/cosmos/TransactionConfirmFields.tsx, apps/ledger-live-mobile/src/locales/en/common.json
Fix static unbonding periods in translations
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10394
- 
---
=> fix static unbonding periods cosmos

.changeset/curvy-teachers-deny.md, libs/ledger-live-common/src/currencies/cryptoIcons.test.ts, libs/ledger-live-common/src/currencies/cryptoIcons.ts
- https://ledgerhq.atlassian.net/browse/LIVE-8942 have created a regression on the testnet icons availability ( reported by https://ledgerhq.atlassian.net/browse/LIVE-10429 )
- I also found out that the `camelCase` logic was wrong (and it was wrong before my changes as well) so I also fixed it.
- we also will need to check icons of Arbitrum, and the other coins named "CURRENCY_" in that screenshot:
- A unit test was added to confirm the logic correctly infer these. there is also a small optim on the code to only do the necessary lookup weither it's a token or currency. In future, this codebase will have to be simplified, especially when we move everything to a "lookup by ledgerId".
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10429 
Pull Requests must pass the CI …
=> bugfix: LIVE-10429

.changeset/poor-bottles-learn.md, libs/ledger-live-common/package.json, libs/ledger-live-common/src/families/cardano/hw-getAddress.ts, libs/ledger-live-common/src/families/cardano/js-synchronisation.ts, libs/ledger-live-common/src/families/cardano/logic.ts, libs/ledger-live-common/src/families/cardano/specs.ts, libs/ledger-live-common/src/families/cardano/speculos-deviceActions.ts, libs/ledger-live-common/src/families/cardano/tx-helpers.ts, pnpm-lock.yaml
Update cardano hw-app package version to support cardano nano app v6
- **JIRA or GitHub link**: [https://ledgerhq.atlassian.net/browse/LIVE-5447](https://ledgerhq.atlassian.net/browse/LIVE-5447)
- 
---
=> Update cardano hw-app

.changeset/sharp-guests-scream.md, apps/ledger-live-desktop/src/renderer/components/OperationsList/index.tsx, libs/coin-evm/src/api/explorer/ledger.ts, libs/coin-evm/src/synchronization.ts, libs/coin-framework/src/account/serialization.ts
Fix logs being improperly filtered regarding the invalid dates from the explorers.
- No impact
---
=> [Bugfix] Fix wrong log filtering

.github/workflows/release-create.yml
* Update the `create-release` workflow to make sure that the scripts are completed before staging the potential changes
- 
---
=> (fix) seperate execution and commit steps

.changeset/five-eggs-yell.md, libs/ledger-live-common/src/postOnboarding/hooks/useStartPostOnboardingCallback.ts
Post Onboarding is not only triggered from the Sync Onboarding flow for stax but also in the classic Pairing component. There is no action setup for devices other than stax so it performs a callback redirecting to the homescreen.
This PR prevents the Post Onboarding from re-opening if there's no action setup.
Before :
https://github.com/LedgerHQ/ledger-live/assets/39890664/267a2d83-0fff-4ee5-a109-f7909ffd2f87
After :
https://github.com/LedgerHQ/ledger-live/assets/39890664/81b6a32c-ea18-4842-9e34-88db8070351e
- **JIRA or GitHub link**:  [LIVE-10395](https://ledgerhq.atlassian.net/browse/LIVE-10395)
- 
---
[LIVE-10395]: https://ledgerhq.atlassian.net/browse/LIVE-10395?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …
=> fix(LLM/LLC): Post Onboarding opening once after classic onboarding (LNX))

apps/ledger-live-mobile/ios/ledgerlivemobile.xcodeproj/project.pbxproj
Revert iOS version required to 13.0
- 
---
=> Revert ios version required to 13.0

apps/ledger-live-mobile/ios/ledgerlivemobile.xcodeproj/project.pbxproj
=> Fix Release ios 13

.changeset/rude-suits-push.md, apps/ledger-live-mobile/src/screens/Swap/Form/index.tsx
prevent transaction amount from being updated after sig process on LLM
Duplicate of LLD fix #5583 
[JIRA-10633] 
- 
---
=> bugfix: Live 10633

.changeset/real-walls-try.md, apps/ledger-live-mobile/src/components/StorylyStories/StorylyProvider.tsx, apps/ledger-live-mobile/src/index.tsx, apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx, libs/ledgerjs/packages/types-live/src/feature.ts, libs/ledgerjs/packages/types-live/src/index.ts, libs/ledgerjs/packages/types-live/src/storyly.ts, libs/live-config/src/featureFlags/defaultFeatures.ts
Adding support for Storyly deeplinks in LLM
https://github.com/LedgerHQ/ledger-live/assets/39890664/4c4d8190-8aca-4bbc-a2b4-e073be4e3f1a
- **JIRA or GitHub link**:  [LIVE-9794]
- 
---
[LIVE-9794]: https://ledgerhq.atlassian.net/browse/LIVE-9794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(LLM/Deeplinks): Adding Deeplinks support for Storyly in LLM

apps/ledger-live-desktop/README.md
Update outdated LLD system requirements by link to official doc.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10667
- 
---
=> chore: update LLD system requirements

apps/ledger-live-mobile/src/screens/Portfolio/PortfolioEmptyState.tsx
Fix the Recover banner when you don't have an account.
Before
After
- 
---
=> fix: recover banner display

.changeset/real-steaks-tan.md, apps/ledger-live-mobile/src/screens/Portfolio/PortfolioEmptyState.tsx
Fix Recover banner overflow banner
https://ledgerhq.atlassian.net/browse/LIVE-10679
- 
---
=> Fix Release Recover Banner

.github/workflows/bot-staging-explorer-btc.yml, .github/workflows/bot-staging-explorer-eth.yml
=> ci: updated staging explorer url

README.md, apps/ledger-live-desktop/README.md, apps/ledger-live-mobile/README.md, libs/ledger-live-common/README.md, libs/ledgerjs/README.md
Update level links to show by default all Tech open jobs
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10671
- 
---
=> chore: update Lever links

.changeset/poor-bottles-learn.md, libs/ledger-live-common/package.json, libs/ledger-live-common/src/families/cardano/hw-getAddress.ts, libs/ledger-live-common/src/families/cardano/js-synchronisation.ts, libs/ledger-live-common/src/families/cardano/logic.ts, libs/ledger-live-common/src/families/cardano/specs.ts, libs/ledger-live-common/src/families/cardano/speculos-deviceActions.ts, libs/ledger-live-common/src/families/cardano/tx-helpers.ts, pnpm-lock.yaml
Revert hw-app-cardano lib update as it breaks LLM
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10658
- 
---
=> revert hw-app-update cardano

apps/ledger-live-desktop/README.md
* LLD Readme Typos
* Visual Studio Code Configuration: Removal of content already available through provided link (risk of drifting away)
* File Structure Section Update
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10671
- 
---
=> chore(readme):  file structure section update and typos

apps/ledger-live-mobile/README.md
Add new possibility to interact with nano cli proxy
- 
---
=> Update mobile README

.changeset/perfect-weeks-mix.md, libs/coin-evm/src/__tests__/unit/editTransaction/hasMinimumFunds.test.ts, libs/coin-evm/src/__tests__/unit/editTransaction/isStrategyDisabled.test.ts, libs/coin-evm/src/__tests__/unit/editTransaction/isTransactionConfirmed.test.ts, libs/coin-evm/src/__tests__/unit/getTransactionStatus.unit.test.ts, libs/coin-evm/src/__tests__/unit/operation.test.ts, libs/coin-evm/src/editTransaction/index.ts, libs/coin-evm/src/getTransactionStatus.ts, libs/coin-evm/src/operation.ts
Add missing tests to improve code cov for coin-evm editEvmTransaction codebase:
- `operation.ts`
- `getTransactionStatus.ts`
- `hasMinimumFunds.ts`
- `isTransactionConfirmed.ts`
- `isStrategyDisabled.ts`
- `getTransactionStatus.ts`
Removed an unreachable statement in the `getStuckAccountAndOperation` function in `libs/coin-evm/src/operation.ts` (see related comment)
|![before1](https://github.com/LedgerHQ/ledger-live/assets/9203826/d6232363-dfd7-467e-8ad5-d29127d1339b)|![after1](https://github.com/LedgerHQ/ledger-live/assets/9203826/34f2c978-8a0b-4974-8e38-61c105bd943b)|
|![before2](https://github.com/LedgerHQ/ledger-live/assets/9203826/a217466d-cf44-4aff- …
=> [SUPPORT][LIVE-10636] Improve code cov for coin-evm editEvmTransaction codebase

.changeset/ten-olives-worry.md, apps/ledger-live-desktop/src/renderer/components/DeviceAction/index.tsx, apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx, apps/ledger-live-desktop/src/renderer/components/ErrorBody.tsx, apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/EarlySecurityChecks/DeviceNotGenuineDrawer.tsx, apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/EarlySecurityChecks/ErrorDrawer.tsx, apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/EarlySecurityChecks/ExitChecksDrawer.tsx, apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/errors/Cancel.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- **JIRA or GitHub link**: [LIVE-10341] 
- Fix "locked device" device action state rendering
- Rework `ErrorBody` component used by device actions so that it works everywhere even in v2 style provider
- Use `ErrorBody` for "device not onboarded" device action state
---
[LIVE-10341]: https://ledgerhq.atlassian.net/browse/LIVE-10341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bugfix/live 10341 LLD polish of "locked device" device action state

.github/workflows/test-desktop-external.yml, .github/workflows/test-desktop.yml, .github/workflows/test-mobile.yml, turbo.json
Update turbo.json file to make sure lld linting will correctly add the lint.json 
file produced whenever we are hitting cache
Also removed the extra prettify steps in CI (we can always do it locally, thank you 
VSCode)
Turborepo allows to replay some scripts using cache so we don't have to actually rerun all the scripts that would take time, if the output are already calculated. However, we forgot to add `lint.json` in the outputs on `ledger-live-destop#lint` thus it was not restoring this file.
Adding the output to the turbo.json allows turbo to understand this file will need to be restore when replaying cache
- fix CI test-desktop.yml
---
=> chore: fix lint.json file not created when replaying outputs with turbo

.changeset/smart-snails-leave.md, apps/ledger-live-mobile/ios/ledgerlivemobile.xcodeproj/project.pbxproj, libs/ledger-live-common/src/families/near/__snapshots__/bridge.integration.test.ts.snap, libs/ledger-live-common/src/families/near/api/archive-node-sdk.ts
- Everytime a user go on their account they load all the Near nodes and the commissions for these nodes. We now add a cache on these function to only call these functions if the data is not in the cache
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10172
- 
---
=> [near] cache getValidator and getCommission

.changeset/itchy-oranges-crash.md, apps/ledger-live-desktop/src/renderer/modals/Receive/index.tsx
Unresponsive button in Receive token flow due to re-render 
```
//apps/ledger-live-desktop/src/renderer/modals/Receive/Body.tsx
useEffect(() => {
const stepId =
params && params.startWithWarning ? "warning" : params.receiveTokenMode ? "account" : null;
if (stepId) onChangeStepId(stepId);
}, [onChangeStepId, params]);
```
This useEffect was called in loop 
https://github.com/LedgerHQ/ledger-live/assets/112866305/73f68cb7-6954-4817-8745-0c134615ebdb
- **JIRA or GitHub link**:[LIVE-10772] 
- 
---
[LIVE-10772]: https://ledgerhq.atlassian.net/browse/LIVE-10772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUGFIX]: Unresponsive button in Receive token flow

.changeset/tricky-needles-allow.md, apps/ledger-live-desktop/src/renderer/families/solana/DelegationFlowModal/steps/StepAmount.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/families/solana/DelegationFlow/SelectAmount.tsx, apps/ledger-live-mobile/src/families/solana/DelegationFlow/Summary.tsx, apps/ledger-live-mobile/src/locales/en/common.json, libs/ledger-live-common/src/families/solana/__snapshots__/bridge.integration.test.ts.snap, libs/ledger-live-common/src/families/solana/banner.test.ts, libs/ledger-live-common/src/families/solana/bridge.integration.test.ts, libs/ledger-live-common/src/families/solana/js-buildTransaction.ts, libs/ledger-live-common/src/families/solana/js-estimateMaxSpendable.ts, libs/ledger-live-common/src/families/solana/js-prepareTransaction.ts, libs/ledger-live-common/src/families/solana/js-signOperation.ts, libs/ledger-live-common/src/families/solana/js-synchronization.ts, libs/ledger-live-common/src/families/solana/serialization.ts, libs/ledger-live-common/src/families/solana/tx-fees.ts, libs/ledger-live-common/src/families/solana/types.ts, libs/ledger-live-common/src/families/solana/utils.ts
As described in the [support article](https://support.ledger.com/hc/en-us/articles/12568029655453-Fixing-a-Sorry-internet-seems-to-be-down-error-with-Solana?support=true), Solana users faces the issue with not enough funds to unstake their SOL pretty often.  To make the process safer this PR adds a friendly warning to reserve some SOL to cover future unstaking fees.
After a small research, we found out that:
- Everstake recommends to keep at least 0.05 SOL
- Phantom also recommends  0.05 SOL
- Solflare recommends 0.01 but keeps 0.05 when “Use Max” is involved
Therefore, we think that 0.01 is a reasonable amount. 
In addition, we found and fixed the discrepancy between maximum spendable amount in the upper text and in the amount field when “Use Max” is selected.
Besides that, as requested …
=> Safer Solana staking

libs/ledger-live-common/src/config/index.test.ts
Unit test example for mocking 
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-9515
- 
---
=> Coinconfig unit test

libs/ledger-live-common/src/exchange/swap/index.ts
Update Moonpay signature
- **JIRA or GitHub link**: [LIVE-10321](https://ledgerhq.atlassian.net/browse/LIVE-10321)
- 
---
[LIVE-10321]: https://ledgerhq.atlassian.net/browse/LIVE-10321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(swap): update Moonpay CAL sig

apps/ledger-live-mobile/docs/llm_e2e_testing.md, apps/ledger-live-mobile/e2e/models/accounts/accountPage.ts, apps/ledger-live-mobile/e2e/models/accounts/accountsPage.ts, apps/ledger-live-mobile/e2e/specs/addAccounts/addAccount.spec.ts, apps/ledger-live-mobile/src/screens/Accounts/AddAccount.tsx, apps/ledger-live-mobile/src/screens/Portfolio/PortfolioEmptyState.tsx
Adds a Detox test to Add account via modal + modifies the doc with correct command line to setup Detox
- [B2CQA-786]
- 
---
[B2CQA-786]: https://ledgerhq.atlassian.net/browse/B2CQA-786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: add test for adding account from modal + correction in doc

apps/ledger-live-desktop/src/renderer/components/LiveAppDrawer.tsx, apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/WalletAPIWebview.tsx, apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/CompleteExchange/Body.tsx, apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/StartExchange/index.tsx, apps/ledger-live-desktop/src/renderer/modals/types.ts, libs/ledger-live-common/src/exchange/platform/completeExchange.ts, libs/ledger-live-common/src/exchange/platform/startExchange.ts, libs/ledger-live-common/src/exchange/platform/types.ts, libs/ledger-live-common/src/hw/actions/startExchange.ts, libs/ledgerjs/packages/hw-app-exchange/src/Exchange.ts, libs/ledgerjs/packages/hw-app-exchange/src/index.ts
* Add startExchange conformance to NG ExchangeTypes
* Add types on startExchange LLD method calls
* Check for app version in case of NG ExchangeType call
- **JIRA or GitHub link**: [LIVE-10434](https://ledgerhq.atlassian.net/browse/LIVE-10434)
- StartExchange (swap) on LLD
---
[LIVE-10434]: https://ledgerhq.atlassian.net/browse/LIVE-10434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(swap): startExchange accept NG types

.changeset/great-clouds-brake.md, libs/ui/packages/native/src/components/Form/Input/AnimatedInput/index.tsx
Fixed warning due to unnecessary forwardRef
- 
---
=> fix(NativeUI): AnimatedInput warning fix

.changeset/brown-cats-mate.md, apps/ledger-live-mobile/src/contentCards/cards/vertical/elements.tsx, apps/ledger-live-mobile/src/contentCards/layouts/grid/index.tsx, apps/ledger-live-mobile/src/dynamicContent/ContentCardsCategory/Layout.tsx, apps/ledger-live-mobile/src/dynamicContent/types.ts, apps/ledger-live-mobile/src/dynamicContent/utils.tsx
Addition of the Grid Layout to the Flexible Content Cards System as well as 3 different variants (small, medium and large) of the squared content card
- 
---
=> LLM - Addition of the Grid Layout to the Flexible Content Cards System

apps/ledger-live-desktop/.gitignore, apps/ledger-live-desktop/scripts/ci-lint.mjs, apps/ledger-live-mobile/scripts/e2e-ci.mjs
Fixes desktop lint:ci scripts to run without `token` or `port` arguments
- 
---
=> chore: update lint script

.changeset/odd-worms-double.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.tsx, libs/ledger-live-common/src/exchange/swap/hooks/live-app-migration/useIsCurrencySupported.ts, libs/ledger-live-common/src/exchange/swap/hooks/live-app-migration/useIsSwapLiveApp.test.ts, libs/ledger-live-common/src/exchange/swap/hooks/live-app-migration/useIsSwapLiveApp.ts, libs/ledgerjs/packages/types-live/src/feature.ts, libs/live-config/src/featureFlags/defaultFeatures.ts
* Add `ptxSwapLiveAppDemoZero` feature flag and use it`
* Fix logic around whitelisting coins and families.
=> fix: update swap live app ff logic & add new feature flag

.changeset/rude-moose-bathe.md, apps/ledger-live-desktop/src/renderer/components/SelectFeeStrategy.tsx, apps/ledger-live-desktop/src/renderer/families/bitcoin/SendAmountFields.tsx, apps/ledger-live-desktop/src/renderer/families/evm/SendAmountFields/SelectFeeStrategy.tsx, apps/ledger-live-desktop/src/renderer/families/evm/SendAmountFields/index.tsx, apps/ledger-live-desktop/src/renderer/modals/Send/fields/AmountField.tsx, apps/ledger-live-desktop/src/renderer/modals/Send/steps/StepAmount.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, libs/coin-evm/src/getTransactionStatus.ts
New insufficient funds errors when selecting a token for which the parent account doesn't have enough balance to pay gas fees.
https://github.com/LedgerHQ/ledger-live/assets/39890664/b44d4d99-fa1e-49fd-a777-c10fad42039b
- **JIRA or GitHub link**: [LIVE-9660]
- 
---
[LIVE-9660]: https://ledgerhq.atlassian.net/browse/LIVE-9660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(LLD/send): New gas fees parent account error

.changeset/moody-eggs-serve.md, libs/env/src/env.ts, libs/ledger-live-common/src/families/solana/validator-app/index.ts
* Solana's `getValidators` function uses the earn dashboard URL to get information about validators (mainnet only)
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10539
- 
---
=> Get solana validators information from earn dashboard

.changeset/lucky-clocks-travel.md, libs/ledger-live-common/src/families/cardano/utils.ts
The current Cardano pool used for our Ledger by Figment validator is close to saturation.
This PR switches to a new, approved one.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10924
---
=> [feat] Change pool ID of Ledger Cardano validator

.changeset/stupid-rules-shave.md, libs/ledger-live-common/src/wallet-api/constants.ts
Use description for the search bar of discover
https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/623?selectedIssue=LIVE-10717
- 
---
=> Use description for the search bar discover

.github/workflows/test-mobile-e2e.yml
Removing any reference to S3 keys in our workflows in favour of IAM role management
- 
---
=> chore: remove remaining s3 keys from workflow

.changeset/lemon-spies-leave.md, libs/ledger-live-common/src/families/solana/tx-fees.ts
**(Backport of https://github.com/LedgerHQ/ledger-live/pull/5913 for release branch)**
For an unknown reason, it seems that the Solana backend call made by `getFeeForMessage` often fails to return a valid fee value. 
The current mitigation was to call a `retryWithNewBlockhash` function, but only once.
This is apparently not enough anymore, so this PR extends the retry mechanism to an arbitrary 10 times.
Manual testing shows that this makes the user facing error to happen a lot less.
In case of a failure even after all the retries, this PR also changes the user-facing message for a cleaner NetworkError, suggesting to the user to retry, which in most cases has a good chance to work the second time.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10945
Pull Requests …
=> [bugfix] Solana: extend the retry mechanism to mitigate error when fetching fees - RELEASE

.changeset/lemon-spies-leave.md, libs/ledger-live-common/src/families/solana/tx-fees.ts
For an unknown reason, it seems that the Solana backend call made by `getFeeForMessage` often fails to return a valid fee value. 
The current mitigation was to call a `retryWithNewBlockhash` function, but only once.
This is apparently not enough anymore, so this PR extends the retry mechanism to an arbitrary 10 times.
Manual testing shows that this makes the user facing error to happen a lot less.
In case of a failure even after all the retries, this PR also changes the user-facing message for a cleaner NetworkError, suggesting to the user to retry, which in most cases has a good chance to work the second time.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10945
- Solana sync …
=> [bugfix] Solana: extend the retry mechanism to mitigate error when fetching fees

libs/exchange-module/package.json, libs/exchange-module/scripts/createModulePackage.mjs
Update the scripts for the exchange module build step to work on windows too by avoiding the use of echo to generate the `package.json` file
- 
---
=> chore: fix exchange module esm package.json generation on windows

.changeset/neat-beers-applaud.md, libs/ledger-live-common/src/wallet-api/constants.ts
Revert changes introduced by https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/623?selectedIssue=LIVE-10717
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/623?selectedIssue=LIVE-10717
- 
---
=> remove description use in search manifest

.changeset/purple-pears-mix.md, apps/ledger-live-mobile/ios/ledgerlivemobile.xcodeproj/project.pbxproj, apps/ledger-live-mobile/src/contentCards/layouts/carousel/index.tsx, apps/ledger-live-mobile/src/contentCards/layouts/carousel/pagination/bullets.tsx, apps/ledger-live-mobile/src/contentCards/layouts/grid/index.tsx, apps/ledger-live-mobile/src/dynamicContent/ContentCardsCategory/Layout.tsx, apps/ledger-live-mobile/src/dynamicContent/types.ts, apps/ledger-live-mobile/src/dynamicContent/useDynamicContent.tsx, apps/ledger-live-mobile/src/dynamicContent/utils.tsx, apps/ledger-live-mobile/src/screens/Manager/index.tsx, apps/ledger-live-mobile/src/screens/Portfolio/PortfolioEmptyState.tsx, apps/ledger-live-mobile/src/screens/Portfolio/index.tsx
Added the my_ledger content cards location as well as the top_wallet one in order to differentiate with the other content cards displayed in the wallet page
- 
---
=> LLM - Added the my_ledger content cards location

.changeset/real-parents-doubt.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/AnalyticsOptInPrompt/variantA/Details.tsx, apps/ledger-live-mobile/src/screens/AnalyticsOptInPrompt/variantA/Main.tsx, apps/ledger-live-mobile/src/screens/AnalyticsOptInPrompt/variantB/Details.tsx, apps/ledger-live-mobile/src/screens/AnalyticsOptInPrompt/variantB/Main.tsx, libs/ui/packages/native/src/components/Form/Switch/index.tsx, libs/ui/packages/native/src/components/Text/getTextStyle.ts, libs/ui/packages/native/src/styles/theme.ts
Created screens (main + secondary) for variants A & B
Variant A :
https://github.com/LedgerHQ/ledger-live/assets/39890664/da8d34c9-0336-4c5f-b908-5942c2166945
Variant B :
- **JIRA or GitHub link**:  [LIVE-10937]
- 
---
[LIVE-10937]: https://ledgerhq.atlassian.net/browse/LIVE-10937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(AnalyticsPrompt): Created screens (main + secondary) for variants A & B

apps/ledger-live-mobile/src/analytics/segment.ts, apps/ledger-live-mobile/src/components/AnalyticsConsole/Status.tsx
Small changes to ptx properties
- **JIRA or GitHub link**: [LIVE-10935]
- 
---
[LIVE-10935]: https://ledgerhq.atlassian.net/browse/LIVE-10935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LLM - Small changes to ptx properties

.changeset/witty-laws-join.md, apps/ledger-live-mobile/src/analytics/Track.ts, apps/ledger-live-mobile/src/components/Web3AppWebview/PlatformAPIWebview.tsx, apps/ledger-live-mobile/src/components/Web3AppWebview/helpers.ts, apps/ledger-live-mobile/src/components/WebPTXPlayer/CustomHandlers.ts, apps/ledger-live-mobile/src/screens/Settings/General/AnalyticsRow.tsx, apps/ledger-live-mobile/src/screens/Swap/Form/index.tsx
Fix CI lint issues on develop due to this PR : https://github.com/LedgerHQ/ledger-live/pull/5917
- 
---
=> LLM - Fix CI lint issues on develop

.changeset/itchy-donuts-knock.md
changeset for https://github.com/LedgerHQ/ledger-live/pull/5949
- 
---
=> chore: added changeset for fixed tezos crash release

.changeset/chilly-avocados-juggle.md, apps/ledger-live-desktop/src/renderer/components/DeviceAction/animations.ts
Replace lottie to allow manager on nanoSP, nano and nanoX
- **JIRA or GitHub link**: [LIVE-5919] 
- lottie animations to allow manager on install language & navigate to my ledger modified on nano, nanoSP and nanoX
---
[LIVE-5919]: https://ledgerhq.atlassian.net/browse/LIVE-5919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LIVE-5919] [LLM ] Fix misalignment between "Allow manager" and "Allow secure connection"

.changeset/seven-bobcats-smash.md, apps/ledger-live-mobile/src/screens/Assets/index.tsx, apps/ledger-live-mobile/src/screens/Portfolio/PortfolioAssets.tsx
"Hide empty token accounts" setting or "Hide token" hides accounts from your account page and from the main Portfolio page
https://github.com/LedgerHQ/ledger-live/assets/112866305/c3c4a8e4-1a8a-43b6-bdfc-0f5346564bb2
- **JIRA or GitHub link**: [LIVE-10816]
- 
---
[LIVE-10816]: https://ledgerhq.atlassian.net/browse/LIVE-10816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUGFIX] : -Hide empty token accounts- setting or -Hide token- hides accounts from your account page and from the main Portfolio page

.changeset/brown-crews-hammer.md, apps/ledger-live-desktop/src/renderer/screens/platform/v2/Catalog/Browse/Result/index.tsx, apps/ledger-live-desktop/src/renderer/screens/platform/v2/Catalog/Browse/Search.tsx, apps/ledger-live-desktop/src/renderer/screens/platform/v2/Catalog/Browse/index.tsx, apps/ledger-live-desktop/src/renderer/screens/platform/v2/hooks.ts, apps/ledger-live-mobile/src/screens/Platform/v2/Catalog/Search/index.tsx, apps/ledger-live-mobile/src/screens/Platform/v2/Catalog/index.tsx, apps/ledger-live-mobile/src/screens/Platform/v2/hooks.ts, libs/ledger-live-common/src/hooks/useSearch.ts, libs/ledger-live-common/src/wallet-api/react.ts
Make the searchable Dapp only visible through the search bar for both LLD and LLM
---
=> feat: make searchable apps not visible in categories

.changeset/fuzzy-frogs-smash.md, .changeset/shaggy-cherries-prove.md, apps/ledger-live-desktop/src/renderer/screens/manager/DeviceDashboard/AppsList/AppActions.tsx, libs/ledger-live-common/src/apps/polyfill.ts
For some apps, the polyfilling of "type" was not matching the logic of list apps v1 which resulted in some issues.
cf. app "Lens" on the screenshots:
**Before:**
"learn more" CTA missing, uninstall CTA misplaced
**After:**
"learn more" is there, uninstall icon placed properly
- **JIRA or GitHub link**: [LIVE-10994] 
- My Ledger on LLM and LLD: apps catalog
---
[LIVE-10994]: https://ledgerhq.atlassian.net/browse/LIVE-10994?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LIVE-10994][LLD][List apps v2] UI issues + Learn more links missing for installed apps not supported by Ledger Live 

apps/ledger-live-desktop/RELEASE_NOTES.md
- add release notes for LLD version 2.75.0 
- 
---
=> chore: add release notes 2.75.0

CODEOWNERS
update codeowners
- **JIRA or GitHub link**:  na (slack) 
- na
---
=> chore: codeowners to mention live-countervalues

CODEOWNERS
Adds the PTX team as CODEOWNERS for the exchange-module
- 
---
=> chore: add CODEOWNERS for the exchange-module

apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/CompleteExchange/Body.tsx
Do not close error drawer if exchange error is an instance of WrongDeviceForAccount
https://ledgerhq.atlassian.net/browse/LIVE-10895
- 
---
=> fix: do not close swap error if wrong device for account

.changeset/gold-beds-appear.md, apps/ledger-live-mobile/src/contentCards/cards/vertical/elements.tsx, apps/ledger-live-mobile/src/contentCards/cards/vertical/index.tsx, apps/ledger-live-mobile/src/dynamicContent/types.ts, apps/ledger-live-mobile/src/dynamicContent/utils.tsx
Big Card CC on myLedger in LLM
- **JIRA or GitHub link**: []LIVE-9965] 
- 
---
=> [FEAT]: Big CC in myLedger

.changeset/real-parents-doubt.md
=> fix(changeset): Fixed broken changeset

.github/workflows/test-desktop-external.yml
Fix broken Desktop External CI due to recent changes in S3 setup
- 
---
=> chore: fix desktop external ci

.changeset/great-maps-warn.md, apps/ledger-live-mobile/src/screens/Swap/Form/TxForm/From.tsx
Show spendable balance rather than full balance
| <img width="1596" alt="Screenshot 2024-01-30 at 15 23 57" src="https://github.com/LedgerHQ/ledger-live/assets/138497251/29d633ad-c1cf-48ef-8812-b37b270ebde4">              |         <img width="1495" alt="Screenshot 2024-01-30 at 15 22 19" src="https://github.com/LedgerHQ/ledger-live/assets/138497251/23e2a7e0-2057-4318-9a9d-b587d3d59810">      |
- **JIRA or GitHub link**: [LIVE-11047](https://ledgerhq.atlassian.net/browse/LIVE-11047)
- ...
---
[LIVE-11047]: https://ledgerhq.atlassian.net/browse/LIVE-11047?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWN …
=> bugfix(LIVE-11047): swap llm issue when trying to swap from sol with delegated account

.changeset/silly-cobras-swim.md, libs/ledger-live-common/src/families/casper/__snapshots__/bridge.integration.test.ts.snap, libs/ledger-live-common/src/families/casper/bridge.integration.test.ts, libs/ledger-live-common/src/families/casper/bridge/account.ts, libs/ledger-live-common/src/families/casper/bridge/bridgeHelpers/addresses.ts, libs/ledger-live-common/src/families/casper/bridge/bridgeHelpers/txn.ts, libs/ledger-live-common/src/families/casper/consts.ts, libs/ledger-live-common/src/families/casper/hw-getAddress.ts, libs/ledger-live-common/src/families/casper/speculos-deviceActions.ts, libs/ledger-live-common/src/families/casper/utils.unit.test.ts
Fixes invalid Ed25519 recipient error when transfering CSPR tokens. Includes minor refactoring related to function name changes and removing redundant logic. Please have a look at the screenshot to better understand this bugfix.
Error with Ed25519 address:
To reproduce please try sending some CSPR to the following ed25519 pubkey `01bf489970ee9ad639854b9a78ed19d08b5f8d8f2185099b44c0fc5f6f467b14b4`
This fix should enable users to be able to send funds to all ed25519 casper pubkey/addresses. 
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11049
---
=> [Bugfix/LLC/Casper] Fix invalid Ed25519 recipients error

.changeset/spicy-mangos-train.md, apps/ledger-live-desktop/src/renderer/screens/platform/v2/Catalog/Card/Full.tsx, apps/ledger-live-mobile/src/screens/Platform/v2/Catalog/AppCard.tsx
Translate cta and subtitble text for lld and llm on discover 
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/623?selectedIssue=LIVE-10948
---
=> feat: translate cta and subtitble

.changeset/honest-rats-tap.md, libs/coin-framework/src/derivation.test.ts, libs/coin-framework/src/derivation.ts
`hw-app-btc` do not support extended derivation paths anymore. This PR removes legacy derivation paths.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-9574
- 
---
=> removed all btc invalid derivation paths

.changeset/forty-dragons-own.md, apps/ledger-live-desktop/src/renderer/components/OperationsList/index.tsx, libs/coin-evm/src/api/explorer/ledger.ts, libs/coin-evm/src/synchronization.ts, libs/coin-framework/src/account/serialization.ts
This reverts commit be22d724cf5499fe4958bfb3b5f763ffaf0d0446.
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/LIVE-10923
---
=> [LIVE-10923] Revert "[SUPPORT] - Adding logs for invalid dates (#5524)"

.changeset/tall-rats-cry.md, libs/ui/packages/crypto-icons/src/svg/currency_linea_goerli.svg
Fixed svg source causing storybook build error.
- ...
---
=> feat(CryptoIcons): fixed svg source causing storybook build error

apps/ledger-live-desktop/src/renderer/components/TrackAppStart.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/ShareAnalyticsButton.tsx
Fix disable settings option
- **JIRA or GitHub link**: [LIVE-11071] 
- ...
---
[LIVE-11071]: https://ledgerhq.atlassian.net/browse/LIVE-11071?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LLD - Fix disable settings option

package.json, pnpm-lock.yaml, tools/actions/turbo-affected/build/main.js, tools/actions/turbo-affected/src/main.ts
Fix turbo version to 1.11.3
- ...
---
=> [HOTFIX] Turbo version - PR gate setup job 

.changeset/giant-frogs-clap.md, .changeset/heavy-birds-carry.md, libs/evm-tools/package.json, libs/evm-tools/src/__tests__/messages/EIP712/index.unit.test.ts, libs/evm-tools/src/message/EIP712/index.ts, pnpm-lock.yaml
`evm-tools` is a dependency used in `hw-app-eth` and `hw-app-eth` is used in the live but also by other wallets.
However `evm-tools` was using `live-network` library that doesn't work well outside of the Live because we rely `LEDGER_CLIENT_VERSION` to inject the httpsAgent in axios.
In this PR we remove this dependency in `evm-tools` so that `hw-app-eth` can be used by other wallets outside Ledger Live
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11001
- 
---
=> Remove live-network dependency in evm-tools

apps/ledger-live-mobile/src/screens/FeatureFlagsSettings/FeatureFlagEdit.tsx, apps/ledger-live-mobile/src/screens/FeatureFlagsSettings/index.tsx
Improved feature flags edition on LLM
https://github.com/LedgerHQ/ledger-live/assets/17146928/0edb5711-7979-447e-97fa-0482caff0cc3
- **JIRA or GitHub link**: [LIVE-11118]
- ...
---
[LIVE-11118]: https://ledgerhq.atlassian.net/browse/LIVE-11118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LLM - improved feature flags edition

.changeset/new-shrimps-rescue.md, apps/ledger-live-desktop/package.json, apps/ledger-live-desktop/src/main/menu.ts, apps/ledger-live-desktop/src/renderer/App.tsx, apps/ledger-live-desktop/src/renderer/hooks/useDeeplinking.ts, apps/ledger-live-desktop/src/storyly/StorylyProvider.tsx, apps/ledger-live-desktop/src/storyly/useStoryly.tsx, apps/ledger-live-desktop/src/types/storyly-web.d.ts, apps/ledger-live-mobile/ios/ledgerlivemobile.xcodeproj/project.pbxproj, pnpm-lock.yaml
Adding support for Storyly deeplinks in LLD (based on https://github.com/LedgerHQ/ledger-live/pull/5696 for LLM)
https://github.com/LedgerHQ/ledger-live/assets/39890664/328c1d7e-7784-4228-824f-f86052b63b8d
- 
---
=> feat(LLD/Deeplinks): Adding Deeplinks support for Storyly in LLD

.github/workflows/build-desktop-external.yml, .github/workflows/build-desktop.yml, .github/workflows/build-mobile-external.yml, .github/workflows/build-mobile.yml, .github/workflows/commitlint.yml, .github/workflows/generate-screenshots.yml, .github/workflows/healthchecks-runners.yaml, .github/workflows/regen-doc.yml, .github/workflows/regen-pods.yml, .github/workflows/release-final-nightly.yml, .github/workflows/test-desktop-external.yml, .github/workflows/test-desktop.yml, .github/workflows/test-mobile-e2e.yml, .github/workflows/test-mobile.yml, .github/workflows/test.yml
- Replace `if: always()` by `if: ${{ !cancelled() }}` in workflows according to the [documentation](https://docs.github.com/en/actions/learn-github-actions/expressions#always)
- **JIRA or GitHub link**: [LIVE-10167] 
- CI workflows `build-desktop` `build-desktop-external` `build-mobile-external` `build-mobile` `commitlint` `generate-screenshots` `healthchecks-runners` `regen-doc` `regen-pods` `release-final-nightly` `test-desktop-external` `test-desktop` `test-mobile-e2e` `test-mobile` `test`
---
[LIVE-10167]: https://ledgerhq.atlassian.net/browse/LIVE-10167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LIVE-10167] [CI] - [Github Actions] - Analyse "if: always()"

.changeset/lazy-parents-clap.md, apps/ledger-live-desktop/src/renderer/screens/manager/DeviceDashboard/AppsList/Item.tsx, apps/ledger-live-mobile/src/screens/Manager/AppsList/AppRow.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
Displaying the app's developer name if it's available.
Introducing a new feature flag `"myLedgerDisplayAppDeveloperName"` to toggle this feature on/off.
https://github.com/LedgerHQ/ledger-live/assets/91890529/1a769a52-6347-4142-8377-b3b3aaa0b62b
- **JIRA or GitHub link**: [LIVE-10949] [LIVE-10950]
- LLM & LLD My Ledger catalog of apps
---
[LIVE-10949]: https://ledgerhq.atlassian.net/browse/LIVE-10949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-10950]: https://ledgerhq.atlassian.net/browse/LIVE-10950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LIVE-10878] App Store Developer Name Display

.github/workflows/test-desktop.yml
To speed up our CI and minimize usage of our runners we don't want to replay our desktop e2e tests on Windows and MacOS.
New workflow: https://github.com/LedgerHQ/ledger-live/actions/runs/7797832626
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11137
- ...
---
=> Remove playwright replay on macOS and Windows

.changeset/young-timers-tickle.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/WebviewErrorDrawer/index.tsx
https://ledgerhq.atlassian.net/browse/LIVE-11114
- ...
---
=> feat: better error message when user reject tx on swap

.changeset/spicy-crews-clean.md, apps/ledger-live-desktop/src/renderer/components/MainSideBar/index.tsx
Fixed sidebar active items for market cryptocurrencies and for portfolio assets
BEFORE
AFTER
- **JIRA or GitHub link**: [LIVE-11013]
- ...
---
[LIVE-11013]: https://ledgerhq.atlassian.net/browse/LIVE-11013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LLD - Fixed sidebar active items

.changeset/young-countries-brush.md, libs/ledger-live-common/src/platform/providers/RemoteLiveAppProvider/index.tsx
Fix RemoteLiveAppProvider not updating if env changes
---
=> support: fix RemoteLiveAppProvider not updating if env changes

.changeset/tasty-forks-kneel.md, apps/ledger-live-mobile/src/components/RootNavigator/WalletConnectLiveAppNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/types/BaseNavigator.ts, apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx, apps/ledger-live-mobile/src/screens/Platform/v2/hooks.ts, apps/ledger-live-mobile/src/screens/Platform/v2/types.ts
Improve wallet connect deep link handling for mobile
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11201 
---
=> fix(LLM): wallet connect deep link handling [LIVE-11201]

.github/workflows/test-desktop-external.yml, .github/workflows/test-desktop.yml, .github/workflows/test-mobile-e2e.yml, apps/ledger-live-desktop/README.md, apps/ledger-live-mobile/README.md
Removing the Allure Reports Export on Server CI jobs until fix is provided
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11193
- ...
---
=> chore: Turn off Allure Reports Export on Server CI jobs

.github/workflows/generate-screenshots.yml
Stop generating mac and windows screenshots with the generate-screenshots github action
- ...
---
=> Stop generating mac and windows screenshots with the generate-screenshots github action

.changeset/dull-dolls-visit.md, apps/ledger-live-mobile/src/components/AccountSubHeader/AccountSubHeaderDrawer.tsx, apps/ledger-live-mobile/src/modals/Info.tsx
Center text on solana and atom modals
BEFORE
AFTER
- **JIRA or GitHub link**: [LIVE-9241]
- ...
---
[LIVE-9241]: https://ledgerhq.atlassian.net/browse/LIVE-9241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LLM - Center text on solana and atom modals

apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.tsx
Small refactor to avoid creating a fake manifest to use customHandlers
- ...
---
=> support: refactor fetching manifest

.changeset/khaki-tomatoes-sleep.md, apps/ledger-live-desktop/src/renderer/hooks/swap-migrations/useSwapLiveAppHook.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx
- send swapApiBase to swap-live-app
https://ledgerhq.atlassian.net/browse/LIVE-10991
- ...
---
=> [Feat/LIVE10991]: send swapApiBase to swap-live-app

.changeset/witty-fans-travel.md, libs/live-config/package.json, libs/live-config/src/LiveConfig.ts, libs/live-config/src/__tests__/LiveConfig.test.ts, libs/live-config/src/providers/index.ts, pnpm-lock.yaml
The schema for a config is shipped for a specific version of the live, however the values in remote (firebase or else) are not dependent on a specific version. So we make sure that the configuration is backward compatible so that if a field is renamed or deleted in firebase, Ledger Live can fallback on the default value.
- ...
---
=> [coin-config] Make getValueBykey backward compatible

apps/ledger-live-mobile/e2e/models/DeviceAction.ts, apps/ledger-live-mobile/e2e/models/manager/managerPage.ts, apps/ledger-live-mobile/e2e/specs/manager.spec.ts, apps/ledger-live-mobile/src/screens/Manager/AppsList/AppInstallButton.tsx, apps/ledger-live-mobile/src/screens/Manager/AppsList/AppRow.tsx, apps/ledger-live-mobile/src/screens/Manager/AppsList/AppUninstallButton.tsx, apps/ledger-live-mobile/src/screens/Manager/AppsList/AppUpdateAll.tsx, apps/ledger-live-mobile/src/screens/Manager/AppsList/AppUpdateButton.tsx, apps/ledger-live-mobile/src/screens/Manager/AppsScreen.tsx, apps/ledger-live-mobile/src/screens/Manager/Device/DeviceAppStorage.tsx, apps/ledger-live-mobile/src/screens/Manager/Device/DeviceName.tsx, apps/ledger-live-mobile/src/screens/Manager/Device/index.tsx
Improve Manager tests : 
-  Check device name
- Check device version
- Check device free/used storage
- Check device available/installed apps
- **JIRA or GitHub link**: [B2CQA-658](https://ledgerhq.atlassian.net/browse/B2CQA-658)
- Detox Manager tests
---
[B2CQA-658]: https://ledgerhq.atlassian.net/browse/B2CQA-658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [B2CQA-658] Detox : Improve Manager tests

.changeset/serious-goats-dream.md, libs/ledger-live-common/src/wallet-api/Exchange/server.ts
Fixed attributing subAccountId when not needed (it crashed XLM) 
Did we had an issue for that????
- ...
---
=> Fix XLM crash when swapping (Demo 0)

.changeset/violet-singers-suffer.md, libs/ledger-live-common/src/exchange/swap/utils/inferRatesError.ts
When using moonpay fixed the error management when not using the min amount or going over max amount
https://ledgerhq.atlassian.net/browse/LIVE-11204
- ...
---
=> fix(LIVE-11204): fix min and max amount error when using moonpay

apps/ledger-live-mobile/.unimportedrc.json, apps/ledger-live-mobile/__tests__/test-renderer.tsx, apps/ledger-live-mobile/src/newArch/features/Market/__integrations__/changeCurrency.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/Market/__integrations__/searchACoin.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/Market/__integrations__/setFavorites.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/Market/__integrations__/shared.tsx
Add 2 integration tests for the Market page:
- Add 2 coins into my favorites
- Change the currency from dollars to euros
- 
---
=> LLM - Add 2 integration tests for the Market page

.changeset/hip-beers-taste.md, libs/ledgerjs/packages/hw-app-btc/README.md, libs/ledgerjs/packages/hw-app-btc/src/Btc.ts, libs/ledgerjs/packages/hw-app-btc/src/BtcNew.ts, libs/ledgerjs/packages/hw-app-btc/src/BtcOld.ts, libs/ledgerjs/packages/hw-app-btc/src/bip32.ts, libs/ledgerjs/packages/hw-app-btc/src/constants.ts, libs/ledgerjs/packages/hw-app-btc/src/createTransaction.ts, libs/ledgerjs/packages/hw-app-btc/src/getWalletPublicKey.ts, libs/ledgerjs/packages/hw-app-btc/src/types.ts
=> Feat LIVE-10405 hwappbtc doc

.changeset/shy-ligers-poke.md, apps/ledger-live-desktop/src/renderer/screens/nft/Collections/Collections.tsx, apps/ledger-live-desktop/src/renderer/screens/nft/Gallery/Gallery.tsx, apps/ledger-live-mobile/src/screens/Nft/WalletNftGallery/index.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts, libs/live-nft-react/src/hooks/useNftGalleryFilter.test.tsx, libs/live-nft-react/src/hooks/useNftGalleryFilter.ts, libs/live-nft/src/api/simplehash.test.ts, libs/live-nft/src/api/simplehash.ts
Addition of a parameter to the simpleHahs FF so that the threshold can be managed manually and adapted according to user feedback.
https://github.com/LedgerHQ/ledger-live/assets/112866305/ab553d0b-1159-4e96-bbc7-b4105ea0c9f3
Url sent : `
https://simplehash.api.live.ledger.com/api/v0/nfts/owners_v2?chains=polygon&wallet_addresses=0x31BD1afBf1775A1FA55Ccb34B42AC482aA51fF6E&limit=50&filters=spam_score__lte=40`
- **JIRA or GitHub link**: [LIVE-11243] 
- ...
---
[LIVE-11243]: https://ledgerhq.atlassian.net/browse/LIVE-11243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SUPPORT]: Update Feature flag to handle threshold spam filter directly from FF

apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/WebviewErrorDrawer/index.tsx, libs/exchange-module/src/index.ts, libs/exchange-module/src/types.ts
fixed typing. Not a breaking change, hex or base64 string stringified to hex does not change the string.
- ...
---
=> chore: fix typing

.changeset/lazy-spiders-confess.md, apps/ledger-live-mobile/src/reducers/accounts.ts
In  **libs/ledger-live-common/src/wallet-api/logic.ts**, `getParentAccount` changed :
- [Before](https://github.com/LedgerHQ/ledger-live/commit/479c6e84ed97721b1d6176414a8dc6d23b267146), it was a function defined in the file as such
```js
function getParentAccount(account: AccountLike, fromAccounts: AccountLike[]): Account | undefined {
return isTokenAccount(account)
? (fromAccounts.find(a => a.id === account.parentId) as Account)
: undefined;
}
```
- Now, we import it from **libs/coin-framework/src/account/helpers.ts** where it's defined as such:
```js
export function getParentAccount(account: AccountLike, accounts: AccountLike[]): Account {
switch (account.type) {
case "Account":
return account;
case "TokenAccount":
case "ChildAccount": {
const parentAccount = accounts.find(a => a.id == …
```
=> accountScreenSelector handling parentAccount equaling account

.changeset/clean-parents-dress.md, .changeset/curly-walls-think.md, libs/ledgerjs/packages/cryptoassets/src/currencies.ts, libs/ui/packages/crypto-icons/src/svg/currency_linea.svg, libs/ui/packages/crypto-icons/src/svg/currency_linea_goerli.svg
Update Linea's icons
Update Linea goerli's color
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11218
- Icon change
- Testnet color change
---
=> [LIVE-11218] Support: Update Linea icons and colors

CODEOWNERS
Remove live-hub from apps i18n files ownership to ease code review
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11253
- ...
---
=> chore: distribute i18n files ownership

.changeset/chilly-avocados-juggle.md, .changeset/hip-fans-help.md, apps/ledger-live-desktop/src/renderer/components/DeviceAction/animations.ts, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/locales/en/common.json
Replace lottie to allow manager on nanoSP, nano and nanoX
Updated allow ledger errors wording
- **JIRA or GitHub link**: [LIVE-5919] [LIVE-5920](https://ledgerhq.atlassian.net/browse/LIVE-5920) 
- lottie animations to allow manager on install language & navigate to my ledger modified on nano, nanoSP and nanoX
---
[LIVE-5919]: https://ledgerhq.atlassian.net/browse/LIVE-5919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-5920]: https://ledgerhq.atlassian.net/browse/LIVE-5920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LIVE-5919][LIVE-5920] [LLM/LLD] Fix misalignment between "Allow manager" and "Allow secure connection" 

.changeset/cold-days-retire.md, apps/ledger-live-desktop/src/renderer/analytics/segment.ts
Tracking issue for pair scalability
- use globals for ff analytics identity flags
- use updateIdentify to set with rest of context
[- **JIRA or GitHub link**: ](https://ledgerhq.atlassian.net/browse/LIVE-11195)
- ... No QA, just MixPanel monitoring
---
=> [Bugfix/LIVE-11195]: Tracking issue for pair scalability

.changeset/chilly-bees-divide.md, apps/ledger-live-desktop/src/renderer/families/celo/AccountBodyHeader/Row.tsx, apps/ledger-live-desktop/src/renderer/families/cosmos/Delegation/Row.tsx, apps/ledger-live-desktop/src/renderer/families/elrond/components/Delegations/components/Delegation/index.tsx, apps/ledger-live-desktop/src/renderer/families/elrond/components/Unbondings/components/Unbonding/index.tsx, apps/ledger-live-desktop/src/renderer/families/near/Staking/Row.tsx, apps/ledger-live-desktop/src/renderer/families/polkadot/Nomination/Row.tsx, apps/ledger-live-desktop/src/renderer/families/solana/Delegation/Row.tsx
Staking discreet mode was not working well for :
- Cosmos
- Solana
- Celo
- Polkadot
- Elrond
- Near
Some others can be missing but don't have enough data to test all 
https://github.com/LedgerHQ/ledger-live/assets/112866305/6dfd1ae2-0b9f-4f36-8732-95c276044fc7
- **JIRA or GitHub link**: [LIVE-11292] 
- ...
---
[LIVE-11292]: https://ledgerhq.atlassian.net/browse/LIVE-11292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BUGFIX] : Staking discreet mode was not working well

.changeset/thirty-suits-allow.md, libs/ledger-live-common/src/exchange/swap/maybeTezosAccountUnrevealedAccount.ts
updated maybeTezosAccountUnrevealedAccount to a more consistent check
- ...
---
=> bugfix: better tezos reveal check

apps/ledger-live-mobile/src/newArch/features/Market/Navigator.tsx, apps/ledger-live-mobile/src/newArch/features/Market/WalletTabNavigator.tsx, apps/ledger-live-mobile/src/newArch/features/Market/__integrations__/shared.tsx, apps/ledger-live-mobile/src/newArch/features/Market/screens/MarketCurrencySelect/index.tsx, apps/ledger-live-mobile/src/newArch/features/Market/screens/MarketCurrencySelect/useMarketCurrencySelectViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Market/screens/MarketDetail/index.tsx, apps/ledger-live-mobile/src/newArch/features/Market/screens/MarketDetail/useMarketDetailViewModel.tsx, apps/ledger-live-mobile/src/newArch/features/Market/screens/MarketList/components/BottomSection/index.tsx, apps/ledger-live-mobile/src/newArch/features/Market/screens/MarketList/components/BottomSection/useBottomSectionViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Market/screens/MarketList/index.tsx, apps/ledger-live-mobile/src/newArch/features/Market/screens/MarketList/useMarketListViewModel.ts
POC to move from Container /Presentational pattern to hooks for the new Architecture
- ...
---
=> Move from Container/Presentational pattern to hooks

apps/ledger-live-desktop/src/renderer/hooks/useBraze.ts, apps/ledger-live-desktop/src/renderer/hooks/usePortfolioCards.tsx, apps/ledger-live-desktop/src/types/dynamicContent.ts
Fix ContentCard link + rename actions label to mainCta & secondaryCta
- ...
---
=> [LLD] - [BUGFIX] - [LIVE-10488] - Fix ContentCard link + rename actions label to mainCta & secondaryCta

.changeset/sweet-grapes-brush.md, libs/ledgerjs/packages/cryptoassets/src/currencies.ts
Current explorer is discontinued, replace it with pera wallet explorer
- **JIRA or GitHub link**: [https://ledgerhq.atlassian.net/browse/LIVE-11276](https://ledgerhq.atlassian.net/browse/LIVE-11276)
- ...
---
=> Update algorand explorer

.changeset/tame-cameras-smoke.md, apps/ledger-live-desktop/src/renderer/components/Alert.tsx
We want <a> elements to be styled with underline and cursor pointer.
After
- ...
---
=> Fix Release LLD - Underline a tags in Alert messages

apps/ledger-live-mobile/ios/LaunchScreen.storyboard
Add constraints on the launchscreen to make sure it's well centered on all iOS devices.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11327
- ...
---
=> Launchscreen constraints on iOS

apps/ledger-live-desktop/RELEASE_NOTES.md
Release notes 2.77.0
- **JIRA or GitHub link**: [notes](https://ledgerhq.atlassian.net/wiki/spaces/WALLETCO/pages/4508811382/LLD+2.77+Release+notes)
- ...
---
=> [LLD] Release notes 2.77.0

libs/live-countervalues/src/portfolio.ts
to prevent issues with icons, we will only consider top50 of supported coins.
- no impact in current develop since the feature is not active
---
=> feat(portfolio): filter market performance to only supported coins

.changeset/plenty-news-visit.md, apps/ledger-live-desktop/tests/specs/accounts/delegate.smoke.spec.ts
Skipping this e2e test as it is flaky and blocking PRs sometimes, approved by QA team
- **JIRA or GitHub link**: [https://ledgerhq.atlassian.net/browse/LIVE-11357](https://ledgerhq.atlassian.net/browse/LIVE-11357)
- ...
---
=> Skip delegate flow flaky test

.changeset/clean-pants-pretend.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.tsx
- Add language and themeId to moonpay redirection URL 
- Add themeId to moonpay redirection URL
- https://ledgerhq.atlassian.net/browse/LIVE-11123
- https://ledgerhq.atlassian.net/browse/LIVE-11307
- ...
---
=> [Bugfix/LIVE-11123]: add language and themeId to moonpay redirection URL 

apps/ledger-live-mobile/src/newArch/features/Market/screens/MarketList/useMarketListViewModel.ts, apps/ledger-live-mobile/src/screens/Market/index.tsx
This PR includes a fix that was preventing user's favorite currencies to not load when out of the `marketData` first page.
https://github.com/LedgerHQ/ledger-live/assets/25589782/3e3df451-d158-4b1c-b531-e4021b089722
- **JIRA or GitHub link**: [LIVE-10674] 
- ...
---
[LIVE-10674]: https://ledgerhq.atlassian.net/browse/LIVE-10674?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LLM] - [LIVE-10674] - Fix favorite currencies not loading when out of marketData first page

.changeset/pink-dragons-greet.md, apps/ledger-live-mobile/src/screens/Manager/Modals/UpdateAllModal.tsx
1. New icon in the available update(s) modal;
2. Change title from UPPERCASE to Pascal case of the first word;
3. Add `{old version} -> {new version}` indicator and align the component.
- ...
---
=> [LIVE-11235][LLM] Update available modal

apps/ledger-live-desktop/RELEASE_NOTES.md
The release notes currently contain text regarding build fixing that shouldn't be customer facing.
No need for a Jira ticket
- ...
---
=> chore: update release note files with proper content

.changeset/grumpy-lions-joke.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/AnalyticsOptInPrompt/Common.tsx, apps/ledger-live-mobile/src/screens/AnalyticsOptInPrompt/variantA/Details.tsx, apps/ledger-live-mobile/src/screens/AnalyticsOptInPrompt/variantA/Main.tsx, apps/ledger-live-mobile/src/screens/AnalyticsOptInPrompt/variantB/Details.tsx, apps/ledger-live-mobile/src/screens/AnalyticsOptInPrompt/variantB/Main.tsx
Updated copy and style of the analytics opt in prompt to match the latest version of the design : https://www.figma.com/file/x9nwU0JtDtyUIhAyBB2El8/Onboarding?type=design&node-id=12440-18936&mode=design&t=mcwNEFg1yKaTnXpk-0
Also added a ScrollView container in those screens to make sure it's displayed properly on small phone.
AFTER
- **JIRA or GitHub link**: [LIVE-11236]
- ...
---
[LIVE-11236]: https://ledgerhq.atlassian.net/browse/LIVE-11236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LLM - Update copy and style of the analytics opt in prompt

.changeset/fluffy-kings-hunt.md, apps/ledger-live-desktop/src/renderer/components/PlatformAppProviderWrapper.tsx, apps/ledger-live-mobile/src/PlatformAppProviderWrapper.tsx, libs/ledger-live-common/src/platform/filters.ts, libs/ledger-live-common/src/platform/providers/RemoteLiveAppProvider/index.tsx
Adding lang parameters to manifest-api call
- **JIRA or GitHub link**:  [JRA ticket](https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/623?selectedIssue=LIVE-9310), [Manifest-api PR](https://github.com/LedgerHQ/manifest-api/pull/411)
- ...
---
=> feat: add lang param to manifest call

.changeset/healthy-sloths-speak.md, libs/coin-evm/src/__tests__/unit/logic.unit.test.ts, libs/coin-evm/src/__tests__/unit/synchronization.unit.test.ts, libs/coin-evm/src/logic.ts, libs/coin-evm/src/synchronization.ts
Adding support for the `blacklistedTokenIds` parameter while doing an EVM synchronization, resulting in dropping both `TokenAccounts` and their `Operations`.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11229
- Removal of `TokenAccounts` when blacklisted
---
=> [LIVE-11229] Feature: Add support for blacklisted tokens in coin-evm

.changeset/breezy-masks-deny.md, libs/ledger-live-common/src/families/internet_computer/bridge.integration.test.ts, libs/ledger-live-common/src/families/internet_computer/bridge/bridgeHelpers/account.ts, libs/ledger-live-common/src/families/internet_computer/bridge/bridgeHelpers/icpRosetta/index.ts, libs/ledger-live-common/src/families/internet_computer/bridge/bridgeHelpers/icpRosetta/types.ts
Fix for account sync error on ICP caused by import of accounts on ledger live using accountId string. The address is now derived from pubkey using network call to rosetta node during sync.
- **JIRA or GitHub link**:https://ledgerhq.atlassian.net/browse/LIVE-10963
- ...
---
=> [Bugfix/ICP] Fix Account sync error for imported accounts 

apps/ledger-live-desktop/RELEASE_NOTES.md
Update release notes for 2.77.2 hotfix
- ...
---
=> update release notes hotfix

.changeset/brave-hounds-whisper.md, apps/ledger-live-desktop/src/renderer/components/LiveAppDrawer.tsx
fix https://ledgerhq.atlassian.net/browse/LIVE-11190
[- **JIRA or GitHub link**: ](https://ledgerhq.atlassian.net/browse/LIVE-11190)
- ...
---
=> bugfix: freeze when disable broadcast

.changeset/chilly-ducks-accept.md, libs/ledger-live-common/src/currencies/__snapshots__/sortByMarketcap.test.ts.snap, libs/ledger-live-common/src/families/tron/__snapshots__/bridge.integration.test.ts.snap, libs/ledger-live-common/src/families/tron/api/index.ts, libs/ledger-live-common/src/families/tron/bridge.integration.test.ts, libs/ledger-live-common/src/families/tron/bridge/js.ts, libs/ledgerjs/packages/cryptoassets/src/tokens.ts
Adapt the live to manage new lowercase identifiers
- Stellar: asset_code and issuer are related to real world data so I think we should not change the integration => uppercase on token import
- Tron : a bit more difficult as IDs were used as contract address, I had to update in a way that it is filtered on known tokens and we use the related contract address
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10852
- ...
---
=> Hotfix lowercase identifier fixes

.changeset/tough-hairs-retire.md, apps/ledger-live-desktop/src/renderer/families/cardano/AccountHeaderManageActions.ts, libs/ledger-live-common/src/families/cardano/logic.ts, libs/ledger-live-common/src/families/cardano/logic.unit.test.ts
fixed canStake method for Cardano 
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11098
- ...
---
=> fix canStake method

.changeset/healthy-otters-design.md, libs/ledger-live-common/src/config/sharedConfig.ts, libs/ledger-live-common/src/families/algorand/config.ts, libs/ledger-live-common/src/families/bitcoin/config.ts, libs/ledger-live-common/src/families/cardano/config.ts, libs/ledger-live-common/src/families/casper/config.ts, libs/ledger-live-common/src/families/celo/config.ts, libs/ledger-live-common/src/families/cosmos/chain/chain.unit.test.ts, libs/ledger-live-common/src/families/cosmos/config.ts, libs/ledger-live-common/src/families/crypto_org/config.ts, libs/ledger-live-common/src/families/elrond/config.ts, libs/ledger-live-common/src/families/evm/config.ts, libs/ledger-live-common/src/families/filecoin/config.ts, libs/ledger-live-common/src/families/hedera/config.ts, libs/ledger-live-common/src/families/internet_computer/config.ts, libs/ledger-live-common/src/families/near/config.ts, libs/ledger-live-common/src/families/polkadot/config.ts, libs/ledger-live-common/src/families/ripple/config.ts, libs/ledger-live-common/src/families/solana/config.ts, libs/ledger-live-common/src/families/stacks/config.ts, libs/ledger-live-common/src/families/stellar/config.ts, libs/ledger-live-common/src/families/tezos/config.ts, libs/ledger-live-common/src/families/tron/config.ts, libs/ledger-live-common/src/families/vechain/config.ts
We implemented coin-config to be able to remotely change the state of the app without depending on the release cylcle.
The first use of coin-config will be to indicate to user the current status of a coin. For now we support "active" and "under_maintenance" which are implemented in this PR.
- ...
---
=> [coin-config] Under maintenance status

libs/ledger-live-common/src/device-core/managerApi/use-cases/getLatestFirmwareForDevice.test.ts
Complete  unit tests for getLatestFirmwareForDevice refacto  
- **JIRA or GitHub link**: [DSDK-114]
- ...
---
[DSDK-114]: https://ledgerhq.atlassian.net/browse/DSDK-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DSDK-114][TU] Complete TU and verify GetLatestFirmwareUpdate refacto

apps/ledger-live-desktop/package.json, pnpm-lock.yaml
patch on latest Electron (still under 28.x, so it's a minor update)
it includes some crash fixes ( see https://github.com/electron/electron/releases/tag/v28.2.3 )
- LLD general non reg. low risk.
---
=> chore: update latest Electron libs patch

.changeset/stale-llamas-jam.md, apps/ledger-live-mobile/src/components/AccountCard.tsx
Fix of an issue with the tag "Native Segwit" for BitCoin with Android. On Import Accounts and Add new Account the tag was on two lines instead of one. 
|   | Before  | After |
|---|---|---|
| Android Add new account  | ![Before - Android Add New Account](https://github.com/LedgerHQ/ledger-live/assets/73439207/a565559a-4579-45c9-a5ee-dc3828fda839) |  ![After - Android Add New Account](https://github.com/LedgerHQ/ledger-live/assets/73439207/48ac57ee-8ef6-4074-b7cb-2e72d52d40e8) |
|  IOS Add new account |  ![No Problem - IOS Add New Account](https://github.com/LedgerHQ/ledger-live/assets/73439207/54580f90-5898-46c0-9267-5f2464e4c9cb)  |  ![No Problem - IOS Add New Account](https://github.com/LedgerHQ/ledger-live/assets/73439207/54580f90-5898-46c0-9267-5f2464e4c9cb)  |
|  Android Import …
=> fix(llm): accountCard tag on android no multi lines

.changeset/new-moles-hunt.md, apps/ledger-live-mobile/src/components/FabActions/hooks/useAssetActions.tsx, apps/ledger-live-mobile/src/components/FabActions/index.tsx, apps/ledger-live-mobile/src/families/celo/accountActions.tsx, apps/ledger-live-mobile/src/families/cosmos/accountActions.tsx, apps/ledger-live-mobile/src/families/elrond/accountActions.tsx, apps/ledger-live-mobile/src/families/evm/accountActions.tsx, apps/ledger-live-mobile/src/families/near/accountActions.tsx, apps/ledger-live-mobile/src/families/polkadot/accountActions.tsx, apps/ledger-live-mobile/src/families/solana/accountActions.tsx, apps/ledger-live-mobile/src/families/tezos/accountActions.tsx, apps/ledger-live-mobile/src/screens/Portfolio/PortfolioQuickActionsBar.tsx
Fix of the page field of the tracker event for the main ctas buy/swap/sell/stake/receive
Page was set to the default "portfolio_navigator". Now page is set with the route name. 
Clean up events that have been triggered twice
|  ![image](https://github.com/LedgerHQ/ledger-live/assets/73439207/81ade151-b7d4-4b94-858b-cb3639ec637f)|      ![image](https://github.com/LedgerHQ/ledger-live/assets/73439207/ab638b99-6e0c-40a2-8f4d-3d2c7b62b8b7) 
| ![image](https://github.com/LedgerHQ/ledger-live/assets/73439207/6bc61f3f-fe3f-46de-b441-31ceaa60b6e4)| ![image](https://github.com/LedgerHQ/ledger-live/assets/73439207/17c98ff2-4d86-4782-ab66-c7e4236cf9b1)
| ![image](https://github.com/LedgerHQ/ledger-live/assets/73439207/7b572e41-7973-4 …
=> fix(llm): button_clicked event on account wallet and market

libs/coin-framework/src/account/accountName.ts, libs/coin-framework/src/account/ordering.ts, libs/coin-framework/src/bridge/jsHelpers.ts
__BSR__
Remove `getNewAccountPlaceholderName` function.
- 
---
=> Coin fmk account placeholder

apps/ledger-live-mobile/src/components/CurrencyUnitValue.tsx, apps/ledger-live-mobile/src/context/Locale.tsx, apps/ledger-live-mobile/src/hooks/useSettings/index.tsx, apps/ledger-live-mobile/src/screens/Market/MarketDetail/MarketStats.tsx, apps/ledger-live-mobile/src/screens/Market/MarketDetail/index.tsx, apps/ledger-live-mobile/src/screens/Market/MarketRowItem.tsx, apps/ledger-live-mobile/src/screens/WalletCentricSections/MarketPrice.tsx
Fallback on default language when the language set in the store is not supported.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11549
- ...
---
=> Fallback on default language when the one set is not supported

apps/ledger-live-desktop/scripts/ci-lint.mjs
Remove `console.log` statement from desktop ci lint script.
- ...
---
=> chore: Remove ci lint script console.log

.changeset/sixty-suns-add.md, apps/ledger-live-desktop/src/renderer/hooks/swap-migrations/useSwapLiveAppHook.tsx
Quickfix to have the same url format as exchangeSDK (used by moonpay)
- ...
---
=> bugfix: adding swap to url

.changeset/healthy-tigers-pull.md, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
Create FF feature_lld_analytics_opt_in_prompt for lld in Firebase and define it in llc
- **JIRA or GitHub link**:  [LIVE-11531](https://ledgerhq.atlassian.net/browse/LIVE-11531)
- ...
---
[LIVE-11319]: https://ledgerhq.atlassian.net/browse/LIVE-11319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-11531]: https://ledgerhq.atlassian.net/browse/LIVE-11531?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(llc): Define FF for lld

apps/ledger-live-mobile/src/screens/Swap/Form/index.tsx
Random crash is produced when a new provider is selected by the user and the quotes are refreshed.
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/LIVE-11616
- ...
---
=> fix: fix random crash in swap llm

.changeset/two-teachers-drum.md, apps/ledger-live-mobile/src/context/LedgerStore.tsx, apps/ledger-live-mobile/src/newArch/features/Market/screens/MarketCurrencySelect/useMarketCurrencySelectViewModel.ts, apps/ledger-live-mobile/src/reducers/settings.ts, apps/ledger-live-mobile/src/screens/Market/MarketCurrencySelect.tsx, apps/ledger-live-mobile/src/screens/Settings/General/CountervalueSettings.tsx, libs/coin-framework/src/currencies/support.ts
Updated fiat currencies call and logic on LLM which prevented appropriate data being displayed
- **JIRA or GitHub link**:  [PROD-5432]
- ...
---
[PROD-5432]: https://ledgerhq.atlassian.net/browse/PROD-5432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(LLM/LLC): Fiat currencies fetch logic rework to fix issues

.changeset/moody-dodos-bow.md, libs/ledger-live-common/src/families/cosmos/config.ts
Update dydx lcd as previous one is dead
- **JIRA or GitHub link**: [https://ledgerhq.atlassian.net/browse/LIVE-11638](https://ledgerhq.atlassian.net/browse/LIVE-11638)
- ...
---
=> update dydx lcd

.changeset/itchy-moles-fold.md, libs/ledger-live-common/src/apps/filtering.ts
Add feature flag check in `libs/ledger-live-common/src/apps/filtering.ts` in order to align with front end.
- ...
---
=> [LIVE-11008][LLD][App Catalog] Show filter for applications supported in Live displays applications not supported by Live

.gitignore, .vscode/extensions.json
Add an extensions.json file containing a very minimal set of Visual Studio Code extensions recommendation: Eslint & Prettier extensions.
This will prompt an invitation to install the extensions to developers who didn't. It can be ignored (even though it really shouldn't).
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11377
- ...
---
=> chore: recommend visual studio code extensions

libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
remove referralProgramDesktopBanner dead (unused) code.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11584
- no changes for the user
---
=> chore: remove referralProgramDesktopBanner dead code

.changeset/nice-needles-bow.md, apps/ledger-live-desktop/src/renderer/screens/platform/v2/Catalog/Browse/Search.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/Platform/v2/Catalog/CatalogSection.tsx
add "All" string from categories, into app file for both LLM and LLD.
[JIRA TICKET](https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/623?selectedIssue=LIVE-11700)
- ...
---
=> feat: translate all filter

.changeset/proud-toes-work.md, apps/ledger-live-mobile/src/components/RootNavigator/WalletTabNavigator.tsx, apps/ledger-live-mobile/src/components/WalletTab/WalletTabHeader.tsx, apps/ledger-live-mobile/src/components/WalletTab/WalletTabNavigatorScrollManager.tsx, apps/ledger-live-mobile/src/components/WalletTab/WalletTabNavigatorTabBarDisabled.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
Remove walletNftGallery feature flag from codebase
- **JIRA or GitHub link**:[LIVE-11421] 
- ...
---
[LIVE-11421]: https://ledgerhq.atlassian.net/browse/LIVE-11421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SUPPORT] : Remove walletNftGallery feature flag from codebase

.changeset/fifty-emus-accept.md, libs/coin-evm/src/logic.ts, libs/coin-evm/src/synchronization.ts, libs/ledger-live-common/src/exchange/swap/getCompleteSwapHistory.ts
Fix swap history.
ERC20 does not appear in the history.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11285
- ...
---
=> Feat: fix swap history

.changeset/six-knives-occur.md, apps/ledger-live-mobile/e2e/specs/swap/dexSwap.spec.ts, apps/ledger-live-mobile/e2e/specs/swap/swap.spec.ts, apps/ledger-live-mobile/src/screens/Swap/Form/Max.tsx
disable max toggle button for main accounts
https://ledgerhq.atlassian.net/browse/LIVE-11707
- ...
---
=> [Bugfix/LIVE-11707]: disable max toggle button for from swap main accounts 

.changeset/thick-items-count.md, apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/hooks/useCommonLogic.tsx, apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/hooks/useDisplayOnPortfolio.tsx, apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/hooks/useVariantA.tsx, apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/screens/VariantA/Main/components/MainBody/components/TrackingInfoList/index.tsx, apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/screens/VariantA/Main/components/MainBody/components/index.tsx, apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/screens/VariantA/Main/components/MainBody/index.tsx, apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/screens/VariantA/Main/components/MainFooter/index.tsx, apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/screens/VariantA/Main/components/index.tsx, apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/screens/VariantA/Main/index.tsx, apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/screens/VariantA/ManagePreferences/components/Body/index.tsx, apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/screens/VariantA/ManagePreferences/components/Footer/index.tsx, apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/screens/VariantA/ManagePreferences/components/index.tsx, apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/screens/VariantA/ManagePreferences/index.tsx, apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/screens/VariantA/index.tsx, apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/screens/components/Footer/index.tsx, apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/screens/components/Header/index.tsx, apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/screens/components/RevokeInfoField/index.tsx, apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/screens/components/index.tsx, apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/screens/index.tsx, apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/types/AnalyticsOptInPromptNavigator.ts, apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/types/AnalyticsOptInromptNavigator.ts, apps/ledger-live-desktop/src/renderer/actions/settings.ts, apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/Welcome/index.tsx, apps/ledger-live-desktop/src/renderer/reducers/settings.ts, apps/ledger-live-desktop/src/renderer/screens/dashboard/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-desktop/tools/utils/index.js
Implementation of the logic and the ui of variant A for the FF privacy analytics. Add alias for the newArch named LLD/
To test the feature you must activate  `lldAnalyticsOptInPrompt` FF in the settings
Portfolio : 
https://github.com/LedgerHQ/ledger-live/assets/73439207/3e6225a8-3483-44cd-ae7d-b5b3f4d5c9b2
Welcome : 
https://github.com/LedgerHQ/ledger-live/assets/73439207/525f48f1-7345-49f2-822f-b616e16ac911
- **JIRA or GitHub link**:[LIVE-11532](https://ledgerhq.atlassian.net/browse/LIVE-11532)  
- ...
---
[LIVE-11532]: https://ledgerhq.atlassian.net/browse/LIVE-11532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(lld): implement variant A for FF feature_lld_analytics_opt_in_prompt

.changeset/large-needles-watch.md, libs/ledger-live-common/src/families/casper/api/types.ts, libs/ledger-live-common/src/families/casper/bridge/bridgeHelpers/txn.ts
Fix missing operations for Casper accounts. Some operations didn't make it to the final list because of unhandled cl_type. The `cl_type` can be either casper address or the public key. This is now handled and should result in all operations for an account to appear in the final list on lld/sync.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11175
- ...
---
=> [Bugfix/Casper] Missing operations in lld for certain accounts

.changeset/fluffy-carrots-help.md, libs/ledger-live-common/src/exchange/swap/utils/index.test.ts, libs/ledger-live-common/src/exchange/swap/utils/index.ts, tools/actions/turbo-affected/build/main.js, tools/actions/turborepo-gh-cache/build/main.js, tools/actions/turborepo-s3-cache/build/main.js
Update text from Moonpay to MoonPay
JIRA or GitHub link: https://ledgerhq.atlassian.net/browse/LIVE-11502
- ...
---
=> feat(LIVE-11502): update text Moonpay to MoonPay

.changeset/great-dots-tease.md, apps/ledger-live-desktop/static/i18n/en/app.json, libs/ledger-live-common/src/exchange/swap/api/v5/fetchRates.ts, libs/ledger-live-common/src/exchange/swap/types.ts
* fix(LIVE-10993): remove backend intended responses
* fix(LIVE-10993): remove import
* fix(LIVE-10993): add changeset
* fix(LIVE-10993): add error 306
* fix(LIVE-10993): add message to min max error DEX
https://github.com/LedgerHQ/ledger-live/pull/6233 
- ...
---
=> CHERRYPICK Bugfix/remove backend errors (#6233)

.changeset/selfish-carrots-thank.md, apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/CompleteExchange/Body.tsx, libs/exchange-module/src/index.ts, libs/exchange-module/src/types.ts, libs/ledger-live-common/src/exchange/error.ts, libs/ledger-live-common/src/exchange/index.ts, libs/ledger-live-common/src/exchange/platform/completeExchange.ts, libs/ledger-live-common/src/exchange/platform/startExchange.ts, libs/ledger-live-common/src/exchange/platform/transfer/completeExchange.ts, libs/ledger-live-common/src/exchange/providers/fund.ts, libs/ledger-live-common/src/exchange/providers/index.ts, libs/ledger-live-common/src/exchange/providers/sell.ts, libs/ledger-live-common/src/exchange/providers/swap.ts, libs/ledger-live-common/src/exchange/swap/completeExchange.ts, libs/ledger-live-common/src/exchange/swap/getExchangeRates.ts, libs/ledger-live-common/src/exchange/swap/index.ts, libs/ledger-live-common/src/exchange/swap/initSwap.ts, libs/ledger-live-common/src/exchange/swap/utils/index.ts, libs/ledger-live-common/src/wallet-api/Exchange/error.ts, libs/ledger-live-common/src/wallet-api/Exchange/server.test.ts, libs/ledger-live-common/src/wallet-api/Exchange/server.ts, libs/ledgerjs/packages/hw-app-exchange/src/Exchange.integ.test.ts
* Update "Platform" CompleteSell function to Swap last evolution.
* Put together exchange "Providers" in a dedicated directory.
* Set `hw-app-exchange` error converter function in a share file between Swap and Sell&Fund
* Update startExchange in customHandler in order to require `providerId` in Sell
* Remove "*_NG" exchange type, as it will be handled entirely by Ledger Live code base
- **JIRA or GitHub link**: [LIVE-11570] [LIVE-11679]
- ...
---
[LIVE-9022]: https://ledgerhq.atlassian.net/browse/LIVE-9022?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-11570]: https://ledgerhq.atlassian.net/browse/LIVE-11570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlh …
=> Add SELL_NG

.github/workflows/test-desktop-external.yml, .github/workflows/test-desktop.yml
Update test-desktop-external workflow (remove :smoke tests and make sure it's iso with test-desktop workflow)
- ...
---
=> chore: update test desktop external

.github/workflows/account-migration.yml, libs/ledger-live-common/src/__tests__/migration/account-migration.ts
- Only trigger account migration job manually
- Check if you could correctly parse inputFile or not
- ...
---
=> Bugfix - Account migration job only run when triggered manually

apps/ledger-live-desktop/src/renderer/screens/account/index.tsx, apps/ledger-live-desktop/src/renderer/screens/nft/Collectibles/Sats.tsx, apps/ledger-live-desktop/src/renderer/screens/nft/Collectibles/index.tsx
=> Sats first look + container grid

apps/ledger-live-desktop/src/newArch/Ordinals/components/Header/Categories/index.tsx, apps/ledger-live-desktop/src/newArch/Ordinals/components/Header/Layouts/index.tsx, apps/ledger-live-desktop/src/newArch/Ordinals/components/Header/index.tsx, apps/ledger-live-desktop/src/newArch/Ordinals/components/Header/utils.tsx, apps/ledger-live-desktop/src/renderer/screens/account/index.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
Add FF + new Display
- ...
---
=> Add FF + new Display

.changeset/silver-dolls-punch.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.tsx
untick swap on reverse swap
[- **JIRA or GitHub link**: ](https://ledgerhq.atlassian.net/browse/LIVE-11085)
- ...
---
=> bugfix: untick max on reverse swap

.changeset/sour-onions-relate.md, apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/hooks/useVariantA.tsx, apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/hooks/useVariantB.tsx, apps/ledger-live-desktop/src/renderer/actions/settings.ts, apps/ledger-live-desktop/src/renderer/analytics/segment.ts, apps/ledger-live-desktop/src/renderer/reducers/settings.ts, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/ShareAnalyticsButton.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/ShareAnalyticsButtonFF.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/SharePersonalRecoButtonFF.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
Change general Settings Toggles. If the FF is enabled we will display the two toggles : Analytics and Personalized Experience. If not we will display the initial toggle. Add also the track methods to track the state of toggles.
Also correct the wording for the store : setSharePersonalizedRecomm`a`ndations => setSharePersonalizedRecomm`e`ndations and sharePersonalizedRecomm`a`ndationsSelector => sharePersonalizedRecomm`e`ndationsSelector
Demo :
https://github.com/LedgerHQ/ledger-live/assets/73439207/3f2bd169-8874-4e78-a479-c02552372f23
- **JIRA or GitHub link**: [LIVE-11535](https://ledgerhq.atlassian.net/browse/LIVE-11535) 
- ...
---
[LIVE-11535]: …
=> feat(lld): change general settings toggles to fit with FF

apps/ledger-live-desktop/src/renderer/actions/dynamicContent.ts, apps/ledger-live-desktop/src/renderer/components/Carousel/Slide.tsx, apps/ledger-live-desktop/src/renderer/components/Carousel/TimeBasedProgressBar.tsx, apps/ledger-live-desktop/src/renderer/components/Carousel/helpers.tsx, apps/ledger-live-desktop/src/renderer/components/Carousel/index.tsx, apps/ledger-live-desktop/src/renderer/components/Page.tsx, apps/ledger-live-desktop/src/renderer/hooks/useActionCards.tsx, apps/ledger-live-desktop/src/renderer/hooks/useBraze.ts, apps/ledger-live-desktop/src/renderer/reducers/dynamicContent.ts, apps/ledger-live-desktop/src/renderer/screens/dashboard/ActionContentCards.tsx, apps/ledger-live-desktop/src/renderer/screens/dashboard/index.tsx, apps/ledger-live-desktop/src/types/dynamicContent.ts, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
This PR:
- Renames the current `portfolioCards` to `actionCards`
- Revert and re introduce the old Carousel and `portfolioCards`.
- Changes `lldPortfolioCarousel` FF to `lldActionCarousel`.
On Braze:
- New location: `action` which now is the action cards.
- The `portfolio` location has been rolled back to its previous use.
https://github.com/LedgerHQ/ledger-live/assets/17146928/5bd6d261-8d59-4c3c-adab-92101704bac7
- **JIRA or GitHub link**: [LIVE-11579] 
- ...
---
[LIVE-11579]: https://ledgerhq.atlassian.net/browse/LIVE-11579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LLD] - [LIVE-11579] - Revert old Carousel / Portfolio content cards + add action cards

.changeset/happy-colts-pump.md, apps/ledger-live-mobile/src/screens/Discover/index.tsx, apps/ledger-live-mobile/src/utils/urls.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
Remove referralProgramDiscoverCard feature flag
- **JIRA or GitHub link**: [LIVE-11581] 
- ...
---
[LIVE-11581]: https://ledgerhq.atlassian.net/browse/LIVE-11581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LLD] - [LIVE-11581] - Remove referralProgramDiscoverCard feature flag

.changeset/gentle-coins-press.md, apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/steps/02-step-flash-mcu.tsx, libs/ledger-live-common/src/__tests__/hw/getDeviceInfo.ts, libs/ledger-live-common/src/hw/firmwareUpdate-main.ts, libs/ledger-live-common/src/hw/flash.ts, libs/ledger-live-common/src/hw/getDeviceInfo.ts
=> [LIVE-11378] Stax mcu upgrade failure

libs/coin-modules/coin-bitcoin/src/wallet-btc/storage/index.ts
Fix serialization.
Source: during bitcoin modularization `coin-bitcoin/src/wallet-btc/crypto/base.ts` has its types improved. However this had a consequence on `coin-bitcoin/src/wallet-btc/storage/index.ts` which functions like `exportSync` had its signature returning `Promises` instead of straight `string`.
To check:
- **JIRA or GitHub link**: [LIVE-11817]
- ...
---
[LIVE-11817]: https://ledgerhq.atlassian.net/browse/LIVE-11817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [BTC] avoid serializing promise instead of string for addresses

.changeset/forty-terms-rule.md
Changeset for LLM to bump old version 
- ...
---
=> Changeset for LLM

.changeset/lovely-adults-hide.md, apps/ledger-live-mobile/src/components/FabActions/index.tsx, apps/ledger-live-mobile/src/components/Stake/useStakingDrawer.tsx, apps/ledger-live-mobile/src/families/tron/AccountBalanceSummaryFooter.tsx, apps/ledger-live-mobile/src/families/tron/Votes/Header.tsx, apps/ledger-live-mobile/src/families/tron/Votes/index.tsx, apps/ledger-live-mobile/src/families/tron/accountActions.tsx
This PR introduces Tron staking functionality to Ledger Live Mobile users by leveraging deep links to redirect users to the relevant staking flows within the Stakekit Ledger Live app
- The "Stake" button on the Tron account screen now redirects users to the "Earn" screen in the Stakekit Live app, with Tron pre-selected.
- Added deep link support for "Manage Vote" and "Claim Reward" actions, directing users to the corresponding sections within the Stakekit Live app.
- Removed the TronStakingDisable alert.
- Removed the Freeze, Unfreeze, and Vote from the Account actions, as StakeKit handles these actions under the hood.
Important: tron needs to be added to the stakePrograms feature flag
https://github.com/LedgerHQ/ledger-live/assets/22058587/df8cba8e-0df1-4fd7-b795-34ac1fbea46d …
=> Feat(LLM): Enable Tron 2.0 Staking in Ledger Live Mobile via Stakekit Live App

.changeset/serious-shrimps-visit.md, apps/ledger-live-mobile/src/families/tezos/operationDetails.ts
Replace tezos op What's this url as previous one is discontinued
- **JIRA or GitHub link**: [https://ledgerhq.atlassian.net/browse/LIVE-10232](https://ledgerhq.atlassian.net/browse/LIVE-10232)
- ...
---
=> [Tezos] Update support url op whats this

.changeset/chilled-radios-drive.md, apps/ledger-live-mobile/src/screens/Portfolio/PortfolioAssets.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
Remove llmWalletQuickActions Feature Flag
- ...
---
=> Remove llmWalletQuickActions FF

.github/pull_request_template.md
- no impact for users
This is a small evolution proposal of our PR template in order to highlight a bit more the mandatory Checklist that a PR needs to document (**not necessarily check it all!** but actually document why one can't be checked)
in fact, looking at the 10 last PRs merged, 60% of them didn't check at all any of the checklist nor documented why it couldn't. so we need some sort of refresh of this idea.
On top of this, I can see that the ability to check the PR reviewers points are not used at all, so we remove the checkability of these, we just keep it as a static guide for reviewers.
- **JIRA or GitHub link**: none 
--- …
=> [PR Template] Improve Checklist usability

.changeset/chatty-walls-prove.md, apps/cli/src/commands/ptx/swap.ts, apps/ledger-live-desktop/src/renderer/components/DeviceAction/index.tsx, apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx, apps/ledger-live-desktop/src/renderer/components/LiveAppDrawer.tsx, apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/CompleteExchange/Body.tsx, apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/CompleteExchange/BodyContent.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/ExchangeDrawer/SwapAction.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/ExchangeDrawer/index.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/ExchangeDeveloperMode.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/index.tsx, apps/ledger-live-mobile/src/components/DeviceAction/index.tsx, apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx, apps/ledger-live-mobile/src/components/RootNavigator/types/PlatformExchangeNavigator.ts, apps/ledger-live-mobile/src/screens/Swap/Form/Modal/Confirmation.tsx, libs/ledger-live-common/src/exchange/platform/types.ts, libs/ledger-live-common/src/exchange/providers/index.ts, libs/ledger-live-common/src/exchange/swap/addToSwapHistory.ts, libs/ledger-live-common/src/exchange/swap/getUpdateAccountWithUpdaterParams.ts, libs/ledger-live-common/src/exchange/swap/mock.ts, libs/ledger-live-common/src/exchange/swap/types.ts, libs/ledger-live-common/src/exchange/types.ts, libs/ledger-live-common/src/hw/actions/completeExchange.ts, libs/ledger-live-common/src/hw/actions/initSwap.ts, libs/ledger-live-common/src/hw/actions/startExchange.ts, libs/ledger-live-common/src/platform/logic.ts, libs/ledger-live-common/src/wallet-api/Exchange/server.ts, libs/ledger-live-common/src/wallet-api/logic.ts
1. Add an input in the "developer" tab of the settings screen to:
* set `MOCK_EXCHANGE_TEST_CONFIG` to true
* send provider info in a `ExchangeProviderNameAndSignature` raw format
2. Dedup `Exchange` and `ExchangeRaw` type in LLC `exchange` directory:
* Use dedicate type `ExchangeSwap` when required
* Use of `Exchange` type (which is a union type)
Need to be checked:
- **JIRA or GitHub link**: [LIVE-11829]
- ...
---
[LIVE-11829]: https://ledgerhq.atlassian.net/browse/LIVE-11829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [Exchange] send debug provider info

apps/ledger-live-mobile/README.md
- ...
Small fix here - the link to the E2E README is broken, so this PR removes it.
---
=> docs: remove broken link in LLM README

.changeset/violet-cycles-press.md, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- No, contains only code removal
- No impact
Cleanup references to a FF already removed
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11575
---
=> Cleanup references to protectServicesDiscoverDesktop Feature Flag

.changeset/large-socks-shave.md, apps/ledger-live-mobile/src/locales/en/common.json
Updated Large Movers description to mention all the cryptos supported instead of just BTC and ETH
| ![image (1)](https://github.com/LedgerHQ/ledger-live/assets/17146928/72339078-3b79-4d3f-9c7f-a4783a17a4a0) | ![image](https://github.com/LedgerHQ/ledger-live/assets/17146928/c2741bd4-8117-49fa-baf5-23709a68862f) |
- ...
---
=> LLM - Updated Large Movers description

pnpm-lock.yaml, tools/github-bot/package.json
Bump some dependencies on the github-bot to fix unresolved transitive deps
- ...
--- …
=> chore(bot): bump deps

pnpm-lock.yaml, tools/github-bot/api/github/webhooks/index.ts, tools/github-bot/package.json, tools/github-bot/src/commands/full-suite.ts, tools/github-bot/src/features/lintCommits/index.ts, tools/github-bot/src/features/orchestrator/index.ts, tools/github-bot/src/features/orchestrator/tools.ts, tools/github-bot/src/tools/monitorWorkflow.ts, tools/github-bot/tsconfig.json
Fix github-bot missing dependency
- ...
--- …
=> chore(bot): fix github-bot

.changeset/mean-garlics-happen.md, libs/ledgerjs/packages/hw-app-exchange/src/SwapUtils.test.ts, libs/ledgerjs/packages/hw-app-exchange/src/SwapUtils.ts
- ...
Support base64 decodeProtobuf
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11860
---
=> fix: support base64 and fix prod llm decodePayloadProtobuf

.changeset/quick-socks-run.md, CODEOWNERS, apps/ledger-live-mobile/src/components/CustomImage/useCenteredImage/getCenteredCropParams.test.ts, apps/ledger-live-mobile/src/components/CustomImage/useCenteredImage/getCenteredCropParams.ts, apps/ledger-live-mobile/src/components/CustomImage/useCenteredImage/getRescaledDimensions.test.ts, apps/ledger-live-mobile/src/components/CustomImage/useCenteredImage/getRescaledDimensions.ts, apps/ledger-live-mobile/src/components/CustomImage/useCenteredImage/index.ts
- LLM custom lock screen preview screen
There were some errors in the implementation of the picture rescaling, before the cropping, which led to bad cropping parameters, leading to an (uncaught) native crash of `expo-image-manipulator`.
The implementation is fixed and unit tests have been added.
Here's the fixed result with the picture that was crashing in the reported issue:
- **JIRA or GitHub link**: [LIVE-11886] 
--- …
=> [LIVE-11886][LLM] Custom lock screen preview crashing with some pictures

.changeset/fifty-emus-itch.md, .changeset/strong-moose-report.md, apps/ledger-live-mobile/src/contentCards/cards/horizontal/index.tsx, apps/ledger-live-mobile/src/contentCards/cards/types.tsx, apps/ledger-live-mobile/src/contentCards/layouts/carousel/index.tsx, apps/ledger-live-mobile/src/contentCards/layouts/carousel/pagination/index.tsx, apps/ledger-live-mobile/src/contentCards/layouts/grid/index.tsx, apps/ledger-live-mobile/src/contentCards/layouts/grid/utils.tsx, apps/ledger-live-mobile/src/dynamicContent/ContentCardsCategory/Layout.tsx, apps/ledger-live-mobile/src/dynamicContent/types.ts, apps/ledger-live-mobile/src/dynamicContent/utils.tsx
This PR regroups those two tickets : [LIVE-11392](https://ledgerhq.atlassian.net/browse/LIVE-11392) & [LIVE-11414](https://ledgerhq.atlassian.net/browse/LIVE-11414)
You can check the following PR what has been merged in here : https://github.com/LedgerHQ/ledger-live/pull/6533
- LLM
- Braze
Fix pagination bug for carousel generated from Braze.
It will jumps to the last indicator with small actions cards
|  https://github.com/LedgerHQ/ledger-live/assets/73439207/110055f7-8876-48ef-8098-0a4405fb0727|  https://github.com/LedgerHQ/ledger-live/assets/73439207/8226cc39-9ead-4309-9931-a0c15a2bb81a
|<img width="465" alt="image" src="https://github.com/LedgerHQ/ledger-live/assets/73439207/32dc4c74-efc7-4b87-9be7-1ae15828d7f4">|![ima …
=> fix(llm): fix carousel pagination for content cards

.changeset/slimy-students-jam.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/Settings/Help/LedgerSupportRow.tsx, apps/ledger-live-mobile/src/screens/Settings/Resources.tsx, apps/ledger-live-mobile/src/utils/urls.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
Added the `llmChatbotSupport` feature flag to redirect to the chabot instead of the faq when enabled
The buttons impacted for now are the `Ledger Support` button in the `Help & Support` drawer and the `Ledger Support` button in the Help settings screen.
https://github.com/LedgerHQ/ledger-live/assets/17146928/e3557e95-4015-4bc4-927a-131a514ff9ba
- **JIRA or GitHub link**: [LIVE-11840] 
- ...
---
[LIVE-11840]: https://ledgerhq.atlassian.net/browse/LIVE-11840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LLM - Help buttons redirect to chatbot instead of faq

.github/workflows/generate-screenshots.yml, tools/github-bot/src/commands/tools.ts
Update workflows and bot commands to make sure generate-screenshots correctly pushes to the branch (either remote or not)
- ...
--- …
=> chore(bot): fix commands

libs/coin-modules/coin-bitcoin/src/hw-signMessage.test.ts
- ...
Adding a small unit test to valid the desired behaviour of bitcoin signMessage.
- **JIRA or GitHub link**: [LIVE-11903]
---
[LIVE-11903]: https://ledgerhq.atlassian.net/browse/LIVE-11903?atlOrigin=eyJpIjoiNWRkNT …
=> Small test on bitcoin signMessage

apps/ledger-live-mobile/e2e/models/manager/managerPage.ts, apps/ledger-live-mobile/e2e/models/onboarding/onboardingSteps.ts, apps/ledger-live-mobile/e2e/specs/deeplinks.spec.ts, apps/ledger-live-mobile/e2e/specs/onboarding.spec.ts, apps/ledger-live-mobile/src/components/BleDevicePairingFlow/BleDevicePairing.tsx, apps/ledger-live-mobile/src/components/SelectDevice2/index.tsx
- LLM E2E test (deeplinks and onboarding)
_Fixing Detox tests broken by the new device selection flow_
- **JIRA or GitHub link**: [LIVE-11839](https://ledgerhq.atlassian.net/browse/LIVE-11839)
---
[LIVE-11839]: …
=> [LIVE-11839][Detox] Fix tests with the new device selection flow

.changeset/rotten-students-breathe.md, apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/Disclaimer.tsx, apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/index.tsx
- ...
* Update the display in disclaimer page for firmware update.
- **JIRA or GitHub link**: [LIVE-10495]
---
[LIVE-10495]: https://ledgerhq.atlassian.net/browse/LIVE-10495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …
=> [LLD] Wrong layout and text alignment for Stax OS update

.changeset/violet-buttons-glow.md, apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/CompleteExchange/Body.tsx
- ...
To be used alongside a removal of sending swap live apps errors to LL. ⚠️ TODO
Fixes moonpay not receiving errors (and demo0 by extension)
[- **JIRA or GitHub link**: ](https://ledgerhq.atlassian.net/browse/LIVE-11818)
--- …
=> bugfix: send swap error to live apps

.changeset/itchy-rivers-flow.md, apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/CompleteExchange/Body.tsx, libs/ledgerjs/packages/errors/src/index.ts, tools/actions/build-checks/build/main.js, tools/actions/desktop-report-build/build/main.js, tools/actions/get-workflow-artifacts-id/build/main.js, tools/actions/turbo-affected/build/main.js
- ...
- Implement DisabledTransactionBroadcastError to handle a specific development scenario where transaction broadcasts are disabled.
- This error is designed exclusively for development environments, facilitating the invocation of the `canceled` API in the exchangeSDK without triggering any UI error notifications in Ledger Live (LL).
- When the `DISABLE_TRANSACTION_BROADCAST` flag is set to true, the `onBroadcastSuccess` method triggers the `onCancel` function with DisabledTransactionBroadcastError.
- This integration ensures that the exchange-sdk's `catch` logic activates, calling the `canceled` API. Subsequently, though the error is thrown, it is strategically caught within the `swap-live-app`.
- Consequently, the UI remains unaffected by this error; no error state or notification …
=> fix: do not throw UserRefusedOnDevice disabled_transaction_boradcast

pnpm-lock.yaml
- ...
Fix lockfile by running `pnpm install --no-frozen-lockfile`.
---
=> fix: pnpm lockfile

.changeset/breezy-tomatoes-occur.md, libs/ledger-live-common/src/exchange/swap/webApp/utils.ts, pnpm-lock.yaml
- ...
Moonpay transaction are failing because we're sending incorrect gasLimit, This PR removes the gasLimit from the customFee, as custom fees should only target the price of the gas, not the amount which is not adjustable for a given transaction. 
[- **JIRA or GitHub link**: 
](https://ledgerhq.atlassian.net/browse/LIVE-11976)
---
- …
=> bugfix: stop sending incorrect gasLimit

.changeset/happy-gorillas-melt.md, apps/ledger-live-mobile/src/locales/en/common.json
- translations
Change add account wording on LLM
| ![image](https://github.com/LedgerHQ/ledger-live/assets/73439207/988dd844-b0de-40f9-956b-fed7c402de42)|![image](https://github.com/LedgerHQ/ledger-live/assets/73439207/9830c1b6-ef10-4961-a9e9-a60aa699c470) |
- **JIRA or GitHub link**:[LIVE-11543](https://ledgerhq.atlassian.net/browse/LIVE-11543) 
--- …
=> fix(llm): change add account wording

tools/native-modules-tools/index.js
- ...
Replace the async copy by the sync version of it in our build tools for LLD
---
=> chore: fix lld losing ref to Electron.Framework

.changeset/ninety-falcons-hope.md, apps/ledger-live-mobile/src/locales/tr/common.json
- ...
Update traduction on swap in TR.
- **JIRA or GitHub link**: [LIVE-10591] 
---
[LIVE-10591]: https://ledgerhq.atlassian.net/browse/LIVE-10591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoi …
=> [LLM] - [LIVE-10591] - Update traduction on swap in TR

.github/workflows/bot-portfolio-report.yml, .github/workflows/bot-transfer.yml, .github/workflows/build-desktop-external.yml, .github/workflows/build-desktop.yml, .github/workflows/build-mobile-external.yml, .github/workflows/build-mobile.yml, .github/workflows/commitlint.yml, .github/workflows/gate.yml, .github/workflows/generate-screenshots.yml, .github/workflows/regen-doc.yml, .github/workflows/regen-pods.yml, .github/workflows/test-bridge-pr.yml, .github/workflows/test-desktop-external.yml, .github/workflows/test-desktop.yml, .github/workflows/test-integration-pr.yml, .github/workflows/test-integration.yml, .github/workflows/test-mobile-e2e.yml, .github/workflows/test-mobile.yml, .github/workflows/test.yml, tools/actions/composites/bot/action.yml, tools/actions/composites/update-snapshots-desktop/action.yml, tools/actions/composites/upload-allure-report/action.yml
- workflows
Updates `action/download-artifact` and `actions/upload-artifact` to v4
It brings faster and more reliable transfer, immutable uploads...
It also brings some api changes due to immutable upload, that have been addressed in the PR as well.
https://github.com/actions/download-artifact/blob/main/docs/MIGRATION.md
--- …
=> chore: update upload/download actions to v4

.changeset/forty-elephants-jump.md, apps/ledger-live-mobile/src/screens/MyLedgerDevice/AppsList/AppRow.tsx, apps/ledger-live-mobile/src/screens/MyLedgerDevice/AppsScreen.tsx
- ...
- Trim search keyword to ensure that auto complete in mobile phone can find the correct answer.
- **JIRA or GitHub link**: [LIVE-8183]
---
[LIVE-8183]: …
=> [LIVE-8183]LLM - MyLedger: hidden apps when using the search bar in the manager because of trimming

.changeset/serious-coins-dance.md, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/index.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts
Disable storyly feature flag in default settings
- ...
- **JIRA or GitHub link**: No ticket 
---
=> [LLD] - [] - Disable storyly feature flag in default settings

.changeset/moody-adults-roll.md, apps/ledger-live-desktop/src/renderer/components/CustomImage/NFTGallerySelector.tsx
- ...
This PR remove the spams NFT in custom lock screen on LLD.
**Before:**
**After:**
- **JIRA or GitHub link**: [LIVE-11842] 
---
[LIVE-11842]: https://ledgerhq.atlassian.net/browse/LIVE-11842?atlOrigin=eyJpIjoiNWR …
=> [LLD] - [LIVE-11842] - Remove the spams NFT in custom lock screen on LLD

.changeset/yellow-parents-dance.md, libs/ledger-live-common/src/families/cosmos/api/Cosmos.ts, libs/ledger-live-common/src/families/cosmos/api/Cosmos.unit.test.ts, libs/ledger-live-common/src/families/cosmos/api/types.ts
- ...
Original PR https://github.com/LedgerHQ/ledger-live/pull/6652 + some changes (will be cherry picked in develop)
- **JIRA or GitHub link**: [https://ledgerhq.atlassian.net/browse/LIVE-12100](https://ledgerhq.atlassian.net/browse/LIVE-12100)
--- …
=> [LIVE-12100] Fix cosmos redelegations

apps/ledger-live-desktop/src/renderer/components/CustomImage/NFTGallerySelector.tsx
- ...
Fix LLD inconsistency in NFTGallerySelector.
---
=> [LLD] - [] - Fix LLD inconsistency in NFTGallerySelector

.changeset/strange-spoons-dream.md, apps/ledger-live-mobile/src/screens/CustomImage/NFTGallerySelector.tsx
- ...
This PR removes the spams NFT in custom lock screen on LLM.
**Before:**
**After:**
- **JIRA or GitHub link**: [LIVE-11843] 
---
[LIVE-11843]: https://ledgerhq.atlassian.net/browse/LIVE-11843?atlOrigin=eyJpIjoiNW …
=> [LLM] - [LIVE-11843] - Remove the spams NFT in custom lock screen on LLM

.changeset/thin-ducks-teach.md, apps/ledger-live-desktop/src/renderer/components/PostOnboardingHub/PostOnboardingActionRow.tsx, apps/ledger-live-desktop/src/renderer/components/PostOnboardingHub/PostOnboardingHubBanner.tsx, apps/ledger-live-desktop/src/renderer/components/PostOnboardingHub/PostOnboardingHubContent.tsx, apps/ledger-live-desktop/src/renderer/components/PostOnboardingHub/PostOnboardingMockAction.tsx, apps/ledger-live-desktop/src/renderer/components/PostOnboardingHub/logic/index.tsx, apps/ledger-live-desktop/src/renderer/components/PostOnboardingHub/logic/useCompleteAction.ts, apps/ledger-live-desktop/src/renderer/components/PostOnboardingScreen/index.tsx, apps/ledger-live-desktop/src/renderer/modals/Receive/steps/StepReceiveFunds.tsx, apps/ledger-live-desktop/src/renderer/screens/customImage/index.tsx, apps/ledger-live-desktop/src/renderer/screens/dashboard/index.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Experimental/PostOnboardingHubTester.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-desktop/tests/models/PostOnboarding.ts, libs/ledgerjs/packages/types-live/README.md, libs/ledgerjs/packages/types-live/src/postOnboarding.ts
Added europa support to post onboarding
Updated post onboarding copy and analytics
Added an entry point to recover in the post onboarding
- **JIRA or GitHub link**: [LIVE-11936]
---
[LIVE-11936]: …
=> ✨ LLD - Europa PostOnboarding

.changeset/spotty-tigers-play.md, apps/ledger-live-mobile/e2e/specs/swap/swap.spec.ts, apps/ledger-live-mobile/src/screens/Swap/Form/Max.tsx, apps/ledger-live-mobile/src/screens/Swap/Form/index.tsx
- ...
- Remove max toggle button from swap LLM
- Add detox test check
https://ledgerhq.atlassian.net/browse/LIVE-12088
---
=> [Feat/LIVE-12088]: remove max toggle button from swap LLM

.changeset/gorgeous-cherries-eat.md, .changeset/grumpy-pillows-think.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/History/OperationRow.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- ...
Fix swap history status translations
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/LIVE-12122
---
=> fix: swap history status translations

.changeset/four-yaks-float.md, apps/ledger-live-mobile/src/screens/Account/NftCollectionsList.tsx, apps/ledger-live-mobile/src/screens/Nft/NftGallery/index.tsx, apps/ledger-live-mobile/src/screens/SendFunds/01b-SelectCollection.tsx
- ...
Remove NFTs Spams in AccountPage in LLM
https://github.com/LedgerHQ/ledger-live/assets/112866305/f090fa59-0778-4a4e-a6ff-5ad7e1b998b4
---
=> [FEAT] - [LLM] - Remove Spams NFT in Accounts Page

.changeset/eleven-shoes-turn.md, apps/ledger-live-mobile/src/utils/urls.tsx
- ...
Set terms and privacy urls for pt-br. They were missing. 
|https://github.com/LedgerHQ/ledger-live/assets/73439207/f456d0dc-089f-489b-a419-bb28d6f60c3a|             https://github.com/LedgerHQ/ledger-live/assets/73439207/cdfcd2f5-ad0b-4f81-aa21-a8ad080b2dc8|
- **JIRA or GitHub link**:  [LIVE-11645](https://ledgerhq.atlassian.net/browse/LIVE-11645)
--- …
=> fix(llm): set terms and privacy urls for pt-br

.changeset/rich-windows-rule.md, apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/CompleteExchange/Body.tsx
- ...
YOLO UNTESTED PR to call onClose when not in swap context
---
=> bugfix: close completeExchange drawer when sell or card

.changeset/mean-jobs-help.md, .changeset/twenty-moose-peel.md, apps/ledger-live-desktop/src/renderer/components/WebPTXPlayer/CustomHandlers.ts, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/WebviewErrorDrawer/index.tsx, apps/ledger-live-mobile/src/components/WebPTXPlayer/CustomHandlers.ts, libs/exchange-module/src/index.ts, libs/exchange-module/src/types.ts, libs/ledger-live-common/src/exchange/swap/types.ts, libs/ledger-live-common/src/wallet-api/Exchange/server.test.ts, libs/ledger-live-common/src/wallet-api/Exchange/server.ts
- ...
Moved errors from swap-live-app to exchange module in order to have the same behavior between Moonpay and swap-live-app
[- **12020**: ](https://ledgerhq.atlassian.net/browse/LIVE-12020)
---
=> feat: exchangeModule triggers error drawer

.changeset/fresh-coats-give.md, apps/ledger-live-mobile/src/PlatformAppProviderWrapper.tsx, apps/ledger-live-mobile/src/index.tsx, apps/ledger-live-mobile/src/screens/Platform/v2/Catalog/Cta.tsx
- ...
Fix untranslated cta on LLM
[LIVE TICKET
](https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/623?selectedIssue=LIVE-11648)
---
=> fix: untranslated CTA [LIVE-11648]

.changeset/warm-readers-whisper.md, libs/live-network/src/network.test.ts, libs/live-network/src/network.ts, libs/promise/src/promise.test.ts, libs/promise/src/promise.ts
- `promises` and `network` libraries
Added a `retryCondition` optional parameter to the `retry` function from the `promises` library to be able to prevent retries based on a condition. It is specifically useful to prevent retries of http calls for requests that returns a 422.
|![Screenshot 2024-03-27 at 17 28 59](https://github.com/LedgerHQ/ledger-live/assets/17146928/37724694-12b5-4c61-920b-11a1664080bb) |![Screenshot 2024-03-27 at 18 34 00](https://github.com/LedgerHQ/ledger-live/assets/17146928/11103407-b617-4328-a34e-354ba1e37845)|
- **JIRA or GitHub link**: [LIVE-11527]
---
- **The PR description clearly documents the changes** …
=> support: prevent unnecessary http call retries when 422

.changeset/little-pens-fly.md, apps/ledger-live-desktop/src/renderer/drawers/NFTViewerDrawer/ExternalViewerButton.tsx
- ...
**Before**     
**After**     
--- …
=> 💄 : Fix Explorer Button in NFT viewer

.changeset/rotten-bears-call.md, libs/ledger-live-common/src/exchange/swap/hooks/v5/useFetchRates.ts
- ...
Add check if moonpay is active before whitelisting it
https://ledgerhq.atlassian.net/browse/LIVE-12227
---
=> fix(LIVE-12227): add check provider for moonpay if FF is on or off

.changeset/weak-tools-swim.md, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/locales/en/common.json
- ...
- Correct some wording errors.
- **JIRA or GitHub link**: [LIVE-12123]
---
[LIVE-12123]: https://ledgerhq.atlassian.net/browse/LIVE-12123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …
=> [LIVE-12123][LLD] Incorrect error when trying to perform an action with Stax not on latest firmware

.changeset/eighty-crabs-search.md, apps/ledger-live-mobile/src/locales/en/common.json
- ...
Add translations for addAccounts > tokens > asa
**Before**
**After**
---
=> ASA Tokens add account translations

.changeset/purple-ligers-stare.md, apps/ledger-live-mobile/src/analytics/BrazePlugin.tsx, apps/ledger-live-mobile/src/analytics/segment.ts
…its and reduce the data points usage
- ...
Add a Braze Plugin to segment to debounce the identify traits and reduce the data points usage
- **JIRA or GitHub link**: [LIVE-11681]
---
[LIVE-11681]: …
=> LLM - Braze Plugin added to Segment to reduce Data Points usage

.changeset/proud-readers-shout.md, .changeset/purple-bobcats-fetch.md, .changeset/tasty-pigs-pretend.md, libs/coin-modules/coin-near/package.json, libs/coin-modules/coin-near/src/api/index.ts, libs/coin-modules/coin-near/src/api/indexer.ts, libs/coin-modules/coin-near/src/api/node.ts, libs/coin-modules/coin-near/src/bridge/js.ts, libs/coin-modules/coin-near/src/config.ts, libs/coin-modules/coin-near/src/js-buildTransaction.ts, libs/coin-modules/coin-near/src/preload.ts, libs/env/src/env.ts, libs/ledger-live-common/src/families/near/__snapshots__/bridge.integration.test.ts.snap, libs/ledger-live-common/src/families/near/config.ts, libs/ledger-live-common/src/families/near/setup.ts, libs/ledgerjs/packages/hw-app-near/src/Near.ts, pnpm-lock.yaml
- Broadcast now using new endpoint method: https://docs.near.org/api/rpc/transactions#send-tx
- Transaction building is now using stringified BigNumbers instead of numbers
- New public node added for some endpoints (getting validators and their commissions)
- Update the RPC request for [broadcast](https://docs.near.org/api/rpc/transactions#send-transaction-async) (old one was [deprecated](https://docs.near.org/api/rpc/transactions#send-transaction-async) and handling of `TIMEOUT_ERROR` with retrial mechanism.
- Update the transaction building by relying on stringified BigNumbers rather than numbers which could go beyond `Number.MAX_SAFE_INTEGER`
- Update chunk size in `hw-app-near` to prevent a [bug](https://ledgerhq.atlassian.net/browse/B2CA-1603) in the nano happening too quickly
- Add …
=> [LIVE-11932][LIVE-11739][LIVE-7351] Bugfix - Making Near functional again.

.changeset/popular-horses-sin.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/ExchangeDrawer/SwapAction.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/ExchangeDrawer/index.tsx, apps/ledger-live-mobile/src/screens/Swap/Form/Modal/index.tsx, libs/ledger-live-common/src/exchange/swap/initSwap.ts
- ...
[- **JIRA or GitHub link**: ](https://ledgerhq.atlassian.net/browse/LIVE-11850)
---
=> added step into userRefused for LLD

.changeset/small-birds-remain.md, apps/ledger-live-desktop/src/renderer/actions/market.ts, apps/ledger-live-desktop/src/renderer/actions/settings.ts, apps/ledger-live-desktop/src/renderer/reducers/market.ts, apps/ledger-live-desktop/src/renderer/reducers/settings.ts, apps/ledger-live-desktop/src/renderer/screens/market/hooks/useMarket.ts, apps/ledger-live-desktop/src/renderer/screens/market/hooks/useMarketCoin.ts
- ...
Starred coins were not saved anymore since rework
---
=> [FIX]: Starred coins were not saved anymore since rework

.github/workflows/test-desktop-external.yml, .github/workflows/test-desktop.yml, .github/workflows/test-mobile-e2e.yml, tools/actions/composites/upload-allure-report/action.yml
- E2E test result allure export
Enabling Allure with new server and credential reverting this [PR](https://github.com/LedgerHQ/ledger-live/pull/6106).
- **JIRA or GitHub link**: [LIVE-10285](https://ledgerhq.atlassian.net/issues/LIVE-11379)
--- …
=> [LIVE-10285] enable allure upload

.changeset/hot-pumas-obey.md, apps/ledger-live-mobile/src/screens/ReceiveFunds/03-Confirmation.tsx
- ...
App crashes when tapping 'Learn how to withdraw from exchange' in receive flow
- **JIRA or GitHub link**: [LIVE-12359] 
---
[LIVE-12359]: https://ledgerhq.atlassian.net/browse/LIVE-12359?atlOrigin=eyJpIjoiNWRkNT …
=> [BUGFIX]: APP crash on receive flow when clicking learn

.changeset/modern-apes-switch.md, libs/coin-modules/coin-polkadot/src/logic/getFeesForTransaction.test.ts, libs/coin-modules/coin-polkadot/src/network/common.ts, libs/coin-modules/coin-polkadot/src/network/sidecar.fixture.ts, libs/coin-modules/coin-polkadot/src/network/sidecar.ts
- ...
`getFeesForTransaction` doesn't rely anymore on backend call (i.e. mock all necessary calls to sidecar).
---
=> [FIX] Polkadot fees test flakiness

libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- ...
This PR adds WalletSync feature flags and initialize the WalletSync repository on LLD.
- **JIRA or GitHub link**: [LIVE-12215] 
---
[LIVE-12215]: https://ledgerhq.atlassian.net/browse/LIVE-12215?atlOrigin=eyJpIj …
=> [LL/LLD] - [LIVE-12215] - Add WalletSync feature flag + add WalletSync architecture in LLD

apps/ledger-live-desktop/src/renderer/screens/asset/AccountDistribution/Row.tsx
- ...
Adding a data test ID
---
=> adding a data-test-id

libs/promise/src/promise.ts
- countervalues fix
An important regression was introduced due to bad logic in promise `retry` function used for the network() function: throwing back the error instead of returning it.
This was implemented to disable networking inner retry mechanism when an API returns HTTP 422, but due to the bug, it makes the network() return the Error instead of throwing it. This causes live-countervalues stack to not work correctly anymore, something we may not have observed because Live instances have caches, but as soon as you change the countervalues (fiat) you will notice it – as long as you have one token that is not supported by our API: in that case there will be one HTTP 422, and the problem is that it will cascade to NO countervalues at all for any of the pairs, since we basically breaks the …
=> fix: promise retry must throw an error, instead of returning it

.changeset/tame-coins-reflect.md, apps/ledger-live-mobile/src/screens/Account/index.tsx
- ...
Make sure that the parentAccount is passed to `getMainAccount` function
- **JIRA or GitHub link**:  [LIVE-12376]
---
[LIVE-12376]: https://ledgerhq.atlassian.net/browse/LIVE-12376?atlOrigin=eyJpIjoiNWRkNTljNzYxN …
=> [LLM] add parentAccount in getMainAccount

libs/coin-modules/coin-polkadot/src/bridge/getFeesForTransaction.test.ts
- ...
Mock completely calls to Polkadot explorer.
---
=> Fix Polkadot flakiness (again)

.changeset/sour-actors-exist.md, libs/ledger-live-common/src/hw/actions/startExchange.ts
* Random check to firmware in order to close exchangeApp before starting fund
* chore: changeset
- ...
cherry pick of 
https://github.com/LedgerHQ/ledger-live/pull/6781
---
=> cherrypick/LIVE-12364 (#6781)

.changeset/wicked-feet-fly.md, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- `buySellShortcut` flag should be available on developer tools
Add flag to enable / disable upcoming shortcut flow in buy sell ui repo.
- **JIRA or GitHub link**: [LIVE-5384](https://ledgerhq.atlassian.net/browse/LIVE-5384)
--- …
=> feat: add buy sell shortcut feature flag

.changeset/dry-kangaroos-brush.md, libs/coin-modules/coin-polkadot/src/logic/craftTransaction.ts, libs/coin-modules/coin-polkadot/src/logic/index.ts
- ...
Expose function for crafting Transaction for external use.
---
=> Expose Polkadot function for external service

.changeset/tasty-balloons-report.md, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/WalletSyncRow.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- ...
This PR adds WalletSync in LLD settings.
- **JIRA or GitHub link**: [LIVE-12209] 
---
[LIVE-12209]: https://ledgerhq.atlassian.net/browse/LIVE-12209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …
=> [LLD] - [LIVE-12209] - Add Wallet Sync in LLD settings

.changeset/real-bulldogs-yell.md, apps/ledger-live-desktop/src/renderer/hooks/swap-migrations/useSwapLiveAppHook.tsx
- ...
Pass correct swap api base url to swap live app
- **JIRA or GitHub link**: [LIVE-12432](https://ledgerhq.atlassian.net/browse/LIVE-12432)
---
[LIVE-12432]: …
=> fix(LIVE-12432): swap demo 1 feature flag not working cards not displayed

.changeset/nice-guests-wave.md, apps/ledger-live-desktop/src/renderer/hooks/useDeeplinking.ts, apps/ledger-live-mobile/src/components/RootNavigator/PostOnboardingNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/types/PostOnboardingNavigator.ts, apps/ledger-live-mobile/src/const/navigation.ts, apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx, apps/ledger-live-mobile/src/screens/PostOnboarding/PostOnboardingDeeplinkHandler.tsx, libs/ledger-live-common/.unimportedrc.json, libs/ledger-live-common/src/postOnboarding/hooks/index.ts, libs/ledger-live-common/src/postOnboarding/hooks/usePostOnboardingDeeplinkHandler.test.ts, libs/ledger-live-common/src/postOnboarding/hooks/usePostOnboardingDeeplinkHandler.ts
- ...
Added a deeplink to both LLM and LLD to redirect to the post onboarding
Deeplink : `/post-onboarding?device=my_device_model_id`
- **JIRA or GitHub link**: [LIVE-12200] 
---
[LIVE-12200]: …
=> LLM / LLD - Post Onboarding Deeplink

.changeset/tame-queens-sniff.md, apps/ledger-live-desktop/src/renderer/analytics/segment.ts
- ...
Add market widget analytics in user properties
- **JIRA or GitHub link**: [LIVE-12426](https://ledgerhq.atlassian.net/browse/LIVE-12426) 
---
[LIVE-12426]: …
=> [SUPPORT]: Add market widget analytics in user properties

.changeset/tame-queens-sniff.md, apps/ledger-live-desktop/src/renderer/analytics/segment.ts
- ...
Add market widget analytics in user properties
- **JIRA or GitHub link**: [LIVE-12426](https://ledgerhq.atlassian.net/browse/LIVE-12426) 
---
[LIVE-12426]: …
=> [SUPPORT]: Add market widget analytics in user properties 

.changeset/weak-cows-design.md, apps/web-tools/README.md, apps/web-tools/package.json, apps/web-tools/pages/derivations.tsx, apps/web-tools/pages/index.tsx, pnpm-lock.yaml
- No impact
Adding a simple derivation paths listing tools into the web-tools
---
=> Feature: Add derivation path helper to web-tools

.changeset/friendly-crabs-heal.md, libs/coin-modules/coin-near/src/api/node.ts
- no impact
Fix Near commission request being cached globally instead of per validator address
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-12503
---
=> [LIVE-12503] Bugfix - Fix Near commission request wrongly cached

apps/web-tools/pages/logsviewer.tsx
This PR adds several features to the log viewer to help Ledger CS Agents more efficiently work with logs. 
Additions: 
- Section to view apps installed on a device and their versions. 
- Section to view device info (modelId and firmware version).  
- "copy" button to copy account address contained in logs.
- "explorer" button to view selected account directly on explorer.
- "copy CLI" button to efficiently grab the correct command to scan an xpub/account address
- mobile log support for all of the above
Before: 
After:
---
=> Add logviewer features

.changeset/plenty-islands-tell.md, libs/ledger-live-common/src/exchange/swap/hooks/useUpdateMaxAmount.ts
- ...
Takes additional fee off the swappable amount when max toggle is on, to prevent insufficient balance error
- **JIRA or GitHub link**: [LIVE-10131](https://ledgerhq.atlassian.net/browse/LIVE-10131)
--- …
=> fix(LIVE-10131): swap tron swapping issue with other pairs than eth and edge cases to investigate part 2

apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/ExchangeDeveloperMode.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- dev settings "Exchange Dev Mode"
this translates a dev settings introduced by https://github.com/LedgerHQ/ledger-live/pull/6475 and requested for translations
- https://ledgerhq.atlassian.net/browse/LIVE-12328
- https://github.com/LedgerHQ/ledger-live/pull/6475
--- …
=> chore: provide translations for ExchangeDeveloperMode settings

apps/ledger-live-desktop/src/renderer/reducers/accounts.ts, apps/ledger-live-desktop/src/renderer/reducers/settings.ts
- none
unused, useless code clean up
- **JIRA or GitHub link**: n/a
---
=> chore: remove DEBUG_TICK dead code

.changeset/blue-vans-try.md, apps/ledger-live-mobile/src/screens/Settings/Debug/Generators/GenerateMockAccountsNFTs.tsx, libs/coin-framework/src/mocks/fixtures/nfts.test.ts, libs/coin-framework/src/mocks/fixtures/nfts.ts, libs/live-nft-react/src/hooks/__tests__/useNftGalleryFilter.test.tsx
- ...
Fix generate Accounts+NFTs in Debug
- Add new NFTs
- Remove old NFTs (some were spams)
- Only Top collections on Opensea
- New way to generate NFTs
https://github.com/LedgerHQ/ledger-live/assets/112866305/650cf058-1a9b-4f15-a5f4-08ff749a36c2
--- …
=> [SUPPORT]: Fix generate Accounts+NFTs

.github/workflows/test-ui-e2e-only-desktop.yml
[slack notif color, test results](https://ledger.slack.com/archives/C05FKJ7DFAP/p1715699376951449)
=> fixed notif color

.changeset/many-pigs-marry.md, libs/ledger-live-common/src/families/bitcoin/setup.ts
- btc signMessage
You can reproduce easily with LLD develop and the wallet-api tools live-app
```json
{
"method": "message.sign",
"params": {
"accountId": "<your-accountId>",
"hexMessage": "68656c6c6f"
}
}
```
At some point `deviceId` in `deviceAccess.ts` becomes an `IPCTransport` causing the issue
Looking at the rest of the code, I found a modification done in this PR: https://github.com/LedgerHQ/ledger-live/pull/6045
It was not matching totally the `evm` setup for `signMessage`:
- https://github.com/LedgerHQ/ledger-live/blob/0d0564e1bf8a3f737565d26a65f7b684c2942216/libs/ledger-live-common/src/families/bitcoin/setup.ts#L47
-  https://github.com/LedgerHQ/ledger-live/blob/0d0564e1bf8a3f737565d26a65f7b684c2942216/libs/ledger-live-common/src/families/evm/setup.ts#L37
- …
=> fix: btc signMessage [LIVE-12360]

.changeset/four-insects-notice.md, apps/ledger-live-mobile/src/families/cosmos/shared/02-SelectAmount.tsx
- Cosmos staking
Fix error message for cosmos staking. It was showing minimum amount : 0000 when we wanted to stake more than the current balance
|![image](https://github.com/LedgerHQ/ledger-live/assets/73439207/a29683d6-26e8-4a7f-8893-8a0391dc58ac)| <img width="389" alt="image" src="https://github.com/LedgerHQ/ledger-live/assets/73439207/e4d7a330-126c-4b6c-821b-1355fb74ef8a">|
- **JIRA or GitHub link**: [LIVE-12485](https://ledgerhq.atlassian.net/browse/LIVE-12485)
--- …
=> fix(llm):  cosmos error message for stake

.changeset/kind-bikes-pretend.md, apps/ledger-live-desktop/src/renderer/hooks/swap-migrations/useSwapLiveAppHook.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.tsx
- send swap params as hash params
- do not show the swap-live-app if pair or amount not selected 
- ...
--- …
=> feat(live-12226): refactor WalletApi integration

CODEOWNERS
- No impact on the product
Update codeowners file:
* remove live-qa team
* add new device libraries
- **JIRA or GitHub link**: LIVE-12652
---
=> chore(codeowners) [LIVE-12652]: Update codeowners

.changeset/orange-windows-kneel.md, libs/ledger-live-common/src/exchange/swap/initSwap.ts
- ...
Adding error message before letting the app returning an obscur 0x6001 error
https://github.com/LedgerHQ/ledger-live/assets/5360522/f42d0e06-adce-4cb4-9e57-25f8c7983b15
https://ledgerhq.atlassian.net/browse/LIVE-12660
--- …
=> bugfix: check amountFrom is the same on partner payload

.changeset/metal-rings-dress.md, libs/coin-framework/src/config.ts, libs/coin-framework/src/errors.ts, libs/coin-modules/coin-polkadot/src/bridge/index.ts, libs/coin-modules/coin-polkadot/src/config.ts, libs/coin-modules/coin-polkadot/src/network/sidecar.mock.ts, libs/coin-modules/coin-polkadot/src/network/sidecar.ts, libs/coin-modules/coin-polkadot/src/network/sidecar.unit.test.ts, libs/env/src/env.ts, libs/ledger-live-common/src/families/polkadot/setup.ts
- ...
Setup CoinConfig so we can access Polkadot staging Sidecar.
To use it, launch LLD: `BYPASS_CORS=1 API_POLKADOT_SIDECAR=<SIDECAR_URL> API_POLKADOT_SIDECAR_CREDENTIALS=<YOUR_BASE64_TOKEN> pnpm dev:lld`
- **JIRA or GitHub link**: TBD
--- …
=> [Coin Polkadot] setup coin config

.changeset/metal-kings-glow.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx
- ...
update the useMemo hook dependency to relod the correct swapState  
https://ledgerhq.atlassian.net/browse/LIVE-12588
--- …
=> fix(live-12226): undefined swapState in swap-live-app

.changeset/fast-squids-eat.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx
- ...
- display the swap-live-app devtools based on the "Enable platform dev tools" flag
https://ledgerhq.atlassian.net/browse/LIVE-12588
---
=> feat: show swap-live-app devtools based on flag

libs/coin-modules/coin-algorand/package.json, libs/coin-modules/coin-algorand/please-add-coverage.test.ts, libs/coin-modules/coin-bitcoin/package.json, libs/coin-modules/coin-evm/package.json, libs/coin-modules/coin-near/package.json, libs/coin-modules/coin-near/please-add-coverage.test.ts, libs/coin-modules/coin-polkadot/package.json, libs/coin-modules/coin-solana/package.json, libs/coin-modules/coin-tezos/package.json, libs/coin-modules/coin-tezos/please-add-coverage.test.ts, libs/coin-modules/coin-xrp/package.json, libs/coin-modules/coin-xrp/please-add-coverage.test.ts, package.json
- no impact
- Add a max concurrency for turbo of 2 tests
- Remove `bridge.integration.test.ts` from coverage
- Add blank test when necessary when no test at all
- Add missing script on new coin modules
--- …
=> Support - Update coin coverage scripts to use html-spa reporter & `collectCoverageFrom` + turbo concurrency

.changeset/brave-waves-smile.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.tsx
- ...
- pass correct target and source currency ids to swap live app
---
=> fix: pass correct target and source currency ids to swap live app

.changeset/smooth-queens-relax.md, libs/ledgerjs/packages/context-module/package.json, libs/ledgerjs/packages/context-module/src/tsconfig.json, libs/ledgerjs/packages/context-module/tsconfig.json
- ...
- Fix multiple build errors on context-module package
- add lib-es build
---
=> fix(context-module): fix multiple builds error and add lib-es

.changeset/beige-nails-pull.md, libs/ledger-live-common/src/market/v2/timers.ts, libs/ledger-live-common/src/market/v2/useMarketDataProvider.ts
- ...
Fix Sentry error when fetching supportedCoins and the response has error / has not finished loading
https://ledger.sentry.io/issues/5391581002/?project=6488660
---
=> 🐛 : [FIX] LDD Sentry Type Error in Market

.changeset/curvy-yaks-study.md, apps/ledger-live-desktop/src/renderer/components/FirmwareUpdateBanner.tsx
- ...
There was an issue when updating selected language for LLD and when you had banner displayed. Translation wasn't updated correclty, you had to change page or do an action to update translation
BEFORE
https://github.com/LedgerHQ/ledger-live/assets/112866305/fdad816b-e65f-4b95-b340-74efb85e07b3
AFTER
https://github.com/LedgerHQ/ledger-live/assets/112866305/d7a9d0f4-ebcd-4b46-9386-24abfddd2c4a
---
- **The PR has been tested** thoroughly, and any potential edge cases …
=> 🐛 : [BUGFIX] Fix trad of Update firmware banner when updating selected language

.changeset/brave-spiders-tickle.md, apps/ledger-live-desktop/src/renderer/screens/dashboard/MarketPerformanceWidget/components/Footer.tsx
- ...
Update Market Widget Button clicks analytics
- **JIRA or GitHub link**: [LIVE-12728] 
---
[LIVE-12728]: https://ledgerhq.atlassian.net/browse/LIVE-12728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …
=> 📈 : [SUPPORT] Update Market Widget Button clicks analytics

.changeset/popular-keys-double.md, libs/env/src/env.ts, libs/ledger-live-common/src/exchange/swap/api/v5/fetchCurrencyAll.ts, libs/ledger-live-common/src/exchange/swap/api/v5/fetchCurrencyFrom.ts, libs/ledger-live-common/src/exchange/swap/api/v5/fetchCurrencyTo.ts, libs/ledger-live-common/src/exchange/swap/api/v5/fetchRates.ts, libs/ledger-live-common/src/exchange/swap/getExchangeRates.ts, libs/ledger-live-common/src/exchange/swap/getStatus.ts, libs/ledger-live-common/src/exchange/swap/index.ts, libs/ledger-live-common/src/exchange/swap/initSwap.ts, libs/ledger-live-common/src/exchange/swap/postSwapState.ts
- ...
Add swap user IP
https://ledgerhq.atlassian.net/browse/LIVE-12276
---
=> feat(LIVE-12276): add swap user IP

.changeset/clever-gorillas-fix.md, apps/ledger-live-desktop/tests/specs/services/wallet-api.spec.ts, apps/ledger-live-desktop/tests/specs/services/wallet-api.spec.ts-snapshots/wallet-api-currencies-darwin.json, apps/ledger-live-desktop/tests/specs/services/wallet-api.spec.ts-snapshots/wallet-api-currencies-linux.json, libs/ledger-live-common/src/platform/types.ts, libs/ledger-live-common/src/wallet-api/constants.ts
- discover live-apps using ripple
The ripple family was renamed to xrp on a recent PR: https://github.com/LedgerHQ/ledger-live/pull/6822
This adds the missing family for the wallet-api and platform-sdk, as well as a test to avoid regressions
- **JIRA or GitHub link**: [LIVE-12651]
--- …
=> fix(wallet-api): xrp family not present [LIVE-12651]

.github/workflows/test-ui-e2e-only-desktop.yml
- ...
ci : fix of e2e workflow
---
=> ci: fix of e2e workflow

.changeset/old-dancers-sin.md, apps/ledger-live-desktop/src/renderer/screens/dashboard/MarketPerformanceWidget/components/Header.tsx
- ...
Colors of icons in Widget were not working well
---
=> 🐛 [BUGFIX] : Colors of icons in Widget

.changeset/young-cherries-press.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FormSummary/index.tsx
- ...
- remove network fees line when demo1 ff is enable 
https://ledgerhq.atlassian.net/browse/LIVE-12701
=> fix: remove network fees line when demo1 ff is enable

.changeset/tiny-rules-enjoy.md, apps/ledger-live-mobile/src/families/tron/accountActions.tsx, pnpm-lock.yaml
- ...
This invariant caused LLM to crash even though tronResources are not used in this component
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-12730
---
=> [LIVE-12730][tron] Remove unused invariant check

.github/workflows/test-ui-e2e-only-desktop.yml
update Slack notification: Adding allure link
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/jira/software/c/projects/QAA/boards/887?selectedIssue=QAA-74  
---
=> Adding link to allure

.changeset/twelve-mails-wonder.md, libs/ledger-live-common/src/wallet-api/useDappLogic.ts
- ...
set account on dapp browser after switching chain from dapp
- **JIRA or GitHub link**:  [TICKET](https://ledgerhq.atlassian.net/browse/LIVE-12574)
---
=> fix: switch chain issue [LIVE-12574]

.github/workflows/test-ui-e2e-only-desktop.yml
- ...
Little update of the slack notification for speculos nightly notification
---
=> ci: fix slack notif for speculos nightly

apps/ledger-live-desktop/tests/page/portfolio.page.ts
Adding a method that check if the asset is visible in the portfolio. In the event that the asset is not visible, we will click on "Show all".
---
=> test: fix of erc20

.changeset/eleven-cameras-speak.md, libs/ledger-live-common/src/exchange/swap/api/v5/__tests__/fetchCurrencyTo.spec.ts, libs/ledger-live-common/src/exchange/swap/api/v5/fetchCurrencyTo.ts, libs/ledger-live-common/src/exchange/swap/hooks/v5/useFetchCurrencyTo.ts
- ...
check FF for fetch currency to
---
=> feat: moonpay ff on fetch currency to

CODEOWNERS
- ...
to prevent modification of trustchain to be pinging wrong team.
---
=> chore(codeowners): explicit apps/web-tools/trustchain ownership

.github/workflows/build-mobile-external.yml
- ...
Fix Build Mobile External to upload the build result.
Example with the fix: https://github.com/LedgerHQ/ledger-live/actions/runs/9302730161
---
=> Fix output for android apk on Build Mobile External workflow

apps/web-tools/trustchain/components/App.tsx, libs/trustchain/.unimportedrc.json, libs/trustchain/README.md, libs/trustchain/package.json, libs/trustchain/src/errors.ts, libs/trustchain/src/qrcode/cipher.test.ts, libs/trustchain/src/qrcode/cipher.ts, libs/trustchain/src/qrcode/index.test.ts, libs/trustchain/src/qrcode/index.ts, libs/trustchain/src/qrcode/types.ts, libs/trustchain/src/sdk.ts, libs/trustchain/src/types.ts, pnpm-lock.yaml
- not used in production
- add `qrcode` feature in trustchain core library
- Add two functions to integrate the UI on both sides of the protocol.
- `createQRCodeHostInstance({onDisplayQRCode, onDisplayDigits, addMember }): Promise<void>`
- `createQRCodeCandidateInstance({ liveCredentials, scannedUrl, onRequestQRCodeInput }): Promise<void>`
- integration tests with a mock websocket server to confirm the dual functions are working together.
- web tools playground has been tested (but trustchain fails in this test, it will be disabled until we make trustchain functional):
https://github.com/LedgerHQ/ledger-live/assets/211411/6d709f34-b03b-4537-9a6f-ce26017a7ff0
- **JIRA or GitHub link**: [LIVE-12865](https://ledgerhq.atlassian.net/browse/LIVE-12865)
---
- **The code aligns with the …
=> chore: trustchain qrcode implementation

apps/web-tools/next.config.js, apps/web-tools/trustchain/components/Actionable.tsx, apps/web-tools/trustchain/components/App.tsx
- web tools
simplify the code to focus on the logic of the web-tools trustchain and move the UI out of the picutre.
- **JIRA or GitHub link**: na 
---
=> chore: trustchain web-tools clean up / simplification

.changeset/angry-bees-dress.md, apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/WalletAPIWebview.tsx, apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/index.tsx, apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/types.ts, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx
- ...
hide webview loader from swap module
https://github.com/LedgerHQ/ledger-live/assets/11476482/863d0b45-b6ed-4785-acfc-8c3503858a83
https://ledgerhq.atlassian.net/browse/LIVE-12767
---
=> fix: hide webview loader from swap module

apps/web-tools/package.json, apps/web-tools/pages/index.tsx, apps/web-tools/trustchain/components/Actionable.tsx, apps/web-tools/trustchain/components/App.tsx, apps/web-tools/trustchain/components/Expand.tsx, apps/web-tools/trustchain/components/QRCode.tsx, apps/web-tools/trustchain/useEnv.ts, apps/web-tools/trustchain/useSDK.ts, libs/trustchain/src/index.ts, libs/trustchain/src/mockSdk.ts, libs/trustchain/src/sdk.ts, libs/trustchain/src/types.ts, pnpm-lock.yaml
- web tools
Mock the return results of the trustchain SDK based on the `MOCK` env variable of the live-env package
Updated the trustchain web tool to be able to test it
- **JIRA or GitHub link**: [LIVE-12626]
--- …
=> Mock Trustchain SDK

.changeset/brave-dolphins-admire.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/FirmwareUpdate/components/UpdateBanner/UpdateBanner.test.tsx, apps/ledger-live-mobile/src/newArch/features/FirmwareUpdate/components/UpdateBanner/useUpdateBannerViewModel.tsx, apps/ledger-live-mobile/src/newArch/features/FirmwareUpdate/utils/isFirmwareUpdateSupported.test.ts, apps/ledger-live-mobile/src/newArch/features/FirmwareUpdate/utils/isFirmwareUpdateSupported.ts, apps/ledger-live-mobile/src/screens/FirmwareUpdate/index.tsx
- Nano X to use the new FW update flow (and enable BLE fw update as well)
Enable Nano X BLE fw update on LLM.
- **JIRA or GitHub link**: [DSDK-308]
---
[DSDK-308]: …
=> feat(llm) [DSDK-308]: nanox ble update

.changeset/silent-suns-tease.md, apps/ledger-live-desktop/src/renderer/components/ContentCards/ActionCard/components.tsx
- ...
Fix text color for Stax post onboarding on light mode.
Before
After
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-12291
---
=> fix: LLD Stax post onboarding text color light mode

.changeset/ten-insects-reflect.md, apps/ledger-live-mobile/ios/Podfile.lock, libs/ui/packages/icons/src/svg/Delete-stop.svg
- React ui
Add delete stop icon with new format 
- **JIRA or GitHub link**: [LIVE-12879](https://ledgerhq.atlassian.net/browse/LIVE-12879)
---
[LIVE-12879]: …
=> feat(icons): add delete stop icon

.changeset/light-pandas-sip.md, libs/ui/packages/react/src/components/form/BaseInput/index.tsx
- ...
Fix color of clearable 
---
=> 🐛 [BUGFIX]: color of clearable element in Input

apps/ledger-live-mobile/e2e/bridge/client.ts, apps/ledger-live-mobile/e2e/bridge/server.ts, apps/ledger-live-mobile/e2e/bridge/types.ts, apps/ledger-live-mobile/e2e/jest.config.js, apps/ledger-live-mobile/e2e/jest.globalTeardown.ts, apps/ledger-live-mobile/e2e/setup.ts, apps/ledger-live-mobile/e2e/specs/getAllureEnvironment.spec.ts
- Allure reporting of Detox test
_Adding Mobile application Environment variable and Feature Flags to Allure reports environment fields_
- [Report exemple](https://github.com/LedgerHQ/ledger-live/files/15483651/index.html.zip)
--- …
=> [QAA-75][Detox]Allure reporting: adding environment variable and feature flags

.changeset/six-crabs-serve.md, apps/ledger-live-mobile/src/components/Alert.tsx, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/AddAccounts/02-TokenCurrencyDisclaimer.tsx
- wording of ERC20 on Add Accountd
- this will require new translations
- this fixes edge cases like ERC20 on Avalanche, that were wrongly displayed as ERC20 on Ethereum due to the limited approach of hardcoding all wording cases.
- **JIRA or GitHub link**: [LIVE-11794](https://ledgerhq.atlassian.net/browse/LIVE-11794)
---
- …
=> chore(llm): generalize the messages for tokens like done on LLD

.changeset/loud-toes-live.md, libs/ledger-live-common/src/families/tron/synchronization.ts
- ...
Tron keep empty sub Account to be ISO with EVM. Required for moment for the swapHistory
https://github.com/LedgerHQ/ledger-live/assets/5360522/2cb591c7-66e4-45e4-b3cf-13729fcdfff1
--- …
=> tron: keep empty subAccounts

libs/trustchain/src/store.ts
- ...
Added store helpers to be used by LLM and LLD to facilitate trustchain related state management
- **JIRA or GitHub link**: [LIVE-12625]
---
[LIVE-12625]: …
=> Trustchain - Added store helpers

.changeset/cyan-files-invite.md, apps/ledger-live-mobile/src/screens/Swap/Form/Modal/Confirmation.tsx
- ...
Remove sourceCurrencyId and targetCurrencyId sending wrong info
https://ledgerhq.atlassian.net/browse/LIVE-12808
---
=> Remove sourceCurrencyId and targetCurrencyId

apps/web-tools/trustchain/components/App.tsx, libs/hw-trustchain/src/NobleCrypto.ts, libs/hw-trustchain/src/__tests__/crypto.ts, libs/trustchain/src/index.test.ts, libs/trustchain/src/sdk.test.ts, libs/trustchain/src/sdk.ts, libs/trustchain/src/wallet-sync-cipher.ts
- no impact yet
implement the methods encryptUserData and decryptUserData. tested and added in web tools playground.
- **JIRA or GitHub link**: [LIVE-12869](https://ledgerhq.atlassian.net/browse/LIVE-12869)
--- …
=> trustchain: add encrypt/decrypt methods in the SDK for wallet sync

.changeset/violet-lemons-battle.md, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- None
Wallet sync llm arch created
FF `feature_llm_wallet_sync` has been created in firebase for dev, staging and prod
FF `feature_llm_wallet_sync` has been added inside codebase
- **JIRA or GitHub link**: [LIVE-12216](https://ledgerhq.atlassian.net/browse/LIVE-12216)
--- …
=> feat(llm): create llm wallet sync arch and ff

.changeset/grumpy-dots-rescue.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/Settings/General/WalletSyncRow.tsx, apps/ledger-live-mobile/src/screens/Settings/General/index.tsx
- General Settings
Add wallet sync entry point inside settings/generals
The row won't be displayed as the ff `llmWalletSync` is not enabled
For the moment this row won't redirect anywhere
| llmWalletSync disabled        | llmWalletSync enabled         |
|![Screenshot 2024-06-10 at 16 26 08](https://github.com/LedgerHQ/ledger-live/assets/73439207/3ca9a56d-985f-441e-b0ce-9032a40eb6ad)|![Screenshot 2024-06-10 at 16 19 49](https://github.com/LedgerHQ/ledger-live/assets/73439207/b0f5e8be-54eb-4aa1-a86c-086531c5eb40)|
- **JIRA or GitHub link**: [LIVE-12157](https://ledgerhq.atlassian.net/browse/LIVE-12157) 
--- …
=> feat(llm): add settings row for wallet sync

.changeset/slimy-parents-glow.md, apps/ledger-live-desktop/src/renderer/families/solana/Delegation/Row.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/families/solana/Delegations/Row.tsx
- ...
Original PR : https://github.com/LedgerHQ/ledger-live/pull/6823
- **JIRA or GitHub link**: [https://ledgerhq.atlassian.net/browse/LIVE-10370](https://ledgerhq.atlassian.net/browse/LIVE-10370)
---
=> Bugfix/solana UI staking issues bp

.changeset/slimy-jokes-punch.md, apps/ledger-live-desktop/src/renderer/components/TopBanner.tsx
- ...
use `openURL` to open URL in browser instead of in electron
- **JIRA or GitHub link**: `N/A`
https://ledgerhq.atlassian.net/browse/LIVE-12975
---
=> Warning banner opens URL in browser

apps/ledger-live-desktop/src/newArch/WalletSync/components/LogoWrapper.tsx
=> 💄: Rework Icons on WelcomeScreen on WalletSync

.changeset/shaggy-apples-hunt.md, package.json, patches/@changesets__get-github-info@0.6.0.patch, pnpm-lock.yaml
Added a changeset to trigger the release branch
- CI
Limit the batching done for changesets on github request using a patch
---
=> chore: patch changesets to avoid too big batching on github requests

apps/ledger-live-desktop/tests/fixtures/common.ts, apps/ledger-live-desktop/tests/misc/reporters/step.ts
Linking the screenshot of a failed test to the proper failed step within this scenario
https://ledgerhq.atlassian.net/browse/QAA-109
=> linked screenshot to failed step

apps/ledger-live-desktop/src/newArch/WalletSync/Flows/Activation/01-CreateOrSynchronizeStep.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/Flows/Activation/03-UnsecuredError.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/Flows/Synchronize/01-SyncModeStep.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/Flows/Synchronize/02-QRCodeStep.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/__tests__/manageSynchronizedInstances.test.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/__tests__/manageYourBackup.test.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/__tests__/synchronize.test.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/__tests__/walletSync.test.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/components/Card.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, libs/ui/packages/react/src/components/layout/List/NumberedList/index.tsx
- ...
Polishing the UI of the various flows on WalletSync
---
=> 💄 : Polishing LedgerSync Screens on LLD

apps/ledger-live-desktop/tests/playwright.config.ts
=> [QAA-105] Added 2 retries for Speculos tests

.changeset/strong-dingos-end.md, libs/live-wallet/src/store.test.ts, libs/live-wallet/src/store.ts
- ...
Keep previously edited account names when we add a new account
https://github.com/LedgerHQ/ledger-live/assets/31533861/e5df24b1-f6e7-4a1a-ab86-0ae5924e014b
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-12995
--- …
=> [LIVE-12995] Keep previously renamed accounts value

.changeset/strong-dingos-end.md, libs/live-wallet/src/store.test.ts, libs/live-wallet/src/store.ts
- ...
Cherry pick this fix https://github.com/LedgerHQ/ledger-live/pull/7079
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-12995
---
=> [Release][LIVE-12995] Keep previously renamed accounts value

libs/trustchain/src/qrcode/index.ts
- trustchain sdk library development
createQRCodeHostInstance and createQRCodeCandidateInstance functions currently returns a Promise<void> that resolves when the qr code sync has been successful. We however didn't managed the fact ws.onclose may occurs prematurely, and in the current implementation, such case would never ends the promise. In real world, it’s not such a big concerns because it’s not easy to make an actual “close”, since network issue would actually likely emit an onerror, but it’s good for completeness of all cases to have this covered, so we throw an error in such case.
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/LIVE-12914
--- …
=> chore(trustchain): improve qrcode websocket handling of onclose

apps/web-tools/trustchain/components/App.tsx, libs/trustchain/README.md, libs/trustchain/src/api.ts, libs/trustchain/src/sdk.ts, libs/trustchain/src/types.ts
- library development
Add the ability to remove an existing Trustchain with the API.
- **JIRA or GitHub link**: [LIVE-12988](https://ledgerhq.atlassian.net/browse/LIVE-12988)
---
[LIVE-12988]: …
=> feat(trustchain): implement sdk.destroyTrustchain

apps/web-tools/package.json, apps/web-tools/trustchain/components/App.tsx, apps/web-tools/trustchain/components/Expand.tsx, apps/web-tools/trustchain/components/IdentityManager.tsx, libs/trustchain/src/api.ts, libs/trustchain/src/mockSdk.ts, libs/trustchain/src/qrcode/index.test.ts, libs/trustchain/src/sdk.test.ts, libs/trustchain/src/sdk.ts, libs/trustchain/src/types.ts, pnpm-lock.yaml
=> chore(trustchain): improve web tools + fixes with latest api

.changeset/six-rivers-study.md, libs/ledger-live-common/src/exchange/swap/hooks/useUpdateMaxAmount.ts
- ...
Only apply fee reduction to ETH and not tokens
[- **JIRA or GitHub link**: ](https://ledgerhq.atlassian.net/browse/LIVE-12901)
---
=> bugfix: LIVE-12901 incorrect ERC20 fees

libs/hw-trustchain/src/ApduDevice.ts, libs/hw-trustchain/src/index.ts, libs/hw-trustchain/src/integration/failure.test.ts, libs/hw-trustchain/src/integration/run-as-owner.test.ts
- lib dev of hw-trustchain
Factorize and return the app name that will eventually also be renamed.
---
=> chore(hw-trustchain): export the app name

apps/ledger-live-desktop/tests/specs/services/dapp.spec.ts
- ...
Temporarily disables switch chain dapp test until we can fix it to unblock others CI 
---
=> test(dapp): temporarily disable switch chain test until fixed

apps/web-tools/trustchain/components/App.tsx, apps/web-tools/trustchain/components/IdentityManager.tsx, libs/trustchain/src/mockSdk.ts, libs/trustchain/src/qrcode/index.test.ts, libs/trustchain/src/qrcode/index.ts, libs/trustchain/src/sdk.ts, libs/trustchain/src/store.ts, libs/trustchain/src/types.ts
- trustchain sdk api
```
LiveCredentials => MemberCredentials
liveAuthenticate => auth
seedIdAuthenticate => authWithDevice
```
- **JIRA or GitHub link**: live-13027
---
=> chore(trustchain): rename sdk methods

.changeset/big-hornets-hide.md, libs/coin-modules/coin-cardano/src/deviceTransactionConfig.ts
- ...
Cardano token transaction was showing fee value in token currency that is fixed to show fee value as main currency
---
=> show tx fee value as main currency

apps/web-tools/trustchain/components/Actionable.tsx, apps/web-tools/trustchain/components/App.tsx, apps/web-tools/trustchain/components/AppAuthenticate.tsx, apps/web-tools/trustchain/components/AppDecryptUserData.tsx, apps/web-tools/trustchain/components/AppDestroyTrustchain.tsx, apps/web-tools/trustchain/components/AppDeviceAuthenticate.tsx, apps/web-tools/trustchain/components/AppEncryptUserData.tsx, apps/web-tools/trustchain/components/AppGetMembers.tsx, apps/web-tools/trustchain/components/AppGetOrCreateTrustchain.tsx, apps/web-tools/trustchain/components/AppInitLiveCredentials.tsx, apps/web-tools/trustchain/components/AppMemberRow.tsx, apps/web-tools/trustchain/components/AppMockEnv.tsx, apps/web-tools/trustchain/components/AppQRCodeCandidate.tsx, apps/web-tools/trustchain/components/AppQRCodeHost.tsx, apps/web-tools/trustchain/components/AppRestoreTrustchain.tsx, apps/web-tools/trustchain/components/AppSetTrustchainAPIEnv.tsx, apps/web-tools/trustchain/components/Input.tsx, apps/web-tools/trustchain/context.ts, apps/web-tools/trustchain/device.ts
add contextual documentation on hover, split by components, polish a bit the UI of trustchain web tools
---
=> chore: split webtools/trustchain into components

apps/ledger-live-desktop/src/renderer/components/OperationsList/Operation.tsx, apps/ledger-live-desktop/src/renderer/modals/SettingsAccount/AccountSettingRenderBody.tsx, apps/ledger-live-desktop/tests/page/account.page.ts, apps/ledger-live-desktop/tests/specs/speculos/README.md, apps/ledger-live-desktop/tests/specs/speculos/add.account.spec.ts
- ...
- Adding check that the account added correspond to the first derivated address (index is 0)
- Clicking on `Show more` to show all the operation history
- Update read me
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/jira/software/c/projects/QAA/boards/887?selectedIssue=QAA-111 
--- …
=> Adding checks on add.account.ts + update readme

libs/trustchain/src/mockSdk.ts, libs/trustchain/src/sdk.ts, libs/trustchain/src/types.ts
- lib development
Add the ability in Trustchain SDK to hook to device user interactions.
---
=> chore(trustchain): add callbacks to be able to hook device phases

.changeset/cool-hornets-join.md, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- ...
- Add feature flag for new feature development.
- **JIRA or GitHub link**: [LIVE-12691]
---
[LIVE-12691]: https://ledgerhq.atlassian.net/browse/LIVE-12691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …
=> [LIVE-12691][LL][Passkey] Add Feature Flag for app Data backup

.changeset/six-meals-try.md, libs/ledger-live-common/src/exchange/swap/hooks/useSwapTransaction.ts
- ...
[- **JIRA or GitHub link**: 
](https://ledgerhq.atlassian.net/browse/LIVE-13044)
--- …
=> fix: changed error when NotEnoughBalance

.changeset/khaki-camels-chew.md, apps/ledger-live-desktop/src/renderer/components/TokenRow.tsx, apps/ledger-live-desktop/src/renderer/screens/accounts/AccountRowItem/index.tsx
- ...
Fix pre release problem about counter values. Also fix an UI error on accounts 
- **JIRA or GitHub link**: [LIVE-13072](https://ledgerhq.atlassian.net/browse/LIVE-13072)
---
[LIVE-13072]: …
=> fix(lld): fix countervalues develop

.changeset/large-carrots-attend.md, apps/ledger-live-desktop/src/renderer/components/OperationsList/Operation.tsx
- ...
Units are wrong on token operations as they refer to mainAccount everytime
Old:
Fixed:
- **JIRA or GitHub link**: [https://ledgerhq.atlassian.net/browse/LIVE-13102](https://ledgerhq.atlassian.net/browse/LIVE-13102)
--- …
=> fix units on token operations

.github/workflows/account-migration.yml, libs/ledger-live-common/src/__tests__/migration/account-migration.ts
- ...
[Account migration test] Test skip synchro if currency in branch 
---
=> [account migration script] if currency not supported we skip it in the next synchro

.changeset/purple-olives-reflect.md, apps/ledger-live-desktop/src/renderer/screens/dashboard/MarketPerformanceWidget/components/WidgetList.tsx
- Market performance widget
Layout issue with Gainers/Losers widget if asset name is too long. There was an overflow out of the box
Changes approved by Product
|![image](https://github.com/LedgerHQ/ledger-live/assets/73439207/18b9a33d-4a1c-466f-bd5c-cc84c1fef2a3)| ![image](https://github.com/LedgerHQ/ledger-live/assets/73439207/5cd7850b-28a6-4edb-85df-829aa450e101)|
- **JIRA or GitHub link**: [LIVE-13077](https://ledgerhq.atlassian.net/browse/LIVE-13077)
--- …
=> fix(lld): layout issue on market performance widget

apps/ledger-live-mobile/.env.mock, apps/ledger-live-mobile/scripts/e2e-ci.mjs
- Detox test flakiness
_Removing unnecessary hardcoded feature flags._
`ratingsPrompt` and `brazePushNotifications` remain disabled as they are not predictable and causes random fails.
---
=> [QAA-86][Detox] Remove unnecessary hardcoded feature flags

.changeset/rude-carrots-compare.md, libs/device-core/src/commands/use-cases/getDeviceName.ts
- ...
- **JIRA or GitHub link**: [LIVE-13123] 
---
- **The PR has …
=> [LIVE-13123] Nano X on old firmware (2.0.1) name is not correctly recognized in My Ledger

.changeset/purple-rivers-crash.md, apps/ledger-live-desktop/src/renderer/families/evm/SendAmountFields/index.tsx
* fix: rare crash where gasOption is defined but not yet in transaction where it should be
* chore: changeset
- ...
cherry pick of https://github.com/LedgerHQ/ledger-live/pull/7163 
---
=> Fix/live 13088 (#7163)

.github/workflows/test-desktop.yml, .github/workflows/test-ui-e2e-only-desktop.yml, apps/ledger-live-desktop/package.json, apps/ledger-live-desktop/tests/specs/speculos/README.md, tools/actions/composites/setup-test-desktop/action.yml
- Desktop test app
_Use staging build for speculos tests :_
Speculos tests currently use the ledger-live-testing Firebase environment. To better simulate real user conditions, we should switch to using the staging environment.
--- …
=> [QAA-118][Playwright][Speculos] Create staging build for speculos tests

.changeset/serious-taxis-perform.md, libs/ledgerjs/packages/cryptoassets/src/abandonseed.ts
- ...
Update tron dead address to prevent address validation issue during gas fee estimation 
---
=> fix(LIVE-13101): update tron dead address

apps/ledger-live-desktop/src/renderer/families/evm/SendAmountFields/index.tsx
add checks instead of replace checks
- ...
revert LIVE-13088 and a a new check to fix the crash instead of 
[- **JIRA or GitHub 13131**: ](https://ledgerhq.atlassian.net/browse/LIVE-13131)
---
=> fix: revert LIVE-13088 and a fix LIVE-13131

apps/ledger-live-desktop/src/renderer/families/evm/SendAmountFields/index.tsx
add checks instead of replace checks
- ...
--- …
=> fix: revert LIVE-13088 and a fix LIVE-13131 (#7180)

.changeset/silver-apples-raise.md, apps/ledger-live-mobile/src/screens/MyLedgerDevice/AppsScreen.tsx, apps/ledger-live-mobile/src/screens/Platform/v2/Catalog/Layout.tsx
- Discover screen
- MyLedger apps
On ios the keyboard was hiding some apps on MyLedger and Discover screen while doing a search. Now the behaviour will be the same as on Android
BEFORE : 
https://github.com/LedgerHQ/ledger-live/assets/73439207/77809113-ea9a-4573-8c83-7ecf8a955602
AFTER : 
- **JIRA or GitHub link**: [LIVE-8842](https://ledgerhq.atlassian.net/browse/LIVE-8842) 
---
- **Any new …
=> :bug:fix(llm): Discover tab/My Ledger doesn't compensate for keyboard height

apps/ledger-live-desktop/RELEASE_NOTES.md
- ...
Update LLD v2.83.0 Release note
---
=> chore(release): update LLD release note v2.83.0

.changeset/tall-moons-flow.md
- ...
Previous changeset pointed to incorrect library
---
=> fix: update changeset to point to correct lib

libs/ledger-live-common/CHANGELOG.md
- ...
conflict resolution between release and main 
---
=> [Chore(release)]: conflict resolution between release and main 

.changeset/cold-carrots-rush.md, apps/ledger-live-mobile/ios/ledgerlivemobile/AppDelegate.mm
- IOS Config
- Splashscreen
Splash screen on IOS devices wasn't working as expected
The device on the left hasn't the fix and the device on the right has the fix : 
https://github.com/LedgerHQ/ledger-live/assets/73439207/74773619-611f-4a97-9a55-dd4c67e171b4
- **JIRA or GitHub link**: [LIVE-13154](https://ledgerhq.atlassian.net/browse/LIVE-13154)
--- …
=> :bug:fix(llm): ios splashcreen wasn't displayed

.changeset/curly-dryers-worry.md, .changeset/funny-chefs-press.md, package.json, pnpm-lock.yaml
- package.json
- package-lock.json
Force strict version of `@grpc/grpc-js` used by `@hashgraph/sdk`
https://github.com/LedgerHQ/ledger-live/assets/23080211/a34a2d69-768a-48cd-a1a7-e0cd242ab325
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-13137
--- …
=> Enforce @hashgraph/sdk peer dependency version to be compatible with React Native

.changeset/unlucky-nails-learn.md, apps/ledger-live-desktop/src/config/urls.ts, apps/ledger-live-desktop/src/renderer/families/tron/operationDetails.tsx, apps/ledger-live-mobile/src/families/tron/operationDetails.tsx, apps/ledger-live-mobile/src/utils/urls.tsx
=> [Tron] Fee info URL

.changeset/tidy-fireants-sit.md, libs/coin-modules/coin-polkadot/.unimportedrc.json, libs/coin-modules/coin-polkadot/src/network/sidecar.ts
- ...
Remove active calls to Polkadot node.
However, keeping the code for future use.
- **JIRA or GitHub link**: [LIVE-13136]
---
[LIVE-13136]: https://ledgerhq.atlassian.net/browse/LIVE-13136?atlOrigin=eyJpIjoiNWRkNT …
=> [DOT] Temporary remove all node calls

.changeset/tidy-fireants-sit.md, libs/coin-modules/coin-polkadot/.unimportedrc.json, libs/coin-modules/coin-polkadot/src/network/sidecar.ts
Signed-off-by: Stéphane Prohaszka <stephane.prohaszka@ledger.fr>
(cherry picked from commit 9c163357d5bfc341d31aaf3376ac606157853265)
- ...
Remove active calls to Polkadot node.
However, keeping the code for future use.
- **JIRA or GitHub link**: [LIVE-13136]
--- …
=> [DOT] Release - Remove all node calls

apps/ledger-live-desktop/tests/specs/speculos/README.md
- ...
Update readMe for Speculos x playwright
---
=> Update readme for Speculos x Playwright

.changeset/metal-buses-judge.md, apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/LandingPagesNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/types/BaseNavigator.ts, apps/ledger-live-mobile/src/components/RootNavigator/types/LandingPagesNavigator.ts, apps/ledger-live-mobile/src/const/navigation.ts, apps/ledger-live-mobile/src/dynamicContent/ContentCardsLocation.tsx, apps/ledger-live-mobile/src/dynamicContent/types.ts, apps/ledger-live-mobile/src/dynamicContent/utils.tsx, apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/GenericLandingPage/index.tsx
- ...
Added 15 landing pages that use Braze cards so the growth team can handle what they display and redirect users to them using a new deeplink : ledgerlive://landing-page?useCase={{myUseCase}} 
Here are all the different use cases that will each trigger a different landing page :
LP_Recover
LP_Buy
LP_Receive
LP_Swap
LP_Stake
LP_Earn
LP_Referral
LP_Shop
LP_Website_Promo
LP_Discover_1
LP_Discover_2
LP_Discover_3
LP_Wallet_Connect
LP_Security_Key
LP_Generic
If no card is available to this user when landing on this new page, the page will close itself automatically
- **JIRA or GitHub link**: [LIVE-13099]
--- …
=> LLM - Growth Landing Pages

.changeset/lovely-boats-sniff.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx
- ...
- add toAccountId to Hash params for swap live app
https://ledgerhq.atlassian.net/browse/LIVE-13163
---
=> fix(live-13163): add toAccountId to Hash Params for swap-live-app

apps/ledger-live-desktop/tests/specs/speculos/add.account.spec.ts, apps/ledger-live-desktop/tests/utils/speculos.ts
- ...
Deactivating ETC for speculos tests
---
=> deactivating speculos tests - ETC

.changeset/wild-ducks-pretend.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.tsx
- ...
- in demo1 reset error and amout to value when target currency is changed 
https://ledgerhq.atlassian.net/browse/LIVE-13216
---
=> fix(live-13216): reset error and amout to value

.changeset/good-actors-refuse.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx
Pass discreet mode option to swap app
- ...
--- …
=> fix: add discreet mode option

.changeset/cold-carrots-rush.md, apps/ledger-live-mobile/ios/ledgerlivemobile/AppDelegate.mm
This reverts commit a5ba9304a6761fbab72406d24f6cb734588465d9.
- ...
--- …
=> Revert ":bug:fix(llm): ios splashcreen wasn't displayed"

.changeset/strange-mangos-occur.md, libs/coin-modules/coin-polkadot/src/api/index.ts, libs/coin-modules/coin-xrp/src/api/index.ts, libs/coin-modules/coin-xrp/src/logic/combine.ts
- ...
Set pubkey parameter as optional for `combine`
---
=> [XRP] Pubkey for combine is now optional

tools/actions/composites/setup-toolchain/action.yml
=> fix: failing setup toolchain action

apps/ledger-live-desktop/tests/specs/speculos/add.account.spec.ts, apps/ledger-live-desktop/tests/utils/speculos.ts
- Speculos add account tests
_Fixing missing dependency and spec name for ETC add acount test_
---
=> [QAA-131][Speculos] Fix ETC add account test

.changeset/heavy-ducks-help.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx
- ...
- set fromAccountId to hash params in swap-live-app
https://ledgerhq.atlassian.net/browse/LIVE-13261
---
=> fix(live-13261): set fromAccountId to hash params

.changeset/khaki-dragons-exist.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/screens/Swap/Form/index.tsx, libs/ledger-live-common/src/exchange/swap/maybeTronEmptyAccount.ts, libs/ledgerjs/packages/errors/src/index.ts
- ...
invert condiition of FF trc20 receive
[- LIVE-13008: ](https://ledgerhq.atlassian.net/browse/LIVE-13008)
---
=> fix: invert condition FF trc20 receive swap

.github/workflows/test-ui-e2e-only-desktop.yml, apps/ledger-live-desktop/tests/utils/speculos.ts
- Speculos test
_We were using outdated coin-apps generated for the bot. We switch to the latest version and also update Speculos image version used for the tests. This is closer behaviour to E2E._
[Speculos Test run](https://github.com/LedgerHQ/ledger-live/actions/runs/9807744066).
Tests are green but Allure server seems down.
---
- …
=> [QAA-134][Speculos] Fix Polkadot add account

.changeset/fair-cooks-arrive.md, apps/ledger-live-desktop/.unimportedrc.json, apps/ledger-live-desktop/src/newArch/Collectibles/Nfts/BreadCrumb/LabelWithMeta.tsx, apps/ledger-live-desktop/src/newArch/Collectibles/Nfts/BreadCrumb/index.tsx, apps/ledger-live-desktop/src/newArch/Collectibles/Nfts/BreadCrumb/useBreadCrumbModel.tsx, apps/ledger-live-desktop/src/newArch/Collectibles/__integration__/nftsCollection.test.tsx, apps/ledger-live-desktop/src/newArch/Collectibles/__integration__/shared.tsx, apps/ledger-live-desktop/src/newArch/Collectibles/types/Nfts.ts, apps/ledger-live-desktop/src/newArch/components/BreadCrumb/common.tsx, apps/ledger-live-desktop/src/newArch/components/BreadCrumb/index.tsx
- No change visible
- Nft Crumb
Rework of the nft gallery breadcrumb. It has been refactor inside newarch. 
Also fix the dropdown selector inside the breadcrumb that was not working as it should. The current dropdown doesn't show what collection we looking into
https://github.com/LedgerHQ/ledger-live/assets/73439207/2b6ea046-f6d8-4827-8e77-96058fc40a15
- **JIRA or GitHub link**: [LIVE-12462](https://ledgerhq.atlassian.net/browse/LIVE-12462)
--- …
=> :boom:feat(lld): nft breadcrumb

.changeset/silent-drinks-sin.md, libs/ledger-live-common/src/exchange/providers/swap.ts
- ...
Fallback in case of CDN/CAL failure did not work as expected. 
This PR fixes the fallback and prevent the swap from not working at all if CDN/CAL throw an error
---
=> fix: LIVE-13279

.changeset/rotten-zoos-reflect.md, libs/ledger-live-common/src/exchange/swap/completeExchange.ts, libs/ledger-live-common/src/exchange/swap/initSwap.ts
- ...
revert ignoring all swaps errors that introduced unrelated isssues
[- **JIRA or GitHub link**: ](https://ledgerhq.atlassian.net/browse/LIVE-13100)
---
=> fix: revert ignoring all swaps error

.github/workflows/test-ui-e2e-only-desktop.yml
- Speculos Tests
_Following this https://github.com/LedgerHQ/ledger-live/pull/7251, we switch back firebase environment to testing for Speculos tests_
- [Speculos Test run](https://github.com/LedgerHQ/ledger-live/actions/runs/9837912497)
--- …
=> [QAA-137][Speculos] Change back firebase env to testing

package.json, pnpm-lock.yaml, turbo.json
- ...
Upgrade Turborepo to 2.0.6
---
=> Upgrade Turborepo to 2.0.6

package.json, pnpm-lock.yaml, turbo.json
This reverts commit ef86807253e481e2d8abad578f870e7423650f2e, reversing changes made to c34461a51f6f2073bdacafe27f059e79f70d92e9.
- ...
--- …
=> Revert Turborepo 2

.changeset/fair-dogs-greet.md, libs/ledger-live-common/src/exchange/providers/swap.ts
- ...
Small fix that should only impacts swap providers terms&conditions list displayed. 
All components calling this changed function were already expecting the new async ...
---
=> fix: getAvailableProviders returns providers from CAL not from backup

.changeset/spotty-seals-admire.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, libs/ledger-live-common/src/exchange/swap/hooks/useUpdateMaxAmount.ts, libs/ledger-live-common/src/exchange/swap/index.ts, libs/ledger-live-common/src/exchange/swap/maybeKeepTronAccountAlive.ts, libs/ledgerjs/packages/errors/src/index.ts
- ...
Warning for swaps if trying to spend to much, and better max estimation when clicking on the button
[- **JIRA 13303**: ](https://ledgerhq.atlassian.net/browse/LIVE-13303)
---
=> feat: checks for tron max values from swap

.changeset/serious-emus-attack.md, .changeset/two-eyes-report.md, apps/ledger-live-desktop/src/renderer/actions/market.ts, apps/ledger-live-desktop/src/renderer/actions/settings.ts, apps/ledger-live-desktop/src/renderer/init.tsx, apps/ledger-live-desktop/src/renderer/middlewares/db.ts, apps/ledger-live-desktop/src/renderer/reducers/market.ts, apps/ledger-live-desktop/src/renderer/reducers/settings.ts, apps/ledger-live-desktop/src/renderer/screens/market/hooks/useMarket.ts, apps/ledger-live-desktop/src/renderer/screens/market/hooks/useMarketCoin.ts, apps/ledger-live-desktop/src/renderer/storage.ts, apps/ledger-live-mobile/src/actions/market.ts, apps/ledger-live-mobile/src/actions/types.ts, apps/ledger-live-mobile/src/context/LedgerStore.tsx, apps/ledger-live-mobile/src/db.ts, apps/ledger-live-mobile/src/index.tsx, apps/ledger-live-mobile/src/reducers/market.ts, apps/ledger-live-mobile/src/reducers/nft.ts, libs/ledger-live-common/src/market/utils/types.ts
- Market state stored in "DB"
- Uniformize Market state (moving some properties from settings to market)
Fix reset of market Store when refrshing app + uniformize market store actions
On both LLM and LLD
**DEMO**
https://github.com/LedgerHQ/ledger-live/assets/112866305/c927eb94-3c2f-4c47-8901-24bcd926ffe8
- **JIRA or GitHub link**: [LIVE-13259] 
--- …
=> 🐛 [BUGFIX] : Reset of market Store when refreshing app + uniformize market store actions

.changeset/gentle-maps-juggle.md, .pnpmfile.cjs, libs/ledger-live-common/package.json, libs/ledger-live-common/src/families/cosmos/signOperation.ts, pnpm-lock.yaml
- ...
`@zondax/ledger-cosmos-js` library declares a `crypto` package that I think was necessary before the RN upgrade to `0.73` where I removed our custom resolver. Since then we have provided node polyfills correctly and declaring this crypto library creates issues. We don't need it anymore for LL.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-13270
---
- **Any new …
=> fix: sign tx for injective

.changeset/gentle-maps-juggle.md, .pnpmfile.cjs, libs/ledger-live-common/package.json, libs/ledger-live-common/src/families/cosmos/signOperation.ts, pnpm-lock.yaml
- ...
Cherry pick https://github.com/LedgerHQ/ledger-live/pull/7293
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-13270
---
=> Release: Fix sign tx for injective

apps/ledger-live-desktop/src/newArch/WalletSync/Flows/Activation/02-DeviceActionStep.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/Flows/Activation/03-ActivationOrSynchroWithTrustchain.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/Flows/ManageInstances/03-DeleteInstanceWithTrustchain.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/Flows/ManageInstances/useInstances.ts, apps/ledger-live-desktop/src/newArch/WalletSync/__tests__/manageSynchronizedInstances.test.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/__tests__/manageYourBackup.test.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/__tests__/synchronize.test.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/__tests__/useFlows.test.ts, apps/ledger-live-desktop/src/newArch/WalletSync/hooks/useAddMember.ts, apps/ledger-live-desktop/src/newArch/WalletSync/hooks/useInitMemberCredentials.ts, apps/ledger-live-desktop/src/newArch/WalletSync/hooks/useRemoveMember.ts, apps/ledger-live-desktop/src/newArch/WalletSync/testHelper/helper.ts
- ...
Rework of : 
- AddMember
- RemoveMember
https://github.com/LedgerHQ/ledger-live/assets/112866305/ffda0ff2-4e4b-4094-aa24-40e0c6ec374a
---
=> [FEAT] : Integrate Trustchain logic in LedgerSync LLD - V2

apps/ledger-live-desktop/tests/fixtures/common.ts, apps/ledger-live-desktop/tests/specs/speculos/add.account.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/delete.account.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/receive.address.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/subAccount.spec.ts, apps/ledger-live-desktop/tests/utils/allureUtils.ts, apps/ledger-live-desktop/tests/utils/electronUtils.ts, apps/ledger-live-desktop/tests/utils/fileUtils.ts, apps/ledger-live-desktop/tests/utils/global.teardown.ts
=> [QAA-133] Refactoring of fixtures file for Playwright

.changeset/tame-donuts-float.md, libs/ui/packages/icons/scripts/build.js
- Should not have any impact on the UI
Remove the warning about the wrongly formatted jsx attributes: `vector-effect` and `stroke-width`
- **JIRA or GitHub link**: [LIVE-13158]
---
[LIVE-13158]: …
=> Fix generated icons attributes case

.changeset/gorgeous-timers-visit.md, libs/trustchain/src/__tests__/sdk/userRefusesRemoveMember.json, libs/trustchain/src/__tests__/sdk/userRefusesRemoveMember.ts, libs/trustchain/src/mock.sdk.test.ts, libs/trustchain/src/test-helpers/recordTrustchainSdkTests.ts, libs/trustchain/src/test-helpers/types.ts, libs/trustchain/src/test-scenarios/userRefusesRemoveMember.ts
- Should not have any impact on the UI
This tests the scenario where the app attempts to remove a member from the trustchain but the user cancels the interaction.
- [LIVE-13215]
---
[LIVE-13215]: …
=> 🧪 support(trustchain): Test refusing member removal on device

apps/ledger-live-desktop/src/newArch/WalletSync/hooks/type.hooks.ts, apps/ledger-live-desktop/src/newArch/WalletSync/hooks/useAddMember.ts, apps/ledger-live-desktop/src/newArch/WalletSync/hooks/useRestoreTrustchain.ts, apps/ledger-live-desktop/src/newArch/WalletSync/hooks/walletSync.hooks.ts
- ...
error handling in getMembers
---
=> [FIX]: error handling in getMembers

apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx
- ...
fix lld bad import for sentry in renderer
---
=> fix: lld bad import for sentry in renderer

.changeset/gorgeous-needles-repeat.md, libs/coin-modules/coin-tezos/src/bridge/getFeesForTransaction.ts, libs/coin-modules/coin-tezos/src/logic/estimateFees.ts
- ...
Fix prepareTransaction so it always returns a 0 amount at least.
- **JIRA or GitHub link**: [LIVE-13350]
---
[LIVE-13350]: https://ledgerhq.atlassian.net/browse/LIVE-13350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3M …
=> [XTZ] Fix prepareTransaction missing data

libs/coin-modules/coin-tezos/src/bridge/prepareTransaction.integ.test.ts, libs/coin-modules/coin-tezos/src/bridge/prepareTransaction.test.ts, libs/coin-modules/coin-tezos/src/bridge/synchronization.integ.test.ts, libs/coin-modules/coin-tezos/src/types/bridge.fixture.ts
- ...
Add some unit test for prepareTransaction only for `send` mode.
- **JIRA or GitHub link**: [LIVE-13350]
---
[LIVE-13350]: https://ledgerhq.atlassian.net/browse/LIVE-13350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …
=> [XTZ] Add unit test for prepareTransaction

apps/ledger-live-desktop/RELEASE_NOTES.md, apps/ledger-live-mobile/android/dapp-store/config.yaml
- ...
Update LLM and LLD release notes
---
=> chore(release): update LLD release note v2.84.0 and LLM v.3.4.0

.changeset/selfish-experts-double.md, .changeset/tricky-steaks-hope.md, apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx, apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/DeviceConnection/Searching.tsx, apps/ledger-live-desktop/tests/specs/syncOnboarding/manual.spec.ts, apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx, apps/ledger-live-mobile/src/components/ValidateOnDevice.tsx, apps/ledger-live-mobile/src/screens/BleDevicePairingFlow/index.tsx, libs/ledgerjs/packages/types-devices/README.md, libs/ledgerjs/packages/types-devices/src/index.ts
- Fix onboarding wrong redirection error when device connected.
- Fix onboarding error when device connected.
- **JIRA or GitHub link**: [LIVE-13353]
---
[LIVE-13353]: …
=> [LIVE-13353][LLD] Wrong onboarding redirection between Stax and Flex

.changeset/mighty-toys-enjoy.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx
- ...
reset toAmount on target change
https://ledgerhq.atlassian.net/browse/LIVE-13358
---
=> fix(live-13358): reset toAmount on target change

.changeset/big-dogs-grin.md, libs/coin-modules/coin-tron/src/bridge/getTransactionStatus.ts, libs/ledger-live-common/src/exchange/swap/hooks/useSwapTransaction.ts
- ...
- correct error messages in swap when input balance greater than available.
https://ledgerhq.atlassian.net/browse/LIVE-13376
---
=> [fix/LIVE-13376]: correct error messages in swap when input balance greater than available

libs/live-wallet/src/cloudsync/__tests__/cipher.test.ts
- live-wallet cloudsync tests
improve a bit the existing tests: the data can be arbitrary data, not a Uint8Array, so we use a complex object that also have emojis in it to ensure we don't have regression on these.
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/LIVE-13384
--- …
=> test(cloudsync): improve cipher tests

libs/trustchain/src/sdk.ts
- trustchain library
make sure that `withAuth` is invalidated if used multiple times in a row with different trustchain / credentials.
**scenario**
- member 1 is on LLD and creates trustchain
- member 2 is on web tools and join trustchain
- member 2 remove member 1
- member 1 automatically ejects
- member 1 joins again the trustchain
- ❌  old bad behavior: the wallet sync loop will experience JWT auth issue. until the app is restarted or that some jwt timeout occured.
- ✅  new expected behavior: the wallet sync should still be able to sync and restore accounts
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-13410
--- …
=> fix(trustchain): invalid jwt token if trustchain/memberCredentials changes

README.md
- ...
Adding a "Common setup errors" section to the README and including a fix for the out of sync Podfile.lock related error.
- **JIRA or GitHub link**: [LIVE-13430](https://ledgerhq.atlassian.net/browse/LIVE-13430)
--- …
=> chore: add common setup errors to readme

.changeset/many-moose-push.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/index.tsx
- ...
always show scrollbar in swap live
https://ledgerhq.atlassian.net/browse/LIVE-13282
---
=> feat: always show scrollbar in swap live

.changeset/breezy-cameras-worry.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/components/Success.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Activation/04-ActivationFinalStep.tsx, apps/ledger-live-desktop/src/renderer/actions/walletSync.ts, apps/ledger-live-desktop/src/renderer/reducers/walletSync.ts, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/WalletSync.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- ...
Polishing Success Screen + Add new attribute in store
---
=> 💄 [FEAT] : Polishing Success Screen + Add new attribute in store

apps/ledger-live-desktop/tests/component/modal.component.ts, apps/ledger-live-desktop/tests/enum/Tokens.ts, apps/ledger-live-desktop/tests/page/modal/add.account.modal.ts, apps/ledger-live-desktop/tests/specs/speculos/receive.address.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/subAccount.spec.ts
- ...
- Fixing Speculos SubAccount for XLM coins.
- Adding Scroll method in the coin/token selection
=> 🐛 [Speculos] [LLD] Fixing E2E SubAccount tests

.changeset/hot-files-itch.md, apps/ledger-live-desktop/src/renderer/drawers/NFTViewerDrawer/index.tsx
- NFT drawer
Fix ui issue in nft drawer description
|<img width="448" alt="Screenshot 2024-07-22 at 14 55 49" src="https://github.com/user-attachments/assets/d4862b2e-22c6-4dab-8c35-79d545ab6ce2">|<img width="448" alt="Screenshot 2024-07-22 at 14 55 39" src="https://github.com/user-attachments/assets/3db31b7e-8f2e-4380-a72e-42f56fd4d13c">|
- **JIRA or GitHub link**: [LIVE-7332](https://ledgerhq.atlassian.net/browse/LIVE-7332)
---
- …
=> :bug:fix(lld): word break issue in nft drawer

.changeset/healthy-jobs-own.md, apps/ledger-live-mobile/src/screens/Analytics/Allocation.tsx
- ...
Allocation display was overlapping content
- **JIRA or GitHub link**: [LIVE-12421] 
---
[LIVE-12421]: https://ledgerhq.atlassian.net/browse/LIVE-12421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
=> [FIX]: Allocation display was overlapping content

libs/trustchain/tests/test-helpers/recordTrustchainSdkTests.ts
- trustchain tests
fix race conditions that can make `pnpm trustchain e2e` fails with `socket hangs up` error in speculos due to not waiting the termination of all button actions that was performed.
--- …
=> test(trustchain): fix recordTrustchainSdkTests to await button actions

.changeset/smart-pots-crash.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx
- ...
set toNewTokenId to hash params
https://ledgerhq.atlassian.net/browse/LIVE-13395
---
=> fix(live-13395): set toNewTokenId to hash params

.github/workflows/test-ui-e2e-only-desktop.yml
- ...
- removing `show more` on the notif
- **JIRA or GitHub [QAA-78:](https://ledgerhq.atlassian.net/browse/QAA-78) 
---
=> 💄 Improving Slack Notif for E2E tests

.changeset/cold-weeks-decide.md, apps/ledger-live-desktop/src/renderer/components/OperationsList/AddressCell.tsx
- ...
Fix overflow in transaction ID.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-13459
---
=> fix(lld): transaction id overflow in operation detail

apps/ledger-live-desktop/tests/enum/Currency.ts, apps/ledger-live-desktop/tests/utils/speculos.ts
- ...
Select the last app version for the coinapp
- **JIRA or GitHub link**: [QAA-135](https://ledgerhq.atlassian.net/jira/software/c/projects/QAA/boards/887?assignee=712020%3A1787baec-823a-432f-bf1c-e8198ea89ef6&selectedIssue=QAA-135)
--- …
=> test: automatically get latest coin app versions

.changeset/moody-zebras-smell.md, libs/ledger-live-common/src/exchange/swap/hooks/useUpdateMaxAmount.ts
- ...
- tron swap: fix negative amountTo when max switch is on 
https://ledgerhq.atlassian.net/browse/LIVE-13475
---
=> fix(live-13475): trx amontFrom when maxSwap is used

.changeset/light-gorillas-report.md, .changeset/quiet-dancers-cough.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useTrustchainSdk.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useTrustchainSdk.ts
- ...
Made Trustchain SDK as Singleton
---
=> ⚡: [FEAT]: Made Trustchain SDK as Singleton

.changeset/selfish-lobsters-occur.md, apps/ledger-live-mobile/src/db.ts, apps/ledger-live-mobile/src/index.tsx
- ...
Save trustchain store in DB
---
=> [FEAT] : Save trustchain store in DB

apps/ledger-live-desktop/src/renderer/families/ton/CommentField.tsx, libs/coin-modules/coin-ton/src/getTransactionStatus.ts
- ...
Fix missing validation on ledger live mobile for transaction comment. 
---
=> Fix[ton] Comment validation on ledger-live-mobile

.github/workflows/test-mobile-e2e.yml, tools/actions/composites/setup-caches/action.yml, tools/actions/composites/setup-toolchain/action.yml
- ...
Upgrade `aws-actions/configure-aws-credentials` to v4
---
=> Upgrade aws-actions/configure-aws-credentials to v4

.changeset/khaki-apes-complain.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx
- ...
- handle no internet connection error 
https://ledgerhq.atlassian.net/browse/LIVE-13472
---
=> fix:(live-13472): no internet error in swap demo1 

.changeset/great-peaches-own.md, apps/ledger-live-desktop/src/renderer/components/Carousel/helpers.tsx, apps/ledger-live-desktop/src/renderer/hooks/useActionCards.tsx, apps/ledger-live-desktop/src/renderer/hooks/useNotifications.ts, apps/ledger-live-mobile/src/dynamicContent/ContentCardsCategory/Layout.tsx
- ...
The action cards on LLD were not registering the clicks and the flexible content cards on LLM always had the unique recipients at 0.
For LLD, the url property of the card had to be set for Braze to register the click (we set it to the card's id just so the value is not null).
For LLM, we had to log the impressions of the flexible cards so Braze could calculate the unique recipients.
- **JIRA or GitHub link**: [LIVE-12815] [LIVE-13258]
--- …
=> Fixed data tracking for Braze cards

apps/ledger-live-desktop/tests/enum/Currency.ts, apps/ledger-live-desktop/tests/page/speculos.page.ts, apps/ledger-live-desktop/tests/utils/speculos.ts, libs/ledger-live-common/src/load/speculos.ts
- ...
- Updating labels
- Adding findLatestAppCandidate function to have latest App version + latest firmware version
---
=> fix: Updating labels for ETH, ETC, ETH sep and ETH Hol

apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx
- ...
send feeStrategy and customFeeConfig as params
https://ledgerhq.atlassian.net/browse/LIVE-13513
---
=> fix(live-13513): send feeStrategy and customFeeConfig as params

.changeset/tame-lobsters-kiss.md, apps/ledger-live-mobile/src/context/LedgerStore.tsx
- ...
Save & Import Trustchain store
---
=> 💾 FIX]: Save & Import trustchain store

.changeset/curly-rules-greet.md, libs/ledgerjs/packages/keyring-eth/scripts/test-sign-transaction.ts
- ...
fix the `test-sign-transaction` script to use the new version of `context-module`.
---
=> 🐛 (keyring-eth): fix sign-transaction test script with new context-module

.changeset/funny-swans-check.md, .changeset/moody-socks-obey.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/shared.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/type.hooks.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useGetMembers.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Manage/Option.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Manage/index.tsx
- ...
- Get members from Trustchain using hook 
- Warning/Error/info Banner
---
=> [FEAT] : Get members from trustchain

.changeset/funny-swans-check.md, .changeset/moody-socks-obey.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/shared.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/type.hooks.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useAddMember.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useGetMembers.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/DeviceSelection/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Manage/Option.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Manage/index.tsx
- ...
Device issues on Activation flow WalletSync
https://github.com/user-attachments/assets/b3b1a09e-a818-46c8-a6da-641a9766363c
---
=> [FIX] : Device issues on Activation flow WalletSync

.changeset/nice-islands-clean.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/__tests__/synchronize.test.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/components/AlertError.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/components/AlertLedgerSyncDown.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/type.hooks.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useGetMembers.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useLedgerSyncInfo.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Manage/Option.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Manage/index.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/ManageInstances/useInstances.ts, apps/ledger-live-desktop/static/i18n/en/app.json, libs/live-wallet/src/cloudsync/api.ts, libs/trustchain/src/api.ts, libs/ui/packages/react/src/components/message/Alert/index.tsx
- ...
Add Ledger Sync Status check
- call to CloudSync
- Call to Trustchain
- ReactUI : Fix color (using palette) + add new icons
if both are successful then it's ok, else display an Error 
https://github.com/user-attachments/assets/4c44b625-dc88-496c-911b-02359e456be4
- **JIRA or GitHub link**:  [LIVE-13237]
https://www.figma.com/design/uI7PKnUK8nAZ0USyiEF3wQ/Wallet-Sync?node-id=9394-18034&t=bh2bNn13pNlILXon-0
--- …
=> ✨ [FEAT] :  Ledger Sync Status

.changeset/shiny-houses-play.md, apps/ledger-live-mobile/.unimportedrc.json, apps/ledger-live-mobile/src/components/RootNavigator/BaseOnboardingNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/types/BaseOnboardingNavigator.ts, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/Accounts/__integrations__/addAccount.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/WalletSyncNavigator.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/walletSyncActivation.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/walletSyncSettings.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Activation/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Activation/ActivationDrawer.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Synchronize/ChooseMethod.tsx, apps/ledger-live-mobile/src/reducers/types.ts, apps/ledger-live-mobile/src/screens/Onboarding/steps/accessExistingWallet.tsx
- WS 
Add sync method drawer for WS.
Also add walletSync navigator to onBoarding navigator so we can access to the WS screen from onboarding
https://github.com/user-attachments/assets/d5ff332e-9213-4b11-9c27-7d59e4505165
https://github.com/user-attachments/assets/5efc1743-3afd-41d0-9f93-be13e21b3742
- **JIRA or GitHub link**: [LIVE-12166](https://ledgerhq.atlassian.net/browse/LIVE-12166)
---
- …
=> :sparkles:feat(llm): add sync method selection drawer

libs/live-wallet/src/walletsync/__tests__/modules/accounts.test.ts, libs/live-wallet/src/walletsync/modules/accounts.ts
- wallet sync, accounts module
A test was added to guarantee there is no issue, notably no "duplication" of accounts, when a coin implementation decide to "implicitly migrate an account id". *(by implicit migration, we mean for instance that after a synchronisation of an account, the `.id` has changed, e.g. the version part of the id was increment. this is something totally legal for coin implementations)*.
In fact, the test has shown there **were a bug** 😆  so we also fix it here. The issue was not a duplication but a detection of both having removed + added, which would have resulted of account disappearing from the user perspective. The solution will now correctly work and account will be preserved (no dup, no remove). …
=> chore(walletsync): add resilience to implicit account id migrations

.changeset/ninety-seas-travel.md, apps/ledger-live-mobile/src/components/RootNavigator/types/WalletSyncNavigator.ts, apps/ledger-live-mobile/src/const/navigation.ts, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/WalletSync/WalletSyncNavigator.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/manageKey.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/ManageKey/Confirm.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/ManageKey/ManageKey.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Success/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/type.hooks.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useDestroyTrustchain.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Manage/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/ManageKey/DeletionSuccess.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/ManageKey/ManageKeyDrawer.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/ManageKey/useManageKeyDrawer.ts
- ...
Manage Key flow for WalletSync
https://github.com/user-attachments/assets/2c68fd15-8ebc-40bd-ba84-e72731bd9fab
- **JIRA or GitHub link**: [LIVE-12165] 
---
[LIVE-12165]: …
=> ✨ [FEAT] :  Manage Key flow for WalletSync

.changeset/little-shirts-remember.md, libs/coin-modules/coin-cardano/src/utils.ts
- ...
Update cardano pool
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-13483
---
=> update cardano pool

.changeset/three-pianos-accept.md, apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx, apps/ledger-live-mobile/src/screens/MyLedgerDevice/AppsList/AppInstallButton.tsx
- Now the installation of app on LLM will be tracked.
- Fix installation app event untracked bug.
- **JIRA or GitHub link**: [LIVE-13058]
---
[LIVE-13058]: https://ledgerhq.atlassian.net/browse/LIVE-13058?atlOrigin=ey …
=> [LIVE-13058][LLM] - Create an event to track Passkey/Security Key app download

.changeset/mean-toes-grab.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.tsx, libs/ledger-live-common/src/exchange/swap/maybeKeepTronAccountAlive.ts
- ...
- show tron keep alive message as error instead of warning
https://github.com/user-attachments/assets/0bb419dc-f623-4095-9026-6a1ec3b554ae
https://ledgerhq.atlassian.net/browse/LIVE-13533
--- …
=> fix(live-13533): display tron keep alive as error instead of warning

.changeset/red-carrots-explain.md, apps/ledger-live-desktop/src/renderer/components/CounterValue.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FormSelectors/FormInputs.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FormSelectors/ToRow.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/hooks/useSwapLiveAppQuoteState.ts
- ...
- get counterValue from swap-live-app in demo1 
https://ledgerhq.atlassian.net/browse/LIVE-13499
---
=> fix(live-13499): get counterValue from swap-live-app in demo1

.changeset/modern-books-jump.md, apps/ledger-live-desktop/src/renderer/components/FirebaseRemoteConfig.tsx, apps/ledger-live-mobile/src/components/FirebaseRemoteConfig.tsx
- ...
As we are at 0.01% of usage with 12 hours we can reduce the interval to pull FF.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-13552
---
=> Pull feature flags every hour for LLM and LLD

.changeset/giant-humans-brush.md, libs/ui/packages/native/src/components/Cards/BannerCard/index.tsx
- ...
The ellipsis wasn't displayed properly when the text is too long in the banner
|![Screenshot_2024-07-25-17-07-16-53_99c1b3bb631177f8a9e1379ae5b12ffe](https://github.com/user-attachments/assets/67bc56fb-2fbb-4e4a-8473-f51590056195)|![Screenshot_2024-07-25-17-01-59-25_99c1b3bb631177f8a9e1379ae5b12ffe](https://github.com/user-attachments/assets/9510e421-861f-4f6e-8820-82723e968b6f)|
|![Screenshot_2024-07-25-17-07-39-39_99c1b3bb631177f8a9e1379ae5b12ffe](https://github.com/user-attachments/assets/8d8e6ac6-80de-4bb2-8471-fe1c9eda6195)|![Screenshot_2024-07-25-17-01-39-26_99c1b3bb631177f8a9e1379ae5b12ffe](https://github.com/user-attachments/assets/20e4f63f-51f6-4458-9bab-850edcdba113)| …
=> fix(ui): banner component title now limited to two lines

.changeset/witty-ants-sin.md, libs/coin-modules/coin-tron/src/bridge/getTransactionStatus.ts
- ...
check for balance against spendable one instead off all for fee estimation errors
[- **JIRA or GitHub link**: ](https://ledgerhq.atlassian.net/browse/LIVE-13071)
---
=> fix: tron fee estimation

.github/workflows/test-ui-e2e-only-desktop.yml, apps/ledger-live-desktop/tests/fixtures/common.ts, apps/ledger-live-desktop/tests/misc/reporters/step.ts, apps/ledger-live-desktop/tests/utils/allureUtils.ts
=> [QAA-132] Add link to video of failed test to Allure report

.changeset/swift-poets-roll.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/walletSync.hooks.ts
- ...
Handle TrustchainOutdated
- **JIRA or GitHub link**: [LIVE-13543] 
---
[LIVE-13543]: https://ledgerhq.atlassian.net/browse/LIVE-13543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …
=> [ERROR]: Handle TrustchainOutdated

.changeset/ninety-seas-travel.md, .changeset/young-terms-grow.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/ManageInstances/01-ManageInstancesStep.tsx, apps/ledger-live-mobile/src/components/RootNavigator/types/WalletSyncNavigator.ts, apps/ledger-live-mobile/src/const/navigation.ts, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/manageInstances.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/ManageInstances/DeletionError.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/ManageInstances/ListInstances.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/TinyCard.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useWalletSyncAnalytics.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Manage/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/ManageInstances/ManageInstancesDrawer.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/ManageInstances/useManageInstanceDrawer.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/ManageKey/ManageKeyDrawer.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/ManageKey/useManageKeyDrawer.ts
- ...
Manage Synchronized Instances (Step 1)
https://github.com/user-attachments/assets/45253fdb-8ab7-41bb-9df5-c554e029d640
Auto-remove/Unsecured error 
https://github.com/user-attachments/assets/778a52cd-5b67-4fde-a9ec-e0a9014993a8
- **JIRA or GitHub link**: [LIVE-12159] 
--- …
=> ✨[FEAT]: Manage Synchronized Instances (Step 1  + Auto-remove/Unsecured error)

.changeset/silly-penguins-thank.md, apps/ledger-live-desktop/src/renderer/components/OnboardingAppInstall/InstallSetOfApps.tsx
- "install apps" part of the Stax/Flex onboarding
Before:
After:
- **JIRA or GitHub link**: [LIVE-13561] 
---
[LIVE-13561]: https://ledgerhq.atlassian.net/browse/LIVE-13561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMD …
=> [LIVE-13561][LLD] Sync onboarding "install apps" text not wrapping

CODEOWNERS
- ...
App installation in the onboarding is in the scope of the Device Experience team.
---
=> chore: update CODEOWNERS for OnboardingAppInstall

.changeset/funny-cooks-camp.md, apps/ledger-live-desktop/src/config/urls.ts, apps/ledger-live-desktop/src/renderer/drawers/SwapOperationDetails/index.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/DrawerFooter.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/ExchangeDrawer/SwapCompleted.tsx, libs/ledger-live-common/src/exchange/providers/swap.ts
- ...
Replace static data by CDN data
---
=> feat(LIVE-13555): replace static data by cdn data

apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Error/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Synchronize/PinCodeDisplay.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Synchronize/PinCodeInput.tsx
- ...
PinCode Display and Input
https://github.com/user-attachments/assets/b683ca0d-a4aa-4c8d-b48e-a6ea24fa5862
Error display 
- **JIRA or GitHub link**: [LIVE-12241] 
---
[LIVE-12241]: …
=> [FEAT]: PinCode Display / Input / error

.changeset/calm-elephants-rescue.md, libs/live-wallet/src/cloudsync/__tests__/sdk.test.ts, libs/live-wallet/src/cloudsync/api.ts, libs/live-wallet/src/cloudsync/sdk.ts, libs/live-wallet/src/walletsync/trustchainLifecyle.ts
- ...
Sending Trustchain id to the Cloud Sync API
- **JIRA or GitHub link**: [LIVE-13572]
---
[LIVE-13572]: https://ledgerhq.atlassian.net/browse/LIVE-13572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
=> Live-Wallet - Send trustchain id to cloudsync API

.github/workflows/test-ui-e2e-only-desktop.yml
=> ⏰ [CI] Updating E2E workflow - Enable broadcast once a week

.changeset/spotty-days-glow.md, libs/coin-modules/coin-ton/package.json, libs/ledger-live-common/package.json, pnpm-lock.yaml
- Prevent a bug with 3.3.0 of @ton/crypto during mobile build phase
Fix the version of @ton/crypto to 3.2.0
---
=> Bugfix - Force version `@ton/crypto` 3.2.0

.changeset/serious-clouds-burn.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/DrawerFooter.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- ...
Add exodus terms of acceptence
https://ledgerhq.atlassian.net/browse/LIVE-13571
---
=> feat(LIVE-13571): add different terms for exodus

.changeset/twelve-windows-melt.md, apps/ledger-live-mobile/src/index.tsx
- ...
See https://ledger.slack.com/archives/C02PQA777EU/p1722696183194819
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-13593
---
=> Make the app more resilient to FF wrong usage

apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useRemoveMember.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/ManageInstances/03-DeleteInstanceWithTrustchain.tsx, apps/ledger-live-mobile/__tests__/test-renderer.tsx, apps/ledger-live-mobile/src/actions/types.ts, apps/ledger-live-mobile/src/actions/walletSync.ts, apps/ledger-live-mobile/src/components/RootNavigator/types/WalletSyncNavigator.ts, apps/ledger-live-mobile/src/const/navigation.ts, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/WalletSync/WalletSyncNavigator.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/shared.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/ManageInstances/ListInstances.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/type.hooks.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useGetMembers.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useRemoveMember.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/walletSync.hooks.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Activation/ActivationInstructionDrawer.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/DeviceSelection/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/FollowInstructions/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/FollowInstructions/useFollowInstructions.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Manage/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/ManageInstances/DeletionInstructionDrawer.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/ManageInstances/DeletionSuccess.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/ManageInstances/ManageInstancesDrawer.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/ManageInstances/ManageInstancesProcess.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/ManageInstances/useManageInstanceDrawer.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/ManageKey/useManageKeyDrawer.ts, apps/ledger-live-mobile/src/reducers/index.ts, apps/ledger-live-mobile/src/reducers/types.ts, apps/ledger-live-mobile/src/reducers/walletSync.ts, apps/ledger-live-mobile/src/screens/Settings/General/WalletSyncRow.tsx
- ...
Manage instance with DeviceAction
https://github.com/user-attachments/assets/45319830-105d-4125-8881-23575555323f
---
=> [FEAT] : Manage instance with DeviceAction

patches/react-native-fast-pbkdf2@0.3.1.patch, pnpm-lock.yaml
- ...
Fix Ton Integration on Android
---
=> fix: ton integration on android build

.changeset/strange-eggs-brake.md, libs/live-wallet/jest.config.js, libs/live-wallet/src/cloudsync/sdk.ts, libs/live-wallet/src/walletsync/__mocks__/watchLoop.ts, libs/live-wallet/src/walletsync/createWalletSyncWatchLoop.test.ts, libs/live-wallet/src/walletsync/createWalletSyncWatchLoop.ts
Added unit tests to the `live-wallet` package to cover the `createWalletSyncWatchLoop`
Added a `advanceTimersByTimeAsync` test helper function to simulate some time passing by
- **JIRA or GitHub link**: [LIVE-13314]
--- …
=> Wallet Sync - Watch Loop Unit Tests

libs/coin-modules/coin-stellar/jest.config.js, libs/coin-modules/coin-stellar/jest.integ.config.js, libs/coin-modules/coin-stellar/package.json, libs/coin-modules/coin-stellar/src/broadcast.test.ts, libs/coin-modules/coin-stellar/src/buildTransaction.integ.test.ts, libs/coin-modules/coin-stellar/src/signOperation.test.ts, libs/coin-modules/coin-stellar/src/synchronization.integ.test.ts, libs/coin-modules/coin-stellar/src/types/bridge.fixture.ts, libs/coin-modules/coin-tron/src/bridge/synchronization.integ.test.ts, pnpm-lock.yaml
- ...
This PR adds only test: integration and unit.
- **JIRA or GitHub link**: [LIVE-13229]
---
[LIVE-13229]: https://ledgerhq.atlassian.net/browse/LIVE-13229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …
=> chore: add some test (integ and unit)

.changeset/afraid-bats-join.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/components/Error.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useQRCode.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useWalletSyncAnalytics.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Synchronize/05-PinCodeError.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Synchronize/index.tsx, apps/ledger-live-desktop/src/renderer/reducers/walletSync.ts, apps/ledger-live-desktop/static/i18n/en/app.json
- ...
Add Error screen when PinCode doesn't match
https://github.com/user-attachments/assets/2b94d808-37dc-491c-84b0-f7b3a44e6bbe
---
=> [FEAT]: Add Error screen when PinCode doesn't match

.changeset/many-hats-push.md, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/walletSyncStatus.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/AlertLedgerSyncDown.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/type.hooks.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useLedgerSyncStatus.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Manage/index.tsx
- ...
Add LedgerSync status banner + hook
- **JIRA or GitHub link**: [LIVE-13236] 
---
[LIVE-13236]: https://ledgerhq.atlassian.net/browse/LIVE-13236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …
=> [FEAT]: Add LedgerSync status banner + hook

libs/live-wallet/src/walletsync/__mocks__/README.md, libs/live-wallet/src/walletsync/__tests__/specific.test.ts, libs/live-wallet/src/walletsync/modules/README.md
- no impact, just doc
This PR contains improvements that facilitate the creation of a new WalletSync module.
it was made in context of this tutorial: https://ledgerhq.atlassian.net/wiki/spaces/WXP/pages/4862509091/TODO+how+to+develop+a+new+WalletSync+module
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-13315
--- …
=> chore(walletsync): polish modules

apps/ledger-live-desktop/tests/page/account.page.ts
- ...
Fix subAccount test (speculos)
---
=> ✨ fix subAccount

apps/ledger-live-desktop/src/renderer/Default.tsx, apps/ledger-live-desktop/src/renderer/components/TopBar/ActivityIndicator.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/WalletSync.tsx, apps/ledger-live-mobile/__tests__/test-renderer.tsx, apps/ledger-live-mobile/src/components/QueuedDrawer.tsx, apps/ledger-live-mobile/src/components/RootNavigator/LandingPagesNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/SettingsNavigator.tsx, apps/ledger-live-mobile/src/components/globalSyncRefreshControl.tsx, apps/ledger-live-mobile/src/context/AuthPass/index.tsx, apps/ledger-live-mobile/src/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/components/StepFlow.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/useAddAccountViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Market/screens/MarketList/components/BottomSection/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/FollowInstructions/useFollowInstructions.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/ManageInstances/useManageInstanceDrawer.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/ManageKey/useManageKeyDrawer.ts, apps/ledger-live-mobile/src/screens/Modals/index.tsx, apps/ledger-live-mobile/src/screens/MyLedgerDevice/AppsScreen.tsx, apps/ledger-live-mobile/src/screens/Portfolio/ReadOnly/index.tsx, apps/ledger-live-mobile/src/screens/WalletCentricAsset/AssetMarketSection.tsx
- ...
just change imports of ~/newArch to LL(M/D) to maintain consistency 
---
=> :art:fix(llm-lld): update imports of newArch

.changeset/loud-bikes-rest.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useQRCode.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/__integrations__/shared.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useQRCodeHost.ts
- ...
Throw error to avoid Error: qrcode websocket prematurely closed on QRCode host
- **JIRA or GitHub link**: [LIVE-13637] 
---
[LIVE-13637]: https://ledgerhq.atlassian.net/browse/LIVE-13637?atlOrigin=eyJpIjoiNWRkNT …
=> [FIX]: Throw error to avoid Error: qrcode websocket prematurely closed on QRCode host

apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/ManageInstances/01-ManageInstancesStep.tsx
- ...
When there is many instances / reduced app screen we couldn't scroll to the last card. 
https://github.com/user-attachments/assets/ceae85bb-6291-4adc-946b-5a8d1adc89df
---
=> :bug:fix(lld): ws manage instances scroll

libs/ledger-live-common/src/exchange/providers/swap.ts
- ...
Update signature of exodus provider in the fallback data that is embedded in Ledger Live.
No code, data change only to align with CAL.
- **JIRA or GitHub link**: [LIVE-13614](https://ledgerhq.atlassian.net/browse/LIVE-13614)
--- …
=> fix(lld): update exodus signature in fallback data

.changeset/eighty-rabbits-hope.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useGetMembers.ts, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useGetMembers.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Manage/index.tsx, libs/trustchain/src/errors.ts
- ...
Fix GetMember :Error: [useGetMembers, null] data is undefined
---
=> 🐛 [FIX]: GetMember :Error: [useGetMembers, null] data is undefined

.changeset/shaggy-avocados-suffer.md, apps/ledger-live-desktop/src/renderer/components/CustomImage/ImportImage.tsx
- LLD Custom lock screen: picture selection
- **JIRA or GitHub link**: [LIVE-12513]
---
[LIVE-12513]: https://ledgerhq.atlassian.net/browse/LIVE-12513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
=> [LIVE-12513] Fix(lld/customlockscreen): disallow selection of gifs

.changeset/orange-balloons-poke.md, libs/live-wallet/src/walletsync/__tests__/modules/accounts.test.ts, libs/live-wallet/src/walletsync/createWalletSyncWatchLoop.test.ts, libs/live-wallet/src/walletsync/modules/accounts.ts
- ...
Added unit tests to the `live-wallet` package to cover the non imported accounts from the `accounts` module
- **JIRA or GitHub link**: [LIVE-13447]
---
[LIVE-13447]: …
=> Wallet Sync - Non imported accounts Unit Tests

.changeset/heavy-bees-poke.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/__tests__/walletSync.test.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- ...
Change wording for WS activation LLD 
- **JIRA or GitHub link**:[LIVE-13579](https://ledgerhq.atlassian.net/browse/LIVE-13579) 
---
[LIVE-13579]: https://ledgerhq.atlassian.net/browse/LIVE-13579?atlOrigin=eyJpIj …
=> :bug:fix(lld): WS wording

apps/web-tools/trustchain/components/AppMemberRow.tsx, apps/web-tools/trustchain/components/IdentityManager.tsx
- web tools only
the real member names like `Mac 29bc7` or `Android 34` will be displayed in the list of members of the web tools.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-13568
---
=> chore(web-tools): show real member name in trustchain web tools

.github/workflows/test-ui-e2e-only-desktop.yml
=> [QAA-151] Fix Desktop e2e nightly slack notif color

.changeset/beige-hornets-judge.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/Migrations/SwapMigrationUI.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx
- ...
Added demo3 manifest id to allow testing on demo3 ppr/stg without local manifest
---
=> feat: add demo3 manifest

libs/ledgerjs/packages/hw-app-exchange/src/ReturnCode.ts
=> fix: typo in exchange-app

apps/ledger-live-desktop/tests/enum/AppInfos.ts, apps/ledger-live-desktop/tests/enum/Currency.ts, apps/ledger-live-desktop/tests/fixtures/common.ts, apps/ledger-live-desktop/tests/page/modal/add.account.modal.ts, apps/ledger-live-desktop/tests/page/modal/send.modal.ts, apps/ledger-live-desktop/tests/specs/speculos/subAccount.spec.ts
- ...
Refacto currency for speculos tests
CI run: https://github.com/LedgerHQ/ledger-live/actions/runs/10453216836
- **JIRA or GitHub link**: [QAA-166](https://ledgerhq.atlassian.net/browse/QAA-166)
---
[QAA-166]: …
=> [QAA-166] Refacto currency for speculos tests

.github/workflows/test-ui-e2e-only-desktop.yml
=> [QAA] Updating slack notif emoji

.changeset/beige-eyes-shout.md, libs/trustchain/mocks/scenarios/addSameMemberMultipleTimes.json, libs/trustchain/src/mockSdk.ts, libs/trustchain/src/sdk.ts, libs/trustchain/tests/scenarios/addSameMemberMultipleTimes.ts
Prevent adding several time the same member
- **JIRA or GitHub link**: [LIVE-13545]
---
[LIVE-13545]: https://ledgerhq.atlassian.net/browse/LIVE-13545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJw …
=> Trustchain - Prevent duplicate add members

.changeset/soft-windows-know.md, apps/ledger-live-desktop/src/renderer/components/WebPTXPlayer/TopBar.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/components/WebPTXPlayer/index.tsx, apps/ledger-live-mobile/src/locales/en/common.json
- ...
Replacing a hardcoded value for "Quote" with new common translations in LLM and LLD, in WebPTXPlayer.
- **JIRA or GitHub link**: [LIVE-9270](https://ledgerhq.atlassian.net/browse/LIVE-9270)
---
[LIVE-9270]: …
=> chore: add translation for back to quote CTA in WebPTXPlayer

.changeset/thirty-coats-laugh.md, apps/ledger-live-desktop/static/i18n/en/app.json
- ...
Minor copy updates for LedgerSync
- **JIRA or GitHub link**: [LIVE-13760] 
---
[LIVE-13760]: https://ledgerhq.atlassian.net/browse/LIVE-13760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …
=> 📝 [FIX]: Minor copy updates for LedgerSync

.changeset/fresh-cows-wait.md, apps/ledger-live-mobile/src/components/MarketQuickActions/index.tsx, apps/ledger-live-mobile/src/components/TabBar/TransferDrawer.tsx, apps/ledger-live-mobile/src/hooks/useQuickActions.ts, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/Market/screens/MarketDetail/index.tsx, apps/ledger-live-mobile/src/screens/Portfolio/PortfolioQuickActionsBar.tsx
- ...
Now market quick actions link to a route specific to the current coin. This PR also adds typechecking to the quick actions routes and fixed the routes that weren't matching `BaseNavigatorStackParamList`. This hopefully fixed most of the issues mentioned in [LIVE-10755].
- [LIVE-10755]
- [LIVE-10741]
--- …
=> 🤑 [FEAT] Add currency support to quick actions

.changeset/fair-pandas-leave.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Activation/index.tsx, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/scanQRCode.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/synchronizeWithQrCode.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/walletSyncSettings.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Synchronize/DrawerHeader.tsx
- ...
Minor copy updates for LedgerSync (LLM)
- **JIRA or GitHub link**: [LIVE-13758] 
---
[LIVE-13758]: https://ledgerhq.atlassian.net/browse/LIVE-13758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …
=> 📝 [FIX]:Minor copy updates for LedgerSync (LLM)

apps/ledger-live-desktop/tests/utils/allureUtils.ts, apps/ledger-live-desktop/tests/utils/speculos.ts
- ...
Improving Allure report:
- Adding Screenshot of the speculos display on failure
- **JIRA or GitHub link**: [QAA-143](https://ledgerhq.atlassian.net/browse/QAA-143)
---
[QAA-143]: …
=> [QAA-143] Improving Allure report

.changeset/tame-carrots-cry.md, apps/ledger-live-mobile/src/hooks/useQuickActions.ts
- ...
The receive market quick action will redirect to the account creation step of the receive flows when no account is available for the given currency.
| ![Simulator Screenshot - iPhone SE (3rd generation) - 2024-08-20 at 16 43 32](https://github.com/user-attachments/assets/f8874e10-cf6f-46a7-9a57-5be2ab626371) | ![Simulator Screenshot - iPhone SE (3rd generation) - 2024-08-20 at 16 42 51](https://github.com/user-attachments/assets/28849b4a-1840-4e80-9a09-4b3120b46f54) |
- [LIVE-10740]
--- …
=> 🤲 [FEAT] Create accounts with the receive market quick action

apps/ledger-live-desktop/src/renderer/analytics/segment.ts, apps/ledger-live-desktop/src/renderer/components/MainSideBar/index.tsx, apps/ledger-live-desktop/src/renderer/screens/card/CardPlatformApp.tsx, apps/ledger-live-desktop/src/renderer/screens/card/index.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/index.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledger-live-common/src/wallet-api/constants.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- Support new card manifest Id.
https://ledgerhq.atlassian.net/browse/LIVE-13740
https://ledgerhq.atlassian.net/browse/LIVE-13713
--- …
=> feature: add new card dapp in LLD entry point

.changeset/new-dolphins-drum.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useTrustchainSdk.ts
- ...
More precise Instances names for LLD Instances
---
=> ✏️[FIX]:  More precise Instances names for LLD Instances

.github/workflows/test-mobile-e2e.yml, apps/ledger-live-mobile/e2e/xray.formater.sh
- Xray export field on [action](https://github.com/LedgerHQ/ledger-live/actions/workflows/test-mobile-e2e.yml) page
Adding the possibility to send Tests results to Xray on the CI
---
=> [QAA-119][Detox] Add Xray export of result

apps/ledger-live-desktop/src/renderer/drawers/OperationDetails/index.tsx, apps/ledger-live-desktop/tests/page/drawer/drawer.ts
- ...
Adding data-testid for e2e test
---
=> fix(speculos): adding new data-testid

.changeset/poor-snails-thank.md, libs/ledger-live-common/src/exchange/swap/hooks/useSwapTransaction.ts
- ...
show gasPrice as error instead of warning
https://ledgerhq.atlassian.net/browse/LIVE-13764
---
=> fix(live-13764): show gasPrice as error instead of warning

.changeset/rude-wombats-begin.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx
- ...
Uses a random Native Segwit address to better estimate BTC swaps
[- **JIRA or GitHub link**: ](https://ledgerhq.atlassian.net/browse/LIVE-9975)
---
=> fix: uses native segwit empty address to compute btc fees

apps/ledger-live-desktop/tests/specs/speculos/manage.ledgersync.spec.ts
- ...
- Fix LedgerSync test
- Adding TMS Link
---
=> Fix LedgerSync test - Speculos + Adding TMS link

apps/ledger-live-desktop/tests/component/modal.component.ts, apps/ledger-live-desktop/tests/page/modal/add.account.modal.ts
=> [e2e] Added missing step descriptions

.changeset/three-melons-beam.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/ManageKey/Confirm.tsx
- ...
Update ManageKey flow copy
- **JIRA or GitHub link**: [LIVE-13828]
---
[LIVE-13828]: https://ledgerhq.atlassian.net/browse/LIVE-13828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …
=> [FEAT]: Update ManageKey flow copy

.changeset/curly-seahorses-collect.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FeesDrawerLiveApp/index.tsx
- ...
fixed swap live app fee drawer error check sync
[- **JIRA or GitHub link**: ](https://ledgerhq.atlassian.net/browse/LIVE-13701)
---
=> fix: swap live app fee drawer error check sync

.changeset/ten-files-live.md, libs/env/src/env.ts, libs/ledger-live-common/src/exchange/swap/utils/isIntegrationTestEnv.ts, libs/ledger-live-common/src/hw/actions/startExchange.ts
- ...
added new env to bypass app requirements to init swaps
---
=> feat: added new env to bypass app requirements to init swaps

.changeset/stupid-dodos-bow.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/__tests__/shared.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/components/Error.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/components/GenericStatusDisplay.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useFlows.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useLedgerSyncAnalytics.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Activation/01-CreateOrSynchronizeStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Activation/04-ActivationFinalStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Activation/index.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Manage/index.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/ManageBackup/01-ManageBackupStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/ManageBackup/02-DeleteBackupStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/ManageBackup/03-FinalStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/ManageInstances/01-ManageInstancesStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/ManageInstances/04-DeletionError.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/ManageInstances/04-DeletionFinalStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Synchronize/01-SyncModeStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Synchronize/02-QRCodeStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Synchronize/03-PinCodeStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Synchronize/04-SyncFinalStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Synchronize/05-PinCodeError.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Synchronize/05-UnbackedError.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Synchronize/06-ActivationAlreadyCreatedSame.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Synchronize/07-ActivationAlreadyCreatedOther.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Synchronize/index.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/router.tsx, apps/ledger-live-desktop/src/renderer/analytics/segment.ts, apps/ledger-live-desktop/src/renderer/reducers/walletSync.ts, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/WalletSync.tsx
- ...
Update Analytics LedgerSync LLD
- **JIRA or GitHub link**: [LIVE-13837] 
---
[LIVE-13837]: https://ledgerhq.atlassian.net/browse/LIVE-13837?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ …
=> [BUGFIX]: Update Analytics LedgerSync LLD

apps/ledger-live-desktop/tests/page/drawer/ledger.sync.drawer.ts, apps/ledger-live-desktop/tests/page/settings.page.ts
- ...
This PR addresses an issue where interactions with locators in the UI could fail if the locators were not immediately visible. The changes introduce a wait mechanism to ensure that locators are visible before any interaction is attempted. …
=> Fix: Add wait for locators to be visible before interaction

apps/ledger-live-desktop/tests/fixtures/common.ts, apps/ledger-live-desktop/tests/page/speculos.page.ts, apps/ledger-live-desktop/tests/utils/allureUtils.ts, libs/ledger-live-common/.unimportedrc.json, libs/ledger-live-common/src/e2e/speculos.ts
- LLD Speculos tests
_We need to share LLD Speculos device managing code with LLM to use it wuth Detox_
- **Speculos tests execution**: [Link](https://github.com/LedgerHQ/ledger-live/actions/runs/10633068770) 
---
=> [QAA-181] Made speculos spawning code common for LLM use

.changeset/four-planes-allow.md, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/FollowInstructions/index.tsx
- ...
Wrong Device name was displayed in FollowInstructions
- **JIRA or GitHub link**: [LIVE-13883] 
---
[LIVE-13883]: https://ledgerhq.atlassian.net/browse/LIVE-13883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …
=> [FIX]: Wrong Device name was displayed in FollowInstructions

.changeset/pink-rings-deny.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx
- ...
New properties to tell evm without EIP1559 they have a drawer + removed gasOption cache creating crashes when switching evm chains. No regression as we fixed feeData correctly fetching fast values now
[- **JIRA or GitHub link**: ](https://ledgerhq.atlassian.net/browse/LIVE-13862)
--- …
=> fix: persistant gasOptions between evm chains creating crashes

.changeset/polite-donuts-peel.md, apps/ledger-live-desktop/src/newArch/features/AnalyticsOptInPrompt/hooks/useCommonLogic.tsx, apps/ledger-live-desktop/src/newArch/features/AnalyticsOptInPrompt/hooks/useDisplayOnPortfolio.tsx, apps/ledger-live-desktop/src/newArch/features/AnalyticsOptInPrompt/screens/VariantA/Main/index.tsx, apps/ledger-live-desktop/src/newArch/features/AnalyticsOptInPrompt/screens/VariantB/Analytics/index.tsx, apps/ledger-live-desktop/src/newArch/features/AnalyticsOptInPrompt/screens/VariantB/PersonalRecommendations/index.tsx, apps/ledger-live-desktop/src/newArch/features/AnalyticsOptInPrompt/screens/VariantB/index.tsx, apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/Welcome/index.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Accounts/Export.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Accounts/index.tsx
- Opt In prompt
- Settings rows
Make the optin prompt scrollable if necessary and fix an issue that made export to csv row from settings disappeared when LS activated 
Also correct variable name from `analitycs` to `analytics`
- **JIRA or GitHub link**: [LIVE-13662](https://ledgerhq.atlassian.net/browse/LIVE-13662)
---
- …
=> :bug:fix(lld) : opt-in prompt and export account tx row setting

.changeset/small-penguins-allow.md, libs/coin-modules/coin-cosmos/src/api/Cosmos.unit.test.ts, pnpm-lock.yaml
=> Chore/regen pnpmlock + fix axios type in cosmos unit test

.changeset/sixty-eagles-watch.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/DeviceActions/FollowStepsOnDevice.tsx
- ...
Fix Animation color on FollowSteps
---
=> [FIX]: Animation color on FollowSteps

.changeset/forty-geese-hug.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/components/GenericStatusDisplay.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useLedgerSyncAnalytics.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Activation/01-CreateOrSynchronizeStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Activation/04-LoadingStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/ManageBackup/03-FinalStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Synchronize/05-UnbackedError.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Synchronize/07-ActivationAlreadyCreatedOther.tsx, apps/ledger-live-desktop/src/renderer/analytics/segment.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/ManageKey/ManageKey.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Success/index.tsx
Improved Ledger Sync Analytics on LLD
- **JIRA or GitHub link**: [LIVE-13905] [LIVE-13881]
---
[LIVE-13905]: https://ledgerhq.atlassian.net/browse/LIVE-13905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZ …
=> LLD - Ledger Sync Analytics Improvements

.changeset/soft-dolls-sparkle.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/AnalyticsOptInPrompt/variantA/Main.tsx
- ...
https://github.com/user-attachments/assets/680a09b3-7c77-47eb-980d-42e97cf45644
- **JIRA or GitHub link**: [LIVE-13777] 
---
[LIVE-13777]: https://ledgerhq.atlassian.net/browse/LIVE-13777?atlOrigin=eyJpIjoiNWRkN …
=> [FIX]: Update Copy and fix color on Analytics Opt-in

.changeset/mighty-yaks-yawn.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx
=> feat: passthrough selected currency for demo3 if exists

.changeset/quick-berries-type.md, apps/ledger-live-mobile/src/components/RootNavigator/WalletConnectLiveAppNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/types/BaseNavigator.ts, apps/ledger-live-mobile/src/components/RootNavigator/types/WalletConnectLiveAppNavigator.ts
- Wallet Connect deeplink on LLM
Pass some additional params to wallet-connect live-app when receiving a request, allowing proper loading screen on the live-app
- **JIRA or GitHub link**: LIVE-13660
---
=> feat(LLM): pass some additional params to wallet-connect live-app when receiving a request [LIVE-13660]

.changeset/fresh-cows-float.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- ...
- send the network down event to demo3
- update error messages for transaction and fees drawers
https://ledgerhq.atlassian.net/browse/LIVE-13868 
https://ledgerhq.atlassian.net/browse/LIVE-13867
--- …
=> feat(live-13868): error messages for transaction and fees drawers

.changeset/cool-chairs-suffer.md, libs/ledger-live-common/src/families/casper/bridge/bridgeHelpers/addresses.ts, libs/ledger-live-common/src/families/casper/utils.unit.test.ts
- ...
Previously, when the address was obtained from the public key, it was incorrectly formatted. It's fixed in this PR.
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/LIVE-13802
---
=> bugfix(casper): adjust address from public key

.changeset/sharp-garlics-cover.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FeesDrawerLiveApp/index.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx
- ...
I was doing it wrong 
- **JIRA or GitHub link**:  LIVE 1392
---
=> fix: moved prepareTransaction before getting status

.changeset/khaki-deers-kick.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx
- ...
In demo 3 params were moved an 2 were forgotten. Putting them back
https://ledgerhq.atlassian.net/browse/LIVE-13955
---
=> fix(LIVE-13955): put back params forgotten to live app

apps/ledger-live-desktop/tests/specs/onboarding/setup-device.spec.ts
- ...
Let's try to deactivate CSS animations to have a stable e2e test with screenshot on Device Selection.
See: https://ledger.slack.com/archives/C02LP0WL39P/p1725957285511059
---
=> LLD - Deactivate css animation for screenshots on device selection

.changeset/eighty-pears-run.md, apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/CompleteExchange/TransactionBroadcastedContent.tsx
- ...
Fixes View Details button for Swap Live App
[Ticket](https://ledgerhq.atlassian.net/browse/LIVE-13987)
---
=> hotfix: swap button fix

.changeset/orange-tomatoes-yell.md, apps/ledger-live-desktop/package.json, pnpm-lock.yaml
- Non reg test when release
Upgrade Electron 30 to 32
No breaking changes that impact our stack
Release notes : 
- https://www.electronjs.org/blog/electron-31-0
- https://www.electronjs.org/blog/electron-32-0
- https://releases.electronjs.org/releases/stable
- **JIRA or GitHub link**: [LIVE-13035] 
--- …
=> chore: 🔧 Update Electron to v32

apps/ledger-live-desktop/tests/specs/speculos/manage.ledgersync.spec.ts
=> Updated wordings shown on Nano to fix LedgerSync test

.github/workflows/build-and-test-external.yml
=> Fix external contributions

.github/workflows/build-and-test-external.yml, .github/workflows/build-and-test-pr.yml
=> fix: restore not canceled condition for ok job

.github/workflows/build-and-test-pr.yml, .github/workflows/build-and-test-push.yml
- ...
Today we can bypass the required status check if you cancel a job (it will be considered a success).
---
=> Prevent PR with cancelled jobs to be merged

.changeset/tame-tigers-end.md, apps/ledger-live-desktop/src/renderer/screens/market/hooks/useMarket.ts
- ...
Fix Search and Starred filters on Market Page 
https://github.com/user-attachments/assets/fe6563f7-d15d-49b1-8a0f-25cae8746809
- **JIRA or GitHub link**: [LIVE-14100] 
---
[LIVE-14100]: …
=> fix: 🐛 Market Filters

.changeset/smooth-ears-learn.md, apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/CompleteExchange/Body.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx
- ...
- add missing custom method for demo3
https://ledgerhq.atlassian.net/browse/LIVE-14094
---
=> fix: drawer loading state on succes

.github/workflows/build-and-test-pr.yml, .github/workflows/test-cli-reusable.yml, .github/workflows/test-libs-reusable.yml, .github/workflows/test-web-tools-reusable.yml, libs/ledger-live-common/src/families/hedera/bridge.integration.test.ts
- ...
Restore missing workflows:
- Test cli
- Test Web app
- Test doc
- Codechecks libs
---
=> Restore missing workflows

.changeset/tiny-pigs-sit.md, apps/ledger-live-mobile/__tests__/jest-setup.js, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Synchronize/ScanQrCode.tsx
- Camera scan qr code
Switch from expo-camera to expo-camera/next. There was an issue with expo-camera on the focus which has been fixed in /next : https://docs.expo.dev/versions/v50.0.0/sdk/camera-next
https://github.com/user-attachments/assets/0a92f398-3e45-4f1f-b371-ee9c7e3a87ba
- **JIRA or GitHub link**: [LIVE-14123](https://ledgerhq.atlassian.net/browse/LIVE-14123)
---
- **Any new …
=> :bug:(llm): camera doesn't refocus when scanning for LS on IOS

.github/workflows/build-and-test-push.yml
=> fix ci on push

.changeset/pretty-buttons-worry.md, apps/ledger-live-desktop/src/config/urls.ts, apps/ledger-live-desktop/src/renderer/families/tezos/DelegateFlowModal/steps/StepSummary.tsx, apps/ledger-live-desktop/src/renderer/families/tezos/operationDetails.tsx, apps/ledger-live-desktop/src/renderer/hooks/useLocalizedUrls/index.ts, apps/ledger-live-desktop/src/renderer/hooks/useLocalizedUrls/useLocalizedUrls.test.tsx, apps/ledger-live-desktop/src/renderer/modals/Send/fields/DomainErrorHandlers.tsx, apps/ledger-live-mobile/src/families/tezos/operationDetails.ts, apps/ledger-live-mobile/src/screens/SendFunds/DomainErrorHandlers.tsx, apps/ledger-live-mobile/src/utils/urls.tsx
- URLs
Update HC links from zendesk to salesforce
useLocalizedUrl has been updated to work with these new links. However if you already came in the support web page the localisation won't change anything because the site keep the previous langage. So useful only for the first time.
Some old harcoded urls remains on blockchain side and already redirect to nothing
- **JIRA or GitHub link**: [LIVE-13922](https://ledgerhq.atlassian.net/browse/LIVE-13922)
---
- **The PR has been tested** thoroughly, and …
=> :alien:fix(ll): update HC links

.changeset/mean-pears-wash.md, apps/web-tools/package.json, docs/package.json, pnpm-lock.yaml
- ...
To set a “High severity” alert on the Next package
See [here](https://github.com/advisories/GHSA-gp8f-8m3g-qvj9)
Just patch on a version `>= 14.2.10`
#7834 
---
=> chore: 📦 Update Next version to fix Next.js Cache Poisoning

apps/ledger-live-desktop/src/renderer/families/evm/SendAmountFields/LowGasAlertBuyMore.tsx, apps/ledger-live-desktop/tests/component/layout.component.ts
- ...
Fixing e2e test
The data-test-Id was removed in this PR: https://github.com/LedgerHQ/ledger-live/pull/7782
---
=> 🐛 fixing e2e tests

.changeset/giant-pants-deliver.md, apps/ledger-live-mobile/src/components/RootNavigator/types/CustomErrorNavigator.ts, apps/ledger-live-mobile/src/components/WebPTXPlayer/CustomHandlers.ts, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/CustomError/index.tsx
- ...
Adds error handling for LLM for exchange interactions
[Ticket](https://ledgerhq.atlassian.net/browse/LIVE-13294)
---
=> feat: error handling llm

.changeset/unlucky-seals-remember.md, apps/ledger-live-desktop/src/renderer/components/UTXOAddressAlert.tsx, apps/ledger-live-desktop/src/renderer/modals/Receive/steps/StepReceiveFunds.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- ...
UTXO disclaimer : Not same UI as Figma because we still use old Design
https://github.com/user-attachments/assets/d5960036-3a70-4b18-a5f1-07e4b3b859c6
- **JIRA or GitHub link**: [LIVE-14054] 
---
[LIVE-14054]: …
=> feat: 💄 Add UTXO disclaimer on Bitcoin like coins

.changeset/curvy-worms-serve.md, apps/ledger-live-mobile/src/screens/Onboarding/steps/accessExistingWallet.tsx
- ...
Onboarding Skip prompt drawer for LedgerSync
https://github.com/user-attachments/assets/760b4c96-8fa9-45c9-b742-c4f96759c9d3
- **JIRA or GitHub link**: [LIVE-14191] 
---
[LIVE-14191]: …
=> feat: 💄 Onboarding Skip prompt drawer for LedgerSync

.changeset/smart-mails-refuse.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/__tests__/synchronize.test.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Manage/index.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Synchronize/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- LS sync flow and copy
Update sync flow when instance already in a trustchain. Update copy too
https://github.com/user-attachments/assets/f5eac803-51d7-4fe0-ab67-409497f71f04
- **JIRA or GitHub link**: [LIVE-14196](https://ledgerhq.atlassian.net/browse/LIVE-14196)
--- …
=> :lipstick:(lld): update sync flow and copy for LS

.changeset/cyan-lamps-unite.md, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/components/StepFlow.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Manage/index.tsx
- ...
Update Sync flow
- **JIRA or GitHub link**: [LIVE-14194] 
---
[LIVE-14194]: https://ledgerhq.atlassian.net/browse/LIVE-14194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …
=> feat: 💄 Update Sync flow LedgerSync

.changeset/great-phones-lick.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/__tests__/manageSynchronizedInstances.test.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/__tests__/manageYourBackup.test.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/__tests__/synchronize.test.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/__tests__/walletSync.test.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Activation/01-CreateOrSynchronizeStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Activation/05-ActivationFinalStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Activation/index.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/ManageBackup/02-FinalStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/ManageInstances/04-DeletionError.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Synchronize/07-ActivationAlreadyCreatedOther.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-desktop/tests/page/drawer/ledger.sync.drawer.ts
- ...
Update LLD Ledger Sync Copy
- **JIRA or GitHub link**: [LIVE-14198] 
---
[LIVE-14198]: https://ledgerhq.atlassian.net/browse/LIVE-14198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0a …
=> feat: 💄Update LLD Ledger Sync Copy

.changeset/fair-goats-sniff.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/Accounts/__integrations__/addAccount.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/components/SelectAddAccountMethod/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/manageInstances.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/scanQRCode.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/synchronizeWithQrCode.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/walletSyncActivated.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/walletSyncActivation.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/walletSyncSettings.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/walletSyncStatus.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Error/Detailed.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Error/Simple.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Success/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useLedgerSyncAnalytics.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useSpecificError.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Activation/ActivationSuccess.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Synchronize/ScannedInvalidQrCode.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Synchronize/ScannedOldImportQrCode.tsx, apps/ledger-live-mobile/src/screens/Onboarding/steps/accessExistingWallet.tsx, apps/ledger-live-mobile/src/utils/urls.tsx
- ...
Update whole flow with new Figma
- **JIRA or GitHub link**: [LIVE-14197] 
---
[LIVE-14197]: https://ledgerhq.atlassian.net/browse/LIVE-14197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoi …
=> feat: 💄 Update Copy of LedgerSync

.changeset/few-gifts-double.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/__tests__/useFlows.test.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useFlows.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useLedgerSyncAnalytics.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Activation/01-CreateOrSynchronizeStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Manage/index.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/ManageBackup/01-DeleteBackupStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/ManageInstances/04-DeletionError.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Synchronize/05-UnbackedError.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Synchronize/07-ActivationAlreadyCreatedOther.tsx, apps/ledger-live-desktop/src/renderer/reducers/walletSync.ts, apps/ledger-live-desktop/static/i18n/en/app.json
- ...
Update Analytics + remove dead code
- **JIRA or GitHub link**: [LIVE-14200] 
---
[LIVE-14200]: https://ledgerhq.atlassian.net/browse/LIVE-14200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …
=> feat: ✏️Update Analytics

.github/workflows/build-mobile.yml, .github/workflows/test-mobile.yml
- ...
Today we can't launch the two edited workflows manually because permissions are not set correctly.
I updated permissions to be aligned with the ones set in the reusable workflow.
---
=> fix: workflow permission for a workflow dispatch

CODEOWNERS, apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FormSelectors/FromRow.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FormSelectors/ToRow.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FormSummary/SectionFees.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FormSummary/SummaryValue.tsx, apps/ledger-live-desktop/tests/component/layout.component.ts, apps/ledger-live-desktop/tests/component/modal.component.ts, apps/ledger-live-desktop/tests/enum/AppInfos.ts, apps/ledger-live-desktop/tests/enum/DeviceLabels.ts, apps/ledger-live-desktop/tests/enum/Swap.ts, apps/ledger-live-desktop/tests/models/Swap.ts, apps/ledger-live-desktop/tests/models/Transaction.ts, apps/ledger-live-desktop/tests/page/abstractClasses.ts, apps/ledger-live-desktop/tests/page/drawer/swap.confirmation.drawer.ts, apps/ledger-live-desktop/tests/page/index.ts, apps/ledger-live-desktop/tests/page/speculos.page.ts, apps/ledger-live-desktop/tests/page/swap.page.ts, apps/ledger-live-desktop/tests/specs/services/swap.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts, apps/ledger-live-desktop/tests/userdata/speculos-tests-app.json, apps/ledger-live-desktop/tests/utils/textParserUtils.ts, libs/ledger-live-common/src/e2e/speculos.ts, libs/speculos-transport/src/index.ts
An automated swap test scenario from ETH to BTC using speculos and rejecting after verifications on nano.
https://github.com/user-attachments/assets/2dcbad12-4b5d-47c6-91cc-a95be54b2456
https://ledgerhq.atlassian.net/browse/QAA-100
--- …
=> first speculos swap scenario: ETH to BTC rejected on device

.changeset/sour-planets-itch.md, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- ...
`spamFilteringTx`  FF
- **JIRA or GitHub link**: [LIVE-14118] 
---
[LIVE-14118]: https://ledgerhq.atlassian.net/browse/LIVE-14118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWN …
=> feat: 🔐 Add spamFilteringTx FF in Code + Firebase

apps/ledger-live-desktop/tests/page/drawer/ledger.sync.drawer.ts
- ...
This PR is to fix an issue that happened on the CI due to changes on wording for the synchronization success and backup deletion
https://github.com/LedgerHQ/ledger-live/commit/2fd05ea7fc5aff83a896f6ca4b7c1f19f984ef51
--- …
=> Updating locators on success screen and key deletion due to an update on wording #7853

.changeset/olive-drinks-complain.md, turbo.json
- Allow envs to be passed when using turbo scripts
Update turbo.json to whitelist the envs we can use when running turbo scripts
Backport from release branch.
- **JIRA or GitHub link**: [NO-ISSUE] 
---
=> chore: update turbo.json config to allow envs to be passed

apps/ledger-live-desktop/tests/specs/speculos/add.account.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/delete.account.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/receive.address.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/subAccount.spec.ts
- ...
Linked 1 test case to 1 test id
Workflow run: https://github.com/LedgerHQ/ledger-live/actions/runs/10925382147
Test execution: https://ledgerhq.atlassian.net/browse/B2CQA-2641
- **JIRA or GitHub link**: [QAA-164](https://ledgerhq.atlassian.net/jira/software/c/projects/QAA/boards/887?selectedIssue=QAA-164)
--- …
=> Link 1 test case to 1 test id (Speculos x Xray)

apps/ledger-live-desktop/tests/playwright.config.ts
- Desktop UI E2E Tests
_Given getAppAndVersion and Network error occurs more often we need to increase maxFailure to prevent quick stop of tests._
- **JIRA or GitHub link**: [UI E2E execution](https://github.com/LedgerHQ/ledger-live/actions/runs/11016461330)
--- …
=> [QAA-206][Playwright] Increase maxFailures in CI

libs/ledgerjs/packages/context-module/package.json, libs/ledgerjs/packages/keyring-eth/package.json
- ...
make packages private
---
=> 📦 (context-module/keyring-eth): make packages private

.github/workflows/test-ui-e2e-only-desktop.yml, apps/ledger-live-desktop/tests/playwright.config.ts
- LLD Speculos test
_Increasing Playwright Max failures for Speculos tests only, as getAppAndVersion error happens more often._
- **JIRA or GitHub link**: [Speculos run](https://github.com/LedgerHQ/ledger-live/actions/runs/11033037697)
--- …
=> [QAA-206] Increase max failure to speculos test only

.changeset/four-worms-end.md, libs/coin-modules/coin-evm/src/__tests__/integration/bridge.integration.test.ts, libs/ledger-live-common/src/families/evm/config.ts
=> chore: update default explorer for local base & zkevm config

.changeset/green-starfishes-suffer.md, apps/ledger-live-desktop/src/renderer/modals/Receive/steps/StepReceiveFunds.tsx, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/ReceiveFunds/03-Confirmation.tsx, libs/ledger-live-common/src/currencies/helpers.ts
- little UI rework of receive screen
- add of warning text for utxos addresses
Rework of the UI of the screen to avoid weird scroll and change animation to use reanimated 
Add message for utxos accounts
UI : 
https://github.com/user-attachments/assets/e860cdf5-5b84-4421-9123-8bce8c83e93c
Message : 
https://github.com/user-attachments/assets/5ec9d117-b1db-43b7-b5de-3f208db11d7e
- **JIRA or GitHub link**: [LIVE-14055](https://ledgerhq.atlassian.net/browse/LIVE-14055)
--- …
=> 💄(llm): ui and message on receive confirmation screen

.github/workflows/test-mobile-e2e-reusable.yml, .github/workflows/test-mobile-e2e.yml, apps/ledger-live-mobile/e2e/bridge/proxy.ts, apps/ledger-live-mobile/e2e/helpers.ts, apps/ledger-live-mobile/package.json, apps/ledger-live-mobile/scripts/e2e-ci.mjs, tools/actions/composites/setup-speculos_image/action.yml
- Detox E2E tests
You can now run Detox Speculos tests via the CI (Android only) via the "Run Speculos tests" checkbox on the [test-mobile-e2e](https://github.com/LedgerHQ/ledger-live/actions/workflows/test-mobile-e2e.yml) action page
- `speculos_tests` true : [Speculos test run](https://github.com/LedgerHQ/ledger-live/actions/runs/10918254519)
- `speculos_tests` false : [Mocked test run](https://github.com/LedgerHQ/ledger-live/actions/runs/10919142193)
--- …
=> [QAA-195][Detox][Speculos] Add Android Speculos tests to CI

.changeset/fresh-cobras-argue.md, apps/ledger-live-desktop/src/newArch/features/Collectibles/__integration__/nftsCollection.test.tsx, apps/ledger-live-desktop/tests/handlers/index.ts, apps/ledger-live-desktop/tests/jestSetup.js
- nft collection test
Fix inte test for nfts that could be unstable (sometimes there was a timeout) and had leak
Add ALLOWED_UNHANDLED_REQUESTS for msw so logs are cleaner 
- **JIRA or GitHub link**: NONE
---
=> :bug:(lld): fix inte test for nfts

.changeset/calm-pets-shout.md, apps/ledger-live-desktop/package.json, apps/ledger-live-desktop/src/storyly/StorylyProvider.tsx, apps/ledger-live-desktop/src/storyly/useStoryly.tsx, apps/ledger-live-desktop/src/types/storyly-web.d.ts, pnpm-lock.yaml
- new major version of storyly-web 
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-14120
---
=> chore: bump storyly version and adapt new api spec

apps/ledger-live-mobile/README.md
- ...
Adds a recommended version for Xcode. Currently running builds on v16 breaks due to [this issue](https://github.com/getsentry/sentry-react-native/issues/3883) with our current sentry version, but ultimately the bigger problem is that as a team we run 15.4 everywhere and don't really support 16 yet.
No ticket
---
- …
=> support: specify xcode version in LLM readme

.changeset/witty-bugs-add.md, apps/ledger-live-desktop/src/storyly/StorylyProvider.tsx, apps/ledger-live-desktop/src/storyly/useStoryly.tsx, apps/ledger-live-desktop/src/types/storyly-web.d.ts
- ...
When a user changes his display language, stories will be displayed based on that (if translated in Storyly app)
https://github.com/user-attachments/assets/a1d34164-af76-4e55-a78f-73c7eb15f135
- **JIRA or GitHub link**: [LIVE-14102](https://ledgerhq.atlassian.net/browse/LIVE-14102)
--- …
=> feat: 🌐 localize storyly

.changeset/witty-cows-breathe.md, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/components/Inscriptions/DiscoveryDrawer/Header.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/components/Inscriptions/DiscoveryDrawer/ProtectBox.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/components/Inscriptions/DiscoveryDrawer/index.tsx, apps/ledger-live-desktop/src/renderer/actions/settings.ts, apps/ledger-live-desktop/src/renderer/reducers/settings.ts, apps/ledger-live-desktop/static/i18n/en/app.json
- Discovery Drawer ORDIS
Add protect box to select if we want to protect our ordinals assets of being sent in a tx. 
This way we will be able to change the strategy in coin control to avoid this behaviour (future pr) 
https://github.com/user-attachments/assets/85bb6b84-106a-43ba-a023-08c215f8d349
updated Header 
figma :
- **JIRA or GitHub link**: [LIVE-14260](https://ledgerhq.atlassian.net/browse/LIVE-14260)
--- …
=> :sparkles:(lld): add protect box inside discovery drawer

apps/ledger-live-desktop/src/renderer/components/AccountsList/AccountRow.tsx, apps/ledger-live-desktop/tests/component/layout.component.ts, apps/ledger-live-desktop/tests/enum/Account.ts, apps/ledger-live-desktop/tests/page/abstractClasses.ts, apps/ledger-live-desktop/tests/page/modal/add.account.modal.ts, apps/ledger-live-desktop/tests/specs/accounts/account.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/delete.account.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/receive.address.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts
- ...
CI run: https://github.com/LedgerHQ/ledger-live/actions/runs/11049781609
---
=> Fix add account e2e test - Bitcoin

.github/workflows/build-and-test-external.yml
=> fix: external contribution conditions to run

.changeset/rare-yaks-deny.md, apps/ledger-live-desktop/src/renderer/families/near/Staking/Header.tsx, apps/ledger-live-desktop/src/renderer/families/near/Staking/Row.tsx, apps/ledger-live-mobile/src/families/near/Staking/index.tsx, apps/ledger-live-mobile/src/locales/en/common.json, libs/coin-modules/coin-near/src/account.ts, libs/coin-modules/coin-near/src/api/node.ts, libs/coin-modules/coin-near/src/api/sdk.types.ts, libs/coin-modules/coin-near/src/logic.ts, libs/coin-modules/coin-near/src/serialization.ts, libs/coin-modules/coin-near/src/types.ts, libs/ledger-live-common/src/families/near/__snapshots__/bridge.integration.test.ts.snap, libs/ledger-live-common/src/families/near/banner.test.ts
- ...
- Remove rewards from Near staking position(s)
- Clean the code accordingly
- **JIRA or GitHub link**:  [https://ledgerhq.atlassian.net/browse/LIVE-11709](https://ledgerhq.atlassian.net/browse/LIVE-11709)
---
=> fix: remove rewards from near staking

.github/workflows/build-and-test-pr.yml, .github/workflows/build-mobile-external-reusable.yml, .github/workflows/test-desktop-external-reusable.yml
=> fix: external contribution concurrency

.github/workflows/build-and-test-external.yml, .github/workflows/build-desktop-external-reusable.yml, .github/workflows/build-mobile-external-reusable.yml, .github/workflows/test-desktop-external-reusable.yml
- ...
Allow external build and test job to checkout from a fork.
---
=> Checkout external contributions

.github/workflows/build-desktop-external-reusable.yml, .github/workflows/build-mobile-external-reusable.yml, .github/workflows/test-desktop-external-reusable.yml
=> fix: external workflow call

libs/ledger-live-common/src/exchange/platform/startExchange.ts, libs/ledger-live-common/src/exchange/platform/transfer/completeExchange.ts, libs/ledger-live-common/src/exchange/providers/getProvidersData.test.ts, libs/ledger-live-common/src/exchange/providers/getProvidersData.ts, libs/ledger-live-common/src/exchange/providers/index.ts, libs/ledger-live-common/src/exchange/providers/sell.ts, libs/ledger-live-common/src/exchange/providers/swap.ts
- ...
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-14243
--- …
=> feat: use cal as sell provider source of true

apps/ledger-live-desktop/index-types.d.ts, apps/ledger-live-desktop/src/renderer/components/debug/DebugMock.tsx, apps/ledger-live-desktop/tests/utils/allureUtils.ts
- Playwright Speculos tests
_We gathered app logs for failed LLD Speculos Tests._
- **JIRA or GitHub link**: [Speculos tests run](https://github.com/LedgerHQ/ledger-live/actions/runs/11068253123)
---
=> [QAA-253][Playwright][Speculos] Get LLD logs for failed tests

.github/workflows/turbo-affected-reusable.yml
- ...
Do not use relative path to target custom github actions and tag the develop branch.
---
=> CI - Do not use relative path and tag the branch for github actions

.changeset/strange-sheep-share.md, libs/trustchain/src/__tests__/tsconfig.json, libs/trustchain/tests/tsconfig.json
- ...
Remove the missing jest types issues in the Trustchain tests files:
| <img width="489" alt="image" src="https://github.com/user-attachments/assets/ba4ef255-25b6-468b-8d94-7ec8ce6ed761"> | <img width="489" alt="image" src="https://github.com/user-attachments/assets/637acd3a-afc2-4c5f-9628-9ff9e4ff27b4"> |
--- …
=> chore: 🧹 fix types errors in `@ledgerhq/trustchain` tests

.changeset/seven-geese-play.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/components/LoadingStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Activation/04-LoadingStep.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- ...
Fix wording and keep the same wording whatever you already had a synchronised instance or not.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-14305
---
=> fix: wording for loading screen of Ledger Sync

.changeset/yellow-flowers-march.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/Accounts/__integrations__/addAccount.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/scanQRCode.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/synchronizeWithQrCode.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/walletSyncActivation.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/DeviceSelection/index.tsx
- ...
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-14304
---
=> LLM - fix wording for ledger sync on activation

.changeset/five-ties-sniff.md, apps/ledger-live-mobile/e2e/page/onboarding/onboardingSteps.page.ts, apps/ledger-live-mobile/src/screens/AnalyticsOptInPrompt/variantA/Main.tsx, apps/ledger-live-mobile/src/screens/AnalyticsOptInPrompt/variantB/Main.tsx
- ...
The onboarding test will tap on the "Accept all" button of the analytics prompt if the prompt shows.
- [LIVE-13649]
---
[LIVE-13649]: https://ledgerhq.atlassian.net/browse/LIVE-13649?atlOrigin=eyJpIjoiNWRkNTljNz …
=> chore(llm): 🔍 accept analytics during onboarding tests

.changeset/thick-poets-lie.md
=> major->minor changeset hw-app-eth and cryptoassets evm

.changeset/stupid-students-clap.md
- ...
Simply a correction of the version bump type of llm due to the use of production instance of firebase for nightly.
Related to this PR #7909 
---
=> chore: use correct version bump for llm's  changeset

apps/ledger-live-desktop/tests/utils/allureUtils.ts
=> Taking speculos screenshot only for Speculos tests

.changeset/bright-months-fold.md, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- ...
Just adds `llmMemoTag` feature flag. Which is disabled by default.
- [LIVE-11448]
---
[LIVE-11448]: https://ledgerhq.atlassian.net/browse/LIVE-11448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …
=> chore(llm): 🚦 create `llmMemoTag` feature flag

.changeset/strange-news-compete.md, apps/ledger-live-desktop/src/renderer/components/FirebaseRemoteConfig.tsx, apps/ledger-live-mobile/src/components/FirebaseRemoteConfig.tsx
- ...
We are far away from the quota with a fetch every hour today, so let's reduce to 5 minutes.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-14326
---
=> Fetch feature flags every 5 minutes

.changeset/thick-foxes-repair.md, apps/ledger-live-desktop/src/renderer/families/cardano/DelegationFlowModal/steps/StepDelegation.tsx, apps/ledger-live-desktop/src/renderer/families/cardano/DelegationFlowModal/steps/StepSummary.tsx, apps/ledger-live-desktop/src/renderer/families/cardano/SendAmountFields/MemoField.tsx, apps/ledger-live-desktop/src/renderer/families/cardano/SendAmountFields/MemoValueField.tsx, apps/ledger-live-desktop/src/renderer/families/cardano/SendAmountFields/index.tsx, apps/ledger-live-desktop/src/renderer/families/cardano/UndelegateFlowModal/steps/StepSummary.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/families/cardano/DelegationFlow/02-Summary.tsx, apps/ledger-live-mobile/src/families/cardano/UndelegationFlow/01-Summary.tsx, apps/ledger-live-mobile/src/locales/en/common.json, libs/coin-modules/coin-cardano/src/bridge/index.ts, libs/coin-modules/coin-cardano/src/buildTransaction.ts, libs/coin-modules/coin-cardano/src/config.ts, libs/coin-modules/coin-cardano/src/errors.ts, libs/coin-modules/coin-cardano/src/estimateMaxSpendable.ts, libs/coin-modules/coin-cardano/src/getTransactionStatus.ts, libs/coin-modules/coin-cardano/src/logic.ts, libs/coin-modules/coin-cardano/src/logic.unit.test.ts, libs/coin-modules/coin-cardano/src/prepareTransaction.ts, libs/coin-modules/coin-cardano/src/signOperation.ts, libs/coin-modules/coin-cardano/src/transaction.ts, libs/coin-modules/coin-cardano/src/types.ts, libs/ledger-live-common/src/families/cardano/config.ts, libs/ledger-live-common/src/families/cardano/setup.ts
* cardano high fees checks
* add custom CardanoFeeTooHigh error
* display feeTooHigh error
* validate protocol params
* handle fee error in delegation
* fee warning in delegation
* show tx status warnings and errors
* update
* tx error update
* sync proto params in tx prepare
* add coinconfig + update translations
* fix cc
* update texts
* add changeset
---------
- ...
Merging ada fix in hotfix branch
original PR : [https://github.com/LedgerHQ/ledger-live/pull/7965](https://github.com/LedgerHQ/ledger-live/pull/7965)
--- …
=> Support/fix ada fees (#7965)

apps/cli/src/commands/live/ledgerSync.ts
=> fix: ts error on cli

libs/ledgerjs/packages/hw-app-eth/tests/Uniswap/index.unit.test.ts, libs/ledgerjs/packages/hw-app-eth/tests/ledgerService.unit.test.ts
- no impact
Updating Uniswap tests for the new @ledgerhq/cryptoassets-evm-signatures library
---
=> Support - Update tests for Uniswap for new cryptoassets-evm-signatures lib

.changeset/kind-numbers-travel.md, apps/ledger-live-desktop/src/renderer/Default.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/EnableAnalyticsConsole.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- ...
Add a toggle to allow analytics console in the dev settings instead of using cmd variable
https://github.com/user-attachments/assets/cd54feaa-ce30-4c5a-ad9a-c2431194618a
---
=> :technologist:(lld): add toggle for analytics console

apps/ledger-live-desktop/tests/specs/services/ethereumStaking.spec.ts
=> fix: flaky test e2e desktop

.changeset/pink-pugs-press.md, apps/ledger-live-desktop/src/main/window-lifecycle.ts
- ...
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10371
--- …
=> Fix app position with external display on windows

.changeset/strange-sheep-share.md
- ...
Changeset is failing as trustchain package does not exist anymore.
---
=> Fix changeset following package rename

.changeset/old-bats-swim.md, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/useAddAccountViewModel.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Manage/index.tsx
- ...
- **JIRA or GitHub link**: [LIVE-14345](https://ledgerhq.atlassian.net/browse/LIVE-14345) && [LIVE-14357](https://ledgerhq.atlassian.net/browse/LIVE-14357)
---
[LIVE-14345]: …
=> :bug:(llm): lockscreen with LS RELEASE

.changeset/old-bats-swim.md, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/useAddAccountViewModel.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Manage/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Synchronize/QrCodeMethod.tsx
- ...
cherry-pick of 9f01d25708c8df912782157379dbcb95043896fc
- **JIRA or GitHub link**:[LIVE-14345](https://ledgerhq.atlassian.net/browse/LIVE-14345) && [LIVE-14357](https://ledgerhq.atlassian.net/browse/LIVE-14357)
--- …
=> :bug:(llm): lockscreen with LS

.changeset/three-islands-carry.md, apps/ledger-live-desktop/src/renderer/components/BalanceInfos/index.tsx, apps/ledger-live-desktop/src/renderer/screens/asset/AssetBalanceSummaryHeader.tsx
=> [FIX/LIVE-9213]: add missing default parent account parameter for swap live app.

.github/workflows/release-final-nightly.yml, .github/workflows/release-prerelease.yml
- Prevent tag push on prerelease / nightly
Do not push tags on prerelease / nightly builds
- **JIRA or GitHub link**: [NO-ISSUE] 
---
=> 💚 (ci): Remove tag push on prerelease

.changeset/wild-poems-play.md, libs/ledger-live-common/src/exchange/providers/swap.ts, libs/ledger-live-common/src/exchange/swap/utils/index.ts
=> feat: display name history

.changeset/nice-plants-complain.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/ReceiveFunds/03-Confirmation.tsx, apps/ledger-live-mobile/src/screens/ReceiveFunds/NeedMemoTagModal/NeedMemoTagModal.tsx, apps/ledger-live-mobile/src/screens/ReceiveFunds/NeedMemoTagModal/index.ts, apps/ledger-live-mobile/src/utils/constants.ts, apps/ledger-live-mobile/src/utils/urls.tsx, libs/ui/packages/native/src/components/cta/Button/getButtonStyle.ts, libs/ui/packages/native/src/components/cta/Button/index.tsx, libs/ui/packages/native/storybook/stories/Cta/Button/Button.stories.tsx
- ...
Add the "Need a Tag/Memo?" modal in the receive flow.
- [LIVE-9630]
---
[LIVE-9630]: https://ledgerhq.atlassian.net/browse/LIVE-9630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …
=> feat(llm): 📝 add the receive flow `NeedMemoTagModal`

.changeset/little-comics-help.md, apps/ledger-live-desktop/src/renderer/components/Carousel/helpers.tsx, apps/ledger-live-desktop/src/renderer/hooks/useActionCards.tsx, apps/ledger-live-desktop/src/renderer/modals/index.ts, apps/ledger-live-desktop/src/renderer/modals/types.ts, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/BrazeTools/Hooks/useGenerateLocalBraze.ts, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/BrazeTools/Modal/Body.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/BrazeTools/Modal/index.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/BrazeTools/index.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/index.tsx, apps/ledger-live-desktop/src/types/dynamicContent.ts, apps/ledger-live-desktop/static/i18n/en/app.json
- Braze and Settings
Add a dev setting to be able to create local braze CC on LLD. This way we can easily test the UI 
https://github.com/user-attachments/assets/7bf96f6a-9871-42b6-96cc-5d2a790ec426
--- …
=> :technologist:(lld): add braze generator tools in dev settings

.changeset/gold-cherries-work.md, libs/ledger-live-common/src/families/algorand/__snapshots__/bridge.integration.test.ts.snap, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- ...
Memo Tag feature flag integration (like LLM) 
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11449
---
=> chore: add memoTag feature flag for LLD

.changeset/early-seas-love.md, libs/ledger-live-common/src/families/evm/config.ts
- ...
Update Metis explorer through Firebase to support CORs.
- **JIRA or GitHub link**: [LIVE-14321](https://ledgerhq.atlassian.net/browse/LIVE-14321)
---
[LIVE-14321]: …
=> fix: Update Metis explorer through Firebase to support CORs

.changeset/new-cougars-develop.md, apps/ledger-live-desktop/src/newArch/features/MemoTag/__tests__/MemoTagInfo.test.tsx, apps/ledger-live-desktop/src/newArch/features/MemoTag/__tests__/MemoTagInfoBody.test.tsx, apps/ledger-live-desktop/src/newArch/features/MemoTag/components/MemoTagInfo.tsx, apps/ledger-live-desktop/src/newArch/features/MemoTag/components/MemoTagInfoBody.tsx, apps/ledger-live-desktop/src/newArch/features/MemoTag/constants.ts, apps/ledger-live-desktop/src/renderer/modals/Receive/steps/StepReceiveFunds.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- add a div section to Receive flow step 2 and 3 , it should be covered by e2e tests
Simply add an alert section to inform user about MemoTag
https://github.com/user-attachments/assets/574c9067-da29-45a3-ae09-f870979fe58c
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-9632
--- …
=> feat: add memo tag information section in LLD recieve flow

apps/ledger-live-mobile/e2e/bridge/proxy.ts, apps/ledger-live-mobile/e2e/helpers.ts, apps/ledger-live-mobile/e2e/page/common.page.ts, apps/ledger-live-mobile/e2e/specs/speculos/addAccount.spec.ts, apps/ledger-live-mobile/package.json, libs/ledgerjs/packages/hw-transport-node-speculos-http/src/SpeculosHttpTransport.ts, pnpm-lock.yaml
- Detox Speculos tests
_In order to support Speculos on iOS tests, we need to be able to connect to remote Speculos Devices._
- **JIRA or GitHub link**: [Speculos Run](https://github.com/LedgerHQ/ledger-live/actions/runs/11211444086/job/31160327967)
--- …
=> [QAA-282][Detox] Add support for remote Speculos capabilities

.github/workflows/test-ui-e2e-only-desktop.yml, apps/cli/package.json, apps/cli/src/live-common-setup.ts, apps/ledger-live-desktop/tests/fixtures/common.ts, apps/ledger-live-desktop/tests/utils/cliUtils.ts, pnpm-lock.yaml
- Playwright tests
_Implement CLI commands to Speculos tests_
- **JIRA or GitHub link**: [Speculos Run](https://github.com/LedgerHQ/ledger-live/actions/runs/11160065539) [Allure report](https://ledger-live.allure.green.ledgerlabs.net/allure/reports/4764dcde-6280-4981-aa09-4e9580a3dc34/index.html#)
--- …
=> [QAA-272][Playwright] Implement CLI commands to Speculos tests

.changeset/pink-apricots-yell.md, libs/live-countervalues/src/portfolio.ts
- ...
Set the Portfolio display to “All time”.
Graph is correctly displayed.
- **JIRA or GitHub link**: [LIVE-11079](https://ledgerhq.atlassian.net/browse/LIVE-11079)
---
[LIVE-11079]: …
=> fix: graph correctly display even if value is NaN

.changeset/wet-socks-film.md, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/components/CoinControlModal/components/ExcludeAssetsSection.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/components/CoinControlModal/components/Footer.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/components/CoinControlModal/components/Row/NoOrdinalsRow.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/components/CoinControlModal/components/Row/index.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/components/CoinControlModal/components/Row/useOrdinalRowModel.ts, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/components/CoinControlModal/components/UtxoPickerHeaderSection.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/components/CoinControlModal/components/UtxoStrategyPicker.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/components/CoinControlModal/components/index.ts, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/components/CoinControlModal/index.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/components/CoinControlModal/useCoinControlModalModel.ts, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/components/Inscriptions/DiscoveryDrawer/index.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/screens/Account/index.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/screens/Account/useBitcoinAccountModel.ts, apps/ledger-live-desktop/src/newArch/features/Collectibles/__integration__/coinControlModal.test.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/__integration__/mockedBTCAccount.ts, apps/ledger-live-desktop/src/newArch/features/Collectibles/__integration__/mockedTx.ts, apps/ledger-live-desktop/src/newArch/features/Collectibles/__integration__/mockedTxStatus.ts, apps/ledger-live-desktop/src/newArch/features/Collectibles/__integration__/shared.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/hooks/useCollectiblesAnalytics.ts, apps/ledger-live-desktop/src/newArch/features/Collectibles/types/enum/Analytics.ts, apps/ledger-live-desktop/src/renderer/components/Modal/index.tsx, apps/ledger-live-desktop/src/renderer/families/bitcoin/SendAmountFields.tsx, apps/ledger-live-desktop/src/renderer/families/bitcoin/useBitcoinPickingStrategy.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-desktop/tests/jestSetup.js, libs/coin-modules/coin-bitcoin/src/logic.ts, libs/live-nft-react/src/index.ts
- Rework of the UI of the coin Control under newArch behind ordinals FF
Rework of the coin control UI using ordinals assets from simplehash
+ little changes on the modal component to be able to test it with jest
+ ResizeObserver mocked in jest to avoid error with modals
this is the first PR another one will come to add simplehash to the coinControl and display assets. Currently it's not like the Figma because we don't have the correct components but it's close
There is some TS ignore that already exist so I didn't change that because it's more about BTC implem
https://github.com/user-attachments/assets/1c0f0e3b-afad-4181-bb07-b7ef6088518d
- **JIRA or GitHub link**: [LIVE-12597](https://ledgerhq.atlassian.net/browse/LIVE-12597)
---
- **The code aligns with the requirements** described in …
=> :sparkles:(lld): rework coin control UI

.changeset/thin-timers-beg.md, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Error/Simple.tsx
…xt component
- ...
Fixed an issue that caused a string to not be rendered in a Text component
|<img width="552" alt="Screenshot 2024-10-10 at 16 09 12" src="https://github.com/user-attachments/assets/f41328e4-64df-4a84-8b77-89d9aa35e313">|<img width="552" alt="Screenshot 2024-10-10 at 16 09 29" src="https://github.com/user-attachments/assets/05d89a9c-fb93-49e0-aae1-fb4ac453ac59">|
- **JIRA or GitHub link**: [LIVE-14451]
---
- …
=> LLM - Fixed Ledger Sync Sentry Error

.github/workflows/test-desktop-reusable.yml
- ...
There is an e2e test which fails in `test-desktop-reusable.yml` at `e2e-tests-linux` job. And this issue is  due to the system character encoding / locale which consider `.` rather than `,` as a digit separator. 
The solution here is , like in `test-mobile-e2e-reusable.yml` workflow on linux based job, is to set the local explicitly to UTF8 so that local and ci environments has the same character/date/digit encoding using the same locale. 
Sample of wallet-api-spec.ts succesfull job
https://github.com/LedgerHQ/ledger-live/actions/runs/11277020149/job/31362203290
This fix doesn't concern `specs/syncOnboarding/manual.spec.ts:20:9 › [stax] SyncOnboarding › [stax] Manual @smoke` failed e2e test due to timeout (it should be investigated by the concerned team, even locally we have the …
=> chore: stabelize e2e flaky test due to system char encoding

.github/workflows/test-mobile-e2e-reusable.yml
- LLM E2E iOS test
_Adding missing dummy app dependency install_
---
=> [QAA-297] LLM iOS E2E : Fix pod install

apps/ledger-live-desktop/tests/enum/Account.ts, apps/ledger-live-desktop/tests/specs/speculos/receive.address.spec.ts
- ...
- **JIRA or GitHub link**: [QAA-296](https://ledgerhq.atlassian.net/jira/software/c/projects/QAA/boards/887?selectedIssue=QAA-296)
---
- **There …
=> [QAA-296] Improving receive E2E tests using the CLI

libs/ledger-live-common/src/wallet-api/logic.ts
=> :bug:(common): wallet btc import

tools/actions/composites/setup-toolchain/action.yml
The comments removed here are >1.5yrs old. Seems like this is not useful any more
=> build: remove 1.5yr old commented out proto code

.changeset/moody-geckos-fix.md, libs/coin-modules/coin-cosmos/src/config.ts
- ...
Update dydx node to reflect firebase value
- **JIRA or GitHub link**: [https://ledgerhq.atlassian.net/browse/LIVE-14352](https://ledgerhq.atlassian.net/browse/LIVE-14352)
---
=> update dydx default node

.changeset/beige-cats-travel.md, apps/ledger-live-mobile/src/components/RootNavigator/BaseOnboardingNavigator.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Success/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Activation/ActivationLoading.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Activation/ActivationSuccess.tsx
- OnBoarding with LS
Fix an issue that was "resetting" the app after sync with LS during onboarding
- **JIRA or GitHub link**: [LIVE-14492](https://ledgerhq.atlassian.net/browse/LIVE-14492)
---
[LIVE-14492]: …
=> :bug:(llm): completeOnboarding after LS sync

.changeset/wet-cars-perform.md, apps/ledger-live-desktop/src/renderer/components/CurrencyDownStatusAlert.tsx, apps/ledger-live-desktop/src/renderer/components/ErrorBanner.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
-currency warning
Add the error statuts from https://status.ledger.com/
API docs = https://ledger.statuspage.io/api
It will always be in english but it's wanted
also add a check to avoid double link 
How to test : 
- launch lld with `MOCK=1 pnpm dev:lld --env-mode=loose` 
- trigger notification using the tool
- you can update the receive message here `apps/ledger-live-desktop/tests/mocks/serviceStatusHelpers.ts`
https://github.com/user-attachments/assets/00533a18-558c-4f6e-a19c-222c732b56a5
- **JIRA or GitHub link**: [LIVE-14065](https://ledgerhq.atlassian.net/browse/LIVE-14065)
--- …
=> :sparkles:(lld): add description from ledgerstatus to currency warning

.changeset/spotty-experts-train.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx
=> feat: backport demo1 changes

apps/ledger-live-mobile/fastlane/.env.ios.nightly
- ...
Quick update on the naming of the nightly app so that it fits the request coming from Guillaume M.
https://ledgerhq.atlassian.net/browse/LIVE-14568
---
=> chore: update the nightly app name

.changeset/hot-guests-hide.md, apps/ledger-live-desktop/src/config/urls.ts, apps/ledger-live-desktop/src/renderer/components/DeviceAction/NoSuchAppOnProviderErrorComponent.tsx, apps/ledger-live-desktop/src/renderer/components/DeviceAction/index.tsx, apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- ...
Replace NoSuchAppOnProvider error screen with the new one 
https://ledgerhq.atlassian.net/browse/LIVE-14462
---
=> feat: implement new  NoSuchAppOnProviderError component body

.changeset/lazy-ads-drop.md, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Synchronize/DrawerHeader.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Manage/index.tsx
- ...
- UI fix
- Support plural keys for `walletSyncActivated.synchronizedInstances.title`
https://ledgerhq.atlassian.net/browse/LIVE-14540
---
=> fix: 🐞 UI for synchronized instances and drawer header text layout

.changeset/wild-squids-promise.md, apps/ledger-live-mobile/src/locales/en/common.json
- ...
Just adding the wording to be displayed in the cta.
https://ledgerhq.atlassian.net/browse/LIVE-14533
---
=> fix: ✍ add scannedInvalidQrCode.tryAgain key support

.changeset/red-tips-knock.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx
- ...
[- **JIRA or GitHub link**: 
](https://ledgerhq.atlassian.net/browse/LIVE-14564)
--- …
=> passing dev mode to swap live app

.changeset/flat-rings-deny.md, apps/ledger-live-desktop/src/renderer/modals/AddAccounts/steps/StepChooseCurrency.tsx
- ...
https://ledgerhq.atlassian.net/browse/LIVE-14444
---
=> fix: 🐞 display of tokenCTA with long wording

.changeset/gold-bats-perform.md, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/components/StepFlow.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/synchronizeWithQrCode.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Activation/ActivationFlow.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useSyncWithQrCode.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Activation/ActivationLoading.tsx
- LLM - Ledger Sync activation using QR Code
Fix integration test for QRCode activation flow on LLM
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-14524
---
=> [LIVE-14524] LLM - Improve QRCode flow for Ledger Sync tests

.changeset/modern-wolves-pretend.md, libs/ledger-live-common/src/exchange/swap/completeExchange.ts
- ...
Tmp exception for thorswap that for sure will be definitive but it's ok 
https://ledgerhq.atlassian.net/browse/LIVE-14396
---
=> feat: thorswap erc20 swap

.changeset/two-elephants-double.md, apps/ledger-live-desktop/src/newArch/features/Collectibles/Nfts/BreadCrumb/useBreadCrumbModel.tsx, apps/ledger-live-desktop/src/renderer/components/Breadcrumb/NFTCrumb.tsx
- nft breadcrumb newarch and current
The nft breadcrumb (newArch and current) was not filtering the spam nfts. The code is duplicated in both because newArch is under ff and the current will be removed a day
https://github.com/user-attachments/assets/6bbdf976-ece1-471b-8419-3ba6cfcfaa40
- **JIRA or GitHub link**: [LIVE-14584](https://ledgerhq.atlassian.net/browse/LIVE-14584)
---
- **Any new …
=> :bug:(lld): nft breadcrumb not filtering spam

.changeset/spotty-windows-deny.md, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useSyncWithQrCode.ts
- ...
Ledger Sync triggers a [unhandled error warning](https://ledger.sentry.io/issues/6001079408/?alert_rule_id=14962658&alert_type=issue&notification_uuid=6b71d22b-7bb5-4d84-af4c-74faf5656b67&project=6723478&referrer=slack) when scanning an old import qr code
- **JIRA or GitHub link**: [LIVE-14573]
--- …
=> LLM - Fixed Unhandled error warning message

.changeset/forty-jobs-buy.md, apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/EarlySecurityChecks/index.tsx, libs/ledger-live-common/src/hw/hooks/useGenuineCheck.test.ts, libs/ledger-live-common/src/hw/hooks/useGenuineCheck.ts
- ...
Added timeout during Allow Manager on Genuine check flow to avoid stale states
- **JIRA or GitHub link**: [LIVE-10625](https://ledgerhq.atlassian.net/browse/LIVE-10625)
---
[LIVE-10625]: …
=> feat: added timeout during Allow Manager on Genuine check flow

.changeset/big-dodos-reflect.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx, libs/ledger-live-common/src/exchange/swap/addToSwapHistory.ts
- ...
Add swap history to live app
https://ledgerhq.atlassian.net/browse/LIVE-14539
---
=> feat/LIVE-14539: add history swap live app

.changeset/late-turtles-join.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/ReceiveFunds/03-Confirmation.tsx, apps/ledger-live-mobile/src/screens/ReceiveFunds/ConfirmationHeaderTitle.tsx, libs/ui/packages/icons/src/svg/share-alt.svg, libs/ui/packages/native/src/components/Cards/BannerCard/index.tsx
- ...
Align the receive screen with Figma design.
| ![simulator_screenshot_B167FDE8-3531-4A1C-BAF9-770E9BBB77B8](https://github.com/user-attachments/assets/a8d54471-38be-404e-b492-659ec97bd59a) | ![simulator_screenshot_51348C97-45BF-4156-BBBF-D6A0FFBF5E4B](https://github.com/user-attachments/assets/d36a7e64-831e-49cf-b53b-adb7bcd28741) |
- [LIVE-11439]
--- …
=> fix(llm): 🥂 align the receive screen with Figma design

.changeset/mean-gifts-worry.md, apps/ledger-live-desktop/src/renderer/components/OnboardingAppInstall/InstallSetOfApps.tsx, apps/ledger-live-desktop/src/renderer/components/OnboardingAppInstall/index.tsx, apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/SyncOnboardingCompanion.tsx
- ...
Retry app installation upon device disconnection 
- **JIRA or GitHub link**: [LIVE-13482](https://ledgerhq.atlassian.net/browse/LIVE-13482)
---
[LIVE-13482]: …
=> fix(lld): retry app installation upon device disconnection

.changeset/rude-dancers-fry.md, apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/SelectUseCase/index.tsx
- ...
Fixed navigation in onboarding/ledger-lecover
- **JIRA or GitHub link**: [LIVE-11633](https://ledgerhq.atlassian.net/browse/LIVE-11633)
---
[LIVE-11633]: …
=> fix(lld): fixed navigation in onboarding/ledger-lecover

.changeset/small-experts-hammer.md, apps/ledger-live-mobile/src/screens/MyLedgerDevice/Device/index.tsx
- ...
- Close apps modal upon errors to show error modal
- **JIRA or GitHub link**: [LIVE-12404](https://ledgerhq.atlassian.net/browse/LIVE-12404)
---
[LIVE-12404]: …
=> fix(llm): Close device card apps modal upon errors

.github/workflows/test-mobile-e2e-reusable.yml, .github/workflows/test-mobile-e2e.yml, .github/workflows/test-ui-e2e-only-desktop.yml, tools/actions/composites/get-allure-summary/action.yml, tools/actions/composites/upload-allure-report/action.yml
- Detox Slack notification
_We want to have the same notficiation as Desktop test for Detox tests_
- [Desktop Notification](https://ledger.slack.com/archives/C05FKJ7DFAP/p1729520232903959) checking no regression
- [Mobile notification](https://ledger.slack.com/archives/CTMQ0S5SB/p1729525595762619)
--- …
=> [QAA-283][Detox] Improve slack notification

libs/hw-ledger-key-ring-protocol/package.json, libs/ledger-key-ring-protocol/package.json, libs/speculos-transport/package.json
- ...
We need to publish the following packages to allow CLI to install from npm.
See issue raised by CS team:https://ledger.slack.com/archives/C8PG210JY/p1728997045300629
---
=> Publish packages that are needed for the cli

apps/ledger-live-desktop/tests/component/drawer.component.ts, apps/ledger-live-desktop/tests/component/layout.component.ts, apps/ledger-live-desktop/tests/component/modal.component.ts, apps/ledger-live-desktop/tests/enum/DeviceLabels.ts, apps/ledger-live-desktop/tests/page/abstractClasses.ts, apps/ledger-live-desktop/tests/page/account.page.ts, apps/ledger-live-desktop/tests/page/portfolio.page.ts, apps/ledger-live-desktop/tests/specs/speculos/delegate.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts
=> [E2E] Fixing broken steps in Allure report

apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts
- ...
trying to mitigate [wrong balance fetch](https://ledger.slack.com/archives/C05FKJ7DFAP/p1729834021280179) on swaps
[reporting](https://github.com/LedgerHQ/ledger-live/actions/runs/11515157507) 
--- …
=> wrong balance fetch LIVE-14410 mitigation attempt

.changeset/gorgeous-parents-join.md, apps/ledger-live-desktop/src/renderer/components/MainSideBar/index.tsx, apps/ledger-live-desktop/src/renderer/init.tsx, apps/ledger-live-desktop/src/renderer/live-common-setup.ts, apps/ledger-live-desktop/static/i18n/en/app.json, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledger-live-common/src/hw/index.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- ...
- Added ldmkTransport feature flag defaults
- Added ldmkTransport feature flag logic placeholder in LLD transport registration
- Added ldmkTransport visual flag in front-end
- **JIRA or GitHub link**: [DSDK-505](https://ledgerhq.atlassian.net/browse/DSDK-505)
--- …
=> feat: added LDMK transport feature flag

.changeset/smart-geckos-add.md, apps/ledger-live-desktop/src/renderer/components/Stepper/Step.tsx
- ...
Center the breadcrumb icons of the stepper
|![image](https://github.com/user-attachments/assets/7956a881-a85c-4a4c-9276-20cf7e8d7fcf)| ![image](https://github.com/user-attachments/assets/6dd03a84-c191-4e98-aaaf-e7f7e494bf38)|
- **JIRA or GitHub link**: NO NEED
--- …
=> :bug:(lld): stepper breadcrumb icons not centered

.changeset/wicked-swans-raise.md, apps/ledger-live-mobile/src/families/cardano/UndelegationFlow/01-Summary.tsx, apps/ledger-live-mobile/src/families/celo/RevokeFlow/VoteAmount.tsx, apps/ledger-live-mobile/src/families/cosmos/shared/02-SelectAmount.tsx, apps/ledger-live-mobile/src/families/near/shared/02-SelectAmount.tsx, apps/ledger-live-mobile/src/families/polkadot/UnbondFlow/01-Amount.tsx, apps/ledger-live-mobile/src/families/shared/StakingErrors/NotEnoughFundFeesAlert/index.tsx, apps/ledger-live-mobile/src/families/solana/DelegationFlow/Summary.tsx, apps/ledger-live-mobile/src/families/tezos/DelegationFlow/Summary.tsx, apps/ledger-live-mobile/src/hooks/index.ts, apps/ledger-live-mobile/src/locales/en/common.json
- undelagation flow
Rework the UI of undelegate error on LLM so the user has a better message. For Ethereum, Solana, Cardano, Polkadot, Near, Injective, MultiverseX, Dydx, Osmosis, Tezos, Celo.
UI is not exactly the same as figma so I did it with the current version. 
Remaning todos : 
Each screen is simulated changing fees inside coin-modules that's why we can't pay the fees even with more than usual fees
Each link redirects to the wanted screen if possible so user can buy/swap/receive
| COIN        | IMG         |
|**COSMOS FAMILY**|
|COSMOS|![image](https://github.com/user-attachments/assets/6038ca07-5d00-49d0-afba-dd577b4730cf)|
|INJ|![image](https://github.com/user-attachments/assets/4a2375d8-fe6c-4695-bded-1dfe8cce7ec5)| …
=> :goal_net:(llm): undelegate error message not enought for fees 

.changeset/silly-timers-burn.md, apps/ledger-live-desktop/src/renderer/components/NotEnoughFundsToUnstake/index.tsx, apps/ledger-live-desktop/src/renderer/families/cardano/UndelegateFlowModal/steps/StepSummary.tsx, apps/ledger-live-desktop/src/renderer/families/celo/UnlockFlowModal/steps/StepAmount.tsx, apps/ledger-live-desktop/src/renderer/families/cosmos/UndelegationFlowModal/steps/Amount.tsx, apps/ledger-live-desktop/src/renderer/families/near/UnstakingFlowModal/steps/Amount.tsx, apps/ledger-live-desktop/src/renderer/families/solana/DelegationDeactivateFlowModal/steps/StepValidator.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- ...
Rework the UI of undelegate error on LLD when the user does not have enough funds to pay for fees.
Note that the current UI does not match [the figma](https://www.figma.com/design/CJSTinoHMRsHDYeS1ylm6E/LLD%2FLLM-Error-Messages?node-id=930-1313&node-type=text&m=dev) so we had to adapt a bit the proposed solution.
List of stackable coins :
| COIN | BEFORE | AFTER |
| ------------- | ------------- | ------------- |
| Sol | ![Screenshot 2024-10-22 at 17 49 37](https://github.com/user-attachments/assets/d98b89fb-7f07-482b-8fe2-1b95c20e3a38) | ![Screenshot 2024-10-23 at 18 31 59](https://github.com/user-attachments/assets/830b65b4-7bd5-4cbd-9934-bda433c0b400) |
| Cardano | ![Screenshot 2024-10-23 at 09 55 29](https://github.com/user-attachments/assets/6af7d778-1616-4d4e-b238-b1321855bacf) …
=> LLD - Rework NotEnoughBalance error message on Unbound screens

apps/ledger-live-desktop/tests/specs/market/market.spec.ts
=> test: fix flakyness on market e2e test

.changeset/tiny-turkeys-doubt.md, apps/ledger-live-mobile/src/screens/SyncOnboarding/EarlySecurityCheck.tsx
- ...
Patched onRetryGenuineCheck allowing user to retry upon genuine check error
- **JIRA or GitHub link**: [LIVE-13006](https://ledgerhq.atlassian.net/browse/LIVE-13006)
---
[LIVE-13006]: …
=> fix(llm): patched onRetryGenuineCheck

.changeset/healthy-houses-smell.md, apps/ledger-live-desktop/src/renderer/components/CustomImage/ImageCropper.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- ...
Localised string in CLS LLD
- **JIRA or GitHub link**: [LIVE-12365](https://ledgerhq.atlassian.net/browse/LIVE-12365)
---
[LIVE-12365]: https://ledgerhq.atlassian.net/browse/LIVE-12365?atlOrigin=eyJpIjoiNWRkNTlj …
=> fix(lld): localised string in CLS

apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts
=> [E2E] Fix send test title

.github/workflows/test-mobile-e2e-reusable.yml, .github/workflows/test-mobile-e2e.yml
- LLM E2E test result notification
_Fixing the LLM E2E results notification printing results_
- **JIRA or GitHub link**: [Notification exemple](https://ledger.slack.com/archives/CTMQ0S5SB/p1730195027901559)
---
=> [QAA-318] Fix Detox result notification

apps/ledger-live-desktop/tests/enum/Account.ts, apps/ledger-live-desktop/tests/enum/AppInfos.ts, apps/ledger-live-desktop/tests/enum/DeviceLabels.ts, apps/ledger-live-desktop/tests/page/speculos.page.ts, apps/ledger-live-desktop/tests/specs/speculos/delegate.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/manage.ledgersync.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/receive.address.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/subAccount.spec.ts, libs/ledger-live-common/src/e2e/speculos.ts
- ...
Reworking speculos interations for e2e testing
- refacto Speculos actions
- refacto DeviceLabels 
- **JIRA**: [QAA-306](https://ledgerhq.atlassian.net/browse/QAA-306)
- **CI run**: [RUN](https://github.com/LedgerHQ/ledger-live/actions/runs/11574171555)
--- …
=> [QAA-306] ♻️ Refacto speculos interations

pnpm-lock.yaml
=> diagnose lockfile

.changeset/nervous-baboons-allow.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/components/LoadingStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Activation/04-LoadingStep.tsx
- ...
Fix loading screen in light mode for Ledger Sync
Before
After
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-14634
---
=> fix: ledger sync loading drawer in light mode

.changeset/wicked-trains-ring.md, apps/ledger-live-desktop/src/config/urls.ts, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-desktop/tests/specs/services/confirmTransaction.spec.ts, apps/ledger-live-desktop/tests/specs/services/wallet-api.spec.ts
- ...
Update typo + url
https://github.com/user-attachments/assets/485810ee-52e7-4597-820b-7796bd10b147
- **JIRA or GitHub link**: [LIVE-14684](https://ledgerhq.atlassian.net/browse/LIVE-14684)
---
[LIVE-14684]: …
=> :bug:(lld): typo + fees url

.changeset/ninety-days-wait.md, apps/ledger-live-desktop/src/renderer/components/Select/index.tsx, apps/ledger-live-desktop/src/renderer/styles/global.ts
- ...
Fix select placeholder in light mode on LLD.
Before
After
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-14644
---
=> fix: select placeholder styles in light mode

.changeset/fifty-years-impress.md, libs/live-nft/src/supported.ts
- ...
Filter in NFT Gallery LLM were not compatible
---
=> bugfix: Filter in NFT Gallery LLM

.changeset/nervous-kangaroos-mix.md, apps/ledger-live-desktop/src/renderer/drawers/SwapOperationDetails/index.tsx
- ...
Issue was for all tokens not only Thorswap. Fixed for every provider
[- **JIRA or GitHub link**: ](https://ledgerhq.atlassian.net/browse/LIVE-14494)
---
=> fixed: swap history for tokens explorer link

apps/ledger-live-desktop/tests/page/swap.page.ts, apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts
checking deeper amount related error messages on swaps e2e scenarios
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/QAA-290
- https://github.com/LedgerHQ/ledger-live/pull/8171#discussion_r1813033675
--- …
=> e2e swap speculos scenarios: fine- tune error messages checks

apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts
- ...
Targeting appropriate staging env test url for e2e swap tests to have quotes
[quotes aren't loaded, url has changed](https://ledger-live.allure.green.ledgerlabs.net/allure/reports/fc152123-8851-481e-b383-6140ce3441b0/#suites/14e80619d2cb176baa0417903e32f671/2c5d5a3433550b6b/)
/ (ad-hoc fix)
--- …
=> fix: swap e2e scenarios target appropriate STG env test url

.changeset/cyan-berries-refuse.md, apps/ledger-live-mobile/ios/ledgerlivemobile/PrivacyInfo.xcprivacy
Updated our iOS Privacy Info file to be compliant with Apple's policy
|[ledgerlivemobile-PrivacyReport 2024-10-18 15-17-16.pdf](https://github.com/user-attachments/files/17560507/ledgerlivemobile-PrivacyReport.2024-10-18.15-17-16.pdf)|[ledgerlivemobile-PrivacyReport 2024-10-21 11-25-59.pdf](https://github.com/user-attachments/files/17560508/ledgerlivemobile-PrivacyReport.2024-10-21.11-25-59.pdf)|
- **JIRA or GitHub link**: [LIVE-14189]
--- …
=> 🔒 LLM - Privacy info modified

apps/ledger-live-desktop/tests/enum/Account.ts, apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts
=> [QAA] test: 🦺 Adding XRP3 account

.changeset/lazy-mayflies-talk.md, apps/ledger-live-desktop/src/renderer/components/CurrencyBadge.tsx, apps/ledger-live-desktop/src/renderer/components/SelectCurrency.tsx
- ...
Fix many overflow issues in Add Account flow.
Before
After
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-14601
---
=> [LIVE-14601] Fix overflow issues in add account flow

.github/workflows/test-mobile-e2e-reusable.yml
=> [QAA] CI: fix llm notif when job fails

apps/ledger-live-desktop/src/renderer/components/SelectCurrency.tsx
=> fix: role option on select currency dropdown

.changeset/mighty-wombats-fix.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx
- ...
fixed bug where tracking consent was not passed to swap live app
---
=> fix: allow tracking to be disabled for swap

.github/workflows/test-mobile-e2e-reusable.yml
=> [QAA][LLM] Fix notification on live-repo-health channel

.changeset/three-gifts-arrive.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx
- ...
align in middle the network down error
---
=> fix(live-14331): align in middle the network down error

.changeset/slow-poems-appear.md, libs/live-wallet/.eslintrc.js, libs/live-wallet/src/walletsync/incrementalUpdates.ts, libs/live-wallet/src/walletsync/index.ts, libs/live-wallet/src/walletsync/root.ts, libs/live-wallet/src/walletsync/trustchainLifecyle.ts
- ...
Remove circular dependencies between import and export from `libs/live-wallet/src/walletsync/index.ts`
---
=> chore(libs): 🩹 remove circular dependencies from walletsync

apps/ledger-live-desktop/tests/userdata/speculos-tests-app.json
- ...
We are going to use from now on the FF PtxSwapCoreExperiment from Firebase Staging. This change impacts only local runs of Automated Swap Tests.
CI run: https://github.com/LedgerHQ/ledger-live/actions/runs/11615250946
--- …
=> updated speculos-tests-app.json to use PtxSwapcoreExperiment firebase

libs/ledger-live-common/src/crypto/index.test.ts
- ...
Add simple unit test.
---
=> Add simple unit test for LLC crypto.ts

libs/coin-modules/coin-xrp/src/bridge/synchronization.test.ts, libs/coin-modules/coin-xrp/src/bridge/synchronization.ts
- ...
Remove undesired `lib` in import path.
---
=> [XRP] Undesired lib path import

.changeset/slow-lions-taste.md, apps/ledger-live-desktop/src/renderer/components/DeviceAction/index.tsx, apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- ...
add drawer change device
https://ledgerhq.atlassian.net/browse/LIVE-14497
---
=> Feat/live 14497: add drawer change device

apps/ledger-live-desktop/tests/enum/Account.ts
- ...
Some Automation TCs were failing because the BTC address changed after a swap. We have checked the new address and changed it to fix the TCs
---
=> Update BTC1 address

.changeset/moody-seals-lie.md, apps/ledger-live-mobile/fastlane/Fastfile
- ...
https://ledgerhq.atlassian.net/browse/LIVE-14346
---
=> chore: fix IOS_BUILD_NUMBER env setting to GITHUB_ENV

.changeset/mean-pugs-hang.md, apps/ledger-live-desktop/src/renderer/screens/exchange/index.tsx, apps/ledger-live-mobile/src/screens/PTX/index.tsx
- ...
Adding discreetMode param for Buy and Sell
- **JIRA or GitHub link**: [LIVE-12985](https://ledgerhq.atlassian.net/browse/LIVE-12985)
---
[LIVE-12985]: …
=> chore: add discreetMode param for buy/sell

apps/ledger-live-desktop/tests/component/layout.component.ts, apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts
limit [LIVE-14410](https://ledgerhq.atlassian.net/browse/LIVE-14410) impacts till it's solved
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-14410
[allure reporting](https://ledger-live.allure.green.ledgerlabs.net/allure/reports/ebc19d73-9963-4d99-84b5-5ae0d97da1cb/#suites/d4891ce61a3eac3340537e2ac4d99e23)
---
- …
=> LIVE-14410 mitigation attempt waiting for fix

.changeset/gorgeous-parents-join.md, .changeset/healthy-houses-smell.md, .changeset/lemon-news-chew.md, .changeset/ninety-days-wait.md, .changeset/pink-candles-happen.md, .changeset/popular-jobs-occur.md
=> Pull main into release

.github/workflows/turbo-affected-reusable.yml
Try to fix current release, it seems that the latest optimisation for checkout are not working inside a release context
- ...
- **JIRA or GitHub link**:  NO ISSUE
--- …
=> [NOISSUE] fix issue with turbo affected workflow for release

.changeset/orange-radios-thank.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useWatchWalletSync.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/type.hooks.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useWatchWalletSync.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/walletSync.hooks.ts
- ...
Persistent sync error on LLD after backup deletion from LLM
**DEMO**
https://github.com/user-attachments/assets/e1034fc3-4e7a-4a35-818d-63b5fc330fd9
https://github.com/user-attachments/assets/e027d6ae-b95c-4954-9957-300e062ad7b2
- [LIVE-14557] 
- [LIVE-14534]
--- …
=> bugfix: 🐛 Persistent sync error on LLD after backup deletion from LLM

.changeset/long-fireants-cheer.md, apps/ledger-live-desktop/src/renderer/actions/settings.ts, apps/ledger-live-desktop/src/renderer/reducers/settings.ts, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/MevProtection.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- ...
MEV Proctection 
https://github.com/user-attachments/assets/0a994e98-25bd-4a8b-88e3-981c88516976
https://github.com/user-attachments/assets/70123f14-742d-4adf-b75c-b72e313ca049
- [LIVE-14739]
- [LIVE-14433] 
- [[LIVE-14738](https://ledgerhq.atlassian.net/browse/LIVE-14738)
--- …
=> feat: ✨ MEV Protection -LLD

.changeset/cyan-experts-raise.md, apps/ledger-live-mobile/src/actions/settings.ts, apps/ledger-live-mobile/src/actions/types.ts, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/reducers/settings.ts, apps/ledger-live-mobile/src/reducers/types.ts, apps/ledger-live-mobile/src/screens/Settings/General/MevProtection.tsx, apps/ledger-live-mobile/src/screens/Settings/General/index.tsx
- ...
MEV Protection on LLM
https://github.com/user-attachments/assets/00d2cab8-1b8e-404e-9933-9a555149ad72
- [LIVE-14743]
- [LIVE-14744]
- [LIVE-14432]
---
[LIVE-14743]: …
=> feat: ✨ MEV Protection -LLM

.changeset/tiny-feet-type.md, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- ...
Just introducing a new feature flag behind the new add account workflow that will be built.
https://ledgerhq.atlassian.net/browse/LIVE-14108
---
=> feat: ✨ add llm add account feature flag

apps/ledger-live-desktop/tests/component/layout.component.ts, apps/ledger-live-desktop/tests/page/accounts.page.ts, apps/ledger-live-desktop/tests/page/index.ts, apps/ledger-live-desktop/tests/page/lockscreen.page.ts, apps/ledger-live-desktop/tests/page/modal/passwordlock.modal.ts, apps/ledger-live-desktop/tests/page/settings.page.ts, apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/settings.spec.ts
- ...
Adding password verifications:
Steps:
- Count number of accounts present
- Set Password
- Log in with wrong password
- Log in with right password
- Check if the account is still present
Deactivating ETH sepolia send test (https://ledgerhq.atlassian.net/browse/LIVE-14844)
- **JIRA or GitHub link**: [QAA-325](https://ledgerhq.atlassian.net/browse/QAA-325)
- CI RUN: [RUN](https://github.com/LedgerHQ/ledger-live/actions/runs/11817107537)
--- …
=> [QAA] Adding password e2e test

.changeset/seven-nails-knock.md, apps/ledger-live-desktop/src/renderer/modals/ProtectDiscover/ProtectDiscoverBody.tsx
- ...
Localised URL
- **JIRA or GitHub link**: [LIVE-11631](https://ledgerhq.atlassian.net/browse/LIVE-11631)
---
[LIVE-11631]: https://ledgerhq.atlassian.net/browse/LIVE-11631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …
=> fix(lld): localised URL

.changeset/grumpy-badgers-invite.md, apps/ledger-live-mobile/scripts/sync-families-dispatch.mjs, apps/ledger-live-mobile/src/families/algorand/MemoTagSummary.tsx, apps/ledger-live-mobile/src/icons/MemoIcon.tsx, apps/ledger-live-mobile/src/newArch/features/MemoTag/components/GenericMemoTagInput.tsx, apps/ledger-live-mobile/src/newArch/features/MemoTag/components/GenericMemoTagSummary.tsx, apps/ledger-live-mobile/src/newArch/features/MemoTag/components/MemoTagSummary.tsx, apps/ledger-live-mobile/src/screens/SendFunds/04-Summary.tsx
- ...
Implement the new design of the summary page for Algorand as the memo was missing there.
- [LIVE-14790]
---
[LIVE-14790]: https://ledgerhq.atlassian.net/browse/LIVE-14790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …
=> feat(llm): ✨ implement the new summary screen memo design for Algorand

.changeset/red-bobcats-leave.md, apps/ledger-live-mobile/src/families/xrp/SendRowTag.tsx
- ...
Remove the local number formating of the the XRP tag.
- [LIVE-14780]
---
[LIVE-14780]: https://ledgerhq.atlassian.net/browse/LIVE-14780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0a …
=> fix(llm): ✨ remove commas from XRP summary tag

.changeset/loud-pumas-fix.md, libs/ledger-live-common/src/walletConnect/index.ts
- ...
This PR enables `wallet-connect-live-app` for rsk chain. 
Related pull request merged in `wallet-connect-live-app`: https://github.com/LedgerHQ/wallet-connect-live-app/pull/194
=> Enable `wallet-connect-live-app` for rsk (Rootstock)

.changeset/five-waves-promise.md, apps/ledger-live-mobile/src/screens/Analytics/DistributionCard.tsx
- allocation screen
For some crypto the icon wasn't well rendered depending on the theme. I've changed for a more accurate component ( the one used for the portfolio list)
|![Simulator Screenshot - iPhone 15 - 2024-11-14 at 14 35 38](https://github.com/user-attachments/assets/806fef37-8c62-4686-8aa2-3c80be5216b4)|![image](https://github.com/user-attachments/assets/b070b754-7005-4c90-91ab-c82dd36e2a9d)|
- **JIRA or GitHub link**: [LIVE-14841](https://ledgerhq.atlassian.net/browse/LIVE-14841)
--- …
=> :bug:(llm) fix icons on allocation screen

apps/ledger-live-mobile/ios/ledgerlivemobile/PrivacyInfo.xcprivacy, clean-brooms-begin.md
- ...
Update the iOS PrivacyInfo file to match what we have on the Google Playstore
[ledgerlivemobile-PrivacyReport 2024-11-13 16-23-02.pdf](https://github.com/user-attachments/files/17736075/ledgerlivemobile-PrivacyReport.2024-11-13.16-23-02.pdf)
--- …
=> 🔒  LLM - Update PrivacyInfo

.changeset/sour-badgers-matter.md, apps/ledger-live-desktop/package.json, apps/ledger-live-desktop/src/newArch/components/DynamicContent/LogContentCardWrapper.tsx, apps/ledger-live-desktop/src/renderer/actions/dynamicContent.ts, apps/ledger-live-desktop/src/renderer/components/Carousel/helpers.tsx, apps/ledger-live-desktop/src/renderer/components/Carousel/index.tsx, apps/ledger-live-desktop/src/renderer/components/ContentCards/ActionCard/index.tsx, apps/ledger-live-desktop/src/renderer/components/Page.tsx, apps/ledger-live-desktop/src/renderer/components/TopBar/NotificationIndicator/AnnouncementPanel.tsx, apps/ledger-live-desktop/src/renderer/hooks/useActionCards.tsx, apps/ledger-live-desktop/src/renderer/hooks/useNotifications.ts, apps/ledger-live-desktop/src/renderer/screens/dashboard/ActionContentCards.tsx, apps/ledger-live-desktop/src/renderer/screens/dashboard/index.tsx, pnpm-lock.yaml
- Braze
Optimize braze tracking based on percentage of the card viewed. If less than 50% then it's not tracked. For mixpanel we send all the extras fields of the CC.
For this a wrapper has been created using an observer.
Also removed an unnecessary lib for observer 
https://github.com/user-attachments/assets/2b36da5c-590e-4cb0-bf67-7824deadc897
https://github.com/user-attachments/assets/8431941c-c5f1-4a0c-9cf9-b92bc339a46b
https://github.com/user-attachments/assets/bb517a84-e73b-4783-aaf3-c199b6539248
- **JIRA or GitHub link**:[LIVE-14466](https://ledgerhq.atlassian.net/browse/LIVE-14466) 
--- …
=> :chart_with_upwards_trend:(lld) optimize braze CC analytics

.changeset/blue-files-train.md, apps/ledger-live-mobile/ios/LaunchScreen.storyboard, apps/ledger-live-mobile/ios/ledgerlivemobile/AppDelegate.mm
-splashscreen
Splashscreen wasn't displayed because in Xcode we didn't set it as a launchScreen (see screenshot)
On ios the screen remains white/black on reboot (to explore to find a solution). This might be better to do after all the RN upgrades 
The launch is a bit long because I am in dev for the video
https://github.com/user-attachments/assets/41504a96-71e8-4c98-b75b-7ae33739da84
- **JIRA or GitHub link**: [LIVE-13154](https://ledgerhq.atlassian.net/browse/LIVE-13154)
--- …
=> :bug:(llm) fix splashscreen

.changeset/moody-deers-marry.md, apps/ledger-live-desktop/src/renderer/modals/Send/steps/StepRecipient.tsx, apps/ledger-live-desktop/src/renderer/modals/Send/steps/StepSummary.tsx
- ...
Wrap LLD memo tag send flow intermediary screen in a FF (which is not done on feature development) 
---
=> fix: wrap lld memo tag send flow info box under a feature flag

.changeset/blue-files-train.md, apps/ledger-live-mobile/ios/LaunchScreen.storyboard, apps/ledger-live-mobile/ios/ledgerlivemobile/AppDelegate.mm
This reverts commit eda204261f30e5a4784ed9af1376f64d8d86155e.
- ...
--- …
=> Revert ":bug:(llm) fix splashscreen (#8382)"

apps/ledger-live-desktop/tests/enum/Account.ts, apps/ledger-live-desktop/tests/enum/Currency.ts, apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts
added e2e speculos swap from SOL and USDC (to ETH, BTC, USDT)
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/QAA-280
---
=> added e2e speculos swap from SOL and USDC

.changeset/afraid-houses-grin.md
=> fix: changeset (patch -> minor) for coin-xrp

.github/workflows/test-mobile-e2e-reusable.yml, .github/workflows/test-ui-e2e-only-desktop.yml
- ...
Updating speculos from 0.9.5 to 0.11
---
=> ci: 👷 updating speculos version for LLD and LLM

.changeset/orange-ducks-do.md, libs/ui/packages/react/.storybook/preview.tsx, libs/ui/packages/react/src/components/layout/Carousel/Carousel.stories.tsx, libs/ui/packages/react/src/components/layout/Carousel/ChevronArrow.tsx, libs/ui/packages/react/src/components/layout/Carousel/Footer/Pagination/index.tsx, libs/ui/packages/react/src/components/layout/Carousel/Footer/Pagination/utils.ts, libs/ui/packages/react/src/components/layout/Carousel/Footer/index.tsx, libs/ui/packages/react/src/components/layout/Carousel/Footer/variantContentCard.tsx, libs/ui/packages/react/src/components/layout/Carousel/index.tsx, libs/ui/packages/shared/palettes/dark.ts, libs/ui/packages/shared/palettes/light.ts
- ...
Update the react-ui Carousel based on the portfolio content cards design:
- [Figma](https://www.figma.com/design/nEFjjnCjeYCDwSENXf5RdY/Braze?node-id=6968-238059&node-type=frame&m=dev): <img width="637" alt="image" src="https://github.com/user-attachments/assets/f2387db0-e5e4-40e2-8a59-735fb816deee">
- [Story](https://react-ui-storybook-git-feat-lld-portfolio-cards-9cdd44-ledgerhq.vercel.app/?path=%2Fstory%2Flayout-carousel--default)
- [LIVE-14467]
--- …
=> feat(lld): 🎠 update react-ui default carousel design

apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts
- ...
Error message priorities have been changed for the swap live app. This PR is about the expected error message when the amount is too big. The name of the TC is "Swap too low quote amounts from Bitcoin to Ethereum" and "Swap too low quote amounts from Ethereum to Bitcoin"
--- …
=> Update error message on swap too low quote test

.changeset/dirty-walls-dream.md, apps/ledger-live-mobile/src/dynamicContent/types.ts
- LP
Add 2 LPs for Reborn
Two braze canvas have been created too !
https://github.com/user-attachments/assets/19b720b1-8383-4592-b232-a6a16d01dcd9
- **JIRA or GitHub link**: [LIVE-14944](https://ledgerhq.atlassian.net/browse/LIVE-14944)
--- …
=> :lipstick: (llm) add LP for reborn

.changeset/curly-pets-sniff.md, apps/ledger-live-desktop/tests/specs/general/portfolio.spec.ts
- ...
Fix flaky test by waiting for elements before comparing snapshots.
Here is an example of the test failure: https://github.com/LedgerHQ/ledger-live/actions/runs/11930771472/job/33252257123
--- …
=> fix(lld): ❄️ fix flaky portfolio e2e test

.changeset/slow-tips-camp.md, libs/coin-framework/src/api/errors.ts, libs/coin-framework/src/api/index.ts, libs/coin-framework/src/api/types.ts, libs/coin-modules/coin-polkadot/src/api/index.integ.test.ts, libs/coin-modules/coin-polkadot/src/api/index.ts, libs/coin-modules/coin-stellar/src/api/index.integ.test.ts, libs/coin-modules/coin-stellar/src/api/index.ts, libs/coin-modules/coin-stellar/src/bridge/buildTransaction.ts, libs/coin-modules/coin-stellar/src/logic/craftTransaction.ts, libs/coin-modules/coin-tezos/src/api/index.integ.test.ts, libs/coin-modules/coin-tezos/src/api/index.ts, libs/coin-modules/coin-xrp/src/api/index.integ.test.ts, libs/coin-modules/coin-xrp/src/api/index.ts
- ...
Feat: add transaction type crafting. Coin-module Tezos is the only one for the time being to use it. It allows crafting of delegate and undelegate.
Chore: for consistency, rename `mode` property of Transaction into `type`. This impact coin-modules: Polkadot, Stellar and Xrp.
--- …
=> [XTZ] Alpaca manage staking transaction

.changeset/blue-pigs-add.md, apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/CompleteExchange/TransactionBroadcastedContent.tsx
this PR center the content of a completed transaction for sell flow. 
- ...
- **JIRA or GitHub link**: [LIVE-14896](https://ledgerhq.atlassian.net/browse/LIVE-14896)
--- …
=> Live 14896 sell card exch sdk success transaction message to center in drawer for consistency with swap

.changeset/afraid-poems-speak.md, apps/ledger-live-desktop/src/renderer/analytics/segment.ts, apps/ledger-live-mobile/src/analytics/segment.ts
- ...
Improve MEV analytics
---
=> feat: Improve MEV analytics

apps/ledger-live-desktop/src/sentry/install.ts, apps/ledger-live-mobile/src/sentry.ts
- ...
Stop filtering DisconnectedDevice and DisconnectedDeviceDuringOperation from errors sent to Sentry.
We will filtered them out if necessary directly from Sentry interface.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-14991
--- …
=> chore: stop filtering disconnected device errors

.changeset/thin-planets-accept.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FeesDrawerLiveApp/index.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Navbar/index.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/utils/index.ts, apps/ledger-live-desktop/src/renderer/screens/platform/LiveApp.tsx
- ...
Add analytics related to the Swap application
- [fix(LIVE-14877): user clicks on History tab](https://ledgerhq.atlassian.net/browse/LIVE-14877)
- [fix(LIVE-14876): user clicks on slow/medium/fast to chose network fees](https://ledgerhq.atlassian.net/browse/LIVE-14876)
- [fix(LIVE-14875): user close "X"](https://ledgerhq.atlassian.net/browse/LIVE-14875)
--- …
=> fix(LIVE-14854): add swap analytics

.changeset/loud-mangos-enjoy.md, libs/ui/packages/react/src/components/cta/Button/index.tsx, libs/ui/packages/react/src/components/layout/Carousel/Carousel.stories.tsx, libs/ui/packages/react/src/components/layout/Carousel/index.tsx, libs/ui/packages/react/src/components/layout/Carousel/types.tsx, libs/ui/packages/react/src/components/layout/ContentCard/PortfolioContentCard/PortfolioContentCard.stories.tsx, libs/ui/packages/react/src/components/layout/ContentCard/PortfolioContentCard/index.tsx, libs/ui/packages/react/src/components/layout/index.ts
- ...
Add a portfolio content card component to the design system
Stories:
- [Card](https://react-ui-storybook-git-feat-lld-portfolio-cards-ui-ledgerhq.vercel.app/?path=%2Fdocs%2Flayout-contentcard-portfoliocontentcard--docs)
- [Cards](https://react-ui-storybook-git-feat-lld-portfolio-cards-ui-ledgerhq.vercel.app/?path=%2Fstory%2Flayout-carousel--portfolio-content-cards)
- [LIVE-14467]
---
- …
=> feat(lld): 🧩 add new portfolio content card component

.changeset/proud-actors-dress.md, apps/ledger-live-desktop/src/newArch/components/DynamicContent/LogContentCardWrapper.tsx, apps/ledger-live-desktop/src/renderer/components/ContentCards/ActionCard/components.tsx
- Braze Action cards and notifs center text issue
Fix issue with actions card layout and notif layout introduced with a previous PR. 
- **JIRA or GitHub link**: [LIVE-15008](https://ledgerhq.atlassian.net/browse/LIVE-15008)
--- …
=> :bug: (lld) notification center and action cards

apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts
- ...
This change intends to fix the test Swap too low quote amounts from Ethereum to Bitcoin. The idea for the test is to check that the error message is shown, so we have decreased the amount swaped and avoid edge cases when partners quotes are to close to the value set in our tests.   
---
- …
=> fix for test Swap too low quote amounts from coin1 to coin2

.changeset/tame-phones-smell.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/PostBuyDeviceSetupNanoWallScreen.tsx
- setup your device drawer
typo and align update
|![image](https://github.com/user-attachments/assets/48c26af5-b7a1-472d-89e8-0fce77d33889)|![image](https://github.com/user-attachments/assets/d36e9b0b-7d9b-4bb5-b38e-3a22a18c6ef3)|
- **JIRA or GitHub link**: [LIVE-15024](https://ledgerhq.atlassian.net/browse/LIVE-15024)
---
- …
=> :sparkles: (llm) update text in setup device drawer

apps/ledger-live-desktop/src/renderer/screens/earn/index.tsx, apps/ledger-live-mobile/src/helpers/getStakeLabelLocaleBased.ts, apps/ledger-live-mobile/src/screens/PTX/Earn/index.tsx
- Just one more variable to be passed to Earn dashboard webview
This PR adds the country from the device locale to be passed to Earn dashboard.
---
=> Pass country from locale as param to Earn dashboard

apps/ledger-live-desktop/tests/fixtures/common.ts, apps/ledger-live-desktop/tests/specs/speculos/delegate.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts
- ...
broadcasting on Monday for scheduled workflows only 
[test for workflow dispatch](https://github.com/LedgerHQ/ledger-live/actions/runs/12008148500/job/33470197914#step:8:47) (rolled back since to comply with schedule)
[SOLANA explorer to testify of broadcast](https://solscan.io/account/HxoKQ5eu5MkqaAw7DaGVermrJqeNH8XkVnEKEpFuS9id)
- **JIRA or GitHub link**: /
--- …
=> DISABLE_TRANSACTION_BROADCAST logic moved to tests suites

apps/ledger-live-desktop/tests/fixtures/common.ts, apps/ledger-live-desktop/tests/page/modal/add.account.modal.ts, apps/ledger-live-desktop/tests/page/modal/send.modal.ts, apps/ledger-live-desktop/tests/specs/speculos/add.account.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts
- ...
- Removed MOCK_COUNTERVALUES for speculos tests
- Fix XRP send test
- Add check for Ton add Account
---
=> [QAA] fixing CounterValues (speculos e2e) + fixing send e2e test (new modal) - XRP 

.changeset/rotten-horses-shop.md, apps/ledger-live-desktop/tests/page/modal/receive.modal.ts, apps/ledger-live-desktop/tests/page/speculos.page.ts, apps/ledger-live-desktop/tests/specs/speculos/receive.address.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/subAccount.spec.ts, libs/ledger-live-common/src/e2e/enum/Account.ts
- ...
Update BTC address
Change NFT to be send
Update methode to check address on receive test
---
=> [QAA] fixing Nightly E2E CI + improving Receive E2E test
