- .changeset/quiet-coats-hang.md
- apps/ledger-live-mobile/src/screens/Market/MarketRowItem.tsx
- **Impacted projects**: ledger-live-mobile
- **Linked resource(s)**: [LIVE-1396]
On the market screen of ledger-live-mobile, when the currency name is too long the price is overlapped.
[LIVE-1396]: https://ledgerhq.atlassian.net/browse/LIVE-1396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: overlapped price on market screen

- libs/ledger-live-common/package.json
- pnpm-lock.yaml
- **Impacted projects**: [`live-desktop`, `@ledgerhq/live-common`, `live-mobile`]
Solana `web3.js` library has recently switched to `BigInt`. But since `BigInt` is not supported in the current version of react native in `live-mobile` it's needed to downgrade `web3.js`.
No changes should be noticeable in any user facing project.
> Solana: downgrade web3 - RN doesnt support BigInt

- .changeset/famous-cougars-occur.md
- apps/ledger-live-desktop/src/renderer/reducers/settings.js
- apps/ledger-live-desktop/src/renderer/screens/market/CountervalueSelect.tsx
- **Impacted projects**: `live-desktop`
- **Linked resource(s)**: [LIVE-2421]
Fix potential issue in countervalueselect component when some values could be undefined and `toLowerCase` could not be applied
[LIVE-2421]: https://ledgerhq.atlassian.net/browse/LIVE-2421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-2421 - Desktop - fix potential crash issue during navigation

- apps/ledger-live-mobile/fastlane/Fastfile
- **Impacted projects**: `live-mobile`
The current state of affairs is that we use a [complex serialization function](https://github.com/LedgerHQ/ledger-live/blob/develop/apps/ledger-live-mobile/fastlane/Fastfile#L29) during Fastlane builds to produce the [android version code](https://developer.android.com/studio/publish/versioning) from the version field inside package.json.
This is not good enough since it can become flaky when trying to release more than 2 tracks (nightly / prerelease (next) + potentially others).
**The solution:** query the google play console and take the highest version code, then just add one.
N/A
_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-step …
> Auto-increment android version code

- .changeset/wild-papayas-bow.md
- apps/ledger-live-mobile/index.js
- apps/ledger-live-mobile/src/index.js
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-2409
due to some recursive objects in our stack and passed in navigation, it makes Sentry crash when tracking the performance. problem was reported to https://github.com/getsentry/sentry-javascript/issues/2470 but in the meantime, we are disabling the feature for now.
> Disable React Navigation sentry integration

- .changeset/silly-pots-clap.md
- apps/ledger-live-mobile/src/components/DeviceAction/index.js
https://ledgerhq.atlassian.net/browse/LIVE-2492
In production mode (so on TestFlight), we have a crash when a device is offline and trying to delegate with Cosmos and the Nano is on the dashboard. 
This PR prevents that by removing a new tracking that we have on Device Actions errors that is causing the crash (network call while offline + result of a device action)
> [LIVE-2492] - Bugfix: Preventing crash w/ offiline device action error

- .changeset/strong-penguins-chew.md
- apps/ledger-live-mobile/ios/ledgerlivemobile.xcodeproj/project.pbxproj
- **Impacted projects**: ledger-live-mobile
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-2493
This increases the minimum supported iOS version of Ledger Live Mobile from 12 to 13 due. It means that we will stop supporting iPhone 6 and below. 
> LLM: increase to iOS 13 minimum

- apps/ledger-live-mobile/android/app/src/main/AndroidManifest.xml
see https://docs.sentry.io/platforms/android/configuration/app-not-respond/
As we tend to see a bunch of 5s timeout, we're trying to be a bit more permissive in allowing slowness of 5s, now up to 10s to be a safe timeout to really detect possible "infinite loop" in case it happens in future.
- **Impacted projects**: llm
- **Linked resource(s)**: Sentry LEDGER-LIVE-MOBILE-5K
> LLM Android: Sentry: Increase ANR timeout to 10s

- .github/workflows/prerelease.yml
- **Impacted projects**: `automation`, `llm`
With the voodoo we made last week, build number shouldn't be a problem anymore on either LLM iOS or LLM Android, allowing us to have unlimited builds on mobile as well, thus this PR aims to add a prerelease build of LLM during a `prerelease` workflow
NO DEMO
it should build a LLM version on prerelease workflow
> trigger mobile build on prerelease

- .changeset/lazy-pants-travel.md
- libs/ledger-live-common/src/families/ethereum/specs.ts
- **Impacted projects**: bot tests (ethereum)
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-2330
According to a Bot notEnoughBalance error on Polygon, maxSpendable replaces now the amount balance for testing
> Bugfix LIVE-2330  [BOT] Polygon NotEnoughBalance error

- apps/ledger-live-desktop/src/main/updater/init.js
- apps/ledger-live-desktop/src/renderer/Default.js
Since we rely on the `package.json` version to determine if we are in prerelease mode, and the CI now adds the `vX.Y.Z.sha.commithash` in our builds to better differenciate which ones we are currently testing, I've added a check to make sur those builds are not considered as prerelease
- **Impacted projects**: `ledger-live-desktop`
NO DEMO
CI builds should not have the waternark anymore
> dont display overlay on ci builds

- .github/labeler.yml
The Github labeler add a `screenshots` tag whenever we modify the content of `desktop/tests/specs/**/*`, but sometime we modify or add tests without making changes to the snapshots. I updated the path to `desktop/tests/specs/*-snapshots/*` instead.
- **Impacted projects**: N/A 
> Update Github labeler path for screenshot label

- .changeset/dry-trains-drive.md
- apps/ledger-live-desktop/src/main/internal-lifecycle.js
a code was still there to remove the sqlite log files on app close. It's no longer needed as the app is no longer creating this sqlite folder: libcore is gone. On top of this, I believe these .log file creations were disabled more than a year ago, so it's long gone!
This will improve performance of closing the app, remove unnecessary access to filesystem (which was even done in sync!)
nothing to demo
> post libcore sunset, remove unecessary sqlite clean up

- apps/ledger-live-mobile/src/screens/Onboarding/steps/discoverLiveInfo.tsx
- libs/ui/packages/native/src/components/Carousel/index.tsx
maxDurationTap parameter added to the carousel to be able to trigger only short taps
scroll disabled on the reborn carousel
- **Impacted projects**: `ledger-live-mobile` `native-ui` 
- JIRA : [LIVE-1813]
[LIVE-1813]: https://ledgerhq.atlassian.net/browse/LIVE-1813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Reborn - Improvements on how we handle the gestures on the carousel

- .changeset/unlucky-jars-speak.md
- apps/ledger-live-mobile/src/screens/Exchange/Buy.js
- apps/ledger-live-mobile/src/screens/Platform/App.js
The platform manifest can be undefined when the user has no network.
Handling this simply because this code will change soon with multibuy 1.5.
- **Linked resource(s)**: [`LIVE-2571`](https://ledgerhq.atlassian.net/browse/LIVE-2571) 
> fix(LLM): platform manifest can be undefined when no network [LIVE-2571]

- apps/ledger-live-mobile/src/components/Carousel/shared.tsx
- apps/ledger-live-mobile/src/components/TabBar/TransferDrawer.tsx
- apps/ledger-live-mobile/src/config/urls.tsx
Two entry points added redirecting to CL Card Live App in the portfolio recommended section and in the transfer menu in the navbar
- **Linked resource(s)**: [LIVE-2088]
https://user-images.githubusercontent.com/17146928/172883160-46156417-d812-4262-a37d-a2269a3bed77.mp4
[LIVE-2088]: https://ledgerhq.atlassian.net/browse/LIVE-2088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Two entry points added redirecting to CL Card Live App in the portfolio recommended section and in the transfer menu in the navbar 

- .changeset/thin-bees-happen.md
- libs/ui/packages/native/src/components/Layout/ScrollListContainer/index.tsx
The ScrollListContainer component was not forwarding the ref being passed to it so 2 issues with that:
- in LLM we were passing a ref to a functional component so that was triggering a warning
- since the ref was not actually being passed, any imperative call on this ref (for instance to scroll the flatlist to the top) would not do anything.
- **Impacted projects**: `native-ui` `ledger-live-mobile` 
- **Linked resource(s)**: no ticket sorry just a message from @juan-cortes on Slack https://ledger.slack.com/archives/C0308JT8WS2/p1654850897917099
> <img width="355" alt="Screenshot 2022-06-10 at 11 42 54" src="https://user-images.githubusercontent.com/91890529/173038487-335f495c-348b-4817-8dba-5fb1c03e89f3.png"> …
> Fix: native-ui ScrollListContainer forwardRef

- .changeset/silly-bulldogs-mate.md
- apps/ledger-live-desktop/src/renderer/modals/WalletConnectPasteLink/Body.js
- libs/ledger-live-common/src/walletconnect/Provider.tsx
Unfortunaltey I didn't find a good way to reproduce the bug yet. BUT, the explanation is:
- On unknown events, WalletConnect connexion is not closed correctly, therefore we never remove the `walletconnect` entry from the `localStorage`
- It results with the user never being able to use WalletConnect anymore
- Removing the entry allows for WalletConnect to work again
This PR adds a `catch` on the `WalletConnect.killSession` that can sometimes return this error: 
It probably is the culprit for never really removing the `localStorage` entry.
Result is: 
If you can kill the session properly, then do it (common case)
If you can't kill it, either because of the unkown event, or because you've touched by the bug before and your entry cannot be removed, then just force remove the entry.
That …
> LIVE-2632 - Bugfix: WalletConnect error on disconnect

- .changeset/funny-pianos-mix.md
- apps/ledger-live-desktop/README.md
- apps/ledger-live-desktop/src/renderer/screens/market/MarketCoinScreen/MarketInfo.tsx
Removed Currency from circulating supply in market/coin info
BUGFIX for LLD
In the currency's info under Circulating Supply was shown a currency which shouldn't be there. Removed it.
> LIVE-2324 - Removing currency for Circulating supply

- libs/ledger-live-common/src/apps/polyfill.ts
Add dep between plugin and Ethereum app
- **Impacted projects**: L Market
- **Linked resource(s)**: None
n/a
n/a
> support: add dep for L Market app

- .changeset/five-cougars-exercise.md
- apps/ledger-live-mobile/src/index.js
- apps/ledger-live-mobile/src/screens/Platform/index.js
- apps/ledger-live-mobile/src/screens/Platform/shared.tsx
This PR contains a fix for deep linking to discover apps on iOS. It was not working anymore as it relied on the platform catalog screen for redirection to the given discover app, and that screen does not exist anymore on iOS.
The solution implemented here is to do the redirection (if and only if the discover app exists) directly by using [`getStateFromPath`](https://reactnavigation.org/docs/navigation-container#linkinggetstatefrompath) in the deep linking configuration of `react-navigation`.
**PS:** I also tested WalletConnect deep linking and all other deep links as the ticket was a bit vague and suggested testing all links, check the `📸 Demo` section below.
**PS2:** I also made deep linking URIs for platform apps **case insensitive** as one of the comments on the Jira ticket was …
> Bugfix: LIVE-2484 LLM deeplinking fixes

- libs/ledger-live-common/src/apps/polyfill.ts
Add dep between plugin and Ethereum app
This PR is the equivalent of #334 for the release branch.
- **Impacted projects**: L Market
- **Linked resource(s)**: None
n/a
n/a
> LIVE-2634 support: add dep for L Market app for release

- .github/workflows/release-prerelease.yml
Use the current ref to trigger the prerelease job on LLB for LLM prereleases
No Demo
Build from the correct branch
> add ref on mobile prerelease job trigger

- .changeset/olive-camels-scream.md
- libs/ledger-live-common/src/apps/support.ts
This PR fixes an error being thrown for you to upgrade your app when using a pre-release version of a Nano App
- **Linked resource(s)**: `None` 
https://user-images.githubusercontent.com/44363395/173400026-631d82a9-6943-4c7e-8986-5b3815b97ba3.mov
https://user-images.githubusercontent.com/44363395/173400069-dffab49a-b6db-4523-92d3-a91cfaa296b8.mov
> Bugfix - Allow pre-release tags in mustUpgrade or shouldUpgrade

- .changeset/strong-buckets-listen.md
- libs/ledger-live-common/src/families/cardano/js-synchronisation.ts
Incremental sync for Cardano was based on `account.blockHeight` to know from which block to start sync. For some reason this field is not reset to 0 during clear cache (maybe it should?), which causes sync to only get data after this block height instead of 0.
The fix consists in using the blockHeight of the last operation, which unlike `account.blockHeight` is correctly 0 after a clear cache.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-2664
> LIVE-2664 Fix incremental sync for Cardano

- libs/ledger-live-common/dependencies.md
- libs/ledger-live-common/package.json
- pnpm-lock.yaml
This PR rollbacks the `@solana/web3.js` to `1.41.3` to prevent the usage of the next versions that are using BigInt which is incompatible with the Hermes js engine right now.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-2669` 
Can't provide more than a screenshot of 2 working transactions made on iOS with this fix since I don't have the funds to do the test again and record it 😋 
> [LIVE-2669] - Bugfix: fix solana dependencies using bigint

- apps/ledger-live-mobile/index.js
We want to increase from 20% to 100% on the sampling rate of Sentry to have more events.
Also filtering out one frequent normal applicative issue.
> Set sampleRate to 100% on LLM + ignore 1 error

- .changeset/shy-meals-yell.md
- apps/ledger-live-mobile/src/components/Nft/NftImage.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/NftNavigator.tsx
LLM - Adding the back button to NFT Viewer and fixed background issue (the skeletton was still loading in the background. Passed the header to transparent so it has no background and is positionned to "absolute" preventing the image to get down in the view.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-2539 https://www.figma.com/file/gmYzg5ekdRJ9tK3KuviFFu/LLM-%2F-NFT?node-id=211%3A560 
before : 
after :
Animation : 
https://user-images.githubusercontent.com/39890664/174078208-b2bc1423-4dae-4b18-8c6a-e5bbe2c7f0b3.mp4 …
> [live 2539] LLM - Back button in NftViewer

- .changeset/fair-seals-switch.md
- apps/ledger-live-desktop/src/main/window-lifecycle.js
- apps/ledger-live-desktop/src/renderer/components/WebPlatformPlayer/index.js
This bug was caused by a "kinda undocumented" electron 15 breaking change which impacted webviews indirectly.
`nativeWindowOpen` has been made `true` by default with electron 15, this PR restores the previous behaviour.
_Note:  both webviews and the api we use are marked as deprected by Chrome and Electron. It might be a good time to rewrite._
See:
- https://www.electronjs.org/docs/latest/breaking-changes#planned-breaking-api-changes-150
- https://github.com/electron/electron/issues/31117
- https://github.com/electron/electron/issues/34678
https://user-images.githubusercontent.com/3428394/174999359-465986ba-8947-4c18-8f53-a87ceeb87a74.mov …
> Fix opening external windows from a webview

- .changeset/wise-bears-tease.md
- .changeset/witty-dodos-drop.md
- apps/ledger-live-mobile/src/components/WebViewScreen/index.tsx
_Bug issue when reloading webviews in LLM. the root cause was due to the native library not handling the layout shift correctly and messing up the rendering thus crashing.
We can fix that by not shift the layout of loading states but use a layered approach instead_
- **Linked resource(s)**: [LIVE-2730] 
[LIVE-2730]: https://ledgerhq.atlassian.net/browse/LIVE-2730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-2730 - bugfix - LLM issue on webview reload crashes

- .changeset/twelve-paws-whisper.md
- libs/ledger-live-common/src/families/ethereum/hw-signMessage.ts
This PR fixes the usage of process.env that parses everything as a string, which made the environment variable `EXPERIMENTAL_EIP712` always true. 
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-2729` `https://ledgerhq.atlassian.net/browse/LIVE-2728` 
Before
https://user-images.githubusercontent.com/44363395/175046843-f6a45e2c-2ebe-44a8-8776-00bec1d3a941.mov
After
https://user-images.githubusercontent.com/44363395/175046882-483ae5ae-a0d7-41be-af34-89363062e0ab.mov
> [LIVE-2728][LIVE-2729] Bugfix - Fix usage of process.env instead of getEnv

- .changeset/fuzzy-lemons-breathe.md
- apps/ledger-live-mobile/src/components/AccountGraphCard.tsx
In account/AccountGraph, when switching to crypto as a main value, the crypto amount had too many decimals with specific cryptos (BTC, ETH...).
Rounding was disabled on that field. Enabling it only if we are in counterValue mode (aka when we use crypto as main value). Not enabling it all the time to prevent re-rounding the other value.
- **Linked resource(s)**:  https://ledgerhq.atlassian.net/browse/LIVE-2271
https://user-images.githubusercontent.com/39890664/174752512-43afea38-9aea-4f4f-9baa-0a85ab1fe53a.mp4
> Rounding the main value of AccountGraph when using counterValue

- .changeset/hungry-queens-beg.md
- libs/ui/packages/icons/package.json
Added the "star" kind of [subpath exports](https://nodejs.org/api/packages.html#subpath-exports) to `@ledgerhq/icons-ui`. (`/path/*`)
The `/trailing-slash/` way of writing [subpath exports](https://nodejs.org/api/packages.html#subpath-exports) is deprecated and will not be supported in nodejs 17+. 
`jest-resolve` also has issues with the syntax, which impacts some of our external devs:
- https://github.com/LedgerHQ/buy-sell-live-app/pull/83
- **Impacted projects**: `@ledgerhq/icons-ui` 
> Better icons-ui subpath exports compatibility

- .github/workflows/test-integration.yml
The concurrency make sure it allows to let parallel runs to happen and not be cancelled into each other, as the goal of test-integration is to be run in parallel "on demand". e.g. running stellar tests on stellar PR and at same time running ethereum tests on another PR.
showscase of the problem:
> Fixes 'concurrency' of test-integration

- .github/workflows/test.yml
- .pnpmfile.cjs
- package.json
- pnpm-lock.yaml
- tools/pnpm-utils/index.js
`pnpm-lock.yaml` has been inconsistent for a while, and needed 2 passes of `pnpm i` to attain its final shape.
This is likely to be caused by `debug` being an optional peer dep of `follow-redirects`.
**Update:** There are still some checksum algorithm diffs from time to time (`concat-map` integrity is sometimes using `sha1`, other times `sha512`)… After investigating a bit is seems like this is unavoidable.
- Side effect: upgrades turborepo to 1.3.1
- **Impacted projects**: `ledger-live`
- **Linked resource(s)**: `N/A`
N/A
> chore: make pnpm lockfile deterministic

- apps/ledger-live-desktop/src/logger/anonymizer.js
- apps/ledger-live-desktop/src/logger/logger.js
- apps/ledger-live-desktop/src/main/internal-lifecycle.js
- apps/ledger-live-desktop/src/sentry/install.js
- the $HOME of user is used instead of $PWD to anonymize the Sentry report of LLD and replace it with a "."
- remove the tracking of http in Sentry LLD because it's not useful enough to investigate problems (it can come back again in future) and remove the associated need to anonymize it.
- adding a console.log to always see when a Sentry report is sent, to help debugging this.
to reproduce, I have used the same method as in #275 and I have run the app from `/` folder.
> Simplify sentry logic and replace home paths into "." in sentry report

- .github/workflows/generate-screenshots.yml
- .github/workflows/test-desktop.yml
Splits `pnpm turbo run ledger-live-desktop#build:testing` into 2 steps: `pnpm build:lld:deps` then `pnpm desktop build:testing`.
Also decreased the memory pressure done by the go garbage collector.
N/A
> ci: attempt to reduce ram usage when running windows playwright tests

- .changeset/brown-mugs-beam.md
- apps/cli/src/commands-index.ts
- apps/cli/src/commands/synchronousOnboarding.ts
- libs/ledger-live-common/src/hw/extractOnboardingState.test.ts
- libs/ledger-live-common/src/hw/extractOnboardingState.ts
- libs/ledger-live-common/src/hw/getOnboardingStatePolling.test.ts
- libs/ledger-live-common/src/hw/getOnboardingStatePolling.ts
- libs/ledger-live-common/src/onboarding/hooks/useOnboardingStatePolling.test.ts
- libs/ledger-live-common/src/onboarding/hooks/useOnboardingStatePolling.ts
- libs/ledger-live-common/src/types/manager.ts
- libs/ledgerjs/packages/errors/src/index.ts
3 features in live-common:
- Function to extract the device onboarding state from byte flags
- Polling mechanism to retrieve the device onboarding state
- Make the polling mechanism available as a react hook for LLM and LLD
- **Impacted projects**: `live-common`
- **Linked resource(s)**: [FAT-13](https://ledgerhq.atlassian.net/browse/FAT-13?atlOrigin=eyJpIjoiNjdmN2UxOTdmNGQ1NGMyMGEyYmUxN2M4YWMzZGVmMjEiLCJwIjoiaiJ9)
Videos have been posted on Slack from [this POC](https://github.com/LedgerHQ/ledger-live/pull/214)
> feat/FAT-13 Sync Onboarding logic

- .github/workflows/release-prerelease.yml
The current CI process for a prerelease is the following:
- bump package versions
- publish libraries to npm
- tag the libraries
- push the tags _<-- Potential issue here_
- trigger LLD/LLM prerelease
The problem is that if someone pushes a commit after the action is started it will fail when pushing tags because the CI branch will not be up to date with the remote.
`git pull` before pushing the tags
N/A
> A bit safer CI prereleases

- .changeset/popular-weeks-shake.md
- libs/ledger-live-common/src/families/bitcoin/js-synchronisation.ts
- libs/ledger-live-common/src/families/bitcoin/logic.ts
- libs/ledger-live-common/src/families/bitcoin/xpub.txs.txNoOutput.unit.test.ts
Crash fix for the case when  there is a transaction with no output for bitcoin family.
Here is an example for a transaction without output: https://zecblockexplorer.com/tx/d1c35527078ceaba10e0e7676aff760b34b419cf7504134e93519814582816dc
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-2748
No demo as it is a bug fix
No crash
> [LIVE-2748] fix crash when there is a transaction with no output for bitcoin

- .changeset/moody-moons-dance.md
- apps/ledger-live-mobile/src/index.js
- apps/ledger-live-mobile/src/screens/Portfolio/ReadOnly/ReadOnlyAssets.tsx
- apps/ledger-live-mobile/src/screens/Settings/Developer/CustomManifest.js
We should import using `/lib` and not `/src`, this causes some global variables to be empty and was breaking adding a custom manifest.
- **Linked resource(s)**: [`LIVE-2893`](https://ledgerhq.atlassian.net/browse/LIVE-2893) 
> fix: imports should use /lib and not /src

- .changeset/odd-pigs-admire.md
- libs/ledger-live-common/src/errors.test.ts
- libs/ledgerjs/packages/errors/src/helpers.ts
- libs/ledgerjs/packages/errors/src/index.test.ts
> NB: this PR includes part of the PR #509 (former PR is more acting as a playground)
We are often seeing these wrong stacktrace and location of the error:
this is due to the usage of `new Error().stack`. We replace it with a more modern polyfill, inspired by https://exploringjs.com/impatient-js/ch_exception-handling.html#an-alternative-to-.cause-a-custom-error-class
Tests were added to confirm that we now have the properly location in the stacktrace.
this also introduces a 3rd parameter that will be passed to the second parameter of the Error constructor. This allows to pass in a `cause` field (which is also polyfilled). NB: this .cause usage is not yet getting used in our libraries, but if we ever have the need to "recover an error into another", this would be the pattern:
```js
try { …
```
> Improve custom errors stacktrace management

- .changeset/tiny-roses-refuse.md
- libs/ledger-live-common/src/api/Ethereum.ts
- libs/ledger-live-common/src/bridge/jsHelpers.ts
- libs/ledger-live-common/src/families/ethereum/bridge/js.ts
- libs/ledger-live-common/src/families/ethereum/datasets/ethereum2.ts
- libs/ledger-live-common/src/families/ethereum/synchronisation.integration.test.ts
- libs/ledger-live-common/src/families/ethereum/synchronisation.ts
- libs/ledger-live-common/src/operation.ts
This PR adds a failsafe to Ethereum incremental synchronisation which is based on the latest "stable" block hash in the Account's operations history.
As of right now a block is considered safe based on an arbitrary value `SAFE_REORG_THRESHOLD` set at `80`, but it looks like even with this security we can end up with a block hash that doesn't exist on chain.
The failsafe will now make sure a block exists before trying an incremental sync from it, and if it doesn't it's going to do a full sync instead.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-2497 
Can't really be demoed. But an integration test reproducing the issue has been added. …
> [LIVE-2497] - Bugfix: Handle reorg on Eth family sync

- .changeset/dirty-balloons-sort.md
- apps/ledger-live-mobile/src/components/AnalyticsConsole.js
Empty the analytics overlay when activating it in debug settings, so there is no flooding of past events when you initialize it.
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-2719
> Bug fix - LIVE-2719 - Empty analytics overlay when activating it

- .changeset/hot-avocados-dream.md
- apps/ledger-live-mobile/src/components/BottomModal.tsx
Inline app install was not working because we lock the modal during the install and it was closing the modal instead.
By removing a dependency on `modalLock` in the `useEffect` we avoid to call `onClose` thinking this is a duplicate modal because of `isModalOpenedref` being `true`.
- **Linked resource(s)**: [`LIVE-2851`](https://ledgerhq.atlassian.net/browse/LIVE-2851) 
> fix: Inline app install not working [LIVE-2851]

- apps/ledger-live-desktop/src/main/InternalProcess.js
This change have no impact from the user perspective. However, on Sentry reporting side, we receive a bunch of `Process not running` error cases, which is useless and in that case, a stop() should have "no effect".
This PR changes the promise to not THROW an exception but simply have a boolean to know if the stop() effectively killed a process or not. This will make the `InternalProcess#restart()` method truly work too (even tho it's currently not used anywhere)
- **Linked resource(s)**: https://sentry.io/organizations/ledger/issues/3405017439
_Pull Requests must pass the CI and be internally validated in order to …
> Improve InternalProcess stop() to not throw error if not running

- .changeset/shiny-swans-tickle.md
- apps/ledger-live-desktop/src/internal/index.js
- apps/ledger-live-desktop/src/main/internal-lifecycle.js
- apps/ledger-live-desktop/src/renderer/App.jsx
- apps/ledger-live-desktop/src/renderer/components/ConnectEnvsToSentry.tsx
- apps/ledger-live-desktop/src/sentry/internal.js
- apps/ledger-live-desktop/src/sentry/main.js
- apps/ledger-live-desktop/src/sentry/renderer.js
- apps/ledger-live-mobile/index.js
- apps/ledger-live-mobile/src/components/FirebaseFeatureFlags.tsx
- apps/ledger-live-mobile/src/index.js
On Sentry, we currently don't know if any experimental OR feature flag has been enabled in context of an error, which is very valuable to know about.
Trade-off: this works with "polling". The current implementation will regularly sync the tags so they are always correct when an error arise.
This PR only do this on LLM as the LLD PR isn't merged there, but we'll eventually also apply the same idea to LLD.
- **Impacted projects**: LLM and LLD 
We can see the env and the feature flags
> Sentry: add more env context on errors

- apps/ledger-live-desktop/src/renderer/components/ConnectEnvsToSentry.tsx
- apps/ledger-live-mobile/index.js
Polishes from merged PR #386 feedbacks
> Polishes from merged PR #386 feedbacks

- .changeset/funny-goats-poke.md
- libs/ledgerjs/packages/cryptoassets/src/currencies.test.ts
- libs/ledgerjs/packages/cryptoassets/src/currencies.ts
Set Goerli currency on coinType=60 per eth accepted convention. 
as it's the [second time](https://github.com/LedgerHQ/ledgerjs/commit/3079bd5feec6720ae70eb82696d5392eea0f919a) we do this mistake in history of Ledger Live, a test was added to make sure we don't do it again. 
- **Impacted projects**: LLM and LLD in Developer settings mode (testnet coin)
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-2923
> Set Goerli currency on coinType=60 per eth accepted convention

- .github/workflows/test-integration.yml
- libs/ledger-live-common/src/countervalues/api/api.ts
- libs/ledger-live-common/src/countervalues/logic.integration.test.ts
- libs/ledger-live-common/src/countervalues/logic.ts
- libs/ledger-live-common/src/countervalues/modules/index.ts
- libs/ledger-live-common/src/countervalues/types.ts
- This improves the test of countervalues with a "strict mode" that disable recovering errors in the countervalues logic (only for test purpose).
- This improves work done at #486 (after having added there a test that reveal a problem) and implements chunking of 50 tickers max to fetch at once in "latest" API.
- **Impacted projects**: `LLM & LLD` 
- **Linked resource(s)**: `LIVE-2767` 
```
PASS  src/countervalues/logic.integration.test.ts
API sanity
✓ recent days have rate for BTC USD (197 ms)
✓ recent days have different rates for BTC USD (58 ms)
extreme cases
✓ all tickers against BTC (507 ms)
Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        4.001 s
```
console logging the chunked payloads before concat() them
_Please make sure you follow …
> countervalues: Chunk batch the fetch of latest and improve tests

- apps/ledger-live-mobile/fastlane/Fastfile
- apps/ledger-live-mobile/package.json
**Add a lane to sync provisioning profiles between apple connect and our private repository.**
- **Linked resource(s)**: https://github.com/LedgerHQ/ledger-live-build/pull/17 
> chore(llm): add lane to sync apple profiles

- .github/workflow-templates/bot-coin-family.yml
- .github/workflows/backup/version-or-release.yml
- .github/workflows/bot-bitcoin-mooncake.yml
- .github/workflows/bot-cardano-silicium.yml
- .github/workflows/bot-filecoin.yml
- .github/workflows/bot-phosphore.yml
- .github/workflows/bot-staging-explorer-btc.yml
- .github/workflows/bot-staging-explorer-eth.yml
- .github/workflows/bot-transfer.yml
- .github/workflows/build-desktop.yml
- .github/workflows/build-mobile.yml
- .github/workflows/release-create-hotfix.yml
- .github/workflows/release-create.yml
- .github/workflows/release-final-nightly.yml
- .github/workflows/release-final.yml
- .github/workflows/release-prepare-desktop.yml
- .github/workflows/release-prepare-hotfix.yml
- .github/workflows/release-prepare-mobile.yml
- .github/workflows/release-prerelease.yml
- .github/workflows/test-integration.yml
- .github/workflows/test-mobile.yml
- .github/workflows/test.yml
- .npmrc
- tools/actions/composites/setup-test-desktop/action.yml
Setting `loglevel=warn` prevents `pnpm store` from outputting multiple lines instead of a single one.
Should fix the CI until pnpm publishes a fix.
- **Linked resource(s)**: https://github.com/actions/setup-node/issues/543 
> Workaround to re-enable pnpm cache in the CI

- apps/ledger-live-mobile/fastlane/.env.adhoc
- apps/ledger-live-mobile/fastlane/.env.mock
- apps/ledger-live-mobile/fastlane/.env.nightly
- apps/ledger-live-mobile/fastlane/.env.production
- apps/ledger-live-mobile/fastlane/.env.staging
- apps/ledger-live-mobile/fastlane/Fastfile
- pnpm-lock.yaml
It seems using wildcards for bundle ids in iOS in conjunction with deeplinks actually breaks the build of iOS' .ipa. Removing the wildcard and moving back to "com.ledger.live.dev" for a simpler workflow
I've added to apple dev portal a new bundle id `com.ledger.live.dev` and will soon depreciate the old one. I've been using `fastlane match` to update the profiles accordingly. Nothing to do on ledger-live-build side as all the bundle ids are handled here
NO DEMO
Ledger Live Build repo is still able to produce adhoc .ipa  …
> remove wildcards bundle id for iOS

- .changeset/friendly-clocks-begin.md
- .changeset/stale-trains-sneeze.md
- apps/ledger-live-desktop/.flowconfig
- apps/ledger-live-desktop/src/renderer/components/BalanceInfos/index.jsx
- apps/ledger-live-desktop/src/renderer/components/ButtonV3.tsx
- apps/ledger-live-desktop/src/renderer/components/Illustration.tsx
- apps/ledger-live-desktop/src/renderer/modals/TermOfUseUpdate/TermOfUseUpdateBody.tsx
- apps/ledger-live-desktop/src/renderer/screens/account/AccountActionsDefault.jsx
- apps/ledger-live-desktop/src/renderer/screens/asset/AssetBalanceSummaryHeader.jsx
- apps/ledger-live-desktop/src/renderer/screens/market/MarketCoinScreen/MarketCoinChart.tsx
- apps/ledger-live-desktop/src/renderer/screens/market/MarketDataProviderWrapper.tsx
- apps/ledger-live-desktop/src/renderer/styles/StyleProviderV3.tsx
- libs/ui/packages/react/src/components/layout/Drawer/index.tsx
- libs/ui/packages/react/src/components/layout/Popin/index.tsx
- libs/ui/packages/react/src/index.ts
- libs/ui/packages/react/src/styles/InvertTheme.tsx
- libs/ui/packages/react/src/styles/index.ts
This PR adds `StyleProviderV3`, a wrapper component that can be used anywhere in the app to wrap components that are supposed to use the v3 styling & design system (`@ledgerhq/react-ui lib`).
The easy way to use this component is to use the associated HOC `withStyleProviderV3` and directly export your screen that uses v3 design like that: `export default withStyleProviderV3(MyComponent)`.
The PR also includes:
- some fixes on the `react-ui` lib regarding some colors that were outdated in the Popin & Drawer components.
- an `InvertThemeV3` wrapper
There are no user facing changes in this PR (the new stuff on LLD isn't used yet, the changes in react-ui either).
The changes in this PR are a subset of @pierrelouis-c 's work in https://github.com/LedgerHQ/ledger-live/pull/593 as this will PR …
> Add StyleProviderV3 to safely use UI lib in LLD

- .changeset/curvy-walls-greet.md
- libs/ledger-live-common/src/families/bitcoin/datasets/bitcoin.ts
- libs/ledger-live-common/src/families/bitcoin/descriptor.ts
- libs/ledger-live-common/src/families/bitcoin/js-synchronisation.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/storage/index.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/storage/types.ts
1. When we did the migration from the field "hash" to "id", the bitcoin sync may be broken
2. xpub is undefined during sync from sentry report. we try to fix it in this PR
- **Impacted projects**: `` LLC
https://ledgerhq.atlassian.net/browse/LIVE-2643
https://ledgerhq.atlassian.net/browse/LIVE-2914
No demo for a bug fix
Bitcoin sync correctly
> LIVE-2643 LIVE-2914 fix xpub null and "hash" to "id" migration

- libs/ledger-live-common/src/load/speculos.ts
LIVE-3008
In the speculos coin apps search logic, we will filter out by default all app version that have a "-" in it.
- **Linked resource(s)**:live-3008 
I managed to fix the problem observed on #ledger-live-bot,
I can confirm my fix works by looking at it resolved using
```
VERBOSE=1 pnpm run:cli sync --device 'speculos:nanos:zcash'
```
which is now selecting :
```
debug: using app Zcash 2.0.6 on nanoS 2.1.0
```
> bot: fixes ZCash

- libs/ledger-live-common/src/bot/index.ts
> 12 specs don't have enough funds! (Bitcoin, Dash, Qtum, ZCash, Decred, cardano, Cosmos, Crypto.org, Elrond, Ethereum, Ethereum Goerli, Tron)
bot is currently warning on coins that we are likely not going to funds (Bitcoin, Ethereum) because too expensive, **yet** they are backed up by Testnet. We assume here that testnet covered spec will be enough to not warn the missing funds problem.
- **Linked resource(s)**: `none (support #ledger-live-bot)` 
> Specs without funds that are backed by testnet to no longer be warned

- .changeset/afraid-poets-trade.md
- .github/workflows/test-integration.yml
- libs/ledger-live-common/src/countervalues/api/api.ts
- libs/ledger-live-common/src/countervalues/logic.integration.test.ts
- libs/ledger-live-common/src/countervalues/logic.ts
- libs/ledger-live-common/src/countervalues/modules/index.ts
- libs/ledger-live-common/src/countervalues/types.ts
_Updated LLC countervalues pair method from POST legacy format to GET format_
- **Impacted projects**: `ledger-live-common` affects -> `ledger-live-desktop`  `ledger-live-mobile`   
- **Linked resource(s)**: [LIVE-2767] 
To test:
check on LLD that theres no regression in countervalues shown and that the switch of countervalues is correct.
basically the goall is to have the same values before this update than after.
The impacted areas are all countervalues related to accounts imported by the nano (the market page is not impacted) 
you can check it on those sections …
> LIVE-2767 LLC - Countervalues API method change

- apps/ledger-live-mobile/fastlane/Fastfile
Another attempt to prevent CI runners from staying on for 6 hours. (LLB)
Next nightly should not last 6h and then fail (LLM)
> stop clogging up runners for 6 hours

- .changeset/weak-queens-shout.md
- libs/ledger-live-common/src/__tests__/test-helpers/bridge.ts
?
Bridge integration tests didn't include a test of the `AmountRequired` error, i.e they were not testing that when the transaction amount is 0 or not provided we return an error.
- **Linked resource(s)**: - 
Integration tests passing for all currencies (but currently broken for many other reasons)
> Add a bridge test for AmountRequired

- .changeset/afraid-moles-train.md
- apps/ledger-live-mobile/src/components/FirmwareUpdateBanner.tsx
- apps/ledger-live-mobile/src/components/SelectDevice/index.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/logic/firmwareUpdate.ts
Use better wording for when the Firwmare update is available but the user is connected via Bluetooth instead of USB.
[LIVE-2955]
[LIVE-2955]: https://ledgerhq.atlassian.net/browse/LIVE-2955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-2955 Fix wording for when user tries to update via Bluetooth

- .github/workflows/build-mobile.yml
with RN update, we need to move to Java 11 and since most devs should have followed the install setup from React Native website, we should be using `zulu11`
- **Impacted projects**: `LLM` `automation` 
no demo
CI is not broken for LLM
> use same JAVA as we use locally

- libs/ui/packages/react/src/styles/global.ts
This PR removes a global CSS setting on the box-sizing prop from the design system. This setting was affecting all elements of the page whenever the design system CSS was included, making it impossible to do a gradual migration to V3.
No JIRA ticket associated to this.
N/A
> Remove global box-sizing setting for the ui lib

- libs/ledger-live-common/src/families/stellar/js-getTransactionStatus.ts
- libs/ledgerjs/packages/cryptoassets/data/stellar.js
Fix 0 amount check when sending Stellar token and update Stellar asset type to a more user-friendly name
- **Impacted projects**: `` LLD and LLM
- https://ledgerhq.atlassian.net/browse/LIVE-2756
- https://ledgerhq.atlassian.net/browse/LIVE-2944
> Fix Stellar amount required + user-friendly Stellar asset type for message

- .changeset/hot-singers-lick.md
- libs/ledger-live-common/src/env.ts
- libs/ledger-live-common/src/families/tezos/synchronisation.integration.test.ts
- libs/ledger-live-common/src/families/tezos/synchronisation.ts
currently, Ledger Live is not able to fetch more than ~1000ops on Tezos account. This increases the "safe max" limit to about 5 times more (this is a workaround until we can implement proper data pagination).
This is made as an env, so we have a technical workaround for us / users. A test was provided.
- **Linked resource(s)**: LIVE-2999 
> Improve robustness of Tezos impl with a way to set max iteration

- .changeset/yellow-sloths-fry.md
- apps/ledger-live-mobile/src/components/Nft/NftViewer.tsx
Add import that was removed during the ESBuild + Vite transition, causing a crash.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-3095` 
> [LIVE-3095] - Bugfix: missing floor price import (develop)

- .changeset/modern-years-relate.md
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/HelpDrawer.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/index.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/index.tsx
- apps/ledger-live-desktop/static/i18n/en/app.json
- libs/ui/packages/react/src/components/asorted/Text/styles.ts
- libs/ui/packages/react/src/components/layout/Drawer/index.tsx
Add a drawer displaying help to the sync onboarding page on desktop. The content is still a placeholder for now, waiting for final designs. The drawer can be opened from clicking on the help icon near the manual title.
Update some styles from React UI lib that weren't finalized.
- **Impacted projects**: `react-ui`, `ledger-live-desktop` 
- **Linked resource(s)**: [FAT-150] 
https://user-images.githubusercontent.com/23487649/181051709-18e10e4a-e18b-4284-89d1-fa5c29609434.mp4
[FAT-150]: https://ledgerhq.atlassian.net/browse/FAT-150?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …
> Add help drawer to desktop sync onboarding

- .changeset/seven-humans-sip.md
- libs/ledger-live-common/src/families/ethereum/hw-signMessage.test.ts
- libs/ledger-live-common/src/families/ethereum/hw-signMessage.ts
- libs/ledger-live-common/src/families/ethereum/types.ts
Until now, we had 2 issues with our message signatures with ethereum:
- The `v` of the signature was wrong for the EIP-712. The parity was used instead of the normal result.
- The signMessage method of the SDK was always returning a stringified message preventing from ever using the`signEIP721Message` method which was triggered by a JSON message.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-2953 
Before:
After:
> [LIVE-2953] - Bugfix: Fix ethereum signMessage for EIP-712

- .github/workflows/release-prepare-desktop.yml
- .github/workflows/release-prepare-hotfix.yml
- .github/workflows/release-prepare-mobile.yml
Prevent CI from triggering unexpected workflow after a prepare-{desktop|mobile|hotfix} workflow
No demo
Stop triggering prerelease CI after a release prepare
> chore: stop cascade trigger after doing a release preprare

- .changeset/tender-mirrors-guess.md
- libs/ui/packages/react/src/components/cta/Button/Button.stories.tsx
- libs/ui/packages/react/src/components/cta/Button/index.tsx
This PR add a missing optional "size" prop to button in React UI, like it is in Native UI
- **Impacted projects**: `react-ui`
- **Linked resource(s)**: [FAT-243]
https://user-images.githubusercontent.com/29443638/181470171-03c650c1-9ddf-4879-8b23-9a6e1654c88a.mp4
[FAT-243]: https://ledgerhq.atlassian.net/browse/FAT-243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add missing "size" property to React UI buttons

- .changeset/chilly-toys-look.md
- apps/ledger-live-mobile/src/screens/Swap/SwapEntry.js
FTX and FTX.US shows up on mobile even we haven't officially release. Currently there's a workaround in place provided by backend team based on User-Agent filter. This PR would directly hide them on the client side.
When new mobile swap version land in the next release, this change would be no longer necessary. This is a temporary solution.
- mobile swap
- [LIVE-3140](https://ledgerhq.atlassian.net/browse/LIVE-3140)
If you don't see FTX and FTX.US anymore from mobile even without backend workaround then that's the success. …
> Disable ftx ftxus temporary as a swap provider before official mobile release

- .changeset/slow-trainers-fry.md
- apps/ledger-live-mobile/src/screens/Manager/AppsList/AppInstallButton.tsx
- apps/ledger-live-mobile/src/screens/Manager/AppsList/AppProgressButton.tsx
- libs/ledger-live-common/src/apps/react.test.ts
- libs/ledger-live-common/src/apps/react.ts
Adapt the UI to the new design proposed where we remove the stop icon from queued installs, and adapt the colors to match the figma linked. Can barely call this a feature, but it's an iteration over the current design, not a fix so 🤷🏼‍♂️ I guess it is.
- **Impacted projects**: `ledger-live-mobile, ledger-live-common` 
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-2864` 
https://user-images.githubusercontent.com/4631227/180757130-a211d195-66fa-4526-bfe5-dd113dd43dab.mov
There are essentially six states for these buttons:
- Not installed:  It should offer the plus icon, to queue installation
- Queued install: Purple ring, no icon, no animation
- Installing: Active element, Purple spinning ring before we have any progress, then percentage progress no spin
- Installed: …
> feat/Live-2864 Update the UI of app buttons in manager

- apps/ledger-live-desktop/src/renderer/analytics/segment.js
- apps/ledger-live-desktop/tests/specs/analytics/segment.spec.ts
add a test that would have found the issue on [LIVE-3176](https://ledgerhq.atlassian.net/browse/LIVE-3176) [analytics integration](https://github.com/LedgerHQ/ledger-live/pull/800/commits/8cc61d9fd2d5595f88dd32a3781b06d8092016c6)
- **Impacted projects**: `no impact, it's just a test` 
- **Linked resource(s)**: `LIVE-3176` 
```
pnpm desktop test:playwright analytics
> ledger-live@0.0.0 desktop /Users/grenaudeau/dev/ledger-live
> pnpm --filter ledger-live-desktop "test:playwright" "analytics"
> ledger-live-desktop@2.45.0-hotfix.2 test:playwright /Users/grenaudeau/dev/ledger-live/apps/ledger-live-desktop
> nyc playwright test --config=tests/playwright.config.ts "analytics"
Running 1 test using 1 worker
✓  analytics/segment.spec.ts:13:1 › Segment (14s)
1 passed (15s)
```
_Please make sure you …
> LLD: add segment integration tests

- .changeset/shaggy-lizards-occur.md
- .github/workflows/test-desktop.yml
- apps/ledger-live-mobile/ios/Podfile.lock
- apps/ledger-live-mobile/package.json
- apps/ledger-live-mobile/src/screens/SelectAccount.tsx
- pnpm-lock.yaml
_LLM - send flow navigation issue fix_
- **Linked resource(s)**: [LIVE-3168] 
[LIVE-3168]: https://ledgerhq.atlassian.net/browse/LIVE-3168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BugFix/ LIVE-3168 - LLM - SendFlow fix navigation issue

- apps/ledger-live-mobile/src/screens/Account/NftCollectionsList.tsx
_Fixes navigation issue on accounts page nft gallery_
- **Linked resource(s)**: [LIVE-3156] 
[LIVE-3156]: https://ledgerhq.atlassian.net/browse/LIVE-3156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BugFix / LIVE-3156 - LLM - NFT navigation issue

- .changeset/twelve-oranges-play.md
- libs/ledger-live-common/src/hw/getOnboardingStatePolling.ts
- libs/ledger-live-common/src/onboarding/hooks/useOnboardingStatePolling.test.ts
- libs/ledger-live-common/src/onboarding/hooks/useOnboardingStatePolling.ts
Refactoring of the useOnboardingStatePolling that has no impact on current develop/production projects. This PR merged on `develop` will make our work easier on both LLD and LLM.
This refactoring brings 2 changes:
- avoid re-rendering: the hook only updates its result on a new onboardingState or new allowedError, not at every run
- update of `useOnboardingStatePolling args`: `getOnboardingStatePolling` as an optional injected dependency to the hook. It is needed for LLD to have the polling working on the **internal thread**. It is set by default to `live-common/hw/getOnboardingStatePolling` so it is not needed to pass it as an arg to use the hook on LLM.
Note: you can see a usage of the "dependency injection"/LLD on commit [371ada8c5f7c8d3cf63f9974d1756933d671e21a](https://github.com/Ledge …
> Refactoring: FAT-82 & 99 Onboarding polling hook refactor

- .changeset/soft-monkeys-lay.md
- apps/ledger-live-mobile/src/screens/ReceiveFunds/03-Confirmation.tsx
_LLM receive flow issue on copy address overflow _
- **Linked resource(s)**: [LIVE-3205] 
[LIVE-3205]: https://ledgerhq.atlassian.net/browse/LIVE-3205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-3205 - LLM - Receive flow copy button overflow issue

- .changeset/shiny-pens-flow.md
- .changeset/thin-tomatoes-poke.md
- libs/ui/packages/native/src/components/cta/Button/index.tsx
_Fixes issue on market header back button arrow being the incorrect color when tapped_
- **Linked resource(s)**: [LIVE-3203] 
[LIVE-3203]: https://ledgerhq.atlassian.net/browse/LIVE-3203?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-3203 - LLM - market backarrow button touch highlight color issue

- libs/ledger-live-common/src/families/celo/specs/createLockMutation.ts
Before attempting to lock funds, we need to ensure that the Celo account is registered.  
- **Impacted projects**: `Bot tests` 
> bugfix: check that Celo bot account is registered before locking tokens

- apps/ledger-live-desktop/src/renderer/families/celo/ActivateFlowModal/steps/StepConfirmation.jsx
- apps/ledger-live-desktop/src/renderer/families/celo/LockFlowModal/steps/StepConfirmation.jsx
- apps/ledger-live-desktop/src/renderer/families/celo/RevokeFlowModal/steps/StepConfirmation.jsx
- apps/ledger-live-desktop/src/renderer/families/celo/SimpleOperationFlowModal/steps/StepConfirmation.jsx
- apps/ledger-live-desktop/src/renderer/families/celo/UnlockFlowModal/steps/StepConfirmation.jsx
- apps/ledger-live-desktop/src/renderer/families/celo/VoteFlowModal/steps/StepConfirmation.jsx
- apps/ledger-live-desktop/src/renderer/families/celo/WithdrawFlowModal/steps/StepConfirmation.jsx
These changes will ensure that an account resync is triggered as soon as a Celo staking transaction is broadcasted, thereby ensuring that account balances are correct before a future operation/transaction can be created.
> feat: sync Celo accounts after broadcasting operation

- .changeset/mighty-queens-enjoy.md
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/TroubleshootingDrawer.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/index.tsx
- apps/ledger-live-desktop/static/i18n/en/app.json
This PR add a USB troubleshooting drawer to sync onboarding
- **Linked resource(s)**: [FAT-225] 
[FAT-225]: https://ledgerhq.atlassian.net/browse/FAT-225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add: USB troubleshooting drawer to sync onboarding

- .changeset/thick-tools-cheat.md
- apps/ledger-live-mobile/src/screens/ReceiveFunds/03-Confirmation.tsx
_ LLM Receive flow prevent issue of double modal during address verification _
- **Linked resource(s)**: [LIVE-3245] 
[LIVE-3245]: https://ledgerhq.atlassian.net/browse/LIVE-3245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BugFix: LIVE-3245 - LLM - Receive flow prevent double modal

- .changeset/empty-seals-bow.md
- .changeset/great-waves-kiss.md
- .changeset/slimy-chicken-act.md
- apps/cli/src/live-common-setup-base.ts
- apps/ledger-live-desktop/src/live-common-set-supported-currencies.js
- apps/ledger-live-mobile/src/live-common-setup.js
- libs/ledger-live-common/src/__tests__/accounts/importAccounts.ts
- libs/ledger-live-common/src/__tests__/test-helpers/setup.ts
- libs/ledger-live-common/src/apps/filtering.test.ts
- libs/ledger-live-common/src/platform/version.test.ts
Bump the platform API version to reflect the addition of `signMessage`
- **Impacted projects**: `live-mobile`, `live-desktop`, `cli` 
- **Linked resource(s)**: [`LIVE-3181`](https://ledgerhq.atlassian.net/browse/LIVE-3181) 
> fix: bump platform API version [LIVE-3181]

- .github/workflows/test-desktop.yml
Trying to fix these errors appearing  **randomly** during the windows playwright tests running on the Github hosted runners:
```
.../node_modules/tiny-secp256k1 install: D:\a\ledger-live\ledger-live\node_modules\.pnpm\nan@2.15.0\node_modules\nan\nan.h(57,10): fatal error C1083: Cannot open include file: 'uv.h': No such file or directory [D:\a\ledger-live\ledger-live\node_modules\.pnpm\tiny-secp256k1@1.1.6\node_modules\tiny-secp256k1\build\secp256k1.vcxproj]
.../blake2@4.1.1/node_modules/blake2 install: C:\Users\runneradmin\AppData\Local\node-gyp\Cache\16.16.0\include\node\node.h(63,10): fatal error C1083: Cannot open include file: 'v8.h': No such file or directory [D:\a\ledger-live\ledger-live\node_modules\.pnpm\blake2@4.1.1\node_modules\blake2\build\binding.vcxproj] …
```
> ci: attempt to fix the flaky node-gyp errors in the windows ci

- .changeset/silly-oranges-begin.md
- apps/ledger-live-desktop/src/renderer/components/WebPlatformPlayer/LiveAppSDKLogic.ts
Fixes the support of ERC20 tokens in broadcastTransaction for LLD
- **Linked resource(s)**: [`LIVE-3142`](https://ledgerhq.atlassian.net/browse/LIVE-3142) 
> fix: use getMainAccount in broadcastTransaction [LIVE-3142]

- .changeset/gentle-ties-pretend.md
- apps/ledger-live-mobile/src/components/FabAccountButtonBar.tsx
- apps/ledger-live-mobile/src/components/FabActions.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/03-Confirmation.tsx
_Fixes issue while receiving tokens from market page._
- **Linked resource(s)**: [LIVE-3199] 
[LIVE-3199]: https://ledgerhq.atlassian.net/browse/LIVE-3199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BugFix: LIVE-3199 - LLM - Receive flow fix isue on receive from market page

- apps/ledger-live-mobile/src/actions/portfolio.js
- apps/ledger-live-mobile/src/components/RootNavigator/AccountsNavigator.tsx
- apps/ledger-live-mobile/src/const/navigation.js
- apps/ledger-live-mobile/src/screens/Portfolio/Assets.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/index.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/AssetRow.tsx
- libs/ledger-live-common/src/portfolio/v2/index.ts
- libs/ledgerjs/packages/types-live/src/portfolio.ts
- pnpm-lock.yaml
Now displaying an assets list in the wallet page instead of an accounts list
- **Impacted projects**: `ledger-live-mobile` `ledger-live-common` 
- **Linked resource(s)**: [LIVE-2806] 
[LIVE-2806]: https://ledgerhq.atlassian.net/browse/LIVE-2806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Assets Centric Wallet - Assets list in the Wallet page

- .github/workflows/bot-filecoin.yml
- libs/ledger-live-common/src/families/filecoin/specs.ts
Filecoin bot spec: increase the max account from 2 to 5 in the bot runs
today the bot is generating only 2 accounts which is too limited to detect all problems ⚠️ 
this lead to a situation where we only start to detect now some problems on the Send Max when account have low balance (case that wouldn't easily be reached with a funds rotation between 2 accounts)
> Filecoin bot spec: increase the max account from 2 to 5

- .changeset/polite-phones-roll.md
- libs/ledger-live-common/src/families/filecoin/bridge/account.ts
Fixing a bug reported by the bot, involving usage of useAllAmount when fees are higher than balance on Filecoin integration
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-3333 
> LIVE-3333 fix useAllAmount flow when fees are higher than balance

- .changeset/hip-readers-enjoy.md
- libs/ui/packages/native/src/components/Text/getTextStyle.ts
- libs/ui/packages/native/src/styles/theme.ts
- libs/ui/packages/native/storybook/stories/Text/Text.stories.tsx
- libs/ui/packages/native/storybook/stories/Text/TextOverview.stories.tsx
- Adding `"h1Inter"` text variant [Figma for reference](https://www.figma.com/file/wGzwuUVo0rkCJ3sM8cpbDY/%F0%9F%93%B1-LLM-%2F-Library?node-id=1137%3A16)
- Fix a layout issue on the web native-ui storybook
- **Linked resource(s)**: [Figma](https://www.figma.com/file/wGzwuUVo0rkCJ3sM8cpbDY/%F0%9F%93%B1-LLM-%2F-Library?node-id=1137%3A16) 
> native-ui: "h1Inter" text variant (h1 with Inter font family)

- libs/ledger-live-common/src/families/elrond/specs.ts
- libs/ledger-live-common/src/families/polkadot/specs.ts
there seemed to be a shared mistake done across different coins in the bot spec that was using `pickSiblings` twice in a row in a mutation spec,
this is likely to create a flaky bug where we would check if an account have enough funds to send a tx to it but where we would actually pick **another** account to send to, making the check useless.
the fix is to share the same `sibling`
> bot: pickSiblings must be used once in spec

- .changeset/tender-shrimps-refuse.md
- apps/ledger-live-desktop/src/renderer/components/WebPlatformPlayer/TopBar.jsx
- apps/ledger-live-desktop/src/renderer/components/WebPlatformPlayer/index.tsx
- apps/ledger-live-desktop/src/renderer/components/WebPlatformPlayer/type.js
- apps/ledger-live-desktop/src/renderer/screens/card/index.jsx
Add the back and forward buttons to the web platform player, allowing to easily back and forth in a Live app and also between live apps (like with the Buy / Sell live-app that redirect to other live apps) 
Possible to display or hide navigation through a new property in the `TopBarConfig` prop.
For now, only enables the navigation on the dedicated Ledger Card entry
The navigation on the Buy / Sell screen will be enabled by this PR -> https://github.com/LedgerHQ/ledger-live/pull/923
https://user-images.githubusercontent.com/9203826/178308976-f1d276d8-cf08-4e71-a35b-a938cd5d8e8a.mov
We can go back and forward on live apps.
_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CO …
> [LIVE-2943] Feat/add back forward buttons to web platform player

- apps/ledger-live-desktop/package.json
- apps/ledger-live-desktop/tools/utils/index.js
- pnpm-lock.yaml
Turns out the upgrade was not seamless, `graceful-fs` caused trouble because `fs` was no more externalized by esbuild and the `__require` shim copied the module into a fresh object and froze the props, making `graceful-fs` unable to redefine them.
To solve it I added a small esbuild plugin to force-externalize all nodejs stdlib modules.
N/A
> chore: upgrade vitejs to v3

- libs/ledger-live-common/src/families/polkadot/specs.ts
Apparently, polkadot running on the bot never had more than 2 accounts which can be limiting the coverage. Today it's a problem because 2 accounts isn't enough to cover all the features we want to cover here (delegation,..)
> Bot: Polkadot: fixes spec to generate more than 2 accounts

- libs/ledger-live-common/src/families/cosmos/specs.ts
Too much funds is locked in delegation of cosmos even with the current settings that target 32 accounts! 
This PR reduces by half the chance to get part of the delegatable amount delegated.
we'll still need to send some ATOM to the bot meanwhile.
> Bot: Cosmos: reduce the chance to get amount delegated by half

- .changeset/breezy-hairs-bathe.md
- apps/ledger-live-mobile/src/components/RootNavigator/CustomBlockRouterNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/MainNavigator.tsx
We have a bug in production that allows users to navigate away from the manager while there are ongoing app operations by using the bottom tab buttons. We ask for confirmation if the user uses the back key or the top left button to navigate back, in this case we show a confirmation modal such as the attached screenshot. This pr introduces the same behaviour to the bottom tab buttons (except the Transfer one which remains disabled as in production).
The same way we are exposing whether the navigation should be locked or not, we now expose the callback from the manager when trying to navigate away. This callback will either be called directly if the navigation is not locked, deferred called if the navigation is locked and the user confirms on the modal, or not called at all if the user …
> bugfix/LIVE-2739 Prevent navigation with ongoing installs/uninstalls

- apps/ledger-live-mobile/src/components/TabBar/CustomTabBar.tsx
Keys were missing in list of components being rendered, so there was a warning.
> Fix LLM react warning - key prop missing in lists of components in CustomTabBar

- .changeset/stale-dancers-beam.md
- .changeset/violet-yaks-tan.md
- apps/ledger-live-mobile/src/components/FabActions.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/ExchangeLiveAppNavigator.tsx
- apps/ledger-live-mobile/src/components/WebPlatformPlayer/InfoPanel.js
- apps/ledger-live-mobile/src/components/WebPlatformPlayer/index.js
- apps/ledger-live-mobile/src/screens/Platform/App.js
- libs/ledger-live-common/src/platform/react.ts
- libs/ledgerjs/packages/types-live/README.md
- libs/ledgerjs/packages/types-live/src/feature.ts
_LLM - Buy Sell in app links should redirect to live app implementation if feature flag is activated_
Redirection is handled at the router level using a specific for this case router to route all exchange buy/sell previous routes to live app
- **Linked resource(s)**: [LIVE-2935] [LIVE-2936] 
[LIVE-2935]: https://ledgerhq.atlassian.net/browse/LIVE-2935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-2936]: https://ledgerhq.atlassian.net/browse/LIVE-2936?atlOrigin=eyJpIj …
> LIVE-2935 LIVE-2936 - LLM - redirect buy sell links to live app

- .github/workflows/test-desktop.yml
prevent CI from trying to post report comment on fork PR as the gha token doesn't 
have permissions to do so
No Demo
Green CI on external PR after test desktop
> ci: prevent reporting on fork PR as token does not have permission

- .changeset/sweet-clocks-shave.md
- .changeset/tall-chefs-hear.md
- apps/ledger-live-desktop/static/i18n/en/app.json
- apps/ledger-live-mobile/src/locales/en/common.json
Found a small typo while developing something else, decided to do a run down of our language files and found a few more.
- **Impacted projects**: `ledger-live-desktop, ledger-live-mobile` 
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-3374` 
No demo
Only wording
> Bugfix/typos Fixes bad wording in language files

- .changeset/smart-shoes-shake.md
- apps/ledger-live-mobile/src/screens/PurchaseDevice/index.tsx
This PR fixes the bug causing users to be stuck between the upsell screen and the purchase device web view
- **Linked resource(s)**: [LIVE-2881](https://ledgerhq.atlassian.net/browse/LIVE-2881)
> LIVE-2881 - Fix redirection from upsell screen

- .changeset/cold-clocks-travel.md
- apps/ledger-live-mobile/src/screens/Onboarding/steps/discoverLiveInfo.tsx
Fix the bug causing users to go back to the stories from the device selection screen
- **Linked resource(s)**: [LIVE-3025](https://ledgerhq.atlassian.net/browse/LIVE-3025)
> LIVE-3025 - Fix redirection to stories from device selection screen

- libs/ledger-live-common/src/families/polkadot/bridge.integration.test.ts
Math.random seems to be pointless in polkadot test, replaced it with fixed values
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-2894` 
> LIVE-2894 DOT: change random value to fixe one in test

- apps/ledger-live-desktop/scripts/i18next-unused.py
LIterally zero impact since we manually trigger the execution of this script. This pr merely makes it look through the right file extensions in order to attempt to identify unused literals. **Before deleting a literal** make sure to properly look for it in the code base yourself, this is not fail proof. Sometimes we build keys dynamically and the script misses.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-3384` 
No demo
Nothing to test
> support/LIVE-3384 Update the i18next-unused.py script

- .changeset/afraid-needles-own.md
- .changeset/young-ads-mate.md
- libs/ui/packages/native/src/components/tags/Tag/index.tsx
- libs/ui/packages/native/storybook/stories/Tag/Tag.stories.tsx
I'm just co-authoring the work of @nparigi-ledger here
The design of the `Tag` component has changed:
- there are now 3 types (`type` prop): `"color"` `"shade"` `"warning"`
- there are 2 sizes (`size` prop): `"small"` `"medium"`
- there is a possibility to add an icon with the `Icon` prop.
- the `active` prop is gone
- **Impacted projects**: `ledger-live-mobile` `native-ui` 
- **Linked resource(s)**: [Figma]()
https://user-images.githubusercontent.com/91890529/185353994-cd4678ce-0566-4314-b2cd-bc44b14153c2.mov
> Feat/native UI tags redesign

- .changeset/light-snakes-bathe.md
- apps/ledger-live-mobile/src/screens/DebugFeatureFlags.tsx
- apps/ledger-live-mobile/src/screens/DebugPlayground.tsx
Adding more information & easier readability of Feature Flags debugging UI:
- sorting flags alphabetically
- color code to reflect `enabled: boolean` state of a given flag
- tags for:
- local override of the flag
- override of the "enabled" value because of language (in case a flag is disabled for the current language)
(i'm not a designer so it's a bit ugly but the point is to be able to easily & quickly read essential information when debugging a feature flag).
- **Linked resource(s)**: `` nothing there
> <img src="https://user-images.githubusercontent.com/91890529/185215207-d495914e-cf09-449e-b962-c326eacddaea.png" width="300px" />
> <img src="https://user-images.githubusercontent.com/91890529/185210593-5362165b-da83-45dd-a017-5651c5353641.p …
> Feat/improve feature flag debug UI

- .changeset/big-carpets-sniff.md
- apps/ledger-live-desktop/src/renderer/Default.jsx
- apps/ledger-live-desktop/src/renderer/components/Storyly/StorylyWrapper.tsx
- apps/ledger-live-desktop/src/renderer/components/Storyly/index.tsx
- apps/ledger-live-desktop/src/renderer/components/Storyly/types.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/RecoveryContent.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/index.tsx
- apps/ledger-live-desktop/src/renderer/hooks/useStoryly.tsx
- apps/ledger-live-desktop/src/renderer/modals/LottieDebugger/index.jsx
- apps/ledger-live-desktop/src/renderer/modals/StorylyDebugger/index.tsx
- apps/ledger-live-desktop/src/renderer/modals/index.js
- apps/ledger-live-desktop/src/renderer/screens/settings/sections/Experimental/StorylyTester.tsx
- apps/ledger-live-desktop/src/renderer/screens/settings/sections/Experimental/index.jsx
- apps/ledger-live-desktop/static/i18n/en/app.json
This PR add the recovery content in the vertical timeline of the sync onboarding along with stories
It also add a debugger screen for Storyly
- **Linked resource(s)**: [FAT-155] 
[FAT-155]: https://ledgerhq.atlassian.net/browse/FAT-155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> add: recovery content sync onboarding

- apps/ledger-live-desktop/static/i18n/en/app.json
- libs/ledger-live-common/src/families/stellar/api/horizon.ts
- libs/ledgerjs/packages/errors/src/index.ts
Network error instead of (scary) fallback to 0 for Stellar balance
- **Linked resource(s)**: LIVE-2722 
[LIVE-2722]: https://ledgerhq.atlassian.net/browse/LIVE-2722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIVE-2722] Stellar sync error instead of 0 balance fallback (#909)

- .changeset/rare-guests-cheer.md
- apps/ledger-live-mobile/src/screens/Manager/AppsScreen.tsx
A bug that has been present for quite some time but we just never noticed it, the last application in the manager was hidden by the tab bar at the bottom of the UI. Adding a little padding to the FlatList makes it visible. This was made obvious when we introduced the [L] Market app since it's rendered last due to the sorting.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-3407` 
https://user-images.githubusercontent.com/4631227/185884417-556a88f5-d78d-4e45-9dea-ac5d4a5f224d.mov
Access the manager and make sure you can see the last item. You should also be able to see it through the tab bar space between the purple button and the tab bar, so it's prettier than just cutting it off.
> Bugfix/LIVE-3407 Fix rendering of last item in manager app list

- apps/ledger-live-mobile/src/live-common-setup.js
https://github.com/LedgerHQ/ledger-live/pull/846 which was tested and targeted for LLD, optimistically enabled Filecoin on LLM too.
But then this issue was found https://ledgerhq.atlassian.net/browse/LIVE-3331 which is a blocker for iOS.
This PR disables Filecoin on LLM, which is safe and enough as the blocker only happens while using Filecoin. Zero impact when Filecoin disabled.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-3364
> LIVE-3364 Disable Filecoin in LLM

- apps/ledger-live-mobile/src/analytics/segment.ts
- apps/ledger-live-mobile/src/components/FirmwareUpdate/DeviceLanguageStep.tsx
- apps/ledger-live-mobile/src/screens/Manager/Device/DeviceLanguage.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/language.tsx
This PRs adds analytics events concerning the device localization feature on LLM. All prompts and manual language changes now have tracking events associated to them
List of added events:
`Page Manager FwUpdateReinstallLanguage`
`Page Manager FwUpdateDeviceLanguagePromptDismissed`
`Page Manager FwUpdateLanguageInstalled`
`Page Manager FwUpdateDeviceLanguagePrompt`
`Page Manager ChangeLanguageEntered`
`Page Manager LanguageInstallTriggered`
`Page Manager LanguageInstalled`
`Page LiveLanguageChange DeviceLanguagePrompt`
`Page LiveLanguageChange LanguageInstalled`
`Page LiveLanguageChange LanguageInstallTriggered`
[FAT-253]
N/A
[FAT-253]: https://ledgerhq.atlassian.net/browse/FAT-253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …
> FAT-253 Analytics for device localization

- .changeset/great-donkeys-fix.md
- libs/ledgerjs/packages/cryptoassets/src/currencies.test.ts
- libs/ledgerjs/packages/cryptoassets/src/currencies.ts
- package.json
Fixes Solana, Crypto.com and Cardano **testnet coins** to be set `disableCountervalue:true` consistently with all other testnet coins to prevent them to be valued in the portfolio of Ledger Live.
Add a test to prevent this to happen again.
- **Impacted projects**: `everything` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-3444 
> Fixes testnet currencies to be $0 valued on countervalues

- .changeset/fluffy-hairs-promise.md
- apps/ledger-live-desktop/scripts/sync-families-dispatch.mjs
There was a mismatch between the file name of a Tezos custom component (`SendWarning.jsx`) and the expected file name in the component generation mechanism (`SendWarning.js`)
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-3422
> LIVE-3422 Fix file name of generated Tezos custom component

- .changeset/tender-dingos-jump.md
- libs/ledgerjs/packages/cryptoassets/src/currencies.ts
Adds explorers links to Zilliqa & Thundercore chains + updates their primary colors.
- **Impacted projects**: `Zilliqa`, `Thundercore`
> Update ZIL&TT explorer and color

- .github/workflows/build-mobile.yml
- .github/workflows/generate-screenshots.yml
- .github/workflows/regen-pods.yml
- apps/ledger-live-mobile/scripts/post.mjs
- tools/actions/composites/pr-comment/action.yml
- tools/github-bot/src/index.ts
Adds a `/regen-pods` command to regenerate podfiles for users that do not have access to mac hardware.
N/A
> ci: add /regen-pods bot command and action

- libs/ledger-live-common/src/families/celo/__snapshots__/bridge.integration.test.ts.snap
Just updating an out-of-date snapshot.  In a recent PR, I made a change to display the locked gold address as the recipient for locking, unlocking, and withdrawing operations (see [here](https://github.com/LedgerHQ/ledger-live/pull/954/files#diff-71f32da087d2549d3276a66e5e92d9d05a1eb5daf998ef3b74694eb07a2055e4R82)).  This change is what caused these changes in the snapshot.
> bugfix: update Celo integration test snapshots

- apps/ledger-live-mobile/fastlane/Fastfile
- libs/ledger-live-common/scripts/watch-ts.mjs
iOS nightly were trying to wait for builds to be validate by apple to then distribute the build into the correct test group.
In the past we've had 6h timeout (whenever a job stops because it's too long), and I experimented with a timeout on 30mn.
Unfortunately, we never had a submission happen this fast, so I just removed the distribution to the tester group (has to be done manually from the apple dev center).
Also add the version on the changelog when pushing .ipa so we have it displayed in the metadata (easier to know version + build)
No Demo
_Pull Requests must pass the CI …
> chore: add changelog + prevent CI from failing on iOS nightly

- apps/ledger-live-mobile/src/actions/settings.js
- apps/ledger-live-mobile/src/components/AccountGraphCard.tsx
- apps/ledger-live-mobile/src/components/CurrencyHeaderLayout.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/Header.tsx
- libs/ui/packages/native/src/components/Tabs/Graph/index.tsx
Fixed 2 bugs :
- removed settings icon in token asset page
- reversed graph tags order
- **Linked resource(s)**: LIVE-3418 LIVE-3439
> Fixed 2 bugs :

- libs/ledger-live-common/src/families/osmosis/specs.ts
Osmosis bot was initially setup to use only 3 accounts. Since Osmosis has staking implemented, and the unlocking period is 14 days, it makes sense to use more accounts than the unlocking period to mitigate and hopefully avoid the situation where all accounts have funds locked waiting to be unlocked.
(For the same reason, the Cosmos bot was set to use 32 accounts because Cosmos has an unlocking delay of 21 days).
- **Impacted projects**: `none` (bot config only) 
> Osmosis bot - Change the max nb of accounts from 3 to 16

- .changeset/orange-bobcats-bathe.md
- libs/ledger-live-common/src/families/filecoin/bridge/account.ts
- libs/ledger-live-common/src/families/filecoin/bridge/utils/utils.ts
Fix possible glitch on amount field between optimistic operation and the historical one.
> Add fee to value on OUT operation after signing tx

- apps/ledger-live-mobile/src/components/AssetCentricGraphCard.tsx
- apps/ledger-live-mobile/src/components/GraphCard.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/index.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/Header.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/index.tsx
Two bugs fixed :
- LLM - Individual Asset page - Crypto quantity is missing for balance 
- LLM - Active wallet page - New design should not display quick action button 
A few pixel polish feedbacks also implemented
- **Linked resource(s)**: [LIVE-3236] [LIVE-3413] 
[LIVE-3236]: https://ledgerhq.atlassian.net/browse/LIVE-3236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-3413]: https://ledgerhq.atlassian.net/browse/LIVE-3413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …
> Asset centric wallet - bugfix/LIVE-3436-added-crypto-quantity-in-asset-page

- .changeset/quiet-cougars-wink.md
- libs/ledger-live-common/src/families/filecoin/bridge/utils/types.ts
- libs/ledger-live-common/src/families/filecoin/bridge/utils/utils.ts
Apply a fix to display fees properly on historical transactions
> Display fees on historical transactions properly

- .changeset/swift-beds-laugh.md
- apps/ledger-live-desktop/src/renderer/analytics/segment.js
- apps/ledger-live-desktop/src/renderer/index.html
- apps/ledger-live-desktop/tests/specs/analytics/segment.spec.ts
In production, `window.analytics` can randomly be undefined at load time. This is very likely due to the order of the scripts.
This PR do a bunch of changes:
- it put scripts back in order, basically we must set the `<script>` that init the analytics object in window first.
- **it fixes the HTML!**, the usage of `<script src=".." />` is bad, it should be `<script src=".."></script>` because otherwise, the next HTML that gets after the first code would be "EATEN"! <img width="548" alt="Screenshot 2022-08-25 at 14 05 18" src="https://user-images.githubusercontent.com/211411/186660818-cbfc83f3-d2fa-4e91-8a7a-b76461aff7c9.png"> (NB: there is a possibility that it was the actual bug at stake, but for some reason i don't reproduce myself)
- it uses `defer` which seems more relevant than "async" …
> Load the app module AFTER the analytics script init

- .changeset/rotten-seals-mix.md
- apps/ledger-live-mobile/src/react-native-hw-transport-ble/makeMock.ts
- apps/ledger-live-mobile/src/screens/PairDevices/Scanning.tsx
- libs/ledgerjs/packages/react-native-hw-transport-ble/src/BleTransport.ts
This is a fix for an error that was found in Sentry.
While scanning devices, if there was a device for which the scan failed, we emitted is as a `null` device. However this broke on React end since we were trying to access infos from this null value as if it were an object.
See associated JIRA task for more info on the error.
The PR prevents the emission of an event in this case, fixing the issue directly in the scanning logic. This could have been prevented if we had a stricter typing, so I've also added some typing to the logic.
- **Impacted projects**: `ledgerjs/react-native-hw-transport-ble`, `ledger-live-mobile`
- **Linked resource(s)**: [LIVE-2641]
- [N/A] **Test coverage** -- this was more a question of proper typing rather than tests
N/A
[LIVE-2641]: …
> LIVE-2641 Prevent emitting an event when device descriptor is null

- .github/workflows/test.yml
- apps/cli/src/commands/botTransfer.ts
- quick fix that solves the CLI compilation issue due to the drop of getImplicitDeviceAction.
- also make the CI run the build:cli
**Note for future:**
in future we will also make the "botTransfer" more **explicit** by defining on each spec a "transferMutation" that would define how to "cash out" from the bot to another bot, meaning that it would also prioritize the "unfreeze" of assets first before moving out, so it could be pretty handy to tackle next time we need that.
- **Impacted projects**: `cli` 
> Fixes botTransfer + make CI test cli compilation

- .changeset/quiet-singers-beg.md
- .changeset/small-donkeys-hope.md
- .changeset/tough-geckos-reflect.md
- apps/ledger-live-desktop/src/renderer/families/cosmos/RedelegationFlowModal/Body.jsx
- apps/ledger-live-desktop/src/renderer/families/cosmos/utils.jsx
- apps/ledger-live-desktop/src/renderer/screens/account/AccountBanner.jsx
- apps/ledger-live-desktop/src/renderer/screens/account/index.jsx
- apps/ledger-live-desktop/static/i18n/en/app.json
- apps/ledger-live-mobile/src/components/AccountBanner.tsx
- apps/ledger-live-mobile/src/const/navigation.ts
- apps/ledger-live-mobile/src/families/cosmos/Delegations/index.tsx
- apps/ledger-live-mobile/src/families/cosmos/RedelegationFlow/index.tsx
- apps/ledger-live-mobile/src/families/cosmos/utils.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- libs/ledger-live-common/src/families/cosmos/banner.test.ts
- libs/ledger-live-common/src/families/cosmos/banner.ts
Add cosmos account banner
3 modes:
- Delegate
- Redelegate
- Hidden
- Mobile and Desktop
- JIRA:  https://ledgerhq.atlassian.net/browse/LIVE-3127
Scope: 
- Basic util in common
- Implementation in Desktop
- Implementation in Mobile
> feat(LIVE-3127): Add cosmos account banner 

- .changeset/three-panthers-peel.md
- libs/ledger-live-common/src/api/explorerConfig/index.ts
When Ethereum Goerli testnet support was added to Live, prod explorer env was not available yet.
Backend team confirms Goerli is now available on prod env, so this PR makes the switch.
> Switch Ethereum Goerli explorer env from staging to prod

- apps/ledger-live-mobile/src/components/AccountGraphCard.tsx
- apps/ledger-live-mobile/src/components/FabActions/index.tsx
- apps/ledger-live-mobile/src/components/FabActions/modals/ZeroBalanceDisabledModalContent.tsx
- apps/ledger-live-mobile/src/reducers/accounts.ts
- apps/ledger-live-mobile/src/screens/ReceiveFunds/03-Confirmation.tsx
Fix receive for token in account page for QR code address click or DisableAction Modal -> Receive, because it was missing parent account id
> Bugfix/LIVE-3556 - LLM  - Asset centric wallet - Fix token receive not working like coin receive

- apps/ledger-live-mobile/src/components/TabBar/TransferButton.tsx
- apps/ledger-live-mobile/src/components/TabBar/TransferDrawer.tsx
- Fix conditions for disabled state in TransferDrawer for some buttons
- Add style to disable visually TransferButton
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/463?modal=detail&selectedIssue=LIVE-3602
> Feat/LIVE-3602 - LLM - Asset centric wallet - Transfer drawer > Disable transfer buttons send and swap 

- apps/ledger-live-mobile/src/components/TabBar/TransferButton.tsx
Small change of color for the TransferDrawer so the disabled text is a little more visible in light theme
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-3615
> Bugfix - LLM - Asset centric wallet - Small change of color for the TransferDrawer text

- .changeset/clever-coins-battle.md
- apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.jsx
This PR fix the onboarding entry point from My Ledger
https://user-images.githubusercontent.com/29443638/188634375-25cfcf07-18f4-4cc4-b627-909c3686e255.mp4
> fix: onboarding launch from My Ledger

- .changeset/big-windows-mix.md
- apps/ledger-live-mobile/docs/linking.md
- apps/ledger-live-mobile/src/components/RootNavigator/ExchangeLiveAppNavigator.tsx
- apps/ledger-live-mobile/src/index.tsx
_Update LLM Deeplnks for Buy / Sell Live app flows to take in account currency as a param_
- **Linked resource(s)**: [LIVE-3509] 
[LIVE-3509]: https://ledgerhq.atlassian.net/browse/LIVE-3509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feat/ LIVE-3509 - LLM Deeplinks updated for buy/sell live apps flow

- .changeset/twelve-planets-whisper.md
- apps/ledger-live-mobile/src/actions/walletconnect.ts
- apps/ledger-live-mobile/src/components/HeaderRightClose.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/WalletConnectLiveAppNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/WalletConnectNavigator.tsx
- apps/ledger-live-mobile/src/components/WebPlatformPlayer/index.tsx
- apps/ledger-live-mobile/src/const/navigation.ts
- apps/ledger-live-mobile/src/index.tsx
- apps/ledger-live-mobile/src/reducers/index.ts
- apps/ledger-live-mobile/src/reducers/walletconnect.ts
- apps/ledger-live-mobile/src/rootnavigation.ts
- apps/ledger-live-mobile/src/screens/Account/hooks/useActions.tsx
- apps/ledger-live-mobile/src/screens/WalletConnect/DeeplinkingSelectAccount.tsx
- apps/ledger-live-mobile/src/screens/WalletConnect/Provider.tsx
- apps/ledger-live-mobile/src/screens/WalletConnect/Scan.tsx
- libs/ledgerjs/packages/types-live/README.md
- libs/ledgerjs/packages/types-live/src/feature.ts
_Implement routing logic to either use the native of live app implementation of wallet connect in the live using a feature flag._
- **Linked resource(s)**: [LIVE-3254] 
[LIVE-3254]: https://ledgerhq.atlassian.net/browse/LIVE-3254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-3254 - LLM - Wallet connect as live app feature flag

- .changeset/purple-roses-greet.md
- apps/ledger-live-mobile/src/components/Animation.tsx
- apps/ledger-live-mobile/src/helpers/getDeviceAnimation.ts
_Fixes undefined lottie animations for nanoS nanoSP and blue_
- **Linked resource(s)**: [LIVE-3652] 
[LIVE-3652]: https://ledgerhq.atlassian.net/browse/LIVE-3652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-3652 - LLM - fix undefined lottie animations

- .changeset/small-eggs-sip.md
- libs/ledger-live-common/src/env.ts
- libs/ledger-live-common/src/exchange/swap/getExchangeRates.ts
- libs/ledger-live-common/src/exchange/swap/getProviders.test.ts
- libs/ledger-live-common/src/exchange/swap/getProviders.ts
- libs/ledger-live-common/src/exchange/swap/index.test.ts
- libs/ledger-live-common/src/exchange/swap/index.ts
- libs/ledger-live-common/src/exchange/swap/mock.ts
- libs/ledger-live-common/src/exchange/swap/types.ts
This switches to swap backend API v4, which drastically reduces size of `/providers` endpoint response.
Note: this PR only converts response back to v3 flattened format of pairs, deeper changes are required to get full benefit of it:
- for swap pane, the response can be intersected with list of accounts instead of full decoding
- for swap button in market/portfolio pages, only a few lookups are sufficient instead of full decoding
- **Impacted projects**: swap, market page, portfolio, account pages
- https://ledgerhq.atlassian.net/browse/LIVE-3570
- https://ledgerhq.atlassian.net/browse/BACK-3654
- https://ledgerhq.atlassian.net/wiki/spaces/BE/pages/3753050176
[live-api-v4.webm](https://user-images.githubusercontent.com/102984500/187739589-0fcd4f9a-2468-4e45-bd48-1 …
> LIVE-3570: Switch to swap backend API v4

- .changeset/smooth-seas-poke.md
- libs/ledger-live-common/src/bot/specs.ts
- libs/ledger-live-common/src/families/algorand/speculos-deviceActions.ts
- libs/ledger-live-common/src/families/bitcoin/speculos-deviceActions.ts
- libs/ledger-live-common/src/families/cardano/speculos-deviceActions.ts
- libs/ledger-live-common/src/families/celo/speculos-deviceActions.ts
- libs/ledger-live-common/src/families/elrond/speculos-deviceActions.ts
- libs/ledger-live-common/src/families/ethereum/speculos-deviceActions.ts
- libs/ledger-live-common/src/families/evm/specs.ts
- libs/ledger-live-common/src/families/evm/speculos-deviceActions.ts
- libs/ledger-live-common/src/families/filecoin/speculos-deviceActions.ts
- libs/ledger-live-common/src/families/polkadot/speculos-deviceActions.ts
- libs/ledger-live-common/src/families/ripple/speculos-deviceActions.ts
- libs/ledger-live-common/src/families/solana/speculos-deviceActions.ts
- libs/ledger-live-common/src/families/stellar/speculos-deviceActions.ts
- libs/ledger-live-common/src/families/tezos/speculos-deviceActions.ts
- libs/ledger-live-common/src/families/tron/speculos-deviceActions.ts
- libs/ledgerjs/packages/cryptoassets/src/currencies.ts
we have way too much boilerplate to implement the speculos-deviceActions using formatCurrencyUnit.
You can see the benefit of this simplification:
This also fixes the bot "evm" on Ethereum family by using what are the current "deviceTicker" to use for the latest ETH nano app.
> provide a formatDeviceAmount helper for the bot

- libs/ledger-live-common/src/families/bitcoin/specs.ts
During BTCJS development, we used to want to run the testnet spec twice in a row. putting it back to the normal "single" mode will be a performance boost of the general bot run.
> Bot: bitcoin testnet to run just once

- .changeset/shy-feet-appear.md
- libs/ledger-live-common/src/hw/extractOnboardingState.test.ts
- libs/ledger-live-common/src/hw/extractOnboardingState.ts
Recently, new onboarding states were added to the firmware. This PR updates the definition of the states and the associated tests for those. It was tested using a 2.1.0-lo5 firmware on a Nano X using the CLI, since it's not yet used in Live itself.
- **Linked resource(s)**: [FAT-356]
Technically, these are breaking changes on the LLC lib. But since this is not yet used anywhere in LIVE. It doesn't break anything.
N/A
[FAT-356]: https://ledgerhq.atlassian.net/browse/FAT-356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FAT-356 Update onboarding states according to the new firmware definitions

- .changeset/yellow-crabs-act.md
- apps/ledger-live-desktop/src/renderer/components/ConnectTroubleshooting.jsx
This PR fix the hover effect of the troubleshoot USB button
- **Linked resource(s)**: [FAT-235] 
https://user-images.githubusercontent.com/29443638/189906330-5bd86960-ada4-4c55-ae7e-1642ab62b9b7.mp4
[FAT-235]: https://ledgerhq.atlassian.net/browse/FAT-235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix troubleshoot button hover effect

- .changeset/plenty-oranges-flash.md
- apps/ledger-live-mobile/src/components/TabBar/TransferButton.tsx
Wrap text when is too long in TabBar Transfer
- **Linked resource(s)**: [LIVE-3585] 
_Before_
_After_
Main app button
[LIVE-385]: https://ledgerhq.atlassian.net/browse/LIVE-385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-3585]: https://ledgerhq.atlassian.net/browse/LIVE-3585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bugfix(TabBar): Wrap text when is too long in TabBar Transfer

- .changeset/cold-books-laugh.md
- .changeset/sweet-points-tease.md
- apps/ledger-live-desktop/src/live-common-set-supported-currencies.js
- apps/ledger-live-desktop/src/live-common-set-supported-currencies.test.js
- libs/ledger-live-common/src/currencies/support.ts
Regression introduced on LLD 2.47 : Osmosis appears twice in the list when trying to add accounts.
Cause: was declared twice in the list of supported currencies. Probably introduced by a bad merge.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-3684
> LIVE-3684 (LLD) Remove duplicate Osmosis in the list during add accounts flow

- apps/ledger-live-mobile/ios/Podfile.lock
- apps/ledger-live-mobile/package.json
- apps/ledger-live-mobile/src/screens/Onboarding/steps/language.tsx
- pnpm-lock.yaml
Updated restarting logic when switching from RTL to LTR and the other way.
- **Linked resource(s)**: LIVE-3369
- 
https://user-images.githubusercontent.com/39890664/190107468-067160ec-6fba-47c7-95da-e7f0f9e28036.mov
> Feat/live 3369/restart when switching lang

- .changeset/plenty-guests-beg.md
- apps/ledger-live-mobile/src/components/CustomImage/BottomButtonsContainer.tsx
- apps/ledger-live-mobile/src/components/CustomImage/ContrastChoice.tsx
- apps/ledger-live-mobile/src/components/FirebaseFeatureFlags.tsx
- apps/ledger-live-mobile/src/components/HeaderTitle.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/CustomImageNavigator.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/CustomImage/Step1Crop.tsx
- apps/ledger-live-mobile/src/screens/CustomImage/Step2Preview.tsx
- apps/ledger-live-mobile/src/screens/CustomImage/Step3Transfer.tsx
- apps/ledger-live-mobile/src/screens/CustomImage/shared.ts
- apps/ledger-live-mobile/src/screens/DebugFeatureFlags.tsx
- Custom image tool:
- Changing the font of navigation headers to Inter (also applied to the entire app).
- Removing the close button in the custom image flow.
- Removing the “bottom drawer”-like layout appearance at the bottom of the Crop & Contrast steps.
- Feature flag debug menu improvements
- Added search input
- Added "add missing flag" input
- More compact UI (the list of FF is becoming quite long)
- Enable/disable toggle
- Fix overriding logic for resetting to actual remote value
- **Linked resource(s)**: [FAT-383]   …
> FAT-383 Custom image pixel polish + feature flag debug menu improvements

- .changeset/healthy-toes-knock.md
- apps/ledger-live-desktop/src/renderer/drawers/OperationDetails/index.jsx
We move the divider at the end to avoid the effect of an empty divider because of the operation details
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-1683` 
> LIVE-1683-move separator

- .changeset/wild-otters-live.md
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/AddAccounts/AddAccountsModal.tsx
- apps/ledger-live-mobile/src/screens/AddAccounts/AddAccountsModalCard.tsx
Update text and ui for Add Account modal
- **Linked resource(s)**: [LIVE-3714] 
_Before_
_After_
Go to Accounts > Add Account
[LIVE-3714]: https://ledgerhq.atlassian.net/browse/LIVE-3714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> support(UI): Update text and ui for Add Account modal

- .changeset/loud-ads-explode.md
- apps/ledger-live-desktop/src/renderer/Default.jsx
A switch for the walletconnect screen was removed in the PR https://github.com/LedgerHQ/ledger-live/pull/593
Behaves in the same way as before: https://github.com/LedgerHQ/ledger-live/pull/593/files#diff-ba34fac6b14664d7b6de0efeec9da7d00f2294fb582e321af7d362db84453bf2R198
Before:
After:
> fix: sidebar & topbar over walletconnect

- .changeset/few-toys-cough.md
- apps/ledger-live-desktop/src/renderer/modals/AddAccounts/steps/StepChooseCurrency.jsx
Add a check of the connectivity when adding an account
> LIVE-3184: Add network check on add account

- .changeset/selfish-schools-end.md
- apps/ledger-live-mobile/src/components/CustomImage/ContrastChoice.tsx
- apps/ledger-live-mobile/src/components/CustomImage/CustomImageBottomModal.tsx
- apps/ledger-live-mobile/src/components/CustomImage/imageUtils.ts
- apps/ledger-live-mobile/src/components/CustomImage/injectedCode/imageProcessing.ts
- apps/ledger-live-mobile/src/components/CustomImage/injectedCode/resultDataTesting.ts
- apps/ledger-live-mobile/src/screens/CustomImage/Step1Crop.tsx
- apps/ledger-live-mobile/src/screens/CustomImage/Step2Preview.tsx
- apps/ledger-live-mobile/src/screens/CustomImage/Step3Transfer.tsx
- apps/ledger-live-mobile/src/screens/CustomImage/types.ts
Fixes for the custom image tool: 
- Back button behaviour in the first step: If the image is coming from the phone gallery, pressing the back button should reopen the gallery
- Prevent choosing another contrast if current contrast is loading
- Implement dithering → quality improvement of image, avoiding color banding
- Implement new ordering of pixels 
- in raw data result
- in raw data result verifier (the last screen that reconstructs the image from the raw data)
- **Linked resource(s)**: [FAT-395] [FAT-406]  …
> LLM custom image fixes

- .changeset/late-spies-knock.md
- apps/ledger-live-mobile/src/experimental.ts
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Settings/Developer/index.tsx
Added translation for Settings and experimental features
- **Linked resource(s)**: [LIVE-3586] 
Go to Settings > Experimental features
[LIVE-3586]: https://ledgerhq.atlassian.net/browse/LIVE-3586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bugfix(Experimentalfeatures): Added translation for Settings and experimental features

- apps/ledger-live-desktop/src/sentry/install.js
- apps/ledger-live-mobile/index.js
Fixes LIVE-3506: ignore 'Transaction simulation failed'
- **Impacted projects**: `mobile, desktop` 
- **Linked resource(s)**: `LIVE-3506` 
> Fixes LIVE-3506: ignore 'Transaction simulation failed'

- .changeset/dirty-dragons-share.md
- apps/ledger-live-desktop/static/i18n/en/app.json
- apps/ledger-live-mobile/src/locales/en/common.json
Error message when trying to send a NFT from LNS is wrong
- **Impacted projects**: `live-desktop` `live-mobile` 
- **Linked resource(s)**: [LIVE-3845] 
[LIVE-3845]: https://ledgerhq.atlassian.net/browse/LIVE-3845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> support(Disclaimer):Error message when trying to send a NFT from LNS is wrong

- .changeset/twenty-ants-serve.md
- apps/ledger-live-mobile/src/components/RootNavigator/NftNavigator.tsx
…
Close individual NFT drawer should back to Gallery/Collection screen
- **Linked resource(s)**: [LIVE-3375] 
https://user-images.githubusercontent.com/112866305/191505643-2351bc43-8bac-4030-a97b-305f45f27d8a.mp4
- Added ETH account with NFT
- Navigate to account page
- Access to NFT gallery or collection page
- Click one NFT to access an individual NFT page 
- 
[LIVE-3375]: https://ledgerhq.atlassian.net/browse/LIVE-3375?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bugfix(BackButton): Close individual NFT drawer should back to Gallery/Collection screen

- .changeset/perfect-weeks-burn.md
- apps/ledger-live-mobile/package.json
- pnpm-lock.yaml
Bumps a library to fix some reported vulnerabilities by dependabot
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-3804` 
In theory no breaking changes should happen, anything breaking should be caught in the non regression phase.
> feat/LIVE-3804 Bump hermes-engine dependency to 0.11.0

- .github/workflows/test-mobile.yml
- apps/ledger-live-mobile/e2e/config.json
- apps/ledger-live-mobile/e2e/helpers.js
- apps/ledger-live-mobile/e2e/setup.js
Tweaking some timeouts
Force exit jest
_This PR is to enable Android Detox tests on the CI_
> [B2CQA-752] Enabling Android Detox CI flow

- .changeset/happy-garlics-kick.md
- apps/ledger-live-mobile/docs/linking.md
- apps/ledger-live-mobile/src/components/RootNavigator/AddAccountsNavigator.tsx
- apps/ledger-live-mobile/src/index.tsx
- apps/ledger-live-mobile/src/navigation/useDeepLinking.ts
- apps/ledger-live-mobile/src/screens/Accounts/AccountRow.tsx
- apps/ledger-live-mobile/src/screens/Accounts/index.tsx
- apps/ledger-live-mobile/src/screens/AddAccounts/01-SelectCrypto.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/01-SelectCrypto.tsx
Add Deeplink for Add Account and Accounts page
- **Linked resource(s)**: [LIVE-3237] [LIVE-3238] 
Start LLM and use `adb shell am start -W -a android.intent.action.VIEW -d "ledgerlive://add-account?currency=ethereum" com.ledger.live.debug` to trigger Deeplink for add-account. Ethereum should be filled by default
[LIVE-3237]: https://ledgerhq.atlassian.net/browse/LIVE-3237?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-3238]: …
> support(Deeplink): Add Deeplink for Add Account and Accounts page

- .changeset/early-impalas-peel.md
- apps/ledger-live-desktop/src/renderer/components/ToastOverlay/Toast.jsx
_Failsafes an issue reported by sentry related to undefined toast callback causing crashes_
- **Linked resource(s)**: [LIVE-3905] 
[LIVE-3905]: https://ledgerhq.atlassian.net/browse/LIVE-3905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-3905 - LLD - fix toast issue when no click callback given

- libs/ledger-live-common/src/families/solana/specs.ts
solana devs will have to add the relevant test but i was too optimistic here thinking it would work like other coins. this should restore solana to pass the bot. a "hint" will appear that you need to define a destinationTest but it's better to have a ✅  test as before until this is added properly. https://github.com/LedgerHQ/ledger-live/commit/b75896f14c694a81c2c1d17c5ce8ef9ce245ce4a#commitcomment-85144438
> Bot: Solana: remove test for "destination" that don't work for MAX

- apps/ledger-live-mobile/src/families/cosmos/AccountBalanceSummaryFooter.tsx
- apps/ledger-live-mobile/src/families/tron/AccountBalanceSummaryFooter.tsx
Fix glitch with cosmos and tron account balance summary banner scrollview
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-3867
> Bugfix / LL-3887 - Fix glitch with cosmos and tron account balance summary banner scrollview

- .changeset/six-moons-change.md
- apps/ledger-live-desktop/package.json
- apps/ledger-live-desktop/src/sentry/install.js
- apps/ledger-live-desktop/src/support/os.test.ts
- apps/ledger-live-desktop/src/support/os.ts
- pnpm-lock.yaml
introduce getOperatingSystemSupportStatus() to ignore sentry reporting on old unsupported OSs
as we can get polluted by unsupported os version, we want clients to NOT send error report if their os isn't supported anymore. Typically we don’t want to see Win 7 related bugs in Sentry. That way we save bandwidth and prevent situation of incident that aren't incident (LIVE-3957 is possibly one of these case)
NB: this PR **do not** impact the UI. but a future goal is to also introduce this function for the UI to possibly tell the user they use too old OS version. For now, we really just need to stop reporting to sentry.
- **Impacted projects**: LLD 
- **Linked resource(s)**: LIVE-3958 
_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/C …
> introduce getOperatingSystemSupportStatus() to ignore sentry reporting on old unsupported OSs

- libs/ledger-live-common/src/families/celo/specs/createSendMutation.ts
- libs/ledger-live-common/src/families/filecoin/specs.ts
this reverts my recent addition of "destinationTest" on the bot for Celo and Filecoin which don't seem to properly validate these.
we want the bot tests to pass instead of having too much unstable tests until we can add them back (they will create more "warnings" on hints for developers to add tests there)
> Bot: remove expectation of validating "destination" tests for celo & fil

- libs/ledger-live-common/src/account/support.ts
add the ability to see precisely the currencyName in the technical error message (not seen to the user as it gets translated)
- **Impacted projects**: `LLD/LLM` but very low impact 
> Improve technical error when 'CurrencyNotSupported' occurs

- tools/github-bot/src/index.ts
Request was made to keep the same Smartling configuration (watch PRs from develop and create jobs asap), but close the automatic PRs.
Smartling PRs triggered when manually exporting translations should still work.
N/A
> ci: auto close smartling prs

- .changeset/cyan-dingos-cheat.md
- apps/ledger-live-desktop/package.json
- apps/ledger-live-desktop/src/internal/commands/index.js
- apps/ledger-live-desktop/src/internal/commands/listenDevices.js
- apps/ledger-live-desktop/src/internal/commands/listenToHidDevices.ts
- apps/ledger-live-desktop/src/renderer/Default.jsx
- apps/ledger-live-desktop/src/renderer/hooks/useListenToHidDevices.ts
- libs/ledgerjs/packages/hw-transport-node-hid-singleton/README.md
- libs/ledgerjs/packages/hw-transport-node-hid-singleton/src/TransportNodeHid.ts
- pnpm-lock.yaml
Refactor that:
- make the `listenDevices` definition command into TS, and rename into `listenToHidDevices`
- transform the `ListenDevices` component (that was mainly a `useEffect` returning null) into a hook `useListenToHidDevices`
- add the `types-devices` lib into LLD
- **Impacted projects**:  `ledger-live-desktop` and `@ledgerhq/hw-transport-node-hid-singleton`
Demo showing that a device is still usb-detected:
https://user-images.githubusercontent.com/15096913/193070245-0addd198-c601-4b28-9a63-1d9e041437c9.mp4
> Support: refactor listen-to-hid-devices to TS and hook

- libs/ledger-live-common/src/families/crypto_org/specs.ts
bot: Disable crypto_org_croeseid spec, we will use the mainnet
also renamed the spec name to not be parsed as an url by slack report
> bot: Disable crypto_org_croeseid spec

- libs/ledger-live-common/src/bot/engine.ts
- libs/ledger-live-common/src/bot/types.ts
- libs/ledger-live-common/src/families/solana/specs.ts
- libs/ledger-live-common/src/rxjs/operators/retryWithDelay.ts
- libs/ledger-live-common/src/rxjs/operators/throwIf.ts
introduces a retries on scanAccounts to prevent tmp fails. Sometimes we have dumb temporary `Can't parse '<'`, this should limit this problem. 
- **Linked resource(s)**: fixes https://github.com/LedgerHQ/ledger-live-issues/issues/36 
> bot: introduces a retries on scanAccounts to prevent tmp fails

- apps/cli/src/commands-index.ts
- apps/cli/src/commands/confirmOp.ts
- libs/ledger-live-common/src/families/cardano/specs.ts
- libs/ledger-live-common/src/families/celo/specs.ts
- libs/ledger-live-common/src/families/ethereum/specs.ts
- libs/ledger-live-common/src/families/filecoin/specs.ts
- libs/ledger-live-common/src/families/osmosis/specs.ts
introduce a confirmOp on the cli, so we can easily do this:
```
pnpm run:cli confirmOp --id js:2:cardano:da85e83cab046f8a50aa6fcd67bd7dffee0e1fd15ad3345a78838239d4d3fc2291f70ea636c86770da1ab8bf2136d60d3f9e49292a5f32d1f460bd4c7e251372:cardano-75ffed02f79a815baf6164cb0175971978ce1f333c586c6df9e2ba762c1174da-OUT
```
when we see the bot message
```
⚠️ TEST waiting operation id to appear after broadcast
Error: could not find optimisticOperation js:2:cardano:da85e83cab046f8a50aa6fcd67bd7dffee0e1fd15ad3345a78838239d4d3fc2291f70ea636c86770da1ab8bf2136d60d3f9e49292a5f32d1f460bd4c7e251372:cardano-75ffed02f79a815baf6164cb0175971978ce1f333c586c6df9e2ba762c1174da-OUT
```
to confirm that it's just eventually landing but it was too slow for the bot to reach it.
in that case, we increase the timeout, …
> introduce cli confirmOp + Increase timeouts for bot

- .github/workflows/backup/version-or-release.yml
- .github/workflows/build-desktop.yml
- .github/workflows/build-mobile.yml
- .github/workflows/generate-screenshots.yml
- .github/workflows/regen-pods.yml
- .github/workflows/test-desktop.yml
- .github/workflows/test-mobile.yml
- .github/workflows/test.yml
The current policy when running actions on a PR/branch is to cancel the previous similar job (if running) to preserve our runners from being overloaded.
The consequence of this on `develop` is that merge commits jobs sometimes do not have the time to complete before another PR is merged. And the outcome is that it is way more complicated to locate merge commits breaking the CI than it should be.
N/A
> ci: attempt to prevent job cancellation on develop

- .changeset/quick-moles-fix.md
- apps/ledger-live-mobile/src/components/RequiresBLE/BluetoothDisabled.tsx
Layout issue with the error message if Bluetooth is disabled when user pairs device
- **Linked resource(s)**: [LIVE-2697] [LIVE-3562] 
_Before_
_After_
Disable bluetooth > Go to Pair device flow 
[LIVE-2697]: https://ledgerhq.atlassian.net/browse/LIVE-2697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-3562]: https://ledgerhq.atlassian.net/browse/LIVE-3562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bugfix(Layout): Layout issue with the error message if Bluetooth is disabled when user pairs device

- .changeset/rich-lemons-prove.md
- apps/ledger-live-mobile/src/context/AuthPass/FailBiometrics.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Settings/General/BiometricsRow.tsx
The text Fingerprint should be translated
FaceID / TouchID/ Fringerprint are handled. If new ones come, there is a Fallback (it will be written in English) but no translation will be provided without updating translation file. 
- **Linked resource(s)**: [LIVE-3869] 
Go General > Settings (have Fringerprint or FaceID activated on your device)
[LIVE-3869]: https://ledgerhq.atlassian.net/browse/LIVE-3869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bugfix(i18n): The text Fingerprint should be translated

- apps/ledger-live-mobile/src/components/RootNavigator/PortfolioNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/WalletTabNavigator.tsx
- apps/ledger-live-mobile/src/const/navigation.ts
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Nft/WalletNftGallery/index.tsx
New homepage tab navigator with two screens :
Cryptos (the old portfolio/wallet page)
NFT (new page for the nft gallery)
+ new (empty) wallet nft gallery screen
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-3666
https://user-images.githubusercontent.com/89014981/193852464-b568086f-ec13-4b66-a7c8-9c356a664e9c.mp4
> Feat / LIVE-3666 - New homepage tab navigator

- .changeset/modern-buckets-enjoy.md
- apps/ledger-live-mobile/ios/Podfile.lock
- apps/ledger-live-mobile/package.json
- pnpm-lock.yaml
- turbo.json
During testing of another feature we found out that saving logs was no longer working on Android > 12. Since this library is used to also export operations it's likely it's impacting that feature too. That issue was addressed by the developers of the library some versions ago and simply bumping it solves it. 
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-3913`
> bugfix/LIVE-3913 Updated share library (fixes export logs and ops)

- .changeset/dry-kiwis-give.md
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/drawers/SyncDesktopInformation.tsx
UI issue on Sync modal
- **Linked resource(s)**: [LIVE-3650] 
_Before_
_After_
https://user-images.githubusercontent.com/112866305/191022822-3abe93e3-3c47-4c07-94ef-35568429a61c.mp4
[LIVE-3650]: https://ledgerhq.atlassian.net/browse/LIVE-3650?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bugfix(UI): UI issue on Sync modal

- .changeset/real-keys-pull.md
- apps/ledger-live-mobile/src/screens/Onboarding/steps/newDeviceInfo.tsx
Onboarding quizz pixel polish LLM
- **Linked resource(s)**: [LIVE-2091] 
https://user-images.githubusercontent.com/112866305/192738895-d1359ef1-3334-46c5-8976-95b1f2c8e3ec.mp4
OnBoarding > Configure Nano
[LIVE-2091]: https://ledgerhq.atlassian.net/browse/LIVE-2091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 💄 support(UI): Onboarding quizz pixel polish LLM

- apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx
- apps/ledger-live-mobile/src/screens/Nft/NftGallery/ReceiveNFTsModal.hook.ts
- apps/ledger-live-mobile/src/screens/Portfolio/PortfolioEmptyState.tsx
nft gallery with reborn : Add paywall to receive flow
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-3808
https://user-images.githubusercontent.com/89014981/194899313-b77f640a-1f5e-4f7b-91ef-d4bd6909b5c6.mp4
> Feat/LIVE-3808 - nft gallery with reborn

- .github/workflow-templates/bot-coin-family.yml
- .github/workflows/bot-bitcoin-mooncake.yml
- .github/workflows/bot-cardano-silicium.yml
- .github/workflows/bot-celo-silicium.yml
- .github/workflows/bot-coin-osmosis.yml
- .github/workflows/bot-cosmos-phosphore.yml
- .github/workflows/bot-filecoin-mooncake.yml
- .github/workflows/bot-hedera-mooncake.yml
- .github/workflows/bot-mere-denis-nonreg.yml
- .github/workflows/bot-phosphore-nonreg.yml
- .github/workflows/bot-phosphore.yml
- .github/workflows/bot-staging-explorer-btc.yml
- .github/workflows/bot-staging-explorer-eth.yml
- .github/workflows/bot-stellar-silicium.yml
- libs/ledger-live-common/src/bot/index.ts
- libs/ledger-live-common/src/bot/types.ts
- tools/actions/composites/bot/action.yml
one missing feature that #1494 will need to filter only production bot runs.
i also explicitly splitted "bot-phosphore" into two diff actions, we need one to be production, running on develop (now running on each commit with cancel mecanism + every 6 hours) VS the one on bot-phosphore branches push.
> Bot: add 'environment' in report.json to filter by 'production'

- .changeset/silver-bobcats-deliver.md
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Onboarding/steps/importAccounts.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/scenes/BaseStepperView.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/scenes/SyncDesktop.tsx
LLM- Sync from Desktop UI Improvment
- **Linked resource(s)**: [LIVE-3842] 
https://user-images.githubusercontent.com/112866305/191936474-40b8a84f-851f-4a3b-85fb-53dffdb63217.mp4
Do Onboarding > Sync from Desktop
[LIVE-3842]: https://ledgerhq.atlassian.net/browse/LIVE-3842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> support(UI-Improvment) : LLM- Sync from Desktop

- .changeset/perfect-singers-smell.md
- libs/ledger-live-common/src/apps/mock.ts
- libs/ledger-live-common/src/hw/actions/app.ts
- libs/ledger-live-common/src/hw/connectApp.ts
- libs/ledger-live-common/src/hw/isUpdateAvailable.test.ts
- libs/ledger-live-common/src/hw/isUpdateAvailable.ts
In our codebase we have hardcoded minimum app version for some specific applications. This was done when we introduced some breaking change in our functionality that was no longer compatible with older versions of the firmware app. What usually happens is that, when a user who has the firmware app in question installed, but with a version lower than the minimum, we prompt them to go to the manager to update the application.
The problem we are solving here is that, if the user is also not on the latest firmware, they can reach the manager and see that installing the application doesn't solve the issue. The solution proposed here checks whether the current provider has a valid application version available for the current device that would pass the minimum version requirement. If there is …
> bugfix/LIVE-3147 Better error handling for outdated device + outdated app flows

- .changeset/spicy-seahorses-laugh.md
- apps/ledger-live-desktop/src/renderer/components/RepairDeviceButton.jsx
- apps/ledger-live-desktop/src/renderer/screens/USBTroubleshooting/USBTroubleshooting.jsx
- apps/ledger-live-desktop/src/renderer/screens/USBTroubleshooting/USBTroubleshootingMachine.js
- apps/ledger-live-desktop/src/renderer/screens/USBTroubleshooting/solutions/RepairFunnel.jsx
- apps/ledger-live-desktop/src/renderer/screens/USBTroubleshooting/solutions/shared.jsx
- apps/ledger-live-desktop/static/i18n/en/app.json
Improves the UX for the USB troubleshooting flow to prevent getting locked in it when we can't connect a device. It will now always include a way of escaping the flow and either returning to the onboarding flow or exiting if it was launched from the settings.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-2178` 
There are videos and screenshots on the linked Jira task.
I'd say this is a best effort bugfix, we are removing blocking cases so it is genuinely a better UX.
Up to product and QA whether this is good enough to merge or not.
> bugfix/LIVE-2178 Prevent lock cases in USBTroubleShooting

- libs/ledger-live-common/src/bot/engine.ts
- libs/ledger-live-common/src/bot/index.ts
- libs/ledger-live-common/src/bot/types.ts
- libs/ledger-live-common/src/env.ts
ctx https://github.com/LedgerHQ/ledger-live-issues/issues/48
Add on bot specs a global timeout to consider the run due after some times so it stops trying more mutations. This is needed because a seed could have theorically an infinite amount of accounts and mutation could take a lot of time to validate transactions (especially when they fail), we need a way to limit the run time.
a typical example we have today is Cosmos spec having 32 accounts and a mutation timeout of 6 minutes. which makes the worse case of more than 3 hours of run: we would have a global failure because our global timeout is only of 2 hours.
- **Linked resource(s)**: part of https://github.com/LedgerHQ/ledger-live-issues/issues/48  …
> Bot: add skipMutationsTimeout to make app ends in finite time

- .github/workflows/bot-super-report-custom.yml
- .github/workflows/bot-super-report.yml
- tools/actions/generate-bot-super-report/build/main.js
- tools/actions/generate-bot-super-report/logic.ts
- tools/actions/generate-bot-super-report/promise.ts
github `/artifacts` api appears to be capricious and randomly returns HTTP 500. This PR implements a retry mechanism to secure our weekly report. Also added some extra delay and a "promise all batched" approach to not spam too much http queries at same time.
> Bot Super Report: add resilience on github HTTP 500 issues

- libs/ledger-live-common/src/families/cosmos/js-getTransactionStatus.ts
Cosmos redelegate can fail when empty validators.
There's already an error that we used to redelegate, i'm not sure if that's enough tho
```javascript
if (
t.validators.some(
(v) =>
!v.address ||
!v.address.includes(this._validatorOperatorAddressPrefix)
) ||
t.validators.length === 0
)
errors.recipient = new InvalidAddress(undefined, {
currencyName: a.currency.name,
});
```
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-3386 
> LIVE-3386: Cosmos redelegate can fail when empty validators

- .changeset/seven-peas-admire.md
- apps/ledger-live-mobile/src/screens/Swap/Form/index.tsx
Swap buttons not available on Currency and account screens (Quick Actions) 
- **Linked resource(s)**: [LIVE-4178] 
[LIVE-4178]: https://ledgerhq.atlassian.net/browse/LIVE-4178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🐛 bugfix(Swap): LLM - Swap buttons not available on Currency and account screens

- libs/ledger-live-common/src/bot/index.ts
- libs/ledger-live-common/src/bot/types.ts
- libs/ledger-live-common/src/families/cosmos/specs.ts
To have more visibility this gives an estimation of the number of runs possible in specs. (optimistic estimation)
This improve the bot run reporting:
> Bot: Estimate the remaining number of runs

- .changeset/lovely-apples-draw.md
- apps/ledger-live-mobile/src/screens/AddAccounts/01-SelectCrypto.tsx
Add account flow: Testnet currencies shouldn't be available by default
- **Linked resource(s)**: [LIVE-1980] 
https://user-images.githubusercontent.com/112866305/191272515-b1c0ab06-21d3-4972-9a4e-616ede7352f6.mp4
- Settings -> Experimental features → Developper Mode = OFF
- Go to add account flow
- Search for “Testnet”
[LIVE-1980]: https://ledgerhq.atlassian.net/browse/LIVE-1980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bugfix(Testnet): LLM - Add account flow: Testnet currencies shouldn't be available by default

- .changeset/flat-schools-yawn.md
- libs/ledgerjs/packages/hw-app-eth/src/services/ledger/loadConfig.ts
Adding a the NFT endpoint as the default value for the `loadConfig` in `hw-app-eth` in order for other wallets to easily add NFT clear signing through resolution only.
- **Impacted projects**: `ledgerjs/hw-app-eth` 
> Feature - Update NFT endpoint default load config in hw-app-eth

- .changeset/short-adults-grow.md
- apps/ledger-live-mobile/src/screens/Manager/Device/CustomLockScreen.tsx
- apps/ledger-live-mobile/src/screens/Manager/Device/DeviceLanguage.tsx
- apps/ledger-live-mobile/src/screens/Manager/Device/DeviceOptionRow.tsx
There was a flex issue in the My Ledger screen where the "Language" option for a device was not properly displayed.
Fixed it & extracted the component "DeviceOptionRow" for other existing options.
- **Linked resource(s)**: [LIVE-4308] 
https://user-images.githubusercontent.com/91890529/196748527-a349ca91-a8d0-4257-b4eb-7ae573bf8a76.mp4
[LIVE-4308]: https://ledgerhq.atlassian.net/browse/LIVE-4308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bugfix/live 4308 "Language" row bad layout in My Ledger

- .changeset/rotten-jobs-fix.md
- libs/ledger-live-common/src/families/evm/api/etherscan.ts
- libs/ledger-live-common/src/families/evm/api/rpc.common.ts
- libs/ledger-live-common/src/families/evm/errors.ts
- libs/ledger-live-common/src/families/evm/types.ts
- pnpm-lock.yaml
We discovered recently that ethers is hardcoding the value of maxPriorityFeePerGas on its [getFeeData method](https://github.com/ethers-io/ethers.js/blob/44cbc7fa4e199c1d6113ceec3c5162f53def5bb8/packages/abstract-provider/src.ts/index.ts#L252) which is very dangerous.
This updated method will catch the last 5 blocks on the chain, sample the transactions to get the average priority fee used to be included in a block (50% percentile) and provide it as maxPriorityFeePerGas + use it to infer the maxFeePerGas with maxFeePerGas = 2 * nextBaseFee + maxPriorityFeePerGas. (Ensuring 6 blocks of valid baseFee)
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-4283 …
> [LIVE-4283] Hotfix - Update getFeesEstimation for EVM to prevent usage of getFeeData

- libs/ledger-live-common/src/families/osmosis/bridge.integration.test.ts
- libs/ledger-live-common/src/families/osmosis/js-getTransactionStatus.unit.test.ts
Integration test didn't work anymore because the dataset account of osmosis account rewards' were higher than fees, so the warning wouldn't be display again.
So I replace the integ test with a more reliable unit test.
> OSMOSIS: replace integ with unit test

- libs/ledger-live-common/src/families/polkadot/specs.ts
It's seems that MIN_SAFE + MIN_SAFE make a result of a leftover < 0 and if the account is < than 1.2 DOT it will fail into a do send max error
> Bugfix: polkadot spec

- libs/ledger-live-common/src/bot/engine.ts
- libs/ledger-live-common/src/bot/types.ts
- libs/ledger-live-common/src/families/hedera/specs.ts
in the bot, we will consider "critical" when we fail to even reach the transactional mutations phase (see schema https://user-images.githubusercontent.com/211411/191263250-141d023c-c019-4139-b1db-5b2988eecca6.png )
in Hedera case, when no accounts were filled yet, it will crash badly. NB: it doesn't solve the fact we don't even see where to send funds, but it's a limitation of the choices of the current hedera implementation.
> Bot: prevent hedera to "critical error" when it just miss funds

- .changeset/soft-insects-look.md
- apps/ledger-live-mobile/src/components/DeviceAction/index.tsx
- apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
New Device Action rendering in the case of a LatestFirmwareVersionRequired error
- **Linked resource(s)**: [jira](https://ledgerhq.atlassian.net/browse/LIVE-4305)
Fwm update can be done on LLM:
Fwm update cannot be done on LLM:
> Bugfix: LIVE-4305 new rendering in the case of a LatestFirmwareVersionRequired error

- .changeset/red-glasses-rule.md
- apps/cli/src/commands-index.ts
- apps/cli/src/commands/getDeviceRunningMode.ts
- libs/ledger-live-common/src/hw/actions/manager.ts
- libs/ledger-live-common/src/hw/firmwareUpdate-repair.ts
- libs/ledger-live-common/src/hw/getDeviceRunningMode.test.ts
- libs/ledger-live-common/src/hw/getDeviceRunningMode.ts
- libs/ledger-live-common/src/mock/fixtures/aDeviceInfo.ts
- libs/ledgerjs/packages/errors/src/index.ts
Fix the following bug:
> When the user falls under the “bootloader repair” path (triggered when their nanos is on bootloader while on the manager, deviceInfo.isBootloader set to true), the [renderBootloaderStep](https://github.com/LedgerHQ/ledger-live/blob/b53d64842471eb2382066aecfc9f2b3b15ef7aed/apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx#L795) is displayed, and the command firmwareRepair defined [here](https://github.com/LedgerHQ/ledger-live/blob/b53d64842471eb2382066aecfc9f2b3b15ef7aed/libs/ledger-live-common/src/hw/firmwareUpdate-repair.ts#L55) is called once the user clicks on the “continue” button (opening the [AutoRepair](https://github.com/LedgerHQ/ledger-live/blob/b53d64842471eb2382066aecfc9f2b3b15ef7aed/apps/ledger-live-desktop/src/renderer/compone …
> Support: FAT-550 fix bootloader repairing steps

- .changeset/lazy-pets-sniff.md
- apps/ledger-live-desktop/src/renderer/components/ChangeDeviceLanguageAction.tsx
- apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/ChangeDeviceLanguagePromptDrawer.tsx
*Steps to Reproduce:*
1. Enable the device localization FF
2. connect a device that supports localization so its registered in LLD as the “last seen” device. (Go to the manager for instance)
3. Go to settings, change the language to a one supported for device localization
4. When prompted, choose to install the language on the device.
5. Deny on the device or do any action that would trigger an error in the device action
*Expected behavior:*
LLD doesn’t go into an infinite loop, sending thousands of error events until the drawer is closed.
*Actual behavior:*
LLD goes in into an infinite loop, sending thousands of error events until the drawer is closed
- **Linked resource(s)**: [FAT-569]  …
> FAT-569 - Fix infinite loop in ChangeDeviceLanguagePromptDrawer

- apps/ledger-live-mobile/src/components/NavigationModalContainer.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/OnboardingNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/types/BaseNavigator.ts
- apps/ledger-live-mobile/src/components/RootNavigator/types/OnboardingNavigator.ts
- apps/ledger-live-mobile/src/const/navigation.ts
- apps/ledger-live-mobile/src/screens/Onboarding/steps/finish.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/importAccounts.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/pairNew.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/drawers/OnboardingPreQuizModal.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/drawers/Warning.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/index.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/scenes/Intro.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/scenes/RestoreRecoveryPhrase.tsx
- apps/ledger-live-mobile/src/screens/PostBuyDeviceScreen.tsx
- apps/ledger-live-mobile/src/screens/PostOnboarding/PostOnboardingHub.tsx
The navigation was broken on the current onboarding. From my understanding, it was coming from the definition of the navigator previously named `ScreenName.OnboardingModalWarning` and with a screen also named `ScreenName.OnboardingModalWarning`.
How was it working before ? Idk 🤷 
If ok, we'll also do the navigator currently named `ScreenName.OnboardingPreQuizModal` - but there is no bug right now, just the same warning about the fact that 2 screens (well 1 navigator and 1 screen) have the same name
> Bugfix: onboarding navigator for support/fix-llm-ts

- .github/workflows/release-final.yml
When automatic workflow fails for `release-final.yml` job, github releases are not always created due to inconsistent merging on main (one commit should equal to one version but unfortunately that is not the case). I added a skip on the condition to make sure we generate the release on manual trigger.
- **Linked resource(s)**: https://github.com/LedgerHQ/ledger-live-issues/issues/56 
closes https://github.com/LedgerHQ/ledger-live-issues/issues/56
> chore(release): generate github releases on manual trigger

- apps/ledger-live-mobile/src/components/FirmwareUpdateBanner.tsx
- apps/ledger-live-mobile/src/components/TabBar/TabBarSafeAreaView.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/index.tsx
… It was mostly due to a react-native glitch with flex layout
Fix update firmware notif breaking layout by putting it sticky again. It was mostly due to a react-native glitch with flex layout
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-4302
https://user-images.githubusercontent.com/89014981/196754381-dbe5e4c0-f88a-4a08-9491-0e7cfa86dc30.mp4
https://user-images.githubusercontent.com/89014981/196752994-66100f41-e937-4be0-ba73-02819b5eae8a.mp4
> Fix/LIVE-4302 - Fix update firmware notif breaking layout

- libs/ledger-live-common/src/bot/engine.ts
- libs/ledger-live-common/src/bot/types.ts
in https://github.com/LedgerHQ/ledger-live/commit/e2da2d229c83a9a65fbdeafcf86ec183614d4eba#commitcomment-87406584, a rare case occured where it seems that the speculos text was duplicated and streamed twice in the events payload.
> - Crypto org > deviceAction confirm step 'To'
this appears to be a bug in the bot engine and the logic that concatenate the value from the device screen.
```
Object {
-   "To": "cro1t62l7pcawxpskk29v3aqfzv77aey82x50gzjjk",
+   "To": "cro1t62l7pcawxpskk29v3aqfzv77aey82x50gzjjk0gzjjk",
}
```
I suspect that the device screen shown
```
cro1t62l7pcawxpskk29v3aqfzv77aey82x5
0gzjjk
```
in two screens, but somehow we "received"
```
cro1t62l7pcawxpskk29v3aqfzv77aey82x50gzjjk
0gzjjk
0gzjjk
```
like we counted twice the second text.
- …
> Bot: dedup two successive identical speculos text events

- .changeset/long-sloths-share.md
- apps/ledger-live-desktop/src/renderer/drawers/OperationDetails/NFTOperationDetails.jsx
UI glitch in Operation details drawer when Collection name is too long
- **Linked resource(s)**: [LIVE-4277] 
[LIVE-4277]: https://ledgerhq.atlassian.net/browse/LIVE-4277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 💄 [FIX] : LLD - UI glitch in Operation details drawer when Collection name is too long

- .changeset/tricky-mugs-battle.md
- apps/ledger-live-mobile/src/components/DeviceAction/InstallSetOfApps/index.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/SyncOnboarding/index.tsx
Add an extra step in the sync onboarding flow to propose installing a default set of apps to the user after genuine check. The app list in flagged, and the fallback in case of network problem is BTC, ETH and Polygon.
- **Linked resource(s)**: [FAT-542] 
N/A, see slack channels
[FAT-542]: https://ledgerhq.atlassian.net/browse/FAT-542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add install set of apps step in mobile sync onboarding

- .changeset/new-toys-crash.md
- .changeset/quick-cups-lie.md
- apps/ledger-live-mobile/src/screens/Onboarding/steps/pairNew.tsx
- apps/ledger-live-mobile/src/screens/PostOnboarding/PostOnboardingDebugScreen.tsx
- apps/ledger-live-mobile/src/screens/SyncOnboarding/CompletionScreen.tsx
- libs/ledger-live-common/src/postOnboarding/hooks/useStartPostOnboardingCallback.ts
This PR fix the post onboarding hub redirection if there is no action for the user
- **Impacted projects**: `ledger-live-mobile` `ledger-live-common` 
- **Linked resource(s)**: [FAT-560] 
DM me on Slack to have a video demo
[FAT-560]: https://ledgerhq.atlassian.net/browse/FAT-560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix post onboarding redirection

- libs/ledger-live-common/src/bot/specs.ts
- libs/ledger-live-common/src/bridge/jsHelpers.ts
- libs/ledger-live-common/src/families/bitcoin/account-used.integration.test.ts
- libs/ledger-live-common/src/families/bitcoin/datasets/bitcoin.ts
Phosphore bot reveals a problem here. Here are its account:
```
Bitcoin 1 cross [native segwit]: 0.006553 BTC (6ops) (bc1qtmdltwjkf4s0tn45hnwe5astlha6ptrrhp2dsv on 84'/0'/0'/0/4) native_segwit#0 js:2:bitcoin:xpub6BqFXyqM4GtCXuxT6zna2zbVnX7Caig7errmzcb99x43DEZoRYeBKWEjAcxMRWkxZYDhXKrUDPASGsNz9KKArY5zcM12KagZfeg3r655wbc:native_segwit
Bitcoin 2 [native segwit]: 0 BTC (0ops) (bc1qv0dj006wuzhgten806mswcqqx8wmptwuanrd6s on 84'/0'/1'/0/0) native_segwit#1 js:2:bitcoin:xpub6BqFXyqM4GtCbSr2LZGTNEV4HctQrQoCUioCUKjS9sV2TZngK6h6yf4wvJpFRTKtp51cSKsrjS7NtXRUyic9WYSbm8B7XM5cPepYrKtcKY4:native_segwit
Bitcoin 1 [taproot]: 0 BTC (0ops) (bc1p9rqp0ytvfxzmepq7qcryhzvk8uhsvg545ckath6s4sx67ctjdxkq6uhrgm on 86'/0'/0'/0/0) taproot#0 js:2:bitcoin:xpub6C7PPFfQw1G6xBtbf7nKN96UiQx9YKiNUswPZ4mGRLsSn3wdHv9AXAqfRxEezaT9Dn …
```
> Bot: rework jsHelpers makeSync to improve TS and make it update a.used + fixes Bitcoin bot to send txs

- .changeset/popular-baboons-compare.md
- libs/ledgerjs/packages/hw-transport-node-hid/package.json
- pnpm-lock.yaml
- patch update of node-hid
- make the version semver match more permissive (^2.1.2 instead of exact 2.1.2)
- **Impacted projects**: LLD 
- **Linked resource(s)**: LIVE-4428 + fixes #1664 
> update node-hid to 2.1.2

- .changeset/cool-cobras-invite.md
- libs/ledger-live-common/src/market/MarketDataProvider.tsx
_should fix issue undefined chartData in specific cases in MarketDataProvider_
- **Impacted projects**: `ledgerlive-common` 
- **Linked resource(s)**: [LIVE-3988] 
[LIVE-3988]: https://ledgerhq.atlassian.net/browse/LIVE-3988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-3988 - bugfix - issue undefined chartData MarketDataProvider

- .github/workflows/bot-carbon.yml
- .github/workflows/bot-mere-denis.yml
- .github/workflows/bot-mooncake.yml
- .github/workflows/bot-oxygen.yml
- .github/workflows/bot-phosphore.yml
- .github/workflows/bot-silicium.yml
Remove the redundancy of having to set both "Use workflow from" and "The branch to run on" if we want a manually triggered bot run to properly run against the branch AND report to the PR and the associated commits.
**BEFORE:**
many recent bot runs have shown this was not understood and done properly, indeed it's actually confusing.
I suspect we actually don't need the "ref" field at all as we can just works with the native support of it.
testing this with Tezos test against this branch on phosphore:
**AFTER:**
_Pull Requests must pass the CI and be internally validated in order to …
> Bot: Remove the .ref of GH actions

- apps/ledger-live-desktop/src/main/internal-lifecycle.js
- apps/ledger-live-desktop/tests/fixtures/common.ts
To make sure we detect internal process crash in future, this makes all the playwright tests running the app in a more strict way which don't allow an internal crash to happen (by default our app would behave in a resilient way, e.g. if a sync makes a bad crash case, a second sync would try to make it run again – that said, an internal crash isn't really acceptable and does not happen really often in real life – this could be made the default behavior, for now we try this strict mode in our tests)
---
how did i test this is working?
I have added `setTimeout(() => process.exit(1), 5000)` in internal/index.js, and bunch of tests were then failing (locally).
now, we can just confirm on this PR that the CI is ✅ 
- **Linked resource(s)**: LIVE-4473 
_Please make …
> makes playwright test fail on an internal process crash

- .changeset/silly-chairs-pretend.md
- apps/ledger-live-mobile/src/actions/types.ts
- apps/ledger-live-mobile/src/analytics/segment.ts
- apps/ledger-live-mobile/src/reducers/settings.ts
- apps/ledger-live-mobile/src/reducers/types.ts
_LLM - Analytics added firstConnectHasDeviceUpdated prop_
- **Linked resource(s)**: [LIVE-4036] 
[LIVE-4036]: https://ledgerhq.atlassian.net/browse/LIVE-4036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-4036 - LLM - Analytics added firstConnectHasDeviceUpdated prop

- .changeset/dirty-suits-change.md
- apps/ledger-live-desktop/release-notes.json
- apps/ledger-live-desktop/src/renderer/reducers/accounts.js
- apps/ledger-live-mobile/src/reducers/accounts.ts
- apps/ledger-live-mobile/src/screens/Account/SubAccountsList.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/index.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricSections/Allocations.tsx
- libs/ledgerjs/packages/types-live/README.md
- libs/ledgerjs/packages/types-live/src/portfolio.ts
- Remove the `BLACKLIST_TOKEN` action in the `account` reducer
- Display subAccounts only if they are not in the `blacklistTokenIds` list 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-3300
> [LLM] When deleting a token from the list of hidden tokens, it should be shown in the application

- apps/ledger-live-desktop/src/renderer/screens/exchange/index.jsx
Remove navigation for buy / sell screen
cf. https://ledgerhq.atlassian.net/browse/LIVE-4522
> remove navigation from buy / sell live app topbar

- libs/ledger-live-common/src/families/ethereum/signOperation.ts
The current way of encoding chainIds caused an issue when encoding larger numbers to hexadecimals.
This PR guarantees that chainIds are correctly encoding as hexadicamals.
- **Linked resource(s)**: `N/A`
N/A
> Fix chainId encoding for Ethereum family transactions

- .changeset/pink-monkeys-heal.md
- .changeset/popular-eagles-camp.md
- .changeset/pretty-rivers-hear.md
- apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/FeatureFlagsSettings/index.tsx
- apps/ledger-live-mobile/src/components/DeviceAction/InstallSetOfApps/index.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/index.tsx
See more info in [FAT-649]
- Includes a fix for a crash that was happening in the "install set of apps" step of the sync onboarding: because of a bad conditional logic some text was getting rendered outside of a `Text` component.
- **Impacted projects**: `ledger-live-mobile` `ledger-live-desktop` 
- **Linked resource(s)**: [FAT-649] 
[FAT-649]: https://ledgerhq.atlassian.net/browse/FAT-649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAT-649]: https://ledgerhq.atlassian.net/browse/FAT-649?atlOrigin=eyJpIjoiNWRkNTljNz …
> Add one switch to enable multiple flags at once

- .changeset/witty-fireants-hide.md
- apps/ledger-live-mobile/src/components/RootNavigator/CustomBlockRouterNavigator.tsx
- apps/ledger-live-mobile/src/screens/PostOnboarding/PostOnboardingHub.tsx
This fixes a regression that made the Quit Manager confirmation modal show every time even if we didn't have any pending actions as long as we performed one or more actions in that session. So, for example, if you enter manager and install BTC, wait for it to complete and then attempt to quit, it will still prompt you to confirm the action because of pending operations.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-4591` 
- User should be able to quit the manager without having to confirm if there are no pending actions running at the time of clicking the back arrow.
> bugfix/LIVE-4591 Fix navigation lock bug on top left (back) navigation

- .changeset/bright-zebras-add.md
- apps/ledger-live-mobile/src/screens/DebugHttpTransport.tsx
With the new and improved device selector screen we forgot to account for the debug http logic and it was causing a crash after adding a device through that screen.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-4622
> bugfix/LIVE-4622 Fix DebugHttpTransport screen

- .changeset/twelve-plums-rescue.md
- apps/ledger-live-mobile/android/app/build.gradle
- apps/ledger-live-mobile/android/app/src/main/AndroidManifest.xml
- apps/ledger-live-mobile/android/app/src/main/java/com/ledger/live/BackgroundRunner.kt
- apps/ledger-live-mobile/android/app/src/main/java/com/ledger/live/MainActivity.java
Starting on Android 12+ a hard requirement was introduced to set a flag on `PendingIntent` that caused a crash when attempting a firmware update. Following the error logs, this PR introduces said flag for affected versions.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-4623` 
- For both Android < 12 and Android 12+, make sure that the firmware update works correctly without the crash.
> bugfix/LIVE-4623 Fix crash on Android 12+ during FW Update

- .changeset/twenty-cows-burn.md
- apps/ledger-live-mobile/src/helpers/useResetOnNavigationFocusState.ts
- apps/ledger-live-mobile/src/screens/BleDevicePairingFlow/index.tsx
- apps/ledger-live-mobile/src/screens/SyncOnboarding/index.tsx
- libs/ledger-live-common/src/hw/getOnboardingStatePolling.test.ts
- libs/ledger-live-common/src/hw/getOnboardingStatePolling.ts
During sync onboarding:
- Polling would continue a bit after navigating to another screen (for example when returning back to the BLE pairing screen) 
- This would exchange an apdu with the device, while the BLE scanning would start, making the current device not seen by our BLE library
BLE pairing screen:
- When returning to this screen using our navigation system, the state of the screen would not be reseted, taking the former paired device as the newly paired device
This does not fix every problem, it looks like it's still possible that some apdu are exchanged while the BLE scanning starts, making sometime the previously paired device unseen by the scanning. But this PR does improve our flows, and fix certain scenarios. 
- **Impacted projects**: LLM and live-common
- **Linked …
> Fix: FAT-607: a first improvement on BLE and polling mechanism

- .changeset/stale-rabbits-deliver.md
- apps/ledger-live-desktop/src/renderer/components/BalanceInfos/index.jsx
- apps/ledger-live-desktop/src/renderer/components/BuyButton.jsx
- apps/ledger-live-desktop/src/renderer/components/ContextMenu/AccountContextMenu.jsx
- apps/ledger-live-desktop/src/renderer/screens/account/AccountHeaderActions.jsx
- apps/ledger-live-desktop/src/renderer/screens/account/EmptyStateAccount.jsx
- apps/ledger-live-desktop/src/renderer/screens/asset/AssetBalanceSummaryHeader.jsx
- apps/ledger-live-desktop/src/renderer/screens/lend/modals/EmptyAccountDeposit/index.jsx
- apps/ledger-live-desktop/src/renderer/screens/market/MarketCoinScreen/index.tsx
- apps/ledger-live-desktop/src/renderer/screens/market/MarketRowItem.tsx
Changing navigation so that "Buy/Sell" is selected (instead of "Discover") when user navigates to smart routing
- **Impacted projects**: `Ledger Live`, `Smart Routing` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-4306 
- [] **Test coverage** 
> LIVE-4306: [feat] select exchange when navigating to smart routing

- .changeset/brown-pumpkins-crash.md
- apps/ledger-live-mobile/src/components/SelectDevice2/RemoveDeviceMenu.tsx
- apps/ledger-live-mobile/src/reducers/types.ts
- apps/ledger-live-mobile/src/screens/PairDevices/index.tsx
The issue is logged [on Sentry](https://sentry.io/organizations/ledger/issues/3747163866/?project=6619346&referrer=project-issue-stream) but I could not find a way to reproduce it. It is probably due to us saving the device without saving the model id somewhere. So there is 1 place where this has been fixed.
If there is no device id, then no illustration is found for the device id and it would crash (`undefined is not a function`).
- **Linked resource(s)**: [FAT-661] 
[FAT-661]: …
> Fix rendering crash in new device selection screen

- apps/ledger-live-desktop/src/logger/logger-transport-file.js
- apps/ledger-live-desktop/src/main/setup.js
- apps/ledger-live-desktop/tests/fixtures/common.ts
- tools/actions/composites/test-desktop/action.yml
these should be the same logs you get when you do Ctrl+E and they can therefore be opened on https://live.ledger.tools/logsviewer
when we have a very technical problem on a playwright run, this could be useful to look into, for instance of internal process crash, etc..
- **Impacted projects**: `LLD tests` 
> Make playwright runs generate log files exported on the CI

- .changeset/shy-months-attend.md
- apps/ledger-live-desktop/src/renderer/Default.jsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/RecoveryContent.tsx
- apps/ledger-live-desktop/src/renderer/hooks/useStoryly.tsx
- apps/ledger-live-desktop/src/renderer/modals/StorylyDebugger/index.tsx
Following this conversation it's clear that we don't want to remotely load and inject some javascript in LLD as it's a big security vulnerability.
Storyly isn't urgently needed for now on LLD so we can disable it until we come up with a better solution (also because there are other priorities right now I don't have time to find the better solution, but **disabling** this script injection is still a big priority before the pre-release).
- **Linked resource(s)**: [FAT-671] 
[FAT-671]: …
> Disable storyly LLD

- .changeset/pretty-terms-repair.md
- apps/ledger-live-mobile/src/components/CustomImage/CustomImageBottomModal.tsx
- apps/ledger-live-mobile/src/components/CustomImage/useCenteredImage.tsx
- apps/ledger-live-mobile/src/components/CustomImage/useResizedImage.tsx
- apps/ledger-live-mobile/src/components/Nft/NftLinksPanel.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/CustomImageNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/types/CustomImageNavigator.ts
- apps/ledger-live-mobile/src/const/navigation.ts
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/CustomImage/PreviewPostEdit.tsx
- apps/ledger-live-mobile/src/screens/CustomImage/PreviewPreEdit.tsx
- apps/ledger-live-mobile/src/screens/CustomImage/Step1Crop.tsx
- apps/ledger-live-mobile/src/screens/CustomImage/Step2Preview.tsx
Rework the custom edit flow. For more information see the proper Slack channels.
- **Linked resource(s)**: [FAT-600], [FAT-605] 
N/A, see slack channels
[FAT-600]: https://ledgerhq.atlassian.net/browse/FAT-600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FAT-605]: https://ledgerhq.atlassian.net/browse/FAT-605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> New edit flow

- .github/workflows/generate-screenshots.yml
`generate-screenshot` action is using the old `is-org-member` action (dead now). Updated it to use `is-fork` instead
- **Linked resource(s)**: Slack 
If it runs correctly we are golden 
We are golden (_edited_)
> fix(ci): generate-screenshot to use is-fork now

- libs/ledger-live-common/src/bot/index.ts
it was assumed that having a .mutation & !.operation was synonym to having errors but it doesn't include the error that could happen before even reaching mutation
that technically means that the bot was only raising (on slack / in the description summary) a partial version of all spec having errors
for instance, in this screenshot you see no mention of "Viacoin" in the "5 specs have problems", yet there is a critical problem at stake (maybe during estimation of max spendable)
- **Impacted projects**: `lld bot` 
> bot engine to include spec mutation with .error

- .changeset/warm-dolphins-study.md
- libs/ledger-live-common/src/families/ethereum/__tests__/transaction.unit.test.ts
- libs/ledger-live-common/src/families/ethereum/modules/send.ts
- libs/ledger-live-common/src/families/ethereum/specs.ts
Fixes wrong amount estimation in send mode`prepareTransaction` when during a send max.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-4684 
https://user-images.githubusercontent.com/44363395/203337722-cf0116f6-9ab9-42dd-a97a-89964b978f2e.mov
> [LIVE-4684] Bugfix - Wrong prepareTransaction gasPrice with EIP1559

- .changeset/eight-walls-move.md
- apps/ledger-live-desktop/src/renderer/screens/exchange/index.jsx
Add lang query param when navigating to smart routing live app
- **Impacted projects**: `Ledger Live`, `Smart Routing` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-4306 
> LIVE-4306: smart routing add lang query param

- .changeset/shaggy-chairs-end.md
- libs/ledger-live-common/src/families/ethereum/__tests__/transaction.unit.test.ts
- libs/ledger-live-common/src/families/ethereum/modules/send.ts
- libs/ledger-live-common/src/families/ethereum/prepareTransaction.ts
Fixing an error when Ethereum accounts with only dust in it where trying to do a send max.
Fixing the `getTransactionStatus` not being triggered because of `@ethereumjs/tx` throwing in `prepareTransaction` 
- https://ledgerhq.atlassian.net/browse/LIVE-4698
- https://ledgerhq.atlassian.net/browse/LIVE-4702 
Send max on dusty account
https://user-images.githubusercontent.com/44363395/203549156-23c9d899-0733-40f7-ae89-39479d0b9f51.mp4
getTransactionStatus
https://user-images.githubusercontent.com/44363395/203549084-250a1d17-c0c0-4df3-a640-e8781f319f29.mp4
_Pull Requests must pass the …
> [LIVE-4698][LIVE-4702] Bugfix - Fix ethereum send max on dusty account and getTransactionStatus not being triggered

- libs/ledger-live-common/package.json
a edge case of previously introduce feature (https://github.com/LedgerHQ/ledger-live/pull/1888)
is that if a live-common/src file is modified not inside a folder that have a nearby `.integration.test.ts`
it will fail, like experienced in https://github.com/LedgerHQ/ledger-live/pull/1871
- this should fail (develop version): https://github.com/LedgerHQ/ledger-live/actions/runs/3548919712 
- this should succeed (this pr): https://github.com/LedgerHQ/ledger-live/actions/runs/3548933751
> Allows ci-test-integration to pass without test

- .changeset/real-bees-roll.md
- apps/ledger-live-mobile/src/screens/Lending/shared/01-Amount.tsx
- apps/ledger-live-mobile/src/screens/SendFunds/03a-AmountCoin.tsx
- apps/ledger-live-mobile/src/screens/Swap/Form/Max.tsx
Mobile key wasn't translate so we revert change to make it only appears on desktop and have no impact in mobile
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-2627 
> LIVE-2627 Revert change key on mobile for usemax

- libs/ledgerjs/script/crypto-assets-importer/importers/eip712.js
EIP712 CAL importer was not getting all the available data to add to the parsed file. 
Before that change we were wrongly importing only the first result instead of merging all of them into a big Map (each key has to be different by definition so we can't have collisions).
- **Impacted projects**: `ledgerjs` 
> Bugfix - Fix EIP712 CAL importer not merging all files

- .changeset/funny-ants-accept.md
- apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx
- apps/ledger-live-mobile/src/components/ValidateOnDevice.tsx
- apps/ledger-live-mobile/src/screens/ConnectDevice.tsx
Device actions have so much padding all over the place that some critical info is out of view and on some screens you need to (not obviously) scroll to see it. This is even worse with some of the bigger lottie animations where the title is not even visible depending on the screen size.
This particular screen has been validated with Aamir from design by the way, I'm not just improvising.
- **Linked resource(s)**: [FAT-689] 
https://user-images.githubusercontent.com/91890529/204019280-29c6e685-247e-4a49-866e-4d086235acfc.mp4 …
> Improve layout in ValidateOnDevice

- .changeset/warm-fishes-talk.md
- apps/ledger-live-mobile/src/screens/CustomImage/Step3Transfer.tsx
This PR changes slightly the CLS flow so it auto-selects a device for the image when the last connected device is an FTS. 
- **Linked resource(s)**:  [FAT-659]
N/A
[FAT-659]: https://ledgerhq.atlassian.net/browse/FAT-659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FAT-659 Automatically select last seen device if compatible for CLS

- .changeset/cyan-feet-worry.md
- .changeset/giant-walls-march.md
- .changeset/sour-countries-learn.md
- apps/ledger-live-mobile/ios/ledgerlivemobile/Info.plist
- libs/ledger-live-common/src/apps/runner.ts
- libs/ledgerjs/packages/react-native-hw-transport-ble/src/BleTransport.ts
This PR introduces a fix on the runners that allows the internal errors that can occur while installing an app to bubble up and reach the surface device action instead of being treated as false completion positives. 
It also introduces a forceful disconnection timeout when we try to close the connection with a device on the BleTransport, preventing endless awaits if the JavaScript thread is paused in the middle of an exchange. This unlocks cases where we were left in a soft brick state where we couldn't communicate with the device anymore until we rebooted or restarted LLM.
Lastly, it enables (like on BIM) background BLE communication capabilities, allowing us to communicate with the device over BLE for _some time_ making the UX a bit better than abruptly breaking.
- **Impacted …
> bugfix/FAT-588 Improve LLM background device communication

- .changeset/thin-otters-cross.md
- apps/ledger-live-mobile/src/components/RootNavigator/types/ReceiveFundsNavigator.ts
- apps/ledger-live-mobile/src/screens/ReceiveFunds/01-SelectCrypto.tsx
ReceiveFunds/01-SelectCrypto must actively not accept TokenCurrency. There were a path in the code that allowed to open that screen with a token which make the app crash ⚠️ 
- **Impacted projects**: LLM 
- **Linked resource(s)**: https://sentry.io/organizations/ledger/issues/3756208221 
> Fixes ReceiveFunds/01-SelectCrypto to not accept TokenCurrency

- libs/ledger-live-common/src/families/bitcoin/bridge/mock.ts
- libs/ledger-live-common/src/families/bitcoin/js-getTransactionStatus.ts
`t.feePerByte` can be undefined, triggering a `Cannot read properties of null (reading 'toNumber')` error and potentially crashing the app.
This PR handles this case properly.
Introduced by this line -> https://github.com/LedgerHQ/ledger-live/pull/1705/files#diff-9481356d1850289b630777fce1fef96c6ace0798ba31894f9357b85cf043c7e3R120
cf. this [CI run](https://github.com/LedgerHQ/ledger-live/actions/runs/3533577647/jobs/5929402610#step:8:6639) failing due to this issue for example
- **Linked resource(s)**: https://github.com/LedgerHQ/ledger-live/pull/1705 …
> fix unhandled undefined or null for feePerByte

- .changeset/pink-terms-breathe.md
- apps/ledger-live-mobile/src/components/Scanner.tsx
The fallback camera screen for iOS was rendering a white screen instead of the fallback UI that leads the user to the permission settings. This PR should address that and make it work for both iOS and Android builds correctly.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-4812` 
https://user-images.githubusercontent.com/4631227/205108315-d7368c9f-59d3-42c8-babc-1e0ada950490.mov
- Refused permissions on camera for iOS should not render a white screen but rather the help UI
> bugfix/LIVE-4812 Fix white screen on fallback camera for recipient scanner iOS

- .changeset/chilly-donkeys-double.md
- libs/ledgerjs/packages/react-native-hw-transport-ble/src/BleTransport.ts
It was found out during regression testing that the stability of the BLE connection was in fact worse than before the changes, so we need to roll them back for now until we understand the underlying cause of this behaviour. This was already merged on `release` we need it on `develop` too.
- **Impacted projects**: `react-native-hw-transport-ble` 
Nothing to demo
Those crashes shouldn't be happening anymore
> bugfix/rollback-ble Undo BleTransport changes

- .changeset/rude-turtles-buy.md
- apps/ledger-live-mobile/src/log-report.ts
- libs/ledger-live-common/src/env.ts
Since we’re seeing more and more logs from LLM that get truncated I propose increasing the maximum number of logged entries on LLM from 1000 to 5000 making it configurable via env if needed, dropping the ble-frame (and making this _excluded types_ also changeable from env) logs since we already have the apdu ones and the framing logic has been proven to work, removing the log id from the logged data since we already have the date and they’re ordered to reduce a bit the size. I would also remove the bulk payloads from script-runners since they’re pretty huge but in most cases we won’t have those.
Unless I’m missing something, this change shouldn’t impact performance negatively since we are not causing new renders, it would however increase the ram memory usage a little bit, but not enough …
> feat/LIVE-4816 Increase the number of logs that are exported on LLM

- apps/ledger-live-desktop/src/main/internal-lifecycle.js
- apps/ledger-live-desktop/tests/fixtures/common.ts
reactivate the work of https://github.com/LedgerHQ/ledger-live/pull/1762
which was in fact not the cause of the CI failure
- **Linked resource(s)**: LIVE-4473 
> makes playwright test fail on an internal process crash (#1762)

- .github/workflows/test-integration-pr.yml
- .github/workflows/test-integration.yml
- package.json
attempt to fix the test-integration tests to build only llc (and not bluetooth libs) to fix Windows.
- **Impacted projects**: CI 
- https://github.com/LedgerHQ/ledger-live/actions/runs/3628377388
- https://github.com/LedgerHQ/ledger-live/actions/runs/3628471726 
> Build only llc for integration tests

- apps/ledger-live-mobile/e2e/reporters/AllureReporterCircus.js
Small PR to fix taking screenshot when test fails for allure reporting.
Like in this [run](https://github.com/LedgerHQ/ledger-live/actions/runs/3619804263/jobs/6101278055)
` error: TypeError: Cannot read properties of undefined (reading 'device')
at AllureReporterCircus.test_done`
> Detox - Allure - Fix screenshots when test failed

- .changeset/tiny-brooms-sit.md
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FormSelectors/FromRow.jsx
In LLD, the loading indicator is currently misaligned in the From form on the Swap screen.
- **Linked resource(s)**:  https://ledgerhq.atlassian.net/browse/LIVE-4747
> LLD - bug - fixes loading indicator on swap page

- .changeset/hot-jars-obey.md
- apps/ledger-live-mobile/src/screens/Swap/Form/index.tsx
In LLM on the Swap screen, if you changed the network fee then we were incorrectly displaying the target account with the From account name. This PR fixes that to not update the target account name when the network fee is changed.
I have also manually checked that you can still change the target account from one ethereum account to another, and it still works as expected.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-4781
https://user-images.githubusercontent.com/119950081/206242523-ab475ab7-1c60-46ac-8891-536ee30a78d4.mp4
_Pull Requests must pass the CI and be internally validated in order to …
> bugfix: llm - fixes issue on swap screen whereby target account was the From account name

- .changeset/nervous-socks-invite.md
- apps/ledger-live-mobile/src/components/TermsFooter.tsx
Currently, the terms & conditions link is aligned to the left whereas it should be centre. This PR fixes this issue.
- **Impacted projects**:  LLM
- **Linked resource(s)**:  https://ledgerhq.atlassian.net/browse/LIVE-4780
ios on left, android on right
> bugfix - llm - aligns terms & conditions link on the swap confirmation modal

- .changeset/calm-bulldogs-crash.md
- .changeset/chatty-spies-wash.md
- .changeset/slimy-tigers-invite.md
- apps/ledger-live-desktop/src/renderer/actions/settings.js
- apps/ledger-live-desktop/src/renderer/components/ByteSize.jsx
- apps/ledger-live-desktop/src/renderer/components/CustomImage/CustomImageDeviceAction.tsx
- apps/ledger-live-desktop/src/renderer/reducers/settings.js
- apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/index.jsx
- apps/ledger-live-desktop/tests/models/DeviceAction.ts
- apps/ledger-live-mobile/src/actions/settings.ts
- apps/ledger-live-mobile/src/actions/types.ts
- apps/ledger-live-mobile/src/components/ByteSize.tsx
- apps/ledger-live-mobile/src/components/CustomImageDeviceAction.tsx
- apps/ledger-live-mobile/src/reducers/settings.ts
- apps/ledger-live-mobile/src/reducers/types.ts
- apps/ledger-live-mobile/src/screens/CustomImage/Step3Transfer.tsx
- apps/ledger-live-mobile/src/screens/Manager/Device/DeviceAppStorage.tsx
- apps/ledger-live-mobile/src/screens/Manager/Device/index.tsx
- libs/ledger-live-common/src/api/Manager.ts
- libs/ledger-live-common/src/apps/formatting.test.ts
- libs/ledger-live-common/src/apps/formatting.ts
- libs/ledger-live-common/src/apps/hw.ts
- libs/ledger-live-common/src/apps/logic.test.ts
- libs/ledger-live-common/src/apps/logic.ts
- libs/ledger-live-common/src/apps/mock.ts
- libs/ledger-live-common/src/apps/types.ts
- libs/ledger-live-common/src/hw/actions/ftsLoadImage.ts
- libs/ledger-live-common/src/hw/ftsFetchImageSize.test.ts
- libs/ledger-live-common/src/hw/ftsFetchImageSize.ts
- libs/ledger-live-common/src/hw/ftsLoadImage.ts
Currently the space taken by the custom image is not taken into account when we access My Ledger, leading to an incorrect available storage breakdown. This PR introduces support for it as part of the response of the `listApps` logic as well as support for updating the space while already in My Ledger if we set it following the CTA.
In addition to this support it fixes two bugs founds during the development:
- A custom image was detected as an app for LLD, breaking the storage distribution and showing a warning about the storage being incomplete. This should be solved too, it can be tested by making sure that a device with no apps but with a custom image shows zero apps in My Ledger and not 1.
- A rendering bug on LLM that only occurred when we have a single application installed. It would …
> feat/FAT-690 Support for custom image storage in logic + UI

- .changeset/green-tools-share.md
- libs/ledger-live-common/src/families/near/api/near-staking-positions-sdk.ts
- libs/ledger-live-common/src/families/near/js-getTransactionStatus.ts
- libs/ledger-live-common/src/families/near/logic.ts
Was noted that new staking positions will not appear on NEAR LLM immediately after staking, it takes awhile. Looks like this is due to a cache ONLY on the staking positions endpoint, only on LLM. We can get around this by adding a `date` param with the timestamp.
- **Impacted projects**: `LLM` `LLC`
- **Linked resource(s)**: [Discord message](https://discord.com/channels/885256081289379850/973221693638193152/1052216993757024306)
[This Discord message](https://discord.com/channels/885256081289379850/973221693638193152/1052598485280628828) has a demo attached.
> fix: NEAR LLM bust staking positions cache

- .changeset/dirty-cycles-itch.md
- apps/ledger-live-mobile/src/components/FallbackCameraBody.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/ImportAccountsNavigator.tsx
- apps/ledger-live-mobile/src/components/Scanner.tsx
- apps/ledger-live-mobile/src/icons/FallbackCamera.tsx
- apps/ledger-live-mobile/src/screens/ImportAccounts/Scan.tsx
The UI for the fallback screen was not adapting well to theme changes, this must've been like this since the v3 rework because it was still using old color palette references and some components were not adapted to themes at all (like the icon). This is just a small polish on what should be a rework of the screen as far as I'm concerned.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/FAT-730` 
https://user-images.githubusercontent.com/4631227/207642208-72e436b4-48e2-4a9c-bb25-3b1a9dc60dc5.mov
Ensure that the camera fallback works with the expected UI for both themes, on both Android and iOS, respecting the color changes. Easily testable using the `DEBUG_THEME=1` flag for switching themes like on the video above. Also ensure …
> bugfix/FAT-730 Fix UI for fallback camera

- .changeset/red-trains-fry.md
- apps/ledger-live-desktop/src/renderer/actions/swap.js
- apps/ledger-live-desktop/src/renderer/actions/swap.test.js
`filterAvailableToAssets` is currently very slow when working with large arrays of `pairs` because of the array spreading inside the reduce statement. When profiling on a separate [branch](https://github.com/LedgerHQ/ledger-live/pull/2123/files) - it took around 15s for this function to execute. 
With the changes done in this PR, this function now returns much faster (where there is no noticeable delay in the UI). 
- **Impacted projects**:  Desktop
- **Linked resource(s)**:  https://ledgerhq.atlassian.net/browse/LIVE-4862
> bugfix - LLD - improves swap redux selector performance

- .changeset/thirty-ties-love.md
- libs/ledger-live-common/src/exchange/index.test.ts
- libs/ledger-live-common/src/exchange/index.ts
- libs/ledger-live-common/src/exchange/platform/transfer/index.ts
- libs/ledger-live-common/src/exchange/sell/index.ts
- libs/ledger-live-common/src/exchange/swap/index.ts
Refacto exchange partner config
- use a util function to generate to config based on name, publickey and signature
- remove curve field from config since it is unused (most of thems had value `secpk256k1` which is not a valid curve)
- **Linked resource(s)**: https://github.com/LedgerHQ/ledger-live/pull/2030
> Refacto exchange partner config

- .changeset/pretty-suits-jump.md
- apps/ledger-live-mobile/src/reducers/ble.ts
- apps/ledger-live-mobile/src/reducers/settings.ts
When merging https://github.com/LedgerHQ/ledger-live/pull/2144 we missed a case where, when a user had seen a device with the codename `nanoFTS`, we tried to access the model information for that reference. Since https://github.com/LedgerHQ/ledger-live/pull/2144 replaced all references in favor of `stax` this is currently crashing the app for devs/qa. The pr prevents them from having to reinstall the app, this wouldn't reach prod . 
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/FAT-742` 
No demo
Even harder than the LLD version to reproduce, you would have to checkout an commit before the rename happened, pair a stax device, update your branch to right after the rename to reproduce the crash, then to this pr to reproduce …
> bugfix/FAT-742 Prevent crash when app tries to use stored nanoFTS ref

- .changeset/early-owls-count.md
- .changeset/heavy-jobs-laugh.md
- .changeset/spicy-socks-sin.md
- apps/ledger-live-desktop/src/renderer/components/CustomImage/FramedImage.tsx
- apps/ledger-live-desktop/src/renderer/components/CustomImage/ImageGrayscalePreview.tsx
- apps/ledger-live-desktop/src/renderer/components/CustomImage/TestImage.tsx
- apps/ledger-live-desktop/src/renderer/components/CustomImage/shared.ts
- apps/ledger-live-desktop/src/renderer/screens/customImage/Step2AdjustImage.tsx
- apps/ledger-live-mobile/src/screens/CustomImage/PreviewPreEdit.tsx
- apps/ledger-live-mobile/src/screens/CustomImage/Step1Crop.tsx
- apps/ledger-live-mobile/src/screens/CustomImage/Step2Preview.tsx
- apps/ledger-live-mobile/src/screens/CustomImage/shared.ts
- apps/ledger-live-mobile/src/screens/Settings/Debug/Features/CustomImageGraphics.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/Features/FetchCustomImage.tsx
- libs/ledger-live-common/src/hw/staxLoadImage.ts
Even though the display is 400x672, two of the pixels from the height are not visible. This resulted in minor cropping of the bottom part of the selected image and, in case there was some text there, rendered it illegible. This PR addresses the issue by modifying the image customization tool to only use the visible pixels and padding the data before sending it to match what the firmware expects from us.
- **Impacted projects**: `ledger-live-mobile, ledger-live-desktop, ledger-live-common` 
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/FAT-720` 
Feel free to use this image for testing, it has pixel perfect size and content on the edges to guarantee it remains visible.
Maybe also play with other images to make sure the cropping doesn't mess with it.
We shouldn't lose the …
> bugfix/FAT-720 Use 670px height for custom lockscreen images

- .changeset/mean-panthers-live.md
- .changeset/rare-dryers-punch.md
- .changeset/twenty-experts-cough.md
- apps/ledger-live-desktop/src/renderer/actions/settings.js
- apps/ledger-live-desktop/src/renderer/components/FirebaseFeatureFlags.tsx
- apps/ledger-live-desktop/src/renderer/components/FirebaseRemoteConfig.tsx
- apps/ledger-live-desktop/src/renderer/reducers/settings.js
- apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/FeatureFlagsSettings/index.tsx
- apps/ledger-live-mobile/src/actions/settings.ts
- apps/ledger-live-mobile/src/actions/types.ts
- apps/ledger-live-mobile/src/components/FirebaseFeatureFlags.tsx
- apps/ledger-live-mobile/src/components/FirebaseRemoteConfig.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/reducers/settings.ts
- apps/ledger-live-mobile/src/reducers/types.ts
- apps/ledger-live-mobile/src/screens/FeatureFlagsSettings/FeatureFlagDetails.tsx
- apps/ledger-live-mobile/src/screens/FeatureFlagsSettings/FeatureFlagEdit.tsx
- apps/ledger-live-mobile/src/screens/FeatureFlagsSettings/GroupedFeatures.tsx
- apps/ledger-live-mobile/src/screens/FeatureFlagsSettings/index.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/index.tsx
- apps/ledger-live-mobile/src/screens/Settings/Experimental/ExperimentalHeader.tsx
- libs/ledger-live-common/src/featureFlags/groupedFeatures.ts
- libs/ledger-live-common/src/featureFlags/index.ts
- libs/ledger-live-common/src/featureFlags/provider.tsx
- libs/ledger-live-common/src/featureFlags/useHasOverriddenFeatureFlags.ts
- libs/ledger-live-common/src/postOnboarding/hooks/usePostOnboardingHubState.test.ts
- libs/ledgerjs/packages/types-live/src/feature.ts
- LLM+LLD: Overriding the configuration of feature flags is now **persistent over app restarts**. This is done using the settings property of the redux store.
- LLM: added a "Flags overridden locally" reusing the Experimental banner to signal whether some flags are overridden locally. This banner can be disabled in the FF debug menu.
- LLM: "Reset all" button to reset all locally overridden feature flags.
- LLM: Grouped features that can be toggled all at once
- **Impacted projects**: `mobile` `desktop` `common` 
- **Linked resource(s)**: [FAT-721] 
sound on 🔊
https://user-images.githubusercontent.com/91890529/207936443-1ffa0ce7-fae7-4d82-8e70-f6d96d4a5a1e.mov
The description of the PR and the demo above summarize what is new and to test on this PR.
_Please make sure you follow these …
> Feature flags UX improvements

- .changeset/lazy-sloths-obey.md
- .changeset/spotty-boxes-battle.md
- apps/ledger-live-desktop/src/renderer/components/WebPlatformPlayer/LiveAppSDKLogic.ts
- apps/ledger-live-mobile/src/components/WebPlatformPlayer/WebView.tsx
If the currencies array passed to `requestAccount` contains other values than string, the underlying function crashes (cf. demo). 
Make sure currencies param of requestAccount is a string array.
<details>
<summary>KO 💥 </summary>
https://user-images.githubusercontent.com/9203826/208966317-7a0a5d13-11ee-4e9c-bf53-67a099a5e05a.mov
</details>
<details>
<summary>OK ✅  </summary>
https://user-images.githubusercontent.com/9203826/208966376-6bfbf50d-d7f8-4f2d-b121-207e6c091f85.mov
</details>
LL should not crash even if invalid values passed as param for live-app-sdk functions
_Pull Requests must …
> [BUGFIX] make sure currencies param of requestAccount is string array

- apps/ledger-live-mobile/detox.config.js
- apps/ledger-live-mobile/package.json
_Increasing detox setup Timeout to prevent apk install fails as in this [build](https://github.com/LedgerHQ/ledger-live/actions/runs/3740270840/jobs/6348449355)
Adding again detox script in package list_
> B2CQA - Increase detox setup Timeout

- .changeset/moody-flowers-enjoy.md
- apps/ledger-live-mobile/src/components/FirmwareUpdateBanner.tsx
- apps/ledger-live-mobile/src/screens/Manager/AppsList/AppUpdateAll.tsx
- apps/ledger-live-mobile/src/screens/Manager/AppsScreen.tsx
This is a small PR just to fix some weird spacing that was happening at the My Ledger page concerning the update banners for firmware and apps. Right now there should never be both the firmware update banner and the apps update banner at the same time. And the margins for the banner should be correct.
- **Linked resource(s)**: [FAT-744](https://ledgerhq.atlassian.net/browse/FAT-744)
> Fix margins for app update and firwmare update banners

- .changeset/khaki-walls-carry.md
- apps/ledger-live-mobile/src/screens/CustomImage/PreviewPreEdit.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/Features/CustomImage.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/Features/index.tsx
When entering the custom lockscreen flow's error screen, the back arrow / back navigation brings back to an infinite loader because we used `navigate` instead of `replace`.
- **Linked resource(s)**: [FAT-710] 
N/A, see proper slack channels
[FAT-710]: https://ledgerhq.atlassian.net/browse/FAT-710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix back navigation when entering CLS error screen

- .changeset/loud-garlics-kiss.md
- .changeset/quiet-jobs-roll.md
- apps/ledger-live-desktop/src/renderer/components/DeviceAction/animations.ts
- apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/SoftwareCheckAllowSecureChannelModal.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/SoftwareCheckLockedDeviceModal.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/TroubleshootingDrawer.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/index.tsx
- libs/ui/packages/react/src/index.ts
- libs/ui/packages/react/src/styles/index.ts
- libs/ui/packages/react/src/styles/theme.ts
In `react-ui`: 
- narrow-typed theme to "dark"| "light"
- and exported Theme type from react-ui
In LLD: fix typing of theme "light" | "dark"
- removed unneeded "as" type casting
- used newly exported `Theme` type.
- migrated `animations.js` to `animations.ts`
Demo showing that theme and animations are not broken:
https://user-images.githubusercontent.com/15096913/210547644-15aa55f3-50b1-46fc-8066-94154ecb0ddd.mp4
> Support: LIVE-5092: Narrow theme type

- apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx
This PR fix the crash of the new device error when a device is not seeded
> Fix crash of the new device error when a device is not seeded

- .changeset/silly-cars-remember.md
- apps/ledger-live-desktop/src/renderer/components/DeviceAction/animations.ts
There's a crash on develop when accessing the manager on LLD coming from the `animations.ts` file. This happens because of a nested object access without `undefined` or `null` checks. In theory the type system should prevent those from happening in this file but since desktop isn't yet fully TS migrated we need this check.
> Fix desktop crash when accessing the manager

- libs/ledger-live-common/src/families/ethereum/signOperation.ts
- pnpm-lock.yaml
- tools/common-tools/package.json
- tools/common-tools/src/demos/eth-tx-tools/index.js
- tools/common-tools/src/demos/index.js
In certain circumstance, Ledger Live fails to sign the TX before even reaching the final device step (for instance during resolveTransaction or during the "provideNFTInformation" device phase).
In that case, we are clueless to look at reproducing it.
This add back the logs, we will be able to more easily build tooling if we have such log of the raw tx. I recommend to make this "rawtx" error code a convention for all coins.
I have made a page in our live tools to allow to debug it:
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5054 
_Pull Requests must pass the CI and be internally …
> ethereum: log the unsigned raw tx

- .changeset/few-toes-appear.md
- apps/ledger-live-mobile/src/components/CheckTermOfUseUpdate.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/SettingsNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/types/SettingsNavigator.ts
- apps/ledger-live-mobile/src/const/navigation.ts
- apps/ledger-live-mobile/src/logic/terms.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/Features/TermsOfUse.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/Features/index.tsx
'Terms of Use Update' pop-up issue in DE & ES and maybe some others languages
- **Linked resource(s)**: [LIVE-5036] 
https://user-images.githubusercontent.com/112866305/209684933-93362551-4c1b-4571-9ebe-19b7bea12f55.mov
**Go To Debug > Features & Flows > Terms of Use (Last one)**
[LIVE-5036]: https://ledgerhq.atlassian.net/browse/LIVE-5036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🐛 [BUGFIX] : LIVE-5036 : LLM- 'Terms of Use Update' pop-up issue in some languages

- apps/ledger-live-desktop/src/internal/commands/index.js
- apps/ledger-live-desktop/src/internal/commands/publicKeyTweakAdd.js
- apps/ledger-live-desktop/src/internal/commands/publicKeyTweakAdd.test.ts
- apps/ledger-live-desktop/src/internal/commands/publicKeyTweakAdd.ts
- apps/ledger-live-desktop/src/logger/logger-transport-in-memory.js
- apps/ledger-live-desktop/src/logger/logger-transport-main.js
- apps/ledger-live-desktop/src/logger/logger-transport-renderer-instance.js
- apps/ledger-live-desktop/src/logger/logger-transport-renderer.js
- apps/ledger-live-desktop/src/main/setup.js
- apps/ledger-live-desktop/src/renderer/bridge/proxy.js
- apps/ledger-live-desktop/src/renderer/commands.js
- apps/ledger-live-desktop/src/renderer/components/ExportLogsButton.jsx
- apps/ledger-live-desktop/src/renderer/experimental.jsx
- apps/ledger-live-desktop/src/renderer/init.jsx
- apps/ledger-live-desktop/src/renderer/live-common-setup.js
- apps/ledger-live-desktop/static/i18n/en/app.json
- libs/ledger-live-common/src/env.ts
This is an **experimental** settings. When not activated, nothing changes (if dev review can double confirm this)
When activated, a bunch of LLD "commands" will execute directly on the renderer side instead of being requested through  `renderer<>main<>internal` process.
This is the first step of the fundamental work of ["Dismantling LLD "internal process" threading model"](https://ledgerhq.atlassian.net/wiki/spaces/WALLETCO/pages/3948118370/Technical+introduction) with a more urgent need to offer a fix for using Ledger Live through VPN (that historically has been [an issue](https://github.com/LedgerHQ/ledger-live-desktop/issues/1073)): the fact things run on Chromium side already help fixing the issue (node.js/axios isn't 100% bullet proof to support all cases of VPN and proxies) …
> Introduce "experimental networking" settings that runs all coin and app logic on renderer side

- apps/ledger-live-desktop/src/sentry/install.js
- apps/ledger-live-mobile/index.js
HederaAddAccountError was added to unify many Hedera network errors, however it wasn't ignored to be sent to sentry. this fixes it.
> Sentry: ignore HederaAddAccountError

- .changeset/fluffy-chairs-develop.md
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.jsx
Debounces the user input on swap form so we do not fetch rates on each key entry.
- **Linked resource(s)**:  https://ledgerhq.atlassian.net/browse/LIVE-5063
https://user-images.githubusercontent.com/119950081/210383418-14f31da3-1cc7-485b-ada0-dd566513b85f.mov
[LIVE-5063]: https://ledgerhq.atlassian.net/browse/LIVE-5063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LLD - bugfix - debounces user input on swap form

- .changeset/rotten-waves-join.md
- libs/ledgerjs/packages/react-native-hw-transport-ble/src/BleTransport.ts
This PR is a revival of #879, adding `/lib` back with a comment explaining the reasons behind the change to prevent it being removed in the future.
- **Impacted projects**: `react-native-hw-transport-ble` 
- **Linked resource(s)**: #2185  
See #879
| with fix          | without fix     |
|------------- | ------------- |
| <img width="540" alt="Screenshot 2023-01-12 at 11 16 10" src="https://user-images.githubusercontent.com/3428394/212040856-bd807ec0-83c0-428d-9c0b-a39d1395be12.png"> | <img width="525" alt="Screenshot 2023-01-12 at 11 17 36" src="https://user-images.githubusercontent.com/3428394/212040874-42414b43-936b-4300-8e91-1b2e2e527c73.png"> |
_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important-steps) …
> Force commonjs imports from react-native transport package

- apps/ledger-live-desktop/tests/fixtures/common.ts
- apps/ledger-live-desktop/tests/models/TermsModal.ts
- apps/ledger-live-desktop/tests/specs/general/passwordlock.spec.ts
- apps/ledger-live-desktop/tests/specs/general/terms.spec.ts
- apps/ledger-live-desktop/tests/specs/general/updater.spec.ts
- apps/ledger-live-desktop/tests/specs/services/discover.spec.ts
- apps/ledger-live-desktop/tests/specs/support/unsupported-os.spec.ts
Some tests were resulting in the following errors:
This is because we are waiting for a Promise and comparing that with a boolean instead of comparing two of the same object types. The fix is to change from `isVisible()` on the locator and asserting if it's `true`/`false`, to just asserting that a locator is visible with `toBeVisible()`.
**EDIT: actually it looks like the issue was an `expect.poll` that didn't have an await, which was causing some weird timing issues and therefore some checks were failing**
N/A …
> Fixed faulty assertions in Playwright tests

- .changeset/gold-ligers-look.md
- apps/ledger-live-desktop/src/logger/logger-transport-in-memory.js
- apps/ledger-live-desktop/src/logger/logger-transport-renderer.js
- apps/ledger-live-desktop/src/main/setup.js
optimize the performance of the memory logger in LLD. `.push()` is faster than `.unshift()`
- **Impacted projects**: LLD 
> Optimize logger

- .changeset/thirty-turtles-thank.md
- libs/ledger-live-common/src/families/cosmos/helpers.ts
- libs/ledger-live-common/src/families/cosmos/helpers.unit.test.ts
Bugfix: cosmos delegate/undelegate/unbond is wrong interpreted into claim reward operation
- **Impacted projects**: `` LLD, Cosmos
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-5161
> Bugfix/LIVE-5161 Cosmos tx type fix

- .changeset/hot-coins-laugh.md
- apps/ledger-live-desktop/src/renderer/icons/providers/Oneinch.jsx
Aligns all swap rates in LLD. They were previously misaligned because the 1inch logo was rendered at 24px wide, whereas it should be 28px.
- **Impacted projects**:  Desktop
- **Linked resource(s)**:  https://ledgerhq.atlassian.net/browse/LIVE-5152
> fix: aligns 1inch swap rate with other rates in LLD

- .changeset/nasty-years-pay.md
- .changeset/poor-glasses-destroy.md
- apps/ledger-live-desktop/src/renderer/components/FormattedVal.jsx
- apps/ledger-live-desktop/src/renderer/components/Price.jsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/Rates/SwapRate.jsx
- libs/ledger-live-common/src/currencies/formatCurrencyUnit.ts
In swap page after an estimation, providers quotes are exchange rates are not readable when too many decimals. Limit decimal to 7.
- **Impacted projects**: LLM & common
- **Linked resource(s)**:  https://ledgerhq.atlassian.net/browse/LIVE-5151
> fix: add static limit to format value

- .changeset/soft-bananas-crash.md
- apps/ledger-live-mobile/src/screens/DeviceConnect/index.tsx
Use the new `SelectDevice2` in the `DeviceConnect` component for the wallet-api, it should fix issue with BLE connectivity
> fix(wallet-api): use the newDeviceSelectionFeature on mobile

- apps/ledger-live-mobile/src/analytics/segment.ts
blockchainsWithNftsOwned added to segment extra properties
- **Linked resource(s)**: [LIVE-4775] 
[LIVE-4775]: https://ledgerhq.atlassian.net/browse/LIVE-4775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> blockchainsWithNftsOwned added to segment extra properties

- .changeset/stupid-fans-vanish.md
- apps/ledger-live-desktop/src/renderer/screens/platform/App.jsx
Fixes an issue whereby when a user presses the close button when they're in doing a DEX swap in the 1inch/paraswap webview, they should be navigated back to the swap screen.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5213
https://user-images.githubusercontent.com/119950081/213429695-3bb18c2d-0105-4704-988b-c83e515d61f9.mov
> bugfix - lld - fixes back button during a DEX swap

- apps/ledger-live-desktop/src/renderer/init.jsx
enableDebugLogger() have a HUGE cost when you use DEV_TOOLS and it should only be activated in verbose mode.
> enableDebugLogger to enable active in VERBOSE case

- .changeset/wild-news-exist.md
- libs/ledgerjs/packages/react-native-hw-transport-ble/src/BleTransport.ts
On iOS some users are facing connection failed issues
In `BleTransport` we now use a singleton to handle the BLE manager, but one usage of it was not correctly updated.
The fact that with the new device selection screen we would not face the same problem can be explained by the fact that on the new device selection screen, a BLE scanning is done before trying to "open" the device. This scanning would have already set up an instance of `bleManager`, avoiding the issue.
- **Impacted projects**: `react-native-hw-transport-ble`
- **Linked resource(s)**: [FAT-801](https://ledgerhq.atlassian.net/browse/FAT-801)
_Pull Requests must pass the CI and be …
> Bugfix: FAT-801 bluetooth connection failed

- apps/ledger-live-desktop/src/renderer/components/EntryButton/EntryButton.tsx
- apps/ledger-live-desktop/src/renderer/screens/dashboard/FeaturedButtons.tsx
Changes Exchange Buttons to use react-ui Tag component.
Changes components over to typescript.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5174
> bugfix: changes exchange buttons to use react-ui tag

- apps/ledger-live-mobile/src/components/Nft/NftList.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/WalletTabNavigator.tsx
- apps/ledger-live-mobile/src/components/WalletTab/WalletTabHeader.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
Due to a blocker on Android preventing from closing the NFT-Multiselect, we removed the header from that view, brought back the initial header and added a cancel button in the bottom bar, near the hide button.
Uploading Screen Recording 2023-01-24 at 17.45.11.mov…
> New close button in NFT Multiselect

- .changeset/dry-frogs-know.md
- .changeset/swift-phones-marry.md
- libs/ledger-live-common/src/families/ethereum/__tests__/modules/erc20.unit.test.ts
- libs/ledger-live-common/src/families/ethereum/modules/erc20.ts
- libs/ledgerjs/packages/hw-app-eth/README.md
- libs/ledgerjs/packages/hw-app-eth/src/services/ledger/erc20.ts
- libs/ledgerjs/packages/hw-app-eth/tests/ERC20/ERC20-CAL-KO.unit.test.ts
- libs/ledgerjs/packages/hw-app-eth/tests/ERC20/ERC20-CAL-OK.unit.test.ts
- libs/ledgerjs/packages/hw-app-eth/tests/Eth.integration.test.ts
Add resilience to malformed dynamic CAL files.
We were supporting the CDN failing, but not files being malformed. 
E.g. If the `erc20.json` file is returning a string instead of an array of strings/numbers, it could cause an error that would prevent every Ethereum family sync. (And that case happened when the CDN returned a 200 string as the 404 error) 
- **Impacted projects**: `live-common`, `hw-app-eth` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5288 
> [LIVE-5288] Bugfix - Add resilience to ethereum tokens fetching

- .changeset/odd-fireants-fix.md
- apps/ledger-live-desktop/src/config/urls.js
some link inside Ledger Live still lead to the old repository.
> fixes old link to old repository

- libs/ledgerjs/packages/react-native-hw-transport-ble/src/BleTransport.ts
Fix the lazy initialization of the BleManager
Merging fix done in https://github.com/LedgerHQ/ledger-live/pull/2376 into `release`
> fix: incorrect usage of bleManager instance

- .changeset/smooth-walls-greet.md
- libs/ledger-live-common/src/hw/getDeviceName.test.ts
- libs/ledger-live-common/src/hw/getDeviceName.ts
Due to unforeseen circumstances we need to bring back the suppossedly superflous apdu that we were sending before the get device name command. When used on a LNX it's sometimes glitching and returning the wrong value.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-5273` 
No demo
Make sure device name looks ok with the old device selection on a nano x.
> bugfix/LIVE-5273 Device name is not displayed properly in LLM

- .changeset/heavy-donkeys-burn.md
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/explorer/index.ts
- libs/ledger-live-common/src/families/stellar/api/horizon.ts
- libs/ledger-live-common/src/network.ts
the proposal is to no longer have `"network"` and `"network-success"` log in the exported logs but only keep the `"network-error"`. This also takes opportunity to start simplification of the networking interception (in parallel of other exploration like #2363 ) 
logging this represents an important part of performance in some contexts (in case where the logger is costly, like internal<>renderer architecture, or in VERBOSE mode).
Reduce the file size of the bot zip export from 257 to 233MB.
In the usecase of "knowing how much http query the bot do" we could in future implement a dedicated solution for this and I will note it somewhere as well
- **Impacted projects**: `lld/llm` 
- **Linked resource(s)**:  https://ledgerhq.atlassian.net/browse/LIVE-5298 
_Please make sure you follow these …
> Simplify network to only log network-error & improve perf

- .changeset/nice-books-mate.md
- .changeset/tender-bats-join.md
- apps/ledger-live-desktop/src/sentry/install.js
- apps/ledger-live-mobile/index.js
- libs/ledgerjs/packages/errors/README.md
- libs/ledgerjs/packages/errors/src/index.ts
`HwTransportError` represents errors coming from the usage of a Transport implementation, and should not be sent to Sentry.
Fixed this for LLD and LLM
- **Impacted projects**: `LLM`, `LLD`
> Bugfix: ignore HwTransportError for Sentry

- libs/ledger-live-common/src/account/serialization.ts
This PR fixes the integration tests that were using snapshots which would not contain the new `transactionRaw` field in operations.
> Support: Update serialization of transactionRaw

- .changeset/real-papayas-yawn.md
- apps/ledger-live-mobile/src/screens/DeviceConnect/index.tsx
Removed the `SkipSelectDevice` from the `DeviceConnect` screen in order to avoid always selecting the same device.
> fix: remove skip select device on DeviceConnect

- .changeset/hot-ants-explode.md
- libs/ledger-live-common/src/apps/hw.ts
- libs/ledger-live-common/src/apps/polyfill.test.ts
- libs/ledger-live-common/src/apps/polyfill.ts
Starting on version `2.1.0` some of our apps that used to depend on Bitcoin have become independent. However, the current way of resolving dependencies is based on the currency family and does not support this. A first approach was introduced on [feat/LIVE-4625](https://github.com/LedgerHQ/ledger-live/pull/1959) but it was flawed in the sense that the presence of the Bitcoin Legacy app does not necessarily mean that the clone app is independent.
This PR introduces a check based on the version and drops the presence check, as well as adding some tests to cover that functionality.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-5293` 
No demo, only logic.
- We should be able to install and run apps that are Bitcoin clones …
> bugfix/LIVE-5293 Dependency resolution for newly standalone currency apps

- .changeset/curly-papayas-itch.md
- libs/ledger-live-common/src/families/tron/bridge/js.ts
Fixes Tron signOperation to alter the input 'transaction' object during signOperation in order to make the bot pass with the extra restriction of a strict check on immutability ( https://github.com/LedgerHQ/ledger-live/pull/2473 )
```
necessary accounts resynced in 0.19ms
▬ Tron 0.3.8 on nanoS 2.1.0
→ FROM Tron 4: 2 TRX (499ops) (TBtPherJfuSMaJnWVtuuo2AvjgdfxzUhAb on 44'/195'/3'/0/0) #3 js:2:tron:TBtPherJfuSMaJnWVtuuo2AvjgdfxzUhAb:
max spendable ~0
★ using mutation 'unfreeze bandwith / energy'
✔️ transaction 
UNFREEZE BANDWIDTH  
TO 
STATUS (133ms)
amount: 0 TRX
estimated fees: 0 TRX
total spent: 0 TRX
errors: 
errors: 
⚠️ TypeError: Cannot assign to read only property 'amount' of object '#<Object>'
(totally spent 136ms – ends at 2023-01-31T11:44:09.151Z) 
```
- **Impacted projects**: `*` …
> Fixes immutability of Tron in signOperation

- .changeset/slimy-foxes-brush.md
- libs/ledger-live-common/src/families/elrond/js-buildSubAccounts.ts
- libs/ledger-live-common/src/families/elrond/specs.ts
https://github.com/LedgerHQ/ledger-live/pull/2473 have revealed problem in Elrond implementation that alters the original object (input of the sync) which can cause subtle bugs all over our stack.
sync must embrace the immutability paradigm and not alter the incoming objects / create copy of objects when necessary.
There were a few mutating issue:
- `tokenAccounts.operations` getting mutated if the token account already exists and it doesn't recreate a ref for that token account. (possible consequence: UI may not always refresh to show the latest state of the account if user stay on the token account, notably on LLM)
- same for `tokenAccounts.balance`
- `operation.extra` mutated in the spec for the bot. this may hide real bug on that test
- **Impacted projects**: `*` 
- **Linked …
> Elrond: fixes immutability of syncESDTTokenAccountOperations

- .changeset/curly-papayas-itch.md
- .changeset/slimy-foxes-brush.md
- libs/ledger-live-common/src/bot/cli.ts
- libs/ledger-live-common/src/bot/engine.ts
- libs/ledger-live-common/src/families/elrond/js-buildSubAccounts.ts
- libs/ledger-live-common/src/families/elrond/specs.ts
- libs/ledger-live-common/src/families/tron/bridge/js.ts
from Slack discussion, we suspect some coins have bug where they modify the original `Account` object, that is supposed to be preserved as immutable.
To detect such issue, we introduce in the bot an usage of `Object.freeze` which in combination with `"use strict"` would make the bot crash on case of mutating the existing account fields in case they get written (it makes field "read-only")
> Make the Bot freeze objects to detect possible mistakes

- .changeset/blue-jars-shop.md
- apps/ledger-live-mobile/src/analytics/UserIdPlugin.tsx
- apps/ledger-live-mobile/src/analytics/segment.ts
Fix the analytics missing equipment id for some users
> Fix the analytics missing equipment id for some users

- .changeset/six-teachers-listen.md
- apps/ledger-live-desktop/src/renderer/families/cosmos/DelegationFlowModal/Info/index.jsx
This PR fixes an issue when opening the cosmos stake modal. Currently it opens a URL in a browser multiple times without clicking on the link. This PR changes this behaviour to only open the link when it is clicked.
- **Linked resource(s)**:  https://ledgerhq.atlassian.net/browse/LIVE-5358
https://user-images.githubusercontent.com/119950081/216098829-cbccdb72-1ea4-43bd-a2a1-2852d81cf5f0.mov
> fix: lld - fixes learn more link in cosmos staking flow

- .changeset/bright-roses-own.md
- apps/ledger-live-desktop/src/renderer/components/BalanceInfos/index.jsx
If feature_portfolio_exchange_banner is enabled, we shouldn’t see the ‘Buy’ and the 'Swap` buttons on the portfolio screen
- https://ledgerhq.atlassian.net/browse/LIVE-5352
> fix: LIVE-5352 remove balance info redundant button in portafolio page

- apps/cli/src/live-common-setup-base.ts
- apps/ledger-live-desktop/src/live-common-setup-base.js
- apps/ledger-live-mobile/src/live-common-setup.ts
- libs/ledger-live-common/src/__tests__/test-helpers/environment.ts
- libs/ledger-live-common/src/env.ts
- libs/ledger-live-common/src/network.ts
Switch HTTP headers to `X-Ledger-Client-Version` that will be standardized everywhere. That way, renderer (web env) can also set these headers (`User-Agent` can't be set on Chrome/Chromium)
- **Impacted projects**: `lld, llm, cli, bot` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5223 
> Switch to new Ledger headers & explicit usage from bot & cli

- .changeset/friendly-coats-watch.md
- apps/ledger-live-desktop/src/renderer/families/cosmos/UndelegationFlowModal/Body.jsx
- apps/ledger-live-desktop/src/renderer/families/cosmos/UndelegationFlowModal/fields/Validator.jsx
- apps/ledger-live-desktop/src/renderer/families/cosmos/UndelegationFlowModal/steps/Amount.jsx
- apps/ledger-live-desktop/src/renderer/families/cosmos/UndelegationFlowModal/steps/Confirmation.jsx
- apps/ledger-live-desktop/src/renderer/families/cosmos/UndelegationFlowModal/steps/index.jsx
- apps/ledger-live-desktop/static/i18n/en/app.json
- libs/ledger-live-common/src/families/cosmos/js-buildTransaction.ts
Bug fix
Delegate - error message displayed when validating a delegation on Comsos
Basiclly, in a unbond transaction,
"transaction.amount" should be replaced with
"transaction.validators[0].amount" in js-buildTransaction.ts
"transaction.amount" doesn't make sense and it is always zero.
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-5371
- [X ] **Atomic delivery** 
- [X ] **No breaking changes** 
> Bugfix-LIVE 5371 fix cosmos unbond

- libs/ledger-live-common/src/families/bitcoin/specs.ts
The error `TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))` because of incorrect read transaction object in the bitcoin bot spec.
The PR fixes the issue
- **Linked resource(s)**: `N/A`
> (bugfix) bitcoin bot spec - extract recipient address from op_return tx

- .changeset/two-snails-try.md
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FeesDrawer/index.jsx
LLD - Swap - No padding for network fees drawer
- **Linked resource(s)**:  https://ledgerhq.atlassian.net/browse/LIVE-5309
> Bugfix: LIVE-5309 fix swap style

- .changeset/funny-teachers-enjoy.md
- apps/ledger-live-desktop/src/renderer/modals/NoFundsStake/index.tsx
Adds `flow: stake` to analytic event properties when pressing buttons in the no-fund modal
> fix: lld - adds stake flow to no-fund modal buttons

- .changeset/rare-fans-move.md
- .changeset/twelve-hounds-cross.md
- libs/ledger-live-common/jest.config.ts
- libs/ledger-live-common/src/naming-service/api.integration.test.ts
- libs/ledger-live-common/src/naming-service/api.ts
- libs/ledger-live-common/src/naming-service/index.tsx
- libs/ledger-live-common/src/naming-service/logic.ts
- libs/ledger-live-common/src/naming-service/naming-service.react.test.tsx
- libs/ledger-live-common/src/naming-service/naming-service.unit.test.tsx
- libs/ledger-live-common/src/naming-service/types.ts
Able to use our explorer to get ENS for a specific `*.*` name
We first create some hooks to be use in LLM and LLD.
But for testing we needed to have a change jsdom in jest live-common env to test React hook we have in live-common.
> Support/live 5078 ENS hooks + jest env change

- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/scenes/RestoreWithProtect.tsx
Add tracking to RestoreWithProtect info modal
because the modal was already done :doughnut: 
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-4989
https://user-images.githubusercontent.com/89014981/212118278-d2bf2d88-8cff-40cf-a23b-5b4284807d3f.mp4
> Feat/LIVE-4989 - Add tracking to RestoreWithProtect info modal

- .changeset/eighty-gifts-speak.md
- apps/ledger-live-desktop/static/i18n/en/app.json
Changes the Earn button on the portfolio screen to say Stake - so it is consistent with other stake buttons.
- **Impacted projects**: Desktop
> bugfix: lld - changes copy of Earn button to Stake

- .changeset/chilly-snails-exist.md
- .changeset/five-fireants-lay.md
- .changeset/young-pumpkins-do.md
- apps/cli/src/live-common-setup-base.ts
- apps/ledger-live-desktop/src/live-common-set-supported-currencies.js
- apps/ledger-live-mobile/src/live-common-setup.ts
- libs/ledger-live-common/src/__tests__/test-helpers/environment.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/crypto/factory.ts
- libs/ledger-live-common/src/families/cosmos/chain/chain.ts
- libs/ledgerjs/packages/cryptoassets/src/abandonseed.ts
As we’ve dropped the cosmos_testnet during the cosmos SDK integration recently. We need to remove cosmos_testnet completely in our codebase.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5457
> LIVE-5457 Cosmos testnet cleanup

- apps/ledger-live-desktop/src/renderer/screens/asset/AssetBalanceSummaryHeader.jsx
Adds stake button on asset screen.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5466
> bugfix: lld - shows stake button on asset screen

- .changeset/stupid-keys-bake.md
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.jsx
- apps/ledger-live-desktop/src/renderer/screens/platform/App.jsx
Refactors how we pass params from swap screen to live-app. According to typescript, `history.push` does not take in a `params` value (even though it seems to work). 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-3880
https://user-images.githubusercontent.com/119950081/217870331-0e711051-d84f-4996-838f-9b1bed8715b5.mov
> fix: lld - redirect to dex live-app using state instead of params

- .github/workflows/build-desktop-external.yml
- .github/workflows/build-desktop.yml
- .github/workflows/build-mobile-external.yml
- .github/workflows/build-mobile.yml
- .github/workflows/generate-screenshots.yml
- .github/workflows/regen-doc.yml
- .github/workflows/regen-pods.yml
- .github/workflows/test-desktop-external.yml
- .github/workflows/test-desktop.yml
- .github/workflows/test-mobile-e2e.yml
- .github/workflows/test-mobile.yml
- .github/workflows/test.yml
We used to have `inputs.xxx` calls in the `concurrency` part of the github actions workflow yaml file.
[**(Like here)**](https://github.com/LedgerHQ/ledger-live/blob/8ee24c5a03f570c03f1e6ef0c3e499766e88b3e6/.github/workflows/generate-screenshots.yml#L21)
Unfortunately even though the [**official documentation**](https://docs.github.com/en/actions/learn-github-actions/contexts#about-contexts) says it is fine, it's [**not**](https://github.com/orgs/community/discussions/35341).
This caused concurrency issues with the generate screenshot workflow cancelling previous runs on different PRs.
Using `github.event.inputs.xxx` calls instead supposedly works though.
- https://github.com/orgs/community/discussions/35341
N/A
_Please make sure …
> fix ci concurrency inputs

- .changeset/five-poets-confess.md
- apps/ledger-live-mobile/src/screens/DeviceConnect/index.tsx
We had to remove the reset of the device to undefined
It avoids starting the ble scanning again on success
The ble scanning is disconnecting all device which was causing the issue
> fix(wallet-api): broken ble on LLM

- .changeset/mighty-drinks-listen.md
- apps/ledger-live-mobile/src/components/QueuedDrawer.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/shared/SeedWarning.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/Features/QueuedDrawers.tsx
- apps/ledger-live-mobile/src/screens/SyncOnboarding/LanguageSelect.tsx
The new queue drawer had a logic error in how it handles the lost of (react-navigation) screen focus
Fixed:
On `QueuedDrawer`:
- When loosing focus: all drawers are cleaned, and it now tries to call the `onClose` of the QueuedDrawer if it tried to be opened after the navigation occurred  
- When getting focus: we now check if the drawer was not added just before (`drawerId`) to avoid adding it several time, because `useFocusEffect` can be triggered several time in certain cases
On other components:
- For a consuming component: onClose needed even if noCloseButton was set to handle lost of screen focus or if other drawer forced it to close
- **Linked resource(s)**: [FAT-827](https://ledgerhq.atlassian.net/browse/FAT-827) …
> Bugfix: FAT-827 fix queued drawer on react-navigation focus change - and for select language

- .changeset/healthy-pillows-joke.md
- apps/ledger-live-mobile/src/screens/DeviceConnect/index.tsx
Use the same logic as the manager screen, we reset the device in order to close the `DeviceActionModal` when `onClose` is called
> fix: reset device on close instead of navigating back

- .changeset/rare-peas-sing.md
- libs/ledger-live-common/src/families/ethereum/synchronisation.ts
Fix eth perf problems
We were calling 20 times the same page
This time we call the same page maximum 2 times
If last tx of last request is the same as the current one we stop calling the backend
The real fix is using the token pagination mechanism
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5490 
> [LIVE-5490] Fix eth sync and perf

- .changeset/big-bats-visit.md
- .changeset/neat-oranges-exercise.md
- apps/ledger-live-mobile/src/components/QueuedDrawer.tsx
- apps/ledger-live-mobile/src/components/SelectDevice2/index.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/language.tsx
Fix 2 issues:
- drawer "add new device" on new device selection is not correctly closed
- `onClose` was called on a drawer that did not tried to be opened if this drawer was forcefully closed (for ex: on navigation/change of screen focus)
- this created an issue if the `onClose` triggers a navigation
- encountered also again a problem with the legacy `onModalHide` calling `onClose` in `BaseModal` for the language selection  
- added a watchdog to avoid calling twice `onClose`
- **Linked resource(s)**: [FAT-827](https://ledgerhq.atlassian.net/browse/FAT-827)
<details>
<summary>Issue 1: android: drawer add new in device selection</summary>
https://user-images.githubusercontent.com/15096913/218483290-b281d87a-22fd-40a2-bae9-0c0a1c1e71b9.mp4
</details>
<details> …
> Fix: add new device drawer closing in new device selection

- .github/workflows/gate.yml
should fix forked prs
This is what PRs coming from forked repos get as of today: 
```
Run tibdex/github-app-token@v1
Error: Error: Input required and not supplied: app_id
```
Using a standard github token should hopefully solve this.
N/A
> ci: use standard github token in the gate

- .changeset/fifty-beers-run.md
- apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/Welcome/index.tsx
I noticed that on a fresh install we have no way of skipping onboarding on LLD for dev builds and, even though we could manually modify the data file to add the flag this is a pita and easily avoided. This PR adds that little button, that's it.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-5662` 
> feat/LIVE-5662 Provide a way of skipping onboarding on dev builds

- tools/common-tools/src/demos/index.js
- tools/common-tools/src/demos/networkTroubleshooting/index.js
makes the networkTroubleshoot tool that we find in Ledger Live settings also available standalone on a web page.
- **Impacted projects**: `tools` 
> feat: add in web tools a way to check network troubleshooting

- .changeset/friendly-toys-fly.md
- apps/ledger-live-desktop/src/renderer/families/cosmos/AccountHeaderManageActions.js
Stake click button is not working as expected
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5709
> fix: fix stake click in cosmos and osmos

- .changeset/healthy-pets-complain.md
- apps/ledger-live-mobile/src/constants.ts
- apps/ledger-live-mobile/src/context/AuthPass/index.tsx
When using LLM password prompt feature, we're currently logging current time when the application goes background. When coming back to the app, we compare the time the app went background to the current time. If the delay is big enough, we prompt the user for his password.
A vulnerability was reported in our bugbounty program : the password prompt can be defeated by setting the device time to a date before the app went background.
The proposed solution was : instead of comparing times, we use an unchangeable value, the device uptime. If the uptime retained when the app went background is smaller than the current uptime, we prompt for the password. That solution didn't worked well.
New solution is an anticipation of a new FaceID feature coming up in the next weeks. The background timeout …
> LLM - Lock issue fix

- .changeset/calm-coats-float.md
- apps/ledger-live-desktop/src/renderer/screens/account/AccountStakeBanner.tsx
Fix osmos stake account banner is not showed after refactor
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5088
> fix: fix osmos banner after refactor

- .changeset/strange-fireants-fly.md
- libs/ledger-live-common/src/families/cosmos/chain/cosmosBase.ts
Increase gas estimation for claim rewards for cosmos to avoid "out of gas" error from users
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5681
> LIVE-5681 Increase gas estimation for claim rewards for cosmos

- .changeset/olive-wolves-grow.md
- libs/ui/packages/react/src/components/form/BaseInput/index.tsx
Removes the input padding added to inputs in the react-ui package.
This padding is not needed and causes the text inside the input to be aligned at the bottom of the input instead of the center:
- **Impacted projects**: `@ledgerhq/react-ui` 
- **Linked resource(s)**: - 
> bugfix(react-ui): remove input padding

- .changeset/big-lobsters-relax.md
- libs/ledger-live-common/src/api/Ethereum.ts
- libs/ledger-live-common/src/families/ethereum/gas.test.ts
- libs/ledger-live-common/src/families/ethereum/gas.ts
add back catch clause in estimate gas limit call
Add back the catch clause in estimate gas limit for eth
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5631 
> fix: remove gas limit error when available balance too low

- .changeset/big-bats-battle.md
- apps/ledger-live-mobile/e2e/specs/password.spec.ts
Fixed E2E tests  - removed a scenario after having removed the autolock timeout for password lock.
> LLM - Fix on E2E tests

- .changeset/great-pets-report.md
- apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/types/BaseNavigator.ts
- apps/ledger-live-mobile/src/components/WebPlatformPlayer/WebViewV2.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/DeviceConnect/index.tsx
- libs/ledger-live-common/src/wallet-api/react.ts
The error is already handled by the UI in `DeviceActionModal`
Also adds a correct title to this screen and fixes the `SafeAreaView`
https://user-images.githubusercontent.com/3009753/220630391-9210c5b6-8811-45f2-9f91-f251e51ecd00.mp4
https://user-images.githubusercontent.com/3009753/220630484-049fa861-b29f-4a7e-80de-931e6bcdfec8.mp4
> fix(DeviceConnect): remove onError handler

- .github/workflows/build-desktop-external.yml
- .github/workflows/build-desktop.yml
- .github/workflows/build-mobile-external.yml
- .github/workflows/build-mobile.yml
- .github/workflows/test-desktop-external.yml
- .github/workflows/test-desktop.yml
- .github/workflows/test-mobile-e2e.yml
- .github/workflows/test-mobile.yml
- .github/workflows/test.yml
Remove on every workflow triggered by the orchestrator the `inputs.ref` parameter. 
It should now be superseded by the `github.ref` / `github.ref_name` context variables.
N/A
> ci: remove now useless ref input

- .changeset/thirty-dancers-appear.md
- apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx
There was a bug in the rendering of errors in the Onboarding device action, probably on some other device action flows too but it was caught during the onboarding one. The easiest way to trigger is to have repl running or another app that wants to access the nano since we need to throw an error that has support links, but this is just a coincidence.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5818 
> fix(errors): rendering of errors in device actions

- .changeset/forty-icons-fetch.md
- apps/ledger-live-mobile/src/actions/settings.ts
- apps/ledger-live-mobile/src/actions/types.ts
- apps/ledger-live-mobile/src/components/DeviceAction/index.tsx
- apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx
- apps/ledger-live-mobile/src/components/DeviceLanguageInstalled.tsx
- apps/ledger-live-mobile/src/components/ModalLock.tsx
- apps/ledger-live-mobile/src/components/QueuedDrawer.tsx
- apps/ledger-live-mobile/src/reducers/settings.ts
- apps/ledger-live-mobile/src/screens/Manager/Device/DeviceLanguageSelection.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/Features/QueuedDrawers.tsx
We were not storing the changed language on the last seen device information leaving to a missed opportunity to prompt the user to also change the device language when they changed the app language and we can offer it. It's easier to understand with the test instructions really.
- **Linked resource(s)**:  https://ledgerhq.atlassian.net/browse/LIVE-5364 
https://user-images.githubusercontent.com/4631227/219421109-18a0d5a4-49ed-4aa3-a6b5-ec5660668b3f.mp4
- LLM should remember the last seen device language now.
- Changing LLM to a language supported by FW should prompt the user.
- If the last seen device language is already LLM's language, no prompt.
> bugfix/LIVE-5364: Fix bug in device language change prompt

- .changeset/chatty-glasses-bow.md
- apps/ledger-live-mobile/src/context/AuthPass/index.tsx
Fixed hierarchy issue causing Auth screen to render behind app in Android
- **Linked resource(s)**: LIVE-5837
N/A
> LLM - AuthScreen not showing on Android

- .changeset/chilly-roses-push.md
- .changeset/lazy-elephants-chew.md
- apps/ledger-live-mobile/src/screens/Manager/AppsList/AppInstallButton.tsx
- apps/ledger-live-mobile/src/screens/Manager/AppsList/AppRow.tsx
- libs/ledger-live-common/src/manager/index.ts
The original ticket only addressed the disabling of the currency but in the process I noticed we were lacking a design for this disabled state. After syncing with Brian and Product, the proposed design shown below is now implemented. 
- **Impacted projects**: `ledger-live-mobile, live-common` 
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-5628` 
- Make sure you can't install Elrond
- Make sure **you can** uninstall Elrond
> feat/LIVE-5628 Disable Elrond + LLM UI for disabled install actions

- .changeset/violet-pandas-grab.md
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FormSummary/SectionFees.jsx
Fixes the close button (and all other buttons) on the coin modal.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-5310
https://user-images.githubusercontent.com/119950081/220974037-fabf1c71-a99b-442d-b227-c640c402a416.mov
> fix: allows coin modal to be closed on swap screen

- apps/ledger-live-mobile/src/config/urls.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/drawers/ProtectConnectionInformationModal.tsx
Updates the Bluetooth connection info modal of Ledger Recover flow.
- **Linked resource(s)**: [LIVE-5500](https://ledgerhq.atlassian.net/browse/LIVE-5500)
[LIVE-5500]: https://ledgerhq.atlassian.net/browse/LIVE-5500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: device connection info

- .changeset/soft-cats-smell.md
- libs/ledgerjs/packages/react-native-hid/android/src/main/java/com/ledgerwallet/hid/HIDDevice.java
- libs/ledgerjs/packages/react-native-hid/android/src/main/java/com/ledgerwallet/hid/LedgerHelper.java
- libs/ledgerjs/packages/react-native-hid/android/src/main/java/com/ledgerwallet/hid/ReactHIDModule.java
- libs/ledgerjs/packages/react-native-hid/android/src/main/java/com/ledgerwallet/hid/ReactHIDPackage.java
- libs/ledgerjs/packages/react-native-hid/src/index.ts
With the changes in Android 12 we lost support for USB OTG on LLM. This PR introduces the now mandatory flag to continue supporting this connection channel since it's the only one for Android with LNS/LNS+ (plus wired LNX/Stax).
- **Impacted projects**: `react-native-hid` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/FAT-828
Not needed.
- USB OTG Should work on all versions of Android.
- Please test old and new because perhaps fixing the new broke the old and I only have a 13 to test with me.
> fix(react-native-hid): support usb otg connectivity for android 12+

- package.json
Improve dev:lld:debug so it uses the good remote debugging port by default
Improve dev:lld:debug so it uses correct port by default
- **Linked resource(s)**: No jira ticket 
> feat: improve lld debug command

- .changeset/tough-cougars-suffer.md
- apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx
- libs/ledger-live-common/src/deviceSDK/commands/getVersion.test.ts
- libs/ledger-live-common/src/deviceSDK/commands/getVersion.ts
- libs/ledger-live-common/src/hw/getVersion.test.ts
- libs/ledger-live-common/src/hw/getVersion.ts
- libs/ledger-live-common/src/manager/localization.test.ts
- libs/ledger-live-common/src/manager/localization.ts
Starting on `rc8` stax devices are able to have localization features, this PR enables the installation via our dev builds, cli and once propagated our repl tool.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-5929` 
No demo.
Localization UI and functionality should be enabled and working with RC8 upwards.
> feat: LIVE-5929 Enable localization flags for stax devices

- apps/ledger-live-mobile/src/actions/protect.ts
- apps/ledger-live-mobile/src/actions/types.ts
- apps/ledger-live-mobile/src/db.ts
- apps/ledger-live-mobile/src/reducers/protect.ts
- apps/ledger-live-mobile/src/screens/Protect/Login.tsx
Fixes infinite redirection to Ledger Recover login page
- **Linked resource(s)**: [LIVE-5128](https://ledgerhq.atlassian.net/browse/LIVE-5128)
[LIVE-5128]: https://ledgerhq.atlassian.net/browse/LIVE-5128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: redirections to login page

- .changeset/two-jars-study.md
- apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/Tutorial/index.tsx
- apps/ledger-live-desktop/src/renderer/components/PostOnboardingHub/PostOnboardingActionRow.tsx
- apps/ledger-live-desktop/src/renderer/components/PostOnboardingHub/logic/index.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/CompletionScreen.tsx
- apps/ledger-live-desktop/src/renderer/screens/settings/sections/Experimental/PostOnboardingHubTester.tsx
- apps/ledger-live-mobile/src/actions/settings.ts
- apps/ledger-live-mobile/src/actions/types.ts
- apps/ledger-live-mobile/src/components/PostOnboarding/PostOnboardingActionRow.tsx
- apps/ledger-live-mobile/src/components/PostOnboarding/PostOnboardingEntryPointCard.tsx
- apps/ledger-live-mobile/src/logic/postOnboarding/actions.ts
- apps/ledger-live-mobile/src/logic/postOnboarding/useNavigateToPostOnboardingHubCallback.ts
- apps/ledger-live-mobile/src/reducers/settings.ts
- apps/ledger-live-mobile/src/screens/Onboarding/steps/pairNew.tsx
- apps/ledger-live-mobile/src/screens/PostOnboarding/PostOnboardingDebugScreen.tsx
- apps/ledger-live-mobile/src/screens/PostOnboarding/PostOnboardingHub.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/Configuration/ReadOnlyModeRow.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/Configuration/ResetOnboardingStateRow.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/Configuration/index.tsx
- apps/ledger-live-mobile/src/screens/SyncOnboarding/CompletionScreen.tsx
- libs/ledger-live-common/src/postOnboarding/PostOnboardingProvider.tsx
- libs/ledger-live-common/src/postOnboarding/hooks/useAllPostOnboardingActionsCompleted.ts
- libs/ledger-live-common/src/postOnboarding/hooks/usePostOnboardingEntryPointVisibleOnWallet.ts
- libs/ledger-live-common/src/postOnboarding/hooks/usePostOnboardingHubState.ts
- libs/ledger-live-common/src/postOnboarding/hooks/useStartPostOnboardingCallback.ts
- libs/ledger-live-common/src/postOnboarding/reducer.ts
- libs/ledgerjs/packages/types-live/README.md
- libs/ledgerjs/packages/types-live/src/postOnboarding.ts
Implementation of analytics in the post onboarding, and some refactoring of the post onboarding selectors which were bad because creating a new ref at each update of the store.
also:
- had to implement a way to reset the navigation stack when navigating from the sync onboarding completion screen to the post onboarding
- the way it was done before, we were calling `navigation.reset(/* params to main navigator */)` and right after that calling `navigation.navigate(/* params to post onboarding hub*/)` so the main screen of the app was effectively rendered first (due to navigation.reset)
- I added a way to reset the navigation stack at once when navigating to the post onboarding hub
- implemented a "reset onboarding state" button in the debug settings to allow going back to a "not onboarded …
> FAT-824 LLM Post onboarding analytics

- .changeset/metal-tips-shop.md
- apps/ledger-live-mobile/src/screens/ClaimNft/ClaimNftQrScan.tsx
In the claim NFT flow, at the step of scanning a QR code, there is a logic to redirect the user to the post onboarding hub in case no QR code gets scanned (after 2 minutes).
The issue is that this timeout was cleared when the screen gets unmounted, but not necessarily when the screen is out of focus (which is the case when we navigate to a live app for instance), so the timeout was still running even after a successful scan of the QR code.
- **Impacted projects**: `mobile` 
- **Linked resource(s)**: [FAT-849] 
[FAT-849]: …
> fix(llm claimNft): timeout logic depending on focused state

- apps/ledger-live-mobile/ios/ledgerlivemobile.xcodeproj/project.pbxproj
Only bundle RN code and images on install in xcode
From @juan-cortes 
> It turns the xCode build from minutes to seconds once it's already installed once
> support(ios): only bundle RN code and images on install

- .changeset/cold-scissors-roll.md
- apps/ledger-live-mobile/src/components/WebPlatformPlayer/index.tsx
Prevents default behavior of closing the WebView upon pressing the OS back button.
- **Linked resource(s)**: [LIVE-5131](https://ledgerhq.atlassian.net/browse/LIVE-5131)
[LIVE-5131]: https://ledgerhq.atlassian.net/browse/LIVE-5131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: prevent back from ledger recover webview

- tools/github-bot/src/features/orchestrator/const.ts
- tools/github-bot/src/features/orchestrator/index.ts
Adds a button to refresh the status of forever ongoing jobs.
- **Impacted projects**: `automation`, `ci` 
- **Linked resource(s)**: https://github.com/LedgerHQ/ledger-live-issues/issues/96 
Adds a button to refresh the status in status check page
Be able to refresh a forever ongoing job
> chore(gh-bot): add refresh option

- libs/ledgerjs/script/crypto-assets-importer/importers/erc20-signatures.js
See https://ledgerhq.atlassian.net/wiki/spaces/~623066f962dc1e006801f92c/pages/4071784452/BACK-4796+Ledger+Live+signature+mismatch+for+Go+rli+tokens
> BACK-4796: Prefix testnet token ticker with "t" in transaction config

- .changeset/forty-toes-smell.md
- apps/ledger-live-mobile/src/screens/ReceiveFunds/01-SelectCrypto.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/03a-ConnectDevice.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/03b-VerifyAddress.tsx
An incorrect dependency was causing the code that triggered the user prompt to verify an address to render again whenever the accounts sync'ed in the background. This pr fixes it.
In the process I also addressed https://ledgerhq.atlassian.net/browse/LIVE-5196 which is only available with the feature flag enabled. Feel free to test it too.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/FAT-740` 
No demo
- Do a receive flow
- After confirmation, wait
- There should be no extra prompt
> bugfix: FAT-740 fix user prompt loop on receive flow

- apps/ledger-live-desktop/src/renderer/families/avalanchepchain/Delegation/Header.jsx
- apps/ledger-live-desktop/src/renderer/families/avalanchepchain/Delegation/Row.jsx
- apps/ledger-live-desktop/static/i18n/en/app.json
- libs/ledger-live-common/src/families/avalanchepchain/api/sdk.ts
- libs/ledger-live-common/src/families/avalanchepchain/serialization.ts
- libs/ledger-live-common/src/families/avalanchepchain/types.ts
This PR fixes the user current delegations table.
Avalanche changed the getCurrentValidators endpoint on the node. With that change, that endpoint no longer provides delegations data. With this PR we're instead getting delegations data from the avalanche explorer.
> fix avalanche delegations table

- .changeset/tasty-dodos-remember.md
- apps/ledger-live-mobile/src/context/AuthPass/index.tsx
FaceId prompt results in app becoming inactive. Inactive is only for Incoming calls, multitasking (eg iPad, non applicable for LLM), and FaceID prompts. FaceID prompt is usually less than a minute, so the bug wasn't visible before removing the timeout delay. Now that it's gone, the faceId prompts and related appstate change triggered an app lock. Removed the appstate Inactive from the condition that triggers an app lock, keeping Background appstate (and next state active).
- **Linked resource(s)**: LIVE-6270
N/A
> Fix - LLM - AuthLoop with FaceId

- .changeset/dry-nails-push.md
- apps/ledger-live-mobile/src/screens/CustomImage/Step3Transfer.tsx
New device selection screen was looking a bit skinny and not taking all the width of the screen, this PR stretches it.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/FAT-855` 
> fix: FAT-855 ui bug on new device selector on nft cls flow

- .changeset/red-poets-sneeze.md
- apps/ledger-live-desktop/src/config/transportChannels.ts
- apps/ledger-live-desktop/src/internal/index.js
- apps/ledger-live-desktop/src/internal/transportHandler.ts
- apps/ledger-live-desktop/src/main/internal-lifecycle.js
- apps/ledger-live-desktop/src/renderer/IPCTransport.js
this is a tiny part of https://github.com/LedgerHQ/ledger-live/pull/2721 , this PR can be safely merged, if it's not merged in time it would get by the other PR otherwise.
This restore the feature for experimental users (experimental execution on renderer) that a bulk flow like installing an app would properly be interrupted when user cancel in the middle of the install. This was accidentally reverted when we peer program that feature back in january with @gsoares-ledger  (i managed to find the historical code at https://github.com/LedgerHQ/ledger-live/commit/4f5bc0a46ebdadb7db90cb5d8fa9800e83b9b68d but I must have messed up a push force at the time in https://github.com/LedgerHQ/ledger-live/pull/2342 )
_Please make sure you …
> chore: exchangeBulk unsubscribe support

- .changeset/chilly-pigs-retire.md
- apps/ledger-live-mobile/src/components/BuyDeviceCTA.tsx
- apps/ledger-live-mobile/src/components/SelectDevice2/index.tsx
- apps/ledger-live-mobile/src/screens/Manager/index.tsx
This PR is a small fix for the interaction between the Services widget and the new device selection screen on the My Ledger tab. Instead of putting it below the SelectDevice2 component (which is the entire new device selection screen), I've put it inside id. This way we can display it only in the first step where we list the known devices and it doesn't appear when we're scanning or pairing a new device. There's an extra prop to the SelectDevice2 component in order to control the display of the widgets otherwise it would appear in every SelectDevice2 usage and not only in the MyLedger tab.
- **Linked resource(s)**: [LIVE-6658](https://ledgerhq.atlassian.net/browse/LIVE-6658)
https://user-images.githubusercontent.com/6013294/222677379-d03b84a3-5 …
> Fix services widget location on device selection screen

- .changeset/moody-beers-smile.md
- libs/ledger-live-common/src/apps/polyfill.ts
As Avalanche is part of the Ethereum family, the Ethereum app is a dependency for the Avalanche app.
This PR removes this dependency for Avalanche.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-6273` 
> add Avalanche and Avalanche test in whitelistDependencies

- .github/workflows/bot-staging-explorer-btc.yml
- .github/workflows/bot-staging-explorer-eth.yml
as a general effort to overall reduce the number of bot runs, this moves to a weekly run instead of daily of the staging btc/eth bots.
> chore: only run the staging explorer btc/eth runs 1/week

- libs/ui/packages/native/.storybook/webpack.config.js
Storybook infers the webpack public path from the `homepage` package.json field, which is obviously wrong.
This PR fixes that.
Proof: https://native-ui-storybook-k1tjpfxaw-ledgerhq.vercel.app/?path=/story/cards--full-background-card
- **Impacted projects**: `ui-native` 
- **Linked resource(s)**: [jira](https://ledgerhq.atlassian.net/wiki/spaces/WALLETCO/pages/3959455989/Fix+ledgerhq+native-ui+storybook+deployment) 
N/A
> Fix the @ledgerhq/native-ui storybook

- .changeset/large-pianos-divide.md
- apps/ledger-live-desktop/src/renderer/components/SideDrawer.jsx
The side drawer close button is broken on MacOS because it is in the draggable area of the window. This PR changes this button to allow this to be clickable. 
- **Impacted projects**: Desktop
- **Linked resource(s)**:  https://ledgerhq.atlassian.net/browse/LIVE-6707
https://user-images.githubusercontent.com/119950081/224049987-ec589173-b83d-4161-b2f4-656c250aa63d.mov
> bugfix/lld: fixes side drawer close button

- .github/workflows/test.yml
- apps/ledger-live-desktop/package.json
- apps/ledger-live-desktop/tests/fixtures/common.ts
- pnpm-lock.yaml
Replace deprecated codecov uploader in Github Actions.
A bit more context:
Codecov was barely setup a while ago with no real configuration and thus the output on the PRs might not be that relevant.
This PR does not intend to fix the configuration for now but only to update the uploader of the deprecated tool.
It is provide AS-IS, take the report with a grain of salt.
- **Linked resource(s)**: https://github.com/LedgerHQ/ledger-live-issues/issues/87 
NO DEMO
closes https://github.com/LedgerHQ/ledger-live-issues/issues/87
> chore(codecov): update uploader in CI

- .changeset/twelve-suns-laugh.md
- libs/ledger-live-common/src/platform/helpers.ts
We removed the filtering done with `isPlatformSupportedCurrency` as we want to show all the currencies in the requestAccount drawer of the platform-sdk.
- **Impacted projects**: `ledger-live-desktop` & `ledger-live-mobile` 
- **Linked resource(s)**: [`LIVE-6272`](https://ledgerhq.atlassian.net/browse/LIVE-6272) 
> fix: requestAccount currencies

- .changeset/olive-cherries-occur.md
- apps/ledger-live-mobile/README.md
- apps/ledger-live-mobile/android/app/src/main/java/com/ledger/live/MainActivity.java
- apps/ledger-live-mobile/scripts/android-import.sh
- apps/ledger-live-mobile/src/components/RootNavigator/index.tsx
- apps/ledger-live-mobile/src/index.tsx
We have a method of manipulating data in our app through an environment variable called BRIDGESTREAM_DATA. This allows us to override the data contained in a QR code and import the modified data from the debug menu. We also have a way of launching the app from the command line with specific flags that convert LLD data into bridgestream data. This enables us to access the data at launch.
These methods were developed as improvement tools for development purposes, but they were not widely utilized. The command line method is no longer operational, and we haven't maintained it. Let’s drop the code :axe:
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-6754` 
No impact
> feat: drop importDataString feature from LLM

- .github/workflows/release-prepare-hotfix.yml
- .github/workflows/release-prepare.yml
Since moving away from a service account to a github app to handle all git related tasks in our automation, github apps cannot have `roles` and thus cannot bypass the _required checks_ (branch protection rules) without having admin access to the repo (which we do not want to give).
To prevent the release flow from failing, instead of attempting a merge of the `release` branch on `develop` then pushing, we just create a PR targeting `develop` directly.
- **Impacted projects**: `release` 
Next release flow should happen without a fail when trying to merge to develop, and instead just create a PR
_Pull Requests must …
> chore: prevent release flow failing because of admin rights

- .changeset/smart-eggs-compete.md
- apps/ledger-live-desktop/tests/specs/countervalues/api.spec.ts
- libs/coin-framework/src/env.ts
- libs/ledger-live-common/src/countervalues/react.tsx
We have recent issues regarding the fact we synchronise too often accounts as well as the fact the countervalues API is too much sollicited.
Increasing the delay of recurrent polling should be acceptable tradeoff. from 2mn to 8mn. I also made the "time to consider an account outdated" to be of 10mn, to prevent seeing "Paused" too often.
- **Linked resource(s)**: relates to LIVE-5589 and LIVE-6795 
> chore: slow rate for account incremental sync and countervalues

- libs/coin-polkadot/src/account.ts
cast only once on polkadot formatAccountSpecifics
Cast only once in formatAccountSpecifics method
> style: polkadot formatAccountSpecifics single cast

- .changeset/cold-roses-whisper.md
- apps/ledger-live-mobile/src/components/AssetCentricGraphCard.tsx
- apps/ledger-live-mobile/src/components/CounterValue.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/Generators/GenerateMockAccountsSelect.tsx
- libs/coin-framework/src/mocks/account.ts
In order to test something reported on Slack about some countervalue mishaps for unsupported tokens I improved the account generator to support specifying delisted (or listed) token ids.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-6698` 
https://user-images.githubusercontent.com/4631227/223703354-8278e46e-84f8-4ccc-abb8-ebd53bf18bd3.mov
Choose some token ids and see if the accounts generated respect them, it will only add the tokens if they exist for that currency, but that's common sense. It also addresses https://ledgerhq.atlassian.net/browse/LIVE-6699 which I've added here since it's a PITA to test otherwise.
> feat: live-6698 improve account generator to support delisted tokens

- .changeset/twenty-vans-call.md
- apps/ledger-live-mobile/src/screens/SyncOnboarding/index.tsx
Closing the sync onboarding even though it was finished would take the user back to the initial step. This is because there's a 2.5 second delay in order for the user to acknowledge they've completed the step (I guess). This PR makes the X trigger the navigation early instead of taking the user back to the beginning of the flow.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-6737` 
https://user-images.githubusercontent.com/4631227/224689900-52ff7b6c-97fb-44ac-883e-6f508992ddf9.mov
- Do a sync onboarding
- Reach the step where you have the green “Your device is ready”
- Close the onboarding before the cofetti animation kicks in
- It should go to confetti now, not to the onboarding initial step.
> fix(sync-onboarding): handle X as completion if onboarding is completed

- .changeset/famous-walls-beg.md
- .changeset/sharp-oranges-hammer.md
- .changeset/silly-impalas-turn.md
- .changeset/young-apes-knock.md
- apps/ledger-live-desktop/src/renderer/components/OnboardingAppInstall/AppInstallItem.tsx
- apps/ledger-live-desktop/src/renderer/components/OnboardingAppInstall/InstallSetOfApps.tsx
- apps/ledger-live-desktop/static/i18n/en/app.json
- apps/ledger-live-mobile/src/components/DeviceAction/InstallSetOfApps/Item.tsx
- apps/ledger-live-mobile/src/components/DeviceAction/InstallSetOfApps/index.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/SettingsNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/types/SettingsNavigator.ts
- apps/ledger-live-mobile/src/const/navigation.ts
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Settings/Debug/Features/InstallSetOfApps.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/Features/index.tsx
- libs/env/src/env.ts
- libs/ledger-live-common/src/apps/hw.ts
- libs/ledger-live-common/src/apps/logic.ts
- libs/ledger-live-common/src/apps/runner.ts
- libs/ledger-live-common/src/apps/types.ts
- libs/ledger-live-common/src/hw/actions/app.ts
- libs/ledger-live-common/src/hw/connectApp.ts
The original functionality of inline app installation was tightly coupled to a flow that had a hard dependency on a set of applications. For instance, accessing a swap flow for BTC-ETH would **need** all of the apps installed in order to succeed. However, with the use that we are giving it on the sync onboarding flow this dependency is no longer as strong. 
This step of the onboarding will attempt to install a list of applications that can change between users since it's either something we provide from firebase or a "recover" list of apps from another device the user has interacted with. There is an odd chance that these apps are not available for installation in the newly onboarded device either because they're not developed, or not compatible, or even already installed.
The way inline …
> feat/FAT-793 UX Improvement for install set of apps

- .changeset/light-suns-stare.md
- libs/ledger-live-common/src/hw/installLanguage.ts
- libs/ledger-live-common/src/hw/staxLoadImage.ts
- libs/ledgerjs/packages/errors/src/index.ts
Currently if a device is full and we try to install a language pack the error is an unexpected response from the device, we had no reference to `5102` meaning the device was full in this context. I'm taking a guess that it is and mapping the error accordingly. Also tackles the https://ledgerhq.atlassian.net/browse/LIVE-6830 topic covering CLS on full device, same issue.
- **Impacted projects**: `ledger-live-common errors` 
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-6749` 
https://user-images.githubusercontent.com/4631227/226449251-c90ba04e-e7c5-4b9c-a0dd-9050a67859f1.mov
This can be tested on either LLD or LLM, on a full device, installing a language pack.
> fix: LIVE-6749 Handle the device full case on language pack install

- .changeset/yellow-days-brush.md
- apps/ledger-live-mobile/src/components/SelectDevice/USBEmpty.android.tsx
- apps/ledger-live-mobile/src/components/SelectDevice/index.tsx
- apps/ledger-live-mobile/src/components/SelectDevice2/index.tsx
- apps/ledger-live-mobile/src/live-common-setup.ts
- apps/ledger-live-mobile/src/reducers/ble.ts
- apps/ledger-live-mobile/src/screens/AddAccounts/03-Accounts.tsx
While addressing the original bug reported on https://ledgerhq.atlassian.net/browse/LIVE-6275 I encountered several issues with the USB OTG integration on LLM so while QA'ing this, please take into account the following bugs and topics:
- Duplicated devices when plugging/removing on the legacy device selector.
- Flashing device row on the select list when entering exiting apps in any flow.
- Entering an app breaks the device action on the new device selector (open app BTC, modal closes).
- Text overflow to the right on the empty state for USB on the legacy device selector screen.
- Disconnect during add accounts shows a "Device disconnected" error modal that can't be closed with the X. …
> bugfix(usb-otg): LIVE-6771 multiple fixes to USB OTG on LLM

- .changeset/odd-kangaroos-give.md
- apps/ledger-live-desktop/src/renderer/components/ExportLogsButton.jsx
- apps/ledger-live-mobile/src/components/useExportLogs.tsx
Two minute chore, makes the exported logs readable by default so I can read them on my phone and also open them without having to worry about formatting them. I can also refer to a specific line without needing the other party to have formatted the log the same way my editor did. Longer to write this than implement it.
- **Impacted projects**: `dekstop, mobile` 
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-6856` 
Merge it
> chore: make exported logs formatted by default

- .changeset/brown-worms-perform.md
- apps/ledger-live-mobile/src/components/WebPlatformPlayer/index.tsx
Hide Recover Webview header on PROD env. Also hides it on SIT env (pentes).
- **Impacted projects**: `ledger-live`
- **Linked resource(s)**: [LIVE-6822](https://ledgerhq.atlassian.net/browse/LIVE-6822)
[LIVE-6822]: https://ledgerhq.atlassian.net/browse/LIVE-6822?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Remove recover webview header on prod

- apps/ledger-live-mobile/src/screens/Settings/Debug/Generators/index.tsx
During a recent app refactoring, I encountered a challenge with resetting the application's state. It required either uninstalling the application or manually resetting the settings to their expected values, which was a tedious and time-consuming process. However, by including destructors in the code, we can streamline this process, benefiting both development and quality assurance teams. Destructors allow for the automatic reset of an application's state, reducing the need for manual intervention and saving time during testing cycles. Thus, utilizing destructors can improve the efficiency and accuracy of debugging tools for both development and QA purposes.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-6732` …
> feat: introduce the first set of destructors on debug menu

- apps/ledger-live-desktop/.eslintrc.js
add a rule that prevent 'lodash' to be directly imported
instead, you should use 'lodash/memoize' module import (or whatever function you need)
> LLD: chore: add a rule that prevent 'lodash' to be directly imported

- .changeset/purple-kids-do.md
- libs/ledgerjs/packages/react-native-hw-transport-ble/src/BleTransport.ts
Requesting for a specific MTU when trying to BLE connect was removed in this PR https://github.com/LedgerHQ/ledger-live/pull/2911 because `ConnectionOptions` was commented as "not used" in `react-native-ble-plx` [here](https://github.com/dotintent/react-native-ble-plx/blob/c8af4dba2ec02a822b6ef3bb4199244498b88326/index.d.ts#L168)
It is actually used and needed when connecting to a device.
🚨 Before merging, and after test with QA, check the connection priority (set to high with the `connectOptions`) with the firmware update over BLE PR
- **Impacted projects**: `@ledgerhq/react-native-hw-transport-ble` but also LLM and LLD indirectly
- **Linked resource(s)**: [LIVE-6889](https://ledgerhq.atlassian.net/browse/LIVE-6889?atlOrigin=eyJpIjoiNzUzOGE0OWM3ZDZmNGE5Zjk1YTk0ZmViNDYxOGQ5YTgiLCJwIjoiaiJ9 …
> Bugfix: Live-6889 Request for a specific MTU when trying to BLE connect

- apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/types/BaseNavigator.ts
- apps/ledger-live-mobile/src/const/navigation.ts
- apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx
- apps/ledger-live-mobile/src/screens/Protect/RedirectToOnboardingRecoverFlow.tsx
Adds a redirection for Recover Restore flow when started from the Live app.
- **Linked resource(s)**: [LIVE-6925](https://ledgerhq.atlassian.net/browse/LIVE-6925)
https://user-images.githubusercontent.com/102669540/228615157-829085f1-e07f-4a92-93b5-48777978ccb0.mp4
[LIVE-6925]: https://ledgerhq.atlassian.net/browse/LIVE-6925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: recover restore flow redirection

- .changeset/honest-hounds-cover.md
- apps/ledger-live-mobile/src/components/Web3AppWebview/helpers.ts
- apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx
Recover has an issue when using a deeplink the URL doesn't update correctly
> fix: recover deeplinks

- .changeset/few-kangaroos-press.md
- apps/ledger-live-mobile/services/BackgroundRunnerService.ts
- apps/ledger-live-mobile/tsconfig.json
There was a mismatch on the signature of the action the background runner service was sending and the handling by the Redux store on LLM. This was causing the firmware update over USB OTG to be stuck in the "preparing update" step  on LLM while the update did continue on the device. This wasn't caught by type checks because the `services/` folder wasn't included on the type checks, this PR also adds it to the checks so it doesn't happen again.
- **Linked resource(s)**: [LIVE-6942]
N/A
Test plan: perform any update via USB on LLM. The status displayed on the app should match what's happening on the device.
[LIVE-6942]: https://ledgerhq.atlassian.net/browse/LIVE-6942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …
> fix(Firmware Update LLM): fix LLM stuck on preparing update step

- .changeset/smart-ligers-own.md
- apps/ledger-live-mobile/src/screens/DeviceConnect/index.tsx
As the wallet-api DeviceConnect screen is used in the Onboarding base navigator now, if you pop by getting the parent, you will pop the BaseNavigator
- **Linked resource(s)**: [`PROTECT-1521`](https://ledgerhq.atlassian.net/browse/PROTECT-1521) 
Before:
https://user-images.githubusercontent.com/3009753/229183293-3836d581-1449-463b-8472-3ddaf5e4ee70.mov
After:
The error in the end is expected, what we want is to stay on the live-app
https://user-images.githubusercontent.com/3009753/229181944-c7bfea1e-57b7-4a74-bb0d-01faf9ac9952.mov …
> fix: navigation.pop in DeviceConnect

- apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/helpers.ts
bugfix : "back to Buy/Sell" button should not be displayed because of an internal iframe navigation
Do not change webviewState when event.isMainFrame is false. See https://github.com/electron/electron/issues/6808 and https://www.electronjs.org/docs/latest/api/web-contents#event-did-navigate-in-page
- **Impacted projects**: `` LLD
- 
> fix: "back to Buy/Sell" button should not be displayed because of an internal iframe navigation

- .changeset/rude-guests-drum.md
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/index.tsx
- apps/ledger-live-mobile/src/screens/SyncOnboarding/index.tsx
`r12` firmware updated the flag value from `Ready` to `WelcomeScreen1` once the device is seeded and restarted. This change was made to be consistent with LNS+ and LNX.
- **Impacted projects**: `LLM` and `LLD`
- **Linked resource(s)**: [LIVE-6997](https://ledgerhq.atlassian.net/browse/LIVE-6997)
[LIVE-6997]: https://ledgerhq.atlassian.net/browse/LIVE-6997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: correctly trigger software checks during sync onboarding

- apps/ledger-live-mobile/e2e/bridge/client.ts
- apps/ledger-live-mobile/src/actions/settings.ts
- apps/ledger-live-mobile/src/actions/types.ts
- apps/ledger-live-mobile/src/components/CheckTermOfUseUpdate.tsx
- apps/ledger-live-mobile/src/index.tsx
- apps/ledger-live-mobile/src/logic/terms.tsx
- apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx
- apps/ledger-live-mobile/src/reducers/settings.ts
- apps/ledger-live-mobile/src/reducers/types.ts
- apps/ledger-live-mobile/src/screens/Onboarding/steps/terms.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/welcome.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/Features/TermsOfUse.tsx
Fix a regression in detox tests introduced in https://github.com/LedgerHQ/ledger-live/pull/3014
Used that opportunity to refactor the terms logic to use Redux instead of a bare storage implementation using AsyncStorage that wasn't easy to work with (no shared dynamically updated state easily accessible).
Removed unused code.
> test(detox): fix deeplink tests

- .changeset/heavy-bananas-wash.md
- apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx
Fix the broken hover effect for the retry button on locked device error rendering, this should impact all cases of this error, so onboarding, rename, manager access, etc. And the rendering may differ depending on the context, but it should always be readable.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-5912` 
Make sure the button text is readable.
> bugfix/LIVE-5912 UI fix for the Retry CTA on locked device errors

- .changeset/new-dogs-visit.md
- apps/ledger-live-desktop/src/renderer/screens/manager/DeviceStorage/DeviceName.tsx
- apps/ledger-live-desktop/src/renderer/screens/manager/DeviceStorage/EditDeviceName.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/types/BaseNavigator.ts
- apps/ledger-live-mobile/src/components/RootNavigator/types/BaseOnboardingNavigator.ts
- apps/ledger-live-mobile/src/screens/EditDeviceName.tsx
- apps/ledger-live-mobile/src/screens/Manager/Device/DeviceName.tsx
- apps/ledger-live-mobile/src/screens/Manager/Device/index.tsx
- libs/ledger-live-common/src/hw/editDeviceName.ts
- libs/ledger-live-common/src/hw/getDeviceNameMaxLength.test.ts
- libs/ledger-live-common/src/hw/getDeviceNameMaxLength.ts
Addressing a bug originally reported here https://github.com/LedgerHQ/ledger-live/issues/2987 where the BLE stack actually breaks on the Nano X if we rename a device to anything longer than 17 characters. This is already patched on 2.2.0 so updating the firmware should fix the problem, however, we have thousands of users that can potentially fall in this case and if the only connection mode they have is BLE this can be quite disruptive. 
This PR introduces the limitation of characters based on model and firmware version, falling back to 17 for all cases except LNX >=2.2.0 and any version of Stax.
Fixes https://github.com/LedgerHQ/ledger-live/issues/2987
- **Impacted projects**: `ledger-live-common, ledger-live-desktop, ledger-live-mobile`  …
> bugfix/LIVE-7007 Dynamic max device name length depending on model/fw

- .changeset/fifty-oranges-help.md
- apps/ledger-live-mobile/src/screens/SyncOnboarding/index.tsx
Instead of a complicated logic of navigation to the pairing screen (which causes a navigation loop from which it's impossible to go out of, except with the OS back gestures/buttons), the close button should not assume anything on the general navigation context and just... navigate back?
- **Impacted projects**: `mobile` 
- **Linked resource(s)**: [LIVE-7091] 
- Click “get started” then close LLM
- Scan sync-onboarding QR-code
- Select Stax device on scanning screen
- Close sync-onboarding (click on cross)
- Click back on scanning screen 
**Expected behavior:**
Go back to onboarding first page
**Actual behavior:**
Opens previous device sync-onboarding
https://user-images.githubusercontent.com/91890529/231806116-fc924e2b-2bf6-4e1a-a8e1-344e353cbecb.MP4 …
> LLM [LIVE-7091] fix LLM sync-onboarding close button behavior

- .changeset/seven-pears-poke.md
- apps/ledger-live-mobile/src/components/SelectDevice2/index.tsx
Debug proxy (http) device were blocked on the new device selection component as the bluetooth requirement has been enforced recently.
This little added check fix this issue.
- **Linked resource(s)**: [LIVE-7067](https://ledgerhq.atlassian.net/browse/LIVE-7067)
<details>
<summary>Small demo</summary>
https://user-images.githubusercontent.com/15096913/231480518-ff0d7055-ef45-4d4f-ad1d-2640ce539a8f.mp4
</details>
[LIVE-7067]: https://ledgerhq.atlassian.net/browse/LIVE-7067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …
> Bugfix: LIVE-7067 allow proxy device to bypass BLE requirements

- .changeset/happy-bananas-collect.md
- apps/cli/src/commands/staxFetchAndRestoreDemo.ts
- libs/ledger-live-common/src/hw/actions/staxLoadImage.ts
- libs/ledger-live-common/src/hw/staxLoadImage.ts
On Stax image loading, we have a manual padding that removes two lines of the image in order to make it adapted to the Stax screen. This PR makes this padding optional so we can load an image without it (useful for the case of restoring images recovered from the device, since they'd already include the padding).
N/A
> feat(Custom Lockscreen): Make image padding optional on Stax CLS

- apps/ledger-live-desktop/src/main/window-lifecycle.ts
window open handling is already managed by https://github.com/LedgerHQ/ledger-live/blob/develop/apps/ledger-live-desktop/src/main/index.ts#L135 since Electron 22
**Expected:** a link from a live app still opens on a browser as before.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-7110 
> chore(LLD): remove minor dead code

- .github/workflow-templates/bot-coin-family.yml
- .github/workflows/bot-carbon.yml
- .github/workflows/bot-mere-denis.yml
- .github/workflows/bot-mooncake.yml
- .github/workflows/bot-nitrogen.yml
- .github/workflows/bot-nonreg-carbon.yml
- .github/workflows/bot-nonreg-mooncake.yml
- .github/workflows/bot-nonreg-nitrogen.yml
- .github/workflows/bot-nonreg-oxygen.yml
- .github/workflows/bot-nonreg-silicium.yml
- .github/workflows/bot-oxygen.yml
- .github/workflows/bot-phosphore.yml
- .github/workflows/bot-portfolio-report.yml
- .github/workflows/bot-silicium.yml
- .github/workflows/bot-staging-explorer-btc.yml
- .github/workflows/bot-staging-explorer-eth.yml
- .github/workflows/bot-transfer.yml
- .github/workflows/sync.yml
- tools/actions/turbo-affected/src/main.ts
- tools/github-bot/src/features/orchestrator/index.ts
As a way to strengthen our security, we want to sunset our old github ledgerlive service account in favor of the github app we now use.
This PR aims to remove any calls / references to the github user and any of it's access token.
- **Impacted projects**: `repository` 
- **Linked resource(s)**: https://github.com/LedgerHQ/ledger-live-issues/issues/92 
no demo
Will run a bot test to see if the github app token can successfully checkout the needed repositories.
> chore: remove instances of service account token

- .changeset/early-baboons-fly.md
- apps/ledger-live-desktop/src/renderer/screens/dashboard/FeaturedButtons.tsx
Added `page: "portfolio"` property to Stake/Buy/Swap portfolio buttons so they can be tracked in mixpanel/segment
- **Impacted projects**: `LLD
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-7002
> bugfix/LL-7002 Portfolio Page Analytics fix

- .changeset/tender-items-watch.md
- libs/ledger-live-common/src/api/Ethereum.test.ts
- libs/ledger-live-common/src/api/Ethereum.ts
Fixing incremental sync fetching previous transactions to a block instead of the subsequent ones.
See explorer swagger explaining it here: https://explorers.api.live.ledger.com/blockchain/v4/eth/docs/#/address/Transactions%20by%20address
- **Impacted projects**: `@ledgerhq/live-common` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-7167 
https://user-images.githubusercontent.com/44363395/233385678-9b003ae4-9ced-476c-9b9d-e2171f51ba23.mp4
> [LIVE-7167] Bugfix - Change incremental sync order for Ethereum family explorers

- apps/ledger-live-desktop/src/renderer/hooks/useDeeplinking.ts
- apps/ledger-live-desktop/src/renderer/screens/exchange/index.tsx
- apps/ledger-live-mobile/src/screens/PTX/BuyAndSell/index.tsx
In LLM / LLD, allow deeplink query params to go to the buy application. This feature will be used in the binance buy integration : the binance sso is made in the browser, then redirects back to binance page in buy section thanks to this deeplink - query params contain authentication state. See related PR in buy application.
- **Impacted projects**: `LLM, LLD` 
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-6743`
> feat: pass buy deeplink query params to the buy application (LIVE-6743)

- .changeset/brown-hairs-count.md
- libs/ledger-live-common/src/hw/staxLoadImage.ts
The recent refactoring of device actions broke the optional padding parameter for loading stax custom lock screens resulting in skewed/distorted images when loading from LLD/LLM. This brings back the default parameter.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-7184` 
No demo
Change CLS on LLM/LLD see if it's not broken.
> fix: LIVE-7184 stax load image pad regression

- .changeset/warm-dancers-return.md
- apps/ledger-live-mobile/src/families/celo/accountActions.tsx
- apps/ledger-live-mobile/src/families/cosmos/accountActions.tsx
- apps/ledger-live-mobile/src/families/elrond/accountActions.tsx
- apps/ledger-live-mobile/src/families/ethereum/accountActions.tsx
- apps/ledger-live-mobile/src/families/near/accountActions.tsx
- apps/ledger-live-mobile/src/families/polkadot/accountActions.tsx
- apps/ledger-live-mobile/src/families/solana/accountActions.tsx
- apps/ledger-live-mobile/src/families/tezos/accountActions.tsx
- Changed `token` to `currency` in LLM Account staking button analytics
- Fix Tezos string
- **Impacted projects**: LLM account staking analytics
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-7066
> bugfix/LL-7066 Fix LLM account staking analytics 

- .changeset/violet-cameras-wonder.md
- apps/ledger-live-desktop/src/renderer/screens/earn/index.tsx
Add currencyTicker to query params passed to EARN dashboard webview component in order for EARN to display values in the same currency as that set in ledger live desktop.
- **Impacted projects**: ledger-live-desktop
- **Linked resource(s)**: LIVE-6884
> Feat/live 6884/currency settings earn

- .changeset/shiny-mice-try.md
- apps/ledger-live-mobile/src/screens/Manager/index.tsx
In the Manager: both the old (SelectDevice) and new (SelectDevice2)
device selection components handle the bluetooth requirements with a hook + bottom drawer.
The fix gives back the responsibilities to those select components to check for
the bluetooth requirements and avoids a duplicated error drawers/messages.
The only drawback: the user has to select again their device once the bluetooth
requirements are respected.
- **Linked resource(s)**:  [LIVE-7226](https://ledgerhq.atlassian.net/browse/LIVE-7226)
<details>
<summary>Quick demo</summary>
You can see that the BLE requirements issue is handled by a "new" drawer and not directly in the drawer that was displaying the device action
https://user-images.githubusercontent.com/15096913/234520406-45b28ce4-015f-47 …
> Bugfix/LIVE-7226: fix possible duplicated BLEerror messages on the Manager

- .changeset/pink-knives-grab.md
- libs/ledger-live-common/src/families/cosmos/js-prepareTransaction.ts
Fix onomy redelegate (add delegation amount to lru cache deps)
- **Impacted projects**: `LLC,LLD,LLM` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-7329 
> fix: onomy redelegate by adding new dep to lru cache (delegation amount)

- .changeset/popular-nails-laugh.md
- libs/ledgerjs/packages/react-native-hw-transport-ble/src/remapErrors.ts
Fix the remapping of errors in the React Native BLE Transport. Due to a recent change in the remapping code, the "was disconnected" and "not found" type of errors were not being correctly remapped into the DisconnectedDevice error class. 
This PR fixes this issue.
- **Impacted projects**: `ledgerjs/react-native-hw-transport-ble`
- **Linked resource(s)**: None
N/A
> fix(React Native BLE Transport): fix remapping of disconnected device ble errors

- .changeset/smooth-cooks-sort.md
- libs/ledger-live-common/src/apps/inlineAppInstall.ts
Due to some refactorings done on the device actions the inline app install events stopped being throttled. This was a regression since it slowed down the UI during inline app installs. This PR adds back a throttle to those events.
N/A
> fix(Ledger Live Common): throttle events coming on inline app installs

- .changeset/lovely-baboons-bathe.md
- apps/ledger-live-desktop/src/renderer/experimental.tsx
- apps/ledger-live-desktop/static/i18n/en/app.json
- apps/ledger-live-mobile/src/experimental.ts
- apps/ledger-live-mobile/src/locales/en/common.json
- libs/env/src/env.ts
- libs/ledger-live-common/src/families/bitcoin/wallet-btc/explorer/index.ts
- libs/ledger-live-common/src/families/stellar/api/horizon.ts
- libs/ledger-live-common/src/network.ts
Restore full network logs under env var + exp setting to help debugging and investigation issues, including in production.
Most of it is a revert of [this PR](https://github.com/LedgerHQ/ledger-live/pull/2419)
- **Impacted projects**: `LLC LLM LLD`
- **Linked resource(s)**: [LIVE-6970](https://ledgerhq.atlassian.net/browse/LIVE-6970)
[LIVE-6970]: https://ledgerhq.atlassian.net/browse/LIVE-6970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIVE-6970] Restore full network logs under env var + exp setting

- apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/types/BaseNavigator.ts
- apps/ledger-live-mobile/src/const/navigation.ts
- apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx
- apps/ledger-live-mobile/src/screens/BleDevicePairingFlow/index.tsx
- apps/ledger-live-mobile/src/screens/Protect/RedirectToRecoverStaxFlow.tsx
Adds the configuration for Stax's recovery with Recover.
NOTE: since I own no Stax, I changed the config to filter NanoX for the demo.
- **Linked resource(s)**: [PROTECT-1734](https://ledgerhq.atlassian.net/browse/PROTECT-1734)
https://user-images.githubusercontent.com/102669540/232054825-03f3251d-58f1-4966-ab3a-f5987c0fec4a.mp4
[PROTECT-1734]: https://ledgerhq.atlassian.net/browse/PROTECT-1734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: deeplink for stax restore with recover

- .changeset/witty-plants-clap.md
- apps/ledger-live-mobile/src/screens/EditDeviceName.tsx
- apps/ledger-live-mobile/src/screens/Manager/Device/DeviceName.tsx
[LIVE-7388]: Fix device name text wrapping issue in My Ledger
[LIVE-7386]: Fix device renaming input focusing issue on iOS by implementing a custom auto focus/blur logic: the input now gets blurred automatically when the modal appears which avoids the glitch that was found.
- **Linked resource(s)**: [LIVE-7388], [LIVE-7386] 
- For [LIVE-7388] (text wrapping issue):
- Before (the edit button is pushed beyond the padding zone):
- After (text is properly wrapped):
- For [LIVE-7386]: (input/keyboard glitch)
https://github.com/LedgerHQ/ledger-live/assets/91890529/1f6a2a6d-6477-40ff-85c7-75b835c43611
_Pull Requests must …
> Bugfix/live 7388 llm device name UI

- apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/SelectUseCase/index.tsx
Opens Recover's modal previously added to the main sidebar when selecting `Restore using Ledger Recover` in the onboarding with a device other than NanoX.
- **Linked resource(s)**: [PROTECT-1716](https://ledgerhq.atlassian.net/browse/PROTECT-1716)
https://user-images.githubusercontent.com/102669540/234521310-db306c5a-db0d-4bdd-acd7-17d52a3fc6d9.mov
[PROTECT-1716]: https://ledgerhq.atlassian.net/browse/PROTECT-1716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: lld recover only on lnx modal

- .changeset/empty-tigers-whisper.md
- .changeset/long-falcons-film.md
- .changeset/moody-hats-lick.md
- .changeset/swift-camels-exist.md
- apps/cli/src/commands-index.ts
- apps/cli/src/commands/staxRemoveImage.ts
- apps/ledger-live-desktop/src/renderer/components/DeviceAction/index.tsx
- apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx
- apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/index.tsx
- apps/ledger-live-desktop/src/renderer/screens/manager/DeviceStorage/CustomImageManagerButton.tsx
- apps/ledger-live-desktop/src/renderer/screens/manager/DeviceStorage/EditDeviceName.tsx
- apps/ledger-live-desktop/src/renderer/screens/manager/DeviceStorage/RemoveCustomImage.tsx
- apps/ledger-live-desktop/static/i18n/en/app.json
- apps/ledger-live-mobile/src/components/CustomImage/CustomImageBottomModal.tsx
- apps/ledger-live-mobile/src/components/DeviceAction/index.tsx
- apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Manager/Device/CustomLockScreen.tsx
- libs/ledger-live-common/src/hw/actions/staxRemoveImage.ts
- libs/ledger-live-common/src/hw/staxRemoveImage.test.ts
- libs/ledger-live-common/src/hw/staxRemoveImage.ts
Introduces the functionality of removing a custom lock screen from a device for both LLM and LLD.
The UI will be aligned with the rework from https://github.com/LedgerHQ/ledger-live/pull/3314 once it's merged.
- **Impacted projects**: `ledger-live-mobile, ledger-live-desktop, live-common` 
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-6570` 
No demo
Be able to remove a CLS that's been set on both LLM and LLD.
> feat/LIVE-6570 Custom lockscreen removal feature for Stax

- .changeset/afraid-seals-design.md
- apps/ledger-live-mobile/src/screens/PairDevices/index.tsx
Historically errors on the pairing screen were being manually reported to Sentry (since around when Sentry reporting was introduced 4 years ago). However, this pollutes our error monitoring and impacts our Sentry usage quota. Since these are errors for which we have no control over as they can stem from user behaviour (e.g. user denied the pairing on the device), it's better to remove this reporting and use Sentry mainly for uncaught errors and crashes.
N/A
> fix(Device Pairing Screen): remove unnecessary manual sentry reporting

- .changeset/fuzzy-experts-kneel.md
- .changeset/gentle-spiders-promise.md
- apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/FirmwareUpdate/index.tsx
- apps/ledger-live-mobile/src/screens/FirmwareUpdate/useUpdateFirmwareAndRestoreSettings.ts
- apps/ledger-live-mobile/src/screens/Manager/Manager.tsx
- libs/ledger-live-common/src/apps/logic.ts
- libs/ledger-live-common/src/apps/react.ts
- libs/ledger-live-common/src/apps/types.ts
- libs/ledger-live-common/src/deviceSDK/actions/updateFirmware.ts
- libs/ledger-live-common/src/deviceSDK/tasks/core.ts
- libs/ledger-live-common/src/hw/actions/app.ts
- libs/ledger-live-common/src/hw/actions/installLanguage.ts
- libs/ledger-live-common/src/hw/actions/manager.ts
- libs/ledger-live-common/src/hw/actions/staxFetchImage.ts
- libs/ledger-live-common/src/hw/actions/staxLoadImage.ts
This PR adds the last step of the new firmware update UX: the restoration of the previously installed apps. Besides that it makes a few improvements on the entirety of the flow such as properly detecting when a device is locked and allowing the users to retry a specific step.
- **Impacted projects**: `ledger-live-mobile`, `ledger-live-common`
- **Linked resource(s)**: [LIVE-6306]
tbd
[LIVE-6306]: https://ledgerhq.atlassian.net/browse/LIVE-6306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(Firmware Update LLM): add restore of apps after firmware update

- .changeset/fuzzy-experts-kneel.md
- .changeset/gentle-spiders-promise.md
- .changeset/kind-melons-tan.md
- .changeset/seven-grapes-own.md
- apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/FirmwareUpdate/index.tsx
- apps/ledger-live-mobile/src/screens/FirmwareUpdate/useUpdateFirmwareAndRestoreSettings.ts
- apps/ledger-live-mobile/src/screens/Manager/Manager.tsx
- libs/ledger-live-common/src/apps/logic.ts
- libs/ledger-live-common/src/apps/react.ts
- libs/ledger-live-common/src/apps/types.ts
- libs/ledger-live-common/src/deviceSDK/actions/updateFirmware.ts
- libs/ledger-live-common/src/deviceSDK/tasks/core.ts
- libs/ledger-live-common/src/deviceSDK/tasks/getDeviceInfo.ts
- libs/ledger-live-common/src/deviceSDK/tasks/updateFirmware.ts
- libs/ledger-live-common/src/hw/actions/app.ts
- libs/ledger-live-common/src/hw/actions/installLanguage.ts
- libs/ledger-live-common/src/hw/actions/manager.ts
- libs/ledger-live-common/src/hw/actions/staxFetchImage.ts
- libs/ledger-live-common/src/hw/actions/staxLoadImage.ts
This PR adds an extra step to the firmware update on LLM. This extra step is responsible for restoring any previously installed language pack to the device after the update. It follows the same pattern that was implemented by the restoration of lockscreen image. (https://github.com/LedgerHQ/ledger-live/pull/3100)
- **Impacted projects**: `ledger-live-mobile`, `ledger-live-common`
- **Linked resource(s)**: [LIVE-6308]
https://user-images.githubusercontent.com/6013294/233604209-ff31655d-3a8a-43b0-8cfa-e45fb662e24b.mp4
[LIVE-6308]: https://ledgerhq.atlassian.net/browse/LIVE-6308?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(Firmware Update LLM): implement language restore logic on fw update

- .changeset/fuzzy-experts-kneel.md
- .changeset/gentle-queens-hope.md
- .changeset/gentle-spiders-promise.md
- .changeset/kind-melons-tan.md
- .changeset/new-radios-tap.md
- .changeset/seven-grapes-own.md
- .changeset/silly-olives-tan.md
- apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/FirmwareUpdate/index.tsx
- apps/ledger-live-mobile/src/screens/FirmwareUpdate/useUpdateFirmwareAndRestoreSettings.ts
- apps/ledger-live-mobile/src/screens/Manager/Manager.tsx
- libs/ledger-live-common/src/apps/logic.ts
- libs/ledger-live-common/src/apps/react.ts
- libs/ledger-live-common/src/apps/types.ts
- libs/ledger-live-common/src/deviceSDK/actions/updateFirmware.ts
- libs/ledger-live-common/src/deviceSDK/tasks/core.ts
- libs/ledger-live-common/src/deviceSDK/tasks/getDeviceInfo.ts
- libs/ledger-live-common/src/deviceSDK/tasks/updateFirmware.ts
- libs/ledger-live-common/src/hw/actions/app.ts
- libs/ledger-live-common/src/hw/actions/installLanguage.ts
- libs/ledger-live-common/src/hw/actions/manager.ts
- libs/ledger-live-common/src/hw/actions/staxFetchImage.ts
- libs/ledger-live-common/src/hw/actions/staxLoadImage.ts
- libs/ui/packages/native/src/components/Layout/List/VerticalStepper/index.tsx
- libs/ui/packages/native/src/components/Layout/List/index.ts
- libs/ui/packages/native/storybook/stories/Layout/List/VerticalStepper.stories.tsx
- libs/ui/packages/native/storybook/stories/Layout/List/VerticalTimeline.stories.tsx
This PR adds an extra step at the beginning and at the end of the new firmware update (implemented on https://github.com/LedgerHQ/ledger-live/pull/2977). 
In case the device being update is a Stax, we back up the custom lock screen image before launching the update and after the update is finished we trigger the load of the image back to the device.
- **Linked resource(s)**: [LIVE-6309]
https://user-images.githubusercontent.com/6013294/228571273-e8ccb75a-7d17-4e3a-bae3-49221ffec95d.mp4
[LIVE-6309]: https://ledgerhq.atlassian.net/browse/LIVE-6309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-6309: Backup and restore Stax background image on firmware update

- .changeset/two-flies-double.md
- apps/ledger-live-mobile/src/components/DeviceAction/index.tsx
- apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx
- apps/ledger-live-mobile/src/screens/Swap/Form/Modal/Confirmation.tsx
For the sake of this task, the only thing that we need to check is that upon selecting a device from the device selection screen, during the Loading step or any other step that is not blocking, we should still see the X on the top right and be allowed to dismiss the modal. A regression introduced a few months ago meant that we had to wait until a timeout error in order to close the modal, leading to a sub-par user experience if they chose the wrong device.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-7435` 
https://github.com/LedgerHQ/ledger-live/assets/4631227/2f278717-7f45-4b64-8650-1aed319606dd
The easiest way to test this is to follow what the video does, select a device that is not available and see if you can …
> fix: allow closing device action modals when no blocking action

- .changeset/curly-bottles-pump.md
- apps/ledger-live-mobile/src/screens/Manager/ProviderWarning.tsx
When you have either an odd provider or developer mode enabled on LLM it should be showing the warning while inside My Ledger. In the first implementation which I hastily merged, I was only showing the banner if the provider was not 1. Meaning that in the specific case of the provider being 1, but the developer mode being ON, there would be no warning. This PR addresses that.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-7301` 
Testing with any combination of the settings should match the expected screenshots.
> fix: correct logic for showing the provider warning ui on LLM

- .changeset/olive-planes-behave.md
- apps/ledger-live-mobile/src/screens/Manager/AppsScreen.tsx
- apps/ledger-live-mobile/src/screens/Manager/Device/DeviceAppStorage.tsx
- apps/ledger-live-mobile/src/screens/Manager/Device/StorageBarItem.tsx
- apps/ledger-live-mobile/src/screens/Manager/Device/index.tsx
The storage bar inside My Ledger for LLM was not reflecting the optimistic state (result of queued installs/uninstalls) like it happens on LLD. This PR introduces that behaviour as well as the nifty animation used on LLD to convey something is happening. 
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-6476` 
https://github.com/LedgerHQ/ledger-live/assets/4631227/2cca972d-b47b-4745-ad82-67764fd1fa15
For a little bit more context, the _state_ of the data when we enter My Ledger is calculated by querying the device for what it has inside, getting what's available in the selected provider, and computing all of that to reflect it on a storage bar so we know how much space is available, what can fit and what can't, etc. 
On …
> feat: live-6476 bring the optimistic storage bar to LLM

- .changeset/purple-peaches-tell.md
- apps/ledger-live-desktop/src/renderer/screens/manager/DeviceStorage/EditDeviceName.tsx
Just removing a duplicate footer in the rename device drawer on LLD (which was the result of a mistake in a conflict resolution I guess?)
- **Linked resource(s)**: [LIVE-7138] 
[LIVE-7138]: https://ledgerhq.atlassian.net/browse/LIVE-7138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(lld/EditDeviceName): remove superfluous footer

- .changeset/eight-colts-double.md
- apps/ledger-live-desktop/src/config/urls.ts
- apps/ledger-live-desktop/src/renderer/components/ExportLogsButton.tsx
- apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/NetworkError.tsx
- apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/WalletAPIWebview.tsx
- apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/helpers.ts
- apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/types.ts
- apps/ledger-live-desktop/src/renderer/icons/ErrorNoBorder.tsx
- apps/ledger-live-desktop/static/i18n/en/app.json
Adds an error handler and error screen for webview when the external web application fails to load properly.  When try again is pressed it imperatively refreshes the webview via its ref.
- **Impacted projects**: `PTX`
- **Linked resource(s)**: `LIVE-7063` 
> feat: add network error component and error fallback for webview

- .changeset/fluffy-rockets-reply.md
- apps/ledger-live-mobile/src/components/GenericErrorView.tsx
- apps/ledger-live-mobile/src/components/Web3AppWebview/NetworkError.tsx
- apps/ledger-live-mobile/src/components/Web3AppWebview/WalletAPIWebview.tsx
- apps/ledger-live-mobile/src/config/urls.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
Adds a network error view to WebPTXPlayer on it's `renderError` prop that allows for a refresh if there are issues caused by network failure. 
- **Impacted projects**: `Ledger live mobile` 
- **Linked resource(s)**: `LIVE-7065` 
> feat: add network error screen

- libs/domain-service/src/__tests__/unit/hooks/logic.unit.test.ts
- libs/domain-service/src/hooks/index.tsx
- libs/domain-service/src/index.ts
- libs/domain-service/src/resolvers/index.ts
- libs/domain-service/src/signers/index.ts
- libs/domain-service/src/tools/index.ts
This PR is adding some special comments to specify to [istanbul](https://istanbul.js.org/) to not take into account some files in the code coverage to prevent some false negative stats.
Full documentation about those specials comments can be found here: https://github.com/gotwarlost/istanbul/blob/master/ignoring-code-for-coverage.md
Command use for coverage: `pnpm domain test -- --coverage --coverage-reporters=lcov --collectCoverageFrom="src/**/*.{ts,tsx}" --coverageDirectory ~/Downloads/domain`
- **Impacted projects**: `@ledgerhq/domain-service` 
Before:
After:
_Pull Requests must pass the CI and be internally …
> Support - Add special comments to ignore istanbul coverage for useless files

- apps/ledger-live-mobile/src/components/NavigationHeaderCloseButton.tsx
- apps/ledger-live-mobile/src/components/WebPTXPlayer/index.tsx
PTX is moving away from iFrames and to WebViews for Providers, on testing our branch we noticed the close button in LLM no longer works as expected on iOS only. To reproduce please use [preview](https://buy-sell-live-app.vercel.app/)
@valpinkman & @elbywan your [LLM TS Migration PR](https://github.com/LedgerHQ/ledger-live/commit/33d10843424e3ff1e6a4d5fe208e72cfdd499b57#) seems to have touched [these lines](https://github.com/LedgerHQ/ledger-live/commit/33d10843424e3ff1e6a4d5fe208e72cfdd499b57#diff-01381f65e110bad68d8d7242631bc9b426acf61c26459f2e8168e34751acdcf9L43-R51), hoping you could review this fix.
- **Impacted projects**: `PTX`
- **Linked resource(s)**: Closes https://ledgerhq.atlassian.net/browse/LIVE-7471 …
> fix: close button to work in buy & sell app

- .changeset/swift-apples-hope.md
- apps/ledger-live-mobile/src/components/WebRecoverPlayer/index.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Onboarding/steps/welcome.tsx
Adds a CTA in LLM Welcome screen to sign-in to Recover. This button will open Recover and pass a query param `shouldBypassLLOnboarding=true`. After a successful sign-in, Recover will add a query param `bypassOnboarding=true` to its URL. A watcher will intercept this param and will set the onboarding to completed.
- **Linked resource(s)**: [PROTECT-1726](https://ledgerhq.atlassian.net/browse/PROTECT-1726)
https://github.com/LedgerHQ/ledger-live/assets/102669540/fe756ee2-07c7-4c95-a9d6-ac5e486ac29e
[PROTECT-1726]: …
> feat: recover login cta in llm welcome screen

- .changeset/olive-dragons-wink.md
- libs/ledger-live-common/src/families/stellar/bridge.integration.test.ts
- libs/ledger-live-common/src/families/stellar/logic.ts
- libs/ledger-live-common/src/families/stellar/tokens.ts
> Buying liabilities equal the total amount of the asset offered to buy aggregated over all offers owned by an account, and selling liabilities equal the total amount of the asset offered to sell aggregated over all offers owned by an account.
https://developers.stellar.org/docs/fundamentals-and-concepts/stellar-data-structures/accounts#trustlines
We need to subtract the selling liabilities from the balance when calculating the spendable balance, instead of the buying liabilities.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-7352 
_Pull Requests must pass the CI and be internally …
> fix(live-common): fix the calculation of spendable balance in Stellar accounts.

- .changeset/spicy-cats-rest.md
- libs/ledger-live-common/src/apps/support.test.ts
- libs/ledger-live-common/src/apps/support.ts
…versions pre-release tags
This PR fixes my own mess where I removed the `includePrerelease` option (that I previously added...) thinking it wasn't used when we added the last `-0` to the minimum semver required, but that `-0` is only working for the minimum version, not higher versions.
TLDR: 
- with ">= 1.10.2-0" only -> `1.10.2-dev` is ok but not `1.10.3-dev`
- with  `includePrerelease` true only -> `1.10.3-dev` is ok but not `1.10.2-dev`
> Bugfix - Allow pre-pelease tags for higher versions of nano apps than the minimum one

- .changeset/strange-peaches-leave.md
- apps/ledger-live-mobile/src/components/Web3AppWebview/PlatformAPIWebview.tsx
Fixes binancecnt authentication through binance.com on iOS :
Selectively set javaScriptCanOpenWindowsAutomatically to true only for multibuy and binancecnt apps, and only on platform sdk webview. We may decide later to extend the solution or not.
- **Impacted projects**: `` LLM iOS : multibuy, binance live app
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-7646
> fix: allow navigation to binance.com for login (LIVE-7646)

- .changeset/plenty-stingrays-trade.md
- apps/ledger-live-mobile/src/screens/Manager/Device/CustomLockScreen.tsx
- apps/ledger-live-mobile/src/screens/Manager/Device/DeviceLanguage.tsx
- apps/ledger-live-mobile/src/screens/Manager/Device/DeviceName.tsx
- apps/ledger-live-mobile/src/screens/Manager/Device/index.tsx
When there are ongoing app operations inside My Ledger, we should disable access to other flows (CLS, Language, Rename) and show it in the UI so that it's evident.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-6329` 
- Access My Ledger with a device that can handle CLS/Lang/Rename
- Start an app operation (ie install Bitcoin)
- Make sure that the flows are disabled.
> feat: LIVE-6329 add visual indicator of disabled CTA while app ops

- .changeset/clever-dolls-lie.md
- apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/steps/01-step-prepare.tsx
Fix overflow of the fw update verification hash for old firmware update flows.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-7523` 
Follow a firmware update of an old path (1.4.2 on lns for instance) check that the identifier doesn't overflow. Depending on the version there may be some ellipsis, some multi-line, etc. It should match what the device shows in any case.
> fix: bad rendering of hash verification on old fw update step

- .changeset/cold-badgers-live.md
- apps/ledger-live-desktop/src/renderer/components/DeviceAction/index.tsx
- apps/ledger-live-desktop/src/renderer/components/ErrorIcon.tsx
- apps/ledger-live-desktop/src/renderer/screens/manager/DeviceStorage/RemoveCustomImage.tsx
- apps/ledger-live-desktop/static/i18n/en/app.json
- apps/ledger-live-mobile/src/components/CustomImage/CustomImageBottomModal.tsx
- apps/ledger-live-mobile/src/components/DeviceAction/index.tsx
- apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx
- apps/ledger-live-mobile/src/components/GenericErrorView.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- libs/ledger-live-common/src/hw/staxRemoveImage.test.ts
- libs/ledger-live-common/src/hw/staxRemoveImage.ts
The initial implementation of the image removal for the Stax device had an edge case where the user may delete the image on the device and then attempt to remove it again on Live. While tackling it I aligned the UI/UX of the flow to match the other flows that were adapted recently (rename, languages and CLS) trying to follow the same spacing, sizes, and behaviour.
- **Impacted projects**: `ledger-live-desktop, ledger-live-mobile` 
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-7292` 
No demo
- Launch LLD/LLD
- Access My Ledger with a Stax device
- Set up a custom lock screen
- Remove the image on Stax device by following the `settings/lockscreen/customize/remove` route
- Attempt to remove the custom lockscreen (Already removed) from the option on My ledger
It is …
> feat/LIVE-7292 Improvements to the removal of CLS on Stax

- .changeset/silly-planes-develop.md
- libs/ledger-live-common/src/wallet-api/react.ts
Fix an encoding issue that would over hex encode anything signed trough the wallet api
- **Impacted projects**: `` eth-dapp-browser
Message signature done in the wallet-api-tools should be correct
> fixed hex encoding issue on sign flow

- .changeset/eight-garlics-reflect.md
- apps/ledger-live-mobile/e2e/models/nft/nftViewerPage.ts
- apps/ledger-live-mobile/e2e/models/wallet/nftGalleryPage.ts
- apps/ledger-live-mobile/e2e/models/wallet/walletTabNavigator.ts
- apps/ledger-live-mobile/e2e/specs/nftGallery.spec.ts
- apps/ledger-live-mobile/src/components/Nft/NftGallery/NftList.tsx
- apps/ledger-live-mobile/src/screens/Nft/NftGallery/NftGalleryEmptyState.tsx
- apps/ledger-live-mobile/src/screens/Nft/WalletNftGallery/index.tsx
Added some more Detox tests to validate the hide NFT flow in the NFT gallery and check the empty state renders.
- **Linked resource(s)**: `LIVE-4142` 
https://github.com/LedgerHQ/ledger-live/assets/1044686/0a24c82b-0640-4c2d-b18b-4272be534088
> test: NFT gallery hide and empty state Detox tests

- apps/ledger-live-mobile/README.md
The current link to docs for ledger cli do not work. 
- Replace broken url with https://developers.ledger.com/docs/coin/ledger-live-cli/ 
- replace suggested cli command with `pnpm run:cli proxy`, which does work
- internal developers
- N/A
> chore: fix ledger cli README instructions

- libs/ledger-live-common/src/countervalues/logic.ts
- libs/ledger-live-common/src/countervalues/react.test.ts
- libs/ledger-live-common/src/countervalues/react.tsx
provide a faster implementation of useTrackingPairForAccounts.
this logic runs to determine what are the pairs to use with countervalues api. 
in the hook, we have two level of memo optimisation: a first level only calculate `inferTrackingPairForAccounts` when accounts and countervalue changes. however, it wasn't enough because accounts can change a lot, like every resync, and we then did a second level of optimisation using a hash that determines where the countervalues are likely to really change (which is most of the time never: unless you add/remove new accounts, there are still same countervalues to fetch), however we were probably not very efficient of that optimisation which likely have the reverse effect of what we try to optimise here.
- AFTER: we can only calculate the "hash" do …
> optimize useTrackingPairForAccounts

- .changeset/young-tigers-bake.md
- libs/ledger-live-common/src/hw/actions/initSwap.ts
Addresses a regression that was introduced in the firmware update rework, the whole swap request dependency is very old code and it was bound to break eventually. This memoizes the request and should prevent the loop.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-7722` 
- Assets **should be swappable**.
- That's basically it, if you can reach the swap confirmation step, the bug is solved.
- If you see a loading step and nothing happens, it's probably eating up your memory and won't do anything.
> fix: prevent endless loop in swap flows

- .changeset/young-tigers-bake.md
- libs/ledger-live-common/src/hw/actions/initSwap.ts
Addresses a regression that was introduced in the firmware update rework, the whole swap request dependency is very old code and it was bound to break eventually. This memoizes the request and should prevent the loop.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-7722` 
- Assets **should be swappable**.
- That's basically it, if you can reach the swap confirmation step, the bug is solved.
- If you see a loading step and nothing happens, it's probably eating up your memory and won't do anything.
> fix: prevent endless loop in swap flows  (to develop)

- .changeset/fast-hornets-flash.md
- apps/ledger-live-mobile/src/screens/RequestAccount/02-SelectAccount.tsx
This PR is to revert regression found in https://github.com/LedgerHQ/ledger-live/pull/3526/files#r1221273156, which resulted in the error message `'JSON-RPC method account.request responded an error', [Error: Request account interrupted by user]`.
I have QA'ed that stake and buy both work post reverting.
- **Impacted projects**: Closes https://ledgerhq.atlassian.net/browse/LIVE-7772
> fix: regression on select account on success

- .changeset/eighty-zebras-build.md
- apps/ledger-live-mobile/src/screens/DeviceConnect/index.tsx
- apps/ledger-live-mobile/src/screens/Platform/exchange/CompleteExchange.tsx
- apps/ledger-live-mobile/src/screens/Platform/exchange/StartExchange.tsx
- apps/ledger-live-mobile/src/screens/SignTransaction/02-ConnectDevice.tsx
The recent refactor in device action implementation meant that rerenders of the screen that renders the `DeviceAction` component would trigger a new execution of the action itself **if the request was set inline**, if we memoize the request this doesn't happen.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-7728` 
In particular it should impact flows starting on the discover section, these were found out to be looping in the regression testing. This should address that.
> bugfix/LIVE-7728 Memoize device action requests to prevent loops

- .changeset/tall-hairs-suffer.md
- apps/ledger-live-desktop/src/renderer/families/near/StakeBanner.tsx
- libs/ledger-live-common/src/families/near/api/archive-node-sdk.ts
Adjusting the commission calculation for NEAR validators as the value from the API has changed.
- **Impacted projects**: `ledger-live-desktop`, `ledger-live-mobile` 
- https://ledgerhq.atlassian.net/browse/LIVE-7693
- [`Discord thread`](https://discord.com/channels/885256081289379850/973221693638193152/1115284843346001930) 
BEFORE:
AFTER:
> fix: NEAR validator commission denomination

- .changeset/eighty-zebras-build.md
- apps/ledger-live-mobile/src/screens/DeviceConnect/index.tsx
- apps/ledger-live-mobile/src/screens/Platform/exchange/CompleteExchange.tsx
- apps/ledger-live-mobile/src/screens/Platform/exchange/StartExchange.tsx
- apps/ledger-live-mobile/src/screens/SignTransaction/02-ConnectDevice.tsx
The recent refactor in device action implementation meant that rerenders of the screen that renders the `DeviceAction` component would trigger a new execution of the action itself **if the request was set inline**, if we memoize the request this doesn't happen.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-7728` 
In particular it should impact flows starting on the discover section, these were found out to be looping in the regression testing. This should address that.
> bugfix/LIVE-7728 Memoize device action requests to prevent loops (develop)

- .changeset/calm-glasses-design.md
- apps/ledger-live-desktop/src/renderer/families/bitcoin/FullNode/steps/StepConnectDevice.tsx
- apps/ledger-live-desktop/src/renderer/modals/AddAccounts/steps/StepConnectDevice.tsx
- apps/ledger-live-desktop/src/renderer/modals/ConnectDevice/index.tsx
- apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/CompleteExchange/Body.tsx
- apps/ledger-live-desktop/src/renderer/modals/Receive/steps/StepConnectDevice.tsx
- apps/ledger-live-desktop/src/renderer/modals/Send/steps/GenericStepConnectDevice.tsx
- apps/ledger-live-desktop/src/renderer/modals/SignMessage/steps/StepSign.tsx
- apps/ledger-live-desktop/src/renderer/modals/SignTransaction/steps/GenericStepConnectDevice.tsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/ExchangeDrawer/SwapAction.tsx
The recent refactor in device action implementation meant that rerenders of the screen that renders the DeviceAction component would trigger a new execution of the action itself if the request was set inline, if we memoize the request this doesn't happen. This is the LLD equivalent of the others.
Introducing a bunch of errors that would need to be addressed @alexandremgo 
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-7784` 
Nothing to demo
> feat: LIVE-7784 memoize device action requests for LLD

- .changeset/lazy-wolves-accept.md
- apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/WalletAPIWebview.tsx
This PR is rewiring the wallet-api on LLD so that the `wallet.userId` now provide the old userId instead of the new one. There seems to be more work worth doing to harmonise the way userId works in LLD.
Wallet API provided userId is now the same displayed in the developper menu
> now providing wallet-api with old userId

- .changeset/unlucky-peas-destroy.md
- apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/PlatformAPIWebview.tsx
- apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/WalletAPIWebview.tsx
Fixing a regression introduced in #3189 breaking the platform-sdk and wallet-api using postMessage, it's only present on prod builds of the app and we might want to improve our testing to include this.
> fix: webview preload dirname for prod app

- .changeset/lemon-mangos-wash.md
- libs/ledgerjs/packages/errors/src/index.test.ts
- libs/ledgerjs/packages/errors/src/index.ts
Node.js prints the `stack` property when displaying an error. Thus, the error message is lost unless it is set on the error instance that generates the stack trace too.
(I can't reopen #3630 so I'm opening this PR)
I've no idea what end user projects this change would impact. I'm personally using `@ledgerhq/hw-transport` and `@ledgerhq/hw-transport-node-hid` npm packages but I don't know which of these use the `@ledgerhq/errors` package.
> fix: Fixes TransportStatusError message on node.js

- .changeset/tiny-dancers-smell.md
- libs/ledger-live-common/src/socket/index.ts
We noticed something strange during a firmware update process between versions 1.1.0 and 1.2.0-rc1. Unfortunately, we couldn't get all the details because we send the data together in bulk and don't have access to the logs. However, after doing some debugging, I have a theory. 
It seems that the data we're receiving from the HSM is incorrect. I noticed a bunch of empty strings at the end of the APDU array. Since we don't check for empty strings, we end up sending HID/BLE frames without any data, which I believe is causing the disconnect. To address this issue, this pull request includes a sanity check or cleanup procedure where we remove empty APDUs before proceeding with the exchange.
- **Impacted projects**: `https://ledgerhq.atlassian.net/browse/LIVE-7868`  …
> fix: blind fix for disconnects during fw update due to bad HSM data

- .changeset/red-falcons-train.md
- apps/ledger-live-desktop/src/renderer/screens/manager/index.tsx
During the typescript migration of LLD we changed the way we passed the `appsToRestore` parameter around turning `appsToRestore={appsToRestore}` to `appsToRestore={appsToRestore || []}`. A seemingly harmless change to make typescript happy but with the added consequence of making anything that depends on that variable having to be recalculated **every time there's a render.** This had the side effect of resetting the app state every time we opened or closed a drawer.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-7878` 
No demo
- Enter the manager
- Install some apps
- Start some flow (rename, cls, language)
- It is expected that the state is respected and not reset.
> fix: LIVE-7878 inline [] causing manager state rerender

- .changeset/slow-seals-boil.md
- apps/cli/src/commands/appUninstallAll.ts
- libs/ledger-live-common/src/apps/logic.ts
- libs/ledger-live-common/src/apps/types.ts
- libs/ledger-live-common/src/hw/actions/uninstallAllApps.ts
- libs/ledger-live-common/src/hw/uninstallAllApps.test.ts
- libs/ledger-live-common/src/hw/uninstallAllApps.ts
With the 1.2.0 version of Stax we receive for the first time a firmware that allows us to bulk uninstall with user consent, allowing us to skip the uninstall queue completely, prevent HSM connections, speeding up the flow, improving the UX. We should use that when available, falling back to the normal uninstall flow when it’s not. Luckily, when the APDU is not available we get a unified `6d02` response, so leverage that in the implementation so that we always try that first.
This pr introduces the device action, the command and logic used, test coverage and a CLI implementation of the command, testable with `FORCE_PROVIDER=3 pnpm run:cli appUninstallAll` on a 1.2.0 Stax. Running the command (without the forced provider) on any other device should still uninstall the applications, but …
> feat/LIVE-7872 Uninstall all feature + CLI implementation

- .changeset/cold-dogs-kick.md
- apps/ledger-live-mobile/ios/Podfile.lock
- apps/ledger-live-mobile/package.json
- pnpm-lock.yaml
When updating Detox in https://github.com/LedgerHQ/ledger-live/pull/3567, `babel/core` was updated from `7.21.0` to `7.22.1`.
This created issues [see ticket](https://ledgerhq.atlassian.net/browse/LIVE-7869) on animations, probably related to [react-native-reanimated](https://www.npmjs.com/package/react-native-reanimated)
I tried updating to any versions between `7.21.0` and `7.22.1`, but issues appeared on every version > `7.21.0` (`7.21.3`).
So i decided to set `babel/core` to a fixed version for now.
Info: this is breaking some tests on Detox, but we've agreed with QA that this fix was more important for now
- **Linked resource(s)**: [LIVE-7869](https://ledgerhq.atlassian.net/browse/LIVE-7869)
Validations video:
<details>
<summary>iOS</summary> …
> Fix: LIVE-7869: navbar and animation not working

- .changeset/sour-phones-sing.md
- apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/steps/01-step-prepare.tsx
During the recent rework for backup and restore of device configuration, we introduced a bug that prevents firmware update for unseeded devices, a feature that is used internally by our colleagues and that we can't simply remove. This PR should address that regression bringing the expected behavior back.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-7816` 
No demo
An unseeded device in recovery mode should be able to complete a firmware update on LLD.
Steps on the ticket.
> bugfix/LIVE-7816 Regression in recovery mode firmware update for LLD

- .changeset/red-falcons-train.md
- apps/ledger-live-desktop/src/renderer/screens/manager/index.tsx
During the typescript migration of LLD we changed the way we passed the `appsToRestore` parameter around turning `appsToRestore={appsToRestore}` to `appsToRestore={appsToRestore || []}`. A seemingly harmless change to make typescript happy but with the added consequence of making anything that depends on that variable having to be recalculated **every time there's a render.** This had the side effect of resetting the app state every time we opened or closed a drawer.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-7878` 
No demo
- Enter the manager
- Install some apps
- Start some flow (rename, cls, language)
- It is expected that the state is respected and not reset.
> fix: LIVE-7878 inline [] causing manager state rerender - Release

- apps/ledger-live-mobile/src/components/SelectDevice2/index.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/scenes/ConnectNano.tsx
New device selector degrades UX for Nano onboarding
- **Linked resource(s)**: [LIVE-7775] 
[LIVE-7775]: https://ledgerhq.atlassian.net/browse/LIVE-7775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bugfix(LLM): New device selector degrades UX for Nano onboarding

- .changeset/friendly-goats-tickle.md
- apps/ledger-live-mobile/src/screens/FirmwareUpdate/index.tsx
After the update is completely finished and all the potential restores are done, the user should be redirected to the MyLedger screen with a reload in order for all the settings to be correctly updated in the MyLedger page (installed, apps, language, lockscreen, available updates, etc). This wasn't working due to a merge issue that broke the logic of an if statement. This PR fixes it.
- **Linked resource(s)**: [LIVE-7661]
https://github.com/LedgerHQ/ledger-live/assets/6013294/13332c24-e0f9-4e7c-bba4-a0a950389190
[LIVE-7661]: https://ledgerhq.atlassian.net/browse/LIVE-7661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(Firmware Update LLM): fix the MyLedger redirection after the update is finished

- .changeset/sweet-pens-repair.md
- libs/ledger-live-common/src/hw/actions/implementations.ts
- libs/ledger-live-common/src/hw/actions/manager.ts
Since https://github.com/LedgerHQ/ledger-live/pull/3105 we've been sending a "deviceChange" event at each loop of the polling mode of device actions. This caused a flickering on the device action "locked" state when the device was locked on the connect manager action. This PR increases the debounce time of replaceable "deviceChange" events to be greater than the polling frequency, this way we don't have a flickering on the device action state.
- **Linked resource(s)**: [LIVE-7821]
Before the PR:
https://github.com/LedgerHQ/ledger-live/assets/6013294/bd9a28f3-c4bb-4db1-96c1-e902ab531c43
After the PR:
https://github.com/LedgerHQ/ledger-live/assets/6013294/e379b08d-b778-4051-915c-29df22eed6f5
[LIVE-7821]: …
> fix(MyLedger): fix flickering of the connect manager action when device is locked

- .changeset/late-meals-greet.md
- apps/ledger-live-desktop/src/renderer/components/ChangeDeviceLanguageAction.tsx
There are two retry buttons in the locked device error screen for the language pack installation on my ledger.
We introduced the concept of `inlineRetry` for device actions that handled the retry mechanism in a footer such as this one, it's just a matter of using that prop.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-7904` 
Trying to change the language on a locked device should throw an error but only offer one retry button, like civilised people.
> fix: LIVE-7910 remove double retry button on locked device lang install

- .changeset/old-wombats-remember.md
- apps/ledger-live-desktop/src/renderer/components/Carousel/Slide.tsx
- apps/ledger-live-desktop/src/renderer/components/LinkWithExternalIcon.tsx
- apps/ledger-live-desktop/src/renderer/components/Onboarding/OnboardingNavHeader.tsx
- apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/Tutorial/shared.tsx
- apps/ledger-live-desktop/src/renderer/components/Stars/Star.tsx
- apps/ledger-live-desktop/src/renderer/families/bitcoin/FullNode/steps/StepDisconnect.tsx
- apps/ledger-live-desktop/src/renderer/families/bitcoin/FullNode/steps/StepLanding.tsx
- apps/ledger-live-desktop/src/renderer/screens/USBTroubleshooting/solutions/Intro.tsx
- apps/ledger-live-desktop/src/renderer/screens/USBTroubleshooting/solutions/shared.tsx
- apps/ledger-live-desktop/src/renderer/screens/manager/Disconnected.tsx
on LLD, fixes all cases where `url("` was used instead of `url('`. unfortunately, prettier seems to want to use `url("` but styled-component only support `url('` syntax for the image to appear.
- **Linked resource(s)**: `LIVE-7877` 
> fix: LLD fixes all cases where url(" was used instead of url('

- .changeset/four-cheetahs-lie.md
- apps/ledger-live-mobile/src/components/CustomImage/useCenteredImage.tsx
- apps/ledger-live-mobile/src/screens/CustomImage/PreviewPreEdit.tsx
Fixed two issues with Custom Lock Screen:
- fix uncaught error in `useCenteredImage`
- fix NFT picture preview not loading in some cases
- **Linked resource(s)**: [LIVE-7874] 
[LIVE-7874]: https://ledgerhq.atlassian.net/browse/LIVE-7874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-7874 fix(llm/customlockscreen): preview from an NFT not loading

- pnpm-lock.yaml
- tools/common-tools/package.json
apparently, vercel started to have this issue
```
live-common-tools:build: Cannot find module: 'tslib'. Make sure this package is installed.
```
so we try to add an explicit dependency to it on the live-common-tools project.
- **Impacted projects**: `live-common-tools` 
> chore: explicit dep to tslib for vercel to compile live-common-tools

- .changeset/little-seahorses-relax.md
- libs/ledgerjs/packages/hw-transport-node-hid-singleton/package.json
- libs/ledgerjs/packages/hw-transport-node-hid/package.json
- libs/ledgerjs/packages/hw-transport-node-hid/src/listenDevices.ts
- pnpm-lock.yaml
From: https://github.com/LedgerHQ/ledger-live/pull/3531, an attempt to fix the following issue: https://github.com/LedgerHQ/ledger-live/issues/3416.
- `@ledgerhq/hw-transport-node-hid`:
- is used by our CLI: `libs/ledgerjs/packages/hw-transport-node-hid/src/TransportNodeHid.ts`
- the `usb` package is bumped from to `1.7.0` to `2.9.0`
- `@ledgerhq/hw-transport-node-hid-singleton`:
- is used by LLD -> `libs/ledgerjs/packages/hw-transport-node-hid-singleton/src/TransportNodeHid.ts`
- the `usb` package is bumped from `2.5.1` to `2.9.0`
The migration from v1 to v2: we simply need to update the import statement (already done for `hw-transport-node-hid-singleton`)
The `usb` package is used to detect/listen to device connections/disconnections. 
The actual communication is done thanks to the …
> chore: bumping usb to 2.9.0 on hw-transport-node-hid and  hw-transport-node-hid-singleton

- .changeset/few-dogs-march.md
- .changeset/rude-mugs-breathe.md
- libs/coin-evm/package.json
- libs/domain-service/package.json
- libs/ledger-live-common/package.json
- pnpm-lock.yaml
PR provided by @Tuditi 
At the moment ledger apps depend on eip55 v2.1.0. This results in build errors in browser contexts, such as electron. 
(https://github.com/iotaledger/firefly/actions/runs/5284776862/jobs/9562554148)
The root cause of this error is that eip55 relies on an old version of the keccak package. This has been fixed in v2.1.1.
This PR aims to update the eip55 dependency.
- **Impacted projects**: `@ledgerhq/live-common` `@ledgerhq/coin-evm` `@ledgerhq/domain-service` 
> Support - Upgrade EIP55 package

- libs/ledger-live-common/src/families/tezos/bakers.whitelist-default.ts
- libs/ledger-live-common/src/families/tezos/bridge.integration.test.ts
- libs/ledger-live-common/src/families/tezos/bridge/js.ts
- Prevent max spendable estimate to be negative
- Update whitelist of Tezos bakers (validators) by removing some obsolete ones
- Remove send max test as we can't easily get the max spendable amount there
- Tezos integration tests are run on this PR
- All integration tests green on this PR
> [support] Fix Tezos integration tests

- .changeset/chilly-bees-protect.md
- apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/steps/restore/CLS.tsx
- apps/ledger-live-desktop/src/renderer/screens/manager/FirmwareUpdate/index.tsx
LLD firmware update analytics: add tracking of the custom lock screen restoration
- **Linked resource(s)**: [LIVE-7710] 
[LIVE-7710]: https://ledgerhq.atlassian.net/browse/LIVE-7710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(lld/fwupdate/analytics): custom lock screen restoration tracking

- apps/ledger-live-mobile/e2e/specs/deeplinks.spec.ts
- apps/ledger-live-mobile/e2e/specs/nftGallery.spec.ts
- apps/ledger-live-mobile/e2e/specs/onboarding.spec.ts
_After the [revert](https://github.com/LedgerHQ/ledger-live/pull/3663) of babel/core package version bump, Detox test including mocked device action are failing. Disabling them until fixing in [ticket](https://ledgerhq.atlassian.net/browse/B2CQA-1834)
> [B2CQA] Disable broken device mock tests

- libs/ledger-live-common/src/families/celo/__snapshots__/bridge.integration.test.ts.snap
- libs/ledger-live-common/src/families/celo/datasets/celo.scanAccounts.1.ts
- libs/ledger-live-common/src/families/celo/js-getTransactionStatus.ts
- Fix precedence of errors in `getTransactionStatus`
- Remove check of the total spent for send max, as the spendable balance of the account is more complex to compute due to staking
- Update snapshot
- Celo integration tests are run on this PR
- All integration tests green on this PR
> [support] Fix Celo integration tests

- .changeset/tender-singers-buy.md
- apps/ledger-live-mobile/src/components/SelectDevice2/index.tsx
- apps/ledger-live-mobile/src/screens/Manager/index.tsx
LLM My Ledger: add tracking in device selection screen
- **Linked resource(s)**: [LIVE-7711] 
[LIVE-7711]: https://ledgerhq.atlassian.net/browse/LIVE-7711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(llm/myledger): tracking for device selection screen

- .changeset/chilled-timers-remember.md
- apps/ledger-live-desktop/src/renderer/actions/settings.ts
- apps/ledger-live-desktop/src/renderer/analytics/segment.ts
- apps/ledger-live-desktop/src/renderer/components/DeviceAction/index.tsx
- apps/ledger-live-desktop/src/renderer/reducers/settings.ts
- apps/ledger-live-desktop/src/renderer/screens/manager/AppsList/index.tsx
This property must be updated for the time being, as it is not possible to uniquely identify the connection of a new or old device.
Each time a Nano is connected, the list is expanded. So you could end up with 45 NanoXs when in fact it's potentially the same device 45 times over. The result is erroneous and potentially very misleading analytics.
To resolve this problem, we need to find a way, like LLM, to have a unique identifier for the Nano. So there's a dependency on the Device team on this subject.
Now if my user has 3 nanoX, 1 Stax and 2 NanoS
the list will be: [ "nanoX", "stax", "nanoS"]
- **Linked resource(s)**: [LIVE-7114] 
_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#im …
> feat(LLD): Update modelListId with unique device type

- .changeset/hungry-phones-judge.md
- libs/ledger-live-common/src/apps/listApps/v2.ts
- libs/ledger-live-common/src/apps/polyfill.ts
The current version of the list apps v2 (recently made available via feature flags) does not support dynamic hash applications, meaning that if you had `"Fido U2F" or "Security Key"`  installed they would not show in the catalog in the first place. At the same time, we were getting the response from the backend in an unordered manner meaning the storage bar from inside the My Ledger screen would not match that of v1 and, more importantly, would not match the order the user installed the apps in.
This little PR addresses both issues. Note that there's a willingness from backend to change the signature of the endpoint that does the apps by hash and return them as a dictionary instead of an array, this may be an improvement to tackle by someone someday when I'm gone. In the meantime this …
> feat: LIVE-7960 Support for dynamic hash + keep order on listapps v2

- .changeset/mighty-panthers-push.md
- libs/coin-evm/src/__tests__/unit/api/explorer/etherscan.unit.test.ts
- libs/coin-evm/src/__tests__/unit/api/explorer/index.unit.test.ts
- libs/coin-evm/src/__tests__/unit/api/gasTracker/index.unit.test.ts
- libs/coin-evm/src/__tests__/unit/api/gasTracker/ledger.unit.test.ts
- libs/coin-evm/src/__tests__/unit/api/rpc/rpc.unit.test.ts
- libs/coin-evm/src/__tests__/unit/signOperation.unit.test.ts
- libs/coin-evm/src/__tests__/unit/synchronization.unit.test.ts
- libs/coin-evm/src/api/explorer/etherscan.ts
- libs/coin-evm/src/api/explorer/index.ts
- libs/coin-evm/src/synchronization.ts
This PR add a `toBlock` parameter to the explorer API of the EVM family. 
Why ? 
Because due to how rate limited some explorers (Etherscan/Blockscout) are, there might be a discrepency between calls concerning how recent the blocks are.
Example: I want to sync a Polygon (2s blocktime) account with Etherscan as an explorer. Etherscan has a 1 call / 5s limit and we need 4 calls to get the full state. So:
- Get the coin operations (latest block 10)
- wait 5 seconds
- Get the erc20 operations (latest block 12)
- wait 5 seconds
- Get the erc721 operations (latest block 15)
- wait 5 seconds
- Get the erc1155 operations (latest block 17)
Which means that when sending an ERC20/ERC721/ERC1155 transaction, you can be too early to get a coin operation and 15 seconds later find an erc1155 event …
> [LIVE-8061] Bugfix - Prevent operation duplicates with rate limited explorers

- .changeset/giant-wolves-add.md
- apps/ledger-live-mobile/src/actions/appstate.ts
- apps/ledger-live-mobile/src/actions/types.ts
- apps/ledger-live-mobile/src/components/FirmwareUpdateBanner.tsx
- apps/ledger-live-mobile/src/hooks/useListenToHidDevices.ts
- apps/ledger-live-mobile/src/reducers/appstate.ts
- apps/ledger-live-mobile/src/reducers/types.ts
- apps/ledger-live-mobile/src/screens/Manager/Manager.tsx
Since https://github.com/LedgerHQ/ledger-live/pull/2742 it has been possible to bypass the USB-only restriction on the firmware update for LNX and start the firmware update using a Bluetooth transport. However, Bluetooth firmware updates are not supported by LNX and can lead to unpredictable behaviour. This PR fixes this and keeps the fix that was made on https://github.com/LedgerHQ/ledger-live/pull/2742 for the firmware update banner. It does that by updating the transport to be considered for the firmware update when we plug a device via USB. If the user is on the manager, the manager gets reloaded and starts using the USB transport for all operations (Firmware update, app installations, etc).
- **Linked resource(s)**: [LIVE-7048]
- [N/A] …
> fix(Firmware Update LLM): fix bluetooth restriction bypass

- .changeset/plenty-items-fry.md
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/ReadOnly/index.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/index.tsx
hide referral banner when the referralBannerMobile feature flag is disabled
hide referral banner when the referralBannerMobile feature flag is disabled
- **Linked resource(s)**: [LIVE-7817] 
[LIVE-7817]: https://ledgerhq.atlassian.net/browse/LIVE-7817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(llm): referral banner

- .changeset/grumpy-cameras-bake.md
- .changeset/stupid-sloths-explain.md
- apps/ledger-live-mobile/src/components/Loading.tsx
- apps/ledger-live-mobile/src/components/Web3AppWebview/helpers.ts
- apps/ledger-live-mobile/src/components/WebPTXPlayer/index.tsx
PR to:
1. Fix flickering in the header by removing the buggy onLoadProgress hook. `isWhitelistedDomain` was being updated by multiple WebView state hooks, including `onLoadProgress` which has the previous `nativeEvent.url` rather than current ... meaning header text flickered due to `isWhitelistedDomain` transitioning from `false` to `true` to `false`.
2. Add a loading spinner when navigating between WebViews in WebPTXPLayer
- **Impacted projects**: Closes https://ledgerhq.atlassian.net/browse/LIVE-7930 & https://ledgerhq.atlassian.net/browse/LIVE-7927 …
> fix: llm - loading between webviews & flickering header text

- .changeset/neat-mugs-bake.md
- apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/FirmwareUpdate/RestoreStepDenied.tsx
- apps/ledger-live-mobile/src/screens/FirmwareUpdate/index.tsx
- apps/ledger-live-mobile/src/screens/FirmwareUpdate/useUpdateFirmwareAndRestoreSettings.ts
Before this PR, we were just skipping the current restore step on the firmware update if the user denied authorization in the device. This PR adds an info banner when this denial happens, the banner explains what happened and gives the user to retry the step or skip it.
- **Linked resource(s)**: [LIVE-7417]
https://github.com/LedgerHQ/ledger-live/assets/6013294/bceb0a5f-bd7e-4379-9c24-86c5c642918a
[LIVE-7417]: https://ledgerhq.atlassian.net/browse/LIVE-7417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(Firmware Update LLM): add info drawer with 'skip' and 'retry' options on restore steps denial

- .changeset/lazy-clocks-repeat.md
- apps/ledger-live-mobile/src/components/BleDevicePairingFlow/BleDevicePairing.tsx
- apps/ledger-live-mobile/src/components/SelectDevice2/index.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
Align the layout of the pairing flow (of the new selector) and change the wording to match the ticket.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-6344` 
Changes look like a lot but it's merely an indentation change from removing a wrapping Flex.
With the stax feature flag enabled (or the new device selection at least). Make sure the UI matches the screenshots and the wording too. Not much to check other than that since it's purely cosmetic.
> feat: LIVE-6344 aligned UI of pairing flow + wording change

- apps/ledger-live-desktop/package.json
- apps/ledger-live-desktop/src/main/index.ts
- pnpm-lock.yaml
everything appears to be smooth on upgrading from Electron 23 to Electron 25. this means we upgrade chromium from 110 to 114 with all the benefits these have. check https://www.electronjs.org/blog for more informations, there are no documented breaking changes that concerns us. if this PR pass the CI tests we will have a first level of confidence.
quick smoke test: I was able to run the app in dev mode on mac and make the USB works.
- **Linked resource(s)**: `LIVE-7943` 
> chore: upgrade to Electron 25

- .changeset/real-adults-double.md
- apps/ledger-live-desktop/src/renderer/screens/manager/FirmwareUpdate/index.tsx
Longer explanation in the linked ticket.
We broke the automatic firmware update process for users on old versions, but we have found a solution. Instead of asking them to download an old version which was the temporary solution, we have this PR. The proposed fix, which opens a drawer instead of a modal, solves the original issue.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-8196` 
No demo
A nano S on 1.4.2 should be able to update its firmware on LLD without complications.
> bugfix/LIVE-8196 Firmware update regression in LLD for old devices

- .changeset/ten-owls-tap.md
- apps/ledger-live-desktop/src/config/urls.ts
- apps/ledger-live-desktop/src/renderer/components/VaultSignerBanner.tsx
- apps/ledger-live-desktop/src/renderer/modals/VaultSigner/index.tsx
This fixes the vault help center url displayed in
- the banner that warns the user vault signer mode is `on`
- the vault settings modal
I took the opportunity to extract this url in the `config/urls` file
> fix: vault center help url and extract it in url helper

- .changeset/new-maps-worry.md
- apps/ledger-live-mobile/src/screens/Manager/Manager.tsx
A bug was introduced on https://github.com/LedgerHQ/ledger-live/pull/3570 that was causing the manager tab to reload during a firmware update. https://github.com/LedgerHQ/ledger-live/pull/3570 's fix relied on reloading the manager tab wen a new USB device was plugged in, however the multiple restarts during the firmware update were being recognized as new USB device being plugged in.
This PR fixes this issue by making the manager reload specific to BLE to USB transitions.
- **Linked resource(s)**: [LIVE-8191]
N/A (just a normal firmware update with no issues)
[LIVE-8191]: https://ledgerhq.atlassian.net/browse/LIVE-8191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(Firmware Update LLM): fix manager reload during update

- .changeset/perfect-chefs-know.md
- .changeset/popular-cooks-switch.md
- apps/ledger-live-mobile/src/actions/settings.ts
- apps/ledger-live-mobile/src/actions/types.ts
- apps/ledger-live-mobile/src/reducers/settings.ts
- apps/ledger-live-mobile/src/screens/Settings/Debug/Configuration/HasStaxRow.tsx
- apps/ledger-live-mobile/src/screens/Settings/Debug/Configuration/index.tsx
- libs/coin-framework/src/mocks/fixtures/nfts.ts
Add debug setting to simulate LL having connected once to a Ledger Stax. Useful to test some features without a Stax device (for instance Stax NFT metadata).
- **Linked resource(s)**: [LIVE-8204] 
https://github.com/LedgerHQ/ledger-live/assets/91890529/018ff61d-9a0b-40ce-b566-c0ad695d8575
[LIVE-8204]: https://ledgerhq.atlassian.net/browse/LIVE-8204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(llm/debug): debug setting to simulate that LLM has seen Stax once

- .changeset/hip-socks-refuse.md
- libs/ledger-live-common/src/hw/actions/implementations.ts
- libs/ledger-live-common/src/hw/actions/manager.ts
https://github.com/LedgerHQ/ledger-live/pull/3542 fixed an issue where the UI was refreshing way too fast when there was an error and it seemed to the user that nothing was happening, this happened only on event-based implementation of device actions (used by LLD), but the fix was also introduced on the polling based implementation (LLM). However, this fix introduced an issue for polling based implementations where the device action UI would flicker when the device was locked (see the video on [LIVE-8228]). 
This PR fixes the polling based flickering by removing the fix that was done on https://github.com/LedgerHQ/ledger-live/pull/3542, but only for the polling based implemenation of the device actions (since it wasn't initially needed there anyway).
This PR also reverts what was done on …
> fix(DeviceActionImplementations): fix flickering on device actions

- .changeset/olive-items-yawn.md
- libs/coin-evm/src/__tests__/hw-getAddress.unit.test.ts
- libs/coin-evm/src/__tests__/signOperation.unit.test.ts
- libs/coin-evm/src/signOperation.ts
- libs/coin-evm/src/signer.ts
This PR adds support for the `setLoadConfig` method of `hw-app-eth` in the `signerContext` and adds the usage of the environment variables `DYNAMIC_CAL_BASE_URL` & `NFT_ETH_METADATA_SERVICE`.
- **Impacted projects**: `@ledgerhq/coin-evm` 
> Feature - Add `setLoadConfig` method to signerContext & support for env var backend URIs

- .changeset/pretty-buckets-try.md
- libs/ledger-live-common/jest.config.ts
Currently when running `pnpm --filter="@ledgerhq/live-common" test` no coverage folder is created at the root of libs/ledger-live-common. This is fixed by moving the collectCoverage parameter outside the projects, at the root of the config object.
With the updated jest config, the coverage will include all untested files by including all ts and tsx files from the src/ folder.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-8184 
> chore(llc):  coverage including untested files

- .changeset/eleven-kids-dance.md
- .changeset/three-coats-teach.md
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/FirmwareUpdate/index.tsx
- apps/ledger-live-mobile/src/screens/FirmwareUpdate/useUpdateFirmwareAndRestoreSettings.ts
- libs/ledger-live-common/src/deviceSDK/actions/updateFirmware.ts
- libs/ledger-live-common/src/deviceSDK/hooks/useUpdateFirmware.ts
Before this PR we would only allow the user to quit the firmware update in case an error happened during the actual firmware update phase (not back up or restore phase). This PR adds a button to the error drawer allowing the user to retry the firmware update step.
_It also fixes an issue with the firmware update device action that would reset the state in case an error happened_
- **Impacted projects**: `ledger-live-mobile`, `ledger-live-common`
- **Linked resource(s)**: [LIVE-7417]
https://github.com/LedgerHQ/ledger-live/assets/6013294/b86268d2-25fe-4b4f-be20-a4054d8e14b5
[LIVE-7417]: https://ledgerhq.atlassian.net/browse/LIVE-7417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(Firmware Update LLM): add possibility to retry firmware update when an error happens

- .changeset/violet-kids-arrive.md
- libs/ledger-live-common/src/families/ethereum/postSyncPatch.ts
When nonce = 0, pending transaction is filtered out by mistake because of (op.transactionSequenceNumber is false when transactionSequenceNumber = 0)
- **Impacted projects**: `` LLC
> fix: LIVE-8236 Missing pending transaction

- apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx
Modified the lotties on device actions (PTX flows...)
No more blue/stax height rule
The container is now 150px height,
If the device is a stax, the lottie is rendered with a height of 210px (allowing it to match the 150px container size, this is due to stax lotties being square with a big space all around)
- **Linked resource(s)**: [LIVE-7537]
N/A
[LIVE-7537]: https://ledgerhq.atlassian.net/browse/LIVE-7537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> style(LLM/Device Actions): Style modifications for device actions lotties

- .github/workflows/build-desktop-external.yml
- .github/workflows/build-desktop.yml
- .github/workflows/build-mobile-external.yml
- .github/workflows/build-mobile.yml
- .github/workflows/test-mobile.yml
- .github/workflows/test.yml
- tools/actions/composites/setup-test-desktop/action.yml
- tools/github-bot/src/features/lintCommits/index.ts
- tools/github-bot/src/tools/monitorWorkflow.ts
Only display errors in `turbo` tasks.
no demo, but less output in CI
> chore: only display error in turbo output

- .changeset/angry-nails-camp.md
- libs/ledger-live-common/src/hw/getLatestAvailableFirmwareFromDeviceId.test.ts
- libs/ledger-live-common/src/hw/getLatestAvailableFirmwareFromDeviceId.ts
- libs/ledger-live-common/src/hw/hooks/useGetLatestAvailableFirmware.test.ts
- libs/ledger-live-common/src/hw/hooks/useGetLatestAvailableFirmware.ts
2 changes (necessary for https://github.com/LedgerHQ/ledger-live/pull/3887 and the same work on LLD by Olivier):
- return device info from `getLatestAvailableFirmwareFromDeviceId` (with unit tests)
- return device info from hook `useGetLatestAvailableFirmware` (with unit tests)
No breaking changes as we only added an additional property to what the hook returns, and the logic is kept the same (unit tests are making sure no logic change was made).
Also the hook is currently only used in `apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/SoftwareCheckStep.tsx` which is in the sync onboarding. You can see a small demo below showing it still works correctly.
- **Impacted projects**: `live-common` …
> Feat/LIVE-8302: return device info from hook to get latest available firmware update

- .changeset/tall-dots-rule.md
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.tsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/config.ts
- apps/ledger-live-desktop/static/i18n/en/app.json
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Swap/Form/index.tsx
- libs/ledger-live-common/src/exchange/swap/getExchangeRates.ts
- libs/ledger-live-common/src/exchange/swap/hooks/useProviderRates.ts
- libs/ledger-live-common/src/exchange/swap/hooks/useSwapTransaction.ts
- libs/ledger-live-common/src/exchange/swap/types.ts
swap service is not available
When any other error or after 10s
Then Error message: Quotes could not be generated because of technical issues. Try swapping again in a few moments. is displayed
- **Impacted projects**: `LLC, LLM, LLD` 
- **Linked resource(s)**: [LIVE-8380](https://ledgerhq.atlassian.net/browse/LIVE-8380) 
https://github.com/LedgerHQ/ledger-live/assets/132384348/8c842373-f52e-4690-8844-8ec0443d62b2
28-021f-4250-a4b8-1db92342e6f0)
[LIVE-5953]: https://ledgerhq.atlassian.net/browse/LIVE-5953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …
> [Bugfix/LIVE-8380] add 10s timeout to swap quotes on LLD & LLM

- .github/workflows/renovate.yml
- renovate-config.js
- renovate.json
The Renovate Github App forces the configuration option `allowScripts` to false and it is not possible to change it from out side.
Because of this flag the `pnpmfile.cjs` config is ignored by Renovate when bumping dependencies which results in massive and wrong updates to the lockfile. And ultimately the build crashes because of package resolution issues 💥.
Self-hosting Renovate using the official github action should fix the problem hopefully.
> ci: add renovate action

- apps/ledger-live-mobile/fastlane/.env.android.release
**Fixes prod android builds reading the `react-native-config` environment from prerelease instead of release.**
```
Reading env from: .env.android.prerelease
```
Results in sentry logs get sent to the prerelease project. 💥 
- **Linked resource(s)**: [`LIVE-5386`](https://ledgerhq.atlassian.net/browse/LIVE-5386) 
> ci(llm): use proper release env for android prod builds

- apps/ledger-live-desktop/src/renderer/screens/earn/index.tsx
- Send discrete mode status as a query parameter to the earn dashboard web app
- **Impacted projects**:  PTX Earn dashboard
- **Linked resource(s)**:  https://ledgerhq.atlassian.net/browse/LIVE-7791
N/A
> feat: add discreet mode param to earn dashboard

- .changeset/smart-eggs-allow.md
- libs/coin-framework/src/derivation.ts
- libs/ledger-live-common/src/families/internet_computer/bridge.integration.test.ts
ICP, like many other chains we support, don't use the standard BIP44 derivation scheme, but a custom one
The custom scheme was defined and used however using the standard BIP44 wasn't disabled, so both were used while scanning for accounts, resulting in the bug of having two versions of each account (one being incorrect).
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-8498 
https://github.com/LedgerHQ/ledger-live/assets/59644786/67124dfc-08f4-4406-89b3-e7a65cbf50d6
> [bugfix] Disable default derivation scheme for ICP, only use custom one

- .changeset/calm-nails-report.md
- apps/ledger-live-mobile/src/screens/SendFunds/02-SelectRecipient.tsx
Correcting typo making all chains (except EVM/Ethereum ones) skip the amount screen during send flow.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-8490 
https://github.com/LedgerHQ/ledger-live/assets/44363395/25204498-cd66-4d8e-8139-5cdf069083f8
> [LIVE-8490] Bugfix - Fix wrong `shouldSkipAmount` in LLM send flow

- apps/ledger-live-mobile/e2e/models/manager/managerPage.ts
- apps/ledger-live-mobile/e2e/models/onboarding/onboardingSteps.ts
- apps/ledger-live-mobile/e2e/specs/onboarding.spec.ts
- apps/ledger-live-mobile/package.json
- pnpm-lock.yaml
_Updating Detox to latest version [2.11.0](https://github.com/wix/Detox/releases/tag/20.11.0)_
On this version, synchronisation with reanimated animation is [fixed](https://github.com/wix-incubator/DetoxSync/pull/59), causing test to [halt](https://wix.github.io/Detox/docs/troubleshooting/synchronization/#endless-looping-animations) on scanning page animation, preventing mock devices to be added. Disabling [synchronisation](https://wix.github.io/Detox/docs/troubleshooting/synchronization/#controlling-the-entire-synchronization-mechanism) temporarily during these tests to fix this issue. …
> [B2CQA-1883] Update detox and fix issues

- .changeset/new-planets-raise.md
- apps/ledger-live-desktop/src/renderer/components/Price.tsx
Swap quotes are not readable in light mode. `Price` component has an optional `color` prop which determines the text color. If value is not provided text color seemed to be defaulted to white. 
Code changes to use `theme.colors.palette.text.shade100` as default value the `color` is not provided.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-8530 
> fix(LIVE-8530): quotes are not readable in light mode

- .changeset/thirty-pumas-sleep.md
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FeesDrawer/index.tsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FormSummary/SectionFees.tsx
- apps/ledger-live-mobile/src/components/SendRowsFee.tsx
- libs/ledger-live-common/src/families/solana/js-prepareTransaction.ts
Following this comment https://github.com/LedgerHQ/ledger-live/pull/3945#discussion_r1259334119 and the related discussion, proposal to remove what seem to be an unnecessary condition on the existence of a `networkInfo` property on the `transaction` object to render (or not) a family custom `SendRowsFee` component.
Not all crypto transaction types have a `networkInfo` property and some of them have some custom `SendRowsFee` component.
If a family `SendRowsFee` component display is dependent on the presence of a `networkInfo` property in the `transaction` object, these families own `SendRowsFee` component will never be displayed.
This condition seems odd because not all families have a `networkInfo` property in their `transaction`. For example `algorand`, but also the new `evm`. But these …
> [SUPPORT] remove unnecessary check on tx networkInfo

- .changeset/angry-apricots-tell.md
- .changeset/wet-houses-study.md
- apps/ledger-live-mobile/src/components/DeviceAction/common.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/FirmwareUpdate/index.tsx
- libs/ui/packages/native/src/components/Icon/IconBadge.tsx
This PR implements most of the design polishes for the firmware update new UX tracked on LIVE-7949. It contains mainly spacing and wording changes. Should have no impact on functionality.
- **Linked resource(s)**: [LIVE-7949]
https://github.com/LedgerHQ/ledger-live/assets/6013294/2c965927-bf93-4567-9d9b-b6babfbd0286
[LIVE-7949]: https://ledgerhq.atlassian.net/browse/LIVE-7949?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIVE-7949] Design polishes for the new firmware update UX

- .changeset/angry-poets-end.md
- apps/ledger-live-mobile/src/components/SelectDevice2/index.tsx
- apps/ledger-live-mobile/src/screens/CustomImage/Step3Transfer.tsx
This PR adds a filter on the type of device to be selectable on the device selections screen. It also makes use of this filter during the NFT -> custom lock screen flow in order to restrict the selection to Stax devices. This had already been done in the old device selection screen but not yet in the new one. 
- **Linked resource(s)**: [LIVE-7445]
https://github.com/LedgerHQ/ledger-live/assets/6013294/ceca7ead-6830-4192-b650-2b543d55681e
[LIVE-7445]: https://ledgerhq.atlassian.net/browse/LIVE-7445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIVE-7445] Filter device selection to only stax when using NFT as CLS

- .changeset/flat-cooks-sin.md
- apps/ledger-live-mobile/src/components/Nft/NftGallery/NftList.tsx
- apps/ledger-live-mobile/src/components/Nft/NftViewer.tsx
- apps/ledger-live-mobile/src/screens/Nft/WalletNftGallery/index.tsx
Apply discreet mode to the NFT gallery to hide floor prices of NFT's
- **Linked resource(s)**: `LIVE-8542` 
> feat: apply discreet mode to nft gallery

- .changeset/light-carrots-fix.md
- libs/ledger-live-common/src/featureFlags/defaultFeatures.ts
Sync onboarding: remove Polygon from default list of apps installed on device as it is no longer needed for full setup of Stax (because we are dropping the claim NFT feature in the post onboarding) 
- **Impacted projects**: `llc llm lld` 
- **Linked resource(s)**: [LIVE-8561] 
[LIVE-8561]: https://ledgerhq.atlassian.net/browse/LIVE-8561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-8561 feat(common/defaultFeatures): remove Polygon from deviceInitialApps

- .changeset/modern-pandas-run.md
- apps/ledger-live-mobile/src/components/Nft/NftVideo.tsx
- apps/ledger-live-mobile/src/components/Nft/NftViewer.tsx
Use a transparent background on the NFT image on the NFT Viewer screen to remove the "letter boxing"
- **Linked resource(s)**: `LIVE-8549` 
https://github.com/LedgerHQ/ledger-live/assets/1044686/45a7c409-0412-41f2-9cd0-1d2c0c182287
> feat: use transparent background on nft viewer screen

- apps/ledger-live-desktop/src/renderer/drawers/SwapOperationDetails/index.tsx
- apps/ledger-live-desktop/tests/models/DiscoverPage.ts
- apps/ledger-live-desktop/tests/models/Drawer.ts
- apps/ledger-live-desktop/tests/models/LiveAppWebview.ts
- apps/ledger-live-desktop/tests/models/Modal.ts
- apps/ledger-live-desktop/tests/models/SwapPage.ts
- apps/ledger-live-desktop/tests/specs/services/ethereumStaking.spec.ts
- apps/ledger-live-desktop/tests/specs/services/liveapp-sdk.spec.ts
- apps/ledger-live-desktop/tests/specs/services/swap.spec.ts
- libs/coin-framework/src/currencies/formatCurrencyUnit.ts
NOTE: this PR is primarily to remove the screenshot which was failing due to flaky amounts in the swap verify drawer. We're now just checking the text and that the amount matches up to the first 3 decimals which are consistent as far as we can see. This issue should be fixed as the user could be seeing the wrong amount in the verify screen. Also the functions that generate the formatted amounts should have unit tests given it is a large, complex function and it is used in many places in LLD and LLM.
- Removed screenshot swap checks in favour of text check
- Tidied up services page objects and tests
_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTING.md#important …
> fix: removed screenshot swap checks in favour of text check and tidied up services page objects and tests

- .changeset/friendly-panthers-build.md
- apps/ledger-live-desktop/src/renderer/screens/platform/v2/Catalog/Browse/Result/index.tsx
- apps/ledger-live-desktop/src/renderer/screens/platform/v2/Catalog/Browse/index.tsx
Fixed the filtering by using the search result whenever a filter is selected
- **Linked resource(s)**: [`LIVE-8639`](https://ledgerhq.atlassian.net/browse/LIVE-8639) 
> fix(discover): filtering on LLD [LIVE-8639]

- .changeset/clean-kiwis-protect.md
- libs/ledger-live-common/src/exchange/index.ts
- libs/ledger-live-common/src/families/tron/exchange.ts
- libs/ledger-live-common/src/generated/exchange.ts
Adding Tron to ledger live common
- **Linked resource(s)**: [LIVE-7243](https://ledgerhq.atlassian.net/browse/LIVE-7243) 
https://github.com/LedgerHQ/ledger-live/assets/138497251/36e6bd7e-72b8-458d-adba-347f87338287
[LIVE-7223]: https://ledgerhq.atlassian.net/browse/LIVE-7223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-7243]: https://ledgerhq.atlassian.net/browse/LIVE-7243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(LIVE-7243): add tron exchange to ledger live common

- .changeset/tidy-crabs-relax.md
- apps/cli/src/commands-index.ts
- apps/cli/src/commands/deviceSDKGetBatteryStatuses.ts
- apps/ledger-live-mobile/src/components/FirmwareUpdateBanner.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- libs/ledger-live-common/src/deviceSDK/actions/getBatteryStatuses.ts
- libs/ledger-live-common/src/deviceSDK/commands/getBatteryStatus.test.ts
- libs/ledger-live-common/src/deviceSDK/commands/getBatteryStatus.ts
- libs/ledger-live-common/src/deviceSDK/hooks/useBatteryStatuses.ts
- libs/ledger-live-common/src/deviceSDK/tasks/getBatteryStatuses.ts
- libs/ledger-live-common/src/hw/getBatteryStatus.ts
This PR makes two changes to the workings of the battery warning banner on firmware updates for Stax. The first one is that it checks the Stax battery status at the moment the user clicks to update, instead of when the component is rendered. This way we always have the latest status right before launching the firmware update.
The second change is making the warning banner unskippable, we do not allow the update to be launched on low, not charging, battery. 
- **Linked resource(s)**: [LIVE-7417]
N/A
[LIVE-7417]: https://ledgerhq.atlassian.net/browse/LIVE-7417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(Firmware Update LLM): make stax battery warning unskippable

- .changeset/chatty-horses-compare.md
- .changeset/giant-pumpkins-study.md
- .changeset/shiny-days-worry.md
- apps/ledger-live-mobile/src/screens/FirmwareUpdate/index.tsx
- apps/ledger-live-mobile/src/screens/FirmwareUpdate/useUpdateFirmwareAndRestoreSettings.ts
- libs/ledger-live-common/src/hw/installApp.ts
This PR adds two improvements to improve User Experience in case an error happens during the app restoration phase of a firmware update. 
The first is an automatic retry mechanism in the app installation operation in order to recover from quick transient errors (e.g. errors that might happen due to an unstable network).
The second one is a manual retry mechanism in case the app restoration fails to recover automatically. It works using the same manual retry mechanism as the other restoration phases of the firmware update. 
- **Impacted projects**: `ledger-live-common`,`ledger-live-mobile`
- **Linked resource(s)**: [LIVE-8528]
https://github.com/LedgerHQ/ledger-live/assets/6013294/f4afbc16-dfdc-414e-a796-aef76b87d0b2
Test plan:
The part concerning the automatic recovery might be hard to …
> [LIVE-8528] Add retry mechanism for app restoration errors during FW update

- .changeset/young-pumas-train.md
- .github/workflows/cal-importer-stg.yml
- .github/workflows/cal-importer.yml
This disables the dynamic CAL CDN workflows, which are handled in the LedgerHQ/crypto-assets repository: LedgerHQ/crypto-assets#805
The workflows are temporarily kept so we can trigger them in case anything is wrong with the transition.
- **Impacted projects**: `@ledgerhq/cryptoassets`
- **Linked resource(s)**: [BACK-5411](https://ledgerhq.atlassian.net/browse/BACK-5411)
CDN contents should not change, eg https://cdn.live.ledger.com/cryptoassets/evm/1/erc20.json
[BACK-5411]: https://ledgerhq.atlassian.net/browse/BACK-5411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BACK-5411: disable dynamic CAL pipelines

- .changeset/wet-toys-jog.md
- libs/coin-evm/src/__tests__/unit/api/explorer/types.unit.test.ts
- libs/coin-evm/src/api/explorer/types.ts
Add missing teloscan in type guard, making sync fail for Telos
https://ledgerhq.atlassian.net/browse/LIVE-7546
> Bugfix - add missing teloscan in type guard

- .changeset/unlucky-cameras-try.md
- libs/ledger-live-common/src/families/cosmos/js-synchronisation.ts
- libs/ledger-live-common/src/families/cosmos/js-synchronisation.unit.test.ts
Fix cosmos operation detail fields names destination_validator, source_validator
It was a regression due to the 
https://github.com/LedgerHQ/ledger-live/commit/e775c83ab7fa28b395c149d03679cdd93535b14a
destination_validator was renamed with "validator_dst" by mistake.
source_validator was renamed with "validator_src" by mistake.
- **Impacted projects**: LLC, LLD, LLM
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-8787
> fix: cosmos operation detail fields names destination_validator, source_validator

- .changeset/healthy-suns-refuse.md
- .changeset/metal-brooms-deny.md
- apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx
- apps/ledger-live-desktop/src/renderer/components/RecoverRestore/index.tsx
- apps/ledger-live-desktop/static/i18n/en/app.json
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Protect/RedirectToOnboardingRecoverFlow.tsx
- libs/ledger-live-common/src/errors.ts
Adjust wording on error device already seeded in onboarding Recover on LLD and LLM
Add "buy a ledger" on desktop screen
Add dynamic Device on message
Add generic error on ledger common
- **Impacted projects**: `ledger-live-mobile``ledger-live-desktop``ledger-common` 
- **Linked resource(s)**: `[PROTECT-2273](https://ledgerhq.atlassian.net/browse/PROTECT-2273)` 
https://github.com/LedgerHQ/ledger-live/assets/118977988/3e2a63d8-e9a0-4b3c-9436-7af75daef487
g Screenrecorder-2023-07-27-11-38-30-256.mp4…
[PROTECT-2273]: https://ledgerhq.atlassian.net/browse/PROTECT-2273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bugfix(protect-2273): recover wording error device seeded

- .changeset/lemon-pigs-promise.md
- libs/ledger-live-common/src/hw/getOnboardingStatePolling.test.ts
- libs/ledger-live-common/src/hw/getOnboardingStatePolling.ts
- libs/ledger-live-common/src/onboarding/hooks/useOnboardingStatePolling.test.ts
During the Sync Onboarding and the Early Security Check: if the user has a problem during the fw update, and their device is in bootloader/update mode, they need to be able to fix their device state.
To be able to know that the device is in bootloader mode, the easiest is for the polling mechanism to return this information.
It will be used by https://github.com/LedgerHQ/ledger-live/pull/3909 and https://github.com/LedgerHQ/ledger-live/pull/3887
- **Impacted projects**: `live-common`
- **Linked resource(s)**: [LIVE-8795](https://ledgerhq.atlassian.net/browse/LIVE-8795) …
> feat: handle device in bootloader as a fatal error in the polling mechanism

- libs/ui/tests/react.spec.js
Try to fix snapshot testing flakiness.
I updated our usage of Playwright to manage screenshots as described in the documentation by moving the await on the expect instead of page.*
https://playwright.dev/docs/test-snapshots
Some issues I found that can be related: https://github.com/microsoft/playwright/issues/18827
> Fix flaky snapshot with playwright

- .changeset/eight-rockets-behave.md
- apps/ledger-live-desktop/src/renderer/modals/AddAccounts/steps/StepChooseCurrency.tsx
- apps/ledger-live-mobile/src/screens/AddAccounts/01-SelectCrypto.tsx
Feature flag wasn't correctly defined for Polygon Zk EVM and Polygon Zk EVM testnet, causing them to always be available even with feature flag off.
- **Impacted projects**: `LLD` `LLM` 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-8844
> [bugfix] Polygon zk evm feature flag

- apps/ledger-live-mobile/src/analytics/segment.ts
- apps/ledger-live-mobile/src/components/BuyDeviceBanner.tsx
- apps/ledger-live-mobile/src/components/DeviceAction/common.tsx
- apps/ledger-live-mobile/src/components/ExploreTab/ExploreTabNavigatorTabBar.tsx
- apps/ledger-live-mobile/src/components/FabActions/ReadOnlyFabActions.tsx
- apps/ledger-live-mobile/src/components/Nft/NftGallery/NftList.hook.ts
- apps/ledger-live-mobile/src/components/RootNavigator/NotificationCenterNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/ReceiveFundsNavigator.tsx
- apps/ledger-live-mobile/src/components/SelectDevice/index.tsx
- apps/ledger-live-mobile/src/components/WalletTab/WalletTabNavigatorTabBar.tsx
- apps/ledger-live-mobile/src/logic/notifications.tsx
- apps/ledger-live-mobile/src/screens/Account/AccountHeader.tsx
- apps/ledger-live-mobile/src/screens/Account/ReadOnly/ReadOnlyAccount.tsx
- apps/ledger-live-mobile/src/screens/Accounts/AccountsNavigationHeader.tsx
- apps/ledger-live-mobile/src/screens/Assets/AssetsNavigationHeader.tsx
- apps/ledger-live-mobile/src/screens/FirmwareUpdate/RestoreStepDenied.tsx
- apps/ledger-live-mobile/src/screens/FirmwareUpdate/index.tsx
- apps/ledger-live-mobile/src/screens/GetDeviceScreen.tsx
- apps/ledger-live-mobile/src/screens/Newsfeed/index.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/discoverLiveInfo.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/Header.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/02-AddAccountSelectDevice.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/03a-ConnectDevice.tsx
- apps/ledger-live-mobile/src/screens/Settings/General/CarouselRow.tsx
- apps/ledger-live-mobile/src/screens/Settings/General/DateFormatDrawer.tsx
- apps/ledger-live-mobile/src/screens/Settings/General/DateFormatRow.tsx
- apps/ledger-live-mobile/src/screens/Settings/Notifications/index.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/Header.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/ReadOnly/index.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/referralProgram.tsx
On demand of the analytics team we're replacing the `screen` property by the `page` property for all usages of the `track` function.
This comes at a cost: some events were already sending events with the `page` property set (on top of `screen` which is set by default for all events sent with `track`), so some data will be lost. The way this is done, for those events, the old value of `page` will stay and replace the value that was set by default for `screen`.
This was agreed to be an acceptable solution.
Usages of the track function are numerous so of course I didn't check them all one by one.
I used these less than desirable regular expressions in the "find in all files" of vs code in order to find _most_ of the places where the track function is used with `screen` being set in the event …
> feat(llm/analytics): replace "screen" by "page" in all usages of track()

- .changeset/beige-needles-sip.md
- apps/ledger-live-desktop/src/renderer/components/ProviderIcon/index.tsx
- apps/ledger-live-desktop/src/renderer/families/ethereum/StakeFlowModal/StakingIcon.tsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/Rates/Rate.tsx
- apps/ledger-live-mobile/src/components/ProviderIcon/index.tsx
- apps/ledger-live-mobile/src/components/ProviderIcon/styles.ts
- Default ProviderIcon to use boxed mode.
- Ensure ProviderIcon sizes can be varied on LLM
- Ensure changes doesn't effect LLD
Related [PR on Ledger live assets](https://github.com/LedgerHQ/ledger-live-assets/pull/674) to remove `width` & `height` to provide fixed icon sizes on LLM
- **Impacted projects**: `LLD` & `LLM`
- **Linked resource(s)**:  [LIVE-8841](https://ledgerhq.atlassian.net/browse/LIVE-8841)
| Variant  | Screenshot |
| LLM Light XXS  | ![Simulator Screenshot - iPhone 14 - 2023-08-02 at 21 28 17](https://github.com/LedgerHQ/ledger-live/assets/138497251/7740fecb-fddd-4af8-bb7e-92c3b857fc63)  |
| LLM Light  XS | ![Simulator Screenshot - iPhone 14 - 2023-08-02 at 21 28 19](https://github.com/LedgerHQ/ledger-live/assets/138497251/61b3ffbe-8720-4b …
> Bugfix(LIVE-8841): default provider icon to use boxed mode

- .changeset/light-jobs-exercise.md
- apps/ledger-live-desktop/src/renderer/components/TranslatedError/hooks/useErrorLinks.tsx
- apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx
- libs/ledger-live-common/src/exchange/swap/hooks/useSwapTransaction.ts
Redirect to the buy/sell app from the NotEnoughGasSwap and select the account in cases where it's the fee token ( e.g ETH ) or the parent account in cases where the user is swapping something like ( USDC on ETH ).
LLM handles this by default so no need for a change, however I have made the conversion of `/platform/:app_id` to `/discover/:app_id` more generic.
- **Impacted projects**: `LLC, LLD, LLM` 
- **Linked resource(s)**: [LIVE-8848](https://ledgerhq.atlassian.net/browse/LIVE-8848) 
https://github.com/LedgerHQ/ledger-live/assets/132384348/ea6cab56-3652-48f0-b2f6-e9896b0dd6aa
https://github.com/LedgerHQ/ledger-live/assets/132384348/b32048dd-acbb-4e97-a182-043f360a22f2
_Please make sure you follow these [**Important Steps**](https://github.com/LedgerHQ/ledger-live/blob/develop/CONTRIBUTI …
> [Feat/LIVE-8848]: redirect to account or parent account if token on click for NotEnoughGasSwap error.

- apps/ledger-live-mobile/src/components/StorylyStories/index.tsx
Support links and deeplinks in Storyly stories CTA.
https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/463?modal=detail&selectedIssue=LIVE-8387
I initially tried to use onPress event as described here: https://docs.storyly.io/docs/react-native-action-handling
Unfortunately the library is not well typed and onPress event parameter is typed as
```
export interface StoryPressEvent {
story: Story;
} 
```
instead of Story.
https://github.com/LedgerHQ/ledger-live/assets/31533861/cb01f112-e504-4c9c-9d38-c38c35b4e42e
_Pull Requests must pass the CI and be internally validated …
> fix: Support StoryCTAClicked event and handle deeplinks

- .changeset/thin-socks-begin.md
- libs/coin-evm/src/__tests__/unit/synchronization.unit.test.ts
- libs/coin-evm/src/synchronization.ts
In evm family, the pending transactions in transaction history disappear after OPERATION_OPTIMISTIC_RETENTION timeout. This bug is related to incorrectly removing pending transaction in postSync method in evm family.
I fix this bug by referring the postSync from ethereum family. 
- **Impacted projects**: `` LLC
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-8887
> Fix: LIVE-8887 pending tx for evm family

- .changeset/fair-tables-shop.md
- .changeset/fluffy-rules-shave.md
- .changeset/old-crabs-hug.md
- .changeset/perfect-donuts-hammer.md
- .changeset/rotten-buses-leave.md
- apps/ledger-live-mobile/src/components/FirmwareUpdateBanner.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/types/ManagerNavigator.ts
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/FirmwareUpdate/UpdateReleaseNotes.tsx
- apps/ledger-live-mobile/src/screens/FirmwareUpdate/index.tsx
- apps/ledger-live-mobile/src/screens/FirmwareUpdate/useUpdateFirmwareAndRestoreSettings.ts
- apps/ledger-live-mobile/src/screens/Manager/AppsScreen.tsx
- apps/ledger-live-mobile/src/screens/Manager/Manager.tsx
- apps/ledger-live-mobile/src/screens/Manager/index.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/ReadOnly/index.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/index.tsx
- libs/ledger-live-common/src/deviceSDK/actions/core.ts
- libs/ledger-live-common/src/deviceSDK/commands/getBatteryStatus.ts
- libs/ledger-live-common/src/deviceSDK/commands/getVersion.ts
- libs/ledger-live-common/src/deviceSDK/hooks/useBatteryStatuses.ts
- libs/ledger-live-common/src/deviceSDK/tasks/core.ts
- libs/ledger-live-common/src/deviceSDK/tasks/getBatteryStatuses.ts
- libs/ledger-live-common/src/deviceSDK/tasks/updateFirmware.ts
This PR fixes several bugs:
- an issue on how "user solvable" errors were handled on the logic and UI of the fw update
- a bug on errors that were supposed to be ignored (e.g. an inexistent lockscreen image when backing up) and were actually being reported to the user -> original ticket [LIVE-8789](https://ledgerhq.atlassian.net/browse/LIVE-8789)
- a bug when a “allow manager”/secure channel was refused as the beginning of the fw update
- a bug on the battery check UX that made the app re-navigate to the firmware update automatically once the user exited it -> original ticket [LIVE-8796](https://ledgerhq.atlassian.net/browse/LIVE-8796): where https://github.com/LedgerHQ/ledger-live/pull/4155 was an 1st attempt to fix it
- a bug on the battery check device action that was updating and …
> fix(FirmwareUpdateLLM): ignore irrelevant errors on the fw update

- .changeset/rude-years-flow.md
- apps/ledger-live-desktop/src/renderer/storage.ts
- apps/ledger-live-desktop/tests/specs/accounts/unknown-currency-resilience.spec.ts
- apps/ledger-live-desktop/tests/userdata/skip-onboarding-with-bad-account-data.json
- apps/ledger-live-mobile/e2e/bridge/client.ts
- apps/ledger-live-mobile/e2e/bridge/server.ts
- apps/ledger-live-mobile/e2e/specs/unknown-currency-resilience.spec.ts
- apps/ledger-live-mobile/src/actions/accounts.ts
This add resiliency on importing accounts that would fail to be decoded in the future on both LLM and LLD.
There are a few possible reasons why an old account could be failed to be imported. For instance, if one of the field including `currencyId`, `derivationMode`, ...other field that have strict assertion (on the `fromAccountRaw` call) are bad (altered, modified, removed).
Some real world examples:
- a derivationMode becomes obsolete and is removed
- a currency becomes obsolete and is removed (example: Ethereum Ropsten)
- one of these field is altered by the user somehow (app.json modified / corrupted)
- exporting/importing an app.json manually from the past / through various backup services
**The previous behavior:**
One bad account data and it was badly crashing the app at boot.
**The …
> chore: add resiliency on importing accounts that fail to be decoded

- apps/ledger-live-mobile/src/screens/ReceiveFunds/02-SelectNetwork.tsx
- apps/ledger-live-mobile/src/screens/ReceiveFunds/03-Confirmation.tsx
Fix animation on banners in step 2 & step 3-bis
replace `react-native-reanimated` with `react-native-animatable`
> 🐛 [FIX]: Fix animation on banners in step 2 & step 3-bis

- .changeset/lazy-pens-judge.md
- apps/ledger-live-mobile/src/components/AnalyticsConsole/EventList.tsx
- apps/ledger-live-mobile/src/components/AnalyticsConsole/index.tsx
There is a layout issue, probably due to ScrollView or Reanimated, or the combination of both, that makes items of the console collapse at some point, as if they have a 0 height in terms of layout.
Without digging further in the issue, a quick workaround for that is simply to unmount the list whenever the visibility of the console is "hidden", so that it remounts when become visible, with a clean layout.
> fix(llm/analyticsconsole): workaround for collapsed items in scrollview

- .github/workflows/test.yml
Split test.yml with UI tests so we can more granularly decide on which runners to 
run the tests. Also killed the libs tests on all OSes, only one is required 
(libcore, still in our <3), but UI libs tests will now run on each OS.
> chore: split ui test from libs tests

- apps/ledger-live-mobile/src/screens/PTX/Earn/index.tsx
LLM doesn't have locales like LLD does so we need to use the `language` to determine the formatting for LLM as before. This PR sets the `language` prop as `locale` for Earn in LLM so we don't need to have specific logic in Earn for LLM and LLD regarding the currency formatting. It also means in future if locales are supported in LLM, it just means changing `locale` prop in the Earn web player from `language` to `locale`
> feat: changing locale prop on the earn app to use the language instead

- .changeset/hot-llamas-run.md
- libs/ledger-live-common/src/families/cosmos/helpers.unit.test.ts
- libs/ledger-live-common/src/families/cosmos/js-synchronisation.ts
- libs/ledger-live-common/src/families/cosmos/js-synchronisation.unit.test.ts
- libs/ledger-live-common/src/families/cosmos/logic.ts
In the response of cosmos events from explorer. The "amount" field string can contain prefix. Our parser should be able to remove this prefix and get the correct amount string. Otherwise, it will cause a bug in the portfolio graph because of the incorrect amount.
It is a problem due to the multi chain rewards update of cosmos. Before the update, we didn't have this prefix as the follows:
```
{
"key": "amount",
"value": "11717uosmo"
},
```
Now we can have prefix of the amount value since multi chain rewards update
```
{
"key": "amount",
"value": "56ibc/0025F8A87464A471E66B234C4F93AEC5B4DA3D42D7986451A059273426290DD5,512ibc/6B8A3F5C2AD51CD6171FA41A7E8C35AD594AB69226438DB94450436EA57B3A89,11717uosmo"
},
```
we should remove the prefix to get the correct value
- …
> Fix: LIVE-8269 cosmos amount string parser

- .changeset/curly-tables-chew.md
- apps/ledger-live-desktop/src/renderer/components/RecoverRestore/index.tsx
Add retry mecanism on error device locked when you try to use Ledger Recover.
Superseeds #4202 
- **Linked resource(s)**: `PROTECT-2292` 
> fix(RecoverRestore): add onRetry to error handling [PROTECT-2292]

- .changeset/cyan-peas-sit.md
- libs/ledger-live-common/src/wallet-api/react.ts
Fix missing new on an error used for `message.sign` when the user cancels the flow
Reported from sentry: https://ledger.sentry.io/issues/4382287269/?project=6488659&query=release%3A2.66.0-next.0&referrer=release-issue-stream
- **Impacted projects**: `ledger-live-desktop` & `ledger-live-mobile` 
> fix(wallet-api): missing new on error constructor

- .changeset/friendly-pumpkins-wonder.md
- libs/ui/packages/icons/package.json
Today we don't add reactLegacy and nativeLegacy in the package but it's needed.
Fix this issue: https://ledger.slack.com/archives/C04CA7UUG9W/p1692180546201699
- **Impacted projects**: `lld` `llm` 
Both folders must be included by the npm package
> Fix reactLegacy and nativeLegacy for icons lib

- .changeset/twenty-apes-sort.md
- apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/EarlySecurityChecks/DeviceNotGenuineDrawer.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/EarlySecurityChecks/ErrorDrawer.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/EarlySecurityChecks/ExitChecksDrawer.tsx
Some refactoring of the error rendering of device actions done in #3909 broke the layout (buttons are pushed to the bottom).
- **Linked resource(s)**: [LIVE-8965] 
[LIVE-8965]: https://ledgerhq.atlassian.net/browse/LIVE-8965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(lld/deviceaction/error): broken layout

- .changeset/breezy-cherries-talk.md
- apps/ledger-live-mobile/src/logic/notifications.tsx
Notifications get re-enabled when updating the app
- **Linked resource(s)**:  [LIVE-8797] 
BUILDS : 
- https://github.com/LedgerHQ/ledger-live-build/actions/runs/5904096063 🍎 
- https://github.com/LedgerHQ/ledger-live-build/actions/runs/5904104923 🤖 
[LIVE-8797]: https://ledgerhq.atlassian.net/browse/LIVE-8797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🐛 [FIX] : Notifications get re-enabled when updating the app

- .github/workflows/test-mobile-e2e.yml
- apps/ledger-live-mobile/.env.mock
- apps/ledger-live-mobile/e2e/helpers.ts
- apps/ledger-live-mobile/e2e/models/accounts/addAccountDrawer.ts
- apps/ledger-live-mobile/e2e/models/passwordEntryPage.ts
- apps/ledger-live-mobile/e2e/models/trade/receivePage.ts
- apps/ledger-live-mobile/e2e/models/trade/swapFormPage.ts
- apps/ledger-live-mobile/e2e/specs/languageChange.spec.ts
- apps/ledger-live-mobile/e2e/specs/market.spec.ts
- apps/ledger-live-mobile/e2e/specs/nftGallery.spec.ts
- apps/ledger-live-mobile/e2e/specs/swap/swap.spec.ts
- apps/ledger-live-mobile/src/screens/Swap/Form/index.tsx
_Aiming to fix flaky detox tests skipped on Android by PR [4133](https://github.com/LedgerHQ/ledger-live/pull/4133)_
- languageChange.spec.ts -> Aspect ratio issue. Fixed by applying Pixel 5 profile.
- market.spec.ts -> Rating pop-up. Fixed by disabling '_ratingsPrompt_' feature flag
- nftGallery.spec.ts ->  Fixed by new deposit flow [PR](https://github.com/LedgerHQ/ledger-live/pull/3928/files#top)
- swap.spec.ts -> Keyboard on CI. Fixed by sending '_\n_' to close keyboard.
[B2CQA-1920]: …
> [B2CQA-1920] Detox : Fix Android Flaky tests

- apps/ledger-live-desktop/src/renderer/components/Select/index.tsx
This PR intends to fix some `ts-expect-error` that appears around the `react-select` library and the way we are using it.
There are 2 more `ts-expect-error` in `apps/ledger-live-desktop/src/renderer/components/Select/index.tsx` but there are pretty hard to fix and would require more time so i'll just open a PR for this fix.
- **Linked resource(s)**: [LIVE-7620] 
[LIVE-7620]: https://ledgerhq.atlassian.net/browse/LIVE-7620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LLD] - [LIVE-7620] - Fixing ts-expect-error's

- .changeset/tender-seahorses-pay.md
- apps/ledger-live-mobile/src/screens/PTX/Earn/index.tsx
Adds safe area inset margin to earn screen to avoid overlapping top bar/ phone notch.
- **Linked resource(s)**: `LIVE-8833` 
> feat: add safe area inset to earn screen

- .changeset/green-games-obey.md
- apps/ledger-live-mobile/src/components/FabActions/FabButtonBar.tsx
- apps/ledger-live-mobile/src/components/wrappedUi/Button.tsx
- libs/ui/packages/native/src/components/cta/Button/index.tsx
* Add `onPressWhenDisabled` prop to native ui component.
* Market detail screen pop will now occur when user clicks on "disabled" looking button.
- **Impacted projects**: `LLM, UI` 
- **Linked resource(s)**: [LIVE-8914](https://ledgerhq.atlassian.net/browse/LIVE-8914) 
https://github.com/LedgerHQ/ledger-live/assets/132384348/40004e82-80d2-4d49-91c4-9d5007a73dfb
[LIVE-8914]: https://ledgerhq.atlassian.net/browse/LIVE-8914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Bugfix/LIVE-8914]: Info message not triggered when user accesses a coin from the Market tab

- .changeset/spotty-pumpkins-sparkle.md
- apps/ledger-live-mobile/src/screens/VerifyAccount/index.tsx
Verifying addresses within a live app would cause a redirection out of the live app for users. In cases where the user was already in a live app like "buy/sell" and was then directed to a provider like "BTCDirect" then the user would be redirected back to the buy/sell app and they were unable to continue with their purchase.
In cases where a user loaded from the discover section they would be redirected back to the discover homepage after they verified their address.
The fix:
- check if we are about to pop from a live app screen. If we are then do not pop, otherwise continue as normal.
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-8928  …
> fix: don't pop from live app when verifying address

- .changeset/fresh-dragons-smile.md
- apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/EarnLiveAppNavigator.tsx
- apps/ledger-live-mobile/src/components/Stake/index.tsx
- apps/ledger-live-mobile/src/components/Stake/useStakingDrawer.tsx
- apps/ledger-live-mobile/src/components/TabBar/TransferDrawer.tsx
- re-use account-specific stake flow navigation functions so that we do not need to navigate to stake flow then skip all of the steps that select an account and close the stake flow;
- Use the stake flow actions directly in the Earn navigator removes the empty navigator modals;
- Other stake flows unaffected.
- **Linked resource(s)**:  https://ledgerhq.atlassian.net/browse/LIVE-9008
Earn dash remains in the background:
In-line with the other screens that use the stake flow from the main navigation or the account pages:
> bugfix: Empty modals when clicking "X" after "Stake" on Earn more rewards tab

- libs/ledger-live-common/src/bridge/react/BridgeSync.tsx
every 20 seconds, Ledger Live log a useless "SYNC_SOME_ACCOUNTS" with the reason "pending-operations" even when you had no accounts with pending operations.
practically it doesn't change anything for the user, but it pollutes the logs. it doesn't change the performance that much but it's just dumb to spam the sync events with these.
- **Impacted projects**: `LLD/LLM` 
- **Linked resource(s)**: `LIVE-9091` 
> chore: prevent SYNC_SOME_ACCOUNTS log with empty accounts[]

- libs/coin-evm/package.json
- libs/coin-evm/src/__tests__/unit/getTransactionStatus.unit.test.ts
- libs/coin-evm/src/getTransactionStatus.ts
- pnpm-lock.yaml
Add (back) the `FeeTooHigh` warning present on the ethereum family on the evm family.
https://github.com/LedgerHQ/ledger-live/blob/42a90710a7c68ea97b2f6867cda603116c76282f/libs/ledger-live-common/src/families/ethereum/modules/send.ts#L384-L386
- Updated tests for `getTransactionStatus` by adding [property based testing](https://fast-check.dev/docs/introduction/why-property-based/) using [fast-check](https://fast-check.dev/)
- Refacto tests for `getTransactionStatus` by using [`describe.each`](https://jestjs.io/docs/api#describeeachtablename-fn-timeout) where suitable to reduce code duplication and improve consistency and readability
- **Impacted projects**: `coin-evm`
- https://ledgerhq.atlassian.net/browse/LIVE-9118
- …
> [BUGFIX][LIVE-9118] add back fee too high warning on evm get transaction status

- .changeset/olive-oranges-know.md
- libs/coin-framework/src/account/serialization.ts
- libs/ledger-live-common/src/families/cosmos/account.ts
- libs/ledger-live-common/src/families/cosmos/datasets/__snapshots__/coreum.integration.test.ts.snap
https://github.com/LedgerHQ/ledger-live/pull/4235 introduced a regression when serializing Operation extra for cosmos.
The root cause is a dumb typo, mixing up the serialized and deserialized variables... False confidence from TS, which was of no help on that mistake. Wondering if the language could help prevent this anyhow :thinking:
Covered by our integration tests, but issue went unnoticed because of them being unstable for other reasons... :disappointed: 
> [bugfix] Fix regression when serializing cosmos operation extra

- pnpm-lock.yaml
- tools/actions/change-product-name/build/main.js
- tools/actions/generate-bot-super-report/action.yml
- tools/actions/generate-bot-super-report/build/main.js
- tools/actions/generate-bot-super-report/logic.ts
- tools/actions/generate-bot-super-report/package.json
- tools/actions/generate-release-message/build/main.js
- tools/actions/get-package-infos/action.yml
- tools/actions/get-package-infos/build/main.js
- tools/actions/get-package-infos/package.json
- tools/actions/get-workflow-artifacts-id/build/main.js
- tools/actions/live-common-affected/build/main.js
- tools/actions/prepare-comment-screenshots/build/main.js
- tools/actions/submit-bot-report/build/main.js
- tools/actions/submit-bot-report/main.ts
- tools/actions/submit-bot-report/package.json
- tools/actions/turbo-affected/build/main.js
- tools/actions/turborepo-gh-cache/build/cleanup.js
- tools/actions/turborepo-gh-cache/build/main.js
- tools/actions/turborepo-gh-cache/build/server.js
- tools/actions/turborepo-s3-cache/build/cleanup.js
- tools/actions/turborepo-s3-cache/build/main.js
- tools/actions/turborepo-s3-cache/build/server.js
- tools/actions/upload-images/action.yml
- tools/actions/upload-images/build/main.js
- tools/actions/upload-images/main.ts
- tools/actions/upload-images/package.json
It seems that some updates to tsup (and maybe isomorphic unfetch), we cannot build some actions anymore. 
Swtiching to node20 as the engine for those specific actions so we can rely on the default `fetch` from node.
- **Impacted projects**: `actions` 
> Update some actions to remove the use of isomorphic-unfetch in favor of `node`'s fetch

- .changeset/ninety-eels-suffer.md
- .changeset/old-keys-complain.md
- libs/ui/packages/react/src/components/form/Checkbox/Checkbox.tsx
While using React UI in the Next Recover project, I noticed a console error on the Checkbox component. The change is made on the parent component. So I added the ReadOnly props to correct the problem
- **Impacted projects**: `react-ui` 
| BEFORE | AFTER |
|:--:|:--:|
| ![image](https://github.com/LedgerHQ/ledger-live/assets/118977988/9ad15140-4760-44bd-9898-2cd708651a8d) | ![image](https://github.com/LedgerHQ/ledger-live/assets/118977988/fd617cd8-436d-4045-bf29-93c10a16b7ec) |
> fix(react-ui): fix checkbox component console error

- libs/ledger-live-common/src/featureFlags/defaultFeatures.ts
- libs/ledger-live-common/src/wallet-api/constants.ts
- libs/ledger-live-common/src/wallet-api/helpers.ts
- Add `evm` to `WALLET_API_FAMILIES` (representing the list of LL cryptos handled by wallet-api)
This is a fixup of [this commit](https://github.com/LedgerHQ/ledger-live/commit/ef171ecf7c7f318f890d819be6b69fd185531939#diff-258e482de005245d8c37bc82a691d6eb884b2bbf1235a2e916feb9c8993efe1cR16) that originally introduced this issue
- Add a default value for the `ptxEarn` feature flag, like this is done for most (all?) of the other feature flags.
It looks like the feature flag is not visible on LL under the _debug_ > _feature flag_ screen otherwise
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-9165
| Before | After |
| <video src="https://github.com/LedgerHQ/ledger-live/assets/9203826/37030c0b-164a-489f-853f …
> [BUGFIX][LIVE-9165] fix request token crypto wallet api

- .changeset/friendly-maps-design.md
- apps/ledger-live-mobile/src/components/FabActions/hooks/useAssetActions.tsx
- apps/ledger-live-mobile/src/components/Toast/PtxToast.tsx
- apps/ledger-live-mobile/src/components/Toast/Toast.tsx
- apps/ledger-live-mobile/src/screens/Account/hooks/useAccountActions.tsx
- Fix where ios ptx alert continued to re-appear when user navigated to other screens.
https://github.com/LedgerHQ/ledger-live/assets/132384348/0814084a-6009-4b04-b8d4-7bb750850785
https://github.com/LedgerHQ/ledger-live/assets/132384348/2d1b88ce-8140-47cb-9bab-4d51e212a77e
> [Bugfix/LIVE-9189]: ios app store alert appearing on navigation change

- .changeset/poor-donuts-swim.md
- apps/ledger-live-mobile/src/screens/SyncOnboarding/SyncOnboardingCompanion.tsx
If the sync onboarding is aborted after the device has been seeded, the device should appear in the list of known devices.
- **Linked resource(s)**: [LIVE-7221] 
https://github.com/LedgerHQ/ledger-live/assets/91890529/3351c63d-104f-42cb-9fe8-43bbcf477937
[LIVE-7221]: https://ledgerhq.atlassian.net/browse/LIVE-7221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(llm/synconboarding): add device to known devices as soon as device is seeded

- .changeset/late-fishes-promise.md
- libs/coin-framework/src/account/serialization.ts
- libs/ledger-live-common/src/families/elrond/account.ts
- libs/ledger-live-common/src/families/elrond/specs.ts
- libs/ledgerjs/packages/cryptoassets/src/currencies.ts
Fix Elrond failed bot tests.
Elrond bot tests failure is related to the following assert in specs.ts:
```
botTest("raw optimistic operation matches", () =>
expect(toOperationRaw(operation)).toMatchObject(opExpected),
);
```
The opExpected includes a unnecessary field: "nftOperations"
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-8495
> Support/LIVE-8495 Fix Elrond bot test

- .github/workflows/bot-staging-explorer-eth.yml
- libs/ledger-live-common/src/bot/cli.ts
Since the `ethereum` family does not exist anymore, replace it's reference in the `update-bot-staging-explorer-eth` job by `evm`
Questions:
Based on the name of the jobs, it seems like we are expecting to test a currency and not a full family.
Does it make sense for [this job](https://github.com/LedgerHQ/ledger-live/blob/develop/.github/workflows/bot-staging-explorer-eth.yml) (as well as for [the bitcoin one](https://github.com/LedgerHQ/ledger-live/blob/develop/.github/workflows/bot-staging-explorer-btc.yml)) to test the whole family or should they rather only test the `ethereum` and `bitcoin` currencies (replacing `BOT_FILTER_FAMILIES: bitcoin` by `BOT_FILTER_CURRENCIES: bitcoin` and `BOT_FILTER_FAMILIES: evm` by `BOT_FILTER_CURRENCIES: ethereum`)?
- **Linked …
> [SUPPORT] update-bot-staging-explorer-eth

- .changeset/light-planes-cry.md
- apps/ledger-live-mobile/src/actions/appstate.ts
- apps/ledger-live-mobile/src/actions/earn.ts
- apps/ledger-live-mobile/src/actions/types.ts
- apps/ledger-live-mobile/src/components/RootNavigator/EarnLiveAppNavigator.tsx
- apps/ledger-live-mobile/src/components/Web3AppWebview/WalletAPIWebview.tsx
- apps/ledger-live-mobile/src/context/AuthPass/index.tsx
- apps/ledger-live-mobile/src/context/RootDrawerContext.tsx
- apps/ledger-live-mobile/src/reducers/appstate.ts
- apps/ledger-live-mobile/src/reducers/earn.ts
- apps/ledger-live-mobile/src/reducers/types.ts
- apps/ledger-live-mobile/src/screens/PTX/Earn/EarnInfoDrawer.tsx
EARN dashboard on Android deep links (e.g. on tapping "Get [coin]" button) were triggering the LLM password lock.`<SkipLock />` does not work in this case because the background state is triggered more than once.
- Adds `isDeepLinking` to state
- Set on when deep link initiated
- Reset to false when earn screen is returned to, or drawer is closed
- **Impacted projects**: `` ledger-live-mobile
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-9180
> fix: add isDeepLinking state to prevent deeplink lock

- apps/ledger-live-desktop/src/renderer/components/LabelInfoTooltip.tsx
- apps/ledger-live-desktop/src/renderer/components/Tooltip.tsx
Fix the display of tooltips in Send flow
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-7958` 
> Tooltip display with LabelInfoTooltip

- apps/ledger-live-mobile/e2e/specs/market.spec.ts
_Since yesterday, Detox E2E mobile market.spec.ts test fails.
We have an error when opening browser to buy nano [link](https://shop.ledger.com/products/ledger-nano-x?utm_source=ledger_live_mobile&utm_medium=buy_from_live&apptracking=false). 
Tested locally on emulator, error happens also when opening directly the link on Google Chrome. No issue on real device._
Disabling test until we find a proper fix.
https://github.com/LedgerHQ/ledger-live/assets/106583189/d7147154-c17e-4e1a-ab57-41c0dfc9bd85
- **Impacted projects**: [`Slack`](https://ledger.slack.com/archives/C030L0D26FN/p1694610593257559) 
_Pull Requests must …
> [B2CQA] Detox disable failing detox market test

- .changeset/neat-colts-glow.md
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/scenes/RestoreWithProtect.tsx
In order to have a better user experience, the text "I don't see Restore with Ledger recover" is replaced by a button.
- **Linked resource(s)**: [protect-2352](https://ledgerhq.atlassian.net/browse/PROTECT-2352) 
| BEFORE | AFTER |
|:--:|:--:|
| ![image](https://github.com/LedgerHQ/ledger-live/assets/118977988/67a4e46f-5204-43fe-87ec-8ec0f820e4e4) | ![image](https://github.com/LedgerHQ/ledger-live/assets/118977988/b63f6bb4-d92b-4cc8-bfb6-63ed879f4d1c) |
> fix(protect-2352): change don't see recover button better ui

- .changeset/neat-insects-sin.md
- apps/ledger-live-desktop/src/renderer/components/PerCurrencySelectAccount/state.ts
- apps/ledger-live-desktop/src/renderer/drawers/DataSelector/SelectAccountAndCurrencyDrawer.tsx
- apps/ledger-live-mobile/src/reducers/accounts.ts
The issue was only visible on mobile but is also prevented on desktop now
The issue was only reproducible when omitting the parent account currency from the currencyIds of the request account query
- **Impacted projects**: `ledger-live-mobile` & `ledger-live-desktop` 
- **Linked resource(s)**: [`LIVE-8954`](https://ledgerhq.atlassian.net/browse/LIVE-8954) 
> fix(wallet-api): request account was not showing token accounts in some cases

- apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/Tutorial/index.tsx
Fix the onboarding loop when we have the Recover upsell.
- **Linked resource(s)**: `https://ledgerhq.atlassian.net/browse/LIVE-9429` 
https://github.com/LedgerHQ/ledger-live/assets/31533861/60a9723f-05bd-43c2-be05-cba79da9b977
> [LIVE-9429] LLD - Onboarding loop Upsell Recover

- .changeset/silent-weeks-repeat.md
- libs/coin-evm/src/__tests__/unit/deviceTransactionConfig.unit.test.ts
- libs/coin-evm/src/deviceTransactionConfig.ts
This PR fixes the forgotten code to migrate from the Ethereum family concerning the `deviceTransactionConfig` in a context where the transaction has not been crafted by Ledger Live
- **Impacted projects**: `@ledgerhq/coin-evm` 
<details>
<summary>Before</summary> 
https://github.com/LedgerHQ/ledger-live/assets/44363395/e484ff3f-e430-4fd5-b5d8-a5774a728330
</details>
<details>
<summary>After</summary>
https://github.com/LedgerHQ/ledger-live/assets/44363395/766fed20-7ee2-4f6a-9592-1fee18e9e345
</details>
> [BUGFIX] - Make deviceTransactionConfig working correctly for Wallet API

- .changeset/swift-items-hear.md
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/EarlySecurityChecks/index.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/EarlySecurityChecks/useChangeLanguagePrompt.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/index.tsx
**Issue**: unseeded Stax device, device not on the "early security checks" screen
When starting the early security checks, there is a race condition that manifests with an error drawer:
https://github.com/LedgerHQ/ledger-live/assets/91890529/a50fb33e-bb3f-4b6d-81c7-6bc33b2304bd
This issue is not blocking but we would rather avoid this.
It is caused by what I added in #4705 (the error handler in the `getDeviceInfo` that is used to determine if the device is in bootloader mode).
**The fix**:
This `getDeviceInfo` was necessary in case the user interrupted the fw update by unplugging the device at the wrong moment, resulting in the device being in bootloader mode. We would perform this check when the `device` object changes (so for instance when the device gets plugged back in). It was …
> Bugfix Stax LLD early security checks race condition

- apps/ledger-live-desktop/.gitignore
- apps/ledger-live-desktop/tools/main.js
to ease the generation of metafiles that can be dropped in https://esbuild.github.io/analyze/ we makes it easier to activate with just an env, instead of having to modify the source code of the build system.
build the LLD app
```
GENERATE_METAFILES=1 pnpm build:lld
```
find in apps/ledger-live-desktop some metafile.*.json files. Typically you can use the renderer one.
- **Impacted projects**: `LLD builds` 
- **Linked resource(s)**: `na` 
> chore: introduce GENERATE_METAFILES for bundle size analyze

- .changeset/old-shirts-doubt.md
- libs/coin-evm/src/__tests__/unit/preload.unit.test.ts
- libs/coin-evm/src/preload.ts
CDN requests were previously cached for 6 hours during `preload`. That change wasn't added to the EVM family after the merge. 
This PR adds the same logic as the one in the Ethereum family.
- **Impacted projects**: `@ledgerhq/coin-evm` 
> [BUGFIX] - Add cache to EVM dynamic CAL requests

- .changeset/thick-icons-pull.md
- apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/PlatformAPIWebview.tsx
- apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/WalletAPIWebview.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/types/AddAccountsNavigator.ts
- apps/ledger-live-mobile/src/components/RootNavigator/types/BaseNavigator.ts
- apps/ledger-live-mobile/src/components/RootNavigator/types/RequestAccountNavigator.ts
- apps/ledger-live-mobile/src/components/Web3AppWebview/PlatformAPIWebview.tsx
- apps/ledger-live-mobile/src/components/Web3AppWebview/helpers.ts
- apps/ledger-live-mobile/src/screens/RequestAccount/02-SelectAccount.tsx
- libs/ledger-live-common/src/wallet-api/react.ts
We had some missing `beforeRemove` to call the `onClose` for the wallet-api and platform-sdk on mobile
This PR also cleans up the `onError` that was not used and replace it by a simple `onClose` used only in the context of the plaform-sdk and wallet-api 
- **Linked resource(s)**: [`LIVE-9487`](https://ledgerhq.atlassian.net/browse/LIVE-9487) 
> fix(LLM): platform-sdk & wallet-api onClose response in `account.request` & `message.sign` [LIVE-9487]

- .changeset/unlucky-cups-hunt.md
- apps/ledger-live-desktop/src/renderer/components/RecoverRestore/index.tsx
During, device pairing, if has an error on lld the previous button redirect to LiveApp disclaimer screen.
- **Linked resource(s)**: [protect-2538](https://ledgerhq.atlassian.net/browse/PROTECT-2538) 
https://github.com/LedgerHQ/ledger-live/assets/118977988/82d5d35d-bde5-4dd6-93d5-9bff0cd634c1
> fix:(protect-2538): previous cta redirect to disclaimer screen

- .changeset/chilly-shoes-do.md
- apps/ledger-live-mobile/src/components/ServicesWidget/Protect/NewProtectState.tsx
the source parameter when redirecting to recovery is no longer necessary. Indeed, they are directly added in the flags functionalities
> chore(recover): remove source query params

- .changeset/purple-lobsters-accept.md
- apps/ledger-live-mobile/src/components/RootNavigator/types/SendFundsNavigator.ts
- apps/ledger-live-mobile/src/components/RootNavigator/types/SignTransactionNavigator.ts
- apps/ledger-live-mobile/src/components/RootNavigator/types/SwapNavigator.ts
- apps/ledger-live-mobile/src/families/evm/EvmCustomFees/Evm1559CustomFees.tsx
- apps/ledger-live-mobile/src/families/evm/EvmCustomFees/EvmLegacyCustomFees.tsx
- apps/ledger-live-mobile/src/families/evm/EvmCustomFees/index.tsx
- apps/ledger-live-mobile/src/families/evm/EvmFeesStrategy.tsx
In the context of the Swap, a transaction might not be containing `gasOptions` yet, making some flow that requires them fail & crash. 
This PR adds them as a fallback prop for the Custom Fee Strategy screen when the transaction doesn't include it already.
https://github.com/LedgerHQ/ledger-live/assets/44363395/aaa40845-9499-464a-88f0-a79912724e75
> [BUGFIX] Add missing GasOptions in Swap flows for Custom Fee Strategy

- .github/workflows/test-desktop.yml
- apps/ledger-live-desktop/tests/fixtures/common.ts
- to be able to investigate playwright runs, we run with VERBOSE and output to a log file.
- the previous "networkResponse.log" is optimized to also use fs.appendFile and not the sync version (fs can be slow)
- optim a bit the github actions
- **Impacted projects**: `playwright lld` 
- **Linked resource(s)**: `na` but in context of Electron update investigation 
> chore(lld): playwright to record logs into a file

- .changeset/rich-buses-help.md
- apps/ledger-live-mobile/src/screens/ReceiveFunds/02-SelectAccount.tsx
LLM - New Receive Flow not masking account values when portfolio is private
- **Linked resource(s)**: [LIVE-9594] 
https://github.com/LedgerHQ/ledger-live/assets/112866305/48dcddcd-1852-4c1a-af88-84b454f4c160
[LIVE-9594]: https://ledgerhq.atlassian.net/browse/LIVE-9594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BUGFIX] : Discreet Mode on Deposit flow

- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/SyncOnboardingCompanion.tsx
To the last step of onboarding stax, we need to set `hasCompletedOnboarding` to `true`
- **Linked resource(s)**: [protect-2575 ](https://ledgerhq.atlassian.net/browse/PROTECT-2575) 
https://github.com/LedgerHQ/ledger-live/assets/118977988/bd0c428b-435a-48f2-8f91-90068e31832d
> bugfix(protect-2575): onboarding stax black screen

- .changeset/dry-numbers-sniff.md
- apps/ledger-live-mobile/src/components/TabBar/TransferDrawer.tsx
- libs/ledger-live-common/src/featureFlags/defaultFeatures.ts
- libs/ledger-live-common/src/hooks/recoverFeatureFlag.ts
- libs/ledgerjs/packages/types-live/src/feature.ts
We need to redirect to specific link on featureflag on quick access recover LiveApp
- **Impacted projects**: `live-mobile` `types-live` `live-common` 
- **Linked resource(s)**: [PROTECT-2592](https://ledgerhq.atlassian.net/browse/PROTECT-2592) 
[PROTECT-2592]: https://ledgerhq.atlassian.net/browse/PROTECT-2592?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(protect-2592): add other link on firebase for quick access recover

- .changeset/poor-moons-jog.md
- apps/ledger-live-mobile/src/screens/Onboarding/steps/protectFlow.tsx
Before onboarding device, we need to allow restore with recover. You have not device selected yet but you can continue restore flow selected recover after login on Ledger Recover.
- **Linked resource(s)**: [PROTECT-2522](https://ledgerhq.atlassian.net/browse/PROTECT-2522) 
https://github.com/LedgerHQ/ledger-live/assets/118977988/96999c81-343e-4687-a3e6-4d713c715948
[PROTECT-2522]: https://ledgerhq.atlassian.net/browse/PROTECT-2522?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1c …
> fix(protect-2522): can restore during onboarding

- .changeset/gorgeous-items-shave.md
- apps/ledger-live-mobile/src/components/DateFormat/FormatDate.tsx
Tap and drag to see price over time on graph is buggy on LLM
- **Linked resource(s)**: [LIVE-8128] 
https://github.com/LedgerHQ/ledger-live/assets/112866305/c48d8a48-c94f-4e83-a631-cfee635218ca
[LIVE-8128]: https://ledgerhq.atlassian.net/browse/LIVE-8128?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BUGFIX] : Tap and drag to see price over time on graph is buggy on LLM

- .changeset/purple-dogs-shake.md
- apps/ledger-live-mobile/src/screens/OperationDetails/Content.tsx
Prevent error in OpDetails for TokenAccounts, using wrong currency with `useNftMetadata` & `useNftCollectionMetadata` hooks (`TokenCurrency` vs `CryptoCurrency`)
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-9628 
> Steps of the non-reg demo:
> - Going into a TokenAccount operation does not break (this is were the error was before, invisible to the end user)
> - Going into an NFT operation still display the correct informations about the NFT: title of the NFT & title of the collection 
https://github.com/LedgerHQ/ledger-live/assets/44363395/2836a98a-9ab0-423d-9cd4-eebbb8ba808d …
> [LIVE-9628] Bugfix - Update currency used in OpDetails NFT hooks with TokenAccount operations

- .changeset/silver-experts-hammer.md
- apps/ledger-live-mobile/src/components/StorylyStories/StoryGroupItem.tsx
Fix thumbnail display in stories
- **Linked resource(s)**: [LIVE-9249](https://ledgerhq.atlassian.net/browse/LIVE-9249) 
https://github.com/LedgerHQ/ledger-live/assets/145363160/80ba3664-0e26-4535-a2e1-44e122a4bdfc
[LIVE-9549]: https://ledgerhq.atlassian.net/browse/LIVE-9549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-9249]: https://ledgerhq.atlassian.net/browse/LIVE-9249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LLM][Stax onboarding] No thumbnail displayed on Stax onboarding for Secret Recovery Phrase stories

- .changeset/old-moons-add.md
- apps/ledger-live-mobile/src/components/CustomImageDeviceAction.tsx
In the custom lock screen device action, in case the user refuses to load / commit the picture on their Stax, we display an error and there is a "save logs" button that should not be present in that case.
- **Linked resource(s)**: [LIVE-6488] 
[LIVE-6488]: https://ledgerhq.atlassian.net/browse/LIVE-6488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(llm/stax/CustomImageDeviceAction): disable renderError "save logs" button

- .github/workflows/generate-screenshots.yml
- .github/workflows/test-desktop-external.yml
- .github/workflows/test-desktop.yml
- tools/actions/composites/setup-test-desktop/action.yml
- tools/actions/composites/setup-toolchain/action.yml
Deactivating the pnpm cache during the macos e2e tests desktop to make sure there are no issues with Electron.Framework when we restore cache.
> Deactivate PNPM cache on Test e2e macOS

- apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/Tutorial/index.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/protectFlow.tsx
Add deeplink event for pairing on ledger-live
> fix(recover): deeplink event pairing device

- apps/ledger-live-mobile/src/screens/PTX/Earn/index.tsx
Add (more) padding at bottom to make "Feedback" button clickable (on more devices).
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-9626
> fix: add more bottom margin on earn screen

- .changeset/sharp-wombats-pull.md
- apps/ledger-live-mobile/src/components/NavigationHeader.tsx
Fix LLM onboarding quizz issue when closing modal
- **Linked resource(s)**: [LIVE-8830] 
[LIVE-8830]: https://ledgerhq.atlassian.net/browse/LIVE-8830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix LLM onboarding quizz issue when closing

- .changeset/cold-rats-sell.md
- apps/ledger-live-desktop/src/renderer/hooks/useNftLinks.ts
- apps/ledger-live-mobile/src/components/Nft/NftLinksPanel.tsx
On LLM and LLD, the "use NFT for Stax custom lock screen" option should be visible only if
- the `customImage` flag is enabled
- AND the user has connected a Stax once
- AND the NFT has some metadata with a picture that can be used as a custom lock screen
builds
- android https://github.com/LedgerHQ/ledger-live-build/actions/runs/6406832356
- ios https://github.com/LedgerHQ/ledger-live-build/actions/runs/6428883444
- lld https://github.com/LedgerHQ/ledger-live/actions/runs/6406844468
- **Impacted projects**: LLM, LLD 
- **Linked resource(s)**: [LIVE-7108] 
https://github.com/LedgerHQ/ledger-live/assets/91890529/a8cf876b-8ecf-4505-b9fa-4396ad80cdb9
https://github.com/LedgerHQ/ledger-live/assets/91890529/5a491f55-7098-437d-af40-9f3c481c67df …
> feat(lld,llm/nft/stax): align custom lock screen entrypoint condition

- apps/ledger-live-desktop/tests/specs/families/ethereum.spec.ts
- apps/ledger-live-desktop/tests/specs/families/polkadot.spec.ts
```
locator.isVisible: Target closed
```
seems to happen from time to time on this test.
as far as i understand, the test actually wasn't properly testing anything, we were expecting the truthyness of the **Promise** and not of the actual boolean it contains. the error that sometimes happens is triggered due to fact the test redeems the DOM which makes the promise eventually will get the unmounting error (target closed) and possibly the test may catch the promise failures (globally?)
- **Impacted projects**: `tests` 
> test: fix an await in the LLD eth tests

- .changeset/sharp-avocados-turn.md
- libs/ledger-live-common/src/wallet-api/logic.ts
Unable to change speed transaction in swap-web-app
Wallet-API fee strategy use upper case while LL is using lower case.
- **Impacted projects**: LLD, LLM (although I do not think no one is using those method yet)
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-9727
> fix: fix walletAPI fee strategy integration

- apps/ledger-live-desktop/src/renderer/animations/index.tsx
Fixes LIVE-9694 by effectively stopping Lottie animations.
- **Impacted projects**: `LLD tests` 
- **Linked resource(s)**: [LIVE-9694] 
[LIVE-9694]: https://ledgerhq.atlassian.net/browse/LIVE-9694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test: fix LIVE-9694

- .github/workflows/build-desktop.yml
as attempt to reduce pressure on our own runners, this set the build-desktop action to use Github's instead of our own runners.
we will see if the build time is fast enough to consider this.
> chore: use github runners for build-desktop on win or mac

- .changeset/early-yaks-protect.md
- libs/ledger-live-common/src/families/cosmos/datasets/__snapshots__/coreum.integration.test.ts.snap
- libs/ledger-live-common/src/families/cosmos/datasets/__snapshots__/cosmos.integration.test.ts.snap
- libs/ledger-live-common/src/families/cosmos/datasets/__snapshots__/seiNetwork.integration.test.ts.snap
- libs/ledger-live-common/src/families/cosmos/js-synchronisation.ts
- libs/ledger-live-common/src/families/cosmos/js-synchronisation.unit.test.ts
This is an attempt to fix "cannot read properties amount of undefined" that happened to 3 users at LLD init
Cannot be reproduced by me or customer support in prod and on develop
At some point I thought it was because a validator/delegation went inactive but the user didn't change his validator for months
Here we cover the only .amount accessible at ledger live initialization other than related to validator
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-9520 
> cosmos handle txs without auth info

- .changeset/sixty-pets-promise.md
- apps/ledger-live-mobile/src/components/BleDevicePairingFlow/BleDevicePairing.tsx
- apps/ledger-live-mobile/src/components/SelectDevice2/index.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Manager/index.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/scenes/BaseStepperView.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/scenes/ConnectNano.tsx
This PR fix the design of new bluetooth pairing error screen using the FF flag `llmNewDeviceSelection `. This screen can appear on **My Ledger**, and during the new **onboarding.**
For the **previous onboarding** flow (Access your wallet -> Connect your ledger -> Pair my nano -> Add with bluetooth), the design is also improved but not totally correct. Since this older flow will be replaced we will not fix it right now.
- **Impacted projects**: `llm`
- **Linked resource(s)**: [LIVE-9554] ; [Figma](https://www.figma.com/file/x9nwU0JtDtyUIhAyBB2El8/Onboarding?type=design&node-id=10078-34306&mode=design&t=RRo0LwguVpuw0RW8-0)
https://github.com/LedgerHQ/ledger-live/assets/35492518/8239f729-43f9-4e5c-ae24-29907d773f14 …
> Bugfix/live 9554 Fix design of bluetooth pairing error screen

- apps/ledger-live-desktop/scripts/beforePack.js
- apps/ledger-live-desktop/tools/main.js
- tools/native-modules-tools/index.js
this is a better version of the fix brought by https://github.com/LedgerHQ/ledger-live/pull/4939 we are reworking the tools to use `fs.promises.cp` instead of a custom implementation of this feature
as suspicion of this to be the reason of macos ci failing, here is a possible fix of copying symlink in the build script.
we are relying on this script at a few places when baking a build of LLD. and it is used in a particular way for playwright too.
- **Impacted projects**: LLD builds and tests 
- **Linked resource(s)**: https://ledgerhq.atlassian.net/browse/LIVE-9602  …
> chore: rework copyFolderRecursively using fs.promises.cp

- .changeset/angry-shirts-explode.md
- .changeset/forty-balloons-invite.md
- apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/ChangeDeviceLanguagePromptDrawer.tsx
- apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/LanguageSelect.tsx
Display appropriate device image in change device language prompt drawer
- **Linked resource(s)**: [LIVE-9388](https://ledgerhq.atlassian.net/browse/LIVE-9388) 
[Demo.webm](https://github.com/LedgerHQ/ledger-live/assets/145363160/4639355f-a931-4e2d-8bf3-48a9bfd4521c)
[LIVE-9388]: https://ledgerhq.atlassian.net/browse/LIVE-9388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIVE-9388][Stax] Modal for device language change when changing LLD language is wrong

- .changeset/little-onions-exercise.md
- .changeset/quick-starfishes-check.md
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/EarlySecurityChecks/index.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/TroubleshootingDrawer.tsx
Display troubleshooting usb drawer instead of locked device drawer if stax is unplugged during genuine check
- **Linked resource(s)**: [LIVE-8686](https://ledgerhq.atlassian.net/browse/LIVE-8686) 
https://github.com/LedgerHQ/ledger-live/assets/145363160/dbec4543-41cc-468b-aebc-7e639605943b
[LIVE-8686]: https://ledgerhq.atlassian.net/browse/LIVE-8686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIVE-8686][STAX ESC] Stax not correctly detected as disconnected if user unplugs during genuine check

- apps/ledger-live-desktop/tests/playwright.config.ts
the macOS CI is sometimes too slow and we can't appreciate if the issue is related to the app not having enough time to load / the test itself OR if it's an actual test bug, so we are going to give more time for the `expect()` to run.
the CI issues appears relatively rarely so the impact of this is very limited, we will almost never reach higher than 30s, but when we do, at least we will know something really is wrong in the test, and not in the CI.
- **Impacted projects**: `playwright tests` 
- **Linked resource(s)**: [na] 
> chore: increase default expect timeout of playwright

- apps/ledger-live-mobile/src/dynamicContent/dynamicContent.tsx
- apps/ledger-live-mobile/src/dynamicContent/types.ts
- apps/ledger-live-mobile/src/dynamicContent/useDynamicContentLogic.ts
- apps/ledger-live-mobile/src/screens/Learn/learn.tsx
- apps/ledger-live-mobile/src/screens/NotificationCenter/Notifications.tsx
Add custom ordering to content cards
When a Braze content card have the property "order", it will be placed before other cards that don't possess this property
Order is as follow : 
First, content cards that have order extra property, ordered by "order" ascending
Then, other content cards, ordered by "createdAt" decreasing
- **Linked resource(s)**: `` https://ledgerhq.atlassian.net/browse/LIVE-8384
> Feat/LIVE-8384 - LLM - Add custom ordering to content cards

- apps/ledger-live-mobile/.gitignore
- apps/ledger-live-mobile/scripts/post.mjs
When reinstalling packages, skip pod reinstall if already there.
before
after
When installing pods, check if cache file exists, compare hashes with the current filesystem, and skip if they are equal.
- **Impacted projects**: `dx` 
> Skip pod reinstall if already there

- tools/actions/composites/setup-toolchain/action.yml
We have an issue with the hashFiles function that can take more than 120s. We only need the pnpm-lock.yaml file to generate a hash from. `**/` search everywhere in the repo while we only need the one at the root.
https://github.com/LedgerHQ/ledger-live/actions/runs/6636764070/job/18029786125
> fix: only use pnpm-lock.yaml for the hash

- .changeset/grumpy-jeans-rule.md
- libs/ledger-live-common/src/wallet-api/CustomLogger/client.ts
Just adding some missing types in the CustomLogger module to improve safety
> refactor: add missing types for the wallet-api CustomLogger

- .changeset/brave-dodos-turn.md
- libs/ledger-live-common/src/deposit/helper.ts
As of today, there is a discrepancy between the `id` returned by the APIs and the one we have in `ledgerjs`. The discrepancy comes from the fact that in `ledgerjs` library currencies id are not lowercase formatted. While waiting for that to be discussed this is a small fix to quick fix the current issue.
- **Impacted projects**: `LL` 
- **Linked resource(s)**: [LIVE-9593] 
Before:
https://github.com/LedgerHQ/ledger-live/assets/25589782/89cd9888-1195-4c38-9e55-b32afa33c3c4
After:
https://github.com/LedgerHQ/ledger-live/assets/25589782/0cd319a4-06d7-4196-8b54-172e75e2d6bd …
> [LL] - [LIVE-9593] - Fix networks not displaying for some tokens on receive and other screens

- .changeset/fresh-squids-cheer.md
- .changeset/poor-cobras-laugh.md
- apps/ledger-live-desktop/src/renderer/Default.tsx
- apps/ledger-live-mobile/src/actions/settings.ts
- apps/ledger-live-mobile/src/actions/types.ts
- apps/ledger-live-mobile/src/components/RootNavigator/index.tsx
- apps/ledger-live-mobile/src/reducers/settings.ts
- apps/ledger-live-mobile/src/screens/Manager/AppsInstallUninstallWithDependenciesContext.ts
- apps/ledger-live-mobile/src/screens/Manager/AppsList/AppInstallButton.tsx
- apps/ledger-live-mobile/src/screens/Manager/AppsList/AppRow.tsx
- apps/ledger-live-mobile/src/screens/Manager/AppsList/AppStateButton.tsx
- apps/ledger-live-mobile/src/screens/Manager/AppsList/AppUninstallButton.tsx
- apps/ledger-live-mobile/src/screens/Manager/AppsScreen.tsx
- apps/ledger-live-mobile/src/screens/Manager/Device/index.tsx
- apps/ledger-live-mobile/src/screens/Manager/Manager.tsx
- apps/ledger-live-mobile/src/screens/Manager/Modals/AppDependenciesModal.tsx
- apps/ledger-live-mobile/src/screens/Manager/Modals/InstallAppDependenciesModal.tsx
- apps/ledger-live-mobile/src/screens/Manager/Modals/InstalledAppsModal.tsx
- apps/ledger-live-mobile/src/screens/Manager/Modals/UninstallAppDependenciesModal.tsx
- apps/ledger-live-mobile/src/screens/Manager/Modals/UninstallDependenciesModal.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/scenes/ConnectNano.tsx
- apps/ledger-live-mobile/src/screens/PairDevices/index.tsx
- libs/ledger-live-common/src/apps/listApps/v2.ts
- libs/ledger-live-common/src/apps/polyfill.ts
- libs/ledger-live-common/src/featureFlags/defaultFeatures.ts
- libs/ledger-live-common/src/manager/api.ts
- libs/ledgerjs/packages/types-live/src/feature.ts
Some breaking changes have been introduced on the Manager API v2 (in staging so far).
Today we are using v1 of the API unless a feature flag `listAppsV2` is enabled, but we should still handle those breaking changes anyway because using the v2 API brings a big network optimisation and we should aim to activate the flag soon.
**Changes in the Manager v2 API (backend)**
- Optimisations
- `/api/v2/apps/hash`: now outputs the apps in the same order as the input which makes it easier for us to use.
- Breaking changes:
- `/api/v2/apps/hash`: now can return some apps as `null` if the hash does not match any app
**Changes in LL (this PR):**
- Both of those API changes are addressed in this PR.
- A new feature flag `listAppsV2minor1` is introduced in order to not activate the old one by mistake …
> Bugfix/live 8698 Manager API v2 breaking changes adaptations

- .changeset/grumpy-adults-warn.md
- .changeset/metal-rats-sell.md
- apps/ledger-live-mobile/src/components/CurrencyGradient.tsx
- apps/ledger-live-mobile/src/components/SelectDevice/BluetoothEmpty.tsx
- apps/ledger-live-mobile/src/components/WalletTab/WalletTabBackgroundGradient.tsx
Background gradient are now adapt to larger phones (ex: samsung fold).
Also fix the nano animation in 'my ledger' tab.
- **Linked resource(s)**: [LIVE-9519] 
Vidéo 'Wallet' tab
[capture fold ui.webm](https://github.com/LedgerHQ/ledger-live/assets/146743014/74ceb904-f32f-4c85-a961-110e1b4713b2)
Capture 'My Ledger' tab
[LIVE-9519]: https://ledgerhq.atlassian.net/browse/LIVE-9519?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): wallet/account gradient displays correctly on large phones (samsung fold)

- tools/native-modules-tools/index.js
it appears that on a second run of `pnpm desktop build:js`, it would fail to copy again a symlink within one of the cp()-ed folder.
we ignore for now the cp if the dest symlink already exists.
- **Impacted projects**: `lld build when you have a cache` 
- **Linked resource(s)**: [n/a] 
> chore: ignore symlink copy of an existing file within the copyFolderRecursively

- tools/actions/composites/upload-allure-report/action.yml
fix this CI warning
```
Allure Reports Export on Server
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/download-artifact@v2. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```
> chore: use download-artifact@v3 to remove a warning

- .changeset/new-squids-hope.md
- apps/ledger-live-desktop/src/renderer/modals/Send/index.tsx
The Send modal is locked on its initial screen while it should be allowed to exit from it freely as long as we haven't entered in the second step of the Send flow.
- **Linked resource(s)**: [LIVE-10016] 
https://github.com/LedgerHQ/ledger-live/assets/25589782/10f49e74-b507-4d9c-9cef-d8475cc73c1b
https://github.com/LedgerHQ/ledger-live/assets/25589782/fd40186c-ff01-4eed-bea4-a32af1594da8
[LIVE-10016]: https://ledgerhq.atlassian.net/browse/LIVE-10016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1K …
> [LLD] - [LIVE-10016] - Fix exit on Send modal

- apps/ledger-live-desktop/tests/models/DeviceAction.ts
deviceActions can very rarely be fast enough for the test not to have opportunity to see the spinner, so we allows this case.
```
Error:   1) accounts/account.spec.ts:18:9 › Accounts @smoke › [BTC] Add account › [BTC] Open device app ───
TimeoutError: locator.waitFor: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator('data-test-id=device-action-loader') to be visible
============================================================
at ../models/DeviceAction.ts:41
39 |     });
40 |
> 41 |     await this.loader.waitFor({ state: "visible" });
|                       ^
42 |     await this.loader.waitFor({ state: "detached" });
43 |   }
44 |
``` …
> test: allow loader not to even have time to appear (LIVE-9623)

- .changeset/brave-rabbits-doubt.md
- apps/ledger-live-desktop/src/renderer/components/MainSideBar/index.tsx
Discover tab can no longer be selected at the same time as the refer a friend one.
- **Linked resource(s)**: [LIVE-8869] 
[LIVE-8869]: https://ledgerhq.atlassian.net/browse/LIVE-8869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(navtabs): refer a friend tab selection no longer select discover tab

- apps/ledger-live-desktop/tests/models/ManagerPage.ts
There is an issue if the firmware update banner appears exactly at the same time as playwright tries to click on the "add" button for the lock screen picture.
The simple fix here is to wait for the banner to be visible before clicking this button.
- **Linked resource(s)**: [LIVE-10030] 
[LIVE-10030]: https://ledgerhq.atlassian.net/browse/LIVE-10030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test(lld/playwright/customImage): avoid firmware update click jacking

- .changeset/tough-ladybugs-do.md
- apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/Welcome/index.tsx
- apps/ledger-live-desktop/static/i18n/en/app.json
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Onboarding/steps/welcome.tsx
- libs/ledger-live-common/src/hooks/recoverFeatureFlag.ts
Remove ' Log in to Ledger Recover' button. 
Deleted code for LLD and commented code for LLM.
- **Linked resource(s)**: [LIVE-9992] 
Before:
After:
[LIVE-9992]: https://ledgerhq.atlassian.net/browse/LIVE-9992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(recover): remove 'Log in to Ledger Recover' button

- .github/workflows/build-desktop.yml
- apps/ledger-live-desktop/tools/main.js
now that renderer bundle size is around 31 MB, we can lock the renderer bundle size to not go higher than 40 MB.
- **Impacted projects**: `LLD build` 
- **Linked resource(s)**: [n/a] 
> chore: lock renderer bundle size to not exceed 40mb

- .changeset/good-mirrors-retire.md
- apps/ledger-live-desktop/src/sentry/install.ts
- apps/ledger-live-mobile/index.js
A `LockedDeviceError` was being sent to Sentry while it represents a behavior errors. After testing, this is just due to a new tracking of errors in [apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/ChangeDeviceLanguagePromptDrawer.tsx](https://github.com/LedgerHQ/ledger-live/blob/b65fc66ae7fbd3c02732862305a2bcc010b249de/apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/ChangeDeviceLanguagePromptDrawer.tsx#L57).
I also added the error `UnresponsiveDeviceError` which represents a locked device error when the device has not been responsive for a certain time (former way to detect a locked device before the response `0x5515`).
And i did the same for LLM.
- **Impacted projects**: `LLD` and `LLM` …
> Fix: added locked device errors to Sentry ignore list

- .changeset/khaki-cups-try.md
- libs/coin-evm/src/__tests__/unit/api/node/ledger.unit.test.ts
- libs/coin-evm/src/__tests__/unit/api/node/rpc.unit.test.ts
- libs/coin-evm/src/__tests__/unit/synchronization.unit.test.ts
- libs/coin-evm/src/api/node/ledger.ts
- libs/coin-evm/src/api/node/rpc.common.ts
- libs/coin-evm/src/api/node/types.ts
- libs/coin-evm/src/editTransaction/getEditTransactionPatch.ts
- libs/coin-evm/src/synchronization.ts
- pnpm-lock.yaml
For some legacy reasons, there is a difference in the response shape of `/blockchain/v4/eth/block/current` and `/blockchain/v4/eth/block/{height}`.
The first endpoint (`/current`) returns a block object in the shape
```
{
"hash": "string",
"height": 1073741824,
"time": "string",
"txs": [
"string"
]
}
```
Whereas the second endpoint (`{height}`) returns an array of block objects (but with only one block inside)
```
[
{
"hash": "string",
"height": 1073741824,
"time": "string",
"txs": [
"string"
]
}
]
```
cf. https://explorers.api.live.ledger.com/blockchain/v4/eth/docs/
The coin-evm implementation assumed both endpoints had the same response shape (the one returning a single object), leading to issues when the block heigh specific endpoint was called (values returned where null.
This PR also …
> [BUGFIX] usage of explorer block endpoint in coin evm

- .changeset/early-squids-think.md
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/EarlySecurityChecks/index.tsx
- apps/ledger-live-desktop/src/renderer/hooks/useNetworkStatus.ts
Improve timeout network down error during ESC:
- creation & usage of `useNetworkStatus` hook that set `networkStatus = 'online'|'offline'` state variable by listening on `window.addEventListener("online"|"offline")`
- adding a condition in `SyncOnboarding/Manual/EarlySecurityChecks/index.tsx` useEffect to display a drawer with `NetworkDown` error
- **Linked resource(s)**: [LIVE-8460] 
https://github.com/LedgerHQ/ledger-live/assets/145363160/5a462bf2-ca83-4b1a-bc23-d1f4fe719271
[LIVE-8460]: …
> [LIVE-8460] LLD - No timeout if user loses connection after Allowing Genuine check

- .changeset/nice-knives-attack.md
- libs/ledger-live-common/src/apps/polyfill.ts
In the "polyfilling" logic of apps data in list apps v2, we were not checking that the `currencyId` coming from the backend was matching a currency locally. This was causing a crash at rendering:
The fix is to only keep the `currencyId` coming from the backend if it actually matches a known currency.
- **Impacted projects**: `common` `llm` `lld` 
- **Linked resource(s)**: [LIVE-10067] 
- [] **Test coverage** 
[LIVE-10067]: https://ledgerhq.atlassian.net/browse/LIVE-10067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(common/listappsv2): don't use currencyId if no matching currency

- libs/coin-framework/jest-global-setup.js
- libs/coin-framework/jest.config.js
- libs/coin-framework/package.json
- libs/coin-framework/src/account/balanceHistoryCache.test.ts
~Update some tests that seem deprecated (for a while).
Was raised by this PR https://github.com/LedgerHQ/ledger-live/pull/4886 but since it's not directly related to this PR, the update is done independently, since it also fails on develop as of today.
Tested on the [last commit](https://github.com/LedgerHQ/ledger-live/commit/a605eb96d6781c7406784c59581cbb604896e95f) that changed these files (cf. [this PR](https://github.com/LedgerHQ/ledger-live/pull/3521)), these tests where already failing back then.~
No changeset added since only updates tests (i.e: dev content, no actual logic update)
EDIT: 
The issue was actually not coming from the tests themselves but from the way the tests are run, and more specifically how timezones are handled.
The CI uses the package.json `test` script to run …
> [SUPPORT] update balanceHistoryCache test

- .changeset/old-laws-melt.md
- libs/ledger-live-common/src/platform/providers/RemoteLiveAppProvider/index.tsx
- libs/ledger-live-common/src/platform/providers/RemoteLiveAppProvider/types.ts
Update the removeLiveApp hook to get a manifest by id to return filtered manifest first.
This has an impact now that we return customized manifest when filtering, we need to return this one in priority.
> fix: remoteLiveApp hook not returning filtered manifest

- .changeset/twelve-singers-jam.md
- apps/cli/README.md
- apps/cli/src/commands-index.ts
- apps/cli/src/commands/listApps.ts
Add listApps command to display all installed apps on device.
You can use `pnpm run:cli listApps` to run the command.
- **Impacted projects**: `cli`
- **Linked resource(s)**: [10079]
https://github.com/LedgerHQ/ledger-live/assets/35492518/3066a822-84b4-404f-81fe-584186849820
> feat(cli): add listApps to display all installed apps on device

- .changeset/late-spiders-battle.md
- apps/ledger-live-desktop/src/renderer/components/QRCodeCameraPickerCanvas.tsx
fix dark mode support of QR Code Camera Picker fallback
PR from https://github.com/LedgerHQ/ledger-live/pull/5330 targeting release
- **Linked resource(s)**: [LIVE-10043] 
[LIVE-10043]: https://ledgerhq.atlassian.net/browse/LIVE-10043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Support/live 10043 fix dark mode support of QR Code Camera Picker fallback

- .changeset/modern-plants-relate.md
- apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/steps/03-step-confirmation.tsx
If the firmware update is interrupted because the device is locked, there should be a retry button in the footer.
- **Linked resource(s)**: [LIVE-9116] 
https://github.com/LedgerHQ/ledger-live/assets/91890529/f7ff6ee8-d902-442d-9973-5836897b237f
[LIVE-9116]: https://ledgerhq.atlassian.net/browse/LIVE-9116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bugfix/live 9116 LLD firmware update: retry button if device is locked

- .changeset/bright-mirrors-protect.md
- apps/ledger-live-mobile/src/components/TabBar/TransferDrawer.tsx
TransferDrawer modifications on Swap/buy popular tag and remove entry for WalletConnect
- **JIRA or GitHub issue**: [LIVE-10094]
- 
---
[LIVE-10094]: https://ledgerhq.atlassian.net/browse/LIVE-10094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [SUPPORT]: TransferDrawer modifications on Swap/buy popular tag and remove entry for WalletConnect

- .changeset/violet-days-beg.md
- apps/ledger-live-mobile/src/screens/PTX/Earn/index.tsx
Android handles webview padding differently from iOS. Padding at the end of the earn dash page was overlapping too much content on Android. 
**BEFORE**
**AFTER**
(Padding has been added to the mobile version of the web app itself, instead.)
screenshots (background blue for clarity):
> fix: platform dependent padding on earn ptx webview

- .changeset/shaggy-bats-behave.md
- apps/ledger-live-mobile/src/components/RootNavigator/types/SendFundsNavigator.ts
- apps/ledger-live-mobile/src/components/RootNavigator/types/SignTransactionNavigator.ts
- apps/ledger-live-mobile/src/components/RootNavigator/types/SwapNavigator.ts
- apps/ledger-live-mobile/src/families/evm/EvmCustomFees/index.tsx
- apps/ledger-live-mobile/src/families/evm/EvmFeesStrategy.tsx
When updating the fees in custom mode for an EVM transaction, clicking on the "Valide Fees" CTA would't do anything (expected behaviour would be to return the fee strategy selection screen with new custom entry selected).
This is happening on `develop` and prod as well and probably originated from the last release merge conflict (cf. https://github.com/LedgerHQ/ledger-live/pull/4905)
This PR fixes this and returns to fee strategy selection screen with the new custom entry selected.
PS: for the swap flow, updating the transaction will redirect to the swap summary screen, which is the expected behaviour as of today.
🎥  Normal flow
| <video src="https://github.com/LedgerHQ/ledger-live/assets/9203826/b9585fd5-f3d6-4acd-b22d-df …
> [BUGFIX][LLM] set custom fees evm flow

- package.json
- pnpm-lock.yaml
ledger live desktop builds regularly fail on the CI due to a library `blake2` that fails to compile due to gyp issues.
It turns out this problematic library is only used by Cardano in https://github.com/cardano-foundation/ledgerjs-hw-app-cardano **for exclusively test purpose**. Therefore we don't need it at all.
Unfortunately, disabling the installation of all "dev deps" of libraries is not something we can easily do right now but at least we can easily disable the compilation of just this unused library. If cardano team can consider a lighter library for their test, it also could be beneficial.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10121
- no impact. this library is …
> chore: disable 'blake2' compilation because problematic unused lib

- .changeset/orange-elephants-sleep.md
- libs/ledger-live-common/src/platform/providers/RemoteLiveAppProvider/index.tsx
Steps to Reproduce:
Open 1inch on LedgerLive 2.71 desktopn with overrided manifests → [change account]
Expected behavior:
All the networks after version 2.71on desktop should be displayed 
Actual behavior:
Only bsc, eth and polygon are displayed
Fix: 
Adding params to the request
- LLD
- LLM
---
> Bugfix: LLD uses Overridden Manifests

- .changeset/orange-elephants-sleep.md
- libs/ledger-live-common/src/platform/providers/RemoteLiveAppProvider/index.tsx
The [following commit](https://github.com/LedgerHQ/ledger-live/commit/7a43ad5cb33cd434c545cee13cd567cb0edf4862) was not included in 2.71, which is why this behavior was broken when tested. However, teh behavior works as expected on develop. #5400 is therefore irrelevant
Fix: 
Reverts LedgerHQ/ledger-live#5400
- **JIRA or GitHub link**: #5400 To be reverted
- **Original and working PR for the feature**: https://github.com/LedgerHQ/ledger-live/commit/7a43ad5cb33cd434c545cee13cd567cb0edf4862
- LLD
- LLM
---
> Revert "Bugfix: LLD uses Overridden Manifests"

- .changeset/lucky-hairs-behave.md
- libs/ledger-live-common/src/families/algorand/bridge/mock.ts
- libs/ledger-live-common/src/families/crypto_org/js-getTransactionStatus.ts
- libs/ledger-live-common/src/families/internet_computer/bridge/account.ts
- libs/ledger-live-common/src/families/near/js-getTransactionStatus.ts
- libs/ledger-live-common/src/families/solana/js-prepareTransaction.ts
- libs/ledger-live-common/src/families/stacks/bridge/account.ts
- libs/ledger-live-common/src/families/stellar/js-getTransactionStatus.ts
- libs/ledger-live-common/src/families/tron/bridge/js.ts
When user input an incorrect address in the send crypto modal in LLD/LLM
Users may see an error: 
This is not a valid {{currencyName}} address
We should replay the {{currencyName}} with the real crypto asset name.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10046
The screenshot after my fix
---
> LIVE-10046 Fix invalid address message wording

- .changeset/silver-lamps-warn.md
- apps/ledger-live-desktop/static/i18n/en/app.json
- apps/ledger-live-mobile/src/locales/en/common.json
- libs/coin-evm/src/__tests__/unit/api/node/ledger.unit.test.ts
- libs/coin-evm/src/api/node/ledger.ts
- libs/ledger-live-common/src/exchange/swap/hooks/useSwapTransaction.ts
- libs/ledgerjs/packages/errors/src/index.ts
- Add 10 second timeout to `estimate-gas` evm endpoint.
- Convert error message in swap app to display correct message.
- **Impacted projects**: `LLM,LLC,LLD` 
> [feat/LIVE-8381]: add 10s timeout on estimate gas calls for

- .changeset/real-berries-suffer.md
- apps/ledger-live-desktop/src/renderer/components/Onboarding/Help/RecoverySeed.tsx
Allow text to break in onboarding link, thus fixing long text in link getting cropped
Before: 
After:
- **JIRA or GitHub issue**: LIVE-8007 
- 
---
> Bugfix/LIVE-8007 - LLD - Allow text to break in onboarding link

- .changeset/violet-bulldogs-pull.md
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/EarlySecurityChecks/index.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/index.tsx
Fix disconnected device drawer during stax ESC
- **Linked resource(s)**: [LIVE-8781] 
https://github.com/LedgerHQ/ledger-live/assets/145363160/be44601a-ac29-4205-abef-4d6e00aab7d1
[LIVE-8781]: https://ledgerhq.atlassian.net/browse/LIVE-8781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIVE-8781][LLD][Stax ESC] Wrong drawer displayed when Stax is disconnection

- .changeset/giant-stingrays-train.md
- .changeset/many-ravens-rhyme.md
- apps/ledger-live-desktop/src/renderer/screens/account/AccountHeaderActions.tsx
- apps/ledger-live-mobile/src/components/CurrencyHeaderLayout.tsx
- apps/ledger-live-mobile/src/screens/Account/AccountHeader.tsx
- apps/ledger-live-mobile/src/screens/Account/AccountHeaderLeft.tsx
- apps/ledger-live-mobile/src/screens/Account/AccountHeaderRight.tsx
- apps/ledger-live-mobile/src/screens/Account/hooks/useAccountActions.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/Header.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/WalletConnectHeader.tsx
- apps/ledger-live-mobile/src/screens/WalletCentricAsset/hooks/useWalletConnectAction.ts
- libs/ledger-live-common/.unimportedrc.json
- libs/ledger-live-common/src/walletConnect/index.ts
Wallet Connect CTA was displayed in the Earn section on supported account page (ETH, BSC and Matic)
Demo 
https://github.com/LedgerHQ/ledger-live/assets/112866305/c1d4610c-1378-46e5-a55c-70e47caa4b0d
- **JIRA or GitHub link**: [LIVE-10088]
---
[LIVE-10088]: https://ledgerhq.atlassian.net/browse/LIVE-10088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BUGFIX] : Wallet Connect CTA was displayed in the Earn section on supported account page, now it's on the Asset & Account header page when supported

- .changeset/cool-lemons-develop.md
- libs/ledger-live-common/src/deviceSDK/tasks/core.test.ts
Support: fixing flaky tests
We wanted to randomly test a number of retries, but this was taking more time than the allowed Jest timeout (5000ms)
- **JIRA or GitHub link**: [LIVE-10155](https://ledgerhq.atlassian.net/browse/LIVE-10155)
- 
---
[LIVE-10155]: https://ledgerhq.atlassian.net/browse/LIVE-10155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-10155/Chore: mocking RxJS timer in unit tests

- .changeset/khaki-clocks-tap.md
- apps/ledger-live-desktop/package.json
- apps/ledger-live-desktop/tests/utils/waitFor.ts
- pnpm-lock.yaml
we're notably interested by these bug fixes:
- Fixed an issue where WebViews could sometimes crash on unload. [#40444](https://github.com/electron/electron/pull/40444) (Also in [26](https://github.com/electron/electron/pull/40443), [28](https://github.com/electron/electron/pull/40445))
- Fixed rendering on Linux due to broken shader cache compilation with driver updates. [#40467](https://github.com/electron/electron/pull/40467)
- **JIRA or GitHub link**:  n/a 
- LLD only
- there should be no impact for the user apart from bugfix brought by electron patch release
---
> chore: update Electron to 27.0.4

- apps/ledger-live-mobile/e2e/helpers.ts
- apps/ledger-live-mobile/e2e/models/stake.ts
- apps/ledger-live-mobile/e2e/models/wallet/portfolioPage.ts
- apps/ledger-live-mobile/e2e/specs/delegate/cosmos.spec.ts
- apps/ledger-live-mobile/src/families/cosmos/DelegationFlow/01-Started.tsx
- apps/ledger-live-mobile/src/families/cosmos/DelegationFlow/02-Summary.tsx
- apps/ledger-live-mobile/src/families/cosmos/shared/02-SelectAmount.tsx
- libs/ledger-live-common/src/families/cosmos/bridge/mock.ts
- libs/ledger-live-common/src/families/cosmos/datasets/__snapshots__/dydx.integration.test.ts.snap
_First Detox Cosmos delegation test. Delegate flow using half amount._
This the LLM equivalent of https://github.com/LedgerHQ/ledger-live/pull/4276
1- https://ledgerhq.atlassian.net/browse/B2CQA-384
2- https://ledgerhq.atlassian.net/browse/B2CQA-1614
3- https://ledgerhq.atlassian.net/browse/B2CQA-1552
4- https://ledgerhq.atlassian.net/browse/B2CQA-1900 
> [B2CQA-387] first detox cosmos delegation tests

- .changeset/cyan-balloons-sleep.md
- apps/ledger-live-desktop/src/renderer/screens/accounts/AccountList/DisplayOptions.tsx
Accounts view: Range and Sort by were reversed
- **JIRA or GitHub link**: [LIVE-10103] 
---
[LIVE-10103]: https://ledgerhq.atlassian.net/browse/LIVE-10103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BUGFIX] : Accounts view: Range and Sort by were reversed 🐛

- apps/ledger-live-mobile/src/screens/OperationDetails/Content.tsx
Fix _Cannot read property 'EditOperationPanel' of undefined_ error causing a crash on LLM
- https://ledgerhq.atlassian.net/browse/LIVE-10206
- LLM, when opening a non evm tx operation details, the app does not crash
---
> [BUGFIX][LIVE-10206] App crash on LLM when viewing non evm operations details

- .changeset/itchy-islands-marry.md
- apps/ledger-live-mobile/src/components/QueuedDrawer.tsx
- apps/ledger-live-mobile/src/context/AuthPass/index.tsx
Close drawer on lock screen. 
Not optimal since we would have preferred to keep the drawer open for after the login. But since we use a react-native-modal nothing can be displayed over it (CF: [stackoverflow](https://stackoverflow.com/questions/39766350/bring-view-on-top-of-modal-using-zindex-style-with-react-native)).
It is also possible to open a drawer from the auth screen with the 'i lost my password' button making it hard to find an adequate solution.
- **Linked resource(s)**: [LIVE-9178] 
https://github.com/LedgerHQ/ledger-live/assets/146743014/9b86bd7a-d0fa-4940-9a19-f91ca3880c4f
_Pull Requests must pass the …
> fix(drawer): close drawer when arriving on auth screen

- .changeset/heavy-mails-grow.md
- apps/ledger-live-mobile/ios/Podfile.lock
- apps/ledger-live-mobile/package.json
- pnpm-lock.yaml
LLM - Fixed unresponsive export logs on android 14
- **JIRA or GitHub link**: [LIVE-10111]
- 
---
[LIVE-10111]: https://ledgerhq.atlassian.net/browse/LIVE-10111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LLM - Fix unresponsive export logs

- libs/ledger-live-common/src/bridge/react/BridgeSync.test.tsx
we like bugfixes that are already fixed. I added a test that confirm it is fixed.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-3221 
- no changes
---
> test(BridgeSync): add a test that confirm LIVE-3221 is already fixed

- .changeset/angry-bulldogs-dress.md
- libs/ledger-live-common/src/families/evm/platformAdapter.test.ts
- libs/ledger-live-common/src/families/evm/platformAdapter.ts
- libs/ledger-live-common/src/families/evm/walletApiAdapter.test.ts
- libs/ledger-live-common/src/families/evm/walletApiAdapter.ts
Use `DEFAULT_NONCE` when wallet-api evm tx nonce not provided.
Side note: these 2 adapters should maybe be reworked in the future to make use of the Bridge rather than creating raw tx objects, to avoid similar issues in the future 🤔 
cc. @LedgerHQ/wallet-api @sprohaszka-ledger 
- https://github.com/LedgerHQ/ledger-live/pull/4886
- wallet-api sign methods (with our without nonce provided) should work fine
- for example this one `walletAPI.transaction.signAndBroadcast( ... ) // without nonce`
---
> [BUGFIX] use DEFAULT_NONCE when wallet-api evm tx nonce not provided

- apps/ledger-live-desktop/index-types.d.ts
- apps/ledger-live-desktop/src/renderer/modals/ExchangeDeviceConfirm/index.tsx
- apps/ledger-live-desktop/tests/specs/services/liveapp-sdk.spec.ts
- apps/ledger-live-desktop/tests/specs/services/wallet-api.spec.ts
Fixing some flakiness in the live-app sdk test, it was using a timeout to close the modal and imitate a validation on the device.
Here we instead use the complete mocked event to wait on the test to be finish with the screenshot.
- **JIRA or GitHub link**: [LIVE-10145](https://ledgerhq.atlassian.net/browse/LIVE-10145)
---
[LIVE-10145]: https://ledgerhq.atlassian.net/browse/LIVE-10145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test: fix live-app flaky test [LIVE-10145]

- tools/actions/desktop-build-checks/build/main.js
- tools/actions/desktop-build-checks/src/main.ts
when Ledger Live Builds report some lib duplicates, it will now link to the documentation in order to guide to fix it.
- **JIRA or GitHub link**: na 
- only CI impact
---
> chore: link to doc to manage duplicates

- .changeset/real-rockets-join.md
- apps/ledger-live-mobile/src/screens/PTX/Earn/index.tsx
|        Navigating to Earn dashboard shows App Not Found error page briefly before the app manifest was updated. This seemed to be caused by the re-render of the component when updating state, as the live app state was loaded but the manifest was not yet set.        |        Navigating no longer shows the App Not Found. The screen is now memoised, so should not re-render as often, minimising risk of re-setting the manifest.        |
- **JIRA or GitHub link**: LIVE-9844 https://ledgerhq.atlassian.net/browse/LIVE-9844
- Navigating to Earn should no longer briefly show the App Not Found error page
- Navigating to other pages from earn, …
> fix: earn app not found earn live-9844

- .changeset/wicked-actors-sleep.md
- libs/coin-framework/src/derivation.test.ts
- libs/coin-framework/src/derivation.ts
After the Ethereum to EVM merge, we forgot to do the migration of legacy derivation paths which was based on "family" name. 
This PR cleans a little bit the `getDerivationModesForCurrency` method and adds the missing `ethM` `ethMM` & `etcM` derivations paths for Ethereum & Ethereum Classic
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10215
- Ethereum & Ethereum classic can now "discover" legacy accounts
---
> [LIVE-10215] BUGFIX - Fix legacy derivation paths missing for Ethereum & Classic

- libs/ledger-live-common/src/families/evm/platformAdapter.test.ts
- libs/ledger-live-common/src/families/evm/platformAdapter.ts
- libs/ledger-live-common/src/families/evm/walletApiAdapter.test.ts
- libs/ledger-live-common/src/families/evm/walletApiAdapter.ts
Cherry-pick of [this PR's](https://github.com/LedgerHQ/ledger-live/pull/5482) fix on develop to not block related developments while release is in progress
- https://github.com/LedgerHQ/ledger-live/pull/5482
- wallet-api sign methods (with our without nonce provided) should work fine
- for example this one walletAPI.transaction.signAndBroadcast( ... ) // without nonce
---
> [BUGFIX][DEVELOP] use DEFAULT_NONCE when wallet-api evm tx nonce not provided

- .changeset/hot-birds-hug.md
- apps/ledger-live-mobile/src/screens/FirmwareUpdate/useUpdateFirmwareAndRestoreSettings.ts
- libs/ledger-live-common/src/deviceSDK/commands/firmwareUpdate/installFirmware.ts
- libs/ledger-live-common/src/deviceSDK/commands/toggleOnboardingEarlyCheck.test.ts
- libs/ledger-live-common/src/deviceSDK/tasks/core.ts
- libs/ledger-live-common/src/deviceSDK/tasks/toggleOnboardingEarlyCheck.ts
- libs/ledger-live-common/src/deviceSDK/transports/core.ts
- libs/ledger-live-common/src/exchange/platform/transfer/completeExchange.ts
- libs/ledger-live-common/src/exchange/swap/completeExchange.ts
- libs/ledger-live-common/src/exchange/swap/initSwap.ts
- libs/ledger-live-common/src/hw/actions/transaction.ts
- libs/ledger-live-common/src/hw/connectApp.ts
- libs/ledger-live-common/src/hw/connectManager.ts
- libs/ledger-live-common/src/hw/deviceAccess.ts
- libs/ledger-live-common/src/hw/getDeviceInfo.ts
- libs/ledger-live-common/src/hw/installLanguage.ts
- libs/ledger-live-common/src/hw/staxFetchImage.ts
- libs/ledger-live-common/src/hw/staxLoadImage.ts
- libs/ledger-live-common/src/hw/uninstallLanguage.ts
- libs/ledger-live-common/src/manager/api.ts
- libs/ledgerjs/packages/errors/README.md
- libs/ledgerjs/packages/errors/src/index.test.ts
- libs/ledgerjs/packages/errors/src/index.ts
- chore: refactoring TransportStatusError: refactor into a real class in order to improve TS inference
- add regression testing on TransportStatusError
- cleaner `LockedDeviceError` and mapping
<details>
<summary>Demo Android - Error successfully mapped</summary>
https://github.com/LedgerHQ/ledger-live/assets/15096913/0daa8aa5-5bb9-4aa4-992d-1afd6a9d5ddf
</details>
- **JIRA or GitHub link**: [LIVE-10162](https://ledgerhq.atlassian.net/browse/LIVE-10162)
[LIVE-10162]: https://ledgerhq.atlassian.net/browse/LIVE-10162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-10162/Chore: refactoring TransportStatusError

- .changeset/big-seahorses-mate.md
- apps/ledger-live-mobile/src/components/RecoverBanner/index.tsx
- apps/ledger-live-mobile/src/components/RecoverBanner/types.ts
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/screens/Portfolio/ReadOnly/index.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/index.tsx
- apps/ledger-live-mobile/src/store.ts
- libs/ledger-live-common/src/featureFlags/defaultFeatures.ts
- libs/ledger-live-common/src/hooks/recoverFeatureFlag.ts
- libs/ledgerjs/packages/types-live/src/feature.ts
Manage banner of ledger recover subscription flow.
I use walletApi storage to set values on liveApp and get it on LLD.
This banner is displayed only if some values are defined on liveApp.
You can enable or disable banner with protectServiceDesktop featureFlags with `bannerSubscriptionNotification`
- 
---
> feat(live-9396): recover llm banner subscription notification portfolio

- .changeset/funny-terms-collect.md
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx
Move swap-web-app cacheKey from input to hash to avoid refresh swap-web-app with any change in params.
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/LIVE-10073
- 
---
> fix: move swap-web-app cacheKey from input to hash

- .changeset/ten-cheetahs-allow.md
- libs/ledger-live-common/src/deviceSDK/actions/getLatestAvailableFirmware.test.ts
- libs/ledger-live-common/src/deviceSDK/tasks/core.test.ts
- libs/ledger-live-common/src/deviceSDK/tasks/core.ts
Part of https://github.com/LedgerHQ/ledger-live/pull/5413
Chore: refactoring deprecated `retryWhen` in `libs/ledger-live-common/src/deviceSDK/tasks/core.ts`
<details>
<summary>Demo Android - FW update success</summary>
https://github.com/LedgerHQ/ledger-live/assets/15096913/cfb8f1f2-a377-4a6d-b974-791a9440cc74
</details>
- **JIRA or GitHub link**: [LIVE-10155](https://ledgerhq.atlassian.net/browse/LIVE-10155)
---
[LIVE-10155]: https://ledgerhq.atlassian.net/browse/LIVE-10155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LIVE-10155/Chore: refactoring deprecated retryWhen

- .changeset/gentle-cups-remember.md
- libs/ledger-live-common/jest.config.ts
- libs/ledger-live-common/src/families/bitcoin/walletApiAdapter.test.ts
- libs/ledger-live-common/src/families/bitcoin/walletApiAdapter.ts
- libs/ledger-live-common/src/families/evm/walletApiAdapter.test.ts
- libs/ledger-live-common/src/families/evm/walletApiAdapter.ts
- libs/ledger-live-common/src/families/polkadot/walletApiAdapter.test.ts
- libs/ledger-live-common/src/families/polkadot/walletApiAdapter.ts
- libs/ledger-live-common/src/families/ripple/walletApiAdapter.test.ts
- libs/ledger-live-common/src/families/ripple/walletApiAdapter.ts
- libs/ledger-live-common/src/wallet-api/converters.test.ts
- libs/ledger-live-common/src/wallet-api/converters.ts
- libs/ledger-live-common/src/wallet-api/logic.ts
- libs/ledger-live-common/src/wallet-api/types.ts
- Use the currencies createTransaction function in their walletApiAdapter implementation instead of creating tx by hand
- in order to improve consistency across the Ledger Live codebase and properly convert incoming tx (in this case from wallet-api) to the appropriate Ledger Live data model
- Update tests and add missing test cases
Seems relevant to avoid unexpected side effects like the one introduced by this commit (4cce42dfceff3170faac78ee0810cdbf11f7bb35) and fixed [here](https://github.com/LedgerHQ/ledger-live/pull/5482) 
- https://ledgerhq.atlassian.net/browse/LIVE-10233
- https://github.com/LedgerHQ/ledger-live/pull/5482
- wallet-api related flows, mainly using the `evm`, `bitcoin` and …
> [SUPPORT] use currencies createTransaction in walletApiAdapter

- .changeset/honest-schools-rule.md
- apps/ledger-live-desktop/src/renderer/components/RecoverRestore/index.tsx
- apps/ledger-live-desktop/tests/specs/recover/recover.spec.ts
Add nanoSP support in the restore flow of Recover on LLD
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/PROTECT-1990
---
> feat(LLD): add nanoSP support in recover restore [PROTECT-1990]

- .changeset/gentle-tips-turn.md
- libs/coin-polkadot/src/deviceTransactionConfig.ts
- libs/coin-polkadot/src/js-buildTransaction.ts
Following an update of the Polkadot protocol, this PR removes the `controller` arg from the calls in our Polkadot integration.
- https://ledgerhq.atlassian.net/browse/LIVE-8064
- https://github.com/paritytech/substrate/pull/14039
- Polkadot integration on LLD and LLC
- The staking feature of the Polkadot coin should still work fine
---
> [FEATURE] Polkadot network upgrade: sunset of stash/controller feature 

- .changeset/little-laws-hang.md
- apps/ledger-live-desktop/src/main/window-lifecycle.ts
- properly type webPreferences
- that typing detected that `blinkFeatures` were no longer relevant. as it's not even a field. (old things from the past)
- `nativeWindowOpen` is apparently not available neither.
- `experimentalFeatures` also shouldn't be needed for us.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-9768
- general non regression. only should affect the renderer side. the automatic tests should cover most.
---
> chore(lld): improve webPreferences typing and document

- .changeset/cyan-students-visit.md
- apps/ledger-live-desktop/src/renderer/components/Carousel/index.tsx
TypeError Cannot destructure property ‘Component’ of ‘n[Y]’ as it is undefined was showing up on some times in Carousel
Related to this error 
- **JIRA or GitHub link**: [LIVE-10306] 
- 
---
[LIVE-10306]: https://ledgerhq.atlassian.net/browse/LIVE-10306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BUGFIX] : LLD was showing an error page : TypeError Cannot destructure property ‘Component’ of ‘n[Y]’ as it is undefined

- .changeset/pretty-poems-lie.md
- apps/ledger-live-mobile/src/components/RootNavigator/CustomImageNavigator.tsx
- apps/ledger-live-mobile/src/screens/CustomImage/ErrorScreen.tsx
Only allow one error page in navigation so going back return to the previous page.
Before
https://github.com/LedgerHQ/ledger-live/assets/146743014/974e9a79-eace-498b-a4d9-88f6bc6f6f49
After
https://github.com/LedgerHQ/ledger-live/assets/146743014/95089369-8154-41e9-9d90-818dc898e2e1
LLM
[LIVE-7703](https://ledgerhq.atlassian.net/browse/LIVE-7703?filter=13654)
- Reforge the navigation history to only keep the last error page
---
[LIVE-7703]: https://ledgerhq.atlassian.net/browse/LIVE-7703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(stax): loading multiple invalid pictures and going back will navigate on correct page

- .changeset/nasty-needles-sell.md
- apps/ledger-live-mobile/src/components/CameraScreen/index.tsx
- apps/ledger-live-mobile/src/components/NavigationHeaderCloseButton.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx
- apps/ledger-live-mobile/src/components/RootNavigator/ImportAccountsNavigator.tsx
- apps/ledger-live-mobile/src/components/Scanner.tsx
There was  2 X icons to close when scanning QR code on Send
- **JIRA or GitHub link**: [LIVE-10250]
- 
---
[LIVE-10250]: https://ledgerhq.atlassian.net/browse/LIVE-10250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BUGFIX] : 2 X icons to close when scanning QR code on Send

- .changeset/sharp-pandas-dance.md
- apps/ledger-live-desktop/src/renderer/families/cardano/Delegation/Row.tsx
- libs/ledger-live-common/src/families/cardano/deviceTransactionConfig.ts
- libs/ledger-live-common/src/families/cardano/js-synchronisation.ts
- libs/ledger-live-common/src/families/cardano/js-synchronisation.unit.test.ts
Fix cardano spendable balance on LLD as it included twice the reward
Fix cardano amount on last step before signing
Integration tests fail the same way on develop : https://github.com/LedgerHQ/ledger-live/actions/runs/6967769829/job/18960305105
Adding unit test for the utxo sum is really difficult as I don't know the specifics on utxos/internalcredential/paymentCred thing
- **JIRA or GitHub link**: [https://ledgerhq.atlassian.net/browse/LIVE-9913](https://ledgerhq.atlassian.net/browse/LIVE-9913), [https://ledgerhq.atlassian.net/browse/LIVE-10253](https://ledgerhq.atlassian.net/browse/LIVE-10253)
- Send max amount on confirmation with device screen
- Available balance
---
- [] **The code aligns with …
> fix cardano send max and spendable balance

- .changeset/hungry-countries-compare.md
- libs/ledger-live-common/src/currencies/mock.ts
- libs/ledgerjs/packages/cryptoassets/src/currencies.ts
Update the NEAR explorer view to https://nearblocks.io/ since the originally used one will be deprecated early 2024.
- https://ledgerhq.atlassian.net/browse/LIVE-10320
- On LLD and LLM, in the transaction details screen, the CTA to view the transaction in block explorer should now redirect to https://nearblocks.io/ instead of https://explorer.near.org
---
> [FEAT][LIVE-10320] update near explorer views urls

- .changeset/lucky-buttons-rush.md
- apps/ledger-live-mobile/src/context/AuthPass/AuthScreen.tsx
- apps/ledger-live-mobile/src/index.tsx
LL Welcome Page Partially in EN when a PWD is set and you are in other language 
- you needed to focus input to have translations updated
https://github.com/LedgerHQ/ledger-live/assets/112866305/756bd346-1dea-44ba-ba02-85a369bb42b1
- **JIRA or GitHub link**: [LIVE-10334] 
- 
---
[LIVE-10334]: https://ledgerhq.atlassian.net/browse/LIVE-10334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BUGFIX] : LL Welcome Page Partially in EN when a PWD is set and you are in other language

- .changeset/tame-schools-float.md
- libs/ledger-live-common/src/families/cosmos/js-buildTransaction.test.ts
- libs/ledger-live-common/src/families/cosmos/js-buildTransaction.ts
- libs/ledger-live-common/src/families/cosmos/js-prepareTransaction.ts
- libs/ledger-live-common/src/families/cosmos/js-signOperation.ts
Replace toString by toFixed method on transaction amounts, on a coin with 18 magnitude, it causes problem by adding the exponential part to numbers as string. It starts being a problem with atleast 1000 value
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10287 , https://ledgerhq.atlassian.net/browse/LIVE-10354
- 
---
> fix big transactions cosmos

- .changeset/heavy-pears-own.md
- apps/ledger-live-desktop/src/renderer/actions/general.ts
- apps/ledger-live-desktop/src/renderer/components/Breadcrumb/AssetCrumb.tsx
- apps/ledger-live-desktop/src/renderer/screens/dashboard/AssetDistribution/index.tsx
- apps/ledger-live-desktop/static/i18n/en/app.json
"Hide empty token accounts" setting or "Hide token" hides accounts from your account page, but not from the main Portfolio page, now it's fixed 
https://github.com/LedgerHQ/ledger-live/assets/112866305/d9c46102-2900-471f-b822-9fec27419276
- **JIRA or GitHub link**: [LIVE-7394]
- 
---
[LIVE-7394]: https://ledgerhq.atlassian.net/browse/LIVE-7394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BUGFIX]: Hide empty token accounts- setting or -Hide token- hides correctly accounts in App

- .changeset/late-apples-complain.md
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/scenes/ConnectNano.tsx
The problem is only happening for Nano X when connected via USB. 
And it was due to a bad naming, and probably a wrong strategy to detect if the device is connected via USB or BLE and what to do with it (we were just looking at which device model was selected on the app, and not how the device was actually connected).
The fix: filtering USB device by their id and not according to their model 
<details>
<summary>Quick win with Nano X + Android + USB</summary>
https://github.com/LedgerHQ/ledger-live/assets/15096913/a901effd-3099-4cf9-8b30-778e62d84f2e
</details>
Other videos (of different scenarios) can be found starting at [this comment](https://ledgerhq.atlassian.net/browse/LIVE-4618?focusedCommentId=382942) …
> Fix: Genuine check is skipped over USB

- .changeset/long-grapes-serve.md
- apps/ledger-live-desktop/src/renderer/components/DeviceAction/index.tsx
- apps/ledger-live-desktop/src/renderer/components/DeviceAction/utils.ts
- apps/ledger-live-desktop/src/renderer/components/RecoverRestore/index.tsx
- Allow restore flow recover with LNS+ previous version
- [JIRA PROTECT-2846](https://ledgerhq.atlassian.net/browse/PROTECT-2846)
- 
---
> fix(protect-2846): allow restore on lns+

- .changeset/sharp-pans-poke.md
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.tsx
- Re-add customDappUrl for non moonpay redirection providers.
- 
---
> bugfix: customDappUrl for non moonpay redirect providers

- .changeset/many-toys-know.md
- libs/ledger-live-common/src/deposit/api.ts
- libs/ledger-live-common/src/deposit/deposit.integration.test.ts
- libs/ledger-live-common/src/deposit/deposit.test.ts
- libs/ledger-live-common/src/deposit/helper.ts
- libs/ledger-live-common/src/deposit/type.ts
- libs/ledger-live-common/src/deposit/useGroupedCurrenciesByProvider.hook.ts
- fixes the order display bug, by using Map instead of objects. Map preserves the insertion order unlike JS Object. Performance should slightly be improved as well. There are other areas of performance improve that has been documented as tasks (and linked with FIXMEs)
- simplify the codebase of the useGroupedCurrenciesByProvider hook
- add an integration test that was revealing the issue
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10244 
- LLM deposit flow, currencies order list
---
> fix(deposit): fixes currencies ordering of deposit flow

- .changeset/lemon-students-cheat.md
- .changeset/twelve-nails-dance.md
- apps/ledger-live-desktop/src/sentry/install.ts
- apps/ledger-live-mobile/index.js
- libs/ledger-live-common/src/manager/hooks.ts
[An error appeared on Sentry](https://ledger.sentry.io/issues/4703029917/events/ae67c61e64a7466db7949a7975fa2f60/?project=6488659) for the latest LLD pre-release builds (2.73.0-next.0 and 2.73.0-next.1).
Basically it’s an uncaught exception in a promise in the hook `useAvailableLanguagesForDevice` that is used notably in the “language settings” section.
It will be triggered every time a user with a wrong value for “My Ledger provider” (a provider for which the device firmware is unknown, for instance provider 1 with a `x.y.z-rcA` firmware etc.) navigates to the settings.
It was not visible on Sentry previously because the error was a simple `“LedgerAPI4xx”` and in [my remapping of the error to something more specific (`“FirmwareNotRecognized”`)](https://github.com/LedgerHQ/ledger-live/pull …
> Fix uncaught FirmwareNotRecognized in useAvailableLanguagesForDevice

- .changeset/rare-beds-marry.md
- apps/ledger-live-mobile/src/families/solana/Delegations/index.tsx
- apps/ledger-live-mobile/src/locales/en/common.json
Add missing i18n pairs for Solana delegation feature.
It only impacts LLM which, for some reason, was only partially internationalized. LLD is not affected since the related key/value pairs were already defined and used there.
PS: can't provide screenshots of the updated version since I don't have Solana funds to test.
- https://ledgerhq.atlassian.net/browse/LIVE-8086
- LLM (iOS and Android) in the Solana delegation flow
---
> [BUGIX][LLM][LIVE-8086] add missing i18n for solana

- .changeset/rude-suits-push.md
- apps/ledger-live-mobile/src/screens/Swap/Form/index.tsx
prevent transaction amount from being updated after sig process on LLM
Duplicate of LLD fix #5583 
[JIRA-10633] 
- 
---
> bugfix: LIVE-10633

- .changeset/healthy-windows-perform.md
- apps/ledger-live-mobile/src/bridge/cache.ts
Switch the storage implementation of `CurrencyBridge#preload` data using the storeWrapper instead of a direct usage, in order to handle data bigger than 2MB. The ethereum preloaded data recently exceeded 2MB which created a crash for many users (on most Android phone that have [this default manufacturer limit](https://react-native-async-storage.github.io/async-storage/docs/limits/))
- **JIRA or GitHub link**: [LIVE-10386](https://ledgerhq.atlassian.net/browse/LIVE-10386)
- LLM storage of coin preloaded data (delegator lists, tokens)
---
[LIVE-10386]: https://ledgerhq.atlassian.net/browse/LIVE-10386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(LLM): chunk the preloaded data in the mobile app to support Android limits of 2MB per sqlite window cursor

- .changeset/bright-insects-allow.md
- apps/ledger-live-mobile/src/families/evm/EvmFeesStrategy.tsx
- apps/ledger-live-mobile/src/screens/SendFunds/04-Summary.tsx
- Remove the `useEffect` hook triggering infinite rerender in the case of live app sign flow
- Make the `NotEnoughBalance` error display buy CTA alongside the `NotEnoughGas` one
- Why transaction error is a `NotEnoughBalance` one in case of custom fees and not a `NotEnoughGas` one like for other default options?
The goal and scope of this PR is to unblock the current LLM pre-release.
This hook has only been commented out for now as it was originally added to automatically select the custom fee option after a user updates custom fees.
This hook does not trigger an infinite rerender in the normal send flow.
TBD if the fact that the custom fees option is not automatically selected once the user comes back from the "Customize fees" screen is a prio or not. I think this has always been here, …
> [BUGFIX][LIVE-10725] infinite rerender on live apps sign eth tx summary

- .changeset/bright-insects-allow.md
- apps/ledger-live-mobile/src/families/evm/EvmFeesStrategy.tsx
- apps/ledger-live-mobile/src/screens/SendFunds/04-Summary.tsx
- Remove the `useEffect` hook triggering infinite rerender in the case of live app sign flow
- Make the `NotEnoughBalance` error display buy CTA alongside the `NotEnoughGas` one
- Why transaction error is a `NotEnoughBalance` one in case of custom fees and not a `NotEnoughGas` one like for other default options?
The goal and scope of this PR is to unblock the current LLM pre-release.
This hook has only been commented out for now as it was originally added to automatically select the custom fee option after a user updates custom fees.
This hook does not trigger an infinite rerender in the normal send flow.
TBD if the fact that the custom fees option is not automatically selected once the user comes back from the "Customize fees" screen is a prio or not. I think this has always been here, …
> [BUGFIX][LIVE-10725] infinite rerender on live apps sign eth tx summary - release

- .changeset/nice-bobcats-drop.md
- libs/ledgerjs/packages/hw-app-btc/src/Btc.ts
- libs/ledgerjs/packages/hw-app-btc/src/BtcNew.ts
- libs/ledgerjs/packages/hw-app-btc/tests/newops/isPathNormal.test.ts
- libs/ledgerjs/packages/hw-app-btc/tests/semver.test.ts
- 9669119dbbac40e8c82532c9308da8babdb43fa8 makes qtum work with old and new nano app interfaces
- dd9dba41f598d1f8813f8d23d57a24b3f8087f82 adds some code improvements:
- use switch instead of if else cascade
- use [semver](https://www.npmjs.com/package/semver) for nano apps versions related tests
-----
All Bitcoin altcoins use the `BtcOld` implementation of the [`hw-app-btc` package](https://github.com/LedgerHQ/ledger-live/tree/develop/libs/ledgerjs/packages/hw-app-btc) today, including Qtum. But Qtum is being updated to use the [app-bitcoin-new](https://github.com/LedgerHQ/app-bitcoin-new) and should therefore now use the `BtcNew` implementation.
This will imply a version check in the codebase to make sure the correct version of the implementation is used depending on the app version. …
> [FEATURE][LIVE-10220] make Qtum work with old and new nano app interfaces

- libs/ledger-live-common/src/families/vechain/specs.ts
For some reason the bot spec for Vechain has been set to use the NanoX app.
While this works, it makes it mandatory to checkout NanoX apps for every single run of the bot in the CI.
Vechain is the only spec using the NanoX app, so this PR makes it use the NanoS+ app instead, which is the reference device that all of our integrations should be gradually migrated to.
- **JIRA or GitHub link**: N/A 
- 
---
> [support] Change vechain's bot spec to use NanoS+ app instead of NanoX

- apps/ledger-live-mobile/index.js
- apps/ledger-live-mobile/src/sentry.ts
```
WARN App Start Span could not be finished. `Sentry.wrap` was called before `Sentry.init`.
```
appears in the warning of LLM in dev mode.
this is due to fact we don't want to do Sentry.wrap when it's not .init in the first place.
the sentry code was moved to sentry.ts for better typing.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10859
- LLM sentry. but no impact.
---
> chore: fixes Sentry warning to happen in dev mode

- .changeset/green-lobsters-learn.md
- apps/ledger-live-desktop/src/renderer/components/LiveAppDrawer.tsx
- apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/WalletAPIWebview.tsx
- apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/CompleteExchange/Body.tsx
Fixing the complete exchange drawer not closing in the wallet-api
Also a small refactor for the start exchange too in order to keep the concern of closing the drawer in the drawer code
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10868
- Only the exchange support of the wallet-api, mainly for the CL card
---
> fix: wallet-api complete exchange drawer not closing

- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FormSummary/SectionFees.tsx
Display fees is they are estimated even if there is no drawer to edit them. 
fixes hidden tezos fees 
[relevant ticket](https://ledgerhq.atlassian.net/browse/LIVE-10851)
- 
---
> feat: display fees even if there no edit available

- .changeset/eight-beds-glow.md
- apps/ledger-live-desktop/src/renderer/modals/Receive/steps/StepReceiveStakingFlow.tsx
Simplify component using JSON.stringify as a hash function to only update based on the relevant currency ID prop. Remove unused actions, replace state with consts, and add a type check instead of a ts expect errror. 
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/LIVE-7343
- StakingModal that appears at the end of the Receive flow for Solana, Celo, Cosmos and Osmo. Behaviour should remain the same
---
> refactor: simplify receive staking flow json stringify hash

- .changeset/eight-rockets-drop.md
- apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx
- apps/ledger-live-desktop/src/renderer/components/ErrorBody.tsx
- apps/ledger-live-desktop/static/i18n/en/app.json
- New rendering component for `FirmwareNotRecognized`/"InvalidProvider" error:
- Added a `buttons` prop to `ErrorBody` component and used it for `DeviceNotOnboardedErrorComponent` and `renderLockedDeviceError`
- **JIRA or GitHub link**: [LIVE-10338] 
- cf. description above
---
[LIVE-10338]: https://ledgerhq.atlassian.net/browse/LIVE-10338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(lld/deviceaction/rendering): FirmwareNotRecognized rendering polish

- apps/ledger-live-mobile/e2e/models/onboarding/onboardingSteps.ts
- apps/ledger-live-mobile/e2e/setup.ts
- apps/ledger-live-mobile/e2e/specs/onboarding.spec.ts
- apps/ledger-live-mobile/src/components/CameraScreen/QRCodeBottomLayer.tsx
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/scenes/SyncDesktop.tsx
- Add Detox test for [B2CQA-1804] Access Wallet screen - Sync with Ledger Live Desktop option
- Add test id for Sync Desktop and Scanning page
- Add camera permissions for iOS
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/B2CQA-1804
---
[B2CQA-1804]: https://ledgerhq.atlassian.net/browse/B2CQA-1804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [B2CQA-1804]: add test for access wallet screen by sync with Ledger Live Desktop

- .changeset/nasty-peas-love.md
- apps/ledger-live-desktop/src/renderer/hooks/useInitSupportedCounterValues.ts
- libs/coin-framework/src/currencies/support.ts
This PR aims to fix two bugs :
- Users only having 2 default CV if the API call fails.
- API call retriggered at each re-render on LLD, making the select list unusable in poor network conditions (auto scroll once data is updated)
Here's how those are fixed :
- fallback to (updated) local list if API call fails.
- fixed hook call to the API retriggered on LLD.
- **JIRA or GitHub link**:  [LIVE-10577] [PROD-5432]
- 
---
[LIVE-10577]: https://ledgerhq.atlassian.net/browse/LIVE-10577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PROD-5432]: https://ledgerhq.atlassian.net/browse/PROD-5432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ …
> fix(Dynamic Counter Values): Bugfixes

- .changeset/spotty-ants-deny.md
- apps/ledger-live-desktop/src/renderer/components/SideDrawer.tsx
Today on some Side Drawers we can't close them using the close cta. The reason is that we have the AppRegionDrag that is positioned in the same area and takes over for a drag event.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10500
- 
---
> Fix close cta on SideDrawer when it overlaps AppRegionDrag

- apps/ledger-live-mobile/src/contentCards/layouts/carousel/index.tsx
- apps/ledger-live-mobile/src/dynamicContent/ContentCardsCategory/Layout.tsx
- apps/ledger-live-mobile/src/dynamicContent/types.ts
- apps/ledger-live-mobile/src/dynamicContent/utils.tsx
Add carousel width factor on vertical cards.
- 
---
> [LLM] - Add carousel with factor on vertical content cards.

- .changeset/chilly-scissors-talk.md
- .changeset/rotten-apples-remember.md
- apps/ledger-live-desktop/package.json
- apps/ledger-live-desktop/src/internal/index.ts
- apps/ledger-live-desktop/src/internal/live-common-setup.ts
- apps/ledger-live-desktop/src/internal/logger.ts
- apps/ledger-live-desktop/src/internal/transportHandler.test.ts
- apps/ledger-live-desktop/src/internal/transportHandler.ts
- apps/ledger-live-desktop/src/internal/types.ts
- apps/ledger-live-desktop/src/main/internal-lifecycle.ts
- apps/ledger-live-desktop/src/main/logger.ts
- apps/ledger-live-desktop/src/main/setup.ts
- apps/ledger-live-desktop/src/renderer/IPCTransport.md
- apps/ledger-live-desktop/src/renderer/IPCTransport.ts
- apps/ledger-live-desktop/src/renderer/components/ExportLogsButton.tsx
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/SyncOnboardingCompanion.tsx
- apps/ledger-live-desktop/src/renderer/init.tsx
- apps/ledger-live-desktop/src/renderer/live-common-setup.ts
- libs/ledger-live-common/src/deviceSDK/transports/core.ts
- libs/ledger-live-common/src/hw/deviceAccess.ts
- libs/ledger-live-common/src/hw/index.ts
- libs/ledgerjs/packages/hw-transport-node-hid-noevents/README.md
- libs/ledgerjs/packages/hw-transport-node-hid-noevents/src/TransportNodeHid.ts
- libs/ledgerjs/packages/hw-transport-node-hid-singleton/README.md
- libs/ledgerjs/packages/hw-transport-node-hid-singleton/src/TransportNodeHid.ts
- libs/ledgerjs/packages/hw-transport/README.md
- libs/ledgerjs/packages/hw-transport/src/Transport.ts
- pnpm-lock.yaml
This PR contains a fix on the sync onboarding ([LIVE-7814](https://ledgerhq.atlassian.net/browse/LIVE-7814)) and a refactoring on how we communicate to the device on LLD ([DSDK-85](https://ledgerhq.atlassian.net/browse/DSDK-85)).
The fix only works on the last version of the Stax fw: `1.4.0-rc1`. It should work (and not work) like before with other versions of the fw (infinite loop fw for ex).
The issue:
During the sync onboarding, on the last step of the onboarding (just after confirming the last seed word), the device stops communicating with the client. Then when the confirmation step is complete, the device "re-opens" the communication.
Before the new fw `1.4.0-rc1` the device itself was not able to correctly re-communicate with the client in certain scenarios. This has been fixed by …
> Fix: LIVE-7814 | DSDK-85: HID USB reconnection on LLD during the sync onboarding and IPC Transport logic refactoring

- .changeset/great-horses-marry.md
- libs/ledger-live-common/src/hw/actions/app.ts
When another app B is already opened while launching an action that needs an app A, which triggers the inline installation of the app A, a wrong component telling the user their device was disconnected was being displayed.
The issue was the event `deviceChange` not processed correctly after an event `disconnected`
- **JIRA or GitHub link**: [LIVE-10969](https://ledgerhq.atlassian.net/browse/LIVE-10969)
- 
---
[LIVE-10969]: https://ledgerhq.atlassian.net/browse/LIVE-10969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix: LIVE-10969 Fix inline install app while another app is opened

- libs/ledger-live-common/src/exchange/swap/maybeTezosAccountUnrevealedAccount.ts
Tezos error for unreavealed account could crash. 
This is a test PR to see if triggering the error after receiving rates solves the issue
[- **JIRA or GitHub link**: ](https://ledgerhq.atlassian.net/browse/LIVE-10967)
- 
---
> bugfix: triggering error only after having quotes to prevent crashes

- .changeset/metal-lemons-perform.md
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/DeviceConnection/index.tsx
Improve stax connect screen before ESC by polling device onboarding state
https://github.com/LedgerHQ/ledger-live/assets/145363160/4522dc25-aeba-4682-83fe-2c5d45e44761
- **JIRA or GitHub link**: [LIVE-6541] 
- Lock stax in connect screen before/after lottie animation change
- Unplug stax in connect screen before/after lottie animation change
---
[LIVE-6541]: https://ledgerhq.atlassian.net/browse/LIVE-6541?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIVE-6541] [LLD]: Improve "connect" screen during sync onboarding via USB

- .changeset/odd-chefs-sell.md
- libs/ledger-live-common/src/families/solana/tx-fees.ts
An addition to #5913. In case of a failure after retries, use hardcoded value for a basic TX fee with one signature.
- **JIRA or GitHub link**: #5913
---
> bugfix(solana): Use fallback TX fee amount in case of failed retries

- .changeset/odd-chefs-sell.md
- libs/ledger-live-common/src/families/solana/tx-fees.ts
(Backport of https://github.com/LedgerHQ/ledger-live/pull/5955 for release branch)
1) https://github.com/LedgerHQ/ledger-live/pull/5913 added a retry x10 mechanism, as a mitigation for https://ledgerhq.atlassian.net/browse/LIVE-10945
2) https://github.com/LedgerHQ/ledger-live/pull/5946 then provided a better fix, by falling back on default fees
3) This PR removes the retry x10 mechanism, since now with the proper fallback only a 1x retry is enough
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10945
---
> [bugfix] Revert increase of nb retries for solana fees - RELEASE

- libs/ledger-live-common/src/exchange/swap/maybeTezosAccountUnrevealedAccount.ts
Tezos error for unreavealed account could crash. 
This is a test PR to see if triggering the error after receiving rates solves the issue
[- **JIRA or GitHub link**: ](https://ledgerhq.atlassian.net/browse/LIVE-10967)
- 
---
> bugfix: triggering error only after having quotes (cherryPick from develop)

- libs/ledger-live-common/src/families/solana/tx-fees.ts
1) https://github.com/LedgerHQ/ledger-live/pull/5913 added a retry x10 mechanism, as a mitigation for https://ledgerhq.atlassian.net/browse/LIVE-10945
2) https://github.com/LedgerHQ/ledger-live/pull/5946 then provided a better fix, by falling back on default fees
3) This PR removes the retry x10 mechanism, since now with the proper fallback only a 1x retry is enough
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10945
---
> [bugfix] Revert increase of nb retries for solana fees

- .github/workflows/test.yml
- libs/ledger-live-common/sonar-project.properties
disable sonarqube until we address a wider solution to target all libs: the current integration causes us too much trouble on the CI and also isn't useful enough, in context of ongoing effort splitting live-common into libraries (e.g. https://github.com/LedgerHQ/ledger-live/pull/5919 ), we will need to revisit the idea and address all libraries under libs/ to be benchmarked by such tool.
- **JIRA or GitHub link**: n/a
- the libs tests should run again on the CI
---
> chore: disable sonarqube

- .changeset/selfish-files-trade.md
- libs/ledger-live-common/src/hw/getOnboardingStatePolling.ts
On LLD, depending at what time the device is unplugged, we would not get the same behavior: sometimes the banner would be displayed, sometimes it would directly be the USB troubleshooting drawer.
What we want: we always want the same behavior: banner first when unplugging because we know the user can reconnect their device, and after 60 secs the troubleshooting drawer, we can:
The simple fix: update the list in `isAllowedOnboardingStatePollingError` to add the error `DisconnectedDeviceDuringOperation`
<details>
<summary>LLD demo</summary>
https://github.com/LedgerHQ/ledger-live/assets/15096913/29da3280-ffce-46f0-9866-aa9995984426
</details>
<details>
<summary>LLM demo - still working</summary>
https://github.com/LedgerHQ/ledger-live/assets/15096913/7e5f28d2-b518-4fd2-baa5-9a36ea45883e …
> Chore: add DisconnectedDeviceDuringOperation to the allowed errors of the sync onboarding polling

- .changeset/smooth-mails-love.md
- apps/ledger-live-mobile/src/families/tron/accountActions.tsx
accountActions had an invariant for `tronResources`, when there were no `tronResources` the app would crash. However they were not mandatory for the component.
In this PR the choice is made to remove the invariant and propose a fallback in case the `tronResources`
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10972
- 
---
> [Tron] - tronResource not mandatory in accountActions component

- .changeset/giant-sloths-switch.md
- libs/ledger-live-common/src/hw/actions/app.ts
Some breaking changes had been added to the open app device action reducer in #5902. The actual fix made in that PR was not those changes so they were unnecessary.
Thanks to @Wozacosta for the initial fix proposal 🙏
**Demo of the fix:**
LLM Android: The device going from one app to another during a device action should not cause any issue and the device action should go on normally. The issue was that the "switch on and unlock your device" drawer was getting displayed and never disappearing.
https://github.com/LedgerHQ/ledger-live/assets/91890529/3f357374-fff0-4f79-8769-ef830bd120aa
**Demo of what had been fixed in #5902 and is still working:**
LLM Android: Unplugging the USB during a device action should not result in the drawer getting dismissed, it should show an error message. …
> [LIVE-10904][LLM][BLE][Android] When using an open app"Switch on and unlock your device" drawer blocks the action

- .changeset/cool-falcons-wave.md
- apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/index.tsx
- apps/ledger-live-desktop/src/renderer/drawers/Drawer.tsx
Disconnect device when onboarding a Stax, waiting for the 'troubleshooting' modal shows, then click on the cross button. Now this action will return to the device selection page, which is the same with the 'close' button at the bottom of the modal.
- **JIRA or GitHub link**: [LIVE-10934](https://ledgerhq.atlassian.net/browse/LIVE-10934)
- 
---
[LIVE-10934]: https://ledgerhq.atlassian.net/browse/LIVE-10934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIVE-10934][BUGFIX] Close button on USB troubleshooting drawer during Sync Onboarding is misleading

- .changeset/thin-snails-drum.md
- libs/ui/packages/native/src/components/Form/Switch/index.tsx
Fixed Switch thumb color to always be white (both in dark & light mode).
Shouldn't be theme dependant.
- **JIRA or GitHub link**:  [LIVE-11023]
- 
---
[LIVE-11023]: https://ledgerhq.atlassian.net/browse/LIVE-11023?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(NativeUI/Switch): Fixed switch thumb color (always white)

- .changeset/swift-socks-complain.md
- apps/ledger-live-mobile/src/contentCards/cards/hero/elements.tsx
- apps/ledger-live-mobile/src/contentCards/cards/hero/index.tsx
- apps/ledger-live-mobile/src/dynamicContent/ContentCardsCategory/Layout.tsx
- apps/ledger-live-mobile/src/dynamicContent/types.ts
- apps/ledger-live-mobile/src/dynamicContent/utils.tsx
Add Hero Content Card and linked it to the Dynamic Content system.
- **JIRA or GitHub link**: [LIVE-9808]
- 
---
[LIVE-9808]: https://ledgerhq.atlassian.net/browse/LIVE-9808?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LLM] - [LIVE-9808] - Add Hero Content Card

- libs/ledger-live-common/src/portfolio/v2/index.ts
a few years ago, we had the countervalues module to use BigNumber and we used `if (countervalue)` to know if a countervalue is available.
This fixes a forgotten place in our codebase where we were still doing `if (countervalue)` which in case of `== 0` would be false where it should be true. "0" must be strictly differentiated from the null/undefined case.
due to this, it creates a bug where the portfolio is showing this:
and we instead are expecting it to be:
- **JIRA or GitHub link**: [LIVE-10176](https://ledgerhq.atlassian.net/browse/LIVE-10176)
- graphs
---
[LIVE-10176]: https://ledgerhq.atlassian.net/browse/LIVE-10176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViL …
> fix(portfolio): fix the countervalueAvailable status

- .changeset/wicked-socks-relate.md
- apps/ledger-live-mobile/src/screens/Nft/NftGallery/NftGalleryEmptyState.tsx
Fix Empty state display in NFT Gallery in French
BEFORE / AFTER
https://github.com/LedgerHQ/ledger-live/assets/112866305/dadd2279-b418-4687-8b3d-5cb60688f499
-->
- 
---
> [BUGFIX]: Fix display of texts in empty state NFT Gallery

- apps/ledger-live-desktop/src/main/window-lifecycle.ts
this should fix a bug where LLD is running but you can’t see it if you have unplugged a second screen on which you had the Ledger Live app opened before.
used this tip: https://github.com/electron/electron/issues/526#issuecomment-563010533
- **JIRA or GitHub link**: [LIVE-10371](https://ledgerhq.atlassian.net/browse/LIVE-10371)
- position of the live app when restarted
---
[LIVE-10371]: https://ledgerhq.atlassian.net/browse/LIVE-10371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(lld): reset app position when changing monitors

- .changeset/silly-ears-cry.md
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/Migrations/SwapMigrationUI.tsx
Check the startsWith for stg and ppd.
- 
---
> fix: check starts with to catch ppd and stg envs

- .changeset/bright-books-join.md
- apps/ledger-live-mobile/src/screens/Manager/AppsList/AppRow.tsx
- apps/ledger-live-mobile/src/screens/Manager/Modals/UpdateAllModal.tsx
1. When an installed app has an update, the displayed capacity is not the one installed, but it should be.
2. When opening the update app modal, the list displays the installed versions of apps instead of the to update ones, but it should be. The bug is described in this [LIVE-9586](https://ledgerhq.atlassian.net/browse/LIVE-9586) ticket.
- **JIRA or GitHub link**: [LIVE-6441](https://ledgerhq.atlassian.net/browse/LIVE-6441)
- 
---
[LIVE-9586]: https://ledgerhq.atlassian.net/browse/LIVE-9586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIVE-6441]: https://ledgerhq.atlassian.net/browse/LIVE-6441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZ …
> [LIVE-6441][BUGFIX] Discrepencies between app size when update available

- .changeset/cool-kiwis-film.md
- .changeset/nervous-cobras-jog.md
- apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/errors/DeviceError.tsx
- libs/ledgerjs/packages/errors/src/index.ts
- Update stax display correct error on locking it
- Set prototype of locked device error in order to fix 'instanceof' check of an error
- **JIRA or GitHub link**: [LIVE-11108] 
- ...
---
[LIVE-11108]: https://ledgerhq.atlassian.net/browse/LIVE-11108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIVE 11108] Handle LockedDeviceError correctly

- .changeset/six-ways-hope.md
- apps/ledger-live-desktop/src/renderer/families/solana/DelegationActivateFlowModal/steps/StepValidator.tsx
- apps/ledger-live-desktop/src/renderer/families/solana/DelegationDeactivateFlowModal/steps/StepValidator.tsx
- apps/ledger-live-desktop/src/renderer/families/solana/DelegationFlowModal/steps/StepValidator.tsx
- apps/ledger-live-desktop/src/renderer/families/solana/DelegationReactivateFlowModal/steps/StepValidator.tsx
- apps/ledger-live-desktop/src/renderer/families/solana/DelegationWithdrawFlowModal/steps/StepAmount.tsx
Display spinner inside "continue" button in solana staking workflows (Delegate/Activate/Deactivate/Reactivate/Withdraw modals).
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10980
- "Continue" button in Solana "Delegate/Activate/Deactivate" staking modals should now display correct loading Spinner
---
> [bugfix] Solana: display spinner in staking workflows

- .changeset/lemon-mugs-poke.md
- apps/ledger-live-mobile/src/contentCards/cards/hero/index.tsx
This PR aims at fixing a UI/functional bug on the Hero Content Card CTA.
**Expected behaviour:**
- On android the CTA button must not take up the entire width of the screen
- CTA should redirect to the mentioned link
**Actual behaviour:**
- Nothing happens when clicking on the CTA
- Large CTA width on Android
This PR fixes that.
https://github.com/LedgerHQ/ledger-live/assets/25589782/8be2af92-c6ba-45e7-bf74-4693b1ab180d
- **JIRA or GitHub link**: [LIVE-11091] 
- ...
---
[LIVE-11091]: https://ledgerhq.atlassian.net/browse/LIVE-11091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LLM] - [LIVE-11091] - Fix UI/functional bug on Hero Content Card

- apps/ledger-live-mobile/e2e/models/accounts/accountsPage.ts
- apps/ledger-live-mobile/e2e/models/wallet/portfolioPage.ts
- apps/ledger-live-mobile/e2e/specs/addAccounts/addAccount.spec.ts
- apps/ledger-live-mobile/e2e/specs/onboarding.spec.ts
- apps/ledger-live-mobile/e2e/specs/unknown-currency-resilience.spec.ts
- apps/ledger-live-mobile/src/screens/Portfolio/ReadOnly/index.tsx
- apps/ledger-live-mobile/src/screens/Portfolio/index.tsx
Add account tests fails because a content card prevents to reach the button
- Adding Scroll to the CTA to prevent test failure
- Improving some tests ids
- **JIRA or GitHub link**: [B2CQA-2125](https://ledgerhq.atlassian.net/browse/B2CQA-2125)
- Detox tests
---
[B2CQA-2125]: https://ledgerhq.atlassian.net/browse/B2CQA-2125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [B2CQA-2125] Detox: fix add account tests 

- .changeset/polite-masks-return.md
- apps/ledger-live-desktop/static/i18n/en/app.json
- apps/ledger-live-mobile/src/locales/en/common.json
Replaced :       "title": "You need {{fees}} {{ticker}} for network fees to **swap** as you are on {{cryptoName}} network. <link0>Buy {{ticker}}</link0>",
with :       "title": "You need {{fees}} {{ticker}} for network fees to **send** as you are on {{cryptoName}} network. <link0>Buy {{ticker}}</link0>",
- **JIRA or GitHub link**:  [LIVE-11097]
- ...
---
[LIVE-11097]: https://ledgerhq.atlassian.net/browse/LIVE-11097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(LLM/ParentAccountError): Fixed copy for parent account error

- .changeset/tame-ants-build.md
- apps/ledger-live-desktop/src/renderer/families/evm/AccountHeaderManageActions.ts
This PR  prevents erroneously including a staking button on `ethereum classic`accounts, as well as other accounts with "ethereum" in the currency ID that are not Ethereum accounts.
The issue does not occur on mobile because only Ethereum is included. On mobile, the logic is just: 
```
// apps/ledger-live-mobile/src/families/evm/accountActions.tsx
if (account.type === "Account" && account.currency.id === "ethereum") {
// show option to stake 
```
But on desktop we checked for the string `ethereum`, and therefore included all test nets:
"ethereum_ropsten",
"ethereum_goerli",
"ethereum_sepolia",
"ethereum_holesky",
This accidentally also includes `ethereum_classic`.
This PR puts the desktop in line with the mobile app, to exclude every account currency except Ethereum (for EVM staking).
- …
> fix: exclude ethereum classic from accounts with stake button

- .changeset/afraid-taxis-tease.md
- apps/ledger-live-desktop/src/renderer/families/evm/StakeFlowModal/component/ProviderItem.tsx
- apps/ledger-live-desktop/src/renderer/modals/Receive/steps/StepReceiveFunds.tsx
- apps/ledger-live-desktop/static/i18n/en/app.json
- apps/ledger-live-mobile/src/families/evm/StakingDrawer/EvmStakingDrawerProvider.tsx
- apps/ledger-live-mobile/src/families/evm/StakingDrawer/types.ts
- apps/ledger-live-mobile/src/locales/en/common.json
Receive flow for NFTs and ERC 20 tokens was showing the ETH staking modal. Instead we only want it to display if the currency that was received was a full ETH account.
Also:
-  minor updates to translations for providers list
- only show the "requires 32 ETH" tag if the provider has a "min" set in Firebase config
- **JIRA or GitHub link**:  [LIVE-10059](https://ledgerhq.atlassian.net/browse/LIVE-10059)
- ... Receive ETH --> full list of providers should show
- Receive an NFT or Token - even from an ETH account --> no eth staking model
- Receive another supported currency: i.e. celo, cosmos, osmo, solana then we want the generic "stake with ledger" modal to appear, and not the full ETH providers list. …
> fix: only open EVM staking modal if the user receives ethereum

- .changeset/mighty-lamps-perform.md
- apps/ledger-live-mobile/src/screens/Onboarding/steps/setupDevice/scenes/RecoveryPhraseSetup.tsx
Fix displayed text in confirm recovery phrase during onboarding Nano
- **JIRA or GitHub link**: [LIVE-8656] 
- ...
---
[LIVE-8656]: https://ledgerhq.atlassian.net/browse/LIVE-8656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FIX]: Fix displayed text in confirm recovery phrase during onboarding Nano

- apps/ledger-live-desktop/package.json
- apps/ledger-live-desktop/src/renderer/components/InputPassword.tsx
- pnpm-lock.yaml
remove unused prop on InputPassword that cost us +1MB on the bundle size.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-9557
- no impact, literally dead code removal. the touch area is the input password but the code branch was not active.
---
> chore(lld): remove unused zxcvbn lib

- .changeset/cool-kiwis-film.md
- .changeset/flat-bats-applaud.md
- .changeset/nervous-cobras-jog.md
- apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/errors/DeviceError.tsx
- libs/ledger-live-common/src/hw/deviceAccess.ts
- libs/ledgerjs/packages/errors/src/index.ts
- Update stax display correct error on locking it
- Set prototype of locked device error in order to fix 'instanceof' check of an error
- Improve withDevice hook to throw LockedDeviceError
- **JIRA or GitHub link**: [LIVE-11108] 
- ...
---
[LIVE-11108]: https://ledgerhq.atlassian.net/browse/LIVE-11108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LIVE-1108][LLD][COMMON][ERRORS] Handle LockedDeviceError correctly

- .changeset/polite-papayas-fold.md
- apps/ledger-live-desktop/src/renderer/modals/Send/fields/RecipientField.tsx
Continue button was greyed out in step 1 of Send flow if the Account to debit is changed
BEFORE 
AFTER
https://github.com/LedgerHQ/ledger-live/assets/112866305/7f3f067f-ec2f-48d2-9ae2-3b76fb068cd8
- **JIRA or GitHub link**: [LIVE-10876]
- ...
---
[LIVE-10876]: https://ledgerhq.atlassian.net/browse/LIVE-10876?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BUGFIX] : Continue button was greyed out in step 1 of Send flow if the Account to debit is changed

- .changeset/rich-dogs-peel.md
- apps/ledger-live-mobile/src/analytics/segment.ts
- apps/ledger-live-mobile/src/locales/en/common.json
- apps/ledger-live-mobile/src/notifications/braze.ts
- apps/ledger-live-mobile/src/reducers/settings.ts
- apps/ledger-live-mobile/src/reducers/types.ts
- apps/ledger-live-mobile/src/screens/Settings/Notifications/index.tsx
Removed recommendations toggle from the notifications settings
Call the braze.setCustomUserAttributes for the optInAnnouncements, optInLargeMovers and optInTxAlerts attributes to update them in braze directly when the user modifies his preferences
- **JIRA or GitHub link**: [LIVE-11228] 
- ...
---
[LIVE-11228]: https://ledgerhq.atlassian.net/browse/LIVE-11228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> LLM - Removed recommendations toggle from the notifications settings

- .changeset/fast-bananas-study.md
- apps/ledger-live-desktop/src/renderer/analytics/segment.ts
- apps/ledger-live-desktop/src/renderer/families/evm/StakeFlowModal/index.tsx
- apps/ledger-live-mobile/src/analytics/segment.ts
- apps/ledger-live-mobile/src/families/evm/StakingDrawer/index.tsx
- We have a new stakingProvidersEnabled user trait in Segment to capture historical data on user activity on the eth staking drawer
- To measure the success of the new providers in the list, the new trait should show on Segment whether the user is displayed e.g. `5` or `3` providers.
- Captured on every event
- **JIRA or GitHub link**: [LIVE-11189](https://ledgerhq.atlassian.net/browse/LIVE-11189)
- ... No behaviour change when using the modal
- Only Segment analytics should update with the new trait
---
[LIVE-11189]: https://ledgerhq.atlassian.net/browse/LIVE-11189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add providers AB test trait to analytics identify for eth staking modal

- .changeset/weak-icons-joke.md
- apps/ledger-live-desktop/src/renderer/hooks/swap-migrations/useSwapLiveAppHook.tsx
- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.tsx
Remove useless renders from LL
verify if swap live state hook props before creating a new cacheKey or it would rerender infinitely 
https://ledgerhq.atlassian.net/browse/LIVE-11143
- ...
---
> bugfix(LIVE-11143): fix useless renders and render issues swap live app

- .changeset/big-dodos-burn.md
- apps/ledger-live-mobile/src/families/evm/StakingDrawer/EvmStakingDrawerProvider.tsx
- apps/ledger-live-mobile/src/families/evm/StakingDrawer/index.tsx
Eth modal conditional render logic did not check for type safety of `hasTag`, so it was throwing "Strings must be rendered inside a Text tag" error. 
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/LIVE-11256
- The ETH account > stake button opens the EVM staking modal without throwing an error.
---
> fix: live 11256 - eth account stake modal conditional render

- .changeset/fair-adults-marry.md
- apps/ledger-live-desktop/src/renderer/hooks/useDeeplinking.ts
Prevents a deep link for wallet connect to go through if only coming from a request and we're already on the live-app page, aligning LLD behavior with LLM
- **JIRA or GitHub link**: [LIVE-11270]
---
[LIVE-11270]: https://ledgerhq.atlassian.net/browse/LIVE-11270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: LLD wallet connect deep link handling for requests [LIVE-11270]

- .changeset/loud-moons-compare.md
- apps/ledger-live-desktop/src/renderer/components/TopBar/ActivityIndicator.tsx
- apps/ledger-live-desktop/src/renderer/components/TopBar/shared.ts
- Fix disabled cursor on "Refresh" label when sync error
- Add pointer cursor when it's interactive
After/Before
*Synchronizing...* will not be red it was just on test purpose
https://github.com/LedgerHQ/ledger-live/assets/112866305/6f697953-fb95-44a7-8f15-2f96f2e2bda0
- **JIRA or GitHub link**:[LIVE-10962] 
- ...
---
[LIVE-10962]: https://ledgerhq.atlassian.net/browse/LIVE-10962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [BUGFIX] : Wrong icon when hovering over 'Refresh' CTA when synchronisation error 🐛
