.changeset/tough-books-lick.md, libs/ledger-live-common/src/apps/listApps/v2.test.ts, libs/ledger-live-common/src/apps/listApps/v2.ts, libs/ledger-live-common/src/device-core/managerApi/repositories/HttpManagerApiRepository.test.ts, libs/ledger-live-common/src/device-core/managerApi/repositories/HttpManagerApiRepository.ts, libs/ledger-live-common/src/device/use-cases/listAppsUseCase.test.ts, libs/ledger-live-common/src/device/use-cases/listAppsUseCase.ts
When the `listAppsV2minor1` feature flag was disabled, it was in fact using v2, and v2 had an issue with the "My Ledger provider ID" not being properly passed to the underlying logic. It was causing an "not found entity" error on some firmware versions. Also there was an issue with error remapping of the "not found entity error".
- Fixed bad conditional branching for `listAppsUseCase`: list apps v1 and v2 were switched
- Added unit tests for that.
- Fixed `forceProvider` parameter missing in `listAppsV2` call in `listAppsUseCase`. It was resulting in "not found entity" errors regardless of the selected "My Ledger" provider in Ledger Live.
- Added a stricter typing (the parameter is now always required)
- Fixed bad error remapping for `HttpManagerApiRepository.getCurrentFirmware` which …
=> [LIVE-11289][Common] Error “not found entity” when using a firmware that requires a “My Ledger provider”

.github/workflows/test.yml
As done for e2e tests, we don't have any benefit to replay UI tests on windows + MacOS, we can only keep linux
- ...
---
=> Remove windows and mac when we run ui tests in CI

.changeset/silly-vans-taste.md, libs/ledger-live-common/src/bot/formatters.ts
The change is trivial, it seems that some time ago `unavailableMutationReasons` was change and `groupBy` usage was made the way, that typecheck didn't help.
Before:
```
🤷‍♂️ couldn't find a mutation to do! (undefined)
```
After
```
🤷‍♂️ couldn't find a mutation to do! (Transfer ~50%: balance is 0, Transfer Max: balance is 0, Delegate: not enough balance, Deactivate Activating Delegation: not enough balance, Deactivate Active Delegation: not enough balance, Reactivate Deactivating Delegation: not enough balance, Activate Inactive Delegation: not enough balance, Withdraw Delegation: not enough balance)
```
- **JIRA or GitHub link**:  N/A
---
=> bugfix: bot formatter to display mutation details properly

apps/ledger-live-desktop/tests/models/OnboardingPage.ts, apps/ledger-live-desktop/tests/specs/onboarding/connect-device.spec.ts, apps/ledger-live-desktop/tests/specs/onboarding/restore-device.spec.ts, apps/ledger-live-desktop/tests/specs/onboarding/setup-device.spec.ts
Today those tests are unstable because we don't make sure that we're hovering the Nano S card on the onboarding when we take the screenshot.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11337
- ...
---
=> fix: make sure mouse is hovering nano S on onboarding e2e tests

.changeset/cyan-pens-prove.md, apps/ledger-live-desktop/src/renderer/analytics/segment.ts, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/utils/index.ts
- add ptxSwapMoonpayProviderEnabled as an identity and tracker analytics property.
- remove from swap page since it is now an extra property for all events.
https://ledgerhq.atlassian.net/browse/LIVE-11132
---
=> [Bugfix/LIVE-11132]: add ptxSwapMoonpayProviderEnabled as an identity and tracker analytics property

.changeset/clean-buses-accept.md, libs/coin-evm/src/__tests__/unit/adapters/ethers.unit.test.ts, libs/coin-evm/src/__tests__/unit/prepareTransaction.unit.test.ts, libs/coin-evm/src/adapters/ethers.ts, libs/coin-evm/src/api/node/rpc.common.ts, libs/coin-evm/src/specs.ts
This PR update the `DEFAULT_NONCE` (-1) behaviour put in place for the "Edit Ethereum Transaction" feature, preventing the serialization of a transaction when using it with `ethers`.
It leads to not being able to get the L1 fees for OP Stack transactions, preventing the usage of the `useMax` feature by not being able to predict a correct maximum amount spendable.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10515
- No impact
---
=> [LIVE-10515] Bugfix: Update `DEFAULT_NONCE` behaviour, preventing OP Stack chains to work correctly

apps/ledger-live-mobile/src/components/CameraScreen/index.tsx
This PR includes a fix that solves a known UI issue on QR code scanning.
- **JIRA or GitHub link**: [LIVE-11362] 
- ...
---
[LIVE-11362]: https://ledgerhq.atlassian.net/browse/LIVE-11362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LLM] - [LIVE-11362] - Fix QR code UI issue on scan

.changeset/dry-birds-learn.md, libs/ledger-live-common/src/families/stacks/bridge.integration.test.ts, libs/ledger-live-common/src/families/stacks/bridge/account.ts, libs/ledger-live-common/src/families/stacks/bridge/utils/misc.ts
Fix for account sync error on stacks caused by import of accounts on ledger live using `accountId` string. The address is now derived from pubkey which is always stored in the accountId string and acts as seedId. 
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10786
- ...
---
=> [Bugfix/Stacks] Fix Account sync error for imported accounts 

.changeset/heavy-wombats-confess.md, apps/ledger-live-desktop/src/renderer/actions/modals.ts, apps/ledger-live-desktop/src/renderer/components/DeviceAction/index.tsx, apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx
Prior to this PR, the drawer does not close. 
Although the main CTA dispatches the `MODAL_CLOSE_ALL` action, it does not effect this drawer. Because this drawer was triggered by `EXCHANGE_APP_DRAWER_OPEN`. 
Which needs to be closed by using the `PLATFORM_APP_DRAWER_CLOSE`.
I don't think this PR is a clean solution, I'm open to suggestions 
https://github.com/LedgerHQ/ledger-live/assets/138497251/8b0ec41f-e42f-49f7-937e-7b9635ca4546
- **JIRA or GitHub link**: [LIVE-11282](https://ledgerhq.atlassian.net/browse/LIVE-11282)
- ...
---
[LIVE-11282]: https://ledgerhq.atlassian.net/browse/LIVE-11282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(LIVE-11282): close platform drawer

.changeset/cyan-socks-taste.md, apps/ledger-live-desktop/src/renderer/families/solana/index.ts, apps/ledger-live-desktop/src/renderer/families/solana/operationDetails.tsx, apps/ledger-live-mobile/src/families/solana/operationDetails.tsx, libs/ledger-live-common/src/families/solana/bridge/bridge.ts, libs/ledger-live-common/src/families/solana/js-synchronization.ts, libs/ledger-live-common/src/families/solana/serialization.ts, libs/ledger-live-common/src/families/solana/types.ts
**Issue:**
After staking SOL, the initial balance increases and balances history on the graph becomes incorrect.
Having research this, we found that this is connected to staking operations containing delegated SOL in their `value` field.
Balances history in graph is calculated from now to past, starting from the current account balance, by applying operations values on the account balance for a given period of time.
Since account balance already contains staked SOL, when delegate/withdraw operation values are applied to the balance, the graph history becomes incorrect, increasing its amount by delegated `Operation.value`.
**Fix:**
Elrond and Cosmos were used as examples for this fix.
- [LLC] Updated delegate/withdraw operations `value` to keep fee instead of delegated amount.
- [LLC] …
=> [bugfix] Solana: Update staking operations to fix balances history in graph

CODEOWNERS
ledger live common still being that monolithic library that we are progressively dismantling into smaller libraries, we don't want live-hub to be pinged on each single modification of package.json, therefore we only make hub owning the /src not the whole live-common package. (Note that specific teams already specialize part of live-common src/* sub paths and that live-hub is a catch all fallback case)
- no impact
---
=> chore: live-hub only owns the /src of live-common, not package.json's

.changeset/eighty-jars-smell.md, apps/ledger-live-mobile/src/screens/SendFunds/03b-AmountNft.tsx
Removes blinking error on ERC1155 NFT send
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-8852
- No impact
---
=> [LIVE-8852] Bugfix: Prevent error message on NFT send if bridge pending

.changeset/quiet-fireants-fry.md, apps/ledger-live-desktop/src/renderer/components/ToastOverlay/Toast.tsx, apps/ledger-live-desktop/src/renderer/drawers/OperationDetails/index.tsx, apps/ledger-live-desktop/tests/specs/services/wallet-api.spec.ts
- Set account to parent account if same id in `operationdetails` drawer
0.  In [wallet-api/logic.ts](https://github.com/LedgerHQ/ledger-live/blob/9098224d29ff811c286e51c2179354dde22a08f4/libs/ledger-live-common/src/wallet-api/logic.ts#L101), we set parentAccount to getParentAccount(account, accounts)
In [getParentAccount](https://github.com/LedgerHQ/ledger-live/blob/9098224d29ff811c286e51c2179354dde22a08f4/libs/coin-framework/src/account/helpers.ts#L374), we return the account passed if it is of type `Account`. 
**Thus if selected a non-child / token account, parent account will be set to the same account.** 
1. Here, if a parentAccount is passed, account was searched on that parentAccount subaccounts, which ended up being undefined. …
=> [LIVE-11121] LLD - Fix Transaction details drawer empty when using third party app

.changeset/unlucky-bottles-dress.md, libs/ledger-live-common/src/families/solana/js-preload.test.ts, libs/ledger-live-common/src/families/solana/js-preload.ts
Solana preloaded data somehow ends up with a data without version, this PR adds a safer check before hydrate
I cannot reproduce so it looks like it is not consistent, anyway hydrate data field should be treated as unsafe, if data is corrupted we have to return; directly.
```
// reinject the preloaded data (typically if it was cached)
// method need to treat the data object as unsafe and validate all fields / be backward compatible.
hydrate(data: unknown, currency: CryptoCurrency): void;
```
If it's unsafe we drop it and rely on fresh data. It looks like in the sentry issue case the user somehow ended up with preload data without version which should not happen as you can see on linked screenshot
- **JIRA or GitHub link**: [https://ledgerhq.atlassian.net/browse/LIVE-11568](https://ledgerhq. …
=> Safer solana hydrate

.changeset/polite-papayas-fold.md, apps/ledger-live-desktop/src/renderer/modals/Send/fields/RecipientField.tsx
Reverts LedgerHQ/ledger-live#6139
=> Revert "[BUGFIX] : Continue button was greyed out in step 1 of Send flow if the Account to debit is changed"

.changeset/hip-peaches-retire.md, apps/ledger-live-desktop/src/renderer/families/evm/SendAmountFields/SelectFeeStrategy.tsx, apps/ledger-live-desktop/src/renderer/modals/Send/SendAmountFields.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FeesDrawer/index.tsx
Check for disableSlowStrategy in the ETH fee drawer. I did not reuse this mapStrategy function as it is specific to bitcoin. 
video shows disabled for fixed rate
https://github.com/LedgerHQ/ledger-live/assets/5360522/bfb1d09d-f1df-4bd1-b576-08a53b7fd519
https://ledgerhq.atlassian.net/browse/LIVE-11585
- ...
---
=> bugfix: check for disableSlowStrategy in ethFee drawer

.changeset/chilly-hornets-smoke.md, apps/ledger-live-mobile/src/reducers/swap.ts, libs/ledger-live-common/src/exchange/swap/const/timeout.ts, libs/ledger-live-common/src/exchange/swap/hooks/useSwapTransaction.ts, libs/ledger-live-common/src/exchange/swap/hooks/v5/useProviderRates.ts
Longer quote refresh rate to prevent swap confirmation flow restarting frequently 
- **JIRA or GitHub link**: [LIVE-11608](https://ledgerhq.atlassian.net/browse/LIVE-11608)
- ...
---
[LIVE-11608]: https://ledgerhq.atlassian.net/browse/LIVE-11608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> bugfix(LIVE-11608): llm swap wrong behaviour with the drawer

.changeset/healthy-horses-doubt.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.tsx, libs/ledger-live-common/src/exchange/swap/hooks/useFromState.ts, libs/ledger-live-common/src/exchange/swap/hooks/useUpdateMaxAmount.ts
This should fix 
> what the minimum for swap is, a swap that was possible to initiate in previous build now returns a "Amount must be higher than n"
- ...
---
=> fix: untick use max button when switching accounts

.changeset/perfect-crabs-arrive.md, apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/CompleteExchange/Body.tsx
Add check to useEffect to avoid multiple broadcast on success
https://ledgerhq.atlassian.net/browse/LIVE-11708
- ...
---
=> fix(LIVE-11708): add check to useEffect to avoid multiple broadcasts

.changeset/eight-mails-crash.md, apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/CompleteExchange/Body.tsx
This fix addresses an issue where two backend calls were made from Ledger Live Desktop (LLD) and the exchange SDK when a swap was canceled or accepted.
Changes:
- There is check in the `onBroadcastSuccess` function to determine if the `swapId` exists. If it does, this indicates that the swap was initiated from the exchange SDK, and there is no need to call `setBroadcastTransaction` in LLD.
- Replicated the old logic where, if `DISABLE_TRANSACTION_BROADCAST` is true, the 'canceled' API from the exchange SDK is called to maintain backward compatibility.
Before
After
https://ledgerhq.atlassian.net/browse/LIVE-11468
- ...
---
=> fix(live-11468): prevent duplicate backend calls on swap cancellation or acceptance

.changeset/pretty-cobras-carry.md, .changeset/warm-jobs-crash.md, libs/coin-modules/coin-evm/src/__tests__/unit/hw-getAddress.unit.test.ts, libs/coin-modules/coin-evm/src/__tests__/unit/logic.unit.test.ts, libs/coin-modules/coin-evm/src/hw-getAddress.ts, libs/ledgerjs/packages/hw-app-eth/README.md, libs/ledgerjs/packages/hw-app-eth/src/Eth.ts, libs/ledgerjs/packages/hw-app-eth/tests/Eth.unit.test.ts
Allows the `$@ledgerhq/hw-app-eth` and `@ledgerhq/coin-evm` to use the `chainId` parameter during address retrieval, displaying the network name and logo on a Stax device
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/LIVE-10057
- New APDU used during a `getAddress`
---
=> [LIVE-10057] Feature: Add support for `chainId` in @ledgerhq/hw-app-eth and @ledgerhq/coin-evm address retrieval

.changeset/cuddly-rings-drive.md, apps/ledger-live-mobile/android/app/src/main/java/com/ledger/live/MainActivity.java
Fix secure_flag for android. 
Native secure_flag makes a white screen when app is in background. 
Switched onPause for onWindowFocusChanged ( https://issuetracker.google.com/issues/237190495 )
Before
After
- **JIRA or GitHub link**:[LIVE-10673](https://ledgerhq.atlassian.net/browse/LIVE-10673) 
- ...
---
[LIVE-10673]: https://ledgerhq.atlassian.net/browse/LIVE-10673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(llm): android preview when app is in background

.changeset/weak-frogs-flow.md, libs/coin-modules/coin-evm/src/__tests__/unit/adapters/etherscan.unit.test.ts, libs/coin-modules/coin-evm/src/__tests__/unit/adapters/ledger.unit.test.ts, libs/coin-modules/coin-evm/src/adapters/etherscan.ts, libs/coin-modules/coin-evm/src/adapters/ledger.ts, libs/coin-modules/coin-evm/src/logic.ts
Updates Operation behaviour regarding amount displayed on failed transaction and removes internal operations from a failed main operation to prevent errors in graph
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11614
- Graph is now not displaying failed transaction (except for fees)
---
=> [LIVE-11614] Bugfix - Update Operation amount on failed transaction

.changeset/sweet-eagles-greet.md, apps/ledger-live-mobile/src/components/RootNavigator/ReceiveFundsNavigator.tsx, apps/ledger-live-mobile/src/screens/ReceiveFunds/02-SelectNetwork.tsx, apps/ledger-live-mobile/src/utils/urls.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
This PR removes the depositNetworkBannerMobile feature flag and components associated with it.
- **JIRA or GitHub link**: [LIVE-11419] 
- ...
---
[LIVE-11419]: https://ledgerhq.atlassian.net/browse/LIVE-11419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LLM] - [LIVE-11419] - Remove `depositNetworkBannerMobile` feature flag

.changeset/curly-dancers-know.md, libs/ledger-live-common/src/exchange/swap/updateAccountSwapStatus.ts
Some issue we had made swaHistory to have many duplicates. We believe those bugs are fixed but we could still have issue with this so just in case filtering ids before calling back-end fixing spam
[- **JIRA or GitHub link**: ](https://ledgerhq.atlassian.net/browse/LIVE-11713)
- ...
---
=> bugfix: convert id list to map to remove duplicate

libs/coin-modules/coin-evm/src/__tests__/unit/logic.unit.test.ts
Updating the perf test of `getSyncHash` to 1s. This shouldn't be necessary to go that high, but that will unlock everyone for a while at least.
- none
---
=> Support: Update synchash perf test due to flakiness of the CI

.changeset/small-pens-clap.md, libs/ledger-live-common/src/families/evm/config.ts
Updating Linea testnet explorer URI which changed to `https://api-testnet.lineascan.build/api` 
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11846
- ...
---
=> [LIVE-11846] Bugfix: Update Linea testnet explorer URI

.changeset/empty-pans-cough.md, libs/coin-modules/coin-evm/src/api/explorer/ledger.ts
A missing index while converting ERC20 events from Ledger explorers led to unexpected missing operations in history for batched token transfers. 
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11819
- Missing ops are back
---
=> [LIVE-11819] Bugfix: Missing index in ledger ERC20 operations' ids

.changeset/heavy-snails-taste.md, apps/ledger-live-mobile/src/polyfill.ts
Some of the libraries we use on LLM use `Promise.allSettled` however it's not supported natively in mobile environment. So we use add this polyfill to add the support
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11636
- ...
---
=> [LLM] Promise.allSettled polyfill

.changeset/bright-pans-punch.md, apps/ledger-live-desktop/src/config/urls.ts, apps/ledger-live-desktop/src/renderer/modals/Help/index.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Help/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
Added the `lldChatbotSupport` feature flag to redirect to the chabot instead of the faq when enabled
The buttons impacted for now are the `Ledger Support` button in the `Help & Support` drawer and the `Ledger Support` button in the `Help` settings screen.
https://github.com/LedgerHQ/ledger-live/assets/17146928/6c631621-e68f-44f9-a9e7-ac292febda0d
- **JIRA or GitHub link**: [LIVE-11554] 
- ...
---
[LIVE-11554]: https://ledgerhq.atlassian.net/browse/LIVE-11554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LLD - Help buttons redirect to chatbot instead of faq

.changeset/silent-windows-train.md, libs/ledger-live-common/src/apps/support.ts
- ...
If the "LiveConfig.getValueByKey" method returns undefined, it means that we don't have the corresponding config key. The Ledger live should return a value instead of throwing an error.
--- …
=> fix: nanoapp minVersion check

.changeset/sharp-queens-lick.md, libs/coin-framework/src/account.test.ts, libs/coin-framework/src/account/groupOperations.ts
Fix an edge case in groupAccountsOperationsByDay method.
When getNext() returns no more operation but there is still operations in data array(the last section we should add as history operation but since totalOperations = count and we don't want to display them unless user click "see more" button)
In this case, the return variable of "completed" should be false, so that we display the "see more" button in UI.
- **JIRA or GitHub link**: [https://ledgerhq.atlassian.net/browse/LIVE-10778](https://ledgerhq.atlassian.net/browse/LIVE-10778)
- ...
---
=> fix: groupAccountsOperationsByDay bug

.changeset/grumpy-cars-rescue.md, libs/ledger-live-common/src/__tests__/test-helpers/environment.ts, libs/ledger-live-common/src/__tests__/test-helpers/setup.ts
- ...
Remote config fix for test environment.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11879
---
=> Fix: LIVE-11879 LiveConfig for bot

.changeset/thin-ants-leave.md, apps/ledger-live-mobile/ios/LaunchScreen.storyboard
- ...
Constraints on the launch screen are not set correctly. The Ledger logo is not well-centered if you use zoom on iOS.
https://github.com/LedgerHQ/ledger-live/assets/31533861/e1768820-124a-420d-b70b-8509dc964c6f
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11498
--- …
=> Launhscreen position with zoom enabled on iOS

pnpm-lock.yaml
- none
due to a [commit](https://github.com/LedgerHQ/ledger-live/commit/95701f2218deefce627e85a00789b708473e80f2) done on develop removing package.json but not running `pnpm i` again, it seems like develop have an outdated pnpm-lock.
- **JIRA or GitHub link**: n/a (firefight) 
--- …
=> chore: update pnpm-lock

apps/cli/src/commands/ptx/swap.ts, apps/ledger-live-desktop/src/renderer/actions/swap.ts, apps/ledger-live-desktop/src/renderer/components/SelectAccount.tsx, apps/ledger-live-desktop/src/renderer/drawers/OperationDetails/index.tsx, apps/ledger-live-desktop/src/renderer/families/cardano/AccountBalanceSummaryFooter.tsx, apps/ledger-live-desktop/src/renderer/families/tezos/Delegation/index.tsx, apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/CompleteExchange/Body.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/TargetAccountDrawer/index.tsx, apps/ledger-live-mobile/src/actions/swap.ts, apps/ledger-live-mobile/src/reducers/accounts.ts, apps/ledger-live-mobile/src/screens/Accounts/AccountRow.tsx, libs/coin-framework/src/account/helpers.test.ts, libs/coin-framework/src/account/helpers.ts, libs/coin-framework/src/account/ordering.ts, libs/coin-framework/src/serialization/account.ts, libs/ledger-live-common/src/account/helpers.ts, libs/ledger-live-common/src/csvExport.ts, libs/ledger-live-common/src/families/solana/bridge/bridge.ts, libs/ledger-live-common/src/families/tezos/cli-transaction.ts, libs/ledger-live-common/src/families/tezos/deviceTransactionConfig.ts, libs/ledger-live-common/src/platform/converters.ts, libs/ledger-live-common/src/wallet-api/converters.ts, libs/ledgerjs/packages/types-live/README.md, libs/ledgerjs/packages/types-live/src/account.ts
We introduced the concept of ChildAccount back in 2020 on the first implementation of Tezos which had this concept of KT Accounts. These not being strictly a token, but a "sub account of tezos", it made sense at the time to diverge from the Token Account.
Since the JS rework of tezos (2021?) as well as Tezos' sunset of kt accounts (delegation now directly happens on the main account), we no longer needed to support KT Accounts. However that type was still forgotten in our type model and became tech debt.
We can now remove it, this makes possible simplifications in the future, you can notably observe that the type `SubAccount` is now strictly equivalent to `TokenAccount`. 
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11884
---
- **The code aligns with the …
=> chore: sunset unused ChildAccount type

apps/ledger-live-desktop/static/i18n/en/app.json
- ...
Before : a user hovering unknown status would see i18n key "... operationDetailsModal.statusTooltips.unknown"
After : he will see a good translated message : "Please contact the swap provider with your swap ID for more information."
- https://ledgerhq.atlassian.net/browse/LIVE-11990
--- …
=> Add missing i18n key for unknown swap status

.changeset/silent-apricots-work.md, apps/ledger-live-desktop/src/renderer/components/ContentCards/ActionCard/index.tsx, apps/ledger-live-desktop/src/renderer/components/RecoverBanner/RecoverBanner.tsx, apps/ledger-live-desktop/src/renderer/screens/dashboard/ActionContentCards.tsx, apps/ledger-live-desktop/src/renderer/screens/dashboard/index.tsx
This makes sure that only one banner at a time is displayed, before this fix, the recover banner could appear on top of the content card banner, instead we have made it so the recover banner is first displayed before the second. This is implemented with a "passthrough" pattern (the RecoverBanner will render any children that is passed if it doesn't need to render anything, that way RecoverBanner remains decoupled from ContentCards)
On top of this, we have fixed inconsistencies in the UI of the Recover Banner that was fixed on this PR by making RecoverBanner renders an ActionCard. a leftContent generic prop was introduced to allow to inject custom left content instead of an image.
⚠️  I have only tested by modifying directly into the code to force enable recover banner because I couldn't …
=> chore: unify rendering of Recover Banner

.changeset/rotten-cups-carry.md, apps/ledger-live-desktop/src/renderer/families/tron/AccountHeaderManageActions.ts, apps/ledger-live-desktop/src/renderer/families/tron/Votes/index.tsx
This PR addresses feedback from @sprohaszka-ledger on PR #6609 
- Remove the noop conditional in the claimOnClick button as the `disabled` property already handles that. 
- Directly reference `platform/stakekit` in Tron onClicks, as there are no other staking providers.
- New changeset …
=> Address Feedback on #6609

.changeset/sharp-camels-rhyme.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/ExchangeDrawer/index.tsx, apps/ledger-live-mobile/src/screens/Swap/Form/Modal/Confirmation.tsx, apps/ledger-live-mobile/src/screens/Swap/Form/Modal/index.tsx, libs/ledger-live-common/src/exchange/swap/postSwapState.ts, libs/ledger-live-common/src/exchange/swap/setBroadcastTransaction.ts, libs/ledger-live-common/src/exchange/swap/types.ts
- ...
Add additional optional properties to the accepted & cancelled swap API calls.
For cancelled calls
```
statusCode: string;
errorMessage: string;
sourceCurrencyId: string;
targetCurrencyId: string;
hardwareWalletType: DeviceModelId;
swapType: TradeMethod;
```
and accepted calls
```
sourceCurrencyId: string;
targetCurrencyId: string;
hardwareWalletType: string;
```
https://ledgerhq.atlassian.net/browse/LIVE-11850
--- …
=> [Bugfix/LIVE-11850]: Add additional properties to the accepted & cancelled swap API calls.

.changeset/rare-sheep-sit.md, apps/ledger-live-desktop/src/renderer/components/LiveAppDrawer.tsx
- ...
Stop closing drawer after start exchange as it is always followed by a completeExchange
[- **JIRA or GitHub link**: ](https://ledgerhq.atlassian.net/browse/LIVE-11188)
---
=> bugfix: do not close drawer after startExchange

.changeset/orange-students-argue.md, apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/steps/02-step-restore.tsx
- ...
Fixes display of restore setting drawer after os update
- **JIRA or GitHub link**: [LIVE-11921]
---
[LIVE-11921]: https://ledgerhq.atlassian.net/browse/LIVE-11921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
=> :bug: [LIVE-11921] [LLD][FW Update] Restore settings drawer is empty

.changeset/itchy-tools-visit.md, apps/ledger-live-desktop/static/i18n/en/app.json, libs/ledger-live-common/src/errors.ts, libs/ledger-live-common/src/exchange/swap/initSwap.ts, libs/live-network/src/network.ts
- ...
Add error message for expired rate
https://ledgerhq.atlassian.net/browse/LIVE-11102
---
=> feat(LIVE-11102): add rate expired error message

.changeset/yellow-parents-dance.md, libs/ledger-live-common/src/families/cosmos/api/Cosmos.ts, libs/ledger-live-common/src/families/cosmos/api/Cosmos.unit.test.ts, libs/ledger-live-common/src/families/cosmos/api/types.ts
- ...
Inspired by https://github.com/LedgerHQ/ledger-live/pull/6633
Fixes cosmos redelegation parsing
- **JIRA or GitHub link**: [https://ledgerhq.atlassian.net/browse/LIVE-12100](https://ledgerhq.atlassian.net/browse/LIVE-12100)
--- …
=> [LIVE-12100] Fix cosmos redelegations

.changeset/hungry-trainers-explain.md, apps/ledger-live-mobile/src/components/SelectDevice2/index.tsx
- ...
Fix ui problem caused by a previous PR : [feat/LIVE-11955](https://github.com/LedgerHQ/ledger-live/pull/6593)
When no CC is displayed, the CTA Select device is in the middle of the screen instead of at the top.
|![image](https://github.com/LedgerHQ/ledger-live/assets/73439207/33cbfc14-d37e-4518-b82b-ba047ac22f57)| ![image](https://github.com/LedgerHQ/ledger-live/assets/73439207/be236784-668e-4120-a24b-f62dd8b534f2)|
--- …
=> fix(llm): fix ui select device screen

.changeset/three-geckos-help.md, apps/ledger-live-desktop/src/renderer/screens/dashboard/MarketPerformanceWidget/useMarketPerformanceWidget.ts, libs/ledger-live-common/src/market/v2/useMarketPerformers.ts
- ...
MarketPerf Widget wasn't updated well when Top 5 crypto is the same for multiples minutes
---
=> [FIX] :  MarketPerf Widget wasn't updated well when Top 5 crypto is the same for multiples minutes

.changeset/rich-windows-rule.md, apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/CompleteExchange/Body.tsx
* bugfix: close completeExchange drawer when sell or card
* chore: changeset
* chore: fix ci
- ...
cherrypick for release
[- **JIRA or GitHub link**: ](https://github.com/LedgerHQ/ledger-live/pull/6664)
---
=> cherrypick:  #6664

.changeset/tall-cherries-allow.md, apps/ledger-live-desktop/src/renderer/screens/platform/v2/Catalog/Card/Cta.tsx, apps/ledger-live-desktop/src/renderer/screens/platform/v2/Catalog/Card/Full.tsx
- ...
Fix ui cta card on discover
---
=> fix: CTA UI [LIVE-11696]

.changeset/sixty-days-check.md, apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/SelectUseCase/index.tsx, apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/SyncOnboardingCompanion.tsx
- ...
PR to enable stax on onboarding via recover & set the correct deeplink source for lld. 
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/PROTECT-3040
---
=> chore(PROTECT-3040): fix stax recover source & enable

.changeset/honest-laws-look.md, apps/ledger-live-desktop/package.json, apps/ledger-live-desktop/src/main/index.ts, pnpm-lock.yaml
- dev mode only
Add deep-link support in dev mode for LLD using: https://github.com/witcher112/electron-app-universal-protocol-client
---
=> chore(LLD): add deeplink support in dev mode

.changeset/fresh-pillows-poke.md, apps/ledger-live-desktop/src/renderer/families/cardano/DelegationFlowModal/steps/StepDelegation.tsx, apps/ledger-live-desktop/src/renderer/families/cardano/UndelegateFlowModal/steps/StepSummary.tsx, apps/ledger-live-mobile/src/families/cardano/Delegations/index.tsx, apps/ledger-live-mobile/src/families/cardano/UndelegationFlow/01-Summary.tsx, libs/ledger-live-common/src/families/cardano/js-estimateMaxSpendable.ts, libs/ledger-live-common/src/families/cardano/js-getTransactionStatus.ts, libs/ledger-live-common/src/families/cardano/js-getTransactionStatus.unit.test.ts, libs/ledger-live-common/src/families/cardano/js-signOperation.ts
Based on #6515 by @pavanvora and validated by @hedi-edelbloute 
Fixed `Invalid data supplied to Ledger`.
Cardano was passing empty inputs to ledger in some special scenario which was throwing error.
- **JIRA or GitHub link**: [https://ledgerhq.atlassian.net/browse/LIVE-10249](https://ledgerhq.atlassian.net/browse/LIVE-10249)
- ...
---
=> [LIVE-10249] Bugfix - Cardano invalid data supplied

.changeset/soft-hats-invent.md, apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/steps/01-step-prepare.tsx
- ...
- Remove unnecessary backup step when updating OS;
- 🧪 To test, launch un OS update on device with nothing to backup.
---
=> [LIVE-11490][LLD] Extra backup state when updating the firmware of an unseed Stax

.changeset/small-zebras-join.md, apps/ledger-live-desktop/src/renderer/Default.tsx, apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/Tutorial/index.tsx, apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/SyncOnboardingCompanion.tsx, apps/ledger-live-desktop/src/renderer/hooks/useRecoverRestoreOnboarding.ts
- ...
Previously, a user ending a Recover Restore flow prematurely (i.e. closing the window) would falsely be marked as onboarding completed. 
This PR updates the feature to ensure a shared storage variable is used in both Recover UI & Ledger Live Desktop.
Related PR: https://github.com/LedgerHQ/protect-frontend/pull/1017 & https://github.com/LedgerHQ/protect-frontend/pull/1021
[Recover FF Development](https://console.firebase.google.com/project/recover-live-app-staging/config/env/firebase?utm_campaign=welcome_2021_CTA_A&utm_medium=email&utm_source=welcome&query=desktop)
[Ledger Live FF Development](https://console.firebase.google.com/project/ledger-live-staging/config/env/firebase?utm_campaign=welcome_2021_CTA_A&utm_medium=email&utm_source=welcome&query=protect_services_de)
- **JIRA or …
=> bugfix: recover restore onboarding false positives

.changeset/curvy-moons-know.md, apps/ledger-live-desktop/src/renderer/components/TransactionConfirm/index.tsx
- **JIRA or GitHub link**: [LIVE-12305]
--- …
=> avoid displaying address field on sign transaction modal

.changeset/few-parents-applaud.md, apps/ledger-live-desktop/src/renderer/components/WebPTXPlayer/TopBar.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/index.tsx, apps/ledger-live-mobile/src/components/RootNavigator/ExchangeLiveAppNavigator.tsx, apps/ledger-live-mobile/src/components/Web3AppWebview/PlatformAPIWebview.tsx, apps/ledger-live-mobile/src/components/Web3AppWebview/WalletAPIWebview.tsx, apps/ledger-live-mobile/src/components/WebPTXPlayer/index.tsx, apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx, apps/ledger-live-mobile/src/screens/PTX/BuyAndSell/index.tsx, libs/ledger-live-common/.unimportedrc.json, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledger-live-common/src/hooks/useInternalAppIds.ts, libs/ledger-live-common/src/wallet-api/constants.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- Find flag in settings: `buySellUi`
- It should toggle on/off, but also accept params json:  `{ "params": { "manifestId": "buy-sell-ui" } }`
- when using manifestId "buy-sell-ui", the URL for buy/sell live app should change to https://buy-sell.ledger.com
- Other functionality should remain the same.
- add buy sell ui flag to enable progressive replacement of multibuy-v2 live app
- when flag is enabled, option to use "buy-sell-ui" manifest id instead of "multibuy-v2" (or to override with a custom staging manifest id)
- allow multibuy logic to apply for either buy-sell manifest
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-12118
--- …
=> [feat/LIVE-12118]: add buy sell ui flag to enable progressive replacement of multibuy-v2 live app

.changeset/nice-rats-hunt.md, .changeset/real-swans-heal.md, apps/ledger-live-desktop/src/main/setup.ts, apps/ledger-live-desktop/src/renderer/components/DeviceAction/index.tsx, apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/index.tsx, apps/ledger-live-desktop/src/renderer/hooks/useKeepScreenAwake.ts, apps/ledger-live-desktop/src/renderer/screens/manager/DeviceDashboard/AppsList/Progress.tsx, apps/ledger-live-desktop/src/renderer/screens/manager/FirmwareUpdate/index.tsx, apps/ledger-live-mobile/ios/Podfile.lock, apps/ledger-live-mobile/package.json, apps/ledger-live-mobile/src/components/FirmwareUpdate/index.tsx, apps/ledger-live-mobile/src/hooks/useKeepScreenAwake.ts, apps/ledger-live-mobile/src/screens/FirmwareUpdate/index.tsx, apps/ledger-live-mobile/src/screens/MyLedgerDevice/AppsList/AppStateButton.tsx, apps/ledger-live-mobile/src/screens/SyncOnboarding/SyncOnboardingCompanion.tsx, pnpm-lock.yaml
Prevent the screen from locking for firmware update and app installation/update
- App install inside My Ledger
- Firmware Update
- Inline App install => DeviceAction Component
- Sync Onboarding
- **JIRA or GitHub link**: [LIVE-12015] 
--- …
=> :bug: [LIVE-12015] [LLD/LLM] Prevent the screen from locking for firmware update and app installation/update

.changeset/wet-wombats-whisper.md, apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/BackupStep.tsx, apps/ledger-live-desktop/src/renderer/hooks/useRecoverRestoreOnboarding.ts, apps/ledger-live-desktop/src/renderer/screens/recover/Player.tsx, apps/ledger-live-mobile/src/screens/Protect/Player.tsx
- ...
This PR is to ensure we capture the device & model id and send this to the Recover webview, so that Recover can send the correct device analytics to segment, and ultimately mixpanel.
We mustn't mix up deviceId and deviceModelId, as they both have different internal meanings/references.
In LLD, when the device is connected via a cable then deviceId is empty & deviceModelId is required, but in LLM no cable is required and deviceId is used.
- **JIRA or GitHub link**: Relates to https://ledgerhq.atlassian.net/browse/PROTECT-3040 
Related PR in Recover: https://github.com/LedgerHQ/protect-frontend/pull/1027
--- …
=> feat(PROTECT-3040): capture device model id in recover

.changeset/green-turkeys-add.md, apps/ledger-live-desktop/src/renderer/components/WebPTXPlayer/CustomHandlers.ts
- ...
close drawer before opening error drawing, prevent double drawer issue
[- **JIRA or GitHub link**: ](https://ledgerhq.atlassian.net/browse/LIVE-12405)
---
=> bugfix: close whatever drawer is opened before opening an error drawer

.changeset/odd-pumas-grab.md, libs/coin-modules/coin-evm/src/__tests__/fixtures/synchronization.fixtures.ts, libs/coin-modules/coin-evm/src/__tests__/unit/logic.unit.test.ts, libs/coin-modules/coin-evm/src/__tests__/unit/synchronization.unit.test.ts, libs/coin-modules/coin-evm/src/logic.ts, libs/coin-modules/coin-evm/src/synchronization.ts
- swapHistory maintained between full syncs
`swapHistory` of `TokenAccounts` used to be erased between sync from scratch due to this data not being retrievable on-chain. This PR optimistically maintains those operations and their ref even after a sync from block 0.
--- …
=> bugfix: LIVE-12085 keep swap history when hard sync subAccounts

.changeset/fair-spiders-admire.md, .changeset/heavy-panthers-hammer.md, apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/EarlySecurityChecks/index.tsx, apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/helpers/createFirmwareUpdateSteps.ts, apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/index.tsx, apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/steps/01-step-prepare.tsx, libs/device-core/src/commands/use-cases/isBootloaderVersionSupported.test.ts, libs/device-core/src/commands/use-cases/isBootloaderVersionSupported.ts, libs/device-core/src/commands/use-cases/isDeviceLocalizationSupported.test.ts, libs/device-core/src/commands/use-cases/isDeviceLocalizationSupported.ts, libs/ledger-live-common/src/hw/firmwareUpdate-repair.ts
- Europa firmware update.
- Europa device localisation
Some fixes necessary to fully support firmware updates of Europa via LLM & LLD:
- `device-core`: the minimum supported version for `isBootloaderVersionSupported` and `isDeviceLocalizationSupported` were incorrect for Europa, which led to an incorrect parsing of the `getVersion` response:
- Device localisation now works fine on Europa.
- `LLD`: the "restore" step of the firmware update was only added for devices supporting device localisation. It should also take into account support of custom lock screen. Given the issue listed previously, Europa was considered as not supporting localisation, therefore highlighting this issue because the restore step was missing, and the update flow broken.
- **JIRA or GitHub link**: [LIVE-11184] …
=> [LIVE-11184][Europa] Firmware update support

.changeset/angry-garlics-try.md, apps/ledger-live-desktop/src/renderer/screens/recover/Player.tsx
- ...
Given a user is on the Recover Live App and disconnects or reconnects their device via a cable, the Recover Web Player will reload due to the useMemo dependencies. This PR is to remove `deviceModelId` from the dependency list to ensure no reload on reconnecting via cable.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/PROTECT-3040
--- …
=> bugfix(PROTECT-3040): recover webview does not reload on device disconnect

.changeset/hip-seals-design.md, .changeset/proud-moles-reply.md, apps/ledger-live-mobile/src/components/Web3AppWebview/PlatformAPIWebview.tsx, apps/ledger-live-mobile/src/components/Web3AppWebview/helpers.ts, apps/ledger-live-mobile/src/components/Web3AppWebview/liveSDKLogic.test.ts, apps/ledger-live-mobile/src/components/Web3AppWebview/liveSDKLogic.ts, libs/ledger-live-common/src/platform/types.ts
- LLM wallet-api and platform-sdk `sign.transaction` calls
Align LLM prepareSignTransaction with LLD implementation, the original PR is: https://github.com/LedgerHQ/ledger-live/pull/6759
We mainly remove the `customGasLimit` and `type: 1` that doesn't seem to be used and instead rely on the `convertToLiveTransaction` to init everything as done in LLD
- **JIRA or GitHub link**: [LIVE-12087]
---
- …
=> fix(wallet-api): align LLM prepareSignTransaction with LLD implementation [LIVE-12087]

.changeset/cold-bugs-breathe.md, libs/live-countervalues/src/api/api.ts
- countervalues if your computer date is outdated
There were an edge cae where, putting your computer system with manual date overrides would create invalid HTTP queries to countervalues API.
We prevent queries to be sent in that case.
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/LIVE-12217
--- …
=> chore: prevent live-countervalues to fetch invalid date range

.changeset/eight-cameras-tease.md, .changeset/friendly-cars-ring.md, apps/ledger-live-desktop/src/renderer/components/PlatformAppProviderWrapper.tsx, apps/ledger-live-mobile/src/PlatformAppProviderWrapper.tsx, libs/ledger-live-common/src/wallet-api/react.ts
- to replicate the error you'd need to empty out your cache on LLD before replicating the bug 
- ...
--- …
=> fix manifest loading breaking if no cache

apps/ledger-live-desktop/src/renderer/actions/general.ts, apps/ledger-live-mobile/src/actions/general.ts, libs/ledger-live-common/src/config/sharedConfig.ts
- make Firebase properly connected to CVS.
in #6771, I have used a wrong id to connect the live config CVS keys.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-11865
---
=> chore: fix Firebase integration of CVS v3 rework

.changeset/loud-jokes-rest.md, apps/ledger-live-mobile/src/locales/en/common.json
- Designed for Stax NFTs drawer
There was a linebreak between “E” and “Ink” in the text displayed for “Designed for Stax” NFTs
Add unicode in translation files so "E Ink Screen" will always remain in the same line. This handles even changes directly done in phone settings on font size. 
|![image](https://github.com/LedgerHQ/ledger-live/assets/73439207/736b4929-ca0f-4988-87a4-fd710bcf6188)|![image](https://github.com/LedgerHQ/ledger-live/assets/73439207/bfa6c6a9-a185-41c2-822c-334e41c24aa1)|
- **JIRA or GitHub link**: [LIVE-12422](https://ledgerhq.atlassian.net/browse/LIVE-12422)
--- …
=> fix(llm): improve layout on Designed for Stax NFT drawer

libs/coin-framework/src/account/balanceHistoryCache.ts, libs/coin-framework/src/account/helpers.test.ts, libs/coin-framework/src/account/helpers.ts, libs/coin-framework/src/account/pending.ts, libs/coin-framework/src/serialization/account.ts, libs/coin-framework/src/serialization/operation.ts, libs/coin-framework/src/test-helpers/bridge-integration-suite.ts, libs/coin-modules/coin-algorand/src/specs.ts, libs/coin-modules/coin-evm/src/__tests__/fixtures/common.fixtures.ts, libs/coin-modules/coin-evm/src/getTransactionStatus.ts, libs/coin-modules/coin-evm/src/logic.ts, libs/coin-modules/coin-evm/src/synchronization.ts
- ...
Related to the sunset of [ChildAccount](https://github.com/LedgerHQ/ledger-live/pull/6524), remove the use of `SubAccount` for direct use of `TokenAccount`. 
---
=> chore: remove SubAccount type usage

.changeset/four-dolls-report.md, apps/ledger-live-desktop/src/renderer/hooks/useRecoverRestoreOnboarding.ts
- ...
There is a race condition, given a user has a password in LLD, then they won't be able to progress given a dispatch is mistakenly called.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-12571
--- …
=> fix(LIVE-1257): if user has a password to bypass onboarding check

.changeset/four-dolls-report.md, apps/ledger-live-desktop/src/renderer/hooks/useRecoverRestoreOnboarding.ts
- ...
Fix an issue where the password is not recognized anymore because of a reset of accounts attribute.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-12571
---
=> Fix LIVE-12571

apps/ledger-live-mobile/e2e/models/discover/getDevicePage.ts, apps/ledger-live-mobile/src/components/Nft/NftGallery/NftList.tsx
- NFT filter animation
Trying to mitigate some flakiness on Detox tests : 
- nftGallery : disabling NFT gallery filter animation when testing which prevented filter to appear
- onboardingReadOnly and market : disabling WebView check on Android (not reliable)
- **JIRA or GitHub link**: [QAA-61](https://ledgerhq.atlassian.net/browse/QAA-61)
--- …
=> [B2CQA][Detox] Reduce NTFGallery et WebView testing flakiness

.changeset/nice-trains-dream.md, apps/ledger-live-desktop/src/renderer/screens/accounts/AccountRowItem/index.tsx
- Accounts page
A regression has been introduced to automatically scroll account pages to the bottom of the page.
|https://github.com/LedgerHQ/ledger-live/assets/73439207/234f952a-b9d8-4f49-8420-17d1ac8ced8d|https://github.com/LedgerHQ/ledger-live/assets/73439207/202a23a3-c8ef-4d36-8d4d-5b1a3c479140|
- **JIRA or GitHub link**:[LIVE-12568](https://ledgerhq.atlassian.net/browse/LIVE-12568) && https://github.com/LedgerHQ/ledger-live/pull/6796 
--- …
=> fix(lld): auto scroll when mounted on accounts page

libs/ledgerjs/packages/context-module/jest.config.ts, libs/ledgerjs/packages/context-module/package.json, libs/ledgerjs/packages/context-module/src/ContextModule.ts, libs/ledgerjs/packages/context-module/src/DefaultContextModule.test.ts, libs/ledgerjs/packages/context-module/src/DefaultContextModule.ts, libs/ledgerjs/packages/context-module/src/README.md, libs/ledgerjs/packages/context-module/src/index.ts, libs/ledgerjs/packages/context-module/src/shared/domain/ContextLoader.ts, libs/ledgerjs/packages/context-module/src/shared/model/ContextResponse.ts, libs/ledgerjs/packages/context-module/src/shared/model/LoaderOptions.ts, libs/ledgerjs/packages/context-module/src/shared/model/Transaction.ts, libs/ledgerjs/packages/context-module/tsconfig.json, pnpm-lock.yaml
- ...
Create the `context-module` package that will be used by the future `keyring-eth` to get all the context of a transaction using different backend.
This ticket is for:
- [DSDK-280](https://ledgerhq.atlassian.net/browse/DSDK-280): create context module
- [DSDK-281](https://ledgerhq.atlassian.net/browse/DSDK-281): create interfaces
- [DSDK-282](https://ledgerhq.atlassian.net/browse/DSDK-282): create entrypoint
- **JIRA or GitHub link**: [DSDK-280] [DSDK-281]
--- …
=> Feat/dsdk 280: create context-module package for clear signing

.changeset/thin-seals-tie.md, apps/ledger-live-desktop/src/renderer/actions/accounts.ts, apps/ledger-live-desktop/src/renderer/components/IsUnlocked.tsx
- LLD lock screen, unlock with ability to restore accounts
- the unlock screen will correctly be protected from race condition: once you submit the password, the input password is disabled and the form can't be sent again.
Some users seems to experience an issue with accounts being null, this can be caused when the accounts are encrypted and something fail to decrypt it in time, 
this may indicate race condition around https://github.com/LedgerHQ/ledger-live/blob/develop/apps/ledger-live-desktop/src/renderer/components/IsUnlocked.tsx#L44-L55 but at least we contain the error into the management of this code scope instead of a fatal crash that occurs in prod today.
this may reveal another race condition that this PR however don't fix but will help locate it. …
=> fix: prevent app to crash during the unlock phase

.changeset/itchy-dryers-trade.md, apps/ledger-live-desktop/src/renderer/Default.tsx
- ...
Fix analytics useEffect previously introduced that was overriding app.json 
- **JIRA or GitHub link**: https://github.com/LedgerHQ/ledger-live/pull/6857/commits/9ce66ffc48695fd0add96d48091a7d533b2ff091 & [LIVE-12571](https://ledgerhq.atlassian.net/browse/LIVE-12571)
--- …
=> fix(lld): fix analytics useEffect in default

libs/ledgerjs/packages/context-module/src/external-plugin/__tests__/abi.json, libs/ledgerjs/packages/context-module/src/external-plugin/__tests__/contract.sol, libs/ledgerjs/packages/context-module/src/external-plugin/data/DappDTO.ts, libs/ledgerjs/packages/context-module/src/external-plugin/data/ExternalPluginDataSource.ts, libs/ledgerjs/packages/context-module/src/external-plugin/data/HttpExternalPluginDataSource.test.ts, libs/ledgerjs/packages/context-module/src/external-plugin/data/HttpExternalPluginDataSource.ts, libs/ledgerjs/packages/context-module/src/external-plugin/domain/ExternalPluginContextLoader.test.ts, libs/ledgerjs/packages/context-module/src/external-plugin/domain/ExternalPluginContextLoader.ts, libs/ledgerjs/packages/context-module/src/external-plugin/model/DappInfos.ts, libs/ledgerjs/packages/context-module/src/external-plugin/model/SelectorDetails.ts, libs/ledgerjs/packages/context-module/src/token/data/HttpTokenDataSource.ts, libs/ledgerjs/packages/context-module/src/token/data/TokenDataSource.ts, libs/ledgerjs/packages/context-module/src/token/domain/TokenContextLoader.test.ts, libs/ledgerjs/packages/context-module/src/token/domain/TokenContextLoader.ts
- ...
Create the `TokenLoader` and `ExternalPluginLoader` that will get all the metadatas used to cleasign, from the CAL backend
This ticket is for:
- [DSDK-284](https://ledgerhq.atlassian.net/browse/DSDK-284): Metadata services/CAL
- [DSDK-270](https://ledgerhq.atlassian.net/browse/DSDK-270): implements CAL service
- **JIRA or GitHub link**: [DSDK-284] [DSDK-270]
--- …
=> Feat/dsdk 284 create CAL service loaders

.changeset/swift-peaches-occur.md, apps/ledger-live-desktop/.unimportedrc.json, apps/ledger-live-desktop/src/renderer/components/SideDrawer.tsx, apps/ledger-live-desktop/src/renderer/modals/Send/fields/RecipientField.react.test.tsx, apps/ledger-live-desktop/src/renderer/reducers/index.ts, apps/ledger-live-desktop/src/renderer/reducers/walletSync.ts, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/WalletSync/SideContent/Activation.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/WalletSync/SideContent/Manage.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/WalletSync/__tests__/walletSync.test.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/WalletSync/index.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/WalletSync/setupTests/shared.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/WalletSyncRow.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-desktop/tests/jestSetup.ts, apps/ledger-live-desktop/tests/testUtils.tsx, apps/ledger-live-desktop/tsconfig.json
- ...
This PR adds the Wallet Sync activation screen on LLD.
**Note:** It is missing shadows on the icons.
- **JIRA or GitHub link**: [LIVE-12264] 
---
[LIVE-12264]: …
=> [LLD] - [LIVE-12264] - Add Wallet Sync activation screen

libs/ethereum-provider/rollup.config.mjs
- ...
Remove potentially buggy import assert syntax from the ethereum-provider's rollup config
---
=> chore(ethereum-provider): remove import assert from rollup config

.changeset/eleven-houses-hunt.md, libs/ledger-live-common/src/apps/listApps/v1.ts, libs/ledger-live-common/src/apps/listApps/v2.test.ts, libs/ledger-live-common/src/apps/listApps/v2.ts
- Storage computation on Europa devices.
On Europa, the custom lock screen size in storage wasn't taken into account in the computation, therefore giving wrong informations about available storage space, and for instance letting the user try to install an app while there is actually so space available for this app.
- **JIRA or GitHub link**: [LIVE-12411] 
--- …
=> fix(common/listApps): custom lock screen size for all compatible models

.changeset/moody-hotels-arrive.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/Account/hooks/useAccountActions.tsx
- ...
This PR fixes a translation issue on the swap main header in Turkish.
- **JIRA or GitHub link**: [LIVE-10591] 
---
[LIVE-10591]: https://ledgerhq.atlassian.net/browse/LIVE-10591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …
=> [LLM] -[LIVE-10591] - Fix swap main header translation value in Turkish

.github/workflows/release-prerelease.yml
- Release Prelease workflow doesn't show the Recover input anymore
Remove the workflow recover parameter that was used to build Recover Beta. It is obsolete now.
The pre-mobile-recover.yml has already been removed from ledger-live-build repo
- **JIRA or GitHub link**: LIVE-12438
--- …
=> chore(ci) [LIVE-12438]: Remove recover input

.changeset/shiny-baboons-jog.md, apps/ledger-live-mobile/src/screens/WalletCentricAsset/index.tsx, libs/ledger-live-common/src/families/elrond/config.ts
- ...
The coin configuration for a currency should be named `config_currency_<currencyName>` however the name was not correct for elrond
---
=> fix elrond coin config name

apps/ledger-live-mobile/.unimportedrc.json, apps/ledger-live-mobile/ios/Podfile.lock, apps/ledger-live-mobile/ios/ledgerlivemobile.xcodeproj/project.pbxproj, apps/ledger-live-mobile/package.json, pnpm-lock.yaml
- there should be no impact, especially on the password lock on LLM
Remove a library that is not used at all in our codebase but still is compiled inside the LLM app.
- **JIRA or GitHub link**: n/a
---
=> chore: remove unused usage of @ledgerhq/react-native-passcode-auth

.changeset/old-carrots-complain.md, apps/ledger-live-desktop/jest.config.js, apps/ledger-live-desktop/src/renderer/components/ButtonV3.tsx, apps/ledger-live-desktop/src/renderer/screens/market/index.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/WalletSync/__tests__/walletSync.test.tsx, libs/ui/packages/react/src/components/cta/Button/index.tsx
- ...
Restore Wallet Sync integration test by fixing our Design System theme usage + by forcing styled-component dependency in Jest.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-12264
---
=> Fix wallet sync integration test

.changeset/blue-donkeys-yawn.md, apps/ledger-live-mobile/src/components/RootNavigator/ExchangeLiveAppNavigator.tsx
- Buy screen title should not be shown anymore
Does not show the default title that comes with React Navigation when navigating to the Buy screen.
- [Ticket](https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/873?assignee=712020%3Aa7bf41de-b9e1-4abb-a605-df11ab5c4df6&selectedIssue=LIVE-12357)
--- …
=> fix: hides title for Buy screen

.github/workflows/test-ui-e2e-only-desktop.yml
updated slack notif related steps to consider github event name (to post tests results on slack when workflow triggered on schedule)
notifications aren't posted on slack when workflow is triggered on schedule
=> added workflow event condition to post slack notification on schedule

.changeset/eight-coins-listen.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/Swap/Form/index.tsx, libs/ledger-live-common/src/exchange/swap/index.ts, libs/ledger-live-common/src/exchange/swap/maybeTezosAccountUnrevealedAccount.ts
- ...
reactivate https://github.com/LedgerHQ/ledger-live/pull/5893 because of https://ledgerhq.atlassian.net/browse/LIVE-12665
[- **JIRA or GitHub link**: ](https://ledgerhq.atlassian.net/browse/LIVE-12665)
---
=> bugfix: LIVE-12665 desactivate tezos unrevealed account swap

.changeset/nine-jeans-tickle.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx
- ...
- roll back the Swap button when the swap form is pending
https://github.com/LedgerHQ/ledger-live/assets/11476482/67a826ee-4b54-470b-bad1-52e2b312e586
https://ledgerhq.atlassian.net/browse/LIVE-12705
--- …
=> Fix/live 12705/show swap btn

.changeset/strange-monkeys-return.md, .github/workflows/test-ui-e2e-only-desktop.yml
- ...
- This PR addresses the issue where variables were set to `null` during scheduled workflows, causing the nightly runs to execute mocked tests instead of speculos tests.
- Activation of the Receive test.
=> ci: Updating nightly for e2e test (speculos)

.changeset/empty-elephants-end.md, apps/ledger-live-desktop/src/renderer/components/BalanceInfos/index.tsx, apps/ledger-live-desktop/src/renderer/components/PillsDaysSelect.tsx, apps/ledger-live-desktop/src/renderer/screens/dashboard/MarketPerformanceWidget/components/Header.tsx
- ...
There was a Layout issue with new Gainers/Losers trend widget if LLD is in French or German
- on Pills on Dashboard
- on Widget on Selectors (Up/down)
https://github.com/LedgerHQ/ledger-live/assets/112866305/b79628ac-c090-48ab-bde6-077a5239cae8
- **JIRA or GitHub link**: [LIVE-12735] 
--- …
=> 🐛 : [BUGFIX] Layout issue with new Gainers/Losers trend widget if LLD is in French or German

libs/ledgerjs/packages/hw-app-eth/README.md, libs/ledgerjs/packages/hw-app-eth/src/Eth.ts, libs/ledgerjs/packages/keyring-eth/jest.config.ts, libs/ledgerjs/packages/keyring-eth/package.json, libs/ledgerjs/packages/keyring-eth/src/DefaultKeyringEth.test.ts, libs/ledgerjs/packages/keyring-eth/src/DefaultKeyringEth.ts, libs/ledgerjs/packages/keyring-eth/src/Keyring.ts, libs/ledgerjs/packages/keyring-eth/src/KeyringEth.ts, libs/ledgerjs/packages/keyring-eth/src/index.ts, libs/ledgerjs/packages/keyring-eth/tsconfig.json, pnpm-lock.yaml
- ...
Create `keyring-eth` module to implement a simple keyring interface with:
- getAddress
- signTransaction
- signMessage
This PR handle two ticket:
- [DSDK-276](https://ledgerhq.atlassian.net/browse/DSDK-276): create interface
- [DSDK-275](https://ledgerhq.atlassian.net/browse/DSDK-275): create module
- **JIRA or GitHub link**: [DSDK-275] [DSDK-276]
--- …
=> Feat/dsdk 276 create keyring-eth module

.changeset/perfect-ladybugs-clap.md, .changeset/sour-crabs-sleep.md, .changeset/stale-lions-provide.md, apps/cli/src/live-common-setup.ts, apps/ledger-live-desktop/src/renderer/reducers/settings.test.ts, apps/ledger-live-desktop/src/renderer/reducers/settings.ts, apps/ledger-live-mobile/e2e/models/DeviceAction.ts, apps/ledger-live-mobile/src/components/SelectDevice2/DeviceList.tsx, apps/ledger-live-mobile/src/components/SelectDevice2/index.tsx, apps/ledger-live-mobile/src/reducers/settings.test.ts, apps/ledger-live-mobile/src/reducers/settings.ts, apps/ledger-live-mobile/src/screens/Onboarding/steps/language.tsx, libs/ledger-live-common/src/hw/index.ts
- USB connection on Android
The store has some bad data in it because we are doing bad type assertions of some objects into the `Device` type.
It's currently causing crashes at different levels of LLM, on Android.
The solution proposed here is:
- Remove the `as Device` type assertions. If an object is incorrect (here, because it does not contain device model id), it is actually unusable so it should be ignored. We could not reproduce the issue but it appears that in some rare cases, the "device discovery" of the Android USB transport sends event with such invalid objects.
- Fix the selectors so that they filter out this invalid data. In cases where it previously would have crashed, it will just behave as if the last connected device was not saved, so the app stays fonctional. The invalid …
=> [LIVE-12648] Crash because of invalid DeviceModelId

.changeset/clever-elephants-add.md, apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx
- ...
- In the case of a token currency the target account name is not shown.
- Use targetAccountCurrency name if accountNameSelector returns null or undefined.
https://ledgerhq.atlassian.net/browse/LIVE-12702
---
=> [Fix/LIVE-12702]: Use targetAccountCurrency name if accountNameSelector returns null or undefined

.github/workflows/build-mobile-external.yml
- ...
Build external mobile workflow is not working following the React Native upgrade as we need to use Java 17.
---
=> Fix Build mobile(external) to use Java 17

libs/hw-trustchain/src/CommandStreamResolver.ts, libs/hw-trustchain/src/__tests__/key_exchange.ts
- hw-trustchain lib only
have a way to access the members name and permission information
it will be needed for https://ledgerhq.atlassian.net/browse/LIVE-12628
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-12842
--- …
=> feat(hw-trustchain): add getMembersData

.changeset/chilled-days-glow.md, .changeset/three-trains-approve.md, apps/ledger-live-desktop/src/renderer/reducers/settings.ts, libs/ledger-live-common/src/families/tron/api/index.ts
- ...
Following Tron PR https://github.com/LedgerHQ/ledger-live/pull/3783/files, Vault support TRC20 as well now. But simillar to before, Tr20 transaction had to be signed in 30 seconds. Ledger Vault takes more time to approve, especially if the transaction requires multiple approvals.
Also adds the `SKIP_ONBOARDING` env variable to the `hasCompletedOnboardingSelector` of LLD to skip the onboarding for Vault users.
Vault client are unable to perform TRC20 tx because they can not approve a tx in 30 seconds
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/VSD-3366 + https://ledgerhq.atlassian.net/browse/LIVE-12852
--- …
=> [LIVE-12852] Bugfix - Extend expired time for TRC20

.changeset/thin-dolls-give.md, apps/ledger-live-desktop/tools/utils/index.js
- ...
We need to enforce only one version of styled components on dev mode for LLD.
Otherwise we cannot resolve the theme correctly depending on where we are on our stack (LLD/react-ui/icons)
Without it we do have issue with our theme
--- …
=> fix: enforce only one version of styled components on dev mode

.changeset/ten-spoons-itch.md, apps/ledger-live-mobile/jest.config.js, package.json, patches/@hashgraph__sdk@2.14.2.patch, pnpm-lock.yaml
- ...
Following the upgrade of React Native, we removed our custom resolver to rely on Metro as it supports symlinks now. hashgraph-sdk does not declare react-native files in exports so it uses default one, and we finally use the NodeClient but we can't on react-native as node stdlibs are not available.
By patching hashgraph-sdk we limit the impact of the change. In the future, we should consider other options to support Hedera.
--- …
=> Patch hashgraph-sdk with new metro resolver to use NativeClient

.changeset/brown-houses-beg.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx
- ...
remove the swap webview conditional for demo0
https://ledgerhq.atlassian.net/browse/LIVE-12813
--- …
=> fix(live-12813): remove the swap webview conditional for demo0

.changeset/polite-fireants-pay.md, apps/ledger-live-mobile/src/components/accountSyncRefreshControl.tsx, apps/ledger-live-mobile/src/components/globalSyncRefreshControl.tsx, apps/ledger-live-mobile/src/newArch/features/Market/hooks/usePullToRefresh.ts, apps/ledger-live-mobile/src/screens/Swap/History/index.tsx
- ...
add track on pull to refresh where a sync is triggered or not so we can quantify the amount of Sync requested to the backend
https://github.com/LedgerHQ/ledger-live/assets/73439207/83494b86-f77e-4aed-8096-2ee99a7afa70
- **JIRA or GitHub link**:[LIVE-12572](https://ledgerhq.atlassian.net/browse/LIVE-12572) 
--- …
=> fix(llm): add tracking on pull to refresh

.changeset/nine-mayflies-jog.md, apps/ledger-live-desktop/src/newArch/Collectibles/components/TableLayout/LayoutContainer.tsx, apps/ledger-live-desktop/src/newArch/Collectibles/components/TableLayout/LayoutToggle.tsx, apps/ledger-live-desktop/src/newArch/Collectibles/components/index.tsx, apps/ledger-live-desktop/src/newArch/Collectibles/hooks/useLayout.tsx, apps/ledger-live-desktop/src/newArch/Collectibles/types/Layouts.ts, apps/ledger-live-desktop/src/renderer/actions/settings.ts, apps/ledger-live-desktop/src/renderer/reducers/settings.ts
- ...
Move the logic that decides if want to render the collection as a List or as a Grid. Rename all variables containing "NFTs" with "Collectibles"
- **JIRA or GitHub link**:  [LIVE-12459](https://ledgerhq.atlassian.net/browse/LIVE-12459)
--- …
=> refactor(lld): tableLayout logic move inside newArch

.changeset/fifty-crabs-arrive.md, apps/ledger-live-desktop/src/renderer/modals/NoFundsStake/index.tsx, apps/ledger-live-desktop/src/renderer/screens/dashboard/FeaturedButtons.tsx, apps/ledger-live-mobile/src/components/NoFunds/NoFunds.tsx, apps/ledger-live-mobile/src/components/TabBar/TransferDrawer.tsx, apps/ledger-live-mobile/src/locales/en/common.json
- ...
remove popular tag lln
https://ledgerhq.atlassian.net/browse/LIVE-12860
---
=> feat(LIVE-12860): remove popular tag llm

.changeset/mean-baboons-camp.md, libs/live-countervalues/src/api/api.ts, libs/live-countervalues/src/logic.integration.test.ts, libs/live-countervalues/src/logic.ts
- countervalues
when a token is removed (e.g. on backend), the API returns HTTP 522 and we must treat it as a full refresh (clearing the cache). A typically usecase is cleaning up a spam coin that was accidentally in our countervalues api (e.g. stether that virtually costed millions)
- **JIRA or GitHub link**: [LIVE-11339](https://ledgerhq.atlassian.net/browse/LIVE-11339)
---
- **Any new …
=> fix: clear cache for a countervalues pair that suddenly is no longer supported

.changeset/beige-years-pump.md, apps/ledger-live-desktop/src/renderer/components/QRCodeCameraPickerCanvas.tsx
- QR code scan
When "scan qr code" pop up on send flow is opened then closed the video stream isn't stopped. 
To avoid this we cut off the stream once the pop up gets unmounted or if a qr code has been well scanned. 
|https://github.com/LedgerHQ/ledger-live/assets/73439207/486a7eb3-8a7a-4c85-a762-5457f14113b4|https://github.com/LedgerHQ/ledger-live/assets/73439207/f9033832-70d8-4cc8-b8e8-2455472e66ae|
- **JIRA or GitHub link**: [LIVE-12938](https://ledgerhq.atlassian.net/browse/LIVE-12938)
--- …
=> fix(lld): camera does not shut off when not scanning qr code

.changeset/nice-drinks-kiss.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx
- ...
render swap live app after LLD quotes loading finish
https://github.com/LedgerHQ/ledger-live/assets/11476482/2a54fdc3-8c15-42f8-b4dd-f652f556ea6e
https://ledgerhq.atlassian.net/browse/LIVE-12813 
---
=> fix: render swap live app after loading finish

apps/ledger-live-mobile/e2e/specs/market.spec.ts, apps/ledger-live-mobile/e2e/specs/onboardingReadOnly.spec.ts
- Market and onboarding readonly tests
_Buy Nano webview checks are flaky. We disable them until we fix it in [QAA-107](https://ledgerhq.atlassian.net/browse/QAA-107)
---
[QAA-107]: …
=> [QAA-106][Detox]Disable flaky webview checks

.changeset/cold-paws-shave.md, apps/ledger-live-desktop/src/renderer/screens/dashboard/MarketPerformanceWidget/components/WidgetList.tsx
- ...
Backend could encounter issues and images would not load. 
A fallback is to be created where we put the letter of the crypto in the image location 
- **JIRA or GitHub link**: [LIVE-12955] 
---
[LIVE-12955]: …
=> 🐛 [BUGFIX] : Add Fallback for Market Widget Crypto icons

.changeset/brave-scissors-brush.md, CODEOWNERS, apps/ledger-live-desktop/tests/specs/services/wallet-api.spec.ts-snapshots/wallet-api-currencies-darwin.json, apps/ledger-live-desktop/tests/specs/services/wallet-api.spec.ts-snapshots/wallet-api-currencies-linux.json, libs/ledger-live-common/src/helpers.ts, libs/ledger-live-common/src/platform/converters.ts, libs/ledger-live-common/src/platform/types.ts, libs/ledger-live-common/src/wallet-api/constants.ts, libs/ledger-live-common/src/wallet-api/converters.ts, libs/ledger-live-common/src/wallet-api/helpers.ts
- discover live-apps, only changes the ripple family name
https://github.com/LedgerHQ/ledger-live/pull/6936 only partially fixed the issue, as the ripple family name would be `xrp` instead of `ripple`
- **JIRA or GitHub link**: [LIVE-12929] 
--- …
=>  fix(wallet-api): ripple wrong family name [LIVE-12929]

.changeset/honest-balloons-walk.md, apps/ledger-live-desktop/src/renderer/Default.tsx, apps/ledger-live-mobile/src/index.tsx
- ...
Fix overriding the analytics opt in when the analyticsOptInPrompt is only enabled for the Onboarding
Automated tests covering this are coming in another PR very soon
- **JIRA or GitHub link**: [LIVE-12646]
--- …
=> 🐛 Fix overriding the analytics opt in when the analyticsOptInPrompt is only enabled for the Onboarding

.changeset/slimy-parents-glow.md, apps/ledger-live-desktop/src/renderer/families/solana/Delegation/Row.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/families/solana/Delegations/Row.tsx
- Check delegations table on LLD and LLM
Minor ui issues in Solana delegations table
1) LLD: Missing translation of delegation status
2) LLM: validator name and status icon gets overlapsed with delegation amount
[https://ledgerhq.atlassian.net/browse/LIVE-10370](https://ledgerhq.atlassian.net/browse/LIVE-10370)
[https://ledgerhq.atlassian.net/browse/LIVE-10726](https://ledgerhq.atlassian.net/browse/LIVE-10726)
--- …
=> [Bugfix]: Solana delegations minor UI issues

.changeset/few-penguins-perform.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/FirmwareUpdate/index.tsx, apps/ledger-live-mobile/src/screens/FirmwareUpdate/useUpdateFirmwareAndRestoreSettings.ts
- ...
Fix issue if Stax loses connection with LLM during firmware upgrade
- **JIRA or GitHub link**: [LIVE-12403] 
---
[LIVE-12403]: https://ledgerhq.atlassian.net/browse/LIVE-12403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …
=> [LIVE-12403] [LLM] :bug: Issue if Stax loses connection with LLM during firmware upgrade

.changeset/stale-comics-own.md, libs/ledger-live-common/src/exchange/providers/swap.ts
- swap pane
Followup of #6853:
- fix internal URL used, bypassing Cloudflare cache
- fix unused field requested
- limit request to swap partners
- add `X-Ledger-Client-Version` header for monitoring
I did not fix in this PR:
- partners data is requested again at every refresh. It is loaded from disk cache but still seems unnecessary and will cause extra backend load if cache does not work
- I am not sure if using `fetch()` is the preferred way in Ledger Live. Other parts of Ledger Live use `network` shared lib that sets the `X-Ledger-Client-Version` header we need for monitoring: https://github.com/LedgerHQ/ledger-live/blob/develop/libs/live-network/src/network.ts#L251
--- …
=> fix(live-common/exchange): fix CAL service integration

.changeset/thin-books-marry.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/WalletSync/drawers/DummyDrawer.tsx, apps/ledger-live-mobile/src/screens/Onboarding/steps/Cards/SelectionCard.tsx, apps/ledger-live-mobile/src/screens/Onboarding/steps/accessExistingWallet.tsx
- OnBoarding
During the onboarding user will have the possibility to sync LLM using wallet sync. 
A dummy drawer has been created to simulate the future one. 
Onboarding entry point is hidden behind a ff
Fix a little prop that was missing too for the rows
- **JIRA or GitHub link**: [LIVE-12194](https://ledgerhq.atlassian.net/browse/LIVE-12194)
--- …
=> feat(llm): add wallet sync entry point during onboarding

.changeset/soft-hairs-try.md, apps/ledger-live-desktop/src/renderer/components/TopBar/NotificationIndicator/InformationDrawer.tsx, apps/ledger-live-desktop/src/storyly/StorylyProvider.tsx, apps/ledger-live-desktop/src/storyly/useStoryly.tsx, apps/ledger-live-desktop/src/types/storyly-web.d.ts
- ...
Fix behavior when you click on a CTA in a Story that opens a deeplink.
Multiple tradeoffs:
- We need to force close Modals and Drawers;
- I had to disable the focus trap on the Announcement Drawer otherwise you can't interact with storyly.
To test I added this link at multiple places:
`<a href="ledgerlive://storyly?g=142749&instance=17650">Click me</a>`
https://github.com/LedgerHQ/ledger-live/assets/31533861/b7fae94c-caf4-48aa-b4ca-261cde2223c5
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-12800
--- …
=> [LIVE-12800] LLD - Storyly cta behavior with deeplinks on LLD

apps/web-tools/trustchain/components/Actionable.tsx, apps/web-tools/trustchain/components/App.tsx, apps/web-tools/trustchain/components/Expand.tsx, apps/web-tools/trustchain/components/IdentityManager.tsx, apps/web-tools/trustchain/useSDK.ts, libs/hw-trustchain/README.md, libs/hw-trustchain/src/CommandBlock.ts, libs/hw-trustchain/src/CommandStreamDecoder.ts, libs/hw-trustchain/src/CommandStreamEncoder.ts, libs/hw-trustchain/src/CommandStreamResolver.ts, libs/hw-trustchain/src/Crypto.ts, libs/hw-trustchain/src/Device.ts, libs/hw-trustchain/src/IndexedTree.ts, libs/hw-trustchain/src/StreamTree.ts, libs/hw-trustchain/src/__tests__/codec.ts, libs/hw-trustchain/src/__tests__/key_exchange.ts, libs/hw-trustchain/src/index.ts, libs/trustchain/README.md, libs/trustchain/package.json, libs/trustchain/src/api.ts, libs/trustchain/src/index.ts, libs/trustchain/src/mockSdk.ts, libs/trustchain/src/qrcode/cipher.ts, libs/trustchain/src/qrcode/index.test.ts, libs/trustchain/src/qrcode/index.ts, libs/trustchain/src/qrcode/types.ts, libs/trustchain/src/sdk.test.ts, libs/trustchain/src/sdk.ts, libs/trustchain/src/types.ts, pnpm-lock.yaml
- no impact for end user at the moment (library development)
**improvements in hw-trustchain library**
- fixes `CommandStreamDecoder` on the `readDeriveCommand`
- fixes `CommandStreamEncoder` on the `topic` field (null -> empty bytes)
- refine `CommandStreamResolver#getMembersData()` method. The `MemberData` is now an `{id, name, permissions}` object.
- rename `SodiumDevice` to `SoftwareDevice`
- `IndexedTree#getHighestIndex` added
- improve `StreamTree#getApplicationRootPath` to support key rotation and also offer a way to ask for an increment (to perform a rotation)
- added more tests.
- exported more objects on the main index.ts.
**improvements in trustchain library (sdk)**
- Introduce `TrustchainSDKContext` in order to contain all contextual information the SDK needs. it must be …
=> chore(trustchain): library sdk development

.changeset/shy-pots-brush.md, apps/ledger-live-mobile/src/newArch/components/QueuedDrawer/TestScreens.tsx, apps/ledger-live-mobile/src/newArch/components/QueuedDrawer/index.tsx
- all drawers in LLM
The property `onClose` was indirectly a dependency of the `useEffect` that triggers auto closing in some cleanup logic of the `QueuedDrawer` component.
The solution is to keep `onClose` in a ref in the component so that it can still be used in that `useEffect` without triggering the useEffect when its value changes.
https://github.com/LedgerHQ/ledger-live/assets/91890529/952ab900-1ba4-4d0e-909a-a416a4e5c0af
https://github.com/LedgerHQ/ledger-live/assets/91890529/54ae643a-d1fe-4448-a19b-fedbf3ed1600
- **JIRA or GitHub link**: [LIVE-12968] 
--- …
=> [LIVE-12968][LLM] QueuedDrawer: if onClose changes, drawer shouldn't auto close

apps/ledger-live-mobile/src/newArch/components/QueuedDrawer/TestScreens.tsx, apps/ledger-live-mobile/src/newArch/components/QueuedDrawer/index.tsx
- all drawers in LLM
Cherrypick of #7068 for the `develop` branch.
Already approved by QA & dev reviewed.
- **JIRA or GitHub link**: [LIVE-12968] 
---
[LIVE-12968]: …
=> fix(llm/QueuedDrawer): QueuedDrawer shouldn't auto close (cherrypick of #7068 for develop)

.changeset/curly-donkeys-tickle.md, libs/ledger-live-common/src/families/stacks/bridge/utils/misc.ts, libs/ledger-live-common/src/families/stacks/bridge/utils/misc.unit.test.ts, libs/ledger-live-common/src/families/stacks/synchronization.ts
- ...
The optimistics transaction disappears when transactions on stacks network takes long time. The pending operations are now added to accounts object during sync to fix the problem. 
- **JIRA or GitHub link**: [https://ledgerhq.atlassian.net/browse/LIVE-10510](https://ledgerhq.atlassian.net/browse/LIVE-10510)
--- …
=> [Fix/stacks] Optimistic operation disappears for long running transactions

libs/trustchain/src/qrcode/index.ts
- trustchain library
it seems that some recent implementations ("ws" and Chrome) is permissive to allow a https:// on a WebSocket instanciation, but it is not the case of Electron so we can explicitly replace `ws*` by `http*` (which effectively will replace https by wss too)
--- …
=> fix(trustchain): make sure the qrcode logic uses a ws(s):// url

libs/hw-trustchain/package.json, libs/hw-trustchain/src/NobleCrypto.ts, pnpm-lock.yaml
- hw-trustchain lib
we had to rollback tiny-secp256k1 to v1 – which is also what we use everywhere in other indirect users of this library – because the v2 actually requires WASM to be supported, which is not the case yet on our LLD (Electron) and LLM (React Native) environments.
--- …
=> fix(hw-trustchain): rollback tiny-secp256k1 to v1 for target without WASM support

libs/hw-trustchain/README.md, libs/hw-trustchain/src/StreamTree.ts, libs/trustchain/src/sdk.ts
- trustchain library
To fully complete the implementation of sdk.removeMember a nice to have was to "lock" the previous derivation after a rotation occurred to essentially close the previous branch of the trustchain.
- **JIRA or GitHub link**:  LIVE-12987
--- …
=> chore(trustchain): implement CLOSE on removeMember

.changeset/eight-pans-promise.md, apps/ledger-live-mobile/src/components/StorylyStories/StorylyProvider.tsx
- ...
This PR fix two issues:
- When you navigate by clicking into a cta in a Story, the Story is still considered as opened , so when you come back and try to open it again, nothing happens
- When you open a story and touch on the left on the screen, the story is closed as there are no previous story, then the story is not considered as closed and we fall into the same issue as the first one.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-12976
--- …
=> [LIVE-12976] LLM - Fix Storyly close action

.changeset/metal-oranges-heal.md, libs/ledger-live-common/src/apps/react.test.ts, libs/ledgerjs/packages/cryptoassets/src/currencies.ts
- Ethereum Classic should require its own app now instead of the generic Ethereum App
Due to Ethereum Classic using `coinType` 61 instead of 60 in the context of Ledger Live, it's incompatible with the Ethereum nano app. 
Rolling it back to using its own dedicated manager app.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-13049
https://github.com/LedgerHQ/ledger-live/assets/44363395/cbb23f59-b442-4a4d-97be-3796cb65bfba
--- …
=> [Release][LIVE-13049] Bugfix - Ethereum Classic using its own nano app

.changeset/quiet-llamas-rush.md, libs/ledger-live-common/src/apps/listApps/v2.test.ts, libs/ledger-live-common/src/apps/listApps/v2.ts, libs/ledger-live-common/src/apps/mock.ts, libs/ledger-live-common/src/device/use-cases/listAppsUseCase.ts
- Apps catalog in My Ledger.
The environment variable controlling "manager is in dev mode" was not getting passed.
I made this parameter non optional to avoid further similar regressions.
Not strictly related to the fix, but I added some tests to check that the filtering of apps with `isDevTools: true` behaves as expected.
- **JIRA or GitHub link**: [LIVE-12928] 
--- …
=> [LIVE-12928][Common] List apps v2 doesn't show apps with isDevTools when Manager in dev mode

.changeset/perfect-needles-search.md, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/FeatureFlagsSettings/index.tsx, apps/ledger-live-mobile/src/screens/Settings/Debug/index.tsx, libs/ledger-live-common/src/featureFlags/groupedFeatures.ts
- ...
Hidden press toggle europa grouped features instead of stax
- **JIRA or GitHub link**: [LIVE-13054] 
---
[LIVE-13054]: https://ledgerhq.atlassian.net/browse/LIVE-13054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …
=> [LIVE-13054] [LLD/LLM] :bug: TypeError: Cannot read property 'featureIds' of undefined

.changeset/silly-frogs-swim.md, apps/ledger-live-desktop/src/newArch/AnalyticsOptInPrompt/screens/VariantA/Main/components/MainBody/components/TrackingInfoList/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/AnalyticsOptInPrompt/variantA/Main.tsx
- Analytics translations
- opt-in prompt
Change the descriptions for Variant A of analytics opt-in prompt
This needed some little UI adjustments so text in LLM fits inside the screen.
```
New translations : 
LLD & LLM Variant A ONLY: 
First opt-in prompt screen : 
Analytics : “To measure the performance of Ledger Live and enhance both the app and your experience (Analytics).”
Personalization : “To provide you with personalized recommendations and content tailored to your preferences, as well as to help us measure the effectiveness of our marketing campaigns (Personalization).”
Second opt-in prompt screen : 
Analytics: “To measure Ledger Live’s performance and improve both the app and your experience, we share usage data, including page visits and clicks.”
Personalization: “To receive …
```
=> fix(llm/lld): change analytics opt-in translations

.changeset/orange-jokes-dream.md, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/FeatureFlagsSettings/GroupedFeatures.tsx, apps/ledger-live-mobile/src/screens/FeatureFlagsSettings/GroupedFeatures.tsx, apps/ledger-live-mobile/src/screens/FeatureFlagsSettings/index.tsx, libs/ledger-live-common/src/featureFlags/groupedFeatures.ts
=> :bug: [LIVE-13054] typing grouped features stax

.changeset/real-planets-grab.md, apps/ledger-live-mobile/src/screens/Settings/Experimental/index.tsx
Removing the KeyboardView from the Experimental settings screen to fix a crash happening since the upgrade to React Native 0.73
Here is a github issue of this exact bug : https://github.com/facebook/react-native/issues/42939
This isn't ideal as the keyboard will now go over the fields in the bottom of the screen but it fixes the crash while we implement a better solution
- **JIRA or GitHub link**: [LIVE-12996]
--- …
=> LLM - fix crash on experimental settings screen

.changeset/warm-rules-tie.md, apps/ledger-live-desktop/src/renderer/components/TokenRow.tsx, apps/ledger-live-desktop/src/renderer/screens/accounts/AccountRowItem/index.tsx
- ...
Fix pre release problem about counter values. Also fix an UI error on accounts 
- [LIVE-13072](https://ledgerhq.atlassian.net/browse/LIVE-13072)
- [LIVE-13091](https://ledgerhq.atlassian.net/browse/LIVE-13091)
--- …
=> fix(lld): fix countervalues release

.changeset/sweet-papayas-complain.md, libs/ledgerjs/packages/hw-transport-node-hid-noevents/package.json, libs/ledgerjs/packages/hw-transport-node-hid-singleton/package.json, libs/ledgerjs/packages/hw-transport-node-hid/package.json, pnpm-lock.yaml
- fix node-hid version to `2.1.2`
On ubuntu LTS 20.04 with glibc < 2.33, `node-hid 2.2.0` is looking for a missing version of glibc on runtime during device connexion. 
Force node-hid version to `2.1.2` fix it.
- **JIRA or GitHub link**: [LIVE-13021] 
--- …
=> :bug: [LIVE-13021] [LLD][Ubuntu] Device not recognised on LLD for Ubuntu

apps/ledger-live-desktop/src/sentry/install.ts
- LLD sentry reporting filtering
actively ignore `Render frame was disposed before WebFrameMain could be accessed` in the list of Sentry ignored errors to not spam our Sentry with silent reports.
This error is triggered when a second click to a URI link it clicked from inside a live app, e.g. the Stake action in Earn live app.
The error is currently not problematic but just an annoyance in dev mode
pending a proper report to Electron team, we still need to actively ignore the error to be sent to Sentry and this is what this PR is doing.
- **JIRA or GitHub link**: LIVE-12926
---
- …
=> fix(lld): Ignore silent JS error on will-frame-navigate second event

.changeset/orange-icons-rescue.md, apps/ledger-live-desktop/src/renderer/screens/manager/Dashboard.tsx, libs/device-core/src/commands/use-cases/getDeviceName.ts
- ...
Investigations for this bug: 
- An old apdu `e0500000`, which is bad formatted, was sent to the device (https://ledgerhq.atlassian.net/browse/LIVE-5273), we chose to delete it as it has no impact to get device/set device on LLM or LLD
- the firmware update bring a device disconnection on next allow manager, but only with a language pack install. Caused by `e053000000` APDU
After several tests that leaded to random behaviors, a trivial solution was to reset the dashboard with the app restauration list after disconnection. 
- **JIRA or GitHub link**: []LIVE-12734] 
---
https://github.com/LedgerHQ/ledger-live/assets/145363160/0c995d41-afa1-4bdd-a79b-b3fe7df014a1 …
=> :bug: [LIVE-12734] [LLD] Device disconnect during restore apps on LNX causing the app restore to fail

.changeset/famous-gifts-cough.md, apps/ledger-live-mobile/src/components/WebViewScreen/index.tsx
- All WebViews
On ios when user press buy a ledger now it opens a webview and auto play a video. It seems like _mediaPlaybackRequiresUserAction_ property for webview is wrongly documented and is set to _true_ by default only for android. 
See => (https://github.com/react-native-webview/react-native-webview/issues/2369)
|https://github.com/LedgerHQ/ledger-live/assets/73439207/605ab607-e6a6-4d8f-b308-a82b05af73e6|https://github.com/LedgerHQ/ledger-live/assets/73439207/552c424c-51ae-46a2-a287-269f33e92371
|https://github.com/LedgerHQ/ledger-live/assets/73439207/e76f8887-90c4-4efd-be79-50fcada5ac09|https://github.com/LedgerHQ/ledger-live/assets/73439207/d897109f-d295-48eb-8bde-153c63ba139e| …
=> fix(llm): webview autoplay video on ios

.changeset/sharp-rabbits-accept.md, libs/ledger-live-common/src/hw/actions/renameDevice.ts, libs/ledger-live-common/src/hw/renameDevice.ts
- renameDevice in live-common to start with a quitApp
This bugfix adds the quitApp action before launching the renameDevice flow, thus removing the broken behavior is the user opened an app while the rename device modal is open.
I went with proposal 1 in the ticket, we could have also decided to make the error a bit more explicit but I believe this is a better UX
- **JIRA or GitHub link**: [LIVE-11803] 
--- …
=> bugfix: LIVE-11803 - rename device broken if an app is open

.changeset/modern-forks-invent.md, apps/ledger-live-mobile/src/screens/ReceiveFunds/02-SelectAccount.tsx
- no tests yet but covered by type safety that wasn't correctly made before my change, on the whole SelectAccount file. 
- Receive funds flow when selecting a token
**Root cause:** the rework of https://github.com/LedgerHQ/ledger-live/pull/6534
as seen here, we did a mistake on LLM ReceiveFunds/02-SelectAccount file where we passed a `Currency` instead of an `Account` on the getDefaultAccountName function.
unfortunately the bad typing was hiding the issue: bad casting using `item.parentAccount as Account` which hides the problem. because actually .parentAccount is a `Account | undefined`. since we didn't have the | undefined part, TypeScript will infer the code as a `Account` and not as an `Account | Currency` that is actually the type of the previously bad code here.
the fix:
- **JIRA or …
=> fix(llm): improve typing of ReceiveFunds/02-SelectAccount and fix crash case

.changeset/rude-flowers-breathe.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/ReceiveFunds/02-AddAccount.tsx
- Receive funds flow -> sync accounts with Ledger Device -> Scan OnChain Accounts
Fix typo if there is only 1 account during sync
Instead of "1 __accounts__  found" we will have "1 __account__ found" without the **s**
|https://github.com/LedgerHQ/ledger-live/assets/73439207/e6da81eb-448c-403f-bc04-c99ab2cbc0ec|https://github.com/LedgerHQ/ledger-live/assets/73439207/b63d1432-d633-4751-9cac-fb5dbd7e65eb|
- **JIRA or GitHub link**: [LIVE-12978](https://ledgerhq.atlassian.net/browse/LIVE-12978)
--- …
=> :bug:fix(llm): typo when 1 account found after scan

.changeset/shy-seahorses-divide.md, libs/coin-modules/coin-solana/src/deviceTransactionConfig.ts
- ...
I couldn't reproduce the issue anymore that was present last week with the thrown error but to be sure I propose this change to avoid any error thrown in a render cycle
- **JIRA or GitHub link**: [LIVE-12394] 
--- …
=> fix: avoid throwing in getDeviceTransactionConfig [LIVE-12394]

libs/trustchain/src/errors.ts, libs/trustchain/src/mockSdk.ts, libs/trustchain/src/sdk.ts, libs/trustchain/src/types.ts
- trustchain lib
- remap device error `UserRefusedOnDevice`. that should make LLD/LLM use the proper wording for the case you refuse on device.
- introduce `TrustchainEjected` error: when you try to do a restoreTrustchain and you are no longer a member (can't read the member key in the trustchain) this error is thrown and the UI will have to reset (eject) the user from the trustchain.
- introduce `sdk.refreshAuth` which can be used to actively refresh a JWT token.
- throw an error when you try to remove yourself because the sdk don't implement this well. pending product to tell us if we still want it supported.
- **JIRA or GitHub link**: part of LIVE-13112
---
- **The PR description clearly documents …
=> trustchain sdk: some error management and sdk.refreshAuth added

.changeset/lemon-pumpkins-speak.md, libs/ledger-live-common/src/exchange/swap/api/v5/fetchCurrencyAll.ts, libs/ledger-live-common/src/exchange/swap/api/v5/fetchCurrencyFrom.ts, libs/ledger-live-common/src/exchange/swap/api/v5/fetchCurrencyTo.ts, libs/ledger-live-common/src/exchange/swap/hooks/v5/constants.ts, libs/ledger-live-common/src/exchange/swap/hooks/v5/useFetchCurrencyAll.ts, libs/ledger-live-common/src/exchange/swap/hooks/v5/useFetchCurrencyFrom.ts, libs/ledger-live-common/src/exchange/swap/hooks/v5/useFetchCurrencyTo.ts
- ...
Cache fetch currencies from / to for 5mins and url dependent
- **JIRA or GitHub link**: [LIVE-13069](https://ledgerhq.atlassian.net/browse/LIVE-13069)
--- …
=> feat(LIVE-13069): swap llm currencies from currencies all seem to be cached forever

.changeset/tall-moons-flow.md, libs/coin-modules/coin-tron/src/bridge/getTransactionStatus.ts
- ...
Use `NotEnoughGas` error in `getTransactionStatus` of Tron bridge, this will allow us to prompt user to buy more currencies if needed. 
Use error if the account balance is `0` or below required estimated gas value
- **JIRA or GitHub link**: [LIVE-13101](https://ledgerhq.atlassian.net/browse/LIVE-13101)
--- …
=> fix(LIVE-13072): use NotEnoughGas to suggest buying more currency

apps/ledger-live-desktop/src/index.ts, apps/ledger-live-desktop/src/renderer/init.tsx, apps/ledger-live-desktop/tests/specs/speculos/add.account.spec.ts
- Speculos tests
- Mocked tests
Currently date and time is mocked for all Playwright tests. We choose to disable mocked time for Speculos tests (MOCK false) to prevent some issue in tests (Date.parse is invalid function issue)
- **JIRA or GitHub link**: [Speculos test run](https://github.com/LedgerHQ/ledger-live/actions/runs/9641394366)
--- …
=> [QAA-121][Playwright] Disable time mocking for speculos tests

.changeset/tame-rings-hide.md, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Activation/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Activation/ActivationDrawer.tsx, apps/ledger-live-mobile/src/screens/Onboarding/steps/accessExistingWallet.tsx
- Onboarding (welcome back)
Add activation drawer in onboarding entry point. 
This drawer calls the same component that we call inside a screen for the settings entry point [#7086](https://github.com/LedgerHQ/ledger-live/pull/7086)
https://github.com/LedgerHQ/ledger-live/assets/73439207/961fa2b9-dbe3-4d0c-8824-8f6131d70dde
- **JIRA or GitHub link**: [LIVE-12149](https://ledgerhq.atlassian.net/browse/LIVE-12149)
--- …
=> ⛓️feat(llm): add WS activation drawer from onboarding

.changeset/spicy-waves-wave.md, libs/ui/packages/native/src/components/Form/Input/AnimatedInput/AnimatedNotchedLabel.tsx, libs/ui/packages/native/src/components/Form/Input/AnimatedInput/index.tsx
- Animated Input 
Animation didn't get triggered on LLM on animated input for ENS. We don't know if this was due to a slow app, an error or smth else. 
To test it we can use react extensions on browser and update manually the value inside the input.
Since we can't reproduce the bug on any env this fix may resolve it. 
- **JIRA or GitHub link**: [LIVE-12654](https://ledgerhq.atlassian.net/browse/LIVE-12654) 
--- …
=> :bug:fix(RN-UI): animated input didn't watch if there was a value entered

.changeset/plenty-weeks-double.md, .changeset/weak-kings-flow.md, apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx, apps/ledger-live-mobile/src/components/ValidateOnDevice.tsx
- Fix Flex wrong onboarding workflow bug;
- Fix title overlaps during Send on Flex.
- Fix Flex wrong onboarding workflow bug;
- Fix title overlaps during Send on Flex.
- **JIRA or GitHub link**: [LIVE-13096](https://ledgerhq.atlassian.net/browse/LIVE-13096) [LIVE-13098](https://ledgerhq.atlassian.net/browse/LIVE-13098)
---
- …
=> [LIVE-13096][LIVE-13098][LLM][Flex] Wrong redirection and text overlaps during Send

.changeset/lucky-lobsters-rescue.md, libs/ledger-live-common/src/families/polkadot/config.ts, libs/ledgerjs/packages/hw-app-polkadot/src/Polkadot.ts
- ...
In react-native, the "app.signWithMetadata" method returns a polkadot signature. It is not a Buffer type variable, we need to cast it to Buffer explicitly. It is only related to Ledger Live mobile app.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-13226
--- …
=> bugfix: LIVE-13226 polkadot send for runtime upgrade

.changeset/eighty-crabs-do.md, apps/ledger-live-desktop/tests/specs/services/wallet-api.spec.ts, apps/ledger-live-desktop/tests/userdata/1AccountBTC1AccountETH1AccountARB.json, libs/ledger-live-common/src/wallet-api/react.ts
- discover
- buy/sell
- card
- on all it's the listing of currencies and tokens that is affected
Fix some tokens not showing in the wallet-api because we cached the listCurrencies at the start of the app and apparently some info are not yet available at that time
But we still have an issue if no accounts is present for a parent family no tokens will be loaded and present in our `currency.list`
| Before | After |
| -------- | ------- |
| <img width="526" alt="Screenshot 2024-06-28 at 19 10 33" src="https://github.com/LedgerHQ/ledger-live/assets/3009753/25f6d7c2-e90a-4ccf-b45e-c5031a44d96d">  |   <img width="527" alt="Screenshot 2024-06-28 at 19 11 55" src="https://github.com/LedgerHQ/ledger-live/assets/3009753/30b923cd-49fd-4a47-adb8-4a7bca2f59b9">  | …
=> fix(wallet-api): avoid caching listCurrencies result too early [LIVE-13205]

.changeset/thin-pugs-fly.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/index.tsx
- remove unused useEffect for demo1
- ...
https://ledgerhq.atlassian.net/browse/LIVE-12781
https://ledgerhq.atlassian.net/browse/LIVE-13280
--- …
=> fix(LIVE-13280): remove the setState in useEffect

.changeset/orange-ties-rescue.md, apps/ledger-live-mobile/src/live-common-setup.ts
- no impact
Due to a bad rebasing with the merging of Scroll, blast & blast sepolia have been forgotten in the set of supported currencies for LLM. This PR fixes this.
---
=> [Bugfix]  Add missing supported currency blast in LLM

.changeset/honest-years-remain.md, libs/coin-modules/coin-tron/src/network/index.ts
- no impact, just no more 403 :p 
While doing requests to TronGrid, the API might provide some links to follow in order to get either the next paginated response. Those links are directly calling TronGrid, which might rate limit people doing too many requests.
This PR replace the TronGrid's URI with the RP's URI for those links.
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/LIVE-13288
--- …
=> [LIVE-13288] Bugfix - Replace TronGrid URI in pagination links

apps/web-tools/trustchain/components/AppGetOrCreateTrustchain.tsx, libs/trustchain/src/mockSdk.ts, libs/trustchain/src/sdk.ts, libs/trustchain/src/test-scenarios/_template.ts, libs/trustchain/src/test-scenarios/create2trustchainInARow.ts, libs/trustchain/src/test-scenarios/getOrCreateTransactionCases.ts, libs/trustchain/src/test-scenarios/member3implicitlyAdded.ts, libs/trustchain/src/test-scenarios/randomMemberTryToDestroy.ts, libs/trustchain/src/test-scenarios/removeMemberWithTheWrongSeed.ts, libs/trustchain/src/test-scenarios/removedMemberEjected.ts, libs/trustchain/src/test-scenarios/removingAMemberCreatesAnInteraction.ts, libs/trustchain/src/test-scenarios/removingYourselfIsForbidden.ts, libs/trustchain/src/test-scenarios/success.ts, libs/trustchain/src/test-scenarios/tokenExpires.ts, libs/trustchain/src/types.ts
- trustchain library, getOrCreateTrustchain
The UI needs an evolution to be able to tell what exactly happened on `getOrCreateTrustchain` and branch different wording based on it.
There are 3 cases:
```ts
| {
// the trustchain didn't exist and was created
type: "created";
trustchain: Trustchain;
}
| {
// the trustchain already existed and was updated (typically the current member was added)
type: "updated";
trustchain: Trustchain;
}
| {
// the trustchain existed and was just retrieved (no need to update it)
type: "restored";
trustchain: Trustchain;
}
```
they are covered by our existing integration tests without having to update snapshots.
- **JIRA or GitHub link**: n/a (slack request)
---
- **The PR …
=> chore(trustchain): getOrCreateTrustchain returns a type to explain the effect

.changeset/tiny-drinks-smell.md, apps/ledger-live-desktop/src/newArch/WalletSync/Flows/Activation/01-CreateOrSynchronizeStep.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/Flows/Activation/04-ActivationFinalStep.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/Flows/Activation/index.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/Flows/Manage/index.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/Flows/ManageInstances/04-DeletionError.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/Flows/ManageInstances/04-DeletionFinalStep.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/Flows/Synchronize/01-SyncModeStep.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/Flows/Synchronize/02-QRCodeStep.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/Flows/Synchronize/03-PinCodeStep.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/Flows/Synchronize/04-SyncFinalStep.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/Flows/Synchronize/index.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/components/Success.tsx, apps/ledger-live-desktop/src/newArch/WalletSync/hooks/useWalletSyncAnalytics.ts, apps/ledger-live-desktop/src/renderer/analytics/segment.ts, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/WalletSync.tsx
- ...
Add analytics for WalletSync in LLD  related to https://ledgerhq.atlassian.net/wiki/spaces/WXP/pages/4653973505/Wallet+Sync+-+LLD+Data+Tracking+Plan
- Page
- Button clicked
- Back button
- Close button
Close Event : 
https://github.com/LedgerHQ/ledger-live/assets/112866305/e4ab150d-11c6-4018-ab2d-87470c9c8ae9
Back Event : 
https://github.com/LedgerHQ/ledger-live/assets/112866305/c9060e69-da6d-4d35-9fe0-6c440e362d11
- **JIRA or GitHub link**:  [LIVE-12205]
--- …
=> [FEAT]  : Analytics WalletSync

.changeset/good-frogs-run.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx, apps/ledger-live-desktop/src/renderer/screens/swapWeb/index.tsx
- ...
In the renderer we might want to use `@sentry/electron/renderer` and not `@sentry/node`.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-13321
---
=> fix(lld): use correct Sentry on renderer side

.changeset/moody-moose-glow.md, apps/ledger-live-mobile/src/components/CustomImage/ImageHexProcessor.tsx, apps/ledger-live-mobile/src/components/CustomImage/ImageProcessor.tsx, apps/ledger-live-mobile/src/components/CustomImage/injectedCode/imageBase64ToHexProcessing.ts, apps/ledger-live-mobile/src/components/CustomImage/injectedCode/imageHexToBase64Processing.ts
- Set image for stax
The `webview` used for the `imageProcessor` was not using a `source` prop, leading to a bad state in the webview not even able to render the error
Also directly injecting the javascript in the html page loaded by the webview instead of using the `injectJavascript` prop
- **JIRA or GitHub link**: [LIVE-13334]
---
- …
=> fix: imageProcessor webview should have a source [LIVE-13334]

.changeset/few-laws-matter.md, apps/ledger-live-desktop/src/newArch/WalletSync/hooks/useRemoveMember.ts
- ...
Handle Unsecured error for Ledger Sync when using wrong Ledger to remove instance
https://github.com/LedgerHQ/ledger-live/assets/112866305/a1382b1f-c46c-420c-887d-2b5377ba865c
---
=> [FEAT] : Handle Unsecured error for Ledger Sync

.changeset/healthy-days-pay.md, apps/ledger-live-desktop/src/renderer/drawers/DataSelector/AccountList.tsx, apps/ledger-live-desktop/tests/page/drawer/drawer.ts, apps/ledger-live-desktop/tests/specs/services/wallet-api.spec.ts
- All live-apps that use the account selection with tokens
- buy/sell
- earn
AccountList not showing the correct name and balance for tokens
Introduced in this big PR: https://github.com/LedgerHQ/ledger-live/pull/6796
It's hard to catch this kind of bug, so it should be covered now with the test
- **JIRA or GitHub link**: [CN-142]
--- …
=> fix(LLD): AccountList not showing the correct name and balance for tokens [CN-142]

.changeset/cyan-panthers-drop.md, .changeset/sweet-wolves-push.md, CODEOWNERS, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/Web3Hub/HeaderContext.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/Navigator.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/__integrations__/mocks/manifests.ts, apps/ledger-live-mobile/src/newArch/features/Web3Hub/__integrations__/web3hub.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/components/ManifestsList/CategoriesList/Badge/index.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/components/ManifestsList/CategoriesList/index.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/components/ManifestsList/LoadingIndicator/index.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/components/ManifestsList/ManifestItem/index.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/components/ManifestsList/index.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/screens/Web3HubApp/components/Header/index.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/screens/Web3HubApp/index.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/screens/Web3HubMain/components/Header/index.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/screens/Web3HubMain/index.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/screens/Web3HubSearch/components/Header/index.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/screens/Web3HubSearch/index.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/screens/Web3HubTabs/components/Header/index.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/screens/Web3HubTabs/index.tsx, libs/ui/packages/native/src/components/Form/Input/BaseInput/index.tsx
- none feature behind FF
Prepared a good template for the other screens
Fixed a lot of small details with the headers and lists while working on it
Implemented some integration tests for the current screens and logic
Only mocks to fetch for now
Started i18n
Also for the changes on the native-ui lib you can see the warning that was printed in the screenshot below, I'm not sure if there is an impact to my change and I suppose that I could also just remove the line
- **JIRA or GitHub link**: [LIVE-13176] [LIVE-13182] [LIVE-13183] [LIVE-13186]
--- …
=> feat(web3hub): main and search screen first iteration [LIVE-13176]

.changeset/heavy-humans-hide.md, apps/ledger-live-mobile/src/components/BleDevicePairingFlow/BleDevicesScanning.tsx, apps/ledger-live-mobile/src/screens/BleDevicePairingFlow/index.tsx
- LLM onboarding flow has been updated;
- Now the property `filterByDeviceModelId` of component `BleDevicePairingFlow` can be passed an array of `DeviceModelId` which will be transferred directly to filter (already supported). This can allow us show all devices with screen after scanning a QR code (no device info included for now).
- Fix filter not work bug when clicking device.
- **JIRA or GitHub link**: [LIVE-13346]
--- …
=> [LIVE-13346][LLM][BLE] Device search in BLE during onboarding doesn't filter on the selected device

libs/live-wallet/package.json, libs/live-wallet/src/cloudsync/__tests__/cipher.test.ts, libs/live-wallet/src/cloudsync/cipher.ts, libs/trustchain/src/mockSdk.ts, pnpm-lock.yaml
- live-wallet lib
Switch `fflate` to `pako` library in `@ledgerhq/live-wallet` because fflate don't support Electron properly. (it features detect renderer as node supported but it's partially supported: ` The V8 platform used by this instance of Node does not support creating Workers`)
NB: `pako` is already used in other part of our monorepo, so it also makes sense to reduce deps
- **JIRA or GitHub link**: n/a
--- …
=> chore(wallet): move to pako compression lib

apps/web-tools/trustchain/components/AppAccountsSync.tsx, apps/web-tools/trustchain/components/AppCloudSync.tsx, libs/live-wallet/src/cloudsync/__tests__/sdk.test.ts, libs/live-wallet/src/cloudsync/sdk.ts, libs/live-wallet/src/walletsync/createWalletSyncWatchLoop.ts, libs/live-wallet/src/walletsync/index.ts, libs/trustchain/src/errors.ts, libs/trustchain/src/sdk.ts
- trustchain, live-wallet libs
move the handling of `onTrustchainRefreshNeeded` to the **watch loop** to have less to handle in CloudSync sdk.
on the other hand, cloud sync will throw a new error `TrustchainOutdated` when it detects some unusually data delete case, which is what may happens during the rotation and when the user is "active" (poll() with a previously used jwt). A test still covers this part.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-13357 
---
- **The PR …
=> chore(trustchain): detect more cases of trustchain refresh needs

libs/live-wallet/src/cloudsync/api.ts
- live-wallet cloudsync
extracted from https://github.com/LedgerHQ/ledger-live/pull/7300
this fixes a possible case where the backend sometimes return `info: null` in payload of out-of-sync status of cloudsync
--- …
=> chore(wallet): fixes cloudsync api parser on out-of-sync info nullable

libs/live-wallet/src/store.test.ts, libs/live-wallet/src/store.ts, libs/live-wallet/src/walletsync/createWalletSyncWatchLoop.ts, libs/live-wallet/src/walletsync/index.ts
- live-wallet
this improve live-wallet/walletsync stack to allows a smooth integration in LLD. ( this code changes is extracted from https://github.com/LedgerHQ/ledger-live/pull/7300 )
- `createWalletSyncWatchLoop`
- differentiate the polling interval from the initial timeout. ultimately moving to just using `setTimeout` for both.
- introduces `onStartPolling` which allows us to know when to set the last error (given by `onError`) back to null
- introduces `onUserRefreshIntent` which is returned by the watch loop and allows the user to force a refresh. we debounce it with a setTimeout.
- introduce `walletStateExportShouldDiffer` predicate to know if live-wallet store's export have changes
- introduce `wsStateSelector` to access the WSState
---
- **The code …
=> chore(walletsync): improve walletsync lib

.changeset/nasty-windows-suffer.md, libs/live-network/src/network.ts
- live-network
This is a generalisation of existing code to explicit the list of statusCodes that are allowed to be retried.
this avoid our stack to do 3 failing http code in a row for http code that will always fails anyway, for instance a Unauthorized case (where you fail authentication). 
**in live-hub context, this is a problem for Wallet Sync feature:**
the committed statusCodes list is taken from https://github.com/sindresorhus/got/blob/main/documentation/7-retry.md#retry
--- …
=> chore(live-network): only retry network for status code that makes sense

libs/live-wallet/src/cloudsync/__tests__/sdk.test.ts, libs/live-wallet/src/cloudsync/sdk.ts
- live-wallet cloudsync
there were a case where you could be stuck forever in a `TrustchainOutdated` case in the watch loop: when CloudSyncSDK see a deleted data from the backend, it needs to dispatch `deleted-data` in order for the user land to effectively save the deletion of the data and the new version to be back to zero. it will still throw TrustchainOutdated as opportunity for user land to also refresh the trustchain (sdk.restoreTrustchain called through the `onTrustchainRefreshNeeded` callback)
--- …
=> fix(cloudsync): to apply deleted-data on outdated case

apps/ledger-live-desktop/tests/specs/speculos/receive.address.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/subAccount.spec.ts
=> Activate disabled tests in speculos folder

apps/ledger-live-desktop/src/main/db/index.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/components/WalletSyncContext.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useDestroyTrustchain.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useOnTrustchainRefreshNeeded.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useTrustchainSdk.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useWatchWalletSync.ts, apps/ledger-live-desktop/src/renderer/Default.tsx, apps/ledger-live-desktop/src/renderer/actions/accounts.ts, apps/ledger-live-desktop/src/renderer/actions/trustchain.ts, apps/ledger-live-desktop/src/renderer/actions/wallet.ts, apps/ledger-live-desktop/src/renderer/bridge/cache.ts, apps/ledger-live-desktop/src/renderer/components/IsUnlocked.tsx, apps/ledger-live-desktop/src/renderer/components/TopBar/ActivityIndicator.tsx, apps/ledger-live-desktop/src/renderer/init.tsx, apps/ledger-live-desktop/src/renderer/middlewares/db.ts, apps/ledger-live-desktop/src/renderer/reducers/accounts.ts, apps/ledger-live-desktop/src/renderer/reducers/trustchain.ts, apps/ledger-live-desktop/src/renderer/reducers/wallet.ts, apps/ledger-live-desktop/src/renderer/storage.ts, apps/web-tools/trustchain/components/App.tsx, apps/web-tools/trustchain/components/AppAccountsSync.tsx, libs/live-wallet/src/ordering.test.ts, libs/live-wallet/src/store.test.ts, libs/live-wallet/src/store.ts
- LLD when trustchain is active
**This integrates Wallet Sync feature on LLD.**
- `walletSyncWatchLoop` is integrated in LLD.
- error automatic handling (removing someone in the members, it will detects that it needs to restoreTrustchain, if member is yourself it will also automatically ejects)
- UI: error and pending state are displayed on the global **✅  Synchronized** top activity banner.
- **JIRA or GitHub link**: live-12636
--- …
=> LLD integration of Wallet Sync

.changeset/tough-bulldogs-ring.md, apps/ledger-live-mobile/__tests__/jest-setup.js, apps/ledger-live-mobile/src/components/RootNavigator/types.ts, apps/ledger-live-mobile/src/components/RootNavigator/types/BaseNavigator.ts, apps/ledger-live-mobile/src/components/RootNavigator/types/MainNavigator.ts, apps/ledger-live-mobile/src/components/RootNavigator/types/helpers.ts, apps/ledger-live-mobile/src/newArch/features/Web3Hub/Navigator.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/TabNavigator.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/__integrations__/web3hub.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/components/BackButton/index.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/components/ManifestsList/LoadingIndicator/index.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/components/TabButton/index.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/screens/Web3HubApp/components/Header/index.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/screens/Web3HubMain/components/Header/index.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/screens/Web3HubSearch/components/Header/index.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/screens/Web3HubTabs/components/Header/index.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/types.ts
- none behind a disabled FF
Add tabs button to main, search and app screens
Added a test for tabs button navigation
Remove some testIDs from the tests and use roles (can be a bit slower but also more correct for accessibility)
Mock buttons from RNGH as it was not working in jest tests
Moved the ReactNavigation declaration merging to ~RootNavigator~BaseNavigator next to the declaration of the ~root~ type (I'll probably do the change to RootNavigator in another PR)
Added MainComposite for tab sub screens used in web3hub tab navigator
Colocate all navigator types
Refactor BackButton
Fixed header styles and animatedStyles for proper placement and sizing
- **JIRA or GitHub link**: [LIVE-13181] [LIVE-13184]
---
- **The code aligns with the requirements** described in the linked JIRA or GitHub …
=> feat(web3hub): add tabs button to main, search and app screens [LIVE-13181]

.changeset/cyan-melons-fetch.md, .changeset/polite-bananas-relax.md, .changeset/rare-windows-rhyme.md, apps/ledger-live-desktop/src/renderer/reducers/market.ts, apps/ledger-live-desktop/src/renderer/screens/market/components/SearchInputComponent.tsx, apps/ledger-live-mobile/src/newArch/features/Market/screens/MarketList/components/SearchHeader/index.tsx, apps/ledger-live-mobile/src/reducers/market.ts, libs/ledger-live-common/src/market/api/index.ts, libs/ledger-live-common/src/market/hooks/useMarketDataProvider.ts
- ...
Discussed in 
https://ledgerhq.atlassian.net/wiki/spaces/BE/pages/4867096580/2024-07-18+CVS+freshness+markets+traffic+analysis
Improvements in this PR : 
- Debounced search in LLD
- Uppercase counterCurrency in LLM/LLD
- lowercase search in LLM/LLD
- 2 characters are needed now to trigger search
- sort ids when favorite filter in On
What's next ? 
- LLM pagination fix
- Discrepancy between listing page and coin page
DEMO 
https://github.com/user-attachments/assets/0438f0a8-7cb9-493f-ba12-a047ec2f8fb8
https://github.com/user-attachments/assets/bbb020bc-034b-4ea5-8513-cf0c54142ca5
--- …
=> [FEAT] : Improve Market for Backend

.changeset/tidy-lobsters-taste.md, apps/ledger-live-mobile/.unimportedrc.json, apps/ledger-live-mobile/src/MobileStorageProvider.ts
- Add mobile storage provider for app data backup
- Add mobile storage provider for app data backup, using `@react-native-async-storage/async-storage`.
- **JIRA or GitHub link**: [LIVE-13127]
---
[LIVE-13127]: …
=> [LIVE-13127][LLM][Passkey] Create use case for saving app data inside local storage

.changeset/lazy-moons-love.md, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- Nothing
Add feature flag to code base for Ordinals. And fix missing export for newArchNftGallery feature flag
- **JIRA or GitHub link**: [LIVE-12466](https://ledgerhq.atlassian.net/browse/LIVE-12466)
--- …
=> :triangular_flag_on_post:feat(lld): add ordinals feature flag

apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useWatchWalletSync.ts, apps/web-tools/trustchain/components/App.tsx, apps/web-tools/trustchain/components/AppAccountsSync.tsx, apps/web-tools/trustchain/components/Tick.tsx, apps/web-tools/trustchain/components/types.ts, libs/live-wallet/src/ordering.test.ts, libs/live-wallet/src/store.test.ts, libs/live-wallet/src/store.ts, libs/live-wallet/src/walletsync/__mocks__/modules/accounts.ts, libs/live-wallet/src/walletsync/__tests__/compatibility.test.ts, libs/live-wallet/src/walletsync/__tests__/generic.test.ts, libs/live-wallet/src/walletsync/__tests__/modules/accountNames.test.ts, libs/live-wallet/src/walletsync/__tests__/modules/accounts.test.ts, libs/live-wallet/src/walletsync/__tests__/specific.test.ts, libs/live-wallet/src/walletsync/aggregator.ts, libs/live-wallet/src/walletsync/createWalletSyncWatchLoop.ts, libs/live-wallet/src/walletsync/incrementalUpdates.ts, libs/live-wallet/src/walletsync/index.ts, libs/live-wallet/src/walletsync/modules/accountNames.ts, libs/live-wallet/src/walletsync/modules/accounts.ts, libs/live-wallet/src/walletsync/types.ts
- wallet sync management of account sync failures
This improve the Wallet Sync reconciliation in order to **keep a memory of non imported account ids to be able to eventually restore them.**
this can be tested by limiting the number of supported currencies on the web tools: (but you can also import tezos/cosmos which currently also fails on the web)
**The previous behaviour:**
non imported accounts management must be done on accounts that could possibly fail the synchronisation (during the resolve). At the moment they become completely ignored and will never appear again on other members. (fail sync = the user had network issues / the backend had issues / the Ledger Live instance don't yet support the coin). worse: in current implementation, account disappear when another member don’t …
=> chore(walletsync): introduce nonImportedAccountInfos management

.changeset/tricky-boats-tie.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/MyLedgerDevice/Device/CustomLockScreen.tsx
- Update wording for changing custom lock screen
- Update wording for changing custom lock screen.
- **JIRA or GitHub link**: [LIVE-12092]
---
[LIVE-12092]: …
=> [LIVE-12092][LLM] Inconsistency in change lock screen wording

libs/live-wallet/src/store.test.ts, libs/live-wallet/src/store.ts
- LLD
following #7376 PR, there is a small regression on Live instances that had the `wallet` store created, they will miss the field `nonImportedAccountInfos`, so in the importer, we need to be sure to accept partial object and complete with the initial value if the fields are not yet set.
---
- …
=> chore(live-wallet): allow store to be partial

.changeset/itchy-tigers-divide.md, apps/ledger-live-mobile/src/contentCards/cards/vertical/elements.tsx, apps/ledger-live-mobile/src/contentCards/cards/vertical/index.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/GenericLandingPage/index.tsx
- ...
Adapted the Large Square Content Card to add : 
- A title and description of multiple lines
- Support of `\n` to handle line breaks
- Support a card with only an image (without a title and a description)
- Fixed the `numberOfLines` style property that wasn't named correctly in the other cards
https://github.com/user-attachments/assets/53a05b4c-b778-454d-9768-ea98c94cf7f2
- **JIRA or GitHub link**: [LIVE-13413]
--- …
=> LLM - Small flexible cards ui modifications to match the Security Key use case

.changeset/flat-bananas-appear.md, apps/ledger-live-mobile/ios/Podfile.lock, apps/ledger-live-mobile/package.json, apps/ledger-live-mobile/src/components/StorylyStories/StorylyProvider.tsx, apps/ledger-live-mobile/src/components/StorylyStories/index.tsx, pnpm-lock.yaml
- ...
Updated Storyly from 2.0.1 to 2.18.1 to fix the black screen issue after seeing a story and putting the app in background on Android
| https://github.com/user-attachments/assets/5a656149-7fac-45ff-913e-eeb8e6b60822 | https://github.com/user-attachments/assets/aa95aa74-bcde-41be-b692-8a89983db18e|
- **JIRA or GitHub link**: [LIVE-13103] 
--- …
=> LLM - Update Storyly

.changeset/four-olives-hammer.md, apps/ledger-live-desktop/src/renderer/modals/Receive/steps/StepReceiveFunds.tsx
- Receive flow account name
Fix an issue that displayed the default account name on receive flow instead of the user one
|https://github.com/user-attachments/assets/589905d8-0e70-4bbf-826f-d776f21df8c8|https://github.com/user-attachments/assets/5e27ad75-adeb-48be-8239-5375bd666b44|
- **JIRA or GitHub link**: [LIVE-13496](https://ledgerhq.atlassian.net/browse/LIVE-13496)
--- …
=> :bug:fix(lld): account name on receive flow

libs/hw-trustchain/package.json, libs/hw-trustchain/src/NobleCrypto.ts, libs/hw-trustchain/src/__tests__/codec.ts, pnpm-lock.yaml
- ...
Remove noble/secp256k1 and use secp256k1 library (which is already used by over LL packages).
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-13493
---
=> chore: Remove noble/secp256k1 and migrate to "secp256k1" library

.changeset/hip-shirts-rule.md, apps/ledger-live-mobile/e2e/page/index.ts, apps/ledger-live-mobile/e2e/page/liveApps/dummyWalletApp.webView.ts, apps/ledger-live-mobile/e2e/page/liveApps/walletAPIReceive.ts, apps/ledger-live-mobile/e2e/specs/wallet-api.spec.ts, apps/ledger-live-mobile/src/screens/VerifyAccount/index.tsx
- Wallet-API: account.receive flow used in buy/sell live apps usually
The old device selection UI was removed recently in the PR: https://github.com/LedgerHQ/ledger-live/pull/6383
But we removed the button to skip the device check too
This PR brings back the button under the new device selection UI for the wallet-api account.receive handler
| <img width="436" alt="Screenshot 2024-07-30 at 15 34 35" src="https://github.com/user-attachments/assets/22b2f092-d966-4e0b-8c6a-c23b9dc2a7b7"> | <img width="429" alt="Screenshot 2024-07-30 at 11 59 34" src="https://github.com/user-attachments/assets/6fa3a7f1-93e4-41fc-b48c-361bd29eb12b"> |
- **JIRA or GitHub link**: [LIVE-13538]
---
- **The code aligns with the requirements** …
=> fix(LLM): skip device check in account.receive for wallet-api [LIVE-13538]

tools/actions/composites/setup-caches/action.yml
- ...
Added parameter to upgrade proto. By default we don't upgrade it.
---
=> fix: remove proto upgrade to use pinned version instead

.changeset/spicy-pumpkins-lick.md, apps/ledger-live-mobile/src/screens/MyLedgerDevice/AppsList/Searchbar.tsx, apps/ledger-live-mobile/src/screens/MyLedgerDevice/AppsScreen.tsx
- cf. description
The apps search bar in My Ledger is now automatically sticking to the top of the screen.
There is also an auto scroll to that search bar whenever the input field gets focus or when the input changes.
> iOS
> 
> https://github.com/user-attachments/assets/a6b3307c-c4c3-420d-966a-b6ab52738315
> Android
> 
> https://github.com/user-attachments/assets/ed9465e0-60e0-4a4c-b686-51913611388a
- **JIRA or GitHub link**: [LIVE-11916]
--- …
=> [LIVE-11916][LLM] My Ledger search bar sticky & auto scroll

.changeset/weak-melons-grow.md, apps/ledger-live-mobile/src/AppProviders.tsx, apps/ledger-live-mobile/src/actions/accounts.ts, apps/ledger-live-mobile/src/actions/types.ts, apps/ledger-live-mobile/src/components/globalSyncRefreshControl.tsx, apps/ledger-live-mobile/src/context/LedgerStore.tsx, apps/ledger-live-mobile/src/db.ts, apps/ledger-live-mobile/src/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/WalletSyncContext/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useDestroyTrustchain.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useOnTrustchainRefreshNeeded.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useWatchWalletSync.ts, apps/ledger-live-mobile/src/reducers/accounts.ts, apps/ledger-live-mobile/src/reducers/wallet.ts
- ...
Added the watch loop to synchronise LLM accounts using wallet sync
See a demo [here](https://ledger.slack.com/archives/C076F0JQZ5E/p1722355896408899)
Also fixed a bug on desktop by reseting the error and pending state of wallet sync when the trustchain has been deleted
- **JIRA or GitHub link**: [LIVE-12640] [LIVE-13542]
---
- …
=> LLM - Wallet Sync accounts synchronisation added

apps/web-tools/trustchain/components/AppAccountsSync.tsx, libs/live-wallet/src/walletsync/createWalletSyncWatchLoop.ts
- watch loop
- reduce the loop to 10s
- small evolution on the `watchConfig` object,
as documented by https://ledgerhq.atlassian.net/wiki/spaces/WXP/pages/4902912002/future+improvement+consideration
we simply can consider that websocket notifications is a small enhancement **on top** of the regular polling mecanism.
We can test on the web tools, the websocket mode is disabled by default
--- …
=> chore(walletsync): enhance the websocket notifications hook for watch loop

.changeset/spotty-chefs-tan.md, libs/live-wallet/src/cloudsync/__tests__/sdk.test.ts, libs/live-wallet/src/cloudsync/api.ts
Fix a wallet sync parser issue happening when the info field was null
- **JIRA or GitHub link**: [LIVE-13539]
---
[LIVE-13539]: https://ledgerhq.atlassian.net/browse/LIVE-13539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …
=> Live-Wallet - Fix a wallet sync parser issue

.changeset/tidy-berries-perform.md, libs/ledger-live-common/src/exchange/swap/hooks/useSwapTransaction.ts
- ...
Might be a Legacy error. The function that is preparing the transaction and calculate the possible the max value is returning MAX number between (balance - fees, 0). So the a very low balance - fees is < 0, then 0 is returned. 
I added an error for this case. isMaxEnabled and fromAmount is 0
- show error when balance - network fees < 0
https://ledgerhq.atlassian.net/browse/LIVE-13597
--- …
=> fix(live-13597): show error when balance minus network fees is a negative value

.changeset/friendly-mugs-kiss.md, .changeset/new-insects-cry.md, .changeset/serious-rats-report.md, apps/ledger-live-desktop/src/renderer/actions/settings.ts, apps/ledger-live-desktop/src/renderer/screens/manager/DeviceDashboard/AppsList/index.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/AllowDebugAppsToggle.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/MockAppUpdate.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/experimental.ts, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/MyLedgerDevice/AppsScreen.tsx, libs/env/src/env.ts, libs/ledger-live-common/src/apps/logic.ts
- live-env: new MOCK_APP_UPDATE env
- live-common: apps/logic modified to take into account MOCK_APP_UPDATE
- lld / llm: use common + env to fake app updates in the manager
Add a new developer setting in both LLD and LLM to fake app upate in MyLedger / Manager.
It will reinstall the current installed app
Will be useful for testing (in anticipation of the app data backup / restore integration)
To test it:
- on lld or llm enable developer mode
- toggle Mock App Update
- go back to My Ledger
- all the apps installed on your device should have an update
- **JIRA or GitHub link**: [LIVE-13573] 
--- …
=> :sparkles: (app-updates): add settings to mock app update

.changeset/red-beans-report.md, CODEOWNERS, apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/Disclaimer.tsx, apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/helpers/createFirmwareUpdateSteps.ts, apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/index.tsx, apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/steps/02-step-flash-mcu.tsx, apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/steps/02-step-updating.tsx, apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/types.ts
also fix unnecessary optional type
- Firmware update on LLD
For devices / old firmwares not supporting device localisation (language packs), the update process on LLD was breaking as it was trying to go to the restore step which does not exist.
This bug affects Nano S of course but also all Nano X and SP firmwares old enough that they don't have an upgrade path straight to a firmware version supporting the device localisation.
I have patched this issue for the "restore" step but a deeper rework of the firmware update process on LLD would be wise later on as the way of doing things might lead to another similar bug in the future. Right now, due to the current stack and lack of ways for mocking firmware updates, doing a rework of the flow brings too much risk so it's not done in this PR.
- …
=> [LIVE-11555][LLD][Firmware update] Update stuck at the end for old firmwares.

.changeset/empty-mayflies-pump.md, apps/ledger-live-mobile/src/components/RequiresCameraPermissions/Fallback.tsx, apps/ledger-live-mobile/src/components/RequiresCameraPermissions/index.tsx, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/components/StepFlow.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/useAddAccountViewModel.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/scanQRCode.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/synchronizeWithQrCode.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Activation/ActivationFlow.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Synchronize/BottomContainer.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Synchronize/QrCode.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Synchronize/ScanQrCode.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Synchronize/ScanTargetSvg.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Activation/ActivationDrawer.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Activation/useActivationDrawerModel.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Synchronize/QrCodeMethod.tsx
- WS flow
Add the scan of LLD WS Qr code.
Change numbered list to fit with designs
https://github.com/user-attachments/assets/fb9b2378-bd6b-40b7-89db-edfdfea2e995
- **JIRA or GitHub link**: [LIVE-12168](https://ledgerhq.atlassian.net/browse/LIVE-12168)
--- …
=> :sparkles:feat(llm): add scan WS qr code

.changeset/real-apricots-rush.md, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/components/StepFlow.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/useAddAccountViewModel.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Activation/ActivationFlow.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useInstanceName.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useSyncWithQrCode.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useTrustchainSdk.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Activation/ActivationDrawer.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Activation/useActivationDrawerModel.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Synchronize/PinCodeInput.tsx
- LLM WS flow 
Add the trustchain integration to the qr code scanned for WS
This allow us to import accounts using WS scanning LLD qr code with LLM
After a scan => pin code : 
- if wrong => error screen on LLD and LLM
- if good => activation screen on LLD and LLM
- **JIRA or GitHub link**: [LIVE-12168](https://ledgerhq.atlassian.net/browse/LIVE-12168)
--- …
=> :sparkles:feat(llm): trustchain integration to qr code scan

apps/ledger-live-desktop/src/main/setup.ts
- LLD, click on a URI scheme from inside a iframe.
- Some `Render frame was disposed before WebFrameMain could be accessed` error occurs on a second `will-frame-navigate` Event from an iframe done in our Electron app.
- This makes LLD's showing a GUI popup with the error shown to the user which is due to Electron's default implementation of handling `uncaughtException` in here: https://github.com/electron/electron/blob/ba8ad4716b58bb84bca85282f4ccbbd19af828a5/lib/browser/init.ts#L21-L37
- As we don't need this `will-frame-navigate` event at all, we can afford to just ignore the error, and instead of having Electron's default impl, we will provide our own uncaughtException handler **in production mode** to be outputting errors to **console.error** instead of an annoying popup on user's …
=> chore(lld): handle uncaughtException to console instead of Electron GUI

libs/live-wallet/src/cloudsync/sdk.ts, libs/live-wallet/src/walletsync/createWalletSyncWatchLoop.ts, libs/live-wallet/src/walletsync/modules/README.md
- no impact
replace TODOs by Jira tickets.
- `LIVE 13633`
- `LIVE 13634` + no more console.warn in CloudSyncSDK#push out-of-sync case
- useless todo in the template of walletsync module
--- …
=> chore(walletsync): clean up TODOs comments

.changeset/pretty-cooks-grin.md, apps/ledger-live-desktop/src/main/setup.ts
same PR as https://github.com/LedgerHQ/ledger-live/pull/7546 targetting `release`
- LLD, click on a URI scheme from inside a iframe.
- Some `Render frame was disposed before WebFrameMain could be accessed` error occurs on a second `will-frame-navigate` Event from an iframe done in our Electron app.
- This makes LLD's showing a GUI popup with the error shown to the user which is due to Electron's default implementation of handling `uncaughtException` in here: https://github.com/electron/electron/blob/ba8ad4716b58bb84bca85282f4ccbbd19af828a5/lib/browser/init.ts#L21-L37
- As we don't need this `will-frame-navigate` event at all, we can afford to just ignore the error, and instead of having Electron's default impl, we will provide our own uncaughtException handler **in production mode** to be …
=> Fix LIVE-12926

libs/trustchain/src/qrcode/index.ts
- logs
we don't need to `console.error` when the error is returned in a Promise reject, the other side could possibly log it, but it's also a normal user flow (if you input the wrong digits) so we shouldn't console.error it. especially that on React Native, it would display as an error screen in dev mode.
--- …
=> chore(trustchain): remove console.error that are annoying for LLM development

.changeset/metal-dolls-whisper.md, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/components/StepFlow.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Activation/ActivationFlow.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/ManageInstances/ListInstances.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useSyncWithQrCode.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Synchronize/PinCodeInput.tsx
- ...
Set nbDigits dynamic for PinCodeInput
---
=> [FEAT]: Set nbDigits dynamic for PinCodeInput

.changeset/khaki-melons-exist.md, apps/ledger-live-desktop/src/renderer/screens/manager/DeviceDashboard/AppsList/AppActions.tsx, apps/ledger-live-desktop/src/renderer/screens/manager/DeviceDashboard/AppsList/Item.tsx, apps/ledger-live-desktop/src/renderer/screens/manager/DeviceDashboard/AppsList/index.tsx, apps/ledger-live-mobile/src/screens/MyLedgerDevice/AppsScreen.tsx, libs/ledger-live-common/src/apps/filtering.test.ts, libs/ledger-live-common/src/apps/filtering.ts, libs/ledger-live-common/src/apps/react.ts
- My Ledger app catalog
Fix & refactor the  logic of "is app supported by Ledger Live" depending on feature flags, as well as associated filters in apps catalog.
Now this logic is in one single place and fully unit tested.
The main issue addressed is that for apps that associated to a currency with a feature flag, those apps were totally gone from the catalog if the feature flag was disabled, which shouldn't be the case. The correct behaviour is to filter out those apps only when the filter "Supported in Live" is selected.
- **JIRA or GitHub link**: [LIVE-13575]
--- …
=> [LIVE-13575][LLD, LLM][MyLedger]: Filtering of apps depending on feature flag

.changeset/hip-spies-develop.md, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/manageInstances.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/ManageInstances/ManageInstancesDrawer.tsx
- ...
Added redirection to the manage key screen
- **JIRA or GitHub link**: [LIVE-13636]
---
[LIVE-13636]: https://ledgerhq.atlassian.net/browse/LIVE-13636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …
=> LLM - Wallet Sync Manage Key redirection added 

.changeset/orange-humans-remember.md, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Synchronize/PinCodeInput.tsx
- ...
Force neutral.c100 Color on PinCodeInput
---
=> [FIX]:  Color on PinCodeInput

.changeset/tiny-socks-jam.md, apps/ledger-live-mobile/src/components/MarketQuickActions/index.tsx, apps/ledger-live-mobile/src/newArch/features/Market/screens/MarketDetail/index.tsx, apps/ledger-live-mobile/src/types/helpers.ts, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- ...
Add a first draft of the MarketQuickActions hidden behind the new `llmMarketQuickActions` feature flag.
- [LIVE-10739]
---
[LIVE-10739]: https://ledgerhq.atlassian.net/browse/LIVE-10739?atlOrigin=eyJpIjoiNWRkNTl …
=>  🚦 [FEAT] Create the `llmMarketQuickActions` feature flag

.changeset/breezy-cups-flow.md, libs/trustchain/src/sdk.ts
If current member is not in the result of the get members, we throw a TrustchainEjected error. It is catched by LLM and LLD to redirect the user to the synchronize screen
- **JIRA or GitHub link**: [LIVE-13409]
--- …
=> fix(trustchain): removed member ejected on get members

.changeset/grumpy-deers-develop.md, CODEOWNERS, apps/ledger-live-desktop/src/renderer/screens/customImage/Step1ChooseImage.tsx, apps/ledger-live-desktop/src/renderer/screens/customImage/index.tsx, apps/ledger-live-desktop/src/renderer/screens/manager/DeviceDashboard/DeviceInformationSummary/CustomImageManagerButton.tsx, apps/ledger-live-desktop/src/renderer/screens/manager/DeviceDashboard/DeviceInformationSummary/index.tsx, apps/ledger-live-desktop/src/renderer/screens/manager/DeviceDashboard/index.tsx
- My Ledger
If the instance of LLD was not previously used to set a lock screen, and a device with a lock screen is connected to LLD, then LLD would not know that this device currently has a lock screen, therefore not displaying the correct CTAs ("Add" instead of "Change", and in the custom lock screen drawer, the button "Remove lock screen picture" was missing).
Using the correct value to determine whether a custom lock screen is setup on the connected device solves this issue.
- **JIRA or GitHub link**: [LIVE-12412]
--- …
=> [LIVE-12412] fix(lld/MyLedger): custom lock screen not recognized

.changeset/afraid-weeks-divide.md, libs/ledger-live-common/src/exchange/swap/hooks/useSwapTransaction.ts
- ...
- display the NotEnoughBalanceSwap error with a delay after the maxValue is loaded 
https://github.com/user-attachments/assets/b1b3e39f-35e0-4e8d-a0a6-e80d0c7c2afe
https://ledgerhq.atlassian.net/browse/LIVE-13704
--- …
=> fix: error is displayed before maxValue is loaded 

.changeset/early-plums-train.md, libs/ui/packages/native/src/components/Form/TabSelector/index.tsx
- RN UI lib
Make the tab selector component more responsive based on the size of the largest option. 
On storybook
https://github.com/user-attachments/assets/8582fd04-1575-4357-be17-3664c6026bc4
On LLM WS Drawer
https://github.com/user-attachments/assets/7bd8808b-68d7-44b2-8cfb-c6793108da2d
- **JIRA or GitHub link**:  No Ticket
---
- …
=> :lipstick:feat(llm/ui): tab selector width

.changeset/chilled-bikes-agree.md, apps/ledger-live-mobile/src/newArch/features/Web3Hub/screens/Web3HubSearch/index.tsx
- Web3Hub still behind a disabled FF
Hidden header should show again when searching
On the search page the header can be hidden while keeping the focus on the search bar, if you add or remove a character while the header is hidden it won’t show again when the list reset to the top
| <video src="https://github.com/user-attachments/assets/72fc96ad-f001-4449-ad45-95563dd9360d">  | <video src="https://github.com/user-attachments/assets/9eb693c5-22f5-4c3f-8f93-cb811d0637aa"> |
- **JIRA or GitHub link**: [LIVE-13727]
---
- …
=> fix: hidden header should show again when searching [LIVE-13727]

.changeset/hip-mangos-behave.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/__tests__/useFlows.test.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useFlows.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Activation/index.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/ManageBackup/03-FinalStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/ManageBackup/index.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/ManageInstances/04-DeletionFinalStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/ManageInstances/index.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Synchronize/04-SyncFinalStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Synchronize/index.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/router.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/WalletSync.tsx
- ...
Add CTAs on missing screens for LedgerSync
- **JIRA or GitHub link**: [LIVE-13578] 
---
[LIVE-13578]: https://ledgerhq.atlassian.net/browse/LIVE-13578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
=> 💄 [BUGFIX]: Add CTAs on missing screens for LedgerSync

.changeset/tricky-forks-fly.md, apps/ledger-live-mobile/src/components/WebPlatformPlayer/BottomBar.tsx, apps/ledger-live-mobile/src/components/WebPlatformPlayer/SelectAccountButton.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/screens/Web3HubApp/components/Web3Player/BottomBar.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/screens/Web3HubApp/components/Web3Player/SelectAccountButton.tsx
- Web3Hub live-app opening (still behind a disabled FF)
- Discover and other live-apps (should open faster now)
This fix (https://github.com/LedgerHQ/ledger-live/pull/7230) introduced a performance regression in some cases (e.g. when a lot of tokens are defined in the currencies field of the manifest) as we now get the currency list again and again.
This PR only removes the listing of currencies that we were doing on all apps even if it was not using the dapp browser v3, this helps most apps for the moment but we still need to improve the performance of the currency listing.
In a next PR we'll try to remove the spreading done on tokens, only do the minimal work necessary to get the informations and try to improve caching on this by instead listening to changes to only pull currencies when …
=> fix: freeze when opening a live-app [LIVE-13411]

.changeset/eighty-candles-boil.md, apps/ledger-live-mobile/android/app/build.gradle, apps/ledger-live-mobile/ios/ledgerlivemobile/Info.plist, apps/ledger-live-mobile/src/newArch/features/Web3Hub/components/ManifestsList/useManifestsListViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Web3Hub/screens/Web3HubApp/useWeb3HubAppViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Web3Hub/screens/Web3HubMain/components/Header/index.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/screens/Web3HubSearch/components/SearchList/useSearchListViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Web3Hub/utils/api/manifests.ts
- Web3hub but still behind a disabled FF
Add missing query params for web3hub manifests requests
Also matches the current prod version for Android and iOS build in dev to get the proper manifest back from the API
- **JIRA or GitHub link**: [LIVE-13726]
--- …
=> fix: missing query params for web3hub manifests requests [LIVE-13726]

.changeset/heavy-eggs-protect.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/walletSync.hooks.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/walletSync.hooks.ts, libs/trustchain/src/mockSdk.ts, libs/trustchain/src/sdk.ts, libs/trustchain/src/types.ts
Fixed the getOrCreateTrustchain when another instance deleted the trustchain
It was due to Ledger Live using the previous token to create a new trustchain
- **JIRA or GitHub link**: [LIVE-13540]
---
[LIVE-13540]: …
=> Ledger Sync - Fixed the getOrCreateTrustchain when another instance deleted the trustchain

.changeset/tame-rocks-lay.md, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Manage/index.tsx
- ...
Fix starting step when WS is activated and you want to sync again
- **JIRA or GitHub link**: [LIVE-13693] 
---
[LIVE-13693]: https://ledgerhq.atlassian.net/browse/LIVE-13693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …
=> [FIX]: Fix starting step when WS is activated and you want to sync again

.changeset/fresh-sloths-boil.md, apps/ledger-live-mobile/src/actions/settings.ts, apps/ledger-live-mobile/src/actions/types.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Activation/ActivationSuccess.tsx, apps/ledger-live-mobile/src/reducers/settings.ts, apps/ledger-live-mobile/src/reducers/types.ts, apps/ledger-live-mobile/src/screens/Onboarding/steps/accessExistingWallet.tsx
- ...
`fromLedgerSyncOnboarding` added in Store to differentiate where we come from to close correctly and redirect to the right screen
https://github.com/user-attachments/assets/1c6cd0fe-5277-4cf5-a3b8-049338baaa86
- [LIVE-13772] 
- [LIVE-13773]
--- …
=> [BUGFIX]: Add fromLedgerSyncOnboarding to trigger right onClose action for Activation

.changeset/selfish-poets-arrive.md, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useAddMember.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useFollowInstructionDrawer.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useRemoveMember.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Activation/ActivationInstructionDrawer.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/FollowInstructions/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/ManageInstances/DeletionInstructionDrawer.tsx
- ...
The "Delete my encryption key" on the wrong seed error was not doing anything on the add member flow and just lead to the main wallet sync page on the remove member flow.
It now shows the delete key confirmation drawer:
https://github.com/user-attachments/assets/f9dad0a7-70f4-48bd-8072-1cd1dc6ba3de
- [LIVE-13779]
---
- …
=> 🗝️ [FIX]: llm "Delete my encryption key" action on wrong seed errors

.changeset/real-pets-travel.md, apps/ledger-live-desktop/src/renderer/screens/exchange/index.tsx, apps/ledger-live-desktop/tests/specs/market/market.spec.ts, apps/ledger-live-desktop/tests/specs/services/buy.spec.ts, apps/ledger-live-mobile/src/components/RootNavigator/ExchangeLiveAppNavigator.tsx, apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
Removes old manifest id for buy sell `multibuy-v2`. The manifest ID we currently use is `buy-sell-ui`
- [LIVE-13748](https://ledgerhq.atlassian.net/browse/LIVE-13748)
---
[LIVE-13748]: …
=> refactor: remove old manifest id for buy-sell "multibuy-v2"

apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/WebviewErrorDrawer/index.tsx
=> fix: use correct i18nkey for swap error code

.changeset/cuddly-peas-look.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useLedgerSyncInfo.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Manage/index.tsx, apps/ledger-live-desktop/src/renderer/modals/SimpleHashTools/index.tsx, apps/ledger-live-desktop/src/renderer/modals/WalletSyncDebugger/index.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/SimpleHashTools/SimpleHashTools.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/WalletSync/Checker/index.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/WalletSync/Generator/index.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/WalletSync/WalletSyncTester.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- ...
- Revamp LedgerSync Debugger
- Introduce v0 of LedgerSyncInfo checker
https://github.com/user-attachments/assets/17e90cdd-81f7-4577-97fe-4d25b67a433a
- **JIRA or GitHub link**: [LIVE-13450] 
---
[LIVE-13450]: …
=> ⚗️  [SUPPORT] : Revamp LedgerSyncDebugger

.changeset/wicked-eyes-explain.md, libs/coin-modules/coin-evm/src/__tests__/unit/api/node/ledger.unit.test.ts, libs/coin-modules/coin-evm/src/api/node/ledger.ts
- ...
When not providing gasOption, prepare Transactions makes a node api call to fetch medium fees regardless of what is asked on feeStrategy. This PR aims to fix this by returning the option asked on the transaction before defaulting to medium
[- **JIRA or GitHub link**: ](https://ledgerhq.atlassian.net/browse/LIVE-13775)
---
- …
=> fix: return transaction.feesStrategy gasOption instead of the medium value

.changeset/twenty-bottles-leave.md, apps/ledger-live-desktop/src/renderer/screens/customImage/Step1ChooseImage.tsx, apps/ledger-live-desktop/src/renderer/screens/customImage/index.tsx, apps/ledger-live-desktop/src/renderer/screens/manager/DeviceDashboard/DeviceInformationSummary/CustomImageManagerButton.tsx, apps/ledger-live-desktop/src/renderer/screens/manager/DeviceDashboard/DeviceInformationSummary/RemoveCustomImage.tsx, apps/ledger-live-desktop/src/renderer/screens/manager/DeviceDashboard/DeviceInformationSummary/index.tsx, apps/ledger-live-desktop/src/renderer/screens/manager/DeviceDashboard/index.tsx, libs/ledger-live-common/src/hw/customLockScreenRemove.test.ts, libs/ledger-live-common/src/hw/customLockScreenRemove.ts
- Removal of custom lock screen on LLM & LLD
There were 2 issues:
In LLD, the device action for CLS removal was mounted in a new drawer.
It seems like in LLD when opening a new drawer, the component inside is remounted almost immediately. This might be a deeper issue that I don't want to fix just for this bug.
For a device action that starts immediately on mount, it's bad because it means the command will be sent twice in a row to the device, without waiting for completion.
The fix for that is simply to reuse the drawer that we are already in.
We were doing some weird stuff to ensure that errors were caught (the `.subscribe(subscriber)` part).
TypeScript was detecting that something was wrong, but we were doing a wrong type assertion.
It was causing an issue where the observable would …
=> [LIVE-10655][LLD] Fix removal of custom lock screen

.changeset/thick-fans-give.md, libs/ledger-live-common/src/apps/listApps.test.ts, libs/ledger-live-common/src/apps/listApps.ts, libs/ledger-live-common/src/hw/connectManager.ts
- LLM+LLD: Access to My Ledger
On old firmwares, the `listApps` APDU is not supported (for instance on Nano X 1.2.4).
Prior to #7453, we were not using that APDU, but always using the HSM to request the list of apps to the device. Sending the `listApps` APDU directly is an optimisation, as it avoids network calls, and it's doable in case the user has already allowed a secure connection on their device. But it fails for old firmwares.
So the solution chosen here, to not have a logic that depends on versions, is to first try to send the APDU, and if it fails, we proceed with the HSM method.
https://github.com/user-attachments/assets/d4925a32-5acd-4c97-904d-0fba0022ac5f
https://github.com/user-attachments/assets/ffaa7afc-72b2-4341-93c7-0cb30b501180
- **JIRA or GitHub link**: [LIVE-13826] …
=> [LIVE-13826] Fix access to My Ledger when listApps APDU not supported

.changeset/tall-mayflies-study.md, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/locales/en/common.json, libs/device-core/src/commands/use-cases/app-backup/restoreAppStorageInit.ts, libs/device-core/src/errors.ts, libs/ledger-live-common/.unimportedrc.json, libs/ledger-live-common/src/device/use-cases/appDataBackup/deleteAppData.test.ts, libs/ledger-live-common/src/device/use-cases/appDataBackup/deleteAppData.ts, libs/ledger-live-common/src/device/use-cases/appDataBackup/deleteAppDataUseCase.test.ts, libs/ledger-live-common/src/device/use-cases/appDataBackup/deleteAppDataUseCase.ts, libs/ledger-live-common/src/device/use-cases/appDataBackup/deleteAppDataUseCaseDI.ts, libs/ledger-live-common/src/device/use-cases/appDataBackup/restoreAppData.ts, libs/ledger-live-common/src/device/use-cases/appDataBackup/types.ts
- add new delete app data use case in live-common/device
Added a new usecase for the deletion of local app data stored on the device storage (llm/lld)
- **JIRA or GitHub link**: [LIVE-13852] 
---
[LIVE-13852]: …
=> :sparkles: (device) [LIVE-13852]: implement delete app data use case

.changeset/popular-chairs-melt.md, apps/ledger-live-desktop/src/renderer/families/bitcoin/SendAmountFields.tsx, apps/ledger-live-desktop/src/renderer/families/evm/SendAmountFields/index.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FeesDrawerLiveApp/index.tsx
- ...
Send workflow change 
https://github.com/user-attachments/assets/6092cb77-560a-42e3-a96c-f7ce1b3c1f46
For swaps we need to display all errors using the same UI inside the fee drawer. This PR makes it so that amountError are displayed inside the drawer 
https://github.com/user-attachments/assets/929bbdf8-d38a-4fb8-8862-1bd80e31eaf8
[**LIVE-13853**: ](https://ledgerhq.atlassian.net/browse/LIVE-13853)
--- …
=> feat: btc and evm fee drawer display amount errors when editing fees

.changeset/sweet-spies-sell.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useQRCode.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useQRCodeHost.ts, libs/ledgerjs/packages/errors/src/helpers.ts, libs/trustchain/src/errors.ts, libs/trustchain/src/qrcode/index.ts
- ...
It retries the QR code processing flow when the WS closes unexpectedly. Since AFAIK there is no way to make sure the WS closed because of the QR code expiration: if the connection closes in less than 30 seconds the flow is not retried and the old error is shown. Here's a demo the behaviour with a min time 3 seconds:
https://github.com/user-attachments/assets/14c923dd-8da3-4e9c-a1f9-e3733958dbbe
I ended up using react query because I was getting some weird behaviour with the old logic. However I didn't manage to use the build in `retry` option because the `delay` option didn't work for me it kept on retrying after +30 seconds instead of immediatley 🤷.
- [LIVE-13766]
---
- **The PR description …
=> 🐦‍🔥 [FIX]: Refresh ledger sync QR code on expiration

.changeset/shaggy-crabs-approve.md, libs/hw-trustchain/src/NobleCrypto.ts, libs/hw-trustchain/src/__tests__/crypto.ts
- ...
Fix the "Expected signature to be an Uint8Array with length 64" error. It was due to some part of the signature being shorter than the expected 32 + 32 bytes. I think it's because leading zeros are getting truncated in segments of the Apdu devices responses.
- [LIVE-13829]
--- …
=> 🔏 [FIX]: Trustchain "Expected signature to be an Uint8Array with length 64" error

.changeset/gentle-lions-appear.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useGetMembers.ts, apps/ledger-live-desktop/src/renderer/actions/accounts.ts, apps/ledger-live-mobile/src/actions/accounts.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useGetMembers.ts, libs/live-wallet/src/store.test.ts, libs/live-wallet/src/store.ts
Improve account names module to avoid erasing a custom name with a default one when two instances are pushing at the same time
- **JIRA or GitHub link**: [LIVE-13670] [LIVE-13452]
---
[LIVE-13670]: …
=> feat(llm/lld): ledger sync - improve account names module

apps/ledger-live-desktop/src/renderer/screens/exchange/index.tsx, apps/ledger-live-mobile/src/screens/PTX/BuyAndSell/index.tsx, libs/ledger-live-common/src/platform/types.ts
This PR accepts another a new variable only from a local manifest called `providerTestBaseUrl` which would be passed to the `buy-sell-ui` that will use it for changing the widgetUrl for allowing us and partners to test in staging or dev environments. 
- ...
---
- **The code aligns with the requirements** described in the linked JIRA …
=> CN-197: add param partnerTestBaseUrl to be passed to buy-sell app

.changeset/empty-pumas-argue.md, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/locales/en/common.json
- ...
Remove Trustchain from error and handle it in generic way
- [LIVE-13564]
- [LIVE-13563]
---
[LIVE-13564]: https://ledgerhq.atlassian.net/browse/LIVE-13564?atlOrigin=eyJpIjoiNWRkNTljNzY …
=> [FIX]: Remove Trustchain from error and handle it in generic way

.changeset/polite-masks-warn.md, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useFollowInstructionDrawer.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useRemoveMember.ts
- ...
Don't run extra device action at the end of the remove member flow on LLM.
---
=> 🩹 [FIX]: Extra device action at the end of the remove member flow on LLM

.changeset/wet-kids-call.md, apps/ledger-live-desktop/src/renderer/families/bitcoin/SendAmountFields.tsx, libs/coin-modules/coin-bitcoin/src/prepareTransaction.ts
- ...
fix: issue with BTC fee drawer when close/open to keep custom opened. and to keep networkInfo
[- **JIRA or GitHub link**: ](https://ledgerhq.atlassian.net/browse/LIVE-13910)
---
=> fix: issue with BTC fee drawer when close/open and using custom

.changeset/gorgeous-ways-exercise.md, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useFollowInstructionDrawer.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/FollowInstructions/index.tsx
- ...
Fix navigation on Drawer when AlreadySecuredOtherSeed error
- **JIRA or GitHub link**: [LIVE-13934] 
---
[LIVE-13934]: https://ledgerhq.atlassian.net/browse/LIVE-13934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …
=> [FIX]: Fix navigation on Drawer when AlreadySecuredOtherSeed error

.changeset/tough-ads-dance.md, apps/ledger-live-mobile/src/newArch/features/WalletSync/WalletSyncNavigator.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useClose.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useDestroyTrustchain.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Activation/ActivationSuccess.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/DeviceSelection/index.tsx
Navigation fixes on sync success screen
Safeareaview added to the device step of the ledger sync flow
---
=> fix(llm): ledger sync navigation fixes

.changeset/witty-feet-dream.md, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/components/SelectAddAccountMethod/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/components/SelectAddAccountMethod/useSelectAddAccountMethodViewModel.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/WalletSyncNavigator.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Activation/Actions.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useLedgerSyncAnalytics.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useSpecificError.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Activation/ActivationDrawer.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Manage/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Synchronize/QrCodeMethod.tsx, apps/ledger-live-mobile/src/screens/Onboarding/steps/accessExistingWallet.tsx
- ...
Analytics LedgerSync
- **JIRA or GitHub link**: [LIVE-11947] 
---
[LIVE-11947]: https://ledgerhq.atlassian.net/browse/LIVE-11947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …
=> [FIX]: Analytics LedgerSync

.changeset/afraid-stingrays-hunt.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx
=> feat: use account id instead of currency id

.changeset/tasty-pandas-behave.md, apps/ledger-live-mobile/src/components/RequiresCameraPermissions/Fallback.tsx
- ...
Fix setting icon rendering color 
---
=> fix: fallback screen settings button icon rendering with the right color

.changeset/happy-onions-know.md, apps/ledger-live-desktop/src/renderer/families/bitcoin/SendAmountFields.tsx
- ...
I introduced a regression when refactoring errors for swap. This PR aims to remove the regression and clean up the code
Video of the issue. Warning error that open buy BTC if clicked (new regression)
https://github.com/user-attachments/assets/0041bb4d-4635-4772-a162-1d35f6ceb6cf
Video of the fix. Old behavior. No warning
https://github.com/user-attachments/assets/91cfc22b-71ea-46d3-a99a-c2e6d6824281
--- …
=> fix: remove errors in drawer

.changeset/tame-years-perform.md, libs/ledgerjs/packages/hw-app-eth/src/modules/EIP712/index.ts, libs/ledgerjs/packages/hw-app-eth/src/modules/EIP712/utils.ts, libs/ledgerjs/packages/hw-app-eth/tests/EIP712/utils.unit.test.ts
- No impact
PR fixing custom types not being split correctly due to an invalid regex
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-13893
---
=> [LIVE-13893] Bugfix- Fix `destructTypeFromString` not splitting types correctly

.changeset/tricky-pans-obey.md, libs/ledgerjs/packages/hw-app-eth/src/modules/EIP712/utils.ts, libs/ledgerjs/packages/hw-app-eth/tests/EIP712/utils.unit.test.ts
- no more throws when a token isn't in CAL
When a token isn't in CAL, we can't send the correct descriptors to the device (`PROVIDE_ERC20_TOKEN_INFOS`) which is supposed to return the token "index" it has in memory. Due to this not being possible, we were throwing an error `missing coinRef` without ever sending anymore APDUs.
This behavior will be changed in the next ethereum nano app, and the app is now expecting the `coinRef` even if the token descriptor hasn't been provided.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-13976
--- …
=> [LIVE-13976] Bugfix - Allow missing coinRef with EIP-712 filters V2

apps/ledger-live-desktop/src/renderer/Default.tsx, apps/ledger-live-desktop/src/renderer/components/WebPTXPlayer/TopBar.tsx, apps/ledger-live-desktop/src/renderer/screens/card/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- ...
Card back button implementation for LLD
---
=> fix: fix back button lld card

.changeset/strong-steaks-rule.md, .changeset/twelve-owls-accept.md, .changeset/wet-clocks-nail.md, apps/cli/package.json, apps/cli/src/commands-index.ts, apps/cli/src/commands/device/reinstallConfigurationConsent.ts, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/locales/en/common.json, libs/device-core/src/commands/entities/ReinstallConfigEntity.ts, libs/device-core/src/commands/use-cases/consent/reinstallConfigurationConsent.test.ts, libs/device-core/src/commands/use-cases/consent/reinstallConfigurationConsent.ts, libs/device-core/src/index.ts, libs/ledgerjs/packages/errors/src/index.ts, pnpm-lock.yaml
- new PINNotSet in @ledgerhq/errors + error entry in translation file for LLM / LLD
- new consent usecase reinstallConfiguration in @ledgerhq/device-core
- implement new usecase in CLI
Implement new APDU to give consent after an OS update to reinstall the whole config of the device.
This allows us to skip all the user consent for each step (language pack, custom locksceen, apps, and now apps data) and only require one approval before the whole restore flow.
- **JIRA or GitHub link**: [LIVE-13028] 
--- …
=> :sparkles: (device-core): add new reinstallConfiguration consent use case

.changeset/lemon-starfishes-do.md, apps/ledger-live-mobile/src/components/DeviceActionModal.tsx, apps/ledger-live-mobile/src/hooks/deviceActions.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/DeviceSelection/index.tsx, apps/ledger-live-mobile/src/screens/AddAccounts/02-SelectDevice.tsx
- ...
**I'm opened to alternative solutions.**
TLDR: I'm not completely satisfied with this solution but I don't see another way which doesn't involve a major refactor.
The issue comes from the current structure of `DeviceActionModal` which relies on the `device` prop and `result` internal state to trigger the drawer. Once `result` is set the drawer is not supposed to re-opened and since `device` is not necessary reset something like this doesn't always work:
```js
useEffect(() => {
if (!device) return () => setResult(null);
}, [device]);
```
(also it might break some other flow unrelated to ledger sync).
The way I see it selecting a device should imperatively trigger the device interaction. But this component is used this way everywhere else there is a device interaction on LLM. …
=> fix: 🔁 device selection after aborted flow

.changeset/curly-terms-rescue.md, libs/coin-modules/coin-tron/src/logic/utils.test.ts, libs/coin-modules/coin-tron/src/logic/utils.ts, libs/coin-modules/coin-tron/src/network/format.test.ts, libs/coin-modules/coin-tron/src/network/format.ts, libs/coin-modules/coin-tron/src/network/types.ts, libs/coin-modules/coin-tron/src/types/bridge.ts
- ...
Approve smart contract method executions broke history graph / operation list on Tron
This PR fixes this and edit operation type to approval (also, it moves from token account to parent)
Before : 
After:
- **JIRA or GitHub link**:  [https://ledgerhq.atlassian.net/browse/LIVE-12478](https://ledgerhq.atlassian.net/browse/LIVE-12478)
--- …
=> fix approve operations tron

apps/ledger-live-desktop/tests/specs/onboarding/connect-device.spec.ts, apps/ledger-live-desktop/tests/specs/onboarding/restore-device.spec.ts
=> Fix stability of device selection screenshot

.changeset/loud-donkeys-glow.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/components/StepFlow.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Activation/ActivationFlow.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useLedgerSyncAnalytics.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useSyncWithQrCode.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Synchronize/ScannedInvalidQrCode.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Synchronize/ScannedOldImportQrCode.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/types/Activation.ts, apps/ledger-live-mobile/src/screens/ImportAccounts/Scan.tsx, libs/trustchain/src/errors.ts, libs/trustchain/src/qrcode/index.test.ts, libs/trustchain/src/qrcode/index.ts
| Description        | Behavior         |
|Scans a Ledger Sync QR code on desktop with FF disabled on mobile|![Screenshot_2024-09-11-17-52-10-82_99c1b3bb631177f8a9e1379ae5b12ffe](https://github.com/user-attachments/assets/0e0037c6-c6a3-4b80-9c54-dc8a7ede5332)|
|Scans the old QR code on desktop with FF enabled on …
=> Ledger Sync - Display error when scanning invalid QR Code

.changeset/thick-glasses-swim.md, apps/ledger-live-desktop/src/renderer/modals/ExportOperations/index.tsx, libs/ledger-live-common/src/csvExport.ts
- export to csv
Accounts names were not exported in the csv it's now fixed. 
- **JIRA or GitHub link**:  [LIVE-14076](https://ledgerhq.atlassian.net/browse/LIVE-14076)
---
[LIVE-14076]: …
=> :bug:fix(lld): fix export to csv account name

.changeset/dry-weeks-bow.md, libs/ledger-live-common/src/families/hedera/__snapshots__/bridge.integration.test.ts.snap, libs/ledger-live-common/src/families/hedera/bridge.integration.test.ts, libs/ledger-live-common/src/families/hedera/utils.ts
Checked out from https://github.com/LedgerHQ/ledger-live/pull/7790.
- ...
Add safety margin to Hedera fee estimates
- **JIRA or GitHub link**: LIVE-12535
---
=> LIVE-12535 fix: add safety margin to estimated fees for hedera

.changeset/rude-ants-share.md, apps/ledger-live-desktop/src/renderer/screens/asset/AssetBalanceSummaryHeader.tsx, apps/ledger-live-desktop/src/renderer/screens/dashboard/FeaturedButtons.tsx, apps/ledger-live-mobile/src/colors.tsx, apps/ledger-live-mobile/src/components/InfoModal.tsx, apps/ledger-live-mobile/src/components/RootNavigator/types/EarnLiveAppNavigator.ts, apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx, apps/ledger-live-mobile/src/reducers/earn.ts, apps/ledger-live-mobile/src/reducers/types.ts, apps/ledger-live-mobile/src/screens/PTX/Earn/EarnInfoDrawer.tsx
- The info modal for Earn will gain an additional property, `learnMoreLink`. A button will redirect to the established external link
- An info icon will show up on top of these modals.
Add an optional "learn more" button to Earn's info modal. Small tweaks to the visuals.
Before:
After:
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-13927
--- …
=> feat: update earn info modal on ledger-live-mobile to add a link to `learnMore`

.changeset/tiny-gifts-matter.md, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/useAddAccountViewModel.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Activation/useActivationDrawerModel.ts
- ...
- Password lock blocked on QRScan
Fix also Step when coming back to AddAccount if I used LedgerSync from GeneralSettings, Drawer was empty => `isOpen` added in deps
- **JIRA or GitHub link**: [LIVE-14101] 
--- …
=> fix: 🐛 Password lock blocked on QRScan

.changeset/unlucky-beds-leave.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/__tests__/shared.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/__tests__/walletSync.test.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Activation/01-CreateOrSynchronizeStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Activation/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/shared.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/walletSyncActivation.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Activation/Actions.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Activation/index.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- LS activation LLD and LLM
Add a field to the feature flag so we can dynamically change the learn more url when activate ledger sync.  
The learmore link will appears only if a value is provided
The UI has changed on both LLD and LLM
Good and bad case integration tests added
The new field is `learnMoreLink` 
LLD : 
https://github.com/user-attachments/assets/92fae350-6a76-4b0f-920c-efbfa6aeb3e9
LLM : 
https://github.com/user-attachments/assets/bc0fec2d-8b05-4673-aa08-33feb6ec6eaf
- **JIRA or GitHub link**: [LIVE-14081](https://ledgerhq.atlassian.net/browse/LIVE-14081) & [LIVE-14082](https://ledgerhq.atlassian.net/browse/LIVE-14082)
--- …
=> :sparkles:(llm/lld): add dynamic learn more for LS activation

.changeset/forty-panthers-clean.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useAddMember.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useAddMember.ts, libs/trustchain/src/sdk.ts, libs/trustchain/src/types.ts
- ...
The ticket (linked below) suggests to display a different error in this case. However if the user initiates a synchronization with a device after being removed from the trustchain I think the process should go to completion, no matter if the synchronization is done with the same seed or with a different one. This is the solution introduced by this PR. WDYT ?
https://github.com/user-attachments/assets/172308c0-5256-4f7d-8b6e-41ba6ba926a3
- [LIVE-14088]
--- …
=> fix(trustchain): 🚦 allow members to sync immediately after getting removed

.changeset/shy-ducks-sparkle.md, apps/ledger-live-mobile/src/screens/Account/index.tsx
- ...
Fix Blank account screen when removing account from LLD when LS activated
https://github.com/user-attachments/assets/3cd321eb-3c5d-4dbd-9144-b821ae9df01c
- **JIRA or GitHub link**: [LIVE-14152] 
--- …
=> fix: 🐛 Fix Blank account screen when removing account from LLD when LS activated

apps/ledger-live-desktop/tests/specs/speculos/add.account.spec.ts
=> Deactivating add Account test for DOT

.changeset/gentle-fireants-nail.md, apps/ledger-live-desktop/src/renderer/components/Carousel/helpers.tsx, apps/ledger-live-desktop/src/renderer/components/Carousel/index.tsx, apps/ledger-live-desktop/src/renderer/hooks/useActionCards.tsx, apps/ledger-live-desktop/src/renderer/hooks/useBraze.ts, apps/ledger-live-desktop/src/renderer/hooks/useNotifications.ts
Fixed an issue with the tracking of the content cards on desktop because we were doing a copy of the `Braze.ClassicCard` object instead of passing the original one to the `logContentCardClick` method.
Also fixes some issues with the tracking of the carousel that was triggered at every rerender.
- **JIRA or GitHub link**: [LIVE-14043]
--- …
=> LLD - Braze Content cards clicks tracking

.changeset/cuddly-eggs-cross.md, apps/ledger-live-desktop/src/renderer/components/WebPTXPlayer/CustomHandlers.ts
- ...
Instead of trying to guess the state of LL inside exchangeSDK, just check if something is open and do not open a new drawer when receiving an error ... 
Really nice fix thanks @chrisduma-ledger for the idea, somehow we all missed it
--- …
=> fix: only open error drawer if no drawer opened

.changeset/sixty-insects-rescue.md, apps/ledger-live-mobile/ios/Podfile.lock, apps/ledger-live-mobile/package.json, apps/ledger-live-mobile/src/components/StorylyStories/StorylyProvider.tsx, apps/ledger-live-mobile/src/components/StorylyStories/StorylyWrapper.tsx, apps/ledger-live-mobile/src/components/StorylyStories/index.tsx, apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx, apps/ledger-live-mobile/src/screens/Portfolio/index.tsx, pnpm-lock.yaml
Update `storyly-react-native` from 2.18.1 to 3.6.0
Stories are now displayed in the user's app language
Fixes the following issues : 
- Story was closing instead of pausing when user long pressed
- Story was not displayed on cold app start when triggered by a deep link
- No more black screen when putting the app in the background in the middle of a story
- **JIRA or GitHub link**: [LIVE-14103] [LIVE-14119] [LIVE-13778] [LIVE-13857]
--- …
=> LLM - Update Storyly and fixes issues

.changeset/silent-melons-lie.md, apps/ledger-live-desktop/src/newArch/features/AnalyticsOptInPrompt/screens/index.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/WalletSync.tsx
Disabling focus trap on analytics and wallet sync drawers to fix the braze modal that wasn't responding when displayed on top of them
Fix tested on a staging build
https://github.com/user-attachments/assets/6116ccb1-6193-4b35-8678-1ac7b6463a91
- **JIRA or GitHub link**: [LIVE-13870]
--- …
=> LLD - Fix Braze Modal not responding when a drawer is opened

.changeset/thin-readers-attend.md, apps/ledger-live-desktop/src/renderer/drawers/DataSelector/AccountList.tsx, apps/ledger-live-desktop/tests/specs/services/wallet-api.spec.ts
- ...
- use spendable balance instead of balance.
- use parent account name as prefix for token accounts.
https://ledgerhq.atlassian.net/browse/LIVE-14165
---
=> [FIX/LIVE-14165]: use spendable balance and account id for token accounts

.changeset/neat-items-lay.md, apps/ledger-live-desktop/src/config/urls.ts, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/components/Inscriptions/DiscoveryDrawer/Header.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/components/Inscriptions/DiscoveryDrawer/index.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/screens/Account/index.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/screens/Account/useBitcoinAccountModel.ts, apps/ledger-live-desktop/src/newArch/features/Collectibles/__integration__/bitcoinPage.test.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/__integration__/shared.tsx, apps/ledger-live-desktop/src/renderer/actions/settings.ts, apps/ledger-live-desktop/src/renderer/reducers/settings.ts, apps/ledger-live-desktop/static/i18n/en/app.json
- BTC accounts
Add discovery drawer when user comes to btc account and feature has just been activated
useLocalizedUrl for learn more is not used because the academy page only exists in english for ordis
Also view coin control redirects to nothing it will be implemented after
A color is hardcoded to match with btc logo color
For the demo the state is forced so we always see the drawer
https://github.com/user-attachments/assets/8de21056-3997-4ab5-b8d0-c5896986631c
- **JIRA or GitHub link**: [LIVE-12481](https://ledgerhq.atlassian.net/browse/LIVE-12481)
--- …
=> :sparkles:(lld): add discovery drawer for ordis

.changeset/empty-clouds-glow.md, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/components/Error.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/components/Inscriptions/DetailsDrawer/index.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/components/Inscriptions/helpers.ts, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/components/Inscriptions/index.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/components/Inscriptions/useInscriptionsModel.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/components/RareSats/index.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/screens/Account/index.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/Ordinals/screens/Account/useBitcoinAccountModel.ts, apps/ledger-live-desktop/src/newArch/features/Collectibles/components/Collection/EmptyCollection.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/hooks/useFetchOrdinals.ts, apps/ledger-live-desktop/src/renderer/modals/Receive/Body.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- ordis
Add empty state in table for inscriptions and rare sats
Add error message to error row
Add dummy drawer that will be replaced by the good one in next pr 
https://github.com/user-attachments/assets/0ac826a8-0658-46d3-9872-e424d67f9402
- **JIRA or GitHub link**: [LIVE-14231](https://ledgerhq.atlassian.net/browse/LIVE-14231)
--- …
=> :sparkles:(lld): add empty message and dummy drawer for ordis

.github/workflows/test-mobile.yml
- ...
We should not run mobile codechecks outside the master workflow.
---
=> fix: allow mobile codecheck workflow only on dispatch

turbo.json
- Dev env
Mark start tasks as `persistent` to enable `interactive` mode
From the doc: Label a task as persistent to prevent other tasks from depending on long-running processes. https://turbo.build/repo/docs/reference/configuration#persistent
Tested locally with `pnpm dev:llm`, metro bundler allows to reload the app or open the debug menu
- **JIRA or GitHub link**: none
---
- **Any new …
=> chore: mark start tasks as `persistent` to enable `interactive` mode

.changeset/sour-poets-play.md, apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx
- Wallet-connect deeplink on LLM
Wallet-connect deep-link from native app for a request would reload the page
Instead of receiving the usual deeplink with a requestId and topic we would receive a `wc:` invalid link that updated the uri used in the webview
Reloading the page would break the wallet-api flow shown when coming back to the app
We will consider cancelling a flow in the wallet-api if the page is reloaded like that with a message and probably logs for us in order to avoid it happening again
- **JIRA or GitHub link**: [LIVE-13641]
--- …
=> fix(LLM): wallet-connect deep-link from native app for a request would reload the page [LIVE-13641]

.changeset/clever-rocks-watch.md, apps/ledger-live-mobile/src/screens/SignMessage/04-ValidationError.tsx, apps/ledger-live-mobile/src/screens/SignMessage/04-ValidationSuccess.tsx
- Wallet API sign message flow on LLM
Now only call success and fail handlers when closing the flow on LLM
Allows to properly retry the sign message without sending an error through the wallet-api
We also only send the success when we actually close the last success screen
For success flow we could also auto close if the handler is present to remove an action but I prefer to keep things as close as we currently have it
- **JIRA or GitHub link**: none
---
- **The PR has been tested** thoroughly, and …
=> fix(wallet-api): only call success and fail handlers when closing the flow on LLM

.changeset/tough-terms-film.md, apps/ledger-live-mobile/src/components/Web3AppWebview/PlatformAPIWebview.tsx, apps/ledger-live-mobile/src/components/Web3AppWebview/helpers.ts
- Discover and live-apps deeplink usage (impact pretty low as we just try to open the deeplink always instead of sometimes)
Open any deep-link from the webview on LLM
Needed for wallet-connect-live-app deep-link back to mobile dApps
`CanOpenUrl` would require us to list every deep-link scheme we want to test and it's not possible in our case: https://stackoverflow.com/a/67111267
- **JIRA or GitHub link**: [LIVE-13641]
--- …
=> fix(wallet-api): open any deep-link from the webview on LLM

.changeset/slow-dingos-destroy.md, apps/ledger-live-desktop/src/renderer/hooks/useDeeplinking.ts, apps/ledger-live-desktop/src/renderer/screens/account/AccountHeaderActions.tsx, apps/ledger-live-mobile/src/components/RootNavigator/WalletConnectLiveAppNavigator.tsx, apps/ledger-live-mobile/src/components/Web3AppWebview/WalletAPIWebview.tsx, apps/ledger-live-mobile/src/screens/Platform/v2/hooks.ts, libs/ledger-live-common/src/wallet-api/constants.ts
- Wallet-connect live-app
Allow wallet-connect live-app to open a deep-link at any time on LLM
Refactor by sharing a single constant for wallet-connect live-app manifest id
- **JIRA or GitHub link**:  [LIVE-13641]
--- …
=> fix(LLM): allow wallet-connect live-app to open a deep-link at any time [LIVE-13641]

.changeset/strong-goats-rush.md, apps/ledger-live-mobile/.env.mock, apps/ledger-live-mobile/e2e/bridge/server.ts
- ...
Do not display the analytics prompt modal in LLM e2e tests by providing `shareAnalytics: true, hasSeenAnalyticsOptInPrompt: true` as default settings. Personally I prefer this approach over the one in #7878 because it doesn't an add extra interaction on each test (which AFAIK would have been way more costly on detox than playwright). That said it looks very unconventional with what was done before. So there might be a better solution.
- [LIVE-13649]
--- …
=> chore(llm): 👌 always skip the analytics prompt in e2e tests

.changeset/big-snakes-marry.md, apps/ledger-live-desktop/src/newArch/features/AnalyticsOptInPrompt/hooks/useCommonLogic.tsx, apps/ledger-live-desktop/src/newArch/features/AnalyticsOptInPrompt/screens/VariantA/Main/components/MainFooter/index.tsx, apps/ledger-live-desktop/src/newArch/features/AnalyticsOptInPrompt/screens/VariantB/components/Footer/index.tsx, apps/ledger-live-desktop/tests/fixtures/common.ts, apps/ledger-live-desktop/tests/page/onboarding.page.ts, apps/ledger-live-desktop/tests/specs/onboarding/connect-device.spec.ts, apps/ledger-live-desktop/tests/specs/onboarding/restore-device.spec.ts, apps/ledger-live-desktop/tests/specs/onboarding/setup-device.spec.ts, apps/ledger-live-desktop/tests/specs/syncOnboarding/manual.spec.ts, apps/ledger-live-desktop/tests/userdata/1AccountBTC1AccountETH-encrypted.json
- ...
Dismiss analytics prompt in LLDs tests by using settings value of `shareAnalytics: true, hasSeenAnalyticsOptInPrompt: true` by default. Use `hasSeenAnalyticsOptInPrompt: true` in onboarding tests to go through the normal user experience.
- [LIVE-13650]
--- …
=> chore(lld): 👌 always skip the analytics prompt in e2e tests

.changeset/six-hairs-raise.md, apps/ledger-live-mobile/e2e/jest.config.js
- ...
Tests files at `e2e/specs/*.spec.ts` are no longer run. It comes from a change in #7789 which looks accidental to me. Here's the change in the glob pattern (from https://www.digitalocean.com/community/tools/glob)
|  <img width="407" alt="image" src="https://github.com/user-attachments/assets/79515aa6-ddba-4450-a975-6b54834fdcfa">   | <img width="407" alt="image" src="https://github.com/user-attachments/assets/6e9311c6-6cf5-4e04-aaf4-c7ca093b299c"> |
--- …
=> chore(llm): 🏚️ run tests at `e2e/specs/*.spec.ts`

.changeset/cuddly-zebras-give.md, libs/ui/packages/icons/tsconfig.json, libs/ui/packages/native/tsconfig.json, libs/ui/packages/react/tsconfig.json, libs/ui/packages/shared/tsconfig.json
- ...
Add [declaration map](https://www.typescriptlang.org/tsconfig/#declarationMap) on dependencies where they are missing. It allows quickly checking the references definitions on IDEs.
I was exploring the code base a bit for tech day, and realised the declaration maps where missing for some packages (mostly the design system related dependencies. 
Before:
https://github.com/user-attachments/assets/a75f19eb-4dc2-4f45-a562-9aea421d3d06
After:
https://github.com/user-attachments/assets/9a1820b9-6f6d-408c-a2f3-fd402bba4b91
--- …
=> chore: 🗺️ fix IDE go to definition feature for some libs

.changeset/plenty-hornets-turn.md, apps/ledger-live-desktop/src/renderer/components/BalanceInfos/index.tsx, apps/ledger-live-desktop/src/renderer/components/ContextMenu/AccountContextMenu.tsx, apps/ledger-live-desktop/src/renderer/modals/NoFundsStake/index.tsx, apps/ledger-live-desktop/src/renderer/screens/account/AccountHeaderActions.tsx, apps/ledger-live-desktop/src/renderer/screens/asset/AssetBalanceSummaryHeader.tsx, apps/ledger-live-desktop/src/renderer/screens/asset/BalanceSummary.tsx, apps/ledger-live-desktop/src/renderer/screens/asset/index.tsx, apps/ledger-live-desktop/src/renderer/screens/dashboard/GlobalSummary.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx, apps/ledger-live-desktop/src/renderer/screens/market/hooks/useMarketActions.ts
- ...
- pass `defaultAccount` to swap page from portfolio asset page
- swap from for analytics of from location in swap live app
https://ledgerhq.atlassian.net/browse/LIVE-9213
---
=> fix: pass account to asset page

.changeset/brown-ducks-rule.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useWatchWalletSync.ts, apps/ledger-live-desktop/src/renderer/reducers/wallet.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useWatchWalletSync.ts, apps/ledger-live-mobile/src/reducers/wallet.ts, apps/web-tools/trustchain/components/AppAccountsSync.tsx, libs/live-wallet/src/walletsync/incrementalUpdates.ts
This PR fixes an issue that caused the synchronization to be broken for an instance in the following situation : 
When the local wallet sync state version was different than the one returned by the cloud sync api (when pushing or pulling data) and the `resolveIncrementalUpdate` function didn't detect any changes between the latestState and the distantState, the local version wasn't updated and all subsequent call to the cloud sync api were returning an out of sync state.
This is fixed by updating the local version to the value returned by the cloud sync api even if there were no differences between the latest data and the distant data. That way the following calls made to pull data from the cloud sync api will be successfull and the synchronization will keep working.
- **JIRA or GitHub …
=> Ledger Sync - Fix side effect causing the synchronization to stop working

apps/ledger-live-desktop/src/newArch/features/WalletSync/__tests__/manageSynchronizedInstances.test.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/__tests__/manageYourBackup.test.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/__tests__/synchronize.test.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/__tests__/walletSync.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/manageKey.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/scanQRCode.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/synchronizeWithQrCode.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/walletSyncActivated.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/walletSyncActivation.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/walletSyncSettings.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/walletSyncStatus.integration.test.tsx
- ...
Fix usage of await in integration tests.
---
=> fix: improve ledger sync tests

.changeset/shy-apples-tickle.md, libs/coin-modules/coin-solana/src/api/chain/account/index.ts, libs/coin-modules/coin-solana/src/api/chain/account/parser.ts, libs/coin-modules/coin-solana/src/api/chain/account/stake.ts, libs/coin-modules/coin-solana/src/api/chain/index.ts, libs/coin-modules/coin-solana/src/api/chain/stake-activation/delegation.ts, libs/coin-modules/coin-solana/src/api/chain/stake-activation/index.ts, libs/coin-modules/coin-solana/src/api/chain/stake-activation/rpc.ts, libs/coin-modules/coin-solana/src/api/chain/validators/bignum.ts
- Delegations table
Multiple RPC endpoints scheduled to be removed on Solana due to transition to Agave 2.0 on Mainnet. See [transition guide](https://github.com/anza-xyz/agave/wiki/Agave-v2.0-Transition-Guide#step-2-review-removed-rpc-endpoints-and-sdk-elements). 
This PR replaces outdated `GetStakeActivation` endpoint with a [solution](https://github.com/solana-developers/solana-rpc-get-stake-activation) provided by Solana team.
--- …
=> fix(coin-solana): transition of outdated Solana GetStakeActivation endpoint

.changeset/wild-cars-shop.md, apps/ledger-live-mobile/src/dynamicContent/ContentCardsLocation.tsx
Fixed a spacing issue when there was a category with all its content cards dismissed by the user
- **JIRA or GitHub link**: [LIVE-14318]
---
[LIVE-14318]: https://ledgerhq.atlassian.net/browse/LIVE-14318?atlOrigin=eyJ …
=> LLM - Fixed a spacing issue when there was a category with all its content cards dismissed by the user

apps/cli/README.md, apps/cli/src/commands-index.ts, apps/cli/src/commands/live/ledgerSync.ts
- ...
Add Ledger Sync commands to the CLI.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-14333
---
=> Add Ledger Sync commands to the CLI

.changeset/tender-icons-impress.md, libs/ledgerjs/packages/hw-app-eth/package.json
- no impact
`ws` lib has been forced to a `7.5.10` version to fix a CVE in the lib, but it's only enforced when bundled in Ledger Live by pnpm & the monorepo. This should enforce it as well for the simple npm package published.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-14339
--- …
=> [LIVE-14339] Support - Enforce WS version even when bundle without pnpm in the monorepo

.changeset/cool-cougars-push.md, libs/env/src/env.ts
- Transactions using EIP-1559 will now only be sure to have enough base fee to be included in the next 3 blocks instead of the next 4 blocks before
Ledger Live is using a base fee multiplier to make sure the transactions crafted can be included in X blocks in the future based on the EIP-1559 spec.
Example of the fee system from [Blocknative](https://www.blocknative.com/blog/eip-1559-fees#4):
| Block | Base Fee   | % Full | Increase in Base Fee | Priority Fee specified | Max Fee specified | Gas Price Paid if confirmed |
|-------|------------|--------|----------------------|------------------------|-------------------|-----------------------------|
| 1     | 100.0 GWEI | 100%   | 12.5%                | 2.0                    | 202.0             | 102.0                       |
| 2     | …
=> [LIVE-7357] Feature - Decrease EIP-1559 base fee multiplier

.github/workflows/build-mobile-reusable.yml
- ...
Like nightly build, this changes will add retry attempts security for pods related generation problem on ios post install scripts for build and test PR.
https://ledgerhq.atlassian.net/browse/LIVE-14221
--- …
=> chore: add retry attempts on ios build workflow to avoid pods issues

.changeset/heavy-peas-cover.md, apps/ledger-live-desktop/src/renderer/screens/earn/index.tsx, apps/ledger-live-mobile/src/screens/PTX/Earn/index.tsx
- no changes until braze is configured in earn dashboard. 
Braze requires a unique key for each platform os ("web", "ios", "android"). Currently there is no way to detect this from within the earn dashboard. This adds the string to the query parameters on initialising earn.
- **JIRA or GitHub link**: [CN-587](https://ledgerhq.atlassian.net/browse/CN-587)
--- …
=> Chore: pass os parameter to earn dashboard

.changeset/tough-owls-grin.md, apps/ledger-live-mobile/scripts/post.mjs
- ...
In order to easily monitor and debug futur ios build failures on the CI , we need to add --verbose in the pod install process.
https://ledgerhq.atlassian.net/browse/LIVE-14340
---
=> chore: add --verbose flag to pod install

.changeset/thick-candles-visit.md, libs/ledger-live-common/.unimportedrc.json, libs/ledger-live-common/src/errors/sendFlow.ts
- Nothing / file created in common
For send flow we want to handle some specifics errors to return the correct support url if there is one or we will use the main support page url
- **JIRA or GitHub link**: [LIVE-14069](https://ledgerhq.atlassian.net/browse/LIVE-14069)
--- …
=> 🥅(lld): add custom errors for send flow

apps/ledger-live-desktop/jest.config.js, apps/ledger-live-mobile/jest.config.js
- ...
When jest:test:coverage was run, shared files in the __integration__ and __tests__ folders were checked. This distorted the results of the coverage
- **JIRA or GitHub link**: NO LINK 
---
=> :technologist:(lld-llm): remove inte and test folders of jest coverage

.changeset/pretty-penguins-hang.md, apps/ledger-live-desktop/src/renderer/analytics/segment.ts, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebView.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/hooks/useIsSwapLiveFlagEnabled.ts, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/index.tsx, libs/ledger-live-common/src/exchange/swap/hooks/live-app-migration/useSwapLiveConfig.test.ts, libs/ledger-live-common/src/exchange/swap/hooks/live-app-migration/useSwapLiveConfig.ts, libs/ledger-live-common/src/exchange/swap/hooks/v5/useFilteredProviders.ts, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- ...
- add ptxSwapCoreExperiment flag based on this logic https://ledgerhq.atlassian.net/wiki/spaces/PTX/pages/5002821634/SWAP+AB+Test+Plan+Document+Improving+User+Flow+by+Improving+quotes+display+-+Demo+3?focusedCommentId=5089132693
https://github.com/user-attachments/assets/37ffa101-8c87-4c14-a0f0-77438be25b98
https://ledgerhq.atlassian.net/browse/LIVE-14205
---
- …
=> feat(live-14205): add ptxSwapCoreExperiment flag

apps/ledger-live-desktop/tests/enum/Account.ts, apps/ledger-live-desktop/tests/fixtures/common.ts, apps/ledger-live-desktop/tests/specs/speculos/README.md, apps/ledger-live-desktop/tests/specs/speculos/delete.account.spec.ts
- ...
Use the cli to craft the app.json used in the speculos e2e test
- **JIRA or GitHub [QAA117:](https://ledgerhq.atlassian.net/browse/QAA-117)
---
[QAA-117]: …
=> ✨ (lld x Speculos): Using cli to build app.json

.changeset/beige-planes-shake.md, apps/ledger-live-desktop/src/renderer/families/evm/StakeFlowModal/index.tsx, apps/ledger-live-mobile/src/families/evm/StakingDrawer/index.tsx, libs/ui/packages/native/src/components/Tabs/Chip/index.tsx, libs/ui/packages/native/src/components/Tabs/TemplateTabs/index.tsx
- Hide the category filters when the providers' list for that category is empty
Hide the category filters when the providers' list for that category is empty.
Only categories with at least one provider will show:
---
=> EARN: hide category filter when providers' list is empty

.changeset/shy-lobsters-report.md, apps/ledger-live-desktop/src/renderer/components/ToastOverlay/TimeBasedProgressBar.tsx, apps/ledger-live-desktop/src/renderer/components/ToastOverlay/Toast.tsx, apps/ledger-live-desktop/src/renderer/components/ToastOverlay/index.tsx
- toasts
Stacked were not disappearing because we didn't delete their id of the list. Fixed ✅ 
Also add duration to toast of 10sec
Fixed the duration bar 
https://github.com/user-attachments/assets/8fc1a9ca-59ea-4940-bfe3-59302e3e8433
- **JIRA or GitHub link**:(https://ledgerhq.atlassian.net/browse/LIVE-14262)[LIVE-14262] 
---
- …
=> :bug:(lld): fix toasts issue

.github/workflows/release-create-hotfix.yml, .github/workflows/release-create.yml, .github/workflows/release-final-nightly.yml, .github/workflows/release-final.yml, .github/workflows/release-prepare-hotfix.yml, .github/workflows/release-prepare.yml, .github/workflows/release-prerelease.yml
Pins dependencies for `release-*.yml` workflows. In reality this pins only the ubuntu version, but all workflows were individually checked for versions that could drift. This includes the following custom action dependencies:
- generate-release-message
- get-package-infos
- setup-toolchain
- turborepo-s3-cache
- setup-git-user
3rd party actions were checked for having a major version pin but the pin was not extended to minor versions.
https://ledgerhq.atlassian.net/browse/LIVE-14091
---
- **The PR …
=> build: pin release workflow dependencies

apps/ledger-live-mobile/README.md
[Our runners use Xcode 15.3](https://github.com/LedgerHQ/mac-foundry/blob/main/build/ledger-live-test/ledger-live-test.pkr.hcl#L59) not 15.4, so updating the readme accordingly
Just fixing an incorrect readme
=> readme: fix xcode version

.changeset/lucky-otters-think.md, libs/ledger-live-common/src/csvExport.ts
- Export csv
There was an issue introduced with previous PR https://github.com/LedgerHQ/ledger-live/pull/7813 that uses token name as account name. 
- **JIRA or GitHub link**: [LIVE-14528](https://ledgerhq.atlassian.net/browse/LIVE-14528)
--- …
=> :bug:(lld): exported account name in csv

.changeset/loud-donkeys-smash.md, apps/ledger-live-desktop/src/renderer/components/AccountSubHeader/AccountSubHeaderDrawer.tsx, apps/ledger-live-desktop/src/renderer/components/AccountSubHeader/index.tsx, apps/ledger-live-desktop/src/renderer/families/casper/AccountSubHeader.tsx, apps/ledger-live-desktop/src/renderer/families/filecoin/AccountSubHeader.tsx, apps/ledger-live-desktop/src/renderer/families/internet_computer/AccountSubHeader.tsx, apps/ledger-live-desktop/src/renderer/families/stacks/AccountSubHeader.tsx, apps/ledger-live-desktop/src/renderer/families/ton/AccountSubHeader.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/components/AccountSubHeader/AccountSubHeaderDrawer.tsx, apps/ledger-live-mobile/src/components/AccountSubHeader/index.tsx, apps/ledger-live-mobile/src/families/casper/AccountSubHeader.tsx, apps/ledger-live-mobile/src/families/filecoin/AccountSubHeader.tsx, apps/ledger-live-mobile/src/families/internet_computer/AccountSubHeader.tsx, apps/ledger-live-mobile/src/families/stacks/AccountSubHeader.tsx, apps/ledger-live-mobile/src/families/ton/AccountSubHeader.tsx, apps/ledger-live-mobile/src/locales/en/common.json
- ...
Third party integration teams, assuming they provided a link, now get's their team names clickable in the "integrated by" drawer
---
=> LIVE-14383 working display of team link

apps/ledger-live-desktop/tests/specs/services/dapp.spec.ts
- Only tests
The test was flaky on slower hard because of missing expect assertion in the test
---
=> test: fix missing expect on dapp test

libs/ledger-live-common/src/e2e/speculos.ts
Trying to fix when text isn't found on speculos device screen by waiting between 2 attempts
[reporting](https://ledger-live.allure.green.ledgerlabs.net/allure/reports/a01ebf08-a321-4c5a-a6c5-fcfb6de75d35/)
failures on Ledger sync is due to wrong CLI command returning 502 & on swap due to changelly not appearing (bit random)
unrelated to my changes
--- …
=> fix attempt: wait between attempts for speculos device's screen to refresh

.changeset/loud-birds-jam.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/components/Drawer.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useLedgerSyncAnalytics.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Activation/01-CreateOrSynchronizeStep.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Activation/index.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Manage/index.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/router.tsx, apps/ledger-live-desktop/src/renderer/screens/accounts/LedgerSyncDrawer.tsx, apps/ledger-live-desktop/src/renderer/screens/accounts/OptionsButton.tsx, apps/ledger-live-desktop/src/renderer/screens/accounts/index.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/WalletSync.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- Ledger Sync 
- Accounts
We missed a QRCode entry point during LS implem. This PR fix the issue to redirect to LS if FF enabled.
If user has already set it it will be manage else it will have the possibility to set up it
https://github.com/user-attachments/assets/d93dee03-edd1-4f84-8f18-cc808847f5f3
- **JIRA or GitHub link**: [LIVE-14461](https://ledgerhq.atlassian.net/browse/LIVE-14461)
---
- …
=> :bug:(lld): update LS entry point from accounts

apps/ledger-live-mobile/package.json, apps/ledger-live-mobile/src/newArch/features/Web3Hub/components/Disclaimer/useDisclaimerViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Web3Hub/constants.ts, apps/ledger-live-mobile/src/newArch/features/Web3Hub/db.ts, libs/ledger-live-common/package.json, pnpm-lock.yaml
Currently, the way we update the app storage causes issues because the data state isn't shared between instances.
Specifically, when we modify a variable with instance X, the state of instance Y isn't updated (as the state isn't shared). As a result, if two different instances update the app storage at the same time, only the last modification is applied, leading to potential data loss.
Ensure that the database state is shared across all instances. This way, a modification in instance Z will automatically reflect in instance Y, by using `Jotai` npm lib, a lightweight library that simplifies state management across an application.
https://github.com/user-attachments/assets/5b840552-b12b-46c2-8067-a9e91f866022
- **JIRA** : https://ledgerhq.atlassian.net/browse/LIVE-14442
---
- **The code …
=> feat(web3Hub): fix state management with jotai

.changeset/shaggy-meals-rescue.md, apps/ledger-live-desktop/src/renderer/components/CustomImage/CustomLockScreenDeviceAction/index.tsx
- ...
LLD will retry CLS installation on Stax and Flex after locking & unlocking device while CLS image is being uploaded
- **JIRA or GitHub link**: [LIVE-13238](https://ledgerhq.atlassian.net/browse/LIVE-13238)
--- …
=> fix(LLD): Retry CLS installation after locking & unlocking device

.changeset/long-meals-laugh.md, apps/ledger-live-desktop/src/renderer/components/TopBar/ActivityIndicator.tsx, apps/ledger-live-desktop/src/renderer/reducers/accounts.ts, apps/ledger-live-desktop/src/renderer/reducers/wallet.ts, apps/ledger-live-desktop/static/i18n/en/app.json, libs/ledger-live-common/src/bridge/react/useAccountSyncState.ts
- ActivityIndicator, isUpToDateSelector, usemaybeaccountname, useaccountsyncstate
in purpose to add a more readable UI inside sync tooltips we will display all the accounts that failed to sync (not update to date / not supported ). For this I've added batch hook to find all the account names
https://github.com/user-attachments/assets/a1718467-0ca8-42fe-b02f-c401aebf28d5
- **JIRA or GitHub link**: [LIVE-14060](https://ledgerhq.atlassian.net/browse/LIVE-14060)
--- …
=> :sparkles:(lld): change sync error tooltip to be more readable

.changeset/fresh-dolls-sin.md, apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/CompleteExchange/Body.tsx, apps/ledger-live-desktop/tests/specs/services/wallet-api.spec.ts
- ...
https://github.com/user-attachments/assets/4fe71777-034f-4c34-9f64-260f99af1500
---
=> [Fix/LIVE-14247]: close banner after calling on cancel when disabled broadcast is enabled.

.github/workflows/build-and-test-external.yml, .github/workflows/build-and-test-pr.yml, .github/workflows/build-desktop-reusable.yml, .github/workflows/build-mobile-reusable.yml, .github/workflows/test-desktop-external-reusable.yml
- ...
This PR brings minor improvement to the CI:
- Restore Build checks 
- Improve fork check expression (thanks @valpinkman)
- Avoid uploading screenshots diff to S3 for external contributions (https://github.com/LedgerHQ/ledger-live/actions/runs/11328879823/job/31506869094?pr=7880)
--- …
=> Improve CI master workflow

apps/ledger-live-desktop/tests/page/portfolio.page.ts, apps/ledger-live-desktop/tests/specs/speculos/add.account.spec.ts
- ...
Adding minor check on Add account
- **JIRA or GitHub link**: [https://ledgerhq.atlassian.net/jira/software/c/projects/QAA/boards/887?selectedIssue=QAA-304](QAA-304)
---
=> 🩹 [QAA-304] Adding check for operation history when adding an account

.changeset/thirty-ants-report.md, libs/ui/packages/native/src/components/Form/Input/AnimatedInputSelect/Select.tsx, libs/ui/packages/native/src/components/Form/Input/AnimatedInputSelect/index.tsx, libs/ui/packages/native/src/components/Form/Input/index.ts, libs/ui/packages/native/storybook/stories/Form/Input/AnimatedInputAndSelect.stories.tsx
- ...
New component [FIgma](https://www.figma.com/design/n5044zBaOWyNMFVYhcCZsW/Send?node-id=3536-4031&node-type=frame&t=b53UpXK7gzavqqoU-0) for MemoTag in LLM
https://github.com/user-attachments/assets/54551336-9a0d-4438-a3f9-890a9f159362
--- …
=> feat: 💄 Add new AnimatedInputSelect in DS

.changeset/breezy-deers-scream.md, apps/ledger-live-mobile/src/index.tsx, apps/ledger-live-mobile/src/iosWebsocketFix.ts
- iOS websocket usage (Solana/send)
Our proxy for Solana is blocking the connection when no user-agent is provided
We are adding the missing user-agent header on the websocket for iOS with RN
We need to use the interceptor as we don't control the code initiating the websocket
Updating the [options passed in by the interceptor](https://github.com/facebook/react-native/blob/3dfe22bd27429a43b4648c597b71f7965f31ca65/packages/react-native/Libraries/WebSocket/WebSocketInterceptor.js#L148-L163) works fine
Another solution could be to use pnpm to patch [react native WebSocket](https://github.com/facebook/react-native/blob/3dfe22bd27429a43b4648c597b71f7965f31ca65/packages/react-native/Libraries/WebSocket/WebSocket.js)
But the interceptor seems lean enough and a simple hack vs patching a lib seems …
=> fix(iOS): Solana error after broadcast on WebSockets [LIVE-14585]

.changeset/slow-dingos-type.md, apps/ledger-live-desktop/src/main/window-lifecycle.ts
- ...
Added event listeners to handle the selection, addition, removal, and permission management of HID devices within ldmk integration
- **JIRA or GitHub link**: [DSDK-509](https://ledgerhq.atlassian.net/browse/DSDK-509)
--- …
=> feat(lld): added window lifecycle event listeners for ldmk transport

.changeset/great-forks-sip.md, libs/env/src/env.ts
- ...
Due to some errors related to explorers, we need to rollback some NFTs support, we only activate for AVAX & BSC
Waiting for [https://ledgerhq.atlassian.net/browse/LIVE-14648 ](https://ledgerhq.atlassian.net/browse/LIVE-14648) to be done to continue activating more EVM
--- …
=> chore: 🔧 Enable only AVAX & BNB NFTs support

apps/ledger-live-desktop/src/newArch/features/WalletSync/__tests__/synchronize.test.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Synchronize/03-PinCodeStep.tsx, apps/ledger-live-desktop/tests/handlers/index.ts, libs/hw-ledger-key-ring-protocol/src/ApduDevice.ts, libs/hw-ledger-key-ring-protocol/src/CommandBlock.ts, libs/hw-ledger-key-ring-protocol/src/CommandStream.ts, libs/hw-ledger-key-ring-protocol/src/Crypto.ts, libs/hw-ledger-key-ring-protocol/src/Device.ts, libs/hw-ledger-key-ring-protocol/src/NobleCrypto.ts, libs/hw-ledger-key-ring-protocol/src/StreamTreeCipher.ts, libs/hw-ledger-key-ring-protocol/src/__tests__/codec.ts, libs/ledger-key-ring-protocol/src/qrcode/cipher.test.ts, libs/ledger-key-ring-protocol/src/qrcode/cipher.ts, libs/ledger-key-ring-protocol/src/qrcode/index.ts, libs/ledger-key-ring-protocol/src/sdk.ts, libs/ledger-key-ring-protocol/tests/test-helpers/recordTrustchainSdkTests.ts, libs/ledger-key-ring-protocol/tests/test-helpers/replayTrustchainSdkTests.ts
- ...
I fixed the integration test for QR Code sync flow on LLD.
I also fixed async/await usage on Ledger Key Ring Protocol libraries
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-14524
---
=> LLD - Fix LS QR Code integration test

.changeset/tiny-cobras-refuse.md, libs/ledger-live-common/src/hw/actions/startExchange.ts
- Swap eth (no regression expected as we only add the Eth app in the deps)
Install Ethereum app if at least one evm family in the swap and the app is not already present in the deps
Avalanche needs the Ethereum app for the swap but we reference the Avalanche app in the cryptoassets lib, meaning if we don't have the Ethereum app already installed we end up with an error
- **JIRA or GitHub link**: [LIVE-14666]
--- …
=> fix(swap): install Ethereum app if at least one evm family in the swap and not already present in the deps [LIVE-14666]

.changeset/big-lions-refuse.md, apps/ledger-live-mobile/src/analytics/SegmentSetup.tsx, apps/ledger-live-mobile/src/analytics/segment.ts, apps/ledger-live-mobile/src/analytics/useFlushInBackground.tsx
We call the segment flush method when we detect that LLM goes in the background to send the events are to segment during the same session (without having to wait for the user to open the app again before sending them)
| Android        | iOS         |
| https://github.com/user-attachments/assets/d092480a-925a-42e5-8ae4-64ad7619a756 | https://github.com/user-attachments/assets/587ed072-62fa-4db9-b80d-a9ee983cc614 |
- **JIRA or GitHub link**: [LIVE-14590]
---
- **The …
=> :chart_with_upwards_trend: LLM - Flush analytics events when putting the app in background

.changeset/purple-peaches-cross.md, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/locales/en/common.json
Update Analytics Opt In Prompt Wording to make sure we do not mention "tracking" as it causes a quiproquo with Apple's `App Tracking Transparency Policy`.
- **JIRA or GitHub link**: [LIVE-14689] 
---
[LIVE-14689]: …
=> :speech_balloon: LLM / LLD - Update Analytics Opt In Prompt wording

.changeset/eighty-geckos-smash.md, apps/ledger-live-desktop/src/config/urls.ts, apps/ledger-live-desktop/src/renderer/modals/Send/steps/StepConfirmation.tsx, apps/ledger-live-mobile/src/components/RootNavigator/SendFundsNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/types/SendFundsNavigator.ts, apps/ledger-live-mobile/src/const/navigation.ts, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/logic/screenTransactionHooks.ts, apps/ledger-live-mobile/src/newArch/components/Collapsible/index.tsx, apps/ledger-live-mobile/src/newArch/components/CopyButton/index.tsx, apps/ledger-live-mobile/src/screens/SendFunds/07-SendBroadcastError.tsx, apps/ledger-live-mobile/src/utils/urls.tsx, libs/ledger-live-common/src/errors/transactionBroadcastErrors.ts, libs/ui/packages/native/src/components/cta/Button/index.tsx
- ...
Display human readable errors when the send flow fails.
https://github.com/user-attachments/assets/f675aa5b-69c9-40de-92aa-f06f0c601dd9
- [LIVE-14070]
---
[LIVE-14070]: …
=> feat(llm): 🥅 display human readable errors when the send flow fails

.changeset/chilled-points-argue.md, apps/ledger-live-mobile/src/families/stellar/MemoTagInput.tsx, apps/ledger-live-mobile/src/families/stellar/MemoTypeDrawer.tsx, apps/ledger-live-mobile/src/newArch/features/MemoTag/hooks/useMemoTagInput.ts, apps/ledger-live-mobile/src/newArch/features/MemoTag/types.ts, apps/ledger-live-mobile/src/screens/SendFunds/02-SelectRecipient.tsx, libs/coin-modules/coin-stellar/src/types/bridge.ts, libs/ledger-live-common/.unimportedrc.json, libs/ledger-live-common/src/families/stellar/bridge/logic.ts, libs/ledger-live-common/src/families/stellar/bridge/mock.ts
- ...
https://github.com/user-attachments/assets/ce3ee13d-5323-4593-9ca0-59eee645fecb
Add stellar memo input and validation. Follow up of #8155.
- [LIVE-9634]
---
[LIVE-9634]: …
=> feat(llm): 📝 add Stellar memo input on the recipient selection step

.changeset/dull-plums-cheer.md, apps/ledger-live-mobile/src/families/algorand/MemoTagInput.tsx, apps/ledger-live-mobile/src/families/cardano/MemoTagInput.tsx, apps/ledger-live-mobile/src/families/casper/MemoTagInput.tsx, apps/ledger-live-mobile/src/families/cosmos/MemoTagInput.tsx, apps/ledger-live-mobile/src/families/crypto_org/MemoTagInput.tsx, apps/ledger-live-mobile/src/families/hedera/MemoTagInput.tsx, apps/ledger-live-mobile/src/families/internet_computer/MemoTagInput.tsx, apps/ledger-live-mobile/src/families/solana/MemoTagInput.tsx, apps/ledger-live-mobile/src/families/stacks/MemoTagInput.tsx, apps/ledger-live-mobile/src/families/stellar/MemoTagInput.tsx, apps/ledger-live-mobile/src/families/ton/MemoTagInput.tsx, apps/ledger-live-mobile/src/families/xrp/MemoTagInput.tsx, apps/ledger-live-mobile/src/newArch/features/MemoTag/components/GenericMemoTagInput.tsx, apps/ledger-live-mobile/src/newArch/features/MemoTag/hooks/useMemoTagInput.ts, apps/ledger-live-mobile/src/newArch/features/MemoTag/types.ts, apps/ledger-live-mobile/src/screens/SendFunds/02-SelectRecipient.tsx
- ...
The memo wasn't set correctly on Solana's transactions. This PR fixes this by changing the "patch" parameter of the "onChange" function set on `MemoInput` from an object to a `Transaction -> Transaction` function. Allowing each coin to set more complex transaction updates to set the memo.
- [LIVE-9634]
--- …
=> fix(llm): 🔧 memo input on the send flow of Solana

.changeset/few-bikes-act.md, apps/ledger-live-desktop/src/renderer/analytics/segment.ts
- ...
The `ptxSwapCoreExperiment` could have the following values: `false`, `Demo0`, `Demo3` or `Demo3Thorswap`, however, in the segment analytics, the false value makes no sense, by setting as `undefined` we don't send the flag.
[LIVE-14547](https://ledgerhq.atlassian.net/browse/LIVE-14547)
--- …
=> fix(LIVE-14547) do not set `ptxSwapCoreExperiment` as `false` in analytics

apps/ledger-live-desktop/tests/enum/Account.ts, apps/ledger-live-desktop/tests/specs/speculos/receive.address.spec.ts
=> tests: 🎭 Adding TRX account to fix broken test

.changeset/green-rice-cheer.md, .changeset/slow-buses-end.md, apps/ledger-live-mobile/src/actions/settings.ts, apps/ledger-live-mobile/src/actions/types.ts, apps/ledger-live-mobile/src/hooks/useAutoRedirectToPostOnboarding/index.ts, apps/ledger-live-mobile/src/hooks/useAutoRedirectToPostOnboarding/useOpenPostOnboardingCallback.ts, apps/ledger-live-mobile/src/hooks/useAutoRedirectToPostOnboarding/useOpenProtectUpsellCallback.ts, apps/ledger-live-mobile/src/hooks/useAutoRedirectToPostOnboarding/useShouldRedirect.test.ts, apps/ledger-live-mobile/src/hooks/useAutoRedirectToPostOnboarding/useShouldRedirect.ts, apps/ledger-live-mobile/src/logic/postOnboarding/useNavigateToPostOnboardingHubCallback.ts, apps/ledger-live-mobile/src/reducers/settings.ts, apps/ledger-live-mobile/src/reducers/types.ts, apps/ledger-live-mobile/src/screens/MyLedgerChooseDevice/index.tsx, apps/ledger-live-mobile/src/screens/Onboarding/steps/pairNew.tsx, apps/ledger-live-mobile/src/screens/Portfolio/index.tsx, apps/ledger-live-mobile/src/screens/PostOnboarding/PostOnboardingHub.tsx, apps/ledger-live-mobile/src/screens/Settings/Debug/Configuration/RecoverUpsellRow.tsx, apps/ledger-live-mobile/src/screens/Settings/Debug/Configuration/ResetOnboardingStateRow.tsx, apps/ledger-live-mobile/src/screens/Settings/Debug/Configuration/index.tsx, apps/ledger-live-mobile/src/screens/SyncOnboarding/CompletionScreen.tsx, apps/ledger-live-mobile/src/screens/SyncOnboarding/SyncOnboardingCompanion.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledger-live-common/src/hooks/recoverFeatureFlag.ts, libs/ledger-live-common/src/postOnboarding/hooks/useStartPostOnboardingCallback.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- Flex/Stax synchronous onboarding:
- With feature flag `recoverUpsellRedirection` deactivated, the onboarding flow is unchanged.
- With feature flag `recoverUpsellRedirection` activated, the "Backup for your Secret Recovery Phrase" step between Secret Recovery Phrase and Apps Installation will be hidden.
- End of the onboarding:
- With feature flag `recoverUpsellRedirection` deactivated, the post onboarding hub is opened immediately.
- With feature flag `recoverUpsellRedirection` activate, the Ledger Recover upsell is opened. When that upsell is dismissed, the user is redirected to the post onboarding hub.
**0. Prerequisite for each test**
- Reset app (Recover upsell shows only once) OR go to `Settings > Debug > Configuration` and press "Reset onboarding state".
- Go to `Settings > Debug …
=> [LLM][PROTECT-3391/3392/3393/3401/3403] Auto redirection to Recover upsell at the end of Stax/Flex onboarding

apps/ledger-live-desktop/src/newArch/features/MemoTag/components/MemoTagField.tsx, apps/ledger-live-desktop/src/renderer/modals/Send/fields/RecipientFieldBase.tsx, apps/ledger-live-desktop/tests/enum/Account.ts, apps/ledger-live-desktop/tests/enum/DeviceLabels.ts, apps/ledger-live-desktop/tests/families/algorand.ts, apps/ledger-live-desktop/tests/families/bitcoin.ts, apps/ledger-live-desktop/tests/families/cardano.ts, apps/ledger-live-desktop/tests/families/cosmos.ts, apps/ledger-live-desktop/tests/families/evm.ts, apps/ledger-live-desktop/tests/families/near.ts, apps/ledger-live-desktop/tests/families/polkadot.ts, apps/ledger-live-desktop/tests/families/solana.ts, apps/ledger-live-desktop/tests/families/stellar.ts, apps/ledger-live-desktop/tests/families/tron.ts, apps/ledger-live-desktop/tests/families/xrp.ts, apps/ledger-live-desktop/tests/page/modal/send.modal.ts, apps/ledger-live-desktop/tests/page/speculos.page.ts, apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts, libs/ledger-live-common/src/e2e/speculos.ts
- ...
Adding 10 new currencies for e2e send testing:
- Polygon
- Bitcoin cash
- Polkadot
- Algorand
- Solana
- Tron
- Stellar
- Cosmos
- Cardano
- Ripple
- **JIRA or GitHub link**: [QAA-313](https://ledgerhq.atlassian.net/browse/QAA-313) | [B2CQA-2819](https://ledgerhq.atlassian.net/browse/B2CQA-2819)
- **CI RUN**: [Run](https://github.com/LedgerHQ/ledger-live/actions/runs/11612190367)
---
- …
=> [QAA] Adding new currencies for e2e send testing

.github/workflows/sonar.yml, .github/workflows/test-design-system-reusable.yml, .github/workflows/test-integration.yml, .github/workflows/test-libs-reusable.yml, .github/workflows/turbo-affected-reusable.yml
[Ticket](https://ledgerhq.atlassian.net/browse/LIVE-14752)
Streamlines our use of the [checkout](https://github.com/actions/checkout) action so it runs as fast as possible in our workflows. Typically this is because we were checking out the entire repo with all branches and complete commit history when we only need the latest snapshot of one branch.
(⭐ = on the critical path)
✅ ⭐ `turbo-affected-reusable.yml`
**before**: 50s checkout ([workflow run](https://github.com/LedgerHQ/ledger-live/actions/runs/11632744890/job/32396487027?pr=8278))
**after**: 10s checkout (9s checkout feature branch, 1s fetch develop) ([workflow run](https://github.com/LedgerHQ/ledger-live/actions/runs/11634052124/job/32400562112?pr=8278))
(**NOTE**: https://github.com/LedgerHQ/ledger-live/pull/8279 shaves a few …
=> Optimise checkout action implementations

.changeset/lemon-news-chew.md, libs/ledger-live-common/src/exchange/platform/transfer/completeExchange.ts
=> Live 14676 card mercuryo tx doesnt work on mobile error swap 003

.changeset/neat-paws-greet.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/__tests__/useAddMember.test.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useAddMember.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useDestroyTrustchain.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useOnTrustchainRefreshNeeded.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/useQRCode.ts, apps/ledger-live-desktop/src/newArch/features/WalletSync/hooks/walletSync.hooks.ts
- ...
Track users creating and joining a Ledger keyring on LLD and test the `useAddMember` hook. The rest of the issue will be done in followup PRs.
https://github.com/user-attachments/assets/9ccad562-9ecc-46c3-9346-b6a0543a1a7a
https://github.com/user-attachments/assets/cede4d36-3a05-4927-8136-8ded54f88aab
https://github.com/user-attachments/assets/c1ffb440-9959-407e-8644-e1b195a0ce02
https://github.com/user-attachments/assets/7bea1688-9707-4503-a14e-27e33cf2d169
https://github.com/user-attachments/assets/324cb85c-8513-4a33-b1d1-576d5c9907b9
https://github.com/user-attachments/assets/3facaf6f-2fa6-4add-8f26-acef2c9a3d67
- [LIVE-14621]
--- …
=> 🔍 feat(lld): Track Ledger keyring activation/deactivation on LLD

.changeset/large-crabs-reply.md, .changeset/pink-candles-happen.md, apps/ledger-live-desktop/src/renderer/components/SignMessageConfirm/index.tsx, apps/ledger-live-desktop/src/renderer/modals/SignMessage/steps/StepSign.tsx, apps/ledger-live-desktop/src/renderer/modals/SignMessage/steps/StepSummary.tsx, apps/ledger-live-mobile/src/components/ValidateMessageOnDevice.tsx, apps/ledger-live-mobile/src/screens/SignMessage/01-Summary.tsx, libs/ledger-live-common/package.json, libs/ledger-live-common/src/families/bitcoin/ACRESetup.ts, libs/ledger-live-common/src/hw/actions/transaction.ts, libs/ledger-live-common/src/hw/signMessage/index.ts, pnpm-lock.yaml
- ACRE messageSign
messageSign used in the custom ACRE handlers now correctly passes `appName` and `dependencies` params to the connect action
I've also updated the lib and added a missing signIn handler for ACRE while testing everything with the app
- **JIRA or GitHub link**: [LIVE-14762]
--- …
=> fix(ACRE): messageSign correctly sends appName and dependencies params to the connect action [LIVE-14762]

.changeset/fuzzy-boxes-confess.md, apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx
- Deeplink analytics LLM
Add default analytics for deeplinks (keep those for PTX)
https://github.com/user-attachments/assets/d6b6fa94-12d8-46d0-9b96-c2083bc8720e
- **JIRA or GitHub link**: [LIVE-14594](https://ledgerhq.atlassian.net/browse/LIVE-14594)
--- …
=> :sparkles:(llm) add default analytics for deeplinks

.changeset/five-pianos-approve.md, libs/coin-modules/coin-evm/src/bridge/js.ts
- Cache duration between 2 CAL requests should now be 1 day and from scratch sync should be more spread across users
Increase preload cache duration to delay potential syncs from scratch
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-14781
--- …
=> [LIVE-14781] Increase preload cache duration for EVMs to 1 day

.changeset/wicked-fireants-pay.md, apps/ledger-live-desktop/src/renderer/components/TopBar/NotificationIndicator/AnnouncementPanel.tsx, apps/ledger-live-desktop/src/renderer/hooks/useDeeplinking/index.ts, apps/ledger-live-desktop/src/renderer/hooks/useDeeplinking/useDeepLinkHandler.ts, apps/ledger-live-desktop/src/renderer/hooks/useDeeplinking/utils.ts
- deeplink
- analytics
add default analytics on deeplinks. Also little rework of the hook so it's divided in 3 files (same code as before)
https://github.com/user-attachments/assets/83b057ad-f5ce-4b5f-8905-0b1e7633c7ea
- **JIRA or GitHub link**: [LIVE-14595](https://ledgerhq.atlassian.net/browse/LIVE-14595)
--- …
=> :sparkles:(lld) add default analytics for deeplinks

.changeset/shaggy-shoes-beg.md, apps/ledger-live-desktop/src/renderer/modals/TroubleshootNetwork/Body.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, libs/ledger-live-common/src/network-troubleshooting/index.ts
- LLD settings
Add missing translations for network troubleshooting modal in settings
https://github.com/user-attachments/assets/5b492611-5f39-4f43-a8bb-4039db9cd121
- **JIRA or GitHub link**: [LIVE-14829](https://ledgerhq.atlassian.net/browse/LIVE-14829)
--- …
=> :bug:(lld): missing translations for network troubleshooting

.changeset/good-boxes-boil.md, apps/ledger-live-mobile/fastlane/Fastfile
- ...
- fix build number setting to GITHUB_ENV
- The build number should be transited to slack , like android one. 
- To avoid ambiguous redirect and directory not found we need to use `tee` with a temporary variable to set the build number
https://ledgerhq.atlassian.net/browse/LIVE-14346
---
- …
=> chore: fix redirecting to GITHUB_ENV in fastfile for ios build

.changeset/tall-moons-invent.md, apps/ledger-live-mobile/src/components/RootNavigator/SwapFormNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/types/SwapFormNavigator.ts, apps/ledger-live-mobile/src/const/navigation.ts, apps/ledger-live-mobile/src/screens/Swap/LiveApp/WebView.tsx, apps/ledger-live-mobile/src/screens/Swap/LiveApp/index.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- ...
This PR aims to add conditional rendering of the swap live app under the feature flag `ptxSwapLiveAppMobile`.
By default this is disabled, when enabled the swap view will be redirected to the swap live app instead of native.
- https://ledgerhq.atlassian.net/browse/LIVE-10694
--- …
=> Feat/LIVE-10694: add webview and feature flag for swap live app view in LLM

.changeset/two-icons-jog.md, apps/ledger-live-mobile/ios/Podfile.lock, apps/ledger-live-mobile/package.json, apps/ledger-live-mobile/src/components/AssetCentricGraphCard.tsx, apps/ledger-live-mobile/src/components/CurrencyBackgroundGradient.tsx, apps/ledger-live-mobile/src/components/CurrencyHeaderLayout.tsx, apps/ledger-live-mobile/src/components/GraphCard.tsx, apps/ledger-live-mobile/src/screens/NotificationCenter/Snackbar/Snackbar.tsx, apps/ledger-live-mobile/src/screens/Platform/v2/Catalog/Layout.tsx, apps/ledger-live-mobile/src/screens/Settings/Experimental/ExperimentalHeader.tsx, libs/ui/packages/native/package.json, pnpm-lock.yaml
- reanimated
Upgrade reanimated on LLM. And replace deprecated enum. 
This fix an issue that we have on pre release too
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-14806
and fix for pre release issue https://ledgerhq.atlassian.net/browse/LIVE-14826
--- …
=> chore: upgrade react-native-reanimated to 3.16.1 - develop

.github/workflows/build-and-test-pr.yml, .github/workflows/turbo-affected-reusable.yml
No ticket - this fixes an issue [encountered](https://ledger.slack.com/archives/C03MHGMAMRQ/p1731403867731049?thread_ts=1731066157.692919&cid=C03MHGMAMRQ) in the latest release. `turbo-affected` errored because the head and base branches weren't correctly handled as variables - they were hardcoded as the PR head and `develop` during the `checkout` and `fetch` stages of `turbo-affected`. When it comes to release, the relevant branches are not the head branch and `develop`, they are the head branch and `main`. Because the `fetch` step hardcoded `develop` as the branch to fetch, `main` was not available for comparison when the turbo-affected script ran, causing an error.
This PR correctly handles the head and base branch names as variables, fixing the problem
=> fix: use correct refs for turbo-affected checkout + fetch

tools/actions/turbo-affected/src/main.ts
This is a very simple PR that shaves 2 extra seconds off the turbo-affected workflow.
The rest of the description is how it works and how I've checked that it works. But that's it.
----
One step of turbo-affected is to list the packages in the monorepo so we can get the canonical list of packages to check for changes. We do this via `pnpm list`, and currently we do so recursively (each found package is then searched for its own sub-packages, even if these are imports/not ledger-owned). This recursive step is unnecessary and adds a couple of extra seconds of pnpm searching the repo for sub-packages. We only use the top-level packages that are returned, and of those, [we only use the `name` and `path` property](https://github.com/LedgerHQ/ledger-live/blob/develop/tools/actions/turbo-affected …
=> build: only list top level packages when checking turbo affected

.changeset/few-owls-cross.md, CODEOWNERS, apps/ledger-live-desktop/src/renderer/families/evm/StakeFlowModal/component/ProviderItem.tsx, apps/ledger-live-mobile/src/families/evm/StakingDrawer/EvmStakingDrawerProvider.tsx
- Add a new staking provider to eth_staking_providers FF in firebase
- Add "name" field
- Given no translated "title", name of EVM staking provider appears as is on the list, to prevent i18n key from appearing instead.
We need to add providers faster than LL release cycle. Given that provider display names are brand names therefore not translated, fallback to the JSON-serialised "name" field from Firebase for any new provider.
Example
Expected behavior:
”Coinbase” should appear in the EVM staking modal with icon
Actual behavior:
i18n translation key stakingProviders.coinbase.title appears in the list
Note that we will only release new providers in this way after the rollout of the new EVM staking modal is 100%. …
=> fix: fall back to firebase display name if no translated title

.github/workflows/release-final.yml
Ticket [here](https://ledgerhq.atlassian.net/browse/LIVE-14836)
This allows us to perform the release-final workflow targeting an arbitrary branch. It defaults to `main` as before, but if we specify `hotfix` instead this will cause us to run the build and release processes from the hotfix branch instead, as part of the [new hotflix process](https://ledgerhq.atlassian.net/wiki/spaces/WALLETCO/pages/4710989838/LL+Incident+Recovery+-+Hotfix+in+all+cases).
This workflow is in `ledger-live` but kicks off the `release-desktop` + `release-mobile` workflows in `ledger-live-build`, which already take a ref/branch as an argument. This argument is used to specify the hotfix branch, and as such there are no changes to be made in the `ledger-live-build` repo.
This PR is based off …
=> release: make it so release-final can target the hotfix branch

.changeset/metal-walls-rush.md, apps/ledger-live-mobile/src/families/algorand/MemoTagInput.tsx, apps/ledger-live-mobile/src/families/internet_computer/MemoTagInput.tsx, apps/ledger-live-mobile/src/families/solana/MemoTagInput.tsx, apps/ledger-live-mobile/src/newArch/utils/__tests__/truncateUtf8.test.ts, apps/ledger-live-mobile/src/newArch/utils/truncateUtf8.ts, libs/ledger-live-common/.unimportedrc.json, libs/ledger-live-common/src/families/algorand/logic.ts
- ...
The issue (described in the ticket) was only on Algorand. Because the error can't be caught in a consistent way (meaning if another coin threw a similar error with slightly different wording) I decided to just truncate the memo in the input directly. For consistency I applied this UX to other coins with a limit on the memo size.
- [LIVE-14785]
--- …
=> fix(llm): ✂️ truncate some coins memo on the recipient step of the send flow

.changeset/chilly-eggs-hammer.md, apps/ledger-live-mobile/src/families/tron/accountActions.tsx
Icon for stake for Tron on the account screen was wrong, this PR fixes it.
- [Jira CN-908](https://ledgerhq.atlassian.net/browse/CN-908)
---
=> CN-908: Fix icon for staking tron on account screen

.changeset/unlucky-boats-bow.md, apps/ledger-live-desktop/src/renderer/actions/general.ts, apps/ledger-live-mobile/src/actions/general.ts, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts, libs/live-countervalues-react/src/index.tsx, libs/live-countervalues/src/api/api.ts, libs/live-countervalues/src/api/index.ts, libs/live-countervalues/src/logic.ts, libs/live-countervalues/src/types.ts
- Countervalues historical requests cache optimization
Countervalues historical requests cache optimization
Based on distribution of requested interval lengths, we can (based on current FF value):
- divide the traffic by 4 by snapping hourly requests on intervals of 2 days
- divide the traffic by 10 by snapping daily requests on intervals of 14 days
- **JIRA or GitHub link**: [LIVE-13492]  
---
- …
=> feat: ✨ Countervalues historical requests cache optimization

apps/ledger-live-mobile/ios/ledgerlivemobile.xcodeproj/xcshareddata/xcschemes/ledgerlivemobile.xcscheme
- ...
This PR solves a problem that prevented us from launching a staging version locally. 
We can refer to this thread : https://github.com/react-native-community/cli/issues/2383
In the case someone wants to test a staging build in local we need to ensure that the build can be launched on simulator / real device. 
When we run `pnpm mobile ios:staging` the build is well done but there is an Exception and the app won't open on the device 
The issue is related to the build target of xcodescheme that focused React instead of Mobile. This is because there is multiple target and by default it will select the first target 
As suggested in the github thread we can remove the React target so xcode targets Mobile. This way the app is correctly build and launch using `pnpm mobile ios:staging` 
I've …
=> :wrench:(ios) update build targets config

.changeset/blue-files-train.md, .changeset/bright-icons-explode.md, .changeset/chilly-eggs-hammer.md, .changeset/cyan-experts-raise.md, .changeset/few-owls-cross.md, .changeset/five-waves-promise.md, .changeset/good-boxes-boil.md, .changeset/long-fireants-cheer.md, .changeset/loud-pumas-fix.md, .changeset/mean-pugs-hang.md, .changeset/metal-walls-rush.md, .changeset/mighty-points-hope.md, .changeset/moody-deers-marry.md, .changeset/orange-radios-thank.md, .changeset/red-bobcats-leave.md, .changeset/rotten-months-glow.md, .changeset/seven-nails-knock.md, .changeset/shaggy-shoes-beg.md, .changeset/small-hairs-flow.md, .changeset/smart-items-laugh.md, .changeset/sour-badgers-matter.md, .changeset/sweet-needles-kiss.md, .changeset/tall-moons-invent.md, .changeset/ten-pigs-dress.md, .changeset/tiny-feet-type.md, .changeset/unlucky-boats-bow.md, .changeset/wild-chefs-smash.md, .github/workflows/changeset-enforce.yml
Adds workflow to enforce changesets version bumps at the `major` or `minor` level only (`patch` will cause build failure).
[Ticket here](https://ledgerhq.atlassian.net/browse/LIVE-14704)
This works on an entire-repo-snapshot basis, so if there are `patch`es in @develop and you've branched off @develop, and your commit does't create an offending changeset, your PR will still fail even though it wasn't your fault (this is currently the case for all tests and code quality checks too - I'm just being explicit). What this does mean is when we merge this all builds will go red until the changeset history is cleared on next release.
Note that the workflow fails with a useful error message: 
The workflow is async, and typically takes 15-20s to run:
The checkout step was optimised to only pull in …
=> [DNM] add changesets-enforce workflow

.changeset/tame-games-roll.md, .changeset/two-apricots-prove.md, apps/ledger-live-desktop/tests/page/market.page.ts, libs/coin-modules/coin-stacks/package.json, libs/coin-modules/coin-stacks/src/bridge/index.ts, libs/ledger-live-common/src/families/stacks/setup.ts
- ...
wrong import and export !
Also, fixes a playwright test: 
When trying to click the 7 day time range, we ended up clicking on dogecoin ! 
https://github.com/LedgerHQ/ledger-live/actions/runs/11897758228/job/33187953305?pr=8159 
To fix this, we now select within the time range dropdown before clicking on the element containing "7d"
--- …
=> fix: playwright, and wrong import and export

.changeset/beige-baboons-share.md, apps/ledger-live-desktop/src/renderer/drawers/NFTViewerDrawer/index.tsx, apps/ledger-live-desktop/src/renderer/drawers/OperationDetails/index.tsx, apps/ledger-live-desktop/src/renderer/modals/Send/fields/RecipientFieldDomainService.tsx, apps/ledger-live-desktop/src/renderer/modals/Send/steps/StepSummary.tsx, apps/ledger-live-desktop/src/renderer/screens/nft/Collections/Collections.tsx, apps/ledger-live-desktop/src/renderer/screens/nft/Send/Summary.tsx, apps/ledger-live-desktop/tests/enum/Account.ts, apps/ledger-live-desktop/tests/enum/DeviceLabels.ts, apps/ledger-live-desktop/tests/families/evm.ts, apps/ledger-live-desktop/tests/models/Transaction.ts, apps/ledger-live-desktop/tests/page/account.page.ts, apps/ledger-live-desktop/tests/page/drawer/nft.drawer.ts, apps/ledger-live-desktop/tests/page/drawer/send.drawer.ts, apps/ledger-live-desktop/tests/page/index.ts, apps/ledger-live-desktop/tests/page/modal/send.modal.ts, apps/ledger-live-desktop/tests/page/speculos.page.ts, apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts
- ...
Adding e2e test => User can send an NFT to an ENS address
- **JIRA or GitHub link**: [QAA-326](https://ledgerhq.atlassian.net/browse/QAA-326)
- **CI Run**: [Run](https://github.com/LedgerHQ/ledger-live/actions/runs/11857975775)
--- …
=> [QAA] Adding e2e test - User can send NFT to an ENS address

.changeset/famous-tables-mate.md, apps/ledger-live-mobile/src/analytics/segment.ts, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- FF & analytics
Add FF and analytics for Reborn II. 
- **JIRA or GitHub link**: [LIVE-14636](https://ledgerhq.atlassian.net/browse/LIVE-14636)
---
[LIVE-14636]: …
=> :triangular_flag_on_post: (llm) reborn feature flag

apps/ledger-live-desktop/README.md, libs/ledger-live-common/package.json, libs/ledger-live-common/scripts/watch-ts-es.mjs, package.json
- LLD watch for common
Follow up on https://github.com/LedgerHQ/ledger-live/pull/8365
Common watch mode would not work on common and I saw that I was also missing the watch:es for common where I thought it was not needed at first
--- …
=> chore: add missing watch:es for common

.github/workflows/release-create-hotfix.yml, .github/workflows/release-create.yml, .github/workflows/release-prerelease.yml, tools/actions/composites/adjust-changeset-level/action.yml
- Automatically upgrade `patch` changesets to `minor` in releases
- Automatically downgrade `minor` and `major` changesets to `patch` in hotfixes
The `changeset` cli itself doesn't provide any ability to modify changeset levels, so this is done via a new action that I've written.
=> force change changeset versions during release process

.changeset/ten-birds-admire.md, apps/ledger-live-mobile/src/components/RootNavigator/MainNavigator.tsx
- Label of bottom navigator for Earn changed to Yield just when in UK locale
Change label to yield for uk, earn for the rest for bottom navigator in llm.
---
=> Change label to yield for uk, earn for the rest for bottom navigator llm

.changeset/new-eels-deliver.md, apps/ledger-live-desktop/src/newArch/features/MemoTag/__tests__/MemoTagField.test.tsx, apps/ledger-live-desktop/src/newArch/features/MemoTag/components/MemoTagField.tsx, apps/ledger-live-desktop/src/newArch/features/MemoTag/constants.ts, apps/ledger-live-desktop/src/newArch/features/MemoTag/utils.ts, apps/ledger-live-desktop/src/renderer/families/casper/MemoField.tsx, apps/ledger-live-desktop/src/renderer/families/casper/SendAmountFields.tsx, apps/ledger-live-desktop/src/renderer/families/casper/SendRecipientFields.tsx, apps/ledger-live-desktop/src/renderer/families/casper/index.ts, apps/ledger-live-desktop/src/renderer/families/casper/types.ts
- ...
This work consist to support Casper send flow within the new Memo/Tag flow. 
- add MemoTag (TransferId)  field in the first step of the send flow (keeping the same label/wording)
- on feature flag off, the legacy input will be shown on the second step.
- business logic in the apps/ledger-live-desktop/src/renderer/families/casper/MemoField.tsx component is a copy for apps/ledger-live-desktop/src/renderer/families/casper/TransferId.tsx component with just an input change  in order to secure the legacy with the feature flag. -> it will be deleted on the deletion of lldMemoTag
https://github.com/user-attachments/assets/520ee418-8ee5-48eb-8bca-7d3f3c9a87a1
https://github.com/user-attachments/assets/8bf0b4c2-96db-4375-8d6c-abda3613fc15 …
=> fix: casper support on memo tag send flow

.github/workflows/release-create-hotfix.yml, .github/workflows/release-create.yml, .github/workflows/release-prerelease.yml
Fixes the error from [this comment](https://ledger.slack.com/archives/C03MHGMAMRQ/p1732551744490439?thread_ts=1732545721.321959&cid=C03MHGMAMRQ) and [associated workflow failure](https://github.com/LedgerHQ/ledger-live/actions/runs/12013943456/job/33488596218)
This was me forgetting to re-point refs to develop at the end of [the automatic changeset level control PR](https://github.com/LedgerHQ/ledger-live/pull/8406).
Unticketed
=> ci: fix old references to feature branch, re-point to @develop

.changeset/mighty-days-tan.md, libs/ledger-live-common/src/cal/partners.ts, libs/ledger-live-common/src/exchange/platform/startExchange.ts, libs/ledger-live-common/src/exchange/providers/swap.ts, libs/ledger-live-common/src/exchange/swap/completeExchange.ts, libs/ledger-live-common/src/exchange/swap/initSwap.ts
- ...
remove CDN for release issues and thorswap as DEX
---
=> feat(LIVE-14948): remove CDN for release issues and thorswap as DEX

.changeset/swift-pens-reply.md, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Manage/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/utils/errors.ts
- Stop showing an error banner in LS
When the Ledger Sync backup is deleted by another instance, we do not show the top error banner with the error message `No such trustchain ...` that was confusing for the user as he is redirected automatically to the initialization screen of LS when this happens
https://github.com/user-attachments/assets/92a4e230-f3ca-4cad-90be-0ec541f99523
- **JIRA or GitHub link**: [LIVE-14541]
--- …
=> 🐛  LLM - Stop showing useless error message in Ledger Sync when backup has been deleted

.github/workflows/test-design-system-reusable.yml, .github/workflows/test-libs-reusable.yml, .github/workflows/test-web-tools-reusable.yml
[Ticket](https://ledgerhq.atlassian.net/browse/LIVE-14750)
Migrates the first batch of workflows to `setup-caches` from `setup-toolchain`.
- test-design-system
- test-libs-reusable
- test-web-tools-resusable
To do this, we stay on the GH runners but force the proto download during `setup-caches`. This costs about 10s but overall doesn't impact run time that much as GH runners outperform ours in several I/O limited steps (e.g. checkout).
https://github.com/LedgerHQ/ledger-live/pull/8474 shows this PR with all this branch's workflows forced to run on the CI (I decided to do this in a separate PR this time to prevent a repeat of the issue we had earlier this afternoon). That PR's base is this branch, so the diffs are useful
This is a win runtime-wise. The `setup-caches` step in Test Docs is …
=> No more setup toolchain (Github runners) batch 1

.github/workflows/release-create.yml, .github/workflows/release-final-nightly.yml, .github/workflows/release-final.yml, .github/workflows/release-prepare-hotfix.yml, .github/workflows/release-prepare.yml, .github/workflows/release-prerelease.yml
Follows https://github.com/LedgerHQ/ledger-live/pull/8372, https://github.com/LedgerHQ/ledger-live/pull/8483 and https://github.com/LedgerHQ/ledger-live/pull/8484
This one implements the equivalent changes in:
- `release-create`
- `release-final-nightly`
- `release-final`
- `release-prepare-hotfix`
- `release-prepare`
- `release-prerelease`
Like the previous one, this PR also does not affect PR-build-and-test workflows.
This covers all the release based workflows. There could be conflicts with the outstanding hotfix changes.
=> No more setup toolchain (Github runners) batch 4

.github/workflows/account-migration.yml, .github/workflows/bot-portfolio-report.yml, .github/workflows/bot-super-report-custom.yml, .github/workflows/bot-super-report.yml, .github/workflows/commitlint.yml, .github/workflows/regen-doc.yml, .github/workflows/regen-pods.yml, .github/workflows/test-bridge-pr.yml, .github/workflows/test-integration-pr.yml, .github/workflows/test-integration.yml
[Ticket](https://ledgerhq.atlassian.net/browse/LIVE-14750)
Follows https://github.com/LedgerHQ/ledger-live/pull/8372 (see that for the original PR description) and https://github.com/LedgerHQ/ledger-live/pull/8483
This one implements the equivalent changes in:
- `commitlint`
- `test-bridge-pr`
- `test-integration-pr`
- `test-integration`
- `account-migration`
- `bot-portfolio-report`
- `bot-super-report-custom`
- `bot-super-report`
- `regen-doc`
- `regen-pods`
Seen as this PR does not affect PR-build-and-test workflows, the checks on this PR correctly demonstrate the effect on workflows (all green at time of writing).
This covers all the PR based workflows that are not in PR-build-and-test and are not `-external` workflows
=> No more setup toolchain (Github runners) batch 3

.github/workflows/build-desktop-reusable.yml
[This issue](https://github.com/LedgerHQ/ledger-live/actions/runs/12033482295/job/33547760487) was noticed in our live CI. This PR fixes it
The workflow for this PR is forced to run here https://github.com/LedgerHQ/ledger-live/pull/8490
=> ci: ensure proto is installed on windows builds

.changeset/many-moons-study.md, CODEOWNERS, libs/live-dmk/.unimportedrc.json, libs/live-dmk/jest.config.json, libs/live-dmk/package.json, libs/live-dmk/src/index.tsx, libs/live-dmk/src/useDeviceSessionState.test.tsx, libs/live-dmk/tsconfig.json, package.json, pnpm-lock.yaml
- ...
Created LDMK transport package
- **JIRA or GitHub link**: [DSDK-506](https://ledgerhq.atlassian.net/browse/DSDK-506)
---
[DSDK-506]: https://ledgerhq.atlassian.net/browse/DSDK-506?atlOrigin=eyJpIjoiNWRkNTljNzYxN …
=> feat: init ldmk-transport pkg

apps/cli/package.json, apps/cli/src/live-common-setup.ts, apps/ledger-live-mobile/e2e/page/common.page.ts, apps/ledger-live-mobile/e2e/page/index.ts, apps/ledger-live-mobile/e2e/setup.ts, apps/ledger-live-mobile/e2e/specs/addAccounts/addAccount.spec.ts, apps/ledger-live-mobile/e2e/specs/deeplinks.spec.ts, apps/ledger-live-mobile/e2e/specs/delegate/cosmos.spec.ts, apps/ledger-live-mobile/e2e/specs/languageChange.spec.ts, apps/ledger-live-mobile/e2e/specs/manager.spec.ts, apps/ledger-live-mobile/e2e/specs/market.spec.ts, apps/ledger-live-mobile/e2e/specs/nftGallery.spec.ts, apps/ledger-live-mobile/e2e/specs/onboarding.spec.ts, apps/ledger-live-mobile/e2e/specs/onboardingReadOnly.spec.ts, apps/ledger-live-mobile/e2e/specs/password.spec.ts, apps/ledger-live-mobile/e2e/specs/receive/currencies.spec.ts, apps/ledger-live-mobile/e2e/specs/receive/receiveFlow.spec.ts, apps/ledger-live-mobile/e2e/specs/send/currencies.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/addAccount.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/receive/receive.ts, apps/ledger-live-mobile/e2e/specs/speculos/receive/receiveBTC.spec.ts, apps/ledger-live-mobile/e2e/specs/swap/dexSwap.spec.ts, apps/ledger-live-mobile/e2e/specs/swap/swap.spec.ts, apps/ledger-live-mobile/e2e/specs/unknown-currency-resilience.spec.ts, apps/ledger-live-mobile/e2e/specs/wallet-api.spec.ts, apps/ledger-live-mobile/e2e/utils/cliUtils.ts, apps/ledger-live-mobile/package.json, libs/speculos-transport/src/index.ts, pnpm-lock.yaml
- LLM Tests
_Implement CLI in Speculos test :_
- Creating temporary userdata file for CLI modification
- Fix minor issue for handling Speculos already used when not using Docker Desktop 
- [Speculos test](https://github.com/LedgerHQ/ledger-live/actions/runs/12013805154) execution
--- …
=> [QAA-331][Detox] Implement CLI in Speculos test

.github/workflows/release-final-nightly.yml, tools/actions/composites/setup-caches/action.yml
This supersedes https://github.com/LedgerHQ/ledger-live/pull/8496 
The [release-final-nightly workflow failed](https://github.com/LedgerHQ/ledger-live/actions/runs/12042603618/job/33576546219) last night because of the migration from `setup-toolchain` to `setup-caches`, specifically [this PR](https://github.com/LedgerHQ/ledger-live/pull/8486).
In `setup-toolchain` AWS credentials inputs were optional, and their absence would cause us to skip the AWS credentials step and cache steps. In `setup-caches` these inputs are mandatory and thus AWS credentials step and cache steps are unskippable. AWS credentials step requires the `id-token: write` permission for the workflow, which wasn't in the release-final-nightly workflow - hence this all broke when we migrated.
After talking with @valpinkman …
=> Fix release-nightly by making AWS step in setup-caches optional

.changeset/silly-seals-argue.md, apps/ledger-live-desktop/src/renderer/hooks/nfts/useSyncNFTsWithAccounts.ts, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/SimpleHashTools/SpamScore/index.tsx, apps/ledger-live-mobile/src/hooks/nfts/useSyncNFTsWithAccounts.ts, libs/live-nft-react/src/hooks/__tests__/useCheckNftAccount.test.tsx, libs/live-nft-react/src/hooks/useCheckNftAccount.ts, libs/live-nft-react/src/tools/helperTests.tsx
- ...
Fix Sentry errors: 
- https://ledger.sentry.io/issues/6072870439/?project=6488660&query=release:2.92.0
- https://ledger.sentry.io/issues/6074948366/?project=6488660
---
=> bugfix: 🐛 Spam filtering errors unhandled

.changeset/swift-islands-begin.md, apps/ledger-live-desktop/src/renderer/components/BalanceInfos/index.tsx, apps/ledger-live-desktop/src/renderer/screens/dashboard/AssetDistribution/Row.tsx, apps/ledger-live-desktop/tests/page/portfolio.page.ts, apps/ledger-live-desktop/tests/page/settings.page.ts, apps/ledger-live-desktop/tests/specs/general/userParametersChange.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/settings.spec.ts
- ...
Adding E2E test : User can Select a countervalue to display amount in Ledger Live
checks:
- Counter value is correct on total balance 
- Counter value is correct on balance diff
- Counter value is correct on Asset row
- Counter value is correct on Operation row
- **JIRA or GitHub link**: [QAA-330](https://ledgerhq.atlassian.net/browse/QAA-330)
--- …
=> [QAA] Adding speculos e2e test - User can Select a countervalue

.github/workflows/account-migration.yml, .github/workflows/release-create.yml, .github/workflows/release-final.yml, .github/workflows/release-prepare-hotfix.yml, .github/workflows/release-prepare.yml, .github/workflows/release-prerelease.yml
Following https://github.com/LedgerHQ/ledger-live/pull/8505 and discussion with @valpinkman, this PR makes `account-migration` and release workflows all skip the actual caching steps when using `setup-caches`, essentially using just the install steps from that workflow. This is to more closely match how setup-toolchain was implemented before switching to `setup-caches`, and ensures we don't see more workflow failures (see https://github.com/LedgerHQ/ledger-live/pull/8505 description) in these other workflows.
=> Skip AWS credentials and cache steps in setup-caches for release workflows and account-migration

.changeset/new-bees-attack.md, apps/ledger-live-desktop/src/helpers/systemLocale.ts, apps/ledger-live-desktop/src/main/window-lifecycle.ts, apps/ledger-live-desktop/src/renderer/hooks/useGetStakeLabelLocaleBased.ts, apps/ledger-live-desktop/src/renderer/reducers/settings.ts, apps/ledger-live-desktop/src/renderer/screens/earn/index.tsx
- Change utils that detect system locale from Electron
This PR changes the Electron util that gets the system locale from the device 
- **JIRA or GitHub link**: [LIVE-15090](https://ledgerhq.atlassian.net/browse/LIVE-15090)
--- …
=> LIVE-15090: change utils from electron that detects device locale

.changeset/giant-zoos-reply.md, apps/ledger-live-desktop/src/renderer/screens/platform/LiveApp.tsx
- ...
Check if `returnTo` is defined as a string before triggering the swap analytic.
Some sections of the application do not provide a `returnTo` value.
https://github.com/user-attachments/assets/38bed508-c138-422e-a132-e03ae6e897ee
--- …
=> fix: check if returnTo is defined

.changeset/giant-zoos-reply.md, apps/ledger-live-desktop/src/renderer/screens/platform/LiveApp.tsx
- ...
Check if `returnTo` is defined as a string before triggering the swap analytic.
Some sections of the application do not provide a `returnTo` value.
https://github.com/user-attachments/assets/38bed508-c138-422e-a132-e03ae6e897ee
--- …
=> fix: check if returnTo is defined (release)

.changeset/fuzzy-cats-enjoy.md, libs/ledgerjs/packages/hw-transport-webhid/src/TransportWebHID.ts
- ...
When using two apps with the WebHID transport, both apps receive data from the inputreport event.
If the app is not active, it may store data with a different channel ID in the this.input cache.
When you return to the app, communication with the device can fail because of this invalid channel ID.
To fix this, don't throw an error for an InvalidChannel. Instead, ignore input events with a different channel ID.
- **JIRA or GitHub link**:  [LIVE-15039]
--- …
=> 🐛 (webhid): Fix invalid channel error when using multiple apps

.github/workflows/release-final-nightly.yml, .github/workflows/release-final.yml, .github/workflows/release-prerelease.yml
The nightly build was failing last night:
https://github.com/LedgerHQ/ledger-live/actions/runs/12061420704/job/33633423504
This is because authenticating with npm was inadvertently removed as part of the switch from setup-toolchain to setup-caches ([PR](https://github.com/LedgerHQ/ledger-live/pull/8486), [ticket](https://ledgerhq.atlassian.net/browse/LIVE-14750)), and that breaks the changesets package publishing step.
This PR adds a npm authentication step to the release workflows whenever we publish to npm. It uses the `setup-node` action (but only authenticates, doesn't install node), and does this in the relevant workflows, not `setup-caches`, as it's particular to release workflows.
A nightly workflow for this branch has been run …
=> Fix `release-final-nightly` npm auth

.changeset/wet-rocks-cough.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx
=> fix: stop saving fees when closing

.changeset/metal-points-destroy.md, apps/ledger-live-desktop/src/renderer/live-common-setup.ts
- lld / renderer / live-common-setup registered transports
Fix IPC transport open wrong condition which broke the transport integration.
Switch the use of the Feature Flag outside of the open method and just switch which transport is registered instead (LDMKTransport or IPCTransport, not both)
---
- …
=> 🐛 (lld): Fix ipc transport open not working

tools/actions/composites/setup-caches/action.yml
Fixes [this failing workflow](https://github.com/LedgerHQ/ledger-live/actions/runs/12065755570/job/33645253496?pr=8504)
Proto installing pnpm caused issues with knowing where the pnpm store is. Using the pnpm action fixes this. Seen as it adds an extra step, we only run this conditionally on the OS being windows and proto being installed as part of setup-caches.
See [this test PR](https://github.com/LedgerHQ/ledger-live/pull/8530) which initiates a workflow to run this PR's changes. Its workflow run (🟢) is [here](https://github.com/LedgerHQ/ledger-live/actions/runs/12072768691/job/33667539378?pr=8530)
=> Fix integration workflow failure on windows

.changeset/lovely-glasses-study.md, apps/ledger-live-desktop/src/renderer/components/SignMessageConfirm/index.tsx, apps/ledger-live-desktop/src/renderer/modals/SignMessage/steps/StepSummary.tsx, apps/ledger-live-mobile/src/components/ValidateMessageOnDevice.tsx, apps/ledger-live-mobile/src/screens/SignMessage/01-Summary.tsx
- ...
Removing message fields from the sign-message modal type Withdraw, for the specific use case of ACRE withdrawals
https://ledgerhq.atlassian.net/browse/LIVE-15014
---
=> feat(ACRE): Remove fields from the sign-message modal type withdraw

tools/actions/composites/setup-toolchain/action.yml
Reverts LedgerHQ/ledger-live#8510
Other PRs and branches still rely on setup-toolchain as they were created before the migration to setup caches. Revery now with the intention of re-merging the original PR at the end of the release cycle
=> Revert "ci: remove setup-toolchain action completely"

.changeset/odd-cooks-glow.md, apps/ledger-live-desktop/src/newArch/components/ContextMenu/createContextMenuItems.ts, apps/ledger-live-desktop/src/newArch/features/Collectibles/hooks/useOpenHideCollectionModal.ts, apps/ledger-live-desktop/src/renderer/actions/constants.ts, apps/ledger-live-desktop/src/renderer/actions/settings.ts, apps/ledger-live-desktop/src/renderer/components/ContextMenu/NFTCollectionContextMenu.tsx, apps/ledger-live-desktop/src/renderer/hooks/nfts/__tests__/useHideSpamCollection.test.ts, apps/ledger-live-desktop/src/renderer/hooks/nfts/__tests__/useNftCollectionsStatus.test.ts, apps/ledger-live-desktop/src/renderer/hooks/nfts/useHideSpamCollection.ts, apps/ledger-live-desktop/src/renderer/hooks/nfts/useNftCollections.ts, apps/ledger-live-desktop/src/renderer/hooks/nfts/useNftCollectionsStatus.ts, apps/ledger-live-desktop/src/renderer/hooks/nfts/useNftLinks.ts, apps/ledger-live-desktop/src/renderer/modals/HideNftCollection/Body.tsx, apps/ledger-live-desktop/src/renderer/modals/HideNftCollection/Footer.tsx, apps/ledger-live-desktop/src/renderer/modals/HideNftCollection/index.tsx, apps/ledger-live-desktop/src/renderer/modals/types.ts, apps/ledger-live-desktop/src/renderer/reducers/accounts.ts, apps/ledger-live-desktop/src/renderer/reducers/settings.ts, apps/ledger-live-desktop/src/renderer/screens/account/index.tsx, apps/ledger-live-desktop/src/renderer/screens/dashboard/index.tsx, apps/ledger-live-desktop/src/renderer/screens/nft/Send/SelectNFT.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Accounts/HiddenNFTCollections/index.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Accounts/HiddenNFTCollections/row.tsx, libs/live-nft-react/src/hooks/types.ts, libs/live-nft-react/src/hooks/useCheckNftAccount.ts, libs/live-nft/src/types.ts
- ...
`hiddenCollections` is now an object renamed `nftCollectionsStatusByNetwork`, containing the different contracts according to their network
3 types of status : 
- _Spam_ => Spam filter automatically adds the contract to the object
- _Whitelisted_ => User manually removes contract from hiddenCollections
- _Blacklisted_ => User manually adds contract to hiddenCollections (Hide Collection)
FF-based display (nftFromSimpleHash) : 
- If ON => display only whitelisted NFTs in addition to others 
- If OFF => Whitelisted and Spam NFTs are displayed in addition to the others
https://github.com/user-attachments/assets/22bfc1d4-a25e-437c-80f9-a5ef9abd5b6f
- **JIRA or GitHub link**: [LIVE-14976] 
---
- …
=> feat: Rework hiddenCollections to handle more easily displays

.changeset/beige-rings-move.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useLedgerSyncAnalytics.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useSpecificError.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/ManageKey/ManageKeyDrawer.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/ManageKey/useManageKeyDrawer.ts
- Ledger Sync
Improve the error message displayed when deleting backup on several instances at the same time
|![Screenshot_2024-11-25-15-12-58-61_99c1b3bb631177f8a9e1379ae5b12ffe](https://github.com/user-attachments/assets/6757bdf2-0662-49b6-8018-a5e1c5518f6c)|![Screenshot_2024-11-25-15-56-39-81_99c1b3bb631177f8a9e1379ae5b12ffe](https://github.com/user-attachments/assets/67325ab0-7641-47cb-a039-7af9b7d39e2a)|
- **JIRA or GitHub link**: [LIVE-14548]
--- …
=> 🐛  LLM - Improve Ledger Sync when backup deleted on multiple instances

.changeset/silly-cougars-rescue.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useSpecificError.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/ManageKey/ManageKeyDrawer.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/utils/errors.ts
…es to delete a backup
- Ledger Sync
Ledger Sync improved error message when an unauthorized member tries to delete a backup
- **JIRA or GitHub link**: [LIVE-14959]
---
[LIVE-14959]: …
=> 🐛  LLM - Improve Ledger Sync error when an unauthorized member tries to delete backup

.github/workflows/release-create-hotfix.yml, .github/workflows/release-final.yml, .github/workflows/release-prepare-hotfix.yml, tools/actions/composites/generate-tag/action.yml
Ticket [here](https://ledgerhq.atlassian.net/browse/LIVE-12917)
This PR implements the new hotfix process for targeting arbitrary past releases to issue a hotfix for.
A demo of the entire new process is [here](https://ledger.slack.com/archives/C07KP3A8CNA/p1730724401574429).
This modifies the *existing* create hotfix workflow to accept parameters for `version` and `application`. Specifying these values allows you to create a hotfix branch at the point of any previous release
<kbd>
</kbd>
- `version` is optional, and if unspecified defaults to "latest" - a special keyword that bypasses the tag finding process (see below), instead creating the hotfix branch from `main` just as the workflow did before this PR
- `application` is mandatory and is implemented as a `choice` dropdown with LLM and …
=> [DNM] Post-"ghost"-release hotfix workflow

.changeset/dry-rockets-hide.md, apps/ledger-live-desktop/src/renderer/actions/marketperformance.ts, apps/ledger-live-desktop/src/renderer/screens/dashboard/MarketPerformanceWidget/components/WidgetList.tsx, apps/ledger-live-desktop/src/renderer/screens/dashboard/MarketPerformanceWidget/useMarketPerformanceWidget.ts, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- x ] `npx changeset` was attached.
- ...
Display Filtered List of Top/Worst Performers Based on Swappable or Buyable Assets
- under FF
- Some differences between MarketWidget & Market (to be fixed later)
- Integrations tests will come soon
https://github.com/user-attachments/assets/52f61a74-646d-4a09-b330-4220dfcb3b71
- **JIRA or GitHub link**: [LIVE-14576]
--- …
=> feat: Display Filtered List of Top/Worst Performers Based on Swappable or Buyable Assets

.changeset/clean-olives-obey.md, apps/ledger-live-mobile/src/components/FabActions/index.tsx, apps/ledger-live-mobile/src/components/FabActions/modals/ZeroBalanceDisabledModalContent.tsx, apps/ledger-live-mobile/src/components/RootNavigator/MainNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/OnboardingNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/types/OnboardingNavigator.ts, apps/ledger-live-mobile/src/dynamicContent/useDynamicContentLogic.ts, apps/ledger-live-mobile/src/newArch/features/Reborn/components/BuyDeviceBanner/useBuyDeviceBannerModel.ts, apps/ledger-live-mobile/src/newArch/features/Reborn/constants/analytics.ts, apps/ledger-live-mobile/src/newArch/features/Reborn/hooks/useRebornFlow.ts, apps/ledger-live-mobile/src/newArch/hooks/__tests__/useFetchWithTimeout.test.ts, apps/ledger-live-mobile/src/newArch/hooks/useFetchWithTimeout.ts, apps/ledger-live-mobile/src/screens/Assets/AssetsNavigationHeader.tsx, apps/ledger-live-mobile/src/screens/Onboarding/steps/NoLedgerYetModal.tsx, apps/ledger-live-mobile/src/screens/Onboarding/steps/discoverLiveInfo.tsx, apps/ledger-live-mobile/src/screens/Platform/v2/hooks.ts
- Reborn entry points
Add reborn entry points : 
- Onboarding
- Earn tab
- My Ledger tab
- banners
- discovery apps
- add assets
- quick actions on asset page
Reborn is based on feature flag to defined what screen to render. In some cases it can happens there is nothing to render on corresponding landing page so we render the current screen. 
fallback case : 
https://github.com/user-attachments/assets/a0b89e50-27ce-41ca-ac35-eb42787150a4
best case : 
https://github.com/user-attachments/assets/92861498-fafc-495e-afc5-a37d81f43809
- **JIRA or GitHub link**: [LIVE-14945](https://ledgerhq.atlassian.net/browse/LIVE-14945)
--- …
=> :sparkles: (llm) add entry points for reborn LP variant A

.changeset/famous-mirrors-carry.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx
- ...
- When creating a new account on the swap live app interface.
- The user will attempt to swap "to" this new account.
- The user will then be unable to.
This was because the `exchangeHandlers` accounts param did not get updated when accounts were changed. Instead this PR proposes passing a getter function that will instead grab the users currents accounts when the function is run. 
https://ledgerhq.atlassian.net/browse/LIVE-15117
--- …
=> FIX/LIVE-15117: exchange.swap does not have up-to-date accounts list when attempting to swap with newly created account.

.github/workflows/test-ui-e2e-only-desktop.yml
- ...
In order to use e2e playwright / speculos tests for release testing, we need to be able to target propre firebase env
added `build_type` input for that purpose
- **JIRA or GitHub link**: /
---
=> added build_type input to target proper Firebase env

.github/workflows/turbo-affected-reusable.yml
[Ticket](https://ledgerhq.atlassian.net/browse/LIVE-15121)
Fixes _part of_ a subtle bug that makes the turbo-affected workflow identify too many packages as affected.
The `ref` that is being removed in this PR accidentally made for a bad comparison of the feature branch with `develop`: the supplied `ref` is calculated in [pr-build-and-test.yml](https://github.com/LedgerHQ/ledger-live/blob/develop/.github/workflows/build-and-test-pr.yml#L20C7-L20C18) as the latest commit in the feature branch, meaning the diffs between it and `develop` include all commits in `develop` that are not in the feature branch. That means other peoples' merged PRs.
The `ref` that we really want is the ref of the _merge commit_ github creates on creation of the pull request (`refs/pull/{PR_NUMBER}/merge`). This is …
=> ci: checkout feature branch *including merge commit* in turbo-affected

.changeset/heavy-worms-retire.md, apps/ledger-live-desktop/src/renderer/families/evm/StakeFlowModal/component/ProviderItem.tsx
Fix missing names regression in staking modal
Before:
After:
- **JIRA or GitHub link**: [CN-959](https://ledgerhq.atlassian.net/browse/CN-959)
---
[CN-959]: …
=> fix: missing names regression in staking modal

.changeset/perfect-toys-shop.md, apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/CompleteExchange/Body.tsx
- ...
This PR fixes [this one](https://github.com/LedgerHQ/ledger-live/pull/8375) adding mev protection for broadcasting. An issue where transactions were not being processed through Blink when MEV Protected was activated during an ETH swap.  
1. Ensure that the MEV Protected feature is activated for a user.  
2. Initiate a swap of ETH funds.  
The transaction should be processed through Blink.  
- **JIRA**:  https://ledgerhq.atlassian.net/browse/LIVE-15149
--- …
=> bugfix: add mev protection on swap

.changeset/lovely-vans-hug.md, apps/ledger-live-mobile/src/components/SelectDevice2/index.tsx
- My Ledger
https://github.com/user-attachments/assets/466f2c38-0875-4cb8-b194-58c1d04512f0
- **JIRA or GitHub link**: [LIVE-15218](https://ledgerhq.atlassian.net/browse/LIVE-15218?atlOrigin=eyJpIjoiNmMyZDUzMzlhOTk0NDRiY2ExNjg4Y2RlMDk0YWY1ODgiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
--- …
=> :bug: (llm) margin issue on my ledger screen

apps/ledger-live-desktop/src/renderer/components/Delegation/ValidatorRow.tsx, apps/ledger-live-desktop/src/renderer/components/LinkWithExternalIcon.tsx, apps/ledger-live-desktop/src/renderer/families/solana/shared/components/LedgerValidatorTCLink.tsx, apps/ledger-live-desktop/src/renderer/icons/Check.tsx, apps/ledger-live-desktop/tests/page/modal/delegate.modal.ts, apps/ledger-live-desktop/tests/specs/accounts/delegate.smoke.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/delegate.spec.ts
- LLD Speculos Stake tests
Following [LIVE-14413](https://ledgerhq.atlassian.net/browse/LIVE-14413), Solana stake modal change during Validator selection. This ticket adapts Speculos tests to these changes.
- [Speculos Run](https://github.com/LedgerHQ/ledger-live/actions/runs/12181851207)
--- …
=> [QAA-356][Playwright][Speculos] Fix solana stake flow

.changeset/cyan-rabbits-return.md, libs/coin-modules/coin-solana/src/utils.ts
- ...
In this [PR](https://github.com/LedgerHQ/ledger-live/pull/8563) we added another solana validator, but we didn't respect the order. The goal is to display `Ledger By Chorus One` first.
https://github.com/user-attachments/assets/5b1bc234-0694-43ce-bd46-95d2a4dda8d7
- **JIRA**: https://ledgerhq.atlassian.net/browse/LIVE-14413
--- …
=> fix: order the display of solana validators

.changeset/rude-bats-fold.md, apps/ledger-live-mobile/src/families/algorand/MemoTagInput.tsx, apps/ledger-live-mobile/src/families/stacks/MemoTagInput.tsx, libs/coin-modules/coin-stacks/src/bridge/getTransactionStatus.ts, libs/coin-modules/coin-stacks/src/contants.ts, libs/ledger-live-common/.unimportedrc.json, libs/ledger-live-common/src/families/stacks/constants.ts
- ...
Truncate Stacks memos in the input to prevent the transaction validation from failing. Follow up to #8340.
https://github.com/user-attachments/assets/b917558b-8872-44c1-962b-478e36bb20e4
- [LIVE-15164]
--- …
=> fix(llm): 🐛 fix long Memo Tag issue on Stacks

.changeset/rare-schools-happen.md, apps/ledger-live-mobile/src/families/cardano/MemoTagInput.tsx
- ...
Truncate Cardano memos in the input to prevent the transaction validation errors.
(Follow up to #8340 and #8604).
https://github.com/user-attachments/assets/cb83d90d-281a-4afb-8967-b645a50b7e2d
- [LIVE-15161]
- [LIVE-15162]
--- …
=> fix(llm): 🐛 fix long Memo Tag issue on Cardano

.changeset/brown-hats-think.md, apps/ledger-live-mobile/src/newArch/features/MemoTag/hooks/useMemoTagInput.ts
- ...
Release PR for #8632
- [LIVE-15278]
---
[LIVE-15278]: https://ledgerhq.atlassian.net/browse/LIVE-15278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(llm): 🐛 release debounce memo tag changes

.changeset/thick-peas-hear.md, apps/ledger-live-desktop/src/renderer/drawers/NFTViewerDrawer/index.tsx, apps/ledger-live-desktop/src/renderer/drawers/OperationDetails/index.tsx, apps/ledger-live-desktop/src/renderer/modals/Send/fields/RecipientFieldDomainService.tsx, apps/ledger-live-desktop/src/renderer/modals/Send/steps/StepSummary.tsx, apps/ledger-live-desktop/src/renderer/screens/nft/Collections/Row.tsx, apps/ledger-live-desktop/src/renderer/screens/nft/Gallery/TokensList/Item.tsx, apps/ledger-live-desktop/src/renderer/screens/nft/Send/Summary.tsx, apps/ledger-live-desktop/tests/models/Transaction.ts, apps/ledger-live-desktop/tests/page/account.page.ts, apps/ledger-live-desktop/tests/page/drawer/nft.drawer.ts, apps/ledger-live-desktop/tests/page/drawer/send.drawer.ts, apps/ledger-live-desktop/tests/page/index.ts, apps/ledger-live-desktop/tests/page/modal/receive.modal.ts, apps/ledger-live-desktop/tests/page/modal/send.modal.ts, apps/ledger-live-desktop/tests/page/nftGallery.page.ts, apps/ledger-live-desktop/tests/specs/speculos/nft.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts, libs/ledger-live-common/.unimportedrc.json, libs/ledger-live-common/src/e2e/enum/Account.ts, libs/ledger-live-common/src/e2e/enum/Nft.ts
- Adding e2e tests
1. Adding 3 e2e tests for NFT:
- The user displays his nft collection
- The user displays all the nfts from his account
- The user can see his NFT floor price
2. Updating Send NFT to ENS address
3. Creating NftGallery page + NFT enum
4. Adding data-testId
- **JIRA or GitHub link**: [QAA-347](https://ledgerhq.atlassian.net/browse/QAA-347)
--- …
=> [QAA-347] Adding NFT e2e tests

.changeset/giant-jobs-whisper.md, libs/coin-framework/src/account/pending.test.ts, libs/coin-framework/src/account/pending.ts
- ...
sent funds between two XRP accounts
When I click on "View details" at the end of the operation, the transaction details section on the right panel is empty.
This issue occurs on XRP when you perform a send transaction after receiving some funds. In this case, the **transactionSequenceNumber** of the **IN** transaction might be greater than that of the **OUT** transaction. As a result, it will be removed from **pendingTransaction** even though it hasn’t yet been added to **operations.**
- **JIRA or GitHub link**:  [LIVE-14771](https://ledgerhq.atlassian.net/browse/LIVE-14771)
--- …
=> fix: show the transaction details on the right panel

.changeset/hungry-moles-yawn.md, apps/ledger-live-mobile/src/newArch/features/MemoTag/components/MemoTagDrawer.tsx
- Copy of the memo drawer
The text of the drawer was the one of the receive flow which would have been misleading for users.
| ![image](https://github.com/user-attachments/assets/cd716032-5c61-4039-96e5-ecd3d7e75f77) | ![image](https://github.com/user-attachments/assets/2959f3b5-c0a7-4688-92a5-cb776fcc708f) |
[Figma for reference](https://www.figma.com/design/n5044zBaOWyNMFVYhcCZsW/Send?node-id=3097-13264)
- [LIVE-15300]
---
- …
=> fix(llm): ✍️ correct memo/tag drawer copy

apps/ledger-live-desktop/tests/fixtures/common.ts, apps/ledger-live-desktop/tests/specs/speculos/delegate.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/delete.account.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/ledgerSync.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/nft.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/receive.address.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/settings.spec.ts, apps/ledger-live-desktop/tests/utils/cliUtils.ts
- LLD Speculos tests
_Improving CLI calls on Playwright Speculos tests_
- [Speculos Run](https://github.com/LedgerHQ/ledger-live/actions/runs/12203133728)
---
=> [QAA-353][Playwright][Speculos] Improve CLI calls

.github/workflows/test-mobile-reusable.yml
This is the outcome of [this ticket](https://ledgerhq.atlassian.net/browse/LIVE-15198)
Moves LLM codechecks to ledger runners after I found that they consistently run quicker on the larger machines, by 29% on average. Here are the runtimes I observed:
| Runner Type   | Run 1  | Run 2  | Run 3  |
|---------------|--------|--------|--------|
| GitHub Runners| 6:47   | 7:29   | 10:06  |
| Ledger Runners| 5:22   | 6:19   | 5:45   |
=> ci: move LLM Codechecks to ledger runners

.github/workflows/test-mobile-reusable.yml
Code checks are failing on our self-hosting runners due to impossibility to install ruby (permission issues) .
Reverts LedgerHQ/ledger-live#8645
=> Revert "ci: move LLM Codechecks to ledger runners"

.changeset/witty-swans-share.md, apps/ledger-live-mobile/src/newArch/features/MemoTag/hooks/useMemoTagInput.ts, apps/ledger-live-mobile/src/screens/SendFunds/02-SelectRecipient.tsx
- ...
Prevent debounce from causing the memo tag not being saved.
Here's 2 example with the debounce set to 1 second for clarity:
https://github.com/user-attachments/assets/15032d30-abdb-4549-b156-0a76a69e0c3f
https://github.com/user-attachments/assets/0515bf4f-fdfb-46f7-bc29-575f96909e4c
- [LIVE-15326]
--- …
=> fix(llm): prevent debounce causing memo change miss

.changeset/witty-swans-share.md, apps/ledger-live-mobile/src/newArch/features/MemoTag/hooks/useMemoTagInput.ts, apps/ledger-live-mobile/src/screens/SendFunds/02-SelectRecipient.tsx
- ...
(Release PR for: #8652)
Prevent debounce from causing the memo tag not being saved.
Here's 2 example with the debounce set to 1 second for clarity:
https://github.com/user-attachments/assets/15032d30-abdb-4549-b156-0a76a69e0c3f
https://github.com/user-attachments/assets/0515bf4f-fdfb-46f7-bc29-575f96909e4c
- [LIVE-15326]
---
- …
=> fix(llm): release prevent debounce causing memo change miss

.changeset/seven-ravens-rest.md, apps/ledger-live-desktop/src/newArch/features/MemoTag/__tests__/MemoTagField.test.tsx, apps/ledger-live-desktop/src/newArch/features/MemoTag/components/MemoTagField.tsx, apps/ledger-live-desktop/src/renderer/families/casper/MemoField.tsx, apps/ledger-live-desktop/src/renderer/families/xrp/SendRecipientFields.tsx
This reverts commit 3a9758f7642cea56e49b45a9e36dc5c4babc57ef.
- ...
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-15143
---
- …
=> Revert "fix(lld): use a debounce on memotag field"

.changeset/funny-trains-speak.md, libs/hw-ledger-key-ring-protocol/package.json, pnpm-lock.yaml
- ...
It may fix the following Sentry error : https://ledger.sentry.io/issues/6115989813/?alert_rule_id=15006706&alert_type=issue&notification_uuid=27e565f1-802b-4dc5-88a0-906844100a0f&project=6505213&referrer=slack
- **JIRA or GitHub link**: [LIVE-15324]
--- …
=> 📌  hw-ledger-key-ring-protocol - pin tiny-secp256k1 version to 1.1.7

apps/ledger-live-desktop/tests/page/speculos.page.ts, apps/ledger-live-mobile/e2e/page/accounts/account.page.ts, apps/ledger-live-mobile/e2e/page/index.ts, apps/ledger-live-mobile/e2e/page/speculos.page.ts, apps/ledger-live-mobile/e2e/page/trade/receive.page.ts, apps/ledger-live-mobile/e2e/specs/speculos/verifyAddress/verifyAddress.ts, apps/ledger-live-mobile/e2e/specs/speculos/verifyAddress/verifyAddressATOM.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/verifyAddress/verifyAddressBCH.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/verifyAddress/verifyAddressBSC.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/verifyAddress/verifyAddressBTC.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/verifyAddress/verifyAddressDOT.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/verifyAddress/verifyAddressETH.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/verifyAddress/verifyAddressSOL.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/verifyAddress/verifyAddressTRX.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/verifyAddress/verifyAddressXRP.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/verifyAddress/verifyAddressXTZ.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/verifyAddress/verifyEmptyAddressTRX.spec.ts, apps/ledger-live-mobile/src/components/Alert.tsx, apps/ledger-live-mobile/src/components/FabActions/actionsList/account/index.tsx, apps/ledger-live-mobile/src/components/FabActions/actionsList/asset/index.tsx, apps/ledger-live-mobile/src/components/MarketQuickActions/index.tsx, apps/ledger-live-mobile/src/families/tron/ReceiveConfirmationPostAlert.tsx, apps/ledger-live-mobile/src/screens/Portfolio/PortfolioQuickActionsBar.tsx, apps/ledger-live-mobile/src/screens/ReceiveFunds/03-Confirmation.tsx, libs/ledger-live-common/src/e2e/speculos.ts, libs/ui/packages/native/src/components/cta/QuickAction/QuickActionButton/index.tsx, libs/ui/packages/native/src/components/cta/QuickAction/QuickActionList/index.tsx
- LLM Tests
- [LLM execution](https://github.com/LedgerHQ/ledger-live/actions/runs/12256183973)
- [LLD execution](https://github.com/LedgerHQ/ledger-live/actions/runs/12254567240)
--- …
=> [QAA-309][Detox][Speculos] Verify address test

.changeset/friendly-carrots-yawn.md, apps/ledger-live-mobile/src/dynamicContent/ContentCardsLocation.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/GenericLandingPage/index.tsx
- ...
Add a margin bottom to the landing pages when there is no sticky cta
- **JIRA or GitHub link**: [LIVE-15104]
---
[LIVE-15104]: https://ledgerhq.atlassian.net/browse/LIVE-15104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmN …
=> 💄  LLM - Landing Pages margin bottom

.changeset/small-jokes-work.md, apps/ledger-live-mobile/src/families/stellar/MemoTagInput.tsx
- ...
Remove invalid format error for Stellar empty hash and return type memo.
https://github.com/user-attachments/assets/6bc4d688-5af1-4d01-95c2-f5a94e28ea17
https://github.com/user-attachments/assets/6120d850-fae5-498b-85bd-8dd175093e90
- [LIVE-15314]
--- …
=> fix(llm): 🚦 do not validate empty Stellar memos

.changeset/witty-taxis-scream.md, apps/ledger-live-desktop/src/renderer/modals/Send/fields/RecipientField.tsx
- ...
- When a user fill the recipient field and change account, the revalidation wasn't triggered. This PR will fix this issue.
See the following video 
<b> Before </b>
https://github.com/user-attachments/assets/1535fba6-ec9f-4a60-8ddc-9c889911de5c
Note: in the end of the video, i was forced to delete and re-paste the casper address so that it can be revalidated via the input onChange event.
<b> After </b>
https://github.com/user-attachments/assets/3a2219af-f61c-4e38-9265-4b1aea763e84
Note: here the revalidation is controlled by both input onChange event and watching the account.id change from the selector above.
https://ledgerhq.atlassian.net/browse/LIVE-14904
---
- …
=> fix: revalidate recipient field on account change in the send flow

.changeset/curvy-parents-push.md, apps/ledger-live-desktop/src/newArch/features/DynamicContent/components/LogContentCardWrapper.tsx, apps/ledger-live-desktop/src/renderer/actions/constants.ts, apps/ledger-live-desktop/src/renderer/actions/settings.ts, apps/ledger-live-desktop/src/renderer/components/TopBar/NotificationIndicator/AnnouncementPanel.tsx, apps/ledger-live-desktop/src/renderer/hooks/useBraze.ts, apps/ledger-live-desktop/src/renderer/reducers/dynamicContent.ts, apps/ledger-live-desktop/src/renderer/reducers/settings.ts
- ...
Even when the user opt-out from analytics, it can happen that braze campaign target anonymous user via (anonymous_user_id), in this case notification impression/seen process won't be made by calling the tracking/impression request (as it's an opt-out mode). As a reinforcement layer for this scenario, LLD should support the fact that this notification is read via an store/offline indexation process. 
Content card's view state will be conditioned by braze metadata and their existence or not in the `anonymousUserNotifications` store.
https://github.com/user-attachments/assets/dbaa9816-4952-4796-a1cd-a7f0e10ab866
https://ledgerhq.atlassian.net/browse/LIVE-15007
---
- …
=> fix: add offline support for anonymous targeted user via braze notifications

.changeset/pretty-hairs-laugh.md, .changeset/weak-donkeys-think.md, apps/ledger-live-desktop/src/renderer/families/cardano/DelegationFlowModal/fields/ValidatorField.tsx, libs/coin-modules/coin-cardano/src/api/getPools.ts
- ...
Given a user who has an active delegation
When his wants to change the validator
Then clicking on ‘Show less’ does not display the selected validator no the one currently delegating
https://github.com/user-attachments/assets/dbe9841a-24d0-484f-b095-2017c7cdcf41
- **JIRA or GitHub link**: [LIVE-14501](https://ledgerhq.atlassian.net/browse/LIVE-14501)
[LIVE-14500](https://ledgerhq.atlassian.net/browse/LIVE-14500)
--- …
=> fix: display the selected validator

.github/workflows/test-mobile-e2e-reusable.yml
- ...
Fix for [[Push] Build and Test](https://github.com/LedgerHQ/ledger-live/actions/workflows/build-and-test-push.yml) which has sharding but should not.
---
=> [QAA-375][Detox][Speculos] Fix Shard for push (bis)

.github/workflows/release-final.yml
[Ticket](https://ledgerhq.atlassian.net/browse/LIVE-15427)
Fixes the issue from [this failing workflow](https://github.com/LedgerHQ/ledger-live/actions/runs/12299306845/job/34324784252#step:3:3) by correctly handling the ref as a string when triggering the ledger-live-build release workflows.
This issue was introduced by the work merged 2 weeks ago to update the hotfix process ([PR](https://github.com/LedgerHQ/ledger-live/pull/8342)). This final step of the release process was not tested due to the likelihood of accidentally creating release artefacts (such as a github release or actual new app builds etc). However this time around I did figure out how to test for these changes without accidentally creating a release and the test was set up [in this testing …
=> treat ref as string when triggering release build

apps/ledger-live-desktop/tests/page/account.page.ts, apps/ledger-live-desktop/tests/page/drawer/swap.confirmation.drawer.ts, apps/ledger-live-desktop/tests/specs/speculos/add.account.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/delegate.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/delete.account.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/ledgerSync.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/nft.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/portfolio.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/receive.address.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/settings.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/subAccount.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts, apps/ledger-live-desktop/tests/userdata/speculos-tests-app.json, apps/ledger-live-desktop/tests/utils/customJsonReporter.ts
- ...
Reactivating swap tests
---
=> [QAA] Adding and reactivating swap tests + fixing ci

.changeset/purple-beers-report.md, libs/coin-modules/coin-solana/src/utils.ts
- ...
We need to reverse the changes done to the Solana validator displayed by default in the staking flow. Figment should remain 1st and Chorus one second.
- **JIRA**: https://ledgerhq.atlassian.net/browse/LIVE-15453
--- …
=> change solana validators order

apps/ledger-live-mobile/e2e/helpers.ts, apps/ledger-live-mobile/e2e/page/common.page.ts, apps/ledger-live-mobile/src/components/BleDevicePairingFlow/BleDevicePairing.tsx, apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx, libs/ui/packages/native/src/components/Loader/InfiniteLoader/index.tsx
- LLM Manager / Onboarding Tests
_We were not waiting for the BLE Scanning loader and as react native upgrade broke iOS tests synchronisation, the open bridge message was send too soon, provoking flakiness_
--- …
=> [QAA-396][Detox] Fix flaky manager/onboarding tests

.changeset/fuzzy-forks-draw.md, apps/ledger-live-desktop/src/renderer/families/cardano/DelegationFlowModal/fields/ValidatorField.tsx, libs/coin-modules/coin-cardano/src/api/getPools.ts
- on showless we do show the selected validators (or default one if no selected)
- on showall we do show the current selected validators first and the default one right after
Show the selected validators on show less, the default one always on top or second (if we do have a current one already selected)
https://github.com/user-attachments/assets/98976f8d-bec2-4b9c-adcf-204ee93789c2
- **JIRA or GitHub link**: [LIVE-14501](https://ledgerhq.atlassian.net/browse/LIVE-14501)
--- …
=> fix: show default validators

apps/ledger-live-desktop/tests/page/asset.page.ts, apps/ledger-live-desktop/tests/page/index.ts, apps/ledger-live-desktop/tests/page/market.page.ts, apps/ledger-live-desktop/tests/page/portfolio.page.ts, apps/ledger-live-desktop/tests/page/swap.page.ts, apps/ledger-live-desktop/tests/specs/speculos/delegate.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts
- ...
Adding new Swap scenarios:
- Entry Point - Portfolio page
- Entry Point - Asset Allocation
- Entry Point - Market page - 1
- Entry Point - Market page - 2
- Entry Point - Account page
- Entry Point - left menu
- **JIRA or GitHub link**: [QAA_383](https://ledgerhq.atlassian.net/browse/QAA-383)
--- …
=> [QAA-383] Swap tests - Entry points

.changeset/nine-toes-worry.md, apps/ledger-live-mobile/src/components/RequiresCameraPermissions/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Synchronize/ScanQrCode.tsx
- ...
https://github.com/user-attachments/assets/c08b25d2-4538-496c-be70-1bb81d8dddad
https://github.com/user-attachments/assets/f5aa19bc-99ed-4428-b57b-1d85a649a310
- **JIRA or GitHub link**: [LIVE-15460]
--- …
=> fix(llm): 🎥 render camera feed right after granting access

.changeset/moody-oranges-reply.md, apps/ledger-live-desktop/src/renderer/components/BalanceInfos/index.tsx, apps/ledger-live-desktop/src/renderer/components/ContextMenu/AccountContextMenu.tsx, apps/ledger-live-desktop/src/renderer/screens/account/AccountHeaderActions.tsx, apps/ledger-live-desktop/src/renderer/screens/asset/AssetBalanceSummaryHeader.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx, apps/ledger-live-desktop/src/renderer/screens/market/hooks/useMarketActions.ts
- ...
Allow ledger-live to define an amount to swap. (Set to 0)
- https://ledgerhq.atlassian.net/browse/LIVE-14956
---
=> fix(LIVE-14956): Set a default 0 value for swap transactions

apps/ledger-live-desktop/tests/page/drawer/delegate.drawer.ts, apps/ledger-live-desktop/tests/page/drawer/send.drawer.ts, apps/ledger-live-desktop/tests/page/modal/send.modal.ts, apps/ledger-live-desktop/tests/page/speculos.page.ts, apps/ledger-live-desktop/tests/specs/speculos/delegate.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/nft.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts, libs/ledger-live-common/src/e2e/families/algorand.ts, libs/ledger-live-common/src/e2e/families/bitcoin.ts, libs/ledger-live-common/src/e2e/families/cardano.ts, libs/ledger-live-common/src/e2e/families/cosmos.ts, libs/ledger-live-common/src/e2e/families/evm.ts, libs/ledger-live-common/src/e2e/families/near.ts, libs/ledger-live-common/src/e2e/families/polkadot.ts, libs/ledger-live-common/src/e2e/families/solana.ts, libs/ledger-live-common/src/e2e/families/stellar.ts, libs/ledger-live-common/src/e2e/families/tron.ts, libs/ledger-live-common/src/e2e/families/xrp.ts, libs/ledger-live-common/src/e2e/models/Delegate.ts, libs/ledger-live-common/src/e2e/models/Swap.ts, libs/ledger-live-common/src/e2e/models/Transaction.ts, libs/ledger-live-common/src/e2e/speculos.ts
- LLD E2E Tests
_Move LLM/LLD Speculos common code_
LLD Speculos [run](https://github.com/LedgerHQ/ledger-live/actions/runs/12416690529)
---
=> [QAA-399][Speculos] Move LLM/LLD Speculos common code

.changeset/young-jeans-sparkle.md, libs/ledger-live-common/src/deposit/deposit.test.ts, libs/ledger-live-common/src/deposit/helper.ts, libs/ledger-live-common/src/deposit/mock.ts
- [] **Impact of the changes:** 
- ...
No cryptocurrency selection available in NFT gallery 'Add New' flow except Ethereum &Polygon (ex-MATIC) missing from the receive crypto search results
So we had to update `groupCurrenciesByProvider` and  to take the first crypto or token (if no currency found) of each provider to fix that
https://github.com/user-attachments/assets/b76da7d6-5a0f-4bc2-a833-ef37a3ac160a
Good POL displayed (AFTER)
https://github.com/user-attachments/assets/964419cf-c475-42c4-908e-d0fa8d97cf34
Wrong Pol (BEFORE)
https://github.com/user-attachments/assets/7a37cc96-b334-4282-aa1a-17709ca55de0
Tests 
- **JIRA or GitHub link**: [LIVE-15351] [LIVE-15381]
--- …
=> bugfix: No cryptocurrency selection available in NFT gallery 'Add New'

.changeset/stupid-starfishes-hammer.md, apps/ledger-live-mobile/src/components/AccountCard.tsx
- ...
Token listed multiple times without account details in Receive flow
https://github.com/user-attachments/assets/0a1c8b17-dbf1-4acd-9ef9-a0a879df527c
https://github.com/user-attachments/assets/9379e304-8e2a-4c3a-a06f-45ce29cc7977
- **JIRA or GitHub link**: [LIVE-15526] 
--- …
=> bugfix:  Token listed multiple times without account details in Receive flow

.changeset/pink-bats-attack.md, apps/ledger-live-desktop/tests/specs/speculos/delegate.spec.ts, libs/ledger-live-common/src/e2e/speculos.ts, libs/ledger-live-common/src/load/speculos.ts
- ...
This PR updates the method for retrieving the latest version of the app. The new implementation now takes into account the firmware version, ensuring that the app version corresponds correctly with the firmware in use.
This update fixes the timeout issue.
- **JIRA or GitHub link**: [QAA-368](https://ledgerhq.atlassian.net/browse/QAA-368)
- ci run: [Run](https://github.com/LedgerHQ/ledger-live/actions/runs/12464979636)
---
- **The PR has been tested** thoroughly, and any potential edge cases …
=> Updating method to get the last appVersion - Speculos e2e

.changeset/rotten-lamps-care.md, apps/ledger-live-desktop/src/renderer/components/OperationsList/AddressCell.tsx, apps/ledger-live-desktop/src/renderer/components/OperationsList/tests/splitAddress.test.ts
- split address
Split address didn't consider special characters that's why hedera address was strangely displayed. The bug was surely with all other coin with address containing special chars
All other addresses won't be affected since we now use a condition
This may change the splitting since we are based on the dots but Hedera might be the only to have addresses with special char in it
> [!NOTE]  
> The behaviour has been validated by Product since the split with dots of an Hedera address should be rare. And there is no other addresses like this AFAWK
|![image](https://github.com/user-attachments/assets/ea4c6fcb-314f-4a24-90f6-3a649c44bece)|![image](https://github.com/user-attachments/assets/6d4ffb11-7e68-4f7c-ad06-9de2 …
=> :bug:(lld) hedera split address

.changeset/afraid-actors-fry.md, apps/ledger-live-desktop/src/renderer/analytics/segment.ts, apps/ledger-live-desktop/src/renderer/screens/dashboard/MarketPerformanceWidget/components/Container.tsx, apps/ledger-live-desktop/src/renderer/screens/dashboard/MarketPerformanceWidget/components/WidgetList.tsx, apps/ledger-live-desktop/src/renderer/screens/dashboard/MarketPerformanceWidget/types.ts, apps/ledger-live-desktop/src/renderer/screens/dashboard/MarketPerformanceWidget/useMarketPerformanceWidget.ts
- ...
Click on MarketWidget should be under FF
https://github.com/user-attachments/assets/d989a006-45bb-4ea8-b47c-4fb69a9129de
- **JIRA or GitHub link**: [LIVE-15543] 
---
[LIVE-15543]: …
=> bugfix: Click on MarketWidget under FF

.changeset/quick-frogs-develop.md, libs/coin-framework/src/api/types.ts, libs/coin-modules/coin-polkadot/src/logic/listOperations.ts, libs/coin-modules/coin-stellar/src/bridge/buildOptimisticOperation.ts, libs/coin-modules/coin-stellar/src/logic/listOperations.ts, libs/coin-modules/coin-stellar/src/network/horizon.ts, libs/coin-modules/coin-stellar/src/network/serialization.ts, libs/coin-modules/coin-stellar/src/types/bridge.fixture.ts, libs/coin-modules/coin-stellar/src/types/bridge.ts, libs/coin-modules/coin-tezos/src/api/index.integ.test.ts, libs/coin-modules/coin-tezos/src/logic/listOperations.ts, libs/coin-modules/coin-tezos/src/network/tzkt.ts, libs/coin-modules/coin-xrp/src/api/index.test.ts, libs/coin-modules/coin-xrp/src/api/index.ts, libs/coin-modules/coin-xrp/src/bridge/synchronization.test.ts, libs/coin-modules/coin-xrp/src/bridge/synchronization.ts, libs/coin-modules/coin-xrp/src/logic/listOperations.test.ts, libs/coin-modules/coin-xrp/src/logic/listOperations.ts, libs/coin-modules/coin-xrp/src/network/index.ts, libs/coin-modules/coin-xrp/src/network/types.ts, libs/coin-modules/coin-xrp/src/types/model.ts
- an extra field named `block` on the `Operation` object returned by the coin framework for `stellar`, `tezos` and `xrp`
Update `listOperations` for the coins module `stellar`, `tezos` and `xrp`. This change is needed because we need extra information about the block for each operation (the time and the hash of the block)
--- …
=> [Alpaca] Add block hash and timestamp

.changeset/loud-masks-relate.md, apps/ledger-live-mobile/ios/LaunchScreen.storyboard, apps/ledger-live-mobile/ios/ledgerlivemobile/AppDelegate.mm, apps/ledger-live-mobile/ios/ledgerlivemobile/Info.plist
- IOS config
Fix IOS splashscreen. It wasn't working due to missconfig. 
In dev there is a little white/black screen after the launchscreen due to metro loading
We can't use RNSplashScreen since there is known issue with detox. Also it looks quite better to handle this in the native part. 
It doesn't look perfect but this will be reworked a day. So for the moment I leave the existing one what it's better than just a white or black screen
https://github.com/user-attachments/assets/de0a66d2-9ca3-48a5-8a04-bb18954fbacb
- **JIRA or GitHub link**: [LIVE-13154](https://ledgerhq.atlassian.net/browse/LIVE-13154)
--- …
=> fix :bug:(llm) ios splashscreen

apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/locales/en/common.json, libs/ledger-live-common/src/families/aptos/errors.ts, libs/ledger-live-common/src/families/aptos/getTransactionStatus.test.ts, libs/ledger-live-common/src/families/aptos/getTransactionStatus.ts
- ...
Add more unit tests to aptos integration
---
=> test(aptos): improve unit tests

.changeset/honest-badgers-develop.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/Swap/LiveApp/WebView.tsx, apps/ledger-live-mobile/src/screens/Swap/LiveApp/index.tsx
- ...
- navigate to error screen if live app is at /unknown-error
https://ledgerhq.atlassian.net/browse/LIVE-10697
---
=> feat: add error page for LLM

.changeset/stale-penguins-tap.md, apps/ledger-live-desktop/tests/specs/services/wallet-api.spec.ts-snapshots/wallet-api-currencies-darwin.json, apps/ledger-live-desktop/tests/specs/services/wallet-api.spec.ts-snapshots/wallet-api-currencies-linux.json, libs/ledgerjs/packages/cryptoassets/src/currencies.ts
- ...
This PR update `rsk` network name to `Rootstock`.  
Branding update: https://rootstock.io/
https://dev.rootstock.io/
Explorer: https://explorer.rootstock.io/ 
Purpose of this PR is just to change the rsk network name to Rootstock without changing underline configurations which were done using rsk as network id. So network id will remains the same. So this will not cause any breaking changes as the network id will be same. 
--- …
=> Update `rsk` network name to `Rootstock`

.changeset/calm-waves-battle.md, .changeset/real-eagles-scream.md, apps/ledger-live-desktop/src/renderer/components/FirebaseFeatureFlags.tsx, apps/ledger-live-desktop/src/renderer/live-common-setup.ts, apps/ledger-live-mobile/src/components/FirebaseFeatureFlags.tsx, libs/ledger-live-common/src/e2e/index.ts, libs/ledger-live-common/src/featureFlags/firebaseFeatureFlags.ts
- Device interactions should work fine with:
- with Ledger Device Management Kit disabled
- with Ledger Device Management Kit enabled (`ldmkTransport` feature flag)
- Speculos
**Sentry issue: https://ledger.sentry.io/issues/6147489966/?project=6488660&query=release:2.94.0**
Two things:
- `getFeature` return type was `any`, which allowed an error to slip through: checking the value of `null.enabled`.
- this was happening only in some cases, because of a race condition between:
- the initialization of Firebase
- the registration of transport modules
The result is a crash that would have looked like this for a user:
**The fix:**
- typing `getFeature` to return `Feature | null`.
- all transport modules are registered at initialization, with a more dynamic logic to choose which transport to …
=> [DSDK-620] Fix LLD crash (race condition in transport registration)

libs/ledger-live-common/src/exchange/providers/swap.integration.test.ts, libs/ledger-services/cal/src/partners/default.ts
=> chore: tests

.changeset/curvy-hornets-wink.md, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Synchronize/ScanQrCode.tsx
- LS qr code scanner
The app crashed when we wanted to use the camera
- **JIRA or GitHub link**: [LIVE-15550](https://ledgerhq.atlassian.net/browse/LIVE-15550)
---
[LIVE-15550]: …
=> fix :bug:(llm) qr code scanner crash

.github/workflows/generate-screenshots.yml, tools/actions/composites/update-snapshots-desktop/action.yml
Ticket [here](https://ledgerhq.atlassian.net/browse/LIVE-14389)
Uses the [ghcommit action](https://github.com/planetscale/ghcommit-action) to make a verified commit for the generated screenshots.
In this PR we replace our manual git commands for creating a commit with the ghcommit action, which makes a request to the Github API to create a commit instead. In this PR we use that action, but provide the `GITHUB_TOKEN` to authenticate the request. The `GITHUB_TOKEN` is locally scoped to just that workflow run (i.e. short lived), and is generated by Github. When Github receives the request it parses the `GITHUB_TOKEN` and recognises the commit as originating from the repo's own actions, marking it as Verified on this basis. Verification that the commit is generated within the repo's actions …
=> In `generate-screenshots` workflow, use commit action for generating signing commits

apps/ledger-live-desktop/src/renderer/components/debug/DisableTransactionBroadcastWarning.tsx, apps/ledger-live-desktop/tests/specs/speculos/ledgerSync.spec.ts, apps/ledger-live-desktop/tests/userdata/erc20-0-balance.json, apps/ledger-live-desktop/tests/userdata/ledgerSync.json, apps/ledger-live-desktop/tests/userdata/skip-onboarding.json, apps/ledger-live-desktop/tests/userdata/speculos-subAccount.json
- ...
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/QAA-354
--- …
=> [QAA-354] playwright e2e speculos tests with Prod env

.changeset/hot-taxis-explain.md, apps/ledger-live-mobile/src/components/NavigationHeaderBackButton.tsx, apps/ledger-live-mobile/src/components/RootNavigator/AccountsNavigator.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/Navigator.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AddAccountButton/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/enums.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AccountsList/index.tsx, apps/ledger-live-mobile/src/newArch/features/Assets/screens/AssetsList/index.tsx, apps/ledger-live-mobile/src/screens/WalletCentricAsset/index.tsx
- Analytics of new accounts list
- Navigator header go back component
Add analytics for the new accounts list scope. 
Please refer to Jira task to review all the needed analytics
https://github.com/user-attachments/assets/f6470339-0d32-4bf9-990d-0e6865020c84
- **JIRA or GitHub link**: [LIVE-15618](https://ledgerhq.atlassian.net/browse/LIVE-15618)
--- …
=> feat :chart_with_upwards_trend: (llm): add analytics for new accounts list

.changeset/clever-tables-draw.md, .changeset/young-bottles-flow.md, apps/ledger-live-mobile/ios/Podfile.lock, apps/ledger-live-mobile/package.json, libs/ledgerjs/packages/react-native-hw-transport-ble/package.json, libs/ledgerjs/packages/react-native-hw-transport-ble/src/BlePlxManager.ts, libs/ledgerjs/packages/react-native-hw-transport-ble/src/BleTransport.ts, pnpm-lock.yaml
- ...
- Extract Ble plx instance to a specific class in @ledgerhq/react-native-hw-transport-ble
- Added missing promise awaiting 
- Update react-native-ble-plx to 3.2.1
- **JIRA or GitHub link**: [LIVE-15119] 
--- …
=> :bug: (rn-ble) [ACRE]: Device disconnected error when trying to sign in on Acre

.changeset/poor-students-kick.md
- ...
Just adds the missing changeset for #8870
---
=> chore: add changeset for #8870

.changeset/poor-students-kick.md, apps/ledger-live-mobile/src/dynamicContent/brazeContentCard.ts, apps/ledger-live-mobile/src/dynamicContent/useDynamicContent.tsx, apps/ledger-live-mobile/src/dynamicContent/useDynamicContentLogic.ts
- ...
Fix the braze related performance issue introduced by #8576.
This fix was already merged into the release branch by #8870.
- [LIVE-15674](https://ledgerhq.atlassian.net/browse/LIVE-15674)
- [LIVE-15681](https://ledgerhq.atlassian.net/browse/LIVE-15681)
--- …
=> fix(llm): ⚡️ fix braze related performance issues

apps/ledger-live-mobile/e2e/helpers.ts, apps/ledger-live-mobile/e2e/page/nft/nftViewer.page.ts, apps/ledger-live-mobile/e2e/page/wallet/nftGallery.page.ts, apps/ledger-live-mobile/e2e/page/wallet/portfolio.page.ts, apps/ledger-live-mobile/e2e/page/wallet/walletTabNavigator.page.ts, apps/ledger-live-mobile/e2e/specs/speculos/ledgerSync/ledgerSync.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/nftGallery.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/verifyAddress/receiveFlowETH.spec.ts, apps/ledger-live-mobile/package.json, apps/ledger-live-mobile/src/components/Nft/NftGallery/NftList.tsx
- LLM Speculos test
- Adapting the exisiting nftGallery test with Speculos
- Fixing test matcher to add tests directly in speculos folder
-  fix tron tests timeout with addition to detoxURLBlacklistRegex
- adding known bugs to allure report
- Speculos [run](https://ledger-live.allure.green.ledgerlabs.net/allure/reports/743990a7-1424-49bc-a04e-2f4d9921e2ee/)
--- …
=> [QAA-307][Detox][Speculos] Adap nft gallery tests

libs/coin-modules/coin-xrp/package.json, libs/coin-modules/coin-xrp/src/api/index.ts, libs/coin-modules/coin-xrp/src/bridge/synchronization.ts, libs/coin-modules/coin-xrp/src/logic/listOperations.test.ts, libs/coin-modules/coin-xrp/src/logic/listOperations.ts, libs/coin-modules/coin-xrp/src/network/index.ts
Follow up of [@ae713b20c1da18ef33beb730f41fb3ea2990e44](https://github.com/LedgerHQ/ledger-live/commit/2ae713b20c1da18ef33beb730f41fb3ea2990e44)
Fix 2 issues:
1. gracefully handle case where no results are returned (npe)
2. iterate properly over pages (some txs were skipped)
Refactored the code to be a bit less mutable.
=> [Coin-Module] Fix XRP pagination issue

.changeset/afraid-falcons-eat.md, apps/ledger-live-desktop/src/renderer/components/TransactionConfirm/ConfirmFooter.tsx, apps/ledger-live-desktop/src/renderer/components/TransactionConfirm/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, libs/ledger-live-common/src/exchange/providers/swap.ts
=> feat: Uniswap's term's of use

.changeset/bright-cooks-breathe.md, apps/ledger-live-mobile/src/families/solana/accountActions.tsx, libs/coin-framework/src/account/helpers.test.ts, libs/coin-framework/src/account/helpers.ts
- click on earn button must work excepte for empty accounts.
- Go to Earn on LLM
- If you have some SOL you should be able to go on stake page when clicking on earn.
Uploading Screen Recording 2024-12-23 at 16.22.27.mov…
- **JIRA or GitHub link**: [LIVE-15273](https://ledgerhq.atlassian.net/browse/LIVE-15273)
--- …
=> fix: earn on llm

.changeset/five-waves-attend.md, apps/ledger-live-mobile/src/screens/Portfolio/PortfolioAssets.tsx, apps/ledger-live-mobile/src/screens/Portfolio/__integrations__/portfolioAssets.integration.test.tsx
- new accounts list add account
Change add account button apparition on portfolio screen with the new accounts list
Update inte test in consequence 
No button on assets list if less than 5 assets 
See all assets if equal or more than 5 assets
Add account button on accounts list
See all accounts button if equal or more than 5 accounts
If nothing default add account button
- **JIRA or GitHub link**: [LIVE-15678](https://ledgerhq.atlassian.net/browse/LIVE-15678) 
--- …
=> feat :lipstick:(llm): change add accounts button logic

.github/workflows/test-mobile-e2e-reusable.yml, .github/workflows/test-ui-e2e-only-desktop.yml, tools/actions/composites/setup-e2e-broadcast/action.yml
- Speculos tests broadcast
Broadcast for scheduled Speculos runs is broken because github.event.schedule.cron seems not available in composite actions. Passing schedule_cron as input to set-broadcast action to fix this. 
- Detox [run](https://github.com/LedgerHQ/ledger-live/actions/runs/12762368727)
- Playwright [run](https://github.com/LedgerHQ/ledger-live/actions/runs/12762370494)
---
- **Any …
=> [Speculos][Playwright][Detox] Fixing scheduled run broadcast

.changeset/wicked-camels-joke.md, apps/ledger-live-mobile/src/screens/ReceiveFunds/01-SelectCrypto.tsx
- ...
Deeplinks entrypoint for receive flow is a SelectCrypto component that intercepts the currency, fetch for a potential network provider via `useGroupedCurrenciesByProvider` common hook  and then perform an explicit navigation to the network page if there is more than 1 network. 
This processing occurs actually on a useEffect level: 
```
useEffect(() => {
if (paramsCurrency) {
const selectedCurrency = findCryptoCurrencyByKeyword(paramsCurrency.toUpperCase());
if (selectedCurrency) {
onPressItem(selectedCurrency);
}
}
}, [onPressItem, paramsCurrency]);
````
What's happening is if the user has already scanned a network based currency before, the first effect that will trigger the `onPressItem(selectedCurrency)` wont wait for  `useGroupedCurrenciesByProvider` result, and while …
=> fix: wait for providers parsing process before pressing on crypto item in receive flow

apps/ledger-live-desktop/src/renderer/drawers/OperationDetails/index.tsx, apps/ledger-live-desktop/tests/component/drawer.component.ts, apps/ledger-live-desktop/tests/page/drawer/operation.drawer.ts, apps/ledger-live-desktop/tests/page/index.ts, apps/ledger-live-desktop/tests/specs/services/ethereumStaking.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/add.account.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/delegate.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/ledgerSync.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/nft.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts
- ...
- **JIRA or GitHub link**: [Ticket to automate](https://ledgerhq.atlassian.net/browse/B2CQA-2073)
--- …
=> [QAA] adding checks - B2CQA-2073

.changeset/pretty-boats-cry.md, apps/ledger-live-mobile/src/screens/Account/hooks/useAccountActions.tsx
- walletState passed from useAccountActions to decorator
This PR fixes a bug where the walletState that was introduced on the accountActions was not passed from the account screen.
https://github.com/user-attachments/assets/6c17e324-29dc-461e-b6eb-4a382e7e50b9
- **JIRA or GitHub link**: [JIRA-15628](https://ledgerhq.atlassian.net/browse/LIVE-15786)
--- …
=> FIX: LIVE-15628 Fix app crashing when selecting EVM accounts

.github/workflows/test-mobile-e2e-reusable.yml, .github/workflows/test-mobile-e2e.yml, apps/ledger-live-mobile/.env.mock.prerelease, apps/ledger-live-mobile/android/app/build.gradle, apps/ledger-live-mobile/android/app/src/detoxPreRelease/google-services.json, apps/ledger-live-mobile/detox.config.js, apps/ledger-live-mobile/scripts/e2e-ci.mjs
- Detox tests and CI
_In order to test pre-release builds we need to add the possibility to run tests targeting firebase production env._
- Detox mocked [run](https://github.com/LedgerHQ/ledger-live/actions/runs/12784181044)
- Detox Speculos production [run](https://github.com/LedgerHQ/ledger-live/actions/runs/12784184411)
---
- …
=> [QAA-425][Detox][Speculos] Add possibility to target production firebase env

.github/workflows/generate-screenshots.yml, tools/actions/composites/update-snapshots-desktop/action.yml
To fix [this issue](https://ledger.slack.com/archives/C05J8CKP88G/p1736960394684999), this PR adds a docker authentication step prior to calling the ghcommit verified commits action during generate-screenshots.
This PR is tested in [this test branch](https://github.com/LedgerHQ/ledger-live/pull/8920), which has the successful workflow run [here](https://github.com/LedgerHQ/ledger-live/actions/runs/12807237858/job/35707513011) 🟢.
=> Authenticate with docker before running ghcommit action

.changeset/clean-moose-kick.md, libs/coin-modules/coin-evm/src/__tests__/coin-tester/indexer.ts, libs/coin-modules/coin-evm/src/__tests__/unit/synchronization.unit.test.ts, libs/coin-modules/coin-evm/src/api/explorer/etherscan.ts, libs/coin-modules/coin-evm/src/api/explorer/index.ts, libs/coin-modules/coin-evm/src/api/explorer/none.ts, libs/coin-modules/coin-evm/src/config.ts
- Prevent non supported requests on blockscout for ERC-1155 NFTs leading to errors during sync
- Allow for `none` explorer type in coin config to allow for node-only sync
Now prevents requests to Blockscout for ERC-1155 transfer events as the endpoint isn't supported for now. Also adds a new explorer type for coin-config `none`, allowing to sync an account with purely a node (although, all token accounts will disappear for the user).
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/LIVE-14648
--- …
=> [LIVE-14648] Feature - Prevent ERC-1155 calls for Blockscout explorer & authorize node-only sync

.changeset/kind-buttons-lay.md, apps/ledger-live-desktop/src/renderer/components/WebPlatformPlayer/CustomHandlers.ts, apps/ledger-live-desktop/src/renderer/modals/SignMessage/Body.tsx, apps/ledger-live-desktop/src/renderer/modals/SignMessage/steps/StepSign.tsx, apps/ledger-live-desktop/src/renderer/modals/SignMessage/types.ts, apps/ledger-live-mobile/src/components/RootNavigator/types/SignMessageNavigator.ts, apps/ledger-live-mobile/src/components/WebPlatformPlayer/CustomHandlers.ts, apps/ledger-live-mobile/src/screens/SignMessage/03-ConnectDevice.tsx, libs/ledger-live-common/src/hw/actions/transaction.ts, libs/ledger-live-common/src/hw/signMessage/index.ts
- wallet-api ACRE flows
Added back the account for the connect action even with an appName present as we should still keep it
And only bypass the derivation check on LL for ACRE flows
- **JIRA or GitHub link**: [LIVE-15787]
--- …
=> fix(wallet-api): only bypass derivation check on LL for ACRE flows [LIVE-15787]

apps/ledger-live-desktop/tests/component/layout.component.ts, apps/ledger-live-desktop/tests/page/lockscreen.page.ts, apps/ledger-live-desktop/tests/page/modal/send.modal.ts, apps/ledger-live-desktop/tests/page/portfolio.page.ts, apps/ledger-live-desktop/tests/specs/accounts/account.spec.ts, apps/ledger-live-desktop/tests/specs/accounts/encrypted.spec.ts, apps/ledger-live-desktop/tests/specs/countervalues/api.spec.ts, apps/ledger-live-desktop/tests/specs/families/bitcoin.spec.ts, apps/ledger-live-desktop/tests/specs/families/ethereum.spec.ts, apps/ledger-live-desktop/tests/specs/general/layout.spec.ts, apps/ledger-live-desktop/tests/specs/general/passwordlock.spec.ts, apps/ledger-live-desktop/tests/specs/general/portfolio.spec.ts, apps/ledger-live-desktop/tests/specs/services/buy.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/add.account.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/settings.spec.ts
- ...
Refacto layout class:
- Keeping only side bar & top bar elements
- **JIRA or GitHub link**: [QAA-80](https://ledgerhq.atlassian.net/browse/QAA-80)
---
[QAA-80]: …
=> [QAA] Refactoring layout class

.changeset/sharp-items-nail.md, apps/ledger-live-mobile/src/components/SelectableAccountsList.tsx, apps/ledger-live-mobile/src/const/navigation.ts, apps/ledger-live-mobile/src/families/hedera/NoAssociatedAccounts.tsx, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/Accounts/Navigator.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountListDrawer/CustomHeader/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountListDrawer/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountListEmpty/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountQuickActionsDrawer/CustomHeader/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountQuickActionsDrawer/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountQuickActionsDrawer/useAccountQuickActionDrawerViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountsListView/components/AccountItem/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountsListView/components/AccountItem/useAccountItemModel.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AddFundsButton/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/components/VerticalGradientBackground/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/types.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccountSuccess/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccountWarning/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/NoAssociatedAccountsView/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/ScanDeviceAccounts/components/CanCreateAccountAlert/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/ScanDeviceAccounts/components/ScanDeviceAccountsFooter/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/ScanDeviceAccounts/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/ScanDeviceAccounts/useScanDeviceAccountsViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/utils/getAccountListKeyExtractor.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/utils/tests/getAccountListKeyExtractor.test.ts, apps/ledger-live-mobile/src/screens/SkipSelectDevice.tsx, libs/live-wallet/src/store.ts
- ...
This PR will cover the following use cases: 
1.  Show a success screen with one or more added account with a currency color based gradient.
-> When user clicks on an account item , a redirection to account details page
-> when user clicks on add funds to my accounts -> a first drawer suggest the account list to select -> a second drawer will appear  with buy/receive cta once an account is selected. 
https://github.com/user-attachments/assets/fec7a199-f521-47fe-81a7-a149d835c675
2.  Show a warning screen one single 0$ balance existing account.
-> Here when you click on Add funds to my accounts -> a drawer with buy/receive (no account list drawer in this case)
https://github.com/user-attachments/assets/9e4a9cc1-9d66-415f-b88b-c6a82fbd4517
3. Show a specific empty state screen for …
=> feat: Add final steps (succes,warning, quickActions, emptyState UI) for add account v2 workflow

.github/workflows/release-final-nightly.yml
Wrapping the release commit in a git status (porcelain to remove human readable elements and no untracked files to avoid dotfiles impacting)
The steps following this should either auto skip or complete quickly allowing the workflow to finish quickly
https://ledgerhq.atlassian.net/browse/LIVE-12391
Success with changes present: https://github.com/LedgerHQ/ledger-live/actions/runs/12870060269/job/35880244698
Success with no changes present: https://github.com/LedgerHQ/ledger-live/actions/runs/12870214117/job/35880740006
=> ci: Enabling CI to return success when no desktop changes occur

.changeset/tiny-hornets-beg.md, apps/ledger-live-desktop/src/renderer/components/LiveAppDrawer.tsx, apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/CompleteExchange/Body.tsx, apps/ledger-live-desktop/src/renderer/modals/Send/steps/GenericStepConnectDevice.tsx
- Swap live-app
Fix double broadcast that could happen on the exchange flow as the useEffect deps could change
- **JIRA or GitHub link**: [LIVE-15840]
---
[LIVE-15840]: …
=> fix: double broadcast on exchange flow [LIVE-15840]

.changeset/hungry-bobcats-sneeze.md, apps/ledger-live-mobile/src/components/ConfirmationModal.tsx, apps/ledger-live-mobile/src/components/NavigationHeaderCloseButton.tsx, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/components/CloseWithConfirmation/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/Navigator.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/types.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccountSuccess/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccountWarning/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/NoAssociatedAccountsView/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/ScanDeviceAccounts/useScanDeviceAccountsViewModel.ts, apps/ledger-live-mobile/src/newArch/features/AssetSelection/Navigator.tsx, apps/ledger-live-mobile/src/newArch/features/DeviceSelection/Navigator.tsx, apps/ledger-live-mobile/src/newArch/features/DeviceSelection/types.ts
- ...
Simply when a user is in an Add account process and try to quit there are 2 possibilities: 
- A confirmation dialog will appear in the following screens:  Crypto and Network and Device Selection, ScanDeviceAccoun screen & Hedera no associated account screen.
- Direct exit from warning/success screen 
The close process will get back to the main wallet page. 
https://github.com/user-attachments/assets/db7016fb-7546-4d99-972a-2fa5779e2abf
https://ledgerhq.atlassian.net/browse/LIVE-15606
--- …
=> feat: close add account v2 multiple navigator via a confirmation drawer

.changeset/red-actors-explode.md, apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/LiveAppSDKLogic.ts, apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/PlatformAPIWebview.tsx, apps/ledger-live-mobile/src/logic/screenTransactionHooks.ts
- ...
mev protection wouldn't be used for now, but if in the future we use the `useSignWithDevice` hook elsewhere where mev protection would make sense, it'll be there. 
LiveAppSDKLogic <- PlatformAPIWebView <-Web3AppWebview/index.tsx 
<- apps/ledger-live-desktop/src/renderer/components/WebPTXPlayer/index.tsx  (used only be LiveAppCard and Buy/Sell)
<- apps/ledger-live-desktop/src/renderer/components/WebPlatformPlayer/index.tsx (only important one here, handle legacy manifests live-app, earn)
<- apps/ledger-live-desktop/src/renderer/components/WebRecoverPlayer/index.tsx 
<- apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx
- **JIRA or GitHub link**: LIVE-15795
--- …
=> make sure all non-cli broadcasts use broadcast config param

.changeset/silent-poets-check.md, libs/ledger-live-common/src/families/cosmos/datasets/__snapshots__/cosmos.integration.test.ts.snap, libs/ledger-live-common/src/families/cosmos/walletApiAdapter.test.ts, libs/ledger-live-common/src/families/cosmos/walletApiAdapter.ts, libs/ledger-live-common/src/generated/walletApiAdapter.ts
- wallet-api cosmos flows
Fixes root cause issue where `validators` in cosmos transactions could be `undefined` when coming from the wallet-api
We still have an issue trying to swap, where it requires `Expert mode` but enabling it in the cosmos app doesn't work for the exchange app
- **JIRA or GitHub link**: [LIVE-15822]
---
- …
=> fix(wallet-api): add missing cosmos walletApiAdapter [LIVE-15822]

.github/workflows/build-and-test-pr.yml
Part of https://ledgerhq.atlassian.net/browse/LIVE-14748
Updates our workflows so that ~`build-and-test-pr` workflows are run on Github runners if the triggering event is a merge queue group.~ the `build-and-test-pr` job runs on merge group, clearing the merge queue. 
This anticipates the activation of a merge queue on `develop`, as has been done in the device-sdk-ts repo.
There is no easy way to test this - I recommend we do a live switchover late in the evening at the end of a workday, announcing to #live-engineering in advance, or at a weekend. Therefore, merge strategy is to merge at the end of a workday, in advance of an end-of-workday session where we turn on the merge queue and validate that it works.
=> Run pr-build-and-test on merge queue

apps/ledger-live-mobile/e2e/models/send.ts, apps/ledger-live-mobile/e2e/models/stake.ts, apps/ledger-live-mobile/e2e/page/accounts/account.page.ts, apps/ledger-live-mobile/e2e/page/index.ts, apps/ledger-live-mobile/e2e/page/speculos.page.ts, apps/ledger-live-mobile/e2e/page/trade/deviceValidation.page.ts, apps/ledger-live-mobile/e2e/page/trade/operationDetails.page.ts, apps/ledger-live-mobile/e2e/page/trade/send.page.ts, apps/ledger-live-mobile/e2e/page/trade/stake.page.ts, apps/ledger-live-mobile/e2e/specs/delegate/cosmos.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/delegate/delegate.ts, apps/ledger-live-mobile/e2e/specs/speculos/delegate/delegateATOM.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/delegate/delegateNEAR.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/delegate/delegateSOL.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/send/send.ts, apps/ledger-live-mobile/src/components/StepHeader.tsx, apps/ledger-live-mobile/src/components/ValidateOnDevice.tsx, apps/ledger-live-mobile/src/families/cosmos/TransactionConfirmFields.tsx, apps/ledger-live-mobile/src/families/cosmos/operationDetails.tsx, apps/ledger-live-mobile/src/families/cosmos/shared/02-SelectAmount.tsx, apps/ledger-live-mobile/src/families/near/StakingFlow/01-Started.tsx, apps/ledger-live-mobile/src/families/near/StakingFlow/02-Summary.tsx, apps/ledger-live-mobile/src/families/near/operationDetails.tsx, apps/ledger-live-mobile/src/families/near/shared/02-SelectAmount.tsx, apps/ledger-live-mobile/src/families/solana/DelegationFlow/SelectAmount.tsx, apps/ledger-live-mobile/src/families/solana/DelegationFlow/Started.tsx, apps/ledger-live-mobile/src/families/solana/DelegationFlow/Summary.tsx, apps/ledger-live-mobile/src/families/solana/operationDetails.tsx, apps/ledger-live-mobile/src/screens/OperationDetails/Content.tsx, libs/ui/packages/native/src/components/cta/QuickAction/QuickActionButton/index.tsx
- LLM Speculos tests
_First detox speculos delegate tests_
- Speculos [Test Mobile E2E](https://github.com/LedgerHQ/ledger-live/actions/runs/12864503397): Allure [report](https://ledger-live.allure.green.ledgerlabs.net/allure/reports/53cd7ba5-5c69-45e5-9d6c-58066b96db2b/#)
--- …
=> [LLM][Detox][Speculos] First Speculos delegate tests

apps/ledger-live-desktop/src/renderer/components/SuccessDisplay.tsx, apps/ledger-live-desktop/src/renderer/families/cardano/DelegationFlowModal/steps/StepSummary.tsx, apps/ledger-live-desktop/tests/component/modal.component.ts, apps/ledger-live-desktop/tests/page/drawer/delegate.drawer.ts, apps/ledger-live-desktop/tests/page/index.ts, apps/ledger-live-desktop/tests/page/liveApp.page.ts, apps/ledger-live-desktop/tests/page/modal/delegate.modal.ts, apps/ledger-live-desktop/tests/page/speculos.page.ts, apps/ledger-live-desktop/tests/specs/speculos/delegate.spec.ts, libs/ledger-live-common/src/e2e/enum/Account.ts, libs/ledger-live-common/src/e2e/enum/AppInfos.ts, libs/ledger-live-common/src/e2e/enum/Currency.ts, libs/ledger-live-common/src/e2e/enum/DeviceLabels.ts, libs/ledger-live-common/src/e2e/families/cardano.ts, libs/ledger-live-common/src/e2e/families/multiversX.ts, libs/ledger-live-common/src/e2e/speculos.ts
- ...
- e2e delegation:
- Injective
- OSMOS
- e2e delegation without broadcast:
- Ada Cardano
- Multivers X
- 'liveApp' Flow:
- Ethereum
- Tron
- Polkadot
🚨 Tezos and Celo not done yet, Waiting for information about the new delegation flow. cc @mcoursier-ledger 
- **JIRA or GitHub link**: [QAA-438](https://ledgerhq.atlassian.net/browse/QAA-438)
--- …
=> [QAA] Adding currencies for E2E delegation test

apps/ledger-live-desktop/tests/component/modal.component.ts, apps/ledger-live-desktop/tests/page/drawer/delegate.drawer.ts, apps/ledger-live-desktop/tests/page/drawer/firmwareUpdate.drawer.ts, apps/ledger-live-desktop/tests/page/modal/add.account.modal.ts, apps/ledger-live-desktop/tests/page/modal/delegate.modal.ts, apps/ledger-live-desktop/tests/page/modal/passwordlock.modal.ts, apps/ledger-live-desktop/tests/page/modal/send.modal.ts, apps/ledger-live-desktop/tests/page/modal/settings.modal.ts, apps/ledger-live-desktop/tests/specs/accounts/delegate.smoke.spec.ts, apps/ledger-live-desktop/tests/specs/general/passwordlock.spec.ts, apps/ledger-live-desktop/tests/specs/manager/firmwareupdate.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/delegate.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/receive.address.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/subAccount.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts
- ...
Refacto modal class for e2e tests
Fix Xray integration by removing B2CQA-600
[QAA-79](https://ledgerhq.atlassian.net/browse/QAA-79)
[QAA-445](https://ledgerhq.atlassian.net/browse/QAA-445)
--- …
=> [QAA] Refacto modal class - e2e tests

.changeset/new-bulldogs-hope.md, apps/ledger-live-mobile/src/components/RootNavigator/types/ReceiveFundsNavigator.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AccountsList/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/components/SelectAddAccountMethod/useSelectAddAccountMethodViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/enums.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/types.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccountSuccess/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccountWarning/index.tsx, apps/ledger-live-mobile/src/newArch/features/AssetSelection/__integrations__/assetSelection.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/AssetSelection/screens/SelectCrypto/useSelectCryptoViewModel.ts, apps/ledger-live-mobile/src/newArch/features/AssetSelection/screens/SelectNetwork/useSelectNetworkViewModel.ts, apps/ledger-live-mobile/src/newArch/features/AssetSelection/types.ts, apps/ledger-live-mobile/src/newArch/features/DeviceSelection/__integrations__/deviceSelection.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/DeviceSelection/types.ts, apps/ledger-live-mobile/src/screens/MyLedgerDevice/Modals/InstalledAppModal.tsx, apps/ledger-live-mobile/src/screens/ReceiveFunds/01-SelectCrypto.tsx, apps/ledger-live-mobile/src/screens/ReceiveFunds/02-SelectAccount.tsx, apps/ledger-live-mobile/src/screens/ReceiveFunds/02-SelectNetwork.tsx, apps/ledger-live-mobile/src/screens/RequestAccount/02-SelectAccount.tsx, apps/ledger-live-mobile/src/screens/Swap/Form/Summary/index.tsx, apps/ledger-live-mobile/src/screens/Swap/SubScreens/SelectAccount.tsx, apps/ledger-live-mobile/src/screens/WalletCentricAsset/index.tsx
- ...
Issue analysis:
After reviewing the scenario in detail, it appears the account selection screen displayed in this particular use case is the "add account v1" version (designed for receiving), even the screen preceding the scan is the "add account v1" (intended for receiving). Therefore, when you select an account from the list, it will be added.
Essentially, on the production environment, this isn't a bug, because it's a logical sequence:
I initiate a "receive" operation.
I select an asset for which I don't have an existing account.
The scan that launches is the "add account v1" version.
The displayed list is the "add account v1" list for receiving (since it's a single selection).
Normally, if the "add account v2" feature flag is activated, we should go through (in this specific …
=> fix: add account v2 redirection from receive when no account found / add account v1 is OK

.github/workflows/release-final.yml, .github/workflows/release-prepare-hotfix.yml, .github/workflows/release-prepare.yml
Fixes the (unticketed) issue from [this comment](https://ledger.slack.com/archives/C03MHGMAMRQ/p1737535147677199) where the "publish apps" workflow did not execute all the expected steps when triggered by the "prepare release" workflow.
This issue stems from this PR - https://github.com/LedgerHQ/ledger-live/pull/8718, which introduced a new mechanism for chaining the workflows together (`workflow_call` chaining technique introduced, `workflow_run` deprecated). Although this was tested and worked well during development, we turned off many of the steps of the downstream "publish" workflow so that we wouldn't create actual releases during testing, therefore only testing the workflow chaining. It turns out 2 of these deacticated steps were affected by the workflow call type, and are now …
=> Check for version differences on `workflow_call` not `workflow_run`

.github/workflows/test-mobile-e2e-reusable.yml, apps/ledger-live-mobile/detox.config.d.ts, apps/ledger-live-mobile/detox.config.js, apps/ledger-live-mobile/docs/llm_e2e_testing.md
When the simulators are updated, the naming inside detox vs the workflow causes the tests to fail. This change provides an alias for the simulators which does not change. When upgrading the simulators, it needs only be upgraded in the pipeline.
Demonstration of the problem: https://github.com/LedgerHQ/ledger-live/actions/runs/12994666080
Passed Run: https://github.com/LedgerHQ/ledger-live/actions/runs/13008738541
=> ci: Improving reliability of tests during mobile upgrades

.github/workflows/turbo-affected-reusable.yml
Part of https://ledgerhq.atlassian.net/browse/LIVE-16491
This was a (hopefully the) missing piece from yesterday's merge queue switch-on. Git refs need to normalised, i.e. the `refs/heads/` substring needs to be removed, before passing to turbo. This PR implements that.
[Here's a PR](https://github.com/LedgerHQ/merge-queue-test/pull/11/files) that shows this working. The `clean-refs` step is mostly copy-pasted from the `clean-refs` step that is already in this repo's `turbo-affected-reusable` workflow (it adds  in variable definitions that this repo's `turbo-affected-reusable` workflow receives when it is run).
[Here's the check](https://github.com/LedgerHQ/merge-queue-test/actions/runs/12932759419/job/36069739445?pr=11) that runs during the PR CI. [Here's the …
=> Normalise refs before passing to turbo-affected

.changeset/itchy-camels-sin.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Synchronize/02-QRCodeStep.tsx, apps/ledger-live-desktop/src/renderer/screens/accounts/OptionsButton.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/walletSyncActivation.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/walletSyncSettings.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Activation/ActivationFlow.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Activation/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Synchronize/BottomContainer.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Synchronize/QrCode.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Synchronize/ScanQrCode.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Activation/index.tsx
- ...
Updated copy on LLM and LLD
Removed entry points in accounts page on LLD
Skip unnecessary step on LLM when clicking on `Turn on Ledger Sync`
https://github.com/user-attachments/assets/2705c7ce-ee48-45ee-80c5-924ad1e7dd78
- **JIRA or GitHub link**: [LIVE-14883] [LIVE-15372] [LIVE-15373] [LIVE-15375] [LIVE-14488] [LIVE-15525]
--- …
=> 💄  Ledger Sync copy and UX improvements

apps/ledger-live-mobile/e2e/page/accounts/account.page.ts, apps/ledger-live-mobile/e2e/specs/speculos/account/accountRename.spec.ts, apps/ledger-live-mobile/src/screens/AccountSettings/AccountNameRow.tsx, apps/ledger-live-mobile/src/screens/AccountSettings/EditAccountName.tsx
- LLM Rename account test
Add test to check that account name change persists after app kill
- [Test Mobile E2E Speculos](https://github.com/LedgerHQ/ledger-live/actions/runs/13026789815)
---
=> [QAA-415][Detox][Speculos] Account name persist after restart

libs/coin-framework/src/api/types.ts, libs/coin-modules/coin-module-boilerplate/src/common-logic/history/listOperations.ts, libs/coin-modules/coin-module-boilerplate/src/network/indexer.ts, libs/coin-modules/coin-polkadot/src/api/index.integ.test.ts, libs/coin-modules/coin-polkadot/src/api/index.ts, libs/coin-modules/coin-stellar/src/api/index.integ.test.ts, libs/coin-modules/coin-stellar/src/api/index.ts, libs/coin-modules/coin-stellar/src/logic/listOperations.ts, libs/coin-modules/coin-tezos/src/api/index.integ.test.ts, libs/coin-modules/coin-tezos/src/api/index.ts, libs/coin-modules/coin-tezos/src/logic/listOperations.ts, libs/coin-modules/coin-xrp/package.json, libs/coin-modules/coin-xrp/src/api/index.integ.test.ts, libs/coin-modules/coin-xrp/src/api/index.test.ts, libs/coin-modules/coin-xrp/src/api/index.ts, libs/coin-modules/coin-xrp/src/bridge/synchronization.test.ts, libs/coin-modules/coin-xrp/src/logic/listOperations.test.ts, libs/coin-modules/coin-xrp/src/logic/listOperations.ts, libs/coin-modules/coin-xrp/src/network/index.ts, libs/coin-modules/coin-xrp/src/network/types.ts, pnpm-lock.yaml
Sorry, this is a big PR.
I changed the API of "operations" so, it impacted the code on all coins that implements the coin framework. Specifically I changed the semantic of "operations" so that it returns all operations, without pagination. In the future we may paginate using a proper token described in this document https://ledgerhq.atlassian.net/wiki/x/XIGeRAE
For stellar/tezos/xrp coins: I also changed signature of "logic" layer so that the token used for iteration is string not a number. The value of the token is a stringified json representation of the token returned by the underlying "network" layer. It's returned by the listOperations so that it could be reused as input in future implementation.
For stellar and tezos, the "api" is adapted for compilation but not yet ready to use, …
=> feat(coin:xrp): apply api change on operations

.changeset/wild-cougars-cough.md, apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx, apps/ledger-live-mobile/src/locales/en/common.json
- ...
Missing tag and translations on device action during interaction with Exchange app
Should fix : https://ledgerhq.atlassian.net/browse/LIVE-16736
- **JIRA or GitHub link**: [LIVE-16736](https://ledgerhq.atlassian.net/browse/LIVE-16736)
--- …
=> :bug fix(llm) missing text tag

.github/workflows/build-and-test-external.yml
Part of https://ledgerhq.atlassian.net/browse/LIVE-16491
Fixes the issue described in [this message](https://ledger.slack.com/archives/C0308JT8WS2/p1738090132410689?thread_ts=1738074868.453619&cid=C0308JT8WS2).
"OK external", the final job from [build-and-test-external](https://github.com/LedgerHQ/ledger-live/blob/develop/.github/workflows/build-and-test-external.yml), is a required check for this repo - that means it must be run on `merge_group` trigger otherwise the merge group checks will hang indefinitely (waiting for a required check which is never triggered). This PR ads the `on: merge_group` condition to handle this.
=> Run build-and-test-external on merge group

apps/ledger-live-desktop/README.md
Inconsequential PR that removes a stray extra space in the desktop readme. Really this PR is to see the CI working following the switch to the merge queue setup, which was just turned on.
=> fix: remove incorrect indentation in desktop readme

.github/workflows/release-prepare-hotfix.yml
We've just found an issue with https://github.com/LedgerHQ/ledger-live/pull/8718.
At the end of the release-prepare-hotfix workflow we automatically call the release-final workflow (simply as a matter of convenience so Desire doesn't have to manually trigger the final release).
A problem with this implementation was that even though you're releasing a hotfix, you want to do it from:
- `main` if the hotfix was created from the "latest" version of the app
- `hotfix` if the hotfix was created from a previous version
Documentation explaining this is [here](https://github.com/LedgerHQ/ledger-live/pull/9044/files). IMO this is a bit confusing and the chaining of "if"s is getting a bit wild, so I think that we may be due a rethink of how we manage this. But for now this PR fixes the issue and …
=> Release from `main` if the hotfix has been done from latest version

.changeset/loud-comics-remember.md
I bump to `major` following the semantic versioning because I broke the coin-framework/api types (not forward compatible)
Is that ok ? Since that's the very first major, maybe you're not using semantic versioning ?
=> chore: add changeset about coin-framework and impacted coin modules

.changeset/loud-llamas-try.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/ScanDeviceAccounts/useScanDeviceAccountsViewModel.ts
- ...
The aim of this fix/feat is to not show the "imported" section in the scan section of the add account v2. 
https://github.com/user-attachments/assets/204fc035-a9e6-4dba-9f9c-8515244eb539
https://github.com/user-attachments/assets/467d5e3f-4440-4cdd-8f17-1940d8a90aec
https://ledgerhq.atlassian.net/browse/LIVE-16637
--- …
=> feat: don't display Accounts already in the Portfolio

.changeset/dull-pianos-wave.md, apps/ledger-live-desktop/src/newArch/features/DynamicContent/__integrations__/PortfolioContentCards.test.tsx, apps/ledger-live-desktop/src/newArch/features/DynamicContent/hooks/usePortfolioCards.ts
With the Braze Web SDK, clicks are not tracked if the url field is empty so we need to set it to a dumb value as it isn't used for anything else
We also need to dismiss the typescript error as they have an error in their typing and the Braze.Card class doesn't declare a url property
- **JIRA or GitHub link**: [LIVE-16763] 
---
- …
=> 🧐  LLD - Fix clicks tracking for Portfolio cards

.changeset/tender-birds-visit.md, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/ScanDeviceAccounts/useScanDeviceAccountsViewModel.ts, apps/ledger-live-mobile/src/screens/ReceiveFunds/02-SelectAccount.tsx, apps/ledger-live-mobile/src/screens/RequestAccount/02-SelectAccount.tsx, apps/ledger-live-mobile/src/screens/WalletCentricAsset/index.tsx
… to unrecognized currency on device scan
- ...
This change fixes both [App crashing when attempting to add account from token asset pages](https://ledgerhq.atlassian.net/browse/LIVE-16638) and [ App crashes when creating an account from the NFTs page](https://ledgerhq.atlassian.net/browse/LIVE-16519)
The main reason behind this crash, is that for token we should call the device action with the parent currency while redirecting directly to the device selection in order to make the scan correctly and avoid `Invariant Violation: appName or currency or account is missing` error triggered by the DeviceAction hook
https://github.com/user-attachments/assets/913e2d1d-1a1b-408e-b862-c547e41a2f38
https://ledgerhq.atlassian.net/browse/LIVE-16638
---
- **The code aligns …
=> fix: 🐞 app crash on token selected for add account v2 redirection due to unrecognized currency on device scan

.github/workflows/test-ui-e2e-only-desktop.yml, apps/ledger-live-mobile/e2e/page/trade/send.page.ts, apps/ledger-live-mobile/e2e/specs/speculos/send/send.ts, apps/ledger-live-mobile/e2e/specs/speculos/send/sendInvalid/sendInvalidTokenAmountBSC_BUSD.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/send/sendInvalid/sendInvalidTokenAmountETH_USDT.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/send/sendInvalid/sendInvalidTokenAmountETH_USDT_2.spec.ts, libs/ledger-live-common/src/e2e/enum/Fee.ts
- ...
Implement invalid transaction - USDT (Amount > Balance)
Implement Fees for Send Tests
- [QAA-448](https://ledgerhq.atlassian.net/browse/QAA-448)
- [QAA-455](https://ledgerhq.atlassian.net/browse/QAA-455)
--- …
=> [QAA - DETOX] Adding fee strategie + Implement invalid Amount - USDT

.changeset/tiny-scissors-yawn.md, apps/ledger-live-mobile/ios/ledgerlivemobile.xcodeproj/project.pbxproj, apps/ledger-live-mobile/ios/ledgerlivemobile/AppDelegate.mm, apps/ledger-live-mobile/ios/ledgerlivemobile/Info.plist
- ...
After investigations we have an issue between the loadingView that conflicts with the react native view. Here the splashscreen is well rendered but switch to another view quickly (white screen). As far as I see there is 4 diff screens rendered. Native Splashscreen => Loading View => LoadingApp.tsx => a white screen (maybe coming from a return null)
Since we have added merge queue we can't stay with so much flakiness so it will need more investigations on this. And maybe create our own native module to handle the apparition and disapparition of the launchscreen. (worst case because will be horrible to maintained with RN updates) 
https://github.com/user-attachments/assets/5cfdbf07-492c-445e-b1e3-b8b48c3f105d
---
- **The code aligns with the requirements** …
=> fix :bug:(detox) ios launchscreen

.changeset/calm-planes-train.md, apps/ledger-live-desktop/src/renderer/families/polkadot/Nomination/index.tsx, apps/ledger-live-mobile/src/families/polkadot/Nominations/index.tsx
- Earn rewards button opening stakekit live app
This PR replaces the action on the "earn rewards" button into the account screen to open stakekit rather than the native staking modal.
- **JIRA or GitHub link**: [CN-1076](https://ledgerhq.atlassian.net/browse/CN-1076)
--- …
=> CN-1076: change the button action earn rewards to open stakekit

.changeset/ten-ties-rush.md, libs/coin-modules/coin-tezos/src/test/bot-deviceActions.ts, libs/coin-modules/coin-tezos/src/test/bot-specs.ts
- ...
⚠️ Error: device action timeout. Recent events was:
{"text":"Review operation","x":13,"y":17,"w":107,"h":11}
{"text":"Operation (0)","x":26,"y":-1,"w":94,"h":11}
{"text":"Reveal","x":47,"y":10,"w":81,"h":11}
(totally spent 62.3s – ends at 2025-01-09T17:22:35.919Z)
- **JIRA or GitHub link**: [LIVE-15843](https://ledgerhq.atlassian.net/browse/LIVE-15843)
--- …
=> fix: device actions bot fix but remind error for fees

.changeset/blue-humans-destroy.md, apps/ledger-live-mobile/src/components/AnalyticsConsole/Event.tsx
- ...
The formating of the analytics console removes the content of deeper properties: arrays content are displayed but object are wrongfully displayed as empty. I believe this was an unintentional side effect. So this PR simplifies the console formatting.
|   <img width="435" alt="Screenshot 2025-02-07 at 18 10 15" src="https://github.com/user-attachments/assets/5c7cc06c-721b-4ac9-beab-cd90059fd9b2" />   |  <img width="435" alt="Screenshot 2025-02-07 at 18 10 45" src="https://github.com/user-attachments/assets/bdb9cc36-1e5b-4f9f-ab67-a9a44a12c926" />
|
--- …
=> fix(llm): 🩹 fix the analytics console for deep properties

.changeset/odd-shoes-promise.md, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/locales/en/common.json
- Solana send token error message 
Add missing error messages
- **JIRA or GitHub link**: [LIVE-16703]
---
[LIVE-16703]: https://ledgerhq.atlassian.net/browse/LIVE-16703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2 …
=> fix: add missing error strings [LIVE-16703]

.changeset/ninety-radios-suffer.md, apps/ledger-live-mobile/src/families/solana/accountActions.tsx
- ...
Have over 1 SOL available to spend
Go to Earn on LLM
Try to stake your SOL
Given the amount of SOL available in my wallet, I should be able to stake and not getting redirected to the screen with CTAs to Buy and Swap.
- **JIRA or GitHub link**: [LIVE-15273](https://ledgerhq.atlassian.net/browse/LIVE-15273)
--- …
=> fix: check account balance or spedable is zero in front

.changeset/lucky-snakes-serve.md, libs/live-countervalues/src/portfolio.ts
- countervalues
Add a props to order the accounts by fullbalance or spendable balance. By default it's the full balance
- **JIRA or GitHub link**: [LIVE-15501](https://ledgerhq.atlassian.net/browse/LIVE-15501)
--- …
=> :bug: fix(llm) accounts list wrong order with staked

.changeset/metal-poets-serve.md, apps/cli/src/commands/device/listApps.ts
- ...
The result of the `listApps` command is currently printed twice:
- in the lines removed in this commit
- in the `next` callback function of the main subscriber (cf https://github.com/LedgerHQ/ledger-live/blob/25bea5fd10d71e46de700d0a8eefb430cd38e0ef/apps/cli/src/cli.ts#L84-L86)
--- …
=> 🐛 (cli): print `listApps` output only once

.changeset/tall-mangos-drive.md, apps/ledger-live-mobile/src/newArch/features/Accounts/__integrations__/accountsListScreen.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/__integrations__/mockedAccounts.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountsListView/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountsListView/useAccountsListViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Assets/components/AssetsListView/index.tsx, apps/ledger-live-mobile/src/newArch/features/Assets/components/AssetsListView/useAssetsListViewModel.ts, apps/ledger-live-mobile/src/newArch/utils/__tests__/getEstimatedListSize.test.ts, apps/ledger-live-mobile/src/newArch/utils/getEstimatedListSize.ts
- accounts/assets lists
Use estimatedListSize to optimise the first render of assets and accounts list this will prevent a calculation before the first render that could slow the render.
As it's done here https://github.com/Shopify/flash-list/blob/ba3b9aa79f5ecb3af17688307b5eb3d9b164337a/src/MasonryFlashList.tsx#L239
Test has been updated too because before that not all the accounts were rendered at the first render. We can see in the mock that there is well 7 accounts with `balance: BigNumber("83315786").multipliedBy(10),` 
- **JIRA or GitHub link**: [LIVE-16939](https://ledgerhq.atlassian.net/browse/LIVE-16939)
--- …
=> :zap: (llm) optimise render of assets/accounts lists

.changeset/chilled-apes-begin.md, apps/ledger-live-desktop/src/renderer/components/LiveAppDrawer.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/Swap/Form/Modal/Confirmation.tsx, libs/ledger-live-common/src/exchange/swap/getIncompatibleCurrencyKeys.ts, libs/ledger-live-common/src/exchange/swap/index.ts
- Swap live-app LNS
Add explicit error message for LNS users swapping Cosmos
Move the duplicated logic to common
I can avoid the multiple duplication in translated strings too IMO and use a param for the currency name instead
- **JIRA or GitHub link**: [LIVE-16786]
--- …
=> feat: add explicit error message for LNS users swapping Cosmos [LIVE-16786]

.github/workflows/build-and-test-pr.yml
Skips merge queue run of `build-and-test-pr` if:
- the PR's pre-merge-queue CI was run against latest `develop`
- the PR is being added to an empty merge queue
In this case, the CI check from before entering the merge queue is sufficient, as it tests an identical repo state to what a merge_group check would test.
=> skip build-and-test-pr if already run on this file set

.github/workflows/build-and-test-pr.yml
Reverts LedgerHQ/ledger-live#9141
Wasn't able to add a test PR to the merge queue out-of-hours without a reviewer present.
Of course, I could skip the branch protections but as I have just learned, this would also have skipped the merge queue which is what I'm trying to test. Will have to be another night 😮‍💨
=> Revert "skip build-and-test-pr if already run on this file set"

.changeset/pink-apes-pump.md, libs/coin-framework/src/currencies/__snapshots__/formatCurrencyUnit.test.ts.snap, libs/coin-modules/coin-evm/src/__tests__/unit/editTransaction/__snapshots__/getFormattedFeeFields.test.ts.snap, libs/ledgerjs/packages/cryptoassets/src/currencies.ts
Sounds like `TOMO` is not properly aligned with `LedgerHQ/crypto-assets` repo (see [here](https://github.com/LedgerHQ/crypto-assets/blob/0ad6155f0ecb61a036e9866b672993a8d1e0c8c8/outputs/update/coins/tomo.asset.json#L7-L13)).
Causing some trouble on Ledger Enterprise side (see TSD-4669).
=> fix(cryptoassets): update TOMO magnitude to 18

.changeset/four-pigs-bathe.md, apps/ledger-live-mobile/src/components/NavigationHeaderCloseButton.tsx, apps/ledger-live-mobile/src/components/SelectableAccountsList.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountListDrawer/CustomHeader/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountListDrawer/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountQuickActionsDrawer/CustomHeader/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountQuickActionsDrawer/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccountSuccess/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccountWarning/index.tsx, apps/ledger-live-mobile/src/screens/AddAccounts/03-Accounts.tsx
- UI of add account flow
Polish of the add account flow UI + fix a old layout issue when an account wasn't created because of empty account on the old UI. I've added the video of the before to ensure that all is still working well even if it's not really relevant in the context
For some styles it can be a bit a mess because I'd to change the style depending of the ff
I've used space[] to ensure that we have the correct value in px and I am not sure why space[6] doesn't render the same as "16px" for borderRadius but 16px doesn't seem working well (not sure)
|https://github.com/user-attachments/assets/98018b86-b739-49e0-af97-babad141a4bf|https://github.com/user-attachments/assets/b599b74a-b1a6-4c48-8199-c05835bb5846|
| …
=> :lipstick: (llm) add account polish

.github/workflows/test-libs-reusable.yml
Temporarily move test libraries to GHA runners due to early termination
=> ci: move library test to GHA hosted runners

.changeset/calm-deers-smile.md, .changeset/tame-experts-film.md, libs/coin-framework/src/api/types.ts, libs/coin-modules/coin-xrp/src/api/index.integ.test.ts, libs/coin-modules/coin-xrp/src/bridge/signOperation.ts, libs/coin-modules/coin-xrp/src/logic/craftTransaction.test.ts, libs/coin-modules/coin-xrp/src/logic/craftTransaction.ts
integration tests: https://github.com/LedgerHQ/ledger-live/actions/runs/13076078720
(failing but I think I'm not accountable)
=> feat(coin:xrp): add memo and destination tag in crafting

.changeset/real-guests-fly.md, apps/ledger-live-desktop/src/renderer/families/near/AccountHeaderManageActions.ts
- Fixes the issues reported from Sentry
Adds a guardrail when `nearResources` from mainAccount is undefined, which will make`hasStakingPositions` falsy
[- **JIRA**: ](https://ledgerhq.atlassian.net/browse/LIVE-16957)
--- …
=> fix: add guardrails when mainAccount does not have nearResources

.changeset/fast-doors-mix.md, libs/coin-framework/src/currencies/__snapshots__/formatCurrencyUnit.test.ts.snap, libs/coin-modules/coin-evm/src/__tests__/unit/editTransaction/__snapshots__/getFormattedFeeFields.test.ts.snap, libs/ledgerjs/packages/cryptoassets/src/currencies.ts
- ...
Some testnet tickers are not the same on nano app and LL
for exemple on nano app we have `ETH` and on LL we have `tETH`
- **JIRA or GitHub link**: [LIVE-16797](https://ledgerhq.atlassian.net/browse/LIVE-16797)
--- …
=> fix: update ethereum testnet units to match nano app

.github/workflows/pr-analysis.yml
- ...
Add a workflow that triggers a SonarQube Cloud Pull Request analysis on all PR targetting develop
- **JIRA or GitHub link**: [LIVE-14776] [LIVE-14777] [LIVE-14778]
---
[LIVE-14778]: …
=> SonarCloud PR Analysis

.github/workflows/test-libs-reusable.yml
Moving library tests back to self hosted runners following resource management updates to deal with high CPU/memory 
Passing test: https://github.com/LedgerHQ/ledger-live/actions/runs/13308587669/job/37165178308
=> ci: Revert test libs to self hosting

package.json
Reducing memory pressure on runners during test to avoid inside-container flakes (such as https://github.com/LedgerHQ/ledger-live/actions/runs/13310399962/job/37171255396)
=> ci: Adjust concurrency to 25% to avoid memory issues

.github/workflows/build-mobile-reusable.yml
Move JS bundle builds on PR to linux due to increased scaling flexability
=> ci: Move iOS PR builds to Linux due to limited macOS runners

.changeset/tasty-guests-suffer.md, tools/actions/live-common-affected/build/main.js, tools/actions/live-common-affected/src/main.ts
=> add coin-modules on affected files

.changeset/gorgeous-teachers-tap.md, apps/ledger-live-mobile/src/actions/earn.ts, apps/ledger-live-mobile/src/actions/types.ts, apps/ledger-live-mobile/src/components/RootNavigator/EarnLiveAppNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/types/EarnLiveAppNavigator.ts, apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx, apps/ledger-live-mobile/src/reducers/earn.ts, apps/ledger-live-mobile/src/reducers/types.ts, apps/ledger-live-mobile/src/screens/PTX/Earn/EarnInfoDrawer.tsx, apps/ledger-live-mobile/src/screens/PTX/Earn/EarnMenuDrawer.tsx
- New modal component added.
Add a new modal, that can be triggered from Earn, that shows a list of options to select from. These will re-direct the user to different dynamic links specified from Earn.
After:
- **JIRA or GitHub link**: [LIVE-15861](https://ledgerhq.atlassian.net/browse/LIVE-15861)
- **Design**: [Figma](https://www.figma.com/design/ZOf1hLXmO4BtdcEWP8XyKX/Stablecoin-integration?node-id=537-32658&t=io8NVNtxtUREorFb-4)
--- …
=> feat: add dropdown drawer menu for managing an Earn position

.changeset/wise-hornets-hunt.md, libs/coin-modules/coin-tezos/package.json, libs/coin-modules/coin-tezos/src/logic/listOperations.test.ts, libs/coin-modules/coin-tezos/src/logic/listOperations.ts
What's changed:
- when recipients or senders is not found, it return an empty array instead of `[""]`
- for delegate/undelegate operations, it adds the target adress as recipients
int tests: https://github.com/LedgerHQ/ledger-live/actions/runs/13325154125
=> fix(coin:tezos): handle missing recipients or senders cleanly

.changeset/clever-dolls-greet.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/components/EmptyList/AccountsEmptyList/index.tsx, apps/ledger-live-mobile/src/newArch/components/EmptyList/__tests__/AccountsEmptyList.test.tsx, apps/ledger-live-mobile/src/newArch/components/EmptyList/components/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/__integrations__/accountsListScreen.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AccountsList/hooks/useGenericAccountsListViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AccountsList/hooks/useSpecificAccountsListViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AccountsList/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AccountsList/utils/getTicker.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AccountsList/utils/navigation.ts, apps/ledger-live-mobile/src/newArch/features/Assets/screens/AssetsList/index.tsx
- assets and accounts list empty screen
When we use a deeplink to open assets and accounts list we can be in an empty screen if we don't have any account. To avoid that I've added an emptyList component that we could use for all our emptyList. 
The idea is to have different empty list components depending on the context => addAccount for assets and accounts screen, maybe receive empty list for other screens. This way we can ensure homogeneity using the same base component
deeplinks you can use : 
ledgerlive://accounts?canAddAccount=true&showHeader=true&isSyncEnabled=true
ledgerlive://assets?showHeader=true
see video on slack
- **JIRA or GitHub link**: [LIVE-16967](https://ledgerhq.atlassian.net/browse/LIVE-16967)
---
- **The code aligns with the requirements** described in the linked JIRA …
=> :lipstick: (llm) empty accounts/assets screen

.changeset/orange-turkeys-wait.md, apps/ledger-live-desktop/src/renderer/screens/settings/SettingsSection.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/Settings/General/MevProtection.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- lld settings
- llm settings
- mevProtection ff
Update the Mev Protection feature flag to accept an url
On LLD I've updated directly SettingsRow component to keep the same archi and as I think it could be useful to have these params in the future 
On LLM I've just sent a component as a description because it's more common on LLM
| LLM        | LLD         |
|https://github.com/user-attachments/assets/1c86dd4c-4536-4b70-9984-a4eddf7ae52b|https://github.com/user-attachments/assets/d17207fa-55f9-450a-a062-d2012a805f4f|
- **JIRA or GitHub link**: [LIVE-17051](https://ledgerhq.atlassian.net/browse/LIVE-17051)
---
- **The PR description clearly documents the changes** …
=> :triangular_flag_on_post: (llm/lld) update mev feature flag

package.json
Reducing the concurrency of turbo to 1 due to parallelism in jest eating up resources
This PR's run show a run with caching enabled
The issue is a bi-product of reducing resource allocation to prevent runner crashes https://ledgerhq.atlassian.net/browse/LIVE-16834
=> ci: adjust concurrency to 1 fixed

apps/ledger-live-mobile/fastlane/Fastfile
On the back of performance testing, 3 workers appears to be an adequate fit for the CI runners to improve consistency.
This issue was borne out of the reduction of runner resources which caused crashes https://ledgerhq.atlassian.net/browse/LIVE-16834
=> ci: Adjust gradle concurrency

.changeset/quick-items-burn.md, apps/ledger-live-mobile/src/analytics/segment.ts, apps/ledger-live-mobile/src/logic/modelIdList.ts, apps/ledger-live-mobile/src/reducers/settings.ts
- ...
In #9109 devices are added to the store in `settings.seenDevices` which is supposed to be a uniq device array. However to identify the devices uniquely the reducer uses `DeviceModelInfo["deviceInfo"]["targetId"]` which actually identifies the firmware version. While discussing the issue the device team pointed out that there is no way to uniquely identify a device.
As an approximation this PR stores **for each model** only the last connected device into `settings.seenDevices`. Then devices are counted based on:
- `ble.knownDevices` + (each model in `settings.seenDevices` but not in `ble.knownDevices`)
- **JIRA or GitHub link**: [LIVE-16680]
--- …
=> fix(llm): 🩹 do not re-count devices multiple time after upgrades

.changeset/mighty-mirrors-relate.md, libs/coin-modules/coin-evm/src/__tests__/coin-tester/anvil.ts, libs/coin-tester/src/main.ts, libs/coin-tester/src/signers/speculos.ts
- ...
Running the EVM coin tester is failing, even all the tests pass. That is because, in some cases, old containers remain and make docker network removal impossible.
Now using `--remove-orphans` to exit cointaners in a clean way to avoid the behavior described above.
--- …
=> fix (coin-tester): stop EVM coin tester smoothly

.changeset/wicked-doors-search.md, apps/ledger-live-desktop/src/renderer/families/evm/StakeFlowModal/component/ProviderItem.tsx, apps/ledger-live-desktop/src/renderer/families/evm/StakeFlowModal/index.tsx
- Visualisation of text
Fix staking modal text overlap when too many words
Before:
After:
- **JIRA or GitHub link**: [LIVE-15869](https://ledgerhq.atlassian.net/browse/LIVE-15869)
---
[LIVE-15869]: …
=> LIVE-15869: Earn eth staking modal text issues if ll in some languages

.changeset/purple-avocados-impress.md, libs/coin-modules/coin-stacks/src/bridge/estimateMaxSpendable.ts, libs/coin-modules/coin-stacks/src/bridge/prepareTransaction.ts
=> fix: force network when estimating transaction

.github/workflows/test-mobile-e2e-reusable.yml, package.json, turbo.json
Ticket [here](https://ledgerhq.atlassian.net/browse/LIVE-16986)
Runs iOS E2E tests with turbo, using cache if available.
[As mentioned in the ticket](https://ledgerhq.atlassian.net/browse/LIVE-16986?focusedCommentId=521951) the iOS E2E test workflow already has some caching implemented, for the iOS build. This is not implemented via turbo though - separate caching mechanism. For now this PR won't cover the refactor we should make to unify the caching approach.
-----------
Testing has been done against this in [this PR](https://github.com/LedgerHQ/ledger-live/pull/9240)
- ✅ `dependsOn` LLM dependencies' builds via turbo.json (you can see we retrieve these builds from cache [here](https://github.com/LedgerHQ/ledger-live/actions/runs/13334150255/job/37245375356?pr=9240#step:13:23))
- ✅ test …
=> turbo caching for iOS E2E tests

.github/workflows/test-mobile-e2e-reusable.yml, package.json, turbo.json
Identical to https://github.com/LedgerHQ/ledger-live/pull/9247
The part that's relevant to the release process is that it updates package.json to include the E2E iOS test command that `develop`'s E2E mobile test workflow now uses. This fixes [the error in the latest workflow run during release](https://github.com/LedgerHQ/ledger-live/actions/runs/13392188207/job/37402276124?pr=9266)
=> ci: e2e ios depends on dependency builds via turbo

.github/workflows/build-desktop-reusable.yml
Currently successful mac builds are being misreported in certain cases. This fix ensures that the individual build steps fail and the reporting step passes
Partial failure (linux) https://github.com/LedgerHQ/ledger-live/actions/runs/13397330840
Partial failure (mac) https://github.com/LedgerHQ/ledger-live/actions/runs/13397562809
Timeout: https://github.com/LedgerHQ/ledger-live/actions/runs/13397620348/job/37420477018
Problem job: https://github.com/LedgerHQ/ledger-live/actions/runs/13291952727/job/37145026465?pr=9209
=> CI: reliable build desktop failures

.changeset/empty-spies-rhyme.md, apps/ledger-live-mobile/package.json, apps/ledger-live-mobile/src/components/RootNavigator/types/BaseNavigator.ts, apps/ledger-live-mobile/src/components/WebPlatformPlayer/index.tsx, apps/ledger-live-mobile/src/components/WebRecoverPlayer/index.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/screens/Web3HubApp/components/Web3Player/index.tsx, apps/ledger-live-mobile/src/screens/Platform/LiveApp.tsx, apps/ledger-live-mobile/src/screens/Swap/LiveApp/WebView.tsx, libs/ledger-live-common/src/wallet-api/useDappLogic.ts, pnpm-lock.yaml
- ...
To enable swap app LLM deeplinks, two problems needed to be fixed:
- an infinite useEffect loop within the useDappAccountLogic function
- the deeplink parameter has different casing on LLM (`customDappURL`) compared to LLD (`customDappUrl`) 
[LIVE-16730](https://ledgerhq.atlassian.net/browse/LIVE-16730) Prevent infinite useEffect loop on Swap deeplinks 
---
- …
=> feat(LIVE-16730): enable Swap deeplinks on LLM

.changeset/real-buttons-sleep.md, apps/ledger-live-desktop/src/renderer/hooks/useDeeplinking/useDeepLinkHandler.ts
- ...
Extracts Swap parameters `amountFrom`, `fromToken` and `toToken` from ledgerlive://swap deeplinks
[LIVE-17004](https://ledgerhq.atlassian.net/browse/LIVE-17004)
---
[LIVE-17004]: …
=> feat: extract swap parameters from deeplink

.changeset/brave-dancers-kick.md, libs/coin-modules/coin-casper/src/test/bot-specs.ts
- ...
test send ~50% was failing cause the `MIN_SAFE = 2.6` and the minimum amout that a user can send on Casper is `2.5`.
I Change the value to `MIN_SAFE * 2` so test send ~50% while work.
--- …
=> fix: casper bot specs min safe value

apps/ledger-live-desktop/tests/page/swap.page.ts, apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts
- ...
Adding test for swap:
- Checking that the default currency is BTC when landing on swap for the first time
- Checking that the default currency is the same as the set up previously established
- **JIRA or GitHub link**: [qaa-257](https://ledgerhq.atlassian.net/browse/QAA-257)
- **Report**: [link](https://ledger-live.allure.green.ledgerlabs.net/allure/reports/edd675f7-257f-4f76-b078-28cec8d8ea4f/#)
--- …
=> [QAA] adding test - Default currency when landing on swap

.changeset/strange-mirrors-wink.md, libs/coin-modules/coin-tezos/src/api/index.test.ts, libs/coin-modules/coin-tezos/src/api/index.ts, libs/coin-modules/coin-tezos/src/logic/listOperations.test.ts, libs/coin-modules/coin-tezos/src/logic/listOperations.ts, libs/coin-modules/coin-tezos/src/network/types.ts, libs/coin-modules/coin-tezos/src/network/tzkt.ts, libs/coin-modules/coin-xrp/src/api/index.ts
Changes:
- the api retrieves operations from oldest to newest, bypassing explorer limit with iteration over pages 
integration tests: https://github.com/LedgerHQ/ledger-live/actions/runs/13366400373
integration tests (old): https://github.com/LedgerHQ/ledger-live/actions/runs/13200265887
=> fix(coin:tezos): api iterates over all results

turbo.json
Ticket [here](https://ledgerhq.atlassian.net/browse/LIVE-17169)
This should fix the issue from [this run](https://github.com/LedgerHQ/ledger-live/actions/runs/13400303219/job/37429985231).
Hypothesis is that we never saw the above failure in testing because during testing the [allure report step was disabled](https://github.com/LedgerHQ/ledger-live/pull/9240/files#diff-83652d5bf6180c5f87f3117471e890d655448ca914458c7ed9c560937a4b7c63R170). You can see in the test run that the upload of the test artefacts [failed because they did not exist](https://github.com/LedgerHQ/ledger-live/actions/runs/13400303219/job/37429305277#step:15:24).
Therefore, adding that directory to outputs Full description and test PR incoming.
The CI run for this PR indicated that [artefacts were uploaded …
=> Track `ios-test-artifacts` in turbo outputs

tools/github-bot/README.md
Removes the CI/orchestrator section from the github live bot readme as the bot no longer orchestrates CI
=> docs: remove references to ci orchestrator

.changeset/pretty-dolls-marry.md, libs/coin-modules/coin-cardano/src/utils.ts
- ...
Right now Ledger by Figment 3 is the default validator, but it will be full soon.
We put Ledger by Figment 2 as the default one.
- **JIRA or GitHub link**:  [LIVE-17216](https://ledgerhq.atlassian.net/browse/LIVE-17216)
--- …
=> fix: Setup Ledger by Figment two as the default validator

.changeset/soft-kangaroos-call.md, apps/ledger-live-mobile/src/context/LedgerStore.tsx
- ledger store
Rework the way we initialise the ledger store to make it faster. 
Previously, the code was executing promises sequentially using await statements one after another:
```
const bleData = await getBle();
const settingsData = await getSettings();
const cachedCurrencyIds = await listCachedCurrencyIds();
```
This approach was slower as each promise had to complete before the next one could start.
The new implementation uses promise concurrency by starting all promises simultaneously:
```
const {getBle, getSettings, listCachedCurrencyIds} = await Promise.all([
retry(getBle, MAX_RETRIES, RETRY_DELAY),
retry(getSettings, MAX_RETRIES, RETRY_DELAY),
retry(listCachedCurrencyIds, MAX_RETRIES, RETRY_DELAY),
])
```
This way we parallelise promise execution and reduce init time.  Also a …
=> :thread: (llm): optimize launch

tools/actions/composites/adjust-changeset-level/action.yml
[Ticket](https://ledgerhq.atlassian.net/browse/LIVE-17338)
Fixes accidental level hardcoding in the `adjust-changeset-level` internal action that stopped the downgrading of minor ➡️ patch changesets during hotfixes.
This has been tested in [this temporary PR](https://github.com/LedgerHQ/ledger-live/pull/9354), which introduces a [(temporary) test workflow](https://github.com/LedgerHQ/ledger-live/pull/9354/files#diff-6f074678577ec9a56edcf2bf29f9ee5cadd2c4f5dbce2ce862599d6e75e83ef0) that runs the action against several test cases.
When we point the tests to the version of the action on `develop` they fail ([this run](https://github.com/LedgerHQ/ledger-live/actions/runs/13543467439/job/37849584591?pr=9354)), but when we point to the version on this branch they pass ([this …
=> fix accidental level hardcoding in adjust-changeset-level

.changeset/dull-flowers-fry.md, apps/ledger-live-mobile/src/components/KeyboardBackgroundDismiss.tsx, apps/ledger-live-mobile/src/components/KeyboardView.tsx, apps/ledger-live-mobile/src/components/PasswordInput.tsx, apps/ledger-live-mobile/src/context/AuthPass/AuthScreen.tsx, apps/ledger-live-mobile/src/context/AuthPass/auth.hooks.ts, apps/ledger-live-mobile/src/context/AuthPass/index.tsx, apps/ledger-live-mobile/src/screens/Settings/General/PasswordForm.tsx
- keyboardView
- auth password
- add password
This PR mainly fix a bug caused by keyboardavoidingview component on IOS. We need to use behavior = "padding" for some reasons since RN 0.73. The bahavior = "height" leads to an infinite loop on the animation of the keyboard and makes the app freezes 
I've also cleaned a bit the files / components so it's more readable but no logic has changed. For e.g in previous code 
```
onHardReset = () => {
this.props.reboot(true);
};
unlock = () => {
this.setState({
passwordError: null,
password: "",
passwordFocused: false,
isModalOpened: false,
});
};
```
were not used.
The changes on apps/ledger-live-mobile/src/components/KeyboardBackgroundDismiss.tsx has been tested too and has quite low impact because it's used only for authscreen and for rename …
=> :bug: fix(llm) password crash on input focus

.github/workflows/release-create-hotfix.yml, .github/workflows/release-create.yml, .github/workflows/release-prepare-hotfix.yml, .github/workflows/release-prepare.yml, .github/workflows/release-prerelease.yml
Reverts LedgerHQ/ledger-live#9335 - we are seeing an issue where branch protection rules on the `release` branch prevent signed commits being created (all testing was not done on the real `release` branch, so this issue is only coming up now). This is blocking the current release, so reverting until we have figured out a workaround
=> Revert "Verified commits in all remaining parts of the release workflows"

.changeset/few-dryers-smoke.md, apps/ledger-live-mobile/src/screens/Swap/LiveApp/index.tsx
- ...
Now Tabs aren't being used in LLM for Swap, the PanGestureHandler is no longer needed. Removing will reduce false positive gesture recognition for swiping to navigate.  
[LIVE-17351](https://ledgerhq.atlassian.net/browse/LIVE-17351)
--- …
=> feat(LIVE-17351): swap LLM prevent scrolling nav conflict

.changeset/proud-houses-peel.md, apps/ledger-live-mobile/src/context/Locale.tsx, apps/ledger-live-mobile/src/hooks/languages/useSupportedLocales.test.ts, apps/ledger-live-mobile/src/hooks/languages/useSupportedLocales.ts, apps/ledger-live-mobile/src/index.tsx, apps/ledger-live-mobile/src/languages.ts, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/locales/index.ts, apps/ledger-live-mobile/src/locales/th/common.json, apps/ledger-live-mobile/src/screens/Onboarding/steps/language.tsx, apps/ledger-live-mobile/src/screens/Onboarding/steps/welcome.tsx, apps/ledger-live-mobile/src/screens/SyncOnboarding/LanguageSelect.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts, libs/ledgerjs/packages/types-live/src/languages.ts
- Add thai language behind feature flag on the Welcome screen and in the settings
- It will automatically ask to install the language on the device when switching language once provided by the API
- External links fallback to english as they are not yet supported in thai
- When starting the app, it will fallback to english if the user was previously in thai and the FF has been disabled
Thai language added
| Scenario        | Demo         |
| Onboarding |https://github.com/user-attachments/assets/d46d54f8-d625-4765-b376-12ff5160715a|
| Settings |https://github.com/user-attachments/assets/d3cabbc2-f422-4048-ae70-cd753f740c49|
- **JIRA or GitHub link**: [LIVE-17155]
--- …
=> ✨  LLM - Thai language added

.changeset/selfish-meals-stare.md, apps/ledger-live-mobile/src/screens/Platform/exchange/CompleteExchange.tsx, apps/ledger-live-mobile/src/screens/Platform/exchange/StartExchange.tsx
- ...
Prevent navigation.pop called twice on exchange drawer onClose, so close navigates back to Swap
- **JIRA or GitHub link**: [LIVE-17291](https://ledgerhq.atlassian.net/browse/LIVE-17291)
---
[LIVE-17291]: …
=> feat(LIVE-17291): navigate to quotes on drawer cancel

.changeset/large-moles-heal.md, apps/ledger-live-mobile/__tests__/test-renderer.tsx, apps/ledger-live-mobile/src/actions/settings.ts, apps/ledger-live-mobile/src/actions/types.ts, apps/ledger-live-mobile/src/analytics/segment.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Activation/ActivationLoading.tsx, apps/ledger-live-mobile/src/reducers/settings.ts, apps/ledger-live-mobile/src/reducers/types.ts, apps/ledger-live-mobile/src/screens/Onboarding/steps/NoLedgerYetModal.tsx, apps/ledger-live-mobile/src/screens/Onboarding/steps/discoverLiveInfo.tsx, apps/ledger-live-mobile/src/screens/Onboarding/steps/pairNew.tsx, apps/ledger-live-mobile/src/screens/Onboarding/steps/postWelcomeSelection.tsx, apps/ledger-live-mobile/src/screens/Onboarding/steps/welcome.tsx, apps/ledger-live-mobile/src/screens/Settings/Debug/Configuration/ResetOnboardingStateRow.tsx, apps/ledger-live-mobile/src/screens/SyncOnboarding/CompletionScreen.tsx, apps/ledger-live-mobile/src/screens/SyncOnboarding/SyncOnboardingCompanion.tsx, apps/ledger-live-mobile/src/screens/SyncOnboarding/__integrations__/completionScreen.integration.test.tsx
- onboarding
- reborn
Add a new selector isReborn to track if the user is in reborn and if he has a device during the onboarding. 
(Schema bellow is a quick representation since there is specific flow depending of the device etc )
- **JIRA or GitHub link**: [LIVE-17091](https://ledgerhq.atlassian.net/browse/LIVE-17091)
---
- …
=> :chart_with_upwards_trend: (llm) enhance reborn analytics

tools/github-bot/src/features/autoClose/index.ts
https://ledgerhq.atlassian.net/browse/LIVE-17102
The [last PR](https://github.com/LedgerHQ/ledger-live/pull/9301) to attempt to auto-close smartling PRs didn't work. I suspected the app's login name wasn't correct, so set up [a proxy using smee](https://smee.io/ITmIQR5eaI2DeydR) and fired some github webhooks at it as I manually closed and reopened a smartling PR. This revealed the real `login` value for the smartling github app, which is updated in this PR.
=> ci: update github app login, to real value this time

.changeset/gentle-icons-shave.md, libs/coin-framework/src/derivation.ts, libs/coin-modules/coin-aptos/src/test/bridgeDatasetTest.ts, libs/ledger-live-common/src/DataModel.test.ts, libs/ledger-live-common/src/DataModel.ts, libs/ledger-live-common/src/families/aptos/__snapshots__/bridge.integration.test.ts.snap, libs/ledger-live-common/src/families/aptos/consts.ts, libs/ledgerjs/packages/hw-app-aptos/README.md, libs/ledgerjs/packages/hw-app-aptos/src/Aptos.ts, libs/ledgerjs/packages/hw-app-aptos/src/bip32.ts, libs/ledgerjs/packages/hw-app-aptos/tests/bip32.test.ts, libs/ledgerjs/packages/types-live/src/derivation.ts
Fix aptos derivation path to match nano app behavior
Path was previously unhardened in metadata, now it's hardened (actual device app derivation)
- **JIRA or GitHub link**: [https://ledgerhq.atlassian.net/browse/LIVE-17309](https://ledgerhq.atlassian.net/browse/LIVE-17309)
--- …
=> fix: aptos derivation path account metadata

.changeset/sharp-llamas-begin.md, libs/coin-modules/coin-evm/docs/evm-family-integration-process/README.md
- ...
The documentation claims that the naming convention for SVGs representing cryptoassets is `<currency_id>.svg`, when it is actually `<currency_ticker>.svg`.
---
=> doc (coin-evm): fix misleading doc on SVG naming convention

.changeset/famous-jobs-sort.md, libs/coin-modules/coin-evm/src/__tests__/unit/preload.unit.test.ts, libs/coin-modules/coin-evm/src/preload.ts
- Add account token listing
Update expected type for the evm hydrate function to check all possible types for value
It also aligns better with the currencyBridge type for hydrate
- **JIRA or GitHub link**:  [LIVE-17507]
--- …
=> fix: potential wrong type for the hydrate value [LIVE-17507]

.github/workflows/release-create-hotfix.yml, .github/workflows/release-create.yml, .github/workflows/release-prepare-hotfix.yml, .github/workflows/release-prepare.yml, .github/workflows/release-prerelease.yml
Hopefully the final PR for https://ledgerhq.atlassian.net/browse/LIVE-17241
- Reverts LedgerHQ/ledger-live#9389
- Uses the live-github-bot installation token instead of the generic GITHUB_TOKEN to sign commits. This creates commits signed as `live-github-bot`. `live-github-bot` is exempt from the branch protections that blocked commits made from the generic `github-actions[bot]` user.
Creating (verified) commits as live-github-bot is demonstrated in [this test PR](https://github.com/LedgerHQ/ledger-live/pull/9409), which creates several commits with several different methods in a separate branch. These commits can be viewed here: https://github.com/LedgerHQ/ledger-live/compare/develop...commit-test-branch (see commit 23b253bbbea90f0a604149cdb7933bd710580000, which was generated from the …
=> Re-implement verified commits in all remaining parts of the release workflows

.github/workflows/release-create.yml
- ...
Remove sortByMarketCap update during the release process as we don't rely on the snapshot anymore.
---
=> fix: remove sortbymarketcap snapshot update in release workflow

.changeset/tame-fans-perform.md, apps/ledger-live-desktop/src/newArch/features/LedgerSyncEntryPoints/components/SettingsEntryPoint/index.tsx
- ...
Overflow in Settings for LedgerSync Entry point when text is too long (German or French Maybe)
Before
After
https://github.com/user-attachments/assets/a5610976-b88c-43ce-a023-96046d2b1184
- **JIRA or GitHub link**: [LIVE-17545] 
--- …
=> fix: Fix Overflow in Settings for LedgerSync Entry point

.changeset/tasty-eggs-retire.md, libs/coin-modules/coin-tezos/src/logic/listOperations.test.ts, libs/coin-modules/coin-tezos/src/logic/listOperations.ts
Tezos tx fee is now the sum of storageFee + bakerFee + allocationFee
instead of just storageFee
tests: https://github.com/LedgerHQ/ledger-live/actions/runs/13541173128
=> fix(coin:tezos): compute operation fees

.github/workflows/temp-log-pr-event.yml
[Ticket](https://ledgerhq.atlassian.net/browse/LIVE-17102)
Adds temporary workflow for dissecting the PR event for Smartling PRs, following on from difficulties getting the [autoClose](https://github.com/LedgerHQ/ledger-live/blob/develop/tools/github-bot/src/features/autoClose/index.ts) feature to target smartling PRs successfully.
Will be removed by me  by end of March 2025
=> ci: temporarily log out PR event attributes for smartling PRs

libs/coin-modules/coin-tezos/src/logic/listOperations.test.ts
- ...
just a follow up after comment of previous pr https://github.com/LedgerHQ/ledger-live/pull/9194/files#r1987253571
=> fix(coin:tezos): better test labels

.changeset/great-mayflies-return.md, apps/ledger-live-mobile/src/screens/Platform/exchange/StartExchange.tsx
- ...
Removes large padding around Device Selection page used by Swap.
| ![image](https://github.com/user-attachments/assets/298c4665-a8d7-447e-aaf5-3cac4efbec30) | ![image](https://github.com/user-attachments/assets/b710760c-fc37-4007-853c-f0fbb6a631bb) |
| ![image](https://github.com/user-attachments/assets/2056c67d-1f2e-45ce-a269-5f4a19ef5028) | ![image](https://github.com/user-attachments/assets/b02b5adc-9552-4aa5-8a97-c41368a04335) |
- **JIRA or GitHub link**: [LIVE-17499](https://ledgerhq.atlassian.net/browse/LIVE-17499)
--- …
=> fix(LIVE-17499) Swap connect device too small

.changeset/mean-numbers-smell.md, package.json, pnpm-lock.yaml
Coin Integration:
And all coin modules using node-libs-react-native
Live Hub:
PTX Swap:
Upgrade elliptic dependency.
`pnpm why elliptic -r --parseable`
```
/apps/cli
/libs/coin-modules/coin-bitcoin
/libs/ledgerjs/packages/hw-app-btc
/libs/hw-ledger-key-ring-protocol
/libs/ledger-key-ring-protocol
/node_modules/.pnpm/bip32@2.0.6/node_modules/bip32
/node_modules/.pnpm/bitcoinjs-lib@5.2.0/node_modules/bitcoinjs-lib
/node_modules/.pnpm/elliptic@6.6.1/node_modules/elliptic
/node_modules/.pnpm/secp256k1@4.0.3/node_modules/secp256k1
/node_modules/.pnpm/secp256k1@5.0.0/node_modules/secp256k1
/node_modules/.pnpm/tiny-secp256k1@1.1.6/node_modules/tiny-secp256k1
/node_modules/.pnpm/tiny-secp256k1@1.1.7/node_modules/tiny-secp256k1
/apps/ledger-live-desktop …
```
=> fix: elliptic pinned to 6.6.1

.changeset/stupid-fans-push.md, apps/ledger-live-desktop/src/renderer/modals/SignMessage/steps/StepSummary.tsx
- wallet-api signMessage modal
We introduced an UI regression in https://github.com/LedgerHQ/ledger-live/pull/9158
It didn't use the theme correctly
We now use the proper button from the design system to match the figma instead of editing the styles of the old button
| Light theme       | Dark theme         |
| <img width="525" alt="Screenshot 2025-03-14 at 08 23 55" src="https://github.com/user-attachments/assets/86acef46-9e89-4c00-bc84-dbebb2b0eea4" />  | <img width="520" alt="Screenshot 2025-03-14 at 08 24 19" src="https://github.com/user-attachments/assets/a4c1b4f8-35ba-41e2-b6e6-3126d46d8d70" /> |
- **JIRA or GitHub link**: [LIVE-17617]
---
- **The PR …
=> fix(wallet-api): signMessage modal continue button not visible with light theme [LIVE-17617]

.changeset/weak-frogs-taste.md, apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/index.tsx
- live-apps
Setting a key to reset the states of the component when we change manifest to get the transition animation to work on page load
- **JIRA or GitHub link**: [LIVE-17717]
---
[LIVE-17717]: …
=> fix: wallet-api transition animation between live-apps [LIVE-17717]

.changeset/nine-tables-smile.md, apps/ledger-live-desktop/src/newArch/features/Collectibles/Nfts/components/DetailDrawer/index.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/Nfts/components/TokensList/index.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/Nfts/components/TokensList/useTokensListModel.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/components/DetailDrawer/index.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/types/TokensList.ts
- detail drawer
Small animation fix. Animation wasn't triggered because te parent component of the side drawer was unmounted. This was done like this to avoid ts issue. Instead we should define a tokenId by default (the first of the list) so we ensure tokenId is never undefined. This way the sidedrawer always exists and appears with all the animations
|https://github.com/user-attachments/assets/433b2042-3f71-4c07-a06f-f69a40b97323|https://github.com/user-attachments/assets/de886ec6-90de-4e59-8681-6a53539a3407|
- **JIRA or GitHub link**: NO NEED 
--- …
=> :lipstick: (lld) drawer animation nft gallery

.changeset/ten-cherries-carry.md, apps/ledger-live-desktop/src/config/urls.ts, apps/ledger-live-desktop/src/renderer/hooks/useLocalizedUrls/useLocalizedUrls.test.tsx, apps/ledger-live-mobile/src/languages.ts, apps/ledger-live-mobile/src/newArch/hooks/useLocalizedUrls/index.ts, apps/ledger-live-mobile/src/newArch/hooks/useLocalizedUrls/useLocalizedUrls.test.tsx, apps/ledger-live-mobile/src/screens/Settings/Resources.tsx, apps/ledger-live-mobile/src/utils/urls.tsx, libs/ledger-live-common/.unimportedrc.json, libs/ledger-live-common/src/hooks/useLocalizedUrl.test.ts, libs/ledger-live-common/src/hooks/useLocalizedUrl.ts
- ...
Rework useLocalizedUrl hook to be centralised in live-common
- fix some edge case ("thai" was not handled correclty)
- some url were broken
- Fix LedgerAcademy and support url localisation
https://github.com/user-attachments/assets/443ca9c6-e41f-417e-9bae-db37a15b82a4
- **JIRA or GitHub link**: [LIVE-17680]
--- …
=> feat: Improve useLocalizedUrl & fix Support/Academy rediction with url localized

.changeset/sharp-snails-fetch.md, apps/ledger-live-mobile/src/screens/ReceiveFunds/02-SelectNetwork.tsx
- receive flow select network
Adjust the animation of the network banner on receive flow (select network).
I've imported the animation used in newArch to have the same one. Since this screen will me be migrated a day to the new one (the one inside new arch) it's not necessary to move the hook and the networkBanner.
|https://github.com/user-attachments/assets/28e39f8b-7272-410a-96a9-a0269cbd2652|https://github.com/user-attachments/assets/ca0f4b41-b1d6-47e1-a738-48ddbb4c43c3| 
- **JIRA or GitHub link**: [LIVE-17759](https://ledgerhq.atlassian.net/browse/LIVE-17759)
--- …
=> :bug: (llm) network banner animation receive flow

.changeset/slimy-elephants-itch.md, apps/ledger-live-desktop/src/newArch/features/LNSUpsell/__tests__/LNSUpsellBanner.test.tsx, apps/ledger-live-desktop/src/newArch/features/LNSUpsell/hooks/useLNSUpsellBannerState.ts, apps/ledger-live-mobile/src/newArch/features/LNSUpsell/components/LNSUpsellBanner/LNSUpsellBanner.test.tsx, apps/ledger-live-mobile/src/newArch/features/LNSUpsell/hooks/useLNSUpsellBannerState.ts
- ...
The LNS upsell banner should still be displayed for opt out users with 2 or more swaps on LLD and LLM.
- **JIRA or GitHub link**: [LIVE-15816] and [LIVE-15849]
---
[LIVE-15816]: …
=> fix: 🎯 target LNS opt out users with many swaps with the upsell campaign

.changeset/pretty-lies-itch.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/Market/screens/MarketDetail/components/MarketGraph/index.tsx, apps/ledger-live-mobile/src/newArch/features/Market/screens/MarketList/components/BottomSection/index.tsx, libs/ledger-live-common/src/market/utils/rangeDataTable.ts
- ...
Bugfix: Standardize Timeframe Display on Portfolio & Market Page Charts -LLM
- **JIRA or GitHub link**: [LIVE-17704]
https://github.com/user-attachments/assets/158f0d51-d4b4-4117-bf29-efd6c7e76dd9
--- …
=> Bugfix: Standardize Timeframe Display on Portfolio & Market Page Charts -LLM

.changeset/heavy-stingrays-ring.md, apps/ledger-live-desktop/src/renderer/families/evm/AccountHeaderManageActions.ts, apps/ledger-live-desktop/src/renderer/families/evm/StakeFlowModal/EthStakingModalBody.tsx, apps/ledger-live-desktop/src/renderer/families/evm/StakeFlowModal/index.tsx, apps/ledger-live-desktop/src/renderer/families/evm/StakeFlowModal_deprecated/EthStakingModalBody.tsx, apps/ledger-live-desktop/src/renderer/families/evm/StakeFlowModal_deprecated/index.tsx, apps/ledger-live-desktop/src/renderer/families/evm/modals.ts, apps/ledger-live-desktop/src/renderer/modals/Receive/steps/StepReceiveFunds.tsx, apps/ledger-live-mobile/src/families/evm/StakingDrawer/EvmStakingDrawerBody.tsx, apps/ledger-live-mobile/src/families/evm/accountActions.tsx
- Account passed to dapps VS account passed to dapp browser v2
This PR fixes a bug where when opening a dapp from eth staking modal (drawer in LLM) the wrong account was selected. It now passes a LL account id to a dapp and a wallet api account id to dapp browser v2 as it uses the wallet api.
- **JIRA or GitHub link**: [LIVE-17649](https://ledgerhq.atlassian.net/browse/LIVE-17649)
---
- **Any new …
=> LIVE-17649: Fix dapp opening from staking modal(drawer in LLM)

.changeset/chilly-cups-perform.md, apps/ledger-live-mobile/src/screens/Account/ListHeaderComponent.tsx, apps/ledger-live-mobile/src/screens/Account/__tests__/nftHelper.test.ts, apps/ledger-live-mobile/src/screens/Account/index.tsx, apps/ledger-live-mobile/src/screens/Account/nftHelper.ts
- ...
Display Solana Collections when FF is ON, hidden when FF OFF 
- The wording will be automatically replace the placeholder with Solana instead of Eth when collections are empty
https://github.com/user-attachments/assets/eb2ca7c3-fbff-4024-987a-62d62e2c8b85
- **JIRA or GitHub link**: [LIVE-17561] 
--- …
=> feat: Display Collections for Solana in Account Page under FF 🔧

.changeset/fast-balloons-type.md, apps/ledger-live-mobile/src/screens/Nft/NftGallery/index.tsx
- ...
Conditional expression that evaluates whether the "Send" button should be displayed, based on two conditions:
`account.currency.id !== "solana"`: The button is shown if the account's currency is not Solana (i.e., the currency is something other than Solana).
`llmSolanaNftsEnabled`: If Solana NFTs are enabled, this part of the expression is true, and the button will be shown regardless of the currency.
https://github.com/user-attachments/assets/b327a27d-371f-4555-98ca-efd2bfe9a559
- **JIRA or GitHub link**: [LIVE-17570] 
--- …
=> feat: Hide send button in NFT gallery Account for Solana

.changeset/ninety-wombats-wonder.md, libs/coin-modules/coin-solana/jest.config.js, libs/coin-modules/coin-solana/package.json, libs/coin-modules/coin-solana/src/__tests__/fixtures/helpers.fixture.ts, libs/coin-modules/coin-solana/src/__tests__/scan-accounts.test.ts, libs/coin-modules/coin-solana/src/api/cached.ts, libs/coin-modules/coin-solana/src/api/chain/index.ts, libs/coin-modules/coin-solana/src/api/chain/stake-activation/index.ts, libs/coin-modules/coin-solana/src/api/chain/stake-activation/rpc.ts, libs/coin-modules/coin-solana/src/estimateMaxSpendable.ts, libs/coin-modules/coin-solana/src/synchronization.ts, libs/coin-modules/coin-solana/src/utils.ts, pnpm-lock.yaml
- ...
The scan account operation for Solana is particularly slow in Ledger Live. One reason is that quite a lot of HTTP requests are done sequentially to list token and staking accounts, as well as fetching all the transactions.
This PR focuses on re-writing this part, grouping RPC requests together or running them asynchronously when possible.
---
- **Any new …
=> fix(llm,lld): improve Solana scan accounts performances

.changeset/gold-cars-knock.md, libs/coin-modules/coin-solana/src/prepareTransaction.ts
- ...
When staking Solana on LLM, the Nano X may disconnect at step 2 of 3 while confirming the transaction. After reconnecting, the **"Delegate From"** address shown on LLM changes, while the address on the Nano X remains the same, causing a mismatch.
Avoid updating the transaction when one is already prepared for the `stake.createAccount` SOL action.
- **JIRA**: https://ledgerhq.atlassian.net/browse/LIVE-13341
--- …
=> fix: sol staking delegate from-address

.changeset/grumpy-cherries-know.md, libs/ledger-live-common/src/exchange/swap/hooks/v5/useFilteredProviders.ts, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
Reverts LedgerHQ/ledger-live#9482
Exodus should not appear, even after removing this flag. Currently it does.
=> Revert "feat(LIVE-17514): remove unused Swap feature flags"

apps/ledger-live-desktop/tests/page/swap.page.ts, apps/ledger-live-desktop/tests/specs/speculos/delegate.spec.ts
=> [QAA Updating delegate and swap e2e tests

.changeset/gold-walls-kiss.md, apps/ledger-live-mobile/src/components/Delta.tsx, apps/ledger-live-mobile/src/newArch/features/Market/components/DeltaVariation/index.tsx
- [ x] `npx changeset` was attached.
- ...
buggfix: '-' with neutral color displayed for 0% variation in market and asset list
- **JIRA or GitHub link**: [LIVE-15671]
---
[LIVE-15671]: …
=> Buggfix: '-' with neutral color displayed for 0% variation in market and asset list

.changeset/kind-carrots-fix.md, apps/ledger-live-mobile/src/locales/en/common.json
- ...
We want to be consistent by displaying what Flex and Stax are displaying when we confirm an address. Actually, they display 'confirm', and now in llm, we display 'approve'. So we just need to change that.
- **JIRA**: https://ledgerhq.atlassian.net/browse/LIVE-17676
--- …
=> change validate address wording

.changeset/afraid-wasps-sing.md, libs/coin-modules/coin-solana/src/api/chain/index.ts
- Solana add account, send/receive and sync
[ky default timeout of 10s](https://github.com/sindresorhus/ky#timeout) was creating errors on our automated tests and could create issues if the node has a lot of latency
We disable it for now but we should probably default to some timeout at some point
- **JIRA or GitHub link**: [LIVE-17918]
--- …
=> fix: disable ky default timeout with solana coin [LIVE-17918]

apps/ledger-live-desktop/tests/specs/speculos/ledgerSync.spec.ts, apps/ledger-live-desktop/tests/utils/ledgerSyncCliUtils.ts
- ...
To avoid failures during execution due to a trust chain that was not properly destroyed when a test fails, the trust chain should be created and then destroyed at the beginning of the script to ensure a fresh new trust chain.
--- …
=> Delete trustchain before starting synchronisation

.changeset/hungry-balloons-grin.md, apps/ledger-live-desktop/src/renderer/modals/Send/steps/Confirmation/NodeError/TechnicalErrorSection.tsx, apps/ledger-live-desktop/src/renderer/modals/Send/steps/Confirmation/NodeError/index.tsx
- ...
Fix the error layout.
|  <img width="539" alt="Screenshot 2025-03-26 at 18 22 38" src="https://github.com/user-attachments/assets/0923d6de-2699-4269-8ba3-b2211a7dcf46" />      |   <img width="539" alt="Screenshot 2025-03-26 at 19 11 22" src="https://github.com/user-attachments/assets/ffe80d04-af1b-40b6-a027-4d22085f029d" />         |
- **JIRA or GitHub link**: [LIVE-17745]
--- …
=> fix(lld): 🐛 prevent long technical errors from breaking the node error layout

.changeset/pink-lamps-warn.md, apps/ledger-live-mobile/e2e/helpers.ts, apps/ledger-live-mobile/ios/ledgerlivemobile/AppDelegate.mm
- ✨ IOS Launchscreen ✨ 
Non animated splashscreen until the swift module is ready. (https://github.com/LedgerHQ/ledger-live/pull/9592)
ByPass the splashscreen during e2e tests so it doesn't duplicate WS. 
https://github.com/user-attachments/assets/53d5105e-3c7a-4f13-af38-efa8602b788a
Detox test
https://github.com/user-attachments/assets/224097be-34c0-4673-835e-0058b96ff3be
- **JIRA or GitHub link**:[LIVE-17159](https://ledgerhq.atlassian.net/browse/LIVE-17159) 
--- …
=> :bug: (ios) reintegrate splashscreen

.changeset/twelve-jokes-admire.md, libs/coin-modules/coin-stellar/src/network/serialization.ts
- ...
This partially reverts https://github.com/LedgerHQ/ledger-live/pull/9584.
The way operation identifiers are built has changed (using Stellar transaction `id`), whereas new operations continue to use the old way (using Stellar transaction `hash`).
--- …
=> fix (coin-stellar): operation identifiers are wrong

libs/ledger-live-common/jest.config.ts
We had a small issue with the transform path regex on the jest config for common that was not working on windows
---
=> chore: fix windows test

apps/ledger-live-desktop/src/main/window-lifecycle.ts
LedgerLive user agent not present in dev mode by adding it when we start the mainWindow of electron and when a webview is attached to the window
- **JIRA or GitHub link**: [LIVE-17642]
---
[LIVE-17642]: …
=> fix(LLD): LedgerLive user agent not present in dev mode [LIVE-17642]

.changeset/little-emus-act.md, .changeset/wicked-otters-smile.md, apps/ledger-live-mobile/src/screens/SyncOnboarding/CompletionScreen.tsx, apps/ledger-live-mobile/src/screens/SyncOnboarding/EuropaCompletionView.tsx, apps/ledger-live-mobile/src/screens/SyncOnboarding/SyncOnboardingCompanion.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts
- Sync onboarding redirection.
The issue seems to be that `onAnimationFinished` captures the first function passed to it, and in that case it was capturing an early `navigation` object which was probably invalid.
PS: also noticed that there was an issue regarding the `deviceInitialApps`: its default value was `enabled: false` and the behavior of the SyncOnboarding was not taking that value into account.
- **JIRA or GitHub link**: [LIVE-17848] 
--- …
=> [LIVE-17848] fix(onboarding): redirection at the end (for Flex)

.changeset/wild-books-act.md, apps/ledger-live-desktop/src/renderer/hooks/useAutoRedirectToPostOnboarding/index.ts, apps/ledger-live-desktop/src/renderer/hooks/useDeeplinking/useDeepLinkHandler.ts, apps/ledger-live-desktop/src/renderer/screens/dashboard/index.tsx
After the onboarding, when clicking the `close` button, it was displaying the Portfolio before the PostOnboarding. It was caused by a re-routing called during the `Dashboard` rendering. So, it was logically processing, first the `Dashboard` rendering and then the one from the component provided by the re-routing. 
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-17336
---
- …
=> fix(lld): unwanted rendering when clicking the 'close' button from the recover screen just after onboarding

.changeset/tiny-spies-march.md, apps/ledger-live-mobile/src/screens/Swap/LiveApp/WebView.tsx, apps/ledger-live-mobile/src/screens/Swap/LiveApp/hooks/useTranslateToSwapAccount.ts
- ...
When the mobile Swap view loads, the accounts available at the time should be used to deduce an available default account.  Further updates to the available accounts should not be used to prevent changing the Swap URL params while it's open.
- **JIRA or GitHub link**: [LIVE-17796](https://ledgerhq.atlassian.net/browse/LIVE-17796)
---
- **The code …
=> feat(LIVE-17796): Swap LLM should only reference accounts on initial load

.changeset/breezy-birds-cheat.md, apps/ledger-live-mobile/package.json, apps/ledger-live-mobile/src/polyfill.ts, pnpm-lock.yaml
- ...
Broadcasting a token transaction in Stellar is simply failing in LLM. This is because the Stellar SDK makes some buffer deserializations of the transaction signature, which don't work well in React Native.
As an example, sending `"USDC"` is perceived as sending `"85,83,68,67"` (stringified version of its `Uint8Array`) and fails when entering https://github.com/stellar/js-stellar-base/blob/68b8bae058b2d62b4b65fbee66b2e3945b836111/src/asset.js#L20-L24
We add (another 😞) polyfill to patch this.
--- …
=> fix (llm): patch hermes typed arrays

apps/ledger-live-mobile/src/screens/Platform/exchange/StartExchange.tsx
- ...
Add a top margin on the StartExchange screen in order to not have multiple lines stuck together and improve readability.
| ![Screenshot 2025-03-28 at 07 46 07](https://github.com/user-attachments/assets/ce79f644-d031-4002-bfa4-556fd949818d) | ![Screenshot 2025-03-28 at 07 45 39](https://github.com/user-attachments/assets/96bb1baa-5c62-4789-802e-0febb2742004) |
[- **JIRA or GitHub link**: 
](https://ledgerhq.atlassian.net/browse/LIVE-17937)
--- …
=> fix(LIVE-17937): add margin to top of StartExchange screen

.changeset/dry-buses-switch.md, apps/ledger-live-desktop/src/renderer/families/evm/nft.ts
- EVM nft send
We should only check for `transaction.mode === "send"` when we don't have an `NFTStandard` passed in
- **JIRA or GitHub link**: [LIVE-18005]
---
[LIVE-18005]: …
=> fix: error thrown in the wrong case [LIVE-18005]

.changeset/tall-crabs-jump.md, libs/live-countervalues/src/__snapshots__/portfolio.test.ts.snap, libs/live-countervalues/src/portfolio.ts, package.json
- ...
Given a range sufficiently large the user would have not owned any tokens. So the "ALL" range will always start with the user owning 0 of a given token. When the user owns some of it the trend would be infinite (nothing to something). Up to know this was addressed by not displaying the trend in this case.
Now the trend will be calculated starting from the first tokens received/purchased by the user:
|     <video src="https://github.com/user-attachments/assets/4e366682-cea6-4316-b6c0-e38209f57c31" />          |    <video src="https://github.com/user-attachments/assets/e006273c-ccfd-4c0a-96eb-b30dc9556564" />           |
- **JIRA or GitHub link**: [LIVE-16965]
---
- **The code aligns with the requirements** described …
=> fix: 🐛 trend on range pre-dating owning an asset

.changeset/empty-gifts-care.md, apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx, apps/ledger-live-mobile/src/screens/Analytics/Operations/OperationsList.tsx, apps/ledger-live-mobile/src/screens/WalletCentricSections/OperationsHistory/OperationRowContainer.tsx, apps/ledger-live-mobile/src/screens/WalletCentricSections/OperationsHistory/OperationsHistoryList.tsx
- tx history
- operation navigation
We had an issue regarding tx history because we didn't check the subaccounts of an account. That's why we have the issue on Eth, Sol and evms etc ... 
Also we were displaying "received" or "send" if there was only one parent account. But this can be confusing if there is subAccount.
+ Change weird navigation
+ Fix non respected eslint rule
https://github.com/user-attachments/assets/145f6469-c205-4a3a-81ba-128ec92b21e5
- **JIRA or GitHub link**: [LIVE-17251](https://ledgerhq.atlassian.net/browse/LIVE-17251)
--- …
=> :bug: (llm) tx history preview

.changeset/afraid-avocados-kneel.md, libs/coin-framework/src/utils.test.ts, libs/coin-framework/src/utils.ts
- ...
For very big numbers, .toString returned scientific notation. Conversion to bigint failed in that situation
[LIVE-17987]
---
[LIVE-17987]: https://ledgerhq.atlassian.net/browse/LIVE-17987?atlOrigin=eyJpIjoiNWRkN …
=> fix(live-17987): convert bignumber to big int

.changeset/lemon-geese-admire.md, apps/ledger-live-mobile/src/components/Nft/NftViewer.tsx
- ...
layout issue when no send button in NFTViewer
Before
After
---
=> bugfix: layout issue when no send button in NFTViewer

.changeset/twenty-camels-hammer.md, apps/ledger-live-mobile/src/components/WebPTXPlayer/index.tsx, apps/ledger-live-mobile/src/screens/PTX/index.tsx
- ...
Adds the query param 'softExit' WebPTXPlayer so that deeplinks opening WebPTXPlayers (eg Swap opening Buy) can specify the close should navigate back to Swap. 
| Without softExit param        | With softExit param         |
| ![Kapture 2025-03-28 at 11 14 59](https://github.com/user-attachments/assets/a6aa1aa6-791c-4550-bbee-672681f16ca6)  close navigates back to home |  ![Kapture 2025-03-28 at 11 13 05](https://github.com/user-attachments/assets/d26bc50e-3d67-4dff-8250-301496fd444a) close navigates back to previous screen |
- **JIRA or GitHub link**: [LIVE-17932](https://ledgerhq.atlassian.net/browse/LIVE-17932)
--- …
=> feat(LIVE-17932): softExit WebPTX parameter

.changeset/nasty-waves-march.md, libs/coin-modules/coin-solana/src/api/chain/index.ts
- ...
Default request behavior made through ky skipped retrying on POST request, problem is all solana requests are made using POST requests. 
- **JIRA or GitHub link**: LIVE-17972
---
=> fix: retry behavior set for post requests within solana calls

.changeset/short-seahorses-burn.md, apps/ledger-live-mobile/src/components/Graph/BarInteraction.tsx, apps/ledger-live-mobile/src/components/Graph/index.tsx
Previously the graph pointer was displayed with a slight offset on the y-axis. This was caused by a static offset applied to the svg `viewBox`. Now the svg view box is set with dynamic component properties also applied to the graph pointer component for an accurate calculation of its cartesian coordinates.
|   ![before](https://github.com/user-attachments/assets/fe82103d-a2c2-4dab-8e24-63065d09c002) | ![after](https://github.com/user-attachments/assets/c0b4ad53-eac8-409d-a32b-abf2e06ecf36) |
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-18025
--- …
=> fix(llm): calculate cartesian coordinates of the graph pointer more accurately

apps/ledger-live-desktop/tests/page/swap.page.ts, apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts, apps/ledger-live-desktop/tests/userdata/speculos-tests-app.json, libs/ledger-live-common/src/e2e/speculos.ts
- ...
- Following the activation of the feature flag `config_nanoapp_ethereum`, we needed to update the nano app used for our Binance Smart Chain and Polygon tests.
- Updated the minimum amount for USDT => BTC swap.
- **JIRA or GitHub link**: [QAA-529](https://ledgerhq.atlassian.net/browse/QAA-529)
- **CI**: [RUN](https://github.com/LedgerHQ/ledger-live/actions/runs/14222684993)
---
- **Any new …
=> [QAA] Fix e2e apps for release testing 

.changeset/cyan-chairs-rest.md, apps/ledger-live-mobile/src/components/Web3AppWebview/PlatformAPIWebview.tsx, apps/ledger-live-mobile/src/components/Web3AppWebview/WalletAPIWebview.tsx
- almost all webviews on mobile, so discover, earn, buy, swap and others
LLM was not setting a userAgent like LLD is doing automatically for the webviews so we're adding it here for mobile
- **JIRA or GitHub link**: [LIVE-18142]
--- …
=> fix: missing LedgerLive userAgent on LLM webview [LIVE-18142]

.changeset/loud-apples-own.md, libs/coin-modules/coin-stellar/src/api/index.integ.test.ts, libs/coin-modules/coin-stellar/src/api/index.ts
- ...
This is a regression from LedgerHQ/ledger-live#9466, `memo` is ignored when crafting stellar transactions through coin modules API.
Note: stellar tests are skipped, I ran them manually
https://ledgerhq.atlassian.net/browse/LIVE-18007
--- …
=> fix(LIVE-18007): fix stellar coin-module ignoring `memo` craft parameter

.changeset/pink-icons-talk.md, libs/ledgerjs/packages/cryptoassets/src/currencies.ts
- ...
EVM chains using Blockscout as source will also use Blockscout to construct explorer URLs. Chains impacted:
- arbitrum
- cronos
- flare
- songbird
- rsk
- optimism
- optimism sepolia
- energy web
- astar
- metis
- velas
- syscoin
- polygon zk evm
- base
- base sepolia
- neon
- lukso
- blast
- blast sepolia
- scroll
- scroll sepolia
- etherlink
- zk sync
- zk sync sepolia
- **JIRA or GitHub link**: [LIVE-17751](https://ledgerhq.atlassian.net/browse/LIVE-17751)
--- …
=> feat: update currencies list with Blockscout explorer links

.changeset/thin-garlics-fail.md, apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/PlatformAPIWebview.tsx, apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/WalletAPIWebview.tsx, apps/ledger-live-desktop/src/renderer/modals/ExchangeDeviceConfirm/index.tsx
- not much live-app that use the `account.receive`
`account.receive` doesn't resolve when dismissing the modal on desktop
https://github.com/user-attachments/assets/b1322933-8644-4c36-87cc-d0f779a798ed
- **JIRA or GitHub link**: [LIVE-18234]
--- …
=> fix(wallet-api): account.receive doesn't resolve when dismissing the modal [LIVE-18234]

.changeset/calm-beans-grow.md, .changeset/cool-suits-tell.md, apps/ledger-live-mobile/src/components/BleDevicePairingFlow/index.tsx, apps/ledger-live-mobile/src/components/RequiresBLE/hooks/useEnableBluetooth.ts, apps/ledger-live-mobile/src/components/SelectDevice2/index.tsx, apps/ledger-live-mobile/src/index.tsx, apps/ledger-live-mobile/src/screens/PairDevices/Scanning.tsx, apps/ledger-live-mobile/src/screens/PairDevices/index.tsx, libs/live-dmk-desktop/vitest.config.ts, libs/live-dmk-mobile/src/hooks/index.ts, libs/live-dmk-mobile/src/hooks/useDeviceManagementKit.test.tsx, libs/live-dmk-mobile/src/hooks/useDeviceManagementKit.tsx, libs/live-dmk-mobile/src/hooks/useLdmkFeatureEnabled.test.tsx, libs/live-dmk-mobile/src/hooks/useLdmkFeatureEnabled.ts, libs/live-dmk-mobile/vitest.config.ts
- ...
On feature flag switch, app should not reload automatically and new chosen transport should work as expected after manual restart (kill/relaunch)
- **JIRA or GitHub link**: [DSDK-724] 
---
[DSDK-724]: …
=> 🚑 (llm) [DSDK-724]: Handle ldmkTransport feature flag switch

.changeset/fresh-fans-fetch.md, .changeset/rare-apes-appear.md, libs/ledger-live-common/src/apps/config.ts, libs/ledgerjs/packages/hw-app-btc/src/constants.ts, libs/ledgerjs/packages/hw-app-btc/src/createTransaction.ts, libs/ledgerjs/packages/hw-app-btc/src/getTrustedInput.ts, libs/ledgerjs/packages/hw-app-btc/src/serializeTransaction.ts, libs/ledgerjs/packages/hw-app-btc/src/splitTransaction.ts, libs/ledgerjs/packages/hw-app-btc/src/startUntrustedHashTransactionInput.ts, libs/ledgerjs/packages/hw-app-btc/src/types.ts, libs/ledgerjs/packages/hw-app-btc/tests/createTransaction.test.ts, libs/ledgerjs/packages/hw-app-btc/tests/splitTransaction.test.ts
~~MOVED TO: https://github.com/LedgerHQ/ledger-live/pull/9897~~
NOTE: assuming no backward compatibility and just enforcing minappversion to `2.3.2`
- ...
Goal:
Refactor and fix Zcash consensus branch ID computation in LedgerJS Bitcoin app, to properly handle multiple Zcash network upgrades (NU6, NU5, etc.), and improve transaction versioning & serialization for Zcash.
Goes hand in hand with: https://github.com/LedgerHQ/app-zcash/compare/develop...LedgerHQ:app-zcash:fix/apa/anotherone
- Branch IDs by Height
Old: single constant ZCASH_NU6_ACTIVATION_HEIGHT.
New: new object ZCASH_ACTIVATION_HEIGHTS with all major Zcash network upgrade heights (Sapling, Blossom, Heartwood, Canopy, NU5, NU6).
- New `getZcashBranchId()` function
Determines correct consensusBranchId based on block height.
Maps …
=> fix: set all zcash tx versions

.changeset/calm-glasses-refuse.md, libs/ledger-live-common/src/apps/support.ts
=> fix: coerce app version when comparing with minversion

e2e/desktop/playwright.config.ts, e2e/desktop/tests/page/modal/delegate.modal.ts
=> LLD: Fixing UI e2e nightly failures

.github/workflows/test-mobile-e2e-reusable.yml
=> ci: remove continue-on-error property

.changeset/weak-pumpkins-retire.md, apps/ledger-live-desktop/src/renderer/analytics/hooks/useTrackTransactionChecksFlow.test.ts, apps/ledger-live-desktop/src/renderer/analytics/hooks/useTrackTransactionChecksFlow.ts, apps/ledger-live-desktop/src/renderer/components/DeviceAction/index.tsx, libs/coin-modules/coin-evm/src/__tests__/unit/signOperation.unit.test.ts, libs/coin-modules/coin-evm/src/signOperation.ts, libs/coin-modules/coin-evm/src/types/signer.ts, libs/ledger-live-common/src/hw/actions/transaction.ts, libs/ledgerjs/packages/types-live/src/transaction.ts, libs/live-signer-evm/src/DmkSignerEth.ts, libs/live-signer-evm/tests/DmkSignerEth.test.ts
- ...
Add analytics on LLD when the opt-in transaction checks screen appear on the device
- **JIRA or GitHub link**: [LIVE-17708]
---
[LIVE-17708]: https://ledgerhq.atlassian.net/browse/LIVE-17708?atlOrigin=eyJpIjoiNW …
=> 📈 (dmk): Add analytics for opt-in for transaction checks

.changeset/quiet-deers-decide.md, apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/index.tsx
- ...
- Fix wrong warning message when updating firmware.
- **JIRA or GitHub link**: [LIVE-18386](https://ledgerhq.atlassian.net/browse/LIVE-18386)
---
[LIVE-18386]: …
=> [LIVE-18386][DMK/LLD] Open app state during update firmware flow is not handle correctly

.changeset/nasty-bats-clap.md, apps/ledger-live-mobile/src/analytics/segment.ts
- It simply adds an additional entry to the Segment analytics user object on LLM. This should give us data to track whether users are shown the new Swap Live App or the legacy one.
Checking if the feature flag for "ptxSwapLiveAppMobile" is set and pass that information to the Segment analytics setup as additional properties.
- **JIRA or GitHub link**: LIVE-18439
--- …
=> feat(LIVE-18439): add swap live app feature flag to llm analytics

.changeset/lemon-boxes-try.md, apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/WalletAPIWebview.tsx, libs/ledger-live-common/src/platform/logic.test.ts, libs/ledger-live-common/src/platform/logic.ts, libs/ledger-live-common/src/platform/tracking.ts, libs/ledger-live-common/src/wallet-api/tracking.ts, libs/ledger-live-common/src/wallet-api/types.ts, libs/ledger-live-common/src/wallet-api/useDappLogic.ts
- dApp browser v3 send transaction only
Add more data on send transaction events for the dApp browser v3
- **JIRA or GitHub link**: [LIVE-18407]
---
[LIVE-18407]: …
=> feat: add more data on events for the dapp browser v3 [LIVE-18407]

.changeset/hot-crabs-arrive.md, libs/coin-modules/coin-tron/src/logic/getBalance.test.ts, libs/coin-modules/coin-tron/src/logic/getBalance.ts
- ...
When account is not yet activated, RPC returns an empty account list => return an empty balance instead of crashing
- https://ledgerhq.atlassian.net/browse/BACK-8730
---
=> fix(BACK-8730): [coin-modules][tron] get balance fails on inactive account

.changeset/nasty-cows-retire.md, apps/ledger-live-desktop/src/renderer/components/TranslatedError/hooks/useErrorLinks.test.tsx, apps/ledger-live-desktop/src/renderer/components/TranslatedError/hooks/useErrorLinks.tsx, apps/ledger-live-desktop/src/renderer/components/TranslatedError/utils/index.test.ts, apps/ledger-live-desktop/src/renderer/components/TranslatedError/utils/index.ts
- ...
The error Cannot use 'in' operator to search for 'links' in Invalid extension provided could occur if the links property is a string instead of an object.
- **JIRA or GitHub link**: [LIVE-14178] 
--- …
=> bugfix: LIVE-14178 - Fix Cannot use 'in' operator to search for 'links' in Invalid extension provided

.changeset/green-garlics-enjoy.md, libs/coin-modules/coin-sui/src/bridge/signOperation.ts
- SWAP works as expected.
Since it is not possible to derive SUI public key from it's address, during the TX signing public key is requested from device. In the SWAP context it is crucial to perform all HW operations before TX SIGN. Otherwise, exchange app can't handle it since lib mode is closed already.
--- …
=> fix: Reorder HW operations during SUI TX signing

.changeset/khaki-brooms-sort.md, libs/coin-modules/coin-solana/src/prepareTransaction.ts
- SPL send
Fixing a change where we forgot to also set transaction to `token.transfer` if initiated as `transfer` with a `subAccountId`
- **JIRA or GitHub link**: [LIVE-18586] [LIVE-18585] [LIVE-18603]
--- …
=> fix: wrong transaction kind for solana SPL [LIVE-18586]

.changeset/strange-suits-fix.md, apps/ledger-live-mobile/src/reducers/ratings.ts
- ...
ratingsDataOfUserSelector returned appFirstStartDate as a string instead of a date causing a warning in dev. It's fixed
---
=> :bug: (llm) fix ratingsDataOfUserSelector type

.changeset/quiet-pets-fail.md, apps/ledger-live-mobile/src/actions/earn.ts, apps/ledger-live-mobile/src/actions/types.ts, apps/ledger-live-mobile/src/components/RootNavigator/EarnLiveAppNavigator.tsx, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx, apps/ledger-live-mobile/src/reducers/earn.ts, apps/ledger-live-mobile/src/reducers/types.ts, apps/ledger-live-mobile/src/screens/PTX/Earn/EarnProtocolInfoDrawer.tsx, libs/ledger-live-common/src/featureFlags/stakePrograms/index.test.ts, libs/ui/packages/icons/src/svg/protocol-apy.svg, libs/ui/packages/icons/src/svg/protocol-strategy.svg, libs/ui/packages/icons/src/svg/protocol-tvl.svg, libs/ui/packages/icons/src/svg/protocol.svg
- Adds a new deeplink modal under the Earn umbrella
Implements a native mobile version of the Protocol Info Modal required for the step of choosing a DeFi protocol for Stablecoin Yield.
- **JIRA**: [LIVE-18338](https://ledgerhq.atlassian.net/browse/LIVE-18338)
--- …
=> LIVE-18338: implement protocol info modal for api deposit flow

.changeset/real-snakes-arrive.md, apps/ledger-live-mobile/__tests__/test-renderer.tsx, apps/ledger-live-mobile/src/screens/AccountSettings/EditAccountName.tsx, apps/ledger-live-mobile/src/screens/AccountSettings/__tests__/EditAccountName.test.tsx
- ...
- EditAccount component from Class to functionnal component
- Tests on EditAccount
Edit Account
https://github.com/user-attachments/assets/41f09081-37f0-4c35-bf5a-637077e845e7
ADD Account (with ledgerSync activated)
https://github.com/user-attachments/assets/d68591ea-f0e0-4bf7-98ca-5a460e1d9b93
- **JIRA or GitHub link**:  [LIVE-17458] 
--- …
=> bugfix: Renaming accounts in Account Settings

.changeset/smooth-birds-chew.md, apps/ledger-live-mobile/src/screens/RequestAccount/02-SelectAccount.tsx, apps/ledger-live-mobile/src/screens/SelectAccount.tsx
- ...
bugfixe: Discreet mode wallet selection
- **JIRA or GitHub link**: [LIVE-18578]
---
[LIVE-18578]: https://ledgerhq.atlassian.net/browse/LIVE-18578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …
=> bugfixe: Discreet mode wallet selection

.changeset/famous-nails-give.md, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/FollowInstructions/index.tsx
- ...
bugfixe: Wrong size for ledger nano X Image on ledger sync
- **JIRA or GitHub link**: [LIVE-18727]
---
[LIVE-18727]: https://ledgerhq.atlassian.net/browse/LIVE-18727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …
=> bugfixe: Wrong size for ledger nano X Image on ledger sync

.changeset/gorgeous-weeks-protect.md, apps/ledger-live-mobile/package.json, apps/ledger-live-mobile/src/polyfill.ts, libs/coin-modules/coin-stellar/.unimportedrc.json, libs/coin-modules/coin-stellar/package.json, libs/coin-modules/coin-stellar/src/globals.d.ts, libs/coin-modules/coin-stellar/src/network/horizon.ts, libs/coin-modules/coin-stellar/src/polyfill.ts, pnpm-lock.yaml
- ...
- The @exodus/patch-broken-hermes-typed-arrays polyfill was globally applied in ledger-live-mobile's main polyfill (apps/ledger-live-mobile/src/polyfill.ts).
- This global patching caused regressions for other coins, notably breaking Polkadot (which heavily depends on Uint8Array internals).
- All modules, even those not needing the fix (like Polkadot), were impacted.
- Removed the global import of @exodus/patch-broken-hermes-typed-arrays from mobile polyfill.
- Moved the patching logic inside coin-stellar only, where the problem with Stellar transactions actually occurs.
- Introduced `patchHermesTypedArraysIfNeeded` and `unpatchHermesTypedArrays` utilities inside libs/coin-modules/coin-stellar.
- At transaction broadcast time (broadcastTransaction), the patch is applied temporarily …
=> fix: localize stellar polyfill and revert it once used

.changeset/curvy-needles-mate.md, libs/ledger-live-common/src/families/evm/config.ts
- ...
Default Polygon batch size to 10, as suggested by the backend team (cf https://ledger.slack.com/archives/C02JFKVJHA6/p1744873319520749?thread_ts=1744725154.424639&cid=C02JFKVJHA6)
--- …
=> conf(live-common): add default value to polygon explorer batch size

.changeset/chilly-hairs-cough.md, apps/ledger-live-desktop/src/renderer/screens/accounts/AccountSyncStatusIndicator.tsx
- account row sync indicator
I've not been able to reproduce the issue since it's more like an infra error. But from my understanding we can add this fallback this way we won't display the message if there is no corresponding translation but "please, try again" instead. What's better than [Object Object] or "no network" I guess
- **JIRA or GitHub link**: [LIVE-16756](https://ledgerhq.atlassian.net/browse/LIVE-16756)
--- …
=> :pencil2: (lld) add fallback to sync error message

.changeset/light-mice-boil.md, apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx
- ...
bugfixe: wrong size for retry button in device action
- **JIRA or GitHub link**: [LIVE-18570]
---
[LIVE-18570]: https://ledgerhq.atlassian.net/browse/LIVE-18570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Zh …
=> bugfixe: wrong size for retry button in device action

.changeset/cold-tomatoes-greet.md, apps/ledger-live-mobile/e2e/specs/deeplinks.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/deeplinks.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/nftGallery.spec.ts, apps/ledger-live-mobile/src/components/RootNavigator/WalletTabNavigator.tsx, apps/ledger-live-mobile/src/screens/Account/ListHeaderComponent.tsx, apps/ledger-live-mobile/src/screens/Account/__tests__/nftHelper.test.ts, apps/ledger-live-mobile/src/screens/Account/nftHelper.ts, apps/ledger-live-mobile/src/screens/Settings/Debug/Generators/index.tsx
- ...
Hiding NFTs in LLM 
- Gallery
- Collections
- Tools
WalletTab when FF OFF
https://github.com/user-attachments/assets/f5b9bf68-bc75-44b3-8906-3f4cacb33c96
- **JIRA or GitHub link**: [LIVE-18378] [LIVE-18408] 
--- …
=> feat: remove NFT support in LLM

.changeset/tender-feet-knock.md, libs/coin-modules/coin-tron/src/api/index.test.ts, libs/coin-modules/coin-tron/src/api/index.ts, libs/coin-modules/coin-tron/src/bridge/synchronization.ts, libs/coin-modules/coin-tron/src/logic/listOperations.integ.test.ts, libs/coin-modules/coin-tron/src/logic/listOperations.ts, libs/coin-modules/coin-tron/src/logic/listOperations.unit.test.ts, libs/coin-modules/coin-tron/src/network/index.integ.test.ts, libs/coin-modules/coin-tron/src/network/index.test.ts, libs/coin-modules/coin-tron/src/network/index.ts, libs/coin-modules/coin-tron/src/network/types.ts
- Tron accounts may have a number of txs > 1000
- Very big accounts may be problematic with initial sync if they use api or logic layer.
- bridge is not impacted because it uses network layer with same behavior as before
Lama adapter needs to have the unlimited set of txs regarding LES needs. The 1000 limit wasn't acceptable. So we implemented the minHeight filter, like we did on other coins.
The limitation of this implementation is that it will be difficult to do initial sync of accounts with a lot of txs.
- https://ledgerhq.atlassian.net/browse/LIVE-18576 
- https://ledger.slack.com/archives/C08CS1LMBCY/p1745916858272569
---
- **The PR description clearly documents the changes** made and explains …
=> feat(live-18576): tron listOperations uses minHeight filter

.changeset/gold-turtles-fly.md, apps/ledger-live-mobile/src/components/RootNavigator/PlatformExchangeNavigator.tsx, apps/ledger-live-mobile/src/screens/Platform/exchange/StartExchange.tsx
add header with title and back button to exchange start device select screen
- Does add a header with back button to the Exchange Start Screen (device selection - see screenshots)
After selecting a provider during the swap flow the user will be guided to the "device selection" screen, which currently doesn't have a title or on screen back navigation, which could potentially cause users (that don't know about swipe back navigation, or with Android back button) cancel the transaction.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-18797
--- …
=> feat(LIVE-18797): add header for exchange start device select screen

.changeset/funny-brooms-tell.md, libs/coin-modules/coin-solana/src/prepareTransaction.ts
- ...
The fiat value does not update when the SOL amount is changed after an initial value has been entered. It remains stuck on the previous fiat value.
https://github.com/user-attachments/assets/bd5bfa0d-52d9-4491-b50e-2ef98d432fb7
- **JIRA or GitHub link**: [LIVE-18742](https://ledgerhq.atlassian.net/browse/LIVE-18742)
---
- …
=> fix: change amount in command if it is not the same in the transaction

.changeset/empty-ants-hug.md, apps/ledger-live-desktop/src/renderer/analytics/hooks/useTrackTransactionChecksFlow.test.ts, apps/ledger-live-desktop/src/renderer/analytics/hooks/useTrackTransactionChecksFlow.ts, apps/ledger-live-desktop/src/renderer/components/DeviceAction/index.tsx, libs/coin-modules/coin-evm/src/__tests__/unit/signOperation.unit.test.ts, libs/coin-modules/coin-evm/src/signOperation.ts, libs/coin-modules/coin-evm/src/types/signer.ts, libs/ledger-live-common/src/hw/actions/transaction.ts, libs/ledgerjs/packages/types-live/src/transaction.ts, libs/live-signer-evm/package.json, libs/live-signer-evm/src/DmkSignerEth.ts, libs/live-signer-evm/tests/DmkSignerEth.test.ts, pnpm-lock.yaml
- ...
Add tracking for transaction checks opt in result. When the user will select to opt-in or not, the dmk will notify the result to LL that will be able to track it using specific hook.
- **JIRA or GitHub link**: [LIVE-17946]
--- …
=> ✨ (dmk): Add tracking for transaction checks opt in result

.changeset/fresh-fishes-change.md, libs/coin-modules/coin-solana/src/__tests__/unit/hw-signMessage.unit.test.ts, libs/coin-modules/coin-solana/src/hw-signMessage.ts, libs/ledger-live-common/src/families/solana/setup.test.ts, libs/ledger-live-common/src/wallet-api/react.ts
- solana sign message
The signature returned by signMessage for the Solana was not in base58 as expected by a lot of apps
---
=> fix: use base58 encoding for Solana signMessage signature

.changeset/angry-scissors-argue.md, libs/coin-modules/coin-tron/src/api/index.test.ts, libs/coin-modules/coin-tron/src/api/index.ts, libs/coin-modules/coin-tron/src/logic/listOperations.integ.test.ts, libs/coin-modules/coin-tron/src/logic/listOperations.ts, libs/coin-modules/coin-tron/src/logic/listOperations.unit.test.ts, libs/coin-modules/coin-tron/src/network/index.ts
- the network and logic layers has changed signatures. The new signature introduce parameters used to better control the underlying call to tronscan.
- the default parameters are same as before
- no impact on bridge with default parameters 
- the api changes behavior: now it returns a limited number of 400 operations. Oldest operations are guaranteed to be returned first. 
- lama-adapter needs to fetch 15k+ operations on some accounts
- this is about ~7k calls made on trongrid where none of them should fail
- looks like we missed a lot of operations trying to fetch all in one gulp
- this commit let the possibility to fetch deepest operations first and still fixing a limit on the total number of operations
- lama-adapter will be able to sync the whole set of operations by fetching bit by …
=> fix(live-18576,coin-tron): retrieve limited number of oldest operations first

.changeset/chatty-clocks-pull.md, apps/ledger-live-mobile/src/components/RecoverBanner/index.tsx
- ...
Visual overlap between recover banner and components above it. Added a small margin to produce gap between the components.
(Black bar is a test component in place of a braze card)
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-18798
--- …
=> fix: add spacing above recover banner

.changeset/flat-trees-pay.md, libs/coin-modules/coin-solana/src/__tests__/unit/hw-signMessage.unit.test.ts, libs/coin-modules/coin-solana/src/hw-signMessage.ts, libs/ledger-live-common/src/families/solana/setup.test.ts
- Solana sign message with the wallet-api
We now return [an envelope](https://docs.anza.xyz/proposals/off-chain-message-signing#envelope) containing both the signature and the signedMessage
It allows live-apps and dApps to verify the signature against the message constructed by LL with the header
You can use the following manifest to test the feature with this small live-app: https://codesandbox.io/p/sandbox/5gz86q
<details>
<summary>Manifest</summary>
```md
{
"id": "sol-test-sign",
"author": "",
"private": false,
"name": "Sol test sign",
"url": "https://5gz86q.csb.app/",
"homepageUrl": "https://5gz86q.csb.app/",
"icon": "",
"platforms": ["ios", "android", "desktop"],
"apiVersion": "^2.0.0",
"manifestVersion": "2",
"branch": "stable",
"categories": ["DeFi"],
"currencies": ["solana"], …
```
=> feat: solana off-chain message signing returns the envelope with the signedMessage [LIVE-19009]

.changeset/new-flies-smell.md, apps/ledger-live-mobile/src/polyfill.ts
- ...
Add polyfill to handle the error `undefined is not a function` when ky retry and call `signal.throwIfAborted();`
https://github.com/sindresorhus/ky/issues/588#issuecomment-2256808504
- **JIRA or GitHub link**:  [LIVE-18520](https://ledgerhq.atlassian.net/browse/LIVE-18520)
--- …
=> fix: add polyfill for ky retry on LLM Android

.changeset/fuzzy-plums-care.md, apps/ledger-live-mobile/src/screens/Swap/SubScreens/OperationDetails.tsx
add check for existing provider urls in swap history
- ...
On Swap History -> Operation Details screen the app is crashing when we don't have a url for the provider defined.
Changes: Adding a check for provider urls to make sure we have a valid link. If the url is missing we only show the provider name and don't add a link.
Images with Link and without Link
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-18412
--- …
=> fix(LIVE-18412): add check for existing provider urls in swap history

.changeset/moody-timers-compare.md, .changeset/thin-mice-study.md, apps/ledger-live-desktop/src/renderer/screens/customImage/Step1ChooseImage.tsx, apps/ledger-live-mobile/src/components/CustomImage/CustomImageBottomModal.tsx
- ...
Now the usage of NFT as custom lock screen is controlled by feature flag `llNftSupport`.
- **JIRA or GitHub link**: [LIVE-18379][LIVE-18826]
---
[LIVE-18379]: …
=> [LIVE-18379][LIVE-18826] Feature flag to control NFT usage for custom lock screen

.changeset/great-laws-obey.md, apps/ledger-live-desktop/src/renderer/Default.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Experimental/index.tsx, apps/ledger-live-mobile/src/index.tsx, apps/ledger-live-mobile/src/screens/Settings/Experimental/FeatureRow.tsx
- ...
This PR introduces the new `setProvider` feature from the Device Management Kit and integrates it into both LLM and LLD. 
- [DSDK-712](https://ledgerhq.atlassian.net/browse/DSDK-712)
- [DSDK-719](https://ledgerhq.atlassian.net/browse/DSDK-719)
--- …
=> chore: set provider in dmk

.changeset/tidy-cheetahs-exercise.md, libs/coin-modules/coin-stellar/src/api/index.test.ts, libs/coin-modules/coin-stellar/src/api/index.ts, libs/coin-modules/coin-stellar/src/logic/listOperations.ts, libs/coin-modules/coin-stellar/src/logic/listOperations.unit.test.ts, libs/coin-modules/coin-stellar/src/network/horizon.ts, libs/coin-modules/coin-stellar/src/network/serialization.ts
- ...
* `listOperations` uses N+1 RPC requests instead of just 1, because it fetches block metadata for each transaction
* `minHeight` is only applied after doing all this, so when requesting operations on an up to date address we do the N+1 requests for the whole first page (200 txs), then throw out everything
* => push down predicate to the inner level so that we do only 1 RPC request
- https://ledgerhq.atlassian.net/browse/BACK-8848
--- …
=> fix(BACK-8848): [coin-modules][stellar] push down filtering predicate

.changeset/lazy-chairs-film.md, libs/coin-modules/coin-solana/src/__tests__/unit/hw-signMessage.unit.test.ts, libs/ledger-live-common/src/families/solana/config.ts
- Sign Message Solana default config
Updates the default config version to toggle between legacy OCMS header or newer one now that we know the expected prod version of 1.8.0
---
=> chore: update default legacyOCMSMaxVersion

.changeset/plenty-files-talk.md, .changeset/shiny-swans-roll.md, libs/coin-modules/coin-ton/src/bridge/bridgeHelpers/api.ts, libs/coin-modules/coin-ton/src/bridge/bridgeHelpers/txn.ts, libs/coin-modules/coin-ton/src/synchronisation.ts, libs/ledger-live-common/src/exchange/swap/getCompleteSwapHistory.ts
- ...
We want to be able to show users TON and Token swaps in the history.
For the others chains, it all good.
What is the problem ?
Actually, int the swap logic, to retrieve the operation behind a swap, they compare ids. 
So the Swap Operation Id (operationId) need to match with the hash of the operation.
But in the context of TON, it is not the case.
What is the Solution ?
Put as hash the same as the one used when crafting a SwapOperation.
https://github.com/user-attachments/assets/9e3509f0-6a83-402f-83de-ed1cd0687b2b
https://github.com/user-attachments/assets/1e7eeb87-7ba3-46d5-ba84-bb08cb8879e1
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-18917
---
- **The PR description …
=> fix: show ton tokens in swap history

.changeset/late-sheep-argue.md, libs/coin-modules/coin-hedera/src/api/mirror.test.ts, libs/coin-modules/coin-hedera/src/api/mirror.ts, libs/coin-modules/coin-hedera/src/bridge/synchronisation.ts
- Hedera account scanning is much faster
This pull request fixes slow account scanning when adding a new Hedera account. 
Here is a demo of how it works now:
https://drive.google.com/file/d/1xOLbOj8AEUaMnO_UsjWl23hD9nreaCdZ/view. 
You can notice that it takes more than 300 requests per account to get the list of transactions from the Mirror Node API. This can be easily reproduced by going to: https://mainnet-public.mirrornode.hedera.com/api/v1/transactions?account.id=0.0.8835924&timestamp=gt:0 and trying to fetch the transactions until `links.next = null`. 
The proposed fix is to simply break the loop when the transactions array is empty, avoiding unnecessary pagination when we know no more data can be returned.
Here is a demo of how it works after the change is made: …
=> fix: optimize the "Add account" flow in Hedera

.changeset/gentle-geckos-melt.md, apps/ledger-live-mobile/src/screens/Account/ListHeaderComponent.tsx
- No impacts
App crash when opening account in E2E tests
Remove test code
- **JIRA or GitHub link**: [LIVE-19248](https://ledgerhq.atlassian.net/browse/LIVE-19248?atlOrigin=eyJpIjoiZTgwMzViOTUwNjRkNGU1MzgxYTQwOWZmOWQyMWJiYjIiLCJwIjoiaiJ9) 
--- …
=> chore/LIVE-19248 App crash when opening account in E2E tests

.changeset/hip-apples-report.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx, apps/ledger-live-mobile/src/screens/Swap/LiveApp/index.tsx
- ...
fix(swap): handle offline state in swap webview and error cases
- Add offline state check before showing unavailable app error
- Hide webview when offline to prevent blank screen
- Simplify error handling logic in mobile swap screen
- Memoize manifest URL and params for better performance
https://github.com/user-attachments/assets/3bfc1890-2798-4413-b843-5c2c68c31890
https://ledgerhq.atlassian.net/browse/LIVE-18314 
https://ledgerhq.atlassian.net/browse/LIVE-19133 
--- …
=> fix(live-19133): handle offline state in swap webview

.changeset/slow-bottles-think.md, apps/ledger-live-mobile/src/screens/PTX/Earn/EarnMenuDrawer.tsx
- fix tracking on MenuDrawr
Fix the tracking of Manage/Earn more position before opening links to the different dapps.
- **JIRA or GitHub link**:  [LIVE-17878](https://ledgerhq.atlassian.net/browse/LIVE-17878)
--- …
=> LIVE-17878: track of Manage/Earn more position before opening link

.changeset/kind-planes-raise.md, apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx
- ...
The provider name was directly used from the provider object, which could lead to inconsistencies. Now using getProviderName utility function to ensure consistent naming across the application.
| ![image](https://github.com/user-attachments/assets/679ca461-d029-4dbf-9068-6b534d9d09fe) | ![image](https://github.com/user-attachments/assets/190d349d-b5a1-48c3-8e4d-c95c87068a58) |
https://ledgerhq.atlassian.net/browse/LIVE-19297 
--- …
=> fix(live-19297):  LLM swap - use getProviderName for consistent provider naming

.changeset/slimy-pens-exist.md, apps/ledger-live-mobile/src/components/StepHeader.tsx, apps/ledger-live-mobile/src/families/cosmos/ClaimRewardsFlow/index.tsx
…n size
- ...
Claim atom header title scale to fit the size of the screen without overlapping on the close button
|<img width="409" alt="Screenshot 2025-06-02 at 18 23 04" src="https://github.com/user-attachments/assets/421136fb-9403-4b15-96d7-38a0503fbca6" />|<img width="409" alt="Screenshot 2025-06-02 at 18 21 43" src="https://github.com/user-attachments/assets/dc4808da-0b4e-464d-b420-29434a6871ad" />|
- **JIRA or GitHub link**: [LIVE-15454]
--- …
=> 🐛  LLM - Claim atom header size now scaling depending on screen

.changeset/dirty-flies-eat.md, apps/ledger-live-mobile/src/screens/PTX/Earn/EarnMenuDrawer.tsx
- Small fix to the attribute names
Amend the name and attributes of the EarnMenuDrawer events
- **JIRA**: (LIVE-17878)[https://ledgerhq.atlassian.net/browse/LIVE-17878]
---
=> fix: amend the name and attributes of the EarnMenuDrawer events

.changeset/silver-dolphins-melt.md, libs/coin-modules/coin-tezos/src/bridge/signOperation.ts, libs/coin-modules/coin-tezos/src/logic/craftTransaction.test.ts, libs/coin-modules/coin-tezos/src/logic/craftTransaction.ts
- ...
Add the leading `0x03` byte in `rawEncode` instead of only bridge, so that ALPACA gets the same crafted transactions for signing.
Note: I checked `rawEncode` is only used here
- https://ledgerhq.atlassian.net/browse/BACK-9017
- https://ledger.slack.com/archives/C07RB4NNN3H/p1748944367222189
--- …
=> fix(BACK-9017): [coin-modules][tezos] ALPACA tezos craft is missing leading `0x03` byte in raw transaction

.changeset/thick-donuts-attack.md, libs/coin-modules/coin-tron/src/bridge/getEstimateFees.test.ts, libs/coin-modules/coin-tron/src/bridge/getEstimateFees.ts, libs/coin-modules/coin-tron/src/logic/constants.ts
- ...
We use to have a default value for transaction using no bandwidth  (0.002 TRX).
But the correct value is (0.001 TRX per bandwidth point needed to complete the transaction.)
- **JIRA or GitHub link**: [LIVE-19388](https://ledgerhq.atlassian.net/browse/LIVE-19388)
--- …
=> fix: estimation fee with no bandwidth

.changeset/light-planets-brake.md, apps/ledger-live-desktop/src/renderer/components/WebPTXPlayer/TopBar.tsx, apps/ledger-live-desktop/src/renderer/components/WebPTXPlayer/index.tsx
- ...
- Added device toggle to the TopBar allowing user to switch resolution between mobile and desktop
- functionality hidden behind **Enable dev tool** developer setting
- functionality has only been applied to PTX WebView, but can be applied to other webviews across LL if required
- **JIRA or GitHub link**: [LIVE-17090] 
---
- …
=> feat: Add the LLM resolution tool in Electron within the PTX WebView

.changeset/friendly-books-sing.md, apps/ledger-live-desktop/src/renderer/init.tsx, apps/ledger-live-desktop/src/renderer/reducers/index.ts, e2e/desktop/tests/page/index.ts, e2e/desktop/tests/specs/rename.account.spec.ts, e2e/desktop/tests/utils/redux.ts, e2e/desktop/tests/utils/userdata.ts, libs/live-wallet/src/store.test.ts, libs/live-wallet/src/store.ts
- ...
Added tests to cover the regression issue that previously forced us to revert this PR
This was due to a change in the ExportedWalletState data returned by the wallet-store.
It caused the `accountNameWithDefaultSelector` and the `isStarredAccountSelector` selectors to make the app crash after rolling back to a previous version not containing the rename account fix.
To prevent this, we nest the `accountNames` and `starredAccountIds` in an `accountsData` property.
Also added a test to validate that the account renamed and accounts starred in a previous app version will be kept with this fix
The Ledger Sync tests confirms that this fix does not impact the Ledger Sync feature.
- **JIRA or GitHub link**: [LIVE-18928]
---
- **The code aligns with the requirements** described in the linked …
=> 🐛  Fix LLD Rename Account

.changeset/perfect-crews-repeat.md, apps/ledger-live-mobile/src/screens/SendFunds/02-SelectRecipient.tsx
- ...
Ensures the memo tag input is focused once the modal is dismissed
https://github.com/user-attachments/assets/496a6c48-38b0-455d-bfb2-eb0c18d9a3a6
- **JIRA or GitHub link**: [LIVE-19476](https://ledgerhq.atlassian.net/browse/LIVE-19476)
--- …
=> fix(LLM): memoTagInput retain input focus on modal close

.changeset/tough-deers-trade.md, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/walletSyncActivation.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Activation/index.tsx
- ...
Add a guard to prevent display when the link is not provided in the feature flag
The issue was that on staging and dev environments, the learnMoreLink key was missing in the feature flag, while it was present in production. This guard ensures the component does not attempt to render the link if it's undefined.
https://github.com/user-attachments/assets/fa3ba3cd-e645-4b80-b542-5a5a6714b5ba
- **JIRA or GitHub link**: [LIVE-19709]
--- …
=> bugfix: display of Learn More on Ledger Sync

.changeset/sixty-camels-wonder.md, .changeset/stupid-pens-relax.md, apps/ledger-live-mobile/src/components/TranslatedError/TranslatedError.tsx, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/DeviceSelection/screens/SelectDevice/index.tsx, apps/ledger-live-mobile/src/newArch/features/DeviceSelection/screens/SelectDevice/useSelectDeviceViewModel.ts, libs/ledger-live-common/src/hw/customLockScreenLoad.test.ts, libs/ledger-live-common/src/hw/customLockScreenLoad.ts
- ...
Map device disconnected from DMK during CLS update
use of withTransport instead of withDevice to fix retry after device session removed
- **JIRA or GitHub link**: [LIVE-18720] [LIVE-18926]
---
[LIVE-18720]: …
=> :bug: (cls): Remap device disconnected error

e2e/mobile/helpers/commonHelpers.ts, e2e/mobile/page/liveApps/swapLiveApp.ts, e2e/mobile/page/trade/swap.page.ts
=> fix: Add time delay for ios in CI

.changeset/seven-dryers-agree.md, libs/coin-modules/coin-aptos/src/__tests__/network/client.test.ts, libs/coin-modules/coin-aptos/src/network/client.ts
- ...
When executing getAccountInfo we call getBalances in order to return all Aptos accounts in blockchain; When a *account* does not have *amount* we were creating a zero-d amount value with BigInt(0) instead of BigNumber(0).
The change would fix the amount as it sets to correct type.  And checking if the balance object has value, otherwise return BigNumber(0).
|      balance: balance[0]?.amount ?? BigInt(0),         |          balance: balance[0].amount ?? BigNumber(0),     |
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-19542
--- …
=> converting bigint ot bignumber

.changeset/odd-maps-return.md, apps/ledger-live-desktop/src/renderer/screens/manager/DeviceDashboard/AppsList/InstallSuccessBanner.tsx
- my ledger / i18next
During add account rework, we changed all the _plural key to _other key as _plural isn't supported by i18next. We missed this one so this PR fixes the issue
- **JIRA or GitHub link**: [LIVE-19917](https://ledgerhq.atlassian.net/browse/LIVE-19917) …
=> :bug: (lld) pluralization issue my ledger

.changeset/eighty-vans-flash.md, apps/ledger-live-desktop/src/renderer/components/StepperNumber.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Accounts/CurrencyRows.tsx, libs/ledgerjs/packages/cryptoassets/src/currencies.ts
- ...
The default block confirmation number is computed with the following formula
```
(30 * 60) / blockAvgTime
```
Let's ensure 200 as the default to match what is done on Tronscan, since this is the explorer of choice in LL for TRON.
Also allow to input confirmation number directly, passing by
---
- …
=> chore(cryptoassets): update TRON block average time

.changeset/light-colts-pretend.md, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/ConnectYourDevice/index.tsx, apps/ledger-live-desktop/src/renderer/drawers/Drawer.tsx, apps/ledger-live-desktop/src/renderer/drawers/Provider.tsx
- ...
Prevents the drawer rendering a component twice, fixing issues with animation retriggers and LDMK initialisation issues
Before:
https://github.com/user-attachments/assets/5ac5d960-0861-45ef-8d42-15b9abe09226
After:
https://github.com/user-attachments/assets/6f316da0-0569-47e4-b9e3-3248295d8621 
- **JIRA or GitHub link**: [LIVE-19919](https://ledgerhq.atlassian.net/browse/LIVE-19919)
---
- …
=> fix(LLD): account selection prevent double render

.changeset/happy-hornets-divide.md, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/ModularDrawerAddAccountFlowManager.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/FundAccount/index.tsx, libs/ui/packages/react/src/pre-ldls/components/AccountList/AccountList.tsx
- ...
2 PRs changed the layout of various add account screens, resulting in disparities in margin. This PR fix the issues.
Also fix accountList item size so it looks better and there is no overlaps
|![image](https://github.com/user-attachments/assets/3ce92937-1e56-4f34-a010-181f96ae871c)|![image](https://github.com/user-attachments/assets/eed1d3bd-f138-4d7b-a880-fa4f77df0464)|
--- …
=> :sparkles: (LLD-AA) fix spacing issues

.changeset/angry-waves-beg.md, apps/ledger-live-desktop/src/renderer/modals/Send/fields/RecipientField.tsx
- ...
Fixes a bug where changing the debit account in the send flow clears the recipient internally, disabling the "Continue" button even though the input looks valid.
https://github.com/user-attachments/assets/41577d21-d25c-46c6-aa9e-ffdc896df629
- **JIRA**: https://ledgerhq.atlassian.net/browse/LIVE-19341
--- …
=> Fix: changing debit account no longer disables continue button

libs/coin-modules/coin-sui/src/api/index.integration.test.ts, libs/coin-modules/coin-sui/src/api/index.ts
To allow Aplaca to integrate with the SUI coin-module, a slight change in the config is needed. It's now the same as other alpaca coins like Tron or Tezos.
=> fix: Sui alpaca integration

e2e/mobile/helpers/elementHelpers.ts, e2e/mobile/page/liveApps/swapLiveApp.ts, e2e/mobile/page/trade/swap.page.ts, e2e/mobile/specs/swap/otherTestCases/swap.other.ts, e2e/mobile/specs/swap/otherTestCases/tooLowAmountForQuoteSwaps/Usdt2ToBtc24EthFee.spec.ts, e2e/mobile/specs/swap/swap.ts, libs/ledger-live-common/src/e2e/speculos.ts
- ...
- Add device.disableSynchronization() before selectKnownDevice in swap tests.
- Disabled new swap feature ptxUseCombinedSwap which is causing failures for android due to a modal being displayed infinitely
- Fix issue with getting minAmount
--- …
=> fix(e2e): QAA-698_Fix swap related issues

.changeset/wild-kangaroos-nail.md, libs/coin-modules/coin-sui/src/api/index.integration.test.ts, libs/coin-modules/coin-sui/src/api/index.ts
- SUI listOperation alpaca API behavior
SUI listOperations never used the minHeight parameter, so alpaca api was not respected and it-tests failed
This PR fixes this in the api folder as to not change the logic, and potentially impact ledger-live.
Now the listOperation with the cursor is called until no new transaction is found after filtering with minHeight
- https://ledgerhq.atlassian.net/browse/BACK-9292
--- …
=> fix: Sui listOperation uses minHeight

.changeset/purple-spies-think.md, e2e/desktop/tests/userdata/speculos-sanctioned-eth.json
- E2E Speculos > Swap test
Add missing app.json for swap test
In the [PR blacklisted addresses](https://github.com/LedgerHQ/ledger-live/pull/10365), we did not put the file `speculos-sanctioned-eth.json`
It’s missing from the userdata used in the e2e swap test: https://github.com/LedgerHQ/ledger-live/blob/develop/e2e/desktop/tests/specs/swap.other.spec.ts#L976
It is failing : https://ledger-live.allure.green.ledgerlabs.net/allure/reports/d2788296-0ede-4291-96e1-82535c3ec8a6/#suites/500d8b838dcfa96d72c7a263e6dc8783/62329b7134cff156/
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/LIVE-20226
--- …
=> [E2E] Add missing app.json for swap test

e2e/mobile/specs/swap/otherTestCases/swap.other.ts, e2e/mobile/utils/swapUtils.ts
- ...
Adding setEnv("DISABLE_TRANSACTION_BROADCAST", true) at the begging of the test ([same method on swap.ts test](https://github.com/LedgerHQ/ledger-live/blob/develop/e2e/mobile/specs/swap/swap.ts#L7))
Original value for DISABLE_TRANSACTION_BROADCAST is set again on the [afterAll](https://github.com/LedgerHQ/ledger-live/blob/38f0a9dcbb129e7fc72cbf484ba6a69582b84927/e2e/mobile/setup.ts#L27)
CI run (only swapWithSendMaxUSDTtoBTC.spec.ts) with broadcast on: 
https://github.com/LedgerHQ/ledger-live/actions/runs/16251255082
--- …
=> fix: disable broadcast for LLM swap max test

.changeset/rare-meals-flash.md, libs/ledger-key-ring-protocol/src/qrcode/index.test.ts, libs/ledger-key-ring-protocol/src/qrcode/index.ts
- ...
This PR improves the detection of legacy base64-encoded QRcode imports by enforcing stricter format validation and checking for a specific binary header.
It also enhances error handling when scanning inputs that are not base64 (e.g., ETH, BTC addresses), providing clearer error messages and reducing false positives.
https://github.com/user-attachments/assets/e9917cd4-401c-42db-af33-23893f0310af
- **JIRA or GitHub link**: [LIVE-20105](https://ledgerhq.atlassian.net/browse/LIVE-20105) 
---
- …
=> bugfix(🐛): improve legacy QRcode import detection and address scan handling

.changeset/neat-carrots-collect.md, libs/coin-modules/coin-polkadot/src/network/sidecar.ts, libs/coin-modules/coin-polkadot/src/network/types.ts
- dot unbonding of reserved fond
Original PR: https://github.com/LedgerHQ/ledger-live/pull/10977
Users were unable to unbond their staked DOT tokens, receiving PolkadotUnauthorizedOperation errors. The lockedBalance was incorrectly showing as 0 despite having staked funds.
The balance calculation was using the balanceInfo.locks array from the sidecar API, which now returns empty arrays. The actual staking balance data is in the reserved field.
**Solution**
- Fixed locked balance: Use reserved field instead of empty locks array
- Fixed spendable balance: Implement correct Polkadot formula: free - max(frozen - reserved, ED
- **JIRA or GitHub link**: [LIVE-20391]
We are from Yield.xyz (formerly StakeKit), we power the Earn infra in Ledger Live. We monitor on-chain actions and user activity …
=> fix(dot): use reserved balance for unbonding logic

.changeset/thirty-icons-search.md, libs/coin-modules/coin-sui/src/bridge/signOperation.test.ts, libs/coin-modules/coin-sui/src/bridge/signOperation.ts
=> fix: sui swap device disconnected

.changeset/wise-cooks-love.md, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/ModularDrawerAddAccountFlowManager.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/__tests__/addAccountFlow.test.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/AccountsWarning/index.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/AccountsWarning/types.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/AccountsWarning/useWarningConfig.tsx
- ...
Adds edit account name button to account in empty account warning
| <img width="500" height="376" alt="image" src="https://github.com/user-attachments/assets/1045dd50-3c39-40c0-8631-0aeb5e9c9693" /> | <img width="501" height="430" alt="image" src="https://github.com/user-attachments/assets/819d4380-37b2-42be-ab6f-4afe4cd84eb9" /> |
- **JIRA or GitHub link**: [LIVE-20093](https://ledgerhq.atlassian.net/browse/LIVE-20093)
---
- …
=> feat(LLD): edit account name on MAD existing new account

apps/ledger-live-desktop/src/renderer/drawers/SwapOperationDetails/index.tsx, libs/coin-modules/coin-hedera/src/api/network.test.ts, libs/coin-modules/coin-hedera/src/bridge/getTransactionStatus.ts, libs/coin-modules/coin-hedera/src/bridge/prepareTransaction.test.ts, libs/coin-modules/coin-hedera/src/bridge/prepareTransaction.ts, libs/coin-modules/coin-hedera/src/transaction.ts, libs/coin-modules/coin-hedera/src/types/bridge.ts, libs/ledger-live-common/src/exchange/swap/completeExchange.ts
- ...
This PR resolves code issues identified by SonarQube and improves transaction logic clarity by relocating transaction.maxFee handling from `getTransactionStatus` to `prepareTransaction`.
---
=> fix: resolve SonarQube code warnings and refactor maxFee logic in Hedera swaps

.changeset/curly-colts-deliver.md, libs/live-signer-solana/src/LegacySignerSolana.ts, libs/live-signer-solana/tests/LegacySignerSolana.test.ts
- ...
Checking the minimum version for app Solana is preventing LNS users to send SPL tokens.
---
=> fix(live-signer-solana): do not check min version on LNS

.changeset/thin-swans-unite.md, libs/coin-modules-monitoring/src/index.test.ts, libs/coin-modules-monitoring/src/index.ts
Ensure fallback to account address for empty xpub in scan and sync logs.
- ...
In case of empty string in xPub, the prop accountAddressOrXpub returned an empty string instead of the address
--- …
=> fix(coin-modules): fallback on empty xpub

.changeset/sweet-carpets-cover.md, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/screens/AssetSelection/index.tsx
- ...
Reduce bottom margin asset list
|https://github.com/user-attachments/assets/91e37ce8-fb2c-4d07-9d36-f490fa9126fd|https://github.com/user-attachments/assets/84d21cb8-e882-42ff-ab12-3e9a796f4797|
- **JIRA or GitHub link**: NO NEED 
--- …
=> :sparkles: (MAD-LLM) asset list reduce bottom margin

.changeset/proud-suits-occur.md, libs/coin-framework/src/api/types.ts, libs/coin-modules/coin-aptos/src/__tests__/api/index.integ.test.ts, libs/coin-modules/coin-stellar/src/api/index.integ.test.ts, libs/coin-modules/coin-stellar/src/api/index.test.ts, libs/coin-modules/coin-stellar/src/api/index.ts, libs/coin-modules/coin-tezos/src/api/index.integ.test.ts, libs/coin-modules/coin-tezos/src/api/index.test.ts, libs/coin-modules/coin-tezos/src/api/index.ts, libs/coin-modules/coin-tron/src/logic/craftTransaction.integ.test.ts, libs/coin-modules/coin-tron/src/logic/craftTransaction.test.ts, libs/coin-modules/coin-tron/src/logic/craftTransaction.ts, libs/coin-modules/coin-xrp/src/api/index.integ.test.ts, libs/coin-modules/coin-xrp/src/api/index.test.ts, libs/coin-modules/coin-xrp/src/api/index.ts
- ...
Pass `FeeEstimation` to `craftTransaction`, so we can directly forward the output of `estimateFees`. Also make `FeeEstimation` more flexible.
---
=> core(coin-framework): pass `FeeEstimation` to `craftTransaction`

.changeset/clean-ties-chew.md, libs/coin-modules/coin-polkadot/package.json, libs/coin-modules/coin-polkadot/src/bridge/getTransactionStatus.test.ts, libs/coin-modules/coin-polkadot/src/bridge/getTransactionStatus.ts, libs/coin-modules/coin-polkadot/src/network/sidecar.ts
- No impact
Bug on Polkadot: User with a balance between 1 and 2 DOT can not send
Fix was merge on `release` branch but not on `develop`
Commits were cherry-pick from the `release`branch
- Check spendable balance to be superior to zero on `getTransactionStatus`
- `EXISTENTIAL_DEPOSIT_RECOMMENDED_MARGIN` used to compute spendable balance
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/LIVE-20586?atlOrigin=eyJpIjoiYWNhNmYwZjA4YTY2NDUwMGIzZDhiYWQxOGE4NWNiZTAiLCJwIjoiaiJ9
---
- **The …
=> Bugfix/live-20586 fix send small DOT amount when total balance < 2 DOTs

.changeset/smooth-dogs-battle.md, apps/ledger-live-mobile/src/components/DBSave.ts, apps/ledger-live-mobile/src/index.tsx
- ...
Moves calls to useDBSaveEffect away from LLM root \<App\> to prevent rerenders on every redux state change.
| ![Kapture 2025-07-29 at 17 18 24](https://github.com/user-attachments/assets/17766e51-23c5-46b4-bb1c-eaec43e9ea74) Starts off with 20 rerenders in root App. Further redux store updates (with toast) trigger rerenders  |  ![Kapture 2025-07-29 at 17 15 48](https://github.com/user-attachments/assets/7f8f6ac3-2283-49c9-b26b-579aaa2b064c)   starts off with 15 rerenders. Further redux store updates (with toast) do not trigger rerenders |
| <img width="270" height="153" alt="image" src="https://github.com/user-attachments/assets/a48ce528-3d3b-468a-affc-916907e891c7" />  Navigation around the app can easily rerender …
=> fix(LLM) rerendering with use db save effect

.changeset/brown-dogs-appear.md, apps/ledger-live-mobile/src/components/useExportLogs.tsx, apps/ledger-live-mobile/src/screens/Swap/SubScreens/SwapCustomError.tsx
fix mobile export logs error and upgrade swap error for screen for consistency
- ...
https://ledgerhq.atlassian.net/browse/LIVE-20549
---
- **There are …
=> feat(LIVE-20549): fix mobile export logs error and upgrade swap error

.changeset/quiet-llamas-scream.md, libs/coin-modules-monitoring/src/currencies.ts, libs/coin-modules/coin-filecoin/src/common-logic/utils.ts, libs/coin-modules/coin-hedera/src/bridge/synchronisation.ts, libs/coin-modules/coin-near/src/api/indexer.ts, libs/coin-modules/coin-tezos/src/bridge/synchronization.ts
Add  datadog monitoring for tier two coins, exceptions are coins needing additionnal configurations to get the account shape (essentially cosmos)
⚠️ Mina is very slow
ℹ️ filecoin - hedera - tezos - near getAccountShape now returns a operationsCount property
- https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/465?selectedIssue=LIVE-20288
--- …
=> feat(coin-monitoring): monitor tier two adresses

libs/coin-modules/coin-hedera/src/api/mirror.test.ts, libs/coin-modules/coin-hedera/src/api/mirror.ts, libs/coin-modules/coin-hedera/src/api/types.ts, libs/coin-modules/coin-hedera/src/bridge/synchronisation.ts
- account balance is fetched from mirror node, not RPC
- synchronization process should work faster and be more stable
This PR should fix "HederaAddAccountError" and make synchronisation process faster. Previously, the account balance was fetched using @hashgraph/sdk and AccountBalanceQuery. With the DEV_TOOLS=1 env enabled, numerous retries were clearly visible in the Network tab, significantly impacting sync time. Right now this is based on the mirror node and should work way better.
---
- **The …
=> fix: fetch Hedera account balance from mirror node

.changeset/polite-feet-appear.md, apps/ledger-live-desktop/src/renderer/components/RecipientAddress.tsx, libs/ledgerjs/packages/errors/src/helpers.ts
- ...
Augment custom errors with their metadata type, removing the need of casts.
| <img width="711" height="197" alt="image" src="https://github.com/user-attachments/assets/5e066f84-8aac-41ee-a2fe-1dae8b9b0a4f" /> | <img width="550" height="157" alt="image" src="https://github.com/user-attachments/assets/78ac105a-351b-45fe-bf2e-652a1a602d2d" /> |
--- …
=> chore(errors): augment custom errors type with metadata

.changeset/angry-poets-cover.md, apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/SyncOnboardingCompanion.tsx, apps/ledger-live-mobile/src/screens/SyncOnboarding/SyncOnboardingCompanion.tsx
- ...
Now we have four ways to seed a device:
- new seed => Backup Recovery Key 🔑
- restore using Secret Recovery Phrase => Backup Recovery Key 🔑
- restore using Recovery Key => Next step ‼️
- restore using Recover subscription => Backup Recovery Key 🔑
Three of them except Recovery Key seed will trigger the Backup Recovery Key step, but the Recovery Key seed will pass directly to the install apps step, so its tracking should be treated separately. With this fix the tracking event can be correctly triggered after the Recovery Key seed on both LLM and LLD.
Demo with LLD:
https://github.com/user-attachments/assets/0a32a7eb-c1fe-4bf6-b838-f05ef2ff235d
- **JIRA or GitHub link**: [LIVE-20605](https://ledgerhq.atlassian.net/browse/LIVE-20605)
---
- **The code aligns with the requirements** …
=> [Fix] Fix a tracking issue during Recovery Key onboarding

libs/coin-framework/src/currencies/__snapshots__/formatCurrencyUnit.test.ts.snap
=> test(coin-framework): update currencies snapshot fo include Canton

.changeset/tall-dodos-rule.md, libs/coin-modules/coin-polkadot/src/network/sidecar.ts, libs/coin-modules/coin-polkadot/src/network/sidecar.unit.test.ts, libs/coin-modules/coin-polkadot/src/network/types.ts, libs/coin-tester-modules/coin-tester-polkadot/src/scenarii/Polkadot.ts
- `Balance` on the balance account dashboard should be correctly displayed
Wrong balance for Polkadot accounts
Users were not able to see their full `balance` on the account. `Bounded` and `unbonding` are missing on the computation.
- `Balance` updated with the correct computation, adding unbonded and unbonding value
- `Spendable balance` need no more computation, Sidecar provide a computed value `transferable`
- Unit tests on the `getBalances`function
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/LIVE-20643?atlOrigin=eyJpIjoiMDM1Y2QwYzBiM2Y5NGI1ZDhkYzQ4MDIwMzgzYmNmZDciLCJwIjoiaiJ9
--- …
=> Wrong balance for Polkadot accounts

.changeset/nine-foxes-flash.md, apps/ledger-live-desktop/src/renderer/families/stellar/operationDetails.tsx, libs/ledger-live-common/src/families/stellar/__snapshots__/bridge.integration.test.ts.snap, libs/ledger-live-common/src/families/stellar/ui.ts
- LLD stellar transaction details
This fixes some UI regressions introduced in #11120:
- make operation display backward compatible with old structure, to avoid having to reindex all accounts
- don't show memo row in details when memo is unset/NO_MEMO/unknown type
- BACK-9348
--- …
=> fix(BACK-9348): stellar operation details UI fixes

.changeset/six-trainers-train.md, apps/ledger-live-mobile/src/context/AuthPass/auth.hooks.ts
- ...
Prevent Android locking on false-positive background->active state changes
Before:
https://github.com/user-attachments/assets/c41fb7b9-e01f-4db9-9bcf-f245370b572b
After:
https://github.com/user-attachments/assets/36a04277-4bb8-4f76-8a12-e55e79df4413
- **JIRA or GitHub link**: [LIVE-20760](https://ledgerhq.atlassian.net/browse/LIVE-20760)
--- …
=> fix(LLM): prevent android locks on transient AppState changes

.changeset/clean-mails-watch.md, apps/ledger-live-mobile/src/components/WebPTXPlayer/CustomHandlers.ts
Using `navigation.popToTop` works in buy/sell as we have no additional routing within the app so it is not intercepted by this listener and it successfully goes back to the homepage
Swap has additional routing and our history stack can get messy. Doing:
```
navigation.getParent()?.navigate(NavigatorName.Base, {
screen: NavigatorName.Main,
});
```
Forces us to load the main screen and unload swap 
- [LIVE-20692](https://ledgerhq.atlassian.net/browse/LIVE-20692)
--- …
=> fix: custom close for card

.changeset/shy-cats-rush.md, apps/ledger-live-desktop/src/renderer/actions/constants.ts, apps/ledger-live-desktop/src/renderer/actions/settings.ts, apps/ledger-live-desktop/src/renderer/hooks/useBraze.ts, apps/ledger-live-desktop/src/renderer/hooks/useNotifications.ts, apps/ledger-live-desktop/src/renderer/reducers/settings.test.ts, apps/ledger-live-desktop/src/renderer/reducers/settings.ts, apps/ledger-live-desktop/src/types/dynamicContent.ts, libs/ledger-live-common/src/braze/anonymousUsers.ts
- Some changes in how anonymous notifications are purged when tracking stops.
- Prevents unnecessary renders and API calls.
- Reduces CPU usage and resolves the infinite loop.
- Keeps purge behaviour intact for stale notifications.
This PR addresses an infinite loop issue observed in [PROD-11430](https://ledgerhq.atlassian.net/browse/PROD-11430), where CLEAR_DISMISSED_CONTENT_CARDS and updateAnonymousUserNotifications were repeatedly dispatched, causing extreme CPU usage and UI lag.
The issue occurs for untracked users when `anonymousUserNotifications` contains a mix of expired and valid entries during initialisation. The purge logic in useBraze partially removes expired items but still generates a new object reference on every run. Because this updated object is part of the `initBraze` …
=> LIVE-20867: prevent infinite rendering cycles when purging anonymous notifications

.changeset/tricky-eels-remain.md, apps/ledger-live-mobile/__tests__/test-renderer.tsx, apps/ledger-live-mobile/src/actions/auth.ts, apps/ledger-live-mobile/src/actions/types.ts, apps/ledger-live-mobile/src/components/RequestBiometricAuth.ts, apps/ledger-live-mobile/src/context/AuthPass/AuthScreen.tsx, apps/ledger-live-mobile/src/context/AuthPass/auth.hooks.ts, apps/ledger-live-mobile/src/context/AuthPass/index.tsx, apps/ledger-live-mobile/src/reducers/__tests__/auth.test.ts, apps/ledger-live-mobile/src/reducers/auth.ts, apps/ledger-live-mobile/src/reducers/index.ts, apps/ledger-live-mobile/src/reducers/types.ts, apps/ledger-live-mobile/src/screens/Settings/General/BiometricsRow.tsx
- Redux behaviour around authentication covered by unit tests
- Refactors code around authentication flow to use Redux - both password and biometrics. Authentication behaviour should remain the same - triggering upon initial load and reentering the app. Skip authentication behaviour should remain the same, demonstrated from reopening the app from the debug page. 
- Fixes bugs mentioned below around authentication triggers 
Refactors AuthPass to use Redux 
Fixes existing bugs:
- When FaceID is enabled, disabling it correctly requires FaceID authentication, but reopening the app required one more FaceID authentication. This is now fixed to prevent subsequent FaceID authentication after disabling
- When FaceID is enabled, opening the app correctly requires FaceID, but reopening the app …
=> Refactor(LLM) LIVE-19861 refactor AuthPass

.changeset/olive-moose-bake.md, libs/coin-modules/coin-stellar/src/network/horizon.ts, libs/coin-modules/coin-stellar/src/polyfill.ts, package.json, patches/@exodus__patch-broken-hermes-typed-arrays.patch, pnpm-lock.yaml
- Patch package `@exodus/patch-broken-hermes-typed-arrays"`
Previously, the fix from `@exodus/patch-broken-hermes-typed-arrays` didn’t work reliably because Node would execute the `require` only once (due to nodejs module caching). As a result, subsequent calls relying on the patch would fail.
With this PR:
* I modified the package via **patch-package** to export the patch function instead of auto-running it,
* I now call the function directly when needed, bypassing the single `require` execution limitation.
This ensures the fix runs every time it’s needed, preventing errors during broadcast calls.
- **JIRA**: https://ledgerhq.atlassian.net/browse/LIVE-20933
--- …
=> fix(coin-stellar): second send token

.changeset/ninety-peaches-report.md, apps/ledger-live-mobile/src/components/Web3AppWebview/NoAccountScreen.tsx, apps/ledger-live-mobile/src/components/Web3AppWebview/PlatformAPIWebview.tsx, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/hooks/useDrawerLifecycle.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/screens/AssetSelection/index.tsx
- LLM modular drawer tracking is now enabled for Live Apps
- Fixes analytics for SearchInput and closeButton in the Network step
- Enable LLM modular drawer tracking for Live Apps
- Fix analytics on SearchInput and closeButton in the Network step
Tracking Plan: https://ledgerhq.atlassian.net/wiki/spaces/WXP/pages/5533728769/MVP+Modular+Drawer-+LLD+Data+Tracking+Plan
- **JIRA or GitHub link**: [LIVE-20433]
--- …
=> LLM MAD Analytics for Live Apps

.changeset/happy-rules-sneeze.md, libs/coin-modules/coin-solana/src/__fixtures__/solana-spl-epjfwdd5aufqssqem2qn1xzybapc8g4weggkzwytdt1v.json, libs/coin-modules/coin-solana/src/bridge.integration.test.ts, libs/coin-modules/coin-solana/src/bridge/js.ts, libs/coin-modules/coin-solana/src/cli-transaction.ts, libs/coin-modules/coin-solana/src/cryptoAssetsStore.test.ts, libs/coin-modules/coin-solana/src/cryptoAssetsStore.ts, libs/coin-modules/coin-solana/src/helpers/token.ts, libs/coin-modules/coin-solana/src/prepareTransaction.ts, libs/coin-modules/coin-solana/src/synchronization.ts, libs/coin-modules/coin-solana/src/tests/tokens-bridge.unit.test.ts, libs/coin-modules/coin-solana/src/transaction.ts, libs/coin-tester-modules/coin-tester-solana/src/scenarii.test.ts, libs/ledger-live-common/src/families/solana/setup.ts
- Solana Token Retrieval in coin-solana
To be able to call the CAL dynamically, we need to inject the `CryptoAssetsStore` into concerned module. 
Implementation will be provided by LiveHub team. This ticket is for the Solana coin module.
- `CryptoAssetsStore` injected into `coin-solana`
- A getter function is used instead of a variable for the `CryptoAssetsStore`, to be able to switch between legacy and new system with feature flag on runtime
- **JIRA**: https://ledgerhq.atlassian.net/browse/LIVE-19997
--- …
=> feat: Update Solana createBridge function signature for Lazy CAL

.changeset/olive-ads-brush.md, apps/ledger-live-desktop/src/renderer/components/TopBar/NotificationIndicator/AnnouncementPanel.tsx, apps/ledger-live-desktop/src/renderer/hooks/useDateFormatter.test.tsx, apps/ledger-live-desktop/src/renderer/hooks/useDateFormatter.ts
- Notif panel
The notification panel is only used by Braze. Our implementation had a good logic but weird behavior in that case. Because Braze uses the language property to determine the language to use but we displayed the Date with the locale. 
To override this I added a forcedLanguage prop to useDateFormatted
|<img width="482" height="746" alt="Screenshot 2025-08-28 at 5 29 45 PM" src="https://github.com/user-attachments/assets/081083c9-c971-476e-a428-da9c62cf9535" />|<img width="484" height="782" alt="Screenshot 2025-08-28 at 5 29 31 PM" src="https://github.com/user-attachments/assets/8b75d770-9a85-432b-94f5-2f60a711419a" />               | …
=> :bug: (lld) use lang instead of locale in notif panel

.changeset/angry-beds-occur.md, libs/ledger-live-common/src/bridge/generic-alpaca/alpaca/index.ts, libs/ledger-live-common/src/bridge/generic-alpaca/alpaca/index.unit.test.ts
- ...
Fix issue introduced on develop that woul'nt retrieve api anymore on xrp
---
=> xrp alpaca switch fix

.changeset/lucky-beds-draw.md, apps/ledger-live-mobile/android/app/build.gradle, apps/ledger-live-mobile/android/build.gradle
- Android builds now use NDK r28.0.12674087 instead of r27.1.12297006
- A bunch of native libraries are automatically compiled with 16KB page alignment
- Improved compatibility with future Android devices using 16KB memory pages
- No functional changes to the app behavior
This PR upgrades the Android NDK from version **r27.1.12297006** to **r28.0.12674087** to ensure compatibility with future Android devices that use 16KB memory pages instead of the traditional 4KB pages.
What is fixed by NDK upgrade alone:
- **JIRA or GitHub link**: LIVE-21183
--- …
=> Upgrade Android NDK from r27 to r28

.changeset/wise-jokes-wonder.md, libs/ui/packages/react/src/components/tabs/Chip/index.tsx
- ...
This PR fixes the Tab indicator sync issue
| Before       
| 
| ------------- |
| After         |
|               |               |
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-21396
--- …
=> fix: Tab Indicator Sync

.changeset/clean-spoons-do.md, apps/ledger-live-mobile/src/components/RootNavigator/MainNavigator.tsx
- ...
Change rendering strategy for Earn app tab
https://github.com/user-attachments/assets/6383447d-f58a-47f2-8dde-c03679e78712
- **JIRA or GitHub link**: [LIVE-21429](https://ledgerhq.atlassian.net/browse/LIVE-21429)
- [Confluence](https://ledgerhq.atlassian.net/wiki/spaces/PTX/pages/6200557585/MOBILE+Rendering+on+Ledger-Live)
---
- …
=> feat(LIVE-21429): Update rendering strategy on earn tab navigation

.changeset/thick-years-boil.md, libs/coin-modules/coin-xrp/src/logic/getBalance.test.ts, libs/coin-modules/coin-xrp/src/logic/getBalance.ts, libs/ledger-live-common/src/bridge/generic-alpaca/tests/getAccountShape.test.ts
- ...
XRP as locked value set to 1, so if balance is 0 we see a negative value !
To avoid that, if spendable balance is negative then we set it to 0.
- **JIRA or GitHub link**: [LIVE-21395](https://ledgerhq.atlassian.net/browse/LIVE-21395)
--- …
=> fix: xrp negative balance

.changeset/eighty-apricots-carry.md, libs/ledger-live-common/src/modularDrawer/hooks/useAssetsData.ts
- Fixes infinite scroll
Fixes infinite scroll whilst preserving skeleton on search
Before:
https://github.com/user-attachments/assets/c259ab40-b4ab-4974-9632-24d318f4688f
After: 
https://github.com/user-attachments/assets/1e42cce2-34a2-4b16-894b-98956bc4ef42
- **JIRA or GitHub link**: [LIVE-21427](https://ledgerhq.atlassian.net/browse/LIVE-21427)
--- …
=> fix(LLD): MAD data hook isloading should exclude next page loads

.changeset/eight-zebras-end.md, libs/coin-modules/coin-sui/src/api/index.integration.test.ts, libs/coin-modules/coin-sui/src/network/sdk.ts
- fix the token on last page (sui list operations)
- block height is a number, conform to coin-fw api (sui list operations)
=> fix(back-9674): cursor on last page + block height type

.changeset/hot-rings-fail.md, libs/ledgerjs/packages/cryptoassets/src/currencies.ts
- ...
Update canton blockavgtime, implies 18 confirmations required instead of 90
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-21545
---
=> update canton blockavg

.changeset/new-walls-peel.md, apps/ledger-live-mobile/src/components/RootNavigator/SettingsNavigator.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/ManageInstances/DeletionSuccess.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/ManageKey/DeletionSuccess.tsx
- ...
We have some issues caused by the way we handle the navigation in LLM that have been revealed by react navigation v7. The bug was caused by a duplication of the screen. And when we pressed the open drawer it killed it directly as the press was trigger twice
https://github.com/user-attachments/assets/66ab5615-8de8-49fc-a0f1-ec1b38c6d4d5
https://github.com/user-attachments/assets/e48845b0-80e1-4c5c-9232-f629fc51a161
- **JIRA or GitHub link**:[LIVE-21665](https://ledgerhq.atlassian.net/browse/LIVE-21665) 
--- …
=> :bug: (llm-LS) duplicated screen during navigation

.changeset/dull-humans-deliver.md, .changeset/orange-pumpkins-hug.md, apps/ledger-live-desktop/src/main/window-lifecycle.ts, apps/ledger-live-desktop/src/renderer/components/WebPlatformPlayer/TopBar.tsx, apps/ledger-live-desktop/src/renderer/screens/platform/v2/Catalog/Card/Minimum.tsx, apps/ledger-live-desktop/tests/models/LiveAppWebview.ts, apps/ledger-live-desktop/tests/page/discover.page.ts, apps/ledger-live-desktop/tests/specs/webviewDevTools/webview-dev-tools.spec.ts, libs/ledger-live-common/src/wallet-api/react.ts
- Any live-app devtools usage
This pull request introduces a minor release for both `ledger-live-desktop` and `@ledgerhq/live-common`, focusing on improvements to the DevTools lifecycle in webviews and a fix for the `UsedAt` type. The most significant changes ensure that DevTools windows are automatically closed when their associated webviews are destroyed, preventing orphaned windows, and that the `UsedAt` type is correctly handled throughout the codebase. Additional updates include new E2E tests to verify DevTools behavior and improved test selectors for UI components.
**Webview DevTools lifecycle improvements:**
* Automatically closes DevTools WebContents when webviews are destroyed to prevent orphaned DevTools windows (`window-lifecycle.ts`). …
=> fix: auto close DevTools WebContents when webviews are destroyed

.changeset/hip-points-care.md, apps/ledger-live-mobile/android/app/build.gradle, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/components/Skeleton/SkeletonList.tsx, libs/ui/packages/native/src/pre-ldls/components/Input/Input.tsx
- SkeletonList LLM MAD
- SearchInput onBlur/onFocus typing
Fix the following error: 
`Error while updating property flex in shadow node of type RCTView java.lang.String cannot be cast to java.lang.Double`
+ remove the "any" in the ui lib to enforce typing
|https://github.com/user-attachments/assets/a8d25797-161f-4965-8eba-5cf23870ae16|https://github.com/user-attachments/assets/516c0c5a-f4c1-45ca-a19f-68c7529ebb33|
- **JIRA or GitHub link**: [LIVE-21698](https://ledgerhq.atlassian.net/browse/LIVE-21698)
---
- **There …
=> :bug: (llm) fix unsupported string property + typing

.changeset/late-rats-live.md, apps/ledger-live-mobile/src/screens/Platform/exchange/StartExchange.tsx, apps/ledger-live-mobile/src/screens/SkipSelectDevice.tsx
This reverts commit 6cf6b1a775d36e5e935c185ace4e32129dffa7ff.
- ...
Revert "feat(LIVE-21138): only auto select device if it's available"
---
=> Revert "feat(LIVE-21138): only auto select device if it's available"

.changeset/angry-kangaroos-exist.md, apps/ledger-live-desktop/src/main/index.ts
- LLD MacOS
- on close window
For unknown reason, this old bug is back: Ledger Live doesn't want to exit from Dock when you close on Mac OS.
We let 3s to be sure all fs is saved (e.g. app.json saves) and after we force its exit.
- **JIRA or GitHub link**: [LIVE-21819](https://ledgerhq.atlassian.net/browse/LIVE-21819)
---
- …
=> fix(LLD): force MacOS to exit on window close

.changeset/twenty-books-pull.md, apps/ledger-live-desktop/src/renderer/families/canton/StepReceiveFunds.tsx, apps/ledger-live-desktop/src/renderer/modals/Receive/steps/StepReceiveFunds.tsx
- receive flow normal & canton
We don't want to display "shared securely" if the user bypass the device check 
We should trigger onFinishReceiveFlow instead of updating the verify state
https://github.com/user-attachments/assets/b20c76c1-7415-4dd1-96b8-0c56927a6797
- **JIRA or GitHub link**: [LIVE-21351](https://ledgerhq.atlassian.net/browse/LIVE-21351)
--- …
=> :bug: (LLD) remove shared securely during receive flow if bypass

.changeset/rotten-dragons-buy.md, apps/ledger-live-mobile/src/components/ConfirmationModal.tsx, apps/ledger-live-mobile/src/components/NavigationHeaderCloseButton.tsx
- ...
When no `Icon` or `image` props were provided, the `confirmationTitle` would take full width and potentially overlap with the close button, making it unclickable.
https://github.com/user-attachments/assets/c186c14d-57fe-4ee3-a8a0-5e63270fc8b8
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-21884
---
- …
=> fix: confirmation modal onClose was not clickable

.changeset/quick-oranges-beg.md, libs/coin-modules/coin-sui/src/network/sdk.test.ts, libs/coin-modules/coin-sui/src/network/sdk.ts
- alpaca api for coin:sui returns positive amounts, even for staking
- no impact for bridge (different code path)
IN or OUT operations always return positive amounts
but UNSTAKING was returning a negative
we believe this is inconsistent API. It's UI to job to negate the amount if that makes sense for user.
https://ledgerhq.atlassian.net/browse/BACK-9784
--- …
=> fix(coin:sui): return positive amount for undelegate operations

.changeset/wise-ligers-float.md, apps/ledger-live-mobile/ios/ledgerlivemobile/Info.plist, apps/ledger-live-mobile/ios/ledgerlivemobileTests/Info.plist
- IOS
As RN is not fully compatible with liquid glass, we can deactivate it using UIDesignRequiresCompatibility (as reco by Apple)
Apple doc: 
https://developer.apple.com/documentation/BundleResources/Information-Property-List/UIDesignRequiresCompatibility
|<img width="1206" height="2622" alt="image" src="https://github.com/user-attachments/assets/27aa46f4-69bb-4499-ae1e-26bf78775d85" />| https://github.com/user-attachments/assets/d322c4cc-5929-46c4-a51f-7a919c988aa1| 
- **JIRA or GitHub link**: [LIVE-21865](https://ledgerhq.atlassian.net/browse/LIVE-21865)
---
- **The PR description clearly documents the changes** made and explains …
=> 🐛 (IOS) disable liquid glass

.changeset/fuzzy-maps-love.md, libs/coin-modules/coin-canton/src/common-logic/utils.test.ts, libs/coin-modules/coin-canton/src/common-logic/utils.ts
- ...
allow alphanumeric after ::  for example abc::zxc123
---
=> fix: canton allow alphanumeric

.changeset/breezy-queens-agree.md, libs/ledger-live-common/src/exchange/swap/updateAccountSwapStatus.ts
- Added operationId to status request on swap history
This PR adds `operationId` to the request to get the transaction status from swap for `nearintents` provider.
- **JIRA or GitHub link**: [LIVE-21230](https://ledgerhq.atlassian.net/browse/LIVE-21230) 
--- …
=> [LIVE-21230] Added operationId to status request on swap history for nearintents

.changeset/tasty-knives-design.md, libs/coin-modules/coin-solana/src/network/chain/account/tokenExtensions.ts, libs/coin-modules/coin-solana/src/prepareTransaction.test.ts
- Solana users should be able to send SPL 2022 that have unknown extensions
Solana users are not able to send SPL 2022 that have unknown extensions. It is the case in the screenshot below, with the `defaultAccountState` extension.
Note this is very similar to https://github.com/LedgerHQ/ledger-live/pull/11013, at the account level.
| <img width="513" height="738" alt="image" src="https://github.com/user-attachments/assets/70a97a78-88ab-4a14-adef-e3457534b0fc" /> | <img width="513" height="738" alt="image" src="https://github.com/user-attachments/assets/5edd45af-36f8-4c45-a58b-72c97e14cdc5" /> |
---
- **The …
=> fix(coin-solana) do not reject unknown SPL 2022 extensions

.changeset/metal-mayflies-check.md, apps/ledger-live-desktop/src/newArch/components/ProviderInterstitial/ProviderInterstitial.test.tsx, apps/ledger-live-desktop/src/newArch/components/ProviderInterstitial/index.tsx, apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/types.ts, apps/ledger-live-desktop/src/renderer/components/WebPlatformPlayer/index.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/index.tsx, apps/ledger-live-desktop/src/renderer/screens/receive/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/components/WebPTXPlayer/index.tsx, apps/ledger-live-mobile/src/components/WebReceivePlayer/index.tsx, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/components/ProviderInterstitial/ProviderInterstitial.test.tsx, apps/ledger-live-mobile/src/newArch/components/ProviderInterstitial/index.tsx, apps/ledger-live-mobile/src/screens/PTX/index.tsx
- ...
Added the provider interstitial to the noah flow. Hopefully moved the existing components into more logical places now it is shared across screens.
Mobile:
Desktop:
https://ledgerhq.atlassian.net/browse/LIVE-21389
--- …
=> feat: LIVE-21389 add noah loading screen

.changeset/forty-boats-taste.md, apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/DrawerFooter.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- ...
This PR Implements A/B test: transaction details vs simplified confirm prompt (desktop)
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-21558
--- …
=> feat: (LIVE-21558) Add A/B test for desktop ‘Confirm on Device’ flow (details vs no-details)

.changeset/flat-actors-protect.md, apps/ledger-live-desktop/src/renderer/screens/receive/index.tsx, apps/ledger-live-mobile/src/screens/ReceiveFunds/01b-ReceiveProvider..tsx, libs/env/src/env.ts, libs/ledger-live-common/.unimportedrc.json, libs/ledger-live-common/src/hooks/useManifestWithSessionId.test.ts, libs/ledger-live-common/src/hooks/useManifestWithSessionId.ts
- ...
In order for tracking to be correctly sent from the Noah live app we need to supply them with the providerSessionId. For Noah this is sent as `externalId`.
Below a test live app that is outputting the url params. Mobile doesn't have locale or theme - I'm looking at that separately:
https://ledgerhq.atlassian.net/browse/LIVE-21973
--- …
=> feat: LIVE-21973 add provider session id to noah

.changeset/rare-radios-relax.md, apps/ledger-live-desktop/src/newArch/features/AnalyticsOptInPrompt/screens/VariantA/Main/index.tsx
- optin prompt
The opt-in prompt had a double scroll layout
No issue with the other variant
|https://github.com/user-attachments/assets/6d45e597-dd5e-47a6-9d0a-b1b2ba82f646|https://github.com/user-attachments/assets/02978a6b-1448-47ed-bcf3-60705ae4fdb6|
- **JIRA or GitHub link**: [LIVE-21998](https://ledgerhq.atlassian.net/browse/LIVE-21998)
--- …
=> :bug: (LLD) fix opt in prompt double scroll

.changeset/tame-drinks-raise.md, apps/ledger-live-desktop/src/renderer/screens/receive/index.tsx
- ...
Add the close button on the receive provider screen. It returns from the previous screen the user was on and re-opens the menu.
Before:
After:
https://github.com/user-attachments/assets/52ff2032-c7c2-4a8c-ba60-4777482310bd
https://ledgerhq.atlassian.net/browse/LIVE-22111
--- …
=> feat: LIVE-22111 close noah desktop

.changeset/old-points-bathe.md, apps/ledger-live-desktop/src/renderer/families/cosmos/DelegationFlowModal/fields/ValidatorField.tsx
- ...
If a problem happens when trying to retrieve validator.validatorAddress the APP should not crash 
- **JIRA or GitHub link**:  [LIVE-21620](https://ledgerhq.atlassian.net/browse/LIVE-21620)
- [LIVE-22017](https://ledgerhq.atlassian.net/browse/LIVE-22017)
--- …
=> fix: Delegation crashes on Cosmos if no validator data is returned

.changeset/popular-turkeys-trade.md, apps/ledger-live-desktop/src/renderer/modals/AddAccounts/steps/StepImport.tsx
- coin-canton
fixing problem when canton account could be added with wrong index
- [LIVE-22040](https://ledgerhq.atlassian.net/browse/LIVE-22040)
---
[LIVE-22040]: …
=> fix: canton add account with wrong index

.changeset/kind-tools-reflect.md, libs/coin-modules/coin-sui/src/api/index.integration.test.ts, libs/coin-modules/coin-sui/src/network/sdk.test.ts, libs/coin-modules/coin-sui/src/network/sdk.ts
- coin module identifies staking/unstaking operations even if they are not the first move call of the transaction
- There was a regression identifying unstaking operations (see ticket) when the move call (ie: the function of the contract that proceeds to the unstaking) is not the first one of the list in the tx (a tx can call many functions)
- I think there was also an historical bug on staking operations (with same conditions) that is also fixed in this PR
- https://ledgerhq.atlassian.net/browse/LIVE-22119
--- …
=> fix(live-22119,coin:sui): identify all unstaking operations
