LedgerHQ/ledger-live

.changeset/hip-crabs-develop.md, apps/ledger-live-mobile/src/components/SelectDevice2/index.tsx, apps/ledger-live-mobile/src/screens/MyLedgerChooseDevice/index.tsx
-My ledger screen
Fix an extra margin at the bottom of my ledger screen
|![Simulator Screenshot - iPhone 15 - 2024-11-27 at 17 30 02](https://github.com/user-attachments/assets/dcd2533c-6d73-45d3-a24e-f815b61c28d8)|![Simulator Screenshot - iPhone 15 - 2024-11-27 at 17 29 47](https://github.com/user-attachments/assets/a3cebd6e-d00f-4b80-8220-d791120fe047)|
https://github.com/user-attachments/assets/beb7ddb3-be40-4e5a-bd91-5e86abfac157
- **JIRA or GitHub link**: NOT NEEDED 
--- …
=> :bug: (llm) layout issue on my ledger screen

apps/ledger-live-desktop/package.json, apps/ledger-live-desktop/src/renderer/App.tsx, apps/ledger-live-desktop/src/renderer/live-common-setup.ts, libs/live-dmk/package.json, libs/live-dmk/src/index.tsx, libs/live-dmk/src/useDeviceSessionState.test.tsx, pnpm-lock.yaml
- ...
- **JIRA or GitHub link**: [DSDK-517](https://ledgerhq.atlassian.net/browse/DSDK-517)
--- …
=> feat(lld): transportDMK registration

.changeset/mean-tables-behave.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx
- ...
Many fix for fee drawer (UI and returns more values)
[- **JIRA or GitHub link**: ](https://ledgerhq.atlassian.net/browse/LIVE-15100)
---
=> Fix/swap UI gas limit

.changeset/fifty-shrimps-hide.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx
=> fix: default gas limit

apps/ledger-live-desktop/src/renderer/screens/dashboard/AssetDistribution/Row.tsx, apps/ledger-live-desktop/tests/page/portfolio.page.ts, apps/ledger-live-desktop/tests/specs/speculos/settings.spec.ts
=> [QAA] Speculos nightly fix

libs/ledger-live-common/src/families/cardano/exchange.ts, libs/ledger-live-common/src/generated/exchange.ts
- ...
Add function to extract derivationPath for Exchange flow.
- **JIRA or GitHub link**: [LIVE-15059]
---
[LIVE-15059]: https://ledgerhq.atlassian.net/browse/LIVE-15059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5 …
=> [ADA] Add extract derivationPath from Account for Swap

.changeset/honest-feet-trade.md, apps/ledger-live-desktop/src/renderer/drawers/SwapOperationDetails/index.tsx
- ...
fix swapId overflow swap history
https://ledgerhq.atlassian.net/browse/LIVE-15002
---
=> bugfix(LIVE-15002): fix swapId overflow swap history

libs/ledger-live-common/src/families/aptos/constants.ts, libs/ledger-live-common/src/families/aptos/logic.ts
- ...
The list of account transactions is not full. This PR extends the tx processing to allow more transactions to be visible for the account
- **JIRA or GitHub link**: [LIVE-14960](https://ledgerhq.atlassian.net/browse/LIVE-14960)
--- …
=> Aptos fixing: History isn't full

.changeset/spicy-schools-look.md, apps/ledger-live-desktop/src/renderer/live-common-setup.ts
- Fix access to speculos transport
[WIP]
---
=> fix(lld): speculos transport

.changeset/eight-ducks-rescue.md, apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/types/BaseNavigator.ts, apps/ledger-live-mobile/src/const/navigation.ts, apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/Navigator.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/components/SelectAddAccountMethod/useSelectAddAccountMethodViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/types.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/ScanDeviceAccounts/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/SelectAccounts/index.tsx, apps/ledger-live-mobile/src/newArch/features/AssetSelection/Navigator.tsx, apps/ledger-live-mobile/src/newArch/features/AssetSelection/screens/SelectCrypto/index.tsx, apps/ledger-live-mobile/src/newArch/features/AssetSelection/screens/SelectNetwork/index.tsx, apps/ledger-live-mobile/src/newArch/features/AssetSelection/screens/SelectNetwork/types.ts, apps/ledger-live-mobile/src/newArch/features/AssetSelection/types.ts, apps/ledger-live-mobile/src/newArch/features/DeviceSelection/Navigator.tsx, apps/ledger-live-mobile/src/newArch/features/DeviceSelection/screens/ConnectDevice/index.tsx, apps/ledger-live-mobile/src/newArch/features/DeviceSelection/screens/SelectDevice/index.tsx, apps/ledger-live-mobile/src/newArch/features/DeviceSelection/types.ts
- ...
**Please read this before merging** 🚨
```
apps/
└── ledger-live-mobile/
└── src/
├── components/
│   └── RootNavigator/
│       ├── BaseNavigator.tsx //add new navigators (feature flagged)
│       └── types/
│           └── BaseNavigator.ts // add new navigators params list types here
├── const/
│   └── navigation.ts // add navigator names
├── navigation/
│   └── DeeplinksProvider.tsx // support entry point to new Add account flow via feature flag
└── newArch/
├── features/
│   ├── Accounts/
│   │   ├── Navigator.tsx // main navigator of the Account context
│   │   └── screens/
│   │       ├── AddAccount/
│   │       │   ├── components/
│   │       │   │   └── SelectAddAccountMethod/
│   │       │   │       └── useSelectAddAccountMethodViewModel.ts
│   │       │   ├── types.ts
│   │ …
```
=> refactor: copy & rename  Receive's reusable step screens for new add account flow

apps/ledger-live-desktop/src/renderer/modals/AddAccounts/steps/StepChooseCurrency.tsx, apps/ledger-live-mobile/src/screens/AddAccounts/01-SelectCrypto.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- ...
Add aptos coin feature flag in the code
- [LIVE-13990]
---
[LIVE-13990]: https://ledgerhq.atlassian.net/browse/LIVE-13990?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1c …
=> feat(aptos): add coin feature flag

apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts
=> Update test send NFT to ENS

.changeset/heavy-starfishes-fix.md, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useOnTrustchainRefreshNeeded.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useRemoveMember.ts
- Ledger Sync
Improve Ledger Sync error when a removed member tries to remove another member
|![Screenshot_2024-11-25-18-27-36-65_99c1b3bb631177f8a9e1379ae5b12ffe](https://github.com/user-attachments/assets/16620560-3261-45ed-9382-ea744432cfd1)|![Screenshot_2024-11-25-17-08-24-86_99c1b3bb631177f8a9e1379ae5b12ffe](https://github.com/user-attachments/assets/d290f40e-05b9-4363-a069-eacad7f23e66)|
- **JIRA or GitHub link**: [LIVE-14550]
--- …
=> 🐛 LLM - Improve Ledger Sync error when a removed member tries to remove another member

.changeset/light-poets-smile.md, apps/ledger-live-mobile/src/components/RootNavigator/SettingsNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/types/SettingsNavigator.ts, apps/ledger-live-mobile/src/const/navigation.ts, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/Platform/Catalog/AppCard.tsx, apps/ledger-live-mobile/src/screens/Settings/Developer/ExchangeDeveloperMode.tsx, apps/ledger-live-mobile/src/screens/Settings/Developer/index.tsx, libs/ledger-live-common/src/exchange/providers/index.ts
Add exchange dev mode in LLM. 
https://github.com/user-attachments/assets/2065e2ac-123a-481d-88c7-559a5e6c3e9e
- ...
- **JIRA or GitHub link**: [LIVE-14434](https://ledgerhq.atlassian.net/browse/LIVE-14434)
--- …
=> Live 14434 sell card swap create exchange dev mode for llm

.changeset/cyan-singers-mix.md, apps/ledger-live-desktop/src/renderer/hooks/useDeeplinking/useDeepLinkHandler.ts, apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx
Enable /card Deeplink
https://github.com/user-attachments/assets/aa41a6d1-98b2-45a6-87e8-586611124f64
For LLM I did a small hack in buy-sell UI to add the links to ledgerlive://card and other deeplinks.
https://github.com/user-attachments/assets/6a926a1c-333a-480b-b8fd-b87c8565deaa
- ... …
=> Live 15092 card create ledgerlive card deeplink to send user to the card live app

.changeset/beige-moose-worry.md, apps/ledger-live-mobile/src/analytics/segment.ts, apps/ledger-live-mobile/src/screens/GetDeviceScreen.tsx, apps/ledger-live-mobile/src/screens/Onboarding/steps/discoverLiveInfo.tsx, apps/ledger-live-mobile/src/screens/Onboarding/steps/postWelcomeSelection.tsx, apps/ledger-live-mobile/src/screens/Onboarding/steps/welcome.tsx
- reborn analytics
Enhance onBoarding analytics
onBoardingHasDevice => should change only if the user select it from onBoarding. If the user doesn't have a ledger during onboarding this will be false forever. If he has it will be true. 
isReborn => I use readonly state to set it as it's the same mechanism
the medias are too big to be post here so refer to the ticket ! 
OnBoardingHasDevice : [video](https://ledgerhq.atlassian.net/browse/LIVE-14746?focusedCommentId=498198)
IsReborn : [video](https://ledgerhq.atlassian.net/browse/LIVE-14746?focusedCommentId=498203)
- **JIRA or GitHub link**:[LIVE-14746](https://ledgerhq.atlassian.net/browse/LIVE-14746) 
--- …
=> :sparkles: (llm): onboarding analytics

.changeset/late-phones-add.md, apps/ledger-live-mobile/jest.config.js, apps/ledger-live-mobile/src/contentCards/cards/hero/elements.tsx, apps/ledger-live-mobile/src/contentCards/cards/hero/index.tsx, apps/ledger-live-mobile/src/contentCards/cards/vertical/elements.tsx, apps/ledger-live-mobile/src/contentCards/cards/vertical/index.tsx, apps/ledger-live-mobile/src/dynamicContent/ContentCardsCategory/Header.tsx, apps/ledger-live-mobile/src/dynamicContent/ContentCardsCategory/index.tsx, apps/ledger-live-mobile/src/dynamicContent/types.ts, apps/ledger-live-mobile/src/dynamicContent/utils.tsx
- Braze CC
Polish for dynamic content from Braze following feedback from Growth team. Also add the possibility to display video and gif using FastImage (native Image doesn't support gif) 
to see more examples you can go to confluence there is more screenshots ! 
new Medium filled image CC (see confluence for more accurate screenshots) : 
| Light        | Dark         |
|![image](https://github.com/user-attachments/assets/25e78411-322d-4e72-8a2f-71e9c52a4c00)|![image](https://github.com/user-attachments/assets/6961b355-a6dd-4571-9fa0-bab2cb335966)|
Flexible Hero Card (made all fields optional so growth is free to add the one they want) : 
Video demo : 
<video src="https://github.com/user-attachments/assets/eada7869-68c1-4bfb-9831-39f6dc5dbac3" />
GIF/IMAGE …
=> :lipstick:(llm) polish braze and support video/gif

apps/cli/src/commands/live/ledgerKeyRingProtocol.ts, apps/ledger-live-mobile/e2e/page/accounts/accounts.page.ts, apps/ledger-live-mobile/e2e/page/common.page.ts, apps/ledger-live-mobile/e2e/page/index.ts, apps/ledger-live-mobile/e2e/page/settings/ledgerSync.page.ts, apps/ledger-live-mobile/e2e/page/settings/settings.page.ts, apps/ledger-live-mobile/e2e/page/settings/settingsGeneral.page.ts, apps/ledger-live-mobile/e2e/page/wallet/portfolio.page.ts, apps/ledger-live-mobile/e2e/specs/speculos/ledgerSync/ledgerSync.spec.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Activation/Actions.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Activation/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/Success/index.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Activation/ActivationSuccess.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/Manage/Option.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/screens/ManageKey/DeletionSuccess.tsx, apps/ledger-live-mobile/src/screens/Accounts/index.tsx
- LLM Speculos tests
_First Ledger Sync tests for LLM similar to [LLD](https://github.com/LedgerHQ/ledger-live/pull/8448)_
- Creation of the trustchain + push of 2 accounts to the cloud with the CLI
- Connection to the trustchain and checking that the accounts are visible on LLM
- Trustchain destruction on LLM
- [Speculos CI run](https://github.com/LedgerHQ/ledger-live/actions/runs/12080896108/job/33688996254)
--- …
=> [QAA-346][Detox] First Speculos Ledger Sync test

.github/workflows/test-mobile-e2e-reusable.yml, apps/ledger-live-mobile/detox.config.js
- LLM E2E tests
iOS: Change Detox build cache order to prevent clean if install dependencies fails and cleans everything
android: filter android arch to speed build time 
- [Workflow](https://github.com/LedgerHQ/ledger-live/actions/runs/12127073105)
--- …
=> [QAA-350] Improve LLM CI stability

apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx
- ...
When creating a new account on the swap live app interface.
- The user will attempt to swap "to" this new account.
- The user will then be unable to.
- This was because the exchangeHandlers accounts param did not get updated when accounts were changed. Instead this PR proposes passing a getter function that will instead grab the users currents accounts when the function is run.
https://ledgerhq.atlassian.net/browse/LIVE-15117
--- …
=> [fix/LIVE-15117]: add custom ptx handlers to handlers memo

.changeset/good-mails-cover.md, apps/ledger-live-desktop/src/newArch/features/MemoTag/components/MemoTagField.tsx, apps/ledger-live-desktop/src/renderer/families/internet_computer/SendAmountFields.tsx, apps/ledger-live-desktop/src/renderer/families/internet_computer/SendRecipientFields.tsx, apps/ledger-live-desktop/src/renderer/families/internet_computer/index.ts, apps/ledger-live-desktop/src/renderer/families/internet_computer/types.ts, apps/ledger-live-desktop/src/renderer/modals/Send/SendRecipientFields.tsx, apps/ledger-live-desktop/src/renderer/modals/Send/steps/StepRecipient.tsx, turbo.json
- ...
- Internet Computer coin related MemoTag field is moved to the first step as a support for the new MemoTag flow. 
- As MemoTagField input manage errors, to avoid overlap between instruction text and error/warning alert under the textbox, we conditioned the toggle of the instruction text while no errors and warning.
- (chore change) : `BYPASS_CORS` is added to turbo.json in order to be able to test networks that doesn't allow requests (casper, icp) blocked by CORS.
https://github.com/user-attachments/assets/f3b05358-ce2a-4ba2-97ac-bfdfd0333a2a
https://ledgerhq.atlassian.net/browse/LIVE-15154
---
- **The PR description clearly documents the changes** made and explains …
=> fix: Move ICP memo tag field on recepient step when FF lldMemoTag is ON

.changeset/ninety-scissors-grow.md, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- feature flag
add feature flag to prepare the UI rework of assets list. added to firebase too
- **JIRA or GitHub link**: [LIVE-14707](https://ledgerhq.atlassian.net/browse/LIVE-14707)
---
[LIVE-14707]: …
=> :triangular_flag_on_post: (llm): add account list feature flag

.changeset/three-mails-hug.md, apps/ledger-live-desktop/src/renderer/families/bitcoin/AccountHeaderManageActions.ts
- Adding condition on the flag that enables bitcoin_testnet staking
This PR adds a condition on the flag that enables bitcoin_testnet staking
---
=> Add bitcoin_testnet for staking using ACRE

.changeset/lovely-vans-hug.md, apps/ledger-live-mobile/src/components/SelectDevice2/index.tsx
- My Ledger
https://github.com/user-attachments/assets/466f2c38-0875-4cb8-b194-58c1d04512f0
- **JIRA or GitHub link**: [LIVE-15218](https://ledgerhq.atlassian.net/browse/LIVE-15218?atlOrigin=eyJpIjoiNmMyZDUzMzlhOTk0NDRiY2ExNjg4Y2RlMDk0YWY1ODgiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
--- …
=> :bug: (llm) margin issue on my ledger screen

.changeset/seven-ravens-rest.md, apps/ledger-live-desktop/src/newArch/features/MemoTag/__tests__/MemoTagField.test.tsx, apps/ledger-live-desktop/src/newArch/features/MemoTag/components/MemoTagField.tsx, apps/ledger-live-desktop/src/renderer/families/casper/MemoField.tsx, apps/ledger-live-desktop/src/renderer/families/xrp/SendRecipientFields.tsx
- ...
Backport this fix https://github.com/LedgerHQ/ledger-live/pull/8612#issue-2720537972 in release branch
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-15143
---
=> Release - fix(lld): use a debounce on memotag field

apps/ledger-live-desktop/tests/specs/speculos/delegate.spec.ts
- LLD Speculos Delegate tests
Solana default validator changed after [LIVE-14413](https://ledgerhq.atlassian.net/browse/LIVE-14413)
- [Speculos run](https://github.com/LedgerHQ/ledger-live/actions/runs/12199164901/)
--- …
=> [Playwright][Solana][Speculos] Change default validator

.changeset/rude-bats-fold.md, apps/ledger-live-mobile/src/families/algorand/MemoTagInput.tsx, apps/ledger-live-mobile/src/families/stacks/MemoTagInput.tsx, libs/coin-modules/coin-stacks/src/bridge/getTransactionStatus.ts, libs/coin-modules/coin-stacks/src/contants.ts, libs/ledger-live-common/.unimportedrc.json, libs/ledger-live-common/src/families/stacks/constants.ts
- ...
This is the release PR for #8604
---
=> fix(llm): 🐛 release fix long Memo Tag issue on Stacks

.changeset/tall-ladybugs-worry.md, apps/ledger-live-mobile/src/screens/makeGenericSelectScreen.tsx
- ...
- set scroll indicator position on right to avoid overlap on Preferred currency screen. 
Preview 📹 IOS
https://github.com/user-attachments/assets/5466fcba-7dbf-4b00-bd1d-74befe762439
Preview 📹 no impact on android
https://github.com/user-attachments/assets/7571b5d0-8dcb-4407-bab5-6f71a8466957
https://ledgerhq.atlassian.net/browse/LIVE-15057
---
- **Any new …
=> fix: set scroll indicator to right to prevent overlaping

.changeset/brown-hats-think.md, apps/ledger-live-mobile/src/newArch/features/MemoTag/hooks/useMemoTagInput.ts
- ...
I can't add the network plugin on Flipper rn so I tested with console logs instead:
Without debounce:
https://github.com/user-attachments/assets/da34d784-e774-49d5-a636-123725098f89
With debounce:
https://github.com/user-attachments/assets/9cc01986-3b69-44c1-a8c6-a4c6619c7783
- [LIVE-15278]
--- …
=> fix(llm): 🐛 debounce memo tag changes

.changeset/rare-schools-happen.md, apps/ledger-live-mobile/src/families/cardano/MemoTagInput.tsx
- ...
This is the release PR for #8608
---
=> fix(llm): 🐛 release fix long Memo Tag issue on Cardano

libs/ledgerjs/packages/hw-app-aptos/package.json
- ...
A dependency package named @ledgerhq/hw-transport-mock was removed from package.json. This package does not seem to exist.
---
=> fix(aptos): remove inexistent dependency

apps/ledger-live-desktop/tests/specs/speculos/delegate.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/portfolio.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/receive.address.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/settings.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts, apps/ledger-live-desktop/tests/utils/allureUtils.ts, apps/ledger-live-desktop/tests/utils/customJsonReporter.ts
- ...
Adding Bug link to allure
- **JIRA or GitHub link**: [QAA-355](https://ledgerhq.atlassian.net/browse/QAA-355)
---
[QAA-355]: https://ledgerhq.atlassian.net/browse/QAA-355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …
=> [QAA-355] Adding Bug link to allure - e2e testing

.changeset/angry-rats-kick.md, apps/ledger-live-mobile/e2e/jest.config.js, apps/ledger-live-mobile/scripts/e2e-ci.mjs, apps/ledger-live-mobile/src/utils/constants.ts, libs/coin-modules/coin-cosmos/src/chain/Coreum.ts, libs/coin-modules/coin-cosmos/src/chain/Cosmos.ts, libs/coin-modules/coin-cosmos/src/chain/Dydx.ts, libs/coin-modules/coin-cosmos/src/chain/Osmosis.ts, libs/coin-modules/coin-cosmos/src/chain/SeiNetwork.ts, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts
- Navigate to the updated links. The links are no longer broken
See https://ledger.slack.com/archives/C02PQA777EU/p1732181750558089
Staking links such as https://support.ledger.com/article/360014339340-Earn-Cosmos-ATOM-staking-rewards-in-Ledger-Live?docs=true-zd?redirect=false
were broken in the zen desk migration. 
- Links are fixed, and any that suffered the same problem because of the query parameters `?docs=true` are also now directing to what appears to be the correct articles again.
- Also added --runInBand and maxWorkers 50% to mobile tests to see if we could improve reliability of tests. See https://jestjs.io/docs/troubleshooting#tests-are-extremely-slow-on-docker-andor-continuous-integration-ci-server
- This should mean that the CPUs do not max out, which is a common cause of …
=> fix(CN-513): all docs=true suffixed links after zendesk migration

libs/ledger-live-common/package.json, libs/ledger-live-common/src/families/aptos/LedgerAccount.ts, libs/ledger-live-common/src/families/aptos/api/index.ts, libs/ledger-live-common/src/families/aptos/js-broadcast.ts, libs/ledger-live-common/src/families/aptos/js-buildTransaction.ts, libs/ledger-live-common/src/families/aptos/js-getFeesForTransaction.ts, libs/ledger-live-common/src/families/aptos/logic.ts, libs/ledger-live-common/src/families/aptos/types.ts, pnpm-lock.yaml
- ...
[aptos](https://www.npmjs.com/package/aptos) package has been deprecated.
This PR replaces it with [@aptos-labs/ts-sdk](https://www.npmjs.com/package/@aptos-labs/ts-sdk).
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-15115
--- …
=> feat(aptos): update aptos package

.changeset/grumpy-pets-allow.md, apps/ledger-live-mobile/src/components/CurrencyIcon.tsx, apps/ledger-live-mobile/src/components/ParentCurrencyIcon.tsx, apps/ledger-live-mobile/src/components/RootNavigator/AccountsNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/types/AccountsNavigator.ts, apps/ledger-live-mobile/src/components/RootNavigator/types/BaseNavigator.ts, apps/ledger-live-mobile/src/const/navigation.ts, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountsListView/components/AccountItem.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountsListView/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountsListView/useAccountsListViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AddAccountButton/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AccountsList/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AccountsList/types.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/utils/formatAddress.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/utils/tests/formatAddress.test.ts, apps/ledger-live-mobile/src/newArch/features/Assets/Navigator.tsx, apps/ledger-live-mobile/src/newArch/features/Assets/components/AssetsListView/components/AssetItem.tsx, apps/ledger-live-mobile/src/newArch/features/Assets/components/AssetsListView/index.tsx, apps/ledger-live-mobile/src/newArch/features/Assets/components/AssetsListView/useAssetsListViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Assets/screens/AssetsList/index.tsx, apps/ledger-live-mobile/src/newArch/features/Assets/screens/AssetsList/types.ts, apps/ledger-live-mobile/src/newArch/features/Assets/types.ts, apps/ledger-live-mobile/src/screens/Accounts/AccountRow.tsx, apps/ledger-live-mobile/src/screens/Portfolio/PortfolioAssets.tsx
- Accounts/Assets list screen and components
Create new accounts and assets list + rearrange some weird coms 
ReadOnlyMode not affected
Following the newArch we will have on Assets folder with the screen/components for the assetsList and the same for the accounts. This way both are independent 
This arch will allow us to call the screen with different params so it's easily to reuse for multiple reasons / UX and also call the list components in stand alone for the rework of the portfolio screen for eg
Deeplinks will be updated in another PR
Inte tests will be added once it's integrated to the portfolio on next PR 
https://github.com/user-attachments/assets/4b84da93-179e-462e-af5c-754a9d6b9af4
https://github.com/user-attachments/assets/644c391c-f75f-4bc3-b833-ca72f0ee9c29
Sync status is the …
=> feat : ✨ (llm) new Account/Asset list view

apps/ledger-live-mobile/src/families/bitcoin/ScreenEditCustomFees.tsx, apps/ledger-live-mobile/src/families/stellar/ScreenEditCustomFees.tsx
- ...
Fix weird coms that shouldn't be there
Another one is removed in the following PR : https://github.com/LedgerHQ/ledger-live/pull/8588
---
=> :pencil2: fix (llm) : update comments

.changeset/large-glasses-relate.md, apps/ledger-live-desktop/src/main/updater/init.ts
- ...
This pull request includes changes to migrate the `ledger-live-desktop` application to use HTTPS for downloading signatures.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-15353
---
=> fix(lld): migrate to https to download signatures

.changeset/smart-olives-learn.md, apps/ledger-live-mobile/src/families/stellar/MemoTagInput.tsx, apps/ledger-live-mobile/src/screens/SendFunds/02-SelectRecipient.tsx
- ...
Focus on the memo tag input when clicking the drawers "Add Tag" button
https://github.com/user-attachments/assets/2184ae00-206e-48fc-8fc0-2cca0d11c94d
- [LIVE-15318]
---
[LIVE-15318]: …
=> fix(llm): 🐛 focus the memo tag input after clicking "Add Tag"

.github/workflows/test-mobile-e2e-reusable.yml
- LLM E2E CI
Enable Slack message for LLM Speculos nightlies
- [Notif exemple](https://ledger.slack.com/archives/CTMQ0S5SB/p1734019795828649)
---
=> [QAA-374][Detox][Speculos] Enable Slack message for nightlies

.github/workflows/test-mobile-e2e-reusable.yml, apps/ledger-live-mobile/scripts/e2e-ci.mjs
- LLM E2E Android CI workflow
- LLM MOCK [execution](https://github.com/LedgerHQ/ledger-live/actions/runs/12313428479)
- LLM Speculos [execution](https://github.com/LedgerHQ/ledger-live/actions/runs/12313388579)
---
- **The PR description clearly documents the changes** …
=> [QAA-375][Detox][Speculos] Shard android tests

.github/workflows/test-mobile-e2e-reusable.yml
- LLM E2E Workflow
Fix for [[Push] Build and Test](https://github.com/LedgerHQ/ledger-live/actions/workflows/build-and-test-push.yml) which has sharding but should not.
---
=> [QAA-375][Detox][Speculos] Fix Shard for push

.github/workflows/test-mobile-e2e-reusable.yml
- LLM E2E CI workflow
_Fix misprint broking CI._
---
=> [QAA-375][Detox][Speculos] Fix Shard for push (bis)(bis)

libs/ledger-live-common/src/families/aptos/logic.test.ts, libs/ledger-live-common/src/families/aptos/logic.ts
- ...
The sender address was removed from function arguments, which impacted the transaction parsing (index of recipient address was broken)
- The parsing fixed to get right recipient address.
- Tests are changed to fit new logic
- [LIVE-15120](https://ledgerhq.atlassian.net/browse/LIVE-15120)
--- …
=> Fix transaction parsing, after removing sender form aptos input argument

libs/ledger-live-common/src/families/aptos/js-getTransactionStatus.ts
- None
Checks for amount being 0.
- LIVE-14962
---
=> fix(aptos): add amount validation

libs/ledger-live-common/src/families/aptos/api/index.test.ts
- ...
Unit tests for Aptos API
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-15124
---
=> test(aptos): Unit tests for Aptos API

.changeset/witty-taxis-scream.md, apps/ledger-live-desktop/src/renderer/modals/Send/fields/RecipientField.tsx
Reverts LedgerHQ/ledger-live#8621
=> Revert "fix: revalidate recipient field on account change in the send flow"

.changeset/stupid-hotels-laugh.md, libs/coin-modules/coin-cardano/src/bridge.integration.test.ts, libs/ledger-live-common/jest.config.ts, libs/ledger-live-common/jest.polyfills.js, libs/ledger-live-common/src/families/celo/bridge.integration.test.ts
=> polyfill only within celo test

.changeset/plenty-beds-chew.md, apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/WalletAPIWebview.tsx, apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/helpers.ts, apps/ledger-live-desktop/src/renderer/screens/platform/LiveApp.tsx, apps/ledger-live-mobile/src/components/Web3AppWebview/helpers.ts, apps/ledger-live-mobile/src/newArch/features/Web3Hub/screens/Web3HubApp/components/Web3Player/SelectAccountModal/useSelectAccountModalViewModel.tsx, apps/ledger-live-mobile/src/screens/Platform/LiveApp.tsx, libs/ledger-live-common/src/hooks/useDBRaw.ts, libs/ledger-live-common/src/platform/utils/extractDappURLFromManifest.ts, libs/ledger-live-common/src/wallet-api/useDappLogic.ts
- discover dapp browser v3 apps like Stader
dApp browser v3 accountId and customDappUrl support
Use saved state in useDBRaw instead of react states as we could use the hook in multiple components especially on LLM and it can become out of sync
| Desktop        | Mobile         |
| <video src="https://github.com/user-attachments/assets/0ad5449f-d61b-4f5a-a573-c356234100c7" /> | <video src="https://github.com/user-attachments/assets/291cb72f-9e83-4cc7-833d-61c0c6dd235e" /> |
--- …
=> feat: dapp browser v3 accountId and customDappUrl support

.github/workflows/test-mobile-e2e-reusable.yml
- LLM Notifcation on slack chanel #
Mocked [notification](https://ledger.slack.com/archives/CTMQ0S5SB/p1734368084444419)
Speculos [notification](https://ledger.slack.com/archives/CTMQ0S5SB/p1734370842971029)
--- …
=> [QAA-378][Detox][Speculos] Align Slack notification with LLD

apps/ledger-live-desktop/tests/page/account.page.ts, apps/ledger-live-desktop/tests/page/modal/delegate.modal.ts, apps/ledger-live-desktop/tests/specs/speculos/delegate.spec.ts
=> [QAA] Updating Solana delegation + nft test

libs/ledger-live-common/src/families/aptos/LedgerAccount.test.ts
- ...
- Added jest based Unit Tests to Ledger account
- [LIVE-14968](https://ledgerhq.atlassian.net/browse/LIVE-14968) 
---
[LIVE-14968]: https://ledgerhq.atlassian.net/browse/LIVE-14968?atlOrigin=eyJpIjoiNWRkNTljNzYx …
=> Added a test file for the LedgerAccount based on Jest.

.github/workflows/test-ui-e2e-only-desktop.yml
=> LLD e2e: Updated runner for nightly workflow

.changeset/stale-guests-drum.md, apps/ledger-live-mobile/src/components/SelectableAccountsList.tsx
- ...
Topics of the [ticket](https://ledgerhq.atlassian.net/browse/LIVE-8988) :
1. Add an ellipsis to the text at the top of the add account screen
Before ![Screenshot_20230817_153219_com ledger live staging-20230818-122005](https://github.com/user-attachments/assets/efc766f1-417d-464f-b203-ed7e4f138a22)
After ![Screenshot_2024-12-19-14-31-04-20_99c1b3bb631177f8a9e1379ae5b12ffe](https://github.com/user-attachments/assets/b6636dac-62ec-4a03-8bbc-ff410c825c1a)
2. Not reproducible
3. Scope of the device team
4. Scope of the device team
5. Nothing to fix
6. Not reproducible
- **JIRA or GitHub link**: [LIVE-8988]
--- …
=> 💄  LLM - Add an ellipsis to the add account title when too long

.changeset/hungry-ravens-beg.md, apps/ledger-live-desktop/src/renderer/families/solana/shared/fields/ValidatorsField.tsx
- ...
Delegate SOL
Select a new provider (not a ledger one)
Click on show less
Provider is be displayed on the modal
https://github.com/user-attachments/assets/b315f637-159a-4286-b84d-ff419225d4cb
- **JIRA or GitHub link**:  [LIVE-15502](https://ledgerhq.atlassian.net/browse/LIVE-15502)
--- …
=> fix: delegation showless

apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts
- ...
This PR aims to fix the minimum amount required to perform a swap from USDC to BTC or USDC to ETH through the provider "Exodus"
Automated tests covering swaps from USDC to Bitcoin/Ethereum were failing on the CI
https://ledger-live.allure.green.ledgerlabs.net/allure/reports/7031f3d4-36ca-4150-bd18-07e9eb326c92/#suites/14e80619d2cb176baa0417903e32f671/4ed339b4fd491a35/
https://ledger-live.allure.green.ledgerlabs.net/allure/reports/7031f3d4-36ca-4150-bd18-07e9eb326c92/#suites/14e80619d2cb176baa0417903e32f671/e074fc13d0d0d662/
--- …
=> Fix : Minimum amount for swap through Exodus

.changeset/red-roses-try.md, apps/ledger-live-mobile/src/locales/en/common.json
- ...
Change a text
Context : https://ledger.slack.com/archives/C02PQA777EU/p1734689765776009
---
=> 💬  LLM - Small copy update on the send flow

clean-brooms-begin.md
=> fix :wastebasket: unexpected changeset file

.changeset/curly-olives-smoke.md, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/walletSyncStatus.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useGetMembers.ts
- ...
Infinite loop during operations involving member removal and QR code scanning
Assuming that if getMembers returns undefined, it means the `trustchain` is ejected
https://github.com/user-attachments/assets/2eadc61d-072c-41be-a68f-5a3628304da7
- **JIRA or GitHub link**: [LIVE-15094] 
--- …
=> bugfix: Infinite loop during operations involving member removal and QR code scanning

apps/ledger-live-desktop/tests/component/layout.component.ts, apps/ledger-live-desktop/tests/page/drawer/swap.confirmation.drawer.ts, apps/ledger-live-desktop/tests/page/swap.page.ts
=> Fix: increased timeout for swap confirmation

apps/ledger-live-desktop/tests/fixtures/common.ts, libs/ledger-live-common/src/e2e/speculos.ts, libs/speculos-transport/src/index.ts
- ...
The retry mechanism for Speculos was broken making Speculos tests timeout when address already used in runners.
Speculos [run](https://github.com/LedgerHQ/ledger-live/actions/runs/12479566232)
---
=> [QAA][Playwright][Speculos] Fix timeout issues

apps/ledger-live-desktop/src/renderer/analytics/segment.ts
- ...
- **JIRA or GitHub link**: [LIVE-15572] 
---
- **The PR …
=> bugfix: Analytics Widget

libs/env/src/env.ts
- ...
Update Aptos endpoints with paths to our reverse proxy.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-15132
---
=> feat(aptos): update node and indexer endpoints

apps/ledger-live-desktop/src/renderer/Default.tsx, apps/ledger-live-desktop/src/renderer/components/debug/DisableTransactionBroadcastWarning.tsx
- ...
Adding the value of the env variable to the element
- **JIRA or GitHub [QAA-382](https://ledgerhq.atlassian.net/browse/QAA-382)
---
[QAA-382]: https://ledgerhq.atlassian.net/browse/QAA-382?atlOrigin=eyJpIjoiNWRk …
=> [QAA-382] Adding the value of DISABLE_TRANSACTION_BROADCAST

libs/ledger-live-common/src/families/aptos/api/index.ts
Update transaction expiration timestamp.
- ...
We need to revert changes to opts.expireTimestamp calculation. Cause currently transaction is expired in the moment of creation.
---
=> Update transaction expiration ts

libs/ledger-live-common/jest.config.ts, libs/ledger-live-common/src/families/aptos/api/index.test.ts, libs/ledger-live-common/src/families/aptos/api/index.ts
- ...
Unit tests for index api for Aptos coin.
Coverage:
100% Statements 64/64
100% Branches 12/12
100% Functions 17/17
100% Lines 64/64
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-15124
---
=> test(aptos): index api

libs/ledger-live-common/src/families/aptos/signOperation.test.ts
- ...
Adds improvements to aptos unit tests
Coverage for the current test
- 100% Statements 57/57
- 100% Branches 15/15
- 100% Functions 5/5
- 100% Lines 55/55
---
=> test(aptos): improve unit tests

.changeset/seven-rocks-dream.md, libs/coin-modules/coin-bitcoin/src/wallet-btc/explorer/index.ts
=> verbosity minimal btc call to explorer

libs/coin-framework/src/currencies/__snapshots__/formatCurrencyUnit.test.ts.snap, libs/coin-modules/coin-evm/src/__tests__/unit/editTransaction/__snapshots__/getFormattedFeeFields.test.ts.snap
- CI
Fix missing snapshots updates from this PR: https://github.com/LedgerHQ/ledger-live/pull/8579
Causing a fail on develop: https://github.com/LedgerHQ/ledger-live/actions/runs/12629394206/job/35187207700
--- …
=> chore: update snapshots for Rootstock name update

libs/ledger-live-common/src/families/aptos/deviceTransactionConfig.ts
- ...
Fix transfer type label.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-15600
---
=> fix: transfer type label

.changeset/curly-olives-smoke.md, apps/ledger-live-mobile/src/newArch/features/WalletSync/__integrations__/walletSyncStatus.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useGetMembers.ts
This reverts commit dffded12835d672baf141af12275485d85b6f394, reversing changes made to 4fad912c0c939816b7da0e9027835bb40b9e6732.
- ...
--- …
=> Revert "Merge pull request #8724 from LedgerHQ/bugfix/ls-LIVE-15094"

.changeset/tame-geese-thank.md, apps/ledger-live-desktop/src/renderer/reducers/devices.ts, apps/ledger-live-desktop/tests/page/drawer/send.drawer.ts, apps/ledger-live-desktop/tests/page/drawer/swap.confirmation.drawer.ts, apps/ledger-live-desktop/tests/page/swap.page.ts, apps/ledger-live-desktop/tests/specs/speculos/delegate.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts, libs/ledger-live-common/.unimportedrc.json, libs/ledger-live-common/src/e2e/enum/Swap.ts, libs/ledger-live-common/src/e2e/enum/TransactionStatus.ts, libs/ledger-live-common/src/e2e/models/Swap.ts
- ...
- Refactoring of the Swap Enum: The enum no longer requires a Provider or a Rate to be specified.
- Provider Selection: We will now always select the first available provider, as long as it meets two conditions:
- It is KYC-free.
- It is native to the liveApp Swap.
- [QAA-405](https://ledgerhq.atlassian.net/browse/QAA-405)
- [QAA-340](https://ledgerhq.atlassian.net/browse/QAA-340)
- [QAA-371](https://ledgerhq.atlassian.net/browse/QAA-371)
--- …
=> [QAA] Update Swap tests to always choose valid provider

apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts, libs/ledger-live-common/src/e2e/enum/Account.ts
- ...
Fix issue with E2E test with speculos for APTOS coin.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-15624
---
=> fix: aptos e2e test with speculos

apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts
=> [QAA] [LLD] Refactoring: env setup step for swap tests

libs/ledger-live-common/src/families/aptos/bridge.integration.test.ts, libs/ledger-live-common/src/families/aptos/bridge/js.ts
- ...
Fix updateTransaction tests:
✓ ref stability on empty transaction
✓ ref stability on self transaction
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-15629
---
=> fix: aptos bridge integration test

.changeset/mean-mangos-compete.md, apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AccountsList/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AccountsList/types.ts, apps/ledger-live-mobile/src/newArch/features/Assets/screens/AssetsList/index.tsx, apps/ledger-live-mobile/src/newArch/features/Assets/screens/AssetsList/types.ts, apps/ledger-live-mobile/src/newArch/utils/parseBoolean.ts
- change ledgerlive://accounts deeplink (wasn't working)
- add ledgerlive://assets deeplink 
Add  ledgerlive://assets with the following params : 
* @params ?showHeader: boolean
* @params ?isSyncEnabled: boolean
* @params ?sourceScreenName: string
Update ledgerlive://accounts. If ff enabled the following params are usable : 
* @params ?showHeader: boolean
* @params ?canAddAccount: boolean
* @params ?isSyncEnabled: boolean
* @params ?sourceScreenName: string
Both are under ff 
| Accounts        | Assets         |
|https://github.com/user-attachments/assets/5278b941-5e2b-4726-98f6-b0b80c62ac3f|https://github.com/user-attachments/assets/4a127deb-fbdf-4ae4-9abb-ec3e84f6856e| …
=> feat :necktie: (llm): update and create deeplinks for new accounts list ui

.changeset/fair-avocados-carry.md, apps/ledger-live-desktop/package.json, pnpm-lock.yaml
- ...
Before: 
react developer tools and redux developer tools weren't loaded, `electron-devtools-installer` failed to properly load them. (error caught here https://github.com/LedgerHQ/ledger-live/blob/develop/apps/ledger-live-desktop/src/main/index.ts#L238) 
Now: 
Bumping the version fixes the issue, we now have the react/redux dev tools back in LLD, and get rid of the ugly start up error.
--- …
=> chore: update broken electron-devtools-installer

libs/ledger-live-common/src/e2e/enum/Account.ts
- ...
The Aptos addresses were switched, and the E2E tests are failing. This PR fixes this issue.
---
=> fix: aptos addresses

.changeset/tame-crabs-sit.md, apps/ledger-live-mobile/src/dynamicContent/brazeContentCard.ts
- ...
- **JIRA or GitHub link**:https://ledgerhq.atlassian.net/browse/LIVE-15674
--- …
=> fix: llm perf issue on iOS due to Braze usage

.github/workflows/test-mobile-e2e-reusable.yml, .github/workflows/test-mobile-e2e.yml, .github/workflows/test-ui-e2e-only-desktop.yml, apps/ledger-live-mobile/scripts/e2e-ci.mjs, tools/actions/composites/setup-e2e-broadcast/action.yml
- LLM/LLD Speculos tests broadcasting
_Enabling LLM transaction broadcasting on Mondays and with an inputs as for LLD._
- LLD Speculos [run](https://github.com/LedgerHQ/ledger-live/actions/runs/12674884990)
- LLM Broadcast [enabled](https://ledger-live.allure.green.ledgerlabs.net/allure/reports/a2024083-3dad-4671-873a-b892d9287597/)
- LLM Broadcast [disabled](https://ledger-live.allure.green.ledgerlabs.net/allure/reports/2f88516b-2dc9-415c-851d-6e1e5964a018/)
--- …
=> [QAA-410][Detox][Speculos] Enable broadcasting on Mondays

.changeset/fair-students-greet.md, apps/ledger-live-desktop/src/renderer/families/cardano/DelegationFlowModal/fields/ValidatorField.tsx
- ...
I select a Cardano account and click on earn. A validator is selected by default and you're able to click on continue button
https://github.com/user-attachments/assets/dfce8b17-8fdb-4100-8040-d0f986440d49
- **JIRA or GitHub link**:  [LIVE-15536](https://ledgerhq.atlassian.net/browse/LIVE-15536)
--- …
=> fix: continue button

apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/Welcome/index.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Help/ResetButton.tsx, apps/ledger-live-desktop/tests/page/index.ts, apps/ledger-live-desktop/tests/page/modal/settings.modal.ts, apps/ledger-live-desktop/tests/page/onboarding.page.ts, apps/ledger-live-desktop/tests/page/settings.page.ts, apps/ledger-live-desktop/tests/specs/speculos/settings.spec.ts, apps/ledger-live-desktop/tests/utils/fileUtils.ts
- ...
Adding E2E test: Verify that the User can reset LLD app - Comparing size of app.json
- **JIRA or GitHub link**: [qaa-420](https://ledgerhq.atlassian.net/browse/QAA-420)
---
=> [QAA-420] - Adding e2e test - reset app

.changeset/tame-tools-unite.md, apps/ledger-live-mobile/ios/ledgerlivemobile/Info.plist
- The app will be able to deeplink to revolut iOS app for KYC
This PR adds revolut to the LSApplicationQueriesSchemes to allow deeplinking to their app on iOS.
---
=> FIX/CN-1018: Add revolut to LSApplicationQueriesSchemes

.github/workflows/test-mobile-e2e-reusable.yml
- Detox LLM Tests
_We need to add AppDelegate file to Detox build cache key to prevent using old cache causing crashes._
- Detox [run](https://github.com/LedgerHQ/ledger-live/actions/runs/12783903696/job/35635861945)
--- …
=> [LLM][Detox] Add AppDelegate file to Detox build cache key

.changeset/swift-trains-raise.md, apps/ledger-live-desktop/src/renderer/families/cardano/DelegationFlowModal/fields/ValidatorField.tsx
- ...
https://github.com/user-attachments/assets/61f71ca1-7c62-43ce-bb71-1c55403a4ed6
- **JIRA or GitHub link**: [LIVE-15758](https://ledgerhq.atlassian.net/browse/LIVE-15758)
---
[LIVE-15758]: …
=> fix: do not put the selected validator as first on the list

.changeset/rich-shirts-punch.md, apps/ledger-live-mobile/src/screens/Swap/LiveApp/WebView.tsx, apps/ledger-live-mobile/src/screens/Swap/LiveApp/index.tsx
- ...
Remove padding for webview for swap mobile 
https://github.com/user-attachments/assets/978a5078-9d97-4269-ac9d-9927b3d9c7d0
https://ledgerhq.atlassian.net/browse/LIVE-15403
---
=> fea(live-15403): remove padding for webview for swap mobile

.changeset/light-ghosts-clap.md, apps/ledger-live-desktop/src/renderer/components/SideBar/SideBarListItem.tsx
- sidebar
There is an issue with the tooltip arrow that's not dynamically changing color. I've deactivated it since it wasn't use before the changes I did on the sidebar. I think the issue is more based on tippy.js that is not updating the arrow (it's a svg so it might be the reason)
|![image](https://github.com/user-attachments/assets/e42cf4bc-7098-45bd-8ab4-5bad266dd05e)|![image](https://github.com/user-attachments/assets/78070c90-0e6e-4e03-9310-af45eb4d1f8b)|
|![image](https://github.com/user-attachments/assets/605f409f-8338-483b-9bbe-b6b265b9eca7)|![image](https://github.com/user-attachments/assets/4af70ca9-4e7e-41dd-b604-d6e2c41af930)|
- **JIRA or …
=> fix :bug:(lld) arrow tooltip wrong color

.changeset/sharp-terms-ring.md, libs/ledger-live-common/src/families/tezos/react.ts
- ...
- **JIRA or GitHub link**:  [LIVE-15814](https://ledgerhq.atlassian.net/browse/LIVE-15814) 
--- …
=> fix: tezos earn bakers

.changeset/thin-camels-tap.md, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/locales/en/common.json
- ...
- **JIRA or GitHub link**: [CN-962](https://ledgerhq.atlassian.net/browse/CN-962)
--- …
=> fix: capitalisation of Ethereum in copy

.changeset/dry-avocados-look.md, libs/ledger-live-common/src/families/aptos/types.ts
- ...
Remove redundant parameter from Aptos Transaction
- **JIRA or GitHub link**: [LIVE-15631](https://ledgerhq.atlassian.net/browse/LIVE-15631)
---
[LIVE-15631]: …
=> Remove redundant parameter from Aptos Transaction

apps/ledger-live-desktop/tests/page/modal/send.modal.ts, apps/ledger-live-desktop/tests/page/swap.page.ts, apps/ledger-live-desktop/tests/specs/speculos/delegate.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/nft.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts, libs/ledger-live-common/src/e2e/enum/Account.ts, libs/ledger-live-common/src/e2e/families/evm.ts, libs/ledger-live-common/src/e2e/speculos.ts
- ...
- Adding E2E test: User can send funds to an ENS address
- Updating ENS for NFT test
- **JIRA or GitHub link**:  [QAA-430](https://ledgerhq.atlassian.net/jira/software/c/projects/QAA/boards/887?assignee=712020:1787baec-823a-432f-bf1c-e8198ea89ef6&selectedIssue=QAA-430)
--- …
=> [QAA] Adding E2E test - User send funds to an ENS

.changeset/tough-frogs-cover.md, libs/coin-modules/coin-bitcoin/src/speculos-deviceActions.ts
- ...
Error on bot nitrogen for Bitcoin cash, Bitcoin Gold, Litecoin and Digibyte 
⚠️ TEST deviceAction confirm step 'Address'
Error: expect(received).toMatchObject(expected)
Object {
-   "Address": "Ga77Dv5ziVdDWY424aNyrKmELTpuMRgt5A",
+   "Address": "OP_RETURN",
}
- **JIRA or GitHub link**: [LIVE-15841](https://ledgerhq.atlassian.net/browse/LIVE-15841)
--- …
=> fix: bot address for litecoin bitcoin gold and others

.changeset/brave-hounds-listen.md, libs/coin-modules/coin-evm/src/speculos-deviceActions.ts
- ...
- **JIRA or GitHub link**:  [LIVE-15844](https://ledgerhq.atlassian.net/browse/LIVE-15844)
--- …
=> fix: device actions bot fix

.changeset/chatty-cobras-add.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx
- ...
Adds `toTokenId` and `fromTokenId` hash parameters for the Swap app
- **JIRA or GitHub link**: [https://ledgerhq.atlassian.net/browse/LIVE-15609](https://ledgerhq.atlassian.net/browse/LIVE-15609)
---
=> feat: token name Swap hash param

apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts
- ...
Adding pair for swap test
- **JIRA or GitHub link**: [QAA-440](https://ledgerhq.atlassian.net/browse/QAA-440)
---
[QAA-440]: https://ledgerhq.atlassian.net/browse/QAA-440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …
=> [QAA] Adding pair DOT/ETH for swap test

.changeset/eleven-dolphins-lick.md, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountsListView/useAccountsListViewModel.ts, libs/live-countervalues/src/portfolio.test.ts, libs/live-countervalues/src/portfolio.ts
- accounts list
Order the accounts by fiat value on accounts list 
|https://github.com/user-attachments/assets/3a543b15-289b-4aaa-b27e-daa64652a937|https://github.com/user-attachments/assets/f3f7c650-8b9f-4e3e-9661-6658559138d9|
- **JIRA or GitHub link**: [LIVE-15667](https://ledgerhq.atlassian.net/browse/LIVE-15667)
---
- **Any …
=> :lipstick: (llm) accounts list ordered by fiat value

.changeset/unlucky-garlics-move.md, apps/ledger-live-desktop/src/renderer/screens/account/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, libs/coin-framework/src/config.ts
- ...
we should create generic translated banner with differents parameters. We will use first use this banner to warn our users about ADA staking issue : 
Text :  The following feature is momentarily unavailable : {{feature}}, to know more please refer to support.
- **JIRA**: https://ledgerhq.atlassian.net/browse/LIVE-15643
---
- …
=> feat: create banner to warn users about potential issues

.github/workflows/test-mobile-e2e-reusable.yml, .github/workflows/test-ui-e2e-only-desktop.yml, tools/actions/composites/setup-e2e-broadcast/action.yml
- LLD Speculos nightly
Given [this](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows), the schedule cron was not correct, preventing broadcasting on mondays. After fixing it, there is no need to pass it to the action as it should be available there too.
--- …
=> [QAA-441][Specullos][Playwright] Fix scheduled run broadcast

.changeset/hip-avocados-marry.md, libs/exchange-module/src/types.ts
- ...
This PR is required to trigger new exchange module version for https://github.com/LedgerHQ/exchange-sdk/pull/95 
fee Strat is case sensitive on LL and requires all lower case.
This fix will prevent redefinition of the type in swap live app
--- …
=> ExchangeModule: fixed incorrect fee strategy types

.github/workflows/test-mobile-e2e-reusable.yml, apps/ledger-live-mobile/detox.config.js, apps/ledger-live-mobile/docs/llm_e2e_testing.md
- LLM E2E Tests
_In order to test with more representative device, we updated iOS and Android emulators version_
Android test are failing because the checks use develop version of the emulator
- LLM E2E test with correct workflow : [Link](https://github.com/LedgerHQ/ledger-live/actions/runs/12872236548)
--- …
=> [Detox] Update emulator and simulator version

.changeset/polite-donkeys-marry.md, apps/ledger-live-mobile/src/screens/Swap/LiveApp/index.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
chore: changeset
- ...
fix to load manifest from feature flag
https://ledgerhq.atlassian.net/browse/LIVE-11174
---
=> fix(live-1174): llm swap fix to load manifest from feature flag

.changeset/big-numbers-smash.md, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountsListView/components/AccountItem/useAccountItemModel.ts
- accounts list wallet centric
Fix an issue where we displayed the wrong currency value for token account
https://github.com/user-attachments/assets/f20be6e4-081e-4815-a411-0f9a9c918616
- **JIRA or GitHub link**: [LIVE-16495](https://ledgerhq.atlassian.net/browse/LIVE-16495) && [LIVE-16499](https://ledgerhq.atlassian.net/browse/LIVE-16499)
--- …
=> :bug:(llm) wrong cvs on token accounts

apps/ledger-live-desktop/tests/page/modal/receive.modal.ts
=> [QAA] fix ci: improve locator

.changeset/cuddly-gorillas-protect.md, apps/ledger-live-mobile/src/newArch/features/Accounts/Navigator.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccountWarning/index.tsx, apps/ledger-live-mobile/src/newArch/features/AssetSelection/screens/SelectNetwork/index.tsx, apps/ledger-live-mobile/src/newArch/features/AssetSelection/screens/SelectNetwork/useSelectNetworkViewModel.ts, apps/ledger-live-mobile/src/newArch/features/AssetSelection/types.ts, apps/ledger-live-mobile/src/newArch/features/DeviceSelection/screens/SelectDevice/useSelectDeviceViewModel.ts, apps/ledger-live-mobile/src/screens/ReceiveFunds/02-SelectAccount.tsx, apps/ledger-live-mobile/src/screens/RequestAccount/02-SelectAccount.tsx, apps/ledger-live-mobile/src/screens/Swap/Form/Summary/index.tsx
- ...
A redirection to the correct screens of add account v2 when : 
- A user is on a recieve flow and try to add a new or existing account 
https://github.com/user-attachments/assets/d257914e-c0c8-4d6e-b8ab-0d14c418f587
- A user is on a Buy flow and try to add a new account 
https://github.com/user-attachments/assets/7044e355-36cb-4c08-b663-6bce5e252bca
- A user is on the swap flow and try to add new account 
https://github.com/user-attachments/assets/7501c6d1-9da0-49ed-b66d-9ebccec01fe5
The add account flow will by pass success screen and return back to the latest Buy/Recieve/Swap flow. 
https://ledgerhq.atlassian.net/browse/LIVE-14645
--- …
=> feat: plug in Receive/Buy/Swap Flow to new Add account v2

.changeset/bright-kiwis-travel.md, libs/ledger-live-common/src/families/evm/config.ts
- ...
Update evm explorers config as it no longers match remote config
- **JIRA or GitHub link**: [https://ledgerhq.atlassian.net/browse/LIVE-14453](https://ledgerhq.atlassian.net/browse/LIVE-14453)
---
=> chore: update evm explorers in currency config

.changeset/eighty-cougars-perform.md, libs/ledger-live-common/src/csvExport.ts
- ...
As mentioned in the issue, the underlying issue is different and under investigation, but in the meantime this provides an easy fix to allow users to export even if impacted by the underlying issue
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/PROD-10176 / https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/465?selectedIssue=LIVE-15397
---
- **Any new …
=> don't operate on undefined value

tools/actions/composites/setup-e2e-broadcast/action.yml
- Broadcasting for E2E test
_Checking the date to see if it's monday to enable speculos broadcasting transactions_
---
=> [Speculos][CI] Fix getting the date for scheduled broadcast

CODEOWNERS
- ...
Update codeowners to reflect YLD team responsability on coin-aptos
---
=> add yld partner team to codeowners

.changeset/healthy-llamas-visit.md, apps/ledger-live-desktop/src/newArch/features/DynamicContent/__integrations__/PortfolioContentCards.test.tsx, apps/ledger-live-desktop/src/newArch/features/DynamicContent/components/PortfolioContentCards/Slide.tsx
- portfolio CC
First part of video => before
End part of video => after
https://github.com/user-attachments/assets/87eab3dc-6f51-4f07-97c3-f848e98aa477
- **JIRA or GitHub link**: [LIVE-16620](https://ledgerhq.atlassian.net/browse/LIVE-16620)
--- …
=> :bug: (lld) click triggered twice on the portfolio CC

.changeset/strong-peas-jam.md, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
Feature flag added to handle Ledger Sync Entry Points on LLM
- **JIRA or GitHub link**: [LIVE-15842]
---
[LIVE-15842]: https://ledgerhq.atlassian.net/browse/LIVE-15842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Z …
=> 🚩 LS entry points feature flag added for LLM

.changeset/eight-geese-dream.md, apps/ledger-live-desktop/src/renderer/analytics/hooks/useTrackManagerSectionEvents.test.ts, apps/ledger-live-desktop/src/renderer/analytics/hooks/useTrackManagerSectionEvents.ts, apps/ledger-live-desktop/src/renderer/components/DeviceAction/index.tsx, apps/ledger-live-desktop/src/renderer/screens/manager/DeviceDashboard/DeviceInformationSummary/EditDeviceName.tsx, apps/ledger-live-desktop/src/renderer/screens/manager/DeviceDashboard/DeviceInformationSummary/RemoveCustomImage.tsx, apps/ledger-live-desktop/src/renderer/screens/manager/index.tsx, apps/ledger-live-desktop/tests/testUtils.tsx
- ...
Added data tracking in my ledger flows
- **JIRA or GitHub link**: [LIVE-15764](https://ledgerhq.atlassian.net/browse/LIVE-15764)
---
[LIVE-15764]: https://ledgerhq.atlassian.net/browse/LIVE-15764?atlOrigin=eyJpI …
=> feat(live-15764): data tracking in my ledger flows

.changeset/curly-pants-walk.md, apps/ledger-live-desktop/src/renderer/screens/account/AccountHeader.tsx, apps/ledger-live-desktop/tests/page/account.page.ts, apps/ledger-live-desktop/tests/specs/accounts/rename.account.spec.ts, libs/live-wallet/src/store.test.ts, libs/live-wallet/src/store.ts
Add `accountNames` and `starredAccountIds` in the exported wallet state of the `live-wallet` package as it was forgotten and wasn't updated in the app.json anymore which broke those two features
e2e test added to LLD to make sure that the account names are properly updated in the app.json even after the app is closed
- **JIRA or GitHub link**: [LIVE-15588]
--- …
=> 🐛  Rename account and starred accounts now fixed on LLM and LLD

.changeset/stale-books-melt.md, apps/ledger-live-desktop/src/renderer/hooks/useBraze.ts
- ...
Only sending the app version to braze when user is tracked (ie he gave his consent).
This will allow us to target LLD users depending on their app version more easily from Braze.
- **JIRA or GitHub link**: [LIVE-16665]
--- …
=> 🧐  LLD - Send app version to Braze SDK

.changeset/early-worms-cry.md, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/locales/en/common.json
- ...
Updates wording of RecoverBanner
- [LIVE-16600](https://ledgerhq.atlassian.net/browse/LIVE-16600)
- [LIVE-16601](https://ledgerhq.atlassian.net/browse/LIVE-16601)
---
[LIVE-16600]: …
=> chore(recover): RecoverBanner wording

apps/ledger-live-mobile/e2e/models/send.ts, apps/ledger-live-mobile/e2e/models/stake.ts, apps/ledger-live-mobile/e2e/page/trade/deviceValidation.page.ts, apps/ledger-live-mobile/e2e/specs/speculos/addAccount/AddAccount.ts, apps/ledger-live-mobile/e2e/specs/speculos/deleteAccount/deleteAccount.ts, apps/ledger-live-mobile/e2e/specs/speculos/verifyAddress/verifyAddress.ts, apps/ledger-live-mobile/src/components/ValidateOnDevice.tsx
…detox speculos
- LLM Detox Speculos tests
_Improving stake validation screen verification and test suite reporting_
- [Test Mobile E2E](https://github.com/LedgerHQ/ledger-live/actions/runs/13019175099)
---
=> [LLM][Detox][Speculos] Improving test suite reporting

.changeset/real-impalas-sell.md, libs/coin-modules/coin-stellar/src/test/bot-deviceActions.ts
- ...
- **JIRA or GitHub link**: [LIVE-15845](https://ledgerhq.atlassian.net/browse/LIVE-15845)
--- …
=> fix: add sign in device actions

.changeset/mean-mice-own.md, libs/coin-modules/coin-aptos/src/__tests__/bridge/getFeesForTransaction.test.ts, libs/coin-modules/coin-aptos/src/bridge/getFeesForTransaction.ts
- change the way how often LL gets Aptos fees for transaction
Update Aptos `getEstimatedGas` to use `makeLRUCache` 
- **JIRA or GitHub link**: [LIVE-15686](https://ledgerhq.atlassian.net/browse/LIVE-15686)
--- …
=> Use makeLRUCache for getEstimatedGas

apps/ledger-live-mobile/e2e/specs/speculos/ledgerSync/ledgerSync.spec.ts
- LLM Detox LedgerSync
Upon [LIVE-14883](https://ledgerhq.atlassian.net/browse/LIVE-14883?atlOrigin=eyJpIjoiNjc3MjcyYjBjMjQ5NDBiYWJmYjI2ZmMzMTBjMGU5ZjciLCJwIjoiamlyYS1zbGFjay1pbnQifQ) we should dismiss drawer check for this flow (Turn on Ledger Sync)
--- …
=> [Detox][Speculos][Ledger Sync] Remove drawer verification

.changeset/lovely-dolls-chew.md, libs/coin-modules/coin-aptos/src/__tests__/bridge/getFeesForTransaction.test.ts
- improve test quality
Change test values to not be the same as default one.
- **JIRA or GitHub link**: Follow up for https://ledgerhq.atlassian.net/browse/LIVE-15686
---
=> Live 15686 lru cahce fix test2

.changeset/seven-tigers-hunt.md, libs/coin-modules/coin-cosmos/src/speculos-deviceActions.ts
- ...
- **JIRA or GitHub link**: [LIVE-15864](https://ledgerhq.atlassian.net/browse/LIVE-15864)
--- …
=> fix: zenrock type on device actions

.changeset/hot-roses-shave.md, apps/ledger-live-mobile/e2e/bridge/start-server.ts
- ...
Folder containing test app.json files was renamed from `setups` to `userdata` but the change needed to be reflected in the e2e script that loads the config.
---
=> chore: update e2e loadConfig script

CODEOWNERS
- ...
Revert yld codeowners
---
=> revert yld codeowners

.changeset/nine-jokes-share.md, apps/ledger-live-desktop/tests/specs/speculos/add.account.spec.ts, apps/ledger-live-desktop/tests/utils/customJsonReporter.ts
- ...
- **JIRA or GitHub link**: [QAA-457](https://ledgerhq.atlassian.net/browse/QAA-457)
---
- **Allure**: [link](https://ledger-live.allure.green.ledgerlabs.net/allure/reports/66860e97-af70-4875-8d8e-6aff03f585a7/#)
- **CI**: [link](https://github.com/LedgerHQ/ledger-live/actions/runs/13073470927)
- …
=> [QAA] Improving Xray x Speculos intégration

.changeset/selfish-buckets-fix.md, apps/ledger-live-desktop/src/renderer/components/WarnBox.tsx, apps/ledger-live-desktop/src/renderer/families/celo/AccountHeaderManageActions/AccountHeaderManageActions.tsx, apps/ledger-live-desktop/src/renderer/families/celo/LockFlowModal/fields/AmountField.tsx, apps/ledger-live-desktop/src/renderer/families/celo/LockFlowModal/steps/StepAmount.tsx, apps/ledger-live-desktop/src/renderer/families/celo/ManageModal/ManageModal.tsx, apps/ledger-live-desktop/src/renderer/families/tezos/DelegateFlowModal/steps/StepStarter.tsx, apps/ledger-live-desktop/src/renderer/families/tezos/DelegateFlowModal/steps/StepSummary.tsx, apps/ledger-live-desktop/src/renderer/screens/account/AccountHeaderActions.tsx, apps/ledger-live-desktop/tests/page/drawer/delegate.drawer.ts, apps/ledger-live-desktop/tests/page/modal/delegate.modal.ts, apps/ledger-live-desktop/tests/page/speculos.page.ts, apps/ledger-live-desktop/tests/specs/speculos/delegate.spec.ts, apps/ledger-live-desktop/tests/specs/speculos/send.tx.spec.ts, libs/ledger-live-common/src/e2e/enum/Account.ts, libs/ledger-live-common/src/e2e/enum/AppInfos.ts, libs/ledger-live-common/src/e2e/enum/Currency.ts, libs/ledger-live-common/src/e2e/enum/DeviceLabels.ts, libs/ledger-live-common/src/e2e/families/celo.ts, libs/ledger-live-common/src/e2e/families/tezos.ts, libs/ledger-live-common/src/e2e/speculos.ts
- ...
Adding E2E tests for Tezos and Celo.
Adding test for token invalid transaction
- [QAA-442](https://ledgerhq.atlassian.net/browse/QAA-442)
- [QAA-454](https://ledgerhq.atlassian.net/browse/QAA-454)
- [CI-run](https://github.com/LedgerHQ/ledger-live/actions/runs/13033805584) 
--- …
=> [QAA] Adding E2E delegate test - tezos & Celo

.changeset/great-parrots-talk.md, apps/ledger-live-desktop/src/newArch/hooks/useExportLogs.ts, apps/ledger-live-desktop/src/renderer/components/ExportLogsButton.tsx, apps/ledger-live-mobile/__mocks__/rn-fetch-blob.ts, apps/ledger-live-mobile/src/components/useExportLogs.tsx, apps/ledger-live-mobile/src/screens/Settings/Debug/Debugging/Store.tsx, apps/web-tools/pages/logsviewer.tsx
- ...
Export logs to txt format and update web tools to support txt as input file.
iOS
https://github.com/user-attachments/assets/8c682bd9-51c1-400c-bd2e-367e40ebe853
Android
https://github.com/user-attachments/assets/74fd7ba8-353d-4886-a3b3-c8b86e614859
LLD
https://github.com/user-attachments/assets/b6728253-2d5f-493c-9dcf-455f5afdd22b
Web Tool
https://github.com/user-attachments/assets/b0a01db6-488c-4ce5-8273-6008a8c1ff4f
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-15700
--- …
=> [LIVE-15700] Export logs to txt

.changeset/loud-comics-remember.md
see also https://github.com/LedgerHQ/ledger-live/pull/9089/files where I misconfigured the base branch
=> chore: add changeset about coin-framework and impacted coin modules

.github/workflows/test-ui-e2e-only-desktop.yml
- ...
Adding Xray Link on the Slack notif
-  [QAA-456](https://ledgerhq.atlassian.net/browse/QAA-456)
---
[QAA-456]: https://ledgerhq.atlassian.net/browse/QAA-456?atlOrigin=eyJpIjoiNWRkNTlj …
=> [QAA] Improve Slack notif with the link to Xray

.changeset/dull-dots-float.md, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountsListView/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountsListView/useAccountsListViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Assets/components/AssetsListView/components/AssetItem.tsx, apps/ledger-live-mobile/src/newArch/features/Assets/components/AssetsListView/index.tsx, apps/ledger-live-mobile/src/newArch/features/Assets/components/AssetsListView/useAssetsListViewModel.ts, apps/ledger-live-mobile/src/screens/Portfolio/AnimatedContainer.tsx, apps/ledger-live-mobile/src/screens/Portfolio/PortfolioAssets.tsx, apps/ledger-live-mobile/src/screens/Portfolio/TabSection.tsx, apps/ledger-live-mobile/src/screens/Portfolio/__integrations__/portfolioAssets.integration.test.tsx, apps/ledger-live-mobile/src/screens/Portfolio/index.tsx, apps/ledger-live-mobile/src/screens/Portfolio/useListsAnimation.ts, apps/ledger-live-mobile/src/screens/WalletCentricAsset/AccountsSection.tsx, apps/ledger-live-mobile/src/screens/WalletCentricSections/SectionContainer.tsx
-  tab section with assets and accounts lists
- portfolio screen
- Enhance tab switch animation on portfolioAssets and portfolio screen layout animations
- The animation is quite complex to set up since we use virtualised lists. I tried to explain what I did with comments in the code so it's easier to understand
- For the inte test we only check if it's well defined since the animation doesn't work in the test env
- We need to wrap all components in data in an animated view to avoid flickering
- The animation is also under the ff to avoid side effects  
- `const animatedHeight = useSharedValue(1);` is needed otherwise it will set the height to 0 and never render it
Test video done with staging builds
dark : 
https://github.com/user-attachments/assets/f91972f7-c792-4254-aefc-0c3bd53ba41b …
=> :lipstick: (llm) animation enhancement tab switch

.github/workflows/test-mobile-e2e-reusable.yml, apps/ledger-live-mobile/e2e/specs/speculos/addAccount/AddAccountETH.spec.ts, apps/ledger-live-mobile/e2e/xray.formater.sh
- LLM CI
_After sharding artifacts folder was split failing Xray export_
- For retries, keeping only the most recent (latest) result
- Displaying xray call response to help debugging when failed
- [Test Mobile E2E](https://github.com/LedgerHQ/ledger-live/actions/runs/13111631338)
--- …
=> [Detox][Speculos][CI] Fix xray export 

apps/ledger-live-mobile/e2e/specs/speculos/ledgerSync/ledgerSync.spec.ts
- LLM Ledger Sync test
_Use production CLI calls to create account on Ledger Sync production tests_
- [Production test](https://ledger-live.allure.green.ledgerlabs.net/allure/reports/dfb85de6-c322-45f0-9339-2a163cb7a3e0/#suites/5a8c457a781e623cd39a96e87b7904fa/b0f950a5ce87cb5a/)
- [Staging test](https://ledger-live.allure.green.ledgerlabs.net/allure/reports/e9b10c81-efe9-4fa0-9065-968b7fe7c3c7/#suites/5a8c457a781e623cd39a96e87b7904fa/a5d32989ef228374/)
--- …
=> [Detox][Speculos] Use correct env for Ledger Sync test

apps/ledger-live-mobile/e2e/specs/speculos/verifyAddress/receiveFlowETH.spec.ts
- No impact
_Remove obsolete receive flow issue link_
---
=> [LLM][Speculos]  Remove obsolete issue link

apps/ledger-live-mobile/e2e/page/trade/send.page.ts, apps/ledger-live-mobile/e2e/specs/send/currencies.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/send/send.ts, apps/ledger-live-mobile/e2e/specs/speculos/send/sendALGO.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/send/sendValidAddress/sendValidAddressATOM2.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/send/sendValidAddress/sendValidAddressXRP2.spec.ts, apps/ledger-live-mobile/src/families/cardano/SendRowsCustom.tsx, apps/ledger-live-mobile/src/families/cosmos/shared/CosmosFamilySendRowsCustomComponent.tsx, apps/ledger-live-mobile/src/families/hedera/SendRowsCustom.tsx, apps/ledger-live-mobile/src/families/internet_computer/SendRowMemo.tsx, apps/ledger-live-mobile/src/families/solana/SendRowsCustom.tsx, apps/ledger-live-mobile/src/families/stacks/SendRowMemo.tsx, apps/ledger-live-mobile/src/families/stellar/SendRowMemo.tsx, apps/ledger-live-mobile/src/families/xrp/SendRowTag.tsx, apps/ledger-live-mobile/src/newArch/features/MemoTag/components/GenericMemoTagInput.tsx, apps/ledger-live-mobile/src/newArch/features/MemoTag/components/GenericMemoTagSummary.tsx, apps/ledger-live-mobile/src/newArch/features/MemoTag/components/MemoTagDrawer.tsx
- LLM Speculos Send tests
Adding memo tag testing during Speculos LLM Send flows.
- [@Mobile • Test App End-2-End Speculos](https://github.com/LedgerHQ/ledger-live/actions/runs/13066325053)
---
=> [QAA-449][Detox][Speculos] Add memo tag in Send test

.changeset/ninety-crews-fail.md, apps/ledger-live-mobile/src/analytics/segment.ts
- reborn tracking
Return false for both LP reborn tracking if the ff is off
- **JIRA or GitHub link**: [LIVE-16755](https://ledgerhq.atlassian.net/browse/LIVE-16755)
---
[LIVE-16755]: …
=> :bug: fix(llm) reborn tracking

.changeset/lemon-berries-lie.md, apps/ledger-live-desktop/src/renderer/components/LiveAppDrawer.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/Swap/Form/Modal/Confirmation.tsx
- ...
Added near to not supported list for LNS
---
=> feat: added near in the not supported coins for LNS

.github/workflows/build-mobile-reusable.yml, .github/workflows/test-mobile-e2e-reusable.yml, tools/actions/composites/setup-caches/action.yml
Current issues with pipelines cause intermittent issues with builds & detox tests.
This temporary change should help alleviate some of the issues in lieu of a pending infra fix
Passing Runs:
https://github.com/LedgerHQ/ledger-live/actions/runs/13136494109/job/36652968547
https://github.com/LedgerHQ/ledger-live/actions/runs/13136576138/job/36653232023
=> ci: Cache cleanup for macOS pods

.changeset/calm-games-reply.md, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/ScanDeviceAccounts/index.tsx
- ...
PS: data used in the video  is fake , it's just to occur a scroll behaviour on the UI 
https://github.com/user-attachments/assets/b1bb3b3c-eda7-4625-a57f-adeb4af4bdeb
https://ledgerhq.atlassian.net/browse/LIVE-16640
Also fixes the unwanted behavior here https://ledgerhq.atlassian.net/browse/LIVE-16505
--- …
=> fix: 🐞 scrollable view behavior while retrieving accounts (add account v2)

.changeset/loud-bees-shake.md, apps/ledger-live-desktop/src/renderer/components/LiveAppDrawer.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/Swap/Form/Modal/Confirmation.tsx
- ledger-live-desktop
- live-mobile
- @ledgerhq/live-common
Show warning message when trying to swap Aptos using a Ledger Nano S.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-15792 and https://ledgerhq.atlassian.net/browse/LIVE-15793
--- …
=> feat: add aptos to the list of not supported coins for swap with LNS

.changeset/yellow-rocks-cross.md, apps/ledger-live-desktop/src/renderer/components/DeviceAction/index.tsx, apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx
- ...
Fix a bug in post onboarding when detached the device.
- **JIRA or GitHub link**: [LIVE-16616](https://ledgerhq.atlassian.net/browse/LIVE-16616)
---
[LIVE-16616]: …
=> [LIVE-16616] Fix post onboarding bug of lottie

apps/ledger-live-mobile/src/screens/Account/index.tsx, apps/ledger-live-mobile/src/screens/WalletCentricSections/OperationsHistory.tsx
- LLM Speculos Send tests
_Fixing account operations history testID to be unique_
- [Test Mobile Speculos](https://github.com/LedgerHQ/ledger-live/actions/runs/13142139424)
---
=> [QAA][LLM][Speculos] Fix Add account tests

.changeset/twelve-ladybugs-judge.md, libs/coin-modules/coin-evm/src/specs.ts
- ...
⚠️ TEST account balance moved with operation value
Error: expect(received).toBe(expected) // Object.is equality
- **JIRA or GitHub link**: [LIVE-16745](https://ledgerhq.atlassian.net/browse/LIVE-16745)
--- …
=> fix: add blast in underValuedFeesCurrencies as we do for base

.changeset/late-kings-crash.md, apps/ledger-live-mobile/src/screens/Portfolio/PortfolioAssets.tsx
- ...
Fix a bug introduced by the rework of accounts list. The button should be displayed until we have the "see all accounts" button
https://github.com/user-attachments/assets/139e4c9a-f80b-4983-93bf-6746c6281526
- **JIRA or GitHub link**: [LIVE-16825](https://ledgerhq.atlassian.net/browse/LIVE-16825)
--- …
=> :bug: fix(llm) missing add account button

.changeset/poor-icons-speak.md, apps/ledger-live-desktop/src/renderer/components/LiveAppDrawer.tsx
- ...
Add lifi to nano S incompatibility list
https://ledgerhq.atlassian.net/browse/LIVE-16651
---
=> Feat/(LIVE-16651) add lifi to nano S incompatibility list

libs/ledger-live-common/src/e2e/families/cardano.ts
- ...
Fix Cardano delegate flow
[Allure](https://ledger-live.allure.green.ledgerlabs.net/allure/reports/782c60aa-4ca9-41df-9202-bea5e9d63d23/#suites/dc0704d67244fc15a4ac3e880c2003b1/65529790124bb741/retries)
- **JIRA or GitHub link**: [qaa-473](https://ledgerhq.atlassian.net/browse/QAA-473)
--- …
=> [QAA] fix Cardano delegate flow - speculos e2e

.changeset/new-colts-wash.md, apps/ledger-live-mobile/src/contentCards/cards/hero/elements.tsx, apps/ledger-live-mobile/src/contentCards/cards/hero/index.tsx
- LLM braze hero content card
missing style props for hero cards. When we pass centerText we missed the textAlign. + change the text size (asked by Growth)
|![image](https://github.com/user-attachments/assets/aa138a5c-4681-44ab-9792-435f62ebcd51)|![image](https://github.com/user-attachments/assets/c739f818-1686-4c18-aaaa-b8b5a0885696)|
- **JIRA or GitHub link**: [LIVE-16804](https://ledgerhq.atlassian.net/browse/LIVE-16804)
---
- …
=> :bug: fix(llm) missing style props for hero card

.changeset/ninety-clouds-fly.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/Swap/LiveApp/WebView.tsx
- ...
- change tabs title
- fix bottom padding for iOS
---
=> fix(live-14726): llm spacing internalization

.changeset/small-hornets-accept.md, libs/coin-modules/coin-stacks/src/bridge/estimateMaxSpendable.ts, libs/coin-modules/coin-stacks/src/bridge/prepareTransaction.ts
- ...
Changes in API caused usage mismatch and reported low fees for transactions to be broadcasted. This fix solves the fee estimation error on broadcast. 
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-16894
--- …
=> [Fix/stacks] transaction broadcast API error

.changeset/thick-bobcats-wait.md, apps/ledger-live-desktop/src/renderer/analytics/hooks/useTrackAddAccountModal.test.ts, apps/ledger-live-desktop/src/renderer/analytics/hooks/useTrackAddAccountModal.ts, apps/ledger-live-desktop/src/renderer/analytics/hooks/useTrackManagerSectionEvents.test.ts, apps/ledger-live-desktop/src/renderer/analytics/hooks/useTrackManagerSectionEvents.ts, apps/ledger-live-desktop/src/renderer/analytics/hooks/useTrackReceiveFlow.ts, apps/ledger-live-desktop/src/renderer/analytics/hooks/variables.ts, apps/ledger-live-desktop/src/renderer/components/DeviceAction/index.tsx, apps/ledger-live-desktop/src/renderer/components/Stepper/index.tsx, apps/ledger-live-desktop/src/renderer/modals/AddAccounts/steps/StepConnectDevice.tsx
- ...
Added tracking in Add account flow
- **JIRA or GitHub link**:  [LIVE-15766](https://ledgerhq.atlassian.net/browse/LIVE-15766)
---
[LIVE-15766]: https://ledgerhq.atlassian.net/browse/LIVE-15766?atlOrigin=eyJpIjoi …
=> feat(live-15766): Data tracking in the add account flow

.changeset/few-fireants-know.md, apps/ledger-live-mobile/src/actions/settings.ts, apps/ledger-live-mobile/src/actions/types.ts, apps/ledger-live-mobile/src/reducers/settings.ts, apps/ledger-live-mobile/src/reducers/types.ts, apps/ledger-live-mobile/src/screens/Portfolio/PortfolioAssets.tsx, apps/ledger-live-mobile/src/screens/Portfolio/TabSection.tsx, apps/ledger-live-mobile/src/screens/Portfolio/useListsAnimation.ts, libs/ui/packages/native/src/components/Form/TabSelector/index.tsx, libs/ui/packages/native/storybook/stories/Form/TabSelector.stories.tsx
- llm ui
- accounts list portfolio
We want to store the last seen tab so the user doesn't have to change every-time of tab if he prefers one to the other
https://github.com/user-attachments/assets/c5cac467-470e-48b3-93a0-a4fe599255cd
storybook : 
typecheck for the initial tab to avoid errors:
- **JIRA or GitHub link**: [LIVE-16838](https://ledgerhq.atlassian.net/browse/LIVE-16838)
---
- **Any new …
=> :lipstick: (llm) store the last seen tab

.changeset/giant-apes-kick.md, libs/coin-modules/coin-solana/src/synchronization.ts
- Solana sync tokens
Fix possible `undefined` tx on solana sync token logic
Typescript couldn't tell us that it can possibly be `undefined` without the `noUncheckedIndexedAccess` compiler flag ([more infos](https://stackoverflow.com/a/50647536)), but enabling it would make simple code hard to write and had unneeded checks everywhere
- **JIRA or GitHub link**: [LIVE-16926]
---
- **Any new …
=> fix: possible undefined tx on solana sync [LIVE-16926]

.changeset/nice-numbers-notice.md, apps/ledger-live-mobile/Gemfile.lock, libs/evm-tools/src/__tests__/messages/EIP712/index.unit.test.ts, libs/evm-tools/src/message/EIP712/index.ts
- ...
Fixes Lido withdrawals triggering a blind sign rather than a clear sign
[Ticket](https://ledgerhq.atlassian.net/browse/LIVE-15288)
---
=> [LIVE-15288] Fix Lido message triggering blind signing

.github/workflows/test-mobile-e2e-reusable.yml
- Detox Android tests
As merge queue was introduced, sharding should be disabled for this runs_
- [Mock E2E](https://github.com/LedgerHQ/ledger-live/actions/runs/13239855746)
- [Speculos E2E](https://github.com/LedgerHQ/ledger-live/actions/runs/13239820476)
--- …
=> [QAA][Detox][Android][CI] Remove sharding on merge queue

.changeset/lemon-dodos-fail.md, libs/coin-modules/coin-cosmos/src/CosmosValidatorsManager.ts
- ...
This is a LES customer, he wants to stake ATOM with KILN on LL, but KILN doesn’t appear as an option for them anymore.
https://github.com/user-attachments/assets/bef0d8f8-ae97-42b4-8088-e0ecf6e498ac
- **JIRA or GitHub link**:  [LIVE-16909](https://ledgerhq.atlassian.net/browse/LIVE-16909)
--- …
=> fix: set validator limit to 200

.changeset/big-garlics-buy.md, libs/coin-modules/coin-near/src/api/node.ts
- ...
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-16937
--- …
=> fix: use near private endpoint to avoid public endpoint rate limiting

.changeset/five-deers-invite.md, apps/ledger-live-desktop/src/renderer/components/EarnRewardsInfoModal.tsx
- Near e2e tests
Follow up for https://github.com/LedgerHQ/ledger-live/pull/9000/files to fix crash on staking NEAR e2e test. By updating button name to trigger correct transition to the delegation modal window.
- **JIRA or GitHub link**: [LIVE-15740](https://ledgerhq.atlassian.net/browse/LIVE-15740)
--- …
=> Fix staking NEAR e2e test crash

apps/ledger-live-desktop/tests/page/abstractClasses.ts, apps/ledger-live-desktop/tests/page/swap.page.ts, apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts, apps/ledger-live-desktop/tests/userdata/speculos-tests-app.json, libs/ledger-live-common/src/e2e/enum/DeviceLabels.ts, libs/ledger-live-common/src/e2e/enum/Swap.ts, libs/ledger-live-common/src/e2e/families/cardano.ts
- ...
Improving swap e2e performance by removing waitForPageNetworkIdleState
- **JIRA or GitHub link**: [qaa-376](https://ledgerhq.atlassian.net/browse/QAA-376)
---
=> [QAA] Improving swap e2e performance

.github/workflows/test-mobile-e2e-reusable.yml
- LLM E2E Detox tests
_If Simulator hangs, Detox will create a new one to continue tests. This behaviour prevents complete deletion of created Simulator when testing is finished. We are now deleting Simulator given their name._
- [Test Mobile E2E](https://github.com/LedgerHQ/ledger-live/actions/runs/13261393474/job/37018621844)
---
- …
=> [QAA][Detox][iOS] Improve Simulator clean after tests

.changeset/slow-icons-rescue.md, apps/ledger-live-desktop/src/renderer/analytics/hooks/useTrackExchangeFlow.test.ts, apps/ledger-live-desktop/src/renderer/analytics/hooks/useTrackExchangeFlow.ts, apps/ledger-live-desktop/src/renderer/analytics/hooks/useTrackManagerSectionEvents.ts, apps/ledger-live-desktop/src/renderer/analytics/hooks/variables.ts, apps/ledger-live-desktop/src/renderer/components/DeviceAction/index.tsx, apps/ledger-live-desktop/src/renderer/components/LiveAppDrawer.tsx, apps/ledger-live-desktop/src/renderer/modals/AddAccounts/steps/StepConnectDevice.tsx, apps/ledger-live-desktop/src/renderer/modals/Receive/steps/StepConnectDevice.tsx, apps/ledger-live-desktop/src/renderer/screens/manager/DeviceDashboard/DeviceInformationSummary/EditDeviceName.tsx, apps/ledger-live-desktop/src/renderer/screens/manager/DeviceDashboard/DeviceInformationSummary/RemoveCustomImage.tsx, apps/ledger-live-desktop/src/renderer/screens/manager/index.tsx
- ...
Added data tracking in the exchange flow
- **JIRA or GitHub link**:  [LIVE-15765](https://ledgerhq.atlassian.net/browse/LIVE-15765)
---
[LIVE-15765]: https://ledgerhq.atlassian.net/browse/LIVE-15765?atlOrigin=ey …
=> feat(lld): data tracking in the exchange flow

.changeset/wise-frogs-kiss.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/DeviceActions/openOrInstall.tsx, apps/ledger-live-desktop/src/renderer/analytics/hooks/useTrackAddAccountModal.test.ts, apps/ledger-live-desktop/src/renderer/analytics/hooks/useTrackAddAccountModal.ts, apps/ledger-live-desktop/src/renderer/analytics/hooks/useTrackManagerSectionEvents.test.ts, apps/ledger-live-desktop/src/renderer/analytics/hooks/useTrackManagerSectionEvents.ts, apps/ledger-live-desktop/src/renderer/analytics/hooks/useTrackReceiveFlow.test.ts, apps/ledger-live-desktop/src/renderer/analytics/hooks/useTrackReceiveFlow.ts, apps/ledger-live-desktop/src/renderer/analytics/hooks/useTrackSyncFlow.test.ts, apps/ledger-live-desktop/src/renderer/analytics/hooks/useTrackSyncFlow.ts, apps/ledger-live-desktop/src/renderer/components/DeviceAction/index.tsx, apps/ledger-live-desktop/src/renderer/components/Stepper/index.tsx, apps/ledger-live-desktop/src/renderer/modals/Receive/index.tsx
- ...
Added data tracking in Ledger sync flow 
---
=> feat(lld): add data tracking in ledger sync flow

libs/coin-modules/coin-tezos/src/network/bakers.ts
It fixes flaky it tests on tezos
fixed it tests: https://github.com/LedgerHQ/ledger-live/actions/runs/13306143320 ✅
Co-authored-by: Hedi Edelbloute <hedi.edelbloute@ledger.fr>
=> feat: sort tezos baker list

.changeset/lucky-roses-relate.md, apps/ledger-live-desktop/src/config/languages.ts, apps/ledger-live-desktop/src/renderer/reducers/settings.test.ts, apps/ledger-live-desktop/src/renderer/reducers/settings.ts, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/RegionSelect.tsx, apps/ledger-live-mobile/src/context/LedgerStore.tsx, libs/ledger-live-common/src/currencies/index.ts, libs/ledger-live-common/src/currencies/support.ts
- ...
I found an issue on LLM where supported currencies where always replaced by those from the storage.
LLD - Region
https://github.com/user-attachments/assets/3a508b4f-93cb-44be-a8e4-0bf8187bcdb4
LLD - Currency
https://github.com/user-attachments/assets/c014d7a7-bfa4-4398-8239-5d7c9e356e73
LLM - Currency
https://github.com/user-attachments/assets/cce37eb2-07a3-4e98-8f3e-cb08dc868dd0
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-15779, https://ledgerhq.atlassian.net/browse/LIVE-15780
--- …
=> Remove OFAC currencies & regions

.changeset/smart-lizards-remember.md, apps/ledger-live-mobile/src/components/SelectableAccountsList.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/Navigator.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountListDrawer/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountQuickActionsDrawer/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountsListView/useAccountsListViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AddFundsButton/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AddFundsButton/useAddFundsButtonViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/components/SelectAddAccountMethod/useSelectAddAccountMethodViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccountSuccess/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccountSuccess/useAddAccountSuccessViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccountWarning/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccountWarning/useAddAccountWarningViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/ScanDeviceAccounts/components/ScannedAccountsSection/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/ScanDeviceAccounts/useScanDeviceAccountsViewModel.ts, apps/ledger-live-mobile/src/newArch/features/AssetSelection/screens/SelectCrypto/index.tsx, apps/ledger-live-mobile/src/newArch/features/AssetSelection/screens/SelectCrypto/useSelectCryptoViewModel.ts, apps/ledger-live-mobile/src/newArch/features/AssetSelection/screens/SelectNetwork/index.tsx, apps/ledger-live-mobile/src/newArch/hooks/useAnalytics/data/addAccounts.ts, apps/ledger-live-mobile/src/newArch/hooks/useAnalytics/enums.ts
- ...
Fix some analytics metadata.
https://ledgerhq.atlassian.net/browse/LIVE-13984
---
=> fix: 🐞 analytics and warning page close process (instead of back)

apps/ledger-live-mobile/e2e/helpers.ts, apps/ledger-live-mobile/e2e/setup.ts, apps/ledger-live-mobile/e2e/specs/speculos/addAccount/AddAccount.ts, apps/ledger-live-mobile/e2e/specs/speculos/deleteAccount/deleteAccount.ts, apps/ledger-live-mobile/e2e/specs/speculos/ledgerSync/ledgerSync.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/verifyAddress/verifyAddress.ts, apps/ledger-live-mobile/e2e/specs/speculos/verifyAddress/verifyEmptyAddressTRX.spec.ts, libs/ledger-live-common/src/e2e/speculos.ts
- E2E Allure reporting
_Add Speculos screenshots for failed tests_
- [@Mobile • Speculos](https://github.com/LedgerHQ/ledger-live/actions/runs/13295879161)
- [@Desktop • Speculos](https://github.com/LedgerHQ/ledger-live/actions/runs/13267720374)
--- …
=> [QAA][Detox] Add Speculos screenshots for failed tests

.changeset/calm-lamps-kneel.md, apps/ledger-live-desktop/static/i18n/en/app.json, libs/ledgerjs/packages/hw-app-exchange/src/ReturnCode.ts
- ...
[[JIRA-16993]](https://ledgerhq.atlassian.net/browse/LIVE-16993)
---
=> feat: LIVE-16993 updated swap error messages

libs/ledger-live-common/src/e2e/enum/Currency.ts
- Speculos tests
_Upon [9119](https://github.com/LedgerHQ/ledger-live/pull/9119) we have to update Sepolia ticker_
---
=> [QAA][LLM][Speculos] Fix Sepolia ticker

.github/workflows/test-ui-e2e-only-desktop.yml
=> [QAA] [CI] Remove allure results retention policy

.changeset/serious-kings-judge.md, libs/coin-modules/coin-bitcoin/src/wallet-btc/__tests__/wallet.estimateMaxSpendable.integration.test.ts, libs/coin-modules/coin-bitcoin/src/wallet-btc/__tests__/wallet.explorer.unit.test.ts, libs/coin-modules/coin-bitcoin/src/wallet-btc/explorer/index.ts, libs/coin-modules/coin-bitcoin/src/wallet-btc/wallet.ts
- ...
https://github.com/user-attachments/assets/570a1874-d5eb-4f32-b417-6ba4db03ef17
- **JIRA or GitHub link**:  [LIVE-16983](https://ledgerhq.atlassian.net/browse/LIVE-16983)
--- …
=> fix: pending utxo use in estimate max spendable

.changeset/eleven-jeans-change.md, apps/ledger-live-desktop/src/newArch/features/DynamicContent/components/PortfolioContentCards/Slide.tsx, apps/ledger-live-desktop/src/newArch/features/LNSUpsell/__tests__/LNSBannerCard.test.tsx, apps/ledger-live-desktop/src/newArch/features/LNSUpsell/__tests__/LNSNotificationBanner.test.tsx, apps/ledger-live-desktop/src/newArch/features/LNSUpsell/components/LNSNotificationBanner/index.tsx, apps/ledger-live-desktop/src/newArch/features/LNSUpsell/components/LNSbannerCard/index.tsx, apps/ledger-live-desktop/src/newArch/features/LNSUpsell/types/enum/Analytics.ts, apps/ledger-live-desktop/src/newArch/features/LNSUpsell/types/index.ts, apps/ledger-live-desktop/static/i18n/en/app.json, libs/ui/packages/react/src/components/layout/Banner/BannerCard/BannerCard.stories.tsx, libs/ui/packages/react/src/components/layout/Banner/BannerCard/index.tsx, libs/ui/packages/react/src/components/layout/Banner/NotificationCard/NotificationCard.stories.tsx, libs/ui/packages/react/src/components/layout/Banner/NotificationCard/index.tsx, libs/ui/packages/react/src/components/layout/ContentCard/PortfolioContentCard/index.tsx, libs/ui/packages/react/src/components/layout/index.ts
- ...
This PR adds 2 banner components for the 3 types of LNS upsell banners in LLD.
For the Manager banner ([Figma](https://www.figma.com/design/t3IHBozEyxyp5wOWkDVX0L/LL-%2F-Marketing?node-id=4900-9134)) and the Account list banner ([Figma](https://www.figma.com/design/t3IHBozEyxyp5wOWkDVX0L/LL-%2F-Marketing?node-id=4924-27440)): the PortfolioContentCard was refactored and extended into a more generic component called BannerCard. This generic component is used to create the LNSBannerCard component.
For the pinned notification banner ([Figma](https://www.figma.com/design/t3IHBozEyxyp5wOWkDVX0L/LL-%2F-Marketing?node-id=4900-9655)) a new generic NotificationCard ca component was created. Which is used to create LNSNotificationBanner.
- …
=> feat(lld): 💄 add the LNS upsell banners components to LLD

.changeset/wet-geckos-cheer.md, libs/ledger-live-common/src/exchange/swap/updateAccountSwapStatus.ts
- ...
Remove uniswap pending history from status calls
https://ledgerhq.atlassian.net/browse/LIVE-16653
---
=> fix(LIVE-16653): remove uniswap from history status calls

.changeset/chatty-insects-chew.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx, apps/ledger-live-mobile/src/screens/Swap/LiveApp/WebView.tsx
- ...
Passing more info to swap live app
---
=> feat: passing last device and LL version and type to the swap live app

.changeset/orange-turkeys-wait.md
=> fix: typo in a changeset blocking the prerelease

apps/ledger-live-desktop/src/newArch/features/MarketPerformanceWidget/components/Header.tsx, apps/ledger-live-desktop/src/renderer/components/FormattedVal.tsx, apps/ledger-live-desktop/tests/page/portfolio.page.ts, apps/ledger-live-desktop/tests/specs/speculos/portfolio.spec.ts
- ...
https://ledgerhq.atlassian.net/browse/B2CQA-3038
---
=> [QAA] Adding market widget checks

.github/workflows/test-ui-e2e-only-desktop.yml, apps/ledger-live-desktop/tests/page/drawer/delegate.drawer.ts, apps/ledger-live-desktop/tests/page/drawer/send.drawer.ts, apps/ledger-live-desktop/tests/page/modal/send.modal.ts, apps/ledger-live-desktop/tests/page/swap.page.ts, apps/ledger-live-desktop/tests/specs/speculos/delegate.spec.ts
- ...
- Adding check for the ticker in transaction amount
- Updating speculos version (latest)
- Re-work of Best Quote method
- **JIRA or GitHub link**: [qaa-481](https://ledgerhq.atlassian.net/browse/QAA-481)
---
=> [QAA] Check tickers for transaction amounts + update speculos image

.changeset/heavy-apes-exist.md, apps/ledger-live-mobile/src/components/RootNavigator/SwapFormNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/SwapNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/types/SwapNavigator.ts, apps/ledger-live-mobile/src/const/navigation.ts, apps/ledger-live-mobile/src/screens/Swap/LiveApp/index.tsx
- ...
- removed tabs
- navigate to history from icon
https://github.com/user-attachments/assets/c03916c4-e9a8-43fe-8f0a-f7b2e1138bd2
https://ledgerhq.atlassian.net/browse/LIVE-16731
---
=> feat(live-16741): llm swap new header navigation

.changeset/orange-turkeys-wait.md
Repeat the fix [here](https://github.com/LedgerHQ/ledger-live/pull/9269) in develop
=> ci: fix typo in changeset

.changeset/polite-moose-prove.md, apps/ledger-live-desktop/src/renderer/drawers/SwapOperationDetails/index.tsx
- ...
add different url for lifi in swap history
https://ledgerhq.atlassian.net/browse/LIVE-17106
---
=> feat(LIVE-17106): add different url for lifi in swap history

.github/workflows/pr-analysis.yml
=> 👷  Activate SonarCloud PR Analysis for the whole organization

apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts, apps/ledger-live-desktop/tests/userdata/speculos-tests-app.json, libs/ledger-live-common/src/e2e/enum/Account.ts, libs/ledger-live-common/src/e2e/enum/AppInfos.ts, libs/ledger-live-common/src/e2e/enum/Currency.ts, libs/ledger-live-common/src/e2e/speculos.ts
- ...
Adding pairs for E2E swap tests:
- XRP → USDC
- ETH → XRP
- BTC → XRP
- BTC → LTC
- **JIRA or GitHub link**: [qaa-281](https://ledgerhq.atlassian.net/browse/QAA-281)
---
=> [QAA] Adding pairs to swap e2e tests

turbo.json
- ...
Release version of #9291
---
=> Update auto-close target to Smartling Github app (release)

.changeset/chilled-walls-vanish.md, libs/ledger-live-common/src/exchange/swap/updateAccountSwapStatus.ts
- ...
swap lifi sends txId like thorswap for history status
---
=> feat: swap lifi sends txId like thorswap for history status

.changeset/happy-llamas-grin.md, apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/CompleteExchange/TransactionBroadcastedContent.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/ExchangeDrawer/SwapCompleted.tsx
- ...
fix swap id to long in completed swap drawer
https://ledgerhq.atlassian.net/browse/LIVE-17222
---
=> fix(LIVE-17222): 

.changeset/stale-clouds-glow.md, apps/ledger-live-mobile/src/components/RootNavigator/BaseNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/FeesNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/SwapNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/types/BaseNavigator.ts, apps/ledger-live-mobile/src/components/RootNavigator/types/FeesNavigator.ts, apps/ledger-live-mobile/src/const/navigation.ts, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/Fees/FeeContainer.tsx, apps/ledger-live-mobile/src/screens/Fees/StrategyIcon.tsx, apps/ledger-live-mobile/src/screens/Fees/index.tsx, apps/ledger-live-mobile/src/screens/Swap/LiveApp/customHandlers/getFee.ts, apps/ledger-live-mobile/src/screens/Swap/LiveApp/customHandlers/index.ts, apps/ledger-live-mobile/src/screens/Swap/LiveApp/customHandlers/swapRedirectToHistory.ts, apps/ledger-live-mobile/src/screens/Swap/LiveApp/hooks/useSwapLiveAppCustomHandlers.ts, apps/ledger-live-mobile/src/screens/Swap/LiveApp/utils/index.ts
- ...
- Swap LLM Swap Drawer
https://ledgerhq.atlassian.net/browse/LIVE-15402
---
=> Feat/LIVE-15402: add gas fee drawer and fix fee fetching for swap-live-app

.changeset/wise-students-wonder.md, apps/ledger-live-mobile/src/analytics/segment.ts, apps/ledger-live-mobile/src/newArch/utils/__tests__/getTokensWithFunds.test.ts, apps/ledger-live-mobile/src/newArch/utils/getTokensWithFunds.ts
- analytics
Add token with funds user property. 
This can't be tested with generated accounts so you have to test with real ones. In the example video I've sent all my bnb usdc to another wallet. 
| PT1        | PT2         |
|https://github.com/user-attachments/assets/96736a21-aa8f-44c5-aad3-df54963a4cba|https://github.com/user-attachments/assets/1f3f4020-5d98-41f6-a6c3-aa78ce94471a|
the event will be like this : 
- **JIRA or GitHub link**: [LIVE-9055](https://ledgerhq.atlassian.net/browse/LIVE-9055)
--- …
=> :chart_with_upwards_trend: (llm) tokens with funds analytics

.changeset/silly-crabs-lay.md, libs/coin-modules/coin-stellar/src/api/index.integ.test.ts, libs/coin-modules/coin-stellar/src/api/index.test.ts, libs/coin-modules/coin-stellar/src/api/index.ts, libs/coin-modules/coin-stellar/src/logic/listOperations.ts, libs/coin-modules/coin-stellar/src/network/horizon.ts
Co-authored-by: Salim Belkhir <salim.belkhir@ledger.fr>
integration tests: https://github.com/LedgerHQ/ledger-live/actions/runs/13495943095
=> fix(coin:stellar): list operations api

.changeset/rich-frogs-double.md, apps/ledger-live-desktop/src/renderer/components/Chart/index.tsx, apps/ledger-live-desktop/src/renderer/screens/account/BalanceSummary.tsx, apps/ledger-live-desktop/src/renderer/screens/asset/BalanceSummary.tsx, apps/ledger-live-desktop/src/renderer/screens/dashboard/GlobalSummary.tsx, apps/ledger-live-desktop/src/renderer/screens/market/MarketCoin/components/MarketCoinChart.tsx
- LLD Graph 
Add tracking when the graph is hovered during at least 2 sec
https://github.com/user-attachments/assets/2d37d202-c9c5-40bd-b96b-90d355b2a38b
- **JIRA or GitHub link**: [LIVE-16807](https://ledgerhq.atlassian.net/browse/LIVE-16807)
--- …
=> :chart_with_upwards_trend: (lld) graph tracking

apps/ledger-live-mobile/e2e/models/currencies.ts, apps/ledger-live-mobile/e2e/models/stake.ts, apps/ledger-live-mobile/e2e/page/speculos.page.ts, apps/ledger-live-mobile/e2e/page/trade/deviceValidation.page.ts, apps/ledger-live-mobile/e2e/page/trade/operationDetails.page.ts, apps/ledger-live-mobile/e2e/page/trade/send.page.ts, apps/ledger-live-mobile/e2e/page/trade/stake.page.ts, apps/ledger-live-mobile/e2e/specs/speculos/delegate/delegate.ts, apps/ledger-live-mobile/e2e/specs/speculos/delegate/delegateADA.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/delegate/delegateEGLD.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/delegate/delegateINJ.spec.ts, apps/ledger-live-mobile/e2e/specs/speculos/delegate/delegateOSMO.spec.ts, apps/ledger-live-mobile/src/components/ValidateOnDevice.tsx, apps/ledger-live-mobile/src/families/cardano/DelegationFlow/01-Started.tsx, apps/ledger-live-mobile/src/families/cardano/DelegationFlow/02-Summary.tsx, apps/ledger-live-mobile/src/families/elrond/components/Details/Details.tsx, apps/ledger-live-mobile/src/families/elrond/components/Flows/Delegate/components/EarnRewards/EarnRewards.tsx, apps/ledger-live-mobile/src/families/elrond/components/Flows/Delegate/components/PickAmount/PickAmount.tsx, apps/ledger-live-mobile/src/families/elrond/components/Flows/Delegate/components/SetDelegation/SetDelegation.tsx, apps/ledger-live-mobile/src/screens/OperationDetails/Content.tsx, libs/ledger-live-common/src/e2e/enum/AppInfos.ts, libs/ledger-live-common/src/e2e/enum/Currency.ts, libs/ledger-live-common/src/e2e/speculos.ts
- Detox Delegate tests
_Adding additional delegated coins_
- Speculos [run](https://github.com/LedgerHQ/ledger-live/actions/runs/13494140979)
---
=> [QAA][Speculos][Detox] Add additional staking coins

apps/ledger-live-desktop/tests/page/swap.page.ts
=> [QAA] fix ci: updated locator

apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts, apps/ledger-live-desktop/tests/userdata/speculos-tests-app.json
- ...
Minimum amount to trigger swap is 14 XRP
---
=> [QAA] updating XRP amount for swap test

apps/ledger-live-mobile/e2e/specs/speculos/delegate/delegateADA.spec.ts
- Detox DelegateADA test
_Fix default ADA delegator in LLM Speculos test_
---
=> [QAA][Speculos][Detox] Fix default ADA delegator

.changeset/cuddly-insects-knock.md, apps/ledger-live-mobile/src/newArch/features/AssetSelection/screens/SelectCrypto/index.tsx, apps/ledger-live-mobile/src/newArch/features/AssetSelection/screens/SelectCrypto/useSelectCryptoViewModel.ts
- ...
The initiated issues, is when an add account v2 flow is triggered from a deeplink, the app wait for the correct context to make the feature based navigation go correctly especially from the only entry point which is SelectCrypto part of Asset Selection new navigator. 
Now we can inject explicitly an AddAccounts context when the root path is `add-account`. 
https://github.com/user-attachments/assets/ba3baa7f-139a-4f8e-812c-2dc413b70ce2
The Account selection screen redirection is deleted as it will be part of v2 increment Receive Flow fusion.
https://ledgerhq.atlassian.net/browse/LIVE-17358
---
- **The PR description clearly documents the changes** made and explains …
=> fix: 🐞 context injection in deeplink redirection to add account v2 + delete the account selection logic

.changeset/young-owls-walk.md, apps/ledger-live-mobile/src/screens/Swap/LiveApp/consts.ts, apps/ledger-live-mobile/src/screens/Swap/LiveApp/customHandlers/getFee.ts, apps/ledger-live-mobile/src/screens/Swap/LiveApp/customHandlers/index.ts
- ...
- use LLD code to fetch fees
https://ledgerhq.atlassian.net/browse/LIVE-15402
---
=> fix(live-15402): partial fix for custom method to get fees 

libs/coin-modules/coin-solana/src/bridge/js.ts, libs/coin-modules/coin-solana/src/config.ts, libs/ledger-live-common/src/families/solana/config.ts
=> chore: add queuedInterval in config

.changeset/giant-pans-brake.md, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/index.tsx
- ...
To handle SimpleHash Migration : for the moment we need to hide Tools related to simpleHash
https://github.com/user-attachments/assets/71187255-a2d8-4824-897c-d3a32407b1aa
- **JIRA or GitHub link**: [LIVE-17384] 
--- …
=> bugfix: Hide SimpleHashTool when FF off

.changeset/sharp-mangos-serve.md, apps/ledger-live-mobile/src/screens/Swap/LiveApp/customHandlers/getFee.ts, apps/ledger-live-mobile/src/screens/Swap/LiveApp/customHandlers/index.ts
- ...
- SWAP LLM open network fees drawer 
https://github.com/user-attachments/assets/e813293a-f0c1-428e-bd28-ca96d1fa10e9
https://ledgerhq.atlassian.net/browse/LIVE-15402
---
=> fix(live-15402): swap llm - open network fees drawer 

.changeset/rude-cows-greet.md, libs/coin-modules/coin-icon/src/specs.ts, libs/ledger-live-common/src/families/celo/specs/createSendMutation.ts
- ...
- **JIRA or GitHub link**:  [LIVE-17385](https://ledgerhq.atlassian.net/browse/LIVE-17385)
--- …
=> fix: specs celo and Icon

.github/workflows/sonar.yml
- ...
The sonar.yml workflow shouldn't be running during busy hours when we might need those resources.
Instead it should run during the night
---
=> 👷  CI - Sonar workflow to run during the night

.changeset/thick-eels-burn.md, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/EnableStagingNftMetadataServiceToggle.tsx, apps/ledger-live-desktop/tests/page/drawer/nft.drawer.ts, apps/ledger-live-mobile/src/screens/Settings/Debug/Configuration/NftMetadataServiceRow.tsx, libs/coin-modules/coin-evm/src/api/nft/index.ts, libs/coin-modules/coin-evm/src/signOperation.ts, libs/env/src/env.ts, libs/ledger-services/trust/src/common.ts, libs/ledger-services/trust/src/solana.test.ts, libs/live-nft/src/api/metadataservice.ts
- ...
Update staging url for NMS and rename env variable to be more accurate with what actually does the NMS (not only ETH related anymore)
- **JIRA or GitHub link**:  [LIVE-17443]
---
[LIVE-17443]: …
=> chore: update nft metadata service staging url 🔧

.changeset/stale-kids-sleep.md, apps/ledger-live-mobile/src/screens/Swap/LiveApp/index.tsx
- ...
swap llm display correct error message when app failed to load
https://ledgerhq.atlassian.net/browse/LIVE-15727
---
=> fix(live-15727): swap llm display correct error message when app failed to load

.changeset/hot-paws-serve.md, libs/coin-modules/coin-tron/src/bridge/synchronization.ts, libs/coin-modules/coin-tron/src/logic/lastBlock.integ.test.ts, libs/coin-modules/coin-tron/src/logic/lastBlock.test.ts, libs/coin-modules/coin-tron/src/logic/lastBlock.ts, libs/coin-modules/coin-tron/src/network/index.ts
- ...
Add lastBlock route for Alpaca.
Remove `fetchCurrentBlockHeight` and use `getLastBlock` in sync
- **JIRA or GitHub link**:  [LIVE-17433](https://ledgerhq.atlassian.net/browse/LIVE-17433)
---
[LIVE-17433]: …
=> feat: add lastBlock function and tests

.changeset/selfish-apples-build.md, apps/ledger-live-desktop/tests/handlers/index.ts, apps/ledger-live-desktop/tests/handlers/nfts.ts, apps/ledger-live-desktop/tests/page/drawer/nft.drawer.ts, libs/coin-modules/coin-evm/src/api/nft/index.ts, libs/live-nft/src/api/metadataservice.ts
- ...
Update to v2 to be more accurate with the new endpoints and to start the migration to handle Solana NFTs
a
- **JIRA or GitHub link**: [LIVE-17447] 
---
[LIVE-17447]: …
=> chore: Update NMS version to v2

.changeset/stale-lions-occur.md, apps/ledger-live-desktop/tests/page/modal/delegate.modal.ts, apps/ledger-live-desktop/tests/specs/speculos/delegate.spec.ts, apps/ledger-live-mobile/e2e/page/trade/stake.page.ts, apps/ledger-live-mobile/e2e/specs/speculos/delegate/delegate.ts, apps/ledger-live-mobile/e2e/specs/speculos/delegate/delegateADA.spec.ts, apps/ledger-live-mobile/src/families/cardano/shared/PoolRow.tsx, apps/ledger-live-mobile/src/families/cardano/shared/SearchBox.tsx
- ...
Fix ADA delegation on LLM and LLD: 
- Select `LBF3 - Ledger by Figment 3` as validator
- [LLD run](https://github.com/LedgerHQ/ledger-live/actions/runs/13654784319)
- [LLM run](https://github.com/LedgerHQ/ledger-live/actions/runs/13654913506)
--- …
=> [QAA] fix ADA delegation - LLM & LLD

.changeset/fresh-panthers-call.md, apps/ledger-live-desktop/src/renderer/components/TopBar/NotificationIndicator/ServiceStatusPanel.tsx
- ...
Status OK centered in Status Center
- **JIRA or GitHub link**: [LIVE-17482] 
---
[LIVE-17482]: https://ledgerhq.atlassian.net/browse/LIVE-17482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwI …
=> bugfix: Status OK centered in Status Center

.changeset/four-lizards-obey.md, apps/ledger-live-desktop/src/renderer/components/WebRecoverPlayer/index.tsx
- ...
The issue in the hitbox of the close button in the recover upsell page is caused by the `AppRegionDrag` component that is overlaying the top of the whole screen and contains the `-webkit-app-region: drag;` css attribute which allows to drag the window but not to click on the buttons.
We had the same issue with the LLD top bar buttons and we solved it by overriding the `-webkit-app-region` attribute on those buttons and set it to `no-drag`
However we can't do that on the recover screen as the buttons exist on the live app and if we were to override this attribute around the whole `WebRecoverPlayer` we wouldn't be able to drag LLD anymore while on this screen.
My suggestion is to add a `margin-top` to this component so that the buttons are accessible and the window will still be …
=> 🐛 LLD - Recover Close Button Hitbox Fixed

.changeset/cyan-ears-boil.md, apps/ledger-live-mobile/src/components/Web3AppWebview/NetworkError.tsx
- ...
Fixes misaligned network error view on Web3AppWebview
| ![image](https://github.com/user-attachments/assets/c8f35a3d-7193-4af7-95a0-6922df5158d9) | ![image](https://github.com/user-attachments/assets/af1187e5-7a5b-4a96-9281-b190382a8dbe) |
| …
=> fix(LIVE-17353): fix misaligned network error

.changeset/late-papayas-march.md, apps/ledger-live-mobile/src/components/RootNavigator/types/BaseNavigator.ts, apps/ledger-live-mobile/src/components/RootNavigator/types/SwapFormNavigator.ts, apps/ledger-live-mobile/src/screens/Swap/LiveApp/customHandlers/getFee.ts, apps/ledger-live-mobile/src/screens/Swap/LiveApp/customHandlers/index.ts, apps/ledger-live-mobile/src/screens/Swap/LiveApp/customHandlers/saveSwapToHistory.ts, apps/ledger-live-mobile/src/screens/Swap/LiveApp/customHandlers/swapRedirectToHistory.ts, apps/ledger-live-mobile/src/screens/Swap/LiveApp/hooks/useSwapLiveAppCustomHandlers.ts, libs/ledger-live-common/src/exchange/swap/getCompleteSwapHistory.ts
- ...
- redirect to history on success and show swap list
https://github.com/user-attachments/assets/07c62e77-bfc1-43a5-9a8c-aef000784a90
https://ledgerhq.atlassian.net/browse/LIVE-17350
https://ledgerhq.atlassian.net/browse/LIVE-17347
--- …
=> fix(live-17350): redirect to history on success and show swap list

.changeset/good-trains-hope.md, CODEOWNERS, apps/ledger-live-mobile/android/app/build.gradle, apps/ledger-live-mobile/android/app/src/main/AndroidManifest.xml, apps/ledger-live-mobile/android/app/src/main/java/com/ledger/live/LocationHelperModule.kt, apps/ledger-live-mobile/android/app/src/main/java/com/ledger/live/NativeModulesPackage.kt, apps/ledger-live-mobile/src/components/RequiresBLE/hooks/useRequireBluetooth.ts, apps/ledger-live-mobile/src/components/RequiresBLE/index.tsx, apps/ledger-live-mobile/src/components/RequiresLocation/AndroidRequiresLocationEnabled.tsx, apps/ledger-live-mobile/src/components/RequiresLocation/AndroidRequiresLocationPermission.tsx, apps/ledger-live-mobile/src/components/RequiresLocation/hooks/useAndroidEnableLocation.ts, apps/ledger-live-mobile/src/components/RequiresLocation/hooks/useAndroidLocationPermission.ts
- iOS:
- no impact
- Android BLE devices scanning:
- on Android versions > 11, location permissions are no longer required, and location services don't need to be enabled anymore.
- on Android versions <= 11, fixed the issue where "Location services required" screen was periodically appearing even though the locations services were already enabled.
cf. "impact of the changes"
The error screen "Location services required" appears periodically even though location services are enabled:
https://github.com/user-attachments/assets/e1f8408b-ce60-48d7-afcd-d9cc4ab605c9
The error screen "Location services required" only appears if the location services are disabled.
https://github.com/user-attachments/assets/498ca0bf-797b-4b22-afdd-a91737b051c3
No location permission required, location services …
=> [LLM][Android][LIVE-13318] Fix location permissions & location service issue

.changeset/tender-rabbits-visit.md, apps/ledger-live-mobile/src/screens/Swap/LiveApp/hooks/useSwapLiveAppCustomHandlers.ts
- ...
- use flatten accounts in transaction flow
https://github.com/user-attachments/assets/0e845a79-60dd-444a-b4e6-9f9ca1ea0009
https://ledgerhq.atlassian.net/browse/LIVE-17393
---
=> fix: use flatten accounts in transaction flow

libs/ledger-live-common/src/hw/getAppAndVersion.test.ts, libs/ledger-live-common/src/hw/listApps.test.ts, libs/ledgerjs/packages/hw-app-exchange/src/Exchange.ts
- ...
Added some tests to understand how some `src/hw` functions worked.
---
=> Add some unit test in LLC `hw`

.changeset/sharp-geese-exist.md, apps/ledger-live-mobile/src/screens/Swap/LiveApp/customHandlers/getFee.ts
- ...
remove llm fee drawer for bitcoin
---
=> fix(LIVE-17421): remove llm fee drawer for bitcoin

apps/ledger-live-mobile/e2e/page/index.ts, apps/ledger-live-mobile/src/components/BleDevicePairingFlow/BleDevicePairing.tsx, apps/ledger-live-mobile/src/components/BleDevicePairingFlow/BleDevicePairingContent/BleDevicePeerRemoved.tsx, apps/ledger-live-mobile/src/components/BleDevicePairingFlow/BleDevicesScanning.tsx, apps/ledger-live-mobile/src/components/BleDevicePairingFlow/DmkBleDevicePairing.tsx, apps/ledger-live-mobile/src/components/BleDevicePairingFlow/DmkBleDevicesScanning.tsx, apps/ledger-live-mobile/src/components/RequiresBLE/hooks/useEnableBluetooth.ts, apps/ledger-live-mobile/src/components/SelectDevice2/index.tsx, apps/ledger-live-mobile/src/index.tsx, apps/ledger-live-mobile/src/live-common-setup.ts, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/react-native-hw-transport-ble/index.ts, apps/ledger-live-mobile/src/screens/PairDevices/Scanning.tsx, apps/ledger-live-mobile/src/screens/PairDevices/index.tsx, apps/ledger-live-mobile/src/screens/Settings/Experimental/LDMKTransportHeader.tsx, apps/ledger-live-mobile/src/services/registerTransports.ts, libs/ledger-live-common/src/ble/hooks/useBleDevicesScanning.ts, libs/live-dmk-desktop/package.json, libs/live-dmk-desktop/vitest.config.ts, libs/live-dmk-mobile/package.json, libs/live-dmk-mobile/src/hooks/useBleDevicesScanning.ts, libs/live-dmk-mobile/src/transport/DeviceManagementKitTransport.ts, libs/live-dmk-mobile/vitest.config.ts, libs/live-dmk-shared/package.json, libs/live-dmk-shared/src/hooks/useDeviceSessionRefresherToggle.test.tsx, pnpm-lock.yaml
=> chore(ldmk-in-llm): add feature flag

.changeset/tasty-readers-divide.md, apps/ledger-live-mobile/src/families/cardano/Delegations/Row.tsx, apps/ledger-live-mobile/src/families/cardano/Delegations/index.tsx, libs/coin-modules/coin-cardano/.unimportedrc.json, libs/coin-modules/coin-cardano/package.json, libs/coin-modules/coin-cardano/src/api/api-types.ts, libs/coin-modules/coin-cardano/src/api/getDelegationInfo.ts, libs/coin-modules/coin-cardano/src/buildOptimisticOperation.ts, libs/coin-modules/coin-cardano/src/buildTransaction.test.ts, libs/coin-modules/coin-cardano/src/buildTransaction.ts, libs/coin-modules/coin-cardano/src/fixtures/accounts.ts, libs/coin-modules/coin-cardano/src/fixtures/protocolParams.ts, libs/coin-modules/coin-cardano/src/serialization.ts, libs/coin-modules/coin-cardano/src/signer.ts, libs/coin-modules/coin-cardano/src/synchronisation.unit.test.ts, libs/coin-modules/coin-cardano/src/types.ts, libs/coin-modules/coin-cardano/src/typhonSerializer.ts, libs/ledger-live-common/package.json, libs/ledger-live-common/src/families/cardano/__snapshots__/bridge.integration.test.ts.snap, libs/ledger-live-common/src/families/cardano/signerSerializer.ts, libs/ledger-live-common/src/mock/account.ts, pnpm-lock.yaml
- This is a background process so no additional action from user is needed except accepting Abstain vote from device while making first transaction after this PR release
Transaction: https://cardanoscan.io/transaction/3654457a056785ddaa25a62c06fa936ac7f064b24154ca09172dee1d5ec56999
The latest Cardano hard fork doesn't allow account to withdraw rewards if it is not delegating in governance and for that reason withdrawing of rewards was disabled as a temporary solution so ledger-live doesn't break.
This PR enables rewards withdrawal by doing `abstain` as default vote for the account which are not delegating.
- **JIRA or GitHub link**:  [LIVE-16725](https://ledgerhq.atlassian.net/browse/LIVE-16725)
--- …
=> feat: add abstain vote delegation by default

.changeset/big-rats-smoke.md, apps/ledger-live-desktop/src/renderer/components/TopBar/index.tsx
- [ X] `npx changeset` was attached.
- ...
Add analytics for discreet mode
- **JIRA or GitHub link**: [LIVE-15567]  
---
https://github.com/user-attachments/assets/91670b24-64ed-4405-9457-1eade663b848
[LIVE-15567]: …
=> feat: add analytics on discreet mode

.changeset/thin-bulldogs-press.md, apps/ledger-live-mobile/src/locales/th/common.json, libs/ui/packages/native/src/components/Form/Input/AnimatedInput/AnimatedNotchedLabel.tsx, libs/ui/packages/native/src/components/Tabs/Graph/index.tsx, libs/ui/packages/native/src/components/Text/getTextStyle.ts
- ...
Fix Thai issues in HIGH prio : https://ledgerhq.atlassian.net/wiki/spaces/LLI/pages/5618663548/L10N+LLM+DEV+Issues+for+Thai+Launch
|<img width="295" alt="input" src="https://github.com/user-attachments/assets/1046aa29-e85a-4abc-a556-9d4c5246c3f5" />|![Screenshot_2025-03-10-16-31-47-75_99c1b3bb631177f8a9e1379ae5b12ffe](https://github.com/user-attachments/assets/2c34fc39-3baa-44d4-bb25-c79294b548a0)|
|<img width="230" alt="reset" src="https://github.com/user-attachments/assets/bee8c99e-f9f5-4c68-8afa-7e35d2897f91" />|![Screenshot_2025-03-10-16-31-57-62_99c1b3bb631177f8a9e1379ae5b12ffe](https://github.com/user-attachments/assets/fca157ab-b7c1-4023-bc4b-39127bbae7b0)|
|<img width="301" alt="graph_all" …
=> 🐛  LLM - Thai UI issues

.github/workflows/test-ui-e2e-only-desktop.yml, apps/ledger-live-desktop/tests/fixtures/common.ts, apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts, tools/actions/composites/setup-e2e-swap/action.yml
- ...
Updating target for SWAP_API_BASE depending on the firebase env:
- testing target STG
- JS target PRD
- Staging target STG
- **JIRA or GitHub link**: [qaa-505](https://ledgerhq.atlassian.net/browse/QAA-505)
- [targeting STG](https://github.com/LedgerHQ/ledger-live/actions/runs/13768152750)
- [targeting PRD](https://github.com/LedgerHQ/ledger-live/actions/runs/13767552427/job/38497724962)
---
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and …
=> [QAA] [SWAP] Point to PRD for non reg tests

.changeset/popular-apes-look.md, .changeset/tidy-clouds-lay.md, apps/ledger-live-desktop/src/newArch/features/DynamicContent/components/LogContentCardWrapper.tsx, apps/ledger-live-desktop/src/newArch/features/DynamicContent/utils/constants/index.ts, apps/ledger-live-desktop/src/newArch/features/LNSUpsell/__tests__/LNSUpsellBanner.test.tsx, apps/ledger-live-desktop/src/newArch/features/LNSUpsell/components/LNSUpsellBanner/index.tsx, apps/ledger-live-desktop/src/newArch/features/LNSUpsell/components/LNSUpsellBanner/useLNSUpsellBannerModel.ts, apps/ledger-live-desktop/src/newArch/features/LNSUpsell/components/LNSUpsellBanner/useLNSUpsellViewNotification.ts, apps/ledger-live-desktop/src/newArch/features/LNSUpsell/components/LNSUpsellBanner/useViewNotification.ts, apps/ledger-live-desktop/src/newArch/features/LNSUpsell/hooks/useLNSUpsellBannerState.ts, apps/ledger-live-desktop/src/newArch/features/LNSUpsell/types/index.ts, apps/ledger-live-desktop/src/renderer/actions/settings.ts, apps/ledger-live-desktop/src/renderer/components/TopBar/NotificationIndicator/InformationDrawer.tsx, apps/ledger-live-desktop/src/renderer/components/TopBar/NotificationIndicator/index.tsx, apps/ledger-live-desktop/src/renderer/hooks/useBraze.ts, apps/ledger-live-desktop/src/renderer/hooks/useUnseenNotificationsCount.ts, apps/ledger-live-desktop/src/renderer/reducers/settings.ts
- ...
Follow up to #9328. This PR:
- Excludes users with 2 or more swap from the campaign.
- Accounts for the hardcoded LNS notification in the notification count.
- Applies the new arch's [useComponentViewModel](https://ledgerhq.atlassian.net/wiki/spaces/WXP/pages/4508058220/Code+Guidelines+-+React+Native#useComponentViewModel) to the banner.
https://github.com/user-attachments/assets/23c21529-f580-41d8-aef7-78d2cdd00083
- [LIVE-16669]
--- …
=> feat(lld): ☝️ LNS upsell follow up

.changeset/olive-bears-burn.md, apps/ledger-live-mobile/src/newArch/features/Market/screens/MarketDetail/components/MarketGraph/index.tsx
- [X ] `npx changeset` was attached.
- ...
Reverse the order displayed on market asset page
- **JIRA or GitHub link**:[LIVE-17242] 
---
https://github.com/user-attachments/assets/25284e0b-bc36-43e1-a994-d3ce3723ac07 …
=> Reverse the order displayed on market asset page

.changeset/nine-bikes-crash.md, libs/ledger-live-common/src/exchange/swap/completeExchange.ts
- ...
add Lifi to the ERC20 exceptions 
---
=> feat: lifi ERC20

.changeset/cyan-cherries-wave.md, apps/ledger-live-mobile/src/components/Web3AppWebview/NetworkError.tsx, apps/ledger-live-mobile/src/components/Web3AppWebview/WalletAPIWebview.tsx
- ...
The `flex="auto"` was causing a crash as it's not supported by React Native. Also, the Android RNWebView component works slightly different to iOS, and renders 'Webpage not available'. This will now be hidden in the case of an error. 
| Either following or crash: ![image](https://github.com/user-attachments/assets/1680173b-dde9-43b6-af1f-bc9dc503cb09) | ![image](https://github.com/user-attachments/assets/a7f1a637-f53e-4eec-aa6d-2299808c805f) |
- **JIRA or GitHub link**: [LIVE-17562](https://ledgerhq.atlassian.net/browse/LIVE-17562)
--- …
=> fix(LIVE-17562): android crash for unavailable swap

.changeset/yellow-coins-agree.md, libs/coin-modules/coin-xrp/src/api/index.test.ts, libs/coin-modules/coin-xrp/src/api/index.ts, libs/coin-modules/coin-xrp/src/logic/listOperations.ts, libs/coin-modules/coin-xrp/src/types/model.ts
- unit test inside the PR
- integration tests: https://github.com/LedgerHQ/ledger-live/actions/runs/13785680254
- Bug fix on api/listOperations that returned always the same operations
- Bug fix on logic/listOperations that made extra calls when no cursor was returned
https://ledgerhq.atlassian.net/browse/BACK-8469
https://ledgerhq.atlassian.net/browse/LIVE-17614
=> fix(coin:xrp): iterate over pages passing the token

.changeset/lucky-lemons-fly.md, apps/ledger-live-desktop/src/newArch/features/LNSUpsell/components/LNSUpsellBanner/index.tsx, apps/ledger-live-desktop/src/newArch/features/LNSUpsell/components/LNSUpsellBanner/useLNSUpsellBannerModel.ts, apps/ledger-live-desktop/src/newArch/features/LNSUpsell/components/LNSUpsellBanner/useViewNotification.ts, apps/ledger-live-desktop/src/newArch/features/LNSUpsell/types/index.ts, apps/ledger-live-desktop/static/i18n/en/app.json, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/lnsUpsell.ts, libs/ui/packages/react/src/components/layout/Banner/NotificationCard/index.tsx
- ...
- Opt-out notification icon change.
- Opt-out CTA becomes learn more.
- Opt-out banner background color change.
- Also adds the default ff links.
- **JIRA or GitHub link**: [LIVE-16669]
---
[LIVE-16669]: …
=> feat(lld): 🖌️ address LNS upsell design changes

.changeset/soft-bulldogs-smoke.md, apps/ledger-live-desktop/src/renderer/components/DeviceAction/NoSuchAppOnProviderErrorComponent.tsx
- ...
Update NoSuchAppOnProviderError Analytics for LedgerSync
- Page name added and button_clicked added
- **JIRA or GitHub link**: [LIVE-14977] 
---
[LIVE-14977]: …
=> feat: Update NoSuchAppOnProviderError Analytics for LedgerSync

.changeset/dry-ghosts-watch.md, libs/coin-modules/coin-casper/src/api/index.ts, libs/coin-modules/coin-casper/src/api/index.unit.test.ts, libs/coin-modules/coin-casper/src/api/types.ts, libs/coin-modules/coin-casper/src/bridge/broadcast.ts
- ...
Broadcast failure results in error message that's not relevant to the failure. This fixes that and improves logging + error handling on casper api.
---
=> fix: casper api error handling

.changeset/old-rats-care.md, libs/ui/packages/native/src/components/Text/getTextStyle.ts
- ...
Fix those two UI issues : https://ledgerhq.atlassian.net/wiki/spaces/LLI/pages/5618663548/L10N+LLM+DEV+Issues+for+Thai+Launch
---
=> 🐛  LLM - fix Thai small UI issues

.changeset/funny-birds-hang.md, libs/ui/packages/native/src/components/Cards/NewBannerCard/index.tsx, libs/ui/packages/native/src/components/Cards/index.ts, libs/ui/packages/native/src/components/Icon/BannerIcon.tsx, libs/ui/packages/native/src/components/Icon/index.ts, libs/ui/packages/native/storybook/stories/Cards/NewBannerCard.stories.tsx, libs/ui/packages/native/storybook/stories/Icon/BannerIcon.stories.tsx
- ...
This PR adds the "NewBannerCard" component which will be used for the LNS upsell campaign. This component also use the new "BannerIcon" component. Finally adds story for both of the components.
Note: the "NewBannerCard" component could be reused for [Ledger Sync Entry Points feature](https://github.com/LedgerHQ/ledger-live/pull/9263)
- [NewBannerCard](https://native-ui-storybook-git-feat-llm-lnsupsell-components-ledgerhq.vercel.app/?path=/story/cards-newbannercard--lns-upsell)
- [BannerIcon](https://native-ui-storybook-git-feat-llm-lnsupsell-components-ledgerhq.vercel.app/?path=/story/icon-bannericon--default)
- **JIRA or GitHub link**: [LIVE-16658]
---
- **The PR description clearly documents …
=> feat(llm): 📦️ add the banner component to use for the LNS upsell campaign

.changeset/smooth-bears-retire.md, apps/ledger-live-desktop/static/i18n/en/app.json
=> ✏️ LLD - Add trademark to devices names

.changeset/brown-papayas-rule.md, apps/ledger-live-mobile/src/families/solana/DelegationFlow/SelectAmount.tsx
- ...
Add more space between text and button. 
- **JIRA or GitHub link**:  [LIVE-15824](https://ledgerhq.atlassian.net/browse/LIVE-15824)
---
[LIVE-15824]: https://ledgerhq.atlassian.net/browse/LIVE-15824?atlOrigin=ey …
=> fix: Text layout issue in SOL staking flow

.changeset/shaggy-kids-carry.md, apps/ledger-live-desktop/src/renderer/families/cosmos/Delegation/Row.tsx, apps/ledger-live-desktop/src/renderer/families/cosmos/Delegation/index.tsx, apps/ledger-live-desktop/src/renderer/families/evm/AccountHeaderManageActions.ts, apps/ledger-live-mobile/src/components/Stake/useStakingDrawer.tsx, apps/ledger-live-mobile/src/families/cosmos/Delegations/index.tsx, apps/ledger-live-mobile/src/families/evm/accountActions.tsx
- Entrypoints for AVAX
- CRO staking pointing everywhere to stakekit
- POL staking with the right token account
This PR:
- Adds the entrypoints for AVAX
- Fixes some links that were still not pointing to stakekit for CRO
- Fixes the currency id for POL which was not polygon but the token`ethereum/erc20/polygon_ecosystem_token` on `evm`
This PR is temporarily adding these fixes and new entry points in this way, which is not ideal but will be replaced soon enough by this other work (https://github.com/LedgerHQ/ledger-live/pull/9441) where we (I and @beths-ledger ) are developing a more generic solution. The reason why this is pushed in this way is product delivery and deadlines that need to be respected and cannot wait for the generic solution to be tested and completed in time for it.
- …
=> FEAT: AVAX entrypoints, fixes on CRO and  POL

.github/workflows/test-mobile-e2e-reusable.yml
- LLM Speculos
_Changing composite name after change on LLD workflow_
- [LLM Run](https://github.com/LedgerHQ/ledger-live/actions/runs/13898512045)
---
=> [QAA][LLM][Speculos] Fix composite to set broadcast

.changeset/lucky-planets-yawn.md, apps/ledger-live-mobile/src/screens/Onboarding/steps/discoverLiveInfo.tsx
- ...
Fix Thai UI issue in onboarding discovery steps
|<img width="409" alt="Screenshot 2025-03-14 at 11 54 35" src="https://github.com/user-attachments/assets/8840059b-906d-4420-890a-7b2f325a5957" />|<img width="409" alt="Screenshot 2025-03-14 at 11 54 10" src="https://github.com/user-attachments/assets/29d244f6-30a5-4453-acb7-6863b53b9463" />|
--- …
=> 🐛  LLM - Fix Thai UI issue in Onboarding

.changeset/selfish-walls-grab.md, libs/ledger-live-common/src/exchange/providers/swap.integration.test.ts, libs/ledger-live-common/src/exchange/providers/swap.ts
- ...
update lifi signature from cdn
---
=> chore(update-lifi-signature): update lifi signature from cdn

.changeset/kind-ligers-stare.md, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- ...
FF is added also in firebase development env
https://ledgerhq.atlassian.net/browse/LIVE-17540
---
=> feat: add lldSolanaNfts feature flag for live scope

libs/coin-modules/coin-aptos/src/__tests__/bridge/logic.test.ts, libs/coin-modules/coin-aptos/src/bridge/logic.ts, libs/coin-modules/coin-aptos/src/constants.ts, libs/coin-modules/coin-aptos/src/types/index.ts
=> feat(aptos): aptos tokens history parsing

apps/ledger-live-mobile/ios/ledgerlivemobile.xcodeproj/project.pbxproj
- ...
https://ledgerhq.atlassian.net/browse/LIVE-17746
--- …
=> chore: project.pbxproj formatting sync - xcode 16.2

libs/ledger-live-common/package.json, libs/live-dmk/package.json, libs/live-signer-evm/package.json, pnpm-lock.yaml
- ...
Update DMK and ETH Signer to latest version with fixes to device session management and web3checks improvements
---
=> ⬆️ (dmk): bump dmk and signer eth to latest version

.changeset/breezy-mails-wait.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/PostOnboarding/PostOnboardingHub.tsx
- ...
Wrong key was used when we did a refacto on PostOnbaording
- **JIRA or GitHub link**:  [LIVE-17678] 
---
[LIVE-17678]: https://ledgerhq.atlassian.net/browse/LIVE-17678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …
=> bugfix: wrong key for localization in postOnboarding

.changeset/dry-taxis-drum.md, libs/coin-modules/coin-solana/src/api/chain/index.ts
- Solana sync, send/receive error handling
Ensure we don't crash on an undefined error from a promise catch in the solana coin module
Small detail I saw right after we merged the PR: https://github.com/LedgerHQ/ledger-live/pull/9480
--- …
=> fix: handle a possibly undefined error from promise catch

.changeset/fluffy-jokes-look.md, apps/ledger-live-mobile/src/families/near/shared/02-SelectAmount.tsx
- ...
Update NEAR stake display to mimic Solana's
https://github.com/user-attachments/assets/ceaea895-d332-4c50-b87e-9c61c21193ad
- [LIVE-10252](https://ledgerhq.atlassian.net/browse/LIVE-10252)
---
[LIVE-10252]: …
=> fix: near staking display

.changeset/thick-ducks-pull.md, apps/ledger-live-mobile/src/screens/Onboarding/steps/Cards/SelectionCard.tsx
- ...
Fix thai UI issue
https://ledgerhq.atlassian.net/wiki/spaces/LLI/pages/5618663548/L10N+LLM+DEV+Issues+for+Thai+Launch?force_transition=beca7582-ef48-47a3-99c2-34ce52115b08
|![Screenshot 2025-03-18 at 10 28 50](https://github.com/user-attachments/assets/b8e1ba23-f432-43fd-a186-f1353fd74340)|![Screenshot 2025-03-18 at 10 28 41](https://github.com/user-attachments/assets/fbd00ceb-2615-4ee2-a9b3-070ec7f4edb7)|
--- …
=> :bug: bugfix(llm): fix thai small text line height

.changeset/tidy-crabs-grow.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AccountsList/index.tsx, apps/ledger-live-mobile/src/newArch/features/LNSUpsell/components/LNSUpsellBanner/LNSUpsellBanner.test.tsx, apps/ledger-live-mobile/src/newArch/features/LNSUpsell/components/LNSUpsellBanner/index.tsx, apps/ledger-live-mobile/src/newArch/features/LNSUpsell/components/LNSUpsellBanner/types.ts, apps/ledger-live-mobile/src/newArch/features/LNSUpsell/components/LNSUpsellBanner/useLNSUpsellBannerModel.ts, apps/ledger-live-mobile/src/newArch/features/LNSUpsell/hooks/useLNSUpsellBannerState.ts, apps/ledger-live-mobile/src/newArch/features/LNSUpsell/index.ts, apps/ledger-live-mobile/src/newArch/features/LNSUpsell/types.ts, apps/ledger-live-mobile/src/screens/MyLedgerDevice/AppsScreen.tsx, apps/ledger-live-mobile/src/screens/NotificationCenter/Notifications.tsx, apps/ledger-live-mobile/src/screens/NotificationCenter/types.ts, apps/ledger-live-mobile/src/screens/Portfolio/index.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts, libs/ledgerjs/packages/types-live/src/lnsUpsell.ts, libs/ui/packages/native/src/components/Cards/NewBannerCard/index.tsx
- ...
Add the llmNanoSUpsellBanners feature flag, the LNSUpsellBanner including the rendering logic (feature flag + devices models + swap history) mostly taken from the LLD version (#9328). And test it.
- **JIRA or GitHub link**: [LIVE-15645]
- And ~~partially~~ : [LIVE-16670](https://ledgerhq.atlassian.net/issues/LIVE-16670)
---
- …
=> feat(llm): 🚩 add the LNSUpsellBanner on LLM

.changeset/poor-mice-dress.md, apps/ledger-live-mobile/src/families/evm/SelectFeesStrategy.test.tsx, apps/ledger-live-mobile/src/families/evm/SelectFeesStrategy.tsx
- ...
Add hardcoded estimation time depending on EVM transaction fee strategy on LLM, the same way we do on LLD.
---
=> feat(llm): display fee strategy estimated time

.changeset/dry-pumas-destroy.md, libs/coin-modules/coin-stellar/src/api/index.integ.test.ts
Update stellar tests so most of them aren't skipped
craft is broken for now => skipped
---
=> Update coin-stellar api integration tests

.changeset/eighty-dots-enjoy.md, apps/ledger-live-mobile/src/components/WebPTXPlayer/CustomHandlers.ts
- ...
- revert swap sign navigation pop
https://github.com/user-attachments/assets/b429d475-92f2-4643-8442-041e60d1af32
https://ledgerhq.atlassian.net/browse/LIVE-17604
---
=> fix(live-17758): swap sign flow navigation

.changeset/rotten-zebras-lie.md, CODEOWNERS, libs/ledger-services/cal/src/common.ts, libs/ledger-services/cal/src/currencies.integ.test.ts, libs/ledger-services/cal/src/currencies.ts, libs/ledger-services/cal/src/index.ts, libs/ledger-services/cal/src/networks.integ.test.ts, libs/ledger-services/cal/src/networks.ts, libs/ledger-services/cal/src/tokens.integ.test.ts, libs/ledger-services/cal/src/tokens.ts
- ...
Add CAL `/networks` call.
Quick comparaison between LedgerLive AppName mapping and CAL AppName:
|Network ID                  | Local AppName                | CAL AppName           |
|----------------------------|------------------------------|-----------------------|
|acala                       | undefined                    | Acala                 |
|aergo                       | undefined                    | Aergo
|aeternity                   | Aeternity                    | Aeternity
|aion                        | Aion                         | Aion
|akroma                      | Akroma                       | Ethereum
|aleph_zero                  | undefined                    | Aleph Zero
|algorand                    | Algorand                     | Algorand
|apothem_network …
=> Add CAL /networks call

.changeset/giant-bugs-beg.md, libs/ledger-live-common/src/market/utils/rangeDataTable.ts
- ...
We used the wrong parameter for the "1h" interval. Normally, we don't use this interval, but in the code, we filter it out in certain places with `.filter(k => k !== "1h")`. During testing, we probably removed this line yesterday, which caused errors on the CoinGecko side.
The "1h" interval is not normally used in the Live environment.
```
export const rangeDataTable: { [key: string]: RangeData } = {
"1y": {
...
interval: "daily",
},
"30d": {
...
interval: "daily",
},
"7d": {
...
interval: "hourly",
},
"24h": {
...
interval: "hourly",
},
"1h": {
...
interval: "5m",
},
};
```
- **JIRA or GitHub link**: [LIVE-17779] 
--- …
=> bugfix: wrong interval parameter for Coingecko usage

.changeset/beige-ants-begin.md, libs/coin-modules/coin-bitcoin/src/wallet-btc/__tests__/wallet.unit.test.ts, libs/coin-modules/coin-bitcoin/src/wallet-btc/wallet.ts
- ...
for the logic behind the change, you can check https://github.com/LedgerHQ/ledger-live/blob/231b6fde688b8101671aaf60b5d4340de332305f/libs/ledger-live-common/src/families/bitcoin/docs/RBF.md
- **JIRA or GitHub link**:  LIVE-16723
--- …
=> fix: remove rbf transactions from usable utxo checks

apps/ledger-live-desktop/tests/page/swap.page.ts, apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts
- ...
Adding check for minimum amount
🚨USDT => ETH will fail due to a real bug cc @gbecerra-ledger 
https://ledgerhq.atlassian.net/browse/LIVE-17785
- **JIRA or GitHub link**: [QAA-494](https://ledgerhq.atlassian.net/browse/QAA-494)
--- …
=> [QAA] Adding minimum amount test - swap

apps/ledger-live-desktop/tests/page/settings.page.ts, apps/ledger-live-desktop/tests/page/swap.page.ts, apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts, libs/ledger-live-common/src/e2e/enum/Swap.ts
- ...
Adding swap e2e test - landing page:
- Checking infos in quote container
- Exchange button
- **JIRA or GitHub link**: [QAA-493](https://ledgerhq.atlassian.net/browse/QAA-493)
---
- **CI**: [Run](https://github.com/LedgerHQ/ledger-live/actions/runs/13926013736)
--- …
=> [QAA] Adding swap e2e test - landing page

.changeset/hungry-bugs-hear.md, apps/ledger-live-desktop/src/renderer/screens/swapWeb/index.tsx, apps/ledger-live-mobile/src/screens/Swap/LiveApp/WebView.tsx, apps/ledger-live-mobile/src/screens/Swap/LiveApp/hooks/useTranslateToSwapAccount.ts, apps/ledger-live-mobile/src/screens/Swap/LiveApp/index.tsx
- ...
- Support for tokens in Swap deeplink
- When multiple accounts exist, but none was specified, use the account with the highest balance.
- https://ledgerhq.atlassian.net/browse/LIVE-17141
---
=> feat(LIVE-17141): Swap deeplink

libs/coin-modules/coin-aptos/src/__tests__/bridge/getTransactionStatus.test.ts, libs/coin-modules/coin-aptos/src/bridge/getTransactionStatus.ts
- ...
Total spent amount shows wrong value for token transaction in transaction summary. 
- **JIRA or GitHub link**: [LIVE-17730](https://ledgerhq.atlassian.net/browse/LIVE-17730)
---
[LIVE-17730]: …
=> Fix totalSpent appearance for tokens transaction

.changeset/tough-feet-eat.md, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- ...
FeatureFlag for Solana NFTs 
- **JIRA or GitHub link**: [LIVE-17558] 
---
[LIVE-17558]: https://ledgerhq.atlassian.net/browse/LIVE-17558?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0 …
=> feat: Solana NFTs FeatureFlag

.changeset/lazy-readers-breathe.md, apps/ledger-live-desktop/src/newArch/features/Collectibles/Nfts/Collections/index.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/__integration__/mockedAccount.ts, apps/ledger-live-desktop/src/newArch/features/Collectibles/__integration__/shared.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/__integration__/solNftsCollection.test.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/components/Collection/EmptyCollection.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/components/Collection/TableHeader.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/types/Collection.ts
- ...
- Disable Receive CTA on Solana Collections.
- This work is based on a TDD approach, we assume that if SOLANA is the currency and the related feature flag is active, then we should hide the receive cta in the nft collection UI.
- If the feature flag is disabled , no collection will be displayed even if the `.nfts` array prop is populated for solana. 
- if the feature flag is disabled, the learn more link will be hidden.
- The wording will be automatically replace the placeholder with Solana instead of Eth.
More adjustments will be done in this ticket scope https://ledgerhq.atlassian.net/browse/LIVE-17554
https://ledgerhq.atlassian.net/browse/LIVE-17553
---
- **The PR …
=> feat: hide receive cta for Nft Solana

libs/coin-modules/coin-sui/.unimportedrc.json, libs/coin-modules/coin-sui/package.json, libs/ledger-live-common/src/families/sui/logic.ts, libs/ledger-live-common/src/families/sui/types.ts, pnpm-lock.yaml
- ...
fix failed action run https://github.com/LedgerHQ/ledger-live/actions/runs/13976128917/job/39130310877?pr=9611
---
=> fix: sui unimported

libs/coin-framework/src/currencies/__snapshots__/formatCurrencyUnit.test.ts.snap
- ...
fixing failed action run https://github.com/LedgerHQ/ledger-live/actions/runs/13976128917/job/39130311245?pr=9611
---
=> chore: update coin-framework currencies snapshots

apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/CompleteExchange/TransactionBroadcastedContent.tsx
- ...
Fix track
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-17591
---
=> fix: fix Page ModalStep-finished type

.changeset/plenty-scissors-sell.md, apps/ledger-live-mobile/src/components/RecipientInput.tsx, libs/ui/packages/native/src/components/Form/Input/AnimatedInput/index.tsx, libs/ui/packages/native/src/components/Form/Input/BaseInput/index.tsx, libs/ui/packages/native/storybook/stories/Form/Input/AnimatedInput.stories.tsx
- ...
largeMode animatedInput for recipient address
- **JIRA or GitHub link**: [LIVE-16800]
https://github.com/user-attachments/assets/3fedc6c9-87f5-4bfa-9919-1756a6a5a351
---
[LIVE-16800]: …
=> Feat/live 16800: largeMode animatedInput for recipient address

.github/workflows/generate-screenshots.yml, .github/workflows/release-create-hotfix.yml, .github/workflows/release-create.yml, .github/workflows/release-prepare-hotfix.yml, .github/workflows/release-prepare.yml, .github/workflows/release-prerelease.yml, tools/actions/composites/update-snapshots-desktop/action.yml
Upgrading the ghcommit action to remove the docker hub pull of alpine
[Test run](https://github.com/LedgerHQ/ledger-live/actions/runs/13991101634/job/39175019699)
=> CI: Upgrade ghcommit action

apps/ledger-live-desktop/src/newArch/features/Collectibles/Nfts/Collections/index.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/Nfts/components/DetailDrawer/Actions.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/components/Collection/TableRow/index.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/components/DetailDrawer/components/DetailField.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/components/DetailDrawer/components/Title.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/components/DetailDrawer/index.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/components/Gallery/TokenList/Item.tsx, apps/ledger-live-desktop/src/newArch/features/Collectibles/types/Collection.ts, apps/ledger-live-desktop/src/newArch/features/Collectibles/types/DetailDrawer.ts, apps/ledger-live-desktop/src/newArch/features/Collectibles/utils/createNftDetailsArrays.ts, apps/ledger-live-desktop/tests/component/drawer.component.ts, apps/ledger-live-desktop/tests/page/drawer/nft.drawer.ts
- ...
Adding data-testId to new arch components
- **JIRA or GitHub link**: [qaa-519](https://ledgerhq.atlassian.net/browse/QAA-519)
CI: https://github.com/LedgerHQ/ledger-live/actions/runs/13994839895/job/39187753303
--- …
=> [QAA] Fixing NFT e2e test

.changeset/loud-boats-tease.md, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/ScanDeviceAccounts/useScanDeviceAccountsViewModel.ts
- ...
Send currency name instead of the whole object in the analytics of add account v2
https://ledgerhq.atlassian.net/browse/LIVE-17844
---
=> fix: use currency name instead of the whole object for the analytics

apps/ledger-live-mobile/src/screens/Nft/NftGallery/index.tsx
=> Fix solana send btn in Collection

libs/coin-modules/coin-sui/jest.config.js, libs/coin-modules/coin-sui/jest.integ.config.js, libs/coin-modules/coin-sui/package.json, libs/coin-modules/coin-sui/src/bridge/synchronisation.test.ts, libs/coin-modules/coin-sui/src/network/sdk.integration.test.ts
- ...
Add integration tests for operations history
---
=> chore: add sui sdk getOperations integ tests

.changeset/plenty-scissors-sell.md, apps/ledger-live-mobile/src/components/RecipientInput.tsx, libs/ui/packages/native/src/components/Form/Input/AnimatedInput/index.tsx, libs/ui/packages/native/src/components/Form/Input/BaseInput/index.tsx, libs/ui/packages/native/storybook/stories/Form/Input/AnimatedInput.stories.tsx
Reverts LedgerHQ/ledger-live#9546
=> Revert "Feat/live 16800: largeMode animatedInput for recipient address"

libs/coin-modules/coin-sui/package.json, libs/coin-modules/coin-sui/src/bridge/broadcast.test.ts, libs/coin-modules/coin-sui/src/bridge/broadcast.ts, libs/coin-modules/coin-sui/src/bridge/buildOptimisticOperation.test.ts, libs/coin-modules/coin-sui/src/bridge/buildOptimisticOperation.ts, libs/coin-modules/coin-sui/src/bridge/buildTransaction.test.ts, libs/coin-modules/coin-sui/src/bridge/buildTransaction.ts, libs/coin-modules/coin-sui/src/bridge/createTransaction.ts, libs/coin-modules/coin-sui/src/bridge/signOperation.ts, libs/coin-modules/coin-sui/src/bridge/synchronisation.ts, libs/coin-modules/coin-sui/src/types/bridge.ts, pnpm-lock.yaml
- ...
Fix pr https://github.com/LedgerHQ/ledger-live/pull/9611 review comments
---
=> chore: fix pr review comments

.changeset/grumpy-hornets-compare.md, .changeset/sixty-carrots-decide.md, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountsListView/AccountsListView.test.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountsListView/index.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountsListView/useAccountsListViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AccountsList/index.tsx, apps/ledger-live-mobile/src/newArch/features/LNSUpsell/components/LNSUpsellBanner/LNSUpsellBanner.test.tsx, apps/ledger-live-mobile/src/newArch/features/LNSUpsell/hooks/useLNSUpsellBannerState.ts, apps/ledger-live-mobile/src/screens/NotificationCenter/Notifications.tsx, apps/ledger-live-mobile/src/screens/NotificationCenter/types.ts
- ...
First: Look for a braze campaign with the key value `{ campaign: LNS_UPSELL_HIGH_TIER }` to exclude users from the hardcoded LNS upsell rather than their swap history.
Second: Do not take the accounts list screen real estate with the LNS upsell banner:
|   <video src="https://github.com/user-attachments/assets/0ee037be-2485-489d-8d1f-8755792767ae" />         |      <video src="https://github.com/user-attachments/assets/8fd811d4-0291-4424-992e-4cdadf6bcb8c" />         |
- **JIRA or GitHub link**: [LIVE-17782]
--- …
=> fix(llm): 🔧 LNS upsell follow-up

.changeset/hip-monkeys-burn.md, apps/ledger-live-mobile/ios/ledgerlivemobile.xcodeproj/project.pbxproj, apps/ledger-live-mobile/ios/ledgerlivemobile/Info.plist, apps/ledger-live-mobile/ios/th.lproj/InfoPlist.strings
- ...
Update languages on the Appstore : [Doc](https://ledgerhq.atlassian.net/wiki/spaces/LLI/pages/5685805206/LL+APP+STORE+-+ADDING+A+NEW+LANGUAGE)
- add Thai
- remove Arabic
- **JIRA or GitHub link**: [LIVE-17874] 
--- …
=> feat: Update languages on the Appstore (Thai)

libs/coin-modules/coin-aptos/src/__tests__/api/index.test.ts, libs/coin-modules/coin-aptos/src/api/graphql/queries.ts, libs/coin-modules/coin-aptos/src/api/graphql/types.ts, libs/coin-modules/coin-aptos/src/api/index.ts
- ...
We used deprecated `address_version_from_move_resources` calls to Aptos indexer that we need to replace with `account_transactions` 
- **JIRA or GitHub link**: [LIVE-17035](https://ledgerhq.atlassian.net/browse/LIVE-17035)
--- …
=> Replace deprecated endpoints

.changeset/dry-drinks-end.md, apps/ledger-live-mobile/src/screens/Nft/NftCollection/__tests__/useNftCollection.test.ts, apps/ledger-live-mobile/src/screens/Nft/NftCollection/index.tsx, apps/ledger-live-mobile/src/screens/Nft/NftCollection/useNftCollection.ts
- ...
Display Collection for Solana Account
- rework to have a hook and some tests
- check if Send button is hidden (when Solana) and visible (when EVM)
https://github.com/user-attachments/assets/7614f174-fb3a-48bb-ac14-e26509ffb72a
- **JIRA or GitHub link**: [LIVE-17571] 
--- …
=> feat: Display Collection for Solana Account

.changeset/friendly-swans-wonder.md, apps/ledger-live-desktop/src/newArch/features/Collectibles/Nfts/screens/Gallery/index.tsx
- ...
Simpy disable send NFT feature for solana.
https://ledgerhq.atlassian.net/browse/LIVE-17555
---
=> feat: hide nft send cta for solana

.changeset/loud-socks-grow.md, apps/ledger-live-mobile/src/screens/Nft/WalletNftGallery/index.tsx
- ...
Wallet NFT Gallery Display for Solana NFTs
- **JIRA or GitHub link**: [LIVE-17606] 
---
[LIVE-17606]: https://ledgerhq.atlassian.net/browse/LIVE-17606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZj …
=> feat: Wallet NFT Gallery Display for Solana NFTs

.changeset/many-lies-trade.md, apps/ledger-live-mobile/src/components/Nft/NftLinksPanel.tsx, apps/ledger-live-mobile/src/components/Nft/NftViewer.tsx
- ...
NFT Details for Solana NFT
- send 
- Hide
- CUstom Screen
are hidden
- **JIRA or GitHub link**: [LIVE-17572] 
---
[LIVE-17572]: https://ledgerhq.atlassian.net/browse/LIVE-17572?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …
=> feat: NFT Details for Solana NFT

.changeset/strange-rivers-dress.md, apps/ledger-live-desktop/src/renderer/drawers/NFTViewerDrawer/index.tsx, apps/ledger-live-mobile/src/components/Nft/NftGallery/NftListItemFloorPriceRow.tsx, apps/ledger-live-mobile/src/components/Nft/NftViewer.tsx, libs/live-nft/src/api/metadataservice.ts
- ...
usage of useFloorPrice hook instead of getFloorPrice to have a fully supported cache and loading mechanism
improve floorPrice to fetch Solana
---
=> feat: Rework getFloorPrice usage in LL and add support for Solana

.changeset/slimy-humans-brush.md, libs/coin-modules/coin-evm/src/__tests__/coin-tester/scenarii/ethereum.ts
- ...
Anvil needs to fork the Blockchain to create a snapshot. This is not possible anymore with the ANKR node, since it does require an authentication that we prefer avoinding.
---
=> fic(coin-evm): update Ethereum node URL in coin tester

.github/workflows/test-ui-e2e-only-desktop.yml, apps/ledger-live-desktop/tests/page/account.page.ts, apps/ledger-live-desktop/tests/specs/speculos/subAccount.spec.ts, libs/ledger-live-common/src/e2e/enum/Account.ts, libs/ledger-live-common/src/e2e/speculos.ts, libs/speculos-transport/src/index.ts
- ...
Adding 3 E2E tests:
- [B2CQA-3055](https://ledgerhq.atlassian.net/browse/B2CQA-3055)
- [B2CQA-3057](https://ledgerhq.atlassian.net/browse/B2CQA-3057)
- [B2CQA-3058](https://ledgerhq.atlassian.net/browse/B2CQA-3058)
Updating Speculos image to target Master on the CI
- **JIRA or GitHub link**: [QAA-479](https://ledgerhq.atlassian.net/browse/QAA-479)
- [Run](https://github.com/LedgerHQ/ledger-live/actions/runs/14040700739)
---
- **The PR has been tested** thoroughly, and any potential edge cases …
=> [QAA] Adding SPL tokens test

.changeset/angry-roses-allow.md, apps/ledger-live-desktop/src/renderer/modals/SignMessage/Components/CopyButton.test.tsx, apps/ledger-live-desktop/src/renderer/modals/SignMessage/Components/CopyButton.tsx, apps/ledger-live-desktop/src/renderer/modals/SignMessage/steps/CopyButton.tsx, apps/ledger-live-desktop/src/renderer/modals/SignMessage/steps/StepSummary.tsx
feat: Add Copy/Paste input to EIP712 Signature
- ...
feat: Add Copy/Paste input to EIP712 Signature
- **JIRA or GitHub link**: [LIVE-5584]
https://github.com/user-attachments/assets/1b00332a-1c02-46d5-87fd-6feb32c1baf2
--- …
=> feat: Add Copy/Paste input to EIP712 Signature

.changeset/silver-shoes-hug.md, apps/ledger-live-mobile/src/components/GraphCard.tsx, apps/ledger-live-mobile/src/screens/Portfolio/GraphCardContainer.tsx
Add analytics on  portfolio graph click. Originally the ticket mentioned an issue about glitchy usage of the graph but I was not able to reproduce with different set of data (confirmed by @cgrellard-ledger). Will investigate further on that subject to found the cause that fixed the issue.
- **JIRA or GitHub link**: [LIVE-16805](https://ledgerhq.atlassian.net/browse/LIVE-16805)
---
- **Any new …
=> fix(llm): add click analytics on portfolio graph

.changeset/few-worms-impress.md, apps/ledger-live-desktop/src/newArch/features/LedgerSyncEntryPoints/components/ManagerEntryPoint/index.tsx
- LS Entry point banner
Automatically go to the line on LS Entry Point banner
Checked by design ✅ 
|![image](https://github.com/user-attachments/assets/76d07de9-bbb6-4085-a49b-2e073f2518e4)|![image](https://github.com/user-attachments/assets/9ea29c67-e334-4375-bf11-314a19252b97)|
https://github.com/user-attachments/assets/a843c279-eb1b-458c-b7ae-a9398c911eae
- **JIRA or GitHub link**: [LIVE-17926](https://ledgerhq.atlassian.net/browse/LIVE-17926)
--- …
=> :bug: (lld) LS entry point overflow

.changeset/curvy-bugs-tickle.md, libs/coin-framework/src/api/types.ts
- No Impact
Alpaca Transaction intent update for memo, tag etc. support
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/LIVE-17858
---
=> feature: Alpaca Transaction intent update for memo, tag etc. support

libs/speculos-transport/src/index.ts
=> fix: update speculos command

.changeset/young-coats-accept.md, libs/live-nft-react/src/hooks/__tests__/useNftGalleryFilter.test.tsx, libs/live-nft-react/src/hooks/helpers/__tests__/helper.test.ts, libs/live-nft-react/src/hooks/helpers/index.ts, libs/live-nft-react/src/hooks/useNftGalleryFilter.ts
- ...
Solana tokenId were equal to null => nothing was returned from SimpleHash so meaning nothing was displayed
- null/undefined is replaced with 0
---
=> bugfix: tokenId === null on galleryFilter to support Solana

apps/cli/scripts/build.mjs, apps/cli/scripts/gen.mjs, apps/cli/scripts/test.mjs, apps/ledger-live-desktop/scripts/ci-lint.mjs, apps/ledger-live-desktop/scripts/replace-assets.mjs, apps/ledger-live-desktop/scripts/sync-families-dispatch.mjs, apps/ledger-live-mobile/scripts/download-hermes-profile.mjs, apps/ledger-live-mobile/scripts/e2e-ci.mjs, apps/ledger-live-mobile/scripts/gen-metafile.mjs, apps/ledger-live-mobile/scripts/post.mjs, apps/ledger-live-mobile/scripts/replace-assets.mjs, apps/ledger-live-mobile/scripts/sync-families-dispatch.mjs, libs/ledger-live-common/scripts/build-ts.mjs, libs/ledger-live-common/scripts/sync-families-dispatch.mjs, libs/ledger-live-common/scripts/watch-ts-es.mjs, libs/ledger-live-common/scripts/watch-ts.mjs, package.json, pnpm-lock.yaml
Setup usePowerShell on windows with zx 8 instead of bash to support development using powershell
On windows bash is not always guaranteed to be present or available with node
If you use wsl the bash command will use wsl and you will not be on the same platform (linux vs win32)
--- …
=> chore: setup usePowerShell on windows with zx 8 instead of bash

apps/ledger-live-desktop/src/renderer/components/TabBar.tsx, apps/ledger-live-desktop/src/renderer/drawers/SwapOperationDetails/index.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/History/History.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/History/OperationRow.tsx, apps/ledger-live-desktop/tests/fixtures/common.ts, apps/ledger-live-desktop/tests/page/drawer/operation.drawer.ts, apps/ledger-live-desktop/tests/page/drawer/swap.confirmation.drawer.ts, apps/ledger-live-desktop/tests/page/swap.page.ts, apps/ledger-live-desktop/tests/specs/speculos/swap.spec.ts, apps/ledger-live-desktop/tests/utils/fileUtils.ts, libs/speculos-transport/src/index.ts
- ...
Adding 2 e2e test for swap:
- B2CQA-604: User can export all history operations
- B2CQA-602: User should be able to see their swap history from the swap history page 
- **JIRA or GitHub link**: [QAA-256](https://ledgerhq.atlassian.net/browse/QAA-256)
- [ruun](https://github.com/LedgerHQ/ledger-live/actions/runs/14032422929)
--- …
=> [QAA] Adding e2e test for swap history coverage

.changeset/eight-sloths-drum.md, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/locales/en/common.json
- Receive token banner
Typo update
Display "a/an" so we don't have to have a specific check to choose between a or an
On LLM it's only on the old add account so I just made the change to be iso
Changes ✅ By loca team and product team
- **JIRA or GitHub link**: [LIVE-17880](https://ledgerhq.atlassian.net/browse/LIVE-17880)
---
- …
=> :pencil2: (llm/lld) Receive token banner typo update

libs/coin-modules/coin-tron/src/logic/utils.ts
=> [COIN-TRON] Add some comments for Contract deserialization

apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/locales/en/common.json, libs/coin-modules/coin-aptos/src/__tests__/bridge/getFeesForTransaction.test.ts, libs/coin-modules/coin-aptos/src/__tests__/bridge/getTransactionStatus.test.ts, libs/coin-modules/coin-aptos/src/bridge/getFeesForTransaction.ts, libs/coin-modules/coin-aptos/src/bridge/getTransactionStatus.ts, libs/ledgerjs/packages/errors/src/index.ts
- ...
For token transaction when there is insufficient balance for paying fees, no validation error were shown to user. 
- **JIRA or GitHub link**: [LIVE-17961](https://ledgerhq.atlassian.net/browse/LIVE-17961)
--- …
=> Fix insufficient fee balance

.changeset/tame-hairs-rhyme.md, apps/ledger-live-mobile/src/components/ConfirmationModal.tsx, apps/ledger-live-mobile/src/components/NavigationHeaderCloseButton.tsx, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/components/CloseWithConfirmation/index.tsx
- ...
Full conversation [here](https://ledger.slack.com/archives/C02PQA777EU/p1742911451629439)
|         ![image](https://github.com/user-attachments/assets/a2b222dd-9987-498b-9e50-9cf55627943f) |         ![image](https://github.com/user-attachments/assets/3b9fc006-2bf3-49ad-893d-93a0e9e9ce7d)
https://ledgerhq.atlassian.net/browse/LIVE-17935
--- …
=> style: 🎨 edit add account confirmation dialog

.changeset/metal-camels-explode.md, apps/ledger-live-mobile/src/components/Nft/NftLinksPanel.tsx, apps/ledger-live-mobile/src/components/Nft/NftViewer.tsx
- ...
Hide Solana collection + check Custom lockScreen
https://github.com/user-attachments/assets/1b19a5d8-34e5-4c92-85bf-b8897eb1e59a
https://github.com/user-attachments/assets/6431e77d-85e1-4585-af27-07c5297e2e6c
- **JIRA or GitHub link**: [LIVE-17598] 
--- …
=> feat: custom lock screen + Hide collection solana

.changeset/wicked-planes-flash.md, libs/env/src/env.ts
- ...
- Support for Solana in NFT_CURRENCIES env variable. 
- It's useful for the use of `isNFTActive` helper and also in `NFTGallerySelector` for `SUPPORTED_NFT_CURRENCIES`
https://ledgerhq.atlassian.net/browse/LIVE-17551
--- …
=> feat: add 'solana' support as an nft currency

apps/ledger-live-mobile/__tests__/test-renderer.tsx
- ...
Refactor test-renderer to be more generic  
---
=> chore: Refactor test-renderer

.github/workflows/test-mobile-e2e-reusable.yml, apps/ledger-live-mobile/e2e/setup.ts, apps/ledger-live-mobile/scripts/e2e-ci.mjs
- Detox CI runs
- Improve allure and slack notif exports conditions
- Add field in workflow to specify test file to run
- Added test file name in allure reports to help QA determine which file to re-run
--- …
=> [LLM][Detox][CI] Improvement on LLM E2E tests CI

.changeset/shiny-lemons-speak.md
- CI builds resolved
Fix incorrect changeset https://github.com/LedgerHQ/ledger-live/blob/145001791397ffa7caad2a67c84e491bcede0051/.changeset/orange-turkeys-wait.md
(Back merge of commit on hotfix ae6341f17c41d5d40b9b6352e2ad0c8d4a81b73e)
back-merge
--- …
=> chore: ledger-live-mobile to live-mobile in changeset

.github/workflows/test-mobile-e2e-reusable.yml
- LLM E2E CI
_Changes broke Allure export on PR checks. Reverting to fix_
---
=> [QAA][CI] Revert problematic LLM E2E CI changes

apps/ledger-live-mobile/src/sentry.ts
- ...
As we are using only 1/6 of our Performance units quota on sentry we can increase the rates of profiles and traces sample. We need to do it progressively and check the impact since we can't really predict if we will have more users than usual.
There is no real risk on this since we have a max quota that we can't exceed only for performance (it's another one for the issues) 
x2 for profilesSampleRate
x1.5 for tracesSampleRate
this leads to a x3 increase in global transaction tracks
- **JIRA or GitHub link**: [LIVE-18082](https://ledgerhq.atlassian.net/browse/LIVE-18082)
---
- …
=> :chart_with_upwards_trend: (llm) adjust sentry performance report rates

apps/ledger-live-desktop/tests/page/account.page.ts, apps/ledger-live-desktop/tests/specs/speculos/ledgerSync.spec.ts, apps/ledger-live-desktop/tests/utils/ledgerSyncCliUtils.ts
- ...
Minor changes were made to the script to rename an account on LLD, then retrieve the data from the CLI and verify that the account has also been renamed in the CLI instance.
---
=> Rename account ledger sync

libs/coin-modules/coin-stellar/src/network/horizon.integ.test.ts
- ...
This [previous revert](https://github.com/LedgerHQ/ledger-live/pull/9708) did not include reverting integration tests, that are now failing.
---
=> fix (coin-stellar): repair stellar integration tests after revert

.changeset/beige-lies-attend.md, apps/ledger-live-mobile/src/components/RootNavigator/EarnLiveAppNavigator.tsx
- Click stake for a stablecoin like USDT account from earn live app
Token accounts included in selectable accounts from earn live app navigator in LLM.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-18068
--- …
=> fix: enable token account staking from earn live app

.changeset/big-mangos-argue.md, apps/ledger-live-desktop/src/newArch/features/LNSUpsell/components/LNSUpsellBanner/LNSUpsellBanner.test.tsx, apps/ledger-live-desktop/src/newArch/features/LNSUpsell/hooks/useLNSUpsellBannerState.ts, apps/ledger-live-desktop/src/renderer/actions/dynamicContent.ts, apps/ledger-live-desktop/src/renderer/hooks/useBraze.ts, apps/ledger-live-desktop/src/renderer/reducers/dynamicContent.ts
- ...
Look for a braze campaign with the key value `{ campaign: LNS_UPSELL_HIGH_TIER }` to exclude users from the hardcoded LNS upsell rather than their swap history.
- **JIRA or GitHub link**: [LIVE-17792]
--- …
=> fix(lld): 🎯 use braze to exclude from the hardcoded LNS upsell rather than the swap history

.changeset/pink-islands-sit.md, libs/coin-modules/coin-cosmos/src/config.ts
- ...
Polkachu nodes have been really unreliable, deprecating their v1 API and leaving us with breaking changes. They appear to be the only provider with such an update: let's simply search for alternatives.
--- …
=> conf (coin-cosmos): drop Polkachu for Cosmos nodes

.changeset/six-avocados-breathe.md, libs/coin-modules/coin-tezos/src/api/index.test.ts, libs/coin-modules/coin-tezos/src/api/index.ts, libs/coin-modules/coin-tezos/src/logic/estimateFees.ts
- ...
ensure error is finally thrown, or `0` is returned, silently eating the error
https://ledgerhq.atlassian.net/browse/BACK-8611
---
=> fix(BACK-8611): fix tezos fee estimation silently catching errors

.changeset/early-ears-drive.md, libs/coin-modules/coin-stellar/src/network/horizon.ts, libs/coin-modules/coin-tezos/src/logic/tezosToolkit.ts
- ...
This is preventing multiple instances with different settings (one for mainnet and one for testnet), required in alpaca.
https://ledgerhq.atlassian.net/browse/LIVE-17982
=> fix(LIVE-17982): fix stellar and tezos coin modules using static global variables

.changeset/quiet-poets-report.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/SignMessage/01-Summary.tsx, apps/ledger-live-mobile/src/screens/SignMessage/Components/CopyButton.test.tsx, apps/ledger-live-mobile/src/screens/SignMessage/Components/CopyButton.tsx
- ...
add copy button for signed message
- **JIRA or GitHub link**: [LIVE-5584]
---
https://github.com/user-attachments/assets/66340ce7-f962-4557-9e84-afa48a76e71f
[LIVE-5584]: …
=> feat: add copy button for signed message

.changeset/poor-lizards-juggle.md, libs/coin-modules/coin-tron/src/logic/craftTransaction.integ.test.ts, libs/coin-modules/coin-tron/src/logic/craftTransaction.test.ts, libs/coin-modules/coin-tron/src/logic/craftTransaction.ts, libs/coin-modules/coin-tron/src/network/index.ts, libs/coin-modules/coin-tron/src/types/bridge.ts
- ...
add support for `memo` and `expiration` craft parameters for tron coin module
- https://ledgerhq.atlassian.net/browse/LIVE-17984
---
=> feat(LIVE-17984): add support for `memo` and `expiration` craft parameters for tron coin module

.changeset/lucky-bananas-shave.md, apps/ledger-live-mobile/src/screens/Settings/General/AnalyticsRow.tsx
- ...
feat: LLM - Remove Enable Analytics and Disable Analytics event
- **JIRA or GitHub link**: [LIVE-11562]
---
[LIVE-11562]: https://ledgerhq.atlassian.net/browse/LIVE-11562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …
=> feat: LLM - Remove Enable Analytics and Disable Analytics event

.changeset/great-scissors-occur.md, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- ...
feat: feature flag for large mover landing page
- **JIRA or GitHub link**: [LIVE-18055]
---
[LIVE-18055]: https://ledgerhq.atlassian.net/browse/LIVE-18055?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …
=> feat: feature flag for large mover landing page

.changeset/wet-parrots-begin.md, apps/ledger-live-desktop/static/i18n/en/app.json
- ...
Updates LLD add memo copy. 
| ![image](https://github.com/user-attachments/assets/a6df6ba4-1d3a-4a29-9082-11d39453eea3) | ![image](https://github.com/user-attachments/assets/dbb85320-206a-46cc-b421-8fef6b6f9382) |
- **JIRA or GitHub link**: [LIVE-15564](https://ledgerhq.atlassian.net/browse/LIVE-15564)
---
- **Any new …
=> feat(LLD): memo tag copy update

apps/ledger-live-desktop/src/newArch/hooks/useStake.test.ts
=> chore: fix use stake test lld

apps/ledger-live-mobile/src/newArch/storage/asyncStorageWrapper/index.ts, apps/ledger-live-mobile/src/newArch/storage/index.ts, apps/ledger-live-mobile/src/newArch/storage/types.ts
Copy current global storage implementation to new architecture and wrap it into a common interface to be able to implement more storage engine and provide engine switch, migration / rollback, etc.
- **Parent PR**: https://github.com/LedgerHQ/ledger-live/pull/9831
- **JIRA**: https://ledgerhq.atlassian.net/browse/LIVE-18086
---
- …
=> chore(llm): move old StoreWrapper to new arch

.changeset/fluffy-poets-think.md, apps/ledger-live-mobile/src/components/RootNavigator/LandingPagesNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/SettingsNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/types/LandingPagesNavigator.ts, apps/ledger-live-mobile/src/components/RootNavigator/types/SettingsNavigator.ts, apps/ledger-live-mobile/src/const/navigation.ts, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/index.tsx, apps/ledger-live-mobile/src/screens/Settings/Debug/Features/index.tsx
- ...
Feat: large mover navigator
- **JIRA or GitHub link**: [LIVE-18098] [LIVE-18202]
---
[LIVE-18098]: https://ledgerhq.atlassian.net/browse/LIVE-18098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …
=> Feat: large mover navigator

.changeset/good-bulldogs-shave.md, apps/ledger-live-desktop/src/renderer/components/Onboarding/Screens/Welcome/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- ...
feat: LLD - Onboarding update CTA to buy a device
- **JIRA or GitHub link**: [LIVE-15565]
---
[LIVE-15565]: https://ledgerhq.atlassian.net/browse/LIVE-15565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …
=> feat: LLD - Onboarding update CTA to buy a device

.changeset/wild-flowers-swim.md, apps/ledger-live-desktop/src/renderer/components/SelectFeeStrategy.tsx, apps/ledger-live-desktop/src/renderer/families/bitcoin/FeesField.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- ...
feat: LLD - Update Fees Copy on Send screen step 2
- **JIRA or GitHub link**:[LIVE-13104] 
https://github.com/user-attachments/assets/939ea2a4-e3d0-4581-9d40-76cd57a79860
---
[LIVE-13104]: …
=> feat: LLD - Update Fees Copy on Send screen step 2

.changeset/slimy-pillows-approved.md, apps/ledger-live-mobile/src/components/RootNavigator/EarnLiveAppNavigator.tsx, apps/ledger-live-mobile/src/newArch/hooks/useStake/useStake.test.ts, apps/ledger-live-mobile/src/newArch/hooks/useStake/useStake.tsx, apps/ledger-live-mobile/src/screens/Account/hooks/useAccountActions.tsx
- ...
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-18157
--- …
=> fix: partner params stake redirects mobile

.changeset/smart-mice-cover.md, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/hooks/__tests__/useModularDrawerVisibility.test.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/hooks/useModularDrawerVisibility.ts, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- ...
Add Feature Flag for the new Asset Network Account selection and useModularDrawerVisibility to handle it
- **JIRA or GitHub link**: [LIVE-18120]
---
[LIVE-18120]: …
=> feat(LLD): Add ModularDrawer feature-flag & related hook

.changeset/tall-suits-sin.md, apps/ledger-live-mobile/src/components/CurrencyHeaderLayout.tsx
- The height of the header adapts better to different phone sizes
| Title        | Before        | After         |
| ------------- | ------------- | ------------- |
|Asset Top|![Screenshot 2025-04-08 at 18 12 21](https://github.com/user-attachments/assets/a9599df8-1b2b-4a05-acb3-d1995c4b9aad)|![Screenshot 2025-04-08 at 18 11 50](https://github.com/user-attachments/assets/6c5948f0-a6a9-4836-8ec2-1c6f392c1308)|
|Asset Scrolled|![Screenshot 2025-04-08 at 18 12 13](https://github.com/user-attachments/assets/54ebb994-9d44-4cb0-81b9-1dcc3e92083b)|![Screenshot 2025-04-08 at 18 11 56](https://github.com/user-attachments/assets/8810d482-00af-4f46-af98-b69a6b157d10)|
|Account Top|![Screenshot 2025-04-08 at 18 12 55](https://github.com/user-attachments/assets/bde80952-6b50-4083-bfe0-35fc75898050)|![S …
=> 🐛  LLM - Fix Account and Asset Header Height

.changeset/nasty-spies-brake.md, apps/ledger-live-mobile/ios/ledgerlivemobile/AppDelegate.mm
- ...
Cherry Pick of https://github.com/LedgerHQ/ledger-live/pull/9863
- **JIRA or GitHub link**: [LIVE-18153](https://ledgerhq.atlassian.net/browse/LIVE-18153)
---
[LIVE-18153]: …
=> :bug: (ios) firebase init duplication (#9863)

.changeset/perfect-bags-remain.md, libs/coin-modules/coin-cosmos/src/config.ts
- ...
Drop Polkachu for Cronos
---
=> conf(coin-cosmos): drop Polkachu for Cronos

.changeset/violet-monkeys-scream.md, apps/ledger-live-desktop/src/renderer/families/casper/MemoField.tsx, apps/ledger-live-desktop/src/renderer/families/solana/MemoValueField.tsx, apps/ledger-live-desktop/src/renderer/families/ton/CommentField.tsx, apps/ledger-live-desktop/src/renderer/modals/Receive/steps/StepReceiveFunds.tsx, apps/ledger-live-desktop/src/renderer/modals/Send/steps/Confirmation/NodeError/TechnicalErrorSection.tsx, apps/ledger-live-desktop/src/renderer/modals/Send/steps/StepRecipient.tsx, apps/ledger-live-desktop/src/renderer/modals/Send/steps/StepSummary.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Accounts/HiddenInscriptions/useHiddenInscriptionsModel.ts, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/WalletSync/Checker/index.tsx, apps/ledger-live-mobile/src/families/algorand/MemoTagSummary.tsx, apps/ledger-live-mobile/src/families/solana/Token2022/TokenExtensionsInfoBox.tsx, apps/ledger-live-mobile/src/families/solana/Token2022/TokenExtensionsInfoDrawer.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountQuickActionsDrawer/useAccountQuickActionDrawerViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountsListView/components/AccountItem/useAccountItemModel.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/components/StepFlow.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccountSuccess/useAddAccountSuccessViewModel.ts, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccountWarning/useAddAccountWarningViewModel.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useAddMember.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useDestroyTrustchain.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useOnTrustchainRefreshNeeded.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useQRCodeHost.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/useSyncWithQrCode.ts, apps/ledger-live-mobile/src/newArch/features/WalletSync/hooks/walletSync.hooks.ts, apps/ledger-live-mobile/src/screens/ImportAccounts/Scan.tsx, apps/ledger-live-mobile/src/screens/MyLedgerDevice/Modals/InstalledAppModal.tsx, apps/ledger-live-mobile/src/screens/Swap/LiveApp/hooks/useSyncAllAccounts.ts
- ...
Homogenisation of newArch imports to eliminate all imports of type  `~/newArch`
---
=> chore(LL): Homogenising newArch imports

.changeset/funny-tables-lay.md, libs/coin-modules/coin-evm/package.json, pnpm-lock.yaml
- ...
`coin-tester-evm` is now handling the coin tester for EVM.
---
=> refactor(coin-evm): remove dependency to `@ledgerhq/coin-tester`

.changeset/brave-jobs-marry.md, apps/ledger-live-mobile/src/analytics/segment.ts, apps/ledger-live-mobile/src/logic/getNotifPermissions.ts, apps/ledger-live-mobile/src/logic/notifications.tsx
- ...
Adds hasEnabledOsNotifications flag to analytics to reflect ledger live OS-level notification preferences
`https://api.segment.io/v1/b` payload:
| <img width="358" alt="image" src="https://github.com/user-attachments/assets/dfdb75b5-7db5-44ca-8465-493e68b849bb" /> |
| :--: |
| *before enabling* |
| <img width="293" alt="image" src="https://github.com/user-attachments/assets/8951e3fa-9c91-454f-abca-81e1dc9eb903" /> |
| :--: |
| *after enabling* |
- **JIRA or GitHub link**: [LIVE-17699](https://ledgerhq.atlassian.net/browse/LIVE-17699)
--- …
=> feat(LLM): add hasEnabledOsNotifications flag to analytics

.changeset/sweet-rules-crash.md, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/Components/Performance.tsx, libs/ui/packages/native/src/components/ProgressPoint/index.tsx, libs/ui/packages/native/src/components/index.ts, libs/ui/packages/native/storybook/stories/ProgressBar/ProgressBar.stories.tsx
- ...
Large Mover Performance Component
- **JIRA or GitHub link**: [LIVE-18141]
---
[LIVE-18141]: https://ledgerhq.atlassian.net/browse/LIVE-18141?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoi …
=> Feat: Large Mover Performance Component

.changeset/cuddly-guests-punch.md, libs/coin-modules/coin-xrp/src/api/index.test.ts, libs/coin-modules/coin-xrp/src/api/index.ts, libs/coin-modules/coin-xrp/src/logic/craftTransaction.ts, libs/coin-modules/coin-xrp/src/logic/index.ts
- ...
xrp coin module API: accept `memos` and `destinationTag` craft parameters
- https://ledgerhq.atlassian.net/browse/LIVE-18191
---
=> feat(LIVE-18191): xrp coin module API: accept `memos` and `destinationTag` craft parameters

.changeset/thick-ants-shave.md, libs/coin-modules/coin-module-boilerplate/src/config.ts, libs/coin-modules/coin-module-boilerplate/src/signer/getAddress.ts, libs/coin-modules/coin-module-boilerplate/src/types/signer.ts
- ...
Fix typos in `coin-module-boilerplate`
---
=> refactor(coin-module-boilerplate): fix typos in coin boilerplate

.changeset/small-teachers-chew.md, libs/coin-modules/coin-tezos/src/logic/listOperations.test.ts, libs/coin-modules/coin-tezos/src/logic/listOperations.ts
- ...
tezos coin module API: add `counter`, `gasLimit` and `storageLimit` to operation details
- https://ledgerhq.atlassian.net/browse/LIVE-17976
---
=> feat(LIVE-17976): tezos coin module API: add `counter`, `gasLimit` and `storageLimit` to operation details

.changeset/brown-days-draw.md, apps/ledger-live-mobile/src/newArch/storage/__tests__/asyncStorageWrapper.test.ts, apps/ledger-live-mobile/src/newArch/storage/asyncStorageWrapper/index.ts, apps/ledger-live-mobile/src/newArch/storage/index.ts, apps/ledger-live-mobile/src/newArch/storage/types.ts, apps/ledger-live-mobile/src/newArch/storage/utils/migrations/__tests__/asyncStorageToMMKV.test.ts, apps/ledger-live-mobile/src/newArch/storage/utils/migrations/asyncStorageToMMKV.ts, apps/ledger-live-mobile/src/newArch/storage/utils/migrations/constants.ts, apps/ledger-live-mobile/src/newArch/storage/utils/migrations/types.ts
Add migration logic to move from `AsyncStorage` to `MMKV` storage. It is still not triggered intentionally will be called in next PRs.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-18089
---
=> feat(llm): create storage migration script

apps/ledger-live-mobile/e2e/page/liveApps/swapLiveApp.ts, apps/ledger-live-mobile/e2e/page/speculos.page.ts, apps/ledger-live-mobile/e2e/specs/speculos/swap/swap.ts, e2e/desktop/tests/page/speculos.page.ts, e2e/desktop/tests/page/swap.page.ts, e2e/desktop/tests/specs/swap.spec.ts, e2e/desktop/tests/userdata/speculos-tests-app.json, libs/ledger-live-common/.unimportedrc.json, libs/ledger-live-common/src/e2e/enum/Currency.ts, libs/ledger-live-common/src/e2e/speculos.ts, libs/ledger-live-common/src/e2e/swap.ts
- ...
Using API to get minimum amount to swap:
- LLD
- LLM
- **JIRA or GitHub link**: [QAA-539](https://ledgerhq.atlassian.net/browse/QAA-539)
- **LLD**: [Run](https://github.com/LedgerHQ/ledger-live/actions/runs/14442819409)
- **LLM**: [Run](https://github.com/LedgerHQ/ledger-live/actions/runs/14442118855)
--- …
=> [QAA] Adding method to get amount to swap

libs/coin-modules/coin-mina/jest.integ.config.js, libs/coin-modules/coin-mina/src/api/index.integ.test.ts, libs/coin-modules/coin-sui/jest.integ.config.js, libs/coin-modules/coin-sui/src/network/sdk.integration.test.ts, libs/coin-modules/coin-sui/src/network/sdk.test.ts
- ...
Add default timeout to mina and sui integ tests
Move network calls to integration.tests so they aren't required
---
=> add default timeout mina & sui integ

apps/ledger-live-mobile/e2e/page/liveApps/swapLiveApp.ts, apps/ledger-live-mobile/e2e/specs/speculos/swap/swap.ts, e2e/desktop/tests/page/swap.page.ts, e2e/desktop/tests/specs/swap.spec.ts
=> [QAA] fixing method to get amount to swap - LLM LLD

.changeset/twelve-hats-accept.md, apps/ledger-live-desktop/src/renderer/screens/manager/index.tsx, libs/ledger-live-common/src/hw/attemptToQuitApp.ts
- ...
Remove unexpected page when returning to manager page.
---
=> [LIVE-18179] `Something went wrong` error briefly appears when reopening My Ledger while device app is open

.changeset/slow-parents-cough.md, apps/ledger-live-desktop/src/renderer/analytics/segment.ts, apps/ledger-live-mobile/src/analytics/segment.ts
- Only data analytics improvement
per token data was unergonomic for analysis
---
=> chore: analytics for staking tokens log a list instead of booleans

.changeset/short-rats-suffer.md, apps/ledger-live-mobile/src/newArch/storage/__tests__/asyncStorageWrapper.test.ts, apps/ledger-live-mobile/src/newArch/storage/__tests__/mmkvStorageWrapper.test.ts, apps/ledger-live-mobile/src/newArch/storage/__tests__/storage.test.ts, apps/ledger-live-mobile/src/newArch/storage/asyncStorageWrapper/index.ts, apps/ledger-live-mobile/src/newArch/storage/constants.ts, apps/ledger-live-mobile/src/newArch/storage/index.ts, apps/ledger-live-mobile/src/newArch/storage/mmkvStorageWrapper/index.ts, apps/ledger-live-mobile/src/newArch/storage/types.ts, apps/ledger-live-mobile/src/newArch/storage/utils/migrations/__tests__/asyncStorageToMMKV.test.ts, apps/ledger-live-mobile/src/newArch/storage/utils/migrations/__tests__/migrator.test.ts, apps/ledger-live-mobile/src/newArch/storage/utils/migrations/asyncStorageToMMKV.ts, apps/ledger-live-mobile/src/newArch/storage/utils/migrations/constants.ts, apps/ledger-live-mobile/src/newArch/storage/utils/migrations/types.ts, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- mmkv and async storage (not used so no impact)
Add rollback and reset scripts for MMKV migration 
How does it works : 
- We rollback the migration if an error is catched during migration
- We rollback if there is more than 5 errors on `get` method (that's the only one that could break since there is a parsing so no need to catch other issues + mmkv-react-native doesn't throw any error)
- We rollback if we ask it explicitly inside the feature flag
- `Reset` method will be only used to debug from the debug settings
For the tests I've separated in two files. Inside migrator.test.ts we will test each method one by one without any context.
Inside asyncStorageToMMKV.test.ts we will test a more global logic
- **JIRA or GitHub link**: [LIVE-18143](https://ledgerhq.atlassian.net/browse/LIVE-18143 …
=> :zap: (llm) MMKV - reset and rollback script

apps/ledger-live-mobile/e2e/page/accounts/account.page.ts, apps/ledger-live-mobile/e2e/specs/speculos/account/accountRename.spec.ts, apps/ledger-live-mobile/src/screens/AccountSettings/AccountNameRow.tsx, apps/ledger-live-mobile/src/screens/AccountSettings/EditAccountName.tsx
- Added a Detox test
_Account renaming persistance test. Skipped until fix of [LIVE-17458](https://ledgerhq.atlassian.net/browse/LIVE-17458)_
[LLM Speculos run](https://github.com/LedgerHQ/ledger-live/actions/runs/14475480189)
--- …
=> [QAA-550][Speculos][LLM] Account renaming persistance test.

.changeset/chilly-lizards-obey.md, apps/ledger-live-desktop/__mocks__/@ledgerhq/device-transport-kit-web-hid.js, apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx, apps/ledger-live-desktop/tests/jestSetup.js, libs/live-dmk-desktop/src/errors.test.ts, libs/live-dmk-desktop/src/errors.ts, libs/live-dmk-desktop/src/index.ts
- ...
Patched WebHidSendReportError error when LDMK transport is enabled
- **JIRA or GitHub link**: [LIVE-18413](https://ledgerhq.atlassian.net/browse/LIVE-18413)
---
[LIVE-18413]: …
=> chore(LLD): patch WebHidSendReportError with LDMK enabled

.changeset/quiet-snails-applaud.md, apps/ledger-live-mobile/src/analytics/hooks/useTrackTransactionChecksFlow.test.ts, apps/ledger-live-mobile/src/analytics/hooks/useTrackTransactionChecksFlow.ts, apps/ledger-live-mobile/src/components/DeviceAction/index.tsx
- ...
Add llm analytics for opt-in for transaction checks
- **JIRA or GitHub link**:  [LIVE-17933]
---
[LIVE-17933]: https://ledgerhq.atlassian.net/browse/LIVE-17933?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhY …
=> 📈 (dmk) [LIVE-17933]: Add llm analytics for opt-in for transaction checks

.changeset/nine-weeks-do.md, apps/ledger-live-mobile/src/components/RootNavigator/SettingsNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/types/SettingsNavigator.ts, apps/ledger-live-mobile/src/const/navigation.ts, apps/ledger-live-mobile/src/newArch/storage/__tests__/asyncStorageWrapper.test.ts, apps/ledger-live-mobile/src/newArch/storage/__tests__/mmkvStorageWrapper.test.ts, apps/ledger-live-mobile/src/newArch/storage/__tests__/storage.test.ts, apps/ledger-live-mobile/src/newArch/storage/asyncStorageWrapper/index.ts, apps/ledger-live-mobile/src/newArch/storage/index.ts, apps/ledger-live-mobile/src/newArch/storage/mmkvStorageWrapper/index.ts, apps/ledger-live-mobile/src/newArch/storage/types.ts, apps/ledger-live-mobile/src/screens/Settings/Debug/Debugging/StorageMigration.tsx, apps/ledger-live-mobile/src/screens/Settings/Debug/Debugging/index.tsx
Add debug tools for migration testing
https://github.com/user-attachments/assets/a50a8e0b-c31c-4599-81b3-212198b2308a
- https://ledgerhq.atlassian.net/browse/LIVE-18144
- https://ledgerhq.atlassian.net/browse/LIVE-18145
--- …
=> feat(llm): impl debug tools for storage migration

apps/ledger-live-mobile/e2e/page/liveApps/swapLiveApp.ts, apps/ledger-live-mobile/e2e/specs/speculos/swap/swap.ts, e2e/desktop/tests/page/swap.page.ts, e2e/desktop/tests/specs/swap.spec.ts
=> fix: 🩹 updating method to get amount to swap - LLM LLD

libs/coin-modules/coin-xrp/src/api/index.ts, libs/coin-modules/coin-xrp/src/logic/craftTransaction.ts
- ...
regression from #9904, causing the tx crafted with an actual empty memo array in `Memos` field, instead of just omitted
-  ledgerhq.atlassian.net/browse/LIVE-18191
---
=> fix(LIVE-18191): xrp coin module: fix empty memo array passed instead of `undefined`

apps/ledger-live-mobile/__tests__/jest-setup.js, apps/ledger-live-mobile/src/analytics/hooks/useTrackAddAccountFlow.test.ts, apps/ledger-live-mobile/src/analytics/hooks/useTrackLedgerSyncFlow.test.ts, apps/ledger-live-mobile/src/analytics/hooks/useTrackMyLedgerEvents.test.ts, apps/ledger-live-mobile/src/analytics/hooks/useTrackOnboardingFlow.test.ts, apps/ledger-live-mobile/src/analytics/hooks/useTrackReceiveFlow.test.ts, apps/ledger-live-mobile/src/analytics/hooks/useTrackSendFlow.test.ts, apps/ledger-live-mobile/src/analytics/hooks/useTrackSwapFlow.test.ts, apps/ledger-live-mobile/src/analytics/hooks/useTrackTransactionChecksFlow.test.ts
- ...
Just mock all segment methods that we use for analytics instead of doing it manually. This is blocking for mmkv analytics as it would need to mock analytics on every tests in the code base => [feat/LIVE-18091](https://github.com/LedgerHQ/ledger-live/pull/9972)
--- …
=> 🔧 (llm) mock segment methods for jest

.changeset/shaggy-drinks-cry.md, apps/ledger-live-desktop/src/renderer/analytics/segment.ts, apps/ledger-live-mobile/src/analytics/segment.ts
- New track in LLM
- Updated value in LLD. Already commented to analytics.
In mixpanel, we don't have event of the feature flag on LLM -> therefore we have a tracking issue
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-18490
--- …
=> fix: fix ptxCard tracks

.changeset/many-jobs-tie.md, libs/coin-modules/coin-tezos/src/logic/listOperations.test.ts, libs/coin-modules/coin-tezos/src/logic/listOperations.ts, libs/coin-modules/coin-tezos/src/network/types.ts
- ...
`listOperations` filter also "reveal" operations and returns them.
- **JIRA or GitHub link**: [LIVE-17978]
---
[LIVE-17978]: https://ledgerhq.atlassian.net/browse/LIVE-17978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …
=> [COIN-XTZ] listOperations returns reveal operation

.changeset/short-ravens-explode.md, libs/live-dmk-mobile/src/hooks/useBleDevicePairing.ts
- ...
disable refresher on ble hook
- **JIRA or GitHub link**: [DSDK-743]
---
[DSDK-743]: https://ledgerhq.atlassian.net/browse/DSDK-743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLW …
=> 🐛 (dmk): disable refresher on ble hook

libs/coin-modules/coin-cosmos/src/synchronisation.integ.test.ts
- integ test
Skip inj test as history is partial
---
=> skip IN inj test sync

libs/coin-modules/coin-celo/jest.config.js, libs/coin-modules/coin-celo/package.json, pnpm-lock.yaml
- coin-celo
fix test-integ command
disable network calls on unit tests
---
=> celo test setup

apps/ledger-live-mobile/e2e/bridge/client.ts, apps/ledger-live-mobile/e2e/bridge/server.ts, apps/ledger-live-mobile/e2e/bridge/types.ts, apps/ledger-live-mobile/e2e/specs/speculos/swap/swap.ts, apps/ledger-live-mobile/src/screens/Swap/LiveApp/customHandlers/index.ts
- Speculos Swap test
_Fixing LLM Speculos Swap test by setting env var after Live app is open and waiting for it to be ready_
- Swap test [run](https://github.com/LedgerHQ/ledger-live/actions/runs/14534386538)
---
=> [Detox] Adding LLM swap live app isReady

.changeset/old-snails-sell.md, .github/workflows/test-coin-tester.yml, tools/actions/composites/run-coin-tester/action.yml, tools/actions/composites/setup-coin-tester-env/action.yml
- ...
Workflow that runs the Coin Tester on every pull request that modifies coin families or modules.
It is also executed daily and can be triggered manually.
- **JIRA or GitHub link**: [LIVE-18207](https://ledgerhq.atlassian.net/browse/LIVE-18207)
--- …
=> fix: test new github action with fake SEED

.github/workflows/test-coin-tester.yml
=> fix: manuelle run fixed

.changeset/modern-papayas-impress.md, apps/ledger-live-mobile/src/newArch/storage/index.ts, apps/ledger-live-mobile/src/newArch/storage/types.ts, apps/ledger-live-mobile/src/screens/Settings/Debug/Debugging/StorageMigration.tsx
- analytics
Add analytics event for each error triggered so we can monitor them. 
Add a button to manually trigger the error in the debug
If there is more than 5 errors triggered it will rollback 
[dashboard](https://mixpanel.com/project/1875669/view/3222519/app/boards#id=9697100)
https://github.com/user-attachments/assets/02d11d03-a481-4012-9910-2d847a4545a4
- **JIRA or GitHub link**: [LIVE-18471](https://ledgerhq.atlassian.net/browse/LIVE-18471)
---
- **The PR has been tested** thoroughly, and …
=> llm-mmkv: add analytics and debug error

.changeset/shaggy-knives-judge.md, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/Components/Footer.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/Components/__tests__/Footer.test.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/Components/__tests__/LargeMoverGraph.test.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/hooks/useFooterQuickAction.tsx, libs/ui/packages/native/src/components/cta/QuickAction/QuickActionButton/index.tsx, libs/ui/packages/native/src/components/cta/QuickAction/QuickActionList/index.tsx
- ...
feat: Large Mover Footer Component
- **JIRA or GitHub link**: [LIVE-18108]
---
[LIVE-18108]: https://ledgerhq.atlassian.net/browse/LIVE-18108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …
=> feat: Large Mover Footer Component

libs/coin-modules/coin-solana/src/network/chain/web3.integ.test.ts
- N/A
Add integration test to validate token account address retrieved from the blockchain.
---
=> [COIN-SOL] Add a simple integ test

.changeset/chilled-bikes-act.md, libs/ui/packages/react/src/pre-ldls/components/Search/Search.stories.tsx, libs/ui/packages/react/src/pre-ldls/components/Search/Search.tsx, libs/ui/packages/react/src/pre-ldls/components/index.ts, libs/ui/packages/react/src/pre-ldls/hooks/index.ts, libs/ui/packages/react/src/pre-ldls/hooks/useDebouncedCallback.stories.tsx, libs/ui/packages/react/src/pre-ldls/hooks/useDebouncedCallback.ts
- ...
Implement the new search component UI.
- **JIRA or GitHub link**: [LIVE-18121]
---
[LIVE-18121]: https://ledgerhq.atlassian.net/browse/LIVE-18121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …
=> feat(react:ui): 🔎 implement the new search component UI

CODEOWNERS
- CODEOWNERS
Update codeowners because there is no team for partners yet
---
=> update codeowners sui hedera

.github/workflows/test-coin-tester.yml
- ...
Fixes invalid matrix JSON formatting in the Coin Tester workflow. Replaces manual string construction with jq to ensure valid JSON for fromJson(...). This resolves strategy parsing errors and supports all triggers (PRs, schedule, manual).
- **JIRA or GitHub link**: LIVE-18548
--- …
=> Fix invalid matrix JSON in Coin Tester workflow

e2e/mobile/.eslintrc.js, e2e/mobile/babel.config.detox.js, e2e/mobile/bridge/client.ts, e2e/mobile/bridge/proxy.ts, e2e/mobile/bridge/server.ts, e2e/mobile/bridge/types.ts, e2e/mobile/helpers/commonHelpers.ts, e2e/mobile/helpers/elementHelpers.ts, e2e/mobile/jest.config.js, e2e/mobile/jest.environment.ts, e2e/mobile/jest.globalSetup.ts, e2e/mobile/jest.globalTeardown.ts, e2e/mobile/package.json, e2e/mobile/setup.ts, e2e/mobile/tsconfig.json, e2e/mobile/utils/cliUtils.ts, e2e/mobile/utils/runCli.ts, e2e/mobile/utils/speculosUtils.ts, e2e/mobile/xray.formater.sh, pnpm-lock.yaml, pnpm-workspace.yaml
- ...
New mobile e2e test folder
- Created e2e/mobile folder with dedicated package.json, tsconfig, and setup files
- Copied Detox env, helpers, bridge, and initial config from apps/ledger-live-mobile
- Added alias paths for shared access to app code
- No test files moved yet; this sets up structure for isolated E2E
--- …
=> Move mobile apps/ledger-live-mobile/e2e -> e2e/mobile (prepare new structure and config)

.changeset/orange-wolves-lie.md, libs/coin-framework/src/api/types.ts, libs/coin-modules/coin-module-boilerplate/src/api/index.ts, libs/coin-modules/coin-polkadot/src/api/index.ts, libs/coin-modules/coin-stellar/src/api/index.ts, libs/coin-modules/coin-tezos/src/api/index.integ.test.ts, libs/coin-modules/coin-tezos/src/api/index.test.ts, libs/coin-modules/coin-tezos/src/api/index.ts, libs/coin-modules/coin-tezos/src/api/types.ts, libs/coin-modules/coin-tezos/src/logic/craftTransaction.ts, libs/coin-modules/coin-tezos/src/logic/getBalance.test.ts, libs/coin-modules/coin-tezos/src/logic/getBalance.ts, libs/coin-modules/coin-tezos/src/logic/listOperations.ts, libs/coin-modules/coin-tezos/src/types/assets.ts, libs/coin-modules/coin-tezos/src/types/index.ts, libs/coin-modules/coin-tron/src/api/index.test.ts, libs/coin-modules/coin-tron/src/api/index.ts, libs/coin-modules/coin-xrp/src/api/index.integ.test.ts, libs/coin-modules/coin-xrp/src/api/index.ts
- CoinFmk estimateFees signature
- CoinFmk craftTransaction signature
Change Alpace `estimateFees` and `craftTransaction` signature.
- **JIRA or GitHub link**: [LIVE-17977]
---
[LIVE-17977]: …
=> [COIN-XTZ] Change estimate fees signature

apps/ledger-live-mobile/e2e/page/liveApps/swapLiveApp.ts, e2e/desktop/tests/page/swap.page.ts, e2e/desktop/tests/specs/swap.spec.ts, libs/ledger-live-common/src/e2e/models/Swap.ts, libs/ledger-live-common/src/e2e/swap.ts
- ...
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/QAA-547 
Desktop CI: https://github.com/LedgerHQ/ledger-live/actions/runs/14638477268/job/41076649772
Mobile CI: https://github.com/LedgerHQ/ledger-live/actions/runs/14638484748/job/41075046405
---
- …
=> [QAA] adding e2e swap test + refacto swap tests

.changeset/chilled-dryers-train.md, libs/coin-modules/coin-evm/src/__tests__/unit/api/explorer/ledger.unit.test.ts, libs/coin-modules/coin-evm/src/api/explorer/ledger.ts, libs/coin-modules/coin-evm/src/config.ts
- ...
This makes `batchSize` configurable in Firebase for Leger EVM explorers
---
=> fix(coin-evm): make batch size configurable for Ledger explorer

apps/ledger-live-mobile/e2e/page/settings/ledgerSync.page.ts, apps/ledger-live-mobile/e2e/specs/speculos/ledgerSync/ledgerSync.spec.ts
- Detox Ledger Sync test
_Disabling detox synchronisation before entering ledger sync settings to prevent flakiness_
- [Test Mobile Speculos](https://github.com/LedgerHQ/ledger-live/actions/runs/14664325230)
- [LIVE-15405](https://ledgerhq.atlassian.net/browse/LIVE-15405)
--- …
=> [QAA[Detox Fix ledger sync

e2e/desktop/tests/page/swap.page.ts
- ...
The issue is that the contract address in your assertion is in mixed case, while the one in the URL has been lowercased.
- Extracted common logic for URL assertions into a reusable method
- Applies to both 1inch and Paraswap provider checks in `verifyProviderURL`
- Adds clearer error messaging when expected URL parts are missing
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/QAA-566
--- …
=> Fix provider redirection url check

e2e/desktop/tests/page/swap.page.ts, e2e/desktop/tests/specs/swap.spec.ts
- ...
Adding a method to select a provider that need KYC
---
=> [QAA] fixing swap e2e test

.changeset/moody-games-fix.md, libs/ui/packages/react/package.json, libs/ui/packages/react/src/pre-ldls/components/AssetItem/AssetItem.stories.tsx, libs/ui/packages/react/src/pre-ldls/components/AssetItem/AssetItem.tsx, libs/ui/packages/react/src/pre-ldls/components/AssetList/AssetList.stories.tsx, libs/ui/packages/react/src/pre-ldls/components/AssetList/AssetList.tsx, libs/ui/packages/react/src/pre-ldls/components/VirtualList/VirtualList.stories.tsx, libs/ui/packages/react/src/pre-ldls/components/VirtualList/VirtualList.tsx, libs/ui/packages/react/src/pre-ldls/components/index.ts, libs/ui/packages/react/src/pre-ldls/libs/index.ts, pnpm-lock.yaml
- ...
Adds the AssetList component and its constituent AssetItem and VirtualList components 
- **JIRA or GitHub link**: [LIVE-18122](https://ledgerhq.atlassian.net/browse/LIVE-18122)
---
[LIVE-18122]: …
=> feat(LLD): asset type list component

.changeset/fuzzy-dolls-grab.md, apps/ledger-live-mobile/src/screens/Platform/v2/Catalog/Search/SearchBar.tsx
- LLM Discover search
Disable discover search bar auto correct
| <video src="https://github.com/user-attachments/assets/5e7bef8b-39e8-488e-8d81-6ced37150d2b" /> | <video src="https://github.com/user-attachments/assets/af7c86a8-b34a-4e1f-ab28-b26b2b189efa" /> |
--- …
=> fix(LLM): discover search bar auto correct

.changeset/grumpy-actors-cross.md, apps/ledger-live-mobile/src/screens/SendFunds/02-SelectRecipient.tsx
- ...
Fix focus  when clicking on Add Memotag
https://github.com/user-attachments/assets/722099fb-b21e-42b0-ad37-20c4eee3e467
- **JIRA or GitHub link**: [LIVE-18513] 
---
[LIVE-18513]: …
=> bugfix(MemoTag): focus when clicking on Add Memotag

apps/ledger-live-desktop/src/renderer/drawers/DataSelector/AccountList.tsx, e2e/desktop/tests/component/drawer.component.ts, e2e/desktop/tests/fixtures/common.ts, e2e/desktop/tests/specs/swap.spec.ts, e2e/desktop/tests/userdata/1AccountDOT.json, e2e/desktop/tests/utils/speculosUtils.ts
- ...
Adding swap test:
- Account FROM not present in app.json
- Account TO not present in app.json
- Account FROM and TO not present in app.json
- **JIRA or GitHub link**: [QAA-491](https://ledgerhq.atlassian.net/browse/QAA-491)
--- …
=> [QAA] Swap a coin for which you have no account yet

.github/workflows/test-ui-e2e-only-desktop.yml, e2e/desktop/aggregate-xray-reports.sh
- ...
Fix xray integration
- **JIRA or GitHub link**: [qaa-556](https://ledgerhq.atlassian.net/browse/QAA-556)
---
=> [QAA] Fixing xray integration

.github/workflows/test-design-system-reusable.yml, .github/workflows/test-libs-reusable.yml, e2e/mobile/package.json
- ...
- Temp exclude mobile E2E tests from affected-libs test pipeline
---
=> Temp exclude mobile E2E tests from affected-libs test pipeline

.changeset/silver-crews-relate.md, apps/ledger-live-mobile/src/index.tsx, apps/ledger-live-mobile/src/newArch/storage/__tests__/storage.test.ts, apps/ledger-live-mobile/src/newArch/storage/index.ts, apps/ledger-live-mobile/src/newArch/storage/screens/PerformanceMonitor/index.tsx, apps/ledger-live-mobile/src/newArch/storage/utils/performance/index.ts, apps/ledger-live-mobile/src/newArch/utils/__tests__/captureExceptionWithExtraData.test.ts, apps/ledger-live-mobile/src/newArch/utils/__tests__/rejectWithError.test.ts, apps/ledger-live-mobile/src/newArch/utils/captureExceptionWithExtraData.ts, apps/ledger-live-mobile/src/newArch/utils/rejectWithError.ts, apps/ledger-live-mobile/src/screens/Settings/Debug/Debugging/StorageMigration.tsx, libs/env/src/env.ts
- debug tools
- migration error handling
- sentry util added and tested
An util for sentry has been added. It makes possible to add extra data to the exception sent to Sentry. It will be displayed as following :
This will allow us to have additional information on the error without sending the value to avoid to send sensible data
Video of the tool : 
https://github.com/user-attachments/assets/e9060c9f-ca62-4d61-a540-6ab03a128b09
It's the last PR regarding storage migration to MMKV. Basically we can monitor it with mixPanel and Sentry and check the benefits of the change with the debug tool 
- **JIRA or GitHub link**: [LIVE-18146](https://ledgerhq.atlassian.net/browse/LIVE-18146)
---
- **The PR …
=> :hammer: (llm-mmkv) performance overlay

.changeset/thick-coats-doubt.md, apps/ledger-live-desktop/src/newArch/features/MemoTag/constants.ts
- ...
Removes internet_computer from memo tag disclaimer list
| ![Kapture 2025-04-07 at 16 51 40](https://github.com/user-attachments/assets/906b62d3-4b79-42d7-95f1-fce9aa5be3e9) | ![Kapture 2025-04-07 at 16 50 19](https://github.com/user-attachments/assets/d81d10d2-f0b8-4597-89b0-271da796970e) |
- **JIRA or GitHub link**: [LIVE-17697](https://ledgerhq.atlassian.net/browse/LIVE-17697)
--- …
=> feat(LLD): skip memo tag disclaimer icp

.changeset/good-ghosts-laugh.md, libs/env/src/env.ts, libs/ledger-live-common/src/apps/config.ts, libs/ledgerjs/packages/cryptoassets/src/tokens.ts
- ...
Add environment variable to enable or disable aptos tokens
- **JIRA or GitHub link**: [LIVE-18565](https://ledgerhq.atlassian.net/browse/LIVE-18565)
---
[LIVE-18565]: …
=> Add token enable flag

e2e/desktop/tests/page/swap.page.ts
- ...
- Url was change for ONE_INCH
https://github.com/LedgerHQ/swap/pull/2867
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/QAA-595
---
=> [e2e][desktop] Fix add ledgerLive param in oneinch url

.changeset/slimy-ravens-joke.md, libs/ui/packages/react/package.json, libs/ui/packages/react/src/pre-ldls/components/VirtualList/VirtualList.stories.tsx, libs/ui/packages/react/src/pre-ldls/components/VirtualList/VirtualList.tsx, pnpm-lock.yaml
- virtual list
Replace the new virtual list component that was using react-window with a new one using tanstack/virtual as it's more recent (and more maintained) and has a better fit with tanstack/query
docs and examples [here](https://tanstack.com/virtual/latest/docs/framework/react/examples/infinite-scroll)
A fake paginated API has been done inside the story to see how it will work. 
- threshold => how many items before the end we should trigger fetchNextPage
- LoadingComponent should be a component to display during the loading of more items (ideally users won't see it) 
- isLoading will be useful to display the loader and is fitting great with tanStackQuery
- overscan => according to the doc `The number of items to render above and below the visible area. Increasing this number will …
=> :lipstick: (ui) handle virtualList pagination

.changeset/fifty-elephants-jog.md, libs/coin-modules/coin-xrp/src/api/index.integ.test.ts, libs/coin-modules/coin-xrp/src/api/index.test.ts, libs/coin-modules/coin-xrp/src/api/index.ts
- ...
Allow to pass signing pub key to craft in `api`
- https://ledgerhq.atlassian.net/browse/BACK-8789
---
=> chore(BACK-8789): [coin-modules][ripple] allow to pass signing pub key to craft

.changeset/ninety-pumpkins-remain.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/DeviceActions/FollowStepsOnDevice.tsx, apps/ledger-live-desktop/src/newArch/utils/getProductName.ts, apps/ledger-live-desktop/src/renderer/components/SignMessageConfirm/index.tsx, apps/ledger-live-desktop/src/renderer/modals/SignMessage/Body.tsx, apps/ledger-live-desktop/src/renderer/modals/SignMessage/steps/StepSummary.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/components/RootNavigator/SignMessageNavigator.tsx, apps/ledger-live-mobile/src/components/ValidateMessageOnDevice.tsx, apps/ledger-live-mobile/src/components/Web3AppWebview/PlatformAPIWebview.tsx, apps/ledger-live-mobile/src/components/Web3AppWebview/helpers.ts, apps/ledger-live-mobile/src/components/WebPlatformPlayer/CustomHandlers.ts, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/WalletSync/components/FollowInstructions/index.tsx, apps/ledger-live-mobile/src/newArch/utils/getProductName.ts
- ...
- **JIRA or GitHub link**: [LIVE-17939](https://ledgerhq.atlassian.net/browse/LIVE-17939)
--- …
=> feat: remove clear signing screen [LIVE-17939]

.github/workflows/bot-nonreg-nitrogen.yml
- ...
Add NEAR to the list of disabled currencies given that the error below kept happening multiple times:
`Error: speculos process failure. vnc_server: readall: connection closed`
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-10483
--- …
=> chore: add near to the list of disabled currencies

.changeset/many-feet-wonder.md, libs/ledger-live-common/src/exchange/swap/completeExchange.ts
=> feat: btc rbf swap

.changeset/breezy-dancers-sing.md, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/Web3AppWebview/AssetAndAccountDrawer.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/Web3AppWebview/__tests__/openAssetAndAccountDrawer.test.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/components/SelectAccountFlow.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/components/SelectAssetFlow.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/hooks/__tests__/useOpenAssetFlow.test.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/hooks/useOpenAssetFlow.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/index.ts, apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/LiveAppSDKLogic.ts, apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/PlatformAPIWebview.tsx, apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/WalletAPIWebview.tsx
- ...
Modular drawer - Integrate into LiveApps flows
https://github.com/user-attachments/assets/cc1b69c7-cbf2-4e66-995a-5b0702c3c1eb
-->
- **JIRA or GitHub link**: [LIVE-18237] 
---
[LIVE-18237]: …
=> feat(LLD): Modular drawer - Integrate into LiveApps flows

.github/workflows/test-coin-modules-integ.yml
- ...
Post on slack whenever coin modules integ tests fail / succeed
---
=> Update coin-integ workflow

.changeset/new-tools-shout.md, libs/coin-modules/coin-polkadot/src/api/index.integ.test.ts
- ...
Update integration test expecting result with the new returned struct.
---
=> [COIN-DOT]: Fix api integration test

.changeset/soft-bobcats-unite.md, apps/ledger-live-mobile/src/analytics/hooks/useTrackTransactionChecksFlow.test.ts, apps/ledger-live-mobile/src/analytics/hooks/useTrackTransactionChecksFlow.ts, apps/ledger-live-mobile/src/components/DeviceAction/index.tsx
- ...
Add tracking for transaction checks opt in result
- **JIRA or GitHub link**: [LIVE-17955]
---
[LIVE-17955]: https://ledgerhq.atlassian.net/browse/LIVE-17955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5 …
=> ✨ (llm): Add tracking for transaction checks opt in result

.changeset/healthy-cows-itch.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx
add the discreet mode parameter to the swap live app web view
- ...
--- …
=> fix(LIVE-18832): add discreet mode parameter back to swap web view

.changeset/weak-seas-deny.md, apps/ledger-live-mobile/src/components/Delta.tsx, apps/ledger-live-mobile/src/components/RootNavigator/types/LandingPagesNavigator.ts, apps/ledger-live-mobile/src/components/RootNavigator/types/SettingsNavigator.ts, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/components/Information/index.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/components/Performance.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/components/PriceAndVariation.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/components/__tests__/CardLargeMover.test.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/hooks/useInformations.ts, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/hooks/useLargeMover.ts, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/index.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/utils/index.tsx, apps/ledger-live-mobile/src/screens/Settings/Debug/Features/index.tsx, knip.json, libs/ledger-live-common/.unimportedrc.json, libs/ledger-live-common/src/market/hooks/useLargeMoverDataProvider.ts
- ...
Added useLargeMover to fetch data
- **JIRA or GitHub link**: [LIVE-18125]
https://github.com/user-attachments/assets/f9963764-089c-4345-b65a-26e4e0190e64
---
[LIVE-18125]: …
=> feat: added useLargeMover to fetch data

.changeset/four-rules-flow.md, libs/ui/packages/react/package.json, libs/ui/packages/react/src/pre-ldls/components/Address/Address.tsx, libs/ui/packages/react/src/pre-ldls/components/AssetItem/AssetItem.stories.tsx, libs/ui/packages/react/src/pre-ldls/components/AssetItem/AssetItem.tsx, libs/ui/packages/react/src/pre-ldls/components/AssetList/AssetList.stories.tsx, libs/ui/packages/react/src/pre-ldls/components/CryptoIcon/CryptoIcon.stories.tsx, libs/ui/packages/react/src/pre-ldls/components/CryptoIcon/CryptoIcon.tsx, libs/ui/packages/react/src/pre-ldls/components/NetworkItem/NetworkItem.stories.tsx, libs/ui/packages/react/src/pre-ldls/components/NetworkItem/NetworkItem.tsx, libs/ui/packages/react/src/pre-ldls/components/NetworkList/NetworkList.stories.tsx, libs/ui/packages/react/src/pre-ldls/components/NetworkList/NetworkList.tsx, pnpm-lock.yaml
- ...
Adds CryptoIcon to LDLS UI library
- **JIRA or GitHub link**: [LIVE-18221](https://ledgerhq.atlassian.net/browse/LIVE-18221)
---
[LIVE-18221]: https://ledgerhq.atlassian.net/browse/LIVE-18221?atlOrigin=eyJpIjoiN …
=> feat(LLD): CryptoIcons

.changeset/old-mice-deny.md, libs/ui/packages/react/src/pre-ldls/components/AssetItem/AssetItem.tsx, libs/ui/packages/react/src/pre-ldls/components/NetworkItem/NetworkItem.tsx
- asset and network items
Icon wasn't well vertically centered => it was a bit weird with a list on LLD 
|<img width="342" alt="image" src="https://github.com/user-attachments/assets/e1ca9c4c-a634-4410-b597-934de030a235" />|<img width="342" alt="image" src="https://github.com/user-attachments/assets/12283fd1-3c5e-4cf0-800d-6520de3c53e5" />|
--- …
=> :bug: (lld/ui) polish asset and network items

.github/workflows/test-coin-modules-integ.yml
- ...
Change slack channel id to live-repo-health
---
=> slack channel coin-modules integ reports

.github/workflows/test-coin-modules-integ.yml
- ...
Prevent reports on manual runs
---
=> prevent slack report manual runs cm integ tests

package.json
- [] `npx changeset` was attached. not rquired
- ...
Do not stop at first failure on integ tests
---
=> coin-modules:test-integ : Do not stop at first failure

.changeset/angry-insects-punch.md, apps/ledger-live-mobile/src/components/RootNavigator/LandingPagesNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/SettingsNavigator.tsx, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/components/Card.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/components/StickyHeader.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/index.tsx
- ...
feat: Large Mover Sticky header component
- **JIRA or GitHub link**: [LIVE-18100] 
---
[LIVE-18100]: https://ledgerhq.atlassian.net/browse/LIVE-18100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …
=> feat: Large Mover Sticky header component

.changeset/proud-emus-whisper.md, libs/coin-modules/coin-tezos/src/api/index.test.ts, libs/coin-modules/coin-tezos/src/api/index.ts, libs/coin-modules/coin-tezos/src/logic/estimateFees.integ.test.ts
- ...
- fix tezos transaction crafting setting gasLimit/storageLimit to 0, an estimation is needed even if providing a custom fee
- update asserts on logic integ test, account/network has changed
- https://ledgerhq.atlassian.net/browse/BACK-8855
--- …
=> chore(BACK-8855): [coin-modules][tezos] fix tezos transaction crafting setting gasLimit/storageLimit to 0

apps/ledger-live-desktop/src/renderer/components/OperationsList/DateCell.tsx, e2e/desktop/tests/page/account.page.ts, e2e/desktop/tests/page/drawer/operation.drawer.ts, e2e/desktop/tests/specs/add.account.spec.ts, e2e/desktop/tests/specs/delegate.spec.ts, e2e/desktop/tests/specs/swap.other.spec.ts
=> fix add account e2e

.changeset/odd-drinks-cheer.md, apps/ledger-live-desktop/static/i18n/en/app.json, libs/ledger-live-common/src/exchange/swap/getIncompatibleCurrencyKeys.ts
- ...
add ton token nano S error drawer
https://ledgerhq.atlassian.net/browse/LIVE-18919
---
=> Fix/live 18919 add ton token nano S error drawer

.changeset/twelve-insects-cross.md, libs/ledger-live-common/src/families/evm/config.ts
Update default explorer to match firebase config
- **JIRA or GitHub link**:[https://ledgerhq.atlassian.net/browse/LIVE-17917](https://ledgerhq.atlassian.net/browse/LIVE-17917)
---
=> update base default explorer

e2e/desktop/tests/specs/nft.spec.ts
- ...
skip nft test 
CI RUN: https://github.com/LedgerHQ/ledger-live/actions/runs/15016983402
---
=> skip nft tests

.changeset/wicked-donkeys-approve.md, apps/web-tools/trustchain/components/Actionable.tsx
- ...
Improve error message when ledger sync is closed
|![Screenshot 2025-05-14 at 15 10 25](https://github.com/user-attachments/assets/220d2723-15e4-48be-bf23-6c2fac0c2b79)|![Screenshot 2025-05-14 at 15 10 17](https://github.com/user-attachments/assets/3d5c25d8-fb5d-47c3-81c2-f136d52bdc2d)|
---
- …
=> 🥅  Web Tool - Improve error message when ledger sync is closed

.changeset/calm-pianos-decide.md, .changeset/cuddly-bags-sip.md, apps/ledger-live-mobile/package.json, libs/ledger-live-common/package.json, libs/live-dmk-desktop/package.json, libs/live-dmk-mobile/package.json, libs/live-dmk-shared/package.json, libs/live-signer-evm/package.json, libs/live-signer-evm/src/DmkSignerEth.ts, libs/live-signer-evm/tests/DmkSignerEth.test.ts, pnpm-lock.yaml
Also fix LIVE-18782
- ...
https://ledgerhq.atlassian.net/browse/LIVE-18782
https://ledgerhq.atlassian.net/browse/LIVE-18780
---
=> bugfix(LIVE-18780): skip open app in ETH signer

.changeset/early-ravens-prove.md, apps/ledger-live-desktop/package.json, pnpm-lock.yaml
- storyly
Upgrade to the latest Storyly SDK version to fix an issue we have with text animation inside stories 
All versions are here => https://github.com/Netvent/storyly-sdk/blob/master/web/RELEASENOTES.md
|https://github.com/user-attachments/assets/6883caf7-e764-4732-9f02-1615d7e5ce41|https://github.com/user-attachments/assets/0285f7e9-5c91-498e-81e0-efef6ee964af|
- **JIRA or GitHub link**: [LIVE-18762](https://ledgerhq.atlassian.net/browse/LIVE-18762)
--- …
=> :package: (lld) update storyly sdk version

.changeset/blue-roses-explain.md, apps/ledger-live-desktop/src/renderer/screens/earn/index.tsx, apps/ledger-live-mobile/src/screens/PTX/Earn/index.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
Adds ptxEarnLiveApp feature flag which allows us to use different manifest for earn app.
DEMO:
https://github.com/user-attachments/assets/53b71008-0040-464b-bb88-5ded07916876
- ...
- **JIRA or GitHub link**: [LIVE-18848](https://ledgerhq.atlassian.net/browse/LIVE-18848)
---
- **The code aligns with the requirements** described in the linked JIRA or GitHub …
=> feat: add earn live app manifest ff

.changeset/silver-pants-grin.md, apps/ledger-live-mobile/src/analytics/Track.ts, apps/ledger-live-mobile/src/analytics/__tests__/Track.test.tsx, apps/ledger-live-mobile/src/screens/Settings/General/ReportErrorsRow.tsx
- Track component
- Tracking inside general settings
The track component was misconfigured and triggered every time we called it, even with props like onUpdate. On LLD, this issue isn't present as we use a class component. 
This PR fixes the issue and add testing
|https://github.com/user-attachments/assets/ab4443bf-4c30-48d1-aa05-b308e947dbc6|https://github.com/user-attachments/assets/93357e5d-2c72-4b12-a9a7-83603f7c8d79|
- **JIRA or GitHub link**:[LIVE-19066](https://ledgerhq.atlassian.net/browse/LIVE-19066)
---
- …
=> :chart_with_upwards_trend: (llm) enhance component lifecycle tracking

.changeset/shy-months-talk.md, apps/ledger-live-mobile/src/components/RootNavigator/types/LandingPagesNavigator.ts, apps/ledger-live-mobile/src/components/RootNavigator/types/SettingsNavigator.ts, apps/ledger-live-mobile/src/navigation/DeeplinksProvider.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/hooks/useLargeMover.ts, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/index.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/utils/index.tsx, apps/ledger-live-mobile/src/screens/Settings/Debug/Features/index.tsx
- ...
Large Mover Deeplink
- **JIRA or GitHub link**: [LIVE-18057]
---
[LIVE-18057]: https://ledgerhq.atlassian.net/browse/LIVE-18057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …
=> Feat: Large Mover Deeplink

.github/workflows/build-desktop-reusable.yml, .github/workflows/build-mobile-reusable.yml, .github/workflows/test-desktop-external-reusable.yml
- ...
Reduce datadog noise, by skipping the report job whenever one of the parent jobs fail. (It should skip instead)
- https://github.com/LedgerHQ/ledger-live/actions/runs/15071334742
- https://github.com/LedgerHQ/ledger-live/actions/runs/15071610642/attempts/2
- https://github.com/LedgerHQ/ledger-live/actions/runs/15071610642
- https://ledgerhq.atlassian.net/browse/LIVE-18772
---
- **Any new …
=> ci(LIVE-18772): reduce datadog noise

.changeset/sweet-hairs-brake.md, libs/ledger-live-common/src/exchange/swap/getIncompatibleCurrencyKeys.ts
- Fixes typo in getIncompatibleCurrencyKeys
|  <img width="533" alt="image" src="https://github.com/user-attachments/assets/c6f5416e-7726-43e2-a6f6-a01c0bb87e08" /> | <img width="383" alt="image" src="https://github.com/user-attachments/assets/6b7c34da-83c0-4304-bb38-71551e16b580" /> |
- …
=> Fix incompatibility messages for Nano S during Sui swaps

.changeset/happy-peaches-fetch.md, apps/ledger-live-mobile/src/components/RootNavigator/types/BaseNavigator.ts, apps/ledger-live-mobile/src/components/RootNavigator/types/LandingPagesNavigator.ts, apps/ledger-live-mobile/src/newArch/components/Swiper/components/Swiper.tsx, apps/ledger-live-mobile/src/newArch/components/Swiper/hooks/useCardRotation.ts, apps/ledger-live-mobile/src/newArch/components/Swiper/hooks/useSwiper.ts, apps/ledger-live-mobile/src/newArch/components/Swiper/types.ts, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/components/Card.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/components/Loading.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/components/__tests__/CardLargeMover.test.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/hooks/useLargeMover.ts, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/index.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/types.d.ts, apps/ledger-live-mobile/src/screens/Settings/Debug/Features/SwiperScreenDebug/index.tsx
- ...
feat: Large Mover swipe card
- **JIRA or GitHub link**: [LIVE-18310]
---
https://github.com/user-attachments/assets/13cf1909-5aff-4e3a-a9de-d83ec1901631
[LIVE-18310]: …
=> feat: Large Mover swipe card

apps/ledger-live-desktop/src/renderer/components/ExportLogsButton.tsx, apps/ledger-live-desktop/src/renderer/components/OpenUserDataDirectoryBtn.tsx, e2e/desktop/tests/fixtures/common.ts, e2e/desktop/tests/page/settings.page.ts, e2e/desktop/tests/specs/settings.spec.ts, e2e/desktop/tests/specs/swap.other.spec.ts
- ...
Adding settings tests:
- B2CQA-825: Verify that user can view user data folder
- B2CQA-2474: User can export logs
Adding swap tests:
- B2CQA-604: User can export all history operations
- B2CQA-602: User should be able to see their swap history from the swap history page
- **JIRA or GitHub link**: [QAA-580](https://ledgerhq.atlassian.net/browse/QAA-580)
- **Run**: https://github.com/LedgerHQ/ledger-live/actions/runs/15045014947
- **Allure**: https://ledger-live.allure.green.ledgerlabs.net/allure/reports/5d288126-f02a-4589-9a30-73868f512146/#
--- …
=> [QAA] adding settings tests

.changeset/light-moose-marry.md, libs/coin-modules/coin-aptos/jest.config.js, libs/coin-modules/coin-aptos/src/__tests__/api/index.integ.test.ts, libs/coin-modules/coin-aptos/src/__tests__/api/index.test.ts, libs/coin-modules/coin-aptos/src/__tests__/bridge/createTransaction.test.ts, libs/coin-modules/coin-aptos/src/__tests__/network/client.test.ts, libs/coin-modules/coin-aptos/src/api/index.ts, libs/coin-modules/coin-aptos/src/bridge/createTransaction.ts, libs/coin-modules/coin-aptos/src/bridge/estimateMaxSpendable.ts, libs/coin-modules/coin-aptos/src/bridge/getFeesForTransaction.ts, libs/coin-modules/coin-aptos/src/bridge/logic.ts, libs/coin-modules/coin-aptos/src/bridge/prepareTransaction.ts, libs/coin-modules/coin-aptos/src/constants.ts, libs/coin-modules/coin-aptos/src/network/client.ts, libs/coin-modules/coin-aptos/src/types/assets.ts
- ...
Adds the estimatefees for Aptos Alpaca integration
- [LIVE-18214](https://ledgerhq.atlassian.net/browse/LIVE-18214)
---
[LIVE-18214]: https://ledgerhq.atlassian.net/browse/LIVE-18214?atlOrigin=eyJpIjoiNWRkNTljNz …
=> feat(LIVE-18214): alpaca estimatefees

.github/labeler.yml
- ...
- so that Cloud Wallet team can be notified and update https://github.com/LedgerHQ/alpaca-coin-module
--- …
=> ci: auto label pull requests changing coin modules API

.changeset/happy-ads-share.md, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/DeviceActions/openOrInstall.tsx, apps/ledger-live-desktop/src/renderer/analytics/segment.ts, apps/ledger-live-desktop/src/renderer/components/LiveAppDrawer.tsx, apps/ledger-live-desktop/src/renderer/components/OnboardingAppInstall/InstallSetOfApps.tsx, apps/ledger-live-desktop/src/renderer/families/bitcoin/FullNode/steps/StepConnectDevice.tsx, apps/ledger-live-desktop/src/renderer/hooks/useConnectAppAction.ts, apps/ledger-live-desktop/src/renderer/modals/AddAccounts/steps/StepConnectDevice.tsx, apps/ledger-live-desktop/src/renderer/modals/ConnectDevice/index.tsx, apps/ledger-live-desktop/src/renderer/modals/ExchangeDeviceConfirm/index.tsx, apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/CompleteExchange/BodyContent.tsx, apps/ledger-live-desktop/src/renderer/modals/Platform/Exchange/StartExchange/index.tsx, apps/ledger-live-desktop/src/renderer/modals/Receive/steps/StepConnectDevice.tsx, apps/ledger-live-desktop/src/renderer/modals/Send/steps/GenericStepConnectDevice.tsx, apps/ledger-live-desktop/src/renderer/modals/SignMessage/steps/StepSign.tsx, apps/ledger-live-desktop/src/renderer/modals/SignTransaction/steps/GenericStepConnectDevice.tsx, apps/ledger-live-mobile/src/analytics/segment.ts, apps/ledger-live-mobile/src/hooks/deviceActions.ts, apps/web-tools/trustchain/components/AppAccountsSync.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledger-live-common/src/hw/connectApp.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- ...
- Add `ldmkConnectApp` feature flag.
- **JIRA or GitHub link**: [DSDK-706]
---
[DSDK-706]: https://ledgerhq.atlassian.net/browse/DSDK-706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …
=> [DSDK-706] Add `ldmkConnectApp` feature flag

.changeset/gorgeous-bags-accept.md, apps/ledger-live-mobile/src/locales/en/common.json
- ...
Ton token error screen nano S
https://ledgerhq.atlassian.net/browse/LIVE-18919
---
=> Fix/live 18919: Ton token error screen nano S

.changeset/late-glasses-smash.md, libs/coin-modules/coin-sui/.unimportedrc.json, libs/coin-modules/coin-sui/src/network/sdk.ts
=> lint: remove jsonrpcerror import

.github/workflows/test-ui-e2e-only-desktop.yml, apps/ledger-live-desktop/src/renderer/reducers/devices.ts, e2e/desktop/package.json, e2e/desktop/tests/page/swap.page.ts, e2e/desktop/tests/specs/add.account.spec.ts, e2e/desktop/tests/specs/delegate.spec.ts, e2e/desktop/tests/specs/delete.account.spec.ts, e2e/desktop/tests/specs/ledgerSync.spec.ts, e2e/desktop/tests/specs/nft.spec.ts, e2e/desktop/tests/specs/portfolio.spec.ts, e2e/desktop/tests/specs/receive.address.spec.ts, e2e/desktop/tests/specs/send.tx.spec.ts, e2e/desktop/tests/specs/settings.spec.ts, e2e/desktop/tests/specs/subAccount.spec.ts, e2e/desktop/tests/specs/swap.other.spec.ts, e2e/desktop/tests/specs/swap.send.spec.ts, libs/ledger-live-common/.unimportedrc.json, libs/ledger-live-common/src/e2e/enum/Device.ts, libs/ledger-live-common/src/e2e/enum/Swap.ts, libs/ledger-live-common/src/e2e/families/cardano.ts, libs/ledger-live-common/src/e2e/families/evm.ts, libs/ledger-live-common/src/e2e/families/solana.ts, libs/ledger-live-common/src/e2e/speculos.ts, tools/actions/composites/run-e2e-playwright-tests/action.yml
- ...
Adding LNS and LNX to our e2e tests
- [QAA-626](https://ledgerhq.atlassian.net/browse/QAA-626)
- [QAA-412](https://ledgerhq.atlassian.net/browse/QAA-412)
---
- **CI Run**: 
- [LNS](https://github.com/LedgerHQ/ledger-live/actions/runs/15132431254)
- [LNX](https://github.com/LedgerHQ/ledger-live/actions/runs/15132975744)
- [LNSP](https://github.com/LedgerHQ/ledger-live/actions/runs/15133641187)
---
- **The PR has been tested** thoroughly, and any potential edge cases …
=> 👷 Adding LNS and LNX to e2e tests - LLD

CODEOWNERS
=> :wrench: (chore) update CO file

.changeset/three-clouds-share.md, libs/coin-modules/coin-aptos/src/__tests__/logic/combine.unit.test.ts, libs/coin-modules/coin-aptos/src/__tests__/network/client.test.ts, libs/coin-modules/coin-aptos/src/api/index.ts, libs/coin-modules/coin-aptos/src/logic/combine.ts, libs/coin-modules/coin-aptos/src/network/client.ts, libs/coin-modules/coin-aptos/src/network/index.ts
- ...
PR implements the method `combine` on Alpaca API integration for Aptos coin.
- **JIRA**: [LIVE-18212](https://ledgerhq.atlassian.net/browse/LIVE-18212) 
---
[LIVE-18212]: …
=> LIVE-18212 - Aptos Alpaca API combine

.changeset/kind-icons-tease.md, apps/ledger-live-desktop/package.json, apps/ledger-live-desktop/src/renderer/families/cosmos/Delegation/__tests__/Delegations.test.tsx, apps/ledger-live-desktop/src/renderer/families/cosmos/__tests__/AccountBalanceSummaryFooter.test.tsx, apps/ledger-live-mobile/__mocks__/@react-native-clipboard/clipboard.js, apps/ledger-live-mobile/package.json, apps/ledger-live-mobile/src/components/Skeleton.tsx, apps/ledger-live-mobile/src/screens/Account/ListHeaderComponent.tsx, apps/ledger-live-mobile/src/screens/Account/__tests__/ListHeaderComponent.test.tsx, apps/ledger-live-mobile/src/screens/WalletCentricSections/SectionTitle.tsx
- No impacts
Add React tests for delegation disable flag in coin configuration
- **JIRA or GitHub link**: [LIVE-18757](https://ledgerhq.atlassian.net/browse/LIVE-18757)
---
[LIVE-18757]: …
=> [LIVE-18757] Add React tests for delegation disable flag in coin configuration

.changeset/new-shoes-dance.md, libs/ledger-services/cal/src/partners/default.ts
- [ x] `npx changeset` was attached.
- ...
--- …
=> feat: changelly v2

.changeset/spicy-ghosts-boil.md, libs/coin-modules/coin-aptos/package.json, libs/coin-modules/coin-aptos/src/__tests__/api/getBalance.unit.test.ts, libs/coin-modules/coin-aptos/src/__tests__/api/index.integ.test.ts, libs/coin-modules/coin-aptos/src/__tests__/network/client.test.ts, libs/coin-modules/coin-aptos/src/api/index.ts, libs/coin-modules/coin-aptos/src/logic/getBalance.ts, libs/coin-modules/coin-aptos/src/network/client.ts, libs/coin-modules/coin-aptos/src/types/index.ts
- ...
Implements `getBalance` method for Aptos Alpaca API integration.
- **JIRA**: [LIVE-18215](https://ledgerhq.atlassian.net/browse/LIVE-18215) 
---
[LIVE-18215]: …
=> LIVE-18215 - aptos alpaca get balance

libs/coin-modules/coin-hedera/.unimportedrc.json, libs/ledger-live-common/.unimportedrc.json
=> chore: update unimportedrc

e2e/desktop/tests/specs/ledgerSync.spec.ts
- ...
Title and description changed
---
=> fix ticket numbers and title

e2e/desktop/tests/page/swap.page.ts, e2e/desktop/tests/specs/swap.other.spec.ts, e2e/desktop/tests/utils/swapUtils.ts
=> [LLD] [e2e] fix: stabilising flaky swap tests 

.changeset/pretty-pumas-listen.md, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/components/SelectAccountFlow/components/AccountSelectionStep.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/components/SelectAccountFlow/components/SelectAccount.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/components/SelectAccountFlow/hooks/tests/sortAccountsByBalance.test.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/components/SelectAccountFlow/hooks/useDetailedAccounts.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/components/SelectAccountFlow/utils/formatDetailedAccount.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/components/SelectAccountFlow/utils/sortAccountsByFiatValue.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/components/SelectAccountFlow/utils/tests/formatDetailedAccount.test.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/components/SelectAccountFlow/utils/tests/sortAccountsByFiatValue.test.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/components/SelectAssetFlow/index.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/components/SelectAssetFlow/useSelectAssetFlow.ts, apps/ledger-live-desktop/src/newArch/utils/formatAddress.ts, apps/ledger-live-desktop/src/newArch/utils/getBalanceAndFiatValue.ts, apps/ledger-live-desktop/src/newArch/utils/getTokenAccountTuples.ts, apps/ledger-live-desktop/src/newArch/utils/tests/formatAddress.test.ts, apps/ledger-live-desktop/src/newArch/utils/tests/getProductName.test.ts, apps/ledger-live-desktop/src/newArch/utils/tests/getTokenAccountTuples.test.ts, apps/ledger-live-desktop/src/renderer/reducers/accounts.ts, libs/ui/packages/react/src/pre-ldls/components/AccountItem/AccountItem.tsx, libs/ui/packages/react/src/pre-ldls/components/Address/Address.tsx, libs/ui/packages/react/src/pre-ldls/components/Tag/Tag.tsx
- select account flow
- account aggregation to display the corresponding token accounts depending on the selected network
- add corresponding account using the button at the top
- add unit tests for all our utils 
storybook preview https://react-ui-storybook-git-feat-madaggregateaccountflow-ledgerhq.vercel.app/?path=/docs/preldls-components-accountlist--docs
https://github.com/user-attachments/assets/735a4c99-a09c-402a-aa53-c1b7dbba4c97
fix broken account row overflow : 
|![image](https://github.com/user-attachments/assets/0ca84489-9a9a-43ef-8f44-a336409bfc0a)|![image](https://github.com/user-attachments/assets/160e08d4-74cb-4306-9677-2c33521d8d45)|
https://github.com/user-attachments/assets/9c106d13-f010-4023-8d80-b462b90 …
=> :sparkles: (LLD/MAD) account selection aggregation

.changeset/cyan-roses-turn.md, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/components/Card.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/components/StickyHeader.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/components/TimeFrame.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/const.ts, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/hooks/useFooterQuickAction.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/index.tsx
- ...
feat: Large Mover Analytics
- **JIRA or GitHub link**: [LIVE-18138]
https://github.com/user-attachments/assets/0544ed79-2fe9-44c5-aa59-751f9f8ff134
---
[LIVE-18138]: …
=> feat: Large Mover Analytics

.changeset/gold-hats-own.md, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- ...
Add Account Feature Flag added
- **JIRA or GitHub link**: [LIVE-18819] 
---
[LIVE-18819]: https://ledgerhq.atlassian.net/browse/LIVE-18819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …
=> ✨ LLD - Add Account Feature Flag

.changeset/tame-bugs-sip.md, apps/ledger-live-mobile/src/screens/PTX/Earn/EarnMenuDrawer.tsx
Demo:
- ...
- Jira: [LIVE-17214](https://ledgerhq.atlassian.net/browse/LIVE-17214)
--- …
=> fix: label cut on bottom

.changeset/grumpy-pets-explain.md, apps/ledger-live-mobile/src/newArch/components/Swiper/components/SwipeableCard.tsx, apps/ledger-live-mobile/src/newArch/components/Swiper/hooks/useCardRotation.ts, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/components/Card.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/components/PriceAndVariation.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/components/Ticker.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/components/__tests__/CardLargeMover.test.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/index.tsx, libs/ui/packages/native/src/components/Form/TabSelector/index.tsx, libs/ui/packages/native/src/components/cta/QuickAction/QuickActionButton/index.tsx
- ...
fix: p1 bugs for large mover (see ticket for full list)
- **JIRA or GitHub link**: [LIVE-19183]
https://github.com/user-attachments/assets/b0370604-12b6-47f3-9f13-0406bed37f50
---
[LIVE-19183]: …
=> fix: p1 bugs for large mover

.github/workflows/test-coin-tester.yml, libs/coin-tester-modules/coin-tester-solana/.env.example, libs/coin-tester-modules/coin-tester-solana/.unimportedrc.json, libs/coin-tester-modules/coin-tester-solana/README.md, libs/coin-tester-modules/coin-tester-solana/docker-compose.yml, libs/coin-tester-modules/coin-tester-solana/jest.config.ts, libs/coin-tester-modules/coin-tester-solana/package.json, libs/coin-tester-modules/coin-tester-solana/src/agave.ts, libs/coin-tester-modules/coin-tester-solana/src/fixtures.ts, libs/coin-tester-modules/coin-tester-solana/src/scenarii.test.ts, libs/coin-tester-modules/coin-tester-solana/src/scenarii/solana.ts, libs/coin-tester-modules/coin-tester-solana/tsconfig.json, libs/coin-tester/README.md, package.json, pnpm-lock.yaml, tools/actions/composites/run-coin-tester/action.yml
- ...
Initialize new package `coin-tester-solana`, and run the tests in the CI. The Solana Coin Tester is limited to two scenarios:
- send 1 Sol
- send all Sol
---
=> feat(coin-tester-solana): add Solana Coin Tester

.changeset/green-goats-whisper.md, libs/ledger-live-common/src/families/evm/config.ts
- ...
Set showNfts default value to true
- **JIRA or GitHub link**: [LIVE-19284](https://ledgerhq.atlassian.net/browse/LIVE-19284)
---
[LIVE-19284]: https://ledgerhq.atlassian.net/browse/LIVE-19284?atlOrigin=eyJpIjoiN …
=> fix/Put showNfts default value to true

.github/workflows/test-mobile-e2e-reusable.yml
- iOS E2E Speculos tests
Use service account access token for Speculos tests
---
=> [QAA][E2E][CI] use service account access token for Speculos tests

.changeset/early-turtles-drum.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/App/App.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx, apps/ledger-live-mobile/src/screens/Swap/LiveApp/index.tsx
- ...
- fix the desktop state after connection restored
- fix mobile QAA netwrok down err
https://github.com/user-attachments/assets/31db83ff-984f-4113-bef0-1a048df2dec2
https://ledgerhq.atlassian.net/browse/LIVE-19133
--- …
=> fix(live-19113): simplify error handling and remove unused state

apps/ledger-live-desktop/src/renderer/components/SideBar/SideBarListItem.tsx, e2e/desktop/tests/component/layout.component.ts, e2e/desktop/tests/fixtures/common.ts, e2e/desktop/tests/page/abstractClasses.ts, e2e/desktop/tests/page/account.page.ts, e2e/desktop/tests/page/accounts.page.ts, e2e/desktop/tests/page/buyAndSell.page.ts, e2e/desktop/tests/page/index.ts, e2e/desktop/tests/page/market.page.ts, e2e/desktop/tests/page/webViewApp.page.ts, e2e/desktop/tests/specs/buySell.spec.ts, libs/ledger-live-common/.unimportedrc.json, libs/ledger-live-common/src/e2e/models/BuySell.ts
=> Implement Buy / Sell flow from different entry point (Asset Allocation, Market page, Account page)

.changeset/mighty-dolls-brush.md, libs/coin-modules/coin-aptos/src/__tests__/api/index.integ.test.ts, libs/coin-modules/coin-aptos/src/logic/transactionsToOperations.ts, libs/coin-modules/coin-aptos/src/network/client.ts, libs/coin-modules/coin-aptos/src/types/assets.ts
- ...
Add tokens operations to the operations list for aptos alpaca api
- **JIRA or GitHub link**: [LIVE-19040](https://ledgerhq.atlassian.net/browse/LIVE-19040)
---
[LIVE-19040]: …
=> Aptos alpaca list token operations

.changeset/tender-panthers-pull.md, libs/coin-modules/coin-cosmos/src/config.ts
- ...
Zenrock was failing cause fee was too low, fixed with `new minGasPrice` which is now 2.5
- **JIRA or GitHub link**: [LIVE-19334](https://ledgerhq.atlassian.net/browse/LIVE-19334)
---
[LIVE-19334]: …
=> fix: zenrock minGasPrice

.changeset/kind-icons-drop.md, apps/ledger-live-mobile/src/components/RootNavigator/LandingPagesNavigator.tsx
- ...
fix: large mover header deleted
- **JIRA or GitHub link**: [LIVE-19357]
---
[LIVE-19357]: https://ledgerhq.atlassian.net/browse/LIVE-19357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2 …
=> fix: large mover header deleted

.changeset/lovely-papayas-scream.md, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/components/Card.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/components/Ticker.tsx
- ...
fix: blur on the top of the card and blur on the ticker
- **JIRA or GitHub link**: [LIVE-19183]
https://github.com/user-attachments/assets/aedb4064-de31-4dfb-84b8-655c4fe451eb
---
[LIVE-19183]: …
=> fix: blur on the top of the card and blur on the ticker

apps/ledger-live-mobile/e2e/bridge/start-server.ts, apps/ledger-live-mobile/e2e/bridge/types.ts, apps/ledger-live-mobile/e2e/jest.globalSetup.ts
- Start-server script
start-server script was broken by [PR](https://github.com/LedgerHQ/ledger-live/pull/9595)
---
=> [Detox][Mock] Fix start-server script

.changeset/red-foxes-kneel.md, apps/ledger-live-mobile/src/components/useExportLogs.tsx, libs/ledgerjs/packages/logs/src/index.test.ts, libs/ledgerjs/packages/logs/src/index.ts
- ...
- **JIRA or GitHub link**: [LIVE-19047] 
---
- **The PR …
=> :bug: (logs): Export log circular error

.changeset/rude-radios-compete.md, apps/ledger-live-desktop/src/config/urls.ts, apps/ledger-live-desktop/static/i18n/en/app.json, libs/coin-framework/src/config.ts, libs/ledger-live-common/src/__tests__/test-helpers/bridge.ts, libs/ledger-live-common/src/bridge/impl.ts, libs/ledger-live-common/src/config/index.ts, libs/ledger-live-common/src/config/sharedConfig.ts, libs/ledger-live-common/src/sanction/errors.ts, libs/ledger-live-common/src/sanction/index.ts
- No impact
Common part used for https://ledgerhq.atlassian.net/browse/LIVE-19170 and https://ledgerhq.atlassian.net/browse/LIVE-19085
Implement sanctioned addresses check
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/LIVE-19413
--- …
=> Feature/live 19413 build common part for completeExchange flow

libs/coin-modules/coin-tezos/src/api/index.integ.test.ts
- ...
see #10427, test assertions need an update as contract of `craftTransaction` slightly changed
---
=> fix(BACK-9017): [coin-modules][tezos] fix integration tests

e2e/desktop/tests/specs/nft.spec.ts, e2e/desktop/tests/specs/swap.other.spec.ts
=> [LLD] [E2E] chore: enable nft tests

e2e/mobile/helpers/commonHelpers.ts, e2e/mobile/package.json, e2e/mobile/page/accounts/addAccount.drawer.ts, e2e/mobile/page/index.ts
=> clean up use of mock in e2e/mobile

.changeset/purple-deers-run.md, apps/ledger-live-mobile/src/families/cosmos/DelegationFlow/02-Summary.tsx
- ...
fix delegation e2e test by removing the bridge dependency on cosmos delegation useEffect
We now create a new instance of the bridge each time we call getTransactionStatus
Which lead to make the component rerender infinitely
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/LIVE-19505?atlOrigin=eyJpIjoiYzg3M2JjMjMyM2UyNDFmODhjNTZhYTE5N2UzODBhOWIiLCJwIjoiaiJ9
---
- **Any new …
=> bugfix: fix delegation e2e test

.changeset/dry-mugs-cross.md, apps/ledger-live-mobile/package.json, libs/ledger-live-common/package.json, libs/ledger-live-common/src/hw/connectAppEventMapper.ts, libs/ledgerjs/packages/hw-app-exchange/package.json, libs/live-dmk-desktop/package.json, libs/live-dmk-mobile/package.json, libs/live-dmk-shared/package.json, libs/live-signer-evm/package.json, pnpm-lock.yaml
- ...
* Fix secure channel errors handling: https://ledgerhq.atlassian.net/browse/LIVE-19430
* Fix unexpected disconnection during OpenApp: https://ledgerhq.atlassian.net/browse/LIVE-19429
--- …
=> :bug: (llc) [LIVE-19430 LIVE-19429]: Fix ConnectApp issues

.changeset/smooth-dogs-join.md
=> :bug: (llm): Add missing changelog for ConnectApp

.changeset/metal-onions-roll.md, apps/web-tools/pages/logsviewer.tsx, libs/live-dmk-desktop/src/transport/DeviceManagementKitTransport.ts, libs/live-dmk-mobile/src/transport/DeviceManagementKitTransport.ts
=> 🧑‍💻 (logviewer): Adapt logviewer for DMK apdu logs

CODEOWNERS
- ...
Update CI Github Team Name
---
=> chore: update CI team name

.changeset/dull-tables-rule.md, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/Web3AppWebview/AssetAndAccountDrawer.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/__tests__/selectAccountFlow.test.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/analytics/__tests__/useModularDrawerAnalytics.test.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/analytics/useModularDrawerAnalytics.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/AssetSelection/components/List.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/AssetSelection/components/SearchInputContainer/test/useSearch.test.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/AssetSelection/components/SearchInputContainer/useSearch.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/NetworkSelection/components/List.tsx
- MAD Analytics
https://github.com/user-attachments/assets/714f1a96-c762-4ba1-9707-f535b830e544
- **JIRA or GitHub link**: [LIVE-19525](https://ledgerhq.atlassian.net/browse/LIVE-19525)
---
[LIVE-19525]: …
=> :chart_with_upwards_trend: (LLD) MAD missing analytics

.changeset/cyan-waves-fetch.md, libs/ledger-live-common/src/hooks/useOFACGeoBlockCheck.ts
- ...
cf https://countervalues.live.ledger.com/docs/openapi/swagger/#/Markets
---
=> fix(ledger-live-common) typo in countervalues market URL

e2e/mobile/package.json, pnpm-lock.yaml
- ...
Bump Detox's version to match with the new patch 
---
=> fix: e2e detox version

libs/ledger-live-common/src/e2e/speculos.ts
=> fix: update BTC app navigation

e2e/mobile/specs/send/send.ts, e2e/mobile/specs/send/sendValidAddress/sendValidAddressATOM.spec.ts, e2e/mobile/specs/send/sendValidAddress/sendValidAddressATOM2.spec.ts, e2e/mobile/specs/send/sendValidAddress/sendValidAddressBCH.spec.ts, e2e/mobile/specs/send/sendValidAddress/sendValidAddressBTC_LEGACY.spec.ts, e2e/mobile/specs/send/sendValidAddress/sendValidAddressBTC_NATIVE_SEGWIT.spec.ts, e2e/mobile/specs/send/sendValidAddress/sendValidAddressBTC_SEGWIT.spec.ts, e2e/mobile/specs/send/sendValidAddress/sendValidAddressBTC_TAPROOT.spec.ts, e2e/mobile/specs/send/sendValidAddress/sendValidAddressETH.spec.ts, e2e/mobile/specs/send/sendValidAddress/sendValidAddressETH2.spec.ts, e2e/mobile/specs/send/sendValidAddress/sendValidAddressETH3.spec.ts, e2e/mobile/specs/send/sendValidAddress/sendValidAddressETH_USDT.spec.ts, e2e/mobile/specs/send/sendValidAddress/sendValidAddressXRP.spec.ts, e2e/mobile/specs/send/sendValidAddress/sendValidAddressXRP2.spec.ts
=> fix: update and valid address testcases

CODEOWNERS
Updating the wallet-api team to coin-integration in our CODEOWNERS file as we'll remove the wallet-api team soon
---
=> chore: update wallet-api team to coin-integration as we'll remove the former soon

e2e/desktop/tests/specs/nft.spec.ts
=> chore: disable NFT tests on LLD

.changeset/silver-geckos-attack.md, libs/ledger-live-common/src/families/evm/config.ts
- ...
Change showNfts default value to false in coin config evm for ETH and POL
- **JIRA or GitHub link**: [LIVE-19537](https://ledgerhq.atlassian.net/browse/LIVE-19537) 
---
[LIVE-19537]: …
=> Feat/set showNfts to false

.changeset/brave-colts-join.md, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/components/Footer.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/hooks/useFooterQuickAction.tsx
- ...
Fix btn 'Sell' greyed out even when account with funds on Large Mover
---
=> bugfix: button Sell greyed out

e2e/mobile/helpers/commonHelpers.ts, e2e/mobile/models/stake.ts, e2e/mobile/page/trade/operationDetails.page.ts, e2e/mobile/specs/send/send.ts
=> fix: broken function due to renaming and add SPECULOS_DEVICE as export

.changeset/five-hornets-rhyme.md, apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/helpers.ts
- web3app
Add missing entry point to MAD drawer
https://github.com/user-attachments/assets/2cd9d22d-0d90-40a0-a865-4f29c4b35804
https://github.com/user-attachments/assets/c0dbc10e-796f-4f8d-a1ca-044a9379b71e
- **JIRA or GitHub link**: [LIVE-19656](https://ledgerhq.atlassian.net/browse/LIVE-19656)
--- …
=> :sparkles: (MAD) missing entry point to MAD

.changeset/purple-llamas-itch.md, libs/coin-modules/coin-solana/src/prepareTransaction.ts, libs/coin-modules/coin-solana/src/signOperation.ts, libs/coin-modules/coin-solana/src/signer.ts, libs/coin-modules/coin-solana/src/tx-fees.ts, libs/coin-modules/coin-solana/src/types.ts, libs/coin-tester-modules/coin-tester-solana/data/virtual.json, libs/coin-tester-modules/coin-tester-solana/docker-compose.yml, libs/coin-tester-modules/coin-tester-solana/src/fixtures.ts, libs/coin-tester-modules/coin-tester-solana/src/scenarii/solana.ts, libs/coin-tester/docker-compose.yml, libs/coin-tester/src/main.ts, libs/ledger-services/cal/src/certificate.integ.test.ts, libs/ledger-services/cal/src/certificate.ts, libs/ledger-services/cal/src/tokens.ts, libs/ledgerjs/packages/hw-app-solana/README.md, libs/ledgerjs/packages/hw-app-solana/src/Solana.ts, libs/ledgerjs/packages/hw-app-solana/src/descriptor.ts, libs/ledgerjs/packages/hw-app-solana/tests/Solana.test.ts, libs/ledgerjs/packages/hw-app-solana/tests/descriptor.test.ts, libs/live-signer-solana/src/LegacySignerSolana.ts, libs/live-signer-solana/tests/LegacySignerSolana.test.ts, tools/actions/composites/setup-coin-tester-env/action.yml
- ...
Provide dynamic token information to Solana app, downloaded from the CAL.
Note we need to fetch a specific certificate from the CAL as well for this use case.
---
=> core(coin-solana,hw-app-solana): support SPL tokens dynamically

.changeset/three-actors-repair.md, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/components/OverlayTutorial.tsx
- ...
here is the figma : https://www.figma.com/design/uQYdD0E0ELDKi3skrduZpw/Notifications?node-id=5429-1595&t=s6FJt2vEdYeBZpQw-0
- **JIRA or GitHub link**: [LIVE-18954]
https://github.com/user-attachments/assets/a2ab4201-8ad7-4068-b8ba-18856f33da29
--- …
=> fix: dark blur for Large Mover overlay tutorial in light mode

.changeset/selfish-balloons-eat.md, apps/ledger-live-mobile/src/components/WebPTXPlayer/CustomHandlers.ts, apps/ledger-live-mobile/src/components/WebPTXPlayer/index.tsx
- ...
Added custom handler to allow buy/sell to add a close button within it's own UI that closes the app in LL
Removed the LL navigation for when it is the internal app only.
Sister PR adding the navigation in the Buy/Sell app:
https://github.com/LedgerHQ/buy-sell-ui/pull/794
Internal App Behavior:
https://github.com/user-attachments/assets/63891109-a1a3-4b75-bb46-4ab2438f75bc
External still uses LL navigation:
[LIVE-17924](https://ledgerhq.atlassian.net/browse/LIVE-17924)
--- …
=> feat: buy sell mobile navigation bar

.changeset/brown-pans-sing.md, apps/ledger-live-mobile/src/components/Graph/index.tsx
- ...
fix gradient in graph
- **JIRA or GitHub link**: [LIVE-19657]
---
[LIVE-19657]: https://ledgerhq.atlassian.net/browse/LIVE-19657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …
=> fix gradient in graph

.changeset/wet-tables-work.md, libs/coin-modules/coin-ton/src/__tests__/unit/prepareTransaction.unit.test.ts, libs/coin-modules/coin-ton/src/utils.ts
- ...
Fix Jetton swap.
- **JIRA or GitHub link**: [LIVE-19376]
---
[LIVE-19376]: https://ledgerhq.atlassian.net/browse/LIVE-19376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …
=> fix(ton): set fees values to amount

.github/workflows/scan-sonar-reusable.yml
- ...
This should fix the scans warning message indicating that the develop branch was not found and the scans will now correctly compare the branch with what's currently on develop
---
=> 🐛 CI - Fix sonar cloud workflow develop branch not found

.changeset/rotten-chicken-report.md, libs/coin-modules/coin-cosmos/src/config.ts
- ...
Update osmo default lcd
- **JIRA or GitHub link**: [https://ledgerhq.atlassian.net/browse/LIVE-19461](https://ledgerhq.atlassian.net/browse/LIVE-19461)
---
=> update osmo lcd

e2e/desktop/tests/specs/subAccount.spec.ts, libs/ledger-live-common/src/e2e/swap.ts
=> fix: update send an SPL token error message and account for empty value in get minimum amount function

.changeset/light-beds-exercise.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx, apps/ledger-live-mobile/src/screens/Swap/LiveApp/WebView.tsx
add analytics opt in data to swap web views desktop and mobile
- ...
add analytics opt in data to swap web views desktop and mobile
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/LIVE-19694
---
=> feat(LIVE-19694): add analytics opt in data for swap

.changeset/hungry-tomatoes-cover.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx, apps/ledger-live-mobile/src/screens/Swap/LiveApp/WebView.tsx
fix wrong analytics data selector for swap webviews
- ...
--- …
=> fix(LIVE-19694): fix wrong analytics data selector for swap webviews

.github/workflows/import-cal-tokens.yml
- **JIRA link**: https://ledgerhq.atlassian.net/browse/LIVE-19703
--- …
=> fix cal tokens workflow

e2e/mobile/helpers/pageScroller.ts, e2e/mobile/page/discover/discover.page.ts
=> fix: scroll issue and discoverApps url for Yearn

apps/ledger-live-mobile/fastlane/Fastfile
- nightly build workflow from `ledger-live-build` will produce `apk` and `aab` instead of `aab` only
We need to have `apk` for `nightly` builds to be able to upload them later to datadog synthetic testing environment. 
For more information, you will found all the details on the [ADR](https://ledgerhq.atlassian.net/wiki/spaces/WXP/pages/5751242830/2025-04-16+-+ADR+Synthetic+Environment+for+Continuous+Startup+Performance+Testing)
--- …
=> build: build apk and aab for nightly builds

.changeset/gorgeous-weeks-stare.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx, apps/ledger-live-mobile/src/screens/Swap/LiveApp/WebView.tsx
- ...
send where user clicked from to swap live app
https://ledgerhq.atlassian.net/browse/LIVE-19638
---
=> feat(LIVE-19638): send where user clicked from to swap live app

.changeset/poor-ligers-accept.md, apps/ledger-live-mobile/src/screens/Swap/LiveApp/customHandlers/index.ts
- ...
add redirect to swap history to mobile
https://ledgerhq.atlassian.net/browse/LIVE-19457
---
=> fix(LIVE-19457): add redirect to swap history to mobile

.changeset/unlucky-beds-build.md, apps/ledger-live-mobile/src/screens/Swap/History/index.tsx
- ...
swap llm csv history export fix
https://ledgerhq.atlassian.net/browse/LIVE-19533
---
=> Fix/live 19533/llm swap export history 2nd fix

.changeset/honest-pans-unite.md, apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/SeedStep.tsx, apps/ledger-live-mobile/src/screens/SyncOnboarding/SyncOnboardingCompanion.tsx
=> [LIVE-18348][TS][Charon] Add new tracking event

.changeset/great-cooks-poke.md, libs/coin-tester-modules/coin-tester-solana/src/scenarii/solana.ts
- ...
App Solana 1.9.2 created after Donjon review.
---
=> test(coin-tester-solana): use app Solana 1.9.2

.changeset/pink-laws-deliver.md, libs/coin-modules/coin-tezos/src/network/bakers.test.ts, libs/coin-modules/coin-tezos/src/network/bakers.ts, libs/coin-modules/coin-tezos/src/network/bakers.whitelist-default.ts
- Tezos "Earn staking rewards" feature.
The PR fixes the Tezos "Earn staking rewards" feature by upgrading the Baking Bad API to the latest version.
|  [     Baking Bad API v2      ](https://api.baking-bad.org/v2/bakers)  | [     Baking Bad API v3      ](https://api.baking-bad.org/v3/bakers) |
https://ledgerhq.atlassian.net/browse/LIVE-19443
--- …
=> Fix Tezos "Earn staking rewards" feature.

.changeset/twelve-eagles-complain.md, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/ModularDrawerFlowManager.tsx, apps/ledger-live-desktop/src/newArch/utils/testnetCurrencies.ts, apps/ledger-live-desktop/src/newArch/utils/tests/testnetCurrencies.test.ts
- MAD assets list
Add test nets currency if dev mode is true. 
There's not much perf consideration as we will display testNet only for dev so it's quite limited and I don't think there is a faster way to get testNets currencies
https://github.com/user-attachments/assets/5c0dfe1a-3f85-4d4b-a581-09698abc4b25
https://github.com/user-attachments/assets/ea452961-0021-457f-8e63-88d80145009c
- **JIRA or GitHub link**: [LIVE-19778](https://ledgerhq.atlassian.net/browse/LIVE-19778)
--- …
=> :sparkles: (MAD) display testnet if dev mode is ON

e2e/desktop/tests/specs/add.account.spec.ts, e2e/mobile/specs/addAccount/addAccountAPT.spec.ts
=> [QAA] adding aptos add account

.changeset/pretty-chicken-yell.md, libs/live-dmk-desktop/src/transport/DeviceManagementKitTransport.ts, libs/live-dmk-mobile/src/transport/DeviceManagementKitTransport.ts
This reverts commit e72e65d6794b960b3f4abf78205a8c82cc4c22e5. In order to make apdu logs working with DMK transport
- ...
--- …
=> :loud_sound: (dmk): Fix exchange apdu logs

.changeset/brave-turkeys-compete.md, apps/ledger-live-mobile/src/components/RootNavigator/SwapNavigator.tsx, apps/ledger-live-mobile/src/components/Web3AppWebview/types.ts, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/Swap/LiveApp/WebView.tsx, apps/ledger-live-mobile/src/screens/Swap/LiveApp/index.tsx, apps/ledger-live-mobile/src/screens/Swap/LiveApp/navigationHandlers/useIsSwapTab.ts, apps/ledger-live-mobile/src/screens/Swap/LiveApp/navigationHandlers/useSwapAndroidHardwareBackPress.ts, apps/ledger-live-mobile/src/screens/Swap/LiveApp/navigationHandlers/useSwapHeaderNavigation.tsx, apps/ledger-live-mobile/src/screens/Swap/LiveApp/navigationHandlers/useSwapNavigationHelper.tsx, apps/ledger-live-mobile/src/screens/Swap/types.ts
- on new swap tab screen the navigation inside the webview has changed. it is now navigating the webview pages rather than closing the live app.
Update swap screen header and webview navigation. Replace static navigation screen title with header title based on webview and native navigation. Use native back button for in webview back navigation.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-19141
Updated navigation header - title per page and in-webview navigation with back button
--- …
=> feat(LIVE-19141): update swap screen header navigation

.changeset/seven-dryers-agree.md, libs/coin-modules/coin-aptos/src/__tests__/network/client.test.ts, libs/coin-modules/coin-aptos/src/network/client.ts
- "@ledgerhq/coin-aptos": minor
- "@ledgerhq/ledger-live-desktop": patch
Hotfix for Aptos add accounts.
Original PR: https://github.com/LedgerHQ/ledger-live/pull/10651
---
=> fix: aptos add accounts

apps/ledger-live-desktop/RELEASE_NOTES.md
- ...
Update release notes for hotfix.
---
=> docs: update release notes

.changeset/silly-apes-do.md, apps/ledger-live-mobile/src/screens/PTX/Earn/index.tsx
- earn live app gets the correct parameter
Fix mistake in LLM param passing where the length of an object was used incorrectly. 
---
=> fix: earn stake programs param not passed

.changeset/sharp-camels-juggle.md, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/CounterValueSelect.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/LanguageSelect.tsx, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/RegionSelect.tsx
- ...
Voici une description de PR claire et complète basée sur ton contexte :
---
This PR addresses excessive re-renders and redundant calls to `i18n.changeLanguage` when selecting a language or region in the **Settings > General** page.
**Issues fixed:**
* Prevents component from re-rendering unnecessarily during live synchronization processes, which previously caused UI freezes and prevented users from selecting a language or region smoothly.
* Adds a guard to ensure `i18n.changeLanguage` is only called when the selected language actually differs from the current language, avoiding redundant language change calls on page navigation.
* Improves overall user experience by stabilizing the language and region selection behavior.
---
1. Navigate to the **Settings > General** page.
2. Select …
=> bugfix(settings): avoid unnecessary re-renders and i18n language changes on selection

.changeset/sharp-bottles-unite.md, apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/SeedStep.tsx, apps/ledger-live-mobile/src/screens/SyncOnboarding/SyncOnboardingCompanion.tsx
- ...
- Add CTA links for Ledger Recovery Key
- **JIRA or GitHub link**: [LIVE-18341] 
---
[LIVE-18341]: https://ledgerhq.atlassian.net/browse/LIVE-18341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiL …
=> [LIVE-18341] Add CTA links for Ledger Recovery Key

.changeset/clean-lemons-pretend.md, apps/ledger-live-desktop/.storybook/main.ts, apps/ledger-live-desktop/.storybook/stub.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/ModularDrawerFlowManager.stories.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/ModularDrawerFlowManager.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/__mocks__/useSelectAssetFlow.mock.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/AssetSelection/AssetSelection.stories.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/NetworkSelection/NetworkSelection.stories.tsx
- ...
Demonstrates the modularisation parameter in storybook so users can visualise the various supported MAD configurations
https://github.com/user-attachments/assets/fbf80e73-9f31-479a-bf3e-469f9e44ac16
- **JIRA or GitHub link**: [LIVE-19228](https://ledgerhq.atlassian.net/browse/LIVE-19228)
--- …
=> feat(LLD): MAD storybook modularisation parameter

.changeset/heavy-horses-sniff.md, apps/ledger-live-mobile/src/screens/Swap/LiveApp/WebView.tsx
- ...
memorize tracking source so updates of the ref do not trigger webview reloads
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-19800
---
=> fix(LIVE-19800): prevent unexpected swap webview reload

.changeset/popular-ligers-love.md, apps/ledger-live-mobile/src/components/RootNavigator/SettingsNavigator.tsx, apps/ledger-live-mobile/src/components/RootNavigator/types/SettingsNavigator.ts, apps/ledger-live-mobile/src/const/navigation.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/Debug/index.tsx, apps/ledger-live-mobile/src/screens/Settings/Debug/Features/index.tsx
- ...
Modular Drawer +> Add a debug entrypoint 
https://github.com/user-attachments/assets/36bc310c-5d29-4f56-97be-ff535d7cdc85
- **JIRA or GitHub link**: [LIVE-19728] 
---
[LIVE-19728]: …
=> feat(debug): LLM - Modular Drawer - Add a debug entrypoint

.changeset/nice-snails-count.md, apps/ledger-live-desktop/src/newArch/hooks/useStake.ts, apps/ledger-live-desktop/src/newArch/hooks/useVersionedStakePrograms.ts, apps/ledger-live-desktop/src/renderer/analytics/segment.ts, apps/ledger-live-desktop/src/renderer/screens/earn/index.tsx, apps/ledger-live-mobile/src/analytics/segment.ts, apps/ledger-live-mobile/src/newArch/hooks/useStake/useStake.tsx, apps/ledger-live-mobile/src/newArch/hooks/useStake/useVersionedStakePrograms.ts, apps/ledger-live-mobile/src/screens/PTX/Earn/index.tsx, libs/ledgerjs/packages/types-live/src/feature.ts
- ...
- **JIRA or GitHub link**: [LIVE-19680](https://ledgerhq.atlassian.net/browse/LIVE-19680)
--- …
=> refactor: handle min version feature flag

.changeset/old-maps-lie.md, libs/ledger-live-common/src/apps/support.test.ts, libs/ledger-live-common/src/apps/support.ts, libs/ledger-live-common/src/hw/connectApp.ts
- ...
Allow min version per model on Firebase.
---
=> chore(llc): allow min version per model

.changeset/thick-trainers-ring.md, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/hooks/__tests__/useDetailedAccounts.test.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/hooks/useScanAccounts.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/AccountsAdded/hooks.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/AccountsAdded/types.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/ConnectYourDevice/index.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/utils/groupAccountsByAsset.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/utils/sortAccountsByFiatValue.ts, apps/ledger-live-desktop/src/newArch/utils/getBalanceAndFiatValue.ts, libs/ui/packages/react/src/pre-ldls/components/AccountItem/AccountItem.tsx
- add account
Force the CVS load during the scan device so we can use it during the add account. Also add balance value in the scan account items and success items so it's iso with the rest of the flow
https://github.com/user-attachments/assets/168bfd55-892d-4e1c-b8b6-aece76454254
If CVS can't be reached : 
https://github.com/user-attachments/assets/0a967141-2f4f-49ba-94a6-218efa0dbe62
- **JIRA or GitHub link**: [LIVE-19942](https://ledgerhq.atlassian.net/browse/LIVE-19942)
--- …
=> :sparkles: (LLD-AA) load cvs for the currency and display balance

.changeset/fast-points-invent.md, libs/live-signer-solana/src/LegacySignerSolana.ts, libs/live-signer-solana/tests/LegacySignerSolana.test.ts
- ...
Bump min trusted version to `1.9.2` for Solana
---
=> chore(live-signer-solana): bump app Solana min trusted version

.changeset/eleven-comics-march.md, libs/coin-tester-modules/coin-tester-evm/src/scenarii/sonic.ts
- ...
Anvil needs to fork the Blockchain to create a snapshot. This is not possible anymore with the ANKR node, since it does require an authentication that we prefer avoiding.
---
=> fix(coin-tester-evm): update Ethereum node URL in coin tester

.changeset/perfect-geese-teach.md, apps/ledger-live-desktop/src/renderer/components/Updater/Banner.tsx
- ...
“Install now and relaunch” link not clickable after switching language
- **JIRA or GitHub link**: [LIVE-20019] 
---
[LIVE-20019]: https://ledgerhq.atlassian.net/browse/LIVE-20019?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …
=> bugfix: fix banner click

.changeset/nasty-hornets-occur.md, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/FundAccount/components/ActionsContainer.tsx, libs/ui/packages/react/src/pre-ldls/components/AccountItem/AccountItem.stories.tsx, libs/ui/packages/react/src/pre-ldls/components/AccountItem/AccountItem.tsx
- fund account 
- accountItem
Fix some UI issues (margin, hover)
The UI is a bit tricky as it shoulnd't be aligned based on the hover
Alignment check
Demo
https://github.com/user-attachments/assets/0241b70c-aca2-4e0e-8c74-422fe704936c
- **JIRA or GitHub link**: [LIVE-19943](https://ledgerhq.atlassian.net/browse/LIVE-19943)
---
- …
=> :sparkles: (LLD-AA) fix layout fund accounts screen

.changeset/smooth-toes-grab.md, libs/coin-modules/coin-icon/src/__test__/unit/logic.unit.test.ts, libs/coin-modules/coin-icon/src/logic.ts
- ...
This is limit is present from the very beginning. However, the ICON team is not aware of such a limit in the protocol and I have been able to send more than 5000 ICX from a localnet.
--- …
=> fix(coin-icon): remove max amount limit

e2e/mobile/specs/swap/otherTestCases/swap.other.ts
- Modified runTooLowAmountForQuoteSwapsTest to get minimum amount using getMinimumAmount()
- This ensures tests use the correct minimum swap amount rather than hardcoded values
- Aligns mobile e2e tests with desktop e2e test pattern
- ...
--- …
=> QAA-690: Fix swap test to use minimum amount instead of hardcoded amount

apps/ledger-live-mobile/src/screens/SyncOnboarding/SyncOnboardingCompanion.tsx
- Update shadow config for charon lottie.
---
=> Fix: Recovery Key shadow adjustment

.changeset/weak-chicken-sniff.md, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/ModularDrawerAddAccountFlowManager.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/AccountsAdded/components/SuccessIcon.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- ...
Changes tick icon to white
Adds title to account selection page
PTX Flow (slightly mocked to highlight alignment improvements):
https://github.com/user-attachments/assets/08b59128-d932-43a9-96a0-ebf755765492
Add account flow
https://github.com/user-attachments/assets/72fc061a-af2a-4cb0-a27d-5729a345ada9
- **JIRA or GitHub link**: [LIVE-19941](https://ledgerhq.atlassian.net/browse/LIVE-19941)
---
- **The PR has been tested** thoroughly, and any potential edge cases have been considered and …
=> feat(LLD): account list selection refinements

.changeset/flat-pots-relax.md, .changeset/mean-pens-look.md, libs/ledger-live-common/src/hw/connectManager.ts, libs/live-dmk-shared/src/device-action/PrepareConnectManager/PrepareConnectManagerDeviceAction.test.ts, libs/live-dmk-shared/src/device-action/PrepareConnectManager/PrepareConnectManagerDeviceAction.ts
- ...
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-20101 and https://ledgerhq.atlassian.net/browse/LIVE-20106
---
- **There …
=> :bug: (dmk-shared) [LIVE-20101]: Support bootloader mode in PrepareManager device action

.github/workflows/release-prepare-hotfix.yml
=> ci: change the order where it opens PRs and merge them

.changeset/four-pugs-share.md, libs/coin-modules/coin-xrp/.eslintrc.js, libs/coin-modules/coin-xrp/src/logic/getTransactionStatus.ts
- ...
Remove cyclic imports within coin-xrp
---
=> fix: circular imports

e2e/mobile/page/trade/swap.page.ts
=> fix: readd delay for modal

libs/coin-framework/src/api/types.ts, libs/coin-modules/coin-aptos/src/__tests__/api/craftTransaction.unit.test.ts, libs/coin-modules/coin-aptos/src/__tests__/api/getBalance.unit.test.ts, libs/coin-modules/coin-aptos/src/__tests__/api/index.integ.test.ts, libs/coin-modules/coin-aptos/src/__tests__/logic/getBalances.test.ts, libs/coin-modules/coin-aptos/src/__tests__/network/client.test.ts, libs/coin-modules/coin-aptos/src/logic/craftTransaction.ts, libs/coin-modules/coin-aptos/src/logic/getBalances.ts, libs/coin-modules/coin-aptos/src/logic/transactionsToOperations.ts, libs/coin-modules/coin-aptos/src/network/client.ts, libs/coin-modules/coin-aptos/src/types/assets.ts, libs/coin-modules/coin-tron/src/api/index.test.ts, libs/coin-modules/coin-tron/src/bridge/getEstimateFees.ts, libs/coin-modules/coin-tron/src/logic/craftTransaction.integ.test.ts, libs/coin-modules/coin-tron/src/logic/craftTransaction.test.ts, libs/coin-modules/coin-tron/src/logic/craftTransaction.ts, libs/coin-modules/coin-tron/src/logic/estimateFees.test.ts, libs/coin-modules/coin-tron/src/logic/estimateFees.ts, libs/coin-modules/coin-tron/src/logic/getBalance.test.ts, libs/coin-modules/coin-tron/src/logic/getBalance.ts, libs/coin-modules/coin-tron/src/logic/listOperations.integ.test.ts, libs/coin-modules/coin-tron/src/network/trongrid/trongrid-adapters.test.ts, libs/coin-modules/coin-tron/src/network/trongrid/trongrid-adapters.ts
=> fix: remove standard and move it to type

.changeset/cyan-eyes-drum.md, libs/coin-modules/coin-tezos/src/bridge/getTransactionStatus.test.ts, libs/coin-modules/coin-tezos/src/bridge/getTransactionStatus.ts
- Tezos getTransactionStatus
- Tezos Delegate Modal
**Previously**, when delegating from an XTZ account with insufficient funds (e.g. < 0.0005 XTZ), the user was allowed to proceed to the signing step. Only afterward, a backend 500 error was returned, poorly interpreted and confusing in the UI.
**Instead** of letting the user sign a transaction that we already know will fail, this PR introduces a pre-check: if the account balance is lower than the estimated delegation fee (~0.0005 XTZ), the action is blocked before reaching the signing step.
<video src="https://github.com/user-attachments/assets/17b80a74-c787-4d76-b348-bb59906c6a65" controls playsinline muted style="max-width: 100%; height: auto;"></video>
<video src="https://github.com/user-attachments/assets/06becf85-98bf-489e-95b5-94683 …
=> fix: Error handling when trying to stake XTZ with a low amount

.changeset/stale-badgers-invent.md, libs/ui/packages/native/package.json, libs/ui/packages/native/src/pre-ldls/components/CryptoIcon/CryptoIcon.stories.tsx, libs/ui/packages/native/src/pre-ldls/components/CryptoIcon/CryptoIcon.tsx, pnpm-lock.yaml
- ...
add cryptoIcon in storybook native pre-ldls
- **JIRA or GitHub link**:[LIVE-19670]
---
[LIVE-19670]: https://ledgerhq.atlassian.net/browse/LIVE-19670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …
=> feat: add cryptoIcon in storybook native pre-ldls

.changeset/serious-walls-smash.md, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/__mocks__/useSelectAssetFlow.mock.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/__tests__/addAccountFlow.test.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/analytics/addAccount.types.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/ConnectYourDevice/index.tsx
- ...
Adds integration tests to newArch AddAccount flow
- **JIRA or GitHub link**: [LIVE-19944](https://ledgerhq.atlassian.net/browse/LIVE-19944)
---
[LIVE-19944]: …
=> feat(LLD): add account integration tests

.changeset/hip-geese-stare.md, libs/ui/packages/native/package.json, libs/ui/packages/native/src/pre-ldls/components/AssetItem/AssetItem.stories.tsx, libs/ui/packages/native/src/pre-ldls/components/AssetItem/AssetItem.tsx, libs/ui/packages/native/src/pre-ldls/components/AssetTypeList/AssetList.stories.tsx, libs/ui/packages/native/src/pre-ldls/components/AssetTypeList/AssetList.tsx, libs/ui/packages/native/src/pre-ldls/components/Tag/Tag.tsx, libs/ui/packages/native/src/pre-ldls/components/index.ts, libs/ui/packages/native/src/pre-ldls/components/sharedStoryBook.tsx, pnpm-lock.yaml
- ...
Add AssetList component in LLM ldls
- **JIRA or GitHub link**: [LIVE-19669]
---
[LIVE-19669]: https://ledgerhq.atlassian.net/browse/LIVE-19669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIj …
=> feat: Add AssetList component in LLM ldls

.changeset/stupid-beers-search.md, libs/coin-modules/coin-evm/src/api/index.ts, libs/coin-modules/coin-evm/src/logic/combine.test.ts, libs/coin-modules/coin-evm/src/logic/combine.ts, libs/coin-modules/coin-evm/src/logic/index.ts
- Alpacaization / Combine function
- **JIRA**: https://ledgerhq.atlassian.net/browse/LIVE-18659
---
=> feat(coin-evm): add alpaca `combine` method

.github/workflows/test-mobile-synthetics-reusable.yml
https://github.com/LedgerHQ/ledger-live-build/actions/runs/16142642607/job/45555634297#step:10:13
Adding platform prefix to artifact file name to avoid artifact name collision in the same run
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-19064
--- …
=> chore: add platform to the performance-report file to avoid collision

.changeset/khaki-starfishes-exercise.md, libs/coin-framework/src/api/types.ts, libs/ledger-live-common/src/bridge/generic-alpaca/signOperation.ts
- ...
Error sentry `sequence number too high`.
Fix by not fetching it twice but only once so it will stay the same
- **JIRA or GitHub link**: [LIVE-20217](https://ledgerhq.atlassian.net/browse/LIVE-20217)
--- …
=> fix: sequence number too high

.changeset/sweet-lobsters-happen.md, apps/ledger-live-mobile/src/components/WebPTXPlayer/CustomHandlers.ts
- ...
Custom handler was accidentally removed in this PR:
[https://github.com/LedgerHQ/ledger-live/commit/f5105d216264b2fd59fc66cf2b9b71f9ef6eb818#diff-88c0f26b7a477eead4d6923[…]de4bda0b32e978963630a59510L39](https://github.com/LedgerHQ/ledger-live/commit/f5105d216264b2fd59fc66cf2b9b71f9ef6eb818#diff-88c0f26b7a477eead4d6923082bc253aa61e64de4bda0b32e978963630a59510L39)
Re-adding so as to fix buy/sell
--- …
=> fix: buy sell close

.github/workflows/test-mobile-e2e-reusable.yml, e2e/mobile/helpers/commonHelpers.ts
- ...
https://github.com/LedgerHQ/ledger-live/actions/runs/16165740601
---
=> ci: update default speculos device

.changeset/poor-jobs-shave.md, .changeset/swift-pets-sell.md, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/hooks/useModularDrawerFlowState.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/Debug/index.tsx, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/ModularDrawer.tsx, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/__integrations__/modularDrawer.test.tsx, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/__mocks__/currencies.mock.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/__mocks__/useGroupedCurrenciesByProvider.mock.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/hooks/__tests__/__mocks__/modularDrawerMocks.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/hooks/__tests__/useAssets.test.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/hooks/__tests__/useModularDrawerFlowStepManager.test.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/hooks/__tests__/useModularDrawerState.test.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/hooks/__tests__/useProviders.test.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/hooks/useAssets.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/hooks/useModularDrawerFlowStepManager.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/hooks/useModularDrawerState.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/hooks/useProviders.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/screens/AssetSelection/index.tsx, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/screens/NetworkSelection/index.tsx, libs/ledger-live-common/.unimportedrc.json, libs/ledger-live-common/src/modularDrawer/utils/index.test.ts, libs/ledger-live-common/src/modularDrawer/utils/index.ts
- ...
This PR improves the asset and network selection flow by introducing better step transitions and enhanced back navigation. 
- **Improved asset and network selection logic** to ensure consistent behavior across different steps.
- **Dynamic step adjustment** based on the selected network to prevent invalid configurations and enhance user guidance.
- **Enhanced back navigation handling**, preserving user context and preventing unexpected resets when returning to previous steps.
- **Adjusted and improved tests** to reflect the updated logic and ensure more robust coverage.
https://github.com/user-attachments/assets/175c1ab2-f104-4543-8bf5-cbe46e4dbb0c
- [LIVE-19727](https://ledgerhq.atlassian.net/browse/LIVE-19727)
---
- **The code aligns with the …
=> feat(😈): handle asset and network selection

.changeset/sharp-islands-turn.md, libs/live-signer-evm/package.json, pnpm-lock.yaml
- ...
Fix for bug https://ledgerhq.atlassian.net/browse/LIVE-19531
Integration of DMK fix: https://ledgerhq.atlassian.net/browse/DSDK-865
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-19531
--- …
=> :bug: (signer-evm) [LIVE-19531]: Remove hardcoded list of ethereum plugins

.changeset/heavy-mails-check.md, apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/SyncOnboardingCompanion.tsx, apps/ledger-live-mobile/src/screens/SyncOnboarding/SyncOnboardingCompanion.tsx
- ...
- Fix un tracking issue in onboarding, now the tracking events will be emitted correctly.
- **JIRA or GitHub link**: [LIVE-20127]
---
[LIVE-20127]: https://ledgerhq.atlassian.net/browse/LIVE-20127?atlOrigin=eyJp …
=> [LIVE-20127] Fix un tracking issue in onboarding

pnpm-lock.yaml
=> chore: update pnpm-lock

CODEOWNERS
=> chore: update codeowners for LLC bridge

.changeset/ninety-nails-joke.md, libs/coin-modules/coin-sui/src/api/index.integration.test.ts, libs/coin-modules/coin-sui/src/bridge/buildTransaction.integration.test.ts, libs/coin-modules/coin-sui/src/bridge/buildTransaction.ts, libs/coin-modules/coin-sui/src/logic/craftTransaction.ts, libs/coin-modules/coin-sui/src/network/sdk.integration.test.ts, libs/coin-modules/coin-sui/src/network/sdk.test.ts, libs/coin-modules/coin-sui/src/network/sdk.ts
=> fix: sui send tokens issue

.changeset/short-ligers-matter.md, apps/ledger-live-mobile/package.json, libs/ledger-live-common/package.json, libs/ledgerjs/packages/hw-app-exchange/package.json, libs/live-dmk-desktop/package.json, libs/live-dmk-mobile/package.json, libs/live-dmk-shared/package.json, libs/live-signer-evm/package.json, pnpm-lock.yaml
- ...
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/DSDK-867
--- …
=> :bug: (common) [DSDK-867]: Fix current app detection for old firmwares

.changeset/ninety-nails-joke.md, libs/coin-modules/coin-sui/src/api/index.integration.test.ts, libs/coin-modules/coin-sui/src/bridge/buildTransaction.integration.test.ts, libs/coin-modules/coin-sui/src/bridge/buildTransaction.ts, libs/coin-modules/coin-sui/src/logic/craftTransaction.ts, libs/coin-modules/coin-sui/src/network/sdk.integration.test.ts, libs/coin-modules/coin-sui/src/network/sdk.test.ts, libs/coin-modules/coin-sui/src/network/sdk.ts
=> fix: sui send tokens hotfix

e2e/mobile/helpers/commonHelpers.ts, e2e/mobile/page/common.page.ts, e2e/mobile/page/liveApps/swapLiveApp.ts, e2e/mobile/page/trade/swap.page.ts, e2e/mobile/specs/swap/swap.ts
- ...
- Revert delay to 40s from 20s
- Ignore LI-FI a a selected provider due to issues
- Disable sync for iOS before selecting known device
- Fix issue with Cardano sign delegation transaction
--- …
=> fix: disabled sync for ios before selecting known device

.changeset/tough-mangos-invite.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/SwapWebViewDemo3.tsx
- ...
send kyc banner feature flag to swap live app
https://ledgerhq.atlassian.net/browse/LIVE-19841
---
=> feat(LIVE-19841): send kyc banner feature flag to swap live app

.changeset/sour-wolves-boil.md, libs/ledger-live-common/src/bridge/generic-alpaca/getAccountShape.ts
=> fix: xrp blockheight set to zero if new account

e2e/mobile/userdata/speculos-tests-app.json
=> Adding readOnlyModeEnabled: false in e2e json

.changeset/hot-kangaroos-buy.md, libs/coin-modules/coin-evm/package.json, libs/coin-modules/coin-polkadot/package.json, pnpm-lock.yaml
- ...
Remove two unused dev. dependencies.
---
=> deps: remove unused dependencies

.changeset/purple-bananas-marry.md, libs/ui/packages/native/src/pre-ldls/components/Search/Search.stories.tsx, libs/ui/packages/native/src/pre-ldls/components/Search/Search.tsx, libs/ui/packages/native/src/pre-ldls/hooks/index.ts, libs/ui/packages/native/src/pre-ldls/hooks/useDebouncedCallback.stories.tsx, libs/ui/packages/native/src/pre-ldls/hooks/useDebouncedCallback.ts, libs/ui/packages/react/src/pre-ldls/components/Search/Search.tsx
- native ui
Add useDebouncedCallback hook and search component to pre ldls UI for RN
It's the same as LLD but with rn event
https://github.com/user-attachments/assets/e16f9ec3-53ec-453c-9574-067b5b2eb964
- **JIRA or GitHub link**: [LIVE-19655](https://ledgerhq.atlassian.net/browse/LIVE-19655)
--- …
=> :sparkles: (LLM-UI) search component

.changeset/tidy-snails-know.md, apps/ledger-live-mobile/src/analytics/hooks/useTrackDmkErrorsEvents.test.ts, apps/ledger-live-mobile/src/analytics/hooks/useTrackDmkErrorsEvents.ts, apps/ledger-live-mobile/src/components/BleDevicePairingFlow/DmkBleDevicePairing.tsx, apps/ledger-live-mobile/src/components/DeviceAction/index.tsx, apps/ledger-live-mobile/src/components/GenericErrorView.tsx, apps/ledger-live-mobile/src/components/SupportLinkError.tsx, apps/ledger-live-mobile/src/components/TranslatedError/TranslatedError.tsx, apps/ledger-live-mobile/src/components/TranslatedError/hooks/useErrorLinks.tsx, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/SyncOnboarding/GenuineCheckErrorDrawer.tsx, libs/live-dmk-mobile/src/index.ts
- ...
- **JIRA or GitHub link**: [LIVE-19953] 
---
- **The PR …
=> :sparkles: (llm): Dmk error tracking

.changeset/cold-ravens-help.md, .changeset/tall-glasses-sparkle.md, libs/live-signer-evm/package.json, pnpm-lock.yaml
=> :sparkles: (signer-eth) [DSDK-871]: Add context-module gating

.changeset/lazy-seahorses-lay.md, apps/ledger-live-desktop/src/main/db/index.ts
- reset button 
removeEncryptionKey isn't working because it does a debounced save. Instead, we can just want to remove everything instead of saving anything, as we just reset the app
https://github.com/user-attachments/assets/9f2bc27c-3f60-48ce-8cd6-924193289e8f
- **JIRA or GitHub link**:[LIVE-20075](https://ledgerhq.atlassian.net/browse/LIVE-20075) 
--- …
=> :bug: (lld) delete LS key on hard reset

libs/coin-modules/coin-xrp/src/api/index.integ.test.ts
- ...
Fix integration tests, and remove some ESLint warnings passing by.
---
=> test: fix XRP integration tests

.changeset/fifty-glasses-cry.md, libs/ledger-live-common/src/bridge/crypto-assets/index.test.ts, libs/ledger-live-common/src/bridge/crypto-assets/index.ts, libs/ledger-live-common/src/bridge/crypto-assets/type.ts, libs/ledger-live-common/src/bridge/impl.ts
- No impact
- Definition of the `CryptoAssetStore` (common `cryptoassets` lib functions used by evm and solana)
- `CryptoAssetStore` "Singleton" 
- Setup function to the bridge
- Feature flag to switch between `cryptoassets` lib and CAL remote call
Live Hub will be responsible to implement the `CryptoAssetStore` and give the implementation to the bridge
The bridge will give the implementation then to the coin-framework, which will be used into `coin-evm` and `coin-solana`
For the moment, the method is set into the bridge, but not used
A feature flag has been set to be able to switch between the `cryptoassets` lib and the CAL remote calls
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/LIVE-19993
---
- **The code aligns with the requirements** described in the linked JIRA …
=> feature/LIVE-19993 Add Bridge  function

.changeset/moody-moose-notice.md, apps/ledger-live-mobile/src/datadog.ts, apps/ledger-live-mobile/src/index.tsx, apps/ledger-live-mobile/src/newArch/features/Market/screens/MarketList/index.tsx, apps/ledger-live-mobile/src/screens/Portfolio/index.tsx, apps/ledger-live-mobile/src/utils/constants.ts
- ...
- Fix tracing hosts and make sure that datadog headers are set in most of `ledger.com` based url (domains and subdomains) 
- Override loading time for MarketList tab screen rendering 
- Inject user id in the session rum to make it easy debugging user's pprevious 
--- …
=> fix: add MarketList loadingTime + improve session tracking

.github/workflows/test-mobile-synthetics-reusable.yml
Fix an issue introduced previously when adding slack notification for synthetics tests.
---
=> ci: pass slack bot token to optional

libs/coin-framework/src/sanction/index.integration.test.ts, libs/ledger-live-common/src/bridge/crypto-assets/index.test.ts, libs/ledger-live-common/src/bridge/crypto-assets/index.ts, libs/ledger-live-common/src/bridge/useBridgeTransaction.test.ts
=> fix: broken lld on develop

.changeset/young-forks-relax.md, libs/coin-modules/coin-sui/src/api/index.ts, libs/coin-modules/coin-sui/src/network/sdk.ts
- ...
SUI alpaca operation sync and time
- [LIVE-20402](https://ledgerhq.atlassian.net/browse/LIVE-20402)
---
[LIVE-20402]: https://ledgerhq.atlassian.net/browse/LIVE-20402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMD …
=> fix: sui operation sync and time

e2e/mobile/page/trade/swap.page.ts, e2e/mobile/specs/swap/otherTestCases/swap.other.ts, e2e/mobile/userdata/speculos-tests-app.json, e2e/mobile/userdata/speculos-x-other-account.json
- ...
- Fixed Swap History test 
- Fixed Swap with different seed tests
- **JIRA or GitHub link**: [QAA-724](https://ledgerhq.atlassian.net/browse/QAA-724)
- [CI_RUN](https://github.com/LedgerHQ/ledger-live/actions/runs/16370265887)
--- …
=> fixed swap tests

.changeset/grumpy-bobcats-exist.md, libs/coin-modules/coin-solana/src/__tests__/fixtures/helpers.fixture.ts, libs/coin-modules/coin-solana/src/__tests__/scan-accounts.test.ts, libs/coin-modules/coin-solana/src/network/chain/account/tokenExtensions.ts
- ...
Also enriching our test helpers, passing by.
---
=> bugfix(coin-solana): do not reject unknown SPL 2022 extensions

.changeset/sweet-planets-drop.md, apps/ledger-live-desktop/src/renderer/screens/accounts/AccountGridItem/Header.tsx
- accounts grid layout token tooltip
Since the ts migration this has never been changed so basically it's not working since that date
|<img width="236" height="134" alt="image" src="https://github.com/user-attachments/assets/6007a0f7-9bb4-48b7-85e3-eb0b271a4be7" />|<img width="379" height="188" alt="image" src="https://github.com/user-attachments/assets/a1dba7ac-742b-41d5-89d6-92b90fade410" />|
- **JIRA or GitHub link**: [LIVE-20416](https://ledgerhq.atlassian.net/browse/LIVE-20416)
--- …
=> :bug: (lld) account grid tooltip

libs/ledger-live-common/src/families/hedera/__snapshots__/bridge.integration.test.ts.snap
- ...
This PR updates bridge.integration.test.ts.snap based on successful `pnpm common ci-test-integration hedera` run:
---
=> test: Hedera bridge.integration.test snapshot update

e2e/desktop/tests/specs/swap.other.spec.ts, libs/ledger-live-common/src/e2e/families/osmosis.ts, libs/ledger-live-common/src/e2e/speculos.ts
=> chore: enable swap velora redirection test

.changeset/tame-hounds-end.md, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/Debug/index.tsx
- ...
Rework MAD debug screen
---
=> chore(LLM): Rework MAD debug screen

.changeset/fifty-panthers-relax.md, libs/coin-modules/coin-evm/src/api/index.integ.test.ts, libs/coin-modules/coin-evm/src/logic/craftTransaction.test.ts, libs/coin-modules/coin-evm/src/logic/craftTransaction.ts, libs/coin-modules/coin-evm/src/network/node/types.ts
- ...
Craft transaction is failing because fee data is missing. This fixes it and takes the opportunity to add EIP-1559 support.
---
=> feat(coin-evm): support EIP-1559 in `craftTransaction`

.changeset/dull-zebras-fly.md, libs/ui/packages/native/src/pre-ldls/libs/index.ts
- ...
Rework useTokens to handle light & dark correctly
https://github.com/user-attachments/assets/c0101d35-c28a-4a24-8a3b-f3169fafb30e
- **JIRA or GitHub link**: [LIVE-20486](https://ledgerhq.atlassian.net/browse/LIVE-20486) 
--- …
=> chore(LLM): rework useTokens to handle light & dark correctly

.changeset/moody-eggs-talk.md, libs/ui/packages/react/src/components/tabs/Chip/Chip.stories.tsx, libs/ui/packages/react/src/components/tabs/Chip/index.tsx
- ...
Update chip styling - example in buy/sell ui
Before
After (Light and Dark)
- [LIVE-20213](https://ledgerhq.atlassian.net/browse/LIVE-20213)
---
[LIVE-20213]: …
=> feat(LIVE-20213): update react ui chip styling

CODEOWNERS
- ...
Add Cloud Wallet team as code owners on coin framework API, as discussed with coin-integration team.
---
=> chore: add Cloud Wallet team as code owners on coin framework API

apps/ledger-live-mobile/src/screens/Fees/FeeContainer.tsx, e2e/desktop/tests/page/swap.page.ts, e2e/desktop/tests/specs/swap.other.spec.ts, e2e/mobile/page/liveApps/swapLiveApp.ts, e2e/mobile/specs/swap/otherTestCases/swap.other.ts, e2e/mobile/specs/swap/otherTestCases/swapNetworkFeesAboveAccountBalance.spec.ts
- ...
_Added swap test
- **JIRA or GitHub link**: [QAA-715](https://ledgerhq.atlassian.net/browse/QAA-715)
- [LLM_RUN](https://github.com/LedgerHQ/ledger-live/actions/runs/16412486232)
- [LLD_RUN](https://github.com/LedgerHQ/ledger-live/actions/runs/16413102741)
--- …
=> [SWAP] New test cases on low amount and error management

apps/ledger-live-mobile/src/AppProviders.tsx, apps/ledger-live-mobile/src/components/Button.tsx, apps/ledger-live-mobile/src/context/ButtonUseTouchableContext.ts
- ...
Drops ButtonUseTouchableContext and defaults ButtonWrapped's useTouchable to`true`.
- **JIRA**: [LIVE-19852](https://ledgerhq.atlassian.net/browse/LIVE-19852)
---
[LIVE-19852]: …
=> chore/mobile: drop ButtonUseTouchableContext

apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/FeesDrawerLiveApp/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/components/RootNavigator/FeesNavigator.tsx, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/screens/Fees/index.tsx
- ...
- add description to the network fees drawers
https://ledgerhq.atlassian.net/browse/LIVE-20336
---
=> feat(live-20336): add description to the network fees drawers

.changeset/odd-bags-travel.md, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/__tests__/modules.test.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/NetworkSelection/NetworkSelection.stories.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/NetworkSelection/modules/createNetworkConfigurationHook.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/NetworkSelection/modules/useLeftAccountsModule.tsx, apps/ledger-live-desktop/src/newArch/features/__mocks__/useSelectAssetFlow.mock.ts
- ...
Adds APY component to the MAD network page
- **JIRA or GitHub link**: [LIVE-20294](https://ledgerhq.atlassian.net/browse/LIVE-20294)
---
[LIVE-20294]: …
=> feat(LLD): integrate APY component into MAD network page

.changeset/many-avocados-hide.md, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/__tests__/modules.test.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/AssetSelection/AssetSelection.stories.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/AssetSelection/modules/createAssetConfigurationHook.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/AssetSelection/modules/useLeftApyModule.tsx
- ...
Integrates APY component into asset page left wallet API configuration 
- **JIRA or GitHub link**: [LIVE-20293](https://ledgerhq.atlassian.net/browse/LIVE-20293)
---
[LIVE-20293]: …
=> feat(LLD): integrate APY component into MAD asset page

.changeset/unlucky-chairs-marry.md, libs/coin-modules-monitoring/package.json, libs/coin-modules-monitoring/src/index.test.ts, libs/coin-modules-monitoring/src/index.ts, pnpm-lock.yaml
- ...
Add test flow inside the monitoring module, setting check points to be sent to Datadog.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-20143
---
=> test(coin-modules-monitoring): set breaks points between tests

.changeset/cyan-rocks-worry.md, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/ModularDrawer/constants.ts, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- ...
Add feature flag
- **JIRA or GitHub link**: [LIVE-20364]
---
[LIVE-20364]: https://ledgerhq.atlassian.net/browse/LIVE-20364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …
=> ✨ LLD - Add lldModularDrawerBackendData FF

.changeset/witty-gorillas-glow.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Navbar/index.tsx, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/index.tsx, libs/ui/packages/react/src/components/tabs/Chip/index.tsx
- ...
Change the swap tabs to use the react ui chips. With a slight amendment on the border radius.
Before:
After:
- [LIVE-20213](https://ledgerhq.atlassian.net/browse/LIVE-20213)  
---
[LIVE-20213]: …
=> feat: update swap nav bar

.changeset/smart-penguins-talk.md, apps/ledger-live-mobile/android/app/src/main/AndroidManifest.xml, apps/ledger-live-mobile/android/build.gradle, apps/ledger-live-mobile/src/components/KeyboardView.tsx, apps/ledger-live-mobile/src/components/TabBar/CustomTabBar.tsx, apps/ledger-live-mobile/src/logic/keyboardVisible.ts, apps/ledger-live-mobile/src/screens/AccountSettings/EditAccountName.tsx, apps/ledger-live-mobile/src/screens/MyLedgerDevice/AppsScreen.tsx, apps/ledger-live-mobile/src/screens/Platform/v2/Catalog/CatalogSection.tsx, apps/ledger-live-mobile/src/screens/Platform/v2/Catalog/Layout.tsx, patches/react-native-fast-pbkdf2@0.3.1.patch, pnpm-lock.yaml
Upgrade Android build target from `34` to `35`. The upgrade creates a regression on Android when interacting with text inputs and the keyboard is displayed. This upgrade includes a fix for these regressions.
Tested manually on:
- Android 15
- Android 14  to ensure regression fixes do not impact lower versions.
- iOS 18 to ensure regression fixes do not impact iOS versions.
Should be monitored carefully since an SDK upgrade can cause many sneaky, "hard-to-find" or invisible modifications.  
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/LIVE-20066
---
- **The PR description documents the changes** made and explains any technical trade-offs or design decisions. …
=> build: upgrade build target for android with corresponding required fixes

.changeset/olive-shrimps-learn.md, libs/coin-tester-modules/coin-tester-polkadot/src/scenarii/Polkadot.ts
- ...
Polkadot coin tester is constantly failing. Updating its scenarios.
---
=> fix(coin-tester-polkadot): repair coin tester Polkadot

e2e/desktop/tests/page/swap.page.ts
=> fix: swap tests following UI rewamp

.changeset/blue-ligers-smoke.md, apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-mobile/src/locales/en/common.json
- ...
add unknown tooltip
https://ledgerhq.atlassian.net/browse/LIVE-18521
---
=> fix(LIVE-18521): add unknown tooltip

.changeset/wet-apples-serve.md, libs/coin-modules/coin-sui/src/network/sdk.test.ts, libs/coin-modules/coin-sui/src/network/sdk.ts
- coin modules, SUI, ALPACA only
In Alpaca SUI `listOperations`, all assets are mapped to native coin.
---
=> fix(SUI): fix token mapped to native coin in ALPACA `listOperations`

e2e/desktop/tests/page/swap.page.ts
=> fix: swap amount digits number

.changeset/dirty-lemons-relate.md, libs/coin-modules/coin-sui/package.json, libs/coin-modules/coin-vechain/package.json, pnpm-lock.yaml
- ...
No need to embed `coin-tester` as a dependency here.
---
=> deps(coin-vechain): remove `coin-tester` from the dependencies

.changeset/lucky-foxes-relate.md, apps/ledger-live-mobile/__tests__/test-renderer.tsx, apps/ledger-live-mobile/src/AppProviders.tsx, apps/ledger-live-mobile/src/actions/toast.ts, apps/ledger-live-mobile/src/components/CustomImage/CustomImageBottomModal.tsx, apps/ledger-live-mobile/src/components/Nft/NftGallery/NftList.hook.ts, apps/ledger-live-mobile/src/components/TabBar/TransferDrawer.tsx, apps/ledger-live-mobile/src/components/Toast/Toast.tsx, apps/ledger-live-mobile/src/logic/postOnboarding/useCompleteAction.ts, apps/ledger-live-mobile/src/reducers/index.ts, apps/ledger-live-mobile/src/reducers/toast.ts, apps/ledger-live-mobile/src/reducers/types.ts, apps/ledger-live-mobile/src/screens/EditDeviceName.tsx, apps/ledger-live-mobile/src/screens/NotificationCenter/Snackbar/Snackbar.tsx, apps/ledger-live-mobile/src/screens/NotificationCenter/Snackbar/SnackbarContainer.tsx, apps/ledger-live-mobile/src/screens/ReceiveFunds/03-Confirmation.tsx, apps/ledger-live-mobile/src/screens/Settings/Debug/Features/Snackbars.tsx
- ...
Migrates toast provider from context provider to redux
| lockscreen example | devtools example | 
|--|--|
| ![Kapture 2025-07-25 at 14 39 51](https://github.com/user-attachments/assets/418acb8b-88fd-4555-ab59-f19b2da8a21a) | ![Kapture 2025-07-25 at 14 41 33](https://github.com/user-attachments/assets/204ac9dd-f861-4616-a575-88460df950b6) |
- **JIRA or GitHub link**: [LIVE-19859](https://ledgerhq.atlassian.net/browse/LIVE-19859)
--- …
=> feat(LLM): migrate toast provider to redux

.changeset/new-pets-vanish.md, libs/coin-modules/coin-tron/src/logic/getBalance.integ.test.ts, libs/coin-modules/coin-tron/src/logic/listOperations.integ.test.ts
- ...
Fix tron test and add missing changeset from [PR](https://github.com/LedgerHQ/ledger-live/pull/10826)
---
=> fix: Tron integ tests

.changeset/fresh-drinks-complain.md, libs/coin-modules/coin-aptos/.unimportedrc.json, libs/coin-modules/coin-aptos/package.json, libs/coin-modules/coin-aptos/src/__tests__/network/client.test.ts, libs/coin-modules/coin-aptos/src/network/client.ts, libs/coin-modules/coin-aptos/src/network/graphql/queries.ts, libs/coin-modules/coin-aptos/src/network/graphql/types.ts, libs/coin-modules/coin-aptos/src/preload.ts, pnpm-lock.yaml
- ...
- Update Aptos TS SDK
- Add client version headers for Aptos coin module
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-20609
---
=> fix: update aptos sdk

.github/workflows/test-mobile-e2e-reusable.yml
=> fix: fix typo with composites branch name

.github/workflows/test-mobile-e2e-reusable.yml, apps/ledger-live-mobile/scripts/e2e-ci.mjs
- Add conditional logic to only include --record-videos failing flag for non-mock tests
- Improves performance and reduces resource usage for mock test runs
- Maintains video recording functionality for e2e tests
- ...
---
- **The PR …
=> feat: disable video recording for mock tests in e2e-ci script

.changeset/chilled-bottles-punch.md, apps/ledger-live-mobile/src/families/aptos/AccountBalanceSummaryFooter.tsx, libs/coin-modules/coin-aptos/src/network/graphql/queries.ts
=> fix: aptos validators query

CODEOWNERS
- ...
change the ownership of swap types to ptx team
---
=> chore(change-swap-codeowner): change the ownership

.changeset/long-toys-end.md, e2e/desktop/tests/specs/delegate.spec.ts, libs/coin-modules/coin-cardano/src/utils.ts
- ...
Change the default validator by LBF 4
- **JIRA or GitHub link**: [LIVE-20564](https://ledgerhq.atlassian.net/browse/LIVE-20564)
---
[LIVE-20564]: https://ledgerhq.atlassian.net/browse/LIVE-20564?atlOrigin=eyJpIj …
=> Change  Cardano default validator to LBF4

e2e/desktop/tests/page/earn.dashboard.page.ts, e2e/desktop/tests/specs/earn.spec.ts
=> fix: remove check on earn live app

.changeset/sharp-singers-double.md, .changeset/sour-cherries-sell.md, apps/ledger-live-desktop/src/renderer/families/stellar/operationDetails.tsx, apps/ledger-live-mobile/src/families/stellar/operationDetails.tsx, libs/coin-modules/coin-stellar/src/logic/listOperations.unit.test.ts, libs/coin-modules/coin-stellar/src/network/serialization.ts, libs/coin-modules/coin-stellar/src/types/bridge.ts, libs/ledger-live-common/.unimportedrc.json, libs/ledger-live-common/src/families/stellar/__snapshots__/bridge.integration.test.ts.snap, libs/ledger-live-common/src/families/stellar/ui.ts
- stellar coin module
- stellar operation details UI LLM+LLD
Memo details for stellar were lost during memo refactoring, but LES requires it
- https://ledgerhq.atlassian.net/browse/BACK-9407
---
=> fix(BACK-9407): [coin-modules][stellar] fix memo details lost

apps/ledger-live-desktop/static/i18n/en/app.json, apps/ledger-live-desktop/static/i18n/th/app.json, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/locales/th/common.json
- ...
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-20695
--- …
=> fix: update wording for geoblocking

e2e/desktop/tests/page/swap.page.ts
=> fix: swap quote card locators

.changeset/yellow-months-sniff.md, apps/cli/src/live-common-setup.ts
- No impact
Setup CryptoAssetsStore in CLI
Mainly to fix E2E tests
- **JIRA or GitHub link**:  https://ledgerhq.atlassian.net/browse/LIVE-20706
---
=> Setup CryptoAssetsStore in CLI

.changeset/beige-bears-stare.md, apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/LiveAppSDKLogic.ts, apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/WalletAPIWebview.tsx, apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/helpers.ts, apps/ledger-live-desktop/src/renderer/drawers/DataSelector/SelectAccountAndCurrencyDrawer.tsx, apps/ledger-live-desktop/src/renderer/drawers/DataSelector/logic.ts, apps/ledger-live-desktop/src/renderer/screens/stake/index.tsx
- account selection/asset selection old drawer
Add analytics in the old drawer so we can A/B test easily 
+ Removal of some useless type casting
https://github.com/user-attachments/assets/13355a4d-7062-42fd-aa34-34e599a416fb
- **JIRA or GitHub link**: [LIVE-20510](https://ledgerhq.atlassian.net/browse/LIVE-20510)
--- …
=> :chart_with_upwards_trend: LLD - AssetSelection drawer tracking

libs/ledger-live-common/src/families/hedera/__snapshots__/bridge.integration.test.ts.snap
- ...
This PR updates bridge.integration.test.ts.snap based on successful `pnpm common ci-test-integration hedera` run:
---
=> test: Hedera bridge.integration.test snapshot update v3

.changeset/nice-buses-press.md, apps/ledger-live-mobile/src/utils/constants.ts
- ...
Nothing special ! just support xrp and cardano as custom attr for Datadog custom view
---
=> add xrp and cardano to the topchain list (product req)

.changeset/rare-mugs-study.md, libs/coin-modules/coin-evm/src/api/index.integ.test.ts
- ...
- `craftTransaction`: test legacy and eip1559
- `getBalance`: test empty balance on pristine account
- `listOperations`: test no operations on pristine account
- `estimateFees`: test legacy and eip1559
- https://ledgerhq.atlassian.net/browse/LIVE-20491
- https://ledgerhq.atlassian.net/browse/LIVE-20492
- https://ledgerhq.atlassian.net/browse/LIVE-20493
- https://ledgerhq.atlassian.net/browse/LIVE-20494
--- …
=> test(coin-evm): improve Alpaca integration tests

libs/ledger-live-common/src/e2e/enum/DeviceLabels.ts, libs/ledger-live-common/src/e2e/families/evm.ts, libs/ledger-live-common/src/e2e/speculos.ts
=> fix: for e2e tests: nano titles update

.github/workflows/coin-monitoring-manual.yml, libs/coin-modules-monitoring/package.json, libs/coin-modules-monitoring/tsconfig.json, package.json, pnpm-lock.yaml, tools/actions/composites/monitor/action.yml
- ...
Add Github action to run `coin-modules-monitoring`.
---
=> test(ci): launch `coin-modules-monitoring` in CI

.github/workflows/test-ui-e2e-only-desktop.yml
=> ci: removing unused input

CODEOWNERS
=> chore: update coin-vechain codeowners

libs/coin-modules/coin-hedera/src/api/utils.ts, libs/coin-modules/coin-hedera/src/bridge/buildOptimisticOperation.ts, libs/coin-modules/coin-hedera/src/bridge/serialization.test.ts, libs/coin-modules/coin-hedera/src/bridge/utils.integration.test.ts, libs/coin-modules/coin-hedera/src/test/bot-specs.ts, libs/coin-modules/coin-hedera/src/test/speculos-deviceActions.ts, libs/ledger-live-common/src/families/hedera/__snapshots__/bridge.integration.test.ts.snap
- fixed logic of FEES operations for HTS token transfer
- fixed linting errors in tests
- added possibility to test HTS token association and transfer with `ledger-live bot`
- updated bridge test snapshot
This PR fixes linting errors in tests and resolves a broken "FEES" operation that was previously not displayed. It also adds HTS tests to `ledger-live bot` and updates the bridge snapshot to address failing integration tests.
--- …
=> fix: send/receive HTS tokens - HTS in bot and fixes (part 4) 

.changeset/twelve-ties-jump.md, apps/ledger-live-mobile/.eslintrc.js, apps/ledger-live-mobile/src/components/AssetCentricGraphCard.tsx, apps/ledger-live-mobile/src/components/CurrencyBackgroundGradient.tsx, apps/ledger-live-mobile/src/components/CurrencyHeaderLayout.tsx, apps/ledger-live-mobile/src/components/GraphCard.tsx, apps/ledger-live-mobile/src/contentCards/layouts/carousel/pagination/bullets.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/ScanDeviceAccounts/components/ScanDeviceAccountsFooter/index.tsx, apps/ledger-live-mobile/src/newArch/features/Web3Hub/components/AnimatedBar/index.tsx, apps/ledger-live-mobile/src/screens/MyLedgerDevice/Device/StorageBarItem.tsx, apps/ledger-live-mobile/src/screens/NpsRatingsModal/index.tsx, apps/ledger-live-mobile/src/screens/RatingsModal/index.tsx, apps/ledger-live-mobile/src/screens/ReceiveFunds/03-Confirmation.tsx, apps/ledger-live-mobile/src/screens/ReceiveFunds/ReceiveSecurityModal/index.tsx, apps/ledger-live-mobile/src/screens/ReceiveFunds/SanctionedAccountModal/index.tsx, apps/ledger-live-mobile/src/screens/Settings/Accounts/TokenContextualModal.tsx
- ...
To properly use reanimated, we can add an ESLint [rule](https://docs.swmansion.com/react-native-reanimated/docs/guides/web-support/#eslint-support)
This way, we will be able to follow the correct pattern + test the animated components safely
However we can still pass no dependencies as it's not mandatory 
--- …
=> :wrench: (llm) add eslint rule for reanimated hooks

.changeset/yellow-cobras-wave.md, apps/ledger-live-mobile/src/newArch/components/QueuedDrawer/temp/QueuedDrawerGorhom.tsx, apps/ledger-live-mobile/src/newArch/components/QueuedDrawer/temp/useQueuedDrawerGorhom.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/ModularDrawerFlowManager/useScreenTransition.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/hooks/useModularDrawerState.ts
=> :bug: (llm) fix new queuedDrawer

.changeset/brown-peas-knock.md, apps/ledger-live-desktop/tests/specs/services/wallet-api.spec.ts, libs/coin-modules/coin-solana/src/buildTransaction.ts
- ...
- **JIRA or GitHub link**: LIVE-20778
---
- **The PR has …
=> fix: set blockhash on rawtransaction

.changeset/late-spoons-do.md, apps/ledger-live-desktop/package.json, apps/ledger-live-desktop/src/renderer/createStore.ts, apps/ledger-live-desktop/src/renderer/middlewares/analytics.ts, apps/ledger-live-desktop/src/renderer/middlewares/db.ts, apps/ledger-live-desktop/src/renderer/middlewares/logger.ts, apps/ledger-live-desktop/src/renderer/middlewares/utils.ts, apps/ledger-live-mobile/ios/Podfile.lock, pnpm-lock.yaml
- ...
Setup Redux Toolkit on LLD and use it to create the store instead of the old deprecated method from redux
Added a `isActionWithType` function to ensure the type of the existing middlewares now that we are using the `Middleware` type imported from `@reduxjs/toolkit` instead of the one we were previously imported from `redux`
- **JIRA or GitHub link**: [LIVE-20415]
---
- **Any new …
=> ✨  LLD - Setup RTK

libs/ledger-live-common/src/families/canton/bridge.integration.test.ts
- ...
Remove bridge test (failure), coin-canton is not implemented yet
- **JIRA or GitHub link**: [https://ledgerhq.atlassian.net/browse/LIVE-20864](https://ledgerhq.atlassian.net/browse/LIVE-20864)
---
=> remove bridge test for : canton

.changeset/shy-cats-rush.md, apps/ledger-live-desktop/src/renderer/actions/constants.ts, apps/ledger-live-desktop/src/renderer/actions/settings.ts, apps/ledger-live-desktop/src/renderer/hooks/useBraze.ts, apps/ledger-live-desktop/src/renderer/hooks/useNotifications.ts, apps/ledger-live-desktop/src/renderer/reducers/settings.test.ts, apps/ledger-live-desktop/src/renderer/reducers/settings.ts, apps/ledger-live-desktop/src/types/dynamicContent.ts, libs/ledger-live-common/src/braze/anonymousUsers.ts
Cherry picked commit to go into release
- **JIRA**:  [LIVE-20867](https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/463?selectedIssue=LIVE-20867)
[LIVE-20867]: https://ledgerhq.atlassian.net/browse/LIVE-20867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Release/LIVE-20867: prevent infinite rendering cycles when purging anonymous notifications

.changeset/strange-hats-beam.md, libs/coin-modules/coin-evm/src/api/index.ts, libs/coin-modules/coin-evm/src/logic/estimateFees.test.ts, libs/coin-modules/coin-evm/src/logic/estimateFees.ts
- ...
Add optional `customFees` parameters to use as fallback in `estimateFees`
---
=> chore(coin-evm): adapt `estimateFees` parameters on `coin-evm`

.changeset/tame-cherries-camp.md, apps/ledger-live-desktop/src/renderer/createStore.ts
- ...
The immutable checks would sometime crash the app as such: 
Next step is: try to avoid mutating bitcoinresources (PR is [here](https://github.com/LedgerHQ/ledger-live/pull/11381)).
--- …
=> chore: (rtk) disable immutable checks in middleware when creating stores

.changeset/eight-mugs-hug.md, apps/ledger-live-mobile/src/screens/NotificationCenter/NotificationsProvider.tsx
- Notification provider refactored.
- Everything should behave the same.
The ticket references the creation of a reducer, but this isn't necessary, as the state already exists there. However, there was the opportunity to memoize the result of the existing selectors to prevent re-renders and create a stable reference to the context provided.
- **JIRA**: [LIVE-19865](https://ledgerhq.atlassian.net/browse/LIVE-19865)
--- …
=> LIVE-19865/refactor: improve NotificationsProvider's performance

libs/ledger-live-common/src/e2e/enum/DeviceLabels.ts, libs/ledger-live-common/src/e2e/families/solana.ts, libs/ledger-live-common/src/e2e/speculos.ts
- ...
CI RUN: https://github.com/LedgerHQ/ledger-live/actions/runs/17123815757/job/48573461816
---
=> test: fix solana e2e - new flow

.changeset/silly-grapes-talk.md, apps/ledger-live-mobile/src/components/WebPTXPlayer/CustomHandlers.ts, libs/exchange-module/src/types.ts, libs/ledger-live-common/src/exchange/swap/api/v5/actions.ts, libs/ledger-live-common/src/exchange/swap/types.ts
- ...
fix: llc swap change amountInAtomicUnit type to BigNumber for better precision
https://github.com/user-attachments/assets/99af3add-fb66-4bed-90a9-9697b02c4617
https://ledgerhq.atlassian.net/browse/LIVE-20841 
--- …
=> fix(live-20333): llc swap - change amountInAtomicUnit type to BigNumber  

apps/ledger-live-desktop/src/renderer/families/hedera/ReceiveWithAssociationModal/Body.tsx, apps/ledger-live-desktop/src/renderer/families/hedera/ReceiveWithAssociationModal/steps/StepAssociationConfirmation.tsx, apps/ledger-live-desktop/src/renderer/families/hedera/ReceiveWithAssociationModal/types.ts, apps/ledger-live-mobile/src/families/hedera/AssociateTokenFlow/AssociationInsufficientFundsError.tsx
- ...
This PR addresses code review feedback from https://github.com/LedgerHQ/ledger-live/pull/10672
---
=> fix: send/receive HTS code review changes

.changeset/perfect-icons-type.md, libs/coin-modules/coin-evm/src/api/index.ts, libs/coin-modules/coin-evm/src/logic/common.ts, libs/coin-modules/coin-evm/src/logic/index.ts, libs/coin-modules/coin-evm/src/logic/validateIntent.test.ts, libs/coin-modules/coin-evm/src/logic/validateIntent.ts
- ...
Implement `validateIntent` for EVM.
---
=> feat(coin-evm): implement `validateIntent`

.github/workflows/test-mobile-synthetics-reusable.yml
- ...
Fix the synthetic test reusable workflow condition that flag the release workflow as failed (even if not)
---
=> chore: fix synthetic tests reusable workflow bool condition

e2e/mobile/specs/buySell/buySell.ts
- ...
- Skipped buySell automated tests for IOS
- [CI_RUN](https://github.com/LedgerHQ/ledger-live/actions/runs/17160307626)
---
=> skipped buySell tests for ios

.changeset/eighty-shirts-matter.md, apps/ledger-live-mobile/src/datadog.ts, apps/ledger-live-mobile/src/index.tsx, apps/ledger-live-mobile/src/newArch/features/Market/screens/MarketList/index.tsx, apps/ledger-live-mobile/src/screens/Portfolio/index.tsx, apps/ledger-live-mobile/src/sentry.ts, apps/ledger-live-mobile/src/types/helpers.ts, apps/ledger-live-mobile/src/utils/datadogUtils.ts, apps/ledger-live-mobile/src/utils/index.ts
- ...
Add feature flags in DD Event Mappers. 
A small code refactoring for using the same Sentry's tags object builder between both to avoid code duplication.
https://ledgerhq.atlassian.net/browse/LIVE-21019
--- …
=> chore: additional infos in datadog events

.changeset/rude-icons-breathe.md, apps/ledger-live-desktop/ledger-live-desktop-deeplinks.html, apps/ledger-live-desktop/package.json, apps/ledger-live-mobile/ledger-live-mobile-deeplinks.html, apps/ledger-live-mobile/package.json, knip.json, pnpm-lock.yaml
- ...
This PR updates and rebuilds the deeplinks testing tool to provide a complete list of deeplinks and make testing them much easier. The tool now dynamically generates content from JavaScript configuration, making it more maintainable and user-friendly.
```javascript
const appConfig = {
title: "Ledger Live Desktop DeepLinks",
deeplinks: [
// Add your new deeplink here
{
section: "Your Section Name",
title: "Your Deeplink Title",
url: "ledgerlive://your-deeplink-path",
description: "Description of what this deeplink does",
examples: [
"ledgerlive://your-deeplink-path?param=value",
"ledgerlive://your-deeplink-path/alternative",
],
},
],
};
```
- **Desktop**: `apps/ledger-live-desktop/ledger-live-desktop-deeplinks.html`
- **Mobile**: …
=> chore: Deeplinks tool for LLM & LLD

.changeset/silly-turtles-happen.md, apps/ledger-live-mobile/src/components/Web3AppWebview/helpers.ts
- Source and Flow in analytics are correctly set on MAD for Buy/Swap/Sell
Source and Flow in analytics are correctly set on MAD for Buy/Swap/Sell
- **JIRA or GitHub link**: [LIVE-20433]
https://github.com/user-attachments/assets/0f53d689-7d2d-453a-9834-24a7681be995
--- …
=> fix: LLM MAD Analytics

.changeset/proud-parents-doubt.md, apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/assets/ContinueOnApex.tsx, apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/assets/ContinueOnEuropa.tsx, apps/ledger-live-desktop/src/renderer/components/SyncOnboarding/Manual/assets/ContinueOnStax.tsx, apps/ledger-live-mobile/src/screens/SyncOnboarding/assets/ContinueOnApex.tsx, apps/ledger-live-mobile/src/screens/SyncOnboarding/assets/ContinueOnEuropa.tsx, apps/ledger-live-mobile/src/screens/SyncOnboarding/assets/ContinueOnStax.tsx
- Update device icon during the sync onboarding process.
- Update device icon during the sync onboarding process for Stax and Flex.
- **JIRA or GitHub link**: [LIVE-21038]
---
[LIVE-21038]: …
=> [LIVE-21038][APEX]Update icon Flex and Stax

.changeset/curly-dots-reflect.md, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/__integrations__/modules.test.tsx, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/screens/AssetSelection/modules/createAssetConfigurationHook.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/screens/AssetSelection/modules/useLeftApyModule.tsx, libs/ledger-live-common/.unimportedrc.json, libs/ledger-live-common/src/modularDrawer/hooks/modules/useLeftApyModule.tsx
- MAD asset selection
Plug APYIndicator to the LLM MAD asset selection if the param is set 
For now it's hardcoded until we use DADA
UseLeftApyModule has been moved to common as it's the same on LLD and LLM
- **JIRA or GitHub link**: [LIVE-20526](https://ledgerhq.atlassian.net/browse/LIVE-20526)
--- …
=> ✨ (MAD-LLM) asset selection APYIndicator

.changeset/wet-apricots-rest.md, libs/ledgerjs/packages/hw-app-canton/README.md, libs/ledgerjs/packages/hw-app-canton/__tests__/Canton.test.ts, libs/ledgerjs/packages/hw-app-canton/jest.config.ts, libs/ledgerjs/packages/hw-app-canton/jest.integ.config.ts, libs/ledgerjs/packages/hw-app-canton/package.json, libs/ledgerjs/packages/hw-app-canton/src/Canton.integ.test.ts, libs/ledgerjs/packages/hw-app-canton/src/Canton.ts, package.json, pnpm-lock.yaml
- CantonApp communication
Add integration tests with [CantonApp](https://github.com/ledgerhq/app-canton) within Speculos.
---
=> feat(hw-app): Add integration tests with Canton app in Speculos

.changeset/small-eggs-collect.md, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/hooks/useDrawerLifecycle.ts
- LLM MAD analytics for close button in network step
Fix LLM MAD analytics for close button in network step
- **JIRA or GitHub link**: [LIVE-20433]
---
[LIVE-20433]: …
=> LLM MAD fix analytics

.changeset/fuzzy-bees-thank.md, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/Debug/const/configurationOptions.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/Debug/index.tsx, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/Debug/utils.ts
- ...
Adapt & rework Modular Dev Tool
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-20529 
---
=> chore: Adapt Modular Dev Tool

e2e/mobile/page/trade/earnDasboard.page.ts, e2e/mobile/specs/earn/earn.ts
- ...
- Fixed failing tests
- [CI_RUN](https://github.com/LedgerHQ/ledger-live/actions/runs/17263331940)
---
=> fixed failing tests

.changeset/dull-poems-applaud.md, libs/coin-modules/coin-evm/src/api/index.integ.test.ts, libs/coin-modules/coin-evm/src/cryptoAssetsStore.ts
- ...
Align integrations tests with the production code.
---
=> test(coin-evm): fix integration tests

.changeset/gorgeous-grapes-scream.md, libs/coin-modules/coin-stellar/.eslintrc.js, libs/coin-modules/coin-stellar/src/logic/validateIntent.ts, libs/coin-modules/coin-stellar/src/network/horizon.ts, libs/coin-modules/coin-stellar/src/network/index.ts, libs/coin-modules/coin-stellar/src/network/serialization.ts
- ...
Remove cyclic imports on Stellar and adds `no-cycle` to avoid regression.
---
=> lint(coin-stellar): remove cyclic import

e2e/mobile/page/trade/buySell.page.ts
- ...
- Fixed Buy / Sell tests
- [CI_RUN](https://github.com/LedgerHQ/ledger-live/actions/runs/17289337176)
---
=> fixed buySell error

.changeset/smart-days-hope.md, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/ModularDrawerFlowManagerRemoteData.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/hooks/useModularDrawerData.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/hooks/useModularDrawerRemoteData.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/AssetSelection/components/List/index.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/AssetSelection/index.tsx, libs/ledger-live-common/src/modularDrawer/data/state-manager/api.ts, libs/ledger-live-common/src/modularDrawer/hooks/__test__/useAssetsData.test.ts, libs/ledger-live-common/src/modularDrawer/hooks/useAssetsData.ts, libs/ui/packages/react/src/pre-ldls/components/VirtualList/VirtualList.tsx, pnpm-lock.yaml
- Pagination on scroll in DADA (requires CORS bypass in dev via `BYPASS_CORS=1 pnpm dev:lld`)
Integrates DADA pagination with MAD virtualised list. Example with network speed throttled:
https://github.com/user-attachments/assets/aec1c032-6374-4383-8a66-438ab094331a
- **JIRA or GitHub link**: [LIVE-20505](https://ledgerhq.atlassian.net/browse/LIVE-20505)
--- …
=> feat(LLD): infinite scroll

.changeset/sweet-pens-clap.md, libs/coin-modules-monitoring/src/currencies.ts
- ...
Enable monitoring of Icon and Sui. Reviewers can check it is working locally with
```sh
pnpm coin:modules:monitoring start icon,sui
```
---
=> chore(coin-modules-monitoring): re-enable monitoring for icon and sui

.changeset/curly-toys-smoke.md, apps/ledger-live-desktop/src/renderer/screens/exchange/Swap2/Form/DrawerFooter.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, libs/ledger-services/cal/src/partners/default.ts
- ...
add cic accept terms
https://ledgerhq.atlassian.net/browse/LIVE-21097
---
=> feat(LIVE-21097): add cic accept terms

apps/ledger-live-mobile/src/newArch/features/DeviceSelection/Navigator.tsx, apps/ledger-live-mobile/src/screens/ReceiveFunds/03-Confirmation.tsx, e2e/mobile/page/trade/receive.page.ts, e2e/mobile/page/wallet/transferMenu.drawer.ts, e2e/mobile/specs/deposit/createNewAccountAndDeposit_XRP_1.spec.ts, e2e/mobile/specs/deposit/deposit.ts, e2e/mobile/specs/deposit/depositInExistingAccount_ETH_1.spec.ts, e2e/mobile/specs/deposit/selectCryptoNetworkWithAccount_ETH_1.spec.ts, e2e/mobile/specs/deposit/selectCryptoNetworkWithoutAccount_ETH_1.spec.ts, e2e/mobile/specs/deposit/selectCryptoWithoutNetworkAndAccount_BTC_LEGACY_1.spec.ts
- ...
- Added deposit test cases
- **JIRA or GitHub link**: [B2CQA-1861](https://ledgerhq.atlassian.net/browse/B2CQA-1861), [B2CQA-1857](https://ledgerhq.atlassian.net/browse/B2CQA-1857), [B2CQA-1855](https://ledgerhq.atlassian.net/browse/B2CQA-1855), [B2CQA-1854](https://ledgerhq.atlassian.net/browse/B2CQA-1854), [B2CQA-1898](https://ledgerhq.atlassian.net/browse/B2CQA-1898),
- [CI_RUN](https://github.com/LedgerHQ/ledger-live/actions/runs/17298957086)
--- …
=> added deposit tests cases

.changeset/long-pots-promise.md, libs/coin-framework/src/api/types.ts, libs/coin-modules/coin-evm/src/api/index.ts, libs/coin-modules/coin-evm/src/logic/getTokenFromAsset.test.ts, libs/coin-modules/coin-evm/src/logic/getTokenFromAsset.ts, libs/coin-modules/coin-evm/src/logic/index.ts, libs/coin-modules/coin-stellar/src/api/index.ts, libs/coin-modules/coin-stellar/src/logic/getTokenFromAsset.test.ts, libs/coin-modules/coin-stellar/src/logic/getTokenFromAsset.ts, libs/coin-modules/coin-stellar/src/logic/index.ts, libs/ledger-live-common/src/bridge/generic-alpaca/buildSubAccounts.ts, libs/ledger-live-common/src/bridge/generic-alpaca/getAccountShape.ts
- ...
Add `getTokenFromAsset` in `BridgeApi`. The way to fetch tokens is different by coin modules, and we need to wrap the logics in a single method to be used in the Generic Adapter.
---
=> feat(coin-framework): add `getTokenFromAsset` in `BridgeApi`

.changeset/warm-laws-fly.md, libs/coin-modules/coin-canton/src/api/listOperations.integ.test.ts, libs/coin-modules/coin-canton/src/common-logic/history/listOperations.ts, libs/coin-modules/coin-canton/src/network/gateway.ts
Simple list operations impl
- **JIRA or GitHub link**:  [https://ledgerhq.atlassian.net/browse/LIVE-21107](https://ledgerhq.atlassian.net/browse/LIVE-21107)
---
=> list operations simple impl canton

.changeset/orange-jokes-know.md, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/components/Card.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/components/PriceAndVariation.tsx, libs/ui/packages/native/src/components/ProgressPoint/index.tsx
- large mover price variation
- large mover progress bar
We were displaying the wrong price variation. Instead of using the data 1y ago (for e.g it depends on timerange) we used the more recent one creating an issue during calculation. 
Also fix an issue with progress point that could be outside of the bar
We need to convert to minor units using unit.magnitude before passing to CurrencyUnitValue because it expects values in minor units instead of major ones
To confirm the fix I compared with CMC datas
|<img width="1206" height="2622" alt="Simulator Screenshot - iPhone 16 Pro - 2025-08-29 at 11 38 31" src="https://github.com/user-attachments/assets/4b753416-b37e-46d9-842f-e7bc3fbd8945" />|<img width="1206" height="2622" …
=> :bug: (llm) largemover price variation and perf bar

.changeset/polite-donuts-clap.md, apps/ledger-live-mobile/src/newArch/features/Accounts/components/AccountsListView/useAccountsListViewModel.ts
- Hides tokens on the account tab
Correctly hides tokens from the accounts list on the home screen
https://github.com/user-attachments/assets/f307c52d-b655-4c64-b271-7cc0b46bfde0
- **JIRA or GitHub link**: [LIVE-21051](https://ledgerhq.atlassian.net/browse/LIVE-21051)
--- …
=> fix(LLM): filter accounts on AccountListView with blacklistedTokenIds

.changeset/lazy-tigers-sleep.md, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/ModularDrawer.tsx, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/ModularDrawerFlowManager/ModularDrawerFlowView.tsx, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/ModularDrawerFlowManager/index.tsx, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/__integrations__/modularDrawer.test.tsx, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/__integrations__/modules.test.tsx, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/screens/AssetSelection/index.tsx
- ...
Fetch & usage of data from **_DADA_**
- empty state
- Loading state
- search filtering
- initial data fetching
https://github.com/user-attachments/assets/835714b6-4dee-45ca-8ff3-4ea23d84ce6a
- https://ledgerhq.atlassian.net/browse/LIVE-20536
- https://ledgerhq.atlassian.net/browse/LIVE-20534
- https://ledgerhq.atlassian.net/browse/LIVE-20532
---
- **Any new …
=> feat: empty state & data fetching & searching with DADA

.changeset/tough-boats-walk.md, libs/coin-modules/coin-canton/src/bridge/signOperation.ts, libs/coin-modules/coin-canton/src/common-logic/transaction/combine.test.ts, libs/coin-modules/coin-canton/src/common-logic/transaction/combine.ts, libs/coin-modules/coin-canton/src/common-logic/utils.ts
- add `combine` for Canton
Add `combine` function implementation for Canton.
- **JIRA or GitHub link**: [LIVE-21140]
---
[LIVE-21140]: https://ledgerhq.atlassian.net/browse/LIVE-21140?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …
=> [Canton]: Combine

.changeset/angry-bags-notice.md, libs/coin-modules/coin-canton/src/common-logic/transaction/broadcast.test.ts, libs/coin-modules/coin-canton/src/common-logic/transaction/broadcast.ts, libs/coin-modules/coin-canton/src/common-logic/transaction/estimateFees.ts, libs/coin-modules/coin-canton/src/network/gateway.integ.test.ts, libs/coin-modules/coin-canton/src/network/gateway.ts, libs/ledger-live-common/src/bridge/generic-alpaca/alpaca/index.ts, libs/ledger-live-common/src/bridge/generic-alpaca/alpaca/index.unit.test.ts
Broadcast impl coin-canton
- **JIRA or GitHub link**: [https://ledgerhq.atlassian.net/browse/LIVE-21139](https://ledgerhq.atlassian.net/browse/LIVE-21139)
---
=> coin-canton broadcast

.changeset/curly-jokes-allow.md, apps/ledger-live-mobile/src/screens/Swap/SubScreens/SwapCustomError.tsx
- ...
fix swap error message without translation
---
=> fix(swap-error-messages): fix swap error message without translation

.changeset/gorgeous-snakes-heal.md, libs/coin-modules-monitoring/src/cli.ts, libs/coin-modules-monitoring/src/run.test.ts, libs/coin-modules-monitoring/src/run.ts
- ...
Monitoring should exit with error code on failure.
---
=> ci(coin-monitoring): exit with `1` on run failure

.changeset/ninety-buttons-beg.md, apps/ledger-live-mobile/src/screens/Platform/exchange/StartExchange.tsx
- ...
add skip device select for swap live app
https://ledgerhq.atlassian.net/browse/LIVE-21138
---
=> feat(LIVE-21138): add skip device select for swap live app

.changeset/chilly-pumpkins-decide.md, apps/ledger-live-mobile/src/components/WebPlatformPlayer/SelectAccountButton.tsx, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/ModularDrawer.tsx, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/hooks/__tests__/useModularDrawerState.test.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/hooks/useAssetsFromDada.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/hooks/useModularDrawerState.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/hooks/useStepNavigation.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/screens/AssetSelection/index.tsx, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/utils/__tests__/helpers.test.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/utils/helpers.ts
- ...
Improve MAD UX & reduce code complexity for some steps
---
=> feat: Improve MAD UX

.changeset/moody-rocks-agree.md, apps/ledger-live-mobile/src/screens/Swap/SubScreens/PendingOperation.tsx
=> fix: swap to currency id tracking

.changeset/ninety-foxes-ring.md, libs/coin-modules/coin-sui/src/network/sdk.ts
- Allow pagination for asc order on sui
--- …
=> feat: allow paginated operations on asc order

.changeset/gold-rocks-wait.md, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/__tests__/selectAccountFlow.test.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/__tests__/selectNetworkFlow.test.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/hooks/__tests__/useOpenAssetFlow.test.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/hooks/useOpenAssetFlow.tsx, apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/LiveAppSDKLogic.ts, apps/ledger-live-desktop/src/renderer/components/Web3AppWebview/helpers.ts, apps/ledger-live-desktop/tests/handlers/assets.ts, apps/ledger-live-desktop/tests/jestSetup.js
- ...
Fix the tests now that we are remotely fetching the data displayed in the drawer
---
=> LLD - Fix modular drawer tests when powered by DADA

.github/workflows/coin-monitoring-manual.yml, .github/workflows/coin-monitoring-scheduled.yml
- ...
Include the monitoring dashboard url in the success report, so it is easily accessible by anyone. Also adding emojis, because why not.
---
=> ci: add dashboard url in monitoring report

.changeset/wicked-cobras-tell.md, libs/coin-framework/src/api/types.ts, libs/coin-modules/coin-evm/src/api/index.ts, libs/coin-modules/coin-evm/src/logic/getTokenFromAsset.test.ts, libs/coin-modules/coin-evm/src/logic/getTokenFromAsset.ts, libs/coin-modules/coin-stellar/src/api/index.ts, libs/coin-modules/coin-stellar/src/logic/getTokenFromAsset.test.ts, libs/coin-modules/coin-stellar/src/logic/getTokenFromAsset.ts, libs/coin-modules/coin-stellar/src/logic/index.ts, libs/ledger-live-common/src/bridge/generic-alpaca/buildSubAccounts.ts, libs/ledger-live-common/src/bridge/generic-alpaca/getTransactionStatus.ts, libs/ledger-live-common/src/bridge/generic-alpaca/prepareTransaction.ts, libs/ledger-live-common/src/bridge/generic-alpaca/utils.ts
- Token operations and history within the generic adapter (i.e. only Stellar USDC)
--- …
=> refactor(llc): use standard token account encoding

.changeset/red-pants-grow.md, apps/ledger-live-mobile/src/components/Web3AppWebview/NoAccountScreen.tsx, apps/ledger-live-mobile/src/components/Web3AppWebview/PlatformAPIWebview.tsx, apps/ledger-live-mobile/src/components/Web3AppWebview/helpers.ts, apps/ledger-live-mobile/src/components/WebPlatformPlayer/SelectAccountButton.tsx, apps/ledger-live-mobile/src/newArch/features/Accounts/screens/AddAccount/components/SelectAddAccountMethod/useSelectAddAccountMethodViewModel.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/ModularDrawer.tsx, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/ModularDrawerProvider.tsx, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/hooks/useAssetsFromDada.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/hooks/useModularDrawerController.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/types.ts, apps/ledger-live-mobile/src/reducers/modularDrawer.ts
- ...
Add new params from Wallet-Api to use in DADA: 
- useCase
- areCurrenciesFiltered
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-21255
---
=> feat: Add useCase & areCurrencyFiltered param in MAD

libs/coin-modules/coin-hedera/src/api/network.test.ts, libs/coin-modules/coin-hedera/src/bridge/prepareTransaction.test.ts, libs/ledger-live-common/src/families/hedera/exchange.ts
- @ledgerhq/coin-hedera
- @ledgerhq/live-common
This PR addresses comments from https://github.com/LedgerHQ/ledger-live/pull/10972
---
=> fix: hedera swaps review changes

.changeset/few-pants-teach.md, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/ModularDrawerFlowManager.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/__tests__/selectAccountFlow.test.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/hooks/useModularDrawerBackButton.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/hooks/useModularDrawerFiltering.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/hooks/useModularDrawerFlowState.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/hooks/useModularDrawerNavigation.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/hooks/useModularDrawerRemoteData.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/hooks/useOpenAssetFlow.tsx
- No changes on functionality
Reduces unnecessary parameters and removes dead code
---
=> refactor(LLD): remove dead MAD code

.changeset/cyan-teachers-destroy.md, apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx, apps/ledger-live-mobile/src/components/TermsFooter.tsx, apps/ledger-live-mobile/src/locales/en/common.json
- ...
Remove details from swap details confirmation
https://ledgerhq.atlassian.net/browse/LIVE-21137
---
=> feat(LIVE-21137): remove swap details from screen

libs/ledger-live-common/src/families/canton/bridge/mock.ts
=> fix: web-tools build

.changeset/eight-ladybugs-argue.md, apps/ledger-live-desktop/src/renderer/families/sui/AccountHeaderManageActions.tsx, libs/coin-modules/coin-sui/src/bridge/estimateMaxSpendable.test.ts, libs/coin-modules/coin-sui/src/bridge/estimateMaxSpendable.ts, libs/coin-modules/coin-sui/src/bridge/getTransactionStatus.ts, libs/coin-modules/coin-sui/src/bridge/utils.ts
- @ledgerhq/coin-sui
- ledger-live-desktop
Fix SUI stake low fund redirect and stake fee estimation.
**JIRA or GitHub link**
https://ledgerhq.atlassian.net/browse/LIVE-21299
https://ledgerhq.atlassian.net/browse/LIVE-21267
--- …
=> fix: sui stake low fund redirect, stake fee estimation

.changeset/eight-ladybugs-argue.md, apps/ledger-live-desktop/src/renderer/families/sui/AccountHeaderManageActions.tsx, libs/coin-modules/coin-sui/src/bridge/estimateMaxSpendable.test.ts, libs/coin-modules/coin-sui/src/bridge/estimateMaxSpendable.ts, libs/coin-modules/coin-sui/src/bridge/getTransactionStatus.ts, libs/coin-modules/coin-sui/src/bridge/utils.ts
=> fix: LIVE-21299 LIVE-21267 stake fee estimation and no fund redirect

.changeset/friendly-pugs-rule.md, apps/ledger-live-desktop/tests/mocks/serviceStatusHelpers.ts, libs/ledger-live-common/src/notifications/ServiceStatusProvider/index.test.ts, libs/ledger-live-common/src/notifications/ServiceStatusProvider/index.tsx, libs/ledger-live-common/src/notifications/ServiceStatusProvider/ledger-components.ts
- ...
Filters service status incidents based on related tickers or Ledger components.
- If there are no `tickers` or no `incidents`, returns an empty list.
- For each incident:
1. ✅ If the incident has no components → keep it (always relevant).
2. ✅ If at least one component name matches a known **Ledger component** → keep it.
3. ✅ If at least one component name contains a **currency ticker** → keep it.
4. ❌ Otherwise, the incident is discarded.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-21135
--- …
=> fix: Incidents display in LLD

.changeset/loud-gifts-sort.md, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/screens/AssetSelection/components/SearchInputContainer/test/useSearch.test.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/screens/AssetSelection/components/SearchInputContainer/useSearch.ts, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/screens/AssetSelection/index.tsx
- ...
Fix bugs related to keyboard on select Asset page and trim the search to avoid unexpected backend errors
https://github.com/user-attachments/assets/7f7917e6-08eb-47fb-b3b0-84a158ad931e
- https://ledgerhq.atlassian.net/browse/LIVE-21358
- https://ledgerhq.atlassian.net/browse/LIVE-21360
---
- …
=> fix: AssetSelection with Keyboard and search trim

.changeset/eleven-badgers-sip.md, libs/coin-modules/coin-canton/src/network/gateway.ts, libs/env/src/env.ts
- ...
set X-Ledger-Canton-Api-Keyheader through env
- [LIVE-21341](https://ledgerhq.atlassian.net/browse/LIVE-21341)
---
[LIVE-21341]: …
=> feat: canton api key setup

.changeset/perfect-cougars-switch.md, apps/ledger-live-mobile/src/components/WebPTXPlayer/index.tsx
=> fix: back to internal domain

libs/coin-modules/coin-tezos/src/bridge/prepareTransaction.test.ts
- ...
Fix test because `burnFeeMutez` must not be 0 when sending to an account that has never been allocated
---
=> fix: tezos tests

.changeset/giant-dancers-pay.md, apps/ledger-live-desktop/src/renderer/components/WebPlatformPlayer/CustomHandlers.ts, apps/ledger-live-mobile/src/components/WebPlatformPlayer/CustomHandlers.ts, libs/ledger-live-common/src/wallet-api/ACRE/server.test.ts, libs/ledger-live-common/src/wallet-api/ACRE/server.ts, libs/wallet-api-acre-module/README.md, libs/wallet-api-acre-module/src/index.ts, libs/wallet-api-acre-module/src/types.ts
- ...
The `custom.acre.registerYieldBearingEthereumAddress` endpoint is a custom handler that provides direct access to the yield-bearing Ethereum address registration functionality. 
**Endpoint**: `custom.acre.registerYieldBearingEthereumAddress`  
**Method**: Custom handler  
**Purpose**: Register BTC yield-bearing Ethereum addresses with automatic account creation in Ledger Live. This is considering either token address or ticker.
```typescript
type RegisterYieldBearingEthereumAddressParams = {
ethereumAddress: string;           // Required: Valid Ethereum address (0x format)
tokenContractAddress?: string;     // Optional: Token contract address
tokenTicker?: string;              // Optional: Token ticker symbol (e.g., stBTC, acreBTC)
meta?: Record<string, unknown>;    // Optional: …
```
=> [LIVE-20866] Add Acre reward address registering functionality to ACRE CustomHandler

.changeset/selfish-turkeys-hear.md, patches/@taquito__http-utils.patch, pnpm-lock.yaml
- ...
Modifie the patch to fix integration tests and get ride of the following error `HttpRequestFailed: GET https://xtz-node.api.live.ledger.com/chains/main/blocks/head/context/constants TypeError: require is not a constructor`
--- …
=> fix: tezos patch

.changeset/odd-maps-tell.md, apps/ledger-live-mobile/src/families/sui/Staking/ValidatorImageWrapper.tsx, libs/coin-modules/coin-canton/src/api/getBalance.integ.test.ts, libs/coin-modules/coin-canton/src/api/index.ts, libs/coin-modules/coin-canton/src/bridge/prepareTransaction.ts, libs/coin-modules/coin-canton/src/bridge/signOperation.ts, libs/coin-modules/coin-canton/src/bridge/updateTransaction.ts, libs/coin-modules/coin-canton/src/common-logic/transaction/craftTransaction.ts, libs/coin-modules/coin-canton/src/network/gateway.ts, libs/coin-modules/coin-canton/src/network/node.ts, libs/coin-modules/coin-canton/src/network/types.ts, libs/coin-modules/coin-canton/src/types/index.ts, libs/ledger-live-common/src/families/canton/config.ts
- ...
- Tap
- Send
- preapproval
Craft transaction tx support
- **JIRA or GitHub link**: [https://ledgerhq.atlassian.net/browse/LIVE-21114](https://ledgerhq.atlassian.net/browse/LIVE-21114)
---
=> feat: craft transaction canton alpaca

.changeset/twenty-adults-change.md, libs/coin-modules/coin-canton/src/bridge/onboard.integ.test.ts, libs/coin-modules/coin-canton/src/bridge/sync.integ.test.ts, libs/coin-modules/coin-canton/src/bridge/sync.ts
chore: add locked balance calculation and update sync integration tests
- ...
📝 Description
Sync integration test is implemented
Locked balance is taken into account when calculating spendable balance
Original PR: https://github.com/LedgerHQ/ledger-live/pull/11696
❓ Context
JIRA or GitHub link:
[LIVE-21304](https://ledgerhq.atlassian.net/browse/LIVE-21304)
[LIVE-20746](https://ledgerhq.atlassian.net/browse/LIVE-20746)
--- …
=> chore: locked balance and sync tests

.changeset/nice-boats-fix.md, apps/ledger-live-desktop/src/renderer/components/TranslatedError/ErrorWithAnchor.test.tsx, apps/ledger-live-desktop/src/renderer/components/TranslatedError/ErrorWithAnchor.tsx
- translated error banners
context https://ledger.slack.com/archives/GCX3FQ2BB/p1757922783965059
https://github.com/user-attachments/assets/1c43ea91-1bce-4e86-83b3-528b4c7bab61
---
=> :bug: (lld) fix allowed support url

.changeset/thick-cherries-sell.md, apps/ledger-live-desktop/src/renderer/components/CustomImage/TestImage.tsx, apps/ledger-live-desktop/src/renderer/modals/UpdateFirmwareModal/steps/restore/CustomLockScreen.tsx
- preview of the Custom Lock Screen when restoring it in the OS update, for Apex
Context: when we do an OS update, we download the lock screen picture from the device as it gets deleted.
And then, when we upload it back to the device, we display a preview of that picture.
This algo is for reconstructing the picture from the raw picture data pulled from the device.
As pictures on Stax/Flex are 4 bits per pixel, and pictures on Apex are 1 bit per pixel, the data is serialised differently, so a new algo is necessary.
It was already implemented on LLM, this is the LLD implementation.
- **JIRA or GitHub link**: [LIVE-21242] 
--- …
=> [LIVE-21242] fix(Custom Lock Screen LLD): implement reconstruction of picture from device for Apex

.changeset/gorgeous-humans-invite.md, libs/coin-modules-monitoring/src/run.ts
=> chore(coin-modules-monitoring): log error stack

.changeset/unlucky-berries-relate.md, libs/coin-modules/coin-sui/package.json, libs/coin-modules/coin-sui/src/api/index.integration.test.ts, libs/coin-modules/coin-sui/src/api/index.ts, libs/coin-modules/coin-sui/src/logic/listOperations.test.ts, libs/coin-modules/coin-sui/src/logic/listOperations.ts, libs/coin-modules/coin-sui/src/network/sdk.ts, pnpm-lock.yaml
- coin module API now returns all operations for address
- duplicated operations may happen for most of out operations
- the previous algorithm still exists and nothing has changed for the bridge sync
- Current algorithm has some cons:
- was missing many operations in ascending mode
- cursor wasn't returned in some cases
- somehow inefficient (filtering of ops, no concurrency)
- is difficult to debug/maintain (recursion with mutable parameter, handling of single cursor with timestamp filtering, lot of tests to migrate when refactoring)
- but has some pros   
- is working in descending mode
- never return duplicated operations 
- We implemented a simpler algorithm:
- we just call "in" and "out" operations concurrently and 
- the API cursor is the concatenation of both cursors.
- a big …
=> fix(coin:sui): large accounts are missing some operations

.changeset/loud-spiders-explode.md, libs/coin-modules/coin-canton/src/common-logic/transaction/estimateFees.ts
- ...
Update fee canton to 2 CC
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-21540
---
=> update fee canton

.changeset/chatty-teachers-join.md, libs/coin-modules/coin-evm/src/api/index.integ.test.ts, libs/coin-modules/coin-evm/src/logic/common.ts, libs/coin-modules/coin-evm/src/logic/estimateFees.test.ts, libs/coin-modules/coin-evm/src/logic/estimateFees.ts, libs/coin-modules/coin-evm/src/logic/validateIntent.test.ts, libs/coin-modules/coin-evm/src/logic/validateIntent.ts, libs/coin-modules/coin-evm/src/utils.ts, libs/ledger-live-common/src/bridge/generic-alpaca/alpaca/index.ts, libs/ledger-live-common/src/bridge/generic-alpaca/alpaca/index.unit.test.ts, libs/ledger-live-common/src/bridge/generic-alpaca/broadcast.ts, libs/ledger-live-common/src/bridge/generic-alpaca/createTransaction.ts, libs/ledger-live-common/src/bridge/generic-alpaca/estimateMaxSpendable.ts, libs/ledger-live-common/src/bridge/generic-alpaca/getAccountShape.ts, libs/ledger-live-common/src/bridge/generic-alpaca/getTransactionStatus.ts, libs/ledger-live-common/src/bridge/generic-alpaca/prepareTransaction.ts, libs/ledger-live-common/src/bridge/generic-alpaca/signOperation.ts, libs/ledger-live-common/src/bridge/generic-alpaca/tests/prepareTransaction.test.ts, libs/ledger-live-common/src/bridge/generic-alpaca/tests/signOperation.test.ts, libs/ledger-live-common/src/bridge/generic-alpaca/types.ts, libs/ledger-live-common/src/bridge/generic-alpaca/utils.ts
- Better typing
- Wider test coverage
- Fee ratio and all amount handling in `validateIntent`
---
=> refactor(llc, coin-evm): support `allAmounts` and `feeRatio` warning

libs/coin-modules/coin-xrp/src/api/index.integ.test.ts
- ...
Fix expected value of `locked` to 0 if blance is 0!
---
=> fix: xrp tests locked

.changeset/brave-candles-fix.md, apps/ledger-live-desktop/src/renderer/families/tezos/DelegateFlowModal/Body.tsx
- ...
defaultBaker can be undefined on apps/ledger-live-desktop/src/renderer/families/tezos/DelegateFlowModal/Body.tsx. This can possibly be a bug because, if the endpoint returns some error or fails to load, the app will crash when clicking on "Earn".
- **JIRA or GitHub link**: [LIVE-21619](https://ledgerhq.atlassian.net/browse/LIVE-21619)
--- …
=> fix: check if defaultBaker exists

.changeset/olive-mayflies-kiss.md, apps/ledger-live-mobile/src/newArch/features/LandingPages/__integrations__/largeMoverLandingPage.integration.test.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/components/Loading.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/components/__tests__/OverlayTutorial.test.tsx, apps/ledger-live-mobile/src/newArch/features/LandingPages/screens/LargeMoverLandingPage/fixtures/navigation.tsx
- Integration test for Large Mover Landing Page
Large Mover integration test
- **JIRA or GitHub link**: [LIVE-18117]
---
[LIVE-18117]: https://ledgerhq.atlassian.net/browse/LIVE-18117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …
=> Feat: Large Mover integration test

.changeset/nervous-games-collect.md, libs/ui/packages/react/src/pre-ldls/components/Search/Search.tsx
- new search input for the MAD
Add colored border when the input is focused (we already do it on LLM)
https://github.com/user-attachments/assets/71884f80-a003-4805-a9a3-bf9e8eec6520
- **JIRA or GitHub link**: [LIVE-21627](https://ledgerhq.atlassian.net/browse/LIVE-21627) 
--- …
=> :lipstick: (ui-MAD) search input border on focus

.changeset/warm-starfishes-cough.md, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/ModularDrawerFlowManager.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/hooks/useModularDrawerData.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/AssetSelection/components/List/index.tsx, apps/ledger-live-desktop/src/renderer/reducers/modularDrawer.ts, apps/ledger-live-desktop/src/renderer/screens/settings/sections/Developer/ModularDrawer/index.tsx, apps/ledger-live-mobile/src/newArch/features/ModularDrawer/hooks/__tests__/useAssets.test.ts, libs/ledger-live-common/src/deposit/type.ts, libs/ledger-live-common/src/modularDrawer/__mocks__/dada.mock.ts, libs/ui/packages/react/src/pre-ldls/components/AssetItem/AssetItem.tsx, libs/ui/packages/react/src/pre-ldls/components/AssetList/AssetList.tsx, pnpm-lock.yaml
- Devtool added, nothing user facing
Added a tool to display and copy the assets id, this will make it easier to provide them to the backend team when we find duplicated assets so that they can group them.
Added a documentation explaining how to use it https://ledgerhq.atlassian.net/wiki/spaces/WXP/pages/6212452535/How+to+find+IDs+of+duplicated+assets
---
- **Any new …
=> ⚗️  LLD MAD - add debug duplicates devtool

.changeset/late-rats-live.md, apps/ledger-live-mobile/src/screens/Platform/exchange/StartExchange.tsx, apps/ledger-live-mobile/src/screens/SkipSelectDevice.tsx
- ...
only auto select device if it's available
https://ledgerhq.atlassian.net/browse/LIVE-21138
---
=> feat(LIVE-21138): only auto select device if it's available

libs/live-wallet/src/liveqr/importAccounts.test.ts, libs/live-wallet/src/liveqr/importAccounts.ts
- none. it's unused code.
- `importAccountsMakeItems ` is dead code
- `importAccountsReduce` is still used tho, so we've added test for it.
- **JIRA or GitHub link**:  na
---
=> cleanup dead code from the old liveqr logic

.changeset/eight-weeks-act.md, libs/coin-modules-monitoring/.eslintrc.js, libs/coin-modules-monitoring/package.json, libs/coin-modules-monitoring/src/cli.ts, libs/coin-modules-monitoring/src/datadog.ts, libs/coin-modules-monitoring/src/measure.ts, libs/coin-modules-monitoring/src/run.test.ts, libs/coin-modules-monitoring/src/run.ts, pnpm-lock.yaml
- ...
add to metrics to the coin module monitoring
Number of API calls
CPU usage
Mem usage
- **JIRA or GitHub link**:  [LIVE-21225](https://ledgerhq.atlassian.net/browse/LIVE-21225) 
---
[LIVE-21225]: …
=> feat:monitoring cpu mem and number of calls

e2e/desktop/tests/specs/earn.spec.ts
- ...
Updating solana index to use index 2 instead of index 0. 
Funds are been send to Solana index 2 from Solana index 0 (5$)
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/QAA-814
---
=> fix:udating solana index for earn test

.changeset/wise-bugs-kick.md, apps/ledger-live-desktop/src/newArch/features/AddAccountDrawer/screens/ScanAccounts/useScanAccounts.ts
- hbar MAD
Demo in 2 parts because I needed to do a tx to trigger all the possibilities
https://github.com/user-attachments/assets/a7878096-a9e2-47ce-8520-8dcb5deb380d
https://github.com/user-attachments/assets/d3fa515e-8d5f-4e96-80e3-cbba98b93671
- **JIRA or GitHub link**: [LIVE-21673](https://ledgerhq.atlassian.net/browse/LIVE-21673)
--- …
=> :bug: (MAD LLD) empty hbar screen

.changeset/fair-walls-serve.md, libs/coin-modules/coin-evm/src/logic/getBalance.test.ts, libs/coin-modules/coin-evm/src/logic/getBalance.ts, libs/coin-modules/coin-evm/src/logic/getStakes.test.ts
- ...
Add staking position on the return of the `getBalance` method.
- **[JIRA or GitHub link](https://ledgerhq.atlassian.net/browse/LIVE-19558)**
---
=> feat: getBalance returns staking positions

e2e/mobile/specs/swap/otherTestCases/swap.other.ts, e2e/mobile/specs/swap/swap.ts
- ...
CI Run: https://github.com/LedgerHQ/ledger-live/actions/runs/17949113189
---
=> fix: adding device selection for swap e2e

.changeset/early-foxes-attack.md, apps/ledger-live-desktop/src/renderer/components/DeviceAction/rendering.tsx, libs/ledger-live-common/src/featureFlags/defaultFeatures.ts, libs/ledgerjs/packages/types-live/src/feature.ts
- ...
This PR renames the FF for swap confirmation drawer
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-21757
---
- **Any new …
=> chore: (LIVE-21757) rename FF for clarity

.changeset/gorgeous-socks-run.md, apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx, apps/ledger-live-mobile/src/components/TermsFooter.tsx, apps/ledger-live-mobile/src/locales/en/common.json, apps/ledger-live-mobile/src/utils/urls.tsx
- ...
fit the drawer to whole screen for confirmation of swap on device
https://ledgerhq.atlassian.net/browse/LIVE-21566
---
=> feaT(LIVE-21566): fit the drawer to whole screen

e2e/desktop/tests/specs/delegate.spec.ts, e2e/desktop/tests/specs/send.tx.spec.ts
=> fix: condition check for broadcasting env var

.changeset/swift-cooks-refuse.md, libs/ledger-live-common/src/families/kaspa/__snapshots__/bridge.integration.test.ts.snap
- @ledgerhq/live-common
Update Kaspa bridge integration test snapshot
---
=> fix: update Kaspa bridge integration test snapshot

.changeset/thick-buckets-mate.md, apps/ledger-live-mobile/__tests__/test-renderer.tsx, apps/ledger-live-mobile/src/actions/settings.ts, apps/ledger-live-mobile/src/actions/types.ts, apps/ledger-live-mobile/src/reducers/index.ts, apps/ledger-live-mobile/src/reducers/settings.ts, apps/ledger-live-mobile/src/reducers/tools.ts, apps/ledger-live-mobile/src/reducers/types.ts, apps/ledger-live-mobile/src/screens/Settings/Debug/Configuration/RtkConsoleRow.tsx, apps/ledger-live-mobile/src/screens/Settings/Debug/Debugging/RTK/index.tsx
- ...
Create a dedicated slice to store all toolings and avoid overload & usage of settings store
---
=> chore: RTK Slice for tools to avoid overlad settings

.changeset/dull-melons-worry.md, apps/ledger-live-desktop/src/renderer/components/OperationsList/ConfirmationCheck.tsx, apps/ledger-live-desktop/src/renderer/families/canton/OnboardModal/steps/StepAuthorize.tsx, apps/ledger-live-desktop/src/renderer/families/canton/OnboardModal/steps/StepOnboard.tsx, apps/ledger-live-desktop/static/i18n/en/app.json, libs/coin-modules/coin-canton/src/api/lastBlock.integ.test.ts, libs/coin-modules/coin-canton/src/api/listOperations.integ.test.ts, libs/coin-modules/coin-canton/src/bridge/createTransaction.ts, libs/coin-modules/coin-canton/src/bridge/onboard.integ.test.ts, libs/coin-modules/coin-canton/src/bridge/prepareTransaction.test.ts, libs/coin-modules/coin-canton/src/bridge/prepareTransaction.ts, libs/coin-modules/coin-canton/src/bridge/signOperation.ts, libs/coin-modules/coin-canton/src/bridge/sync.integ.test.ts, libs/coin-modules/coin-canton/src/bridge/sync.ts, libs/coin-modules/coin-canton/src/bridge/transaction.ts, libs/coin-modules/coin-canton/src/config.ts, libs/coin-modules/coin-canton/src/network/gateway.integ.test.ts, libs/coin-modules/coin-canton/src/network/node.integ.test.ts, libs/coin-modules/coin-canton/src/network/node.unit.test.ts, libs/coin-modules/coin-canton/src/test/bridgeDatasetTest.ts, libs/coin-modules/coin-canton/src/types/bridge.ts, libs/ledger-live-common/src/families/canton/bridge/mock.ts, libs/ledger-live-common/src/families/canton/config.ts, libs/ledgerjs/packages/types-live/src/operation.ts
- ...
- added new tx type
- moved hardcoded instrumentId to config
- added FEES case
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-21570
---
=> feat: canton new tx type, moved hardcoded instrumentId to config

.changeset/sweet-penguins-live.md, libs/ledger-live-common/src/families/kaspa/__snapshots__/bridge.integration.test.ts.snap, libs/ledger-live-common/src/families/kaspa/bridge.integration.test.ts
- @ledgerhq/live-common
Add snapshot for Kaspa bridge integration test.
---
=> test: add snapshot for Kaspa bridge integration test

.changeset/many-pandas-help.md, apps/ledger-live-mobile/src/analytics/segment.ts
- ...
Add  llmSyncOnboardingIncr1 feature flag tracking to user and event property fields.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-21693
---
=> feat: add llmSyncOnboardingIncr1 feature flag tracking

.changeset/nice-worms-breathe.md, libs/ledger-live-common/src/modularDrawer/hooks/useRightBalanceNetwork.tsx
- LLM network balance per token
- **JIRA or GitHub link**: [LIVE-21770](https://ledgerhq.atlassian.net/browse/LIVE-21770)
---
[LIVE-21770]: https://ledgerhq.atlassian.net/browse/LIVE-21770?atlOrigin=eyJpIjoiNWRkNTljNz …
=> fix(LL): mad network balance

.changeset/strong-mayflies-fry.md, libs/coin-modules-monitoring/src/currencies.ts
- ...
Following the migration to the generic bridge for Tezos: the coin-monitoring module now looks for adresses instead of public keys for Tezos
---
=> chore: use tezos addresses for coin monitoring

.changeset/plenty-coins-run.md, apps/ledger-live-desktop/src/newArch/features/MarketPerformanceWidget/components/Header.tsx, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/Web3AppWebview/__tests__/openAssetAndAccountDrawer.test.ts, apps/ledger-live-desktop/src/newArch/features/ModularDrawer/screens/AssetSelection/components/SearchInputContainer/index.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/components/TinyCard.tsx, apps/ledger-live-desktop/src/newArch/features/WalletSync/screens/Synchronize/02-QRCodeStep.tsx, apps/ledger-live-desktop/src/renderer/components/FormattedVal.tsx, apps/ledger-live-desktop/src/renderer/drawers/DataSelector/AccountList.tsx, apps/ledger-live-desktop/src/renderer/drawers/OperationDetails/index.tsx, apps/ledger-live-desktop/src/renderer/drawers/SwapOperationDetails/index.tsx, apps/ledger-live-desktop/tests/handlers/index.ts, apps/ledger-live-desktop/tests/jestSetup.js
- ...
Cleanup Jest logs
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-21167
---
=> chore: cleanup logs on Jest

.changeset/neat-clocks-share.md, apps/ledger-live-desktop/src/renderer/components/FormattedVal.tsx, apps/ledger-live-desktop/src/renderer/families/cosmos/Delegation/__tests__/Delegations.test.tsx, apps/ledger-live-desktop/src/renderer/modals/Send/fields/RecipientFieldBase.tsx, apps/ledger-live-mobile/src/components/RecipientInput.tsx
- ...
Cleanup some errors & warning during tests exec on LLM & LLD
---
=> chore: resolve errors & warning during tests exec

.changeset/poor-moose-fetch.md, apps/ledger-live-mobile/android/app/src/main/java/com/ledger/live/MainActivity.kt
- android native module
In MainActivity we had a clipboard listener that triggered an infinite loop because it overrode the clipboard, making the state changes infinitely. This PR removes the code
|https://github.com/user-attachments/assets/9ed38637-2f2d-4ec4-908a-52c6c078ceda|https://github.com/user-attachments/assets/08bafffa-b47f-4d57-a37b-acfb894f1f08|
- **JIRA or GitHub link**: [LIVE-21764](https://ledgerhq.atlassian.net/browse/LIVE-21764)
--- …
=> :bug: (LLM-android) remove clipboard listener

CODEOWNERS, e2e/desktop/tests/utils/swapUtils.ts, libs/ledger-live-common/src/e2e/enum/Account.ts
=> fix: wait for drawer to load before proceeding to device interaction

.changeset/tasty-phones-heal.md, apps/ledger-live-desktop/src/main/index.ts
merge https://github.com/LedgerHQ/ledger-live/pull/12047 into release
- LLD Mac OS
See https://github.com/LedgerHQ/ledger-live/pull/12047
---
=> [RELEASE] fix(LLD): app.quit() for all OSs

.changeset/cuddly-moles-matter.md, apps/ledger-live-desktop/src/renderer/components/BoldToggle.tsx, apps/ledger-live-mobile/src/components/CollapsibleList.tsx, apps/ledger-live-mobile/src/components/ProgressBar.tsx, libs/ui/packages/native/storybook/stories/CenterView/index.tsx
- ...
Refactors function components to remove the usage of `defaultProps` 
React will drop support for `defaultProps` on function components in a future major release.
**Changes:**
* Replaced `defaultProps` with Typescript default parameters.
* Ensures forward compatibility with upcoming React versions.
No behavior changes, only implementation updates.
DEMO for MyLedger part
https://github.com/user-attachments/assets/8273a005-5786-4e2c-a7ed-1887c170398c
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-21872
--- …
=> chore: replace defaultProps with default parameters

.changeset/cold-carrots-perform.md, libs/coin-modules/coin-near/src/api/node.ts, libs/coin-modules/coin-near/src/preload.ts
- might show the wrong commission value since it failed to get it from the rcp
_E2E tests are failing due to not returning a list of the validators with a commission when a network error exists._
- [**JIRA or GitHub link**: ](https://ledgerhq.atlassian.net/browse/LIVE-21723)
--- …
=> fix: [LIVE-21723] add commission fallback / update network dependency

.changeset/cuddly-mangos-explode.md, apps/ledger-live-mobile/src/newArch/features/Market/utils/marketIdResolver.ts, apps/ledger-live-mobile/src/screens/WalletCentricAsset/AssetMarketSection.tsx, apps/ledger-live-mobile/src/screens/WalletCentricSections/MarketPrice.tsx
- ...
Adds a temporary resolver to address the issue described below 
This is a **short-term fix** and does not provide a permanent solution.
A more **robust and sustainable implementation** will be required to fully address the underlying problem with asset and Market ID mismatches.
**Issue Summary:**
The problem is caused by an incompatibility between asset IDs and the Market API identifiers.
**Details:**
* The Market API uses Meta Currency Identifiers for `currencyId`.
* The Assets pages provide the direct ERC-20 token ID (full path + address).
* Some assets, particularly on Polygon, do not have an associated Market section.
**Impact:**
This mismatch prevents the system from correctly loading prices for all tokens, causing the page to become unresponsive ⚠️
**Next Steps / …
=> fix: Stablecoin market price page unresponsive

.changeset/itchy-cooks-accept.md, libs/coin-modules/coin-tezos/src/logic/listOperations.ts, libs/ledger-live-common/src/bridge/generic-alpaca/utils.ts
- ...
Fix issue about optimistic operations for generic bridge (showing `delegate` / `undelegated` instead of `sent` waiting for the broadcast in the operation history and drawer).
- **[JIRA or GitHub link](https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/465?selectedIssue=LIVE-21829)**: 
--- …
=> fix: shows delegate/undelegate instead of sent in the drawer

e2e/desktop/tests/specs/swap.send.spec.ts
- ...
Removal of unnecesary pairs for the swap e2e
https://ledger-live.allure.green.ledgerlabs.net/allure/reports/9cab61a7-fca5-434d-8494-93a243b8c03e/#suites/e1824454c15537cd2d7656c3afe948fb/4418933330fbd9c/
---
=> Removal of unnecesary pairs for the swap e2e

.changeset/ten-apricots-listen.md, apps/ledger-live-desktop/src/renderer/drawers/OperationDetails/index.tsx, e2e/desktop/tests/page/drawer/send.drawer.ts, e2e/desktop/tests/page/speculos.page.ts, e2e/desktop/tests/specs/send.tx.spec.ts, e2e/desktop/tests/specs/subAccount.spec.ts, e2e/desktop/tests/specs/swap.send.spec.ts, e2e/desktop/tests/userdata/speculos-subAccount.json, libs/ledger-live-common/src/e2e/enum/Account.ts, libs/ledger-live-common/src/e2e/enum/AppInfos.ts, libs/ledger-live-common/src/e2e/enum/Currency.ts, libs/ledger-live-common/src/e2e/enum/Network.ts, libs/ledger-live-common/src/e2e/enum/TokenType.ts, libs/ledger-live-common/src/e2e/enum/TransactionStatus.ts, libs/ledger-live-common/src/e2e/families/sui.ts, libs/ledger-live-common/src/e2e/speculos.ts
Reverts LedgerHQ/ledger-live#11762
=> Revert "Feat/live 19322 sui tokens e2e tests and Live-18304 native sui"

.changeset/spicy-flowers-doubt.md, libs/ledger-live-common/src/deposit/useGroupedCurrenciesByProvider.hook.ts
- LLM receive
- LLM old add account
This PR excludes from receive and old add account flows the currencies that are under ff OFF. 
https://github.com/user-attachments/assets/090b8b9c-280c-47b9-9046-74d8b5396cf0
- **JIRA or GitHub link**: [LIVE-21940](https://ledgerhq.atlassian.net/browse/LIVE-21940)
--- …
=> 🐛 (common) exclude ff OFF currencies

.changeset/pretty-roses-count.md, apps/ledger-live-mobile/src/components/DeviceAction/index.tsx, apps/ledger-live-mobile/src/components/DeviceAction/rendering.tsx, apps/ledger-live-mobile/src/components/ValidateError.tsx
- ...
Redirect to my device screen if a firmware update is required for a swap
- **JIRA or GitHub link**: [LIVE-20895]
---
[LIVE-20895]: https://ledgerhq.atlassian.net/browse/LIVE-20895?atlOrigin=eyJpIjoiNWRkNTljNzYxN …
=> :bug: (swap): Fix fw update redirect error

.github/workflows/test-mobile-e2e-reusable.yml, .github/workflows/test-ui-e2e-only-desktop.yml
=> ci: update tag for the speculos image

.changeset/brown-radios-remember.md, libs/coin-modules/coin-evm/src/api/index.ts, libs/coin-modules/coin-evm/src/logic/validateIntent.test.ts, libs/coin-modules/coin-evm/src/logic/validateIntent.ts
- Alpaca only, no impact on LL
Recompute final fee value from custom fees parameters to ensure coherence.
---
=> feat(coin-evm): recompute fees from parameters

.changeset/short-waves-double.md, apps/ledger-live-desktop/src/renderer/families/canton/OnboardModal/components/ValidatorRow.tsx, apps/ledger-live-desktop/src/renderer/families/canton/OnboardModal/index.tsx, apps/ledger-live-desktop/src/renderer/families/canton/OnboardModal/steps/StepAuthorize.tsx, apps/ledger-live-desktop/src/renderer/families/canton/OnboardModal/steps/StepOnboard.tsx, apps/ledger-live-desktop/src/renderer/families/canton/OnboardModal/steps/__tests__/StepAuthorize.test.tsx, apps/ledger-live-desktop/src/renderer/families/canton/OnboardModal/steps/__tests__/StepOnboard.test.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- ...
update canton translations
---
=> feat: update canton translations

.changeset/lemon-fans-fly.md, apps/ledger-live-mobile/src/components/MarketQuickActions/MarketQuickActions.test.tsx, apps/ledger-live-mobile/src/components/MarketQuickActions/index.tsx
- market's quick actions
The market's quick actions were displayed for every coin we received from the BE even if the coin isn't supported. To fix this, we add 2 filters. The first one with the coins supported in LL and the second one with the ff from coin inte
So the rule => if the currency isn't supported by LL or if his ff is off we disable QAs. If the parent currency of a token is disable via ff we disable QAs
Also I fixed a non-needed type assertion
Inte tests have been added to cover a max of use cases
To avoid flakiness I've mocked the local supportedCurrencies and rampCatalog
https://github.com/user-attachments/assets/ec46afaf-ab4c-487a-9d07-7cd7408bd748
- **JIRA or GitHub link**: [LIVE-21955](https://ledgerhq.atlassian.net/browse/LIVE-21955)
---
- **The code aligns with the …
=> 🐛 (llm) market quick actions

.changeset/clever-donuts-guess.md, apps/ledger-live-desktop/src/renderer/index.html
Remove forgotten code we had at the time we were building LLD with Parcel. This is long gone and not used.
But this code creates unecessary resource loading at the boot of our app, you can notice it by opening with DEV_TOOLS=1 and refreshing, see the **red** attempt to load a index.ts that doesn't exist :
--- …
=> fix(lld): remove unecessary script in index.html

.changeset/brave-buttons-kiss.md, libs/ledger-live-common/src/exchange/swap/postSwapState.ts, libs/ledger-live-common/src/exchange/swap/setBroadcastTransaction.ts, libs/ledger-live-common/src/exchange/swap/types.ts, libs/ledger-live-common/src/wallet-api/Exchange/server.ts
- ...
Litte changes on how values are computed for helping swap debugs. Id to address and toAmount to FromAmount for better consistency 
---
=> fix: update swap tracking

e2e/mobile/page/trade/receive.page.ts, e2e/mobile/specs/subAccount/subAccount.ts
- ...
* Selecting asset by regex because the token that comes on the currency name testId is unpredictable
- **JIRA**: [QAA-831](https://ledgerhq.atlassian.net/browse/QAA-831)
---
[QAA-831]: …
=> fix(e2e): select token by token type to handle duplicated assets

libs/ledger-live-common/src/dada-client/entities/index.ts
- no impact
just fixing the import
---
=> chore: fix live-common import on one part dada-client

.changeset/thick-colts-attend.md, libs/coin-modules/coin-kaspa/src/logic/scanOperations.ts
- @ledgerhq/coin-kaspa
Fix issue on Kaspa scan operations.
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-21910
---
=> fix: kaspa scan operations

.changeset/polite-kids-glow.md, apps/ledger-live-desktop/src/main/index.ts
- LLD Sentry integration
prevent error "set-tags" handling to appear in the console of LLD.
---
=> fix(lld): handle sentry-set-tags

.changeset/thick-ads-drum.md, .github/workflows/test-mobile-e2e-reusable.yml, .github/workflows/test-ui-e2e-only-desktop.yml, apps/ledger-live-desktop/src/renderer/modals/Send/Body.tsx, apps/ledger-live-desktop/src/renderer/modals/Send/steps/StepRecipient.test.tsx, apps/ledger-live-desktop/src/renderer/modals/Send/steps/StepRecipient.tsx, apps/ledger-live-desktop/src/renderer/modals/Send/types.ts
- ...
Do not skip the amount step on send flow.
---
=> fix(lld): do not skip send flow amount step

.changeset/rotten-teachers-raise.md, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/ShareAnalyticsButton.tsx
- analytics row Ui if ff OFF
If lldAnalyticsOptInPrompt is deactivated, we could have a UI issue => this shouldn't happen as this ff is legally required 
|https://github.com/user-attachments/assets/3e84da5e-8ec8-4b8d-9de5-62faca10e6e6|https://github.com/user-attachments/assets/5d6e0228-f3a9-4118-bc8b-d49a546a5dc3|
- **JIRA or GitHub link**: [LIVE-21997](https://ledgerhq.atlassian.net/browse/LIVE-21997)
--- …
=> :bug: (LLD) fix analytics row ui

libs/ledger-live-common/src/dada-client/MIGRATION_GUIDE.md
Document the way to migrate from listTokens() static sync usage to a dynamic DaDa tokens loading (paginated / non paginated).
- **JIRA or GitHub link**: LIVE-21909
---
=> Document migration to move from listTokens() to DaDa

libs/coin-modules/coin-internet_computer/src/api/api.ts, libs/coin-modules/coin-internet_computer/src/types/signer.ts
=> refac: minor updates and cleanup

.changeset/big-roses-give.md, apps/ledger-live-desktop/tests/specs/services/dapp.spec.ts-mocks/1inch-live-app.ts, apps/ledger-live-desktop/tests/specs/services/services-api-mocks/getRates.mock.ts, apps/ledger-live-mobile/e2e/page/discover/discover.page.ts, apps/ledger-live-mobile/src/screens/Settings/Developer/manifests/1inch.ts, apps/ledger-live-mobile/src/utils/urls.tsx, e2e/mobile/page/discover/discover.page.ts, libs/ledger-live-common/src/exchange/providers/swap.ts, libs/ledger-live-common/src/exchange/swap/api/v5/__mocks__/fetchRates.mocks.ts, libs/ledger-live-common/src/exchange/swap/mock.ts, libs/ledger-live-common/src/platform/providers/RemoteLiveAppProvider/api/mock.json, libs/ledger-services/cal/src/partners/default.ts
- Change of swap urls for 1inch.io to 1inch.com
1inch urls update after they switched to new domain .com
- **JIRA or GitHub link**: [LIVE-21736](https://ledgerhq.atlassian.net/browse/LIVE-21736)
---
[LIVE-21736]: …
=> chore: update 1inch domain from .io to .com

.changeset/little-buttons-live.md, apps/ledger-live-desktop/src/newArch/features/AnalyticsOptInPrompt/screens/VariantA/ManagePreferences/components/Footer/index.tsx, apps/ledger-live-desktop/static/i18n/en/app.json
- ...
update label in AnalyticsPrompt
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-22013
---
=> fix: update label in AnalyticsPrompt

.changeset/neat-guests-refuse.md, apps/ledger-live-desktop/src/renderer/components/Onboarding/LangSwitcher.tsx, apps/ledger-live-desktop/src/renderer/reducers/settings.ts, apps/ledger-live-desktop/src/renderer/screens/settings/sections/General/LanguageSelect.tsx
- lang switcher / selector
Cleanup the language selector so we don't use not useless selector and we avoid type assertions (it was typed as any 🙃 )
We were mapping the language to find the corresponding locale instead of using the locales directly
- **JIRA or GitHub link**: [LIVE-22081](https://ledgerhq.atlassian.net/browse/LIVE-22081)
--- …
=> :globe_with_meridians: (lld) cleanup language switching mechanism

.changeset/tricky-lions-whisper.md, apps/ledger-live-mobile/src/screens/ReceiveFundsOptions/ReceiveFundsOptions.test.tsx, apps/ledger-live-mobile/src/screens/ReceiveFundsOptions/index.tsx
- ...
Fix the gap at the bottom of the receive modal:
Before:
After:
N/A
---
=> fix: receive modal gap

.changeset/modern-pandas-rhyme.md, libs/coin-framework/src/api/types.ts, libs/coin-modules/coin-evm/src/api/index.ts, libs/coin-modules/coin-evm/src/logic.ts, libs/coin-modules/coin-evm/src/logic/common.ts, libs/coin-modules/coin-evm/src/logic/craftTransaction.ts, libs/coin-modules/coin-evm/src/logic/estimateFees.test.ts, libs/coin-modules/coin-evm/src/logic/estimateFees.ts, libs/coin-modules/coin-evm/src/logic/validateIntent.test.ts, libs/coin-modules/coin-evm/src/logic/validateIntent.ts, libs/coin-modules/coin-evm/src/network/node/ledger.ts, libs/coin-modules/coin-evm/src/network/node/rpc.common.ts, libs/coin-modules/coin-evm/src/network/node/types.ts, libs/coin-modules/coin-evm/src/types/transaction.ts, libs/ledger-live-common/src/bridge/generic-alpaca/getTransactionStatus.ts, libs/ledger-live-common/src/bridge/generic-alpaca/utils.ts
- Ensure non regression on additional fee calculation for EVM L2
- support layer 2 additional fees
- pass custom gas options in estimations
- **JIRA or GitHub link**: https://ledgerhq.atlassian.net/browse/LIVE-21957
--- …
=> feat(coin-evm): support layer 2 fees and custom gas options

.changeset/nice-frogs-end.md, libs/coin-modules/coin-canton/src/bridge/onboard.test.ts, libs/coin-modules/coin-canton/src/bridge/onboard.ts, libs/coin-modules/coin-canton/src/bridge/sync.ts, libs/coin-modules/coin-canton/src/network/gateway.ts
- coin-canton onboard and sync
Use api endpoint to get the current pre-approval status for canton account
- [LIVE-22132](https://ledgerhq.atlassian.net/browse/LIVE-22132)
---
[LIVE-22132]: …
=> feat: add canton account pre-approval api
